SAMRAI: SAMRAI::math::HierarchyFaceDataOpsInteger Class Reference
SAMRAI::math::HierarchyFaceDataOpsInteger Class Reference
#include <source/SAMRAI/math/HierarchyFaceDataOpsInteger.h>
Public Member Functions
HierarchyFaceDataOpsInteger (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int coarsest_level=-1, const int finest_level=-1)
virtual ~HierarchyFaceDataOpsInteger ()
void setPatchHierarchy (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy)
void resetLevels (const int coarsest_level, const int finest_level)
const boost::shared_ptr
< hier::PatchHierarchy > getPatchHierarchy () const
int numberOfEntries (const int data_id, const bool interior_only=true) const
void copyData (const int dst_id, const int src_id, const bool interior_only=true) const
void swapData (const int data1_id, const int data2_id) const
void printData (const int data_id, std::ostream &s, const bool interior_only=true) const
void setToScalar (const int data_id, const int &alpha, const bool interior_only=true) const
void scale (const int dst_id, const int &alpha, const int src_id, const bool interior_only=true) const
void addScalar (const int dst_id, const int src_id, const int &alpha, const bool interior_only=true) const
void add (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void subtract (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void multiply (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void divide (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void reciprocal (const int dst_id, const int src_id, const bool interior_only=true) const
void linearSum (const int dst_id, const int &alpha, const int src1_id, const int &beta, const int src2_id, const bool interior_only=true) const
void axpy (const int dst_id, const int &alpha, const int src1_id, const int src2_id, const bool interior_only=true) const
void axmy (const int dst_id, const int &alpha, const int src1_id, const int src2_id, const bool interior_only=true) const
void abs (const int dst_id, const int src_id, const bool interior_only=true) const
int min (const int data_id, const bool interior_only=true) const
int max (const int data_id, const bool interior_only=true) const
void setRandomValues (const int data_id, const int &width, const int &low, const bool interior_only=true) const
Detailed Description
Class HierarchyFaceDataOpsInteger provides a collection of operations that manipulate integer face-centered patch data components over multiple levels in an AMR hierarchy. It is derived from the abstract base class HierarchyDataOpsInteger which defines the interface to similar operations for face-centered, face-centered, face-centered patch data objects where the data is of type integer. The operations include basic arithmetic and some ordering operations. On each patch, the operations are performed by the PatchFaceDataOpsInteger data member.
The patch hierarchy and set of levels within that hierarcy over which the operations will be performed are set in the constructor. However, note that the constructor accepts default arguments for the coarsest and finest level numbers. If the level numbers are not specified when calling the constructor the levels which exist in the hierarchy will be assumed in all operations. The hierarchy and levels may be changed at any time using the proper member functions.
Note that, when it makes sense, an operation accept a boolean argument which indicates whether the operation should be performed on all of the data or just those data elements corresponding to the patch interiors. If no boolean argument is provided, the default behavior is to treat only the patch interiors. Also, a similar set of operations for real (double and float) and complex face-centered data is provided in the classes HierarchyFaceDataOpsReal and HierarchyFaceDataOpsComplex, respectively.
See also:
math::PatchFaceDataOpsInteger
Constructor & Destructor Documentation
SAMRAI::math::HierarchyFaceDataOpsInteger::HierarchyFaceDataOpsInteger (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int coarsest_level = -1, const int finest_level = -1) [explicit]
The constructor for the HierarchyFaceDataOpsInteger class sets the default patch hierarchy and coarsest and finest patch levels in that hierarchy over which operations will be performed. The hierarchy and operations may be reset using the member fuctions setPatchHierarchy() and resetLevels() below. If no level number arguments are given here, the levels over which the operations will be performed are those already existing in the hierarchy. If the hierarchy level configuration changes, the operations must be explicitly reset by calling the resetLevels() function.
Precondition:
hierarchy
References resetLevels(), and TBOX_ASSERT.
SAMRAI::math::HierarchyFaceDataOpsInteger::~HierarchyFaceDataOpsInteger () [virtual]
Virtual destructor for the HierarchyFaceDataOpsInteger class.
Member Function Documentation
void SAMRAI::math::HierarchyFaceDataOpsInteger::setPatchHierarchy (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy) [virtual]
Reset patch hierarchy over which operations occur.
Precondition:
hierarchy
Implements SAMRAI::math::HierarchyDataOpsInteger.
References TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::resetLevels (const int coarsest_level, const int finest_level) [virtual]
Reset range of patch levels over which operations occur.
Precondition:
getPatchHierarchy()
(coarsest_level >= 0) && (finest_level >= coarsest_level) && (finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), TBOX_ASSERT, and SAMRAI::pdat::FaceGeometry::toFaceBox().
Referenced by HierarchyFaceDataOpsInteger().
const boost::shared_ptr< hier::PatchHierarchy > SAMRAI::math::HierarchyFaceDataOpsInteger::getPatchHierarchy () const [virtual]
Return const pointer to patch hierarchy associated with operations.
Implements SAMRAI::math::HierarchyDataOpsInteger.
int SAMRAI::math::HierarchyFaceDataOpsInteger::numberOfEntries (const int data_id, const bool interior_only = true) const [virtual]
Return the total number of data values for the component on the set of hierarchy levels. If the boolean argument is true, the number of elements will be summed over patch interiors in a unique way which avoids multiple counting of redundant values (recall the definition of node points on a patch interior). If the boolean argument is false, all elements will be counted (including ghost values) over all patches.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, MPI_INT, MPI_SUM, SAMRAI::math::PatchFaceDataOpsInteger::numberOfEntries(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::copyData (const int dst_id, const int src_id, const bool interior_only = true) const [virtual]
Copy source data to destination data.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataOpsInteger::copyData(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::swapData (const int data1_id, const int data2_id) const [virtual]
Swap data pointers (i.e., storage) between two data components.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataOpsInteger::swapData(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::printData (const int data_id, std::ostream & s, const bool interior_only = true) const [virtual]
Print data over multiple levels to specified output stream.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataOpsInteger::printData(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::setToScalar (const int data_id, const int & alpha, const bool interior_only = true) const [virtual]
Set data component to given scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataOpsInteger::setToScalar(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::scale (const int dst_id, const int & alpha, const int src_id, const bool interior_only = true) const [virtual]
Set destination to source multiplied by given scalar, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::scale(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::addScalar (const int dst_id, const int src_id, const int & alpha, const bool interior_only = true) const [virtual]
Add scalar to each entry in source data and set destination to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References SAMRAI::math::PatchFaceDataBasicOps< TYPE >::addScalar(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::add (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set destination to sum of two source components, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References SAMRAI::math::PatchFaceDataBasicOps< TYPE >::add(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::subtract (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Subtract second source component from first source component pointwise and set destination data component to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::subtract(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::multiply (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set destination component to product of two source components, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::multiply(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::divide (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Divide first data component by second source component pointwise and set destination data component to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::divide(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::reciprocal (const int dst_id, const int src_id, const bool interior_only = true) const [virtual]
Set each entry of destination component to reciprocal of corresponding source data component entry.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::reciprocal(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::linearSum (const int dst_id, const int & alpha, const int src1_id, const int & beta, const int src2_id, const bool interior_only = true) const [virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here are scalar values.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::linearSum(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::axpy (const int dst_id, const int & alpha, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here is a scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References SAMRAI::math::PatchFaceDataBasicOps< TYPE >::axpy(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::axmy (const int dst_id, const int & alpha, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here is a scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References SAMRAI::math::PatchFaceDataBasicOps< TYPE >::axmy(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::abs (const int dst_id, const int src_id, const bool interior_only = true) const [virtual]
Set destination data to absolute value of source data, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References SAMRAI::math::PatchFaceDataOpsInteger::abs(), BOOST_CAST, and TBOX_ASSERT.
int SAMRAI::math::HierarchyFaceDataOpsInteger::min (const int data_id, const bool interior_only = true) const [virtual]
Return minimum data value over all patches in the collection of levels.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::min(), MPI_INT, MPI_MIN, and TBOX_ASSERT.
int SAMRAI::math::HierarchyFaceDataOpsInteger::max (const int data_id, const bool interior_only = true) const [virtual]
Return maximum data value over all patches in the collection of levels.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::max(), MPI_INT, MPI_MAX, and TBOX_ASSERT.
void SAMRAI::math::HierarchyFaceDataOpsInteger::setRandomValues (const int data_id, const int & width, const int & low, const bool interior_only = true) const [virtual]
Set data entries to random values. See the operations in the array data operation classes for details on the generation of the random values.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsInteger.
References BOOST_CAST, SAMRAI::math::PatchFaceDataBasicOps< TYPE >::setRandomValues(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/math/HierarchyFaceDataOpsInteger.h
source/SAMRAI/math/HierarchyFaceDataOpsInteger.C