SAMRAI: SAMRAI::hier::PatchDescriptor Class Reference
SAMRAI::hier::PatchDescriptor Class Reference
Class PatchDescriptor maintains a collection of patch data factories and associated names that describes how patch data entries are constructed on each patch in an AMR hierarchy. The factory mechanism is used to create new instances of concrete patch data objects without knowing their actual types. See the Design Patterns book by Gamma {et al.} for more details about the Abstract Factory pattern. Generally, a PatchDescriptor object is intended to be shared among all patches (which are distributed across processors) so that they store patch data objects in the same way.
#include <source/SAMRAI/hier/PatchDescriptor.h>
Public Member Functions
PatchDescriptor ()
~PatchDescriptor ()
int definePatchDataComponent (const std::string &name, const boost::shared_ptr< PatchDataFactory > &factory)
void removePatchDataComponent (int id)
boost::shared_ptr
< PatchDataFactory > getPatchDataFactory (int id) const
boost::shared_ptr
< PatchDataFactory > getPatchDataFactory (const std::string &name) const
int getMaxNumberRegisteredComponents () const
int mapNameToIndex (const std::string &name) const
const std::string & mapIndexToName (const int id) const
IntVector getMaxGhostWidth (const tbox::Dimension &dim) const
void setMinGhostWidth (const IntVector &min_value)
Set a minimum value on the value returned by getMaxGhostWidth().
tbox::Dimension getPatchDataDim (int data_id) const
Return the Dimension of the data for the given data_id.
void printClassData (std::ostream &stream=tbox::plog) const
Detailed Description
Class PatchDescriptor maintains a collection of patch data factories and associated names that describes how patch data entries are constructed on each patch in an AMR hierarchy. The factory mechanism is used to create new instances of concrete patch data objects without knowing their actual types. See the Design Patterns book by Gamma {et al.} for more details about the Abstract Factory pattern. Generally, a PatchDescriptor object is intended to be shared among all patches (which are distributed across processors) so that they store patch data objects in the same way.
Patch data factory objects (and associated names) are explicitly added to the PatchDescriptor using the definePatchDataComponent() member function. This function returns an integer index that can be used to identify the corresponding patch data on a a patch. Factories can be removed from the PatchDescriptor using the removePatchDataComponent() member function, which returns the integer index associated with the removed factory to a "free list" so that it can be used again. At any time, the valid range of indices is >= 0 and < getMaxNumberRegisteredComponents().
Note that the SAMRAIManager utility establishes a maximum number of patch data object that may live on a Patch object which, for consistency, must be the same as the number of patch data factories a PatchDescriptor will hold. See the documentation of the SAMRAIManager utility for information about changing this maximum value.
See also:
tbox::SAMRAIManager
PatchDataFactory
PatchDataData
Patch
Constructor & Destructor Documentation
SAMRAI::hier::PatchDescriptor::PatchDescriptor ()
Constructor for a patch descriptor initializes the descriptor to hold zero patch data factory entries.
References SAMRAI::tbox::SAMRAIManager::getMaxNumberPatchDataEntries(), and SAMRAI::hier::IntVector::getZero().
SAMRAI::hier::PatchDescriptor::~PatchDescriptor ()
The destructor for a patch descriptor deallocates the internal data structures.
Member Function Documentation
int SAMRAI::hier::PatchDescriptor::definePatchDataComponent (const std::string & name, const boost::shared_ptr< PatchDataFactory > & factory)
Add a new patch data factory and name std::string identifier to the patch descriptor. The factory will be given the specified name which must be unique for the mapNameToIndex() function to execute as expected. However, there is no internal checking done to ensure that names are unique.
Returns:
int index assigned to given patch data factory in patch descriptor.
Parameters:
name std::string name to be associated in name list with given factory
factory pointer to factory to add to patch descriptor
Precondition:
!name.empty()
factory
!d_free_indices.empty()
References TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::PatchDescriptor::removePatchDataComponent (int id)
Deallocate the patch data factory in the patch descriptor identified by the given index. The index may be assigned to another factory in the future. However, index will be invalid as a patch data index until it is re-allocated by the definePatchDataComponent() member function. An invalid id value passed to this function is silently ignored.
Parameters:
id int index of factory to remove from patch descriptor.
boost::shared_ptr<PatchDataFactory> SAMRAI::hier::PatchDescriptor::getPatchDataFactory (int id) const [inline]
Retrieve a patch data factory by integer index identifier. The identifier is the one previously returned by definePatchDataComponent(). Note that the factory pointer will be null if the index is is not currently assigned.
Returns:
pointer to patch data factory assigned to given index.
Parameters:
id int index of factory to return, which must be >= 0 and < the return value of getMaxNumberRegisteredComponents();
Precondition:
(id >= 0) && (id < getMaxNumberRegisteredComponents())
References TBOX_ASSERT.
boost::shared_ptr< PatchDataFactory > SAMRAI::hier::PatchDescriptor::getPatchDataFactory (const std::string & name) const
Retrieve a patch data factory by name std::string identifier. Recall that uniqueness of names is not strictly enforced. So if more than one factory matches the given name, then only one of them is returned. If no matching factory is found, then a null pointer is returned.
Returns:
pointer to patch data factory assigned to given name.
Parameters:
name std::string name of factory.
References mapNameToIndex().
int SAMRAI::hier::PatchDescriptor::getMaxNumberRegisteredComponents () const [inline]
Get the maximum number of components currently known to the patch descriptor. That is, this number indicates the largest number of components that have been registered with the descriptor via the definePatchDataComponent() function, which is equal to the largest known patch data component index + 1. Note that the total number of registered components is reduced by calls to removePatchDataComponent(), but the max number remains the same when components are removed. In that case, the corresponding indices are placed on a list of "free" values to be re-used in subsequent calls to definePatchDataComponent().
Returns:
largest index assigned to this point.
int SAMRAI::hier::PatchDescriptor::mapNameToIndex (const std::string & name) const
Lookup a factory by std::string name and return its integer index identifier. Note that more than one factory may have the same name. In this case, the identifier of one of the factories is chosen. If no matching factory is found, then an invalid negative index is returned.
Referenced by getPatchDataFactory().
const std::string& SAMRAI::hier::PatchDescriptor::mapIndexToName (const int id) const [inline]
Lookup a factory by identifier and return its name.
Precondition:
(id >= 0) && (id < getMaxNumberRegisteredComponents())
References TBOX_ASSERT.
IntVector SAMRAI::hier::PatchDescriptor::getMaxGhostWidth (const tbox::Dimension & dim) const
Return the IntVector indicating the maximum ghost cell width of all registered patch data components for the provided dimension.
If no components have been registered returns the value set by setMinGhostWidth(), which is zero by default.
Parameters:
dim Dimension
References SAMRAI::tbox::Dimension::getValue(), and SAMRAI::hier::IntVector::max().
void SAMRAI::hier::PatchDescriptor::setMinGhostWidth (const IntVector & min_value) [inline]
Set a minimum value on the value returned by getMaxGhostWidth().
This method allows users to specify a mininum value returned by getMaxGhostWidth(). The default minimum is zero. This value can be used as a substitute for data that is not yet registered with the PatchDescriptor and therefore cannot be reflected in getMaxGhostWidth().
The dimension associated with the set value is taken to be min_value.getDim().
References SAMRAI::hier::IntVector::getDim(), and SAMRAI::tbox::Dimension::getValue().
tbox::Dimension SAMRAI::hier::PatchDescriptor::getPatchDataDim (int data_id) const
Return the Dimension of the data for the given data_id.
Parameters:
[in] data_id
void SAMRAI::hier::PatchDescriptor::printClassData (std::ostream & stream = tbox::plog) const
Print patch descriptor data to given output stream (plog by default).
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchDescriptor.h
source/SAMRAI/hier/PatchDescriptor.C