SAMRAI: SAMRAI::math::HierarchyNodeDataOpsComplex Class Reference
SAMRAI::math::HierarchyNodeDataOpsComplex Class Reference
#include <source/SAMRAI/math/HierarchyNodeDataOpsComplex.h>
Public Member Functions
HierarchyNodeDataOpsComplex (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int coarsest_level=-1, const int finest_level=-1)
virtual ~HierarchyNodeDataOpsComplex ()
void setPatchHierarchy (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy)
void resetLevels (const int coarsest_level, const int finest_level)
const boost::shared_ptr
< hier::PatchHierarchy > getPatchHierarchy () const
void copyData (const int dst_id, const int src_id, const bool interior_only=true) const
void swapData (const int data1_id, const int data2_id) const
void printData (const int data_id, std::ostream &s, const bool interior_only=true) const
void setToScalar (const int data_id, const dcomplex &alpha, const bool interior_only=true) const
void scale (const int dst_id, const dcomplex &alpha, const int src_id, const bool interior_only=true) const
void addScalar (const int dst_id, const int src_id, const dcomplex &alpha, const bool interior_only=true) const
void add (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void subtract (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void multiply (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void divide (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void reciprocal (const int dst_id, const int src_id, const bool interior_only=true) const
void linearSum (const int dst_id, const dcomplex &alpha, const int src1_id, const dcomplex &beta, const int src2_id, const bool interior_only=true) const
void axpy (const int dst_id, const dcomplex &alpha, const int src1_id, const int src2_id, const bool interior_only=true) const
void axmy (const int dst_id, const dcomplex &alpha, const int src1_id, const int src2_id, const bool interior_only=true) const
void abs (const int dst_id, const int src_id, const bool interior_only=true) const
void setRandomValues (const int data_id, const dcomplex &width, const dcomplex &low, const bool interior_only=true) const
size_t numberOfEntries (const int data_id, const bool interior_only=true) const
double sumControlVolumes (const int data_id, const int vol_id) const
double L1Norm (const int data_id, const int vol_id=-1) const
double L2Norm (const int data_id, const int vol_id=-1) const
double weightedL2Norm (const int data_id, const int weight_id, const int vol_id=-1) const
double RMSNorm (const int data_id, const int vol_id=-1) const
double weightedRMSNorm (const int data_id, const int weight_id, const int vol_id=-1) const
double maxNorm (const int data_id, const int vol_id=-1) const
dcomplex dot (const int data1_id, const int data2_id, const int vol_id=-1) const
dcomplex integral (const int data_id, const int vol_id) const
Detailed Description
Class HierarchyNodeDataOpsComplex provides a collection of operations that manipulate complex node-centered patch data components over multiple levels in an AMR hierarchy. It is derived from the abstract base class HierarchyDataOpsComplex which defines the interface to similar operations for node-centered, face-centered, node-centered patch data objects where the data is complex. The operations include basic arithmetic and norms. On each patch, the operations are performed by the PatchNodeDataOpsComplex data member.
The patch hierarchy and set of levels within that hierarcy over which the operations will be performed are set in the constructor. However, note that the constructor accepts default arguments for the coarsest and finest level numbers. If the level numbers are not specified when calling the constructor the levels which exist in the hierarchy will be assumed in all operations. The hierarchy and levels may be changed at any time using the proper member functions.
Note that, when it makes sense, an operation accept a boolean argument which indicates whether the operation should be performed on all of the data or just those data elements corresponding to the patch interiors. If no boolean argument is provided, the default behavior is to treat only the patch interiors. Also, a similar set of operations for real (double and float) and integer node-centered data is provided in the classes HierarchyNodeDataOpsReal and HierarchyNodeDataOpsInteger, respectively.
See also:
PatchNodeDataOpsComplex
Constructor & Destructor Documentation
SAMRAI::math::HierarchyNodeDataOpsComplex::HierarchyNodeDataOpsComplex (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int coarsest_level = -1, const int finest_level = -1) [explicit]
The constructor for the HierarchyNodeDataOpsComplex class sets the default patch hierarchy and coarsest and finest patch levels in that hierarchy over which operations will be performed. The hierarchy and operations may be reset using the member fuctions setPatchHierarchy() and resetLevels() below. If no level number arguments are given here, the levels over which the operations will be performed are those already existing in the hierarchy. If the hierarchy level configuration changes, the operations must be explicitly reset by calling the resetLevels() function.
Precondition:
hierarchy
References resetLevels(), and TBOX_ASSERT.
SAMRAI::math::HierarchyNodeDataOpsComplex::~HierarchyNodeDataOpsComplex () [virtual]
Virtual destructor for the HierarchyNodeDataOpsComplex class.
Member Function Documentation
void SAMRAI::math::HierarchyNodeDataOpsComplex::setPatchHierarchy (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy) [virtual]
Reset patch hierarchy over which operations occur.
Precondition:
hierarchy
Implements SAMRAI::math::HierarchyDataOpsComplex.
References TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::resetLevels (const int coarsest_level, const int finest_level) [virtual]
Reset range of patch levels over which operations occur.
Precondition:
getPatchHierarchy()
(coarsest_level >= 0) && (finest_level >= coarsest_level) && (finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), TBOX_ASSERT, and SAMRAI::pdat::NodeGeometry::toNodeBox().
Referenced by HierarchyNodeDataOpsComplex().
const boost::shared_ptr< hier::PatchHierarchy > SAMRAI::math::HierarchyNodeDataOpsComplex::getPatchHierarchy () const [virtual]
Return const pointer to patch hierarchy associated with operations.
Implements SAMRAI::math::HierarchyDataOpsComplex.
void SAMRAI::math::HierarchyNodeDataOpsComplex::copyData (const int dst_id, const int src_id, const bool interior_only = true) const [virtual]
Copy source data to destination data.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataOpsComplex::copyData(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::swapData (const int data1_id, const int data2_id) const [virtual]
Swap data pointers (i.e., storage) between two data components.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataOpsComplex::swapData(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::printData (const int data_id, std::ostream & s, const bool interior_only = true) const [virtual]
Print data over multiple levels to specified output stream.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataOpsComplex::printData(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::setToScalar (const int data_id, const dcomplex & alpha, const bool interior_only = true) const [virtual]
Set data component to given scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataOpsComplex::setToScalar(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::scale (const int dst_id, const dcomplex & alpha, const int src_id, const bool interior_only = true) const [virtual]
Set destination to source multiplied by given scalar, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataBasicOps< TYPE >::scale(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::addScalar (const int dst_id, const int src_id, const dcomplex & alpha, const bool interior_only = true) const [virtual]
Add scalar to each entry in source data and set destination to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References SAMRAI::math::PatchNodeDataBasicOps< TYPE >::addScalar(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::add (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set destination to sum of two source components, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References SAMRAI::math::PatchNodeDataBasicOps< TYPE >::add(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::subtract (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Subtract second source component from first source component pointwise and set destination data component to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataBasicOps< TYPE >::subtract(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::multiply (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set destination component to product of two source components, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataBasicOps< TYPE >::multiply(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::divide (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Divide first data component by second source component pointwise and set destination data component to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataBasicOps< TYPE >::divide(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::reciprocal (const int dst_id, const int src_id, const bool interior_only = true) const [virtual]
Set each entry of destination component to reciprocal of corresponding source data component entry.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataBasicOps< TYPE >::reciprocal(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::linearSum (const int dst_id, const dcomplex & alpha, const int src1_id, const dcomplex & beta, const int src2_id, const bool interior_only = true) const [virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here are scalar values.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataBasicOps< TYPE >::linearSum(), and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::axpy (const int dst_id, const dcomplex & alpha, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here is a scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References SAMRAI::math::PatchNodeDataBasicOps< TYPE >::axpy(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::axmy (const int dst_id, const dcomplex & alpha, const int src1_id, const int src2_id, const bool interior_only = true) const [virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here is a scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References SAMRAI::math::PatchNodeDataBasicOps< TYPE >::axmy(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::abs (const int dst_id, const int src_id, const bool interior_only = true) const [virtual]
Set destination data to absolute value of source data, pointwise. Note that the source data must be dcomplex and the destination must be double.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References SAMRAI::math::PatchNodeDataNormOpsComplex::abs(), BOOST_CAST, and TBOX_ASSERT.
void SAMRAI::math::HierarchyNodeDataOpsComplex::setRandomValues (const int data_id, const dcomplex & width, const dcomplex & low, const bool interior_only = true) const [virtual]
Set data entries to random values. See the operations in the array data operation classes for details on the generation of the random values.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataBasicOps< TYPE >::setRandomValues(), and TBOX_ASSERT.
size_t SAMRAI::math::HierarchyNodeDataOpsComplex::numberOfEntries (const int data_id, const bool interior_only = true) const [virtual]
Return the total number of data values for the component on the set of hierarchy levels. If the boolean argument is true, the number of elements will be summed over patch interiors in a unique way which avoids multiple counting of redundant values (recall the definition of node points on a patch interior). If the boolean argument is false, all elements will be counted (including ghost values) over all patches.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, MPI_SUM, SAMRAI::math::PatchNodeDataNormOpsComplex::numberOfEntries(), and TBOX_ASSERT.
Referenced by RMSNorm(), and weightedRMSNorm().
double SAMRAI::math::HierarchyNodeDataOpsComplex::sumControlVolumes (const int data_id, const int vol_id) const [virtual]
Return sum of the control volumes associated with the data component. Note that if the control volumes are set properly, this is equivalent to integrating a data component containing all ones over the collection of hierarchy levels.
Precondition:
vol_id >= 0
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, MPI_DOUBLE, MPI_SUM, SAMRAI::math::PatchNodeDataNormOpsComplex::sumControlVolumes(), and TBOX_ASSERT.
Referenced by RMSNorm(), and weightedRMSNorm().
double SAMRAI::math::HierarchyNodeDataOpsComplex::L1Norm (const int data_id, const int vol_id = -1) const [virtual]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is undefined (vol_id < 0), the return value is .
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataNormOpsComplex::L1Norm(), MPI_DOUBLE, MPI_SUM, and TBOX_ASSERT.
double SAMRAI::math::HierarchyNodeDataOpsComplex::L2Norm (const int data_id, const int vol_id = -1) const [virtual]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is undefined (vol_id < 0), the return value is .
Implements SAMRAI::math::HierarchyDataOpsComplex.
References dot().
Referenced by RMSNorm().
double SAMRAI::math::HierarchyNodeDataOpsComplex::weightedL2Norm (const int data_id, const int weight_id, const int vol_id = -1) const [virtual]
Return discrete weighted -norm of the data using the control volume to weight the contribution of the data and weight entries to the sum. That is, the return value is the sum . If the control volume is undefined (vol_id < 0), the return value is .
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, MPI_DOUBLE, MPI_SUM, TBOX_ASSERT, and SAMRAI::math::PatchNodeDataNormOpsComplex::weightedL2Norm().
Referenced by weightedRMSNorm().
double SAMRAI::math::HierarchyNodeDataOpsComplex::RMSNorm (const int data_id, const int vol_id = -1) const [virtual]
Return discrete root mean squared norm of the data. If the control volume is specified (vol_id >= 0), the return value is the -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the -norm divided by the square root of the number of data entries.
Implements SAMRAI::math::HierarchyDataOpsComplex.
References L2Norm(), numberOfEntries(), and sumControlVolumes().
double SAMRAI::math::HierarchyNodeDataOpsComplex::weightedRMSNorm (const int data_id, const int weight_id, const int vol_id = -1) const [virtual]
Return discrete weighted root mean squared norm of the data. If the control volume is specified (vol_id >= 0), the return value is the weighted -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the weighted -norm divided by the square root of the number of data entries.
Implements SAMRAI::math::HierarchyDataOpsComplex.
References numberOfEntries(), sumControlVolumes(), and weightedL2Norm().
double SAMRAI::math::HierarchyNodeDataOpsComplex::maxNorm (const int data_id, const int vol_id = -1) const [virtual]
Return the -norm of the data using the control volume to weight the contribution of each data entry to the maximum. That is, the return value is , where the max is over the data elements where . If the control volume is undefined (vol_id < 0), it is ignored during the computation of the maximum.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataNormOpsComplex::maxNorm(), MPI_DOUBLE, MPI_MAX, and TBOX_ASSERT.
dcomplex SAMRAI::math::HierarchyNodeDataOpsComplex::dot (const int data1_id, const int data2_id, const int vol_id = -1) const [virtual]
Return the dot product of the two data arrays using the control volume to weight the contribution of each product to the sum. That is, the return value is the sum . If the control volume is undefined (vol_id < 0), it is ignored during the summation.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsComplex.
References BOOST_CAST, SAMRAI::math::PatchNodeDataNormOpsComplex::dot(), MPI_DOUBLE, MPI_SUM, and TBOX_ASSERT.
Referenced by L2Norm().
dcomplex SAMRAI::math::HierarchyNodeDataOpsComplex::integral (const int data_id, const int vol_id) const
Return the integral of the function represented by the data array. The return value is the sum .
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
References BOOST_CAST, SAMRAI::math::PatchNodeDataNormOpsComplex::integral(), MPI_DOUBLE, MPI_SUM, and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/math/HierarchyNodeDataOpsComplex.h
source/SAMRAI/math/HierarchyNodeDataOpsComplex.C