SAMRAI: SAMRAI::hier::BlockId Class Reference
SAMRAI::hier::BlockId Class Reference
Generic identifier for identifying the block id.
#include <source/SAMRAI/hier/BlockId.h>
Public Types
typedef unsigned int block_t
Primitive type for the number associated with a block.
Public Member Functions
BlockId ()
Default constructor sets the value to invalid.
BlockId (const BlockId &other)
Copy constructor.
BlockId (const unsigned int &value)
Construct from an unsigned int.
BlockId (const int &value)
Construct from a signed int.
~BlockId ()
Default constructor.
BlockId & operator= (const BlockId &rhs)
Assignment operator.
void setId (const int &rhs)
Set to an int value.
void setId (const unsigned int &rhs)
bool isValid () const
Whether the value is valid.
const block_t & getBlockValue () const
Access the numerical value.
Comparison with another BlockId.
bool operator== (const BlockId &rhs) const
Equality operator.
bool operator!= (const BlockId &rhs) const
Inequality operator.
bool operator< (const BlockId &rhs) const
Less-than operator.
bool operator> (const BlockId &rhs) const
Greater-than operator.
bool operator<= (const BlockId &rhs) const
Less-than-or-equal-to operator.
bool operator>= (const BlockId &rhs) const
Greater-thanor-equal-to operator.
Comparison with an integer.
bool operator== (const block_t &rhs) const
Equality operator.
bool operator!= (const block_t &rhs) const
Inequality operator.
bool operator< (const block_t &rhs) const
Less-than operator.
bool operator> (const block_t &rhs) const
Greater-than operator.
bool operator<= (const block_t &rhs) const
Less-than-or-equal-to operator.
bool operator>= (const block_t &rhs) const
Greater-thanor-equal-to operator.
Static Public Member Functions
static const BlockId & zero ()
Get the BlockId with a numerical value of zero.
static const BlockId & invalidId ()
Get the designated invalid value for this class.
Friends
std::ostream & operator<< (std::ostream &co, const BlockId &r)
Format and insert object into a stream.
Detailed Description
Generic identifier for identifying the block id.
Comparison operators are provided to define sorted ordering of objects.
Member Typedef Documentation
typedef unsigned int SAMRAI::hier::BlockId::block_t
Primitive type for the number associated with a block.
Constructor & Destructor Documentation
SAMRAI::hier::BlockId::BlockId ()
Default constructor sets the value to invalid.
SAMRAI::hier::BlockId::BlockId (const BlockId & other)
Copy constructor.
SAMRAI::hier::BlockId::BlockId (const unsigned int & value) [explicit]
Construct from an unsigned int.
This method is explicit to prevent automatic conversion.
SAMRAI::hier::BlockId::BlockId (const int & value) [explicit]
Construct from a signed int.
This method is explicit to prevent automatic conversion.
Precondition:
value >= 0
References TBOX_ASSERT.
SAMRAI::hier::BlockId::~BlockId ()
Default constructor.
Member Function Documentation
BlockId& SAMRAI::hier::BlockId::operator= (const BlockId & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs
Returns:
*this
void SAMRAI::hier::BlockId::setId (const int & rhs) [inline]
Set to an int value.
Parameters:
[in] rhs
References TBOX_ASSERT.
Referenced by SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::ConstNeighborIterator(), SAMRAI::hier::BaseGridGeometry::NeighborIterator::NeighborIterator(), SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator=(), and SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator=().
void SAMRAI::hier::BlockId::setId (const unsigned int & rhs) [inline]
bool SAMRAI::hier::BlockId::isValid () const [inline]
Whether the value is valid.
Referenced by SAMRAI::hier::BoxUtilities::chopBoxes().
const block_t& SAMRAI::hier::BlockId::getBlockValue () const [inline]
Access the numerical value.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BaseGridGeometry::areNeighbors(), SAMRAI::hier::BaseGridGeometry::areSingularityNeighbors(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::Box::coarsen(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::ConstNeighborIterator(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::IntVector::getBlockVector(), SAMRAI::hier::CoarseFineBoundary::getBoundaries(), SAMRAI::hier::BaseGridGeometry::getDomainIsSingleBox(), SAMRAI::hier::BaseGridGeometry::getDomainOutsideBlock(), SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::BoxLevel::getGlobalBoundingBox(), SAMRAI::hier::BoxLevel::getGlobalMaxBoxSize(), SAMRAI::hier::BoxLevel::getGlobalMinBoxSize(), SAMRAI::hier::BoxLevel::getLocalBoundingBox(), SAMRAI::hier::BoxLevel::getLocalMaxBoxSize(), SAMRAI::hier::BoxLevel::getLocalMinBoxSize(), SAMRAI::hier::BaseGridGeometry::getNumberOfNeighbors(), SAMRAI::hier::BaseGridGeometry::getOffset(), SAMRAI::hier::PatchLevel::getPhysicalDomain(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::hier::BaseGridGeometry::getRotationIdentifier(), SAMRAI::hier::BaseGridGeometry::getSingularityBoxContainer(), SAMRAI::hier::BaseGridGeometry::getTransformedBlock(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BaseGridGeometry::NeighborIterator::NeighborIterator(), SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator++(), SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator++(), SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator=(), SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator=(), SAMRAI::hier::PatchGeometry::PatchGeometry(), SAMRAI::hier::Box::putToIntBuffer(), SAMRAI::hier::Box::putToMessageStream(), SAMRAI::hier::Patch::putToRestart(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), SAMRAI::hier::BaseGridGeometry::putToRestart(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::hier::Box::refine(), SAMRAI::hier::BaseGridGeometry::registerNeighbors(), SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch(), SAMRAI::hier::BaseGridGeometry::transformBox(), and SAMRAI::hier::BaseGridGeometry::transformBoxContainer().
static const BlockId& SAMRAI::hier::BlockId::zero () [inline, static]
Get the BlockId with a numerical value of zero.
static const BlockId& SAMRAI::hier::BlockId::invalidId () [inline, static]
Get the designated invalid value for this class.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::Box::Box(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::Transformation::inverseTransform(), and SAMRAI::hier::Transformation::transform().
bool SAMRAI::hier::BlockId::operator== (const BlockId & rhs) const [inline]
Equality operator.
All comparison operators compare the numerical value.
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator!= (const BlockId & rhs) const [inline]
Inequality operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator< (const BlockId & rhs) const [inline]
Less-than operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator> (const BlockId & rhs) const [inline]
Greater-than operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator<= (const BlockId & rhs) const [inline]
Less-than-or-equal-to operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator>= (const BlockId & rhs) const [inline]
Greater-thanor-equal-to operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator== (const block_t & rhs) const [inline]
Equality operator.
All comparison operators compare the numerical value.
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator!= (const block_t & rhs) const [inline]
Inequality operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator< (const block_t & rhs) const [inline]
Less-than operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator> (const block_t & rhs) const [inline]
Greater-than operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator<= (const block_t & rhs) const [inline]
Less-than-or-equal-to operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
bool SAMRAI::hier::BlockId::operator>= (const block_t & rhs) const [inline]
Greater-thanor-equal-to operator.
See note on comparison for operator==(const BlockId&);
Parameters:
[in] rhs
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & co, const BlockId & r) [friend]
Format and insert object into a stream.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BlockId.h
source/SAMRAI/hier/BlockId.C