SAMRAI: SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE > Class Template Reference
SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE > Class Template Reference
#include <source/SAMRAI/math/PatchSideDataMiscellaneousOpsReal.h>
Public Member Functions
PatchSideDataMiscellaneousOpsReal ()
virtual ~PatchSideDataMiscellaneousOpsReal ()
int computeConstrProdPos (const boost::shared_ptr< pdat::SideData< TYPE > > &data1, const boost::shared_ptr< pdat::SideData< TYPE > > &data2, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
void compareToScalar (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src, const TYPE &alpha, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
int testReciprocal (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
TYPE maxPointwiseDivide (const boost::shared_ptr< pdat::SideData< TYPE > > &numer, const boost::shared_ptr< pdat::SideData< TYPE > > &denom, const hier::Box &box) const
Compute max of "conditional" quotients of two arrays.
TYPE minPointwiseDivide (const boost::shared_ptr< pdat::SideData< TYPE > > &numer, const boost::shared_ptr< pdat::SideData< TYPE > > &denom, const hier::Box &box) const
Compute min of quotients of two arrays.
Detailed Description
template<class TYPE>
class SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >
Class PatchSideDataMiscellaneousOpsReal provides access to a collection of operations that may be applied to numerical side-centered patch data of type double and float. The primary intent of this class is to provide the interface to these operations for the class PatchSideDataOpsReal which provides access to a more complete set of operations that may be used to manipulate side-centered patch data. Each member function accepts a box argument indicating the region of index space on which the operation should be performed. The operation will be performed on the intersection of this box and those boxes corresponding to the patch data objects. Also, each operation allows an additional side-centered patch data object to be used to represent a control volume that weights the contribution of each data entry in the given norm calculation. Note that the control volume patch data must be of type double and have side-centered geometry (i.e., the same as the data itself). The use of control volumes is important when these operations are used in vector kernels where the data resides over multiple levels of spatial resolution in an AMR hierarchy. If the control volume is not given in the function call, it will be ignored in the calculation. Also, note that the depth of the control volume patch data object must be either 1 or be equal to the depth of the other data objects.
Since these operations are used only by the vector kernels for the KINSOL and CVODE solver packages at this time, they are intended to be instantiated for the standard built-in types double and float (since those solvers only treat double and float data). To extend this class to other data types or to include other operations, the member functions must be specialized or the new operations must be added.
See also:
math::ArrayDataMiscellaneousOpsReal
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::PatchSideDataMiscellaneousOpsReal () [inline]
Empty constructor and destructor.
template<class TYPE > SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::~PatchSideDataMiscellaneousOpsReal () [inline, virtual]
Member Function Documentation
template<class TYPE > int SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos (const boost::shared_ptr< pdat::SideData< TYPE > > & data1, const boost::shared_ptr< pdat::SideData< TYPE > > & data2, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return 1 if and , for any in the index region, where . Otherwise return 0. If the control volume is NULL, all values in the index set are used.
Precondition:
data1 && data2
data1->getDirectionVector() == data2->getDirectionVector()
!cvol || (data1->getDirectionVector() == hier::IntVector::min(data1->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::compareToScalar (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src, const TYPE & alpha, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Wherever in the index region, set if , and otherwise. If the control volume is NULL, all values in the index set are considered.
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
!cvol || (dst->getDirectionVector() == hier::IntVector::min(dst->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > int SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::testReciprocal (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Wherever in the index region, set if , and otherwise. If anywhere, 0 is the return value. Otherwise 1 is returned. If the control volume all values in the index set are considered.
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
!cvol || (dst->getDirectionVector() == hier::IntVector::min(dst->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > TYPE SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide (const boost::shared_ptr< pdat::SideData< TYPE > > & numer, const boost::shared_ptr< pdat::SideData< TYPE > > & denom, const hier::Box & box) const [inline]
Compute max of "conditional" quotients of two arrays.
Return the maximum of pointwise "conditional" quotients of the numerator and denominator.
The "conditional" quotient is defined as |numerator/denominator| where the denominator is nonzero. Otherwise, it is defined as |numerator|.
Note: This method is currently intended to support the PETSc-2.1.6 vector wrapper only. Please do not use it!
Precondition:
numer && denom
References TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > TYPE SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide (const boost::shared_ptr< pdat::SideData< TYPE > > & numer, const boost::shared_ptr< pdat::SideData< TYPE > > & denom, const hier::Box & box) const [inline]
Compute min of quotients of two arrays.
Return the minimum of pointwise quotients of the numerator and denominator.
The quotient is defined as (numerator/denominator) where the denominator is nonzero. When the denominator is zero, the entry is skipped. If the denominator is always zero, the value of tbox::IEEE::getFLT_MAX() is returned (see SAMRAI::tbox::IEEE).
Note: This method is currently intended to support the SUNDIALS vector wrapper only. Please do not use it!
Precondition:
numer && denom
References TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchSideDataMiscellaneousOpsReal.h
source/SAMRAI/math/PatchSideDataMiscellaneousOpsReal.C