SAMRAI: SAMRAI::tbox::HDFDatabase Class Reference
SAMRAI::tbox::HDFDatabase Class Reference
#include <source/SAMRAI/tbox/HDFDatabase.h>
Public Member Functions
HDFDatabase (const std::string &name)
HDFDatabase (const std::string &name, hid_t group_ID)
virtual ~HDFDatabase ()
virtual bool keyExists (const std::string &key)
virtual std::vector< std::string > getAllKeys ()
virtual enum DataType getArrayType (const std::string &key)
Return the type of data associated with the key.
virtual size_t getArraySize (const std::string &key)
virtual bool isDatabase (const std::string &key)
virtual boost::shared_ptr
< Database > putDatabase (const std::string &key)
virtual boost::shared_ptr
< Database > getDatabase (const std::string &key)
virtual bool isBool (const std::string &key)
virtual void putBoolArray (const std::string &key, const bool *const data, const size_t nelements)
virtual std::vector< bool > getBoolVector (const std::string &key)
virtual bool isDatabaseBox (const std::string &key)
virtual void putDatabaseBoxArray (const std::string &key, const DatabaseBox *const data, const size_t nelements)
virtual std::vector< DatabaseBox > getDatabaseBoxVector (const std::string &key)
virtual bool isChar (const std::string &key)
virtual void putCharArray (const std::string &key, const char *const data, const size_t nelements)
virtual std::vector< char > getCharVector (const std::string &key)
virtual bool isComplex (const std::string &key)
virtual void putComplexArray (const std::string &key, const dcomplex *const data, const size_t nelements)
virtual std::vector< dcomplex > getComplexVector (const std::string &key)
virtual bool isDouble (const std::string &key)
virtual void putDoubleArray (const std::string &key, const double *const data, const size_t nelements)
virtual std::vector< double > getDoubleVector (const std::string &key)
virtual bool isFloat (const std::string &key)
virtual void putFloatArray (const std::string &key, const float *const data, const size_t nelements)
virtual std::vector< float > getFloatVector (const std::string &key)
virtual bool isInteger (const std::string &key)
virtual void putIntegerArray (const std::string &key, const int *const data, const size_t nelements)
virtual std::vector< int > getIntegerVector (const std::string &key)
virtual bool isString (const std::string &key)
virtual void putStringArray (const std::string &key, const std::string *const data, const size_t nelements)
virtual std::vector< std::string > getStringVector (const std::string &key)
virtual void printClassData (std::ostream &os=pout)
virtual bool create (const std::string &name)
virtual bool open (const std::string &name, bool read_write_mode=false)
virtual bool attachToFile (hid_t group_id)
Attach the Database to an existing HDF file.
virtual bool close ()
virtual std::string getName ()
Returns the name of this database.
hid_t getGroupId ()
Detailed Description
Class HDFDatabase implements the interface of the Database class to store data in the HDF5 (Hierarchical Data Format) data format.
It is assumed that all processors will access the database in the same manner. Error reporting is done using the SAMRAI error reporting macros.
See also:
tbox::Database
Constructor & Destructor Documentation
SAMRAI::tbox::HDFDatabase::HDFDatabase (const std::string & name) [explicit]
The HDF database constructor creates an empty database with the specified name. By default the database will not be associated with a file until it is mounted, using the mount() member function.
The name string is *NOT* the name of the HDF file.
Precondition:
!name.empty()
References TBOX_ASSERT.
SAMRAI::tbox::HDFDatabase::HDFDatabase (const std::string & name, hid_t group_ID)
Constructor used to create sub-databases.
Precondition:
!name.empty()
References TBOX_ASSERT.
SAMRAI::tbox::HDFDatabase::~HDFDatabase () [virtual]
The database destructor closes the HDF5 group or data file.
References close(), NULL_USE, and TBOX_ASSERT.
Member Function Documentation
bool SAMRAI::tbox::HDFDatabase::keyExists (const std::string & key) [virtual]
Return true if the specified key exists in the database and false otherwise.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
std::vector< std::string > SAMRAI::tbox::HDFDatabase::getAllKeys () [virtual]
Return a vector of all keys in the current database. Note that no keys from subdatabases contained in the current database will appear in the array. To get the keys of any other database, you must call this routine for that database.
Implements SAMRAI::tbox::Database.
enum Database::DataType SAMRAI::tbox::HDFDatabase::getArrayType (const std::string & key) [virtual]
Return the type of data associated with the key.
If the key does not exist, then INVALID is returned
Parameters:
key Key name in database.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, isDatabase(), NULL_USE, SAMRAI::tbox::Database::SAMRAI_BOOL, SAMRAI::tbox::Database::SAMRAI_BOX, SAMRAI::tbox::Database::SAMRAI_CHAR, SAMRAI::tbox::Database::SAMRAI_COMPLEX, SAMRAI::tbox::Database::SAMRAI_DATABASE, SAMRAI::tbox::Database::SAMRAI_DOUBLE, SAMRAI::tbox::Database::SAMRAI_FLOAT, SAMRAI::tbox::Database::SAMRAI_INT, SAMRAI::tbox::Database::SAMRAI_INVALID, SAMRAI::tbox::Database::SAMRAI_STRING, and TBOX_ASSERT.
size_t SAMRAI::tbox::HDFDatabase::getArraySize (const std::string & key) [virtual]
Return the size of the array associated with the key. If the key does not exist, then zero is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
bool SAMRAI::tbox::HDFDatabase::isDatabase (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a database entry. If the key does not exist or if the string is empty, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getArrayType(), and getDatabase().
boost::shared_ptr< Database > SAMRAI::tbox::HDFDatabase::putDatabase (const std::string & key) [virtual]
Create a new database with the specified key name and return a pointer to it. A new group with the key name is also created in the data file.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
boost::shared_ptr< Database > SAMRAI::tbox::HDFDatabase::getDatabase (const std::string & key) [virtual]
Get the database with the specified key name. If the specified key does not represent a database entry in the database, then an error message is printed and the program exits.
Precondition:
!key.empty()
isDatabase(key)
Implements SAMRAI::tbox::Database.
References isDatabase(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isBool (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a boolean entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getBoolVector().
void SAMRAI::tbox::HDFDatabase::putBoolArray (const std::string & key, const bool *const data, const size_t nelements) [virtual]
Create a boolean array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References H5T_SAMRAI_BOOL, NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< bool > SAMRAI::tbox::HDFDatabase::getBoolVector (const std::string & key) [virtual]
Get a boolean entry from the database with the specified key name. If the specified key does not exist in the database, then an error message is printed and the program exits.
Precondition:
!key.empty()
isBool(key)
Implements SAMRAI::tbox::Database.
References isBool(), NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isDatabaseBox (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a box entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getDatabaseBoxVector().
void SAMRAI::tbox::HDFDatabase::putDatabaseBoxArray (const std::string & key, const DatabaseBox *const data, const size_t nelements) [virtual]
Create a box array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< DatabaseBox > SAMRAI::tbox::HDFDatabase::getDatabaseBoxVector (const std::string & key) [virtual]
Get a box entry from the database with the specified key name. If the specified key does not exist in the database or is not a box vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implements SAMRAI::tbox::Database.
References isDatabaseBox(), NULL_USE, SAMRAI::tbox::DatabaseBox::setDim(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isChar (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a char entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getCharVector().
void SAMRAI::tbox::HDFDatabase::putCharArray (const std::string & key, const char *const data, const size_t nelements) [virtual]
Create a character array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< char > SAMRAI::tbox::HDFDatabase::getCharVector (const std::string & key) [virtual]
Get a character entry from the database with the specified key name. If the specified key does not exist in the database, then an error message is printed and the program exits.
Precondition:
!key.empty()
isChar(key)
Implements SAMRAI::tbox::Database.
References isChar(), NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isComplex (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a complex entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getComplexVector().
void SAMRAI::tbox::HDFDatabase::putComplexArray (const std::string & key, const dcomplex *const data, const size_t nelements) [virtual]
Create a complex array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< dcomplex > SAMRAI::tbox::HDFDatabase::getComplexVector (const std::string & key) [virtual]
Get a complex entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isComplex(key)
Implements SAMRAI::tbox::Database.
References isComplex(), NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isDouble (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a double entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getDoubleVector().
void SAMRAI::tbox::HDFDatabase::putDoubleArray (const std::string & key, const double *const data, const size_t nelements) [virtual]
Create a double array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References H5T_SAMRAI_DOUBLE, NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< double > SAMRAI::tbox::HDFDatabase::getDoubleVector (const std::string & key) [virtual]
Get a double entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isDouble(key)
Implements SAMRAI::tbox::Database.
References isDouble(), NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isFloat (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a float entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getFloatVector().
void SAMRAI::tbox::HDFDatabase::putFloatArray (const std::string & key, const float *const data, const size_t nelements) [virtual]
Create a float array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References H5T_SAMRAI_FLOAT, NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< float > SAMRAI::tbox::HDFDatabase::getFloatVector (const std::string & key) [virtual]
Get a float entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isFloat(key)
Implements SAMRAI::tbox::Database.
References isFloat(), NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isInteger (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents an integer entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getIntegerVector().
void SAMRAI::tbox::HDFDatabase::putIntegerArray (const std::string & key, const int *const data, const size_t nelements) [virtual]
Create an integer array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References H5T_SAMRAI_INT, NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< int > SAMRAI::tbox::HDFDatabase::getIntegerVector (const std::string & key) [virtual]
Get an integer entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isInteger(key)
Implements SAMRAI::tbox::Database.
References isInteger(), NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::isString (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a string entry. If the key does not exist or if the string is empty, then false is returned.
Implements SAMRAI::tbox::Database.
References BEGIN_SUPPRESS_HDF5_WARNINGS, END_SUPPRESS_HDF5_WARNINGS, NULL_USE, and TBOX_ASSERT.
Referenced by getStringVector().
void SAMRAI::tbox::HDFDatabase::putStringArray (const std::string & key, const std::string *const data, const size_t nelements) [virtual]
Create a string array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
std::vector< std::string > SAMRAI::tbox::HDFDatabase::getStringVector (const std::string & key) [virtual]
Get a string entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isString(key)
Implements SAMRAI::tbox::Database.
References isString(), NULL_USE, TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::tbox::HDFDatabase::printClassData (std::ostream & os = pout) [virtual]
Print contents of current database to the specified output stream. If no output stream is specified, then data is written to stream pout. Note that none of the subdatabases contained in the current database will have their contents printed. To view the contents of any other database, you must call this print routine for that database.
Implements SAMRAI::tbox::Database.
References TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::create (const std::string & name) [virtual]
Create a new database file.
Returns true if successful.
Parameters:
name name of database. Normally a filename.
Precondition:
!name.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::open (const std::string & name, bool read_write_mode = false) [virtual]
Open an existing database file.
Returns true if successful.
Parameters:
name name of database. Normally a filename.
read_write_mode Open the database in read-write mode instead of read-only mode.
Precondition:
!name.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::attachToFile (hid_t group_id) [virtual]
Attach the Database to an existing HDF file.
If an application has an existing HDF file used for restart this method can be used to write SAMRAI restart information to the existing file instead of SAMRAI creating a distinct file.
The group_id should be a hid returned from a H5Gcreate call. SAMRAI data will be written within this group.
Returns true if attach was successful.
Precondition:
group_id > 0
References TBOX_ERROR.
bool SAMRAI::tbox::HDFDatabase::close () [virtual]
Close the database.
Returns true if successful.
If the database is currently open then close it. This should flush all data to the file (if the database is on disk).
Implements SAMRAI::tbox::Database.
References NULL_USE, and TBOX_ASSERT.
Referenced by ~HDFDatabase().
std::string SAMRAI::tbox::HDFDatabase::getName (void) [virtual]
Returns the name of this database.
The name for the root of the database is the name supplied when creating it. Names for nested databases are the keyname of the database.
Implements SAMRAI::tbox::Database.
hid_t SAMRAI::tbox::HDFDatabase::getGroupId () [inline]
Return the group_id so VisIt can access an object's HDF database.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/HDFDatabase.h
source/SAMRAI/tbox/HDFDatabase.C