SAMRAI: SAMRAI::pdat::FaceGeometry Class Reference
SAMRAI::pdat::FaceGeometry Class Reference
#include <source/SAMRAI/pdat/FaceGeometry.h>
Public Types
typedef FaceOverlap Overlap
Public Member Functions
FaceGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct the face geometry object given an AMR index space box and ghost cell width.
virtual ~FaceGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in face-centered index space between the source box geometry and the destination box geometry.
void computeDestinationBoxes (std::vector< hier::BoxContainer > &dst_boxes, const FaceGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the face-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a FaceOverlap object based on the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this face centered box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this face centered box geometry object.
Static Public Member Functions
static hier::Box toFaceBox (const hier::Box &box, tbox::Dimension::dir_t face_normal)
Convert an AMR index box space box into an face geometry box. An face geometry box extends the given AMR index box space box by one in upper end for the face normal coordinate direction.
static void transform (hier::Box &box, int &normal_direction, const hier::Transformation &transformation)
Transform a face-centered box.
static void transform (FaceIndex &index, const hier::Transformation &transformation)
Transform a FaceIndex.
static FaceIterator begin (const hier::Box &box, tbox::Dimension::dir_t axis)
static FaceIterator end (const hier::Box &box, tbox::Dimension::dir_t axis)
Detailed Description
Class FaceGeometry manages the mapping between the AMR index space and the face-centered geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between face- centered box geometries for communication operations.
See header file for FaceData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
pdat::FaceOverlap
Member Typedef Documentation
typedef FaceOverlap SAMRAI::pdat::FaceGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::FaceGeometry::FaceGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct the face geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::FaceGeometry::~FaceGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
hier::Box SAMRAI::pdat::FaceGeometry::toFaceBox (const hier::Box & box, tbox::Dimension::dir_t face_normal) [static]
Convert an AMR index box space box into an face geometry box. An face geometry box extends the given AMR index box space box by one in upper end for the face normal coordinate direction.
Recall that box indices are cyclically shifted such that the face normal direction is the first coordinate index. See SideData header file.
Precondition:
(face_normal >= 0) && (face_normal < box.getDim().getValue())
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::math::PatchFaceDataOpsInteger::abs(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchFaceDataNormOpsComplex::abs(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::add(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::addScalar(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::axmy(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::axpy(), SAMRAI::math::PatchFaceDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::PatchFaceDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), computeDestinationBoxes(), SAMRAI::math::PatchFaceDataOpsReal< TYPE >::copyData(), SAMRAI::math::PatchFaceDataOpsInteger::copyData(), SAMRAI::math::PatchFaceDataOpsComplex::copyData(), SAMRAI::pdat::FaceData< TYPE >::copyOnBox(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::divide(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::dot(), SAMRAI::math::PatchFaceDataNormOpsComplex::dot(), SAMRAI::pdat::FaceData< TYPE >::FaceData(), SAMRAI::pdat::OuterfaceData< TYPE >::fill(), SAMRAI::pdat::FaceData< TYPE >::fill(), SAMRAI::pdat::OuterfaceData< TYPE >::fillAll(), SAMRAI::pdat::FaceData< TYPE >::fillAll(), SAMRAI::pdat::OuterfaceData< TYPE >::getSizeOfData(), SAMRAI::pdat::FaceData< TYPE >::getSizeOfData(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::integral(), SAMRAI::math::PatchFaceDataNormOpsComplex::integral(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::L2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::linearSum(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::max(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::PatchFaceDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchFaceDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::min(), SAMRAI::math::PatchFaceDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::multiply(), SAMRAI::math::PatchFaceDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsComplex::numberOfEntries(), SAMRAI::pdat::OuterfaceData< TYPE >::OuterfaceData(), SAMRAI::pdat::OuterfaceData< TYPE >::printAxisFace(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::HierarchyFaceDataOpsReal< TYPE >::resetLevels(), SAMRAI::math::HierarchyFaceDataOpsInteger::resetLevels(), SAMRAI::math::HierarchyFaceDataOpsComplex::resetLevels(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::scale(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::setRandomValues(), SAMRAI::pdat::OuterfaceGeometry::setUpOverlap(), setUpOverlap(), SAMRAI::math::PatchFaceDataBasicOps< TYPE >::subtract(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::PatchFaceDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchFaceDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::weightedL2Norm(), and SAMRAI::math::PatchFaceDataNormOpsComplex::weightedL2Norm().
void SAMRAI::pdat::FaceGeometry::transform (hier::Box & box, int & normal_direction, const hier::Transformation & transformation) [static]
Transform a face-centered box.
At input, the Box is assumed to represent an face-centered box with the given normal direction. The Box will be transformed according to the coordinate system transformation defined by the Transformation object. At output, normal_direction will represent the output box's new normal direction.
Parameters:
[in,out] box
[in,out] normal_direction
[in] transformation
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_JUP_KUP, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Box::lower(), SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::pdat::FaceOverlap::getSourceBoxContainer().
void SAMRAI::pdat::FaceGeometry::transform (FaceIndex & index, const hier::Transformation & transformation) [static]
Transform a FaceIndex.
This static method applies a coordinate system transformation to the given FaceIndex.
Parameters:
[in,out] index
[in] transformation
References SAMRAI::pdat::FaceIndex::getAxis(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::pdat::FaceIndex::setAxis(), TBOX_ASSERT, and TBOX_ERROR.
FaceIterator SAMRAI::pdat::FaceGeometry::begin (const hier::Box & box, tbox::Dimension::dir_t axis) [static]
Referenced by SAMRAI::pdat::FaceData< TYPE >::printAxis().
FaceIterator SAMRAI::pdat::FaceGeometry::end (const hier::Box & box, tbox::Dimension::dir_t axis) [static]
Referenced by SAMRAI::pdat::FaceData< TYPE >::printAxis().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::FaceGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in face-centered index space between the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::pdat::FaceGeometry::computeDestinationBoxes (std::vector< hier::BoxContainer > & dst_boxes, const FaceGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const
Compute the face-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
Precondition:
src_mask.getDim() == transformation.getOffset.getDim()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxContainer::pushBack(), TBOX_ASSERT_OBJDIM_EQUALITY2, toFaceBox(), and SAMRAI::hier::Transformation::transform().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::FaceGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a FaceOverlap object based on the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getOffset(), and toFaceBox().
const hier::Box& SAMRAI::pdat::FaceGeometry::getBox () const [inline]
Return the box for this face centered box geometry object.
const hier::IntVector& SAMRAI::pdat::FaceGeometry::getGhosts () const [inline]
Return the ghost cell width for this face centered box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/FaceGeometry.h
source/SAMRAI/pdat/FaceGeometry.C