SAMRAI: SAMRAI::math::ArrayDataNormOpsInteger Class Reference
SAMRAI::math::ArrayDataNormOpsInteger Class Reference
#include <source/SAMRAI/math/ArrayDataNormOpsInteger.h>
Public Member Functions
ArrayDataNormOpsInteger ()
~ArrayDataNormOpsInteger ()
void abs (pdat::ArrayData< int > &dst, const pdat::ArrayData< int > &src, const hier::Box &box) const
Detailed Description
Class ArrayDataNormOpsInteger provides a set of common norm operations that may be applied to arrays of integer data values maintained as pdat::ArrayData<TYPE> objects. The intent of this class is to provide a single implementation of these operations as they are needed by objects that perform these operations on the standard array-based patch data types (i.e., cell-centered, face-centered, node-centered). Note that each operation is performed on the intersection of the box in the function argument list and the boxes associated with all pdat::ArrayData<TYPE> objects. Currently, the only norm operation implemented in this class is the absolute value operation.
See also:
pdat::ArrayData
Constructor & Destructor Documentation
SAMRAI::math::ArrayDataNormOpsInteger::ArrayDataNormOpsInteger ()
Empty constructor and destructor.
SAMRAI::math::ArrayDataNormOpsInteger::~ArrayDataNormOpsInteger ()
Member Function Documentation
void SAMRAI::math::ArrayDataNormOpsInteger::abs (pdat::ArrayData< int > & dst, const pdat::ArrayData< int > & src, const hier::Box & box) const
Set destination component to absolute value of source component. That is, each destination entry is set to .
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == box.getDim())
dst.getDepth() == src.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataOpsInteger::abs(), SAMRAI::math::PatchNodeDataOpsInteger::abs(), SAMRAI::math::PatchFaceDataOpsInteger::abs(), SAMRAI::math::PatchEdgeDataOpsInteger::abs(), and SAMRAI::math::PatchCellDataOpsInteger::abs().
The documentation for this class was generated from the following files:
source/SAMRAI/math/ArrayDataNormOpsInteger.h
source/SAMRAI/math/ArrayDataNormOpsInteger.C