SAMRAI: SAMRAI::hier::PatchGeometry Class Reference
SAMRAI::hier::PatchGeometry Class Reference
#include <source/SAMRAI/hier/PatchGeometry.h>
Classes
class TwoDimBool
Array of 2*DIM booleans (with default constructor), used to instantiate the sparse container map<LocalId,TwoDimBool> (map<LocalId,bool[2*DIM]> does not work).
Public Member Functions
PatchGeometry (const IntVector &ratio_to_level_zero, const TwoDimBool &touches_regular_bdry)
virtual ~PatchGeometry ()
const std::vector< std::vector
< BoundaryBox > > & getPatchBoundaries () const
void setBoundaryBoxesOnPatch (const std::vector< std::vector< BoundaryBox > > &bdry)
Set the boundary box vectors for this patch geometry.
const IntVector & getRatio () const
bool intersectsPhysicalBoundary () const
const std::vector< BoundaryBox > & getNodeBoundaries () const
const std::vector< BoundaryBox > & getEdgeBoundaries () const
const std::vector< BoundaryBox > & getFaceBoundaries () const
const std::vector< BoundaryBox > & getCodimensionBoundaries (const int codim) const
void setCodimensionBoundaries (const std::vector< BoundaryBox > &bdry_boxes, const int codim)
Box getBoundaryFillBox (const BoundaryBox &bbox, const Box &patch_box, const IntVector &gcw) const
Compute a box outside a physical domain that needs to be filled.
bool getTouchesRegularBoundary () const
Query whether patch touches a regular boundary.
bool getTouchesPeriodicBoundary () const
Query whether patch touches a regular boundary.
bool getTouchesRegularBoundary (int axis, int upperlower) const
Query whether patch touches a specific regular boundary.
void printClassData (std::ostream &stream) const
const tbox::Dimension & getDim () const
Detailed Description
Class PatchGeometry is the base class for geometry classes that manage index space and mesh increment information on individual patches. Patch geometry information is used for setting boundary conditions in ghost cells and is used in the inter-level transfer operators for refining or coarsening data between two patches associated with different index spaces. The boundary information for patches is actually computed by the BaseGridGeometry class.
See also:
hier::BoundaryBox
hier::BaseGridGeometry
Constructor & Destructor Documentation
SAMRAI::hier::PatchGeometry::PatchGeometry (const IntVector & ratio_to_level_zero, const TwoDimBool & touches_regular_bdry)
The constructor for the patch geometry base class.
Precondition:
(ratio_to_level_zero.getDim() == touches_regular_bdry.getDim())
all components of ratio_to_level_zero must be nonzero and all components of ratio_to_level_zero not equal to 1 must have the same sign
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::hier::PatchGeometry::~PatchGeometry () [virtual]
The virtual destructor for the patch geometry base class.
Member Function Documentation
const std::vector<std::vector<BoundaryBox> >& SAMRAI::hier::PatchGeometry::getPatchBoundaries () const [inline]
Return const reference to patch boundary information.
References SAMRAI::hier::PatchBoundaries::getVectors().
void SAMRAI::hier::PatchGeometry::setBoundaryBoxesOnPatch (const std::vector< std::vector< BoundaryBox > > & bdry)
Set the boundary box vectors for this patch geometry.
A vector of length DIM of std::vector<BoundaryBox> is passed in to be stored as the boundary boxes for this patch geometry.
Parameters:
bdry The vector of BoundaryBox vectors.
References SAMRAI::tbox::Dimension::getValue(), and setCodimensionBoundaries().
const IntVector& SAMRAI::hier::PatchGeometry::getRatio () const [inline]
Return const reference to ratio to level zero index space.
Referenced by SAMRAI::geom::CartesianPatchGeometry::printClassData().
bool SAMRAI::hier::PatchGeometry::intersectsPhysicalBoundary () const [inline]
Return a boolean value indicating whether the patch boundary intersects the physical domain boundary in a non-periodic direction. In other words, the return value is true when the patch has non-empty boundary boxes that lie outside the physical domain. Otherwise, the return value is false. Note that when a patch touches the "boundary" of the physical domain in a periodic direction, there are no boundary boxes to fill; the data is filled from the proper region of the domain interior in the periodic direction.
const std::vector<BoundaryBox>& SAMRAI::hier::PatchGeometry::getNodeBoundaries () const [inline]
Return vector of boundary box components for patch each of which intersects the patch at a single point (i.e., 0-dim intersection between cells in patch and cells in boundary box).
References getDim(), and SAMRAI::tbox::Dimension::getValue().
const std::vector<BoundaryBox>& SAMRAI::hier::PatchGeometry::getEdgeBoundaries () const [inline]
Return vector of boundary box components for patch each of which intersects the patch along a 1-dim edge (i.e., 1-dim intersection between cells in patch and cells in boundary box).
Precondition:
getDim().getValue() >= 2
References getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ERROR.
const std::vector<BoundaryBox>& SAMRAI::hier::PatchGeometry::getFaceBoundaries () const [inline]
Return vector of boundary box components for patch each of which intersects the patch along a 2-dim face (i.e., 2-dim intersection between cells in patch and cells in boundary box).
Precondition:
getDim().getValue() >= 3
References getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ERROR.
const std::vector<BoundaryBox>& SAMRAI::hier::PatchGeometry::getCodimensionBoundaries (const int codim) const [inline]
Return vector of boundary box components for patch each of which intersects the patch as a (DIM - codim)-dimensional object. That is,
if DIM == 1: (codim == 1) => same components as getNodeBoundaries.
if DIM == 2, (codim == 1) => same components as getEdgeBoundaries. (codim == 2) => same components as getNodeBoundaries.
if DIM == 3, (codim == 1) => same components as getFaceBoundaries. (codim == 2) => same components as getEdgeBoundaries. (codim == 3) => same components as getNodeBoundaries.
Precondition:
(codim > 0) && (codim <= getDim().getValue()) when codim < 0 or codim > DIM.
References getDim(), and TBOX_ASSERT.
void SAMRAI::hier::PatchGeometry::setCodimensionBoundaries (const std::vector< BoundaryBox > & bdry_boxes, const int codim)
Set the vector of boundary box components of the given codimension for a patch.
Precondition:
(codim > 0) && (codim <= getDim().getValue())
for each boundary_box in bdry_boxes, getBoundaryType() == codim
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
Referenced by setBoundaryBoxesOnPatch().
Box SAMRAI::hier::PatchGeometry::getBoundaryFillBox (const BoundaryBox & bbox, const Box & patch_box, const IntVector & gcw) const
Compute a box outside a physical domain that needs to be filled.
The patch box will be grown by the given ghost cell width and then intersected with the boundary box. The resulting intersection will be grown to the needed ghost cell width in the direction normal to the boundary.
Parameters:
bbox BoundaryBox representing location and type of boundary
patch_box The box for the patch where data is being filled
gcw ghost cell width to fill
Precondition:
bbox.getDim() == patch_box.getDim()
bbox.getDim() == gcw.getDim()
all components of gcw are >= 0
References SAMRAI::hier::BoundaryBox::getBoundaryType(), SAMRAI::hier::BoundaryBox::getBox(), SAMRAI::hier::BoundaryLookupTable::getDirections(), SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::hier::BoundaryLookupTable::getLookupTable(), SAMRAI::hier::BoundaryLookupTable::getMaxLocationIndices(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoundaryLookupTable::isUpper(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
bool SAMRAI::hier::PatchGeometry::getTouchesRegularBoundary () const [inline]
Query whether patch touches a regular boundary.
Returns true if the Patch touches any non-periodic physical boundary
bool SAMRAI::hier::PatchGeometry::getTouchesPeriodicBoundary () const [inline]
Query whether patch touches a regular boundary.
Returns true if the Patch touches any periodic boundary
bool SAMRAI::hier::PatchGeometry::getTouchesRegularBoundary (int axis, int upperlower) const [inline]
Query whether patch touches a specific regular boundary.
Returns true if the Patch touches a non-periodic physical boundary on the side of the Patch specified in the argument list. The side is specified by an axis direction and a flag specified the upper or lower side.
Parameters:
axis Axis direction normal to the side being checked
upperlower Flag should be 0 if checking the lower side in the axis direction, or 1 if checking the upper side.
Precondition:
(axis >= 0) && (axis < getDim().getValue())
(upperlower == 0) || (upperlower == 1)
References getDim(), and TBOX_ASSERT.
void SAMRAI::hier::PatchGeometry::printClassData (std::ostream & stream) const
Print object data to the specified output stream.
Reimplemented in SAMRAI::geom::CartesianPatchGeometry.
References SAMRAI::tbox::Dimension::getValue().
const tbox::Dimension& SAMRAI::hier::PatchGeometry::getDim () const [inline]
Referenced by getCodimensionBoundaries(), getEdgeBoundaries(), getFaceBoundaries(), getNodeBoundaries(), getTouchesRegularBoundary(), and SAMRAI::geom::CartesianPatchGeometry::printClassData().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchGeometry.h
source/SAMRAI/hier/PatchGeometry.C