SAMRAI: SAMRAI::tbox::RankTreeStrategy Class Reference
SAMRAI::tbox::RankTreeStrategy Class Reference
Strategy pattern for getting information on MPI ranks aranged on a user-defined tree.
#include <source/SAMRAI/tbox/RankTreeStrategy.h>
Public Member Functions
RankTreeStrategy ()
Constructor.
virtual ~RankTreeStrategy ()
Destructor.
virtual void setupTree (const RankGroup &rank_group, int my_rank)=0
Set up the tree.
virtual int getRank () const =0
Access the rank used in initialization.
virtual int getParentRank () const =0
Access the parent rank.
virtual int getChildRank (unsigned int child_number) const =0
Access a child rank.
virtual unsigned int getNumberOfChildren () const =0
Return the number of children.
virtual unsigned int getChildNumber () const =0
Return the child number.
virtual unsigned int getDegree () const =0
Return the degree of the tree (the maximum number of children each node may have).
virtual unsigned int getGenerationNumber () const =0
Return the generation number.
virtual int getRootRank () const =0
Return the rank of the root of the tree.
bool isRoot () const
Return whether the local process is the root of its tree.
Static Public Member Functions
static int getInvalidRank ()
What this class considers an invalid rank.
static unsigned int getInvalidChildNumber ()
What this class considers an invalid child number.
Detailed Description
Strategy pattern for getting information on MPI ranks aranged on a user-defined tree.
The purpose of a rank tree is to facilitate "collective-like" communications where information is communicated up or down the tree along its edges. It gives the parent rank, children ranks, etc., for a node in the tree.
To improve communication performance, the tree should map well to the communication hardware. That is, processes on each ends of an edge should be close to each other on the communication network. Implementations of this strategy should consider the network topology when deciding how to lay out the process on the tree.
Constructor & Destructor Documentation
SAMRAI::tbox::RankTreeStrategy::RankTreeStrategy ()
Constructor.
SAMRAI::tbox::RankTreeStrategy::~RankTreeStrategy () [virtual]
Destructor.
Member Function Documentation
virtual void SAMRAI::tbox::RankTreeStrategy::setupTree (const RankGroup & rank_group, int my_rank) [pure virtual]
Set up the tree.
Set up the tree for the processors in the given RankGroup. Prepare to provide tree data for the given rank.
Parameters:
[in] rank_group
[in] my_rank The rank whose parent and children are sought, usually the local process.
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
virtual int SAMRAI::tbox::RankTreeStrategy::getRank () const [pure virtual]
Access the rank used in initialization.
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
Referenced by isRoot().
virtual int SAMRAI::tbox::RankTreeStrategy::getParentRank () const [pure virtual]
Access the parent rank.
Returns:
parent rank or getInvalidRank() if is root of the tree.
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
virtual int SAMRAI::tbox::RankTreeStrategy::getChildRank (unsigned int child_number) const [pure virtual]
Access a child rank.
Parameters:
child_number If outside [0, getNumberOfChildren()), the invalid rankd should be returned.
Returns:
Child's rank, or getInvalidRank() if child_number is outside [0, getNumberOfChildren()).
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
virtual unsigned int SAMRAI::tbox::RankTreeStrategy::getNumberOfChildren () const [pure virtual]
Return the number of children.
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
virtual unsigned int SAMRAI::tbox::RankTreeStrategy::getChildNumber () const [pure virtual]
Return the child number.
Return child number or invalidChildNumber() if is root of the tree.
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
virtual unsigned int SAMRAI::tbox::RankTreeStrategy::getDegree () const [pure virtual]
Return the degree of the tree (the maximum number of children each node may have).
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
virtual unsigned int SAMRAI::tbox::RankTreeStrategy::getGenerationNumber () const [pure virtual]
Return the generation number.
The generation number starts at zero, at the root, and increases by one each generation.
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
virtual int SAMRAI::tbox::RankTreeStrategy::getRootRank () const [pure virtual]
Return the rank of the root of the tree.
Implemented in SAMRAI::tbox::BalancedDepthFirstTree, SAMRAI::tbox::BreadthFirstRankTree, and SAMRAI::tbox::CenteredRankTree.
Referenced by isRoot().
bool SAMRAI::tbox::RankTreeStrategy::isRoot () const [inline]
Return whether the local process is the root of its tree.
References getRank(), and getRootRank().
Referenced by SAMRAI::hier::Connector::computeTransposeOf().
static int SAMRAI::tbox::RankTreeStrategy::getInvalidRank () [inline, static]
What this class considers an invalid rank.
When a parent or child does not exist, this value is returned for the rank.
Referenced by SAMRAI::tbox::CenteredRankTree::getChildRank(), SAMRAI::tbox::BreadthFirstRankTree::getChildRank(), SAMRAI::tbox::BalancedDepthFirstTree::getChildRank(), SAMRAI::tbox::CenteredRankTree::makeFirstRankTheRoot(), SAMRAI::tbox::BalancedDepthFirstTree::setLeftLeafSwitching(), and SAMRAI::tbox::BreadthFirstRankTree::setTreeDegree().
static unsigned int SAMRAI::tbox::RankTreeStrategy::getInvalidChildNumber () [inline, static]
What this class considers an invalid child number.
The root of the tree is not anyone's child, so it should return this for getChildNumber();.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/RankTreeStrategy.h
source/SAMRAI/tbox/RankTreeStrategy.C