SAMRAI: SAMRAI::tbox::SAMRAIManager Class Reference
SAMRAI::tbox::SAMRAIManager Class Reference
Utility for managing startup and shutdown of SAMRAI objects and for managing the maximum number of patch data components allowed.
#include <source/SAMRAI/tbox/SAMRAIManager.h>
Static Public Member Functions
static void initialize (bool initialize_IEEE_assertion_handlers=true)
Initial setup of the SAMRAI package.
static void startup ()
Startup of the SAMRAI package.
static void shutdown ()
Shutdown the SAMRAI package.
static void finalize ()
Final cleanup of the SAMRAI package.
static bool isInitialized ()
Returns true if SAMRAIManager has been initialized.
static bool isStarted ()
Returns true if SAMRAIManager has been started.
static int getMaxNumberPatchDataEntries ()
Return maximum number of patch data entries supported by SAMRAI.
static void setMaxNumberPatchDataEntries (int maxnum)
Set maximum number of patch data entries supported by SAMRAI.
Detailed Description
Utility for managing startup and shutdown of SAMRAI objects and for managing the maximum number of patch data components allowed.
The startup/shutdown mechanism in SAMRAIManager is used to manage the allocation and deallocation of certain memory, particularly static data that must exist during the full extent of a run or for the full extent of a single problem within a run. The specific data that is controlled by this mechanism is managed using the StartupShutdownManager.
The four steps of the startup/shutdown mechanism are:
initialize -- called at the start of a program after MPI is initialized but befor any other SAMRAI objects are used.
startup -- called to begin a problem-specific segment of the code.
shutdown -- called at the end of a problem-specific segment of the code. Shuts down and deallocates everything that was started and allocated by startup.
finalize -- called at the end of a program right before MPI is finalized.
The startup and shutdown functions may be called multiple times within a run, in order to allow for the execution of more than one problem within one program. Initialize and finalize must be called exactly once in a single run.
Additionally this class manages static data that controls the maximum number of patch data components that can be allowed.
See also:
SAMRAI_MPI
StartupShutdownManager
Member Function Documentation
void SAMRAI::tbox::SAMRAIManager::initialize (bool initialize_IEEE_assertion_handlers = true) [static]
Initial setup of the SAMRAI package.
This function should be invoked ONLY ONCE at the start of a process to initialize SAMRAI and AFTER MPI is initialized (if used) by a call to one of the SAMRAI_MPI init routines.
This function initializes IEEE expection handlers and SAMRAI I/O, as well as data for any classes that implement the initialize callback interface through StartupShutdownManager.
Parameters:
[in] initialize_IEEE_assertion_handlers (defaults to true)
Precondition:
!s_initialized
References SAMRAI::tbox::badnew(), SAMRAI::tbox::IEEE::setupFloatingPointExceptionHandlers(), and TBOX_ASSERT.
static void SAMRAI::tbox::SAMRAIManager::startup () [inline, static]
Startup of the SAMRAI package.
This function invokes startup for any classes that implement the startup callback interface through StartupShutdownManager. This function may be invoked more than once in a process if solving multiple SAMRAI problems.
Precondition:
s_initialized
!s_started
References TBOX_ASSERT.
static void SAMRAI::tbox::SAMRAIManager::shutdown () [inline, static]
Shutdown the SAMRAI package.
This function invokes shutdown for any classes that implement the startup callback interface through StartupShutdownManager. This function may be invoked more than once in an process if solving multiple SAMRAI problems.
Precondition:
s_initialized
s_started
References TBOX_ASSERT.
static void SAMRAI::tbox::SAMRAIManager::finalize () [inline, static]
Final cleanup of the SAMRAI package.
This function should be invoked ONLY ONCE at the end of a process to complete the cleanup of SAMRAI memory allocations and any other cleanup tasks. IEEE assertion handlers and SAMRAI I/O will be finalized, as well as data for any classes that implement the finalize callback interface through StartupShutdownManager.
After this function is called, the only thing that should occur before exiting the program is a call to SAMRAI_MPI::finalize().
This function should be invoked only once.
Precondition:
s_initialized
References TBOX_ASSERT.
static bool SAMRAI::tbox::SAMRAIManager::isInitialized () [inline, static]
Returns true if SAMRAIManager has been initialized.
static bool SAMRAI::tbox::SAMRAIManager::isStarted () [inline, static]
Returns true if SAMRAIManager has been started.
static int SAMRAI::tbox::SAMRAIManager::getMaxNumberPatchDataEntries () [inline, static]
Return maximum number of patch data entries supported by SAMRAI.
The value is either the default value (256) or the value set by calling the setMaxNumberPatchDataEntries() function.
Referenced by SAMRAI::hier::ComponentSelector::ComponentSelector(), and SAMRAI::hier::PatchDescriptor::PatchDescriptor().
void SAMRAI::tbox::SAMRAIManager::setMaxNumberPatchDataEntries (int maxnum) [static]
Set maximum number of patch data entries supported by SAMRAI.
The maximum number will be set to the maximum of the current value and the argument value.
Note that this routine cannot be called anytime after the max patch data entries value has been accessed via the getMaxNumberPatchDataEntries() function, neither by the user nor internally within SAMRAI. Typically, the first internal access of this value occurs whenever any objects related to the patch hierarchy or variables are created.
Precondition:
s_max_patch_data_entries_accessed
References TBOX_ERROR.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/SAMRAIManager.h
source/SAMRAI/tbox/SAMRAIManager.C