SAMRAI: SAMRAI::mesh::TileClustering Class Reference
SAMRAI::mesh::TileClustering Class Reference
Tiled patch clustering algorithm.
#include <source/SAMRAI/mesh/TileClustering.h>
Public Member Functions
TileClustering (const tbox::Dimension &dim, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
Constructor.
virtual ~TileClustering ()
Destructor.
void findBoxesContainingTags (boost::shared_ptr< hier::BoxLevel > &new_box_level, boost::shared_ptr< hier::Connector > &tag_to_new, const boost::shared_ptr< hier::PatchLevel > &tag_level, const int tag_data_index, const int tag_val, const hier::BoxContainer &bound_boxes, const hier::IntVector &min_box, const hier::IntVector &max_gcw)
Implement the mesh::BoxGeneratorStrategy interface method of the same name.
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
Protected Member Functions
void getFromInput (const boost::shared_ptr< tbox::Database > &input_db)
Read parameters from input database.
Detailed Description
Tiled patch clustering algorithm.
Input Parameters
Definitions:
tile_size Tile size in the index space of the tag level.
coalesce_boxes Whether to coalesce boxes after clustering. This can lead to clusters that are bigger than specified tile size.
coalesce_boxes_from_same_patch Whether to coalesce tiled-boxes that originate from the same tag patch. This can reduce number of tiles and lead to clusters bigger than tile size.
allow_remote_tile_extent Whether tile may extend to remote tag patches. If false, tiles will be cut at process boundaries, resulting in completely local tiles. If true, allow tiles to cross process boundaries where, resulting in less tile fragmentation. If false, clusters' extent can depend on how tag level is partitioned.
DEV_debug_checks Whether to run expensive checks for debugging.
Details:
parameter
type
default
range
opt/req
behavior on restart
tile_size
int[]
all values are 8
all values > 0
opt
Not written to restart. Value in input db used.
coalesce_boxes
bool
true
false/true
opt
Not written to restart. Value in input db used.
coalesce_boxes_from_same_patch
bool
false
false/true
opt
Not written to restart. Value in input db used.
allow_remote_tile_extent
bool
true
false/true
opt
Not written to restart. Value in input db used.
DEV_debug_checks
bool
false
false/true
opt
Not written to restart. Value in input db used.
Constructor & Destructor Documentation
SAMRAI::mesh::TileClustering::TileClustering (const tbox::Dimension & dim, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>()) [explicit]
Constructor.
References getFromInput(), SAMRAI::hier::MappingConnectorAlgorithm::setTimerPrefix(), SAMRAI::hier::OverlapConnectorAlgorithm::setTimerPrefix(), setTimerPrefix(), and TBOX_omp_init_lock.
SAMRAI::mesh::TileClustering::~TileClustering () [virtual]
Destructor.
Deallocate internal data.
References TBOX_omp_destroy_lock.
Member Function Documentation
void SAMRAI::mesh::TileClustering::findBoxesContainingTags (boost::shared_ptr< hier::BoxLevel > & new_box_level, boost::shared_ptr< hier::Connector > & tag_to_new, const boost::shared_ptr< hier::PatchLevel > & tag_level, const int tag_data_index, const int tag_val, const hier::BoxContainer & bound_boxes, const hier::IntVector & min_box, const hier::IntVector & max_gcw) [virtual]
Implement the mesh::BoxGeneratorStrategy interface method of the same name.
Create a set of boxes that covers all integer tags on the patch level that match the specified tag value. Each box will be at least as large as the given minimum size and the tolerances will be met.
Implements SAMRAI::mesh::BoxGeneratorStrategy.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::findOverlapBoxes(), SAMRAI::hier::BoxContainer::front(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::isEmpty(), SAMRAI::hier::BoxContainer::makeTree(), MPI_MAX, NULL_USE, SAMRAI::tbox::plog, SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and TBOX_ERROR.
void SAMRAI::mesh::TileClustering::setTimerPrefix (const std::string & timer_prefix)
Setup names of timers.
References SAMRAI::tbox::TimerManager::getManager(), and SAMRAI::tbox::TimerManager::getTimer().
Referenced by TileClustering().
void SAMRAI::mesh::TileClustering::getFromInput (const boost::shared_ptr< tbox::Database > & input_db) [protected]
Read parameters from input database.
Parameters:
input_db Input Database.
References SAMRAI::tbox::Dimension::getValue().
Referenced by TileClustering().
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/TileClustering.h
source/SAMRAI/mesh/TileClustering.C