SAMRAI: SAMRAI::hier::TransferOperatorRegistry Class Reference
SAMRAI::hier::TransferOperatorRegistry Class Reference
Class TransferOperatorRegistry is intended to serve as the registry for SAMRAI transfer operators. It will be a singleton object held by class hier::BaseGridGeometry.
#include <source/SAMRAI/hier/TransferOperatorRegistry.h>
Public Member Functions
TransferOperatorRegistry (const tbox::Dimension &dim)
Set the state of the hier::TransferOperatorRegistry members.
virtual ~TransferOperatorRegistry ()
Destructor.
void addCoarsenOperator (const char *var_type_name, const boost::shared_ptr< CoarsenOperator > &coarsen_op)
Add a concrete spatial coarsening operator.
void addRefineOperator (const char *var_type_name, const boost::shared_ptr< RefineOperator > &refine_op)
Add a concrete spatial refinement operator.
void addTimeInterpolateOperator (const char *var_type_name, const boost::shared_ptr< TimeInterpolateOperator > &time_op)
Add a concrete time interpolation operator.
boost::shared_ptr
< CoarsenOperator > lookupCoarsenOperator (const boost::shared_ptr< Variable > &var, const std::string &op_name)
Lookup function for coarsening operator.
boost::shared_ptr< RefineOperator > lookupRefineOperator (const boost::shared_ptr< Variable > &var, const std::string &op_name)
Lookup function for refinement operator.
boost::shared_ptr
< TimeInterpolateOperator > lookupTimeInterpolateOperator (const boost::shared_ptr< Variable > &var, const std::string &op_name="STD_LINEAR_TIME_INTERPOLATE")
Lookup function for time interpolation operator.
IntVector getMaxTransferOpStencilWidth (const tbox::Dimension &dim)
Get the max stencil width of all transfer operators.
void setMinTransferOpStencilWidth (const IntVector &min_value)
Set a minimum value on the value returned by getMaxTransferOpStencilWidth().
const IntVector & getMinTransferOpStencilWidth () const
bool hasOperators ()
void printClassData (std::ostream &os) const
Print class data representation.
Detailed Description
Class TransferOperatorRegistry is intended to serve as the registry for SAMRAI transfer operators. It will be a singleton object held by class hier::BaseGridGeometry.
This hier::TransferOperatorRegistry class provides a lookup mechanism to search for time interpolation and spatial coarsening/refining operators. That is, algorithms and applications that manage communication on an AMR hierarchy may query the hier::TransferOperatorRegistry object for operators that may be applied to specific variables.
Typically, the operators are assigned to the hier::TrnasferOperatorRegistry object in the constructor of the geometry object that defines the mesh coordinate system.
Note:
Additional operators may be added to a transfer geometry object at any time during program execution. However, each operator must be added BEFORE it is requested or an unrecoverable assertion will be thrown and the program will abort.
See the time interpolation,spatial coarsening, and spatial refinement operator base classes for more information about adding new operators for either new patch data types or new operators for pre-existing patch data types.
See also:
hier::BaseGridGeometry
hier::RefineOperator
hier::CoarsenOperator
hier::TimeInterpolateOperator
Constructor & Destructor Documentation
SAMRAI::hier::TransferOperatorRegistry::TransferOperatorRegistry (const tbox::Dimension & dim) [explicit]
Set the state of the hier::TransferOperatorRegistry members.
Parameters:
[in] dim
SAMRAI::hier::TransferOperatorRegistry::~TransferOperatorRegistry () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::hier::TransferOperatorRegistry::addCoarsenOperator (const char * var_type_name, const boost::shared_ptr< CoarsenOperator > & coarsen_op)
Add a concrete spatial coarsening operator.
Parameters:
[in] var_type_name The type name of the variable with which coarsen_op is associated
[in] coarsen_op The concrete coarsening operator to add to the lookup hash map.
References getMaxTransferOpStencilWidth(), and TBOX_WARNING.
void SAMRAI::hier::TransferOperatorRegistry::addRefineOperator (const char * var_type_name, const boost::shared_ptr< RefineOperator > & refine_op)
Add a concrete spatial refinement operator.
Parameters:
[in] var_type_name The type name of the variable with which refine_op is associated
[in] refine_op The concrete refinement operator to add to the lookup hash map.
References getMaxTransferOpStencilWidth(), and TBOX_WARNING.
void SAMRAI::hier::TransferOperatorRegistry::addTimeInterpolateOperator (const char * var_type_name, const boost::shared_ptr< TimeInterpolateOperator > & time_op)
Add a concrete time interpolation operator.
Parameters:
[in] var_type_name The type name of the variable with which time_op is associated
[in] time_op The concrete time interpolation operator to add to the lookup hash map.
boost::shared_ptr< CoarsenOperator > SAMRAI::hier::TransferOperatorRegistry::lookupCoarsenOperator (const boost::shared_ptr< Variable > & var, const std::string & op_name)
Lookup function for coarsening operator.
Extract the spatial coarsening operator matching the request for the given variable from the hash map. If the operator is found, a pointer to it will be returned. Otherwise, an unrecoverable error will result and the program will abort.
Parameters:
[in] var The Variable for which the corresponding coarsening operator should match.
[in] op_name The string identifier of the coarsening operator.
Precondition:
var
getMinTransferOpStencilWidth().getDim() == var->getDim()
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
boost::shared_ptr< RefineOperator > SAMRAI::hier::TransferOperatorRegistry::lookupRefineOperator (const boost::shared_ptr< Variable > & var, const std::string & op_name)
Lookup function for refinement operator.
Extract the spatial refinement operator matching the request for the given variable from the hash map. If the operator is found, a pointer to it will be returned. Otherwise, an unrecoverable error will result and the program will abort.
Parameters:
[in] var The Variable for which the corresponding refinement operator should match.
[in] op_name The string identifier of the refinement operator.
Precondition:
var
getMinTransferOpStencilWidth().getDim() == var->getDim()
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
boost::shared_ptr< TimeInterpolateOperator > SAMRAI::hier::TransferOperatorRegistry::lookupTimeInterpolateOperator (const boost::shared_ptr< Variable > & var, const std::string & op_name = "STD_LINEAR_TIME_INTERPOLATE")
Lookup function for time interpolation operator.
Extract the time interpolation operator matching the request for the given variable from the hash map. If the operator is found, a pointer to it will be returned. Otherwise, an unrecoverable error will result and the program will abort.
Parameters:
[in] var The Variable for which the corresponding time interpolation operator should match.
[in] op_name The string identifier of the time interpolation operator. Default: STD_LINEAR_TIME_INTERPOLATE
Precondition:
var
getMinTransferOpStencilWidth().getDim() == var->getDim()
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
IntVector SAMRAI::hier::TransferOperatorRegistry::getMaxTransferOpStencilWidth (const tbox::Dimension & dim)
Get the max stencil width of all transfer operators.
The max stencil width computed from all registered (constructed) transfer operators. This function is simply returns the max from the registered refine, coarsen and time-refine operators.
Returns:
The max stencil width computed from all registered operators.
See also:
hier::BaseGridGeometry::getMaxTransferOpStencilWidth().
hier::RefineOperator::getMaxRefineOpStencilWidth().
hier::CoarsenOperator::getMaxCoarsenOpStencilWidth().
References SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::CoarsenOperator::getMaxCoarsenOpStencilWidth(), SAMRAI::hier::RefineOperator::getMaxRefineOpStencilWidth(), and SAMRAI::hier::IntVector::max().
Referenced by addCoarsenOperator(), and addRefineOperator().
void SAMRAI::hier::TransferOperatorRegistry::setMinTransferOpStencilWidth (const IntVector & min_value) [inline]
Set a minimum value on the value returned by getMaxTransferOpStencilWidth().
This method allows users to specify a minimum value returned by getMaxTransferOpStencilWidth(). The default minimum is zero. This value can be used as a substitute for data that is not yet registered with the Geometry and therefore cannot be reflected in getMaxTransferOpStencilWidth().
Parameters:
[in] min_value The minimum value to set.
Precondition:
getMinTransferOpStencilWidth().getDim() == min_value.getDim()
References getMinTransferOpStencilWidth(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
const IntVector& SAMRAI::hier::TransferOperatorRegistry::getMinTransferOpStencilWidth () const [inline]
Referenced by setMinTransferOpStencilWidth().
bool SAMRAI::hier::TransferOperatorRegistry::hasOperators () [inline]
void SAMRAI::hier::TransferOperatorRegistry::printClassData (std::ostream & os) const
Print class data representation.
Parameters:
[in] os The std::ostream to print to.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/TransferOperatorRegistry.h
source/SAMRAI/hier/TransferOperatorRegistry.C