SAMRAI: SAMRAI::pdat::OuteredgeGeometry Class Reference
SAMRAI::pdat::OuteredgeGeometry Class Reference
#include <source/SAMRAI/pdat/OuteredgeGeometry.h>
Public Types
typedef EdgeOverlap Overlap
Public Member Functions
OuteredgeGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct an outeredge geometry object given an AMR index space box and ghost cell width.
virtual ~OuteredgeGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in edge-centered index space on the boundaries of the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a EdgeOverlap object based on the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this outeredge box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this outeredge box geometry object.
Static Public Member Functions
static hier::Box toOuteredgeBox (const hier::Box &box, tbox::Dimension::dir_t axis, tbox::Dimension::dir_t face_normal, int side)
Detailed Description
Class OuteredgeGeometry manages the mapping between the AMR index and the outeredge geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between outeredge box geometries and edge or outeredge box geometries for communication operations.
See header file for OuteredgeData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
EdgeGeometry
EdgeOverlap
Member Typedef Documentation
typedef EdgeOverlap SAMRAI::pdat::OuteredgeGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::OuteredgeGeometry::OuteredgeGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct an outeredge geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::OuteredgeGeometry::~OuteredgeGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
hier::Box SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox (const hier::Box & box, tbox::Dimension::dir_t axis, tbox::Dimension::dir_t face_normal, int side) [static]
Convert a given box in the standard cell-centered AMR index space to an outeredge geometry box for the specified axis, face normal, and lower/upper side. See OuteredgeData header file for a detailed description of an outeredge box.
Precondition:
(0 <= axis) && (axis < dim.getValue())
(0 <= face_normal) && (face_normal < dim.getValue())
(face_normal != axis)
(side == 0) || (side == 1)
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, SAMRAI::pdat::EdgeGeometry::toEdgeBox(), and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::pdat::OuteredgeData< TYPE >::getDataBox(), SAMRAI::pdat::OuteredgeData< TYPE >::getSizeOfData(), and SAMRAI::pdat::OuteredgeData< TYPE >::OuteredgeData().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OuteredgeGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in edge-centered index space on the boundaries of the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OuteredgeGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a EdgeOverlap object based on the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getOffset(), and SAMRAI::pdat::EdgeGeometry::toEdgeBox().
const hier::Box& SAMRAI::pdat::OuteredgeGeometry::getBox () const [inline]
Return the box for this outeredge box geometry object.
const hier::IntVector& SAMRAI::pdat::OuteredgeGeometry::getGhosts () const [inline]
Return the ghost cell width for this outeredge box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OuteredgeGeometry.h
source/SAMRAI/pdat/OuteredgeGeometry.C