SAMRAI: SAMRAI::tbox::StartupShutdownManager Class Reference
SAMRAI::tbox::StartupShutdownManager Class Reference
Class StartupShutdownManager is a utility for managing callbacks invoked at program and problem startup and completion.
#include <source/SAMRAI/tbox/StartupShutdownManager.h>
Classes
class AbstractHandler
Abstract base class for handler interface.
class Handler
Standard implementation of a Startup/Shutdown handler.
Static Public Member Functions
static void registerHandler (AbstractHandler *handler)
Register a handler with the StartupShutdownManager.
static void initialize ()
Invoke the registered initialization handlers.
static void startup ()
Invoke the registered startup handlers.
static void shutdown ()
Invoke the registered shutdown handlers.
static void finalize ()
Invoke the registered finalize handlers.
Static Public Attributes
static const unsigned char priorityArenaManager = 10
Priorities for standard SAMRAI classes.
static const unsigned char priorityReferenceCounter = 20
static const unsigned char priorityLogger = 25
static const unsigned char priorityListElements = 30
static const unsigned char priorityList = 30
static const unsigned char priorityInputManager = 40
static const unsigned char priorityRestartManager = 50
static const unsigned char priorityVariableDatabase = 60
static const unsigned char priorityStatistician = 70
static const unsigned char priorityBoundaryLookupTable = 80
static const unsigned char priorityHierarchyDataOpsManager = 90
static const unsigned char priorityTimerManger = 95
static const unsigned char priorityTimers = 98
static const unsigned char priorityVariables = 100
Detailed Description
Class StartupShutdownManager is a utility for managing callbacks invoked at program and problem startup and completion.
There are four steps in the lifecycle of managed objects.
An object is initialized once at the start of a run and a corresponding finalization is done once at the end of the run. These methods can be used to create and destroy static state that is independent of problem; e.g., when running multiple problems during a single program (i.e., main) execution.
The lifecycle also has a startup/shutdown step. This is invoked at least once per run but may be invoked multiple times if multiple SAMRAI problems are being run within a single execution of the main function. These methods should setup/teardown any state that is problem dependent.
In order to address dependencies between classes a Handler provides a priority (ordering) using the getPriority method. Ordering within the same priority is undefined.
The StartupShutdowManger::AbstractHandler defines the interface for the class that is registered. StartupShutdowManger::Handler is a helper class provided to simplify the use of the StartupShutdownManager. One may simply create a static instance of the Handler class, providing the constructor with callbacks to invoke and priority to use.
The StartupShutdownManger is normally managed by the SAMRAIManager class.
Member Function Documentation
void SAMRAI::tbox::StartupShutdownManager::registerHandler (AbstractHandler * handler) [static]
Register a handler with the StartupShutdownManager.
The AbstractHandler interface defines callback methods that will be invoked on SAMRAI initialize, startup and shutdown, and finalize.
The AbstractHandler also defines a priority (via getPriority) used to specify the order for startup and shutdown. Lower numbers are started first, higher last (0 first, 254 last). Order is inverted on shutdown (254 first, 0 last).
The priority is required since handlers may have dependencies.
Users are reserved priorities 127 to 254. Unless there is a known dependency on a SAMRAI shutdown handler, users should use these priorities.
Note: Currently it is allowed to register a handler in a phase if the handler does not have a callback for that phase. In other words if during the startup callback of a class A it causes another class B to register a handler it will work only if the handler for B does not have a startup method (hasStartup returns false). This restriction is in place to prevent one from registering a handler during startup that needs to be started. This should be avoided but for legacy reasons is being done in SAMRAI.
Parameters:
handler
References SAMRAI::tbox::StartupShutdownManager::AbstractHandler::getPriority(), SAMRAI::tbox::StartupShutdownManager::AbstractHandler::hasInitialize(), SAMRAI::tbox::StartupShutdownManager::AbstractHandler::hasShutdown(), SAMRAI::tbox::StartupShutdownManager::AbstractHandler::hasStartup(), and TBOX_ASSERT.
Referenced by SAMRAI::tbox::StartupShutdownManager::Handler::Handler().
void SAMRAI::tbox::StartupShutdownManager::initialize () [static]
Invoke the registered initialization handlers.
This should only be called once per program execution.
References TBOX_ASSERT.
void SAMRAI::tbox::StartupShutdownManager::startup () [static]
Invoke the registered startup handlers.
This routine must be called at SAMRAI problem startup. It may be called more than once per run if running multiple SAMRAI problems within the same execution of the main function.
References TBOX_ASSERT.
void SAMRAI::tbox::StartupShutdownManager::shutdown () [static]
Invoke the registered shutdown handlers.
This routine must be called at SAMRAI problem shutdown. It may be called more than once per run if running multiple SAMRAI problems within the same execution of the main function.
References TBOX_ASSERT.
void SAMRAI::tbox::StartupShutdownManager::finalize () [static]
Invoke the registered finalize handlers.
This should only be called once per program execution.
References TBOX_ASSERT.
Member Data Documentation
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityArenaManager = 10 [static]
Priorities for standard SAMRAI classes.
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityReferenceCounter = 20 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityLogger = 25 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityListElements = 30 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityList = 30 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityInputManager = 40 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityRestartManager = 50 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityVariableDatabase = 60 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityStatistician = 70 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityBoundaryLookupTable = 80 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityHierarchyDataOpsManager = 90 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityTimerManger = 95 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityTimers = 98 [static]
const unsigned char SAMRAI::tbox::StartupShutdownManager::priorityVariables = 100 [static]
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/StartupShutdownManager.h
source/SAMRAI/tbox/StartupShutdownManager.C