SAMRAI: SAMRAI::solv::SimpleCellRobinBcCoefs Class Reference
SAMRAI::solv::SimpleCellRobinBcCoefs Class Reference
A prefabricated Robin boundary condition coefficients with an interface like the old Poisson solvers.
#include <source/SAMRAI/solv/SimpleCellRobinBcCoefs.h>
Public Member Functions
SimpleCellRobinBcCoefs (const tbox::Dimension &dim, const std::string &object_name=std::string())
Constructor.
virtual ~SimpleCellRobinBcCoefs ()
Destructor.
void setHierarchy (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int ln_min=-1, const int ln_max=-1)
Set the hierarchy where boundary data associated with the hierarchy is found.
void setBoundaries (const std::string &boundary_type, const int fluxes=-1, const int flags=-1, int *bdry_types=0)
Specify the boundary conditions that are to be used at the physical domain boundary.
void cacheDirichletData (int dirichlet_data_id)
Cache data providing Dirichlet boundary values.
void restoreDirichletData (int dirichlet_data_id)
Copy cached Dirichlet data into ghost cells.
void setDiffusionCoefId (int diffusion_coef_id)
Set the patch data index of the diffusion coefficient used in Neumann boundary fluxes.
void setDiffusionCoefConstant (double diffusion_coef_value)
Set the value of the diffusion coefficient used in Neumann boundary fluxes to a constant.
const std::string & getObjectName () const
Get the name of this object.
void setBcCoefs (const boost::shared_ptr< pdat::ArrayData< double > > &acoef_data, const boost::shared_ptr< pdat::ArrayData< double > > &bcoef_data, const boost::shared_ptr< pdat::ArrayData< double > > &gcoef_data, const boost::shared_ptr< hier::Variable > &variable, const hier::Patch &patch, const hier::BoundaryBox &bdry_box, double fill_time=0.0) const
Function to fill arrays of Robin boundary condition coefficients at a patch boundary.
hier::IntVector numberOfExtensionsFillable () const
Detailed Description
A prefabricated Robin boundary condition coefficients with an interface like the old Poisson solvers.
This class is intended to make it easy for users of the old Poisson solver to adapt to the new solver by providing an interface similar to that of the old solver. Underneath, the boundary condition is converted to Robin bc coefficients used by the new solver.
This class refers to some grid-based outerside or ghost cell data touching patch outer sides when providing the Robin bc coefficients. In the most general case, it is unable to provide coefficients for patches outside the grid on which that data is provided. It is also unable to provide coefficients for boundary boxes that extend past the edge or corner of a patch. This may limit this class from being used when certain features of the Poisson solver is enabled.
Constructor & Destructor Documentation
SAMRAI::solv::SimpleCellRobinBcCoefs::SimpleCellRobinBcCoefs (const tbox::Dimension & dim, const std::string & object_name = std::string()) [explicit]
Constructor.
References SAMRAI::tbox::TimerManager::getManager().
SAMRAI::solv::SimpleCellRobinBcCoefs::~SimpleCellRobinBcCoefs () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs (const boost::shared_ptr< pdat::ArrayData< double > > & acoef_data, const boost::shared_ptr< pdat::ArrayData< double > > & bcoef_data, const boost::shared_ptr< pdat::ArrayData< double > > & gcoef_data, const boost::shared_ptr< hier::Variable > & variable, const hier::Patch & patch, const hier::BoundaryBox & bdry_box, double fill_time = 0.0) const [virtual]
Function to fill arrays of Robin boundary condition coefficients at a patch boundary.
This implementation of the virtual function RobinBcCoefStrategy::setBcCoefs() uses information specified by the call to setBoundaries() to determine the coefficients.
Parameters:
acoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box. If this is a null pointer, then the calling function is not interested in a, and you can disregard it.
bcoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box.
gcoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box.
variable variable to set the coefficients for.
patch patch requiring bc coefficients
bdry_box boundary box showing where on the boundary the coefficient data is needed.
fill_time solution time corresponding to filling, for use when coefficients are time-dependent.
Precondition:
(d_dim == patch.getDim()) && (d_dim == bdry_box.getDim())
!acoef_data || (d_dim == acoef_data->getDim())
!bcoef_data || (d_dim == bcoef_data->getDim())
!gcoef_data || (d_dim == gcoef_data->getDim())
Implements SAMRAI::solv::RobinBcCoefStrategy.
References SAMRAI::pdat::OuterfaceData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::BoundaryBox::getBox(), SAMRAI::hier::Patch::getBox(), SAMRAI::hier::Patch::getGlobalId(), SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::hier::Patch::getPatchData(), SAMRAI::hier::Patch::getPatchGeometry(), SAMRAI::hier::Patch::getPatchLevelNumber(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Patch::inHierarchy(), NULL_USE, SAMRAI::tbox::plog, TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, TBOX_ASSERT_DIM_OBJDIM_EQUALITY2, and TBOX_ERROR.
hier::IntVector SAMRAI::solv::SimpleCellRobinBcCoefs::numberOfExtensionsFillable () const [virtual]
Implements SAMRAI::solv::RobinBcCoefStrategy.
References SAMRAI::hier::IntVector::getZero().
void SAMRAI::solv::SimpleCellRobinBcCoefs::setHierarchy (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int ln_min = -1, const int ln_max = -1)
Set the hierarchy where boundary data associated with the hierarchy is found.
This class requires you to specify some grid data associated with a hierarchy, such as the Dirichlet boundary values, the flux or the Dirichlet/Neumann flag. That hierarchy and the range of relevant patch levels is specified by calling this function.
Precondition:
hierarchy
d_dim == hierarchy->getDim()
Postcondition:
(d_ln_min >= 0) && (d_ln_max >= 0) && (d_ln_min <= d_ln_max)
References TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ERROR.
Referenced by SAMRAI::solv::CellPoissonFACSolver::initializeSolverState().
void SAMRAI::solv::SimpleCellRobinBcCoefs::setBoundaries (const std::string & boundary_type, const int fluxes = -1, const int flags = -1, int * bdry_types = 0)
Specify the boundary conditions that are to be used at the physical domain boundary.
The boundary conditions specified as the std::string argument "boundary_type." The boundary type argument can be "Dirichlet", "Neumann", or "Mixed".
If using Dirichlet boundary conditions, then before the solver is called, the storage for the unknown u must have a box_level of ghost cells at least one cell wide that includes the Dirichlet boundary values.
If using Neumann boundary conditions, then before the solver is called, the outerface boundary flux data must be set for the Neumann conditions. The fluxes argument gives the patch data index of this flux data.
The mixed boundary type is for a mixture of Dirichlet and Neumann boundary conditions are used at the physical domain boundary. The fluxes argument gives the patch data index of the outerface data that specifies the flux data for the Neumann conditions. The flags array is an outerface data array of integer flags that specifies whether Dirichlet (flag == zero) or Neumann (flag == one) conditions are to be used at a particular cell boundary face. Note that the flag data must be set before the matrix entries can be computed and the flux data must be set before the solver is called. The bdry_types argument can be used if the boundary conditions are mixed but one or more of the faces of the physical boundary are entirely either Dirichlet or Neumann boundaries. The bdry_types argument should be an array of 2*DIM integers, specifying the boundary conditions on each side of the physical domain. It should be ordered {x_lo, x_hi, y_lo, y_hi, z_lo, z_hi}, with the values for each face being 0 for Dirichlet conditions, 1 for Neumann conditions, and 2 for mixed boundary conditions. The bdry_type argument is never required, but if used it can sometimes make the PoissonHYPRESolver class more efficient.
Precondition:
(boundary_type != "Neumann") || (fluxes >= 0)
(boundary_type != "Mixed") || ((fluxes >= 0) && (flags >= 0))
(boundary_type == "Dirichlet") || (boundary_type != "Neumann") || (boundary_type != "Mixed")
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ERROR.
Referenced by SAMRAI::solv::CellPoissonHypreSolver::setBoundaries(), and SAMRAI::solv::CellPoissonFACSolver::setBoundaries().
void SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData (int dirichlet_data_id)
Cache data providing Dirichlet boundary values.
This function makes a private copy of the relevant ghost cell data that it later uses provide the coefficient g on Dirichlet boundaries. The index must correspond to cell-centered double data with non-zero ghost width.
Functions setHierarchy() and setBoundaries() should be called before this one. This function should be called each time the hierarchy or Dirichlet data changes.
Parameters:
dirichlet_data_id patch data id of the source cell data for copy.
Precondition:
d_hierarchy
References SAMRAI::hier::PatchLevel::begin(), BOOST_CAST, SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::PatchLevel::end(), SAMRAI::hier::Patch::getGlobalId(), SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::hier::Patch::getPatchData(), SAMRAI::hier::Patch::getPatchGeometry(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::solv::CellPoissonFACSolver::solveSystem().
void SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData (int dirichlet_data_id)
Copy cached Dirichlet data into ghost cells.
Reverse action of cacheDirichletData by copying cached data back into the ghost cells.
The cached data is not dallocated.
Parameters:
dirichlet_data_id patch data id of the destination cell data for copy.
Precondition:
!d_dirichlet_data_pos.empty()
References SAMRAI::hier::PatchLevel::begin(), BOOST_CAST, SAMRAI::hier::PatchLevel::end(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::Patch::getGlobalId(), SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::hier::Patch::getPatchData(), SAMRAI::hier::Patch::getPatchGeometry(), SAMRAI::hier::Box::shift(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::solv::CellPoissonFACSolver::solveSystem().
void SAMRAI::solv::SimpleCellRobinBcCoefs::setDiffusionCoefId (int diffusion_coef_id) [inline]
Set the patch data index of the diffusion coefficient used in Neumann boundary fluxes.
The diffusion coefficient, along with the prescribed flux, is used to set the gradient of the solution normal to the boundary. By default, the diffusion coefficient is assumed to be 1. If used, the diffusion coefficient data id must be set before asking for the coefficient g, which depends on it. The index must correspond to side-centered double data.
This function overrides the effect of setDiffusionCoefConstant().
Referenced by SAMRAI::solv::CellPoissonFACSolver::initializeSolverState().
void SAMRAI::solv::SimpleCellRobinBcCoefs::setDiffusionCoefConstant (double diffusion_coef_value) [inline]
Set the value of the diffusion coefficient used in Neumann boundary fluxes to a constant.
This function is similar to setDiffusionCoefId() but is used when the diffusion coefficient is a constant.
This function overrides the effect of setDiffusionCoefId().
Referenced by SAMRAI::solv::CellPoissonFACSolver::initializeSolverState().
const std::string& SAMRAI::solv::SimpleCellRobinBcCoefs::getObjectName () const [inline]
Get the name of this object.
Returns:
The name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/solv/SimpleCellRobinBcCoefs.h
source/SAMRAI/solv/SimpleCellRobinBcCoefs.C