SAMRAI: SAMRAI::tbox::SiloDatabase Class Reference
SAMRAI::tbox::SiloDatabase Class Reference
#include <source/SAMRAI/tbox/SiloDatabase.h>
Public Member Functions
SiloDatabase (const std::string &name)
SiloDatabase (const std::string &name, DBfile *file, const std::string &directory, const bool create_in_file)
virtual ~SiloDatabase ()
virtual bool keyExists (const std::string &key)
virtual std::vector< std::string > getAllKeys ()
virtual enum DataType getArrayType (const std::string &key)
Return the type of data associated with the key.
virtual size_t getArraySize (const std::string &key)
virtual bool isDatabase (const std::string &key)
virtual boost::shared_ptr
< Database > putDatabase (const std::string &key)
virtual boost::shared_ptr
< Database > getDatabase (const std::string &key)
virtual bool isBool (const std::string &key)
virtual void putBoolArray (const std::string &key, const bool *const data, const size_t nelements)
virtual std::vector< bool > getBoolVector (const std::string &key)
virtual bool isDatabaseBox (const std::string &key)
virtual void putDatabaseBoxArray (const std::string &key, const DatabaseBox *const data, const size_t nelements)
virtual std::vector< DatabaseBox > getDatabaseBoxVector (const std::string &key)
virtual bool isChar (const std::string &key)
virtual void putCharArray (const std::string &key, const char *const data, const size_t nelements)
virtual std::vector< char > getCharVector (const std::string &key)
virtual bool isComplex (const std::string &key)
virtual void putComplexArray (const std::string &key, const dcomplex *const data, const size_t nelements)
virtual std::vector< dcomplex > getComplexVector (const std::string &key)
virtual bool isDouble (const std::string &key)
virtual void putDoubleArray (const std::string &key, const double *const data, const size_t nelements)
virtual std::vector< double > getDoubleVector (const std::string &key)
virtual bool isFloat (const std::string &key)
virtual void putFloatArray (const std::string &key, const float *const data, const size_t nelements)
virtual std::vector< float > getFloatVector (const std::string &key)
virtual bool isInteger (const std::string &key)
virtual void putIntegerArray (const std::string &key, const int *const data, const size_t nelements)
virtual std::vector< int > getIntegerVector (const std::string &key)
virtual bool isString (const std::string &key)
virtual void putStringArray (const std::string &key, const std::string *const data, const size_t nelements)
virtual std::vector< std::string > getStringVector (const std::string &key)
virtual std::string getName ()
Returns the name of this database.
virtual void printClassData (std::ostream &os=pout)
virtual bool create (const std::string &name)
virtual bool open (const std::string &name, const bool read_write_mode=false)
virtual bool attachToFile (DBfile *file, const std::string &directory)
Attach the Database to an existing Silo file.
virtual bool close ()
bool hasDirectory ()
Detailed Description
Class SiloDatabase implements the interface of the Database class to store data in the Silo (Hierarchical Data Format) data format.
It is assumed that all processors will access the database in the same manner. Error reporting is done using the SAMRAI error reporting macros.
See also:
Database
Constructor & Destructor Documentation
SAMRAI::tbox::SiloDatabase::SiloDatabase (const std::string & name) [explicit]
The Silo database constructor creates an empty database with the specified name. By default the database will not be associated with a file until it is mounted, using the mount() member function.
Precondition:
!name.empty
References TBOX_ASSERT.
SAMRAI::tbox::SiloDatabase::SiloDatabase (const std::string & name, DBfile * file, const std::string & directory, const bool create_in_file)
Constructor used to create sub-databases.
Precondition:
!name.empty()
file != 0
!directory.empty()
References TBOX_ASSERT, and TBOX_ERROR.
SAMRAI::tbox::SiloDatabase::~SiloDatabase () [virtual]
The database destructor closes the Silo group or data file.
References close().
Member Function Documentation
bool SAMRAI::tbox::SiloDatabase::keyExists (const std::string & key) [virtual]
Return true if the specified key exists in the database and false otherwise.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
std::vector< std::string > SAMRAI::tbox::SiloDatabase::getAllKeys () [virtual]
Return a vector of all keys in the current database. Note that no keys from subdatabases contained in the current database will appear in the array. To get the keys of any other database, you must call this routine for that database.
Precondition:
hasDirectory()
Implements SAMRAI::tbox::Database.
References hasDirectory(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printClassData().
enum Database::DataType SAMRAI::tbox::SiloDatabase::getArrayType (const std::string & key) [virtual]
Return the type of data associated with the key.
If the key does not exist, then INVALID is returned
Parameters:
key Key name in database.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References SAMRAI::tbox::Database::SAMRAI_BOOL, SAMRAI::tbox::Database::SAMRAI_BOX, SAMRAI::tbox::Database::SAMRAI_CHAR, SAMRAI::tbox::Database::SAMRAI_COMPLEX, SAMRAI::tbox::Database::SAMRAI_DATABASE, SAMRAI::tbox::Database::SAMRAI_DOUBLE, SAMRAI::tbox::Database::SAMRAI_FLOAT, SAMRAI::tbox::Database::SAMRAI_INT, SAMRAI::tbox::Database::SAMRAI_INVALID, SAMRAI::tbox::Database::SAMRAI_STRING, and TBOX_ASSERT.
Referenced by printClassData().
size_t SAMRAI::tbox::SiloDatabase::getArraySize (const std::string & key) [virtual]
Return the size of the array associated with the key. If the key does not exist, then zero is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
bool SAMRAI::tbox::SiloDatabase::isDatabase (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a database entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getDatabase().
boost::shared_ptr< Database > SAMRAI::tbox::SiloDatabase::putDatabase (const std::string & key) [virtual]
Create a new database with the specified key name and return a pointer to it. A new group with the key name is also created in the data file.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
boost::shared_ptr< Database > SAMRAI::tbox::SiloDatabase::getDatabase (const std::string & key) [virtual]
Get the database with the specified key name. If the specified key does not represent a database entry in the database, then an error message is printed and the program exits.
Precondition:
!key.empty()
isDatabase(key)
Implements SAMRAI::tbox::Database.
References isDatabase(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::isBool (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a boolean entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getBoolVector().
void SAMRAI::tbox::SiloDatabase::putBoolArray (const std::string & key, const bool *const data, const size_t nelements) [virtual]
Create a boolean array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
std::vector< bool > SAMRAI::tbox::SiloDatabase::getBoolVector (const std::string & key) [virtual]
Get a boolean entry from the database with the specified key name. If the specified key does not exist in the database or is not a boolean vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
isBool(key)
Implements SAMRAI::tbox::Database.
References isBool(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::isDatabaseBox (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a box entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
void SAMRAI::tbox::SiloDatabase::putDatabaseBoxArray (const std::string & key, const DatabaseBox *const data, const size_t nelements) [virtual]
Create a box array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References SAMRAI::tbox::DatabaseBox::d_data, SAMRAI::tbox::DatabaseBox_POD::d_dimension, SAMRAI::tbox::DatabaseBox_POD::d_hi, SAMRAI::tbox::DatabaseBox_POD::d_lo, TBOX_ASSERT, and TBOX_ERROR.
std::vector< DatabaseBox > SAMRAI::tbox::SiloDatabase::getDatabaseBoxVector (const std::string & key) [virtual]
Get a box entry from the database with the specified key name. If the specified key does not exist in the database, then an error message is printed and the program exits.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
bool SAMRAI::tbox::SiloDatabase::isChar (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a char entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getCharVector().
void SAMRAI::tbox::SiloDatabase::putCharArray (const std::string & key, const char *const data, const size_t nelements) [virtual]
Create a character array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
std::vector< char > SAMRAI::tbox::SiloDatabase::getCharVector (const std::string & key) [virtual]
Get a character entry from the database with the specified key name. If the specified key does not exist in the database, then an error message is printed and the program exits.
Precondition:
!key.empty()
isChar(key)
Implements SAMRAI::tbox::Database.
References isChar(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::isComplex (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a complex entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getComplexVector().
void SAMRAI::tbox::SiloDatabase::putComplexArray (const std::string & key, const dcomplex *const data, const size_t nelements) [virtual]
Create a complex array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT, and TBOX_ERROR.
std::vector< dcomplex > SAMRAI::tbox::SiloDatabase::getComplexVector (const std::string & key) [virtual]
Get a complex entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isComplex(key)
Implements SAMRAI::tbox::Database.
References isComplex(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::isDouble (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a double entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getDoubleVector().
void SAMRAI::tbox::SiloDatabase::putDoubleArray (const std::string & key, const double *const data, const size_t nelements) [virtual]
Create a double array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
std::vector< double > SAMRAI::tbox::SiloDatabase::getDoubleVector (const std::string & key) [virtual]
Get a double entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isDouble(key)
Implements SAMRAI::tbox::Database.
References isDouble(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::isFloat (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a float entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getFloatVector().
void SAMRAI::tbox::SiloDatabase::putFloatArray (const std::string & key, const float *const data, const size_t nelements) [virtual]
Create a float array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
std::vector< float > SAMRAI::tbox::SiloDatabase::getFloatVector (const std::string & key) [virtual]
Get a float entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isFloat(key)
Implements SAMRAI::tbox::Database.
References isFloat(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::isInteger (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents an integer entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getIntegerVector().
void SAMRAI::tbox::SiloDatabase::putIntegerArray (const std::string & key, const int *const data, const size_t nelements) [virtual]
Create an integer array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
std::vector< int > SAMRAI::tbox::SiloDatabase::getIntegerVector (const std::string & key) [virtual]
Get an integer entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isInteger(key)
Implements SAMRAI::tbox::Database.
References isInteger(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::isString (const std::string & key) [virtual]
Return true or false depending on whether the specified key represents a string entry. If the key does not exist, then false is returned.
Precondition:
!key.empty()
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by getStringVector().
void SAMRAI::tbox::SiloDatabase::putStringArray (const std::string & key, const std::string *const data, const size_t nelements) [virtual]
Create a string array entry in the database with the specified key name.
Precondition:
!key.empty()
data != 0
Implements SAMRAI::tbox::Database.
References SAMRAI::tbox::Utilities::sizetToString(), TBOX_ASSERT, and TBOX_ERROR.
std::vector< std::string > SAMRAI::tbox::SiloDatabase::getStringVector (const std::string & key) [virtual]
Get a string entry from the database with the specified key name. If the specified key does not exist in the database then an error message is printed and the program exits.
Precondition:
!key.empty()
isString(key)
Implements SAMRAI::tbox::Database.
References isString(), TBOX_ASSERT, and TBOX_ERROR.
std::string SAMRAI::tbox::SiloDatabase::getName (void) [virtual]
Returns the name of this database.
The name for the root of the database is the name supplied when creating it. Names for nested databases are the keyname of the database.
Implements SAMRAI::tbox::Database.
void SAMRAI::tbox::SiloDatabase::printClassData (std::ostream & os = pout) [virtual]
Print contents of current database to the specified output stream. If no output stream is specified, then data is written to stream pout. Note that none of the subdatabases contained in the current database will have their contents printed. To view the contents of any other database, you must call this print routine for that database.
Implements SAMRAI::tbox::Database.
References getAllKeys(), getArrayType(), SAMRAI::tbox::Database::SAMRAI_BOOL, SAMRAI::tbox::Database::SAMRAI_BOX, SAMRAI::tbox::Database::SAMRAI_CHAR, SAMRAI::tbox::Database::SAMRAI_COMPLEX, SAMRAI::tbox::Database::SAMRAI_DATABASE, SAMRAI::tbox::Database::SAMRAI_DOUBLE, SAMRAI::tbox::Database::SAMRAI_FLOAT, SAMRAI::tbox::Database::SAMRAI_INT, SAMRAI::tbox::Database::SAMRAI_INVALID, and SAMRAI::tbox::Database::SAMRAI_STRING.
bool SAMRAI::tbox::SiloDatabase::create (const std::string & name) [virtual]
Create a new database file.
Returns true if successful.
Parameters:
name name of database. Normally a filename.
Precondition:
!name.empty()
Implements SAMRAI::tbox::Database.
References close(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::open (const std::string & name, const bool read_write_mode = false) [virtual]
Open an existing database file.
Returns true if successful.
Parameters:
name name of database. Normally a filename.
read_write_mode Open the database in read-write mode instead of read-only mode. NOTE: This class currently does not support read-only mode, so this flag must be true.
Precondition:
!name.empty()
Implements SAMRAI::tbox::Database.
References close(), TBOX_ASSERT, and TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::attachToFile (DBfile * file, const std::string & directory) [virtual]
Attach the Database to an existing Silo file.
If an application has an existing Silo file used for restart this method can be used to write SAMRAI restart information to the existing file instead of SAMRAI creating a distinct file.
SAMRAI data will be written to the directory specified within the Silo file.
Returns true if attach was successful.
Precondition:
file != 0
References TBOX_ERROR.
bool SAMRAI::tbox::SiloDatabase::close () [virtual]
Close the database.
Returns true if successful.
If the database is currently open then close it. This should flush all data to the file (if the database is on disk).
Implements SAMRAI::tbox::Database.
References TBOX_ASSERT.
Referenced by create(), open(), and ~SiloDatabase().
bool SAMRAI::tbox::SiloDatabase::hasDirectory () [inline]
Referenced by getAllKeys().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/SiloDatabase.h
source/SAMRAI/tbox/SiloDatabase.C