SAMRAI: SAMRAI::hier::MappingConnectorAlgorithm Class Reference
SAMRAI::hier::MappingConnectorAlgorithm Class Reference
Algorithms for using MappingConnectors representing changes to a BoxLevel.
#include <source/SAMRAI/hier/MappingConnectorAlgorithm.h>
Public Member Functions
MappingConnectorAlgorithm ()
Constructor.
virtual ~MappingConnectorAlgorithm ()
Deallocate internal data.
void setBarrierBeforeCommunication (bool do_barrier)
Set whether to barrier before potential major communication.
void setSanityCheckMethodPreconditions (bool do_check)
Set whether to run expensive sanity checks on input parameters when at the beginning of certain methods.
void setSanityCheckMethodPostconditions (bool do_check)
Set whether to run expensive sanity checks on outputs before returning from certain methods.
void setSAMRAI_MPI (const tbox::SAMRAI_MPI &mpi, bool make_duplicate=true)
Set the SAMRAI_MPI to use.
void modify (Connector &anchor_to_mapped, const MappingConnector &old_to_new, BoxLevel *mutable_new=0, BoxLevel *mutable_old=0) const
Most general version for modifying Connectors using MappingConnectors. Modification is the changing of existing Connectors when boxes in a BoxLevel changes according to specified MappingConnectors.
const std::string getObjectName () const
Get the name of this object.
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
Detailed Description
Algorithms for using MappingConnectors representing changes to a BoxLevel.
MappingConnectorAlgorithm objects check and apply mappings.
Constructor & Destructor Documentation
SAMRAI::hier::MappingConnectorAlgorithm::MappingConnectorAlgorithm ()
Constructor.
The default constructor creates an uninitialized object in distributed state.
References setTimerPrefix().
SAMRAI::hier::MappingConnectorAlgorithm::~MappingConnectorAlgorithm () [virtual]
Deallocate internal data.
References SAMRAI::tbox::SAMRAI_MPI::freeCommunicator().
Member Function Documentation
void SAMRAI::hier::MappingConnectorAlgorithm::setBarrierBeforeCommunication (bool do_barrier) [inline]
Set whether to barrier before potential major communication.
This developer feature makes sure all processes start major operations at the same time so that timers do not include the time waiting for slower processes to get to the starting point.
Parameters:
[in] do_barrier
void SAMRAI::hier::MappingConnectorAlgorithm::setSanityCheckMethodPreconditions (bool do_check) [inline]
Set whether to run expensive sanity checks on input parameters when at the beginning of certain methods.
The checks are expensive and meant mainly for debugging.
Parameters:
[in] do_check
void SAMRAI::hier::MappingConnectorAlgorithm::setSanityCheckMethodPostconditions (bool do_check) [inline]
Set whether to run expensive sanity checks on outputs before returning from certain methods.
The checks are expensive and meant mainly for debugging.
Parameters:
[in] do_check
void SAMRAI::hier::MappingConnectorAlgorithm::setSAMRAI_MPI (const tbox::SAMRAI_MPI & mpi, bool make_duplicate = true)
Set the SAMRAI_MPI to use.
If set, communication will use the specified SAMRAI_MPI instead of the SAMRAI_MPI from BoxLevels. This protects communication operations from accidentally interacting with unrelated communications, but it limits operations to work only with metadata objects with comptatible (congruent) SAMRAI_MPI objects.
If make_duplicate is true, the specified SAMRAI_MPI will be duplicated for exclusise use. The duplicate will be freed upon object destruction.
References SAMRAI::tbox::SAMRAI_MPI::dupCommunicator(), and SAMRAI::tbox::SAMRAI_MPI::freeCommunicator().
Referenced by SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), SAMRAI::mesh::TreeLoadBalancer::setSAMRAI_MPI(), and SAMRAI::mesh::CascadePartitioner::setSAMRAI_MPI().
void SAMRAI::hier::MappingConnectorAlgorithm::modify (Connector & anchor_to_mapped, const MappingConnector & old_to_new, BoxLevel * mutable_new = 0, BoxLevel * mutable_old = 0) const
Most general version for modifying Connectors using MappingConnectors. Modification is the changing of existing Connectors when boxes in a BoxLevel changes according to specified MappingConnectors.
The change is represented by a the mapper old_to_new and its transpose, new_to_old. The Connectors to be modified are anchor_to_mapped and its transpose mapped_to_anchor, which on input, go between an anchor (not mapped) BoxLevel and the old BoxLevel. On output, these Connectors will go from the anchor box_level to the new box_level.
 Input:
                                    (anchor)
                                   ^ /
                                  / /
              mapped_to_anchor-> / /
                                / / <--anchor_to_mapped
                               / v
 mapped box_level:           (old) ---------> (new)
                                   <---------
 Output:
                                    (anchor)
                                          \ ^
                                           \ \
                                            \ \ <-mapped_to_anchor
                        anchor_to_mapped --> \ \
                                              v \
                                              (new)
The BoxLevels before and after the mapping are represented by the base and head of the mapping. No BoxLevel is modified, other than the "mutable" BoxLevels in the argument.
An important constraint in the old_to_new MappingConnectors is that this method cannot handle multiple maps at once. For example, it cannot map box J to box K and at the same time map box I to box J. Box J in the old box_level and box J on the new box_level are considered entirely different boxes.
After modifying, the output Connectors that had referenced old BoxLevels will be reset to reference the new BoxLevel. This is the end of the modify operation.
The following "in-place" modification is provided for users' convenience. Often times, the "new" level is a temporary object and users often reset output equivalent to:
old = new
reset Connectors using old in place of new.
The modify methods support these optional steps as follows: If mutable versions of some BoxLevel are given, the output Connectors can be reset to reference these versions instead.
If mutable_new points to the old BoxLevel and mutable_old points to the new, then do an in-place switch as follows:
Swap the mutable_old and mutable_new BoxLevels.
Use mutable_old (which actually the new BoxLevel after the swap) as the mapped BoxLevel in the output Connectors. Otherwise:
If mutable_new is non-NULL, set it equal to new and use it as the mapped BoxLevel in the output Connectors.
If mutable_old is non-NULL, set it equal to the old BoxLevel.
Parameters:
[in,out] anchor_to_mapped Connector to be modified. On input, this points to the BoxLevel being mapped.
[in] old_to_new Mapping from the old BoxLevel to the new BoxLevel. The width of old-->new should indicate the maximum amount of box growth caused by the change. A value of zero means no growth.
[in,out] mutable_new See comments.
[in,out] mutable_old See comments.
Precondition:
(!old_to_new.hasTranspose() || (&old_to_new.getBase() == &old_to_new.getTranspose().getHead())) && (&old_to_new.getBase() == &anchor_to_mapped.getHead()) && (&old_to_new.getBase() == &mapped_to_anchor.getBase())
&anchor_to_mapped.getBase() == &mapped_to_anchor.getHead()
(!old_to_new.hasTranspose() || (&old_to_new.getHead() == &old_to_new.getTranspose().getBase()))
anchor_to_mapped.isTransposeOf(mapped_to_anchor)
(!old_to_new.hasTranspose() || (old_to_new.getTranspose().isTransposeOf(old_to_new)))
anchor_to_mapped.getParallelState() == BoxLevel::DISTRIBUTED
References SAMRAI::hier::Connector::assertTransposeCorrectness(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::createLocalTranspose(), SAMRAI::hier::BoxLevel::DISTRIBUTED, SAMRAI::hier::Connector::format(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Connector::getParallelState(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::tbox::SAMRAI_MPI::hasNullCommunicator(), SAMRAI::hier::Connector::hasTranspose(), SAMRAI::tbox::SAMRAI_MPI::isCongruentWith(), SAMRAI::hier::Connector::isTransposeOf(), SAMRAI::tbox::plog, TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
const std::string SAMRAI::hier::MappingConnectorAlgorithm::getObjectName () const [inline]
Get the name of this object.
void SAMRAI::hier::MappingConnectorAlgorithm::setTimerPrefix (const std::string & timer_prefix)
Setup names of timers.
By default, timers are named "hier::MappingConnectorAlgorithm::*", where the third field is the specific steps performed by the MappingConnectorAlgorithm. You can override the first two fields with this method. Conforming to the timer naming convention, timer_prefix should have the form "*::*".
Referenced by SAMRAI::mesh::CascadePartitioner::CascadePartitioner(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), MappingConnectorAlgorithm(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::mesh::TileClustering::TileClustering(), and SAMRAI::mesh::TreeLoadBalancer::TreeLoadBalancer().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/MappingConnectorAlgorithm.h
source/SAMRAI/hier/MappingConnectorAlgorithm.C