SAMRAI: SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE > Class Template Reference
SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE > Class Template Reference
#include <source/SAMRAI/math/ArrayDataMiscellaneousOpsReal.h>
Public Member Functions
ArrayDataMiscellaneousOpsReal ()
~ArrayDataMiscellaneousOpsReal ()
int computeConstrProdPosWithControlVolume (const pdat::ArrayData< TYPE > &data1, const pdat::ArrayData< TYPE > &data2, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
int computeConstrProdPos (const pdat::ArrayData< TYPE > &data1, const pdat::ArrayData< TYPE > &data2, const hier::Box &box) const
void compareToScalarWithControlVolume (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src, const TYPE &alpha, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
void compareToScalar (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src, const TYPE &alpha, const hier::Box &box) const
int testReciprocalWithControlVolume (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
int testReciprocal (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src, const hier::Box &box) const
TYPE maxPointwiseDivide (const pdat::ArrayData< TYPE > &numer, const pdat::ArrayData< TYPE > &denom, const hier::Box &box) const
Compute max of "conditional" quotients of two arrays.
TYPE minPointwiseDivide (const pdat::ArrayData< TYPE > &numer, const pdat::ArrayData< TYPE > &denom, const hier::Box &box) const
Compute min of quotients of two arrays.
Detailed Description
template<class TYPE>
class SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >
Class ArrayDataMiscellaneousOpsReal provides various operations that may be applied to arrays of real (double and float) numerical data values maintained using pdat::ArrayData<TYPE> objects. These operations are sufficiently different from basic arithmetic and norm operations that we chose to implement them in a separate class. However, as in the case of the more common operations, the intent of this class is to provide a single implementation of the operations as they are needed by objects that manipulate standard array-based patch data types (i.e., cell-centered, face-centered, node-centered). Each operation is implemented in two different ways. The choice of operation is based on whether control volume information is to be used to weight the contribution of each data entry to the calculation. The use of control volumes is important when these operations are used in vector kernels where the data resides over multiple levels of spatial resolution in an AMR hierarchy. The actual index region on which each operation occurs is the intersection of this box and the boxes of all the pdat::ArrayData<TYPE> objects involved.
Since these operations are used only by the vector kernels for the KINSOL and CVODE solver packages at this time, they are intended to be instantiated for the standard built-in types double and float (since those solvers only treat double and float data). To extend this class to other data types or to include other operations, the member functions must be specialized or the new operations must be added.
See also:
pdat::ArrayData
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::ArrayDataMiscellaneousOpsReal () [inline]
Empty constructor and destructor.
template<class TYPE > SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::~ArrayDataMiscellaneousOpsReal () [inline]
Member Function Documentation
template<class TYPE > int SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume (const pdat::ArrayData< TYPE > & data1, const pdat::ArrayData< TYPE > & data2, const pdat::ArrayData< double > & cvol, const hier::Box & box) const [inline]
Return 1 if and , for any in the index region, where . Otherwise return 0.
Precondition:
(data1.getDim() == data2.getDim()) && (data1.getDim() == cvol.getDim()) && (data1.getDim() == box.getDim())
data1.getDepth() == data2.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
template<class TYPE > int SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos (const pdat::ArrayData< TYPE > & data1, const pdat::ArrayData< TYPE > & data2, const hier::Box & box) const [inline]
Return 1 if and , for any in the index region. Otherwise return 0.
Precondition:
(data1.getDim() == data2.getDim()) && (data1.getDim() == box.getDim())
data1.getDepth() == data2.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
template<class TYPE > void SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src, const TYPE & alpha, const pdat::ArrayData< double > & cvol, const hier::Box & box) const [inline]
Wherever in the index region, set if , and otherwise.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == cvol.getDim()) && (dst.getDim() == box.getDim())
dst.getDepth() == src.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
template<class TYPE > void SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src, const TYPE & alpha, const hier::Box & box) const [inline]
Set if , and otherwise.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == box.getDim())
dst.getDepth() == src.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
template<class TYPE > int SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src, const pdat::ArrayData< double > & cvol, const hier::Box & box) const [inline]
Wherever in the index region, set if , and otherwise. If anywhere, 0 is the return value. Otherwise 1 is returned.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == cvol.getDim()) && (dst.getDim() == box.getDim())
dst.getDepth() == src.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
template<class TYPE > int SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src, const hier::Box & box) const [inline]
Set if , and otherwise. If anywhere, 0 is the return value. Otherwise 1 is returned.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == box.getDim())
dst.getDepth() == src.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
template<class TYPE > TYPE SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide (const pdat::ArrayData< TYPE > & numer, const pdat::ArrayData< TYPE > & denom, const hier::Box & box) const [inline]
Compute max of "conditional" quotients of two arrays.
Return the maximum of pointwise "conditional" quotients of the numerator and denominator.
The "conditional" quotient is defined as |numerator/denominator| where the denominator is nonzero. Otherwise, it is defined as |numerator|.
Note: This method is currently intended to support the PETSc-2.1.6 vector wrapper only. Please do not use it!
Precondition:
(numer.getDim() == denom.getDim()) && (numer.getDim() == box.getDim())
numer.getDepth() == denom.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
template<class TYPE > TYPE SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide (const pdat::ArrayData< TYPE > & numer, const pdat::ArrayData< TYPE > & denom, const hier::Box & box) const [inline]
Compute min of quotients of two arrays.
Return the minimum of pointwise quotients of the numerator and denominator.
The quotient is defined as (numerator/denominator) where the denominator is nonzero. When the denominator is zero, the entry is skipped. If the denominator is always zero, the value of tbox::IEEE::getDBL_MAX() is returned (see SAMRAI::tbox::IEEE).
Note: This method is currently intended to support the SUNDIALS vector wrapper only. Please do not use it!
Precondition:
(numer.getDim() == denom.getDim()) && (numer.getDim() == box.getDim())
numer.getDepth() == denom.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
The documentation for this class was generated from the following files:
source/SAMRAI/math/ArrayDataMiscellaneousOpsReal.h
source/SAMRAI/math/ArrayDataMiscellaneousOpsReal.C