SAMRAI: SAMRAI::pdat::CellData< TYPE > Class Template Reference
SAMRAI::pdat::CellData< TYPE > Class Template Reference
Class CellData<TYPE> provides an implementation for data defined at cell centers on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a cell data object represents data of some template TYPE and depth at the centers of the cells in the box. Here, depth indicates the number of data values at each cell index location. The CellGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and cell-centered data.
#include <source/SAMRAI/pdat/CellData.h>
Public Types
typedef CellIterator iterator
Public Member Functions
CellData (const hier::Box &box, int depth, const hier::IntVector &ghosts)
The constructor for an cell data object.
virtual ~CellData ()
The virtual destructor for a cell data object.
int getDepth () const
Return the depth (e.g., the number of components in each spatial location) of the array.
TYPE * getPointer (int depth=0)
Get a pointer to the beginning of a depth component of the cell centered array.
const TYPE * getPointer (int depth=0) const
Get a const pointer to the beginning of a depth component of the cell centered array.
TYPE & operator() (const CellIndex &i, int depth=0)
Return reference to cell data entry corresponding to a given cell index and depth.
const TYPE & operator() (const CellIndex &i, int depth=0) const
Return a const reference to cell data entry corresponding to a given cell index and depth.
ArrayData< TYPE > & getArrayData ()
Return a reference to the array data object for the cell centered data object.
const ArrayData< TYPE > & getArrayData () const
Return a const reference to the array data object for the cell centered data object.
virtual void copy (const hier::PatchData &src)
A fast copy from source to destination (i.e., this) patch data object.
virtual void copy2 (hier::PatchData &dst) const
A fast copy from source (i.e., this) to destination patch data object.
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Copy data from source to destination (i.e., this) patch data object on the given overlap.
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
Copy data from source (i.e., this) to destination patch data object on the given overlap.
void copyOnBox (const CellData< TYPE > &src, const hier::Box &box)
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
virtual void copyDepth (int dst_depth, const CellData< TYPE > &src, int src_depth)
Fast copy (i.e., source and this cell data objects are defined over the same box) to this destination cell data object from the given source cell data object at the specified depths.
virtual bool canEstimateStreamSizeFromBox () const
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
virtual size_t getDataStreamSize (const hier::BoxOverlap &overlap) const
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be a CellOverlap of the same DIM.
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be a CellOverlap of the same DIM.
virtual void sum (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Add data from source to destination (i.e., this) patch data object on the given overlap.
virtual void unpackStreamAndSum (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream and add into this patch data object over the specified box overlap region. The overlap must be an CellOverlap of the same DIM.
void fill (const TYPE &t, int d=0)
Fill all values at depth d with the value t.
void fill (const TYPE &t, const hier::Box &box, int d=0)
Fill all values at depth d within the box with the value t.
void fillAll (const TYPE &t)
Fill all depth components with value t.
void fillAll (const TYPE &t, const hier::Box &box)
Fill all depth components within the box with value t.
void print (const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all cell data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
void print (const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all cell data values at the given array depth in the specified box.
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Static Public Member Functions
static size_t getSizeOfData (const hier::Box &box, int depth, const hier::IntVector &ghosts)
Calculate the amount of memory needed to represent cell- centered data over a CELL-centered AMR index space box.
Detailed Description
template<class TYPE>
class SAMRAI::pdat::CellData< TYPE >
Class CellData<TYPE> provides an implementation for data defined at cell centers on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a cell data object represents data of some template TYPE and depth at the centers of the cells in the box. Here, depth indicates the number of data values at each cell index location. The CellGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and cell-centered data.
A cell-centerd data array is stored in (i,...,k,d) order, where i,...,k are spatial indices and d indicates the depth at that location. Memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory. For example, a three-dimensional cell data object defined over a box [l0:u0,l1:u1,l2:u2] holds a data array sized as
 *
 *   [ l0 : u0 ,
 *     l1 : u1 ,
 *     l2 : u2 , d ]
 *
 *
Other spatial dimensions are represented similarly.
The data type TYPE must define a default constructor (i.e., taking no arguments) and also the copy assignment operator.
See also:
pdat::ArrayData
hier::PatchData
pdat::CellDataFactory
pdat::CellIndex
pdat::CellIterator
pdat::CellGeometry
Member Typedef Documentation
template<class TYPE> typedef CellIterator SAMRAI::pdat::CellData< TYPE >::iterator
The cell iterator iterates over the elements of a cell centered box geometry. This typedef is a convenience for using the CellIterator class.
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::CellData< TYPE >::CellData (const hier::Box & box, int depth, const hier::IntVector & ghosts) [inline]
The constructor for an cell data object.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the cell data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the node data will be allocated.
Precondition:
box.getDim() == ghosts.getDim()
depth > 0
ghosts.min() >= 0
References SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::tbox::TimerManager::getManager(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > SAMRAI::pdat::CellData< TYPE >::~CellData () [inline, virtual]
The virtual destructor for a cell data object.
Member Function Documentation
template<class TYPE > size_t SAMRAI::pdat::CellData< TYPE >::getSizeOfData (const hier::Box & box, int depth, const hier::IntVector & ghosts) [inline, static]
Calculate the amount of memory needed to represent cell- centered data over a CELL-centered AMR index space box.
This function assumes that the amount of memory needed for TYPE is sizeof(TYPE). If this is not the case, then a specialized function must be defined.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the cell data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the node data will be allocated.
Precondition:
box.getDim() == ghosts.getDim()
depth > 0
References SAMRAI::hier::Box::grow(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > int SAMRAI::pdat::CellData< TYPE >::getDepth () const [inline]
Return the depth (e.g., the number of components in each spatial location) of the array.
template<class TYPE > TYPE * SAMRAI::pdat::CellData< TYPE >::getPointer (int depth = 0) [inline]
Get a pointer to the beginning of a depth component of the cell centered array.
Precondition:
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch().
template<class TYPE > const TYPE * SAMRAI::pdat::CellData< TYPE >::getPointer (int depth = 0) const [inline]
Get a const pointer to the beginning of a depth component of the cell centered array.
Precondition:
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::CellData< TYPE >::operator() (const CellIndex & i, int depth = 0) [inline]
Return reference to cell data entry corresponding to a given cell index and depth.
Precondition:
getDim() == i.getDim()
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > const TYPE & SAMRAI::pdat::CellData< TYPE >::operator() (const CellIndex & i, int depth = 0) const [inline]
Return a const reference to cell data entry corresponding to a given cell index and depth.
Precondition:
getDim() == i.getDim()
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > ArrayData< TYPE > & SAMRAI::pdat::CellData< TYPE >::getArrayData () [inline]
Return a reference to the array data object for the cell centered data object.
Referenced by SAMRAI::pdat::CellData< TYPE >::copyOnBox().
template<class TYPE > const ArrayData< TYPE > & SAMRAI::pdat::CellData< TYPE >::getArrayData () const [inline]
Return a const reference to the array data object for the cell centered data object.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy from source to destination (i.e., this) patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, source data must be CellData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getArrayData().getDim() == src.getDim()
References SAMRAI::hier::PatchData::copy2(), SAMRAI::hier::Box::empty(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy from source (i.e., this) to destination patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, destination data must be CellData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getArrayData().getDim() == dst.getDim()
dynamic_cast<CellData<TYPE> *>(&dst) != 0
References SAMRAI::hier::Box::empty(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from source to destination (i.e., this) patch data object on the given overlap.
Currently, source data must be CellData of the same DIM and TYPE and the overlap must be a CellOverlap of the same DIM. If not, then an unrecoverable error results.
References SAMRAI::hier::PatchData::copy2(), and SAMRAI::hier::Transformation::NO_ROTATE.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from source (i.e., this) to destination patch data object on the given overlap.
Currently, destination data must be CellData of the same DIM and TYPE and the overlap must be a CellOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
dynamic_cast<CellData<TYPE> *>(&dst) != 0
dynamic_cast<const CellOverlap *>(&overlap) != 0
References SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::copyOnBox (const CellData< TYPE > & src, const hier::Box & box) [inline]
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
Precondition:
(getDim() == src.getDim()) && (getDim() == box.getDim())
References SAMRAI::pdat::CellData< TYPE >::getArrayData(), and TBOX_ASSERT_OBJDIM_EQUALITY3.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::copyDepth (int dst_depth, const CellData< TYPE > & src, int src_depth) [inline, virtual]
Fast copy (i.e., source and this cell data objects are defined over the same box) to this destination cell data object from the given source cell data object at the specified depths.
Precondition:
getArrayData.getDim() == src.getDim()
References SAMRAI::hier::Box::empty(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::CellData< TYPE >::canEstimateStreamSizeFromBox () const [inline, virtual]
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Implements SAMRAI::hier::PatchData.
template<class TYPE > size_t SAMRAI::pdat::CellData< TYPE >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Precondition:
dynamic_cast<const CellOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::CellOverlap::getDestinationBoxContainer(), SAMRAI::pdat::CellOverlap::getSourceOffset(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be a CellOverlap of the same DIM.
Precondition:
dynamic_cast<const CellOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::CellOverlap::getDestinationBoxContainer(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::pdat::CellOverlap::getTransformation(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be a CellOverlap of the same DIM.
Precondition:
dynamic_cast<const CellOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::CellOverlap::getDestinationBoxContainer(), SAMRAI::pdat::CellOverlap::getSourceOffset(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::sum (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Add data from source to destination (i.e., this) patch data object on the given overlap.
Currently, source data must be CellData of the same DIM and TYPE and the overlap must be an CellOverlap of the same DIM. If not, then an unrecoverable error results.
References SAMRAI::pdat::CellOverlap::getDestinationBoxContainer(), SAMRAI::pdat::CellOverlap::getSourceOffset(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::unpackStreamAndSum (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream and add into this patch data object over the specified box overlap region. The overlap must be an CellOverlap of the same DIM.
References SAMRAI::pdat::CellOverlap::getDestinationBoxContainer(), SAMRAI::pdat::CellOverlap::getSourceOffset(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::fill (const TYPE & t, int d = 0) [inline]
Fill all values at depth d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::fill (const TYPE & t, const hier::Box & box, int d = 0) [inline]
Fill all values at depth d within the box with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all depth components with value t.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all depth components within the box with value t.
Precondition:
getDim() == box.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::print (const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all cell data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to cell index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::print (const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all cell data values at the given array depth in the specified box.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to cell index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::CellGeometry::begin(), SAMRAI::pdat::CellGeometry::end(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check that class version and restart file version are equal. If so, read data members from the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::CellData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number and other data members to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/CellData.h
source/SAMRAI/pdat/CellData.C