SAMRAI: SAMRAI::hier::RefineOperator Class Reference
SAMRAI::hier::RefineOperator Class Reference
#include <source/SAMRAI/hier/RefineOperator.h>
Public Member Functions
RefineOperator (const std::string &name)
Construct the object with a name to allow the TransferOperatorRegistry class to look up the object using a string.
virtual ~RefineOperator ()
const std::string & getOperatorName () const
virtual int getOperatorPriority () const =0
virtual IntVector getStencilWidth (const tbox::Dimension &dim) const =0
virtual void refine (Patch &fine, const Patch &coarse, const int dst_component, const int src_component, const BoxOverlap &fine_overlap, const IntVector &ratio) const =0
Static Public Member Functions
static IntVector getMaxRefineOpStencilWidth (const tbox::Dimension &dim)
Get the max stencil width of all refine operators.
Detailed Description
Class RefineOperator is an abstract base class for each spatial refinement operator used in the SAMRAI framework. This class defines the interface between numerical refinement routines and the rest of the framework. Each concrete refinement operator subclass must provide three four operations:
(1) {an implementation of the refinement operation appropriate for its corresponding patch data type.}
(2) {a function that determines whether or not the operator matches an arbitrary request for a refinement operator.}
(3) {a function that returns the stencil width of the operator (i.e., the number of ghost cells needed by the operator).}
(4) {a function that returns an integer stating the priority of the operator with respect to other refinement operators.}
To add a new refinement operator (either for a new patch data type or for a new time refinement routine on an existing type), define the operator by inheriting from this abstract base class. The operator subclass must implement the refinement operation in the refine() fnction. The stencil width and operator priority must be returned from the getStencilWidth() and getOperatorPriority() functions, respectively. Then, the new operator must be added to the operator list for the appropriate transfer geometry object using the BaseGridGeometry::addRefineOperator() function.
Since spatial refinement operators usually depend on patch data centering and data type as well as the mesh coordinate system, they are defined in the geometry package.
See also:
TransferOperatorRegistry
Constructor & Destructor Documentation
SAMRAI::hier::RefineOperator::RefineOperator (const std::string & name)
Construct the object with a name to allow the TransferOperatorRegistry class to look up the object using a string.
The constructor must be given a name. The object will be registered under this name with the TransferOperatorRegistry class. The name must be unique, as duplicate names are not allowed.
SAMRAI::hier::RefineOperator::~RefineOperator () [virtual]
The virtual destructor for the refinement operator does nothing interesting.
Member Function Documentation
const std::string& SAMRAI::hier::RefineOperator::getOperatorName () const [inline]
Return name std::string identifier of the refinement operation.
virtual int SAMRAI::hier::RefineOperator::getOperatorPriority () const [pure virtual]
Return the priority of this operator relative to other refinement operators. The SAMRAI transfer routines guarantee that refinement using operators with lower priority values will be performed before those with higher priority.
Implemented in SAMRAI::pdat::CellComplexConstantRefine, SAMRAI::pdat::CellDoubleConstantRefine, SAMRAI::pdat::CellFloatConstantRefine, SAMRAI::pdat::CellIntegerConstantRefine, SAMRAI::pdat::EdgeComplexConstantRefine, SAMRAI::pdat::EdgeDoubleConstantRefine, SAMRAI::pdat::EdgeFloatConstantRefine, SAMRAI::pdat::EdgeIntegerConstantRefine, SAMRAI::pdat::FaceComplexConstantRefine, SAMRAI::pdat::FaceDoubleConstantRefine, SAMRAI::pdat::FaceFloatConstantRefine, SAMRAI::pdat::FaceIntegerConstantRefine, SAMRAI::pdat::OuterfaceComplexConstantRefine, SAMRAI::pdat::OuterfaceDoubleConstantRefine, SAMRAI::pdat::OuterfaceFloatConstantRefine, SAMRAI::pdat::OuterfaceIntegerConstantRefine, SAMRAI::pdat::SideComplexConstantRefine, SAMRAI::pdat::SideDoubleConstantRefine, SAMRAI::pdat::SideFloatConstantRefine, SAMRAI::pdat::SideIntegerConstantRefine, SAMRAI::geom::CartesianCellComplexConservativeLinearRefine, SAMRAI::geom::CartesianCellComplexLinearRefine, SAMRAI::geom::CartesianCellDoubleConservativeLinearRefine, SAMRAI::geom::CartesianCellDoubleLinearRefine, SAMRAI::geom::CartesianCellFloatConservativeLinearRefine, SAMRAI::geom::CartesianCellFloatLinearRefine, SAMRAI::geom::CartesianEdgeDoubleConservativeLinearRefine, SAMRAI::geom::CartesianEdgeFloatConservativeLinearRefine, SAMRAI::geom::CartesianFaceDoubleConservativeLinearRefine, SAMRAI::geom::CartesianFaceFloatConservativeLinearRefine, SAMRAI::geom::CartesianNodeComplexLinearRefine, SAMRAI::geom::CartesianNodeDoubleLinearRefine, SAMRAI::geom::CartesianNodeFloatLinearRefine, SAMRAI::geom::CartesianSideDoubleConservativeLinearRefine, and SAMRAI::geom::CartesianSideFloatConservativeLinearRefine.
virtual IntVector SAMRAI::hier::RefineOperator::getStencilWidth (const tbox::Dimension & dim) const [pure virtual]
Return the stencil width associated with the refinement operator. The SAMRAI transfer routines guarantee that the source patch will contain sufficient ghost cell data surrounding the interior to satisfy the stencil width requirements for each refinement operator. If your implementation doesn't work with the given dimension, return zero.
Implemented in SAMRAI::pdat::CellComplexConstantRefine, SAMRAI::pdat::CellDoubleConstantRefine, SAMRAI::pdat::CellFloatConstantRefine, SAMRAI::pdat::CellIntegerConstantRefine, SAMRAI::pdat::EdgeComplexConstantRefine, SAMRAI::pdat::EdgeDoubleConstantRefine, SAMRAI::pdat::EdgeFloatConstantRefine, SAMRAI::pdat::EdgeIntegerConstantRefine, SAMRAI::pdat::FaceComplexConstantRefine, SAMRAI::pdat::FaceDoubleConstantRefine, SAMRAI::pdat::FaceFloatConstantRefine, SAMRAI::pdat::FaceIntegerConstantRefine, SAMRAI::pdat::OuterfaceComplexConstantRefine, SAMRAI::pdat::OuterfaceDoubleConstantRefine, SAMRAI::pdat::OuterfaceFloatConstantRefine, SAMRAI::pdat::OuterfaceIntegerConstantRefine, SAMRAI::pdat::SideComplexConstantRefine, SAMRAI::pdat::SideDoubleConstantRefine, SAMRAI::pdat::SideFloatConstantRefine, SAMRAI::pdat::SideIntegerConstantRefine, SAMRAI::geom::CartesianCellComplexConservativeLinearRefine, SAMRAI::geom::CartesianCellComplexLinearRefine, SAMRAI::geom::CartesianCellDoubleConservativeLinearRefine, SAMRAI::geom::CartesianCellDoubleLinearRefine, SAMRAI::geom::CartesianCellFloatConservativeLinearRefine, SAMRAI::geom::CartesianCellFloatLinearRefine, SAMRAI::geom::CartesianEdgeDoubleConservativeLinearRefine, SAMRAI::geom::CartesianEdgeFloatConservativeLinearRefine, SAMRAI::geom::CartesianFaceDoubleConservativeLinearRefine, SAMRAI::geom::CartesianFaceFloatConservativeLinearRefine, SAMRAI::geom::CartesianNodeComplexLinearRefine, SAMRAI::geom::CartesianNodeDoubleLinearRefine, SAMRAI::geom::CartesianNodeFloatLinearRefine, SAMRAI::geom::CartesianSideDoubleConservativeLinearRefine, and SAMRAI::geom::CartesianSideFloatConservativeLinearRefine.
Referenced by getMaxRefineOpStencilWidth().
virtual void SAMRAI::hier::RefineOperator::refine (Patch & fine, const Patch & coarse, const int dst_component, const int src_component, const BoxOverlap & fine_overlap, const IntVector & ratio) const [pure virtual]
Refine the source component on the coarse patch to the destination component on the fine patch. The refinement operation is performed on the intersection of the destination patch and the boxes contained in fine_overlap. The coarse patch is guaranteed to contain sufficient data for the stencil width of the refinement operator.
Implemented in SAMRAI::pdat::CellComplexConstantRefine, SAMRAI::pdat::CellDoubleConstantRefine, SAMRAI::pdat::CellFloatConstantRefine, SAMRAI::pdat::CellIntegerConstantRefine, SAMRAI::pdat::EdgeComplexConstantRefine, SAMRAI::pdat::EdgeDoubleConstantRefine, SAMRAI::pdat::EdgeFloatConstantRefine, SAMRAI::pdat::EdgeIntegerConstantRefine, SAMRAI::pdat::FaceComplexConstantRefine, SAMRAI::pdat::FaceDoubleConstantRefine, SAMRAI::pdat::FaceFloatConstantRefine, SAMRAI::pdat::FaceIntegerConstantRefine, SAMRAI::pdat::OuterfaceComplexConstantRefine, SAMRAI::pdat::OuterfaceDoubleConstantRefine, SAMRAI::pdat::OuterfaceFloatConstantRefine, SAMRAI::pdat::OuterfaceIntegerConstantRefine, SAMRAI::pdat::SideComplexConstantRefine, SAMRAI::pdat::SideDoubleConstantRefine, SAMRAI::pdat::SideFloatConstantRefine, SAMRAI::pdat::SideIntegerConstantRefine, SAMRAI::geom::CartesianCellComplexConservativeLinearRefine, SAMRAI::geom::CartesianCellComplexLinearRefine, SAMRAI::geom::CartesianCellDoubleConservativeLinearRefine, SAMRAI::geom::CartesianCellDoubleLinearRefine, SAMRAI::geom::CartesianCellFloatConservativeLinearRefine, SAMRAI::geom::CartesianCellFloatLinearRefine, SAMRAI::geom::CartesianEdgeDoubleConservativeLinearRefine, SAMRAI::geom::CartesianEdgeFloatConservativeLinearRefine, SAMRAI::geom::CartesianFaceDoubleConservativeLinearRefine, SAMRAI::geom::CartesianFaceFloatConservativeLinearRefine, SAMRAI::geom::CartesianNodeComplexLinearRefine, SAMRAI::geom::CartesianNodeDoubleLinearRefine, SAMRAI::geom::CartesianNodeFloatLinearRefine, SAMRAI::geom::CartesianSideDoubleConservativeLinearRefine, and SAMRAI::geom::CartesianSideFloatConservativeLinearRefine.
IntVector SAMRAI::hier::RefineOperator::getMaxRefineOpStencilWidth (const tbox::Dimension & dim) [static]
Get the max stencil width of all refine operators.
The max stencil width computed from all registered (constructed) refine operators.
References getStencilWidth(), SAMRAI::hier::IntVector::max(), TBOX_omp_set_lock, and TBOX_omp_unset_lock.
Referenced by SAMRAI::hier::TransferOperatorRegistry::getMaxTransferOpStencilWidth().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/RefineOperator.h
source/SAMRAI/hier/RefineOperator.C