SAMRAI: SAMRAI::tbox::AsyncCommPeer< TYPE > Class Template Reference
SAMRAI::tbox::AsyncCommPeer< TYPE > Class Template Reference
Supports point-to-point asynchronous communication operations that can overlap other communcations using a AsyncCommStage.
#include <source/SAMRAI/tbox/AsyncCommPeer.h>
Public Member Functions
AsyncCommPeer ()
Default constructor does not set up anything. You must initialize() the object before using it.
AsyncCommPeer (AsyncCommStage *stage, AsyncCommStage::Handler *handler=0)
Construct staged communication object.
virtual ~AsyncCommPeer ()
Destructor.
void initialize (AsyncCommStage *stage, AsyncCommStage::Handler *handler=0)
Initialize the object.
void setMPITag (const int primary_tag, const int secondary_tag)
Set the MPI tags used for communication.
void setMPI (const SAMRAI_MPI &mpi)
Set the MPI object used for communications.
const SAMRAI_MPI & getMPI () const
Gets the MPI object used for communications.
TaskOp getNextTaskOp () const
Next task in a current communication operation.
BaseOp getBaseOp () const
Operation being performed.
int getPrimaryTag () const
Primary tag for the first message.
int getSecondaryTag () const
Secondary tag for the first message.
void logCurrentState (std::ostream &co) const
For use in debugging.
Define the peer relationship.
void setPeerRank (int peer_rank)
Set the peer rank.
int getPeerRank () const
Rank of peer process.
void limitFirstDataLength (size_t max_first_data_len)
Limit the data length in first message of a communication.
Communication methods
bool beginSend (const TYPE *buffer, int size, bool automatic_push_to_completion_queue=false)
Begin a send communication.
bool checkSend (bool automatic_push_to_completion_queue=false)
Check the current broadcast communication and complete the broadcast if all MPI requests are fulfilled.
bool beginRecv (bool automatic_push_to_completion_queue=false)
Begin a receive communication.
bool checkRecv (bool automatic_push_to_completion_queue=false)
Check the current receive communication and complete the receive if the MPI request has been fulfilled.
int getRecvSize () const
Return the size of received data.
const TYPE * getRecvData () const
Get access to the received data.
void clearRecvData ()
Clear the receive buffer immediately.
bool proceedToNextWait ()
Check the current communication and complete it if all MPI requests are fulfilled.
bool isDone () const
Whether the last communication operation has finished.
void completeCurrentOperation ()
Wait for the current operation to complete.
bool isSender ()
Whether the current (or last) operation was a send.
bool isReceiver ()
Whether the current (or last) operation was a receive.
Timers for MPI calls
void setSendTimer (const boost::shared_ptr< Timer > &send_timer)
Set the send-timer.
void setRecvTimer (const boost::shared_ptr< Timer > &recv_timer)
Set the receive-timer.
void setWaitTimer (const boost::shared_ptr< Timer > &wait_timer)
Set the wait-timer.
Detailed Description
template<class TYPE>
class SAMRAI::tbox::AsyncCommPeer< TYPE >
Supports point-to-point asynchronous communication operations that can overlap other communcations using a AsyncCommStage.
To use this class:
Construct an object with a stage or initialize() it with a stage.
Set the MPI communicator and tag values for use in the MPI nonblocking message passing functions.
Set the peer rank using setPeerRank().
Call the beginSend() and beginRecv() functions. Make sure there is a matching call on the peer processor.
Use the stage to advance the message passing operations. The stage tells you which members have completed their operations.
Received data can be accessed using getRecvSize() and getRecvData().
It is not neccesary to know how much data is being sent. This class will figure that out (using overhead data attached to the actual user data being communicated).
To check on sends and receives without using the stage, use checkSend() and checkRecv() or proceedToNextWait(). To wait for the current operation to complete, use completeCurrentOperation().
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::tbox::AsyncCommPeer< TYPE >::AsyncCommPeer () [inline]
Default constructor does not set up anything. You must initialize() the object before using it.
template<class TYPE > SAMRAI::tbox::AsyncCommPeer< TYPE >::AsyncCommPeer (AsyncCommStage * stage, AsyncCommStage::Handler * handler = 0) [inline, explicit]
Construct staged communication object.
See also:
initialize().
template<class TYPE > SAMRAI::tbox::AsyncCommPeer< TYPE >::~AsyncCommPeer () [inline, virtual]
Destructor.
Precondition:
isDone()
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), and TBOX_ERROR.
Member Function Documentation
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::initialize (AsyncCommStage * stage, AsyncCommStage::Handler * handler = 0) [inline]
Initialize the object.
Attach self to the given stage and set the Handler.
Parameters:
stage The stage handling communicaiton requests for the object.
handler Optional pointer to user-defined data.
Precondition:
isDone()
References SAMRAI::tbox::AsyncCommStage::Member::attachStage(), SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), SAMRAI::tbox::AsyncCommStage::Member::setHandler(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::setPeerRank (int peer_rank) [inline]
Set the peer rank.
We assume (without checking) that the peer processor does a complementary call using this processor as its peer. If this assumption is wrong, there will likely be communication errors.
Parameters:
peer_rank
Precondition:
isDone()
References SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
template<class TYPE> int SAMRAI::tbox::AsyncCommPeer< TYPE >::getPeerRank () const [inline]
Rank of peer process.
Referenced by SAMRAI::hier::BaseConnectorAlgorithm::receiveAndUnpack(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
template<class TYPE> void SAMRAI::tbox::AsyncCommPeer< TYPE >::limitFirstDataLength (size_t max_first_data_len) [inline]
Limit the data length in first message of a communication.
Sometimes, the receiver does not know how much data is being sent. In such cases, the receiver would assume the data is no more than a size that the sender and receiver have agreed upon before hand, max_first_data_len. If the message is longer, the sender sends it in two parts. The first message contains no more than max_first_data_len items and indicates the true length of the data. A second message is used if needed.
The receiver must set a first data length no less than the sender's or risk a fatal MPI "truncated message" error.
The limit is set to one by default, meaning that any message more than one item long would be sent in two parts.
Referenced by SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPITag (const int primary_tag, const int secondary_tag) [inline]
Set the MPI tags used for communication.
The primary_tag is used for every message. If a message must be sent in two parts (see limitFirstDataLength()), the secondary tag is used for the follow-up message. It is advisable to use different values for the two tags to ensure that the second message is not mistaken for the first.
Attention:
This class is NOT (and cannot be) responsible for ensuring that the MPI communicator and tag are sufficient to select the correct messages. Please specify appropriate values for the MPI communicator and tag. Very elusive bugs can occur if incorrect messages are received.
Parameters:
primary_tag
secondary_tag
Precondition:
isDone()
References SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPI (const SAMRAI_MPI & mpi) [inline]
Set the MPI object used for communications.
Attention:
This class is NOT (and cannot be) responsible for ensuring that the MPI object and tag are sufficient to select the correct messages. Please specify appropriate values for the MPI object and tag. Very elusive bugs can occur if incorrect messages are received. To be safe, it is best to create a new communicator to avoid interference with other communications within SAMRAI.
Parameters:
mpi
Precondition:
isDone()
References SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
template<class TYPE> const SAMRAI_MPI& SAMRAI::tbox::AsyncCommPeer< TYPE >::getMPI () const [inline]
Gets the MPI object used for communications.
template<class TYPE> TaskOp SAMRAI::tbox::AsyncCommPeer< TYPE >::getNextTaskOp () const [inline]
Next task in a current communication operation.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::beginRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::beginSend(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::clearRecvData().
template<class TYPE> BaseOp SAMRAI::tbox::AsyncCommPeer< TYPE >::getBaseOp () const [inline]
Operation being performed.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvData(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvSize().
template<class TYPE> int SAMRAI::tbox::AsyncCommPeer< TYPE >::getPrimaryTag () const [inline]
Primary tag for the first message.
template<class TYPE> int SAMRAI::tbox::AsyncCommPeer< TYPE >::getSecondaryTag () const [inline]
Secondary tag for the first message.
template<class TYPE> bool SAMRAI::tbox::AsyncCommPeer< TYPE >::beginSend (const TYPE * buffer, int size, bool automatic_push_to_completion_queue = false) [inline]
Begin a send communication.
This must be paired with a beginRecv() by the peer processor.
On return, the data in buffer would have been copied so it is safe to deallocate or modify buffer.
Parameters:
buffer
size
automatic_push_to_completion_queue Whether to automatically push this member onto the completion queue of its stage (where you can retrieve it using the stage's popFromCompletionQueue() method.
Returns:
Whether operation is completed.
Precondition:
getNextTaskOp() == none
References SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getNextTaskOp(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
template<class TYPE > bool SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend (bool automatic_push_to_completion_queue = false) [inline]
Check the current broadcast communication and complete the broadcast if all MPI requests are fulfilled.
If no communication is in progress, this call does nothing.
Parameters:
automatic_push_to_completion_queue See beginSend().
Returns:
Whether operation is completed.
Precondition:
getBaseOp() == send
References SAMRAI::tbox::AsyncCommPeer< TYPE >::getBaseOp(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer(), SAMRAI::tbox::AsyncCommStage::Member::getStatusPointer(), SAMRAI::tbox::SAMRAI_MPI::Isend(), MPI_BYTE, MPI_ERR_IN_STATUS, MPI_REQUEST_NULL, MPI_SUCCESS, SAMRAI::tbox::plog, SAMRAI::tbox::AsyncCommStage::Member::pushToCompletionQueue(), TBOX_ASSERT, TBOX_ERROR, and SAMRAI::tbox::SAMRAI_MPI::Test().
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::beginSend(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::proceedToNextWait().
template<class TYPE > bool SAMRAI::tbox::AsyncCommPeer< TYPE >::beginRecv (bool automatic_push_to_completion_queue = false) [inline]
Begin a receive communication.
This must be paired with a beginSend() by the peer processor.
The received data is stored in an internal buffer accessible through getRecvData(). After receiving, the internal buffer is available until the object goes out of scope, another communication operation is initiated or deallocateInternalRecvBuffer() is called.
The actual length of data received by the last receive operation is returned by getRecvSize().
Parameters:
automatic_push_to_completion_queue See beginSend().
Returns:
Whether operation is completed.
References SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getNextTaskOp(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
template<class TYPE > bool SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv (bool automatic_push_to_completion_queue = false) [inline]
Check the current receive communication and complete the receive if the MPI request has been fulfilled.
Returns:
Whether operation is completed.
Parameters:
automatic_push_to_completion_queue See beginSend().
Precondition:
getBaseOp() == recv
References SAMRAI::tbox::SAMRAI_MPI::Get_count(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getBaseOp(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer(), SAMRAI::tbox::AsyncCommStage::Member::getStatusPointer(), SAMRAI::tbox::SAMRAI_MPI::Irecv(), MPI_BYTE, MPI_ERR_IN_STATUS, MPI_REQUEST_NULL, MPI_SUCCESS, SAMRAI::tbox::plog, SAMRAI::tbox::AsyncCommStage::Member::pushToCompletionQueue(), TBOX_ASSERT, TBOX_ERROR, and SAMRAI::tbox::SAMRAI_MPI::Test().
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::beginRecv(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::proceedToNextWait().
template<class TYPE > int SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvSize () const [inline]
Return the size of received data.
Precondition:
getBaseOp() == recv
References SAMRAI::tbox::AsyncCommPeer< TYPE >::getBaseOp(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
template<class TYPE > const TYPE * SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvData () const [inline]
Get access to the received data.
Precondition:
getBaseOp() == recv
References SAMRAI::tbox::AsyncCommPeer< TYPE >::getBaseOp(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::clearRecvData () [inline]
Clear the receive buffer immediately.
This is optional. The received data remains inside the object the next communicaiton operation starts, or until it is explicitly freed.
It is an error to clear the receive buffer in the middle of a communication operation.
Precondition:
getNextTaksOp() == none
References SAMRAI::tbox::AsyncCommPeer< TYPE >::getNextTaskOp(), and TBOX_ERROR.
template<class TYPE > bool SAMRAI::tbox::AsyncCommPeer< TYPE >::proceedToNextWait () [inline, virtual]
Check the current communication and complete it if all MPI requests are fulfilled.
Implements SAMRAI::tbox::AsyncCommStage::Member.
References SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation().
template<class TYPE > bool SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone () const [inline, virtual]
Whether the last communication operation has finished.
This means more than just whether there is outstanding MPI requests such as that returned by hasOutstandingRequests(). The communication is more complex, requiring up to two messages and copying of the received message into the correct buffer. When isDone() returns true, the operation is truly finished.
Implements SAMRAI::tbox::AsyncCommStage::Member.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation(), SAMRAI::tbox::AsyncCommPeer< TYPE >::initialize(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPI(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPITag(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setPeerRank(), SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::~AsyncCommPeer().
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation () [inline, virtual]
Wait for the current operation to complete.
Implements SAMRAI::tbox::AsyncCommStage::Member.
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer(), SAMRAI::tbox::AsyncCommStage::Member::getStatusPointer(), SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), MPI_SUCCESS, SAMRAI::tbox::AsyncCommPeer< TYPE >::proceedToNextWait(), TBOX_ERROR, and SAMRAI::tbox::SAMRAI_MPI::Waitall().
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
template<class TYPE> bool SAMRAI::tbox::AsyncCommPeer< TYPE >::isSender () [inline]
Whether the current (or last) operation was a send.
template<class TYPE> bool SAMRAI::tbox::AsyncCommPeer< TYPE >::isReceiver () [inline]
Whether the current (or last) operation was a receive.
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::setSendTimer (const boost::shared_ptr< Timer > & send_timer) [inline]
Set the send-timer.
Set the timer for non-blocking sends. If the timer is null, revert to the default timer named "tbox::AsyncCommPeer::MPI_Isend()".
Parameters:
[in] send_timer
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::setRecvTimer (const boost::shared_ptr< Timer > & recv_timer) [inline]
Set the receive-timer.
Set the timer for non-blocking receives. If the timer is null, revert to the default timer named "tbox::AsyncCommPeer::MPI_Irecv()".
Parameters:
[in] recv_timer
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::setWaitTimer (const boost::shared_ptr< Timer > & wait_timer) [inline]
Set the wait-timer.
Set the timer for blocking waits. If the timer is null, revert to the default timer named "tbox::AsyncCommPeer::MPI_Waitall()".
This timer is used when in this class and is not the same as the timer given to AsyncCommStage (unless the user sets it up that way explicitly).
Parameters:
[in] wait_timer
template<class TYPE > void SAMRAI::tbox::AsyncCommPeer< TYPE >::logCurrentState (std::ostream & co) const [inline]
For use in debugging.
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), and SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/AsyncCommPeer.h
source/SAMRAI/tbox/AsyncCommPeer.C