SAMRAI: SAMRAI::math::PatchSideDataBasicOps< TYPE > Class Template Reference
SAMRAI::math::PatchSideDataBasicOps< TYPE > Class Template Reference
#include <source/SAMRAI/math/PatchSideDataBasicOps.h>
Public Member Functions
PatchSideDataBasicOps ()
virtual ~PatchSideDataBasicOps ()
void scale (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const TYPE &alpha, const boost::shared_ptr< pdat::SideData< TYPE > > &src, const hier::Box &box) const
void addScalar (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src, const TYPE &alpha, const hier::Box &box) const
void add (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src1, const boost::shared_ptr< pdat::SideData< TYPE > > &src2, const hier::Box &box) const
void subtract (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src1, const boost::shared_ptr< pdat::SideData< TYPE > > &src2, const hier::Box &box) const
void multiply (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src1, const boost::shared_ptr< pdat::SideData< TYPE > > &src2, const hier::Box &box) const
void divide (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src1, const boost::shared_ptr< pdat::SideData< TYPE > > &src2, const hier::Box &box) const
void reciprocal (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src, const hier::Box &box) const
void linearSum (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const TYPE &alpha, const boost::shared_ptr< pdat::SideData< TYPE > > &src1, const TYPE &beta, const boost::shared_ptr< pdat::SideData< TYPE > > &src2, const hier::Box &box) const
void axpy (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const TYPE &alpha, const boost::shared_ptr< pdat::SideData< TYPE > > &src1, const boost::shared_ptr< pdat::SideData< TYPE > > &src2, const hier::Box &box) const
void axmy (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const TYPE &alpha, const boost::shared_ptr< pdat::SideData< TYPE > > &src1, const boost::shared_ptr< pdat::SideData< TYPE > > &src2, const hier::Box &box) const
TYPE min (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box) const
TYPE max (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box) const
void setRandomValues (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const TYPE &width, const TYPE &low, const hier::Box &box) const
Detailed Description
template<class TYPE>
class SAMRAI::math::PatchSideDataBasicOps< TYPE >
Class PatchSideDataBasicOps provides access to a collection of basic numerical operations that may be applied to numerical side- centered patch data. These operations include simple arithmetic operations as well as min and max, etc. This class provides a single implementation of these operations that may be used to manipulate any side-centered patch data objects. Each member function accepts a box argument indicating the region of index space on which the operation should be performed. The operation will be performed on the intersection of this box and those boxes corresponding to the patch data objects involved.
These operations typically apply only to the numerical standard built-in types, such as double, float, and int, and the complex type (which may or may not be a built-in type depending on the C++ compiler). Thus, this templated class should only be used to instantiate objects with those types as the template parameter. None of the operations are implemented for any other type.
See also:
ArrayDataBasicOps
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::math::PatchSideDataBasicOps< TYPE >::PatchSideDataBasicOps () [inline]
Empty constructor and destructor.
template<class TYPE > SAMRAI::math::PatchSideDataBasicOps< TYPE >::~PatchSideDataBasicOps () [inline, virtual]
Member Function Documentation
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::scale (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const TYPE & alpha, const boost::shared_ptr< pdat::SideData< TYPE > > & src, const hier::Box & box) const [inline]
Set dst = alpha * src, elementwise.
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::scale(), and SAMRAI::math::HierarchySideDataOpsComplex::scale().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::addScalar (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src, const TYPE & alpha, const hier::Box & box) const [inline]
Set dst = src + alpha, elementwise.
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::addScalar(), and SAMRAI::math::HierarchySideDataOpsComplex::addScalar().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::add (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src1, const boost::shared_ptr< pdat::SideData< TYPE > > & src2, const hier::Box & box) const [inline]
Set dst = src1 + src2, elementwise.
Precondition:
dst && src1 && src2
(dst->getDirectionVector() == src1->getDirectionVector()) && (dst->getDirectionVector() == src2->getDirectionVector())
(dst->getDim() == src1->getDim()) && (dst->getDim() == src2->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::add(), and SAMRAI::math::HierarchySideDataOpsComplex::add().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::subtract (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src1, const boost::shared_ptr< pdat::SideData< TYPE > > & src2, const hier::Box & box) const [inline]
Set dst = src1 - src2, elementwise.
Precondition:
dst && src1 && src2
(dst->getDirectionVector() == src1->getDirectionVector()) && (dst->getDirectionVector() == src2->getDirectionVector())
(dst->getDim() == src1->getDim()) && (dst->getDim() == src2->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::subtract(), and SAMRAI::math::HierarchySideDataOpsComplex::subtract().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::multiply (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src1, const boost::shared_ptr< pdat::SideData< TYPE > > & src2, const hier::Box & box) const [inline]
Set dst = src1 * src2, elementwise.
Precondition:
dst && src1 && src2
(dst->getDirectionVector() == src1->getDirectionVector()) && (dst->getDirectionVector() == src2->getDirectionVector())
(dst->getDim() == src1->getDim()) && (dst->getDim() == src2->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::multiply(), and SAMRAI::math::HierarchySideDataOpsComplex::multiply().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::divide (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src1, const boost::shared_ptr< pdat::SideData< TYPE > > & src2, const hier::Box & box) const [inline]
Set dst = src1 / src2, elementwise. No check for division by zero.
Precondition:
dst && src1 && src2
(dst->getDirectionVector() == src1->getDirectionVector()) && (dst->getDirectionVector() == src2->getDirectionVector())
(dst->getDim() == src1->getDim()) && (dst->getDim() == src2->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::divide(), and SAMRAI::math::HierarchySideDataOpsComplex::divide().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::reciprocal (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src, const hier::Box & box) const [inline]
Set dst = 1 / src, elementwise. No check for division by zero.
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::reciprocal(), and SAMRAI::math::HierarchySideDataOpsComplex::reciprocal().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::linearSum (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const TYPE & alpha, const boost::shared_ptr< pdat::SideData< TYPE > > & src1, const TYPE & beta, const boost::shared_ptr< pdat::SideData< TYPE > > & src2, const hier::Box & box) const [inline]
Set dst = alpha * src1 + beta * src2, elementwise.
Precondition:
dst && src1 && src2
(dst->getDirectionVector() == src1->getDirectionVector()) && (dst->getDirectionVector() == src2->getDirectionVector())
(dst->getDim() == src1->getDim()) && (dst->getDim() == src2->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::linearSum(), and SAMRAI::math::HierarchySideDataOpsComplex::linearSum().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::axpy (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const TYPE & alpha, const boost::shared_ptr< pdat::SideData< TYPE > > & src1, const boost::shared_ptr< pdat::SideData< TYPE > > & src2, const hier::Box & box) const [inline]
Set dst = alpha * src1 + src2, elementwise.
Precondition:
dst && src1 && src2
(dst->getDirectionVector() == src1->getDirectionVector()) && (dst->getDirectionVector() == src2->getDirectionVector())
(dst->getDim() == src1->getDim()) && (dst->getDim() == src2->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::axpy(), and SAMRAI::math::HierarchySideDataOpsComplex::axpy().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::axmy (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const TYPE & alpha, const boost::shared_ptr< pdat::SideData< TYPE > > & src1, const boost::shared_ptr< pdat::SideData< TYPE > > & src2, const hier::Box & box) const [inline]
Set dst = alpha * src1 - src2, elementwise.
Precondition:
dst && src1 && src2
(dst->getDirectionVector() == src1->getDirectionVector()) && (dst->getDirectionVector() == src2->getDirectionVector())
(dst->getDim() == src1->getDim()) && (dst->getDim() == src2->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::axmy(), and SAMRAI::math::HierarchySideDataOpsComplex::axmy().
template<class TYPE> TYPE SAMRAI::math::PatchSideDataBasicOps< TYPE >::min (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box) const [inline]
Return the minimum patch data component entry When the data is complex, the result is the data element with the smallest norm.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::min().
template<class TYPE> TYPE SAMRAI::math::PatchSideDataBasicOps< TYPE >::max (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box) const [inline]
Return the maximum patch data component entry When the data is complex, the result is the data element with the largest norm.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::max().
template<class TYPE> void SAMRAI::math::PatchSideDataBasicOps< TYPE >::setRandomValues (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const TYPE & width, const TYPE & low, const hier::Box & box) const [inline]
Set patch data to random values. See the operations in the ArrayDataBasicOps class for details on the generation of the random values for each data type.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::setRandomValues(), and SAMRAI::math::HierarchySideDataOpsComplex::setRandomValues().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchSideDataBasicOps.h
source/SAMRAI/math/PatchSideDataBasicOps.C