SAMRAI: SAMRAI::pdat::OuterfaceGeometry Class Reference
SAMRAI::pdat::OuterfaceGeometry Class Reference
#include <source/SAMRAI/pdat/OuterfaceGeometry.h>
Public Types
typedef FaceOverlap Overlap
Public Member Functions
OuterfaceGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct an outerface geometry object given an AMR index space box and ghost cell width.
virtual ~OuterfaceGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in face-centered index space on the boundaries of the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a FaceOverlap object based on the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this outerface box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this outerface box geometry object.
Detailed Description
Class OuterfaceGeometry manages the mapping between the AMR index and the outerface geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between outerface box geometries and face or outerface box geometries for communication operations.
See header file for OuterfaceData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
FaceGeometry
FaceOverlap
Member Typedef Documentation
typedef FaceOverlap SAMRAI::pdat::OuterfaceGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::OuterfaceGeometry::OuterfaceGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct an outerface geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::OuterfaceGeometry::~OuterfaceGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OuterfaceGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in face-centered index space on the boundaries of the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OuterfaceGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a FaceOverlap object based on the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getOffset(), and SAMRAI::pdat::FaceGeometry::toFaceBox().
const hier::Box& SAMRAI::pdat::OuterfaceGeometry::getBox () const [inline]
Return the box for this outerface box geometry object.
const hier::IntVector& SAMRAI::pdat::OuterfaceGeometry::getGhosts () const [inline]
Return the ghost cell width for this outerface box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OuterfaceGeometry.h
source/SAMRAI/pdat/OuterfaceGeometry.C