SAMRAI: SAMRAI::tbox::StartupShutdownManager::AbstractHandler Class Reference
SAMRAI::tbox::StartupShutdownManager::AbstractHandler Class Reference
Abstract base class for handler interface.
#include <source/SAMRAI/tbox/StartupShutdownManager.h>
Public Member Functions
AbstractHandler ()
Default constructor.
virtual ~AbstractHandler ()
Virtual destructor since class has virtual methods.
virtual void initialize ()=0
Method that is invoked on initialize.
virtual void startup ()=0
Method that is invoked on startup.
virtual void shutdown ()=0
Method that is invoked on shutdown.
virtual void finalize ()=0
Method that is invoked on finalize.
virtual unsigned char getPriority ()=0
Get the Priority of this handler.
virtual bool hasInitialize ()=0
Query if handler has initialize callback function.
virtual bool hasStartup ()=0
Query if handler has startup callback function.
virtual bool hasShutdown ()=0
Query if handler has shutdown callback function.
virtual bool hasFinalize ()=0
Query if handler has finalize callback function.
Detailed Description
Abstract base class for handler interface.
Defines the four methods to invoke in the lifecycle and four methods to indicate if the interface should be called for that stage.
Note the odd looking "has" methods are needed for some error checking.
Constructor & Destructor Documentation
SAMRAI::tbox::StartupShutdownManager::AbstractHandler::AbstractHandler ()
Default constructor.
SAMRAI::tbox::StartupShutdownManager::AbstractHandler::~AbstractHandler () [virtual]
Virtual destructor since class has virtual methods.
Member Function Documentation
virtual void SAMRAI::tbox::StartupShutdownManager::AbstractHandler::initialize () [pure virtual]
Method that is invoked on initialize.
This is done once per run.
Only called by StartupShutdownManager.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
virtual void SAMRAI::tbox::StartupShutdownManager::AbstractHandler::startup () [pure virtual]
Method that is invoked on startup.
This may be done more than once per run.
Only called by StartupShutdownManager.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
virtual void SAMRAI::tbox::StartupShutdownManager::AbstractHandler::shutdown () [pure virtual]
Method that is invoked on shutdown.
This may be done more than once per run.
Only called by StartupShutdownManager.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
virtual void SAMRAI::tbox::StartupShutdownManager::AbstractHandler::finalize () [pure virtual]
Method that is invoked on finalize.
This is done once per run.
Only called by StartupShutdownManager.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
virtual unsigned char SAMRAI::tbox::StartupShutdownManager::AbstractHandler::getPriority () [pure virtual]
Get the Priority of this handler.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
Referenced by SAMRAI::tbox::StartupShutdownManager::registerHandler().
virtual bool SAMRAI::tbox::StartupShutdownManager::AbstractHandler::hasInitialize () [pure virtual]
Query if handler has initialize callback function.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
Referenced by SAMRAI::tbox::StartupShutdownManager::registerHandler().
virtual bool SAMRAI::tbox::StartupShutdownManager::AbstractHandler::hasStartup () [pure virtual]
Query if handler has startup callback function.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
Referenced by SAMRAI::tbox::StartupShutdownManager::registerHandler().
virtual bool SAMRAI::tbox::StartupShutdownManager::AbstractHandler::hasShutdown () [pure virtual]
Query if handler has shutdown callback function.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
Referenced by SAMRAI::tbox::StartupShutdownManager::registerHandler().
virtual bool SAMRAI::tbox::StartupShutdownManager::AbstractHandler::hasFinalize () [pure virtual]
Query if handler has finalize callback function.
Implemented in SAMRAI::tbox::StartupShutdownManager::Handler.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/StartupShutdownManager.h
source/SAMRAI/tbox/StartupShutdownManager.C