SAMRAI: SAMRAI::pdat::CellGeometry Class Reference
SAMRAI::pdat::CellGeometry Class Reference
#include <source/SAMRAI/pdat/CellGeometry.h>
Public Types
typedef CellOverlap Overlap
Public Member Functions
CellGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct the cell geometry object given an AMR index space box and ghost cell width.
virtual ~CellGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in cell-centered index space between the source box geometry and the destination box geometry.
void computeDestinationBoxes (hier::BoxContainer &dst_boxes, const CellGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const hier::BoxContainer &dst_restrict_boxes) const
Compute the cell-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a CellOverlap object that consists simply of the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this cell centered box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this cell centered box geometry object.
Static Public Member Functions
static hier::Box toCellBox (const hier::Box &box)
Convert an AMR index box space box into a cell geometry box. A cell geometry box is the same as the given AMR index box space box.
static void transform (CellIndex &index, const hier::Transformation &transformation)
Transform a CellIndex.
static CellIterator begin (const hier::Box &box)
static CellIterator end (const hier::Box &box)
Detailed Description
Class CellGeometry manages the mapping between the AMR index space and the cell-centered geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between cell- centered box geometries for communication operations.
See header file for CellData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
pdat::CellOverlap
Member Typedef Documentation
typedef CellOverlap SAMRAI::pdat::CellGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::CellGeometry::CellGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct the cell geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim()== ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::CellGeometry::~CellGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
static hier::Box SAMRAI::pdat::CellGeometry::toCellBox (const hier::Box & box) [inline, static]
Convert an AMR index box space box into a cell geometry box. A cell geometry box is the same as the given AMR index box space box.
void SAMRAI::pdat::CellGeometry::transform (CellIndex & index, const hier::Transformation & transformation) [static]
Transform a CellIndex.
This static method applies a coordinate system transformation to the given CellIndex.
Parameters:
[in,out] index
[in] transformation
References SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ERROR.
Referenced by SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions().
CellIterator SAMRAI::pdat::CellGeometry::begin (const hier::Box & box) [static]
Referenced by SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), and SAMRAI::pdat::CellData< TYPE >::print().
CellIterator SAMRAI::pdat::CellGeometry::end (const hier::Box & box) [static]
Referenced by SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), and SAMRAI::pdat::CellData< TYPE >::print().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::CellGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in cell-centered index space between the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::pdat::CellGeometry::computeDestinationBoxes (hier::BoxContainer & dst_boxes, const CellGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const hier::BoxContainer & dst_restrict_boxes) const
Compute the cell-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxContainer::intersectBoxes(), SAMRAI::hier::BoxContainer::isEmpty(), SAMRAI::hier::BoxContainer::pushBack(), SAMRAI::hier::BoxContainer::removeIntersections(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::hier::Transformation::transform().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::CellGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a CellOverlap object that consists simply of the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
const hier::Box& SAMRAI::pdat::CellGeometry::getBox () const [inline]
Return the box for this cell centered box geometry object.
const hier::IntVector& SAMRAI::pdat::CellGeometry::getGhosts () const [inline]
Return the ghost cell width for this cell centered box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/CellGeometry.h
source/SAMRAI/pdat/CellGeometry.C