SAMRAI: SAMRAI::hier::BoxTree Class Reference
SAMRAI::hier::BoxTree Class Reference
Utility sorting Boxes into tree-like form for finding box overlaps.
#include <source/SAMRAI/hier/BoxTree.h>
Public Member Functions
~BoxTree ()
Destructor.
Static Public Member Functions
static void printStatistics (const tbox::Dimension &dim)
Print statistics on number of constructor calls, tree builds, tree searches, etc.
static void resetStatistics (const tbox::Dimension &dim)
Reset statistics on number of constructor calls, tree builds, tree searches, etc.
Friends
class MultiblockBoxTree
Detailed Description
Utility sorting Boxes into tree-like form for finding box overlaps.
This class recursively splits a set of Boxes into tree-like form and stores them for fast searches. The recursive splitting stops when the number of boxes in a leaf node of the tree is less than a minimum number specified in the constructor.
All boxes in a BoxTree must exist in the same index space. This means that they must all have the same BlockId value.
Overlap searches are done by
hasOverlap()
findOverlapBoxes()
Except for two static methods and a destructor needed by boost shared_ptr, the entire interface is private.
Constructor & Destructor Documentation
SAMRAI::hier::BoxTree::~BoxTree ()
Destructor.
Member Function Documentation
void SAMRAI::hier::BoxTree::printStatistics (const tbox::Dimension & dim) [static]
Print statistics on number of constructor calls, tree builds, tree searches, etc.
This method is for developers to analyze performance.
References SAMRAI::tbox::SAMRAI_MPI::AllReduce(), SAMRAI::tbox::Statistician::finalize(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::tbox::Statistician::getStatistic(), SAMRAI::tbox::Statistician::getStatistician(), SAMRAI::tbox::Dimension::getValue(), MPI_MAX, MPI_MIN, MPI_SUM, and SAMRAI::tbox::plog.
void SAMRAI::hier::BoxTree::resetStatistics (const tbox::Dimension & dim) [static]
Reset statistics on number of constructor calls, tree builds, tree searches, etc.
This method is for developers to analyze performance.
References SAMRAI::tbox::Dimension::getValue().
Friends And Related Function Documentation
friend class MultiblockBoxTree [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxTree.h
source/SAMRAI/hier/BoxTree.C