SAMRAI: SAMRAI::math::PatchFaceDataOpsInteger Class Reference
SAMRAI::math::PatchFaceDataOpsInteger Class Reference
#include <source/SAMRAI/math/PatchFaceDataOpsInteger.h>
Public Member Functions
PatchFaceDataOpsInteger ()
virtual ~PatchFaceDataOpsInteger ()
int numberOfEntries (const boost::shared_ptr< pdat::FaceData< int > > &data, const hier::Box &box) const
void copyData (const boost::shared_ptr< pdat::FaceData< int > > &dst, const boost::shared_ptr< pdat::FaceData< int > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::FaceData< int > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::FaceData< int > > &dst, const int &alpha, const hier::Box &box) const
void abs (const boost::shared_ptr< pdat::FaceData< int > > &dst, const boost::shared_ptr< pdat::FaceData< int > > &src, const hier::Box &box) const
Detailed Description
Class PatchFaceDataOpsInteger provides a collection of operations that may be used to manipulate integer face-centered patch data. The operations include basic arithmetic, min, max, etc. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base class PatchFaceDataBasicOps from which it is derived.
A more extensive set of operations is implemented for real (double and float) and complex patch data in the classes PatchFaceDataOpsReal and PatchFaceDataOpsComplex, repsectively.
See also:
math::PatchFaceDataBasicOps
Constructor & Destructor Documentation
SAMRAI::math::PatchFaceDataOpsInteger::PatchFaceDataOpsInteger ()
Empty constructor and destructor.
SAMRAI::math::PatchFaceDataOpsInteger::~PatchFaceDataOpsInteger () [virtual]
Member Function Documentation
int SAMRAI::math::PatchFaceDataOpsInteger::numberOfEntries (const boost::shared_ptr< pdat::FaceData< int > > & data, const hier::Box & box) const
Return the number of data values for the face-centered data object in the given box. Note that it is assumed that the box refers to the cell-centered index space corresponding to the patch hierarchy.
Precondition:
data
data->getDim() == box.getDim()
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::size(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
Referenced by SAMRAI::math::HierarchyFaceDataOpsInteger::numberOfEntries().
void SAMRAI::math::PatchFaceDataOpsInteger::copyData (const boost::shared_ptr< pdat::FaceData< int > > & dst, const boost::shared_ptr< pdat::FaceData< int > > & src, const hier::Box & box) const
Copy dst data to src data over given box.
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::FaceGeometry::toFaceBox().
Referenced by SAMRAI::math::HierarchyFaceDataOpsInteger::copyData().
void SAMRAI::math::PatchFaceDataOpsInteger::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::FaceData<int> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::FaceData<int> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyFaceDataOpsInteger::swapData().
void SAMRAI::math::PatchFaceDataOpsInteger::printData (const boost::shared_ptr< pdat::FaceData< int > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyFaceDataOpsInteger::printData().
void SAMRAI::math::PatchFaceDataOpsInteger::setToScalar (const boost::shared_ptr< pdat::FaceData< int > > & dst, const int & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyFaceDataOpsInteger::setToScalar().
void SAMRAI::math::PatchFaceDataOpsInteger::abs (const boost::shared_ptr< pdat::FaceData< int > > & dst, const boost::shared_ptr< pdat::FaceData< int > > & src, const hier::Box & box) const
Set destination component to absolute value of source component. That is, each destination entry is set to .
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::FaceGeometry::toFaceBox().
Referenced by SAMRAI::math::HierarchyFaceDataOpsInteger::abs().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchFaceDataOpsInteger.h
source/SAMRAI/math/PatchFaceDataOpsInteger.C