SAMRAI: SAMRAI::pdat::SideIterator Class Reference
SAMRAI::pdat::SideIterator Class Reference
#include <source/SAMRAI/pdat/SideIterator.h>
Public Member Functions
SideIterator (const SideIterator &iterator)
SideIterator & operator= (const SideIterator &iterator)
~SideIterator ()
const SideIndex & operator* () const
const SideIndex * operator-> () const
SideIterator & operator++ ()
SideIterator operator++ (int)
bool operator== (const SideIterator &iterator) const
bool operator!= (const SideIterator &iterator) const
Friends
SideIterator SideGeometry::begin (const hier::Box &box, tbox::Dimension::dir_t axis)
SideIterator SideGeometry::end (const hier::Box &box, tbox::Dimension::dir_t axis)
Detailed Description
Class SideIterator is an iterator that provides methods for stepping through the index space associated with a side centered box. The indices are enumerated in column-major (e.g., Fortran) order. The iterator should be used as follows:
 * hier::Box box;
 * ...
 * SideIterator cend(box, axis, false);
 * for (SideIterator c(box, axis, true); c != cend; ++c) {
 *    // use index c of the box
 * }
 *
Note that the side iterator may not compile to efficient code, depending on your compiler. Many compilers are not smart enough to optimize the looping constructs and indexing operations.
See also:
pdat::SideData
pdat::SideGeometry
pdat::SideIndex
Constructor & Destructor Documentation
SAMRAI::pdat::SideIterator::SideIterator (const SideIterator & iterator)
Copy constructor for the side iterator
SAMRAI::pdat::SideIterator::~SideIterator ()
Destructor for the side iterator.
Member Function Documentation
SideIterator& SAMRAI::pdat::SideIterator::operator= (const SideIterator & iterator) [inline]
Assignment operator for the side iterator.
const SideIndex& SAMRAI::pdat::SideIterator::operator* () const [inline]
Extract the side index corresponding to the iterator position in the box.
const SideIndex* SAMRAI::pdat::SideIterator::operator-> () const [inline]
Extract a pointer to the side index corresponding to the iterator position in the box.
SideIterator & SAMRAI::pdat::SideIterator::operator++ ()
Pre-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
SideIterator SAMRAI::pdat::SideIterator::operator++ (int)
Post-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
bool SAMRAI::pdat::SideIterator::operator== (const SideIterator & iterator) const [inline]
Test two iterators for equality (same index value).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
bool SAMRAI::pdat::SideIterator::operator!= (const SideIterator & iterator) const [inline]
Test two iterators for inequality (different index values).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
Friends And Related Function Documentation
SideIterator SideGeometry::begin (const hier::Box & box, tbox::Dimension::dir_t axis) [friend]
SideIterator SideGeometry::end (const hier::Box & box, tbox::Dimension::dir_t axis) [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/SideIterator.h
source/SAMRAI/pdat/SideIterator.C