SAMRAI: SAMRAI::pdat::OutersideGeometry Class Reference
SAMRAI::pdat::OutersideGeometry Class Reference
#include <source/SAMRAI/pdat/OutersideGeometry.h>
Public Types
typedef SideOverlap Overlap
Public Member Functions
OutersideGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct an outerside geometry object given an AMR index space box and ghost cell width.
virtual ~OutersideGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in side-centered index space on the boundaries of the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a SideOverlap object based on the given boxes and the offset.
const hier::Box & getBox () const
Return the box for this outerside box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this outerside box geometry object.
Detailed Description
Class OutersideGeometry manages the mapping between the AMR index and the outerside geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between outerside box geometries and side or outerside box geometries for communication operations.
See header file for OutersideData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
pdat::SideGeometry
pdat::SideOverlap
Member Typedef Documentation
typedef SideOverlap SAMRAI::pdat::OutersideGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::OutersideGeometry::OutersideGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct an outerside geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim() == ghosts.getDim
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::OutersideGeometry::~OutersideGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OutersideGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in side-centered index space on the boundaries of the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OutersideGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a SideOverlap object based on the given boxes and the offset.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getOffset(), and SAMRAI::pdat::SideGeometry::toSideBox().
const hier::Box& SAMRAI::pdat::OutersideGeometry::getBox () const [inline]
Return the box for this outerside box geometry object.
const hier::IntVector& SAMRAI::pdat::OutersideGeometry::getGhosts () const [inline]
Return the ghost cell width for this outerside box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OutersideGeometry.h
source/SAMRAI/pdat/OutersideGeometry.C