SAMRAI: SAMRAI::hier::Variable Class Reference
SAMRAI::hier::Variable Class Reference
#include <source/SAMRAI/hier/Variable.h>
Public Member Functions
Variable (const std::string &name, const boost::shared_ptr< PatchDataFactory > &factory)
virtual ~Variable ()
int getInstanceIdentifier () const
const std::string & getName () const
virtual bool fineBoundaryRepresentsVariable () const =0
virtual bool dataLivesOnPatchBorder () const =0
void setPatchDataFactory (const boost::shared_ptr< PatchDataFactory > &factory)
boost::shared_ptr
< PatchDataFactory > getPatchDataFactory () const
const tbox::Dimension & getDim () const
Static Public Member Functions
static int getCurrentMaximumInstanceNumber ()
Detailed Description
Class Variable provides a description of a variable quantity in an AMR application. A variable has the following attributes: (1) a name, (2) a unique instance number, and (3) a way to create the proper type of storage on the patches in an AMR hierarchy.
Variable is a base class for all variables; subclasses for each data type (e.g., cell-centered variables or node-centered variables) will define member functions to create the appropriate storage management classes. Note that a variable object is distinct from the storage for the quantity to which the variable refers.
The user defines a set of variables and the role they play in the solution algorithm when describing an AMR application. Each variable type knows how to create instances of the associated data objects on patches in an AMR patch hierarchy via the getPatchDataFactory() member function. For example, we might have a concrete myVariable3<double> object that is derived from Variable3. The myVariable3<double> object returns a myVariableFactory3<double> object from its member function getPatchDataFactory(), and this factory is used to create the myVariable3<double> objects on the patches. Thus, a solution algorithm may be implemented to manage storage of variable quantities through the abstract interface without knowing the specific concrete variable types in use. This approach gives maximum flexibility when defining new user data types and variables and solution algorithms.
Each variable is assigned an ``instance number,'' a unique integer identifier numbered from 0 through MAX-1, where MAX is the value returned by static function getCurrentMaximumInstanceNumber(). These identifiers can be used to rapidly look up variable instances in a table. For example, the instance number can be used to map variables to algorithmic data within an algorithm as alluded to above..
Variable types for which data exists on the borders of patches (such as node, side, etc.), the data will thus live on the interface between coarse and fine patch levels. Thus, it must be specified whether coarse or fine data values take precedence on the interface between levels. This information is provided by the fineBoundaryRepresentsVariable() function. Each concrete variable subclass defines the behavior of this function.
See also:
hier::PatchDataFactory
Constructor & Destructor Documentation
SAMRAI::hier::Variable::Variable (const std::string & name, const boost::shared_ptr< PatchDataFactory > & factory)
Create a variable object with the specified name and patch data factory. On creation, each variable is assigned a unique instance identifier.
SAMRAI::hier::Variable::~Variable () [virtual]
Virtual destructor for variable objects.
Member Function Documentation
static int SAMRAI::hier::Variable::getCurrentMaximumInstanceNumber () [inline, static]
Return the current maximum instance number over all variable objects. The instance identifier returned from each variable objhect is guaranteed to be between 0 and this number minus one. Note that this number changes as new variable instances are created.
int SAMRAI::hier::Variable::getInstanceIdentifier () const [inline]
Return the instance identifier for this particular variable object. The instance identifiers are unique integers numbered starting from zero.
const std::string& SAMRAI::hier::Variable::getName (void) const [inline]
Return the name assigned to this variable.
virtual bool SAMRAI::hier::Variable::fineBoundaryRepresentsVariable () const [pure virtual]
Return true if the fine data values represent the variable quantity on coarse-fine interfaces if variable data lives on patch borders; false otherwise. The boolean return value is supplied by the concrete variable subclass.
Implemented in SAMRAI::pdat::CellVariable< TYPE >, SAMRAI::pdat::EdgeVariable< TYPE >, SAMRAI::pdat::FaceVariable< TYPE >, SAMRAI::pdat::IndexVariable< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeVariable< TYPE >, SAMRAI::pdat::OuteredgeVariable< TYPE >, SAMRAI::pdat::OuterfaceVariable< TYPE >, SAMRAI::pdat::OuternodeVariable< TYPE >, SAMRAI::pdat::OutersideVariable< TYPE >, and SAMRAI::pdat::SideVariable< TYPE >.
virtual bool SAMRAI::hier::Variable::dataLivesOnPatchBorder () const [pure virtual]
Return true if the variable data lives on patch borders; false otherwise. The boolean return value is supplied by the concrete variable subclass.
Implemented in SAMRAI::pdat::CellVariable< TYPE >, SAMRAI::pdat::EdgeVariable< TYPE >, SAMRAI::pdat::FaceVariable< TYPE >, SAMRAI::pdat::IndexVariable< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeVariable< TYPE >, SAMRAI::pdat::OuteredgeVariable< TYPE >, SAMRAI::pdat::OuterfaceVariable< TYPE >, SAMRAI::pdat::OuternodeVariable< TYPE >, SAMRAI::pdat::OutersideVariable< TYPE >, and SAMRAI::pdat::SideVariable< TYPE >.
void SAMRAI::hier::Variable::setPatchDataFactory (const boost::shared_ptr< PatchDataFactory > & factory) [inline]
Set the patch data factory object. Normally, the factory is set in the constructor, but this member function enables the factory to be changed later in the lifetime of the variable.
Precondition:
getDim() == factory->getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr<PatchDataFactory> SAMRAI::hier::Variable::getPatchDataFactory () const [inline]
Return a non-const pointer to a patch data factory that will be used to instantiate instances of this variable on the patches. The factory returned will have been set by the variable subclasses.
Referenced by SAMRAI::pdat::SideVariable< TYPE >::getDepth(), SAMRAI::pdat::OutersideVariable< TYPE >::getDepth(), SAMRAI::pdat::OuternodeVariable< TYPE >::getDepth(), SAMRAI::pdat::OuterfaceVariable< TYPE >::getDepth(), SAMRAI::pdat::OuteredgeVariable< TYPE >::getDepth(), SAMRAI::pdat::NodeVariable< TYPE >::getDepth(), SAMRAI::pdat::FaceVariable< TYPE >::getDepth(), SAMRAI::pdat::EdgeVariable< TYPE >::getDepth(), and SAMRAI::pdat::CellVariable< TYPE >::getDepth().
const tbox::Dimension& SAMRAI::hier::Variable::getDim () const [inline]
Return the dimension of this object.
Referenced by SAMRAI::pdat::SideVariable< TYPE >::SideVariable().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/Variable.h
source/SAMRAI/hier/Variable.C