SAMRAI: SAMRAI::tbox::Statistician Class Reference
SAMRAI::tbox::Statistician Class Reference
#include <source/SAMRAI/tbox/Statistician.h>
Public Member Functions
boost::shared_ptr< Statistic > getStatistic (const std::string &name, const std::string &stat_type)
bool checkStatisticExists (boost::shared_ptr< Statistic > &stat, const std::string &name) const
int getNumberProcessorStats () const
int getNumberPatchStats () const
void resetProcessorStatistics ()
void resetPatchStatistics ()
void resetStatistics ()
int getProcStatId (const std::string &name) const
int getGlobalProcStatSequenceLength (int proc_stat_id)
double getGlobalProcStatValue (int proc_stat_id, int seq_num, int proc_num)
double getGlobalProcStatSum (int proc_stat_id, int seq_num)
double getGlobalProcStatMax (int proc_stat_id, int seq_num)
int getGlobalProcStatMaxProcessorId (int proc_stat_id, int seq_num)
double getGlobalProcStatMin (int proc_stat_id, int seq_num)
int getGlobalProcStatMinProcessorId (int proc_stat_id, int seq_num)
void printGlobalProcStatData (int proc_stat_id, std::ostream &os, int precision=12)
void printGlobalProcStatDataFormatted (int proc_stat_id, std::ostream &os, int precision=12)
void printGlobalProcStatDataFormatted (int proc_stat_id, int proc_id, std::ostream &os, int precision=12)
int getPatchStatId (const std::string &name) const
int getGlobalPatchStatSequenceLength (int patch_stat_id)
int getGlobalPatchStatNumberPatches (int patch_stat_id, int seq_num)
int getGlobalPatchStatPatchMapping (int patch_stat_id, int seq_num, int patch_num)
double getGlobalPatchStatValue (int patch_stat_id, int seq_num, int patch_num)
double getGlobalPatchStatSum (int patch_stat_id, int seq_num)
double getGlobalPatchStatMax (int patch_stat_id, int seq_num)
int getGlobalPatchStatMaxPatchId (int patch_stat_id, int seq_num)
double getGlobalPatchStatMin (int patch_stat_id, int seq_num)
int getGlobalPatchStatMinPatchId (int patch_stat_id, int seq_num)
double getGlobalPatchStatProcessorSum (int patch_stat_id, int processor_id, int seq_num)
double getGlobalPatchStatProcessorSumMax (int patch_stat_id, int seq_num)
int getGlobalPatchStatProcessorSumMaxId (int patch_stat_id, int seq_num)
double getGlobalPatchStatProcessorSumMin (int patch_stat_id, int seq_num)
int getGlobalPatchStatProcessorSumMinId (int patch_stat_id, int seq_num)
int getGlobalPatchStatNumberPatchesOnProc (int patch_stat_id, int seq_num, int proc_id)
int getGlobalPatchStatMaxPatchesPerProc (int patch_stat_id, int seq_num)
int getGlobalPatchStatMaxPatchesPerProcId (int patch_stat_id, int seq_num)
int getGlobalPatchStatMinPatchesPerProc (int patch_stat_id, int seq_num)
int getGlobalPatchStatMinPatchesPerProcId (int patch_stat_id, int seq_num)
void printGlobalPatchStatData (int patch_stat_id, std::ostream &os, int precision=12)
void printGlobalPatchStatDataFormatted (int patch_stat_id, std::ostream &os, int precision=12)
void finalize (bool gather_individual_stats_on_proc_0=false)
void printLocalStatData (std::ostream &os, int precision=12) const
void printAllGlobalStatData (std::ostream &os, int precision=12)
void printAllSummedGlobalStatData (std::ostream &os, int precision=12)
void printAllSummedGlobalStatData (const std::string &filename, int precision=12)
void printSpreadSheetOutput (const std::string &dirname=std::string(), int precision=12)
void printSpreadSheetOutputForProcessor (const int proc_id, const std::string &dirname=std::string(), int precision=12)
Static Public Member Functions
static Statistician * createStatistician (bool read_from_restart=true)
static Statistician * getStatistician ()
Protected Member Functions
Statistician ()
~Statistician ()
void registerSingletonSubclassInstance (Statistician *subclass_instance)
void checkStatsForConsistency (std::vector< int > &total_patches)
bool checkProcStatExists (boost::shared_ptr< Statistic > &stat, const std::string &name) const
bool checkPatchStatExists (boost::shared_ptr< Statistic > &stat, const std::string &name) const
Friends
class StatisticRestartDatabase
Detailed Description
Class Statistician is a Singleton class that manages a simple database of Statistic objects. This class provides a single point of access to statistic objects so that any one of them may be updated or recorded at any point in the code. Access to the Singleton statistician instance follows the standard SAMRAI implementation found in other classes with similar Singleton behavior. See static member functions below for more information.
Statistic objects can be to the database or accessed in code as follows:
boost::shared_ptr<Statistic> stat = Statistician::getStatistician-> getStatistic("name", "PROC_STAT");
Here `name' is the name string identifier for the statistic object and `PROC_STAT' is the type of statistic. See discussion for the getStatistic() method below for more information.
The statistic state is saved to restart files when restart file generation is active. This allows users to continue to accumulate timing information when restarting a run. If desired, all statistics can be reset when restarting by calling the function resetAllStatistics().
A variety of print options exist to dump statistics data. Notably, the printSpreadSheetOutput("print_dir") will write statistics data in a tab-separated format to files in the supplied directory name. The naming convention for statistics data is "\<name\>-\<type\>.txt" where <name> is the name of the statistic and <type> is either proc or patch stat. The files may be read in to a spreadsheet program such as MS Excel.
For more information about data that can be recorded with statistics, consult the header file for the Statistic class.
See also:
tbox::Statistic
Constructor & Destructor Documentation
SAMRAI::tbox::Statistician::Statistician () [protected]
The constructor for Statistician is protected. Consistent with the definition of a Singleton class, only a statistician object can have access to the constructor for the class.
SAMRAI::tbox::Statistician::~Statistician () [protected]
Statistician is a Singleton class; its destructor is protected.
Member Function Documentation
Statistician * SAMRAI::tbox::Statistician::createStatistician (bool read_from_restart = true) [static]
Create the singleton instance of the statistic manager and return a pointer to it. This function is provided so that so that users can control whether statistic information will be written to/read from restart files.
Statistics that exist in the restart file will be read from restart when a run is restarted and the second argument is true.
Generally, this routine should only be called once during program execution. If the statistician has been previously created (e.g., by an earlier call to this routine) this routine will do nothing other than return the pointer to the existing singleton instance.
Statistician * SAMRAI::tbox::Statistician::getStatistician () [static]
Return a pointer to the singleton statistician instance. All access to the Statistician object is through the getStatistician() function. For example, to add a statistic object with the name "my_stat" to the statistician, use the following call: Statistician::getStatistician()->addStatistic("my_stat").
Precondition:
s_statistician_instance
References TBOX_ASSERT.
Referenced by SAMRAI::tbox::StatisticRestartDatabase::getFromRestart(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), SAMRAI::mesh::GriddingAlgorithm::printStatistics(), SAMRAI::hier::BoxTree::printStatistics(), and SAMRAI::tbox::StatisticRestartDatabase::putToRestart().
boost::shared_ptr< Statistic > SAMRAI::tbox::Statistician::getStatistic (const std::string & name, const std::string & stat_type)
Return pointer to statistic object with the given name string. If a statistics with the given name already exists in the database of statistics, the statistic with that name will be returned. Otherwise, a new statistic will be created with that name. The stat_type string identifier is only used when a new statistic object must be created. The two avaible options are processor statistics and patch statistics which are indicated by the strings "PROC_STAT" and "PATCH_STAT", respectively.
Precondition:
!name.empty()
!stat_type.empty()
(stat_type == "PROC_STAT") || (stat_type == "PATCH_STAT")
References TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::tbox::StatisticRestartDatabase::getFromRestart(), and SAMRAI::hier::BoxTree::printStatistics().
bool SAMRAI::tbox::Statistician::checkStatisticExists (boost::shared_ptr< Statistic > & stat, const std::string & name) const
Return true if a statistic whose name matches the argument string exists in the database of statistics controlled by the statistician. If a match is found, the statistic pointer in the argument list is set to that statistic. Otherwise, return false and return a null pointer.
Precondition:
!name.empty()
References checkPatchStatExists(), checkProcStatExists(), and TBOX_ASSERT.
int SAMRAI::tbox::Statistician::getNumberProcessorStats () const [inline]
Return integer number of local processor statistics maintained by statistician.
Referenced by SAMRAI::tbox::StatisticRestartDatabase::putToRestart().
int SAMRAI::tbox::Statistician::getNumberPatchStats () const [inline]
Return integer number of local patch statistics maintained by statistician.
Referenced by SAMRAI::tbox::StatisticRestartDatabase::putToRestart().
void SAMRAI::tbox::Statistician::resetProcessorStatistics ()
Reset all processor statistics to contain no information. The primary intent of this function is to avoid using restarted statistic values when performing a restarted run. However, it can be called anytime.
Referenced by resetStatistics().
void SAMRAI::tbox::Statistician::resetPatchStatistics ()
Reset all patch statistics to contain no information. The primary intent of this function is to avoid using restarted statistic values when performing a restarted run. However, it can be called anytime.
Referenced by resetStatistics().
void SAMRAI::tbox::Statistician::resetStatistics ()
Reset all patch and processor statistics to contain no information.
References resetPatchStatistics(), and resetProcessorStatistics().
int SAMRAI::tbox::Statistician::getProcStatId (const std::string & name) const
Return integer instance identifier for processor statistic with given name. If this statistician object maintains no processor statistic with that name, then a warning message results and the return value will be the invalid instance identifier "-1".
References checkProcStatExists().
int SAMRAI::tbox::Statistician::getGlobalProcStatSequenceLength (int proc_stat_id)
Return number of sequence entries for processor statistic with given integer identifier. For convenience, the routine getProcStatId() is provided to map the statistic string name to the proper integer identifier.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_state && (proc_stat_id >= 0) && (proc_stat_id < static_cast<int>(d_global_proc_stat_data.size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printAllSummedGlobalStatData().
double SAMRAI::tbox::Statistician::getGlobalProcStatValue (int proc_stat_id, int seq_num, int proc_num)
Return statistic data value for processor statistic with given integer identifier, sequence number, and processor number. For convenience, the routine getProcStatId() is provided to map the statistic string name to the proper integer identifier. The function getGlobalProcStatSequenceLength() provides the sequence length for a given processor statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_state && (proc_stat_id >= 0) && (proc_stat_id < static_cast<int>(d_global_proc_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_proc_stat_data[proc_stat_id].size())) && (proc_num < SAMRAI_MPI::getSAMRAIWorld().getSize()))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalProcStatSum (int proc_stat_id, int seq_num)
Return global sum of processor statistic with given integer identifier and sequence number. To identify the correct integer identifier and valid sequence numbers, the method getProcStatId() maps the statistic string name to its integer identifier and the method getGlobalProcStatSequenceLength() returns the maximum sequence length for the processor statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && (proc_stat_id >= 0) && (proc_stat_id < static_cast<int>(d_global_proc_stat_sum.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_proc_stat_sum[proc_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printAllSummedGlobalStatData().
double SAMRAI::tbox::Statistician::getGlobalProcStatMax (int proc_stat_id, int seq_num)
Return global max of processor statistic with given integer identifier and sequence number. To identify the correct integer identifier and valid sequence numbers, the method getProcStatId() maps the statistic string name to its integer identifier and the method getGlobalProcStatSequenceLength() returns the maximum sequence length for the processor statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && (proc_stat_id >= 0) && (proc_stat_id < static_cast<int>(d_global_proc_stat_max.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_proc_stat_max[proc_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalProcStatMaxProcessorId (int proc_stat_id, int seq_num)
Returns rank of processor holding global max for the processor statistic specified by the given integer identifyer and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && (proc_stat_id >= 0) && (proc_stat_id < static_cast<int>(d_global_proc_stat_imax.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_proc_stat_imax[proc_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalProcStatMin (int proc_stat_id, int seq_num)
Return global min of processor statistic with given integer identifier and sequence number. To identify the correct integer identifier and valid sequence numbers, the method getProcStatId() maps the statistic string name to its integer identifier and the method getGlobalProcStatSequenceLength() returns the maximum sequence length for the processor statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && (proc_stat_id >= 0) && (proc_stat_id < static_cast<int>(d_global_proc_stat_min.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_proc_stat_min[proc_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalProcStatMinProcessorId (int proc_stat_id, int seq_num)
Returns rank of processor holding global max for the processor statistic specified by the given integer identifyer and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && (proc_stat_id >= 0) && (proc_stat_id < static_cast<int>(d_global_proc_stat_imin.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_proc_stat_imin[proc_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::tbox::Statistician::printGlobalProcStatData (int proc_stat_id, std::ostream & os, int precision = 12)
Print global processor statistic data for a particular statistic to given output stream. Floating point precision may be specified (default is 12). Note that this method generates a general dump of the data but does NOT generate it in tabulated form. To generate tabulated data, see the printGlobalProcStatDataFormatted() method.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (proc_stat_id >= 0) && (precision > 0))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printAllGlobalStatData().
void SAMRAI::tbox::Statistician::printGlobalProcStatDataFormatted (int proc_stat_id, std::ostream & os, int precision = 12)
Print processor stat data in formatted output to given output stream. Floating point precision may be specified (default is 12).
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (proc_stat_id >= 0) && (precision > 0))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printSpreadSheetOutput(), and printSpreadSheetOutputForProcessor().
void SAMRAI::tbox::Statistician::printGlobalProcStatDataFormatted (int proc_stat_id, int proc_id, std::ostream & os, int precision = 12)
Print stat data for specified processor in formatted output to given output stream. Floating point precision may be specified (default is 12).
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (proc_stat_id >= 0) && (proc_id >= 0) && (precision > 0))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getPatchStatId (const std::string & name) const
Return integer instance identifier for patch statistic with given name. If this statistician object maintains no patch statistic with that name, then a warning message results and the return value will be the invalid instance identifier "-1".
References checkPatchStatExists().
int SAMRAI::tbox::Statistician::getGlobalPatchStatSequenceLength (int patch_stat_id)
Return number of sequence entries for patch statistic with given integer identifier. For convenience, the routine getPatchStatId() is provided to map the statistic string name to the proper integer identifier.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printAllSummedGlobalStatData().
int SAMRAI::tbox::Statistician::getGlobalPatchStatNumberPatches (int patch_stat_id, int seq_num)
Return number of patch entries for patch statistic with given integer identifier, and sequence number. For convenience, the routine getPatchStatId() is provided to map the statistic string name to the proper integer identifier. The function getGlobalPatchStatSequenceLength() provides the sequence length for a given patch statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatPatchMapping (int patch_stat_id, int seq_num, int patch_num)
Return global processor mapping for patch statistic with given integer identifier, sequence number, and patch number. For convenience, the routine getPatchStatId() is provided to map the statistic string name to the proper integer identifier. The function getGlobalPatchStatSequenceLength() provides the sequence length for a given patch statistic. The function getGlobalPatchStatNumberPatches() gives the number of patches associated with a patch statistic and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_mapping.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_mapping[patch_stat_id].size())) && (patch_num >= 0) && (patch_num < static_cast<int>(d_global_patch_stat_mapping[patch_stat_id][seq_num].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalPatchStatValue (int patch_stat_id, int seq_num, int patch_num)
Return statistic data value for patch statistic with given integer identifier, sequence number, and patch number. For convenience, the routine getPatchStatId() is provided to map the statistic string name to the proper integer identifier. The function getGlobalPatchStatSequenceLength() provides the sequence length for a given patch statistic. The function getGlobalPatchStatNumberPatches() gives the number of patches associated with a patch statistic and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())) && (patch_num >= 0) && (patch_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id][seq_num].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalPatchStatSum (int patch_stat_id, int seq_num)
Return global sum of patch statistic with given integer identifier and sequence number. To identify the correct integer identifier and valid sequence numbers, the method getPatchStatId() maps the statistic string name to its integer identifier and the method getGlobalPatchStatSequenceLength() returns the maximum sequence length for the processor statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printAllSummedGlobalStatData().
double SAMRAI::tbox::Statistician::getGlobalPatchStatMax (int patch_stat_id, int seq_num)
Return global max of patch statistic with given integer identifier and sequence number. To identify the correct integer identifier and valid sequence numbers, the method getPatchStatId() maps the statistic string name to its integer identifier and the method getGlobalPatchStatSequenceLength() returns the maximum sequence length for the processor statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchId (int patch_stat_id, int seq_num)
Returns ID of patch holding global max for the patch statistic specified by the given integer identifyer and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalPatchStatMin (int patch_stat_id, int seq_num)
Return global min of patch statistic with given integer identifier and sequence number. To identify the correct integer identifier and valid sequence numbers, the method getPatchStatId() maps the statistic string name to its integer identifier and the method getGlobalPatchStatSequenceLength() returns the maximum sequence length for the processor statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchId (int patch_stat_id, int seq_num)
Returns patch ID of patch holding global min for the patch statistic specified by the given integer identifyer and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSum (int patch_stat_id, int processor_id, int seq_num)
Returns the sum of patch statistic information for a particular processor. The patch statistic is specified by its integer identifyer and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (processor_id >= 0) && (processor_id < SAMRAI_MPI::getSAMRAIWorld().getSize()) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMax (int patch_stat_id, int seq_num)
Returns the maximum value of the patch statistic data summed on each processor. That is, patch statistic information is summed on each processor, and this method returns the maximum value, across all processors, of this summed data. The patch statistic is specified by its integer identifyer and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMaxId (int patch_stat_id, int seq_num)
Returns the processor ID which holds the maximum value of summed patch statistic information across processors. See the discussion for the method getGlobalPatchStatProcessorSumMax() for more information on the summed patch statistic information on processors.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
double SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMin (int patch_stat_id, int seq_num)
Returns the minimum value of the patch statistic data summed on each processor. That is, patch statistic information is summed on each processor, and this method returns the minimum value, across all processors, of this summed data. The patch statistic is specified by its integer identifyer and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMinId (int patch_stat_id, int seq_num)
Returns the processor ID which holds the minimum value of summed patch statistic information across processors. See the discussion for the method getGlobalPatchStatProcessorSumMin() for more information on the summed patch statistic information on processors.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatNumberPatchesOnProc (int patch_stat_id, int seq_num, int proc_id)
Return number of patches on the specified processor number for patch statistic with given identifier, and sequence number.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())) && (proc_id >= 0 && proc_id < SAMRAI_MPI::getSAMRAIWorld().getSize()))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProc (int patch_stat_id, int seq_num)
Returns the maximum number of patches per processor for the specified patch statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProcId (int patch_stat_id, int seq_num)
Returns the processor ID holding the maximum number of patches per processor for the specified patch statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProc (int patch_stat_id, int seq_num)
Returns the minimum number of patches per processor for the specified patch statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())) && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProcId (int patch_stat_id, int seq_num)
Returns the processor ID holding the minimum number of patches per processor for the specified patch statistic.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats && (patch_stat_id >= 0) && (patch_stat_id < static_cast<int>(d_global_patch_stat_proc_data.size())) && (seq_num >= 0) && (seq_num < static_cast<int>(d_global_patch_stat_proc_data[patch_stat_id].size())))
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::tbox::Statistician::printGlobalPatchStatData (int patch_stat_id, std::ostream & os, int precision = 12)
Print global processor statistic data for a particular statistic to given output stream. Floating point precision may be specified (default is 12). Note that this method generates a general dump of the data but does NOT generate it in tabulated form. To generate tabulated data, see the printGlobalPatchStatDataFormatted() method.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (patch_stat_id >= 0 && precision > 0)
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printAllGlobalStatData().
void SAMRAI::tbox::Statistician::printGlobalPatchStatDataFormatted (int patch_stat_id, std::ostream & os, int precision = 12)
Print patch stat data in formatted output to given output stream. Floating point precision may be specified (default is 12).
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (patch_stat_id >= 0 && precision > 0)
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by printSpreadSheetOutput().
void SAMRAI::tbox::Statistician::finalize (bool gather_individual_stats_on_proc_0 = false)
Typically, this routine is called after a calculation has completed so that statistic data can be retrieved, analized, printed to a file, etc. It is not essential that this routine be called, however, as each "get" and "print" routine checks to see if statistic data has been finalized before it peforms its function.
If gather_individual_stats_on_proc_0 == true, the statistics are gathered on proc 0 for further access. If not, only globally-reduced (min, max, sum) values for "PROC_STATS" are available (on all processes). Non-local "PATCH_STATS" are only available if gather_individual_stats_on_proc_0 == true.
References SAMRAI::tbox::Schedule::addTransaction(), checkStatsForConsistency(), SAMRAI::tbox::Schedule::communicate(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), and SAMRAI::tbox::Schedule::setTimerPrefix().
Referenced by SAMRAI::hier::BoxTree::printStatistics().
void SAMRAI::tbox::Statistician::printLocalStatData (std::ostream & os, int precision = 12) const
Print data to given output stream for local statistics managed by this statistician object. Note that no fancy formatting is done. Floating point precision can be specified (default is 12).
void SAMRAI::tbox::Statistician::printAllGlobalStatData (std::ostream & os, int precision = 12)
Print global statistic data information to given output stream. The data will NOT be in tabulated form. Floating point precision can be specified (default is 12).
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats)
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), printGlobalPatchStatData(), printGlobalProcStatData(), and TBOX_ERROR.
void SAMRAI::tbox::Statistician::printAllSummedGlobalStatData (std::ostream & os, int precision = 12)
Print sums of all global statistic data information to given output stream. Floating point precision can be specified (default is 12).
References getGlobalPatchStatSequenceLength(), getGlobalPatchStatSum(), getGlobalProcStatSequenceLength(), getGlobalProcStatSum(), SAMRAI::tbox::SAMRAI_MPI::getRank(), and SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld().
Referenced by printAllSummedGlobalStatData().
void SAMRAI::tbox::Statistician::printAllSummedGlobalStatData (const std::string & filename, int precision = 12)
Print sums of all global statistic data information to specified filename. Floating point precision can be specified (default is 12).
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and printAllSummedGlobalStatData().
void SAMRAI::tbox::Statistician::printSpreadSheetOutput (const std::string & dirname = std::string(), int precision = 12)
Write all statistics data in tab-separated format to files in the supplied directory name. The naming convention used is "\<name\>-\<type\>.txt" where <name> is the name of the statistic and <type> is either proc or patch stat. Floating point precision may be specified (default is 12). The files may be read in to a spreadsheet program such as MS Excel. If no directory name is supplied, the files will be written to the directory where the application is run.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats)
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), printGlobalPatchStatDataFormatted(), printGlobalProcStatDataFormatted(), SAMRAI::tbox::Utilities::recursiveMkdir(), and TBOX_ERROR.
void SAMRAI::tbox::Statistician::printSpreadSheetOutputForProcessor (const int proc_id, const std::string & dirname = std::string(), int precision = 12)
Write tab-separated statistics data for specified processor. This method is identical to "printSpreadSheetOutput()" (above), but only prints data for a single processor. This may be useful for information that is the same across all processors. This method will only print processor stats. Any patch stats will be ignored.
Precondition:
(SAMRAI_MPI::getSAMRAIWorld().getRank() != 0) || (!d_must_call_finalize && d_has_gathered_stats)
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), printGlobalProcStatDataFormatted(), SAMRAI::tbox::Utilities::processorToString(), SAMRAI::tbox::Utilities::recursiveMkdir(), and TBOX_ERROR.
void SAMRAI::tbox::Statistician::registerSingletonSubclassInstance (Statistician * subclass_instance) [protected]
Initialize Singleton instance with instance of subclass. This function is used to make the singleton object unique when inheriting from this base class.
Precondition:
!s_statistician_instance
References TBOX_ERROR.
void SAMRAI::tbox::Statistician::checkStatsForConsistency (std::vector< int > & total_patches) [protected]
During finalize() check statistic information on all processors for consistency before generating vectors of data.
Precondition:
total_patches.size() == 0
References SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), MPI_INT, MPI_MAX, MPI_MIN, MPI_SUM, TBOX_ASSERT, and TBOX_ERROR.
Referenced by finalize().
bool SAMRAI::tbox::Statistician::checkProcStatExists (boost::shared_ptr< Statistic > & stat, const std::string & name) const [protected]
Return true if a processor statistic whose name matches the argument string exists in the database of statistics controlled by the statistician. If a match is found, the statistic pointer in the argument list is set to that statistic. Otherwise, return false and return a null pointer.
Referenced by checkStatisticExists(), and getProcStatId().
bool SAMRAI::tbox::Statistician::checkPatchStatExists (boost::shared_ptr< Statistic > & stat, const std::string & name) const [protected]
Return true if a patch statistic whose name matches the argument string exists in the database of statistics controlled by the statistician. If a match is found, the statistic pointer in the argument list is set to that statistic. Otherwise, return false and return a null pointer.
Referenced by checkStatisticExists(), and getPatchStatId().
Friends And Related Function Documentation
friend class StatisticRestartDatabase [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Statistician.h
source/SAMRAI/tbox/Statistician.C