SAMRAI: SAMRAI::mesh::TransitLoad Class Reference
SAMRAI::mesh::TransitLoad Class Reference
Base class for container of work in transit during partitioning.
#include <source/SAMRAI/mesh/TransitLoad.h>
Public Member Functions
TransitLoad ()
TransitLoad (const TransitLoad &other)
virtual ~TransitLoad ()
virtual double adjustLoad (TransitLoad &hold_bin, double ideal_load, double low_load, double high_load)=0
Adjust the load in this TransitSet by moving work between it and another TransitSet.
virtual void assignToLocalAndPopulateMaps (hier::BoxLevel &balanced_box_level, hier::MappingConnector &balanced_to_unbalanced, hier::MappingConnector &unbalanced_to_balanced, double flexible_load_tol=0.0)=0
Assign contents to local process and populate the balanced<==>unbalanced maps.
Methods required by prototype design pattern
virtual TransitLoad * clone () const =0
Clone object according to design pattern.
virtual void initialize ()=0
Initialize object according to design pattern.
virtual double getSumLoad () const =0
Container-like characteristics.
virtual void insertAll (const hier::BoxContainer &other)=0
Insert all boxes from the given BoxContainer.
virtual void insertAll (TransitLoad &other)=0
Insert all boxes from the given TransitSet.
virtual size_t getNumberOfItems () const =0
Return number of items in this container.
virtual size_t getNumberOfOriginatingProcesses () const =0
Return number of processes contributing to the contents.
virtual bool empty () const
Whether container is empty.
virtual void clear ()=0
Empty the container.
Parameters in box breaking
void setAllowBoxBreaking (bool allow_box_breaking)
Whether to allow box breaking.
bool getAllowBoxBreaking () const
Whether object may break up boxes.
void setThresholdWidth (double threshold_width)
Set threshold for resisting small and thin boxes.
double getThresholdWidth () const
Return the threshold width for resisting small and thin boxes.
Diagnostic support
virtual void setTimerPrefix (const std::string &)
Set prefix of internal diagnostic timer names.
virtual void recursivePrint (std::ostream &co=tbox::plog, const std::string &border=std::string(), int detail_depth=1) const
Object printing method to aid in debugging.
Packing/unpacking for communication.
virtual void putToMessageStream (tbox::MessageStream &msg) const =0
Put content into MessageStream.
virtual void getFromMessageStream (tbox::MessageStream &msg)=0
Add to content from MessageStream.
tbox::MessageStream & operator<< (tbox::MessageStream &msg, const TransitLoad &transit_load)
tbox::MessageStream & operator>> (tbox::MessageStream &msg, TransitLoad &transit_load)
Detailed Description
Base class for container of work in transit during partitioning.
TransitLoad base class follows the prototype design pattern. Subclasses must implement clone(), initialize(), and a copy constructor according to this design pattern.
TransitLoad has dual responsibilities.
First, it's a container of loads that move around. The implementation may represent the work however it wants and should be able to shift load from one container to another. See adjustLoad().
Second, it generates the mappings between the pre- and post-balance BoxLevels. It must have this responsibility because the implementation alone knows how the work is represented. See assignToLocalAndPopulateMaps().
For usage examples, see mesh::TreeLoadBalancer.
Constructor & Destructor Documentation
SAMRAI::mesh::TransitLoad::TransitLoad ()
SAMRAI::mesh::TransitLoad::TransitLoad (const TransitLoad & other)
virtual SAMRAI::mesh::TransitLoad::~TransitLoad () [inline, virtual]
Member Function Documentation
virtual TransitLoad* SAMRAI::mesh::TransitLoad::clone () const [pure virtual]
Clone object according to design pattern.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
virtual void SAMRAI::mesh::TransitLoad::initialize () [pure virtual]
Initialize object according to design pattern.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
virtual double SAMRAI::mesh::TransitLoad::getSumLoad () const [pure virtual]
Container-like characteristics.
Return the total load contained.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
Referenced by SAMRAI::mesh::VoucherTransitLoad::adjustLoad(), SAMRAI::mesh::CascadePartitionerTree::distributeLoad(), SAMRAI::mesh::CascadePartitionerTree::printClassData(), and recursivePrint().
virtual void SAMRAI::mesh::TransitLoad::insertAll (const hier::BoxContainer & other) [pure virtual]
Insert all boxes from the given BoxContainer.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
virtual void SAMRAI::mesh::TransitLoad::insertAll (TransitLoad & other) [pure virtual]
Insert all boxes from the given TransitSet.
Changes to other as an implementation side-effect is allowed. This and other are guaranteed to be the same concrete type.
Parameters:
other [i] Other TransitLoad container whose implementation matches this one.
virtual size_t SAMRAI::mesh::TransitLoad::getNumberOfItems () const [pure virtual]
Return number of items in this container.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
Referenced by empty(), and recursivePrint().
virtual size_t SAMRAI::mesh::TransitLoad::getNumberOfOriginatingProcesses () const [pure virtual]
Return number of processes contributing to the contents.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
Referenced by recursivePrint().
virtual bool SAMRAI::mesh::TransitLoad::empty () const [inline, virtual]
Whether container is empty.
Reimplemented in SAMRAI::mesh::BoxTransitSet.
References getNumberOfItems().
Referenced by SAMRAI::mesh::VoucherTransitLoad::adjustLoad().
virtual void SAMRAI::mesh::TransitLoad::clear () [pure virtual]
Empty the container.
Implemented in SAMRAI::mesh::BoxTransitSet.
virtual void SAMRAI::mesh::TransitLoad::putToMessageStream (tbox::MessageStream & msg) const [pure virtual]
Put content into MessageStream.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
virtual void SAMRAI::mesh::TransitLoad::getFromMessageStream (tbox::MessageStream & msg) [pure virtual]
Add to content from MessageStream.
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
virtual double SAMRAI::mesh::TransitLoad::adjustLoad (TransitLoad & hold_bin, double ideal_load, double low_load, double high_load) [pure virtual]
Adjust the load in this TransitSet by moving work between it and another TransitSet.
Parameters:
[in,out] hold_bin Holding bin for reserve load. hold_bin implementation is guaranteed to match this one.
[in] ideal_load The load that this bin should have.
[in] low_load Return when this bin's load is in the range [low_load,high_load]
[in] high_load Return when this bin's load is in the range [low_load,high_load]
Returns:
Net load added to this TransitSet. If negative, load decreased.
virtual void SAMRAI::mesh::TransitLoad::assignToLocalAndPopulateMaps (hier::BoxLevel & balanced_box_level, hier::MappingConnector & balanced_to_unbalanced, hier::MappingConnector & unbalanced_to_balanced, double flexible_load_tol = 0.0) [pure virtual]
Assign contents to local process and populate the balanced<==>unbalanced maps.
This method uses communication to set up the map.
Parameters:
[in,out] balanced_box_level Empty BoxLevel to populate with the contents of this TransitLoad.
[in,out] balanced_to_unbalanced Empty Connector to populate with the balanced--->unbalanced edges.
[in,out] unbalanced_to_balanced Empty Connector to populate with the unbalanced--->balanced edges.
[in] flexible_load_tol
Implemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
void SAMRAI::mesh::TransitLoad::setAllowBoxBreaking (bool allow_box_breaking) [inline]
Whether to allow box breaking.
Referenced by SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps().
bool SAMRAI::mesh::TransitLoad::getAllowBoxBreaking () const [inline]
Whether object may break up boxes.
Referenced by SAMRAI::mesh::BoxTransitSet::adjustLoad(), and SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps().
void SAMRAI::mesh::TransitLoad::setThresholdWidth (double threshold_width) [inline]
Set threshold for resisting small and thin boxes.
This is not a hard limit, but implementations should use it to determine when a box is getting too small in any coordinate direction. Default initial threshold is very small (practically unlimited).
Referenced by SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps().
double SAMRAI::mesh::TransitLoad::getThresholdWidth () const [inline]
Return the threshold width for resisting small and thin boxes.
Referenced by SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps().
virtual void SAMRAI::mesh::TransitLoad::setTimerPrefix (const std::string &) [inline, virtual]
Set prefix of internal diagnostic timer names.
Reimplemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
void SAMRAI::mesh::TransitLoad::recursivePrint (std::ostream & co = tbox::plog, const std::string & border = std::string(), int detail_depth = 1) const [virtual]
Object printing method to aid in debugging.
Reimplemented in SAMRAI::mesh::BoxTransitSet, and SAMRAI::mesh::VoucherTransitLoad.
References getNumberOfItems(), getNumberOfOriginatingProcesses(), getSumLoad(), and NULL_USE.
Friends And Related Function Documentation
tbox::MessageStream& operator<< (tbox::MessageStream & msg, const TransitLoad & transit_load) [friend]
tbox::MessageStream& operator>> (tbox::MessageStream & msg, TransitLoad & transit_load) [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/TransitLoad.h
source/SAMRAI/mesh/TransitLoad.C