SAMRAI: SAMRAI::xfer::PatchLevelInteriorFillPattern Class Reference
SAMRAI::xfer::PatchLevelInteriorFillPattern Class Reference
PatchLevelFillPattern implementation for patch interior filling.
#include <source/SAMRAI/xfer/PatchLevelInteriorFillPattern.h>
Public Member Functions
PatchLevelInteriorFillPattern ()
Default constructor.
virtual ~PatchLevelInteriorFillPattern ()
Destructor.
void computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > &fill_box_level, boost::shared_ptr< hier::Connector > &dst_to_fill, const hier::BoxLevel &dst_box_level, const hier::IntVector &fill_ghost_width, bool data_on_patch_border)
Compute the boxes to be filled and related communication data.
bool needsToCommunicateDestinationFillBoxes () const
Return false because source patch owner can compute destination fill boxes.
void computeDestinationFillBoxesOnSourceProc (FillSet &dst_fill_boxes_on_src_proc, const hier::BoxLevel &dst_box_level, const hier::Connector &src_to_dst, const hier::IntVector &fill_ghost_width)
Compute the destination fill boxes.
bool doesSourceLevelCommunicateToDestination () const
Tell RefineSchedule to communicate data directly from source level to destination level.
int getMaxFillBoxes () const
Return the maximum number of fill boxes.
bool fillingCoarseFineGhosts () const
Returns false because this fill pattern fills only interior data.
bool fillingEnhancedConnectivityOnly () const
Returns false because this fill pattern is not specialized for enhanced connectivity only.
Detailed Description
PatchLevelFillPattern implementation for patch interior filling.
For documentation on this interface see PatchLevelFillPattern
Those fill boxes for this PatchLevelFillPattern will consist of the patch interiors on the destination level only.
See also:
RefineAlgorithm
RefineSchedule
Constructor & Destructor Documentation
SAMRAI::xfer::PatchLevelInteriorFillPattern::PatchLevelInteriorFillPattern ()
Default constructor.
SAMRAI::xfer::PatchLevelInteriorFillPattern::~PatchLevelInteriorFillPattern () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > & fill_box_level, boost::shared_ptr< hier::Connector > & dst_to_fill, const hier::BoxLevel & dst_box_level, const hier::IntVector & fill_ghost_width, bool data_on_patch_border) [virtual]
Compute the boxes to be filled and related communication data.
The computed fill_box_level will be the boxes of dst_box_level, the "interior" of the destination level.
Parameters:
[out] fill_box_level Output BoxLevel to be filled
[out] dst_to_fill Output Connector between dst_box_level and fill_box_level
[in] dst_box_level destination level
[in] fill_ghost_width Ghost width being filled by refine schedule
[in] data_on_patch_border true if there is data living on patch borders
Precondition:
dst_box_level.getDim() == fill_ghost_width.getDim()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::BoxLevel::getRefinementRatio(), NULL_USE, SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::xfer::PatchLevelInteriorFillPattern::needsToCommunicateDestinationFillBoxes () const [virtual]
Return false because source patch owner can compute destination fill boxes.
For this fill pattern, the source owner can compute fill boxes for all of its destination neighbors using local data, so this method returns false, allowing a communication step to be skipped.
Returns:
false.
Implements SAMRAI::xfer::PatchLevelFillPattern.
void SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc (FillSet & dst_fill_boxes_on_src_proc, const hier::BoxLevel & dst_box_level, const hier::Connector & src_to_dst, const hier::IntVector & fill_ghost_width) [virtual]
Compute the destination fill boxes.
Parameters:
[in] dst_box_level Destination level
[in] src_to_dst Connector of source to destination
[in] fill_ghost_width Ghost width filled by refine schedule
[out] dst_fill_boxes_on_src_proc FillSet storing the destination neighbors of the source mapped boxes
Precondition:
dst_box_level.getDim() == fill_ghost_width.getDim()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::Connector::getLocalNeighbors(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), NULL_USE, SAMRAI::hier::BoxNeighborhoodCollection::numNeighbors(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::hier::BoxContainer::unshiftPeriodicImageBoxes().
bool SAMRAI::xfer::PatchLevelInteriorFillPattern::doesSourceLevelCommunicateToDestination () const [virtual]
Tell RefineSchedule to communicate data directly from source level to destination level.
RefineSchedule should attempt to fill the destination level from the source level on the same resolution to the extent possible.
Returns:
true
Implements SAMRAI::xfer::PatchLevelFillPattern.
int SAMRAI::xfer::PatchLevelInteriorFillPattern::getMaxFillBoxes () const [virtual]
Return the maximum number of fill boxes.
Returns:
maximum number of fill boxes.
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelInteriorFillPattern::fillingCoarseFineGhosts () const [virtual]
Returns false because this fill pattern fills only interior data.
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelInteriorFillPattern::fillingEnhancedConnectivityOnly () const [virtual]
Returns false because this fill pattern is not specialized for enhanced connectivity only.
Implements SAMRAI::xfer::PatchLevelFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/PatchLevelInteriorFillPattern.h
source/SAMRAI/xfer/PatchLevelInteriorFillPattern.C