SAMRAI: SAMRAI::hier::Box Class Reference
SAMRAI::hier::Box Class Reference
#include <source/SAMRAI/hier/Box.h>
Classes
struct box_equality
struct id_equal
struct id_less
Public Types
typedef BoxIterator iterator
Public Member Functions
Box (const tbox::Dimension &dim)
Creates an empty box with invalid BlockId and BoxId values.
Box (const Index &lower, const Index &upper, const BlockId &block_id)
Box (const Box &box)
Copy constructor.
Box (const tbox::DatabaseBox &box)
Box (const Index &lower, const Index &upper, const BlockId &block_id, const LocalId &local_id, const int owner_rank, const PeriodicId &periodic_id=PeriodicId::zero())
Initializing constructor.
Box (const Box &box, const LocalId &local_id, const int owner_rank, const PeriodicId &periodic_id=PeriodicId::zero())
Initializing constructor.
Box (const tbox::Dimension &dim, const GlobalId &id, const PeriodicId &periodic_id=PeriodicId::zero())
Constructor with undefined box.
Box (const tbox::Dimension &dim, const BoxId &box_id)
Constructor with undefined box and a BoxId.
Box (const Box &other, const PeriodicId &periodic_id, const IntVector &refinement_ratio)
"Copy" constructor allowing change in PeriodicId.
~Box ()
The destructor for Box.
void initialize (const Box &box, const LocalId &local_id, const int owner_rank, const PeriodicId &periodic_id=PeriodicId::zero())
Set all the attributes of the Box.
void initialize (const Box &other, const PeriodicId &periodic_id, const IntVector &refinement_ratio)
Set all the attributes identical to that of a reference Box, but with a different PeriodicId.
void setId (const BoxId &box_id)
Set the BoxId.
const BoxId & getBoxId () const
Get the BoxId.
void setBlockId (const BlockId &block_id)
Set the BlockId.
const BlockId & getBlockId () const
Get the BlockId.
void setLocalId (const LocalId &local_id)
Set the LocalId.
const LocalId & getLocalId () const
Get the LocalId.
const GlobalId & getGlobalId () const
Get the GlobalId.
int getOwnerRank () const
Get the owner rank.
const PeriodicId & getPeriodicId () const
Get the periodic shift number.
bool isPeriodicImage () const
Whether the Box is a periodic image.
bool isIdEqual (const Box &other) const
Box & operator= (const Box &rhs)
assignment operator
Index & lower ()
Return a non-const lower index of the box.
Index & upper ()
Return a non-const upper index of the box.
const Index & lower () const
Return a const lower index of the box.
const Index & upper () const
Return a const upper index of the box.
int & lower (const int i)
Return the i'th component (non-const) of the lower index.
int & upper (const int i)
Return the i'th component (non-const) of the upper index.
const int & lower (const int i) const
Return the i'th component (const) of the lower index.
const int & upper (const int i) const
Return the i'th component (const) of the upper index.
void setEmpty ()
Set the state of the box to empty.
bool empty () const
Return whether the box is ``empty''.
bool isEmpty () const
Return whether the box is ``empty''.
int numberCells (const int i) const
Return the number of cells (an integer) represented by the box in the given coordinate direction.
IntVector numberCells () const
Return the number of cells (a vector of integers) represented by the box in every coordinate direction.
int size () const
Calculate the number of indices represented by the box.
int longestDirection () const
Return the direction of the box that is longest.
int offset (const Index &p) const
Given an index, calculate the offset of the index into the box.
Index index (const int offset) const
Given an offset, calculate the index of the offset into the box.
iterator begin () const
Return an iterator pointing to the first index of this.
iterator end () const
Return an iterator pointing to the last index of this.
bool contains (const Index &p) const
Check whether an index lies within the bounds of the box.
bool contains (const Box &box) const
Check whether a given box lies within the bounds of the box.
bool isSpatiallyEqual (const Box &box) const
Check whether two boxes represent the same portion of index space on the same block.
Box operator* (const Box &box) const
Calculate the intersection of the index spaces of two boxes.
Box & operator*= (const Box &box)
Calculate the intersection of the index spaces of this and the given box.
void intersect (const Box &other, Box &result) const
Box intersection.
bool intersects (const Box &box) const
check if boxes intersect.
Box operator+ (const Box &box) const
Calculate the bounding box of two boxes.
Box & operator+= (const Box &box)
Increase this box to become the bounding box of this box and the argument box.
bool coalesceWith (const Box &box)
Return true if this box can be coalesced with the argument box, and set this box to the union of the boxes.
void grow (const IntVector &ghosts)
Grow this box by the specified ghost cell width.
void grow (const int direction, const int ghosts)
Grow this box by the specified ghost cell width in the given coordinate direction.
void growLower (const IntVector &ghosts)
Similar to grow() functions. However, box is only grown in lower directions (i.e., only lower index is changed).
void growLower (const int direction, const int ghosts)
Similar to grow() functions. However, box is only grown in lower bound of given direction in index space.
void growUpper (const IntVector &ghosts)
Similar to grow() function. However, box is only grown in upper directions (i.e., only upper index is changed).
void growUpper (const int direction, const int ghosts)
Similar to grow() functions. However, box is only grown in upper bound of given direction in index space.
void lengthen (const int direction, const int ghosts)
Similar to growUpper() and growLower() functions. However, box is lengthened (never shortened).
void shorten (const int direction, const int ghosts)
Similar to growUpper() and growLower() functions. However, box is shortened (never lengthened).
void shift (const IntVector &offset)
Shift this box by the specified offset.
void shift (const int direction, const int offset)
Similar to shift() function above, but shift occurs only in specified direction in index space.
void rotate (const Transformation::RotationIdentifier rotation_ident)
Rotate 90 degrees around origin.
void refine (const IntVector &ratio)
Refine the index space of a box by specified vector ratio.
void coarsen (const IntVector &ratio)
Coarsen the index space of a box by specified vector ratio.
Box & operator= (const tbox::DatabaseBox &box)
This assignment operator constructs a Box given a DatabaseBox.
Box & Box_from_DatabaseBox (const tbox::DatabaseBox &box)
Sets a Box from a tbox::DatabaseBox and returns a reference to the Box.
void set_Box_from_DatabaseBox (const tbox::DatabaseBox &box)
Sets a Box from a DatabaseBox.
tbox::DatabaseBox DatabaseBox_from_Box () const
Returns a tbox::DatabaseBox generated from a Box.
operator tbox::DatabaseBox ()
operator tbox::DatabaseBox () const
const tbox::Dimension & getDim () const
Return the dimension of this object.
void lockId ()
Lock the BoxId of this Box so that it may not be changed in any way.
bool idLocked ()
Returns true if the BoxId of this Box is locked.
Static Public Member Functions
static Box grow (const Box &box, const IntVector &ghosts)
Static function to grow a box by the specified vector ghost cell width.
static Box shift (const Box &box, const IntVector &offset)
Static function to shift a box by the specified offset.
static Box refine (const Box &box, const IntVector &ratio)
Static function to refine the index space of a box by the specified refinement ratio.
static Box coarsen (const Box &box, const IntVector &ratio)
Static function to coarsen the index space of a box by the specified coarsening ratio.
static const Box & getEmptyBox (const tbox::Dimension &dim)
Return an empty Box of the specified dimension.
static const Box & getUniverse (const tbox::Dimension &dim)
Returns a Box that represents the maximum allowed index extents for a given dimension. The "universe" that can be represented.
Friends
class BoxIterator
std::istream & operator>> (std::istream &s, Box &box)
Read the box description in the form [L,U], where L and U are the lower and upper bounds of the box.
std::ostream & operator<< (std::ostream &s, const Box &box)
Output the box description in the form [L,U], where L and U are the lower and upper bounds of the box.
Packing and unpacking Boxes
void putToIntBuffer (int *buffer) const
Put self into a int buffer.
void getFromIntBuffer (const int *buffer)
Set attributes according to data in int buffer.
void putToMessageStream (tbox::MessageStream &msg) const
Put self into a MessageStream.
void getFromMessageStream (tbox::MessageStream &msg)
Set attributes according to data in MessageStream.
static int commBufferSize (const tbox::Dimension &dim)
Give number of ints required for putting a Box in message passing buffer.
Detailed Description
Class Box represents a n-dimensional box in the AMR index space. It is defined by lower and upper bounds given by index objects. The box semantics assumes that the box is cell-centered. A cell-centered convention implies that the index set covered by the box includes both the lower and upper bounds.
The Box contains identifying information in its state with a BlockId and a BoxId. If the Box is part of a single-block mesh, the BlockId should be zero. If the mesh is multi-block, the BlockId will have a value identifying on which block the Box exists. The BoxId contains information about the MPI rank associated with the Box as well as a PeriodicId to handle periodic shifts. Since periodic conditions and multiblock meshes cannot be mixed in SAMRAI, the BlockId and the PeriodicId associated with a Box cannot both be nonzero.
See also:
hier::BoxIterator
hier::Index
hier::BlockId
hier::BoxId
hier::PeriodicId
Member Typedef Documentation
typedef BoxIterator SAMRAI::hier::Box::iterator
A box iterator iterates over the elements of a box. This class is defined elsewhere, and the typedef is used to point to that class.
Constructor & Destructor Documentation
SAMRAI::hier::Box::Box (const tbox::Dimension & dim) [explicit]
Creates an empty box with invalid BlockId and BoxId values.
Parameters:
[in] dim
SAMRAI::hier::Box::Box (const Index & lower, const Index & upper, const BlockId & block_id)
Create a box describing the index space between lower and upper. The box is assumed to be cell centered and include all elements between lower and upper, including the end points.
Parameters:
[in] lower Lower extent
[in] upper Upper extent
[in] block_id Block where the Box exists
Precondition:
lower.getDim() == upper.getDim()
block_id != BlockId::invalidId()
References SAMRAI::hier::BlockId::invalidId(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::hier::Box::Box (const Box & box)
Copy constructor.
SAMRAI::hier::Box::Box (const tbox::DatabaseBox & box) [explicit]
Construct a Box from a DatabaseBox.
References set_Box_from_DatabaseBox().
SAMRAI::hier::Box::Box (const Index & lower, const Index & upper, const BlockId & block_id, const LocalId & local_id, const int owner_rank, const PeriodicId & periodic_id = PeriodicId::zero())
Initializing constructor.
Parameters:
[in] lower
[in] upper
[in] block_id
[in] local_id
[in] owner_rank
[in] periodic_id Describes the periodic shift. If periodic_id is non-zero, specify the Box in the position shifted according to the periodic_id. The default argument for periodic_id corresponds to the zero-shift.
Precondition:
periodic_id.isValid()
periodic_id.getPeriodicValue() < PeriodicShiftCatalog::getCatalog(box.getDim())->getNumberOfShifts()
References SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
SAMRAI::hier::Box::Box (const Box & box, const LocalId & local_id, const int owner_rank, const PeriodicId & periodic_id = PeriodicId::zero())
Initializing constructor.
Parameters:
[in] box
[in] local_id
[in] owner_rank
[in] periodic_id Describes the periodic shift. If periodic_id is non-zero, specify the Box in the position shifted according to the periodic_id. The default argument for periodic_id corresponds to the zero-shift.
Precondition:
periodic_id.isValid()
periodic_id.getPeriodicValue() < PeriodicShiftCatalog::getCatalog(box.getDim())->getNumberOfShifts()
References SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), getDim(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
SAMRAI::hier::Box::Box (const tbox::Dimension & dim, const GlobalId & id, const PeriodicId & periodic_id = PeriodicId::zero())
Constructor with undefined box.
The box can be initialized using any of the initialize() methods or by assignment.
Parameters:
[in] dim
[in] id
[in] periodic_id
Precondition:
periodic_id.isValid()
periodic_id.getPeriodicValue() < PeriodicShiftCatalog::getCatalog(dim)->getNumberOfShifts()
References SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), SAMRAI::hier::PeriodicShiftCatalog::getNumberOfShifts(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
SAMRAI::hier::Box::Box (const tbox::Dimension & dim, const BoxId & box_id)
Constructor with undefined box and a BoxId.
The box can be initialized using any of the initialize() methods or by assignment.
Parameters:
[in] dim
[in] box_id
Precondition:
box_id.getPeriodicId().isValid()
box_id.getPeriodicId().getPeriodicValue() < PeriodicShiftCatalog::getCatalog(dim)->getNumberOfShifts()
References SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), SAMRAI::hier::PeriodicShiftCatalog::getNumberOfShifts(), SAMRAI::hier::BoxId::getPeriodicId(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
SAMRAI::hier::Box::Box (const Box & other, const PeriodicId & periodic_id, const IntVector & refinement_ratio)
"Copy" constructor allowing change in PeriodicId.
Parameters:
[in] other Make a copy (but not an exact copy) of this Box.
[in] periodic_id Periodic shift number to use instead of the shift in other. The box will be set to the real box shifted to the position specified by this value.
[in] refinement_ratio The index space where the Box lives.
Precondition:
other.getDim() == refinement_ratio.getDim()
periodic_id.isValid()
periodic_id.getPeriodicValue() < PeriodicShiftCatalog::getCatalog(other.getDim())->getNumberOfShifts()
(refinement_ratio > IntVector::getZero(other.getDim())) || (refinement_ratio < IntVector::getZero(other.getDim()))
See also:
initialize(const Box&, const int, const IntVector&);
References SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), SAMRAI::hier::IntVector::getDim(), getPeriodicId(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::PeriodicId::isValid(), shift(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and TBOX_ERROR.
SAMRAI::hier::Box::~Box ()
The destructor for Box.
Member Function Documentation
void SAMRAI::hier::Box::initialize (const Box & box, const LocalId & local_id, const int owner_rank, const PeriodicId & periodic_id = PeriodicId::zero()) [inline]
Set all the attributes of the Box.
Parameters:
[in] box
[in] local_id
[in] owner_rank
[in] periodic_id The periodic shift number. If this is not zero, specify box in the shifted position. The default argument for periodic_id corresponds to the zero-shift.
Precondition:
idLocked()
References idLocked(), SAMRAI::hier::BoxId::initialize(), and TBOX_ERROR.
Referenced by SAMRAI::hier::Connector::checkTransposeCorrectness(), and SAMRAI::hier::Patch::getFromRestart().
void SAMRAI::hier::Box::initialize (const Box & other, const PeriodicId & periodic_id, const IntVector & refinement_ratio)
Set all the attributes identical to that of a reference Box, but with a different PeriodicId.
Parameters:
[in] other Initialize to this Box, but with the shift given by periodic_id.
[in] periodic_id PeriodicId number to use instead of the shift in other. The box will be set to the real box shifted to the position specified by this value.
[in] refinement_ratio The index space where the Box lives.
Precondition:
(getDim() == other.getDim()) && (getDim() == refinement_ratio.getDim())
periodic_id.isValid()
periodic_id.getPeriodicValue() < PeriodicShiftCatalog::getCatalog(getDim())->getNumberOfShifts()
(refinement_ratio > IntVector::getZero(getDim())) || (refinement_ratio < IntVector::getZero(getDim()))
!idLocked()
References getBlockId(), SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), SAMRAI::hier::IntVector::getDim(), getLocalId(), getOwnerRank(), getPeriodicId(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxId::initialize(), SAMRAI::hier::PeriodicId::isValid(), shift(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and TBOX_ERROR.
void SAMRAI::hier::Box::setId (const BoxId & box_id) [inline]
Set the BoxId.
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), and SAMRAI::hier::BoxContainer::getFromRestart().
const BoxId& SAMRAI::hier::Box::getBoxId () const [inline]
Get the BoxId.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::BaseGridGeometry::chopDomain(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::BoxContainer::erase(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges(), SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::hier::Box::id_less::operator()(), SAMRAI::hier::operator<<(), SAMRAI::hier::PatchLevel::PatchLevel(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::xfer::RefineTimeTransaction::RefineTimeTransaction(), SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel(), and SAMRAI::hier::PatchLevel::setRefinedPatchLevel().
void SAMRAI::hier::Box::setBlockId (const BlockId & block_id) [inline]
Set the BlockId.
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::BoxContainer::getFromRestart(), SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::pdat::FaceGeometry::toFaceBox(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::BaseGridGeometry::transformBox().
const BlockId& SAMRAI::hier::Box::getBlockId () const [inline]
Get the BlockId.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::hier::BoxContainer::coalesce(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), contains(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::BoxContainer::getBoundingBox(), SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors(), initialize(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::BoxContainer::intersectBoxes(), SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::hier::Patch::putToRestart(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), SAMRAI::hier::BoxContainer::removeIntersections(), SAMRAI::hier::Connector::shrinkWidth(), SAMRAI::hier::BoxContainer::simplify(), SAMRAI::pdat::FaceGeometry::toFaceBox(), SAMRAI::pdat::NodeGeometry::toNodeBox(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox().
void SAMRAI::hier::Box::setLocalId (const LocalId & local_id) [inline]
Set the LocalId.
References SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::hier::BoxId::getPeriodicId(), and SAMRAI::hier::BoxId::initialize().
const LocalId& SAMRAI::hier::Box::getLocalId () const [inline]
Get the LocalId.
References SAMRAI::hier::BoxId::getLocalId().
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::algs::OuternodeSumTransactionFactory::allocate(), SAMRAI::algs::OuteredgeSumTransactionFactory::allocate(), SAMRAI::xfer::CoarsenCopyTransaction::CoarsenCopyTransaction(), SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::mesh::BoxInTransit::getLocalId(), SAMRAI::hier::Patch::getLocalId(), initialize(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::algs::OuteredgeSumTransaction::OuteredgeSumTransaction(), SAMRAI::algs::OuternodeSumTransaction::OuternodeSumTransaction(), SAMRAI::hier::Patch::Patch(), SAMRAI::hier::Patch::putToRestart(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), SAMRAI::xfer::RefineCopyTransaction::RefineCopyTransaction(), and SAMRAI::xfer::RefineTimeTransaction::RefineTimeTransaction().
const GlobalId& SAMRAI::hier::Box::getGlobalId () const [inline]
Get the GlobalId.
References SAMRAI::hier::BoxId::getGlobalId().
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::algs::OuternodeSumTransaction::canEstimateIncomingMessageSize(), SAMRAI::algs::OuteredgeSumTransaction::canEstimateIncomingMessageSize(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::xfer::CoarsenCopyTransaction::CoarsenCopyTransaction(), SAMRAI::algs::OuternodeSumTransaction::computeIncomingMessageSize(), SAMRAI::algs::OuteredgeSumTransaction::computeIncomingMessageSize(), SAMRAI::algs::OuternodeSumTransaction::computeOutgoingMessageSize(), SAMRAI::algs::OuteredgeSumTransaction::computeOutgoingMessageSize(), SAMRAI::algs::OuternodeSumTransaction::copyLocalData(), SAMRAI::algs::OuteredgeSumTransaction::copyLocalData(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::Patch::getGlobalId(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::algs::OuternodeSumTransaction::packStream(), SAMRAI::algs::OuteredgeSumTransaction::packStream(), SAMRAI::xfer::RefineCopyTransaction::RefineCopyTransaction(), SAMRAI::algs::OuternodeSumTransaction::unpackStream(), and SAMRAI::algs::OuteredgeSumTransaction::unpackStream().
int SAMRAI::hier::Box::getOwnerRank () const [inline]
Get the owner rank.
References SAMRAI::hier::BoxId::getOwnerRank().
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::algs::OuteredgeSumTransaction::canEstimateIncomingMessageSize(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::BoxLevel::getBoxStrict(), SAMRAI::algs::OuternodeSumTransaction::getDestinationProcessor(), SAMRAI::algs::OuteredgeSumTransaction::getDestinationProcessor(), SAMRAI::mesh::BoxInTransit::getOwnerRank(), SAMRAI::algs::OuternodeSumTransaction::getSourceProcessor(), SAMRAI::algs::OuteredgeSumTransaction::getSourceProcessor(), SAMRAI::hier::BoxLevel::hasBox(), initialize(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::hier::Patch::putToRestart(), and SAMRAI::hier::BoxNeighborhoodCollection::putToRestart().
const PeriodicId& SAMRAI::hier::Box::getPeriodicId () const [inline]
Get the periodic shift number.
See also:
PeriodicShiftCatalog.
References SAMRAI::hier::BoxId::getPeriodicId().
Referenced by Box(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doLocalTransposeWork(), initialize(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), and SAMRAI::hier::BoxContainer::separatePeriodicImages().
bool SAMRAI::hier::Box::isPeriodicImage () const [inline]
Whether the Box is a periodic image.
References SAMRAI::hier::BoxId::isPeriodicImage().
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::BoxNeighborhoodCollection::erasePeriodicNeighbors(), and SAMRAI::hier::BoxNeighborhoodCollection::getPeriodicNeighbors().
bool SAMRAI::hier::Box::isIdEqual (const Box & other) const [inline]
Referenced by SAMRAI::mesh::BoxInTransit::isOriginal(), SAMRAI::pdat::SideIterator::operator!=(), SAMRAI::pdat::NodeIterator::operator!=(), SAMRAI::pdat::FaceIterator::operator!=(), SAMRAI::pdat::EdgeIterator::operator!=(), SAMRAI::pdat::CellIterator::operator!=(), SAMRAI::hier::Box::id_equal::operator()(), SAMRAI::pdat::SideIterator::operator==(), SAMRAI::pdat::NodeIterator::operator==(), SAMRAI::pdat::FaceIterator::operator==(), SAMRAI::pdat::EdgeIterator::operator==(), and SAMRAI::pdat::CellIterator::operator==().
static int SAMRAI::hier::Box::commBufferSize (const tbox::Dimension & dim) [inline, static]
Give number of ints required for putting a Box in message passing buffer.
This number is independent of instance but dependent on dimension.
See also:
putToIntBuffer(), getFromIntBuffer().
References SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromIntBuffer(), getFromIntBuffer(), SAMRAI::hier::BaseConnectorAlgorithm::packReferencedNeighbors(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::hier::BoxNeighborhoodCollection::putToIntBuffer(), and putToIntBuffer().
void SAMRAI::hier::Box::putToIntBuffer (int * buffer) const
Put self into a int buffer.
This is the opposite of getFromIntBuffer(). Number of ints written is given by commBufferSize().
References commBufferSize(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), and SAMRAI::hier::BoxId::putToIntBuffer().
Referenced by SAMRAI::hier::BaseConnectorAlgorithm::packReferencedNeighbors(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
void SAMRAI::hier::Box::getFromIntBuffer (const int * buffer)
Set attributes according to data in int buffer.
This is the opposite of putToIntBuffer(). Number of ints read is given by commBufferSize().
References commBufferSize(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::BoxId::getFromIntBuffer(), and SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromIntBuffer().
void SAMRAI::hier::Box::putToMessageStream (tbox::MessageStream & msg) const
Put self into a MessageStream.
This is the opposite of getFromMessageStream().
Parameters:
msg [in] Stream. Must be in write mode.
References SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::MessageStream::pack(), and SAMRAI::hier::BoxId::putToMessageStream().
Referenced by SAMRAI::mesh::BoxInTransit::putToMessageStream().
void SAMRAI::hier::Box::getFromMessageStream (tbox::MessageStream & msg)
Set attributes according to data in MessageStream.
This is the opposite of putToMessageStream().
Parameters:
msg [in] Stream. Must be in read mode.
References SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::BoxId::getFromMessageStream(), SAMRAI::tbox::Dimension::getValue(), and SAMRAI::tbox::MessageStream::unpack().
Referenced by SAMRAI::mesh::BoxInTransit::getFromMessageStream().
Box & SAMRAI::hier::Box::operator= (const Box & rhs)
assignment operator
Parameters:
rhs
Precondition:
(this == &rhs) || (getDim() == rhs.getDim())
(this == &rhs) || !idLocked()
References TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Index& SAMRAI::hier::Box::lower () [inline]
Return a non-const lower index of the box.
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::pdat::ArrayDataAccess::access(), SAMRAI::pdat::access(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::mesh::BalanceBoxBreaker::burstBox(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BaseGridGeometry::chopDomain(), coalesceWith(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), contains(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::pdat::ArrayData< TYPE >::fill(), SAMRAI::hier::BoxUtilities::findBadCutPointsForBorderAndDirection(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::findBestCutPointsForDirectionGivenMax(), SAMRAI::hier::BoxUtilities::findBestCutPointsForDirectionGivenNumber(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::BoxUtilities::fixBadCutPointsForDirection(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::pdat::OuternodeData< TYPE >::getDataBox(), SAMRAI::pdat::OutersideData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuternodeData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuterfaceData< TYPE >::getSizeOfData(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), index(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), longestDirection(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::pdat::SideIterator::operator++(), SAMRAI::pdat::NodeIterator::operator++(), SAMRAI::pdat::FaceIterator::operator++(), SAMRAI::pdat::EdgeIterator::operator++(), SAMRAI::pdat::CellIterator::operator++(), SAMRAI::pdat::ArrayDataIterator::operator++(), SAMRAI::hier::operator<<(), SAMRAI::hier::operator>>(), SAMRAI::pdat::OuterfaceData< TYPE >::OuterfaceData(), SAMRAI::pdat::OuternodeData< TYPE >::OuternodeData(), SAMRAI::pdat::OutersideData< TYPE >::OutersideData(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), shift(), SAMRAI::hier::BoxContainer::simplify(), SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::pdat::FaceGeometry::toFaceBox(), SAMRAI::pdat::NodeGeometry::toNodeBox(), SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
Index& SAMRAI::hier::Box::upper () [inline]
Return a non-const upper index of the box.
Referenced by SAMRAI::pdat::ArrayDataAccess::access(), SAMRAI::pdat::access(), SAMRAI::pdat::ArrayDataIterator::ArrayDataIterator(), SAMRAI::mesh::BalanceBoxBreaker::burstBox(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BaseGridGeometry::chopDomain(), coalesceWith(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), contains(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::BoxUtilities::findBadCutPointsForBorderAndDirection(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::BoxUtilities::fixBadCutPointsForDirection(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::pdat::OuternodeData< TYPE >::getDataBox(), SAMRAI::pdat::OutersideData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuternodeData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuterfaceData< TYPE >::getSizeOfData(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), longestDirection(), SAMRAI::pdat::SideIterator::operator++(), SAMRAI::pdat::NodeIterator::operator++(), SAMRAI::pdat::FaceIterator::operator++(), SAMRAI::pdat::EdgeIterator::operator++(), SAMRAI::pdat::CellIterator::operator++(), SAMRAI::pdat::ArrayDataIterator::operator++(), SAMRAI::hier::operator<<(), SAMRAI::hier::operator>>(), SAMRAI::pdat::OuterfaceData< TYPE >::OuterfaceData(), SAMRAI::pdat::OuternodeData< TYPE >::OuternodeData(), SAMRAI::pdat::OutersideData< TYPE >::OutersideData(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), shift(), SAMRAI::hier::BoxContainer::simplify(), SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth(), SAMRAI::pdat::EdgeGeometry::toEdgeBox(), SAMRAI::pdat::FaceGeometry::toFaceBox(), SAMRAI::pdat::NodeGeometry::toNodeBox(), SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox(), SAMRAI::pdat::SideGeometry::toSideBox(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::pdat::EdgeGeometry::transform(), and SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox().
const Index& SAMRAI::hier::Box::lower () const [inline]
Return a const lower index of the box.
const Index& SAMRAI::hier::Box::upper () const [inline]
Return a const upper index of the box.
int& SAMRAI::hier::Box::lower (const int i) [inline]
Return the i'th component (non-const) of the lower index.
int& SAMRAI::hier::Box::upper (const int i) [inline]
Return the i'th component (non-const) of the upper index.
const int& SAMRAI::hier::Box::lower (const int i) const [inline]
Return the i'th component (const) of the lower index.
const int& SAMRAI::hier::Box::upper (const int i) const [inline]
Return the i'th component (const) of the upper index.
void SAMRAI::hier::Box::setEmpty () [inline]
Set the state of the box to empty.
References getDim().
Referenced by intersect(), operator*(), and operator*=().
bool SAMRAI::hier::Box::empty () const [inline]
Return whether the box is ``empty''.
isEmpty() is preferred to match "is" standard syntax for boolean methods.
See also:
isEmpty()
References isEmpty().
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::pdat::ArrayDataIterator::ArrayDataIterator(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BaseGridGeometry::chopDomain(), coalesceWith(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::pdat::CellGeometry::computeDestinationBoxes(), SAMRAI::solv::CellPoissonFACOps::computeVectorWeights(), contains(), SAMRAI::pdat::SideData< TYPE >::copy(), SAMRAI::pdat::NodeData< TYPE >::copy(), SAMRAI::pdat::FaceData< TYPE >::copy(), SAMRAI::pdat::EdgeData< TYPE >::copy(), SAMRAI::pdat::CellData< TYPE >::copy(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::SideData< TYPE >::copy2(), SAMRAI::pdat::NodeData< TYPE >::copy2(), SAMRAI::pdat::FaceData< TYPE >::copy2(), SAMRAI::pdat::EdgeData< TYPE >::copy2(), SAMRAI::pdat::CellData< TYPE >::copy2(), SAMRAI::pdat::SideData< TYPE >::copyDepth(), SAMRAI::pdat::NodeData< TYPE >::copyDepth(), SAMRAI::pdat::FaceData< TYPE >::copyDepth(), SAMRAI::pdat::EdgeData< TYPE >::copyDepth(), SAMRAI::pdat::CellData< TYPE >::copyDepth(), SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::pdat::ArrayData< TYPE >::fill(), SAMRAI::pdat::ArrayData< TYPE >::fillAll(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), SAMRAI::hier::BoxUtilities::findBadCutPoints(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::findBestCutPointsForDirectionGivenMax(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenNumber(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::BoxUtilities::fixBadCutPoints(), SAMRAI::hier::BoxUtilities::fixBadCutPointsForDirection(), grow(), growLower(), growUpper(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), intersect(), SAMRAI::hier::BoxContainer::intersectBoxes(), intersects(), isSpatiallyEqual(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), lengthen(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), numberCells(), operator*(), operator*=(), operator+(), operator+=(), SAMRAI::hier::operator<<(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::OuterfaceData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), shorten(), SAMRAI::hier::BoxContainer::simplify(), size(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::pdat::ArrayData< TYPE >::sum(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::pdat::EdgeGeometry::toEdgeBox(), SAMRAI::pdat::FaceGeometry::toFaceBox(), SAMRAI::pdat::NodeGeometry::toNodeBox(), SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox(), SAMRAI::pdat::SideGeometry::toSideBox(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::pdat::EdgeGeometry::transform(), SAMRAI::pdat::OutersideData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStream(), SAMRAI::pdat::OuterfaceData< TYPE >::unpackStream(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStreamAndSum(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
bool SAMRAI::hier::Box::isEmpty () const [inline]
Return whether the box is ``empty''.
A box is empty if any of the lower bounds is greater than the corresponding upper bound. An empty box has a size of zero.
References getDim(), and SAMRAI::tbox::Dimension::getValue().
Referenced by empty(), and SAMRAI::pdat::ArrayData< TYPE >::isValid().
int SAMRAI::hier::Box::numberCells (const int i) const [inline]
Return the number of cells (an integer) represented by the box in the given coordinate direction.
References empty().
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::hier::BoxLevel::addBox(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::mesh::BalanceBoxBreaker::burstBox(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::BaseGridGeometry::chopDomain(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::mesh::BalanceUtilities::computeDomainDependentProcessorLayout(), SAMRAI::mesh::BalanceUtilities::computeDomainIndependentProcessorLayout(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::pdat::ArrayData< TYPE >::fill(), SAMRAI::hier::BoxUtilities::findBadCutPointsForBorderAndDirection(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::findBestCutPointsForDirectionGivenMax(), SAMRAI::hier::BoxUtilities::findBestCutPointsForDirectionGivenNumber(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenNumber(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::hier::BoxUtilities::fixBadCutPoints(), SAMRAI::hier::BoxUtilities::fixBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::hier::BoxContainer::print(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::hier::Patch::recursivePrint(), SAMRAI::hier::Connector::recursivePrint(), SAMRAI::hier::BoxLevel::recursivePrint(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::geom::CartesianGridGeometry::setGeometryData(), SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume(), SAMRAI::hier::Connector::writeNeighborhoodsToErrorStream(), and SAMRAI::hier::Connector::writeNeighborhoodToStream().
IntVector SAMRAI::hier::Box::numberCells () const [inline]
Return the number of cells (a vector of integers) represented by the box in every coordinate direction.
References empty(), getDim(), and SAMRAI::hier::IntVector::getZero().
Referenced by index().
int SAMRAI::hier::Box::size () const [inline]
Calculate the number of indices represented by the box.
If the box is empty, then the number of index points within the box is zero.
References empty(), getDim(), and SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::hier::BoxLevel::addBox(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::pdat::ArrayData< TYPE >::fill(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::pdat::ArrayData< TYPE >::getSizeOfData(), index(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::math::PatchSideDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsComplex::numberOfEntries(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchFaceDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsComplex::numberOfEntries(), SAMRAI::math::PatchEdgeDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsComplex::numberOfEntries(), SAMRAI::math::PatchCellDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::pdat::ArrayData< TYPE >::packStream(), SAMRAI::hier::BoxContainer::print(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::hier::Patch::recursivePrint(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::pdat::ArrayData< TYPE >::unpackStream(), SAMRAI::pdat::ArrayData< TYPE >::unpackStreamAndSum(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
int SAMRAI::hier::Box::longestDirection () const
Return the direction of the box that is longest.
References getDim(), SAMRAI::tbox::Dimension::getValue(), lower(), and upper().
int SAMRAI::hier::Box::offset (const Index & p) const [inline]
Given an index, calculate the offset of the index into the box.
This function assumes column-major (e.g., Fortran) ordering of the indices within the box. This operation is a convenience function for array indexing operations.
References getDim().
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::pdat::ArrayData< TYPE >::fill(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
Index SAMRAI::hier::Box::index (const int offset) const
Given an offset, calculate the index of the offset into the box.
This function assumes column-major (e.g., Fortran) ordering of the indices within the box. This operation is a convenience function for array indexing operations.
Parameters:
offset
Precondition:
(offset >= 0) && (offset <= size())
References getDim(), lower(), numberCells(), size(), and TBOX_ASSERT.
BoxIterator SAMRAI::hier::Box::begin () const
Return an iterator pointing to the first index of this.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), SAMRAI::pdat::OuterfaceData< TYPE >::printAxisFace(), SAMRAI::pdat::OutersideData< TYPE >::printAxisSide(), SAMRAI::pdat::OuternodeData< TYPE >::printAxisSide(), and SAMRAI::pdat::OuteredgeData< TYPE >::printAxisSide().
BoxIterator SAMRAI::hier::Box::end () const
Return an iterator pointing to the last index of this.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), SAMRAI::pdat::OuterfaceData< TYPE >::printAxisFace(), SAMRAI::pdat::OutersideData< TYPE >::printAxisSide(), SAMRAI::pdat::OuternodeData< TYPE >::printAxisSide(), and SAMRAI::pdat::OuteredgeData< TYPE >::printAxisSide().
bool SAMRAI::hier::Box::contains (const Index & p) const [inline]
Check whether an index lies within the bounds of the box.
Parameters:
p
References getDim(), and SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::mesh::BalanceBoxBreaker::burstBox(), contains(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeInsideBox(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeOutsideBox().
bool SAMRAI::hier::Box::contains (const Box & box) const
Check whether a given box lies within the bounds of the box.
If box is empty, always return true.
Parameters:
box
Precondition:
getDim() == box.getDim()
References contains(), empty(), getBlockId(), lower(), TBOX_ASSERT_OBJDIM_EQUALITY2, and upper().
bool SAMRAI::hier::Box::isSpatiallyEqual (const Box & box) const [inline]
Check whether two boxes represent the same portion of index space on the same block.
References empty().
Referenced by SAMRAI::mesh::BalanceBoxBreaker::burstBox(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::hier::BoxLevel::getSpatiallyEqualBox(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), SAMRAI::pdat::SideIterator::operator!=(), SAMRAI::pdat::NodeIterator::operator!=(), SAMRAI::pdat::FaceIterator::operator!=(), SAMRAI::pdat::EdgeIterator::operator!=(), SAMRAI::pdat::CellIterator::operator!=(), SAMRAI::hier::Box::box_equality::operator()(), SAMRAI::pdat::SideIterator::operator==(), SAMRAI::pdat::NodeIterator::operator==(), SAMRAI::pdat::FaceIterator::operator==(), SAMRAI::pdat::EdgeIterator::operator==(), SAMRAI::pdat::CellIterator::operator==(), and SAMRAI::pdat::ArrayData< TYPE >::sum().
Box SAMRAI::hier::Box::operator* (const Box & box) const
Calculate the intersection of the index spaces of two boxes.
The intersection with an empty box always yields an empty box.
Parameters:
box
Precondition:
getDim() == box.getDim()
(getBlockId() == box.getBlockId()) || empty() || box.empty()
References empty(), SAMRAI::hier::IntVector::max(), SAMRAI::hier::IntVector::min(), setEmpty(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Box & SAMRAI::hier::Box::operator*= (const Box & box)
Calculate the intersection of the index spaces of this and the given box.
The intersection with an empty box always yields an empty box.
Parameters:
box
Precondition:
getDim() == box.getDim()
(getBlockId() == box.getBlockId()) || empty() || box.empty()
References empty(), SAMRAI::hier::IntVector::max(), SAMRAI::hier::IntVector::min(), setEmpty(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
void SAMRAI::hier::Box::intersect (const Box & other, Box & result) const
Box intersection.
Calculate the intersection of the index spaces of two boxes. The intersection with an empty box always yields an empty box.
Parameters:
other
result
Precondition:
getDim() == box.getDim()
(getBlockId() == box.getBlockId()) || empty() || box.empty()
References empty(), SAMRAI::hier::IntVector::max(), SAMRAI::hier::IntVector::min(), setEmpty(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxContainer::intersectBoxes().
bool SAMRAI::hier::Box::intersects (const Box & box) const
check if boxes intersect.
Returns true if two boxes have a non-empty intersection.
Parameters:
box
Precondition:
getDim() == box.getDim()
(getBlockId() == box.getBlockId()) || empty() || box.empty()
References empty(), getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::BoxContainer::findOverlapBoxes(), SAMRAI::hier::BoxContainer::hasOverlap(), SAMRAI::hier::BoxContainer::removeIntersections(), and SAMRAI::hier::Connector::shrinkWidth().
Box SAMRAI::hier::Box::operator+ (const Box & box) const
Calculate the bounding box of two boxes.
Note that this is not the union of the two boxes (since union is not closed over boxes), but rather the smallest box that contains both boxes.
If one box is empty and the other is non-empty, the non-empty box will be returned.
Parameters:
box
Precondition:
getDim() == box.getDim()
(getBlock_id() == box.getBlockId()) || empty() || box.empty()
References empty(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Box & SAMRAI::hier::Box::operator+= (const Box & box)
Increase this box to become the bounding box of this box and the argument box.
If this box is empty, this box will become equal to the argument box.
If the argument box is empty, this box will be unchanged.
Parameters:
box
Precondition:
getDim() == box.getDim()
(getBlockId() == box.getBlockId()) || empty() || box.empty()
References empty(), SAMRAI::hier::IntVector::max(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
bool SAMRAI::hier::Box::coalesceWith (const Box & box)
Return true if this box can be coalesced with the argument box, and set this box to the union of the boxes.
Otherwise, return false and leave boxes as is. Two boxes may be coalesced if their union is a box (recall that index set union is not closed over boxes). If one box is empty and the other is non-empty, then the return value is true and this box becomes equal to the non-empty box. If both boxes are empty, the return value is true and this box remains empty.
Parameters:
box
Precondition:
getDim() == box.getDim()
References empty(), getDim(), SAMRAI::tbox::Dimension::getValue(), lower(), TBOX_ASSERT_OBJDIM_EQUALITY2, and upper().
void SAMRAI::hier::Box::grow (const IntVector & ghosts) [inline]
Grow this box by the specified ghost cell width.
The lower bound decremented by the width, and the upper bound is incremented by the width. All directions are grown by the corresponding component in the IntVector; ghost cell widths may be different in each direction. Negative ghost cell widths will shrink the box.
Parameters:
ghosts
Precondition:
getDim() == ghosts.getDim()
References empty(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::pdat::CellGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::PatchGeometry::getBoundaryFillBox(), SAMRAI::pdat::SideData< TYPE >::getSizeOfData(), SAMRAI::pdat::NodeData< TYPE >::getSizeOfData(), SAMRAI::pdat::FaceData< TYPE >::getSizeOfData(), SAMRAI::pdat::EdgeData< TYPE >::getSizeOfData(), SAMRAI::pdat::CellData< TYPE >::getSizeOfData(), grow(), SAMRAI::hier::BoxNeighborhoodCollection::growNeighbors(), SAMRAI::hier::PatchData::PatchData(), SAMRAI::hier::Connector::recursivePrint(), and SAMRAI::hier::Connector::shrinkWidth().
void SAMRAI::hier::Box::grow (const int direction, const int ghosts) [inline]
Grow this box by the specified ghost cell width in the given coordinate direction.
The lower bound is decremented by the width, and the upper bound is incremented by the width. Note that negative ghost cell widths will shrink the box.
Parameters:
direction
ghosts
Precondition:
(direction >= 0) && (direction < getDim().getValue())
References empty(), getDim(), and TBOX_ASSERT.
void SAMRAI::hier::Box::growLower (const IntVector & ghosts) [inline]
Similar to grow() functions. However, box is only grown in lower directions (i.e., only lower index is changed).
Parameters:
ghosts
Precondition:
getDim() == ghosts.getDim()
References empty(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::hier::BoundaryBoxUtils::extendBoxOutward(), and SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth().
void SAMRAI::hier::Box::growLower (const int direction, const int ghosts) [inline]
Similar to grow() functions. However, box is only grown in lower bound of given direction in index space.
Parameters:
direction
ghosts
Precondition:
(direction >= 0) && (direction < getDim().getValue())
References empty(), getDim(), and TBOX_ASSERT.
void SAMRAI::hier::Box::growUpper (const IntVector & ghosts) [inline]
Similar to grow() function. However, box is only grown in upper directions (i.e., only upper index is changed).
Parameters:
ghosts
Precondition:
getDim() == ghosts.getDim()
References empty(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), and SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth().
void SAMRAI::hier::Box::growUpper (const int direction, const int ghosts) [inline]
Similar to grow() functions. However, box is only grown in upper bound of given direction in index space.
Parameters:
direction
ghosts
Precondition:
(direction >= 0) && (direction < getDim().getValue())
References empty(), getDim(), and TBOX_ASSERT.
void SAMRAI::hier::Box::lengthen (const int direction, const int ghosts)
Similar to growUpper() and growLower() functions. However, box is lengthened (never shortened).
The sign of ghosts refer to whether the box is lengthened in the upper or lower side.
Parameters:
direction
ghosts
Precondition:
(direction >= 0) && (direction < getDim().getValue())
References empty(), getDim(), and TBOX_ASSERT.
void SAMRAI::hier::Box::shorten (const int direction, const int ghosts)
Similar to growUpper() and growLower() functions. However, box is shortened (never lengthened).
The sign of ghosts refer to whether the box is shortened in the upper or lower side.
Parameters:
direction
ghosts
Precondition:
(direction >= 0) && (direction < getDim().getValue())
References empty(), getDim(), and TBOX_ASSERT.
void SAMRAI::hier::Box::shift (const IntVector & offset) [inline]
Shift this box by the specified offset.
The box will be located at (lower+offset, upper+offset).
Parameters:
offset
Precondition:
getDim() == offset.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), Box(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), SAMRAI::hier::BoundaryBoxUtils::getSurfaceBoxFromBoundaryBox(), initialize(), SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream(), SAMRAI::pdat::ArrayData< TYPE >::packStream(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), SAMRAI::pdat::ArrayData< TYPE >::sum(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::BaseGridGeometry::transformBox().
void SAMRAI::hier::Box::shift (const int direction, const int offset) [inline]
Similar to shift() function above, but shift occurs only in specified direction in index space.
The box will located at (lower+offset, upper+offset) in that direction.
Parameters:
direction
offset
Precondition:
(direction >= 0) && (direction < getDim().getValue())
References getDim(), and TBOX_ASSERT.
void SAMRAI::hier::Box::rotate (const Transformation::RotationIdentifier rotation_ident)
Rotate 90 degrees around origin.
Parameters:
rotation_ident
Precondition:
(getDim().getValue() == 1) || (getDim().getValue() == 2) || (getDim().getValue() == 3)
References getDim(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::BaseGridGeometry::transformBox().
void SAMRAI::hier::Box::refine (const IntVector & ratio)
Refine the index space of a box by specified vector ratio.
Each component of the box is multiplied by the refinement ratio, then (ratio-1) is added to the upper corner.
Parameters:
ratio
Precondition:
getDim() == ratio.getDim()
References coarsen(), getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::hier::Connector::recursivePrint(), refine(), SAMRAI::hier::BoxNeighborhoodCollection::refineNeighbors(), SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch(), and SAMRAI::hier::Connector::shrinkWidth().
void SAMRAI::hier::Box::coarsen (const IntVector & ratio) [inline]
Coarsen the index space of a box by specified vector ratio.
Each component is divided by the specified coarsening ratio and rounded (if necessary) such that the coarsened box contains the cells that are the parents of the refined box. In other words, refining a coarsened box will always yield a box that is equal to or larger than the original box.
Parameters:
ratio
Precondition:
getDim() == ratio.getDim()
References getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::Connector::checkOverlapCorrectness(), coarsen(), SAMRAI::hier::BoxNeighborhoodCollection::coarsenNeighbors(), SAMRAI::hier::Connector::recursivePrint(), refine(), and SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch().
Box& SAMRAI::hier::Box::operator= (const tbox::DatabaseBox & box) [inline]
This assignment operator constructs a Box given a DatabaseBox.
Parameters:
box
Precondition:
getDim().getValue() == box.getDimVal()
References Box_from_DatabaseBox(), getDim(), SAMRAI::tbox::DatabaseBox::getDimVal(), and TBOX_ASSERT.
Box& SAMRAI::hier::Box::Box_from_DatabaseBox (const tbox::DatabaseBox & box) [inline]
Sets a Box from a tbox::DatabaseBox and returns a reference to the Box.
References set_Box_from_DatabaseBox().
Referenced by operator=().
void SAMRAI::hier::Box::set_Box_from_DatabaseBox (const tbox::DatabaseBox & box)
Sets a Box from a DatabaseBox.
References SAMRAI::tbox::DatabaseBox::getDimVal(), SAMRAI::tbox::DatabaseBox::lower(), and SAMRAI::tbox::DatabaseBox::upper().
Referenced by Box(), and Box_from_DatabaseBox().
tbox::DatabaseBox SAMRAI::hier::Box::DatabaseBox_from_Box () const
Returns a tbox::DatabaseBox generated from a Box.
References getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::DatabaseBox::lower(), SAMRAI::tbox::DatabaseBox::setDim(), and SAMRAI::tbox::DatabaseBox::upper().
Referenced by operator tbox::DatabaseBox().
SAMRAI::hier::Box::operator tbox::DatabaseBox () [inline]
Type conversion from Box to DatabaseBox
References DatabaseBox_from_Box().
SAMRAI::hier::Box::operator tbox::DatabaseBox () const [inline]
Type conversion from Box to DatabaseBox
References DatabaseBox_from_Box().
static Box SAMRAI::hier::Box::grow (const Box & box, const IntVector & ghosts) [inline, static]
Static function to grow a box by the specified vector ghost cell width.
Parameters:
box
ghosts
Precondition:
box.getDim() == ghosts.getDim()
References grow(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
static Box SAMRAI::hier::Box::shift (const Box & box, const IntVector & offset) [inline, static]
Static function to shift a box by the specified offset.
Parameters:
box
offset
Precondition:
box.getDim() == offset.getDim()
References lower(), TBOX_ASSERT_OBJDIM_EQUALITY2, and upper().
static Box SAMRAI::hier::Box::refine (const Box & box, const IntVector & ratio) [inline, static]
Static function to refine the index space of a box by the specified refinement ratio.
Parameters:
box
ratio
Precondition:
box.getDim() == ratio.getDim()
References refine(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
static Box SAMRAI::hier::Box::coarsen (const Box & box, const IntVector & ratio) [inline, static]
Static function to coarsen the index space of a box by the specified coarsening ratio.
Parameters:
box
ratio
Precondition:
box.getDim() == ratio.getDim()
References coarsen(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
const tbox::Dimension& SAMRAI::hier::Box::getDim () const [inline]
Return the dimension of this object.
References getDim().
Referenced by SAMRAI::math::PatchSideDataOpsInteger::abs(), SAMRAI::math::PatchSideDataNormOpsComplex::abs(), SAMRAI::math::PatchFaceDataOpsInteger::abs(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchFaceDataNormOpsComplex::abs(), SAMRAI::math::PatchEdgeDataOpsInteger::abs(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchEdgeDataNormOpsComplex::abs(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::add(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::addScalar(), SAMRAI::pdat::ArrayDataIterator::ArrayDataIterator(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::axmy(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::axpy(), Box(), SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::calculateOverlap(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::calculateOverlap(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::calculateOverlap(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPoints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBox(), coalesceWith(), coarsen(), SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchInteriorVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::xfer::BoxGeometryVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerCellVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerCellNoCornersVariableFillPattern::computeFillBoxesOverlap(), contains(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::math::PatchSideDataOpsReal< TYPE >::copyData(), SAMRAI::math::PatchSideDataOpsInteger::copyData(), SAMRAI::math::PatchSideDataOpsComplex::copyData(), SAMRAI::math::PatchFaceDataOpsInteger::copyData(), SAMRAI::math::PatchFaceDataOpsComplex::copyData(), SAMRAI::math::PatchEdgeDataOpsInteger::copyData(), SAMRAI::math::PatchEdgeDataOpsComplex::copyData(), SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::xfer::RefineTimeTransaction::copyLocalData(), DatabaseBox_from_Box(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::divide(), SAMRAI::math::PatchSideDataNormOpsComplex::dot(), SAMRAI::math::PatchFaceDataNormOpsComplex::dot(), SAMRAI::math::PatchEdgeDataNormOpsComplex::dot(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::pdat::ArrayData< TYPE >::fill(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), SAMRAI::hier::BoxUtilities::findBadCutPoints(), SAMRAI::hier::BoxUtilities::findBadCutPointsForBorderAndDirection(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::fixBadCutPoints(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::Patch::getDim(), getDim(), SAMRAI::pdat::SideData< TYPE >::getSizeOfData(), SAMRAI::pdat::OutersideData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuternodeData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuterfaceData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuteredgeData< TYPE >::getSizeOfData(), SAMRAI::pdat::FaceData< TYPE >::getSizeOfData(), SAMRAI::pdat::EdgeData< TYPE >::getSizeOfData(), grow(), growLower(), growUpper(), index(), SAMRAI::math::PatchSideDataNormOpsComplex::integral(), SAMRAI::math::PatchFaceDataNormOpsComplex::integral(), SAMRAI::math::PatchEdgeDataNormOpsComplex::integral(), intersects(), isEmpty(), SAMRAI::math::PatchSideDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchSideDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L2Norm(), lengthen(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::linearSum(), longestDirection(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::max(), SAMRAI::math::PatchSideDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchFaceDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::min(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::multiply(), numberCells(), SAMRAI::math::PatchSideDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsComplex::numberOfEntries(), SAMRAI::math::PatchFaceDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsComplex::numberOfEntries(), SAMRAI::math::PatchEdgeDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsComplex::numberOfEntries(), offset(), SAMRAI::pdat::SideIterator::operator++(), SAMRAI::pdat::NodeIterator::operator++(), SAMRAI::pdat::FaceIterator::operator++(), SAMRAI::pdat::EdgeIterator::operator++(), SAMRAI::pdat::CellIterator::operator++(), SAMRAI::pdat::ArrayDataIterator::operator++(), operator=(), SAMRAI::pdat::OuternodeData< TYPE >::OuternodeData(), SAMRAI::xfer::RefineTimeTransaction::packStream(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::reciprocal(), SAMRAI::hier::Patch::recursivePrint(), refine(), SAMRAI::hier::BoxContainer::removeIntersections(), rotate(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::scale(), SAMRAI::hier::BoxContainer::separatePeriodicImages(), setEmpty(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::setRandomValues(), shift(), shorten(), SAMRAI::pdat::SideData< TYPE >::SideData(), size(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::subtract(), SAMRAI::pdat::ArrayData< TYPE >::sum(), SAMRAI::math::PatchSideDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchFaceDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchEdgeDataNormOpsComplex::sumControlVolumes(), SAMRAI::pdat::EdgeGeometry::toEdgeBox(), SAMRAI::pdat::FaceGeometry::toFaceBox(), SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox(), SAMRAI::pdat::SideGeometry::toSideBox(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::pdat::EdgeGeometry::transform(), SAMRAI::hier::BoxContainer::unshiftPeriodicImageBoxes(), SAMRAI::math::PatchSideDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::weightedL2Norm(), and SAMRAI::math::PatchEdgeDataNormOpsComplex::weightedL2Norm().
void SAMRAI::hier::Box::lockId () [inline]
Lock the BoxId of this Box so that it may not be changed in any way.
Referenced by SAMRAI::hier::BoxContainer::insert().
bool SAMRAI::hier::Box::idLocked () [inline]
Returns true if the BoxId of this Box is locked.
Referenced by initialize().
static const Box& SAMRAI::hier::Box::getEmptyBox (const tbox::Dimension & dim) [inline, static]
Return an empty Box of the specified dimension.
Can be used to avoid object creation overheads.
References SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::xfer::RefineTransactionFactory::allocate(), SAMRAI::algs::OuteredgeSumTransactionFactory::allocate(), and SAMRAI::pdat::SideData< TYPE >::SideData().
static const Box& SAMRAI::hier::Box::getUniverse (const tbox::Dimension & dim) [inline, static]
Returns a Box that represents the maximum allowed index extents for a given dimension. The "universe" that can be represented.
References SAMRAI::tbox::Dimension::getValue().
Friends And Related Function Documentation
friend class BoxIterator [friend]
std::istream& operator>> (std::istream & s, Box & box) [friend]
Read the box description in the form [L,U], where L and U are the lower and upper bounds of the box.
std::ostream& operator<< (std::ostream & s, const Box & box) [friend]
Output the box description in the form [L,U], where L and U are the lower and upper bounds of the box.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/Box.h
source/SAMRAI/hier/Box.C