SAMRAI: SAMRAI::math::PatchSideDataOpsReal< TYPE > Class Template Reference
SAMRAI::math::PatchSideDataOpsReal< TYPE > Class Template Reference
#include <source/SAMRAI/math/PatchSideDataOpsReal.h>
Public Member Functions
PatchSideDataOpsReal ()
virtual ~PatchSideDataOpsReal ()
void copyData (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const TYPE &alpha, const hier::Box &box) const
Detailed Description
template<class TYPE>
class SAMRAI::math::PatchSideDataOpsReal< TYPE >
Class PatchSideDataOpsReal provides a collection of operations to manipulate float and double numerical side-centered patch data. The operations include basic arithmetic, norms and ordering, and assorted miscellaneous operations. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base classes PatchSideDataBasicOps, PatchSideDataNormOpsReal, and PatchSideDataMiscellaneousOpsReal from which it is derived. The name of each of these base classes is indicative of the set of side-centered patch data operations that it provides.
Note that this templated class should only be used to instantiate objects with double or float as the template parameter. A similar set of operations is implemented for complex and integer patch data in the classes PatchSideDataOpsComplex and PatchSideDataOpsInteger, repsectively.
See also:
math::PatchSideDataBasicOps
math::PatchSideDataMiscellaneousOpsReal
math::PatchSideDataNormOpsReal
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::math::PatchSideDataOpsReal< TYPE >::PatchSideDataOpsReal () [inline]
Empty constructor and destructor.
template<class TYPE > SAMRAI::math::PatchSideDataOpsReal< TYPE >::~PatchSideDataOpsReal () [inline, virtual]
Member Function Documentation
template<class TYPE > void SAMRAI::math::PatchSideDataOpsReal< TYPE >::copyData (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src, const hier::Box & box) const [inline]
Copy dst data to src data over given box.
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::math::PatchSideDataOpsReal< TYPE >::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const [inline]
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::SideData<TYPE> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::SideData<TYPE> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getDirectionVector() == patch->getPatchData(data2_id)->getDirectionVector()
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::PatchSideDataOpsReal< TYPE >::printData (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const [inline]
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::math::PatchSideDataOpsReal< TYPE >::setToScalar (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const TYPE & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchSideDataOpsReal.h
source/SAMRAI/math/PatchSideDataOpsReal.C