SAMRAI: SAMRAI::mesh::BoxTransitSet Class Reference
SAMRAI::mesh::BoxTransitSet Class Reference
Implementation of TransitLoad, representing the load with a set of boxes, each of which represents a load and knows the origin of its load.
#include <source/SAMRAI/mesh/BoxTransitSet.h>
Classes
class Outputter
Intermediary between BoxTransitSet and output streams, adding ability to control the output. See BoxTransitSet::format().
Public Types
typedef double LoadType
Public Member Functions
void reassignOwnership (hier::SequentialLocalIdGenerator &id_gen, int new_owner_rank)
void putInBoxLevel (hier::BoxLevel &box_level) const
Put local Boxes into a BoxLevel.
void generateLocalBasedMapEdges (hier::MappingConnector &unbalanced_to_balanced, hier::MappingConnector &balanced_to_unbalanced) const
Generate unbalanced<==>balanced edges incident from local boxes.
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
void setPrintFlags (bool steps, bool pop_steps, bool swap_steps, bool break_steps, bool edge_steps)
Set print flags for individual object.
void recursivePrint (std::ostream &co=tbox::plog, const std::string &border=std::string(), int detail_depth=1) const
Object printing method to aid in debugging.
Outputter format (const std::string &border=std::string(), int detail_depth=2) const
Return a object to that can format the BoxTransitSet for inserting into output streams.
Constructor
BoxTransitSet (const PartitioningParams &pparams)
Copy constructor
The content may be omitted from the copy, using the flag copy_load.
BoxTransitSet (const BoxTransitSet &other, bool copy_load=true)
TransitLoad abstract interfaces
BoxTransitSet * clone () const
void initialize ()
LoadType getSumLoad () const
void insertAll (const hier::BoxContainer &box_container)
void insertAll (TransitLoad &other)
void insertAllWithExistingLoads (const hier::BoxContainer &box_container)
void setWorkload (const hier::PatchLevel &patch_level, const int work_data_id)
Set workloads in the members of this BoxTransitSet.
size_t getNumberOfItems () const
size_t getNumberOfOriginatingProcesses () const
void putToMessageStream (tbox::MessageStream &msg) const
void getFromMessageStream (tbox::MessageStream &msg)
LoadType adjustLoad (TransitLoad &hold_bin, LoadType ideal_load, LoadType low_load, LoadType high_load)
void assignToLocal (hier::BoxLevel &balanced_box_level, const hier::BoxLevel &unbalanced_box_level, double flexible_load_tol=0.0, const tbox::SAMRAI_MPI &alt_mpi=tbox::SAMRAI_MPI(MPI_COMM_NULL))
void assignToLocalAndPopulateMaps (hier::BoxLevel &balanced_box_level, hier::MappingConnector &balanced_to_unbalanced, hier::MappingConnector &unbalanced_to_balanced, double flexible_load_tol=0.0, const tbox::SAMRAI_MPI &alt_mpi=tbox::SAMRAI_MPI(MPI_COMM_NULL))
Interfaces like the C++ standard stl::set, to help readability.
typedef std::set< BoxInTransit,
BoxInTransitMoreLoad >
::iterator iterator
typedef std::set< BoxInTransit,
BoxInTransitMoreLoad >
::const_iterator const_iterator
typedef std::set< BoxInTransit,
BoxInTransitMoreLoad >
::reverse_iterator reverse_iterator
typedef std::set< BoxInTransit,
BoxInTransitMoreLoad >
::key_type key_type
typedef std::set< BoxInTransit,
BoxInTransitMoreLoad >
::value_type value_type
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
size_t size () const
std::pair< iterator, bool > insert (const value_type &x)
void erase (iterator pos)
size_t erase (const key_type &k)
bool empty () const
Whether container is empty.
void clear ()
Empty the container.
void swap (BoxTransitSet &other)
iterator lower_bound (const key_type &k) const
iterator upper_bound (const key_type &k) const
Detailed Description
Implementation of TransitLoad, representing the load with a set of boxes, each of which represents a load and knows the origin of its load.
As a container, this class is nearly identical to std::set<BoxInTransit,BoxInTransitMoreLoad>.
Member Typedef Documentation
typedef double SAMRAI::mesh::BoxTransitSet::LoadType
typedef std::set<BoxInTransit, BoxInTransitMoreLoad>::iterator SAMRAI::mesh::BoxTransitSet::iterator
typedef std::set<BoxInTransit, BoxInTransitMoreLoad>::const_iterator SAMRAI::mesh::BoxTransitSet::const_iterator
typedef std::set<BoxInTransit, BoxInTransitMoreLoad>::reverse_iterator SAMRAI::mesh::BoxTransitSet::reverse_iterator
typedef std::set<BoxInTransit, BoxInTransitMoreLoad>::key_type SAMRAI::mesh::BoxTransitSet::key_type
typedef std::set<BoxInTransit, BoxInTransitMoreLoad>::value_type SAMRAI::mesh::BoxTransitSet::value_type
Constructor & Destructor Documentation
SAMRAI::mesh::BoxTransitSet::BoxTransitSet (const PartitioningParams & pparams)
References SAMRAI::mesh::BalanceBoxBreaker::setPrintBreakSteps(), setTimerPrefix(), and TBOX_ASSERT.
Referenced by clone().
SAMRAI::mesh::BoxTransitSet::BoxTransitSet (const BoxTransitSet & other, bool copy_load = true)
References SAMRAI::mesh::BalanceBoxBreaker::setPrintBreakSteps().
Member Function Documentation
BoxTransitSet * SAMRAI::mesh::BoxTransitSet::clone () const [virtual]
Clone object according to design pattern.
Implements SAMRAI::mesh::TransitLoad.
References BoxTransitSet().
void SAMRAI::mesh::BoxTransitSet::initialize () [virtual]
Initialize object according to design pattern.
Implements SAMRAI::mesh::TransitLoad.
LoadType SAMRAI::mesh::BoxTransitSet::getSumLoad () const [inline, virtual]
Container-like characteristics. Return the total load contained.
Implements SAMRAI::mesh::TransitLoad.
Referenced by adjustLoad(), and recursivePrint().
void SAMRAI::mesh::BoxTransitSet::insertAll (const hier::BoxContainer & box_container) [virtual]
Insert all boxes from the given BoxContainer.
Implements SAMRAI::mesh::TransitLoad.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::mesh::BoxInTransit::getLoad(), SAMRAI::mesh::BoxInTransit::getSize(), SAMRAI::hier::BoxContainer::size(), and TBOX_ERROR.
void SAMRAI::mesh::BoxTransitSet::insertAll (TransitLoad & other)
Insert all boxes from the given TransitLoad. Changes to other as an implementation side-effect is allowed. This and other are guaranteed to be the same concrete type.
Parameters:
other [in] Other TransitLoad container whose implementation matches this one.
References size(), and TBOX_ERROR.
void SAMRAI::mesh::BoxTransitSet::insertAllWithExistingLoads (const hier::BoxContainer & box_container) [virtual]
Insert Boxes from the given container but preserve load values currently held by the TransitLoad.
Implements SAMRAI::mesh::TransitLoad.
References begin(), SAMRAI::hier::BoxContainer::end(), end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::mesh::BoxInTransit::setCornerWeights(), SAMRAI::mesh::BoxInTransit::setLoad(), and TBOX_ERROR.
void SAMRAI::mesh::BoxTransitSet::setWorkload (const hier::PatchLevel & patch_level, const int work_data_id) [virtual]
Set workloads in the members of this BoxTransitSet.
The BoxInTransit members of this BoxTransitSet will have their workload values set according to the data on the given patch level associated with the given data id
Parameters:
[in] patch_level Level with boxes that are the same as those held in this BoxTransitSet
[in] work_data_id Data id for the workload data that exists on the patch level
Implements SAMRAI::mesh::TransitLoad.
References begin(), SAMRAI::mesh::BalanceUtilities::computeNonUniformWorkloadOnCorners(), end(), SAMRAI::mesh::BoxInTransit::getLoad(), SAMRAI::hier::PatchLevel::getPatch(), SAMRAI::mesh::BoxInTransit::setCornerWeights(), and SAMRAI::mesh::BoxInTransit::setLoad().
size_t SAMRAI::mesh::BoxTransitSet::getNumberOfItems () const [virtual]
Return number of items in this container.
Implements SAMRAI::mesh::TransitLoad.
References size().
size_t SAMRAI::mesh::BoxTransitSet::getNumberOfOriginatingProcesses () const [virtual]
Return number of processes contributing to the contents.
Implements SAMRAI::mesh::TransitLoad.
References begin(), and end().
void SAMRAI::mesh::BoxTransitSet::putToMessageStream (tbox::MessageStream & msg) const [virtual]
Put content into MessageStream.
Implements SAMRAI::mesh::TransitLoad.
References begin(), end(), SAMRAI::mesh::BoxInTransit::putToMessageStream(), and size().
void SAMRAI::mesh::BoxTransitSet::getFromMessageStream (tbox::MessageStream & msg) [virtual]
Add to content from MessageStream.
Implements SAMRAI::mesh::TransitLoad.
References SAMRAI::mesh::PartitioningParams::getDim(), and insert().
BoxTransitSet::LoadType SAMRAI::mesh::BoxTransitSet::adjustLoad (TransitLoad & hold_bin, LoadType ideal_load, LoadType low_load, LoadType high_load)
Adjust the load in this TransitSet by moving work between it and another TransitSet.
Parameters:
[in,out] hold_bin Holding bin for reserve load. hold_bin implementation is guaranteed to match this one.
[in] ideal_load The load that this bin should have.
[in] low_load Return when this bin's load is in the range [low_load,high_load]
[in] high_load Return when this bin's load is in the range [low_load,high_load]
Returns:
Net load added to this TransitSet. If negative, load decreased.
References empty(), SAMRAI::mesh::TransitLoad::getAllowBoxBreaking(), SAMRAI::mesh::PartitioningParams::getMinBoxSize(), SAMRAI::mesh::PartitioningParams::getMinLoad(), SAMRAI::hier::IntVector::getProduct(), getSumLoad(), SAMRAI::tbox::plog, size(), and TBOX_ASSERT.
void SAMRAI::mesh::BoxTransitSet::assignToLocal (hier::BoxLevel & balanced_box_level, const hier::BoxLevel & unbalanced_box_level, double flexible_load_tol = 0.0, const tbox::SAMRAI_MPI & alt_mpi = tbox::SAMRAI_MPI(MPI_COMM_NULL)) [virtual]
Assign contents to local process. This method may use communication.
Parameters:
[in,out] balanced_box_level Empty BoxLevel to populate with the contents of this TransitLoad.
[in] unbalanced_box_level
[in] flexible_load_tol
[in] alt_mpi Alternate SAMRAI_MPI to use for communication if needed, overriding that in balanced_box_level.
Implements SAMRAI::mesh::TransitLoad.
References SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), NULL_USE, putInBoxLevel(), and reassignOwnership().
Referenced by assignToLocalAndPopulateMaps().
void SAMRAI::mesh::BoxTransitSet::assignToLocalAndPopulateMaps (hier::BoxLevel & balanced_box_level, hier::MappingConnector & balanced_to_unbalanced, hier::MappingConnector & unbalanced_to_balanced, double flexible_load_tol = 0.0, const tbox::SAMRAI_MPI & alt_mpi = tbox::SAMRAI_MPI(MPI_COMM_NULL)) [virtual]
Assign contents to local process and populate the balanced<==>unbalanced maps. This method may use communication.
Parameters:
[in,out] balanced_box_level Empty BoxLevel to populate with the contents of this TransitLoad.
[in,out] balanced_to_unbalanced Empty Connector to populate with the balanced--->unbalanced edges.
[in,out] unbalanced_to_balanced Empty Connector to populate with the unbalanced--->balanced edges.
[in] flexible_load_tol
[in] alt_mpi Alternate SAMRAI_MPI to use for communication if needed, overriding that in balanced_box_level.
This method uses communication to populate the map.
Implements SAMRAI::mesh::TransitLoad.
References assignToLocal(), SAMRAI::hier::Connector::getBase(), NULL_USE, and SAMRAI::tbox::plog.
void SAMRAI::mesh::BoxTransitSet::reassignOwnership (hier::SequentialLocalIdGenerator & id_gen, int new_owner_rank)
References begin(), end(), and SAMRAI::hier::SequentialLocalIdGenerator::nextValue().
Referenced by assignToLocal().
void SAMRAI::mesh::BoxTransitSet::putInBoxLevel (hier::BoxLevel & box_level) const
Put local Boxes into a BoxLevel.
References SAMRAI::hier::BoxLevel::addBox(), begin(), end(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), and TBOX_ASSERT.
Referenced by assignToLocal().
void SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges (hier::MappingConnector & unbalanced_to_balanced, hier::MappingConnector & balanced_to_unbalanced) const
Generate unbalanced<==>balanced edges incident from local boxes.
This method does no communication. Semilocal edges not incident from remote Boxes are not communicated.
References begin(), end(), SAMRAI::hier::Connector::getBase(), SAMRAI::mesh::BoxInTransit::getBox(), SAMRAI::hier::Box::getBoxId(), SAMRAI::mesh::BoxInTransit::getOrigBox(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::Connector::insertLocalNeighbor(), and SAMRAI::mesh::BoxInTransit::isOriginal().
void SAMRAI::mesh::BoxTransitSet::setTimerPrefix (const std::string & timer_prefix) [virtual]
Setup names of timers.
By default, timers are named "mesh::BoxTransitSet::*", where the third field is the specific steps performed by the Schedule. You can override the first two fields with this method. Conforming to the timer naming convention, timer_prefix should have the form "*::*".
Reimplemented from SAMRAI::mesh::TransitLoad.
Referenced by BoxTransitSet(), and SAMRAI::mesh::VoucherTransitLoad::setTimerPrefix().
void SAMRAI::mesh::BoxTransitSet::setPrintFlags (bool steps, bool pop_steps, bool swap_steps, bool break_steps, bool edge_steps)
Set print flags for individual object.
void SAMRAI::mesh::BoxTransitSet::recursivePrint (std::ostream & co = tbox::plog, const std::string & border = std::string(), int detail_depth = 1) const [virtual]
Object printing method to aid in debugging.
Reimplemented from SAMRAI::mesh::TransitLoad.
References begin(), end(), getSumLoad(), SAMRAI::tbox::plog, and size().
Outputter SAMRAI::mesh::BoxTransitSet::format (const std::string & border = std::string(), int detail_depth = 2) const [inline]
Return a object to that can format the BoxTransitSet for inserting into output streams.
Usage example (printing with a tab indentation):
    *    cout << "my boxes:\n" << boxes.format("\t") << endl;
    *
Parameters:
[in] border Left border of the output
[in] detail_depth How much detail to print.
iterator SAMRAI::mesh::BoxTransitSet::begin () [inline]
Referenced by generateLocalBasedMapEdges(), getNumberOfOriginatingProcesses(), insertAllWithExistingLoads(), putInBoxLevel(), putToMessageStream(), reassignOwnership(), recursivePrint(), and setWorkload().
iterator SAMRAI::mesh::BoxTransitSet::end () [inline]
Referenced by generateLocalBasedMapEdges(), getNumberOfOriginatingProcesses(), insertAllWithExistingLoads(), putInBoxLevel(), putToMessageStream(), reassignOwnership(), recursivePrint(), and setWorkload().
const_iterator SAMRAI::mesh::BoxTransitSet::begin () const [inline]
const_iterator SAMRAI::mesh::BoxTransitSet::end () const [inline]
reverse_iterator SAMRAI::mesh::BoxTransitSet::rbegin () const [inline]
reverse_iterator SAMRAI::mesh::BoxTransitSet::rend () const [inline]
size_t SAMRAI::mesh::BoxTransitSet::size () const [inline]
Referenced by adjustLoad(), getNumberOfItems(), insertAll(), putToMessageStream(), and recursivePrint().
std::pair<iterator, bool> SAMRAI::mesh::BoxTransitSet::insert (const value_type & x) [inline]
Referenced by getFromMessageStream(), and SAMRAI::mesh::VoucherTransitLoad::setWorkload().
void SAMRAI::mesh::BoxTransitSet::erase (iterator pos) [inline]
size_t SAMRAI::mesh::BoxTransitSet::erase (const key_type & k) [inline]
bool SAMRAI::mesh::BoxTransitSet::empty () const [inline, virtual]
Whether container is empty.
Reimplemented from SAMRAI::mesh::TransitLoad.
Referenced by adjustLoad().
void SAMRAI::mesh::BoxTransitSet::clear () [inline, virtual]
Empty the container.
Implements SAMRAI::mesh::TransitLoad.
Referenced by SAMRAI::mesh::VoucherTransitLoad::setWorkload().
void SAMRAI::mesh::BoxTransitSet::swap (BoxTransitSet & other) [inline]
iterator SAMRAI::mesh::BoxTransitSet::lower_bound (const key_type & k) const [inline]
iterator SAMRAI::mesh::BoxTransitSet::upper_bound (const key_type & k) const [inline]
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/BoxTransitSet.h
source/SAMRAI/mesh/BoxTransitSet.C