SAMRAI: SAMRAI::geom::CartesianGridGeometry Class Reference
SAMRAI::geom::CartesianGridGeometry Class Reference
#include <source/SAMRAI/geom/CartesianGridGeometry.h>
Public Member Functions
CartesianGridGeometry (const tbox::Dimension &dim, const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db)
CartesianGridGeometry (const std::string &object_name, const double *x_lo, const double *x_up, hier::BoxContainer &domain)
CartesianGridGeometry (const std::string &object_name, const double *x_lo, const double *x_up, hier::BoxContainer &domain, const boost::shared_ptr< hier::TransferOperatorRegistry > &op_reg)
Construct a new coarsened/refined CartesianGridGeometry object with the supplied domain.
virtual ~CartesianGridGeometry ()
boost::shared_ptr
< hier::BaseGridGeometry > makeRefinedGridGeometry (const std::string &fine_geom_name, const hier::IntVector &refine_ratio) const
boost::shared_ptr
< hier::BaseGridGeometry > makeCoarsenedGridGeometry (const std::string &coarse_geom_name, const hier::IntVector &coarsen_ratio) const
void setGeometryDataOnPatch (hier::Patch &patch, const hier::IntVector &ratio_to_level_zero, const TwoDimBool &touches_regular_bdry) const
Compute and set grid data for patch.
void setGeometryData (const double *x_lo, const double *x_up, const hier::BoxContainer &domain)
const double * getDx () const
const double * getXLower () const
const double * getXUpper () const
virtual void printClassData (std::ostream &os) const
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Protected Member Functions
virtual void buildOperators ()
Build operators appropriate for a CartesianGridGeometry.
Detailed Description
Class CartesianGridGeometry provides simple Cartesian mesh geometry management on an AMR hierarchy. The mesh coordinates on each hierarchy level are limited to mesh increments specified as DIM-tuple (dx[0],...,dx[DIM-1]) and spatial coordinates of the lower and upper corners of the smallest parallelepiped bounding the entire computational domain. The mesh increments on each level are defined with respect to the coarsest hierarchy level and multiplying those values by the proper refinement ratio. This class sets geometry information on each patch in an AMR hierarchy. This class is derived from the geom::GridGeometry base class.
Input Parameters
Definitions:
domain_boxes an array of boxes representing the index space for the entire domain on the coarsest mesh level; i.e., level zero.
periodic_dimension An array of integer values (expected number of values is equal to the spatial dimension of the mesh) representing the directions in which the physical domain is periodic. A non-zero value indicates that the direction is periodic. A zero value indicates that the direction is not periodic.
x_lo values representing the spatial coordinates of the lower corner of the physical domain.
x_up values representing the spatial coordinates of the upper corner of the physical domain.
No values read in from a restart database may be overridden by input database values.
Details:
parameter
type
default
range
opt/req
behavior on restart
domain_boxes
array of DatabaseBoxes
none
all Boxes must be non-empty
req
May not be modified by input db on restart
periodic_dimension
int[]
all values 0
any int
opt
May not be modified by input db on restart
x_lo
double[]
none
each x_lo < corresponding x_up
req
May not be modified by input db on restart
x_up
double[]
none
each x_up > corresponding x_lo
req
May not be modified by input db on restart
A sample input file for a two-dimensional problem might look like:
    domain_boxes = [(0,0) , (49,39)]
    x_lo = 0.0 , 0.0
    x_up = 50.0 , 40.0
    periodic_dimension = 0, 1  // periodic in y only
This generates a two-dimensional rectangular domain periodic in the y-direction, and having 50 cells in the x-direction and 40 cells in the y-direction, with the cell size 1 unit in each direction.
See also:
geom::GridGeometry
Constructor & Destructor Documentation
SAMRAI::geom::CartesianGridGeometry::CartesianGridGeometry (const tbox::Dimension & dim, const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db)
Constructor for CartesianGridGeometry initializes data members based on parameters read from the specified input database or from the restart database corresponding to the specified object name.
Precondition:
!object_name.empty()
input_db
References buildOperators(), SAMRAI::tbox::RestartManager::getManager(), and TBOX_ASSERT.
Referenced by makeCoarsenedGridGeometry(), and makeRefinedGridGeometry().
SAMRAI::geom::CartesianGridGeometry::CartesianGridGeometry (const std::string & object_name, const double * x_lo, const double * x_up, hier::BoxContainer & domain)
Constructor for CartesianGridGeometry sets data members based on arguments.
Precondition:
!object_name.empty()
domain.size() > 0
x_lo != 0
x_up != 0
References buildOperators(), setGeometryData(), SAMRAI::hier::BoxContainer::size(), and TBOX_ASSERT.
SAMRAI::geom::CartesianGridGeometry::CartesianGridGeometry (const std::string & object_name, const double * x_lo, const double * x_up, hier::BoxContainer & domain, const boost::shared_ptr< hier::TransferOperatorRegistry > & op_reg)
Construct a new coarsened/refined CartesianGridGeometry object with the supplied domain.
This method is intended to be called only by boost::make_shared from the make[Coarsened, Refined]GridGeometry methods to make a coarsened or refined version of a given CartesianGridGeometry.
Parameters:
[in] object_name The same name as the uncoarsened/unrefined grid geometry.
[in] x_lo The same lower corner as the uncoarsened/unrefined grid geometry.
[in] x_up The same upper corner as the uncoarsened/unrefined grid geometry.
[in] domain The coarsened/refined domain.
[in] op_reg The same operator registry as the uncoarsened/unrefined grid geometry.
Precondition:
!object_name.empty()
domain.size() > 0
x_lo != 0
x_up != 0
References buildOperators(), setGeometryData(), SAMRAI::hier::BoxContainer::size(), and TBOX_ASSERT.
SAMRAI::geom::CartesianGridGeometry::~CartesianGridGeometry () [virtual]
Destructor for CartesianGridGeometry deallocates data describing grid geometry and unregisters the object with the restart manager.
Member Function Documentation
boost::shared_ptr< hier::BaseGridGeometry > SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry (const std::string & fine_geom_name, const hier::IntVector & refine_ratio) const [virtual]
Create and return a pointer to a refined version of this Cartesian grid geometry object.
Precondition:
!fine_geom_name.empty()
fine_geom_name != getObjectName()
refine_ratio > hier::IntVector::getZero(getDim())
Reimplemented from SAMRAI::geom::GridGeometry.
References CartesianGridGeometry(), SAMRAI::hier::BaseGridGeometry::d_transfer_operator_registry, SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::hier::BaseGridGeometry::getObjectName(), SAMRAI::hier::BaseGridGeometry::getPeriodicShift(), SAMRAI::hier::BaseGridGeometry::getPhysicalDomain(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::refine(), and TBOX_ASSERT.
boost::shared_ptr< hier::BaseGridGeometry > SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry (const std::string & coarse_geom_name, const hier::IntVector & coarsen_ratio) const [virtual]
Create and return a pointer to a coarsened version of this Cartesian grid geometry object.
Precondition:
!coarse_geom_name.empty()
coarse_geom_name != getObjectName()
coarsen_ratio > hier::IntVector::getZero(getDim())
Reimplemented from SAMRAI::geom::GridGeometry.
References SAMRAI::hier::BoxContainer::begin(), CartesianGridGeometry(), SAMRAI::hier::BoxContainer::coarsen(), SAMRAI::hier::BaseGridGeometry::d_transfer_operator_registry, SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::hier::BaseGridGeometry::getObjectName(), SAMRAI::hier::BaseGridGeometry::getPeriodicShift(), SAMRAI::hier::BaseGridGeometry::getPhysicalDomain(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Box::isSpatiallyEqual(), SAMRAI::tbox::plog, SAMRAI::hier::Box::refine(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch (hier::Patch & patch, const hier::IntVector & ratio_to_level_zero, const TwoDimBool & touches_regular_bdry) const [virtual]
Compute and set grid data for patch.
Virtual method -- should be overridden in specialized grid geometry classes
Parameters:
[in,out] patch The patch on which to set grid data and the new concrete patch geometry object.
[in] ratio_to_level_zero ratio to coarsest level
[in] touches_regular_bdry Array storing which patches touch non-periodic boundaries.
Precondition:
(getDim() == patch.getDim()) && (getDim() == ratio_to_level_zero.getDim()) && (getDim() == touches_regular_bdry.getDim())
Reimplemented from SAMRAI::hier::BaseGridGeometry.
References SAMRAI::hier::Box::coarsen(), SAMRAI::hier::Patch::getBox(), SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::refine(), SAMRAI::hier::Patch::setPatchGeometry(), TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY2.
void SAMRAI::geom::CartesianGridGeometry::setGeometryData (const double * x_lo, const double * x_up, const hier::BoxContainer & domain)
Set data members for this CartesianGridGeometry object.
Precondition:
x_lo != 0
x_up != 0
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::hier::BaseGridGeometry::getPhysicalDomain(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), and TBOX_ASSERT.
Referenced by CartesianGridGeometry().
const double* SAMRAI::geom::CartesianGridGeometry::getDx () const [inline]
Return const pointer to dx array for reference level in hierarchy.
const double* SAMRAI::geom::CartesianGridGeometry::getXLower () const [inline]
Return const pointer to lower spatial coordinate for reference level in hierarchy.
const double* SAMRAI::geom::CartesianGridGeometry::getXUpper () const [inline]
Return const pointer to upper spatial coordinate for reference level in hierarchy.
void SAMRAI::geom::CartesianGridGeometry::printClassData (std::ostream & os) const [virtual]
Print class data representation.
Reimplemented from SAMRAI::hier::BaseGridGeometry.
References SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::hier::BaseGridGeometry::getObjectName(), and SAMRAI::tbox::Dimension::getValue().
void SAMRAI::geom::CartesianGridGeometry::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [virtual]
Writes the state of the CartesianGridGeometry object to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::BaseGridGeometry.
References SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
void SAMRAI::geom::CartesianGridGeometry::buildOperators () [protected, virtual]
Build operators appropriate for a CartesianGridGeometry.
Reimplemented from SAMRAI::geom::GridGeometry.
References SAMRAI::hier::BaseGridGeometry::addCoarsenOperator(), and SAMRAI::hier::BaseGridGeometry::addRefineOperator().
Referenced by CartesianGridGeometry().
The documentation for this class was generated from the following files:
source/SAMRAI/geom/CartesianGridGeometry.h
source/SAMRAI/geom/CartesianGridGeometry.C