SAMRAI: SAMRAI::mesh::VoucherTransitLoad Class Reference
SAMRAI::mesh::VoucherTransitLoad Class Reference
Implementation of TransitLoad, representing the load with a set of vouchers, each of which has a work value and the rank of the process that issued the voucher.
#include <source/SAMRAI/mesh/VoucherTransitLoad.h>
Public Types
typedef double LoadType
Public Member Functions
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
void recursivePrint (std::ostream &co=tbox::plog, const std::string &border=std::string(), int detail_depth=1) const
Object printing method to aid in debugging.
Constructor
VoucherTransitLoad (const PartitioningParams &pparams)
Copy constructor
VoucherTransitLoad (const VoucherTransitLoad &other, bool copy_load=true)
TransitLoad abstract interfaces
VoucherTransitLoad * clone () const
void initialize ()
LoadType getSumLoad () const
void insertAll (const hier::BoxContainer &box_container)
void insertAll (TransitLoad &other)
size_t getNumberOfItems () const
size_t getNumberOfOriginatingProcesses () const
void putToMessageStream (tbox::MessageStream &msg) const
void getFromMessageStream (tbox::MessageStream &msg)
LoadType adjustLoad (TransitLoad &hold_bin, LoadType ideal_load, LoadType low_load, LoadType high_load)
void assignToLocalAndPopulateMaps (hier::BoxLevel &balanced_box_level, hier::MappingConnector &balanced_to_unbalanced, hier::MappingConnector &unbalanced_to_balanced, double flexible_load_tol=0.0)
Detailed Description
Implementation of TransitLoad, representing the load with a set of vouchers, each of which has a work value and the rank of the process that issued the voucher.
As a container, this class is nearly identical to std::set<Voucher,VoucherMoreLoad>.
Terminology: To avoid confusing the sending and receiving of messages, the sending and receiving of work use the terms supply and demand. During redemption of vouchers, the holder of a voucher demands the work. The issuer of that voucher supplies the work. Both send and receive messages to accomplish this.
Member Typedef Documentation
typedef double SAMRAI::mesh::VoucherTransitLoad::LoadType
Constructor & Destructor Documentation
SAMRAI::mesh::VoucherTransitLoad::VoucherTransitLoad (const PartitioningParams & pparams)
References setTimerPrefix().
Referenced by clone().
SAMRAI::mesh::VoucherTransitLoad::VoucherTransitLoad (const VoucherTransitLoad & other, bool copy_load = true)
Member Function Documentation
VoucherTransitLoad * SAMRAI::mesh::VoucherTransitLoad::clone () const [virtual]
Clone object according to design pattern.
Implements SAMRAI::mesh::TransitLoad.
References VoucherTransitLoad().
void SAMRAI::mesh::VoucherTransitLoad::initialize () [virtual]
Initialize object according to design pattern.
Implements SAMRAI::mesh::TransitLoad.
LoadType SAMRAI::mesh::VoucherTransitLoad::getSumLoad () const [inline, virtual]
Container-like characteristics. Return the total load contained.
Implements SAMRAI::mesh::TransitLoad.
Referenced by adjustLoad(), and recursivePrint().
void SAMRAI::mesh::VoucherTransitLoad::insertAll (const hier::BoxContainer & box_container) [virtual]
Insert all boxes from the given BoxContainer.
Implements SAMRAI::mesh::TransitLoad.
References SAMRAI::hier::BoxContainer::begin(), and SAMRAI::hier::BoxContainer::end().
void SAMRAI::mesh::VoucherTransitLoad::insertAll (TransitLoad & other)
Insert all boxes from the given TransitSet. Changes to other as an implementation side-effect is allowed. This and other are guaranteed to be the same concrete type.
Parameters:
other [i] Other TransitLoad container whose implementation matches this one.
References SAMRAI::mesh::PartitioningParams::getLoadComparisonTol(), and TBOX_ASSERT.
size_t SAMRAI::mesh::VoucherTransitLoad::getNumberOfItems () const [virtual]
Return number of items in this container.
Implements SAMRAI::mesh::TransitLoad.
size_t SAMRAI::mesh::VoucherTransitLoad::getNumberOfOriginatingProcesses () const [virtual]
Return number of processes contributing to the contents.
Implements SAMRAI::mesh::TransitLoad.
void SAMRAI::mesh::VoucherTransitLoad::putToMessageStream (tbox::MessageStream & msg) const [virtual]
Put content into MessageStream.
Implements SAMRAI::mesh::TransitLoad.
void SAMRAI::mesh::VoucherTransitLoad::getFromMessageStream (tbox::MessageStream & msg) [virtual]
Add to content from MessageStream.
Implements SAMRAI::mesh::TransitLoad.
VoucherTransitLoad::LoadType SAMRAI::mesh::VoucherTransitLoad::adjustLoad (TransitLoad & hold_bin, LoadType ideal_load, LoadType low_load, LoadType high_load)
Adjust the load in this TransitSet by moving work between it and another TransitSet.
Parameters:
[in,out] hold_bin Holding bin for reserve load. hold_bin implementation is guaranteed to match this one.
[in] ideal_load The load that this bin should have.
[in] low_load Return when this bin's load is in the range [low_load,high_load]
[in] high_load Return when this bin's load is in the range [low_load,high_load]
Returns:
Net load added to this TransitSet. If negative, load decreased.
References SAMRAI::mesh::TransitLoad::empty(), SAMRAI::mesh::PartitioningParams::getLoadComparisonTol(), SAMRAI::mesh::PartitioningParams::getMinBoxSize(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::mesh::TransitLoad::getSumLoad(), getSumLoad(), SAMRAI::tbox::plog, and TBOX_ASSERT.
void SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps (hier::BoxLevel & balanced_box_level, hier::MappingConnector & balanced_to_unbalanced, hier::MappingConnector & unbalanced_to_balanced, double flexible_load_tol = 0.0) [virtual]
Assign contents to local process and populate the balanced<==>unbalanced maps. This method uses communication to set up the map.
Parameters:
[in,out] balanced_box_level Empty BoxLevel to populate with the contents of this TransitLoad.
[in,out] balanced_to_unbalanced Empty Connector to populate with the balanced--->unbalanced edges.
[in,out] unbalanced_to_balanced Empty Connector to populate with the unbalanced--->balanced edges.
[in] flexible_load_tol
This method uses communication to redeem vouchers and up the map.
Implements SAMRAI::mesh::TransitLoad.
References SAMRAI::mesh::BoxTransitSet::clear(), SAMRAI::mesh::BoxTransitSet::format(), SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges(), SAMRAI::tbox::SAMRAI_MPI::Get_count(), SAMRAI::mesh::TransitLoad::getAllowBoxBreaking(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::mesh::PartitioningParams::getLoadComparisonTol(), SAMRAI::hier::BoxLevel::getLocalNumberOfCells(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::mesh::TransitLoad::getThresholdWidth(), SAMRAI::mesh::BoxTransitSet::insertAll(), MPI_ANY_SOURCE, MPI_CHAR, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_SOURCE, SAMRAI::tbox::plog, SAMRAI::tbox::SAMRAI_MPI::Probe(), SAMRAI::mesh::BoxTransitSet::putInBoxLevel(), SAMRAI::mesh::BoxTransitSet::reassignOwnership(), SAMRAI::mesh::TransitLoad::setAllowBoxBreaking(), SAMRAI::mesh::TransitLoad::setThresholdWidth(), and TBOX_ASSERT.
void SAMRAI::mesh::VoucherTransitLoad::setTimerPrefix (const std::string & timer_prefix) [virtual]
Setup names of timers.
By default, timers are named "mesh::VoucherTransitLoad::*", where the third field is the specific steps performed by the Schedule. You can override the first two fields with this method. Conforming to the timer naming convention, timer_prefix should have the form "*::*".
Reimplemented from SAMRAI::mesh::TransitLoad.
References SAMRAI::mesh::BoxTransitSet::setTimerPrefix().
Referenced by VoucherTransitLoad().
void SAMRAI::mesh::VoucherTransitLoad::recursivePrint (std::ostream & co = tbox::plog, const std::string & border = std::string(), int detail_depth = 1) const [virtual]
Object printing method to aid in debugging.
Reimplemented from SAMRAI::mesh::TransitLoad.
References getSumLoad().
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/VoucherTransitLoad.h
source/SAMRAI/mesh/VoucherTransitLoad.C