SAMRAI: SAMRAI::geom::CartesianPatchGeometry Class Reference
SAMRAI::geom::CartesianPatchGeometry Class Reference
#include <source/SAMRAI/geom/CartesianPatchGeometry.h>
Public Types
typedef
hier::PatchGeometry::TwoDimBool TwoDimBool
Public Member Functions
CartesianPatchGeometry (const hier::IntVector &ratio_to_level_zero, const TwoDimBool &touches_regular_bdry, const double *dx, const double *x_lo, const double *x_hi)
virtual ~CartesianPatchGeometry ()
const double * getDx () const
const double * getXLower () const
const double * getXUpper () const
virtual void printClassData (std::ostream &os) const
Detailed Description
Class CartesianPatchGeometry implements simple Cartesian mes geometry management for a single patch in an AMR hierarchy. The geometry is limited to the mesh increments being specified by the DIM-tuple (dx[0],...,dx[DIM-1]) associated with the patch, and the spatial coordinates of the lower and upper corners of the patch within the computational domain. The grid data is set by CartesianGridGeometry class. This patch geometry class is derived from hier::PatchGeometry base class.
See also:
hier::BoundaryBox
hier::PatchGeometry
geom::CartesianGridGeometry
Member Typedef Documentation
typedef hier::PatchGeometry::TwoDimBool SAMRAI::geom::CartesianPatchGeometry::TwoDimBool
Constructor & Destructor Documentation
SAMRAI::geom::CartesianPatchGeometry::CartesianPatchGeometry (const hier::IntVector & ratio_to_level_zero, const TwoDimBool & touches_regular_bdry, const double * dx, const double * x_lo, const double * x_hi)
Constructor for CartesianPatchGeometry class. It simply passes patch boundary information to hier::PatchGeometry base class constructor and allocates storage for spatial coordinates on patch.
Precondition:
dx != 0
x_lo != 0
x_up != 0
References SAMRAI::hier::IntVector::getDim(), and TBOX_ASSERT.
SAMRAI::geom::CartesianPatchGeometry::~CartesianPatchGeometry () [virtual]
Destructor for CartesianPatchGeometry deallocates the storage for spatial coordinates on patch.
Member Function Documentation
const double* SAMRAI::geom::CartesianPatchGeometry::getDx () const [inline]
Return const pointer to dx array for patch.
const double* SAMRAI::geom::CartesianPatchGeometry::getXLower () const [inline]
Return const pointer to lower spatial coordinate for patch.
const double* SAMRAI::geom::CartesianPatchGeometry::getXUpper () const [inline]
Return const pointer to upper spatial coordinate for patch.
void SAMRAI::geom::CartesianPatchGeometry::printClassData (std::ostream & os) const [virtual]
Print CartesianPatchGeometry class data.
Reimplemented from SAMRAI::hier::PatchGeometry.
References SAMRAI::hier::PatchGeometry::getDim(), SAMRAI::hier::PatchGeometry::getRatio(), and SAMRAI::tbox::Dimension::getValue().
The documentation for this class was generated from the following files:
source/SAMRAI/geom/CartesianPatchGeometry.h
source/SAMRAI/geom/CartesianPatchGeometry.C