SAMRAI: SAMRAI::math::PatchSideDataOpsInteger Class Reference
SAMRAI::math::PatchSideDataOpsInteger Class Reference
#include <source/SAMRAI/math/PatchSideDataOpsInteger.h>
Public Member Functions
PatchSideDataOpsInteger ()
virtual ~PatchSideDataOpsInteger ()
int numberOfEntries (const boost::shared_ptr< pdat::SideData< int > > &data, const hier::Box &box) const
void copyData (const boost::shared_ptr< pdat::SideData< int > > &dst, const boost::shared_ptr< pdat::SideData< int > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::SideData< int > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::SideData< int > > &dst, const int &alpha, const hier::Box &box) const
void abs (const boost::shared_ptr< pdat::SideData< int > > &dst, const boost::shared_ptr< pdat::SideData< int > > &src, const hier::Box &box) const
Detailed Description
Class PatchSideDataOpsInteger provides a collection of operations that may be used to manipulate integer side-centered patch data. The operations include basic arithmetic, min, max, etc. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base class PatchSideDataBasicOps from which it is derived.
A more extensive set of operations is implemented for real (double and float) and complex patch data in the classes PatchSideDataOpsReal and PatchSideDataOpsComplex, repsectively.
See also:
math::PatchSideDataBasicOps
Constructor & Destructor Documentation
SAMRAI::math::PatchSideDataOpsInteger::PatchSideDataOpsInteger ()
Empty constructor and destructor.
SAMRAI::math::PatchSideDataOpsInteger::~PatchSideDataOpsInteger () [virtual]
Member Function Documentation
int SAMRAI::math::PatchSideDataOpsInteger::numberOfEntries (const boost::shared_ptr< pdat::SideData< int > > & data, const hier::Box & box) const
Return the number of data values for the side-centered data object in the given box. Note that it is assumed that the box refers to the cell-centered index space corresponding to the patch hierarchy.
Precondition:
data
data->getDim() == box.getDim()
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::size(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::numberOfEntries().
void SAMRAI::math::PatchSideDataOpsInteger::copyData (const boost::shared_ptr< pdat::SideData< int > > & dst, const boost::shared_ptr< pdat::SideData< int > > & src, const hier::Box & box) const
Copy dst data to src data over given box.
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::copyData().
void SAMRAI::math::PatchSideDataOpsInteger::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::SideData<int> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::SideData<int> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getDirectionVector() == patch->getPatchData(data2_id)->getDirectionVector()
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::swapData().
void SAMRAI::math::PatchSideDataOpsInteger::printData (const boost::shared_ptr< pdat::SideData< int > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::printData().
void SAMRAI::math::PatchSideDataOpsInteger::setToScalar (const boost::shared_ptr< pdat::SideData< int > > & dst, const int & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::setToScalar().
void SAMRAI::math::PatchSideDataOpsInteger::abs (const boost::shared_ptr< pdat::SideData< int > > & dst, const boost::shared_ptr< pdat::SideData< int > > & src, const hier::Box & box) const
Set destination component to absolute value of source component. That is, each destination entry is set to .
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsInteger::abs().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchSideDataOpsInteger.h
source/SAMRAI/math/PatchSideDataOpsInteger.C