SAMRAI: SAMRAI::pdat::EdgeOverlap Class Reference
SAMRAI::pdat::EdgeOverlap Class Reference
#include <source/SAMRAI/pdat/EdgeOverlap.h>
Public Member Functions
EdgeOverlap (const std::vector< hier::BoxContainer > &boxes, const hier::Transformation &transformation)
virtual ~EdgeOverlap ()
virtual bool isOverlapEmpty () const
virtual const hier::BoxContainer & getDestinationBoxContainer (const int axis) const
virtual void getSourceBoxContainer (hier::BoxContainer &src_boxes, int &axis_direction) const
Get a BoxContainer representing the source boxes of the overlap.
virtual const hier::IntVector & getSourceOffset () const
virtual const
hier::Transformation & getTransformation () const
Refturn the transformation between the destination and source index spaces.
Detailed Description
Class EdgeOverlap represents the intersection between two edge centered geometry boxes. It is a subclass of hier::BoxOverlap and records the portions of index space that needs to be copied between two objects with edge centered geometry.
See also:
hier::BoxOverlap
pdat::EdgeOverlap
Constructor & Destructor Documentation
SAMRAI::pdat::EdgeOverlap::EdgeOverlap (const std::vector< hier::BoxContainer > & boxes, const hier::Transformation & transformation)
The constructor takes the list of boxes and the transformation from source to destination index spaces. This information is used later in the generation of communication schedules.
References SAMRAI::hier::Transformation::getOffset().
SAMRAI::pdat::EdgeOverlap::~EdgeOverlap () [virtual]
The virtual destructor does nothing interesting except deallocate box data.
Member Function Documentation
bool SAMRAI::pdat::EdgeOverlap::isOverlapEmpty () const [virtual]
Return whether there is an empty intersection between the two edge centered boxes. This method over-rides the virtual function in the hier::BoxOverlap base class.
Implements SAMRAI::hier::BoxOverlap.
const hier::BoxContainer & SAMRAI::pdat::EdgeOverlap::getDestinationBoxContainer (const int axis) const [virtual]
Return the list of boxes (in edge centered index space) that constitute the intersection. The boxes are given in the destination coordinate space and must be shifted by -(getSourceOffset()) to lie in the source index space. The axis argument represents which axis is desired: X=0, Y=1, and Z=2.
Precondition:
(axis >= 0) && (axis < d_dst_boxes.size())
References TBOX_ASSERT.
Referenced by SAMRAI::pdat::OuteredgeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::EdgeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::pdat::EdgeData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::sum(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream(), SAMRAI::pdat::EdgeData< TYPE >::unpackStream(), and SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum().
void SAMRAI::pdat::EdgeOverlap::getSourceBoxContainer (hier::BoxContainer & src_boxes, int & axis_direction) const [virtual]
Get a BoxContainer representing the source boxes of the overlap.
The src_boxes container will be filled with edge-centered source boxes of the overlap in the source coordinate space. The given axis direction is the axis in destination space on input and in source space on output.
Parameters:
[out] src_boxes
[in,out] axis_direction
Precondition:
src_boxes.isEmpty()
axis_direction >= 0 && axis_direction < d_dst_boxes.size()
Postcondition:
axis_direction >= 0 && axis_direction < d_dst_boxes.size()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getInverseTransformation(), SAMRAI::hier::BoxContainer::isEmpty(), TBOX_ASSERT, and SAMRAI::pdat::EdgeGeometry::transform().
const hier::IntVector & SAMRAI::pdat::EdgeOverlap::getSourceOffset () const [virtual]
Return the offset between the destination and source index spaces. The destination index space is the source index space shifted by this amount.
Implements SAMRAI::hier::BoxOverlap.
References SAMRAI::hier::Transformation::getOffset().
Referenced by SAMRAI::pdat::OuteredgeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::EdgeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::sum(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream(), SAMRAI::pdat::EdgeData< TYPE >::unpackStream(), and SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum().
const hier::Transformation & SAMRAI::pdat::EdgeOverlap::getTransformation () const [virtual]
Refturn the transformation between the destination and source index spaces.
The destination index space is the source index space rotated and shifted by the returned transformation.
Returns:
The transformation.
Implements SAMRAI::hier::BoxOverlap.
Referenced by SAMRAI::pdat::EdgeData< TYPE >::packStream().
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/EdgeOverlap.h
source/SAMRAI/pdat/EdgeOverlap.C