SAMRAI: SAMRAI::algs::MethodOfLinesIntegrator Class Reference
SAMRAI::algs::MethodOfLinesIntegrator Class Reference
Class MethodOfLinesIntegrator implements a spatially adaptive version of the Strong Stability Preserving (SSP) Runge-Kutta time integration algorithm.
#include <source/SAMRAI/algs/MethodOfLinesIntegrator.h>
Public Types
enum MOL_VAR_TYPE { SOLN = 0, RHS = 1 }
Public Member Functions
MethodOfLinesIntegrator (const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db, MethodOfLinesPatchStrategy *patch_strategy)
virtual ~MethodOfLinesIntegrator ()
void initializeIntegrator (const boost::shared_ptr< mesh::GriddingAlgorithm > &gridding_alg)
double getTimestep (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const double time) const
void advanceHierarchy (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const double time, const double dt)
void registerVariable (const boost::shared_ptr< hier::Variable > &variable, const hier::IntVector &ghosts, const MOL_VAR_TYPE m_v_type, const boost::shared_ptr< hier::BaseGridGeometry > &transfer_geom, const std::string &coarsen_name=std::string(), const std::string &refine_name=std::string())
virtual void printClassData (std::ostream &os) const
void initializeLevelData (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int level_number, const double init_time, const bool can_be_refined, const bool initial_time, const boost::shared_ptr< hier::PatchLevel > &old_level=boost::shared_ptr< hier::PatchLevel >(), const bool allocate_data=true)
void resetHierarchyConfiguration (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int coarsest_level, const int finest_level)
virtual void applyGradientDetector (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int level_number, const double time, const int tag_index, const bool initial_time, const bool uses_richardson_extrapolation_too)
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
const std::string & getObjectName () const
Detailed Description
Class MethodOfLinesIntegrator implements a spatially adaptive version of the Strong Stability Preserving (SSP) Runge-Kutta time integration algorithm.
The original non-adaptive version of the algorithm is described in S. Gottlieb, C.W. Shu, E. Tadmor, SIAM Review, Vol. 43, No. 1, pp. 89-112. The advanceHierarchy() method integrates all levels of an AMR hierarchy through a specified timestep. See this method for details of the time-stepping process. Application-specific numerical routines that are necessary for these operations are provided by the MethodOfLinesPatchStrategy data member. The collaboration between this class and the patch strategy follows the the Strategy design pattern. A concrete patch strategy object is derived from the base class to provide those routines for a specific problem.
This class is derived from the mesh::StandardTagAndInitStrategy abstract base class which defines an interface for routines required by the dynamic adaptive mesh refinement routines in the mesh::GriddingAlgorithm class. This collaboration also follows the Strategy design pattern.
Initialization of an MethodOfLinesIntegrator object is performed by first setting default values, then reading from input. All input values may override values read from restart. Data read from input is summarized as follows:
Input Parameters
Definitions:
alpha_1
alpha_2
beta
arrays of double values (length = order) specifying the coeffients used in the multi-step Strong Stability Preserving (SSP) Runge-Kutta algorithm.
Note that when continuing from restart, the input parameters in the input database override all values read in from the restart database.
Details:
parameter
type
default
range
opt/req
behavior on restart
alpha_1
array of doubles
[1.0, 0.75, 2.0/3.0]
any doubles but no more than 3 of them
opt
Parameter read from restart db may be overridden by input db
alpha_2
array of doubles
[0.0, 0.25, 2.0/3.0]
any doubles but no more than 3 of them
opt
Parameter read from restart db may be overridden by input db
beta
array of doubles
[1.0, 0.25, 2.0/3.0]
any doubles but no more than 3 of them
opt
Parameter read from restart db may be overridden by input db
The following represents a sample input entry:
  MethodOfLinesIntegrator{
     alpha_1               = 1., 0.75, 0.33333
     alpha_2               = 0., 0.25, 0.66666
     beta                  = 1., 0.25, 0.66666
  }
See also:
mesh::StandardTagAndInitStrategy
Member Enumeration Documentation
enum SAMRAI::algs::MethodOfLinesIntegrator::MOL_VAR_TYPE
Enumerated type for the different categories of variable quantities allowed by the method of lines integration algorithm. See registerVariable(...) function for more details.
SOLN {Solution quantity for time-dependent ODE problem solved by RK time-stepping algorithm.}
RHS {Right-hand-side of ODE problem solved; i.e., du/dt = RHS.}
Enumerator:
SOLN
RHS
Constructor & Destructor Documentation
SAMRAI::algs::MethodOfLinesIntegrator::MethodOfLinesIntegrator (const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db, MethodOfLinesPatchStrategy * patch_strategy)
The constructor for MethodOfLinesIntegrator configures the method of lines integration algorithm with the concrete patch strategy object (containing problem-specific numerical routines) and initializes integration algorithm parameters provided in the specified input database and in the restart database corresponding to the specified object_name.
Precondition:
!object_name.empty()
patch_strategy != 0
References SAMRAI::tbox::RestartManager::getManager(), SAMRAI::algs::MethodOfLinesPatchStrategy::setInteriorContext(), SAMRAI::algs::MethodOfLinesPatchStrategy::setInteriorWithGhostsContext(), and TBOX_ASSERT.
SAMRAI::algs::MethodOfLinesIntegrator::~MethodOfLinesIntegrator () [virtual]
The destructor for MethodOfLinesIntegrator unregisters the integrator object with the restart manager.
References SAMRAI::tbox::RestartManager::getManager().
Member Function Documentation
void SAMRAI::algs::MethodOfLinesIntegrator::initializeIntegrator (const boost::shared_ptr< mesh::GriddingAlgorithm > & gridding_alg)
Initialize integrator by setting the number of time levels of data needed based on specifications of the gridding algorithm.
This routine also invokes variable registration in the patch strategy.
Precondition:
gridding_alg
References NULL_USE, SAMRAI::algs::MethodOfLinesPatchStrategy::registerModelVariables(), and TBOX_ASSERT.
double SAMRAI::algs::MethodOfLinesIntegrator::getTimestep (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const double time) const
Return a suitable time increment over which to integrate the ODE problem. A minimum is taken over the increment computed on each patch in the hierarchy.
Precondition:
hierarchy
References SAMRAI::algs::MethodOfLinesPatchStrategy::computeStableDtOnPatch(), MPI_MIN, and TBOX_ASSERT.
void SAMRAI::algs::MethodOfLinesIntegrator::advanceHierarchy (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const double time, const double dt)
Advance the solution through the specified dt, which is assumed for the problem and state of the solution. Advances all patches in the hierarchy passed in.
Precondition:
hierarchy
References SAMRAI::algs::MethodOfLinesPatchStrategy::singleStep(), and TBOX_ASSERT.
void SAMRAI::algs::MethodOfLinesIntegrator::registerVariable (const boost::shared_ptr< hier::Variable > & variable, const hier::IntVector & ghosts, const MOL_VAR_TYPE m_v_type, const boost::shared_ptr< hier::BaseGridGeometry > & transfer_geom, const std::string & coarsen_name = std::string(), const std::string & refine_name = std::string())
Register variable quantity defined in the patch strategy with the method of lines integrator which manipulates its storage.
Precondition:
variable
transfer_geom
variable->getDim() == ghosts.getDim()
References SAMRAI::hier::VariableDatabase::getDatabase(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::PatchDataRestartManager::getManager(), SAMRAI::hier::VariableDatabase::registerVariableAndContext(), RHS, SAMRAI::hier::ComponentSelector::setFlag(), SOLN, TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
void SAMRAI::algs::MethodOfLinesIntegrator::printClassData (std::ostream & os) const [virtual]
Print all data members of MethodOfLinesIntegrator object.
void SAMRAI::algs::MethodOfLinesIntegrator::initializeLevelData (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int level_number, const double init_time, const bool can_be_refined, const bool initial_time, const boost::shared_ptr< hier::PatchLevel > & old_level = boost::shared_ptr<hier::PatchLevel>(), const bool allocate_data = true) [virtual]
Initialize data on a new level after it is inserted into an AMR patch hierarchy by the gridding algorithm. The level number indicates that of the new level. The old_level pointer corresponds to the level that resided in the hierarchy before the level with the specified number was introduced. If the pointer is NULL, there was no level in the hierarchy prior to the call and the level data is set based on the user routines and the simulation time. Otherwise, the specified level replaces the old level and the new level receives data from the old level appropriately before it is destroyed.
Typically, when data is set, it is interpolated from coarser levels in the hierarchy. If the data is to be set, the level number must match that of the old level, if non-NULL. If the old level is non-NULL, then data is copied from the old level to the new level on regions of intersection between those levels before interpolation occurs. Then, user-supplied patch routines are called to further initialize the data if needed. The boolean argument after_regrid is passed into the user's routines.
The boolean argument initial_time indicates whether the integration time corresponds to the initial simulation time. If true, the level should be initialized with initial simulation values. Otherwise, it should be assumed that the simulation time is at some point after the start of the simulation. This information is provided since the initialization of the data on a patch may be different in each of those circumstances. The can_be_refined boolean argument indicates whether the level is the finest allowable level in the hierarchy.
Precondition:
hierarchy
level_number >= 0
hierarchy->getPatchLevel(level_number)
!old_level || (level_number == old_level->getLevelNumber())
!old_level || (hierarchy->getDim() == old_level->getDim())
Implements SAMRAI::mesh::StandardTagAndInitStrategy.
References SAMRAI::algs::MethodOfLinesPatchStrategy::initializeDataOnPatch(), NULL_USE, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::algs::MethodOfLinesIntegrator::resetHierarchyConfiguration (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int coarsest_level, const int finest_level) [virtual]
Reset cached communication schedules after the hierarchy has changed (due to regridding, for example) and the data has been initialized on the new levels. The intent is that the cost of data movement on the hierarchy will be amortized across multiple communication cycles, if possible. Note, that whenever this routine is called, communication schedules are updated for every level finer than and including that indexed by coarsest_level.
Precondition:
hierarchy
(coarsest_level >= 0) && (coarsest_level <= finest_level) && (finest_level <= hierarchy->getFinestLevelNumber())
Implements SAMRAI::mesh::StandardTagAndInitStrategy.
References NULL_USE, and TBOX_ASSERT.
void SAMRAI::algs::MethodOfLinesIntegrator::applyGradientDetector (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int level_number, const double time, const int tag_index, const bool initial_time, const bool uses_richardson_extrapolation_too) [virtual]
Set integer tags to "one" on the given level where refinement of that level should occur using the user-supplied gradient detector. The boolean argument initial_time is true when the level is being subject to error estimation at initialization time. If it is false, the error estimation process is being invoked at some later time after the AMR hierarchy was initially constructed. The boolean argument uses_richardson_extrapolation_too is true when Richardson extrapolation error estimation is used in addition to the gradient detector, and false otherwise. This argument helps the user to manage multiple regridding criteria. This information is passed along to the user's patch data tagging routines since the application of the error estimator may be different in each of those circumstances.
Precondition:
hierarchy
hierarchy->getPatchLevel(level_number)
Reimplemented from SAMRAI::mesh::StandardTagAndInitStrategy.
References SAMRAI::algs::MethodOfLinesPatchStrategy::tagGradientDetectorCells(), and TBOX_ASSERT.
void SAMRAI::algs::MethodOfLinesIntegrator::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Writes object state out to the given restart database.
Precondition:
restart_db
References TBOX_ASSERT.
const std::string& SAMRAI::algs::MethodOfLinesIntegrator::getObjectName () const [inline]
Returns the object name.
The documentation for this class was generated from the following files:
source/SAMRAI/algs/MethodOfLinesIntegrator.h
source/SAMRAI/algs/MethodOfLinesIntegrator.C