SAMRAI: SAMRAI::pdat::ArrayDataIterator Class Reference
SAMRAI::pdat::ArrayDataIterator Class Reference
#include <source/SAMRAI/pdat/ArrayDataIterator.h>
Public Member Functions
ArrayDataIterator (const hier::Box &box, bool begin)
ArrayDataIterator (const ArrayDataIterator &iterator)
ArrayDataIterator & operator= (const ArrayDataIterator &iterator)
~ArrayDataIterator ()
const hier::Index & operator* () const
const hier::Index * operator-> () const
ArrayDataIterator & operator++ ()
ArrayDataIterator operator++ (int)
bool operator== (const ArrayDataIterator &iterator) const
bool operator!= (const ArrayDataIterator &iterator) const
Detailed Description
Class ArrayDataIterator is an iterator that provides methods for stepping through the index space associated with a pdat_ArrayData object. The indices are enumerated in column-major (e.g., Fortran) order. The iterator should be used as follows:
 * hier::Box box;
 * ...
 * ArrayDataIterator cend(box, false);
 * for (ArrayDataIterator c(box, true); c != cend; c++) {
 *    // use index c of the box
 * }
 *
Note that the array data iterator may not compile to efficient code, depending on your compiler. Many compilers are not smart enough to optimize the looping constructs and indexing operations.
See also:
ArrayData
hier::Index
Constructor & Destructor Documentation
SAMRAI::pdat::ArrayDataIterator::ArrayDataIterator (const hier::Box & box, bool begin)
Constructor for the array data iterator. The iterator will enumerate the indices in the argument box.
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), and SAMRAI::hier::Box::upper().
SAMRAI::pdat::ArrayDataIterator::ArrayDataIterator (const ArrayDataIterator & iterator)
Copy constructor for the array data iterator
SAMRAI::pdat::ArrayDataIterator::~ArrayDataIterator ()
Destructor for the array data iterator.
Member Function Documentation
ArrayDataIterator& SAMRAI::pdat::ArrayDataIterator::operator= (const ArrayDataIterator & iterator) [inline]
Assignment operator for the array data iterator.
const hier::Index& SAMRAI::pdat::ArrayDataIterator::operator* () const [inline]
Extract the index corresponding to the iterator position in the box.
const hier::Index* SAMRAI::pdat::ArrayDataIterator::operator-> () const [inline]
Extract pointer to the index corresponding to the iterator position in the box.
ArrayDataIterator & SAMRAI::pdat::ArrayDataIterator::operator++ ()
Pre-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
ArrayDataIterator SAMRAI::pdat::ArrayDataIterator::operator++ (int)
Post-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
bool SAMRAI::pdat::ArrayDataIterator::operator== (const ArrayDataIterator & iterator) const [inline]
Test two iterators for equality (same index value).
bool SAMRAI::pdat::ArrayDataIterator::operator!= (const ArrayDataIterator & iterator) const [inline]
Test two iterators for inequality (different index values).
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/ArrayDataIterator.h
source/SAMRAI/pdat/ArrayDataIterator.C