SAMRAI: SAMRAI::hier::GlobalId Class Reference
SAMRAI::hier::GlobalId Class Reference
A locally determined, globally unique identifier.
#include <source/SAMRAI/hier/GlobalId.h>
Public Member Functions
GlobalId ()
Default constructor is non-initializing.
GlobalId (const LocalId &local_id, const int owner_rank)
Initializing constructor.
GlobalId (const GlobalId &other)
Copy constructor.
~GlobalId ()
Destructor.
int & getOwnerRank ()
Access the owner rank.
const int & getOwnerRank () const
Access the owner rank.
LocalId & getLocalId ()
Access the LocalId.
const LocalId & getLocalId () const
Access the LocalId.
Comparison operators
bool operator== (const GlobalId &r) const
Equality operator.
bool operator!= (const GlobalId &r) const
Inequality operator.
bool operator< (const GlobalId &r) const
Less-than operator.
bool operator> (const GlobalId &r) const
Greater-than operator.
bool operator<= (const GlobalId &r) const
Less-than-or-equal-to operator.
bool operator>= (const GlobalId &r) const
Greater-thanor-equal-to operator.
Friends
std::ostream & operator<< (std::ostream &co, const GlobalId &r)
Format and insert rank and LocalId into a stream.
Detailed Description
A locally determined, globally unique identifier.
GlobalIds are used as object identifiers in distributed sets of objects, such as Patches and Boxes. GlobalIds allow objects to be created in parallel while maintaining globally-unique identifiers for those objects.
GlobalId includes an owner rank and a LocalId. A GlobalId is typically generated only by the owner, so global uniqueness is guaranteed by uniqueness of the LocalId portion.
Comparison operators are provided to define sorted ordering of objects. The owners and LocalIds are used for all comparisons. The owner ranks are compared first, followed by the LocalIds.
Constructor & Destructor Documentation
SAMRAI::hier::GlobalId::GlobalId ()
Default constructor is non-initializing.
Sets rank to an invalid value provided by SAMRAI_MPI.
The object can be initialized using the assignment operator or the non-const versions of the getOwnerRank() and getLocalId() methods.
SAMRAI::hier::GlobalId::GlobalId (const LocalId & local_id, const int owner_rank)
Initializing constructor.
SAMRAI::hier::GlobalId::GlobalId (const GlobalId & other)
Copy constructor.
Parameters:
[in] other
SAMRAI::hier::GlobalId::~GlobalId ()
Destructor.
Member Function Documentation
int& SAMRAI::hier::GlobalId::getOwnerRank () [inline]
Access the owner rank.
Referenced by SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::hier::BoxId::initialize(), SAMRAI::hier::BoxId::isValid(), SAMRAI::hier::BoxId::operator<(), SAMRAI::hier::operator<<(), and SAMRAI::hier::BoxId::operator>().
const int& SAMRAI::hier::GlobalId::getOwnerRank () const [inline]
Access the owner rank.
LocalId& SAMRAI::hier::GlobalId::getLocalId () [inline]
Access the LocalId.
Referenced by SAMRAI::hier::BoxId::getLocalId(), SAMRAI::hier::BoxId::initialize(), SAMRAI::hier::BoxId::isValid(), SAMRAI::hier::BoxId::operator<(), SAMRAI::hier::operator<<(), and SAMRAI::hier::BoxId::operator>().
const LocalId& SAMRAI::hier::GlobalId::getLocalId () const [inline]
Access the LocalId.
bool SAMRAI::hier::GlobalId::operator== (const GlobalId & r) const [inline]
Equality operator.
All comparison operators use the owner and rank. Compare the owner values first; if they compare equal, compare the LocalId next.
bool SAMRAI::hier::GlobalId::operator!= (const GlobalId & r) const [inline]
Inequality operator.
See note on comparison for operator==(const GlobalId&);
bool SAMRAI::hier::GlobalId::operator< (const GlobalId & r) const [inline]
Less-than operator.
See note on comparison for operator==(const GlobalId&);
bool SAMRAI::hier::GlobalId::operator> (const GlobalId & r) const [inline]
Greater-than operator.
See note on comparison for operator==(const GlobalId&);
bool SAMRAI::hier::GlobalId::operator<= (const GlobalId & r) const [inline]
Less-than-or-equal-to operator.
See note on comparison for operator==(const GlobalId&);
bool SAMRAI::hier::GlobalId::operator>= (const GlobalId & r) const [inline]
Greater-thanor-equal-to operator.
See note on comparison for operator==(const GlobalId&);
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & co, const GlobalId & r) [friend]
Format and insert rank and LocalId into a stream.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/GlobalId.h
source/SAMRAI/hier/GlobalId.C