SAMRAI: SAMRAI::solv::KINSOL_SAMRAIContext Class Reference
SAMRAI::solv::KINSOL_SAMRAIContext Class Reference
Wraps the KINSOLSolver C++ wrapper class so that KINSOL may be used in applications that require a nonlinear solver.
#include <source/SAMRAI/solv/KINSOL_SAMRAIContext.h>
Public Member Functions
KINSOL_SAMRAIContext (const std::string &object_name, KINSOLAbstractFunctions *my_functions, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
~KINSOL_SAMRAIContext ()
void initialize (const boost::shared_ptr< SAMRAIVectorReal< double > > &solution)
int solve ()
KINSOLSolver * getKINSOLSolver ()
void getFromInput (const boost::shared_ptr< tbox::Database > &input_db, bool is_from_restart)
void getFromRestart ()
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
virtual void printClassData (std::ostream &os) const
const std::string & getObjectName () const
Detailed Description
Wraps the KINSOLSolver C++ wrapper class so that KINSOL may be used in applications that require a nonlinear solver.
Class KINSOL_SAMRAIContext wraps the KINSOLSolver C++ wrapper class so that KINSOL may be used in applications that require a nonlinear solver. The class KINSOLSolver does not depend on SAMRAI. Making it derived from the SAMRAI nonlinear solver interface would require the KINSOL C++ wrapper to depend on SAMRAI.
Important note: This class can only create a KINSOL C++ wrapper instance, initialize it in a rudimentary way, and invoke the solution process. All other interaction with the nonlinear solver (i.e., setting parameters, retrieving solver statistics, etc.) must be done directly with the KINSOL wrapper accessible via the routine getKINSOLSolver(). Alternatively, solver parameters may be set up at initialization time using the SAMRAI input database.
Input Parameters
If no parameters are read from input, KINSOL defaults are used. See KINSOL documentation for default information.
Definitions:
residual_stop_tolerance stopping tolerance on norm of scaled residual
max_nonlinear_iterations maximum number of nonlinear iterations
max_krylov_dimension maximum dimension of Krylov space
global_newton_strategy globalization strategy
max_newton_step maximum allowable Newton step
nonlinear_step_tolerance stopping tolerance on maximum entry in scaled Newton step
relative_function_error relative error in function evaluation
linear_convergence_test linear solver convergence tolerance
max_subsetup_calls number of nonlinear iterations between checks by the nonlinear residual monitoring algorithm (specifies lenght of subinterval) NOTE: should be a multiple of max_solves_no_precond_setup
residual_monitoring_params values of omega_min and omega_max scalars used by nonlinear residual monitoring algorithm
residual_monitoring_constant constant value used by residual monitoring algorithm. If omega=0, then it is estimated using omega_min and omega_max.
no_min_eps control whether or not the value * of eps is bounded below by 0.01*fnormtol. FALSE = "constrain value of eps by setting to the following: eps = MAX{0.01*fnormtol, eps}" TRUE = "do notconstrain value of eps".
eisenstat_walker_params Eisenstat-Walker choice 2; i.e., the values are given as ETAALPHA, followed by ETAGAMMA. Note: the values only apply when linear convergence test is set to ETACHOICE2.
linear_solver_constant_tolerance constant linear solver relative tolerance Note: value only applies when convergence test is set to ETACONSTANT.
max_solves_no_precond_setup number of nonlinear steps separating successive calls to preconditioner setup routine
max_linear_solve_restarts maximum number of linear solver restarts allowed
KINSOL_log_filename name of KINSOL log file
KINSOL_print_flag KINSOL log file print options
uses_preconditioner indicates whether a preconditioner is supplied
uses_jac_times_vector indicates whether an analytic Jacobian-vector product is supplied
All values read in from a restart database may be overriden by input database values. If no new input database value is given, the restart database value is used.
Details:
parameter
type
default
range
opt/req
behavior on restart
residual_stop_tolerance
double
-1.0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
max_nonlinear_iterations
int
200
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
max_krylov_dimension
int
10
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
global_newton_strategy
int
0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
max_newton_step
double
-1.0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
nonlinear_step_tolerance
double
-1.0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
relative_function_error
double
-1.0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
linear_convergence_test
int
3
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
max_subsetup_calls
int
5
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
residual_monitoring_params
double[2]
[0.00001, 0.9]
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
residual_monitoring_constant
double
0.0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
no_min_eps
bool
FALSE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
eisenstat_walker_params
double[2]
[2.0, 0.9]
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
linear_solver_constant_tolerance
double
0.1
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
max_solves_no_precond_setup
int
10
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
max_linear_solve_restarts
int
0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
KINSOL_log_filename
string
""
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
KINSOL_print_flag
int
0
Refer to KINSOL documentation
opt
Parameter read from restart db may be overridden by input db
uses_preconditioner
bool
FALSE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
uses_jac_times_vector
bool
FALSE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
A sample input file entry might look like:
   residual_stop_tolerance  =  10.e-6
   max_nonlinear_iterations =  200
   max_newton_step          =  0.1
   KINSOL_log_filename      =  "mylogfile"
   KINSOL_print_flag        =  3   // print all output KINSOL has to offer
See also:
solv::NonlinearSolverStrategy
Constructor & Destructor Documentation
SAMRAI::solv::KINSOL_SAMRAIContext::KINSOL_SAMRAIContext (const std::string & object_name, KINSOLAbstractFunctions * my_functions, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>())
Constructor for algs::KINSOL_SAMRAIContext allocates the KINSOL C++ wrapper object and initializes rudimentary state associated with user-supplied solver components. Then, it reads solver parameter from input and restart which may override default values.
Precondition:
!object_name.empty()
my_functions != 0
References getFromInput(), getFromRestart(), SAMRAI::tbox::RestartManager::getManager(), and TBOX_ASSERT.
SAMRAI::solv::KINSOL_SAMRAIContext::~KINSOL_SAMRAIContext ()
Destructor for algs::KINSOL_SAMRAIContext destroys the KINSOL C++ wrapper object and the KINSOL solution vector wrapper.
References SAMRAI::solv::Sundials_SAMRAIVector::destroySundialsVector(), and SAMRAI::tbox::RestartManager::getManager().
Member Function Documentation
void SAMRAI::solv::KINSOL_SAMRAIContext::initialize (const boost::shared_ptr< SAMRAIVectorReal< double > > & solution) [virtual]
Initialize the state of KINSOL based on vector argument representing the solution of the nonlinear system. In general, this routine must be called before the solve() routine is invoked.
Precondition:
solution
Implements SAMRAI::solv::NonlinearSolverStrategy.
References SAMRAI::solv::Sundials_SAMRAIVector::createSundialsVector(), SAMRAI::solv::KINSOLSolver::initialize(), and TBOX_ASSERT.
int SAMRAI::solv::KINSOL_SAMRAIContext::solve () [virtual]
Solve the nonlinear problem and return and integer value defined by KINSOL. A return value of 1 indicates success (i.e., KINSOL_SUCCESS). Consult the KINSOL documentation, KINSOL header file kinsol.h, or the header file for the class KINSOLSolver for more information about KINSOL return codes. In general, the initialize() routine must be called before this solve function to set up the solver.
Implements SAMRAI::solv::NonlinearSolverStrategy.
References SAMRAI::solv::KINSOLSolver::solve().
KINSOLSolver* SAMRAI::solv::KINSOL_SAMRAIContext::getKINSOLSolver () [inline]
Return pointer to KINSOL solver C++ wrapper object.
void SAMRAI::solv::KINSOL_SAMRAIContext::getFromInput (const boost::shared_ptr< tbox::Database > & input_db, bool is_from_restart)
Read input parameters from given database.
Parameters:
[in] input_db
[in] is_from_restart
References SAMRAI::solv::KINSOLSolver::setEisenstatWalkerParameters(), SAMRAI::solv::KINSOLSolver::setGlobalStrategy(), SAMRAI::solv::KINSOLSolver::setJacobianTimesVector(), SAMRAI::solv::KINSOLSolver::setLinearSolverConstantTolerance(), SAMRAI::solv::KINSOLSolver::setLinearSolverConvergenceTest(), SAMRAI::solv::KINSOLSolver::setLogFileData(), SAMRAI::solv::KINSOLSolver::setMaxIterations(), SAMRAI::solv::KINSOLSolver::setMaxKrylovDimension(), SAMRAI::solv::KINSOLSolver::setMaxLinearSolveRestarts(), SAMRAI::solv::KINSOLSolver::setMaxNewtonStep(), SAMRAI::solv::KINSOLSolver::setMaxStepsWithNoPrecondSetup(), SAMRAI::solv::KINSOLSolver::setMaxSubSetupCalls(), SAMRAI::solv::KINSOLSolver::setNoMinEps(), SAMRAI::solv::KINSOLSolver::setNonlinearStepTolerance(), SAMRAI::solv::KINSOLSolver::setPreconditioner(), SAMRAI::solv::KINSOLSolver::setRelativeFunctionError(), SAMRAI::solv::KINSOLSolver::setResidualMonitoringConstant(), SAMRAI::solv::KINSOLSolver::setResidualMonitoringParams(), and SAMRAI::solv::KINSOLSolver::setResidualStoppingTolerance().
Referenced by KINSOL_SAMRAIContext().
void SAMRAI::solv::KINSOL_SAMRAIContext::getFromRestart ()
Retrieve solver parameters from restart database matching object name.
When assertion checking is active, an unrecoverable assertion will result if a restart database matching the object name does not exist, or if the class version number does not match that in restart.
References SAMRAI::tbox::RestartManager::getManager(), SAMRAI::solv::KINSOLSolver::setEisenstatWalkerParameters(), SAMRAI::solv::KINSOLSolver::setGlobalStrategy(), SAMRAI::solv::KINSOLSolver::setJacobianTimesVector(), SAMRAI::solv::KINSOLSolver::setLinearSolverConstantTolerance(), SAMRAI::solv::KINSOLSolver::setLinearSolverConvergenceTest(), SAMRAI::solv::KINSOLSolver::setLogFileData(), SAMRAI::solv::KINSOLSolver::setMaxIterations(), SAMRAI::solv::KINSOLSolver::setMaxKrylovDimension(), SAMRAI::solv::KINSOLSolver::setMaxLinearSolveRestarts(), SAMRAI::solv::KINSOLSolver::setMaxNewtonStep(), SAMRAI::solv::KINSOLSolver::setMaxStepsWithNoPrecondSetup(), SAMRAI::solv::KINSOLSolver::setMaxSubSetupCalls(), SAMRAI::solv::KINSOLSolver::setNoMinEps(), SAMRAI::solv::KINSOLSolver::setNonlinearStepTolerance(), SAMRAI::solv::KINSOLSolver::setPreconditioner(), SAMRAI::solv::KINSOLSolver::setRelativeFunctionError(), SAMRAI::solv::KINSOLSolver::setResidualMonitoringConstant(), SAMRAI::solv::KINSOLSolver::setResidualMonitoringParams(), SAMRAI::solv::KINSOLSolver::setResidualStoppingTolerance(), and TBOX_ERROR.
Referenced by KINSOL_SAMRAIContext().
void SAMRAI::solv::KINSOL_SAMRAIContext::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Retrieve solver parameters from restart database matching object name.
Precondition:
restart_db
References TBOX_ASSERT.
void SAMRAI::solv::KINSOL_SAMRAIContext::printClassData (std::ostream & os) const [virtual]
Print out all members of integrator instance to given output stream.
const std::string& SAMRAI::solv::KINSOL_SAMRAIContext::getObjectName () const [inline]
Returns the object name.
The documentation for this class was generated from the following files:
source/SAMRAI/solv/KINSOL_SAMRAIContext.h
source/SAMRAI/solv/KINSOL_SAMRAIContext.C