SAMRAI: SAMRAI::pdat::SideGeometry Class Reference
SAMRAI::pdat::SideGeometry Class Reference
#include <source/SAMRAI/pdat/SideGeometry.h>
Public Types
typedef SideOverlap Overlap
Public Member Functions
SideGeometry (const hier::Box &box, const hier::IntVector &ghosts, const hier::IntVector &directions)
Construct the side geometry object given an AMR index space box, ghost cell width and directions vector indicating which coordinate directions are allocated.
SideGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct the side geometry object given an AMR index space box and ghost cell width.
virtual ~SideGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in side-centered index space between the source box geometry and the destination box geometry.
void computeDestinationBoxes (std::vector< hier::BoxContainer > &dst_boxes, const SideGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the side-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a SideOverlap object based on the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this side centered box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this side centered box geometry object.
const hier::IntVector & getDirectionVector () const
Static Public Member Functions
static hier::Box toSideBox (const hier::Box &box, tbox::Dimension::dir_t side_normal)
Convert an AMR index box space box into an side geometry box. An side geometry box extends the given AMR index space box by one at upper end for the side normal coordinate direction.
static void transform (hier::Box &box, int &normal_direction, const hier::Transformation &transformation)
Transform a side-centered box.
static void transform (SideIndex &index, const hier::Transformation &transformation)
Transform a SideIndex.
static SideIterator begin (const hier::Box &box, tbox::Dimension::dir_t axis)
static SideIterator end (const hier::Box &box, tbox::Dimension::dir_t axis)
Detailed Description
Class SideGeometry manages the mapping between the AMR index space and the side-centered geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between side- centered box geometries for communication operations.
See header file for SideData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
pdat::SideOverlap
Member Typedef Documentation
typedef SideOverlap SAMRAI::pdat::SideGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::SideGeometry::SideGeometry (const hier::Box & box, const hier::IntVector & ghosts, const hier::IntVector & directions)
Construct the side geometry object given an AMR index space box, ghost cell width and directions vector indicating which coordinate directions are allocated.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
directions.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::SideGeometry::SideGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct the side geometry object given an AMR index space box and ghost cell width.
No directions vector is provided, so it is assumed that all coordinate directions are allocated.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::SideGeometry::~SideGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
hier::Box SAMRAI::pdat::SideGeometry::toSideBox (const hier::Box & box, tbox::Dimension::dir_t side_normal) [static]
Convert an AMR index box space box into an side geometry box. An side geometry box extends the given AMR index space box by one at upper end for the side normal coordinate direction.
Precondition:
(side_normal >= 0) && (side_normal < box.getDim().getValue())
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::math::PatchSideDataOpsInteger::abs(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchSideDataNormOpsComplex::abs(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::add(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::addScalar(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::axmy(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::axpy(), SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), computeDestinationBoxes(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::math::PatchSideDataOpsReal< TYPE >::copyData(), SAMRAI::math::PatchSideDataOpsInteger::copyData(), SAMRAI::math::PatchSideDataOpsComplex::copyData(), SAMRAI::pdat::SideData< TYPE >::copyOnBox(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::divide(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::dot(), SAMRAI::math::PatchSideDataNormOpsComplex::dot(), SAMRAI::pdat::SideData< TYPE >::fill(), SAMRAI::pdat::OutersideData< TYPE >::fill(), SAMRAI::pdat::SideData< TYPE >::fillAll(), SAMRAI::pdat::OutersideData< TYPE >::fillAll(), SAMRAI::pdat::SideData< TYPE >::getSizeOfData(), SAMRAI::pdat::OutersideData< TYPE >::getSizeOfData(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::integral(), SAMRAI::math::PatchSideDataNormOpsComplex::integral(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::PatchSideDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::L2Norm(), SAMRAI::math::PatchSideDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::linearSum(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::max(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::PatchSideDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::min(), SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::multiply(), SAMRAI::math::PatchSideDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsComplex::numberOfEntries(), SAMRAI::pdat::OutersideData< TYPE >::OutersideData(), SAMRAI::pdat::OutersideData< TYPE >::printAxisSide(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::HierarchySideDataOpsReal< TYPE >::resetLevels(), SAMRAI::math::HierarchySideDataOpsInteger::resetLevels(), SAMRAI::math::HierarchySideDataOpsComplex::resetLevels(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::scale(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::setRandomValues(), setUpOverlap(), SAMRAI::pdat::OutersideGeometry::setUpOverlap(), SAMRAI::pdat::SideData< TYPE >::SideData(), SAMRAI::math::PatchSideDataBasicOps< TYPE >::subtract(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::PatchSideDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedL2Norm(), and SAMRAI::math::PatchSideDataNormOpsComplex::weightedL2Norm().
void SAMRAI::pdat::SideGeometry::transform (hier::Box & box, int & normal_direction, const hier::Transformation & transformation) [static]
Transform a side-centered box.
At input, the Box is assumed to represent an side-centered box with the given normal direction. The Box will be transformed according to the coordinate system transformation defined by the Transformation object. At output, normal_direction will represent the output box's new normal direction.
Parameters:
[in,out] box
[in,out] normal_direction
[in] transformation
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_JUP_KUP, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::hier::Box::setUpper(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::pdat::SideOverlap::getSourceBoxContainer().
void SAMRAI::pdat::SideGeometry::transform (SideIndex & index, const hier::Transformation & transformation) [static]
Transform a SideIndex.
This static method applies a coordinate system transformation to the given SideIndex.
Parameters:
[in,out] index
[in] transformation
References SAMRAI::pdat::SideIndex::getAxis(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::pdat::SideIndex::setAxis(), TBOX_ASSERT, and TBOX_ERROR.
SideIterator SAMRAI::pdat::SideGeometry::begin (const hier::Box & box, tbox::Dimension::dir_t axis) [static]
Referenced by SAMRAI::pdat::SideData< TYPE >::printAxis().
SideIterator SAMRAI::pdat::SideGeometry::end (const hier::Box & box, tbox::Dimension::dir_t axis) [static]
Referenced by SAMRAI::pdat::SideData< TYPE >::printAxis().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::SideGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in side-centered index space between the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::pdat::SideGeometry::computeDestinationBoxes (std::vector< hier::BoxContainer > & dst_boxes, const SideGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const
Compute the side-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
Precondition:
src_mask.getDim() == transformation.getOffset.getDim()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getDim(), getDirectionVector(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxContainer::pushBack(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, toSideBox(), and SAMRAI::hier::Transformation::transform().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::SideGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a SideOverlap object based on the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getOffset(), and toSideBox().
const hier::Box& SAMRAI::pdat::SideGeometry::getBox () const [inline]
Return the box for this side centered box geometry object.
const hier::IntVector& SAMRAI::pdat::SideGeometry::getGhosts () const [inline]
Return the ghost cell width for this side centered box geometry object.
const hier::IntVector& SAMRAI::pdat::SideGeometry::getDirectionVector () const [inline]
Return constant reference to vector describing which coordinate directions managed by this side geometry object.
A vector entry of zero indicates that this object will not perform operations involving the corresponding coordinate direction. A non-zero value indicates otherwise.
Referenced by computeDestinationBoxes().
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/SideGeometry.h
source/SAMRAI/pdat/SideGeometry.C