SAMRAI: SAMRAI::pdat::OutersideData< TYPE > Class Template Reference
SAMRAI::pdat::OutersideData< TYPE > Class Template Reference
Class OutersideData<TYPE> provides an implementation for data defined at cell sides (faces) on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outerside data object represents data of some template TYPE and depth on the cell sides (faces) on the boundary of the box. Here, depth indicates the number of data values at each face index location. The OuteredgsideGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outerside-centered data.
#include <source/SAMRAI/pdat/OutersideData.h>
Public Member Functions
OutersideData (const hier::Box &box, int depth)
Constructor for an outerside data object.
virtual ~OutersideData ()
Virtual destructor for a outerside data object.
int getDepth () const
Return the depth (i.e., the number of data values for each spatial location) of the array.
TYPE * getPointer (int side_normal, int side, int depth=0)
Get a pointer to the beginning of a particular side normal, side, and depth component of the outerside centered array.
const TYPE * getPointer (int side_normal, int side, int depth=0) const
Get a const pointer to the beginning of a particular side normal, side, and depth component of the outerside centered array.
TYPE & operator() (const SideIndex &i, int side, int depth=0)
Return a reference to data entry corresponding to a given side index, side location, and depth.
const TYPE & operator() (const SideIndex &i, int side, int depth=0) const
Return a const reference to data entry corresponding to a given side index, side location, and depth.
ArrayData< TYPE > & getArrayData (int side_normal, int side)
Return a reference to the array data object for side normal and side location of the outerside centered array.
const ArrayData< TYPE > & getArrayData (int side_normal, int side) const
Return a const reference to the array data object for side normal and side location of the outerside centered array.
virtual void copy (const hier::PatchData &src)
A fast copy from source to destination (i.e., this) patch data object.
virtual void copy2 (hier::PatchData &dst) const
A fast copy from source (i.e., this) to destination patch data object.
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Copy data from source to destination (i.e., this) patch data object on the given overlap.
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
Copy data from source (i.e., this) to destination patch data object on the given overlap.
void copyDepth (int dst_depth, const SideData< TYPE > &src, int src_depth)
Fast copy (i.e., assumes side and outerside data objects are defined over the same box) from the given side source data object to this destination outerside data object at the specified depths.
void copyDepth2 (int dst_depth, SideData< TYPE > &dst, int src_depth) const
Fast copy (i.e., assumes side and outerside data objects are defined over the same box) to the given side destination data object from this source outerside data object at the specified depths.
virtual bool canEstimateStreamSizeFromBox () const
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
virtual size_t getDataStreamSize (const hier::BoxOverlap &overlap) const
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an SideOverlap of the same DIM.
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an SideOverlap of the same DIM.
void fill (const TYPE &t, int d=0)
Fill all values at depth d with the value t.
void fill (const TYPE &t, const hier::Box &box, int d=0)
Fill all values at depth d within the box with the value t.
void fillAll (const TYPE &t)
Fill all depth components with value t.
void fillAll (const TYPE &t, const hier::Box &box)
Fill all depth components within the box with value t.
void print (const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all outerside data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
void print (const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all outerside data values at the given array depth in the specified box.
void printAxisSide (tbox::Dimension::dir_t side_normal, int side, const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all outerside centered data values for specified side_normal and side location residing in the specified box. If the depth of the data is greater than one, all depths are printed.
void printAxisSide (tbox::Dimension::dir_t side_normal, int side, const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all outerside centered data values for specified side_normal, side location, and depth residing in the specified box.
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
Check that class version and restart file version are equal. If so, read data members from the restart database.
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write out the class version number and other data members to the restart database.
Static Public Member Functions
static size_t getSizeOfData (const hier::Box &box, int depth)
Calculate the amount of memory needed to represent outerside- centered data over a CELL-centered AMR index space box.
Detailed Description
template<class TYPE>
class SAMRAI::pdat::OutersideData< TYPE >
Class OutersideData<TYPE> provides an implementation for data defined at cell sides (faces) on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outerside data object represents data of some template TYPE and depth on the cell sides (faces) on the boundary of the box. Here, depth indicates the number of data values at each face index location. The OuteredgsideGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outerside-centered data.
Outerside data is stored in 2*DIM arrays, each of which contains data associated with side (face) indices normal to a coordinate axis direction and an upper or lower box side (face) in the face normal direction. The data layout in the outerside data arrays matches the corresponding array sections provided by the side data implementation. Also, in each of array, memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory. For example, a three-dimensional outerside data object created over a CELL-centered AMR index space [l0:u0,l1:u1,l2:u2] allocates six data arrays sized as follows:
 *
 * face normal 0:
 *   lower face      [ l0:l0     , l1:u1     , l2:u2     , d ]
 *   upper face      [ u0+1:u0+1 , l1:u1     , l2:u2     , d ]
 *
 * face normal 1:
 *   lower face      [ l0:u0     , l1:l1     , l2:u2     , d ]
 *   upper face      [ l0:u0     , u1+1:u1+1 , l2:u2     , d ]
 *
 * face normal 2:
 *   lower face      [ l0:u0     , l1:u1     , l2:l2     , d ]
 *   upper face      [ l0:u0     , l1:u1     , u2+1:u2+1 , d ]
 *
 *
Here the face normal directions 0, 1, 2 can be thought of as the x, y, and z face normal directions, respectively, and d is the depth index (i.e., number of values at each face index location). Other spatial dimensions are represented similarly.
The data type TYPE must define a default constructor (that takes no arguments) and also the assignment operator.
IMPORTANT: The OuterfaceData<TYPE> class provides the same storage as this outerside data class, except that the coordinate directions of the individual arrays are permuted; i.e., OuterfaceData is consistent with the FaceData implementation.
See also:
ArrayData
hier::PatchData
OutersideDataFactory
OutersideGeometry
SideIterator
SideIndex
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::OutersideData< TYPE >::OutersideData (const hier::Box & box, int depth) [inline]
Constructor for an outerside data object.
Note: Outerside data always has ghost cell width of zero.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the outerside data object will be created.
depth gives the number of data values for each spatial location in the array.
Precondition:
depth > 0
References SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, SAMRAI::pdat::SideGeometry::toSideBox(), and SAMRAI::hier::Box::upper().
template<class TYPE > SAMRAI::pdat::OutersideData< TYPE >::~OutersideData () [inline, virtual]
Virtual destructor for a outerside data object.
Member Function Documentation
template<class TYPE > size_t SAMRAI::pdat::OutersideData< TYPE >::getSizeOfData (const hier::Box & box, int depth) [inline, static]
Calculate the amount of memory needed to represent outerside- centered data over a CELL-centered AMR index space box.
This function assumes that the amount of memory needed for TYPE is sizeof(TYPE). If this is not the case, then a specialized function must be defined.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the outerside data object will be created. Note: the ghost cell width is assumed to be zero.
depth gives the number of data values for each spatial location in the array.
Precondition:
depth > 0
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, SAMRAI::pdat::SideGeometry::toSideBox(), and SAMRAI::hier::Box::upper().
template<class TYPE > int SAMRAI::pdat::OutersideData< TYPE >::getDepth () const [inline]
Return the depth (i.e., the number of data values for each spatial location) of the array.
template<class TYPE > TYPE * SAMRAI::pdat::OutersideData< TYPE >::getPointer (int side_normal, int side, int depth = 0) [inline]
Get a pointer to the beginning of a particular side normal, side, and depth component of the outerside centered array.
Parameters:
side_normal integer side normal direction for data
side integer lower (0) or upper (1) side of outerside data array
depth integer depth component
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > const TYPE * SAMRAI::pdat::OutersideData< TYPE >::getPointer (int side_normal, int side, int depth = 0) const [inline]
Get a const pointer to the beginning of a particular side normal, side, and depth component of the outerside centered array.
Parameters:
side_normal integer side normal direction for data
side integer lower (0) or upper (1) side of outerside data array
depth integer depth component
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::OutersideData< TYPE >::operator() (const SideIndex & i, int side, int depth = 0) [inline]
Return a reference to data entry corresponding to a given side index, side location, and depth.
Parameters:
i const reference to SideIndex, MUST be an index on the outerside of the box.
side integer (lower/upper location of outerside data)
depth integer depth component
Precondition:
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::SideIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > const TYPE & SAMRAI::pdat::OutersideData< TYPE >::operator() (const SideIndex & i, int side, int depth = 0) const [inline]
Return a const reference to data entry corresponding to a given side index, side location, and depth.
Parameters:
i const reference to SideIndex, MUST be an index on the outerside of the box.
side integer (lower/upper location of outerside data)
depth integer depth component
Precondition:
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::SideIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > ArrayData< TYPE > & SAMRAI::pdat::OutersideData< TYPE >::getArrayData (int side_normal, int side) [inline]
Return a reference to the array data object for side normal and side location of the outerside centered array.
Parameters:
side_normal integer side normal direction for data
side integer lower (0) or upper (1) side of outerside data array
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::OutersideData< TYPE >::copy().
template<class TYPE > const ArrayData< TYPE > & SAMRAI::pdat::OutersideData< TYPE >::getArrayData (int side_normal, int side) const [inline]
Return a const reference to the array data object for side normal and side location of the outerside centered array.
Parameters:
side_normal integer side normal direction for data
side integer lower (0) or upper (1) side of outerside data array
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy from source to destination (i.e., this) patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, source data must be SideData the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
dynamic_cast<const SideData<TYPE> *>(&src) != 0
References SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::SideData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy from source (i.e., this) to destination patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, destination data must be SideData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<SideData<TYPE> *>(&dst) != 0
References SAMRAI::pdat::SideData< TYPE >::getArrayData(), SAMRAI::hier::PatchData::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from source to destination (i.e., this) patch data object on the given overlap.
IMPORTANT: this routine is not yet implemented!
References SAMRAI::pdat::OutersideData< TYPE >::getArrayData(), SAMRAI::pdat::SideOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from source (i.e., this) to destination patch data object on the given overlap.
Currently, destination data must be SideData of the same DIM and TYPE and the overlap must be a SideOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<SideData<TYPE> *>(&dst) != 0
dynamic_cast<const SideOverlap *>(&overlap) != 0
References SAMRAI::pdat::SideData< TYPE >::getArrayData(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::copyDepth (int dst_depth, const SideData< TYPE > & src, int src_depth) [inline]
Fast copy (i.e., assumes side and outerside data objects are defined over the same box) from the given side source data object to this destination outerside data object at the specified depths.
Precondition:
getDim == src.getDim()
References SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::pdat::SideData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::copyDepth2 (int dst_depth, SideData< TYPE > & dst, int src_depth) const [inline]
Fast copy (i.e., assumes side and outerside data objects are defined over the same box) to the given side destination data object from this source outerside data object at the specified depths.
Precondition:
getDim == dst.getDim()
References SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::pdat::SideData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::OutersideData< TYPE >::canEstimateStreamSizeFromBox () const [inline, virtual]
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Implements SAMRAI::hier::PatchData.
template<class TYPE > size_t SAMRAI::pdat::OutersideData< TYPE >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Precondition:
dynamic_cast<const SideOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::SideOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an SideOverlap of the same DIM.
Precondition:
dynamic_cast<const SideOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::pdat::SideOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an SideOverlap of the same DIM.
Precondition:
dynamic_cast<const SideOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::pdat::SideOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::fill (const TYPE & t, int d = 0) [inline]
Fill all values at depth d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::fill (const TYPE & t, const hier::Box & box, int d = 0) [inline]
Fill all values at depth d within the box with the value t.
Precondition:
getDim() == box.getDim()
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all depth components with value t.
References SAMRAI::hier::PatchData::getDim(), and SAMRAI::tbox::Dimension::getValue().
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all depth components within the box with value t.
Precondition:
getDim() == box.getDim()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::print (const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerside data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::print (const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerside data values at the given array depth in the specified box.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
depth integer depth component
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::OutersideData< TYPE >::printAxisSide(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::printAxisSide (tbox::Dimension::dir_t side_normal, int side, const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerside centered data values for specified side_normal and side location residing in the specified box. If the depth of the data is greater than one, all depths are printed.
Parameters:
side_normal integer side normal direction for data
side integer lower (0) or upper (1) side of outerside data array
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(side_normal >= 0) && (side_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::OutersideData< TYPE >::print().
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::printAxisSide (tbox::Dimension::dir_t side_normal, int side, const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerside centered data values for specified side_normal, side location, and depth residing in the specified box.
Parameters:
side_normal integer side normal direction for data
side integer lower (0) or upper (1) side of outerside data array
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
depth integer depth component
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
(side_normal >= 0) && (side_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::Box::begin(), SAMRAI::hier::Box::end(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check that class version and restart file version are equal. If so, read data members from the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OutersideData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number and other data members to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OutersideData.h
source/SAMRAI/pdat/OutersideData.C