SAMRAI: SAMRAI::hier::BoxNeighborhoodCollection Class Reference
SAMRAI::hier::BoxNeighborhoodCollection Class Reference
Given a Box in a base BoxLevel, the Boxes in a head BoxLevel which are adjacent to the base Box are its neighbors and are said to form the neighborhood of the base Box. This class describes the neighborhoods of a collection of base Boxes. Each base Box in the collection has a neighborhood of adjacent head Boxes.
#include <source/SAMRAI/hier/BoxNeighborhoodCollection.h>
Classes
class ConstIterator
An iterator over the base Boxes of the neighborhoods in a const BoxNeighborhoodCollection. The interface does not allow modification of the base Boxes.
class ConstNeighborIterator
An iterator over the neighbors in the neighborhood of a base Box in a const BoxNeighborhoodCollection. The interface does not allow modification of the neighbors.
class Iterator
An iterator over the base Boxes of the neighborhoods in a BoxNeighborhoodCollection. The interface does not allow modification of the base Boxes.
class NeighborIterator
An iterator over the neighbors in the neighborhood of a base Box in a BoxNeighborhoodCollection. The interface does not allow modification of the neighbors.
Public Types
typedef std::pair< Iterator, bool > InsertRetType
Public Member Functions
BoxNeighborhoodCollection ()
Constructs an empty object. There are not yet any base Boxes whose neighborhoods are represented by this object.
BoxNeighborhoodCollection (const BoxContainer &base_boxes)
Constructs a collection of empty neighborhoods for each base box in base_boxes.
BoxNeighborhoodCollection (const BoxNeighborhoodCollection &other)
Copy constructor.
BoxNeighborhoodCollection & operator= (const BoxNeighborhoodCollection &rhs)
Assignment operator.
~BoxNeighborhoodCollection ()
Destructor.
bool operator== (const BoxNeighborhoodCollection &rhs) const
Determine if two collections are equivalent.
bool operator!= (const BoxNeighborhoodCollection &rhs) const
Determine if two collections are not equivalent.
void getOwners (std::set< int > &owners) const
Insert the rank of the processor owning each neighbor in each neighborhood into the supplied set.
void getOwners (ConstIterator &itr, std::set< int > &owners) const
Insert the rank of the processor owning each neighbor in each neighborhood into the supplied set.
Iteration
Iterator begin ()
Returns an iterator pointing to the beginning of the collection of neighborhoods.
ConstIterator begin () const
Returns an iterator pointing to the beginning of the collection of neighborhoods.
Iterator end ()
Returns an iterator pointing just past the end of the collection of neighborhoods.
ConstIterator end () const
Returns an iterator pointing just past the end of the collection of neighborhoods.
NeighborIterator begin (const BoxId &base_box_id)
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box with the supplied BoxId.
ConstNeighborIterator begin (const BoxId &base_box_id) const
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box with the supplied BoxId.
NeighborIterator begin (Iterator &base_box_itr)
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box pointed to by base_box_itr.
ConstNeighborIterator begin (const ConstIterator &base_box_itr) const
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box pointed to by base_box_itr.
NeighborIterator end (const BoxId &base_box_id)
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box with the supplied BoxId.
ConstNeighborIterator end (const BoxId &base_box_id) const
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box with the supplied BoxId.
NeighborIterator end (Iterator &base_box_itr)
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box pointed to by base_box_itr.
ConstNeighborIterator end (const ConstIterator &base_box_itr) const
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box pointed to by base_box_itr.
Lookup
ConstIterator find (const BoxId &base_box_id) const
Returns an iterator pointing to the base Box with the supplied BoxId. If no base Box's BoxId is base_box_id this method returns end().
Iterator find (const BoxId &base_box_id)
Returns an iterator pointing to the base Box with the supplied BoxId. If no base Box's BoxId is base_box_id this method returns end().
State queries
bool empty () const
Returns true if the number of box neighborhoods == 0.
int numBoxNeighborhoods () const
Returns the number of box neighborhoods.
bool emptyBoxNeighborhood (const BoxId &base_box_id) const
Returns true if the neighborhood of the base Box with the supplied BoxId is empty.
bool emptyBoxNeighborhood (const ConstIterator &base_box_itr) const
Returns true if the neighborhood of the base Box pointed to by base_box_itr is empty.
int numNeighbors (const BoxId &base_box_id) const
Returns the number of neighbors in the neighborhood of the base Box with the supplied BoxId.
int numNeighbors (const ConstIterator &base_box_itr) const
Returns the number of neighbors in the neighborhood of the base Box pointed to by base_box_itr.
int sumNumNeighbors () const
Returns the number of neighbors in all neighborhoods.
bool hasNeighbor (const BoxId &base_box_id, const Box &nbr) const
Returns true if nbr is a neighbor of the base Box with the supplied BoxId.
bool hasNeighbor (const ConstIterator &base_box_itr, const Box &nbr) const
Returns true if nbr is a neighbor of the base Box pointed to by base_box_itr.
bool neighborhoodEqual (const BoxId &base_box_id, const BoxNeighborhoodCollection &other) const
Returns true if the neighborhood of the base Box with the supplied BoxId is the same in this and other.
bool isBaseBox (const BoxId &base_box_id) const
Returns true if base_box_id is the BoxId of the base Box of a neighborhood held by this object.
bool isLocal (int rank) const
Returns true if all neighbors of all base Boxes are owned by the processor owning this object.
Neighborhood editing
Iterator insert (const BoxId &base_box_id, const Box &new_nbr)
Inserts a new neighbor into the neighborhood of the base Box with the supplied BoxId.
void insert (Iterator &base_box_itr, const Box &new_nbr)
Inserts a new neighbor into the neighborhood of the base Box pointed to by base_box_itr.
Iterator insert (const BoxId &base_box_id, const BoxContainer &new_nbrs)
Inserts new neighbors into the neighborhood of the base Box with the supplied BoxId.
void insert (Iterator &base_box_itr, const BoxContainer &new_nbrs)
Inserts new neighbors into the neighborhood of the base Box pointed to by base_box_itr.
void erase (const BoxId &base_box_id, const Box &nbr)
Erases a neighbor from the neighborhood of the base Box with the supplied BoxId.
void erase (Iterator &base_box_itr, const Box &nbr)
Erases a neighbor from the neighborhood of the base Box pointed to by base_box_itr.
void erase (const BoxId &base_box_id, const BoxContainer &nbrs)
Erases neighbors from the neighborhood of the base Box with the supplied BoxId.
void erase (Iterator &base_box_itr, const BoxContainer &nbrs)
Erases neighbors from the neighborhood of the base Box pointed to by base_box_itr.
InsertRetType insert (const BoxId &new_base_box)
Inserts a base Box with an empty neighborhood. If the base Box does not exist in this object then this function returns true. Otherwise it returns false and takes no action.
void erase (const BoxId &base_box_id)
Erases the neighbors of the base Box with the supplied BoxId including the base Box itself.
void erase (Iterator &base_box_itr)
Erases the neighbors of the base Box pointed to by base_box_itr including base Box iself.
void erase (Iterator &first_base_box_itr, Iterator &last_base_box_itr)
Erases the neighbors of the base Boxes pointed to in the range [first_base_box_itr, last_base_box_itr) including the base Boxes themselves.
void eraseNonLocalNeighborhoods (int rank)
For all base Boxes not owned by the process owning this object this method erases the base Box and its neighbors.
void eraseEmptyNeighborhoods ()
Erases all base Boxes having no neighbors.
void erasePeriodicNeighbors ()
Erases all neighbors in all neighborhoods which are periodic image boxes.
void clear ()
Erases all contents so empty() == true.
Coarsen, refine, grow.
void coarsenNeighbors (const IntVector &ratio)
Coarsens the neighbors of each base Box by the given ratio.
void refineNeighbors (const IntVector &ratio)
Refines the neighbors of each base Box by the given ratio.
void growNeighbors (const IntVector &growth)
Grows the neighbors of each base Box by the given amount.
Neighborhood member extraction
Currently, the way some algorithms are implemented these are needed but we may find that it is not necessary.
void getNeighbors (BoxContainer &neighbors) const
Fill the supplied BoxContainer with the neighbors from all the neighborhoods in this object. The container has no notion of the neighborhoods to which its contents belong.
void getNeighbors (BoxContainer &neighbors, const BlockId &block_id) const
Fill the supplied BoxContainer with the neighbors having the specified block id from all the neighborhoods in this object. The container has no notion of the neighborhoods to which its contents belong.
void getNeighbors (std::map< BlockId, BoxContainer > &neighbors) const
Fill the supplied map with the neighbors from all the neighborhoods in this object by block id. The container has no notion of the neighborhoods to which its contents belong.
void getNeighbors (const BoxId &base_box_id, BoxContainer &neighbors) const
Fill the supplied BoxContainer with the neighbors of the base Box with the supplied BoxId.
void getPeriodicNeighbors (BoxContainer &result) const
Place any periodic neighbors from each neighborhood into the supplied BoxContainer.
Communication packing/unpacking
void putToIntBuffer (std::vector< int > &send_mesg, const tbox::Dimension &dim, int buff_init) const
Load an integer communication buffer with the data from this object.
void getFromIntBuffer (const std::vector< int > &recv_mesg, const std::vector< int > &proc_offset, const tbox::Dimension &dim, int num_proc, int rank)
Populate object based on information contained in an integer communication buffer.
IO--these are only called from the mblktree test.
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Writes the neighborhood information to the supplied restart database.
void getFromRestart (tbox::Database &restart_db)
Constructs the neighborhoods from the supplied restart database.
Friends
class Iterator
class ConstIterator
Detailed Description
Given a Box in a base BoxLevel, the Boxes in a head BoxLevel which are adjacent to the base Box are its neighbors and are said to form the neighborhood of the base Box. This class describes the neighborhoods of a collection of base Boxes. Each base Box in the collection has a neighborhood of adjacent head Boxes.
Member Typedef Documentation
typedef std::pair<Iterator, bool> SAMRAI::hier::BoxNeighborhoodCollection::InsertRetType
Constructor & Destructor Documentation
SAMRAI::hier::BoxNeighborhoodCollection::BoxNeighborhoodCollection ()
Constructs an empty object. There are not yet any base Boxes whose neighborhoods are represented by this object.
SAMRAI::hier::BoxNeighborhoodCollection::BoxNeighborhoodCollection (const BoxContainer & base_boxes)
Constructs a collection of empty neighborhoods for each base box in base_boxes.
Parameters:
base_boxes Base boxes whose neighborhoods will be represented by this object.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), and insert().
SAMRAI::hier::BoxNeighborhoodCollection::BoxNeighborhoodCollection (const BoxNeighborhoodCollection & other)
Copy constructor.
Parameters:
other
References begin(), end(), and insert().
SAMRAI::hier::BoxNeighborhoodCollection::~BoxNeighborhoodCollection ()
Destructor.
Member Function Documentation
BoxNeighborhoodCollection & SAMRAI::hier::BoxNeighborhoodCollection::operator= (const BoxNeighborhoodCollection & rhs)
Assignment operator.
Parameters:
rhs
References begin(), clear(), end(), and insert().
bool SAMRAI::hier::BoxNeighborhoodCollection::operator== (const BoxNeighborhoodCollection & rhs) const
Determine if two collections are equivalent.
Parameters:
rhs
References begin(), end(), numBoxNeighborhoods(), and numNeighbors().
bool SAMRAI::hier::BoxNeighborhoodCollection::operator!= (const BoxNeighborhoodCollection & rhs) const
Determine if two collections are not equivalent.
Parameters:
rhs
Iterator SAMRAI::hier::BoxNeighborhoodCollection::begin () [inline]
Returns an iterator pointing to the beginning of the collection of neighborhoods.
References Iterator.
Referenced by SAMRAI::hier::Connector::begin(), begin(), BoxNeighborhoodCollection(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doTransposeWork(), eraseEmptyNeighborhoods(), eraseNonLocalNeighborhoods(), erasePeriodicNeighbors(), getNeighbors(), getOwners(), getPeriodicNeighbors(), isLocal(), neighborhoodEqual(), operator=(), operator==(), putToIntBuffer(), putToRestart(), sumNumNeighbors(), and SAMRAI::hier::Connector::writeNeighborhoodToStream().
ConstIterator SAMRAI::hier::BoxNeighborhoodCollection::begin () const [inline]
Returns an iterator pointing to the beginning of the collection of neighborhoods.
References ConstIterator.
Iterator SAMRAI::hier::BoxNeighborhoodCollection::end () [inline]
Returns an iterator pointing just past the end of the collection of neighborhoods.
References Iterator.
Referenced by begin(), BoxNeighborhoodCollection(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doTransposeWork(), emptyBoxNeighborhood(), SAMRAI::hier::Connector::end(), end(), erase(), eraseEmptyNeighborhoods(), eraseNonLocalNeighborhoods(), erasePeriodicNeighbors(), SAMRAI::hier::Connector::find(), find(), getNeighbors(), getOwners(), getPeriodicNeighbors(), hasNeighbor(), SAMRAI::hier::Connector::hasNeighborSet(), insert(), isBaseBox(), isLocal(), neighborhoodEqual(), numNeighbors(), operator=(), operator==(), putToIntBuffer(), putToRestart(), sumNumNeighbors(), and SAMRAI::hier::Connector::writeNeighborhoodToStream().
ConstIterator SAMRAI::hier::BoxNeighborhoodCollection::end () const [inline]
Returns an iterator pointing just past the end of the collection of neighborhoods.
References ConstIterator.
NeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::begin (const BoxId & base_box_id) [inline]
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id
References begin(), and find().
ConstNeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::begin (const BoxId & base_box_id) const [inline]
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id
References begin(), and find().
NeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::begin (Iterator & base_box_itr) [inline]
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
ConstNeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::begin (const ConstIterator & base_box_itr) const [inline]
Returns an iterator pointing to the first neighbor in the neighborhood of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
NeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::end (const BoxId & base_box_id) [inline]
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id
References end(), and find().
ConstNeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::end (const BoxId & base_box_id) const [inline]
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id
References end(), and find().
NeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::end (Iterator & base_box_itr) [inline]
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
ConstNeighborIterator SAMRAI::hier::BoxNeighborhoodCollection::end (const ConstIterator & base_box_itr) const [inline]
Returns an iterator pointing just past the last neighbor in the neighborhood of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
ConstIterator SAMRAI::hier::BoxNeighborhoodCollection::find (const BoxId & base_box_id) const [inline]
Returns an iterator pointing to the base Box with the supplied BoxId. If no base Box's BoxId is base_box_id this method returns end().
Parameters:
base_box_id
References ConstIterator, and end().
Referenced by begin(), SAMRAI::hier::Connector::checkTransposeCorrectness(), emptyBoxNeighborhood(), end(), erase(), SAMRAI::hier::Connector::find(), SAMRAI::hier::Connector::findLocal(), getNeighbors(), hasNeighbor(), SAMRAI::hier::Connector::hasNeighborSet(), isBaseBox(), numNeighbors(), and SAMRAI::hier::Connector::writeNeighborhoodToStream().
Iterator SAMRAI::hier::BoxNeighborhoodCollection::find (const BoxId & base_box_id) [inline]
Returns an iterator pointing to the base Box with the supplied BoxId. If no base Box's BoxId is base_box_id this method returns end().
Parameters:
base_box_id
References end(), and Iterator.
bool SAMRAI::hier::BoxNeighborhoodCollection::empty () const [inline]
Returns true if the number of box neighborhoods == 0.
int SAMRAI::hier::BoxNeighborhoodCollection::numBoxNeighborhoods () const [inline]
Returns the number of box neighborhoods.
Referenced by SAMRAI::hier::Connector::cacheGlobalReducedData(), SAMRAI::hier::Connector::getLocalNumberOfNeighborSets(), operator==(), putToIntBuffer(), putToRestart(), and SAMRAI::hier::Connector::writeNeighborhoodsToErrorStream().
bool SAMRAI::hier::BoxNeighborhoodCollection::emptyBoxNeighborhood (const BoxId & base_box_id) const [inline]
Returns true if the neighborhood of the base Box with the supplied BoxId is empty.
Parameters:
base_box_id
References find().
Referenced by SAMRAI::hier::Connector::isEmptyNeighborhood(), and SAMRAI::hier::Connector::numLocalEmptyNeighborhoods().
bool SAMRAI::hier::BoxNeighborhoodCollection::emptyBoxNeighborhood (const ConstIterator & base_box_itr) const [inline]
Returns true if the neighborhood of the base Box pointed to by base_box_itr is empty.
Parameters:
base_box_itr
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
int SAMRAI::hier::BoxNeighborhoodCollection::numNeighbors (const BoxId & base_box_id) const [inline]
Returns the number of neighbors in the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id
References find().
Referenced by SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::hier::Connector::finalizeContext(), neighborhoodEqual(), SAMRAI::hier::Connector::numLocalNeighbors(), operator==(), putToIntBuffer(), putToRestart(), sumNumNeighbors(), and SAMRAI::hier::Connector::writeNeighborhoodsToErrorStream().
int SAMRAI::hier::BoxNeighborhoodCollection::numNeighbors (const ConstIterator & base_box_itr) const [inline]
Returns the number of neighbors in the neighborhood of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
int SAMRAI::hier::BoxNeighborhoodCollection::sumNumNeighbors () const
Returns the number of neighbors in all neighborhoods.
References begin(), end(), and numNeighbors().
Referenced by SAMRAI::hier::Connector::cacheGlobalReducedData(), SAMRAI::hier::Connector::getLocalNumberOfRelationships(), and putToIntBuffer().
bool SAMRAI::hier::BoxNeighborhoodCollection::hasNeighbor (const BoxId & base_box_id, const Box & nbr) const [inline]
Returns true if nbr is a neighbor of the base Box with the supplied BoxId.
Parameters:
base_box_id
nbr
References find().
Referenced by SAMRAI::hier::Connector::checkTransposeCorrectness(), and SAMRAI::hier::Connector::hasLocalNeighbor().
bool SAMRAI::hier::BoxNeighborhoodCollection::hasNeighbor (const ConstIterator & base_box_itr, const Box & nbr) const
Returns true if nbr is a neighbor of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr
nbr
References end().
bool SAMRAI::hier::BoxNeighborhoodCollection::neighborhoodEqual (const BoxId & base_box_id, const BoxNeighborhoodCollection & other) const
Returns true if the neighborhood of the base Box with the supplied BoxId is the same in this and other.
Parameters:
base_box_id
other
References begin(), end(), and numNeighbors().
Referenced by SAMRAI::hier::Connector::neighborhoodEqual().
bool SAMRAI::hier::BoxNeighborhoodCollection::isBaseBox (const BoxId & base_box_id) const [inline]
Returns true if base_box_id is the BoxId of the base Box of a neighborhood held by this object.
Parameters:
base_box_id
References end(), and find().
Referenced by SAMRAI::hier::Connector::checkTransposeCorrectness().
bool SAMRAI::hier::BoxNeighborhoodCollection::isLocal (int rank) const
Returns true if all neighbors of all base Boxes are owned by the processor owning this object.
Note:
Currently, this is only called (via Connector::isLocal) from within a small number of TBOX_ASSERTs so it is only a sanity check and is not called in optimized code. If the method becomes algorithmically important an optimization would be to store a boolean to indicate if there are any non-local neighbors which would avoid the search that this method currently does.
Parameters:
rank The rank of the process owning this object.
References begin(), and end().
Referenced by SAMRAI::hier::Connector::isLocal().
void SAMRAI::hier::BoxNeighborhoodCollection::getOwners (std::set< int > & owners) const
Insert the rank of the processor owning each neighbor in each neighborhood into the supplied set.
Parameters:
owners
References begin(), and end().
Referenced by SAMRAI::hier::Connector::getLocalOwners().
void SAMRAI::hier::BoxNeighborhoodCollection::getOwners (ConstIterator & itr, std::set< int > & owners) const
Insert the rank of the processor owning each neighbor in each neighborhood into the supplied set.
Parameters:
itr
owners
References begin(), and end().
Iterator SAMRAI::hier::BoxNeighborhoodCollection::insert (const BoxId & base_box_id, const Box & new_nbr) [inline]
Inserts a new neighbor into the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id The BoxId of the neighborhood base Box.
new_nbr The new neighbor of base_box_id.
Returns:
An Iterator pointing to the base Box with the supplied BoxId.
Referenced by BoxNeighborhoodCollection(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::hier::Connector::doLocalTransposeWork(), getFromIntBuffer(), getFromRestart(), insert(), SAMRAI::hier::Connector::insertLocalNeighbor(), SAMRAI::hier::Connector::insertNeighbors(), SAMRAI::hier::Connector::makeEmptyLocalNeighborhood(), and operator=().
void SAMRAI::hier::BoxNeighborhoodCollection::insert (Iterator & base_box_itr, const Box & new_nbr)
Inserts a new neighbor into the neighborhood of the base Box pointed to by base_box_itr.
Note:
base_box_itr must point to a valid base Box or this function can not work. Unlike the other versions of insert, this version has no return value. The base Box must already exist and the Iterator already points to it so returning an Iterator or bool has no value.
Parameters:
base_box_itr Iterator pointing to the base Box.
new_nbr The new neighbor of the base Box.
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
Iterator SAMRAI::hier::BoxNeighborhoodCollection::insert (const BoxId & base_box_id, const BoxContainer & new_nbrs) [inline]
Inserts new neighbors into the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id The BoxId of the base Box.
new_nbrs The new neighbors of the base Box.
Returns:
An Iterator pointing to the base Box with the supplied BoxId.
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References insert().
void SAMRAI::hier::BoxNeighborhoodCollection::insert (Iterator & base_box_itr, const BoxContainer & new_nbrs)
Inserts new neighbors into the neighborhood of the base Box pointed to by base_box_itr.
Note:
base_box_itr must point to a valid base Box or this function can not work. Unlike the other versions of insert, this version has no return value. The base Box must already exist and the Iterator already points to it so returning an Iterator or bool has no value.
Parameters:
base_box_itr Iterator pointing to the base Box.
new_nbrs The new neighbors of the base Box.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), end(), and TBOX_ASSERT.
void SAMRAI::hier::BoxNeighborhoodCollection::erase (const BoxId & base_box_id, const Box & nbr) [inline]
Erases a neighbor from the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id The BoxId of the base Box.
nbr The neighbor of the base Box to be erased.
References find().
Referenced by erase(), eraseEmptyNeighborhoods(), SAMRAI::hier::Connector::eraseLocalNeighborhood(), SAMRAI::hier::Connector::eraseNeighbor(), eraseNonLocalNeighborhoods(), erasePeriodicNeighbors(), and SAMRAI::hier::Connector::shrinkWidth().
void SAMRAI::hier::BoxNeighborhoodCollection::erase (Iterator & base_box_itr, const Box & nbr)
Erases a neighbor from the neighborhood of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr An iterator pointing to the base Box.
nbr The neighbor of the base Box to be erased.
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
d_nbrs.find(nbr) != d_nbrs.end()
References end(), and TBOX_ASSERT.
void SAMRAI::hier::BoxNeighborhoodCollection::erase (const BoxId & base_box_id, const BoxContainer & nbrs) [inline]
Erases neighbors from the neighborhood of the base Box with the supplied BoxId.
Parameters:
base_box_id The BoxId of the base Box.
nbrs The neighbors of base Box to be erased.
References erase(), and find().
void SAMRAI::hier::BoxNeighborhoodCollection::erase (Iterator & base_box_itr, const BoxContainer & nbrs)
Erases neighbors from the neighborhood of the base Box pointed to by base_box_itr.
Parameters:
base_box_itr An iterator pointing to the base Box.
nbrs The neighbors of base Box to be erased.
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
for each box in nbrs, d_nbrs.find(box) != d_nbrs.end()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), end(), and TBOX_ASSERT.
BoxNeighborhoodCollection::InsertRetType SAMRAI::hier::BoxNeighborhoodCollection::insert (const BoxId & new_base_box)
Inserts a base Box with an empty neighborhood. If the base Box does not exist in this object then this function returns true. Otherwise it returns false and takes no action.
Parameters:
new_base_box The new base_box of an empty neighborhood.
Returns:
A pair whose first member is an Iterator and second member is a bool. If new_base_box was already a base Box then the Iterator points to the already existing base Box's neighborhood and the bool is false. If new_base_box did not already exist then the Iterator points to the newly inserted base Box's neighborhood and the bool is true.
References Iterator.
void SAMRAI::hier::BoxNeighborhoodCollection::erase (const BoxId & base_box_id) [inline]
Erases the neighbors of the base Box with the supplied BoxId including the base Box itself.
Parameters:
base_box_id The BoxId of the base Box whose neighbors are to be erased.
References erase(), and find().
void SAMRAI::hier::BoxNeighborhoodCollection::erase (Iterator & base_box_itr)
Erases the neighbors of the base Box pointed to by base_box_itr including base Box iself.
Parameters:
base_box_itr Iterator pointing to the base box whose neighbors are to be erased.
Precondition:
base_box_itr.d_collection == this
base_box_itr != end()
References end(), and TBOX_ASSERT.
void SAMRAI::hier::BoxNeighborhoodCollection::erase (Iterator & first_base_box_itr, Iterator & last_base_box_itr)
Erases the neighbors of the base Boxes pointed to in the range [first_base_box_itr, last_base_box_itr) including the base Boxes themselves.
Parameters:
first_base_box_itr Iterator pointing to the first base Box whose neighbors are to be erased.
last_base_box_itr Iterator pointing one past the last base Box whose neighbors are to be erased.
References erase().
void SAMRAI::hier::BoxNeighborhoodCollection::eraseNonLocalNeighborhoods (int rank)
For all base Boxes not owned by the process owning this object this method erases the base Box and its neighbors.
Parameters:
rank the rank of the process owning this object.
References begin(), end(), and erase().
Referenced by SAMRAI::hier::Connector::finalizeContext().
void SAMRAI::hier::BoxNeighborhoodCollection::eraseEmptyNeighborhoods ()
Erases all base Boxes having no neighbors.
References begin(), end(), and erase().
Referenced by SAMRAI::hier::Connector::eraseEmptyNeighborSets().
void SAMRAI::hier::BoxNeighborhoodCollection::erasePeriodicNeighbors ()
Erases all neighbors in all neighborhoods which are periodic image boxes.
References begin(), end(), erase(), and SAMRAI::hier::Box::isPeriodicImage().
Referenced by SAMRAI::hier::Connector::removePeriodicLocalNeighbors(), and SAMRAI::hier::Connector::removePeriodicRelationships().
void SAMRAI::hier::BoxNeighborhoodCollection::clear ()
Erases all contents so empty() == true.
Referenced by SAMRAI::hier::Connector::clear(), SAMRAI::hier::Connector::clearNeighborhoods(), SAMRAI::hier::Connector::finalizeContext(), operator=(), and SAMRAI::hier::Connector::setParallelState().
void SAMRAI::hier::BoxNeighborhoodCollection::coarsenNeighbors (const IntVector & ratio)
Coarsens the neighbors of each base Box by the given ratio.
Parameters:
ratio
References SAMRAI::hier::Box::coarsen().
Referenced by SAMRAI::hier::Connector::coarsenLocalNeighbors().
void SAMRAI::hier::BoxNeighborhoodCollection::refineNeighbors (const IntVector & ratio)
Refines the neighbors of each base Box by the given ratio.
Parameters:
ratio
References SAMRAI::hier::Box::refine().
Referenced by SAMRAI::hier::Connector::refineLocalNeighbors().
void SAMRAI::hier::BoxNeighborhoodCollection::growNeighbors (const IntVector & growth)
Grows the neighbors of each base Box by the given amount.
Parameters:
growth
References SAMRAI::hier::Box::grow().
Referenced by SAMRAI::hier::Connector::growLocalNeighbors().
void SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors (BoxContainer & neighbors) const
Fill the supplied BoxContainer with the neighbors from all the neighborhoods in this object. The container has no notion of the neighborhoods to which its contents belong.
Parameters:
neighbors
References begin(), end(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::BoxContainer::isOrdered(), and SAMRAI::hier::BoxContainer::pushBack().
Referenced by SAMRAI::hier::Connector::getLocalNeighbors(), and SAMRAI::hier::Connector::getNeighborBoxes().
void SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors (BoxContainer & neighbors, const BlockId & block_id) const
Fill the supplied BoxContainer with the neighbors having the specified block id from all the neighborhoods in this object. The container has no notion of the neighborhoods to which its contents belong.
Parameters:
neighbors
block_id
References begin(), end(), SAMRAI::hier::Box::getBlockId(), and SAMRAI::hier::BoxContainer::insert().
void SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors (std::map< BlockId, BoxContainer > & neighbors) const
Fill the supplied map with the neighbors from all the neighborhoods in this object by block id. The container has no notion of the neighborhoods to which its contents belong.
Parameters:
neighbors
References begin(), end(), and SAMRAI::hier::Box::getBlockId().
void SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors (const BoxId & base_box_id, BoxContainer & neighbors) const
Fill the supplied BoxContainer with the neighbors of the base Box with the supplied BoxId.
Parameters:
base_box_id
neighbors
References begin(), end(), find(), and SAMRAI::hier::BoxContainer::insert().
void SAMRAI::hier::BoxNeighborhoodCollection::getPeriodicNeighbors (BoxContainer & result) const
Place any periodic neighbors from each neighborhood into the supplied BoxContainer.
Parameters:
result
References begin(), end(), SAMRAI::hier::BoxContainer::insert(), and SAMRAI::hier::Box::isPeriodicImage().
void SAMRAI::hier::BoxNeighborhoodCollection::putToIntBuffer (std::vector< int > & send_mesg, const tbox::Dimension & dim, int buff_init) const
Load an integer communication buffer with the data from this object.
Parameters:
send_mesg The integer communication buffer
dim
buff_init Initializer for newly allocated buffer data.
References begin(), SAMRAI::hier::Box::commBufferSize(), SAMRAI::hier::BoxId::commBufferSize(), end(), numBoxNeighborhoods(), numNeighbors(), sumNumNeighbors(), and TBOX_ASSERT.
void SAMRAI::hier::BoxNeighborhoodCollection::getFromIntBuffer (const std::vector< int > & recv_mesg, const std::vector< int > & proc_offset, const tbox::Dimension & dim, int num_proc, int rank)
Populate object based on information contained in an integer communication buffer.
Parameters:
recv_mesg The integer communication buffer
proc_offset Offset of beginning of message stream in recv_mesg for each process.
dim
num_proc
rank
References SAMRAI::hier::Box::commBufferSize(), SAMRAI::hier::BoxId::commBufferSize(), SAMRAI::hier::Box::getFromIntBuffer(), SAMRAI::hier::BoxId::getFromIntBuffer(), and insert().
void SAMRAI::hier::BoxNeighborhoodCollection::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Writes the neighborhood information to the supplied restart database.
Parameters:
restart_db
References begin(), end(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::Box::getLocalId(), SAMRAI::hier::BoxId::getLocalId(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::hier::Box::getPeriodicId(), SAMRAI::hier::BoxId::getPeriodicId(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::LocalId::getValue(), SAMRAI::tbox::Utilities::intToString(), numBoxNeighborhoods(), numNeighbors(), SAMRAI::tbox::Utilities::patchToString(), and SAMRAI::tbox::Utilities::processorToString().
Referenced by SAMRAI::hier::Connector::putToRestart().
void SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart (tbox::Database & restart_db)
Constructs the neighborhoods from the supplied restart database.
Parameters:
restart_db
References SAMRAI::tbox::Database::getDatabase(), SAMRAI::tbox::Database::getInteger(), SAMRAI::tbox::Database::getIntegerVector(), SAMRAI::hier::BoxId::getLocalId(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::hier::BoxId::getPeriodicId(), SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::LocalId::getValue(), insert(), SAMRAI::tbox::Utilities::intToString(), SAMRAI::tbox::Utilities::patchToString(), SAMRAI::tbox::Utilities::processorToString(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::setId(), and TBOX_ERROR.
Friends And Related Function Documentation
friend class Iterator [friend]
Referenced by begin(), end(), find(), and insert().
friend class ConstIterator [friend]
Referenced by begin(), end(), and find().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxNeighborhoodCollection.h
source/SAMRAI/hier/BoxNeighborhoodCollection.C