SAMRAI: SAMRAI::tbox::Dimension Class Reference
SAMRAI::tbox::Dimension Class Reference
#include <source/SAMRAI/tbox/Dimension.h>
Public Types
typedef unsigned short int dir_t
Primitive type for direction or dimension.
Public Member Functions
Dimension (const unsigned short &dim)
Dimension (const Dimension &dimension)
bool operator== (const Dimension &rhs) const
bool operator!= (const Dimension &rhs) const
bool operator> (const Dimension &rhs) const
bool operator>= (const Dimension &rhs) const
bool operator< (const Dimension &rhs) const
bool operator<= (const Dimension &rhs) const
unsigned short getValue () const
Static Public Member Functions
static const Dimension & getMaxDimension ()
Friends
std::ostream & operator<< (std::ostream &s, const Dimension &rhs)
Detailed Description
Class Dimension is used to represent the dimension of a SAMRAI object.
The maximum dimension is set at compile time using a flag to the configure script. This is used to allocate arrays in some lower level classes such as IntVector. If dynamic memory allocation is used the performance impact is significant; a maximum dimension allows for stack based memory allocation in performance critical classes at the expense of wasting storage for objects with dimension less than the maximum dimension.
A class is used rather than a simple short or integer to provide enhanced type safety.
Member Typedef Documentation
typedef unsigned short int SAMRAI::tbox::Dimension::dir_t
Primitive type for direction or dimension.
Constructor & Destructor Documentation
SAMRAI::tbox::Dimension::Dimension (const unsigned short & dim) [explicit]
Constructor for Dimension, object is built using the specified dimension
Note that the constructor is "explicit" thus making automatic type conversions from integers impossible. This is intentionally to avoid unintended conversions.
Precondition:
(dim > 0) && (dim <= SAMRAI::MAX_DIM_VAL)
References TBOX_DIM_ASSERT.
SAMRAI::tbox::Dimension::Dimension (const Dimension & dimension)
Construct a dimension equal to the argument.
Member Function Documentation
bool SAMRAI::tbox::Dimension::operator== (const Dimension & rhs) const [inline]
Equality operator.
bool SAMRAI::tbox::Dimension::operator!= (const Dimension & rhs) const [inline]
Inequality operator.
bool SAMRAI::tbox::Dimension::operator> (const Dimension & rhs) const [inline]
Greater than operator.
bool SAMRAI::tbox::Dimension::operator>= (const Dimension & rhs) const [inline]
Greater than or equal operator.
bool SAMRAI::tbox::Dimension::operator< (const Dimension & rhs) const [inline]
Less than operator.
bool SAMRAI::tbox::Dimension::operator<= (const Dimension & rhs) const [inline]
Less than or equal operator.
unsigned short SAMRAI::tbox::Dimension::getValue () const [inline]
Returns the dimension of the Dimension as an unsigned short.
The method is provided to allow sizing of arrays based on the dimension and for iteration. In general this should not be used for comparisons, the Dimension comparison operations are better suited for that purpose.
Referenced by SAMRAI::math::PatchSideDataOpsInteger::abs(), SAMRAI::math::PatchSideDataNormOpsComplex::abs(), SAMRAI::math::PatchFaceDataOpsInteger::abs(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchFaceDataNormOpsComplex::abs(), SAMRAI::math::PatchEdgeDataOpsInteger::abs(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchEdgeDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::pdat::ArrayDataIterator::ArrayDataIterator(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::axpy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::hier::BoundaryBox::BoundaryBox(), SAMRAI::hier::BoundaryLookupTable::BoundaryLookupTable(), SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::hier::BoxLevel::cacheGlobalReducedData(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::calculateOverlap(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::calculateOverlap(), SAMRAI::hier::IntVector::ceilingDivide(), SAMRAI::solv::CellPoissonFACSolver::CellPoissonFACSolver(), SAMRAI::hier::BaseGridGeometry::chopDomain(), SAMRAI::hier::Box::coalesceWith(), SAMRAI::hier::Index::coarsen(), SAMRAI::hier::Box::coarsen(), SAMRAI::hier::Box::commBufferSize(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::hier::BaseGridGeometry::computeBoundaryBoxesOnLevel(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::Box::contains(), SAMRAI::pdat::SideData< TYPE >::copy(), SAMRAI::pdat::OutersideData< TYPE >::copy(), SAMRAI::pdat::OuterfaceData< TYPE >::copy(), SAMRAI::pdat::FaceData< TYPE >::copy(), SAMRAI::pdat::EdgeData< TYPE >::copy(), SAMRAI::pdat::SideData< TYPE >::copy2(), SAMRAI::pdat::OutersideData< TYPE >::copy2(), SAMRAI::pdat::OuterfaceData< TYPE >::copy2(), SAMRAI::pdat::FaceData< TYPE >::copy2(), SAMRAI::pdat::EdgeData< TYPE >::copy2(), SAMRAI::math::PatchSideDataOpsReal< TYPE >::copyData(), SAMRAI::math::PatchSideDataOpsInteger::copyData(), SAMRAI::math::PatchSideDataOpsComplex::copyData(), SAMRAI::math::PatchFaceDataOpsInteger::copyData(), SAMRAI::math::PatchFaceDataOpsComplex::copyData(), SAMRAI::math::PatchEdgeDataOpsInteger::copyData(), SAMRAI::math::PatchEdgeDataOpsComplex::copyData(), SAMRAI::pdat::SideData< TYPE >::copyDepth(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth(), SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth(), SAMRAI::pdat::FaceData< TYPE >::copyDepth(), SAMRAI::pdat::EdgeData< TYPE >::copyDepth(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth2(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth2(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth2(), SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth2(), SAMRAI::pdat::SideData< TYPE >::copyOnBox(), SAMRAI::pdat::FaceData< TYPE >::copyOnBox(), SAMRAI::pdat::EdgeData< TYPE >::copyOnBox(), SAMRAI::tbox::DatabaseBox::DatabaseBox(), SAMRAI::hier::Box::DatabaseBox_from_Box(), SAMRAI::solv::CellPoissonFACSolver::deallocateSolverState(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::divide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::math::PatchSideDataNormOpsComplex::dot(), SAMRAI::math::PatchFaceDataNormOpsComplex::dot(), SAMRAI::math::PatchEdgeDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::pdat::EdgeData< TYPE >::EdgeData(), SAMRAI::pdat::EdgeIndex::EdgeIndex(), SAMRAI::hier::Box::empty(), SAMRAI::pdat::FaceData< TYPE >::FaceData(), SAMRAI::pdat::FaceIndex::FaceIndex(), SAMRAI::pdat::FaceOverlap::FaceOverlap(), SAMRAI::pdat::SideData< TYPE >::fill(), SAMRAI::pdat::OutersideData< TYPE >::fill(), SAMRAI::pdat::OuternodeData< TYPE >::fill(), SAMRAI::pdat::OuterfaceData< TYPE >::fill(), SAMRAI::pdat::OuteredgeData< TYPE >::fill(), SAMRAI::pdat::FaceData< TYPE >::fill(), SAMRAI::pdat::EdgeData< TYPE >::fill(), SAMRAI::pdat::ArrayData< TYPE >::fill(), SAMRAI::pdat::SideData< TYPE >::fillAll(), SAMRAI::pdat::OutersideData< TYPE >::fillAll(), SAMRAI::pdat::OuternodeData< TYPE >::fillAll(), SAMRAI::pdat::OuterfaceData< TYPE >::fillAll(), SAMRAI::pdat::OuteredgeData< TYPE >::fillAll(), SAMRAI::pdat::FaceData< TYPE >::fillAll(), SAMRAI::pdat::EdgeData< TYPE >::fillAll(), SAMRAI::hier::BoxUtilities::findBadCutPointsForBorderAndDirection(), SAMRAI::hier::SingularityFinder::findSingularities(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::PatchGeometry::getBoundaryFillBox(), SAMRAI::hier::BoundaryBox::getBoundaryOrientation(), SAMRAI::hier::AssumedPartitionBox::getBox(), SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), SAMRAI::solv::LocationIndexRobinBcCoefs::getCoefficients(), SAMRAI::pdat::OuternodeData< TYPE >::getDataBox(), SAMRAI::pdat::SideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OutersideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuternodeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuterfaceData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuteredgeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), SAMRAI::pdat::FaceData< TYPE >::getDataStreamSize(), SAMRAI::pdat::EdgeData< TYPE >::getDataStreamSize(), SAMRAI::hier::PatchGeometry::getEdgeBoundaries(), SAMRAI::hier::Box::getEmptyBox(), SAMRAI::hier::PatchGeometry::getFaceBoundaries(), SAMRAI::mesh::TileClustering::getFromInput(), SAMRAI::mesh::BergerRigoutsos::getFromInput(), SAMRAI::hier::Box::getFromIntBuffer(), SAMRAI::hier::Box::getFromMessageStream(), SAMRAI::pdat::SideData< TYPE >::getFromRestart(), SAMRAI::pdat::OutersideData< TYPE >::getFromRestart(), SAMRAI::pdat::OuternodeData< TYPE >::getFromRestart(), SAMRAI::pdat::OuterfaceData< TYPE >::getFromRestart(), SAMRAI::pdat::OuteredgeData< TYPE >::getFromRestart(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getFromRestart(), SAMRAI::pdat::FaceData< TYPE >::getFromRestart(), SAMRAI::pdat::EdgeData< TYPE >::getFromRestart(), SAMRAI::hier::PatchData::getFromRestart(), SAMRAI::hier::IntVector::getFromRestart(), SAMRAI::hier::BoundaryLookupTable::getLookupTable(), SAMRAI::hier::PatchDescriptor::getMaxGhostWidth(), SAMRAI::hier::Index::getMaxIndex(), SAMRAI::hier::Index::getMinIndex(), SAMRAI::hier::PatchGeometry::getNodeBoundaries(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::Index::getOneIndex(), SAMRAI::hier::BaseGridGeometry::getPeriodicShift(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::hier::Transformation::getReverseRotationIdentifier(), SAMRAI::hier::Transformation::getRotationIdentifier(), SAMRAI::pdat::SideData< TYPE >::getSizeOfData(), SAMRAI::pdat::OutersideData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuternodeData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuterfaceData< TYPE >::getSizeOfData(), SAMRAI::pdat::OuteredgeData< TYPE >::getSizeOfData(), SAMRAI::pdat::FaceData< TYPE >::getSizeOfData(), SAMRAI::pdat::EdgeData< TYPE >::getSizeOfData(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), SAMRAI::hier::Box::getUniverse(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Index::getZeroIndex(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), SAMRAI::solv::CellPoissonFACSolver::initializeSolverState(), SAMRAI::math::PatchSideDataNormOpsComplex::integral(), SAMRAI::math::PatchFaceDataNormOpsComplex::integral(), SAMRAI::math::PatchEdgeDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::hier::Box::intersects(), SAMRAI::hier::IntVector::IntVector(), SAMRAI::math::PatchSideDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::PatchSideDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::solv::LocationIndexRobinBcCoefs::LocationIndexRobinBcCoefs(), SAMRAI::hier::Box::longestDirection(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::hier::IntVector::max(), SAMRAI::math::PatchSideDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchFaceDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::hier::IntVector::min(), SAMRAI::hier::Index::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::multiply(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::pdat::NodeIndex::NodeIndex(), SAMRAI::math::PatchSideDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsComplex::numberOfEntries(), SAMRAI::math::PatchFaceDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchFaceDataNormOpsComplex::numberOfEntries(), SAMRAI::math::PatchEdgeDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsComplex::numberOfEntries(), SAMRAI::hier::IntVector::operator!=(), SAMRAI::pdat::OuteredgeData< TYPE >::operator()(), SAMRAI::hier::PatchGeometry::TwoDimBool::operator()(), SAMRAI::hier::IntVector::operator*=(), SAMRAI::pdat::SideIterator::operator++(), SAMRAI::pdat::NodeIterator::operator++(), SAMRAI::pdat::FaceIterator::operator++(), SAMRAI::pdat::EdgeIterator::operator++(), SAMRAI::pdat::CellIterator::operator++(), SAMRAI::hier::IntVector::operator+=(), SAMRAI::hier::IntVector::operator-(), SAMRAI::hier::IntVector::operator-=(), SAMRAI::hier::IntVector::operator/=(), SAMRAI::hier::IntVector::operator<(), SAMRAI::tbox::operator<<(), SAMRAI::hier::operator<<(), SAMRAI::hier::IntVector::operator<=(), SAMRAI::solv::LocationIndexRobinBcCoefs::operator=(), SAMRAI::hier::PatchBoundaries::operator=(), SAMRAI::hier::IntVector::operator=(), SAMRAI::hier::IntVector::operator==(), SAMRAI::hier::IntVector::operator>(), SAMRAI::hier::IntVector::operator>=(), SAMRAI::hier::operator>>(), SAMRAI::pdat::OuteredgeData< TYPE >::OuteredgeData(), SAMRAI::pdat::OuterfaceData< TYPE >::OuterfaceData(), SAMRAI::pdat::OutersideData< TYPE >::OutersideData(), SAMRAI::pdat::SideData< TYPE >::packStream(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::OuterfaceData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream(), SAMRAI::pdat::FaceData< TYPE >::packStream(), SAMRAI::pdat::EdgeData< TYPE >::packStream(), SAMRAI::hier::PatchBoundaries::PatchBoundaries(), SAMRAI::hier::PatchGeometry::PatchGeometry(), SAMRAI::hier::PatchLevel::PatchLevel(), SAMRAI::pdat::SideData< TYPE >::print(), SAMRAI::pdat::OutersideData< TYPE >::print(), SAMRAI::pdat::OuternodeData< TYPE >::print(), SAMRAI::pdat::OuterfaceData< TYPE >::print(), SAMRAI::pdat::OuteredgeData< TYPE >::print(), SAMRAI::pdat::FaceData< TYPE >::print(), SAMRAI::pdat::EdgeData< TYPE >::print(), SAMRAI::hier::BoxLevelStatistics::printBoxStats(), SAMRAI::hier::PatchGeometry::printClassData(), SAMRAI::hier::CoarseFineBoundary::printClassData(), SAMRAI::geom::CartesianPatchGeometry::printClassData(), SAMRAI::geom::CartesianGridGeometry::printClassData(), SAMRAI::hier::BoxTree::printStatistics(), SAMRAI::hier::Box::putToIntBuffer(), SAMRAI::hier::Box::putToMessageStream(), SAMRAI::pdat::SideData< TYPE >::putToRestart(), SAMRAI::pdat::OutersideData< TYPE >::putToRestart(), SAMRAI::pdat::OuternodeData< TYPE >::putToRestart(), SAMRAI::pdat::OuterfaceData< TYPE >::putToRestart(), SAMRAI::pdat::OuteredgeData< TYPE >::putToRestart(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::putToRestart(), SAMRAI::pdat::FaceData< TYPE >::putToRestart(), SAMRAI::pdat::EdgeData< TYPE >::putToRestart(), SAMRAI::hier::PatchHierarchy::putToRestart(), SAMRAI::hier::PatchData::putToRestart(), SAMRAI::hier::IntVector::putToRestart(), SAMRAI::hier::BoxLevel::putToRestart(), SAMRAI::hier::BaseGridGeometry::putToRestart(), SAMRAI::geom::CartesianGridGeometry::putToRestart(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::hier::Box::refine(), SAMRAI::appu::VisItDataWriter::registerDerivedPlotQuantity(), SAMRAI::hier::BaseGridGeometry::registerNeighbors(), SAMRAI::appu::VisItDataWriter::registerNodeCoordinates(), SAMRAI::appu::VisItDataWriter::registerSingleNodeCoordinate(), SAMRAI::hier::BoxContainer::removeIntersections(), SAMRAI::hier::BoxTree::resetStatistics(), SAMRAI::hier::BoxContainer::rotate(), SAMRAI::hier::Transformation::rotateIndex(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::scale(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::hier::PatchGeometry::TwoDimBool::setAll(), SAMRAI::solv::LocationIndexRobinBcCoefs::setBcCoefs(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBoundaries(), SAMRAI::hier::PatchGeometry::setBoundaryBoxesOnPatch(), SAMRAI::solv::LocationIndexRobinBcCoefs::setBoundarySlope(), SAMRAI::solv::LocationIndexRobinBcCoefs::setBoundaryValue(), SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel(), SAMRAI::hier::PatchGeometry::setCodimensionBoundaries(), SAMRAI::tbox::DatabaseBox::setDim(), SAMRAI::geom::CartesianGridGeometry::setGeometryData(), SAMRAI::hier::BaseGridGeometry::setGeometryDataOnPatch(), SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch(), SAMRAI::hier::BaseGridGeometry::setGeometryOnPatches(), SAMRAI::hier::PatchDescriptor::setMinGhostWidth(), SAMRAI::mesh::MultiblockGriddingTagger::setPhysicalBoundaryConditions(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::solv::LocationIndexRobinBcCoefs::setRawCoefficients(), SAMRAI::hier::PatchLevel::setRefinedPatchLevel(), SAMRAI::pdat::SideData< TYPE >::SideData(), SAMRAI::pdat::SideOverlap::SideOverlap(), SAMRAI::hier::SingularityFinder::SingularityFinder(), SAMRAI::hier::Box::size(), SAMRAI::hier::IntVector::sortIntVector(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::pdat::OuternodeData< TYPE >::sum(), SAMRAI::pdat::OuteredgeData< TYPE >::sum(), SAMRAI::math::PatchSideDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchFaceDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchEdgeDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::pdat::SideIndex::toCell(), SAMRAI::pdat::FaceIndex::toCell(), SAMRAI::pdat::EdgeIndex::toCell(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::pdat::EdgeGeometry::transform(), SAMRAI::pdat::CellGeometry::transform(), SAMRAI::hier::PatchGeometry::TwoDimBool::TwoDimBool(), SAMRAI::pdat::SideData< TYPE >::unpackStream(), SAMRAI::pdat::OutersideData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStream(), SAMRAI::pdat::OuterfaceData< TYPE >::unpackStream(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::unpackStream(), SAMRAI::pdat::FaceData< TYPE >::unpackStream(), SAMRAI::pdat::EdgeData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStreamAndSum(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum(), SAMRAI::math::PatchSideDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume(), and SAMRAI::solv::CellPoissonFACSolver::~CellPoissonFACSolver().
static const Dimension& SAMRAI::tbox::Dimension::getMaxDimension () [inline, static]
Returns the maximum dimension for the currently compiled library as a Dimension object.
When the SAMRAI library is compiled a maximum dimension allowed is specified (the default is 3). This method is typically used to allocate arrays.
Referenced by SAMRAI::hier::Index::Index().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & s, const Dimension & rhs) [friend]
Output operator for debugging and error messages.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Dimension.h
source/SAMRAI/tbox/Dimension.C