SAMRAI: SAMRAI::tbox::MessageStream Class Reference
SAMRAI::tbox::MessageStream Class Reference
Class to provide buffers for communication of data.
#include <source/SAMRAI/tbox/MessageStream.h>
Public Types
enum StreamMode { Read, Write }
Enumeration to identify if a buffer is being used to read or write data.
Public Member Functions
MessageStream (const size_t num_bytes, const StreamMode mode, const void *data_to_read=0, bool deep_copy=true)
Create a message stream of the specified size and mode.
MessageStream ()
Default constructor creates a message stream with a buffer that automatically grows as needed, for writing.
~MessageStream ()
const void * getBufferStart () const
Return a pointer to the start of the message buffer.
size_t getCurrentSize () const
Return the current size of the buffer in bytes.
void growBufferAsNeeded ()
Tell a Write-mode stream to allocate more buffer as needed for data.
bool endOfData () const
Whether a Read-mode MessageStream has reached the end of its data.
template<typename DATA_TYPE >
MessageStream & operator<< (const DATA_TYPE &data)
Pack a single data item into message stream.
template<typename DATA_TYPE >
void pack (const DATA_TYPE *data, size_t size=1)
Pack an array of data items into message stream.
void pack (const MessageStream &other)
Pack content of another data stream into this one.
template<typename DATA_TYPE >
MessageStream & operator>> (DATA_TYPE &data)
Unpack a single data item from message stream.
template<typename DATA_TYPE >
void unpack (DATA_TYPE *data, size_t size=1)
Unpack an array of data items from message stream.
void printClassData (std::ostream &os) const
Print out internal object data.
bool readMode () const
Returns true if stream is in read mode.
bool writeMode () const
Returns true if stream is in write mode.
bool growAsNeeded () const
Returns true if the buffer is grown as needed in Write mode.
bool canCopyIn (size_t num_bytes) const
Returns true if num_bytes can be copied into the stream.
bool canCopyOut (size_t num_bytes) const
Returns true if num_bytes can be copied out of the stream.
Static Public Member Functions
template<typename DATA_TYPE >
static size_t getSizeof (size_t num_items=1)
Static method to get amount of message stream space needed to communicate data type indicated by template parameter.
Detailed Description
Class to provide buffers for communication of data.
MessageStream provides a message buffer that can hold data of any type. It is used by communication routines in the Schedule class.
TODO: Because this class supports both read and write modes, it has extra data and methods that don't make sense, depending on the mode. It should be rewritten as two classes, like std::cin and std::cout are. BTNG.
See also:
tbox::Schedule
Member Enumeration Documentation
enum SAMRAI::tbox::MessageStream::StreamMode
Enumeration to identify if a buffer is being used to read or write data.
Enumerator:
Read
Write
Constructor & Destructor Documentation
SAMRAI::tbox::MessageStream::MessageStream (const size_t num_bytes, const StreamMode mode, const void * data_to_read = 0, bool deep_copy = true)
Create a message stream of the specified size and mode.
Parameters:
[in] num_bytes Number of bytes in the stream.
[in] mode MessageStream::Read or MessageStream::Write.
[in] data_to_read Data for unpacking, should be num_bytes bytes long. This is used when mode == MessageStream::Read, ignored in write mode.
[in] deep_copy Whether to make deep copy of data_to_read. The default is to make a deep copy, which is safer but slower than a shallow (pointer) copy. This is used when mode == MessageStream::Read, ignored in write mode. In shallow copy mode, you cannot call growBufferAsNeeded().
Precondition:
num_bytes >= 0
mode != Read || data_to_read != 0
References Read, TBOX_ASSERT, and TBOX_ERROR.
SAMRAI::tbox::MessageStream::MessageStream ()
Default constructor creates a message stream with a buffer that automatically grows as needed, for writing.
SAMRAI::tbox::MessageStream::~MessageStream ()
Destructor for a message stream.
References Read.
Member Function Documentation
template<typename DATA_TYPE > static size_t SAMRAI::tbox::MessageStream::getSizeof (size_t num_items = 1) [inline, static]
Static method to get amount of message stream space needed to communicate data type indicated by template parameter.
IMPORTANT: All size information given to the message stream should be based on values returned by this method.
TODO: Implementation should be moved out of header? If we do this, Then we need to create another implementation file to include in this header. I don't think it's worth it. RDH
Returns:
The number of bytes for num_items of type DATA_TYPE.
Parameters:
[in] num_items
const void* SAMRAI::tbox::MessageStream::getBufferStart () const [inline]
Return a pointer to the start of the message buffer.
References Read.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and pack().
size_t SAMRAI::tbox::MessageStream::getCurrentSize () const [inline]
Return the current size of the buffer in bytes.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and pack().
void SAMRAI::tbox::MessageStream::growBufferAsNeeded () [inline]
Tell a Write-mode stream to allocate more buffer as needed for data.
It is an error to use this method for a Read-mode stream.
Precondition:
writeMode()
References TBOX_ASSERT, and writeMode().
bool SAMRAI::tbox::MessageStream::endOfData () const [inline]
Whether a Read-mode MessageStream has reached the end of its data.
Precondition:
readMode()
References readMode(), and TBOX_ASSERT.
template<typename DATA_TYPE > MessageStream& SAMRAI::tbox::MessageStream::operator<< (const DATA_TYPE & data) [inline]
Pack a single data item into message stream.
Parameters:
[in] data Single item of type DATA_TYPE to be copied into the stream.
Precondition:
writeMode()
References TBOX_ASSERT, and writeMode().
template<typename DATA_TYPE > void SAMRAI::tbox::MessageStream::pack (const DATA_TYPE * data, size_t size = 1) [inline]
Pack an array of data items into message stream.
Parameters:
[in] data Pointer to an array of data of type DATA_TYPE to be copied into the stream.
[in] size Number of items to pack.
Precondition:
writeMode()
References TBOX_ASSERT, and writeMode().
Referenced by SAMRAI::tbox::Statistic::packStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream(), SAMRAI::pdat::ArrayData< TYPE >::packStream(), and SAMRAI::hier::Box::putToMessageStream().
void SAMRAI::tbox::MessageStream::pack (const MessageStream & other) [inline]
Pack content of another data stream into this one.
Parameters:
[in] other The other data stream.
Precondition:
writeMode()
References getBufferStart(), getCurrentSize(), TBOX_ASSERT, and writeMode().
template<typename DATA_TYPE > MessageStream& SAMRAI::tbox::MessageStream::operator>> (DATA_TYPE & data) [inline]
Unpack a single data item from message stream.
Parameters:
[out] data Single item of type DATA_TYPE that will be copied from the stream.
Precondition:
readMode()
References readMode(), and TBOX_ASSERT.
template<typename DATA_TYPE > void SAMRAI::tbox::MessageStream::unpack (DATA_TYPE * data, size_t size = 1) [inline]
Unpack an array of data items from message stream.
Parameters:
[out] data Pointer to an array of data of type DATA_TYPE that will receive data copied from the stream.
[out] size Number of items that will be copied.
Precondition:
readMode()
References readMode(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::Box::getFromMessageStream(), SAMRAI::tbox::Statistic::unpackStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::unpackStream(), SAMRAI::pdat::ArrayData< TYPE >::unpackStream(), and SAMRAI::pdat::ArrayData< TYPE >::unpackStreamAndSum().
void SAMRAI::tbox::MessageStream::printClassData (std::ostream & os) const
Print out internal object data.
Parameters:
[out] os Output stream.
bool SAMRAI::tbox::MessageStream::readMode () const [inline]
Returns true if stream is in read mode.
References Read.
Referenced by endOfData(), operator>>(), and unpack().
bool SAMRAI::tbox::MessageStream::writeMode () const [inline]
Returns true if stream is in write mode.
References Write.
Referenced by growBufferAsNeeded(), operator<<(), and pack().
bool SAMRAI::tbox::MessageStream::growAsNeeded () const [inline]
Returns true if the buffer is grown as needed in Write mode.
bool SAMRAI::tbox::MessageStream::canCopyIn (size_t num_bytes) const [inline]
Returns true if num_bytes can be copied into the stream.
bool SAMRAI::tbox::MessageStream::canCopyOut (size_t num_bytes) const [inline]
Returns true if num_bytes can be copied out of the stream.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/MessageStream.h
source/SAMRAI/tbox/MessageStream.C