SAMRAI: SAMRAI::tbox::Statistic Class Reference
SAMRAI::tbox::Statistic Class Reference
#include <source/SAMRAI/tbox/Statistic.h>
Classes
struct PatchStat
struct PatchStatRecord
struct ProcStat
Public Member Functions
~Statistic ()
const std::string & getName () const
std::string getType () const
int getInstanceId () const
int getStatSequenceLength () const
void reset ()
void recordProcStat (double value, int seq_num=-1)
void recordPatchStat (int patch_num, double value, int seq_num)
bool canEstimateDataStreamSize ()
int getDataStreamSize ()
void packStream (MessageStream &stream)
void unpackStream (MessageStream &stream)
void printClassData (std::ostream &stream, int precision=12) const
void putToRestart (const boost::shared_ptr< Database > &restart_db) const
void getFromRestart (const boost::shared_ptr< Database > &restart_db)
Protected Member Functions
Statistic (const std::string &name, const std::string &stat_type, int instance_id)
const std::vector
< Statistic::ProcStat > & getProcStatSeqArray () const
const std::vector
< Statistic::PatchStat > & getPatchStatSeqArray () const
Friends
class Statistician
Detailed Description
Class Statistic defines a simple object that can be used to record information generated during the course of a simulation for post- processing later. Each statistic object is created by the singleton Statistian object and is defined by a name string identifier and is characterized by the sort of information it may record. Depending on how the object is created, it may record processor information (i.e., a separate value for each processor), or patch information (i.e., a separate value for each patch on each processor). An example of the former may be the total number of cells on each processor. An example of the second may be the number of cells on each patch. Each recorded data item may be any numerical value, but it will always be stored as a double for simplicity. The string identifier for a processor stat is "PROC_STAT" and the string identifier for a patch stat is "PATCH_STAT".
An example use of a Statistic to record the number of gridcells on each processor is as follows:
boost::shared_ptr<Statistic> stat_num_gridcells = Statistician::getStatistician()-> getStatistic("NumberGridcells", "PROC_STAT"); ... stat_num_gridcells->recordProcStat(num_cells_on_proc); ...
The type of the statistic restricts the way in which the statistic object may be used to record information. For a "processor" stat only the recordProcStat() functions can be used. For a "patch" stat only the recordPatchStat() functions can be used.
Typically, the information is recorded to generate a time sequence of values. But this need not be the case always. An optional time stamp may be provided for each value as it is recorded. In any case, the sequence order of the values is determined by the recording order.
Also, the Statistician class is used to manage Statistic objects. It provided a global point of access for creating and accessing statistic objects and supports post-processing statistic information in parallel.
In some cases, it may be desirable to record information for each level in a calculation; e.g., the number of cells on each processor on level zero, level 1, etc. In this case, one can cimply create a separate statistic object for each level.
See also:
tbox::Statistician
Constructor & Destructor Documentation
SAMRAI::tbox::Statistic::~Statistic ()
Virtual destructor destroys recorded object data.
References reset().
SAMRAI::tbox::Statistic::Statistic (const std::string & name, const std::string & stat_type, int instance_id) [protected]
The constructor for the Statistic class sets the name string and the statistic type for a statistic object.
Precondition:
!name.empty()
!stat_type.empty()
(stat_type == "PROC_STAT") || (stat_type = "PATCH_STAT")
instance_id > -1
References TBOX_ASSERT, and TBOX_ERROR.
Member Function Documentation
const std::string& SAMRAI::tbox::Statistic::getName (void) const [inline]
Return string name identifier for statistic object.
Referenced by printClassData(), and SAMRAI::mesh::GriddingAlgorithm::printStatistics().
std::string SAMRAI::tbox::Statistic::getType () const [inline]
Return string statistic type identifier for statistic object.
Referenced by printClassData(), recordPatchStat(), and recordProcStat().
int SAMRAI::tbox::Statistic::getInstanceId () const [inline]
Return integer instance identifier for statistic object.
Referenced by printClassData(), and SAMRAI::mesh::GriddingAlgorithm::printStatistics().
int SAMRAI::tbox::Statistic::getStatSequenceLength () const [inline]
Return integer length of list of statistic sequence records. This value is either the length of the processor statistic list or the patch statistic list, whichever corresponds to the statistic type.
Referenced by printClassData(), and SAMRAI::mesh::GriddingAlgorithm::printStatistics().
void SAMRAI::tbox::Statistic::reset () [inline]
Reset the state of the statistic information.
Referenced by ~Statistic().
void SAMRAI::tbox::Statistic::recordProcStat (double value, int seq_num = -1)
Record double processor statistic value. The optional sequence number argument identifies where in timestep sequence the value should be. If the sequence number is not specified, an internal counter will determine the appropriate sequence number.
Precondition:
getType() == "PROC_STAT"
References getType(), and TBOX_ERROR.
Referenced by getFromRestart(), and unpackStream().
void SAMRAI::tbox::Statistic::recordPatchStat (int patch_num, double value, int seq_num)
Record double patch statistic value. The patch number refers to the global patch number on a level. The sequence number argument identifies where in timestep sequence the value should be. The sequence number MUST be explicitly specified because the number of patches on each processor will generally be different at each sequence step.
Precondition:
getType() == "PATCH_STAT"
References getType(), SAMRAI::tbox::Statistic::PatchStatRecord::patch_id, TBOX_ERROR, and SAMRAI::tbox::Statistic::PatchStatRecord::value.
Referenced by getFromRestart(), and unpackStream().
bool SAMRAI::tbox::Statistic::canEstimateDataStreamSize () [inline]
Return true if size of stream required to pack all statistic data can be determined for all processors without exchanging any details of structure of statistic data. Otherwise, return false.
int SAMRAI::tbox::Statistic::getDataStreamSize ()
Return integer number of bytes needed to stream the statistic data. This is the amount needed by the stat transaction class.
void SAMRAI::tbox::Statistic::packStream (MessageStream & stream)
Pack contents of statistic data structure into message stream.
Precondition:
SAMRAI_MPI::getSAMRAIWorld().getRank() != 0
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::MessageStream::pack(), and TBOX_ERROR.
void SAMRAI::tbox::Statistic::unpackStream (MessageStream & stream)
Unpack contents of statistic data structure from message stream.
Precondition:
SAMRAI_MPI::getSAMRAIWorld().getRank() == 0
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), recordPatchStat(), recordProcStat(), TBOX_ERROR, and SAMRAI::tbox::MessageStream::unpack().
void SAMRAI::tbox::Statistic::printClassData (std::ostream & stream, int precision = 12) const
Print statistic data to given output stream. Floating point precision can be specified (default is 12).
Precondition:
precision > 0
References getInstanceId(), getName(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), getStatSequenceLength(), getType(), and TBOX_ASSERT.
void SAMRAI::tbox::Statistic::putToRestart (const boost::shared_ptr< Database > & restart_db) const
Write statistic data members to restart database. The restart_db pointer must be non-null.
Precondition:
restart_db
References TBOX_ASSERT.
void SAMRAI::tbox::Statistic::getFromRestart (const boost::shared_ptr< Database > & restart_db)
Read restarted times from restart database.
Precondition:
restart_db
References recordPatchStat(), recordProcStat(), TBOX_ASSERT, and TBOX_ERROR.
const std::vector<Statistic::ProcStat>& SAMRAI::tbox::Statistic::getProcStatSeqArray () const [inline, protected]
Return const reference to list of processor records.
const std::vector<Statistic::PatchStat>& SAMRAI::tbox::Statistic::getPatchStatSeqArray () const [inline, protected]
Return const reference to list of patch records.
Friends And Related Function Documentation
friend class Statistician [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Statistic.h
source/SAMRAI/tbox/Statistic.C