SAMRAI: SAMRAI::hier::PeriodicShiftCatalog Class Reference
SAMRAI::hier::PeriodicShiftCatalog Class Reference
Catalogs periodic shifts and assigns each one a unique PeriodicId.
#include <source/SAMRAI/hier/PeriodicShiftCatalog.h>
Public Member Functions
PeriodicShiftCatalog (const tbox::Dimension &dim)
Constructs uninitialized object.
~PeriodicShiftCatalog ()
const IntVector & shiftNumberToShiftDistance (const PeriodicId &shift_number) const
Return the shift distance corresponding to the given shift number.
PeriodicId shiftDistanceToShiftNumber (const IntVector &shift_distance) const
Return the shift number corresponding to the given shift distance.
int getInvalidShiftNumber () const
Return the "invalid" shift number.
const PeriodicId & getOppositeShiftNumber (const PeriodicId &shift_number) const
Return the shift number corresponding to the negative of the shift distance of the given shift number.
bool isPeriodic () const
Determine whether there is any periodicity.
int getNumberOfShifts () const
Return the number of possible shifts.
const PeriodicId & getZeroShiftNumber () const
Return the shift number corresponding to no shift.
void initializeShiftsByIndexDirections (const IntVector &shift_distance_along_index_directions)
Compute all possible shifts for periodicity along the index directions and initialize the shifts in the catalog.
Detailed Description
Catalogs periodic shifts and assigns each one a unique PeriodicId.
In a periodic domain, a Box location (or rather its images) can appear to be in many places. We define the "shift distance" as the IntVector distance in index space from the original grid location to the image.
This class catalogs all possible shifts for a periodic configuration and assigns an integer index to each shift. A shift can be referenced by a single PeriodicId rather than its IntVector distance.
TODO: Periodic shift definition and management should probably be be combined with multi-block relationships in the multi-block re-design.
Constructor & Destructor Documentation
SAMRAI::hier::PeriodicShiftCatalog::PeriodicShiftCatalog (const tbox::Dimension & dim) [explicit]
Constructs uninitialized object.
After construction, the object should be populated with periodic shifts, if any exist, using initializeShiftsByIndexDirections().
SAMRAI::hier::PeriodicShiftCatalog::~PeriodicShiftCatalog ()
Member Function Documentation
const IntVector& SAMRAI::hier::PeriodicShiftCatalog::shiftNumberToShiftDistance (const PeriodicId & shift_number) const [inline]
Return the shift distance corresponding to the given shift number.
Parameters:
[in] shift_number
Precondition:
shift_number.isValid()
shift_number.getPeriodicValue() < getNumberOfShifts()
References SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::Box::Box(), and SAMRAI::hier::Box::initialize().
PeriodicId SAMRAI::hier::PeriodicShiftCatalog::shiftDistanceToShiftNumber (const IntVector & shift_distance) const [inline]
Return the shift number corresponding to the given shift distance.
The shift distance must correspond to an actual distance in the catalog. Otherwise, invalidShiftNumber() is returned.
Parameters:
[in] shift_distance
int SAMRAI::hier::PeriodicShiftCatalog::getInvalidShiftNumber () const [inline]
Return the "invalid" shift number.
const PeriodicId& SAMRAI::hier::PeriodicShiftCatalog::getOppositeShiftNumber (const PeriodicId & shift_number) const [inline]
Return the shift number corresponding to the negative of the shift distance of the given shift number.
Parameters:
[in] shift_number
Precondition:
shift_number.isValid()
shift_number.getPeriodicValue() < getNumberOfShifts()
References SAMRAI::hier::PeriodicId::getPeriodicValue(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doLocalTransposeWork(), and SAMRAI::hier::Connector::reorderRelationshipsByHead().
bool SAMRAI::hier::PeriodicShiftCatalog::isPeriodic () const [inline]
Determine whether there is any periodicity.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), and SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships().
int SAMRAI::hier::PeriodicShiftCatalog::getNumberOfShifts () const [inline]
Return the number of possible shifts.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::Box::Box(), and SAMRAI::hier::Box::initialize().
const PeriodicId& SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber () const [inline]
Return the shift number corresponding to no shift.
References SAMRAI::hier::PeriodicId::zero().
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::hier::Box::Box(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Box::initialize(), SAMRAI::hier::Connector::reorderRelationshipsByHead(), SAMRAI::hier::BoxContainer::separatePeriodicImages(), and SAMRAI::hier::BoxContainer::unshiftPeriodicImageBoxes().
void SAMRAI::hier::PeriodicShiftCatalog::initializeShiftsByIndexDirections (const IntVector & shift_distance_along_index_directions)
Compute all possible shifts for periodicity along the index directions and initialize the shifts in the catalog.
The shift_distances should be non-negative integers representing the minimum distance (in reference index space) in each direction that a domain has to be shifted before it repeats. In non-periodic directions, use the value of zero.
Periodic shifts along index directions is the only periodic shifting that SAMRAI fully supports. There are 3 possible shifts per direction: forward, backward and no-shift. In D-dimension, there can be up to 3^D images of the same location, including diagonal shifts that results from combining multiple shifts along different directions.
This method must only be called once for each dimension (indicated by the dimension of shift_distances).
Parameters:
[in] shift_distance_along_index_directions The periodic shift distance in each index direction.
References SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), and SAMRAI::hier::IntVector::getZero().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PeriodicShiftCatalog.h
source/SAMRAI/hier/PeriodicShiftCatalog.C