SAMRAI: SAMRAI::algs::ImplicitIntegrator Class Reference
SAMRAI::algs::ImplicitIntegrator Class Reference
Manage implicit time integration over an AMR patch hierarchy.
#include <source/SAMRAI/algs/ImplicitIntegrator.h>
Public Member Functions
ImplicitIntegrator (const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db, ImplicitEquationStrategy *implicit_equations, solv::NonlinearSolverStrategy *nonlinear_solver, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy)
virtual ~ImplicitIntegrator ()
void initialize ()
int advanceSolution (const double dt, const bool first_step)
Integrate entire patch hierarchy through the specified time increment.
double getNextDt (const bool good_solution, const int solver_retcode)
bool checkNewSolution (const int solver_retcode) const
double updateSolution ()
double getInitialTime () const
double getFinalTime () const
double getCurrentTime () const
double getCurrentDt () const
int getIntegratorStep () const
int getMaxIntegratorSteps () const
bool stepsRemaining () const
virtual void printClassData (std::ostream &os) const
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
const std::string & getObjectName () const
Detailed Description
Manage implicit time integration over an AMR patch hierarchy.
Class ImplicitIntegrator manages implicit time integration over an AMR patch hierarchy. It maintains references to ImplicitEquationStrategy and solv::NonlinearSolverStrategy objects, which provide operations describing the implicit equations and solving the problem at each time step, respectively. When a time step is performed, data on all levels is integrated through the same time increment.
Input Parameters
Definitions:
initial_time initial simulation time.
final_time final simulation time.
max_integrator_steps maximum number of timesteps performed on the coarsest hierarchy level during the simulation.
All input data items described above, except for initial_time, may be overridden by new input values when continuing from restart.
Details:
parameter
type
default
range
opt/req
behavior on restart
initial_time
double
none
>=0
req
May not be modified by input db on restart
final_time
double
none
final_time >= initial_time
req
Parameter read from restart db may be overridden by input db
max_integrator_steps
int
none
>=0
req
Parameter read from restart db may be overridden by input db
A sample input file entry might look like:
 initial_time = 0.0
 final_time   = 1.0
 max_integrator_steps = 100
See also:
ImplicitEquationStrategy
solv::NonlinearSolverStrategy
Constructor & Destructor Documentation
SAMRAI::algs::ImplicitIntegrator::ImplicitIntegrator (const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db, ImplicitEquationStrategy * implicit_equations, solv::NonlinearSolverStrategy * nonlinear_solver, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy)
The constructor for ImplicitIntegrator initializes the default state of the integrator. The integrator is configured with the concrete strategy objects in the argument list that provide operations related to the nonlinear solver and implicit equations to solve. Data members are initialized from the input and restart databases.
Note that no vectors are created in the constructor. Vectors are created and the nonlinear solver is initialized in the initialize() member function.
Precondition:
!object_name.empty()
implicit_equations != 0
nonlinear_solver != 0
hierarchy
References SAMRAI::algs::ImplicitEquationStrategy::getInitialDt(), SAMRAI::tbox::RestartManager::getManager(), and TBOX_ASSERT.
SAMRAI::algs::ImplicitIntegrator::~ImplicitIntegrator () [virtual]
Empty destructor for ImplicitIntegrator
Member Function Documentation
void SAMRAI::algs::ImplicitIntegrator::initialize ()
Initialize state of time integrator. This includes creating solution vector and initializing solver components.
References SAMRAI::solv::NonlinearSolverStrategy::initialize(), SAMRAI::algs::ImplicitEquationStrategy::setupSolutionVector(), and TBOX_ERROR.
int SAMRAI::algs::ImplicitIntegrator::advanceSolution (const double dt, const bool first_step)
Integrate entire patch hierarchy through the specified time increment.
Integrate entire patch hierarchy through the specified time increment. The time advance assumes the use of a nonlinear solver to implicitly integrate the discrete equations. The integer return value is the return code generated by the particular solver package in use. It is the user's responsibility to interpret this code in a manner consistent with the solver she is using.
The boolean first_step argument is true when this is the very first call to the advance function or if the call occurs immediately after the hierarchy has changed due to regridding. Otherwise it is false. Note that, when the argument is true, the use of extrapolation to construct the initial guess for the advanced solution may not be possible.
Parameters:
dt Time step size
first_step Whether this is the first step after grid change
Returns:
value is the return code generated by the particular solver package in use
References SAMRAI::solv::NonlinearSolverStrategy::initialize(), SAMRAI::algs::ImplicitEquationStrategy::setInitialGuess(), SAMRAI::solv::NonlinearSolverStrategy::solve(), and stepsRemaining().
double SAMRAI::algs::ImplicitIntegrator::getNextDt (const bool good_solution, const int solver_retcode)
Return time increment for next solution advance. Timestep selection is generally based on whether the nonlinear solution iteration converged and, if so, whether the solution meets some user-defined criteria. This routine assumes that, before it is called, the routine checkNewSolution() was called. The boolean argument is the return value from that call. The integer argument is the return code generated by the nonlinear solver package that computed the solution.
References SAMRAI::algs::ImplicitEquationStrategy::getNextDt(), and MPI_MIN.
bool SAMRAI::algs::ImplicitIntegrator::checkNewSolution (const int solver_retcode) const
Check time advanced solution to determine whether it is acceptable. Return true if the solution is acceptable; return false otherwise. The integer argument is the return code generated by the call to the nonlinear solver "solve" routine. The meaning of this value depends on the particular nonlinear solver in use and must be intepreted properly by the user-supplied solution checking routine.
References SAMRAI::algs::ImplicitEquationStrategy::checkNewSolution(), and MPI_MIN.
double SAMRAI::algs::ImplicitIntegrator::updateSolution ()
Update solution (e.g., reset pointers for solution data, update dependent variables, etc.) after time advance. It is assumed that when this routine is invoked, an acceptable new solution has been computed. The double return value is the simulation time corresponding to the advanced solution.
References SAMRAI::algs::ImplicitEquationStrategy::updateSolution().
double SAMRAI::algs::ImplicitIntegrator::getInitialTime () const [inline]
Return initial integration time.
double SAMRAI::algs::ImplicitIntegrator::getFinalTime () const [inline]
Return final integration time.
double SAMRAI::algs::ImplicitIntegrator::getCurrentTime () const [inline]
Return current integration time.
double SAMRAI::algs::ImplicitIntegrator::getCurrentDt () const [inline]
Return current timestep.
int SAMRAI::algs::ImplicitIntegrator::getIntegratorStep () const [inline]
Return current integration step number.
int SAMRAI::algs::ImplicitIntegrator::getMaxIntegratorSteps () const [inline]
Return maximum number of integration steps.
bool SAMRAI::algs::ImplicitIntegrator::stepsRemaining () const [inline]
Return true if the number of integration steps performed by the integrator has not reached the specified maximum; return false otherwise.
Referenced by advanceSolution().
void SAMRAI::algs::ImplicitIntegrator::printClassData (std::ostream & os) const [virtual]
Print out all members of integrator instance to given output stream.
void SAMRAI::algs::ImplicitIntegrator::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Write out state of object to given restart database.
Precondition:
restart_db
References TBOX_ASSERT.
const std::string& SAMRAI::algs::ImplicitIntegrator::getObjectName () const [inline]
Returns the object name.
The documentation for this class was generated from the following files:
source/SAMRAI/algs/ImplicitIntegrator.h
source/SAMRAI/algs/ImplicitIntegrator.C