SAMRAI: SAMRAI::tbox::Array< TYPE > Class Template Reference
SAMRAI::tbox::Array< TYPE > Class Template Reference
#include <source/SAMRAI/tbox/Array.h>
Classes
class DoNotInitialize
Public Member Functions
Array ()
Array (const int n, const TYPE &default_value=TYPE())
Array (const int n, const typename Array::DoNotInitialize &do_not_initialize_flag)
Array (const Array &rhs)
~Array ()
Array & operator= (const Array &rhs)
TYPE & operator[] (const int i)
const TYPE & operator[] (const int i) const
bool isNull () const
bool empty () const
void setNull ()
void clear ()
TYPE * getPointer (const int i=0)
const TYPE * getPointer (const int i=0) const
int getSize () const
int size () const
void resizeArray (const int n, const TYPE &default_value=TYPE())
void push_back (const TYPE &value)
const TYPE & back ()
void erase (const int position)
template<>
Array (const int n, const bool &default_value)
template<>
Array (const int n, const char &default_value)
template<>
Array (const int n, const int &default_value)
template<>
Array (const int n, const float &default_value)
template<>
Array (const int n, const double &default_value)
template<>
void deleteObjects ()
template<>
void deleteObjects ()
template<>
void deleteObjects ()
template<>
void deleteObjects ()
template<>
void deleteObjects ()
template<>
Array (const int n, const bool &default_value)
template<>
Array (const int n, const char &default_value)
template<>
Array (const int n, const int &default_value)
template<>
Array (const int n, const float &default_value)
template<>
Array (const int n, const double &default_value)
template<>
void deleteObjects ()
template<>
void deleteObjects ()
template<>
void deleteObjects ()
template<>
void deleteObjects ()
template<>
void deleteObjects ()
Static Public Attributes
static const Array< TYPE >
::DoNotInitialize UNINITIALIZED
Detailed Description
template<class TYPE>
class SAMRAI::tbox::Array< TYPE >
Class Array<TYPE> defines a smart pointer to an array of TYPE and manages all reference counting and deallocation of the array (even if the data was originally allocated from an arena). When the reference count on a Array<TYPE> object goes to zero, the array objects are automatically deallocated. The array class frees the user from deleting and tracking aliases for object arrays.
A block with references count and arena pointer is allocated for all non-empty arrays. These reference counted blocks are freed at the end of the lifetime of the array.
Class TYPE must define a copy constructor and an assignment operator.
See also:
tbox::ReferenceCounter
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::tbox::Array< TYPE >::Array () [inline]
Create an array of zero elements.
template<class TYPE > SAMRAI::tbox::Array< TYPE >::Array (const int n, const TYPE & default_value = TYPE()) [inline, explicit]
Create an array of ``n'' elements.
Elements will be initialized with "n" copies of default_value. If not default_value is supplied the default_constructor is invoked to create a default value.
template<class TYPE > SAMRAI::tbox::Array< TYPE >::Array (const int n, const typename Array< TYPE >::DoNotInitialize & do_not_initialize_flag) [inline]
Create an array of ``n'' uninitialized elements.
The tbox::Array::UNINITIALIZED value should be used for the second argument to flag that the array is uninitialized.
CAUTION: Invoking this constructor will potentially result in a core dump as the element objects will not be initialized (the default constructor is not invoked). If TYPE is a builtin type the arrays values should be assigned before use. If TYPE is a class, use the new placement operator on each array element location to invoke a constructor. This is shown in the following example:
 for(int i = 0; i < d_elements; ++i) {
       void *p = &d_objects[i];
       (void) new (p) TYPE(arg1, arg2);
    }
This constructor may be used to optimize the construction of Arrays when the elements are known to be assigned to some value after construction and thus does not need to be initialized. A loop over the array elements doing an assiggment to the default_value is avoided.
Parameters:
n
do_not_initialize_flag
References NULL_USE.
template<class TYPE > SAMRAI::tbox::Array< TYPE >::Array (const Array< TYPE > & rhs) [inline]
Copy constructor for the array. This creates an alias to the right hand side and increments the reference count.
CAUTION: invoking resizeArray() forces a deep copy. Upon return, two objects that formerly were aliases to the same underlying data will point to separate data. For this reason, it is best to pass a Array by reference, instead of by value.
References SAMRAI::tbox::ReferenceCounter::addReference().
template<class TYPE > SAMRAI::tbox::Array< TYPE >::~Array () [inline]
Destructor for the array. If the reference count for the array data has gone to zero, then the array data is deallocated from the memory arena from which it was allocated.
References SAMRAI::tbox::ReferenceCounter::deleteReference().
template<> SAMRAI::tbox::Array< bool >::Array (const int n, const bool & default_value) [inline]
template<> SAMRAI::tbox::Array< char >::Array (const int n, const char & default_value) [inline]
template<> SAMRAI::tbox::Array< int >::Array (const int n, const int & default_value) [inline]
template<> SAMRAI::tbox::Array< float >::Array (const int n, const float & default_value) [inline]
template<> SAMRAI::tbox::Array< double >::Array (const int n, const double & default_value) [inline]
template<> SAMRAI::tbox::Array< bool >::Array (const int n, const bool & default_value) [inline]
template<> SAMRAI::tbox::Array< char >::Array (const int n, const char & default_value) [inline]
template<> SAMRAI::tbox::Array< int >::Array (const int n, const int & default_value) [inline]
template<> SAMRAI::tbox::Array< float >::Array (const int n, const float & default_value) [inline]
template<> SAMRAI::tbox::Array< double >::Array (const int n, const double & default_value) [inline]
Member Function Documentation
template<class TYPE > Array< TYPE > & SAMRAI::tbox::Array< TYPE >::operator= (const Array< TYPE > & rhs) [inline]
Array assignment. The assignment operator copies a pointer to the array data and increments the reference count. Both array objects refer to the same data, and changes to individual array entry values in one will be reflected in the other array. However, this assignment operation DOES NOT involve a "deep copy" (see the resizeArray() routines below). Thus, changes to one Array object container will not necessarily be reflected in the other container.
References SAMRAI::tbox::ReferenceCounter::addReference(), and SAMRAI::tbox::ReferenceCounter::deleteReference().
Referenced by SAMRAI::tbox::Array< TYPE >::resizeArray().
template<class TYPE > TYPE & SAMRAI::tbox::Array< TYPE >::operator[] (const int i) [inline]
Non-const array subscripting. Return a reference the object at array index ``i'' (between 0 and N-1, where N is the number of elements in the array.
Parameters:
i Array index of item whose reference is to be returned.
Precondition:
(i >= 0) && (i < size())
References SAMRAI::tbox::Array< TYPE >::size(), and TBOX_ASSERT.
template<class TYPE > const TYPE & SAMRAI::tbox::Array< TYPE >::operator[] (const int i) const [inline]
Const array subscripting. Return a const reference to the object at array index ``i'' (between 0 and N-1, where N is the number of elements in the array.
Parameters:
i Array index of item whose reference is to be returned.
Precondition:
(i >= 0) && (i < size())
References SAMRAI::tbox::Array< TYPE >::size(), and TBOX_ASSERT.
template<class TYPE > bool SAMRAI::tbox::Array< TYPE >::isNull () const [inline]
Test whether the array is NULL (has any elements).
template<class TYPE > bool SAMRAI::tbox::Array< TYPE >::empty () const [inline]
Test whether the array is empty (has no elements).
Identical to isNull() but this method is common to several container classes, including STL classes.
template<class TYPE > void SAMRAI::tbox::Array< TYPE >::setNull () [inline]
Set the length of the array to zero. If the reference count for the objects has dropped to zero, then the array data is deallocated.
References SAMRAI::tbox::ReferenceCounter::deleteReference().
template<class TYPE > void SAMRAI::tbox::Array< TYPE >::clear () [inline]
Set the length of the array to zero. If the reference count for the objects has dropped to zero, then the array data is deallocated.
Identical to setNull() but this method is common to several container classes, including STL classes.
References SAMRAI::tbox::ReferenceCounter::deleteReference().
template<class TYPE > TYPE * SAMRAI::tbox::Array< TYPE >::getPointer (const int i = 0) [inline]
Return a non-const pointer to the i-th object. The index must be between 0 and N-1, where N is the number of elements in the array.
Parameters:
i Array index of item whose reference is to be returned.
Precondition:
(i >= 0) && (i < size())
References SAMRAI::tbox::Array< TYPE >::size(), and TBOX_ASSERT.
template<class TYPE > const TYPE * SAMRAI::tbox::Array< TYPE >::getPointer (const int i = 0) const [inline]
Return a const pointer to the i-th object. The index must be between 0 and N-1, where N is the number of elements in the array.
Parameters:
i Array index of item whose reference is to be returned.
Precondition:
(i >= 0) && (i < size())
References SAMRAI::tbox::Array< TYPE >::size(), and TBOX_ASSERT.
template<class TYPE > int SAMRAI::tbox::Array< TYPE >::getSize () const [inline]
Return the number of elements in the array.
template<class TYPE > int SAMRAI::tbox::Array< TYPE >::size () const [inline]
Return the number of elements in the array. Identical to getSize(), but this method is common to several container classes.
Referenced by SAMRAI::tbox::Array< TYPE >::back(), SAMRAI::tbox::Array< TYPE >::erase(), SAMRAI::tbox::Array< TYPE >::getPointer(), and SAMRAI::tbox::Array< TYPE >::operator[]().
template<class TYPE > void SAMRAI::tbox::Array< TYPE >::resizeArray (const int n, const TYPE & default_value = TYPE()) [inline]
Resize the array by allocating new array storage and copying from the old array into the new; i.e., a "deep" copy. Space for the new array is allocated via the standard ``new'' operator.
Elements added be initialized with copies of "default" using the copy constructor for classes and assignment for internal types.
References SAMRAI::tbox::Array< TYPE >::operator=().
Referenced by SAMRAI::tbox::Array< TYPE >::push_back().
template<class TYPE > void SAMRAI::tbox::Array< TYPE >::push_back (const TYPE & value) [inline]
Adds a new element at the end of the array, after its current last element. The content of this new element is initialized to a copy of value.
References SAMRAI::tbox::Array< TYPE >::resizeArray().
template<class TYPE > const TYPE & SAMRAI::tbox::Array< TYPE >::back () [inline]
Returns a reference to the last element in the array container.
Precondition:
size() > 0
References SAMRAI::tbox::Array< TYPE >::size(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::tbox::Array< TYPE >::erase (const int position) [inline]
Removes from the array container a single element at position.
Parameters:
position Array index of element to be removed.
Precondition:
(position >= 0) && (position < size())
References SAMRAI::tbox::ReferenceCounter::deleteReference(), SAMRAI::tbox::Array< TYPE >::size(), and TBOX_ASSERT.
template<> void SAMRAI::tbox::Array< bool >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< char >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< int >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< float >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< double >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< bool >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< char >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< int >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< float >::deleteObjects () [inline]
template<> void SAMRAI::tbox::Array< double >::deleteObjects () [inline]
Member Data Documentation
template<class TYPE> const Array< TYPE >::DoNotInitialize SAMRAI::tbox::Array< TYPE >::UNINITIALIZED [inline, static]
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Array.h
source/SAMRAI/tbox/Array.C