SAMRAI: SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator Class Reference
SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator Class Reference
Class ConstNeighborIterator iterates over the Neighbors of a block.
#include <source/SAMRAI/hier/BaseGridGeometry.h>
Public Member Functions
ConstNeighborIterator (const ConstNeighborIterator &other)
Copy constructor.
ConstNeighborIterator (const NeighborIterator &other)
Copy constructor.
~ConstNeighborIterator ()
Destructor.
ConstNeighborIterator & operator= (const ConstNeighborIterator &rhs)
Assignment operator.
ConstNeighborIterator & operator= (const NeighborIterator &rhs)
Assignment operator.
const Neighbor & operator* () const
Dereference operator.
ConstNeighborIterator operator++ (int)
Post-increment operator.
ConstNeighborIterator & operator++ ()
Pre-increment operator.
bool operator== (const ConstNeighborIterator &rhs) const
Equality operator.
bool operator!= (const ConstNeighborIterator &rhs) const
Inequality operator.
Friends
class BaseGridGeometry
Detailed Description
Class ConstNeighborIterator iterates over the Neighbors of a block.
The iterator points to a const Neighbor.
Constructor & Destructor Documentation
SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::ConstNeighborIterator (const ConstNeighborIterator & other)
Copy constructor.
Parameters:
[in] other The const iterator to copy.
References SAMRAI::hier::BlockId::getBlockValue(), and SAMRAI::hier::BlockId::setId().
SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::ConstNeighborIterator (const NeighborIterator & other)
Copy constructor.
Parameters:
[in] other The non-const iterator to copy.
References SAMRAI::hier::BlockId::getBlockValue(), and SAMRAI::hier::BlockId::setId().
SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::~ConstNeighborIterator ()
Destructor.
Member Function Documentation
ConstNeighborIterator& SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator= (const ConstNeighborIterator & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs The const iterator being assigned.
Returns:
This object after the assignment.
References SAMRAI::hier::BlockId::getBlockValue(), and SAMRAI::hier::BlockId::setId().
ConstNeighborIterator& SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator= (const NeighborIterator & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs The non-const iterator being assigned.
Returns:
This object after the assignment.
References SAMRAI::hier::BlockId::getBlockValue(), and SAMRAI::hier::BlockId::setId().
const Neighbor& SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator* () const [inline]
Dereference operator.
Returns:
The Neighbor that the iterator is currently pointing to.
ConstNeighborIterator SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator++ (int) [inline]
Post-increment operator.
Returns:
This iterator prior to having been incremented.
References SAMRAI::hier::BlockId::getBlockValue().
ConstNeighborIterator& SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator++ () [inline]
Pre-increment operator.
Returns:
This iterator after having been incremented.
References SAMRAI::hier::BlockId::getBlockValue().
bool SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator== (const ConstNeighborIterator & rhs) const [inline]
Equality operator.
Parameters:
[in] rhs The right hand side of the comparison.
Returns:
True if this and rhs are pointing to the same Neighbor of the same block of the same grid geometry.
bool SAMRAI::hier::BaseGridGeometry::ConstNeighborIterator::operator!= (const ConstNeighborIterator & rhs) const [inline]
Inequality operator.
Parameters:
[in] rhs The right hand side of the comparison.
Returns:
True if this and rhs are not pointing to different Neighbors or iterating over different block or different grid geometries.
Friends And Related Function Documentation
friend class BaseGridGeometry [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BaseGridGeometry.h
source/SAMRAI/hier/BaseGridGeometry.C