SAMRAI: SAMRAI::pdat::SecondLayerNodeVariableFillPattern Class Reference
SAMRAI::pdat::SecondLayerNodeVariableFillPattern Class Reference
Class SecondLayerNodeVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
#include <source/SAMRAI/pdat/SecondLayerNodeVariableFillPattern.h>
Public Member Functions
SecondLayerNodeVariableFillPattern (const tbox::Dimension &dim)
Constructor.
virtual ~SecondLayerNodeVariableFillPattern ()
Destructor.
boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &dst_patch_box, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation) const
Calculate overlaps between the destination and source geometries according to the fill pattern.
boost::shared_ptr
< hier::BoxOverlap > computeFillBoxesOverlap (const hier::BoxContainer &fill_boxes, const hier::BoxContainer &node_fill_boxes, const hier::Box &patch_box, const hier::Box &data_box, const hier::PatchDataFactory &pdf) const
Computes a BoxOverlap object which defines the space to be filled by a refinement operation.
const hier::IntVector & getStencilWidth ()
Returns the stencil width of 1 in all directions.
const std::string & getPatternName () const
Returns a string name identifier "SECOND_LAYER_NODE_FILL_PATTERN".
Detailed Description
Class SecondLayerNodeVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
It is used to calculate overlaps according to a pattern which limits the overlaps to the second layer of boundary nodes, that is the nodes lying one cell width away from the patch boundary.
Constructor & Destructor Documentation
SAMRAI::pdat::SecondLayerNodeVariableFillPattern::SecondLayerNodeVariableFillPattern (const tbox::Dimension & dim) [explicit]
Constructor.
Parameters:
[in] dim Dimension
SAMRAI::pdat::SecondLayerNodeVariableFillPattern::~SecondLayerNodeVariableFillPattern () [virtual]
Destructor.
Member Function Documentation
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::SecondLayerNodeVariableFillPattern::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & dst_patch_box, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation) const [virtual]
Calculate overlaps between the destination and source geometries according to the fill pattern.
This will return the portion of the intersection of the node geometries of the intersection of the node geometries that lies in the second layer of boundary nodes, that is the nodes lying one cell width away from the patch boundary. The patch is identified by the argument dst_patch_box.
Parameters:
[in] dst_geometry geometry object for destination box
[in] src_geometry geometry object for source box
[in] dst_patch_box box for the destination patch
[in] src_mask the source mask, the box resulting from transforming the source box
[in] fill_box the box to be filled
[in] overwrite_interior controls whether or not to include the destination box interior in the overlap. This has no effect in this implementation, since all calculated overlaps will be on the destination box exterior.
[in] transformation the transformation from source to destination index space.
Returns:
boost::shared_ptr to the calculated overlap object
Precondition:
dst_patch_box.getDim() == src_mask.getDim()
dynamic_cast<const NodeGeometry *>(&dst_geometry) != 0
dynamic_cast<const NodeGeometry *>(&src_geometry) != 0
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::BoxContainer::intersectBoxes(), NULL_USE, TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::NodeGeometry::toNodeBox().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap (const hier::BoxContainer & fill_boxes, const hier::BoxContainer & node_fill_boxes, const hier::Box & patch_box, const hier::Box & data_box, const hier::PatchDataFactory & pdf) const [virtual]
Computes a BoxOverlap object which defines the space to be filled by a refinement operation.
For this implementation, that space is the node-centered intersection between fill_boxes, (computed by the RefineSchedule), data_box, which specifies the extent of the destination data, and the boundary nodes that define the stencil of this fill pattern.
Parameters:
[in] fill_boxes list representing the all of the space on a patch or its ghost region that may be filled by a refine operator (cell-centered represtentation)
[in] node_fill_boxes node-centered represenation of fill_boxes
[in] patch_box box representing the patch where a refine operator will fill data. (cell-centered representation)
[in] data_box box representing the full extent of the region covered by a patch data object, including all ghosts (cell-centered representation)
[in] pdf patch data factory for the data that is to be filled
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coalesce(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::intersectBoxes(), NULL_USE, and SAMRAI::pdat::NodeGeometry::toNodeBox().
const hier::IntVector & SAMRAI::pdat::SecondLayerNodeVariableFillPattern::getStencilWidth () [virtual]
Returns the stencil width of 1 in all directions.
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::IntVector::getOne().
const std::string & SAMRAI::pdat::SecondLayerNodeVariableFillPattern::getPatternName () const [virtual]
Returns a string name identifier "SECOND_LAYER_NODE_FILL_PATTERN".
Implements SAMRAI::xfer::VariableFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/SecondLayerNodeVariableFillPattern.h
source/SAMRAI/pdat/SecondLayerNodeVariableFillPattern.C