SAMRAI: SAMRAI::geom::GridGeometry Class Reference
SAMRAI::geom::GridGeometry Class Reference
Class GridGeometry manages the index space that determines the extent of the coarse-level domain of a SAMRAI hierarchy.
#include <source/SAMRAI/geom/GridGeometry.h>
Public Member Functions
GridGeometry (const tbox::Dimension &dim, const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db, bool allow_multiblock=true)
Construct a new GridGeometry object and initialize from input.
GridGeometry (const std::string &object_name, hier::BoxContainer &domain)
Construct a new GridGeometry object based on arguments.
GridGeometry (const std::string &object_name, hier::BoxContainer &domain, const boost::shared_ptr< hier::TransferOperatorRegistry > &op_reg)
Construct a new coarsened/refined GridGeometry object with the supplied domain.
virtual ~GridGeometry ()
Virtual destructor.
virtual boost::shared_ptr
< hier::BaseGridGeometry > makeRefinedGridGeometry (const std::string &fine_geom_name, const hier::IntVector &refine_ratio) const
Create a pointer to a refined version of this grid geometry object.
virtual boost::shared_ptr
< hier::BaseGridGeometry > makeCoarsenedGridGeometry (const std::string &coarse_geom_name, const hier::IntVector &coarsen_ratio) const
Create a pointer to a coarsened version of this grid geometry object.
Protected Member Functions
virtual void buildOperators ()
Build operators appropriate for a GridGeometry.
Detailed Description
Class GridGeometry manages the index space that determines the extent of the coarse-level domain of a SAMRAI hierarchy.
A GridGeometry object can be directly constructed with a consistent state, or it may be used as a base class to derive child classes that manage particular grid types (e.g., Cartesian, cylindrical, etc.). Direct construction of a GridGeometry object is recommended for multiblock problems and other problems where the physical locations of mesh coordinates are managed by user code.
Input Parameters
Definitions:
num_blocks specifies the number of blocks in the mesh configuration.
domain_boxes_ For each block, an array of boxes representing the index space for the entire domain within a block on the coarsest mesh level; i.e., level zero. The key must have an integer value as a suffix (domain_boxes_0, domain_boxes_1, etc.), and there must be an entry for every block from 0 to num_blocks-1.
periodic_dimension An array of integer values (expected number of values is equal to the spatial dimension of the mesh) representing the directions in which the physical domain is periodic. A non-zero value indicates that the direction is periodic. A zero value indicates that the direction is not periodic. This key should only be used when the number of blocks is 1 (a single block mesh), as periodic boundaries are not supported for multiblock meshes.
Singularity When there is a reduced or enhanced connectivity singularity, this key must be used to identify which blocks touch the singularity and the position of the singularity in relation to each block's index space. The key for this entry must include a unique trailing integer, and the integers for the full set of Singularity keys must be a continuous sequence beginning with 0.
BlockNeighbors For multiblock grids, a BlockNeighbors entry must be given for every pair of blocks that touch each other in any way. Like Singularity, each entry must have a trailing integer beginning with 0.
No values read in from a restart database may be overridden by input database values.
Details:
parameter
type
default
range
opt/req
behavior on restart
num_blocks
int
1
>=1
opt
May not be modified by input db on restart
domain_boxes_N
array of DatabaseBoxes
none
all Boxes must be non-empty
req
May not be modified by input db on restart
periodic_dimension
int[]
all values 0
any int
opt
May not be modified by input db on restart
Singularity
see Multiblock.pdf for subentries
none
see Multiblock.pdf for subentries
opt
May not be modified by input db on restart
BlockNeighbors
see Multiblock.pdf for subentries
none
see Multiblock.pdf for subentries
opt
May not be modified by input db on restart
A description of the input format for Singularity* and BlockNeighbors* is included in the Multiblock.pdf document in the docs/userdocs directory of the SAMRAI distribution.
See also:
hier::BaseGridGeometry
Constructor & Destructor Documentation
SAMRAI::geom::GridGeometry::GridGeometry (const tbox::Dimension & dim, const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db, bool allow_multiblock = true)
Construct a new GridGeometry object and initialize from input.
This constructor for GridGeometry initializes data members based on parameters read from the specified input database.
This constructor is intended for use when directly constructing a GridGeometry without using a derived child class. The object will contain all index space grid information for a mesh, but nothing about the physical coordinates of the mesh.
Parameters:
[in] dim
[in] object_name
[in] input_db
[in] allow_multiblock set to false if called by inherently single block derived class such as CartesianGridGeometry
References buildOperators().
Referenced by makeCoarsenedGridGeometry(), and makeRefinedGridGeometry().
SAMRAI::geom::GridGeometry::GridGeometry (const std::string & object_name, hier::BoxContainer & domain)
Construct a new GridGeometry object based on arguments.
This constructor creates a new GridGeometry object based on the arguments, rather than relying on input or restart data.
Parameters:
[in] object_name
[in] domain Each element of the array describes the index space for a block.
References buildOperators().
SAMRAI::geom::GridGeometry::GridGeometry (const std::string & object_name, hier::BoxContainer & domain, const boost::shared_ptr< hier::TransferOperatorRegistry > & op_reg)
Construct a new coarsened/refined GridGeometry object with the supplied domain.
This method is intended to be called only by boost::make_shared from the make[Coarsened, Refined]GridGeometry methods to make a coarsened or refined version of a given GridGeometry.
Parameters:
[in] object_name The same name as the uncoarsened/unrefined grid geometry.
[in] domain The coarsened/refined domain.
[in] op_reg The same operator registry as the uncoarsened/unrefined grid geometry.
References buildOperators().
SAMRAI::geom::GridGeometry::~GridGeometry () [virtual]
Virtual destructor.
Member Function Documentation
boost::shared_ptr< hier::BaseGridGeometry > SAMRAI::geom::GridGeometry::makeRefinedGridGeometry (const std::string & fine_geom_name, const hier::IntVector & refine_ratio) const [virtual]
Create a pointer to a refined version of this grid geometry object.
Virtual method -- should be overridden in specialized grid geometry classes
Parameters:
[in] fine_geom_name std::string name of the geometry object
[in] refine_ratio the refinement ratio.
Returns:
The pointer to the grid geometry object.
Precondition:
!fine_geom_name.empty()
fine_geom_name != getObjectName()
getDim() == refine_ratio.getDim()
refine_ratio > hier::IntVector::getZero(getDim())
Implements SAMRAI::hier::BaseGridGeometry.
Reimplemented in SAMRAI::geom::CartesianGridGeometry.
References SAMRAI::hier::BaseGridGeometry::d_transfer_operator_registry, SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::hier::BaseGridGeometry::getObjectName(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::BaseGridGeometry::getPeriodicShift(), SAMRAI::hier::BaseGridGeometry::getPhysicalDomain(), SAMRAI::hier::IntVector::getZero(), GridGeometry(), SAMRAI::hier::BoxContainer::refine(), TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY1.
boost::shared_ptr< hier::BaseGridGeometry > SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry (const std::string & coarse_geom_name, const hier::IntVector & coarsen_ratio) const [virtual]
Create a pointer to a coarsened version of this grid geometry object.
Virtual method -- should be overridden in specialized grid geometry classes
Parameters:
[in] coarse_geom_name std::string name of the geometry object
[in] coarsen_ratio the coasening ratio
Returns:
The pointer to a coarsened version of this grid geometry object.
Precondition:
!coarse_geom_name.empty()
coarse_geom_name != getObjectName()
getDim() == coarsen_ratio.getDim()
coarsen_ratio > hier::IntVector::getZero(getDim())
Implements SAMRAI::hier::BaseGridGeometry.
Reimplemented in SAMRAI::geom::CartesianGridGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coarsen(), SAMRAI::hier::BaseGridGeometry::d_transfer_operator_registry, SAMRAI::hier::BaseGridGeometry::getDim(), SAMRAI::hier::BaseGridGeometry::getObjectName(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::BaseGridGeometry::getPeriodicShift(), SAMRAI::hier::BaseGridGeometry::getPhysicalDomain(), SAMRAI::hier::IntVector::getZero(), GridGeometry(), SAMRAI::hier::Box::isSpatiallyEqual(), SAMRAI::tbox::plog, SAMRAI::hier::Box::refine(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ERROR.
void SAMRAI::geom::GridGeometry::buildOperators () [protected, virtual]
Build operators appropriate for a GridGeometry.
Implements SAMRAI::hier::BaseGridGeometry.
Reimplemented in SAMRAI::geom::CartesianGridGeometry.
References SAMRAI::hier::BaseGridGeometry::addCoarsenOperator(), SAMRAI::hier::BaseGridGeometry::addRefineOperator(), and SAMRAI::hier::BaseGridGeometry::addTimeInterpolateOperator().
Referenced by GridGeometry().
The documentation for this class was generated from the following files:
source/SAMRAI/geom/GridGeometry.h
source/SAMRAI/geom/GridGeometry.C