SAMRAI: SAMRAI::mesh::BergerRigoutsos Class Reference
SAMRAI::mesh::BergerRigoutsos Class Reference
Asynchronous Berger-Rigoutsos implementation. This class is derived from the abstract base class BoxGeneratorStrategy. Thus, it serves as a concrete implementation of the box generator Strategy pattern interface.
#include <source/SAMRAI/mesh/BergerRigoutsos.h>
Public Member Functions
BergerRigoutsos (const tbox::Dimension &dim, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
Constructor.
virtual ~BergerRigoutsos ()
Destructor.
void findBoxesContainingTags (boost::shared_ptr< hier::BoxLevel > &new_box_level, boost::shared_ptr< hier::Connector > &tag_to_new, const boost::shared_ptr< hier::PatchLevel > &tag_level, const int tag_data_index, const int tag_val, const hier::BoxContainer &bound_boxes, const hier::IntVector &min_box, const hier::IntVector &tag_to_new_width)
Implement the BoxGeneratorStrategy interface method of the same name.
void useDuplicateMPI (const tbox::SAMRAI_MPI &mpi)
Duplicate the MPI communication object for private internal use.
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
const std::string getObjectName () const
Get the name of this object.
void setEfficiencyTolerance (const double efficiency_tolerance, const int level_number)
Set efficiency tolerance for clustering tags on level.
double getEfficiencyTolerance (const int level_number) const
Return efficiency tolerance for clustering tags on level.
void setCombineEfficiency (const double combine_efficiency, const int level_number)
Set combine efficiency for clustering tags on level.
double getCombineEfficiency (const int level_number) const
Return combine efficiency for clustering tags on level.
Protected Member Functions
void getFromInput (const boost::shared_ptr< tbox::Database > &input_db)
Read parameters from input database.
Friends
class BergerRigoutsosNode
Detailed Description
Asynchronous Berger-Rigoutsos implementation. This class is derived from the abstract base class BoxGeneratorStrategy. Thus, it serves as a concrete implementation of the box generator Strategy pattern interface.
This class uses the BergerRigoutsosNode class to carry out the asynchronous Berger-Rigoutsos algorithm. It handles aspects not central to that algorithm. It:
Implements the box generator Strategy pattern interface.
Provides an interface with the input database for setting parameters influencing the implementation.
Sorts the output data (if user requests).
Performs some additional error checking. For more details on the parallel implementation, see BergerRigoutsosNode.
Input Parameters
Definitions:
max_box_size The maximum cluster size allowed. This parameter is not critical to clustering but limiting the cluster size may improve performance of load balancing algorithms (due to the excessive work required by the owner of huge clusters).
sort_output_nodes Whether to sort the output. This makes the normally non-deterministic ordering deterministic and the results repeatable.
check_min_box_size A flag to control how to resolve an initial box that violates the minimum box size. Set to one of these strings:
"IGNORE" - violations will be quietly disregarded.
"WARN" - violations will cause a warning but the code will continue anyway.
"ERROR" - violations will cause an unrecoverable assertion.
efficiency_tolerance each value specifies the minimum fraction of tagged cells to total cells in boxes used to construct patches on a new level. If the ratio is below the tolerance value, the box may be split into smaller boxes and pieces removed until the ratio becomes greater than or equal to the tolerance. This tolerance helps users control the amount of extra refined cells created (beyond those tagged explicitly) that is typical in patch-based AMR computations. The index of the value in the array corresponds to the number of the level to which the tolerance value applies. If more values are given than the maximum number of levels allowed in the hierarchy, extra values will be ignored. If fewer values are given, then the last value given will be used for each level without a specified input value. For example, if only a single value is specified, then that value will be used on all levels.
combine_efficiency each value serves as a threshold for the ratio of the total number of cells in two boxes into which a box may be split and the number of cells in the original box. If that ratio is greater than the combine efficiency, the box will not be split. This tolerance helps users avoids splitting up portions of the domain into into very small patches which can increase the overhead of AMR operations. Multiple values in the array are handled similar to efficiency_tolerance.
Details:
parameter
type
default
range
opt/req
behavior on restart
max_box_size
int[]
all values max int
all values > 0
opt
Not written to restart. Value in input db used.
sort_output_nodes
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
check_min_box_size
string
"WARN"
"WARN", "IGNORE", "ERROR"
opt
Not written to restart. Value in input db used.
efficiency_tolerance
array of doubles
0.8 for each level
all values > 0.0 && < 1.0
opt
Not written to restart. Value in input db used.
combine_efficiency
array of doubles
0.8 for each level
all values > 0.0 && < 1.0
opt
Not written to restart. Value in input db used.
Constructor & Destructor Documentation
SAMRAI::mesh::BergerRigoutsos::BergerRigoutsos (const tbox::Dimension & dim, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>()) [explicit]
Constructor.
References getFromInput(), setTimerPrefix(), and TBOX_omp_init_lock.
SAMRAI::mesh::BergerRigoutsos::~BergerRigoutsos () [virtual]
Destructor.
Deallocate internal data.
References SAMRAI::tbox::SAMRAI_MPI::Finalized(), SAMRAI::tbox::SAMRAI_MPI::freeCommunicator(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), MPI_COMM_NULL, and TBOX_omp_destroy_lock.
Member Function Documentation
void SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags (boost::shared_ptr< hier::BoxLevel > & new_box_level, boost::shared_ptr< hier::Connector > & tag_to_new, const boost::shared_ptr< hier::PatchLevel > & tag_level, const int tag_data_index, const int tag_val, const hier::BoxContainer & bound_boxes, const hier::IntVector & min_box, const hier::IntVector & tag_to_new_width) [virtual]
Implement the BoxGeneratorStrategy interface method of the same name.
Create a set of boxes that covers all integer tags on the patch level that match the specified tag value. Each box will be at least as large as the given minimum size and the tolerances will be met.
Precondition:
!bound_boxes.empty()
(tag_level->getDim() == (*(bound_boxes.begin())).getDim()) && (tag_level->getDim() == min_box.getDim()) && (tag_level->getDim() == tag_to_new_width.getDim())
Implements SAMRAI::mesh::BoxGeneratorStrategy.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::IntVector::getBlockVector(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getZero(), MPI_COMM_NULL, SAMRAI::tbox::plog, SAMRAI::tbox::SAMRAI_MPI::setCommunicator(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY4, TBOX_ERROR, and TBOX_WARNING.
void SAMRAI::mesh::BergerRigoutsos::useDuplicateMPI (const tbox::SAMRAI_MPI & mpi)
Duplicate the MPI communication object for private internal use.
A private communicator isolates the complex communications used by the asynchronous algorithm from other communications, protecting this algorithm from un-related communication bugs. Using a duplicated MPI communicator is optional but recommended.
Duplicating the communicator is expensive but need only be done once. All processes in the communicator must participate. The duplicate communicator is active until this object is destructed or you call this method with MPI_COMM_NULL.
When a duplicate MPI communicator is in use, the SAMRAI_MPI object from the tag level must be congruent with it.
References SAMRAI::tbox::SAMRAI_MPI::dupCommunicator(), SAMRAI::tbox::SAMRAI_MPI::freeCommunicator(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), MPI_COMM_NULL, and TBOX_ASSERT.
void SAMRAI::mesh::BergerRigoutsos::setTimerPrefix (const std::string & timer_prefix)
Setup names of timers.
By default, timers are named "mesh::BergerRigoutsosNode::*", where the third field is the specific steps performed by the BergerRigoutsosNode. You can override the first two fields with this method. Conforming to the timer naming convention, timer_prefix should have the form "*::*".
References SAMRAI::tbox::TimerManager::getManager(), and SAMRAI::tbox::AsyncCommStage::setCommunicationWaitTimer().
Referenced by BergerRigoutsos().
const std::string SAMRAI::mesh::BergerRigoutsos::getObjectName () const [inline]
Get the name of this object.
void SAMRAI::mesh::BergerRigoutsos::setEfficiencyTolerance (const double efficiency_tolerance, const int level_number) [inline]
Set efficiency tolerance for clustering tags on level.
Parameters:
[in] efficiency_tolerance
[in] level_number
Precondition:
level_number >= 0
(efficiency_tolerance >= 0) && (efficiency_tolerance <= 1.0)
References TBOX_ASSERT.
double SAMRAI::mesh::BergerRigoutsos::getEfficiencyTolerance (const int level_number) const [inline]
Return efficiency tolerance for clustering tags on level.
Returns:
efficiency tolerance for clustering tags on level.
Precondition:
level_number >= 0
References TBOX_ASSERT.
void SAMRAI::mesh::BergerRigoutsos::setCombineEfficiency (const double combine_efficiency, const int level_number) [inline]
Set combine efficiency for clustering tags on level.
Parameters:
[in] combine_efficiency
[in] level_number
Precondition:
level_number >= 0
(combine_efficiency >= 0) && (combine_efficiency <= 1.0)
References TBOX_ASSERT.
double SAMRAI::mesh::BergerRigoutsos::getCombineEfficiency (const int level_number) const [inline]
Return combine efficiency for clustering tags on level.
Returns:
combine efficiency for clustering tags on level.
Precondition:
level_number >= 0
References TBOX_ASSERT.
void SAMRAI::mesh::BergerRigoutsos::getFromInput (const boost::shared_ptr< tbox::Database > & input_db) [protected]
Read parameters from input database.
Parameters:
input_db Input Database.
References SAMRAI::tbox::Dimension::getValue(), INPUT_RANGE_ERROR, and INPUT_VALUE_ERROR.
Referenced by BergerRigoutsos().
Friends And Related Function Documentation
friend class BergerRigoutsosNode [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/BergerRigoutsos.h
source/SAMRAI/mesh/BergerRigoutsos.C