SAMRAI: SAMRAI::pdat::FirstLayerEdgeVariableFillPattern Class Reference
SAMRAI::pdat::FirstLayerEdgeVariableFillPattern Class Reference
Class FirstLayerEdgeVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
#include <source/SAMRAI/pdat/FirstLayerEdgeVariableFillPattern.h>
Public Member Functions
FirstLayerEdgeVariableFillPattern (const tbox::Dimension &dim)
Constructor.
virtual ~FirstLayerEdgeVariableFillPattern ()
Destructor.
boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &dst_patch_box, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation) const
Calculate overlaps between the destination and source geometries according to the fill pattern.
boost::shared_ptr
< hier::BoxOverlap > computeFillBoxesOverlap (const hier::BoxContainer &fill_boxes, const hier::BoxContainer &node_fill_boxes, const hier::Box &patch_box, const hier::Box &data_box, const hier::PatchDataFactory &pdf) const
Computes a BoxOverlap object which defines the space to be filled by a refinement operation.
const hier::IntVector & getStencilWidth ()
Returns the stencil width of 0 in all directions.
const std::string & getPatternName () const
Returns a string name identifier "FIRST_LAYER_EDGE_FILL_PATTERN".
Detailed Description
Class FirstLayerEdgeVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
It is used to calculate overlaps according to a pattern which limits the overlaps to the first layer of boundary edges, that is the edges that lie on the patch boundary.
In this diagram of a 2x2 patch with a ghost width of one, + are patch nodes, * are ghost nodes. i markes the i edges that will be filled using this pattern, and j marks the j edges that will be filled.
*...*...*...*...* | | | | | *...+-i-+-i-+...* | j | j | *...+---+---+...* | j | j | *...+-i-+-i-+...* | | | | | *...*...*...*...*
Constructor & Destructor Documentation
SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::FirstLayerEdgeVariableFillPattern (const tbox::Dimension & dim) [explicit]
Constructor.
Parameters:
[in] dim Dimension
SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::~FirstLayerEdgeVariableFillPattern () [virtual]
Destructor.
Member Function Documentation
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & dst_patch_box, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation) const [virtual]
Calculate overlaps between the destination and source geometries according to the fill pattern.
This will return the portion of the intersection of the edge geometries that lies on the boundary of the patch. The patch is identified by the argument dst_patch_box. The argument overwrite_interior should be set to true, since the stencil defined by this class consists of boundary edges, which SAMRAI by convention considers to be part of the patch interior. If overwrite_interior is false, then the returned BoxOverlap will be empty.
Parameters:
[in] dst_geometry geometry object for destination box
[in] src_geometry geometry object for source box
[in] dst_patch_box box for the destination patch
[in] src_mask the source mask, the box resulting from transforming the source box
[in] fill_box the box to be filled
[in] overwrite_interior controls whether or not to include the destination box interior in the overlap.
[in] transformation the transformation from source to destination index space.
Returns:
boost::shared_ptr to the calculated overlap object
Precondition:
dst_patch_box.getDim() == src_mask.getDim()
dynamic_cast<const EdgeGeometry *>(&dst_geometry) != 0
dynamic_cast<const EdgeGeometry *>(&src_geometry) != 0
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::computeFillBoxesOverlap (const hier::BoxContainer & fill_boxes, const hier::BoxContainer & node_fill_boxes, const hier::Box & patch_box, const hier::Box & data_box, const hier::PatchDataFactory & pdf) const [virtual]
Computes a BoxOverlap object which defines the space to be filled by a refinement operation.
For this implementation, that space is the edge-centered intersection between fill_boxes, (computed by the RefineSchedule), data_box, which specifies the extent of the destination data, and the boundary edges that define the stencil of this fill pattern.
Parameters:
[in] fill_boxes list representing the all of the space on a patch or its ghost region that may be filled by a refine operator (cell-centered represtentation)
[in] node_fill_boxes node-centered represenation of fill_boxes
[in] patch_box box representing the patch where a refine operator will fill data. (cell-centered representation)
[in] data_box box representing the full extent of the region covered by a patch data object, including all ghosts (cell-centered representation)
[in] pdf patch data factory for the data that is to be filled
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), NULL_USE, and SAMRAI::pdat::EdgeGeometry::toEdgeBox().
const hier::IntVector & SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::getStencilWidth () [virtual]
Returns the stencil width of 0 in all directions.
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::IntVector::getZero().
const std::string & SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::getPatternName () const [virtual]
Returns a string name identifier "FIRST_LAYER_EDGE_FILL_PATTERN".
Implements SAMRAI::xfer::VariableFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/FirstLayerEdgeVariableFillPattern.h
source/SAMRAI/pdat/FirstLayerEdgeVariableFillPattern.C