SAMRAI: SAMRAI::mesh::ChopAndPackLoadBalancer Class Reference
SAMRAI::mesh::ChopAndPackLoadBalancer Class Reference
Class ChopAndPackLoadBalancer provides load balancing routines for AMR hierarchy levels based on either uniform or non-uniform workload estimates.
#include <source/SAMRAI/mesh/ChopAndPackLoadBalancer.h>
Public Member Functions
ChopAndPackLoadBalancer (const tbox::Dimension &dim, const std::string &name, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
ChopAndPackLoadBalancer (const tbox::Dimension &dim, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
virtual ~ChopAndPackLoadBalancer ()
void setMaxWorkloadFactor (double factor, int level_number=-1)
void setWorkloadTolerance (double tolerance, int level_number=-1)
void setWorkloadPatchDataIndex (int data_id, int level_number=-1)
void setUniformWorkload (int level_number=-1)
void setBinPackMethod (const std::string &method, int level_number=-1)
void setIgnoreLevelDomainIsSingleBox (bool flag)
bool getLoadBalanceDependsOnPatchData (int level_number) const
void loadBalanceBoxLevel (hier::BoxLevel &balance_box_level, hier::Connector *balance_to_anchor, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int level_number, const hier::IntVector &min_size, const hier::IntVector &max_size, const hier::BoxLevel &domain_box_level, const hier::IntVector &bad_interval, const hier::IntVector &cut_factor, const tbox::RankGroup &rank_group=tbox::RankGroup()) const
virtual void printClassData (std::ostream &os) const
const std::string & getObjectName () const
Detailed Description
Class ChopAndPackLoadBalancer provides load balancing routines for AMR hierarchy levels based on either uniform or non-uniform workload estimates.
This class is derived from the abstract base class LoadBalanceStrategy; thus, it is a concrete implementation of the load balance Strategy pattern interface.
Load balancing operations, whether based on uniform or non-uniform workloads, can be specified for each level in the hierarchy individually or for the entire hierarchy. Basic load balance parameters can be set from an input file, while more complex behavior can be set at run-time via member functions, including dynamic reconfiguration of balance operations.
Input Parameters
Definitions:
bin_pack_method String value indicating the type of bin packing to use to map patches to processors. Currently, two options are supported: "GREEDY" and "SPATIAL". The "GREEDY" method simply maps each patch (box) to the first processor (bin), in ascending tbox::MPI process number, whose difference between the average workload and its current workload is less than the workload of the patch in question. The "SPATIAL" method first constructs an ordering of the patches (boxes) by passing a Morton-type curve through the center of each box. Then, it attempts to map the patches to processors by assigning patches that are near each other on the curve to the same processor. If no input value is specified, a default value of "SPATIAL" is used. The input value will be used for all levels and will below.
max_workload_factor Double array (length = number of levels) used during the box-splitting phase to determine which boxes to split. Specifically, boxes will be chopped if their estimated workload is greater than max_workload_factor * A, where A is the average workload (i.e., A = (total work)/(num processors)). The default value for this parameter is 1.0. It can be set to any value greater than zero, either in the input file or via the setMaxWorkloadFactor() member function below.
workload_tolerance Double array (length = number of levels) used during the box-splitting phase to determine which boxes to split. The tolerance value can be use to prevent splitting of boxes when the computed box workload is close to the computed ideal workload. A box is split if:
(box_workload <= ((1. + workload_tolerance) * ideal_workload))
Tolerance values should be greater than or equal to 0.0 and less then 1.0. Large values will probably have undesirable results. It can be set either in the input file or via the setWorkloadTolerance() member function below.
NOTE: If a length is less than max levels then finest value specified is use for finer levels. If length is greater than max levels, the values are ignored.
ignore_level_box_union_is_single_box Boolean flag to control chopping of level boxes when the union of the input boxes passed to the loadBalanceBoxes() routine is a single box. The default value is false, which means that the domain will be chopped to make patch boxes based on the (single box) union of the boxes describing the level regardless of the input boxes. When the value is set to true, either via the setIgnoreLevelDomainIsSingleBox() function or an input file, the domain will be chopped by chopping each of the input boxes.
processor_layout Integer array (length = DIM) indicating the way in which the domain should be chopped when a level can be described as a single parallelepiped region (i.e., a box). If no input value is provided, or if the product of these entries does not equal the number of processors, then the processor layout computed will be computed from the size of the domain box and the number of processors in use if necessary.
NOTE: The largest patch size constraint specified in the input for the GriddingAlgorithm object takes precedence over the processor layout specification. That is, if the processor layout indicates that the resulting level patches would be larger than the largest patch size, the layout will be ignored and boxes obeying the patch size constrint will result.
tile_size Tile size when using tile mode. Tile mode restricts box cuts to tile boundaries.
Details:
parameter
type
default
range
opt/req
behavior on restart
bin_pack_method
string
"SPATIAL"
"SPATIAL", "GREEDY"
opt
Not written to restart. Value in input db used.
max_workload_factor
array of doubles
none
0.0 <= all values
opt
Not written to restart. Value in input db used.
workload_tolerance
array of doubles
none
0.0 <= all values < 1.0
opt
Not written to restart. Value in input db used.
ignore_level_box_union_is_single_box
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
processor_layout
int[]
N/A
N/A
opt
Not written to restart. Value in input db used.
tile_size
IntVector
1
1-
opt
Not written to restart. Value in input db used.
A sample input file entry might look like:
    processor_layout = 4 , 4 , 4    // number of processors is 64
    bin_pack = "GREEDY"
    max_workload_factor = 0.9
    ignore_level_box_union_is_single_box = TRUE
Performance warning: This class implements a sequential algorithm. The time it takes to this balancer increases with processor count. However, you can probably use this load balancer on up to 1K processors before its performance degrades noticably.
See also:
mesh::LoadBalanceStrategy
Constructor & Destructor Documentation
SAMRAI::mesh::ChopAndPackLoadBalancer::ChopAndPackLoadBalancer (const tbox::Dimension & dim, const std::string & name, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>())
Construct load balancer object, including setting default object state and reading input data from the input data base, if required.
Parameters:
[in] dim
[in] name User-defined string identifier used for error reporting. This string must be non-empty.
[in] input_db (optional) database pointer providing parameters from input file. This pointer may be null indicating no input will be read.
Precondition:
!name.empty()
References TBOX_ASSERT.
SAMRAI::mesh::ChopAndPackLoadBalancer::ChopAndPackLoadBalancer (const tbox::Dimension & dim, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>()) [explicit]
Construct load balancer object, including setting default object state and reading input data from the input data base, if required. The only difference between this constructor and the previous one is the string identifier input. If this constructor is used, the default object name "ChopAndPackLoadBalancer" applies.
Parameters:
[in] dim
[in] input_db (optional) database pointer providing parameters from input file. This pointer may be null indicating no input will be read.
SAMRAI::mesh::ChopAndPackLoadBalancer::~ChopAndPackLoadBalancer () [virtual]
The virtual destructor releases all internal storage.
Member Function Documentation
void SAMRAI::mesh::ChopAndPackLoadBalancer::setMaxWorkloadFactor (double factor, int level_number = -1)
Set the max workload factor for either the specified level or all hierarchy levels. See discussion about inputs above for information on how this value is used during load balancing operations.
Parameters:
factor Double value of multiplier for average workload used in box chopping. The default value is 1.0.
level_number Optional integer number for level to which factor is applied. If no value is given, the factor will be used for all levels.
Precondition:
factor > 0.0
References TBOX_ASSERT.
void SAMRAI::mesh::ChopAndPackLoadBalancer::setWorkloadTolerance (double tolerance, int level_number = -1)
Set the workload tolerance for either the specified level or all hierarchy levels. See discussion about inputs above for information on how this value is used during load balancing operations.
Parameters:
tolerance Double value of tolerance. The default value is 0.0;
level_number Optional integer number for level to which factor is applied. If no value is given, the value will be used for all levels.
Precondition:
tolerance > 0.0
References TBOX_ASSERT.
void SAMRAI::mesh::ChopAndPackLoadBalancer::setWorkloadPatchDataIndex (int data_id, int level_number = -1)
Configure the load balancer to use the data stored in the hierarchy at the specified descriptor index for estimating the workload on each cell.
Parameters:
data_id Integer value of patch data identifier for workload estimate on each cell.
level_number Optional integer number for level on which data id is used. If no value is given, the data will be used for all levels.
Precondition:
hier::VariableDatabase::getDatabase()->getPatchDescriptor()->getPatchDataFactory(data_id) is actually a boost::shared_ptr<pdat::CellDataFactory<double> >
References BOOST_CAST, SAMRAI::hier::VariableDatabase::getDatabase(), and TBOX_ASSERT.
void SAMRAI::mesh::ChopAndPackLoadBalancer::setUniformWorkload (int level_number = -1)
Configure the load balancer to load balance boxes by assuming all cells on the specified level or all hierarchy levels are weighted equally.
Parameters:
level_number Optional integer number for level on which uniform workload estimate will be used. If the level number is not specified, a uniform workload estimate will be used on all levels.
void SAMRAI::mesh::ChopAndPackLoadBalancer::setBinPackMethod (const std::string & method, int level_number = -1)
Configure the load balancer to use the bin-packing procedure for mapping patches to processors indicated by the string.
Parameters:
method String value indicating bin-packing method to use. See input file description above for valid options. The default value is "GREEDY".
level_number Optional integer number for level on which bin-packing method will be used. If no value is given, the prescribed methods will be used on all levels.
Precondition:
(method == "GREEDY") || (method == "SPATIAL")
References TBOX_ERROR.
void SAMRAI::mesh::ChopAndPackLoadBalancer::setIgnoreLevelDomainIsSingleBox (bool flag) [inline]
Set the boolean flag to control chopping of level boxes when the union of the input boxes passed to the loadBalanceBoxes() routine is a single box. The default value is false, which means that the domain will be chopped to make patch boxes based on the (single box) union of the boxes describing the level regardless of the input boxes. When the value is set to true, the domain will be chopped by chopping each of the input boxes.
Parameters:
flag Boolean value indicating whether to ignore the set of input boxes to the loadBalanceBoxes() routine when the union of those boxes is a single box.
bool SAMRAI::mesh::ChopAndPackLoadBalancer::getLoadBalanceDependsOnPatchData (int level_number) const [virtual]
Return true if load balancing procedure for given level depends on patch data on mesh; otherwise return false. This can be used to determine whether a level needs to be rebalanced although its box configuration is unchanged. This function is pure virtual in the LoadBalanceStrategy base class.
Returns:
Boolean value indicating whether load balance depends on patch data.
Parameters:
level_number Integer patch level number.
Implements SAMRAI::mesh::LoadBalanceStrategy.
void SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel (hier::BoxLevel & balance_box_level, hier::Connector * balance_to_anchor, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int level_number, const hier::IntVector & min_size, const hier::IntVector & max_size, const hier::BoxLevel & domain_box_level, const hier::IntVector & bad_interval, const hier::IntVector & cut_factor, const tbox::RankGroup & rank_group = tbox::RankGroup()) const [virtual]
Given a list of boxes, representing the domain of a level in the AMR hierarchy, generate an array of boxes and an associated processor mapping from which the patches for the level will be generated and assigned. The resulting boxes and processor mapping will be determined based on parameters set via input or member functions above. This function is pure virtual in the LoadBalanceStrategy base class.
The load balancing algorithm should ignore any periodic image Boxes in the input balance_box_level.
Parameters:
balance_box_level
balance_to_anchor
hierarchy Input patch hierarchy in which level will reside.
level_number Input integer number of level in patch hierarchy. This value must be >= 0.
min_size Input integer vector of minimum sizes for output boxes. All entries must be > 0.
max_size Input integer vector of maximum sizes for output boxes. All entries must be >= min_size.
domain_box_level
bad_interval Input integer vector used to create boxes near physical domain boundary with sufficient number of cells. No box face will be closer to the boundary than the corresponding interval of cells to the boundary (the corresponding value is given by the normal direction of the box face) unless the face coincides with the boundary itself. The point of this argument is to have no patch live within a certain ghost cell width of the boundary if its boundary does not coincide with that boundary . That is, all ghost cells along a face will be either in the domain interior or outside the domain. All entries must be >= 0. See hier::BoxUtilities documentation for more details.
cut_factor Input integer vector used to create boxes with correct sizes. The length of each box direction will be an integer multiple of the corresponding cut factor vector entry. All vector entries must be > 0. See hier::BoxUtilities documentation for more details.
rank_group Needed for compatibility with parent class. This argument is ignored.
Precondition:
!balance_to_anchor || balance_to_anchor->hasTranspose()
(d_dim == balance_box_level.getDim()) && (d_dim == min_size.getDim()) && (d_dim == max_size.getDim()) && (d_dim == domain_box_level.getDim()) && (d_dim == bad_interval.getDim()) && (d_dim == cut_factor.getDim())
Implements SAMRAI::mesh::LoadBalanceStrategy.
References SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Connector::clearNeighborhoods(), SAMRAI::hier::BoxLevel::DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps(), SAMRAI::hier::BoxLevel::getGlobalBoxes(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::ProcessorMapping::getProcessorAssignment(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::Connector::hasTranspose(), SAMRAI::hier::BoxLevel::initialize(), NULL_USE, SAMRAI::hier::BoxContainer::pushBack(), SAMRAI::hier::Connector::removePeriodicRelationships(), SAMRAI::hier::Connector::setBase(), SAMRAI::hier::Connector::setHead(), SAMRAI::hier::BoxLevel::setParallelState(), TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY6.
void SAMRAI::mesh::ChopAndPackLoadBalancer::printClassData (std::ostream & os) const [virtual]
Print out all members of the class instance to given output stream.
const std::string& SAMRAI::mesh::ChopAndPackLoadBalancer::getObjectName () const [inline]
Returns the name of this object.
Returns:
The name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/ChopAndPackLoadBalancer.h
source/SAMRAI/mesh/ChopAndPackLoadBalancer.C