SAMRAI: SAMRAI::xfer::CoarsenSchedule Class Reference
SAMRAI::xfer::CoarsenSchedule Class Reference
Class CoarsenSchedule performs the communication operations to coarsen data from a finer level to a coarser level.
#include <source/SAMRAI/xfer/CoarsenSchedule.h>
Public Member Functions
CoarsenSchedule (const boost::shared_ptr< hier::PatchLevel > &crse_level, const boost::shared_ptr< hier::PatchLevel > &fine_level, const boost::shared_ptr< CoarsenClasses > &coarsen_classes, const boost::shared_ptr< CoarsenTransactionFactory > &transaction_factory, CoarsenPatchStrategy *patch_strategy, bool fill_coarse_data)
Constructor.
~CoarsenSchedule ()
The destructor for the schedule releases all internal storage.
void getFromInput ()
Read static data from input database.
void reset (const boost::shared_ptr< CoarsenClasses > &coarsen_classes)
Reset this coarsen schedule to perform data transfers asssociated items in the given CoarsenClasses argument.
void coarsenData () const
Execute the stored communication schedule and perform the data movement.
const boost::shared_ptr
< CoarsenClasses > & getEquivalenceClasses () const
Return the coarsen equivalence classes used in the schedule.
void setDeterministicUnpackOrderingFlag (bool flag)
Set whether to unpack messages in a deterministic order.
void printClassData (std::ostream &stream) const
Print the coarsen schedule state to the specified data stream.
Static Public Member Functions
static void setScheduleGenerationMethod (const std::string &method)
Static function to set box intersection algorithm to use during schedule construction for all CoarsenSchedule objects.
Detailed Description
Class CoarsenSchedule performs the communication operations to coarsen data from a finer level to a coarser level.
Data is typically coarsened from the interiors of source patch components on the source patch level into interiors of destination patch components on the destination level. Variations are possible for special situations; see the CoarsenAlgorithm class header for more information. Generally, the source patch data must contain sufficient ghost cells to satisfy the coarsening operators involved. If a coarsen operator has a non-zero ghost cell width, then the source ghost cells must be filled before the coarsen schedule is executed. The communication schedule is executed by calling member function coarsenData().
Each schedule object is typically created by a coarsen algorithm and represents communication dependencies for a particular configuration of the AMR hierarchy. The communication schedule is only valid for that particular configuration and must be regenerated when the AMR patch hierarchy changes. As long as the patch levels involved in the creation of the schedule remain unchanged, the schedule may be used for multiple communication cycles. For more information about creating refine schedules, see the CoarsenAlgorithm header file.
NOTE: Algorithmic variations are available by calling the static method CoarsenSchedule::setScheduleGenerationMethod(), which sets the option for all instances of the class.
See also:
xfer::CoarsenAlgorithm
xfer::CoarsenPatchStrategy
xfer::CoarsenClasses
Constructor & Destructor Documentation
SAMRAI::xfer::CoarsenSchedule::CoarsenSchedule (const boost::shared_ptr< hier::PatchLevel > & crse_level, const boost::shared_ptr< hier::PatchLevel > & fine_level, const boost::shared_ptr< CoarsenClasses > & coarsen_classes, const boost::shared_ptr< CoarsenTransactionFactory > & transaction_factory, CoarsenPatchStrategy * patch_strategy, bool fill_coarse_data)
Constructor.
Creates a coarsen schedule that coarsens data from source patch data components on the fine level into the destination patch data components on the coarse level.
In general, this constructor is called by a CoarsenAlgorithm object. For possible variations on data coarsening, see the CoarsenAlgorithm class header information.
If the coarsening operators require data from ghost cells, then the associated source patch data components must have a sufficient ghost cell width and and they must be filled with valid data before calling coarsenData().
Parameters:
[in] crse_level boost::shared_ptr to coarse (destination) patch level.
[in] fine_level boost::shared_ptr to fine (source) patch level.
[in] coarsen_classes boost::shared_ptr to structure containing patch data and operator information. In general, this is constructed by the calling CoarsenAlgorithm object.
[in] transaction_factory boost::shared_ptr to a factory object that will create data transactions.
[in] patch_strategy boost::shared_ptr to a coarsen patch strategy object that provides user-defined coarsen operations. This pointer may be null, in which case no user-defined coarsen operations will be performed.
[in] fill_coarse_data Boolean indicating whether coarse data should be filled before coarsening operations are done.
Precondition:
crse_level
fine_level
coarsen_classes
transaction_factory
crse_level->getDim() == fine_level->getDim()
References getFromInput(), SAMRAI::tbox::plog, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::xfer::CoarsenSchedule::~CoarsenSchedule ()
The destructor for the schedule releases all internal storage.
Member Function Documentation
void SAMRAI::xfer::CoarsenSchedule::getFromInput ()
Read static data from input database.
References SAMRAI::tbox::InputManager::getInputDatabase().
Referenced by CoarsenSchedule().
void SAMRAI::xfer::CoarsenSchedule::reset (const boost::shared_ptr< CoarsenClasses > & coarsen_classes)
Reset this coarsen schedule to perform data transfers asssociated items in the given CoarsenClasses argument.
The schedule will be changed to operate on data given by the coarsen_classes argument rather than the data it has previously been set to operate on.
Parameters:
[in] coarsen_classes boost::shared_ptr to structure containing patch data and operator information. In general, this is constructed by the calling CoarsenAlgorithm object. This pointer must be non-null.
Precondition:
coarsen_classes
References TBOX_ASSERT.
void SAMRAI::xfer::CoarsenSchedule::coarsenData () const
Execute the stored communication schedule and perform the data movement.
References SAMRAI::tbox::plog.
const boost::shared_ptr<CoarsenClasses>& SAMRAI::xfer::CoarsenSchedule::getEquivalenceClasses () const [inline]
Return the coarsen equivalence classes used in the schedule.
void SAMRAI::xfer::CoarsenSchedule::setDeterministicUnpackOrderingFlag (bool flag)
Set whether to unpack messages in a deterministic order.
By default message unpacking is ordered by receive time, which is not deterministic. If your results are dependent on unpack ordering and you want deterministic results, set this flag to true.
Parameters:
[in] flag
void SAMRAI::xfer::CoarsenSchedule::setScheduleGenerationMethod (const std::string & method) [static]
Static function to set box intersection algorithm to use during schedule construction for all CoarsenSchedule objects.
If this method is not called, the default will be used. If an invalid string is passed, an unrecoverable error will result.
Parameters:
[in] method string identifying box intersection method. Valid choices are: "DLBG" (default case), and "ORIG_NSQUARED". More details can be found below in the comments for the generateSchedule() routine.
Precondition:
(method == "ORIG_NSQUARED") || (method == "DLBG")
References TBOX_ERROR.
void SAMRAI::xfer::CoarsenSchedule::printClassData (std::ostream & stream) const
Print the coarsen schedule state to the specified data stream.
Parameters:
[out] stream Output data stream.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/CoarsenSchedule.h
source/SAMRAI/xfer/CoarsenSchedule.C