SAMRAI: SAMRAI::hier::ProcessorMapping Class Reference
SAMRAI::hier::ProcessorMapping Class Reference
#include <source/SAMRAI/hier/ProcessorMapping.h>
Public Member Functions
ProcessorMapping ()
ProcessorMapping (const int n)
ProcessorMapping (const ProcessorMapping &mapping)
ProcessorMapping (const std::vector< int > &mapping)
~ProcessorMapping ()
void setMappingSize (const size_t n)
void setNumberNodes (const int n)
int getProcessorAssignment (const int i) const
void setProcessorAssignment (const int i, const int p)
const std::vector< int > & getProcessorMapping () const
void setProcessorMapping (const std::vector< int > &mapping)
int getNumberOfLocalIndices () const
const std::vector< int > & getLocalIndices () const
int getSizeOfMappingArray () const
bool isMappingLocal (const int i) const
Detailed Description
Class ProcessorMapping represents the processor assignments of patches to processors. It makes sure that all processor assignments are in the range from 0 through NODES-1 and answers whether a particular assignment is local to the processor.
Constructor & Destructor Documentation
SAMRAI::hier::ProcessorMapping::ProcessorMapping ()
Create a default processor mapping array with 0 elements. Before the mapping can be used, its size should be set using the function setMappingSize() and each element of the mapping should be set by setProcessorAssignment().
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and SAMRAI::tbox::SAMRAI_MPI::getSize().
SAMRAI::hier::ProcessorMapping::ProcessorMapping (const int n) [explicit]
Create a processor mapping array with enough space for n elements. All elements of the mapping are initialized to processor zero, but they should be set by setProcessorAssignment() later.
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and SAMRAI::tbox::SAMRAI_MPI::getSize().
SAMRAI::hier::ProcessorMapping::ProcessorMapping (const ProcessorMapping & mapping)
Create a new processor mapping and copy the processor assignments from the argument.
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and SAMRAI::tbox::SAMRAI_MPI::getSize().
SAMRAI::hier::ProcessorMapping::ProcessorMapping (const std::vector< int > & mapping) [explicit]
Create a new processor mapping and get processor assignments from the the std::vector<int> argument.
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), and setProcessorMapping().
SAMRAI::hier::ProcessorMapping::~ProcessorMapping ()
The destructor simply releases the storage for the mapping.
Member Function Documentation
void SAMRAI::hier::ProcessorMapping::setMappingSize (const size_t n)
Resize the mapping so that it has n elements. Before it can be used, each element should be set using setProcessorAssignment().
Referenced by SAMRAI::mesh::BalanceUtilities::binPack(), and SAMRAI::mesh::BalanceUtilities::spatialBinPack().
void SAMRAI::hier::ProcessorMapping::setNumberNodes (const int n) [inline]
Sets the number of boxes to n. IMPORTANT NOTE: This method should only be used for testing purposes. Under normal circumstances, the number of boxes is set by a call to tbox::SAMRAI_MPI::getNodes() and should NOT be changed.
int SAMRAI::hier::ProcessorMapping::getProcessorAssignment (const int i) const [inline]
Return the processor assignment for the specified patch index.
Precondition:
(i >= 0) && (i < getProcessorMapping().size())
References TBOX_ASSERT.
Referenced by SAMRAI::mesh::BalanceUtilities::computeLoadBalanceEfficiency(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BalanceUtilities::spatialBinPack().
void SAMRAI::hier::ProcessorMapping::setProcessorAssignment (const int i, const int p) [inline]
Set the processor assignment (second argument) for the specified patch index (first argument).
Precondition:
(i >= 0) && (i < getProcessorMapping().size())
(p >= 0) && (p < d_nodes)
References TBOX_ASSERT.
Referenced by SAMRAI::mesh::BalanceUtilities::binPack(), and setProcessorMapping().
const std::vector<int>& SAMRAI::hier::ProcessorMapping::getProcessorMapping () const [inline]
Return an std::vector<int> of the processor mappings.
void SAMRAI::hier::ProcessorMapping::setProcessorMapping (const std::vector< int > & mapping)
Sets the processor mappings from an std::vector<int>. Remaps the processors so that patches are not accidentally mapped to non-existent boxes.
References setProcessorAssignment().
Referenced by ProcessorMapping().
int SAMRAI::hier::ProcessorMapping::getNumberOfLocalIndices () const [inline]
Return the number of local indices (that is, those indices mapped to the local processor).
const std::vector<int>& SAMRAI::hier::ProcessorMapping::getLocalIndices () const [inline]
Return a vector containing the local indices (that is, those indices mapped to the local processor).
int SAMRAI::hier::ProcessorMapping::getSizeOfMappingArray () const [inline]
Return the total number of indices in the mapping array.
bool SAMRAI::hier::ProcessorMapping::isMappingLocal (const int i) const [inline]
Check whether the specified index is a local index (that is, mapped to the local processor).
Precondition:
(i >= 0) && (i < getProcessorMapping().size())
References TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/ProcessorMapping.h
source/SAMRAI/hier/ProcessorMapping.C