SAMRAI: SAMRAI::hier::AssumedPartitionBox Class Reference
SAMRAI::hier::AssumedPartitionBox Class Reference
Compute an assumed partition of a box. The assumed partition should very fast to create and query and requires minimal storage.
#include <source/SAMRAI/hier/AssumedPartitionBox.h>
Public Member Functions
AssumedPartitionBox (const Box &unpartitioned_box, int rank_begin, int rank_end, int index_begin=0, double avg_parts_per_rank=1.0, bool interleave=false)
Construct AssumedPartition from a box.
AssumedPartitionBox (const tbox::Dimension &dim)
Nearly default constructor.
void partition (const Box &unpartitioned_box, int rank_begin, int rank_end, int index_begin=0, double avg_parts_per_rank=1.0, bool interleave=false)
Partition the given box, discarding the current state.
~AssumedPartitionBox ()
Destructor.
const Box & getUnpartitionedBox () const
Return the original unpartitioned box.
int getNumberOfParts () const
Number of box partitions.
int getOwner (int box_index) const
Return the owner for a box.
Box getBox (int box_index) const
Return box for given index.
Box getBox (const IntVector &position) const
Return box for given partition's position in the partition grid.
void getAllBoxes (BoxContainer &all_boxes) const
Get all partition boxes.
void getAllBoxes (BoxContainer &all_boxes, int rank) const
Get all partition boxes owned by a given rank.
int begin () const
Return index of first partition box.
int end () const
Return one past index of last partition box.
int beginOfRank (int rank) const
Return index of first box in the contiguous index range assigned to given rank.
int endOfRank (int rank) const
Return one past index of last box in the contiguous index range assigned to given rank.
bool findOverlaps (BoxContainer &overlapping_boxes, const Box &box) const
Find box partitions overlapping the given box.
size_t selfCheck () const
Check the assumed partition for errors and inconsistencies. Write error diagnostics to plog.
void recursivePrint (std::ostream &os, const std::string &border, int detail_depth=2) const
Print info from this object.
Detailed Description
Compute an assumed partition of a box. The assumed partition should very fast to create and query and requires minimal storage.
An assumed partition avoids extreme imbalances, but its purpose is not fine load balancing.
Constructor & Destructor Documentation
SAMRAI::hier::AssumedPartitionBox::AssumedPartitionBox (const Box & unpartitioned_box, int rank_begin, int rank_end, int index_begin = 0, double avg_parts_per_rank = 1.0, bool interleave = false)
Construct AssumedPartition from a box.
Parameters:
[in] unpartitioned_box Incoming unpartitioned box
[in] rank_begin First rank
[in] rank_end One past last rank
[in] index_begin First index
[in] avg_parts_per_rank See partition()
[in] interleave See partition()
SAMRAI::hier::AssumedPartitionBox::AssumedPartitionBox (const tbox::Dimension & dim)
Nearly default constructor.
SAMRAI::hier::AssumedPartitionBox::~AssumedPartitionBox () [inline]
Destructor.
Member Function Documentation
void SAMRAI::hier::AssumedPartitionBox::partition (const Box & unpartitioned_box, int rank_begin, int rank_end, int index_begin = 0, double avg_parts_per_rank = 1.0, bool interleave = false)
Partition the given box, discarding the current state.
The partition should degerate correctly if the box is empty, i.e., the partition size and count should be zero.
Parameters:
[in] unpartitioned_box Incoming unpartitioned box
[in] rank_begin First rank
[in] rank_end One past last rank
[in] index_begin
[in] avg_parts_per_rank Algorithm normally tries to get one partition per rank. This parameter is a request to change that.
[in] interleave Algorithm normally assign consecutive box indices to a process. This flag causes it to interleave (round-robin) the box assignments.
const Box& SAMRAI::hier::AssumedPartitionBox::getUnpartitionedBox () const [inline]
Return the original unpartitioned box.
int SAMRAI::hier::AssumedPartitionBox::getNumberOfParts () const [inline]
Number of box partitions.
Referenced by getOwner().
int SAMRAI::hier::AssumedPartitionBox::getOwner (int box_index) const
Return the owner for a box.
References SAMRAI::tbox::SAMRAI_MPI::getInvalidRank(), getNumberOfParts(), and TBOX_ASSERT.
Referenced by getBox(), and selfCheck().
Box SAMRAI::hier::AssumedPartitionBox::getBox (int box_index) const
Return box for given index.
References SAMRAI::hier::Box::getDim(), SAMRAI::hier::IntVector::getOne(), getOwner(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and TBOX_ASSERT.
Referenced by findOverlaps(), getAllBoxes(), recursivePrint(), and selfCheck().
Box SAMRAI::hier::AssumedPartitionBox::getBox (const IntVector & position) const
Return box for given partition's position in the partition grid.
References SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getDim(), getOwner(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Box::lower(), and TBOX_ASSERT.
void SAMRAI::hier::AssumedPartitionBox::getAllBoxes (BoxContainer & all_boxes) const
Get all partition boxes.
References begin(), end(), getBox(), and SAMRAI::hier::BoxContainer::push_back().
void SAMRAI::hier::AssumedPartitionBox::getAllBoxes (BoxContainer & all_boxes, int rank) const
Get all partition boxes owned by a given rank.
References beginOfRank(), endOfRank(), getBox(), and SAMRAI::hier::BoxContainer::push_back().
int SAMRAI::hier::AssumedPartitionBox::begin () const [inline]
Return index of first partition box.
Referenced by getAllBoxes(), recursivePrint(), and selfCheck().
int SAMRAI::hier::AssumedPartitionBox::end () const [inline]
Return one past index of last partition box.
Referenced by getAllBoxes(), recursivePrint(), and selfCheck().
int SAMRAI::hier::AssumedPartitionBox::beginOfRank (int rank) const
Return index of first box in the contiguous index range assigned to given rank.
This method should not be used for objects when the ranks are interleaved.
If rank is lower than ranks in partitioning, return first index. If rank is higher than ranks in partitioning, return one past last index.
References TBOX_ERROR.
Referenced by getAllBoxes(), and selfCheck().
int SAMRAI::hier::AssumedPartitionBox::endOfRank (int rank) const
Return one past index of last box in the contiguous index range assigned to given rank.
This method should not be used for objects when the ranks are interleaved.
If rank is lower than ranks in partitioning, return first index. If rank is higher than ranks in partitioning, return one past last index.
References TBOX_ERROR.
Referenced by getAllBoxes(), and selfCheck().
bool SAMRAI::hier::AssumedPartitionBox::findOverlaps (BoxContainer & overlapping_boxes, const Box & box) const
Find box partitions overlapping the given box.
The search cost is proportional to number of overlapping boxes found, NOT the total number of partitions.
Parameters:
[out] overlapping_boxes
[in] box
Returns:
Whether any partitions are found.
References SAMRAI::hier::Box::begin(), SAMRAI::hier::Box::coarsen(), SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::end(), SAMRAI::hier::Box::getBlockId(), getBox(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::IntVector::getZero(), and SAMRAI::hier::BoxContainer::insert().
size_t SAMRAI::hier::AssumedPartitionBox::selfCheck () const
Check the assumed partition for errors and inconsistencies. Write error diagnostics to plog.
Returns:
Number of errors found. (Errors indicate a bug in this class.)
References SAMRAI::hier::BoxContainer::begin(), begin(), beginOfRank(), SAMRAI::hier::BoxContainer::clear(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), end(), endOfRank(), SAMRAI::hier::BoxContainer::erase(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::BoxContainer::findOverlapBoxes(), SAMRAI::hier::BoxContainer::format(), SAMRAI::hier::Box::getBlockId(), getBox(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::SAMRAI_MPI::getInvalidRank(), SAMRAI::hier::IntVector::getOne(), getOwner(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::makeTree(), SAMRAI::hier::BoxContainer::order(), SAMRAI::tbox::plog, SAMRAI::hier::BoxContainer::pushBack(), SAMRAI::hier::BoxContainer::removeIntersections(), SAMRAI::hier::BoxContainer::size(), and SAMRAI::hier::BoxContainer::unorder().
void SAMRAI::hier::AssumedPartitionBox::recursivePrint (std::ostream & os, const std::string & border, int detail_depth = 2) const
Print info from this object.
Parameters:
[in,out] os The output stream
[in] border
[in] detail_depth
References begin(), end(), SAMRAI::hier::BoxContainer::format(), getBox(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::BoxContainer::pushBack(), and SAMRAI::hier::Box::size().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/AssumedPartitionBox.h
source/SAMRAI/hier/AssumedPartitionBox.C