SAMRAI: SAMRAI::math::PatchNodeDataOpsInteger Class Reference
SAMRAI::math::PatchNodeDataOpsInteger Class Reference
#include <source/SAMRAI/math/PatchNodeDataOpsInteger.h>
Public Member Functions
PatchNodeDataOpsInteger ()
virtual ~PatchNodeDataOpsInteger ()
size_t numberOfEntries (const boost::shared_ptr< pdat::NodeData< int > > &data, const hier::Box &box) const
void copyData (const boost::shared_ptr< pdat::NodeData< int > > &dst, const boost::shared_ptr< pdat::NodeData< int > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::NodeData< int > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::NodeData< int > > &dst, const int &alpha, const hier::Box &box) const
void abs (const boost::shared_ptr< pdat::NodeData< int > > &dst, const boost::shared_ptr< pdat::NodeData< int > > &src, const hier::Box &box) const
Detailed Description
Class PatchNodeDataOpsInteger provides a collection of operations that may be used to manipulate integer node-centered patch data. The operations include basic arithmetic, min, max, etc. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base class PatchNodeDataBasicOps from which it is derived.
A more extensive set of operations is implemented for real (double and float) and complex patch data in the classes PatchNodeDataOpsReal and PatchNodeDataOpsComplex, repsectively.
See also:
PatchNodeDataBasicOps
Constructor & Destructor Documentation
SAMRAI::math::PatchNodeDataOpsInteger::PatchNodeDataOpsInteger ()
Empty constructor and destructor.
SAMRAI::math::PatchNodeDataOpsInteger::~PatchNodeDataOpsInteger () [virtual]
Member Function Documentation
size_t SAMRAI::math::PatchNodeDataOpsInteger::numberOfEntries (const boost::shared_ptr< pdat::NodeData< int > > & data, const hier::Box & box) const [inline]
Return the number of data values for the node-centered data object in the given box. Note that it is assumed that the box refers to the cell-centered index space corresponding to the patch hierarchy.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::NodeGeometry::toNodeBox().
Referenced by SAMRAI::math::HierarchyNodeDataOpsInteger::numberOfEntries().
void SAMRAI::math::PatchNodeDataOpsInteger::copyData (const boost::shared_ptr< pdat::NodeData< int > > & dst, const boost::shared_ptr< pdat::NodeData< int > > & src, const hier::Box & box) const [inline]
Copy dst data to src data over given box.
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::NodeGeometry::toNodeBox().
Referenced by SAMRAI::math::HierarchyNodeDataOpsInteger::copyData().
void SAMRAI::math::PatchNodeDataOpsInteger::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects iare checked for consistency of depth, box, and ghost box.
Precondition:
patch
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::NodeData<int> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::NodeData<int> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsInteger::swapData().
void SAMRAI::math::PatchNodeDataOpsInteger::printData (const boost::shared_ptr< pdat::NodeData< int > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyNodeDataOpsInteger::printData().
void SAMRAI::math::PatchNodeDataOpsInteger::setToScalar (const boost::shared_ptr< pdat::NodeData< int > > & dst, const int & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyNodeDataOpsInteger::setToScalar().
void SAMRAI::math::PatchNodeDataOpsInteger::abs (const boost::shared_ptr< pdat::NodeData< int > > & dst, const boost::shared_ptr< pdat::NodeData< int > > & src, const hier::Box & box) const [inline]
Set destination component to absolute value of source component. That is, each destination entry is set to .
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsInteger::abs(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::NodeGeometry::toNodeBox().
Referenced by SAMRAI::math::HierarchyNodeDataOpsInteger::abs().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchNodeDataOpsInteger.h
source/SAMRAI/math/PatchNodeDataOpsInteger.C