SAMRAI: SAMRAI::hier::PatchGeometry::TwoDimBool Class Reference
SAMRAI::hier::PatchGeometry::TwoDimBool Class Reference
Array of 2*DIM booleans (with default constructor), used to instantiate the sparse container map<LocalId,TwoDimBool> (map<LocalId,bool[2*DIM]> does not work).
#include <source/SAMRAI/hier/PatchGeometry.h>
Public Member Functions
TwoDimBool (const tbox::Dimension &dim)
TwoDimBool (const tbox::Dimension &dim, bool v)
void setAll (bool v)
bool & operator() (int dim, int side)
const bool & operator() (int dim, int side) const
const tbox::Dimension & getDim () const
Detailed Description
Array of 2*DIM booleans (with default constructor), used to instantiate the sparse container map<LocalId,TwoDimBool> (map<LocalId,bool[2*DIM]> does not work).
Constructor & Destructor Documentation
SAMRAI::hier::PatchGeometry::TwoDimBool::TwoDimBool (const tbox::Dimension & dim) [explicit]
References setAll().
SAMRAI::hier::PatchGeometry::TwoDimBool::TwoDimBool (const tbox::Dimension & dim, bool v)
References SAMRAI::tbox::Dimension::getValue().
Member Function Documentation
void SAMRAI::hier::PatchGeometry::TwoDimBool::setAll (bool v) [inline]
References SAMRAI::tbox::Dimension::getValue().
Referenced by TwoDimBool().
bool& SAMRAI::hier::PatchGeometry::TwoDimBool::operator() (int dim, int side) [inline]
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
const bool& SAMRAI::hier::PatchGeometry::TwoDimBool::operator() (int dim, int side) const [inline]
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
const tbox::Dimension& SAMRAI::hier::PatchGeometry::TwoDimBool::getDim () const [inline]
Return the dimension of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchGeometry.h
source/SAMRAI/hier/PatchGeometry.C