SAMRAI: SAMRAI::mesh::BalanceBoxBreaker Class Reference
SAMRAI::mesh::BalanceBoxBreaker Class Reference
Utilities for breaking up boxes during partitioning.
#include <source/SAMRAI/mesh/BalanceBoxBreaker.h>
Public Member Functions
BalanceBoxBreaker (const PartitioningParams &pparams, bool print_break_steps=false)
Constructor.
BalanceBoxBreaker (const BalanceBoxBreaker &other)
Copy constructor.
bool breakOffLoad (hier::BoxContainer &breakoff, hier::BoxContainer &leftover, double &brk_load, const hier::Box &box, double box_load, const std::vector< double > &corner_weights, double ideal_load, double low_load, double high_load, double threshold_width) const
Break off a given load size from a given Box.
void setPrintBreakSteps (bool print_break_steps)
Set whether to print box breaking steps for debugging.
Static Public Member Functions
static void burstBox (hier::BoxContainer &boxes, const hier::Box &bursty, const hier::Box &solid)
Break up box bursty against box solid and adds the pieces in the given container.
static double computeBalancePenalty (double imbalance)
Compute the penalty associated with an imbalance.
static double computeWidthScore (const hier::IntVector &box_size, double threshold_width)
Compute a score that is low for box widths smaller than some threshold_width.
static double computeWidthScore (const hier::BoxContainer &boxes, double threshold_width)
Compute a combined width score for multiple boxes.
Friends
std::ostream & operator<< (std::ostream &os, const TrialBreak &tb)
Detailed Description
Utilities for breaking up boxes during partitioning.
Constructor & Destructor Documentation
SAMRAI::mesh::BalanceBoxBreaker::BalanceBoxBreaker (const PartitioningParams & pparams, bool print_break_steps = false)
Constructor.
Parameters:
[in] pparams
[in] print_break_steps Flag for debugging this class.
SAMRAI::mesh::BalanceBoxBreaker::BalanceBoxBreaker (const BalanceBoxBreaker & other)
Copy constructor.
Member Function Documentation
bool SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad (hier::BoxContainer & breakoff, hier::BoxContainer & leftover, double & brk_load, const hier::Box & box, double box_load, const std::vector< double > & corner_weights, double ideal_load, double low_load, double high_load, double threshold_width) const
Break off a given load size from a given Box.
Attempt to break off the ideal_load, or at least a load inside the range [low_load, high_load].
Parameters:
[out] breakoff Boxes broken off (usually just one).
[out] leftover Remainder of box after breakoff is gone.
[out] brk_load The load broken off.
[in] box Box to break.
[in] corner_weights Fraction of the total load associated with each corner.
[in] box_load Load of the box before breaking.
[in] ideal_load Ideal load to break.
[in] low_load
[in] high_load
[in] threshold_width Try to avoid making boxes thinner than this width in any direction.
Returns:
whether a successful break was made.
Precondition:
ideal_load_to_break > 0
References SAMRAI::hier::BoxContainer::clear(), computeBalancePenalty(), computeWidthScore(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxUtilities::findBadCutPoints(), SAMRAI::mesh::PartitioningParams::getBadInterval(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getDim(), SAMRAI::mesh::PartitioningParams::getDomainBoxes(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::numberCells(), SAMRAI::tbox::plog, SAMRAI::hier::Box::size(), SAMRAI::hier::BoxContainer::swap(), and TBOX_ASSERT.
void SAMRAI::mesh::BalanceBoxBreaker::setPrintBreakSteps (bool print_break_steps) [inline]
Set whether to print box breaking steps for debugging.
Referenced by SAMRAI::mesh::BoxTransitSet::BoxTransitSet().
void SAMRAI::mesh::BalanceBoxBreaker::burstBox (hier::BoxContainer & boxes, const hier::Box & bursty, const hier::Box & solid) [static]
Break up box bursty against box solid and adds the pieces in the given container.
This version differs from that in BoxContainer in that it tries to minimize slivers.
References SAMRAI::hier::BoxContainer::clear(), SAMRAI::hier::Box::contains(), SAMRAI::hier::Box::isSpatiallyEqual(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::BoxContainer::push_back(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, and SAMRAI::hier::Box::upper().
static double SAMRAI::mesh::BalanceBoxBreaker::computeBalancePenalty (double imbalance) [inline, static]
Compute the penalty associated with an imbalance.
Referenced by breakOffLoad().
double SAMRAI::mesh::BalanceBoxBreaker::computeWidthScore (const hier::IntVector & box_size, double threshold_width) [static]
Compute a score that is low for box widths smaller than some threshold_width.
References SAMRAI::hier::IntVector::min().
Referenced by breakOffLoad(), and computeWidthScore().
double SAMRAI::mesh::BalanceBoxBreaker::computeWidthScore (const hier::BoxContainer & boxes, double threshold_width) [static]
Compute a combined width score for multiple boxes.
References SAMRAI::hier::BoxContainer::begin(), computeWidthScore(), and SAMRAI::hier::BoxContainer::end().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const TrialBreak & tb) [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/BalanceBoxBreaker.h
source/SAMRAI/mesh/BalanceBoxBreaker.C