SAMRAI: SAMRAI::xfer::RefineScheduleConnectorWidthRequestor Class Reference
SAMRAI::xfer::RefineScheduleConnectorWidthRequestor Class Reference
Implementation of the strategy class hier::PatchHierarchy::ConnectorWidthRequestorStrategy to tell the hier::PatchHierarchy how wide RefineSchedule needs Connectors between hierarchy levels to be.
#include <source/SAMRAI/xfer/RefineScheduleConnectorWidthRequestor.h>
Public Member Functions
RefineScheduleConnectorWidthRequestor ()
Constructor.
void computeRequiredConnectorWidths (std::vector< hier::IntVector > &self_connector_widths, std::vector< hier::IntVector > &fine_connector_widths, const hier::PatchHierarchy &patch_hierarchy) const
Compute Connector widths that this class requires in order to work properly on a given hierarchy.
void setGhostCellWidthFactor (int gcw_factor)
Set the factor by which the ghost data widths in the PatchHierarchy are multiplied to increase their effective values. for the purpose of handling more ghost data than registered.
void computeRequiredFineConnectorWidthsForRecursiveRefinement (std::vector< hier::IntVector > &fine_connector_widths, const hier::IntVector &data_gcw_on_initial_dst_ln, const hier::IntVector &max_stencil_width, const hier::PatchHierarchy &patch_hierarchy, int initial_dst_ln) const
Detailed Description
Implementation of the strategy class hier::PatchHierarchy::ConnectorWidthRequestorStrategy to tell the hier::PatchHierarchy how wide RefineSchedule needs Connectors between hierarchy levels to be.
Constructor & Destructor Documentation
SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::RefineScheduleConnectorWidthRequestor ()
Constructor.
Member Function Documentation
void SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths (std::vector< hier::IntVector > & self_connector_widths, std::vector< hier::IntVector > & fine_connector_widths, const hier::PatchHierarchy & patch_hierarchy) const
Compute Connector widths that this class requires in order to work properly on a given hierarchy.
Implements the pure virtual method hier::PatchHierarchy::ConnectorWidthRequestorStrategy::computeRequiredConnectorWidths()
Parameters:
[out] self_connector_widths Array of widths for Connectors from a level to itself.
[out] fine_connector_widths Array of widths for Connectors from a level to the next finer level.
[in] patch_hierarchy
References computeRequiredFineConnectorWidthsForRecursiveRefinement(), SAMRAI::hier::PatchHierarchy::getDim(), SAMRAI::hier::PatchHierarchy::getGridGeometry(), SAMRAI::hier::PatchHierarchy::getMaxNumberOfLevels(), SAMRAI::xfer::RefinePatchStrategy::getMaxRefineOpStencilWidth(), SAMRAI::hier::PatchHierarchy::getPatchDescriptor(), and SAMRAI::hier::IntVector::getZero().
Referenced by SAMRAI::mesh::StandardTagAndInitializeConnectorWidthRequestor::computeRequiredConnectorWidths().
void SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::setGhostCellWidthFactor (int gcw_factor)
Set the factor by which the ghost data widths in the PatchHierarchy are multiplied to increase their effective values. for the purpose of handling more ghost data than registered.
We support values of ghost data width that are larger than those registered by some factor. An example of the need is when we fill a PatchLevel that is a coarsened version of a current level in the hierarchy. Coarsening the level effectively increases the size of the ghost data region because the coarse cells are bigger.
Note that the Connector widths are not linear functions of this factor. Increasing the factor is NOT the same as multiplying the Connector widths by the same factor.
Parameters:
[in] gcw_factor By default, gcw_factor=1.
Precondition:
gcw_factor >= 0
References TBOX_ASSERT.
Referenced by SAMRAI::mesh::StandardTagAndInitializeConnectorWidthRequestor::computeRequiredConnectorWidths(), and SAMRAI::xfer::RefineSchedule::RefineSchedule().
void SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredFineConnectorWidthsForRecursiveRefinement (std::vector< hier::IntVector > & fine_connector_widths, const hier::IntVector & data_gcw_on_initial_dst_ln, const hier::IntVector & max_stencil_width, const hier::PatchHierarchy & patch_hierarchy, int initial_dst_ln) const
References SAMRAI::hier::IntVector::ceilingDivide(), SAMRAI::hier::PatchHierarchy::getDim(), SAMRAI::hier::PatchHierarchy::getRatioToCoarserLevel(), SAMRAI::hier::IntVector::getZero(), and SAMRAI::hier::IntVector::max().
Referenced by computeRequiredConnectorWidths(), and SAMRAI::xfer::RefineSchedule::RefineSchedule().
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/RefineScheduleConnectorWidthRequestor.h
source/SAMRAI/xfer/RefineScheduleConnectorWidthRequestor.C