SAMRAI: SAMRAI::pdat::EdgeIndex Class Reference
SAMRAI::pdat::EdgeIndex Class Reference
#include <source/SAMRAI/pdat/EdgeIndex.h>
Public Types
enum {
X = 0, Y = 1, Z = 2, Lower = 0,
Upper = 1, LowerLeft = 0, LowerRight = 1, UpperLeft = 2,
UpperRight = 3
}
Public Member Functions
EdgeIndex (const tbox::Dimension &dim)
EdgeIndex (const hier::Index &rhs, const int axis, const int edge)
EdgeIndex (const EdgeIndex &rhs)
EdgeIndex & operator= (const EdgeIndex &rhs)
~EdgeIndex ()
int getAxis () const
void setAxis (const int axis)
hier::Index toCell (const int edge) const
EdgeIndex & operator+= (const hier::IntVector &rhs)
EdgeIndex operator+ (const hier::IntVector &rhs) const
EdgeIndex & operator+= (const int rhs)
EdgeIndex operator+ (const int rhs) const
EdgeIndex & operator-= (const hier::IntVector &rhs)
EdgeIndex operator- (const hier::IntVector &rhs) const
EdgeIndex & operator-= (const int rhs)
EdgeIndex operator- (const int rhs) const
EdgeIndex & operator*= (const hier::IntVector &rhs)
EdgeIndex operator* (const hier::IntVector &rhs) const
EdgeIndex & operator*= (const int rhs)
EdgeIndex operator* (const int rhs) const
bool operator== (const EdgeIndex &rhs) const
bool operator!= (const EdgeIndex &rhs) const
Detailed Description
Class EdgeIndex implements a simple n-dimensional integer vector for edge centered variables. Edge indices contain an integer index location in AMR index space along with the designated edge axis (X=0, Y=1, or Z=2). See the edge box geometry class for more information about the mapping between the AMR index space and the edge indices.
See also:
hier::Index
pdat::EdgeData
pdat::EdgeGeometry
pdat::EdgeIterator
Member Enumeration Documentation
anonymous enum
Enumerator:
X
Y
Z
Lower
Upper
LowerLeft
LowerRight
UpperLeft
UpperRight
Constructor & Destructor Documentation
SAMRAI::pdat::EdgeIndex::EdgeIndex (const tbox::Dimension & dim) [explicit]
The default constructor for a edge index creates an uninitialized index.
SAMRAI::pdat::EdgeIndex::EdgeIndex (const hier::Index & rhs, const int axis, const int edge)
Construct a edge index from a regular index, axis, and edge. The axis can be one of EdgeIndex::X (0), EdgeIndex::Y (1), or EdgeIndex::Z (2). The edge argument can be one of the constants EdgeIndex::LowerLeft (0), EdgeIndex::LowerRight(1), EdgeIndex::UpperLeft (2) or EdgeIndex::UpperRight(3).
References SAMRAI::hier::IntVector::getDim(), and SAMRAI::tbox::Dimension::getValue().
SAMRAI::pdat::EdgeIndex::EdgeIndex (const EdgeIndex & rhs)
The copy constructor creates a edge index equal to the argument.
SAMRAI::pdat::EdgeIndex::~EdgeIndex ()
The edge index destructor does nothing interesting.
Member Function Documentation
EdgeIndex& SAMRAI::pdat::EdgeIndex::operator= (const EdgeIndex & rhs) [inline]
The assignment operator sets the edge index equal to the argument.
Reimplemented from SAMRAI::hier::Index.
int SAMRAI::pdat::EdgeIndex::getAxis () const [inline]
Get the axis for which this edge index is defined (X=0, Y=1, Z=2).
Referenced by SAMRAI::pdat::OuteredgeData< TYPE >::operator()(), SAMRAI::pdat::EdgeData< TYPE >::operator()(), and SAMRAI::pdat::EdgeGeometry::transform().
void SAMRAI::pdat::EdgeIndex::setAxis (const int axis) [inline]
Set the edge axis (X=0, Y=1, Z=2).
Referenced by SAMRAI::pdat::EdgeGeometry::transform().
hier::Index SAMRAI::pdat::EdgeIndex::toCell (const int edge) const
For dimension 2, converts the edge index into the index on the lower side (argument edge = 0) or the upper side (argument edge = 1) of the edge. For dimension 3, converts the edge index into the index on the lower left (argument edge == 0), the lower right (argument edge == 1), the upper left (argument edge == 2), or the upper right (argument edge == 3) of the edge.
TODO: I find the above comment confusing.
References SAMRAI::hier::IntVector::getDim(), and SAMRAI::tbox::Dimension::getValue().
EdgeIndex& SAMRAI::pdat::EdgeIndex::operator+= (const hier::IntVector & rhs) [inline]
Plus-equals operator for a edge index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator+=().
EdgeIndex SAMRAI::pdat::EdgeIndex::operator+ (const hier::IntVector & rhs) const [inline]
Plus operator for a edge index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
EdgeIndex& SAMRAI::pdat::EdgeIndex::operator+= (const int rhs) [inline]
Plus-equals operator for a edge index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator+=().
EdgeIndex SAMRAI::pdat::EdgeIndex::operator+ (const int rhs) const [inline]
Plus operator for a edge index and an integer.
Reimplemented from SAMRAI::hier::Index.
EdgeIndex& SAMRAI::pdat::EdgeIndex::operator-= (const hier::IntVector & rhs) [inline]
Minus-equals operator for a edge index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator-=().
EdgeIndex SAMRAI::pdat::EdgeIndex::operator- (const hier::IntVector & rhs) const [inline]
Minus operator for a edge index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
EdgeIndex& SAMRAI::pdat::EdgeIndex::operator-= (const int rhs) [inline]
Minus-equals operator for a edge index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator-=().
EdgeIndex SAMRAI::pdat::EdgeIndex::operator- (const int rhs) const [inline]
Minus operator for a edge index and an integer.
Reimplemented from SAMRAI::hier::Index.
EdgeIndex& SAMRAI::pdat::EdgeIndex::operator*= (const hier::IntVector & rhs) [inline]
Times-equals operator for a edge index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator*=().
EdgeIndex SAMRAI::pdat::EdgeIndex::operator* (const hier::IntVector & rhs) const [inline]
Times operator for a edge index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
EdgeIndex& SAMRAI::pdat::EdgeIndex::operator*= (const int rhs) [inline]
Times-equals operator for a edge index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator*=().
EdgeIndex SAMRAI::pdat::EdgeIndex::operator* (const int rhs) const [inline]
Times operator for a edge index and an integer.
Reimplemented from SAMRAI::hier::Index.
bool SAMRAI::pdat::EdgeIndex::operator== (const EdgeIndex & rhs) const [inline]
Returns true if two edge index objects are equal. All components and the corresponding edge axes must be the same for equality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::IntVector.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::pdat::EdgeIndex::operator!= (const EdgeIndex & rhs) const [inline]
Returns true if two edge index objects are not equal. Any of the components or axes may be different for inequality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::IntVector.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/EdgeIndex.h
source/SAMRAI/pdat/EdgeIndex.C