SAMRAI: SAMRAI::hier::PatchLevel Class Reference
SAMRAI::hier::PatchLevel Class Reference
Container class for patches defined at a single level of the AMR hierarchy.
#include <source/SAMRAI/hier/PatchLevel.h>
Classes
class Iterator
Iterator for looping through local patches.
Public Types
typedef Iterator iterator
Typdef PatchLevel::Iterator to standard iterator nomenclature.
Public Member Functions
PatchLevel (const tbox::Dimension &dim)
Default constructor. PatchLevel must be initialized before it can be used.
PatchLevel (const BoxLevel &box_level, const boost::shared_ptr< BaseGridGeometry > &grid_geometry, const boost::shared_ptr< PatchDescriptor > &descriptor, const boost::shared_ptr< PatchFactory > &factory=boost::shared_ptr< PatchFactory >(), bool defer_boundary_box_creation=false)
Construct a new patch level given a BoxLevel.
PatchLevel (const boost::shared_ptr< BoxLevel > box_level, const boost::shared_ptr< BaseGridGeometry > &grid_geometry, const boost::shared_ptr< PatchDescriptor > &descriptor, const boost::shared_ptr< PatchFactory > &factory=boost::shared_ptr< PatchFactory >(), bool defer_boundary_box_creation=false)
Construct a new patch level given a BoxLevel.
PatchLevel (const boost::shared_ptr< tbox::Database > &restart_database, const boost::shared_ptr< BaseGridGeometry > &grid_geometry, const boost::shared_ptr< PatchDescriptor > &descriptor, const boost::shared_ptr< PatchFactory > &factory, bool defer_boundary_box_creation=false)
Construct a new patch level from the specified PatchLevel restart database.
virtual ~PatchLevel ()
The virtual destructor for patch level deallocates all patches.
int getLevelNumber () const
Get the level number.
void setLevelNumber (const int level)
Set the number of this level to the level in the hierarchy aligning with the index space of this level.
int getNextCoarserHierarchyLevelNumber () const
Convenience method to get the next coarser level number in a hierarchy.
void setNextCoarserHierarchyLevelNumber (const int level)
Convenience method to set the number of of the next coarser level in a hierarchy.
bool inHierarchy () const
Determine if this level resides in a hierarchy.
void setLevelInHierarchy (bool in_hierarchy)
Setting to indicate whether this level resides in a hierarchy.
int getNumberOfPatches () const
Get the number of patches.
int getLocalNumberOfPatches () const
Get the local number of patches.
int getGlobalNumberOfPatches () const
Get the global number of patches.
int getLocalNumberOfCells () const
Get the local number of Cells.
long int getGlobalNumberOfCells () const
Get the global number of cells.
const boost::shared_ptr< Patch > & getPatch (const GlobalId &gid) const
Get a Patch based on its GlobalId.
boost::shared_ptr< Patch > getPatch (const BoxId &mbid) const
Get a Patch based on its BoxId.
const boost::shared_ptr< Patch > & getPatch (size_t index) const
Get a patch using a random access index.
boost::shared_ptr
< PatchDescriptor > getPatchDescriptor () const
Get the PatchDescriptor.
boost::shared_ptr< PatchFactory > getPatchFactory () const
Get the PatchFactory.
boost::shared_ptr
< BaseGridGeometry > getGridGeometry () const
Get the grid geometry.
void setRefinedPatchLevel (const boost::shared_ptr< PatchLevel > &coarse_level, const IntVector &refine_ratio, const boost::shared_ptr< BaseGridGeometry > &fine_grid_geometry=boost::shared_ptr< BaseGridGeometry >(), bool defer_boundary_box_creation=false)
Update this patch level through refining.
void setCoarsenedPatchLevel (const boost::shared_ptr< PatchLevel > &fine_level, const IntVector &coarsen_ratio, const boost::shared_ptr< BaseGridGeometry > &coarse_grid_geom=boost::shared_ptr< BaseGridGeometry >(), bool defer_boundary_box_creation=false)
Update this patch through coarsening.
void setBoundaryBoxes ()
Create and store the boundary boxes for this level.
const std::vector< BoxContainer > & getPhysicalDomainArray () const
Get the physical domain.
const BoxContainer & getPhysicalDomain (const BlockId &block_id) const
const BoxContainer & getBoxes () const
Get the box defining the patches on the level.
void getBoxes (BoxContainer &boxes, const BlockId &block_id) const
Get boxes for a particular block.
const boost::shared_ptr
< BoxLevel > & getBoxLevel () const
Get the BoxLevel associated with the PatchLevel.
const BoxLevel & getGlobalizedBoxLevel () const
Get the globalized version of the BoxLevel associated with the PatchLevel.
const ProcessorMapping & getProcessorMapping () const
Get the mapping of patches to processors.
const IntVector & getRatioToLevelZero () const
Get the ratio between the index space of this PatchLevel and the reference level in the AMR hierarchy.
const IntVector & getRatioToCoarserLevel () const
Get the ratio between this level and the next coarser level in the patch hierarchy.
void setRatioToCoarserLevel (const IntVector &ratio)
Set the ratio between this level and the next coarser level in the patch hierarchy.
int getMappingForPatch (const BoxId &box_id) const
Get the processor mapping for the patch.
const Box & getBoxForPatch (const BoxId &box_id) const
Get the box for the specified patch.
bool patchTouchesRegularBoundary (const BoxId &box_id) const
Determine if the patch is adjacent to a non-periodic physical domain boundary.
void allocatePatchData (const int id, const double timestamp=0.0)
Allocate the specified component on all patches.
void allocatePatchData (const ComponentSelector &components, const double timestamp=0.0)
Allocate the specified components on all patches.
bool checkAllocated (const int id) const
Determine if the patch data has been allocated.
void deallocatePatchData (const int id)
Deallocate the specified component on all patches.
void deallocatePatchData (const ComponentSelector &components)
Deallocate the specified components on all patches.
const tbox::Dimension & getDim () const
Get the dimension of this object.
void setTime (const double timestamp, const int id)
Set the simulation time for the specified patch component.
void setTime (const double timestamp, const ComponentSelector &components)
Set the simulation time for the specified patch components.
void setTime (const double timestamp)
Set the simulation time for all allocated patch components.
const Connector & findConnector (const PatchLevel &head, const IntVector &min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only=false) const
Find an overlap Connector with the given PatchLevel's BoxLevel as its head and minimum Connector width. If the specified Connector is not found, take the specified action.
const Connector & findConnectorWithTranspose (const PatchLevel &head, const IntVector &min_connector_width, const IntVector &transpose_min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only=false) const
Find an overlap Connector with its transpose with the given PatchLevel's BoxLevel as its head and minimum Connector widths. If the specified Connector is not found, take the specified action.
const Connector & createConnector (const PatchLevel &head, const IntVector &connector_width) const
Create an overlap Connector, computing relationships by globalizing data.
const Connector & createConnectorWithTranspose (const PatchLevel &head, const IntVector &connector_width, const IntVector &transpose_connector_width) const
Create an overlap Connector with its transpose, computing relationships by globalizing data.
void cacheConnector (boost::shared_ptr< Connector > &connector) const
Cache the supplied overlap Connector and its transpose if it exists.
bool hasConnector (const PatchLevel &head, const IntVector &min_connector_width, bool exact_width_only=false) const
Returns whether the object has overlap Connectors with the given PatchLevel's BoxLevel as the head and minimum Connector width.
void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
Use the PatchLevel restart database to set the state of the PatchLevel and to create all patches on the local processor.
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write data to the restart database.
int recursivePrint (std::ostream &os, const std::string &border=std::string(), int depth=0)
Print a patch level to varying details.
Iterator begin () const
Construct an iterator pointing to the first Patch in the PatchLevel.
Iterator end () const
Construct an iterator pointing to the last Patch in the PatchLevel.
Detailed Description
Container class for patches defined at a single level of the AMR hierarchy.
The patches in a patch level are distributed across the processors of a parallel machine, so not all patches reside on the local processor. (However, each patch is assigned to one and only one processor.)
To iterate over the local patches in a patch level, use the patch level iterator class (PatchLevel::Iterator).
See also:
hier::BasePatchLevel
hier::Patch
hier::PatchDescriptor
hier::PatchFactory
hier::PatchLevelFactory
hier::PatchLevel::Iterator
Member Typedef Documentation
typedef Iterator SAMRAI::hier::PatchLevel::iterator
Typdef PatchLevel::Iterator to standard iterator nomenclature.
Constructor & Destructor Documentation
SAMRAI::hier::PatchLevel::PatchLevel (const tbox::Dimension & dim) [explicit]
Default constructor. PatchLevel must be initialized before it can be used.
SAMRAI::hier::PatchLevel::PatchLevel (const BoxLevel & box_level, const boost::shared_ptr< BaseGridGeometry > & grid_geometry, const boost::shared_ptr< PatchDescriptor > & descriptor, const boost::shared_ptr< PatchFactory > & factory = boost::shared_ptr<PatchFactory>(), bool defer_boundary_box_creation = false)
Construct a new patch level given a BoxLevel.
This constructor makes a COPY of the supplied BoxLevel. If the caller intends to modify the supplied BoxLevel for other purposes after creating this PatchLevel, then this constructor must be used rather than the constructor taking a boost::shared_ptr<BoxLevel>.
The BoxLevel provides refinement ratio information, establishing the ratio between the index space of the new level and some reference level (typically level zero) in some patch hierarchy.
The ratio information provided by the BoxLevel is also used by the grid geometry instance to initialize geometry information of both the level and the patches on that level.
Parameters:
[in] box_level
[in] grid_geometry
[in] descriptor The PatchDescriptor used to allocate patch data on the local processor
[in] factory Optional PatchFactory. If none specified, a default (standard) patch factory will be used.
[in] defer_boundary_box_creation Flag to indicate suppressing construction of the boundary boxes.
Precondition:
grid_geometry
descriptor
box_level.getDim() == grid_geometry->getDim()
box_level.getRefinementRatio() != IntVector::getZero(getDim())
all components of box_level's refinement ratio must be nonzero and, all components not equal to 1 must have the same sign
References SAMRAI::hier::Box::getBoxId(), getDim(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::hier::PatchLevel::PatchLevel (const boost::shared_ptr< BoxLevel > box_level, const boost::shared_ptr< BaseGridGeometry > & grid_geometry, const boost::shared_ptr< PatchDescriptor > & descriptor, const boost::shared_ptr< PatchFactory > & factory = boost::shared_ptr<PatchFactory>(), bool defer_boundary_box_creation = false)
Construct a new patch level given a BoxLevel.
This constructor ACQUIRES the supplied BoxLevel. If the caller will not modify the supplied BoxLevel for other purposes after creating this PatchLevel, then this constructor may be used rather than the constructor taking a BoxLevel&. Use of this constructor where permitted is more efficient as it avoids copying an entire BoxLevel. Note that this constructor locks the supplied BoxLevel so that any attempt by the caller to modify it after calling this constructor will result in an unrecoverable error.
The BoxLevel provides refinement ratio information, establishing the ratio between the index space of the new level and some reference level (typically level zero) in some patch hierarchy.
The ratio information provided by the BoxLevel is also used by the grid geometry instance to initialize geometry information of both the level and the patches on that level.
Parameters:
[in] box_level
[in] grid_geometry
[in] descriptor The PatchDescriptor used to allocate patch data on the local processor
[in] factory Optional PatchFactory. If none specified, a default (standard) patch factory will be used.
[in] defer_boundary_box_creation Flag to indicate suppressing construction of the boundary boxes.
Precondition:
grid_geometry
descriptor
box_level.getDim() == grid_geometry->getDim()
box_level.getRefinementRatio() != IntVector::getZero(getDim())
all components of box_level's refinement ratio must be nonzero and, all components not equal to 1 must have the same sign
References SAMRAI::hier::Box::getBoxId(), getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::hier::PatchLevel::PatchLevel (const boost::shared_ptr< tbox::Database > & restart_database, const boost::shared_ptr< BaseGridGeometry > & grid_geometry, const boost::shared_ptr< PatchDescriptor > & descriptor, const boost::shared_ptr< PatchFactory > & factory, bool defer_boundary_box_creation = false)
Construct a new patch level from the specified PatchLevel restart database.
The box, mapping, and ratio to level zero data which are normally passed in during the construction of a new patch level are retrieved from the specified restart database.
Parameters:
[in] restart_database
[in] grid_geometry
[in] descriptor The PatchDescriptor used to allocate patch data.
[in] factory
[in] defer_boundary_box_creation Flag to indicate suppressing construction of the boundary boxes. Default: false
Precondition:
restart_database
grid_geometry
descriptor
References getFromRestart(), and TBOX_ASSERT.
SAMRAI::hier::PatchLevel::~PatchLevel () [virtual]
The virtual destructor for patch level deallocates all patches.
Member Function Documentation
int SAMRAI::hier::PatchLevel::getLevelNumber () const [inline]
Get the level number.
Returns:
the number of this level in a hierarchy, or the number of a hierarchy level matching the index space of this level. If this level does not align with the index space of a level in the hierarchy, then this value is -1. When the level is in a hierarchy, the return value of the number of the level in the hierarchy.
See also:
inHierarchy()
void SAMRAI::hier::PatchLevel::setLevelNumber (const int level) [inline]
Set the number of this level to the level in the hierarchy aligning with the index space of this level.
The default value is -1 meaning the level index space does not align with that of any hierarchy level.
Parameters:
[in] level
References begin(), and end().
int SAMRAI::hier::PatchLevel::getNextCoarserHierarchyLevelNumber () const [inline]
Convenience method to get the next coarser level number in a hierarchy.
Used for data interpolation from coarser levels. If the level is in a hierarchy, then this value is getLevelNumber() - 1.
See also:
inHierarchy()
Returns:
The next coarser level in the hierarchy or -1 if the level does not exist in the hierarchy.
void SAMRAI::hier::PatchLevel::setNextCoarserHierarchyLevelNumber (const int level) [inline]
Convenience method to set the number of of the next coarser level in a hierarchy.
For the purposes of data interpolation from coarser levels, set the next coarser level in a hierarchy. The default of -1 means the level does not relate to any hierarchy.
Parameters:
[in] level
bool SAMRAI::hier::PatchLevel::inHierarchy () const [inline]
Determine if this level resides in a hierarchy.
Returns:
true if this level resides in a hierarchy, otherwise false.
void SAMRAI::hier::PatchLevel::setLevelInHierarchy (bool in_hierarchy) [inline]
Setting to indicate whether this level resides in a hierarchy.
Parameters:
[in] in_hierarchy Flag to indicate whether this level resides in a hierarchy. Default: false
References begin(), and end().
int SAMRAI::hier::PatchLevel::getNumberOfPatches () const [inline]
Get the number of patches.
This is equivalent to calling PatchLevel::getGlobalNumberOfPatches().
References getGlobalNumberOfPatches().
int SAMRAI::hier::PatchLevel::getLocalNumberOfPatches () const [inline]
Get the local number of patches.
Referenced by recursivePrint().
int SAMRAI::hier::PatchLevel::getGlobalNumberOfPatches () const [inline]
Get the global number of patches.
Referenced by getNumberOfPatches(), and recursivePrint().
int SAMRAI::hier::PatchLevel::getLocalNumberOfCells () const [inline]
Get the local number of Cells.
Referenced by recursivePrint().
long int SAMRAI::hier::PatchLevel::getGlobalNumberOfCells () const [inline]
Get the global number of cells.
Referenced by recursivePrint().
const boost::shared_ptr<Patch>& SAMRAI::hier::PatchLevel::getPatch (const GlobalId & gid) const [inline]
Get a Patch based on its GlobalId.
Parameters:
[in] gid
Returns:
A boost::shared_ptr to the Patch indicated by the GlobalId.
References TBOX_ERROR.
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), getBoxForPatch(), patchTouchesRegularBoundary(), and SAMRAI::hier::BaseGridGeometry::setBoundaryBoxes().
boost::shared_ptr<Patch> SAMRAI::hier::PatchLevel::getPatch (const BoxId & mbid) const [inline]
Get a Patch based on its BoxId.
Parameters:
[in] mbid
Returns:
A boost::shared_ptr to the Patch indicated by the BoxId.
Precondition:
d_patches.find(mbid) != d_patches.end()
References TBOX_ERROR.
const boost::shared_ptr<Patch>& SAMRAI::hier::PatchLevel::getPatch (size_t index) const [inline]
Get a patch using a random access index.
The index specifies the position of the patch as would be encountered when iterating through the patches.
References TBOX_ERROR.
boost::shared_ptr<PatchDescriptor> SAMRAI::hier::PatchLevel::getPatchDescriptor () const [inline]
Get the PatchDescriptor.
Returns:
pointer to the patch descriptor for the hierarchy.
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), and SAMRAI::hier::BaseGridGeometry::setBoundaryBoxes().
boost::shared_ptr<PatchFactory> SAMRAI::hier::PatchLevel::getPatchFactory () const [inline]
Get the PatchFactory.
Returns:
the factory object used to created patches in the level.
boost::shared_ptr<BaseGridGeometry> SAMRAI::hier::PatchLevel::getGridGeometry () const [inline]
Get the grid geometry.
Returns:
A boost::shared_ptr to the grid geometry description.
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), and getFromRestart().
void SAMRAI::hier::PatchLevel::setRefinedPatchLevel (const boost::shared_ptr< PatchLevel > & coarse_level, const IntVector & refine_ratio, const boost::shared_ptr< BaseGridGeometry > & fine_grid_geometry = boost::shared_ptr<BaseGridGeometry>(), bool defer_boundary_box_creation = false)
Update this patch level through refining.
The data members of this patch level are updated by refining the information on a given coarse level using the given ratio between the two levels. The fine level will cover the same physical space as the coarse level and will have the same number of patches with the same mapping of those patches to processors. However, the index space of the level will be refined by the specified ratio.
Assumptions
If the fine grid geometry is null (default case), then it is assumed that this level is to use the same grid geometry as the given coarse level and the ratio to level zero is set relative to the given coarse level. Otherwise, we use the given grid geometry (assumed to be a proper refinement of the grid geometry used on the given coarse level) and copy ratio to level zero from given coarse level. In other words, the function can be used to produce two different results.
When passed a null grid geometry pointer, the refined patch level can be used for data exchange operations with the AMR hierarchy in which the coarse level resides -- both levels are defined with respect to the index space of the grid geometry object which they share. Thus, the refined patch level can be used in data exchanges with the AMR hierarchy of the coarse level automatically.
Second, when passed a non-null fine grid geometry pointer, the level is defined relative to that geometry and the refined patch level cannot be used in data exchanges with the AMR hierarchy of the coarse level automatically in general. This mode is used to construct a refined copy of an entire patch hierarchy, typically.
Parameters:
[in] coarse_level
[in] refine_ratio
[in] fine_grid_geometry Default: boost::shared_ptr to a null grid geometry
[in] defer_boundary_box_creation Default: false
Precondition:
coarse_level
refine_ratio > IntVector::getZero(getDim())
(getDim() == coarse_level->getDim()) && (getDim() == refine_ratio.getDim())
!fine_grid_geometry || getDim() == fine_grid_geometry->getDim()
References SAMRAI::hier::Box::getBoxId(), getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), SAMRAI::hier::BoxContainer::refine(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ASSERT_OBJDIM_EQUALITY3.
void SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel (const boost::shared_ptr< PatchLevel > & fine_level, const IntVector & coarsen_ratio, const boost::shared_ptr< BaseGridGeometry > & coarse_grid_geom = boost::shared_ptr<BaseGridGeometry>(), bool defer_boundary_box_creation = false)
Update this patch through coarsening.
The data members of this patch level are updated by coarsening the information on a given fine level using the given ratio between the two levels. The coarse level will cover the same physical space as the fine level and will have the patches with the same GlobalIndices. However, the index space of the level will be coarsened by the specified ratio.
Assumptions
If the coarse grid geometry is null (default case), then it is assumed that this level is to use the same grid geometry as the given fine level and the ratio to level zero is set relative to the given fine level. Otherwise, we use the given grid geometry (assumed to be a proper coarsening of the grid geometry used on the given fine level) and copy ratio to level zero from given fine level. In other words, the function can be used to produce two different results.
When passed a null grid geometry pointer, the coarsened patch level can be used for data exchange operations with the AMR hierarchy in which the fine level resides -- both levels are defined with respect to the index space of the grid geometry object which they share. Thus, the coarsened patch level can be used in data exchanges with the AMR hierarchy of the fine level automatically.
When passed a non-null coarse grid geometry pointer, the level is defined relative to that geometry and the coarsened patch level cannot be used in data exchanges with the AMR hierarchy of the fine level automatically in general. This mode is used to construct a coarsened copy of an entire patch hierarchy, typically.
Parameters:
[in] fine_level
[in] coarsen_ratio
[in] coarse_grid_geom Default: boost::shared_ptr to a null grid geometry
[in] defer_boundary_box_creation Default: false
Precondition:
fine_level
coarsen_ratio > IntVector::getZero(getDim())
(getDim() == fine_level->getDim()) && (getDim() == coarsen_ratio.getDim())
!coarse_grid_geom || getDim() == coarse_grid_geom->getDim()
References SAMRAI::hier::BoxContainer::coarsen(), SAMRAI::hier::Box::getBoxId(), getDim(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ASSERT_OBJDIM_EQUALITY3.
void SAMRAI::hier::PatchLevel::setBoundaryBoxes () [inline]
Create and store the boundary boxes for this level.
If boundary boxes have already been constructed, this function does nothing.
Note:
If the level is constructed with boundary box creation deferred, this method must be called before any attempt at filling data at physical boundaries. This function is called from xfer::RefineSchedule prior to any physical boundary operations.
const std::vector<BoxContainer>& SAMRAI::hier::PatchLevel::getPhysicalDomainArray () const [inline]
Get the physical domain.
Returns:
A const reference to the box array that defines the extent of the index space on the level.
Referenced by SAMRAI::hier::BaseGridGeometry::setBoundaryBoxes().
const BoxContainer& SAMRAI::hier::PatchLevel::getPhysicalDomain (const BlockId & block_id) const [inline]
References SAMRAI::hier::BlockId::getBlockValue().
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries().
const BoxContainer& SAMRAI::hier::PatchLevel::getBoxes () const [inline]
Get the box defining the patches on the level.
The internal state of PatchLevel (where boxes are concern) is dependent on the BoxLevel associated with it, and computed only if getBoxes() is called. The first call to getBoxes() must be done by all processors as it requires communication.
Returns:
a const reference to the box array that defines the patches on the level.
void SAMRAI::hier::PatchLevel::getBoxes (BoxContainer & boxes, const BlockId & block_id) const
Get boxes for a particular block.
The boxes from only the specified block will be stored in the output BoxContainer.
Parameters:
[out] boxes
[in] block_id
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::clear(), SAMRAI::hier::BoxContainer::end(), and SAMRAI::hier::BoxContainer::pushBack().
const boost::shared_ptr<BoxLevel>& SAMRAI::hier::PatchLevel::getBoxLevel () const [inline]
Get the BoxLevel associated with the PatchLevel.
Returns:
a reference to a boost::shared_ptr to the BoxLevel associated with the PatchLevel.
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), cacheConnector(), SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary(), createConnector(), createConnectorWithTranspose(), findConnector(), findConnectorWithTranspose(), hasConnector(), and recursivePrint().
const BoxLevel& SAMRAI::hier::PatchLevel::getGlobalizedBoxLevel () const [inline]
Get the globalized version of the BoxLevel associated with the PatchLevel.
Note:
The first time this method is used, a global communication is done. Thus all processors must use this method the first time any processor uses it.
Returns:
The globalized version of the BoxLevel associated with the PatchLevel.
const ProcessorMapping& SAMRAI::hier::PatchLevel::getProcessorMapping () const [inline]
Get the mapping of patches to processors.
Returns:
A const reference to the mapping of patches to processors.
const IntVector& SAMRAI::hier::PatchLevel::getRatioToLevelZero () const [inline]
Get the ratio between the index space of this PatchLevel and the reference level in the AMR hierarchy.
Returns:
A const reference to the vector ratio between the index space of this patch level and that of a reference level in AMR hierarchy (that is, level zero).
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), and SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries().
const IntVector& SAMRAI::hier::PatchLevel::getRatioToCoarserLevel () const [inline]
Get the ratio between this level and the next coarser level in the patch hierarchy.
This vector is set with the setRatioToCoarserLevel() function. If the level is not in a hierarchy, a default ratio of zero is returned.
Returns:
the vector ratio between this level and the next coarser level in the patch hierarchy.
void SAMRAI::hier::PatchLevel::setRatioToCoarserLevel (const IntVector & ratio) [inline]
Set the ratio between this level and the next coarser level in the patch hierarchy.
This is required only when level resides in a hierarchy.
Parameters:
[in] ratio
int SAMRAI::hier::PatchLevel::getMappingForPatch (const BoxId & box_id) const [inline]
Get the processor mapping for the patch.
Returns:
the processor that owns the specified patch. The patches are numbered starting at zero.
Parameters:
[in] box_id Patch's BoxId
References NULL_USE.
const Box& SAMRAI::hier::PatchLevel::getBoxForPatch (const BoxId & box_id) const [inline]
Get the box for the specified patch.
Returns:
The box for the specified patch.
Parameters:
[in] box_id Patch's BoxId
Precondition:
box_id.getOwnerRank() == getBoxLevel()->getMPI().getRank()
References SAMRAI::hier::BoxId::getOwnerRank(), getPatch(), and TBOX_ASSERT.
bool SAMRAI::hier::PatchLevel::patchTouchesRegularBoundary (const BoxId & box_id) const [inline]
Determine if the patch is adjacent to a non-periodic physical domain boundary.
Parameters:
[in] box_id Patch's BoxId
Returns:
True if patch with given number is adjacent to a non-periodic physical domain boundary. Otherwise, false.
Precondition:
box_id.getOwnerRank() == getBoxLevel()->getMPI().getRank()
References SAMRAI::hier::BoxId::getOwnerRank(), getPatch(), and TBOX_ASSERT.
void SAMRAI::hier::PatchLevel::allocatePatchData (const int id, const double timestamp = 0.0) [inline]
Allocate the specified component on all patches.
Parameters:
[in] id
[in] timestamp Default: zero (0.0)
References begin(), and end().
void SAMRAI::hier::PatchLevel::allocatePatchData (const ComponentSelector & components, const double timestamp = 0.0) [inline]
Allocate the specified components on all patches.
Parameters:
[in] components The componentSelector indicating which elements to allocate
[in] timestamp Default: zero (0.0)
References begin(), and end().
bool SAMRAI::hier::PatchLevel::checkAllocated (const int id) const [inline]
Determine if the patch data has been allocated.
Returns:
True if (1) there are no patches in this patch level or if (2) all of the patches have allocated the patch data component, otherwise false.
Parameters:
[in] id The patch identifier.
void SAMRAI::hier::PatchLevel::deallocatePatchData (const int id) [inline]
Deallocate the specified component on all patches.
This component will need to be reallocated before its next use.
Parameters:
[in] id The patch identifier
References begin(), and end().
void SAMRAI::hier::PatchLevel::deallocatePatchData (const ComponentSelector & components) [inline]
Deallocate the specified components on all patches.
Components will need to be reallocated before their next use.
Parameters:
[in] components The ComponentSelector indicating which components to deallocate.
References begin(), and end().
const tbox::Dimension& SAMRAI::hier::PatchLevel::getDim () const [inline]
Get the dimension of this object.
Returns:
the dimension of this object.
Referenced by SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries(), getFromRestart(), PatchLevel(), putToRestart(), setCoarsenedPatchLevel(), and setRefinedPatchLevel().
void SAMRAI::hier::PatchLevel::setTime (const double timestamp, const int id) [inline]
Set the simulation time for the specified patch component.
Parameters:
[in] timestamp
[in] id The patch identifier
References begin(), and end().
void SAMRAI::hier::PatchLevel::setTime (const double timestamp, const ComponentSelector & components) [inline]
Set the simulation time for the specified patch components.
Parameters:
[in] timestamp
[in] components The ComponentSelector indicating on which components to set the simulation time.
References begin(), and end().
void SAMRAI::hier::PatchLevel::setTime (const double timestamp) [inline]
Set the simulation time for all allocated patch components.
Parameters:
[in] timestamp
References begin(), and end().
const Connector& SAMRAI::hier::PatchLevel::findConnector (const PatchLevel & head, const IntVector & min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only = false) const [inline]
Find an overlap Connector with the given PatchLevel's BoxLevel as its head and minimum Connector width. If the specified Connector is not found, take the specified action.
If multiple Connectors fit the criteria, the one with the smallest ghost cell width (based on the algebraic sum of the components) is selected.
Parameters:
[in] head Find the overlap Connector with this PatchLevel's BoxLevel as the head.
[in] min_connector_width Find the overlap Connector satisfying this minimum Connector width.
[in] not_found_action Action to take if Connector is not found.
[in] exact_width_only If true, reject Connectors that do not match the requested width exactly.
Returns:
The Connector which matches the search criterion.
Precondition:
getBoxLevel()->isInitialized()
head.getBoxLevel()->isInitialized()
References getBoxLevel().
Referenced by SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary().
const Connector& SAMRAI::hier::PatchLevel::findConnectorWithTranspose (const PatchLevel & head, const IntVector & min_connector_width, const IntVector & transpose_min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only = false) const [inline]
Find an overlap Connector with its transpose with the given PatchLevel's BoxLevel as its head and minimum Connector widths. If the specified Connector is not found, take the specified action.
If multiple Connectors fit the criteria, the one with the smallest ghost cell width (based on the algebraic sum of the components) is selected.
Parameters:
[in] head Find the overlap Connector with this PatchLevel's BoxLevel as the head.
[in] min_connector_width Find the overlap Connector satisfying this minimum Connector width.
[in] transpose_min_connector_width Find the transpose overlap Connector satisfying this minimum Connector width.
[in] not_found_action Action to take if Connector is not found.
[in] exact_width_only If true, reject Connectors that do not match the requested width exactly.
Returns:
The Connector which matches the search criterion.
Precondition:
getBoxLevel()->isInitialized()
head.getBoxLevel()->isInitialized()
References getBoxLevel().
const Connector& SAMRAI::hier::PatchLevel::createConnector (const PatchLevel & head, const IntVector & connector_width) const [inline]
Create an overlap Connector, computing relationships by globalizing data.
The base will be this PatchLevel's BoxLevel. Find Connector relationships using a (non-scalable) global search.
See also:
hier::Connector
hier::Connector::initialize()
Parameters:
[in] head This PatchLevel's BoxLevel will be the head.
[in] connector_width
Returns:
A const reference to the newly created overlap Connector.
Precondition:
getBoxLevel()->isInitialized()
head.getBoxLevel()->isInitialized()
References getBoxLevel().
const Connector& SAMRAI::hier::PatchLevel::createConnectorWithTranspose (const PatchLevel & head, const IntVector & connector_width, const IntVector & transpose_connector_width) const [inline]
Create an overlap Connector with its transpose, computing relationships by globalizing data.
The base will be this PatchLevel's BoxLevel. Find Connector relationships using a (non-scalable) global search.
See also:
hier::Connector
hier::Connector::initialize()
Parameters:
[in] head This PatchLevel's BoxLevel will be the head.
[in] connector_width
[in] transpose_connector_width
Returns:
A const reference to the newly created overlap Connector.
Precondition:
getBoxLevel()->isInitialized()
head.getBoxLevel()->isInitialized()
References getBoxLevel().
void SAMRAI::hier::PatchLevel::cacheConnector (boost::shared_ptr< Connector > & connector) const [inline]
Cache the supplied overlap Connector and its transpose if it exists.
Parameters:
[in] connector
Precondition:
connector
getBoxLevel()->isInitialized()
getBoxLevel() == connector->getBase()
References getBoxLevel().
bool SAMRAI::hier::PatchLevel::hasConnector (const PatchLevel & head, const IntVector & min_connector_width, bool exact_width_only = false) const [inline]
Returns whether the object has overlap Connectors with the given PatchLevel's BoxLevel as the head and minimum Connector width.
TODO: does the following comment mean that this must be called before the call to findConnector?
If this returns true, the Connector fitting the specification exists and findConnector() will not throw an assertion.
Parameters:
[in] head Find the overlap Connector with this PatchLevel's BoxLevel as the head.
[in] min_connector_width Find the overlap Connector satisfying this minimum ghost cell width.
[in] exact_width_only If true, reject Connectors that do not match the requested width exactly.
Returns:
True if a Connector is found, otherwise false.
References getBoxLevel().
void SAMRAI::hier::PatchLevel::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db)
Use the PatchLevel restart database to set the state of the PatchLevel and to create all patches on the local processor.
Assertions
Assertions will check that database is a non-null boost::shared_ptr, that the data being retrieved from the database are of the type expected. Also checked is the number of patches is positive, and the number of patches and size of processor mapping array are the same, and that the number of patches and the number of boxes on the level are equal.
Parameters:
[in,out] restart_db
Precondition:
restart_db
References begin(), SAMRAI::tbox::Utilities::blockToString(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::Box::getBoxId(), getDim(), getGridGeometry(), SAMRAI::hier::Box::getLocalId(), SAMRAI::hier::LocalId::getValue(), SAMRAI::tbox::Utilities::levelToString(), SAMRAI::tbox::Utilities::patchToString(), SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by PatchLevel().
void SAMRAI::hier::PatchLevel::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Write data to the restart database.
Writes the data from the PatchLevel to the restart database. Also tells all local patches to write out their state to the restart database.
Parameters:
[in,out] restart_db
Precondition:
restart_db
References begin(), SAMRAI::tbox::Utilities::blockToString(), end(), getDim(), SAMRAI::tbox::Utilities::levelToString(), SAMRAI::tbox::Utilities::patchToString(), and TBOX_ASSERT.
int SAMRAI::hier::PatchLevel::recursivePrint (std::ostream & os, const std::string & border = std::string(), int depth = 0)
Print a patch level to varying details.
If depth>0, print function will be called for each patch in the level.
Parameters:
[in] os The std::ostream in which to print to
[in] border Default: empty string
[in] depth Default: zero (0).
Returns:
0. Always.
References begin(), end(), getBoxLevel(), getGlobalNumberOfCells(), getGlobalNumberOfPatches(), getLocalNumberOfCells(), and getLocalNumberOfPatches().
Iterator SAMRAI::hier::PatchLevel::begin () const [inline]
Construct an iterator pointing to the first Patch in the PatchLevel.
Referenced by allocatePatchData(), SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::hier::BaseGridGeometry::computeBoundaryBoxesOnLevel(), deallocatePatchData(), SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries(), getFromRestart(), putToRestart(), recursivePrint(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), SAMRAI::hier::BaseGridGeometry::setGeometryOnPatches(), setLevelInHierarchy(), setLevelNumber(), and setTime().
Iterator SAMRAI::hier::PatchLevel::end () const [inline]
Construct an iterator pointing to the last Patch in the PatchLevel.
Referenced by allocatePatchData(), SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::hier::BaseGridGeometry::computeBoundaryBoxesOnLevel(), deallocatePatchData(), SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries(), putToRestart(), recursivePrint(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), SAMRAI::hier::BaseGridGeometry::setGeometryOnPatches(), setLevelInHierarchy(), setLevelNumber(), and setTime().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchLevel.h
source/SAMRAI/hier/PatchLevel.C