SAMRAI: SAMRAI::pdat::NodeIndex Class Reference
SAMRAI::pdat::NodeIndex Class Reference
#include <source/SAMRAI/pdat/NodeIndex.h>
Public Types
enum Corner {
Left = 0, Right = 1, LowerLeft = 0, LowerRight = 1,
UpperLeft = 2, UpperRight = 3, LLL = 0, ULL = 1,
LUL = 2, UUL = 3, LLU = 4, ULU = 5,
LUU = 6, UUU = 7
}
Public Member Functions
NodeIndex (const tbox::Dimension &dim)
NodeIndex (const hier::Index &rhs, const Corner corner)
NodeIndex (const hier::Index &rhs, const hier::IntVector &corner)
NodeIndex (const NodeIndex &rhs)
NodeIndex & operator= (const NodeIndex &rhs)
~NodeIndex ()
NodeIndex & operator+= (const hier::IntVector &rhs)
NodeIndex operator+ (const hier::IntVector &rhs) const
NodeIndex & operator+= (const int rhs)
NodeIndex operator+ (const int rhs) const
NodeIndex & operator-= (const hier::IntVector &rhs)
NodeIndex operator- (const hier::IntVector &rhs) const
NodeIndex & operator-= (const int rhs)
NodeIndex operator- (const int rhs) const
NodeIndex & operator*= (const hier::IntVector &rhs)
NodeIndex operator* (const hier::IntVector &rhs) const
NodeIndex & operator*= (const int rhs)
NodeIndex operator* (const int rhs) const
bool operator== (const NodeIndex &rhs) const
bool operator!= (const NodeIndex &rhs) const
Detailed Description
Class NodeIndex implements a simple n-dimensional integer vector for node centered variables. Given a hier::Box in the AMR abstract index space, the index space for a node-centered variable runs from the lower corner of the box to the upper corner of the box plus one in each direction. See the node box geometry class for more information about the mapping between the AMR index space and the node indices.
See also:
hier::Index
NodeData
NodeGeometry
NodeIterator
Member Enumeration Documentation
enum SAMRAI::pdat::NodeIndex::Corner
The Corner enumerated type is used when converting from a cell centered index to a node centered index. In 1d, use Left and Right. In 2d, use LowerLeft, LowerRight, UpperLeft, and UpperRight. In 3d, the naming is less intuitive, and use names LLL through UUU, where L means lower and U means upper. Therefore, to get the box upper in X, lower in Y, and lower in Z, use corner name ULL.
Enumerator:
Left
Right
LowerLeft
LowerRight
UpperLeft
UpperRight
LLL
ULL
LUL
UUL
LLU
ULU
LUU
UUU
Constructor & Destructor Documentation
SAMRAI::pdat::NodeIndex::NodeIndex (const tbox::Dimension & dim) [explicit]
The default constructor for a node index creates an uninitialized index.
SAMRAI::pdat::NodeIndex::NodeIndex (const hier::Index & rhs, const Corner corner)
Construct a node index from a regular index and a corner.
The Corner enumerated type is only defined for 3D or lower, so use the next constructor with an hier::IntVector argument when using higher dimensions.
Precondition:
getDim() == rhs.getDim()
References SAMRAI::hier::Index::getDim(), operator=(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::NodeIndex::NodeIndex (const hier::Index & rhs, const hier::IntVector & corner)
Construct a node index from a regular index and an hier::IntVector. For each direction, if the hier::IntVector contains a 0, the node index will represent a lower bound in that direction, and if 1 will represent an upper bound in that direction.
Precondition:
getDim() == rhs.getDim()
for each element of corner, e, e == 0 || e == 1
References SAMRAI::hier::Index::getDim(), SAMRAI::tbox::Dimension::getValue(), operator=(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::NodeIndex::NodeIndex (const NodeIndex & rhs)
The copy constructor creates a node index equal to the argument.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::NodeIndex::~NodeIndex ()
The node index destructor does nothing interesting.
Member Function Documentation
NodeIndex& SAMRAI::pdat::NodeIndex::operator= (const NodeIndex & rhs) [inline]
The assignment operator sets the node index equal to the argument.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by NodeIndex().
NodeIndex& SAMRAI::pdat::NodeIndex::operator+= (const hier::IntVector & rhs) [inline]
Plus-equals operator for a node index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator+=().
NodeIndex SAMRAI::pdat::NodeIndex::operator+ (const hier::IntVector & rhs) const [inline]
Plus operator for a node index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
NodeIndex& SAMRAI::pdat::NodeIndex::operator+= (const int rhs) [inline]
Plus-equals operator for a node index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator+=().
NodeIndex SAMRAI::pdat::NodeIndex::operator+ (const int rhs) const [inline]
Plus operator for a node index and an integer.
Reimplemented from SAMRAI::hier::Index.
NodeIndex& SAMRAI::pdat::NodeIndex::operator-= (const hier::IntVector & rhs) [inline]
Minus-equals operator for a node index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator-=().
NodeIndex SAMRAI::pdat::NodeIndex::operator- (const hier::IntVector & rhs) const [inline]
Minus operator for a node index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
NodeIndex& SAMRAI::pdat::NodeIndex::operator-= (const int rhs) [inline]
Minus-equals operator for a node index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator-=().
NodeIndex SAMRAI::pdat::NodeIndex::operator- (const int rhs) const [inline]
Minus operator for a node index and an integer.
Reimplemented from SAMRAI::hier::Index.
NodeIndex& SAMRAI::pdat::NodeIndex::operator*= (const hier::IntVector & rhs) [inline]
Times-equals operator for a node index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator*=().
NodeIndex SAMRAI::pdat::NodeIndex::operator* (const hier::IntVector & rhs) const [inline]
Times operator for a node index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
NodeIndex& SAMRAI::pdat::NodeIndex::operator*= (const int rhs) [inline]
Times-equals operator for a node index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator*=().
NodeIndex SAMRAI::pdat::NodeIndex::operator* (const int rhs) const [inline]
Times operator for a node index and an integer.
Reimplemented from SAMRAI::hier::Index.
bool SAMRAI::pdat::NodeIndex::operator== (const NodeIndex & rhs) const [inline]
Returns true if two node index objects are equal. All components must be the same for equality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::pdat::NodeIndex::operator!= (const NodeIndex & rhs) const [inline]
Returns true if two node index objects are not equal. Any of the components may be different for inequality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/NodeIndex.h
source/SAMRAI/pdat/NodeIndex.C