SAMRAI: SAMRAI::algs::OuternodeSumTransactionFactory Class Reference
SAMRAI::algs::OuternodeSumTransactionFactory Class Reference
Concrete subclass of the xfer::RefineTransactionFactory base class that allocates transaction outernode sum objects for a xfer::RefineSchedule object.
#include <source/SAMRAI/algs/OuternodeSumTransactionFactory.h>
Public Member Functions
OuternodeSumTransactionFactory ()
Default constructor.
virtual ~OuternodeSumTransactionFactory ()
Virtual destructor for base class.
void setRefineItems (const xfer::RefineClasses::Data *const *refine_items)
Set the array of xfer::RefineClasses::Data items used by the transactions.
void unsetRefineItems ()
Clear the array of xfer::RefineClasses::Data items used by the transactions.
boost::shared_ptr
< tbox::Transaction > allocate (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_node, const hier::Box &src_node, const xfer::RefineClasses::Data **refine_data, int item_id, const hier::Box &box, bool use_time_interpolation=false) const
Allocate an OuternodeSumTransaction object.
boost::shared_ptr
< tbox::Transaction > allocate (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_node, const hier::Box &src_node, const xfer::RefineClasses::Data **refine_data, int item_id) const
Allocate an OuternodeSumTransaction object.
void preprocessScratchSpace (const boost::shared_ptr< hier::PatchLevel > &level, double fill_time, const hier::ComponentSelector &preprocess_vector) const
Function to initialize scratch space data for the sum transactions (patch data components indicated by the component selector) to zero.
Detailed Description
Concrete subclass of the xfer::RefineTransactionFactory base class that allocates transaction outernode sum objects for a xfer::RefineSchedule object.
See also:
xfer::RefineTransactionFactory
xfer::OuternodeSumTransaction
Constructor & Destructor Documentation
SAMRAI::algs::OuternodeSumTransactionFactory::OuternodeSumTransactionFactory ()
Default constructor.
SAMRAI::algs::OuternodeSumTransactionFactory::~OuternodeSumTransactionFactory () [virtual]
Virtual destructor for base class.
Member Function Documentation
void SAMRAI::algs::OuternodeSumTransactionFactory::setRefineItems (const xfer::RefineClasses::Data *const * refine_items)
Set the array of xfer::RefineClasses::Data items used by the transactions.
void SAMRAI::algs::OuternodeSumTransactionFactory::unsetRefineItems ()
Clear the array of xfer::RefineClasses::Data items used by the transactions.
boost::shared_ptr< tbox::Transaction > SAMRAI::algs::OuternodeSumTransactionFactory::allocate (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_node, const hier::Box & src_node, const xfer::RefineClasses::Data ** refine_data, int item_id, const hier::Box & box, bool use_time_interpolation = false) const [virtual]
Allocate an OuternodeSumTransaction object.
Parameters:
dst_level boost::shared_ptr to destination patch level.
src_level boost::shared_ptr to source patch level.
overlap boost::shared_ptr to overlap region between patches.
dst_node Destination Box in destination patch level.
src_node Source Box in source patch level.
refine_data Pointer to array of refine data items
item_id Integer index of xfer::RefineClasses::Data item associated with transaction.
box Const reference to box defining region of refine transaction. Use following allocate method if not needed.
use_time_interpolation Optional boolean flag indicating whether the refine transaction involves time interpolation. Default is false.
Precondition:
dst_level
src_level
overlap
dst_node.getLocalId() >= 0
src_node.getLocalId() >= 0
item_id >= 0
(dst_level->getDim() == src_level->getDim()) && (dst_level->getDim() == dst_node.getDim()) && (dst_level->getDim() == src_node.getDim())
Implements SAMRAI::xfer::RefineTransactionFactory.
References SAMRAI::hier::Box::getLocalId(), NULL_USE, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
Referenced by allocate().
boost::shared_ptr< tbox::Transaction > SAMRAI::algs::OuternodeSumTransactionFactory::allocate (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_node, const hier::Box & src_node, const xfer::RefineClasses::Data ** refine_data, int item_id) const
Allocate an OuternodeSumTransaction object.
Same as previous allocate routine but with default empty box and no timer interpolation.
Precondition:
dst_level
src_level
overlap
dst_node.getLocalId() >= 0
src_node.getLocalId() >= 0
item_id >= 0
(dst_level->getDim() == src_level->getDim()) && (dst_level->getDim() == dst_node.getDim()) && (dst_level->getDim() == src_node.getDim())
Reimplemented from SAMRAI::xfer::RefineTransactionFactory.
References allocate(), SAMRAI::hier::Box::getLocalId(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
void SAMRAI::algs::OuternodeSumTransactionFactory::preprocessScratchSpace (const boost::shared_ptr< hier::PatchLevel > & level, double fill_time, const hier::ComponentSelector & preprocess_vector) const [virtual]
Function to initialize scratch space data for the sum transactions (patch data components indicated by the component selector) to zero.
Parameters:
level boost::shared_ptr to patch level holding scratch data.
fill_time Double value of simulation time at which preprocess operation is called.
preprocess_vector Const reference to hier::ComponentSelector indicating patch data array indices of scratch patch data objects to preprocess.
Precondition:
level
Implements SAMRAI::xfer::RefineTransactionFactory.
References BOOST_CAST, SAMRAI::hier::ComponentSelector::getSize(), SAMRAI::hier::ComponentSelector::isSet(), NULL_USE, and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/algs/OuternodeSumTransactionFactory.h
source/SAMRAI/algs/OuternodeSumTransactionFactory.C