SAMRAI: SAMRAI::xfer::PatchLevelFullFillPattern Class Reference
SAMRAI::xfer::PatchLevelFullFillPattern Class Reference
PatchLevelFullFillPattern is a PatchLevelFillPattern that fills the entire region the destination level, both interior and ghost.
#include <source/SAMRAI/xfer/PatchLevelFullFillPattern.h>
Public Member Functions
PatchLevelFullFillPattern ()
Default constructor.
virtual ~PatchLevelFullFillPattern ()
Destructor.
void computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > &fill_box_level, boost::shared_ptr< hier::Connector > &dst_to_fill, const hier::BoxLevel &dst_box_level, const hier::IntVector &fill_ghost_width, bool data_on_patch_border)
bool needsToCommunicateDestinationFillBoxes () const
void computeDestinationFillBoxesOnSourceProc (FillSet &dst_fill_boxes_on_src_proc, const hier::BoxLevel &dst_box_level, const hier::Connector &src_to_dst, const hier::IntVector &fill_ghost_width)
bool doesSourceLevelCommunicateToDestination () const
int getMaxFillBoxes () const
bool fillingCoarseFineGhosts () const
bool fillingEnhancedConnectivityOnly () const
Detailed Description
PatchLevelFullFillPattern is a PatchLevelFillPattern that fills the entire region the destination level, both interior and ghost.
For documentation on this interface see xfer::PatchLevelFillPattern
The fill boxes for this PatchLevelFillPattern will consist of the entire region of the destination level that can be filled, both interior and ghost regions.
If a RefineSchedule is created using an RefineAlgorithm::createSchedule which takes no PatchLevelFillPattern argument, this class will be used as the default PatchLevelFillPattern.
See also:
xfer::RefineAlgorithm
xfer::RefineSchedule
Constructor & Destructor Documentation
SAMRAI::xfer::PatchLevelFullFillPattern::PatchLevelFullFillPattern ()
Default constructor.
SAMRAI::xfer::PatchLevelFullFillPattern::~PatchLevelFullFillPattern () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > & fill_box_level, boost::shared_ptr< hier::Connector > & dst_to_fill, const hier::BoxLevel & dst_box_level, const hier::IntVector & fill_ghost_width, bool data_on_patch_border) [virtual]
Compute the boxes to be filled and related communication data. This pure virtual method provides an interface to give the RefineSchedule the information needed to fill particular spatial regions on the destination level. The specific regions (such as patch interiors, ghost regions, or some combination thereof) will be specified in the concrete implementations of this class. Implementations of this method should store the desired regions to be filled in the BoxSet fill_box_level, and should compute a BoxNeighborhoodCollection describing the relationship between dst_box_level and fill_box_level.
Parameters:
[out] fill_box_level BoxLevel to be filled
[out] dst_to_fill Connector between dst_box_level and fill_box_level
[in] dst_box_level destination level
[in] fill_ghost_width ghost width being filled by refine schedule
[in] data_on_patch_border true if there is data living on patch borders
The computed fill_box_level for this fill pattern will be the boxes of dst_box_level grown by the fill_ghost_width.
Precondition:
dst_box_level.getDim() == fill_ghost_width.getDim()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::Box::grow(), NULL_USE, SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::xfer::PatchLevelFullFillPattern::needsToCommunicateDestinationFillBoxes () const [virtual]
Return true if source owner can compute destination boxes on its own. If the fill pattern is such that the source patch owner cannot compute fill boxes for all of its destination neighbors using local data, then a communication is needed to acquire this information, and this method should return true. If the source owner can compute the fill boxes for its destination neighbors using its local data, then this method should return false, which will prevent an unneeded communication step.If this method returns true, computeDestinationFillBoxesOnSourceProc() will not be called.
Returns:
true if communication needed, false otherwise.
For this fill pattern, the source owner can compute fill boxes for all of its destination neighbors using local data, so this method returns false, allowing a communication step to be skipped.
Implements SAMRAI::xfer::PatchLevelFillPattern.
void SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc (FillSet & dst_fill_boxes_on_src_proc, const hier::BoxLevel & dst_box_level, const hier::Connector & src_to_dst, const hier::IntVector & fill_ghost_width) [virtual]
Virtual method to compute the destination fill boxes. If needsToCommunicateDestinationFillBoxes() returns true, then this method will not be called and the child classes do not need an implementation.This method must be implemented if needsToCommunicateDestinationFillBoxes() returns false, as that means that the source patch owner will compute destination fill boxes using its own local data with this method.
Parameters:
[out] dst_fill_boxes_on_src_proc FillSet storing the destination neighbors of the source mapped boxes
[in] dst_box_level destination level
[in] src_to_dst Connector of source to destination
[in] fill_ghost_width Ghost width being filled by refine schedule
Precondition:
dst_box_level.getDim() == fill_ghost_width.getDim()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::Connector::getLocalNeighbors(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), SAMRAI::hier::BoxNeighborhoodCollection::numNeighbors(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::hier::BoxContainer::unshiftPeriodicImageBoxes().
bool SAMRAI::xfer::PatchLevelFullFillPattern::doesSourceLevelCommunicateToDestination () const [virtual]
Tell RefineSchedule whether it needs to communicate data directly from source level to destination level. The return value of this method tells the RefineSchedule whether or not to create an internal schedule to communicate as much data as possible from the source level to the destination level on the same level of resolution. If it returns false, all of the fill boxes on the destination level will be filled from a coarser level. If true, then any parts of the fill boxes that can be filled by communicating data from the source level interior will be filled, and whatever parts of the fill boxes are left unfilled by that communication will be filled from a coarser level.Generally this method should return true for fill pattern implementations that are used to fill the full interiors of patches and false for patterns that fill only at or outside of patch boundaries.
Returns:
true if data should be communicated directly from source to destination.
RefineSchedule should attempt to fill the destination level from the source level on the same resolution to the extent possible.
Implements SAMRAI::xfer::PatchLevelFillPattern.
int SAMRAI::xfer::PatchLevelFullFillPattern::getMaxFillBoxes () const [virtual]
Return the maximum number of fill boxes. Each destination patch has an associated set of fill boxes, and this is the maximum size of those sets across all destination patches.The maximum number returned is for the patches on the destination level provided to the most recent invocation of the computeDestinationFillBoxesOnSourceProc method.
Returns:
maximum number of fill boxes.
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelFullFillPattern::fillingCoarseFineGhosts () const [virtual]
Return true if the fill pattern is intended to allow the filling of ghost regions at coarse-fine boundaries.
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelFullFillPattern::fillingEnhancedConnectivityOnly () const [virtual]
Return true if the fill pattern is specialized for filling at enhanced connectivity block boundaries only, false for all other cases.
Implements SAMRAI::xfer::PatchLevelFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/PatchLevelFullFillPattern.h
source/SAMRAI/xfer/PatchLevelFullFillPattern.C