SAMRAI: SAMRAI::xfer::PatchInteriorVariableFillPattern Class Reference
SAMRAI::xfer::PatchInteriorVariableFillPattern Class Reference
Class PatchInteriorVariableFillPattern is an implementation of the abstract base class VariableFillPattern.
#include <source/SAMRAI/xfer/PatchInteriorVariableFillPattern.h>
Public Member Functions
PatchInteriorVariableFillPattern (const tbox::Dimension &dim)
Constructor.
virtual ~PatchInteriorVariableFillPattern ()
Destructor.
boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &dst_patch_box, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation) const
Calculate overlap between the destination and source geometries using the geometries' own overlap calculation methods.
boost::shared_ptr
< hier::BoxOverlap > computeFillBoxesOverlap (const hier::BoxContainer &fill_boxes, const hier::BoxContainer &unfilled_node_boxes, const hier::Box &patch_box, const hier::Box &data_box, const hier::PatchDataFactory &pdf) const
const hier::IntVector & getStencilWidth ()
Implementation of interface to get stencil width.
const std::string & getPatternName () const
Returns a string name identifier "PATCH_INTERIOR_FILL_PATTERN".
Detailed Description
Class PatchInteriorVariableFillPattern is an implementation of the abstract base class VariableFillPattern.
It is used to calculate overlaps hat consist of the intersections between patches, including only patch interiors. (The boundaries of a patch are considered to be part of the interior.)
Constructor & Destructor Documentation
SAMRAI::xfer::PatchInteriorVariableFillPattern::PatchInteriorVariableFillPattern (const tbox::Dimension & dim) [explicit]
Constructor.
Parameters:
[in] dim Dimension
SAMRAI::xfer::PatchInteriorVariableFillPattern::~PatchInteriorVariableFillPattern () [virtual]
Destructor.
Member Function Documentation
boost::shared_ptr< hier::BoxOverlap > SAMRAI::xfer::PatchInteriorVariableFillPattern::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & dst_patch_box, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation) const [virtual]
Calculate overlap between the destination and source geometries using the geometries' own overlap calculation methods.
The intersection between the given dst_geometry and src_geometry will be calculated according to the properties of those geometries, but will not include any ghost space outside of the patch represented by dst_patch_box.
If the argument overwrite_interior is set to false, then the returned BoxOverlap will be empty, since this class only computes overlaps representing patch interiors.
Parameters:
[in] dst_geometry geometry object for destination box
[in] src_geometry geometry object for source box
[in] dst_patch_box box for the destination patch
[in] src_mask the source mask, the box resulting from transforming the source box
[in] fill_box the box to be filled
[in] overwrite_interior controls whether or not to include the destination box interior in the overlap.
[in] transformation the transformation from source to destination index space.
Returns:
boost::shared_ptr to the calculated overlap object
Precondition:
dst_patch_box.getDim() == src_mask.getDim()
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::BoxGeometry::calculateOverlap(), NULL_USE, and TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::xfer::PatchInteriorVariableFillPattern::computeFillBoxesOverlap (const hier::BoxContainer & fill_boxes, const hier::BoxContainer & unfilled_node_boxes, const hier::Box & patch_box, const hier::Box & data_box, const hier::PatchDataFactory & pdf) const [virtual]
Computes a BoxOverlap object which defines the space to be filled by a refinement operation. For this implementation, that space is the intersection between fill_boxes (computed by the RefineSchedule), data_box, which specifies the extent of the destination data, and patch_box, which specifies the patch interior of the destination. The patch data factory is used to compute the overlap with the appropriate data centering, consistent with the centering of the data to be filled.
Parameters:
[in] fill_boxes list representing the all of the space on a patch or its ghost region that may be filled by a refine operator (cell-centered represtentation)
[in] unfilled_node_boxes node-centered representation of fill_boxes
[in] patch_box box representing the patch where a refine operator will fill data. (cell-centered representation)
[in] data_box box representing the full extent of the region covered by a patch data object, including all ghosts (cell-centered representation)
[in] pdf patch data factory for the data that is to be filled
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::PatchDataFactory::getBoxGeometry(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::intersectBoxes(), and NULL_USE.
const hier::IntVector & SAMRAI::xfer::PatchInteriorVariableFillPattern::getStencilWidth () [virtual]
Implementation of interface to get stencil width.
Returns:
Zero IntVector since this fills patch interiors only.
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::IntVector::getZero().
const std::string & SAMRAI::xfer::PatchInteriorVariableFillPattern::getPatternName () const [virtual]
Returns a string name identifier "PATCH_INTERIOR_FILL_PATTERN".
Implements SAMRAI::xfer::VariableFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/PatchInteriorVariableFillPattern.h
source/SAMRAI/xfer/PatchInteriorVariableFillPattern.C