SAMRAI: SAMRAI::tbox::StatisticRestartDatabase Class Reference
SAMRAI::tbox::StatisticRestartDatabase Class Reference
#include <source/SAMRAI/tbox/Statistician.h>
Public Member Functions
StatisticRestartDatabase (const std::string &object_name, bool read_from_restart)
virtual ~StatisticRestartDatabase ()
void putToRestart (const boost::shared_ptr< Database > &restart_db) const
Serializes the object by writing necessary state to the specified restart database.
void getFromRestart ()
const std::string & getObjectName () const
Friends
class Statistician
Constructor & Destructor Documentation
SAMRAI::tbox::StatisticRestartDatabase::StatisticRestartDatabase (const std::string & object_name, bool read_from_restart)
References getFromRestart(), SAMRAI::tbox::RestartManager::getManager(), SAMRAI::tbox::RestartManager::isFromRestart(), SAMRAI::tbox::RestartManager::registerRestartItem(), and TBOX_ASSERT.
SAMRAI::tbox::StatisticRestartDatabase::~StatisticRestartDatabase () [virtual]
References SAMRAI::tbox::RestartManager::getManager(), and SAMRAI::tbox::RestartManager::unregisterRestartItem().
Member Function Documentation
void SAMRAI::tbox::StatisticRestartDatabase::putToRestart (const boost::shared_ptr< Database > & restart_db) const [virtual]
Serializes the object by writing necessary state to the specified restart database.
Implements SAMRAI::tbox::Serializable.
References SAMRAI::tbox::Statistician::getNumberPatchStats(), SAMRAI::tbox::Statistician::getNumberProcessorStats(), SAMRAI::tbox::Statistician::getStatistician(), and TBOX_ASSERT.
void SAMRAI::tbox::StatisticRestartDatabase::getFromRestart ()
References SAMRAI::tbox::RestartManager::getManager(), SAMRAI::tbox::Statistician::getStatistic(), SAMRAI::tbox::Statistician::getStatistician(), TBOX_ERROR, and TBOX_WARNING.
Referenced by StatisticRestartDatabase().
const std::string& SAMRAI::tbox::StatisticRestartDatabase::getObjectName () const [inline]
Return string name identifier for statistic object.
Friends And Related Function Documentation
friend class Statistician [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Statistician.h
source/SAMRAI/tbox/Statistician.C