SAMRAI: SAMRAI::hier::BaseGridGeometry::NeighborIterator Class Reference
SAMRAI::hier::BaseGridGeometry::NeighborIterator Class Reference
Class NeighborIterator iterates over the Neighbors of a block.
#include <source/SAMRAI/hier/BaseGridGeometry.h>
Public Member Functions
NeighborIterator (const NeighborIterator &other)
Copy constructor.
~NeighborIterator ()
Destructor.
NeighborIterator & operator= (const NeighborIterator &rhs)
Assignment operator.
Neighbor & operator* () const
Dereference operator.
NeighborIterator operator++ (int)
Post-increment operator.
NeighborIterator & operator++ ()
Pre-increment operator.
bool operator== (const NeighborIterator &rhs) const
Equality operator.
bool operator!= (const NeighborIterator &rhs) const
Inequality operator.
Friends
class BaseGridGeometry
Detailed Description
Class NeighborIterator iterates over the Neighbors of a block.
The iterator points to a mutable Neighbor.
Constructor & Destructor Documentation
SAMRAI::hier::BaseGridGeometry::NeighborIterator::NeighborIterator (const NeighborIterator & other)
Copy constructor.
Parameters:
[in] other The non-const iterator to copy.
References SAMRAI::hier::BlockId::getBlockValue(), and SAMRAI::hier::BlockId::setId().
SAMRAI::hier::BaseGridGeometry::NeighborIterator::~NeighborIterator ()
Destructor.
Member Function Documentation
NeighborIterator& SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator= (const NeighborIterator & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs The non-const iterator being assigned.
Returns:
This object after the assignment.
References SAMRAI::hier::BlockId::getBlockValue(), and SAMRAI::hier::BlockId::setId().
Neighbor& SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator* () const [inline]
Dereference operator.
Returns:
The Neighbor that the iterator is currently pointing to.
NeighborIterator SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator++ (int) [inline]
Post-increment operator.
Returns:
This iterator prior to having been incremented.
References SAMRAI::hier::BlockId::getBlockValue().
NeighborIterator& SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator++ () [inline]
Pre-increment operator.
Returns:
This iterator after having been incremented.
References SAMRAI::hier::BlockId::getBlockValue().
bool SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator== (const NeighborIterator & rhs) const [inline]
Equality operator.
Parameters:
[in] rhs The right hand side of the comparison.
Returns:
True if this and rhs are pointing to the same Neighbor of the same block of the same grid geometry.
bool SAMRAI::hier::BaseGridGeometry::NeighborIterator::operator!= (const NeighborIterator & rhs) const [inline]
Inequality operator.
Parameters:
[in] rhs The right hand side of the comparison.
Returns:
True if this and rhs are not pointing to different Neighbors or iterating over different block or different grid geometries.
Friends And Related Function Documentation
friend class BaseGridGeometry [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BaseGridGeometry.h
source/SAMRAI/hier/BaseGridGeometry.C