SAMRAI: SAMRAI::algs::TimeRefinementIntegrator Class Reference
SAMRAI::algs::TimeRefinementIntegrator Class Reference
#include <source/SAMRAI/algs/TimeRefinementIntegrator.h>
Public Member Functions
TimeRefinementIntegrator (const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const boost::shared_ptr< TimeRefinementLevelStrategy > &level_integrator, const boost::shared_ptr< mesh::GriddingAlgorithmStrategy > &gridding_algorithm)
virtual ~TimeRefinementIntegrator ()
double initializeHierarchy ()
double advanceHierarchy (const double dt, const bool rebalance_coarsest=false)
bool atRegridPoint (const int level_number) const
double getIntegratorTime () const
double getStartTime () const
double getEndTime () const
int getIntegratorStep () const
int getMaxIntegratorSteps () const
bool stepsRemaining (const int level_number) const
bool stepsRemaining () const
double getLevelDtActual (const int level_number) const
double getLevelDtMax (const int level_number) const
double getLevelSimTime (const int level_number) const
int getLevelStep (const int level_number) const
int getLevelMaxSteps (const int level_number) const
const boost::shared_ptr
< hier::PatchHierarchy > getPatchHierarchy () const
boost::shared_ptr
< TimeRefinementLevelStrategy > getLevelIntegrator () const
boost::shared_ptr
< mesh::GriddingAlgorithmStrategy > getGriddingAlgorithm () const
bool firstLevelStep (const int level_number) const
bool lastLevelStep (const int level_number) const
void setRegridInterval (const int regrid_interval)
virtual void printClassData (std::ostream &os) const
void printDataForLevel (std::ostream &os, const int level_number) const
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
const std::string & getObjectName () const
Detailed Description
Class TimeRefinementIntegrator manages time integration over an AMR patch hierarchy using local time refinement for finer hierarchy levels. This class orchestrates hierarchy construction, data advancement and synchronization, and the dynamic grid refinement processes. The basic ideas behind these algorithms are described in several sources on structured adaptive mesh refinement. See Berger and Colella, J. Comp. Phys. (82)1:64-84, 1989 for an introduction to algorithm. See Trangenstein, SIAM J. Sci. Comput. 16(4):819-839, 1995, or Hornung, PhD thesis, Dept. of Mathematics, Duke University, 1994 for further discussion.
This class can be used in two different modes: refined timestepping, which divides they hierarchy's timestep into smaller timesteps on finer levels, or synchronized timestepping, which advances all levels in a hierarchy by the same timestep. The mode that is used is determined by querying the level integrator that is passed into the constructor. One and only one mode can be used for each instantiation of this class.
The algorithm requires that integration steps on different levels are interleaved since the time increment used on each level is determined by the spatial resolution of the mesh on that level (e.g., CFL condition). Generally, when using refined timestepping, coarser levels use larger time increments than finer levels. Thus, data must be synchronized between levels and the dynamic regridding process must be coordinated with the time stepping sequence.
The routines in this class are implemented in a manner that is generic with respect to the details of the level integration and regridding methods, and the discrete equations being solved. Thus, the class may be employed for a variety of applications. Upon construction, an object of this class is configured with routines suitable for a given problem. The TimeRefinementLevelStrategy data member supplies routines for advancing levels and synchronizing data on different levels during time integration. The mesh::GriddingAlgorithmStrategy data member provides operations that construct and dynamically reconfigure the patch hierarchy. The collaboration between this class and each of those objects follows the Strategy design pattern.
Initialization begins by setting data on the coarsest AMR hierarchy level. Then, each successively finer level is created and initialized after invoking the regridding procedures on the most recently initialized level. This process is performed until either a maximum number of levels is reached or no further refinement is needed.
Time integration is performed by invoking a recursive advance procedure on the coarsest AMR hierarchy level. On a level, data is integrated to a given point using a sequence of integration steps, where the size of each time increment depends on the problem being solved. After each step on a level, the next finer level (if it exists) is integrated to the same time using a sequence of time steps appropriate for the level. This class may dynamically adjust the time step sequence used on each level during the data advance process depending on requirements of the integrator and information about stable time step size. Dynamic mesh regridding is invoked during the integration process so that time integration, data synchronization, and mesh movement are coordinated properly.
Input Parameters
Definitions:
regrid_interval when using synchronized timestepping, number of timesteps between each regrid of the hierarchy
start_time start time for the simulation.
end_time end time for the simulation.
grow_dt maximum factor by which each succesive time increment may grow (typically >= 1.0).
max_integrator_steps maximum number of timesteps performed on the coarsest hierarchy level during the simulation.
tag_buffer array of integer values (one for each level that may be refined) representing the number of cells by which tagged cells are buffered before clustering into boxes.
Note that the input values for regrid_interval, end_time, grow_dt, max_integrator_steps, and tag_buffer override values read in from restart.
Details:
parameter
type
default
range
opt/req
behavior on restart
regrid_interval
int
1
>=1
opt
Parameter read from restart db may be overridden by input db
start_time
double
none
start_time >=0
req
May not be modified by input db on restart
end_time
double
none
end_time >= start_time
req
Parameter read from restart db may be overridden by input db
grow_dt
double
1.0
>0
opt
Parameter read from restart db may be overridden by input db
max_integrator_steps
int
none
>=0
req
Parameter read from restart db may be overridden by input db
tag_buffer
array of ints
regrid_interval value for corresponding level
all values >= 0
opt
Parameter read from restart db may be overridden by input db
A sample input file entry might look like:
    start_time            = 0.e0      // initial simulation time
    end_time              = 10.e0     // final simulation time
    grow_dt               = 1.1e0     // growth factor for timesteps
    max_integrator_steps  = 50        // max number of simulation timesteps
    tag_buffer            = 1,1,1,1   // a max of 4 finer levels in hierarchy
See also:
TimeRefinementLevelStrategy
mesh::GriddingAlgorithmStrategy
Constructor & Destructor Documentation
SAMRAI::algs::TimeRefinementIntegrator::TimeRefinementIntegrator (const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const boost::shared_ptr< TimeRefinementLevelStrategy > & level_integrator, const boost::shared_ptr< mesh::GriddingAlgorithmStrategy > & gridding_algorithm)
The constructor for TimeRefinementIntegrator initializes the time stepping parameters needed to integrate the levels in the AMR hierarchy. Some data is set to default values; others are read from the specified input database and the restart database corresponding to the specified object_name. Consult top of this header file for further details.
Note that this object also invokes the variable creation and registration process in the level strategy.
Precondition:
!object_name.empty()
hierarchy
level_integrator
gridding_algorithm
References SAMRAI::tbox::RestartManager::getManager(), SAMRAI::hier::IntVector::max(), SAMRAI::tbox::plog, setRegridInterval(), SAMRAI::algs::TimeRefinementIntegratorConnectorWidthRequestor::setTagBuffer(), TBOX_ASSERT, and TBOX_ERROR.
SAMRAI::algs::TimeRefinementIntegrator::~TimeRefinementIntegrator () [virtual]
The destructor for TimeRefinementIntegrator unregisters the integrator object with the restart manager.
References SAMRAI::tbox::RestartManager::getManager().
Member Function Documentation
double SAMRAI::algs::TimeRefinementIntegrator::initializeHierarchy ()
Set AMR patch hierarchy configuration and data at start of simulation. If the run is begun from a restart file, the hierarchy and data are read from the hierarchy database. Otherwise, the hierarchy and data are initialized by the gridding algorithm data member. In this case, the coarsest level is constructed and initialized. Then, error estimation is performed to determine if and where it should be refined. Successively finer levels are created and initialized until the maximum allowable number of levels is achieved or no further refinement is needed. The double return value is the time increment for the first data advance step on the coarsest hierarchy level (i.e., level 0).
This function assumes that the hierarchy exists, but that it contains no patch levels, when it is called. On return from this function, the initial hierarchy configuration and simulation data is set properly for the advanceHierarchy() function to be called. In particular, on each level constructed only the data needed for initialization exists.
References SAMRAI::tbox::RestartManager::getManager().
double SAMRAI::algs::TimeRefinementIntegrator::advanceHierarchy (const double dt, const bool rebalance_coarsest = false)
Advance each level in the hierarchy through the given time increment and return an appropriate time increment for subsequent advances of the coarsest hierarchy level (level 0). The boolean argument indicates whether the coarsest hierarchy level (i.e., level 0) should be load balanced before the levels are advanced. In general, the problem domain (determined by the union of patches on level 0) does not change once set. However, the boolean flag here allows one to reconfigure the patches on the coarsest level which constitute this union. This may be required depending on a dynamic change of the work load. By default, the level will not be subject to load balancing.
This function assumes that all data on each level in the hierarchy has been set and that only the data need for initialization exists on each level (as opposed to both current and new data, for example). Upon return from this function, the simulation data on each hierarchy levels is advanced through the time increment dt. In addition, data on all hierarchy levels has been synchronized so that it is consistent at the new simulation time (where this synchronization process is defined by the level strategy). Thus, the data is set properly for any subsequent calls to this function.
Precondition:
dt >= 0
References TBOX_ASSERT.
bool SAMRAI::algs::TimeRefinementIntegrator::atRegridPoint (const int level_number) const
Return true if the current step count for the level indicates that regridding should occur. In particular, true is returned if both the level allows refinement and the step count is an integer multiple of the regrid step interval. Otherwise, false is returned.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
double SAMRAI::algs::TimeRefinementIntegrator::getIntegratorTime () const [inline]
Return current integration time for coarsest hierarchy level.
double SAMRAI::algs::TimeRefinementIntegrator::getStartTime () const [inline]
Return initial integration time.
double SAMRAI::algs::TimeRefinementIntegrator::getEndTime () const [inline]
Return final integration time.
int SAMRAI::algs::TimeRefinementIntegrator::getIntegratorStep () const [inline]
Return integration step count for entire hierarchy (i.e., number of steps taken by the coarsest level).
int SAMRAI::algs::TimeRefinementIntegrator::getMaxIntegratorSteps () const [inline]
Return maximum number of integration steps allowed for entire hierarchy (i.e., steps allowed on coarsest level).
bool SAMRAI::algs::TimeRefinementIntegrator::stepsRemaining (const int level_number) const [inline]
Return true if any steps remain in current step sequence on level (i.e., before it will synchronize with some coarser level). Return false otherwise.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
bool SAMRAI::algs::TimeRefinementIntegrator::stepsRemaining () const [inline]
Return true if any integration steps remain, false otherwise.
double SAMRAI::algs::TimeRefinementIntegrator::getLevelDtActual (const int level_number) const [inline]
Return current time increment used to advance level.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
double SAMRAI::algs::TimeRefinementIntegrator::getLevelDtMax (const int level_number) const [inline]
Return maximum time increment currently allowed on level.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
double SAMRAI::algs::TimeRefinementIntegrator::getLevelSimTime (const int level_number) const [inline]
Return current simulation time for level.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
int SAMRAI::algs::TimeRefinementIntegrator::getLevelStep (const int level_number) const [inline]
Return step count for current integration sequence on level.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
int SAMRAI::algs::TimeRefinementIntegrator::getLevelMaxSteps (const int level_number) const [inline]
Return maximum number of time steps allowed on level in current integration step sequence.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
const boost::shared_ptr<hier::PatchHierarchy> SAMRAI::algs::TimeRefinementIntegrator::getPatchHierarchy () const [inline]
Return const pointer to patch hierarchy managed by integrator.
boost::shared_ptr<TimeRefinementLevelStrategy> SAMRAI::algs::TimeRefinementIntegrator::getLevelIntegrator () const [inline]
Return pointer to level integrator.
boost::shared_ptr<mesh::GriddingAlgorithmStrategy> SAMRAI::algs::TimeRefinementIntegrator::getGriddingAlgorithm () const [inline]
Return pointer to gridding algorithm object.
bool SAMRAI::algs::TimeRefinementIntegrator::firstLevelStep (const int level_number) const [inline]
Return true if current step on level is first in current step sequence; otherwise return false.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
bool SAMRAI::algs::TimeRefinementIntegrator::lastLevelStep (const int level_number) const [inline]
Return true if current step on level is last in current step sequence; otherwise return false.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
void SAMRAI::algs::TimeRefinementIntegrator::setRegridInterval (const int regrid_interval)
Set the regrid interval to a new value. This may only be used when using synchronized timestepping.
Precondition:
!d_use_refined_timestepping
References SAMRAI::tbox::plog, and TBOX_ASSERT.
Referenced by TimeRefinementIntegrator().
void SAMRAI::algs::TimeRefinementIntegrator::printClassData (std::ostream & os) const [virtual]
Print data representation of this object to given output stream.
References printDataForLevel().
void SAMRAI::algs::TimeRefinementIntegrator::printDataForLevel (std::ostream & os, const int level_number) const
Print time stepping data for a single level to given output stream.
Precondition:
(level_number >= 0) && (level_number <= getPatchHierarchy()->getFinestLevelNumber())
References TBOX_ASSERT.
Referenced by printClassData().
void SAMRAI::algs::TimeRefinementIntegrator::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Write object state out to the given restart database.
Precondition:
restart_db
References TBOX_ASSERT.
const std::string& SAMRAI::algs::TimeRefinementIntegrator::getObjectName () const [inline]
Returns the object name.
The documentation for this class was generated from the following files:
source/SAMRAI/algs/TimeRefinementIntegrator.h
source/SAMRAI/algs/TimeRefinementIntegrator.C