SAMRAI: SAMRAI::hier::UncoveredBoxIterator Class Reference
SAMRAI::hier::UncoveredBoxIterator Class Reference
An iterator over the uncovered Boxes in a hierarhcy.
#include <source/SAMRAI/hier/UncoveredBoxIterator.h>
Public Member Functions
UncoveredBoxIterator (const UncoveredBoxIterator &other)
Copy constructor.
~UncoveredBoxIterator ()
UncoveredBoxIterator & operator= (const UncoveredBoxIterator &rhs)
Assignment operator.
const std::pair
< boost::shared_ptr< Patch >
, Box > & operator* () const
Dereference operator mimicking a pointer dereference.
const std::pair
< boost::shared_ptr< Patch >
, Box > * operator-> () const
Dereference operator mimicking a pointer dereference.
bool operator== (const UncoveredBoxIterator &rhs) const
Equality comparison.
bool operator!= (const UncoveredBoxIterator &rhs) const
Inequality comparison.
UncoveredBoxIterator & operator++ ()
Pre-increment iterator.
UncoveredBoxIterator operator++ (int)
Post-increment iterator.
Friends
class PatchHierarchy
class FlattenedHierarchy
Detailed Description
An iterator over the uncovered Boxes in a hierarhcy.
This iterator points to a pair consisting of the current uncovered Box and the Patch with which it is associated. Note that in the case of overlapping Patches in which the overlap is uncovered, the overlapping region will appear multiple times in the iteration. The number of appearances is equal to the number of Patches that overlap that region.
Constructor & Destructor Documentation
SAMRAI::hier::UncoveredBoxIterator::UncoveredBoxIterator (const UncoveredBoxIterator & other)
Copy constructor.
Parameters:
[in] other The iterator being copied.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), FlattenedHierarchy, SAMRAI::hier::FlattenedHierarchy::getVisibleBoxes(), and TBOX_ASSERT.
SAMRAI::hier::UncoveredBoxIterator::~UncoveredBoxIterator ()
Destructor.
Member Function Documentation
UncoveredBoxIterator & SAMRAI::hier::UncoveredBoxIterator::operator= (const UncoveredBoxIterator & rhs)
Assignment operator.
Parameters:
[in] rhs The right hand side of the assignment.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), FlattenedHierarchy, SAMRAI::hier::FlattenedHierarchy::getVisibleBoxes(), and TBOX_ASSERT.
const std::pair< boost::shared_ptr< Patch >, Box > & SAMRAI::hier::UncoveredBoxIterator::operator* () const
Dereference operator mimicking a pointer dereference.
const std::pair< boost::shared_ptr< Patch >, Box > * SAMRAI::hier::UncoveredBoxIterator::operator-> () const
Dereference operator mimicking a pointer dereference.
bool SAMRAI::hier::UncoveredBoxIterator::operator== (const UncoveredBoxIterator & rhs) const
Equality comparison.
Parameters:
[in] rhs The right hand side of the comparison.
bool SAMRAI::hier::UncoveredBoxIterator::operator!= (const UncoveredBoxIterator & rhs) const
Inequality comparison.
Parameters:
[in] rhs The right hand side of the comparison.
UncoveredBoxIterator & SAMRAI::hier::UncoveredBoxIterator::operator++ ()
Pre-increment iterator.
Pre-increment increment the iterator and returns the incremented state.
UncoveredBoxIterator SAMRAI::hier::UncoveredBoxIterator::operator++ (int)
Post-increment iterator.
Post-increment saves the iterator, increments it and returns the saved iterator.
Friends And Related Function Documentation
friend class PatchHierarchy [friend]
friend class FlattenedHierarchy [friend]
Referenced by operator=(), and UncoveredBoxIterator().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/UncoveredBoxIterator.h
source/SAMRAI/hier/UncoveredBoxIterator.C