SAMRAI: SAMRAI::math::ArrayDataNormOpsComplex Class Reference
SAMRAI::math::ArrayDataNormOpsComplex Class Reference
#include <source/SAMRAI/math/ArrayDataNormOpsComplex.h>
Public Member Functions
ArrayDataNormOpsComplex ()
~ArrayDataNormOpsComplex ()
void abs (pdat::ArrayData< double > &dst, const pdat::ArrayData< dcomplex > &src, const hier::Box &box) const
double sumControlVolumes (const pdat::ArrayData< dcomplex > &data, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
double L1NormWithControlVolume (const pdat::ArrayData< dcomplex > &data, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
double L1Norm (const pdat::ArrayData< dcomplex > &data, const hier::Box &box) const
double L2NormWithControlVolume (const pdat::ArrayData< dcomplex > &data, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
double L2Norm (const pdat::ArrayData< dcomplex > &data, const hier::Box &box) const
double weightedL2NormWithControlVolume (const pdat::ArrayData< dcomplex > &data, const pdat::ArrayData< dcomplex > &wgt, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
double weightedL2Norm (const pdat::ArrayData< dcomplex > &data, const pdat::ArrayData< dcomplex > &wgt, const hier::Box &box) const
double maxNormWithControlVolume (const pdat::ArrayData< dcomplex > &data, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
double maxNorm (const pdat::ArrayData< dcomplex > &data, const hier::Box &box) const
dcomplex dotWithControlVolume (const pdat::ArrayData< dcomplex > &data1, const pdat::ArrayData< dcomplex > &data2, const pdat::ArrayData< double > &cvol, const hier::Box &box) const
dcomplex dot (const pdat::ArrayData< dcomplex > &data1, const pdat::ArrayData< dcomplex > &data2, const hier::Box &box) const
dcomplex integral (const pdat::ArrayData< dcomplex > &data, const pdat::ArrayData< double > &vol, const hier::Box &box) const
Detailed Description
Class ArrayDataNormOpsComplex provides a set of common norm operations that may be applied to arrays of complex data values maintained as pdat::ArrayData<TYPE> objects. The intent of this class is to provide a single implementation of these operations as they are needed by objects that perform these operations on the standard array-based patch data types (i.e., cell-centered, face-centered, node-centered). Each of the norm operations is implemented in two different ways. The choice of operation is based on whether control volume information is to be used to weight the contribution of each data entry to the norm calculation. The use of control volumes is important when these operations are used in vector kernels where the data resides over multiple levels in an AMR hierarchy. Note also that each operation will be performed on the intersection of the box in the function argument list and the boxes associated with all pdat::ArrayData<TYPE> objects.
Note that a similar set of norm operations is implemented for real array data (double and float) in the class ArrayDataNormOpsReal.
See also:
pdat::ArrayData
Constructor & Destructor Documentation
SAMRAI::math::ArrayDataNormOpsComplex::ArrayDataNormOpsComplex ()
Empty constructor and destructor.
SAMRAI::math::ArrayDataNormOpsComplex::~ArrayDataNormOpsComplex ()
Member Function Documentation
void SAMRAI::math::ArrayDataNormOpsComplex::abs (pdat::ArrayData< double > & dst, const pdat::ArrayData< dcomplex > & src, const hier::Box & box) const
Set destination component to norm of source component. That is, each destination entry is set to .
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == box.getDim())
dst.getDepth() == src.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::abs(), SAMRAI::math::PatchNodeDataNormOpsComplex::abs(), SAMRAI::math::PatchFaceDataNormOpsComplex::abs(), SAMRAI::math::PatchEdgeDataNormOpsComplex::abs(), and SAMRAI::math::PatchCellDataNormOpsComplex::abs().
double SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes (const pdat::ArrayData< dcomplex > & data, const pdat::ArrayData< double > & cvol, const hier::Box & box) const
Return sum of entries in control volume array.
Precondition:
(data.getDim() == cvol.getDim()) && (data.getDim() == box.getDim())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchNodeDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchFaceDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchEdgeDataNormOpsComplex::sumControlVolumes(), and SAMRAI::math::PatchCellDataNormOpsComplex::sumControlVolumes().
double SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume (const pdat::ArrayData< dcomplex > & data, const pdat::ArrayData< double > & cvol, const hier::Box & box) const
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum .
Precondition:
(data.getDim() == cvol.getDim()) && (data.getDim() == box.getDim())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L1Norm(), and SAMRAI::math::PatchCellDataNormOpsComplex::L1Norm().
double SAMRAI::math::ArrayDataNormOpsComplex::L1Norm (const pdat::ArrayData< dcomplex > & data, const hier::Box & box) const
Return discrete -norm of the data. That is, the return value is the sum .
Precondition:
(data.getDim() == box.getDim()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L1Norm(), and SAMRAI::math::PatchCellDataNormOpsComplex::L1Norm().
double SAMRAI::math::ArrayDataNormOpsComplex::L2NormWithControlVolume (const pdat::ArrayData< dcomplex > & data, const pdat::ArrayData< double > & cvol, const hier::Box & box) const [inline]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum .
Precondition:
(data.getDim() == cvol.getDim()) && (data.getDim() == box.getDim())
References dotWithControlVolume(), and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L2Norm(), and SAMRAI::math::PatchCellDataNormOpsComplex::L2Norm().
double SAMRAI::math::ArrayDataNormOpsComplex::L2Norm (const pdat::ArrayData< dcomplex > & data, const hier::Box & box) const [inline]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum .
Precondition:
data.getDim() == box.getDim()
References dot(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L2Norm(), and SAMRAI::math::PatchCellDataNormOpsComplex::L2Norm().
double SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume (const pdat::ArrayData< dcomplex > & data, const pdat::ArrayData< dcomplex > & wgt, const pdat::ArrayData< double > & cvol, const hier::Box & box) const
Return discrete weighted -norm of the data using the control volume to weight the contribution of the data and weight entries to the sum. That is, the return value is the sum .
Precondition:
(data.getDim() == wgt.getDim()) && (data.getDim() == cvol.getDim()) && (data.getDim() == box.getDim())
data.getDepth() == wgt.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::weightedL2Norm(), and SAMRAI::math::PatchCellDataNormOpsComplex::weightedL2Norm().
double SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm (const pdat::ArrayData< dcomplex > & data, const pdat::ArrayData< dcomplex > & wgt, const hier::Box & box) const
Return discrete weighted -norm of the data. That is, the return value is the sum .
Precondition:
(data.getDim() == wgt.getDim()) && (data.getDim() == box.getDim())
data.getDepth() == wgt.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchFaceDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::weightedL2Norm(), and SAMRAI::math::PatchCellDataNormOpsComplex::weightedL2Norm().
double SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume (const pdat::ArrayData< dcomplex > & data, const pdat::ArrayData< double > & cvol, const hier::Box & box) const
Return the -norm of the data using the control volume to weight the contribution of each data entry to the maximum. That is, the return value is , where the max is over the data elements where .
Precondition:
(data.getDim() == cvol.getDim()) && (data.getDim() == box.getDim())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchNodeDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchFaceDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::maxNorm(), and SAMRAI::math::PatchCellDataNormOpsComplex::maxNorm().
double SAMRAI::math::ArrayDataNormOpsComplex::maxNorm (const pdat::ArrayData< dcomplex > & data, const hier::Box & box) const
Return the -norm of the data. That is, the return value is .
Precondition:
data.getDim() == box.getDim()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchNodeDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchFaceDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::maxNorm(), and SAMRAI::math::PatchCellDataNormOpsComplex::maxNorm().
dcomplex SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume (const pdat::ArrayData< dcomplex > & data1, const pdat::ArrayData< dcomplex > & data2, const pdat::ArrayData< double > & cvol, const hier::Box & box) const
Return the dot product of the two data arrays using the control volume to weight the contribution of each product to the sum. That is, the return value is the sum .
Precondition:
(data1.getDim() == data2.getDim()) && (data1.getDim() == cvol.getDim()) && (data1.getDim() == box.getDim())
data1.getDepth() == data2.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::dot(), SAMRAI::math::PatchNodeDataNormOpsComplex::dot(), SAMRAI::math::PatchFaceDataNormOpsComplex::dot(), SAMRAI::math::PatchEdgeDataNormOpsComplex::dot(), SAMRAI::math::PatchCellDataNormOpsComplex::dot(), and L2NormWithControlVolume().
dcomplex SAMRAI::math::ArrayDataNormOpsComplex::dot (const pdat::ArrayData< dcomplex > & data1, const pdat::ArrayData< dcomplex > & data2, const hier::Box & box) const
Return the dot product of the two data arrays. That is, the return value is the sum .
Precondition:
(data1.getDim() == data2.getDim()) && (data1.getDim() == box.getDim())
data1.getDepth() == data2.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::dot(), SAMRAI::math::PatchNodeDataNormOpsComplex::dot(), SAMRAI::math::PatchFaceDataNormOpsComplex::dot(), SAMRAI::math::PatchEdgeDataNormOpsComplex::dot(), SAMRAI::math::PatchCellDataNormOpsComplex::dot(), and L2Norm().
dcomplex SAMRAI::math::ArrayDataNormOpsComplex::integral (const pdat::ArrayData< dcomplex > & data, const pdat::ArrayData< double > & vol, const hier::Box & box) const
Return the integral of the function based on the data array. The return value is the sum .
Precondition:
(data.getDim() == vol.getDim()) && (data.getDim() == box.getDim())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::PatchSideDataNormOpsComplex::integral(), SAMRAI::math::PatchNodeDataNormOpsComplex::integral(), SAMRAI::math::PatchFaceDataNormOpsComplex::integral(), SAMRAI::math::PatchEdgeDataNormOpsComplex::integral(), and SAMRAI::math::PatchCellDataNormOpsComplex::integral().
The documentation for this class was generated from the following files:
source/SAMRAI/math/ArrayDataNormOpsComplex.h
source/SAMRAI/math/ArrayDataNormOpsComplex.C