SAMRAI: SAMRAI::math::PatchCellDataOpsComplex Class Reference
SAMRAI::math::PatchCellDataOpsComplex Class Reference
#include <source/SAMRAI/math/PatchCellDataOpsComplex.h>
Public Member Functions
PatchCellDataOpsComplex ()
virtual ~PatchCellDataOpsComplex ()
void copyData (const boost::shared_ptr< pdat::CellData< dcomplex > > &dst, const boost::shared_ptr< pdat::CellData< dcomplex > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::CellData< dcomplex > > &dst, const dcomplex &alpha, const hier::Box &box) const
Detailed Description
Class PatchCellDataOpsComplex provides a collection of operations that may be used to manipulate complex cell-centered patch data. The operations include basic arithmetic and norms. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base classes PatchCellDataBasicOps, PatchCellDataNormOpsComplex from which it is derived. The name of each of these base classes is indicative of the set of cell-centered patch data operations that it provides.
A similar set of operations is implemented for real (double and float) and integer patch data in the classes PatchCellDataOpsReal and PatchCellDataOpsInteger, respectively.
See also:
PatchCellDataBasicOps
PatchCellDataNormOpsComplex
Constructor & Destructor Documentation
SAMRAI::math::PatchCellDataOpsComplex::PatchCellDataOpsComplex ()
Empty constructor and destructor.
SAMRAI::math::PatchCellDataOpsComplex::~PatchCellDataOpsComplex () [virtual]
Member Function Documentation
void SAMRAI::math::PatchCellDataOpsComplex::copyData (const boost::shared_ptr< pdat::CellData< dcomplex > > & dst, const boost::shared_ptr< pdat::CellData< dcomplex > > & src, const hier::Box & box) const [inline]
Copy dst data to src data over given box.
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::copyData().
void SAMRAI::math::PatchCellDataOpsComplex::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::CellData<dcomplex> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::CellData<dcomplex> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::swapData().
void SAMRAI::math::PatchCellDataOpsComplex::printData (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const [inline]
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::printData().
void SAMRAI::math::PatchCellDataOpsComplex::setToScalar (const boost::shared_ptr< pdat::CellData< dcomplex > > & dst, const dcomplex & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::setToScalar().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchCellDataOpsComplex.h
source/SAMRAI/math/PatchCellDataOpsComplex.C