SAMRAI: SAMRAI::hier::VariableDatabase Class Reference
SAMRAI::hier::VariableDatabase Class Reference
Generates and manages mappings between Variables and/or (Variable,VariableContext) pairs and patch data indices.
#include <source/SAMRAI/hier/VariableDatabase.h>
Public Member Functions
virtual int getNumberOfRegisteredPatchDataIndices () const
Get the number of patch data indices registered with the database.
virtual int getNumberOfRegisteredVariableContexts () const
Get number of variable contexts registered with the database.
virtual boost::shared_ptr
< PatchDescriptor > getPatchDescriptor () const
Get the patch descriptor managed by the database.
virtual boost::shared_ptr
< VariableContext > getContext (const std::string &context_name)
Creates or returns a VariableContext object with the given name.
virtual bool checkContextExists (const std::string &context_name) const
Check whether context with given name exists in the database.
virtual void addVariable (const boost::shared_ptr< Variable > &variable)
Add the Variable to the database.
virtual void removeVariable (const std::string &variable_name)
Remove the Variable from the database identified by name.
virtual boost::shared_ptr
< Variable > getVariable (const std::string &variable_name) const
Get variable in database with given name string identifier.
virtual bool checkVariableExists (const std::string &variable_name) const
Check whether a variable with given name exists in the database.
virtual int registerClonedPatchDataIndex (const boost::shared_ptr< Variable > &variable, int old_id)
Create and register a new patch data index by cloning the data factory associated with the Variable at the index provided.
virtual int registerPatchDataIndex (const boost::shared_ptr< Variable > &variable, int data_id=idUndefined())
Add given patch data index and variable pair to the database.
virtual void removePatchDataIndex (int data_id)
Remove the patch data index from the VariableDatabase if it exists.
virtual bool checkVariablePatchDataIndex (const boost::shared_ptr< Variable > &variable, int data_id) const
Check whether the given variable is mapped to the given patch data index in the database.
virtual bool checkVariablePatchDataIndexType (const boost::shared_ptr< Variable > &variable, int data_id) const
Check whether the given variable matches the patch data type associated with the given patch data index in the database.
virtual int registerVariableAndContext (const boost::shared_ptr< Variable > &variable, const boost::shared_ptr< VariableContext > &context, const IntVector &ghosts)
Register variable and context pair along with the ghost width for the patch data mapped to the (Variable, VariableContext) pair with the variable database.
virtual int mapVariableAndContextToIndex (const boost::shared_ptr< Variable > &variable, const boost::shared_ptr< VariableContext > &context) const
Map variable-context pair in database to patch data index.
virtual bool mapIndexToVariable (const int index, boost::shared_ptr< Variable > &variable) const
Map patch data index to variable associated with the data, if possible, and set the variable pointer to the variable in the database.
virtual bool mapIndexToVariableAndContext (const int index, boost::shared_ptr< Variable > &variable, boost::shared_ptr< VariableContext > &context) const
Map patch data index to variable-context pair associated with the data, if possible, and set the variable and context pointers to the corresponding database entries.
virtual void printClassData (std::ostream &os=tbox::plog, bool print_only_user_defined_variables=true) const
Print variable, context, and patch descriptor information contained in the database to the specified output stream.
virtual int registerInternalSAMRAIVariable (const boost::shared_ptr< Variable > &variable, const IntVector &ghosts)
Register internal SAMRAI variable and ghost width with the variable database.
virtual void removeInternalSAMRAIVariablePatchDataIndex (int data_id)
Remove the given index from the variable database if it exists in the database and is associated with an internal SAMRAI variable registered with the function registerInternalSAMRAIVariable().
Static Public Member Functions
static VariableDatabase * getDatabase ()
Return a pointer to the singleton variable database instance.
Protected Member Functions
VariableDatabase ()
The constructor for VariableDatabase is protected. Consistent with the definition of a Singleton class, only the database object has access to the constructor for the class.
virtual ~VariableDatabase ()
The destructor for VariableDatabase is protected. See the comments for the constructor.
int getVariableId (const std::string &name) const
Return integer identifier for first variable found matching given string name identifier (care must be used to avoid adding variables to database with same name to insure correct behavior), or return an undefined integer index if no such variable exists in the database.
void registerSingletonSubclassInstance (VariableDatabase *subclass_instance)
Initialize Singleton instance with instance of subclass. This function is used to make the singleton object unique when inheriting from this base class.
Static Protected Member Functions
static int idUndefined ()
Return integer value used to indicate undefined variable or context identifier. This routine is protected to allow subclasses to be consistent with this database class.
Detailed Description
Generates and manages mappings between Variables and/or (Variable,VariableContext) pairs and patch data indices.
This class is a Singleton, and serves as a globally accessible lookup table for the bookkeeping information related to variable storage on a SAMRAI patch hierarchy. The database may be used to manage the mapping between a Variable or (Variable,VariableContext) pair and the patch data index associated with the data for the Variable or (Variable,VariableContext) pair.
Typically, numerical routines or solution algorithms manage and access data in terms of Variables and/or (Variable,VariableContext) pairs (e.g., "OLD", "NEW").
Definitions
Patch data index: SAMRAI uses a patch data index value (an integer) to lookup patch data information in the patch descriptor object that is shared by all patches in a SAMR hierarchy.
Variable: A storage management class. Each concrete implementation (cell-centered, node-centered, etc.) provides the appropriate storage management for that type.
VariableContext: A way to consistently address the state of a variable in multiple contexts. For example, an application may need to manage data for "OLD" pressure values as well as "NEW" pressure values. The context allows the user to have a single variable in multiple contexts, without having to create multiple variables. A context is optional and a user could create multiple variables; e.g., "pressure_old" and "pressure_new".
When the association between Variable and VariableContext is needed, the registration operations are used to create this association. Each variable and context pair maps to a unique integer patch data index. The integer indices are the same for every patch in the hierarchy so data objects are accessed identically for all patches.
The following example shows the mapping between a PatchData indices and a Variable/VariableContext pair.
    PatchData Index   Variable   Context
    ================  ========   =======
    index = 0         uval       CURRENT
    index = 1         flux       CURRENT
    index = 2         flux       SCRATCH
Usage
The typical way to use the database is as follows:
Add Variable to the database
Get or create the VariableContext via the getContext() function
Register the VariableContext pair in the database
    // other setup including dimension and IntVectors specifying ghosts
    ...
    // Get the singleton variable database.
    VariableDatabase* var_db = VariableDatabase.getDatabase();
    // Create the context (or access it if it exists already).
    boost::shared_ptr<VariableContext> current =
       var_db->getContext("CURRENT");
    // Define the variable.
    boost::shared_ptr<pdat::FaceVariable<double> > flux(
       new pdat::FaceVariable<double>(dim, "flux", 1));
    // Register the Variable/VariableContext pair.
    // "ghosts" is an IntVector defining the data ghost width for this
    // usage context.  Note that other contexts may have different ghost
    // widthsi for the same variable.
    const int flux_current_id =
       var_db->registerVariableAndContext(flux, current, ghosts);
A Variable can also be added to the database using the addVariable() function. This function does not register a mapping between a Variable and VariableContext, rather it is used when there are multiple objects needing to access a single Variable. This eliminates issues with shared objects, order of creation, etc. For example, two different algorithms in an application may need to access the current value for pressure. Each of these algorithms may use the database to access the patch data index of this shared state. This is not needed if registerVariableAndContext() is used.
Alternate Usage
The database can be used to maintain a mapping between a single patch data index and a Variable. This type of mapping is constructed using either the registerPatchDataIndex() function or registerClonedPatchDataIndex() function.
Add variable and index pair to the database via the addVariablePatchDataIndex() function. Or, clone an existing variable-index pair via registerClonedPatchDataIndex(). Either of these functions will check to make sure that the type of the variable matches the given patch data index.
Get variable for the index via the mapIndexToVariable() function.
The database is also used in SAMRAI to manage the reading/writing of patch data objects to/from restart files.
Note:
Variable names are unique in the database
VariableContext names are unique in the database
VariableContext should be generated solely through the use of the getContext() function to avoid unexpected results; e.g., multiple context objects with the same name.
A Variable can be removed from the database using removeVariable().
The database can free PatchData indices using removepatchDataIndex() function.
A VariableContext persists once created and cannot be removed from the database.
The database is reset (all data wiped) during shutdown. It is started from a clean state during a new startup.
See also:
PatchDescriptor
VariableContext
Variable
Patch
Constructor & Destructor Documentation
SAMRAI::hier::VariableDatabase::VariableDatabase () [protected]
The constructor for VariableDatabase is protected. Consistent with the definition of a Singleton class, only the database object has access to the constructor for the class.
The constructor initializes the state of database contents.
References getContext(), and idUndefined().
Referenced by getDatabase().
SAMRAI::hier::VariableDatabase::~VariableDatabase () [protected, virtual]
The destructor for VariableDatabase is protected. See the comments for the constructor.
The destructor deallocates database contents.
Member Function Documentation
VariableDatabase * SAMRAI::hier::VariableDatabase::getDatabase () [static]
Return a pointer to the singleton variable database instance.
Note:
When the database is accessed for the first time, the Singleton instance is registered with the StartupShutdownManager class which destroys such objects at program completion. Thus, this class is not explicitly allocated or deallocated.
Returns:
Bare pointer to variable database instance.
References VariableDatabase().
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::addComponent(), SAMRAI::solv::CellPoissonFACSolver::CellPoissonFACSolver(), SAMRAI::solv::CellPoissonFACOps::checkInputPatchDataIndices(), SAMRAI::solv::SAMRAIVectorReal< TYPE >::cloneVector(), SAMRAI::solv::SAMRAIVectorReal< TYPE >::freeVectorComponents(), SAMRAI::hier::Patch::getPatchData(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), SAMRAI::xfer::RefineClasses::itemIsValid(), SAMRAI::xfer::CoarsenClasses::itemIsValid(), SAMRAI::xfer::RefineClasses::itemsAreEquivalent(), SAMRAI::xfer::CoarsenClasses::itemsAreEquivalent(), SAMRAI::xfer::CoarsenClasses::printCoarsenItem(), SAMRAI::xfer::RefineClasses::printRefineItem(), SAMRAI::xfer::CoarsenAlgorithm::registerCoarsen(), SAMRAI::appu::VisItDataWriter::registerNodeCoordinates(), SAMRAI::xfer::RefineAlgorithm::registerRefine(), SAMRAI::appu::VisItDataWriter::registerSingleNodeCoordinate(), SAMRAI::algs::PatchBoundaryEdgeSum::registerSum(), SAMRAI::algs::MethodOfLinesIntegrator::registerVariable(), SAMRAI::appu::VisItDataWriter::resetLevelPlotQuantity(), SAMRAI::solv::GhostCellRobinBcCoefs::setGhostDataId(), SAMRAI::mesh::MultiblockGriddingTagger::setScratchTagPatchDataIndex(), SAMRAI::mesh::TreeLoadBalancer::setWorkloadPatchDataIndex(), SAMRAI::mesh::ChopAndPackLoadBalancer::setWorkloadPatchDataIndex(), SAMRAI::mesh::CascadePartitioner::setWorkloadPatchDataIndex(), SAMRAI::solv::CellPoissonFACSolver::~CellPoissonFACSolver(), and SAMRAI::algs::PatchBoundaryEdgeSum::~PatchBoundaryEdgeSum().
int SAMRAI::hier::VariableDatabase::getNumberOfRegisteredPatchDataIndices () const [virtual]
Get the number of patch data indices registered with the database.
int SAMRAI::hier::VariableDatabase::getNumberOfRegisteredVariableContexts () const [virtual]
Get number of variable contexts registered with the database.
boost::shared_ptr< PatchDescriptor > SAMRAI::hier::VariableDatabase::getPatchDescriptor () const [virtual]
Get the patch descriptor managed by the database.
This descriptor is shared by all patches in the hierarchy.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::addComponent(), and SAMRAI::algs::PatchBoundaryEdgeSum::registerSum().
boost::shared_ptr< VariableContext > SAMRAI::hier::VariableDatabase::getContext (const std::string & context_name) [virtual]
Creates or returns a VariableContext object with the given name.
If a context exists in the database with the given name, it is returned. Otherwise, a new context is created and returned.
Note:
It is impossible to add two distinct variable context objects to the database with the same name.
The name must not be empty; a null pointer will be return in this case.
Parameters:
[in] context_name
Returns:
Variable context.
References idUndefined().
Referenced by VariableDatabase().
bool SAMRAI::hier::VariableDatabase::checkContextExists (const std::string & context_name) const [virtual]
Check whether context with given name exists in the database.
Parameters:
[in] context_name
References idUndefined().
void SAMRAI::hier::VariableDatabase::addVariable (const boost::shared_ptr< Variable > & variable) [virtual]
Add the Variable to the database.
If the given Variable already exists nothing is done; the same Variable may be added multiple times. If a Variable exists with the same name identifier but is a different Variable object, an error will be logged and the program will abort. This prevents multiple Variables being associated with the same name.
Parameters:
[in] variable boost::shared_ptr to variable
Precondition:
variable
References TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::VariableDatabase::removeVariable (const std::string & variable_name) [virtual]
Remove the Variable from the database identified by name.
Parameters:
[in] variable_name
References getVariableId(), idUndefined(), and removePatchDataIndex().
boost::shared_ptr< Variable > SAMRAI::hier::VariableDatabase::getVariable (const std::string & variable_name) const [virtual]
Get variable in database with given name string identifier.
Parameters:
[in] variable_name
Returns:
Variable in the database with given name. If no such variable exists, a null pointer is returned.
References getVariableId(), and idUndefined().
Referenced by SAMRAI::solv::CellPoissonFACSolver::CellPoissonFACSolver(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), and SAMRAI::algs::PatchBoundaryEdgeSum::registerSum().
bool SAMRAI::hier::VariableDatabase::checkVariableExists (const std::string & variable_name) const [virtual]
Check whether a variable with given name exists in the database.
Parameters:
[in] variable_name
Returns:
True if variable with name exists in database; otherwise, false.
References getVariableId(), and idUndefined().
int SAMRAI::hier::VariableDatabase::registerClonedPatchDataIndex (const boost::shared_ptr< Variable > & variable, int old_id) [virtual]
Create and register a new patch data index by cloning the data factory associated with the Variable at the index provided.
The new index and variable pair is added to the VariableDatabase. A variable-patch data index pair generated using this function cannot be looked up using a VariableContext. If the old_id is invalid or undefined, or does not map to patch data of the same type as variable, the program will abort with an error message.
Note:
This function does not deallocate any patch data storage associated with the new patch data index.
Parameters:
[in] variable boost::shared_ptr to Variable. If the variable is unknown to the database, then an invalid patch data index (< 0) will be returned
[in] old_id Integer patch data index currently associated with variable. If this value is not a valid patch data index (< 0) or does not map to patch data matching the type of the given variable, the program will abort with an error message.
Returns:
New integer patch data index. If new patch data not added, return value is an invalid (undefined) patch data index (< 0).
Precondition:
variable
checkVariablePatchDataIndex(variable, old_id)
References checkVariablePatchDataIndex(), idUndefined(), SAMRAI::tbox::Utilities::intToString(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::cloneVector().
int SAMRAI::hier::VariableDatabase::registerPatchDataIndex (const boost::shared_ptr< Variable > & variable, int data_id = idUndefined()) [virtual]
Add given patch data index and variable pair to the database.
This registration function is primarily intended for Variable objects (i.e., DO NOT use for internal SAMRAI variables) that are not associated with a VariableContext and for which a patch data index is already known.
[Default Case]
If the index is unspecified, the default variable factory is cloned and the Variable and new index are added to the database. In this case, the patch data will have the default ghost associated with the given variable (defined by the patch data factory it generates).
Note:
variable-patch data index pair generated with this function cannot be looked up using a VariableContext.
This function does not allocate any patch data storage associated with the integer index.
This function must not be used by SAMRAI developers for creating patch data indices for internal SAMRAI variables. The routine registerInternalSAMRAIVariable() must be used for that case.
Parameters:
[in] variable boost::shared_ptr to Variable
[in] data_id Optional integer patch data index to be added (along with variable) to the database. If the value is unspecified (default case), the default variable patch data factory is used to generate a new factory. If the value is provided and does not map to patch data matching the type of the given variable, the program will abort with an error message.
Returns:
New integer patch data index. If new patch data index not added, return value is an invalid patch data index (< 0).
Precondition:
variable
data_id == idUndefined() || checkVariablePatchDataIndex(variable, data_id)
References checkVariablePatchDataIndex(), idUndefined(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::VariableDatabase::removePatchDataIndex (int data_id) [virtual]
Remove the patch data index from the VariableDatabase if it exists.
Side Effects
This function also removes the given index from the patch descriptor and any mapping between the index and a variable from the database.
Note:
This function does not deallocate any patch data storage associated with the integer index.
Parameters:
[in] data_id Integer patch data index to be removed from the database
References idUndefined().
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::freeVectorComponents(), removeInternalSAMRAIVariablePatchDataIndex(), and removeVariable().
bool SAMRAI::hier::VariableDatabase::checkVariablePatchDataIndex (const boost::shared_ptr< Variable > & variable, int data_id) const [virtual]
Check whether the given variable is mapped to the given patch data index in the database.
Parameters:
[in] variable boost::shared_ptr to variable
[in] data_id Integer patch data index
Returns:
Boolean true if the variable is mapped the given patch data index; false otherwise.
Precondition:
variable
(data_id >= 0) && (data_id < getPatchDescriptor()->getMaxNumberRegisteredComponents())
References TBOX_ASSERT.
Referenced by registerClonedPatchDataIndex(), and registerPatchDataIndex().
bool SAMRAI::hier::VariableDatabase::checkVariablePatchDataIndexType (const boost::shared_ptr< Variable > & variable, int data_id) const [virtual]
Check whether the given variable matches the patch data type associated with the given patch data index in the database.
Parameters:
[in] variable boost::shared_ptr to variable
[in] data_id Integer patch data index
Returns:
Boolean true if the type of the variable matches the type of the patch data at the given patch data index; false otherwise.
Precondition:
variable
(data_id >= 0) && (data_id < getPatchDescriptor()->getMaxNumberRegisteredComponents())
References TBOX_ASSERT.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::addComponent().
int SAMRAI::hier::VariableDatabase::registerVariableAndContext (const boost::shared_ptr< Variable > & variable, const boost::shared_ptr< VariableContext > & context, const IntVector & ghosts) [virtual]
Register variable and context pair along with the ghost width for the patch data mapped to the (Variable, VariableContext) pair with the variable database.
Typically, this function will generate a new patch data index for the variable and ghost width and add the variable-context pair and index to the database. If the variable-context pair is already mapped to some patch data index in the database, and the given ghost width matches that of the patch data, then that index will be returned and the function will do nothing. However, if the variable-context pair is already mapped to some patch data index with a different ghost width, the program will abort with a descriptive error message.
If either the variable or the context is unknown to the database prior to calling this routine, both items will be added to the database, if possible. The constraints for the getContext() and addVariable() routines apply.
Note:
It is an error to map a (Variable,VariableContext) pair plus data index having a different ghost width than that passed in the argument list. The program will abort with a descriptive message in this case.
Parameters:
[in] variable boost::shared_ptr to variable
[in] context boost::shared_ptr to variable context
[in] ghosts Optional ghost width for patch data associated with variable-context pair.
Returns:
Integer patch data index of variable-context pair in database.
Precondition:
variable
context
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), and TBOX_ASSERT.
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::registerVariable().
int SAMRAI::hier::VariableDatabase::mapVariableAndContextToIndex (const boost::shared_ptr< Variable > & variable, const boost::shared_ptr< VariableContext > & context) const [virtual]
Map variable-context pair in database to patch data index.
If there is no such pair in the database (either the variable does not exist, the context does not exist, or the pair has not been registered), then an invalid patch data index (i.e., < 0) is returned.
Note:
For this function to operate as expected, the database mapping information must have been generated using the registerVariableAndContext() function. If the variable was registered without a variable context, then the patch data index associated with the variable will not be returned. See the other map...() functions declared in this class.
Parameters:
[in] variable boost::shared_ptr to variable
[in] context boost::shared_ptr to variable context
Returns:
Integer patch data index of variable-context pair in database. If the variable-context pair was not registered with the database, then an invalid data index (< 0) will be returned.
Precondition:
variable
context
References idUndefined(), and TBOX_ASSERT.
bool SAMRAI::hier::VariableDatabase::mapIndexToVariable (const int index, boost::shared_ptr< Variable > & variable) const [virtual]
Map patch data index to variable associated with the data, if possible, and set the variable pointer to the variable in the database.
Parameters:
[in] index Integer patch data index
[out] variable boost::shared_ptr to variable that maps to patch data index in database. If there is no index in the database matching the index input value, then the variable pointer is set to null.
Returns:
Boolean true if patch data index maps to variable in the database; otherwise false.
Referenced by SAMRAI::solv::CellPoissonFACOps::checkInputPatchDataIndices(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), and SAMRAI::solv::GhostCellRobinBcCoefs::setGhostDataId().
bool SAMRAI::hier::VariableDatabase::mapIndexToVariableAndContext (const int index, boost::shared_ptr< Variable > & variable, boost::shared_ptr< VariableContext > & context) const [virtual]
Map patch data index to variable-context pair associated with the data, if possible, and set the variable and context pointers to the corresponding database entries.
Note:
For this function to operate as expected, the database mapping information must have been generated using the registerVariableAndContext() function. If the variable was registered without a variable context, then the variable and variable context returned may not be what is expected by the user; e.g., they may be associated with internal SAMRAI variables.
Parameters:
[in] index patch data index
[out] variable boost::shared_ptr to variable set to matching variable in database. If no match is found, it is set to null.
[out] context boost::shared_ptr to variable context set to matching variable context in database. If no match is found, it is set to null.
Returns:
Boolean true if patch data index maps to variable-context pair in the database; otherwise false.
void SAMRAI::hier::VariableDatabase::printClassData (std::ostream & os = tbox::plog, bool print_only_user_defined_variables = true) const [virtual]
Print variable, context, and patch descriptor information contained in the database to the specified output stream.
Parameters:
[in] os Optional output stream. If not given, tbox::plog is used.
[in] print_only_user_defined_variables Optional boolean value indicating whether to print information for all variables in database or only those that are associated with user- defined quantities; i.e., not internal SAMRAI variables. The default is true, indicating that only user-defined variable information will be printed.
References idUndefined().
int SAMRAI::hier::VariableDatabase::registerInternalSAMRAIVariable (const boost::shared_ptr< Variable > & variable, const IntVector & ghosts) [virtual]
Register internal SAMRAI variable and ghost width with the variable database.
This function will generate a new patch data index for the variable and ghost width unless the variable is already mapped to some patch data index in the database with a different ghost width or as a user-defined variable. If the variable is unknown to the database prior to calling this routine, it will be added to the database.
Note:
This routine is intended for managing internal SAMRAI work variables that are typically unseen by users. It should not be called by users for registering variables, or within SAMRAI for registering any user-defined variables with the variable database. This function enforces the same constraints on variable registration that are applied for registering user-defined variables; e.g., using the routine registerVariableAndContext(). Thus, it is the responsibility of SAMRAI developers to avoid naming and ghost width conflicts with user-defined variables or other internal SAMRAI variables.
Parameters:
[in] variable boost::shared_ptr to variable
[in] ghosts Ghost width for patch data associated with the variable
Returns:
Integer patch data index of variable-ghost width pair in database.
Precondition:
variable
ghosts.min() >= 0
References idUndefined(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::solv::CellPoissonFACSolver::CellPoissonFACSolver(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), and SAMRAI::algs::PatchBoundaryEdgeSum::registerSum().
void SAMRAI::hier::VariableDatabase::removeInternalSAMRAIVariablePatchDataIndex (int data_id) [virtual]
Remove the given index from the variable database if it exists in the database and is associated with an internal SAMRAI variable registered with the function registerInternalSAMRAIVariable().
Also, remove the given index from the patch descriptor and remove any mapping between the index and a variable from the variable database.
Note:
This function does not deallocate any patch data storage associated with the integer index.
This routine is intended for managing internal SAMRAI work variables that are typically unseen by users. It should not be called by users for removing patch data indices, or within SAMRAI for removing any patch data indices associated with user-defined variables.
The given index will not be removed if is not associated with an internal SAMRAI variable in the variable database; i.e., a user-defined variable.
Parameters:
[in] data_id Integer patch data identifier to be removed from the database.
References removePatchDataIndex().
static int SAMRAI::hier::VariableDatabase::idUndefined () [inline, static, protected]
Return integer value used to indicate undefined variable or context identifier. This routine is protected to allow subclasses to be consistent with this database class.
Referenced by checkContextExists(), checkVariableExists(), getContext(), getVariable(), getVariableId(), mapVariableAndContextToIndex(), printClassData(), registerClonedPatchDataIndex(), registerInternalSAMRAIVariable(), registerPatchDataIndex(), removePatchDataIndex(), removeVariable(), and VariableDatabase().
int SAMRAI::hier::VariableDatabase::getVariableId (const std::string & name) const [protected]
Return integer identifier for first variable found matching given string name identifier (care must be used to avoid adding variables to database with same name to insure correct behavior), or return an undefined integer index if no such variable exists in the database.
References idUndefined().
Referenced by checkVariableExists(), getVariable(), and removeVariable().
void SAMRAI::hier::VariableDatabase::registerSingletonSubclassInstance (VariableDatabase * subclass_instance) [protected]
Initialize Singleton instance with instance of subclass. This function is used to make the singleton object unique when inheriting from this base class.
Precondition:
!s_variable_database_instance
References TBOX_ERROR.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/VariableDatabase.h
source/SAMRAI/hier/VariableDatabase.C