SAMRAI: SAMRAI::mesh::MultiblockGriddingTagger Class Reference
SAMRAI::mesh::MultiblockGriddingTagger Class Reference
Class MultiblockGriddingTagger is a concrete implementation of RefinePatchStrategy that is used for boundary filling of tag data.
#include <source/SAMRAI/mesh/MultiblockGriddingTagger.h>
Public Member Functions
MultiblockGriddingTagger ()
The constructor does nothing interesting.
virtual ~MultiblockGriddingTagger ()
The virtual destructor does nothing interesting.
virtual void setScratchTagPatchDataIndex (int buf_tag_indx)
Set the patch data index for tag data. This routine must be called with a valid cell-centered integer patch data index.
virtual void setPhysicalBoundaryConditions (hier::Patch &patch, const double fill_time, const hier::IntVector &ghost_width_to_fill)
Physical boundary fill.
virtual void fillSingularityBoundaryConditions (hier::Patch &patch, const hier::PatchLevel &encon_level, boost::shared_ptr< const hier::Connector > dst_to_encon, const hier::Box &fill_box, const hier::BoundaryBox &boundary_box, const boost::shared_ptr< hier::BaseGridGeometry > &grid_geometry)
Set the ghost data at a multiblock singularity.
virtual hier::IntVector getRefineOpStencilWidth (const tbox::Dimension &dim) const
Return maximum stencil width needed for user-defined data interpolation operations. This is needed to determine the correct interpolation data dependencies.
virtual void preprocessRefine (hier::Patch &fine, const hier::Patch &coarse, const hier::Box &fine_box, const hier::IntVector &ratio)
virtual void postprocessRefine (hier::Patch &fine, const hier::Patch &coarse, const hier::Box &fine_box, const hier::IntVector &ratio)
Detailed Description
Class MultiblockGriddingTagger is a concrete implementation of RefinePatchStrategy that is used for boundary filling of tag data.
This class is needed for the calls to RefineSchedule in the GriddingAlgorithm.
This class implements the interface from SingularityPatchStrategy for fillSingularityBoundaryConditions(), so that boundary conditions for tag data that abuts a singularity can be properly filled. Also implemented are the interfaces for xfer::RefinePatchStrategy, needed primarily for physical boundary filling.
See also:
mesh::GriddingAlgorithm
xfer::RefineSchedule
xfer::RefinePatchStrategy
Constructor & Destructor Documentation
SAMRAI::mesh::MultiblockGriddingTagger::MultiblockGriddingTagger ()
The constructor does nothing interesting.
SAMRAI::mesh::MultiblockGriddingTagger::~MultiblockGriddingTagger () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
void SAMRAI::mesh::MultiblockGriddingTagger::setScratchTagPatchDataIndex (int buf_tag_indx) [virtual]
Set the patch data index for tag data. This routine must be called with a valid cell-centered integer patch data index.
References BOOST_CAST, SAMRAI::hier::VariableDatabase::getDatabase(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm().
void SAMRAI::mesh::MultiblockGriddingTagger::setPhysicalBoundaryConditions (hier::Patch & patch, const double fill_time, const hier::IntVector & ghost_width_to_fill) [virtual]
Physical boundary fill.
Implementation of interface defined in xfer::RefinePatchStrategy. Fills ghost cells of patch data at physical boundaries.
Parameters:
patch Patch where data is stored
fill_time Simulation time when filling occurs
ghost_width_to_fill Maximum ghost width of all data to be filled
Implements SAMRAI::xfer::RefinePatchStrategy.
References BOOST_CAST, SAMRAI::hier::Patch::getBox(), SAMRAI::hier::Patch::getDim(), SAMRAI::hier::Patch::getPatchData(), SAMRAI::hier::Patch::getPatchGeometry(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::min(), NULL_USE, and TBOX_ASSERT.
void SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions (hier::Patch & patch, const hier::PatchLevel & encon_level, boost::shared_ptr< const hier::Connector > dst_to_encon, const hier::Box & fill_box, const hier::BoundaryBox & boundary_box, const boost::shared_ptr< hier::BaseGridGeometry > & grid_geometry) [virtual]
Set the ghost data at a multiblock singularity.
Implementation of interface defined in RefinePatchStrategy. Fills ghost cells of patch data that abut multiblock singularities. The encon_level contains the data from neighboring blocks that also also abut the singularity, and that data from the neighbors is used to fill data on the local patch.
Parameters:
patch Local patch containing data to be filled
encon_level Level representing enhanced connectivity ghost regions
dst_to_encon Connector from destination level to encon_level
fill_box All ghost data to be filled will be within this box
boundary_box BoundaryBox object that stores information about the type and location of the boundary where ghost cells will be filled
grid_geometry
Precondition:
(patch.getDim() == fill_box.getDim()) && (patch.getDim() == boundary_box.getDim())
!grid_geometry->hasEnhancedConnectivity() || dst_to_encon
Implements SAMRAI::xfer::SingularityPatchStrategy.
References SAMRAI::pdat::CellGeometry::begin(), BOOST_CAST, SAMRAI::hier::Transformation::calculateReverseShift(), SAMRAI::hier::Box::empty(), SAMRAI::pdat::CellGeometry::end(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Patch::getBox(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::PatchLevel::getPatch(), SAMRAI::hier::Patch::getPatchData(), SAMRAI::hier::Patch::getPatchGeometry(), SAMRAI::hier::Transformation::getReverseRotationIdentifier(), SAMRAI::hier::Transformation::NO_ROTATE, NULL_USE, TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, SAMRAI::pdat::CellGeometry::transform(), and SAMRAI::hier::Transformation::transform().
hier::IntVector SAMRAI::mesh::MultiblockGriddingTagger::getRefineOpStencilWidth (const tbox::Dimension & dim) const [virtual]
Return maximum stencil width needed for user-defined data interpolation operations. This is needed to determine the correct interpolation data dependencies.
Always returns an IntVector of ones, because that is the maximum stencil needed for the operations in GriddingAlgorithm
Implements SAMRAI::xfer::RefinePatchStrategy.
References SAMRAI::hier::IntVector::getOne().
void SAMRAI::mesh::MultiblockGriddingTagger::preprocessRefine (hier::Patch & fine, const hier::Patch & coarse, const hier::Box & fine_box, const hier::IntVector & ratio) [virtual]
Perform user-defined refining operations. This member function is called before standard refining operations (expressed using concrete subclasses of the hier::RefineOperator base class). The preprocess function must refine data from the scratch components of the coarse patch into the scratch components of the fine patch on the specified fine box region. Recall that the scratch components are specified in calls to the registerRefine() function in the xfer::RefineAlgorithm class.
Parameters:
fine Fine patch containing destination data.
coarse Coarse patch containing source data.
fine_box Box region on fine patch into which data is refined.
ratio Integer vector containing ratio relating index space between coarse and fine patches.
Implements SAMRAI::xfer::RefinePatchStrategy.
References NULL_USE.
void SAMRAI::mesh::MultiblockGriddingTagger::postprocessRefine (hier::Patch & fine, const hier::Patch & coarse, const hier::Box & fine_box, const hier::IntVector & ratio) [virtual]
Perform user-defined refining operations. This member function is called before standard refining operations (expressed using concrete subclasses of the hier::RefineOperator base class). The postprocess function must refine data from the scratch components of the coarse patch into the scratch components of the fine patch on the specified fine box region. Recall that the scratch components are specified in calls to the registerRefine() function in the xfer::RefineAlgorithm class.
Parameters:
fine Fine patch containing destination data.
coarse Coarse patch containing source data.
fine_box Box region on fine patch into which data is refined.
ratio Integer vector containing ratio relating index space between coarse and fine patches.
Precondition:
(fine.getDim() == coarse.getDim()) && (fine.getDim() == fine_box.getDim()) && (fine.getDim() == ratio.getDim())
Implements SAMRAI::xfer::RefinePatchStrategy.
References NULL_USE, and TBOX_ASSERT_OBJDIM_EQUALITY4.
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/MultiblockGriddingTagger.h
source/SAMRAI/mesh/MultiblockGriddingTagger.C