SAMRAI: SAMRAI::math::PatchCellDataOpsInteger Class Reference
SAMRAI::math::PatchCellDataOpsInteger Class Reference
#include <source/SAMRAI/math/PatchCellDataOpsInteger.h>
Public Member Functions
PatchCellDataOpsInteger ()
virtual ~PatchCellDataOpsInteger ()
size_t numberOfEntries (const boost::shared_ptr< pdat::CellData< int > > &data, const hier::Box &box) const
void copyData (const boost::shared_ptr< pdat::CellData< int > > &dst, const boost::shared_ptr< pdat::CellData< int > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::CellData< int > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::CellData< int > > &dst, const int &alpha, const hier::Box &box) const
void abs (const boost::shared_ptr< pdat::CellData< int > > &dst, const boost::shared_ptr< pdat::CellData< int > > &src, const hier::Box &box) const
Detailed Description
Class PatchCellDataOpsInteger provides a collection of operations that may be used to manipulate integer cell-centered patch data. The operations include basic arithmetic, min, max, etc. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base class PatchCellDataBasicOps from which it is derived.
A more extensive set of operations is implemented for real (double and float) and complex patch data in the classes PatchCellDataOpsReal and PatchCellDataOpsComplex, respectively.
See also:
PatchCellDataBasicOps
Constructor & Destructor Documentation
SAMRAI::math::PatchCellDataOpsInteger::PatchCellDataOpsInteger ()
Empty constructor and destructor.
SAMRAI::math::PatchCellDataOpsInteger::~PatchCellDataOpsInteger () [virtual]
Member Function Documentation
size_t SAMRAI::math::PatchCellDataOpsInteger::numberOfEntries (const boost::shared_ptr< pdat::CellData< int > > & data, const hier::Box & box) const [inline]
Return the number of data values for the cell-centered data object in the given box.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsInteger::numberOfEntries().
void SAMRAI::math::PatchCellDataOpsInteger::copyData (const boost::shared_ptr< pdat::CellData< int > > & dst, const boost::shared_ptr< pdat::CellData< int > > & src, const hier::Box & box) const [inline]
Copy dst data to src data over given box.
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::HierarchyCellDataOpsInteger::copyData().
void SAMRAI::math::PatchCellDataOpsInteger::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::CellData<int> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::CellData<int> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyCellDataOpsInteger::swapData().
void SAMRAI::math::PatchCellDataOpsInteger::printData (const boost::shared_ptr< pdat::CellData< int > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const [inline]
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsInteger::printData().
void SAMRAI::math::PatchCellDataOpsInteger::setToScalar (const boost::shared_ptr< pdat::CellData< int > > & dst, const int & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsInteger::setToScalar().
void SAMRAI::math::PatchCellDataOpsInteger::abs (const boost::shared_ptr< pdat::CellData< int > > & dst, const boost::shared_ptr< pdat::CellData< int > > & src, const hier::Box & box) const [inline]
Set destination component to absolute value of source component. That is, each destination entry is set to .
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsInteger::abs(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::HierarchyCellDataOpsInteger::abs().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchCellDataOpsInteger.h
source/SAMRAI/math/PatchCellDataOpsInteger.C