SAMRAI: SAMRAI::math::PatchSideDataNormOpsComplex Class Reference
SAMRAI::math::PatchSideDataNormOpsComplex Class Reference
#include <source/SAMRAI/math/PatchSideDataNormOpsComplex.h>
Public Member Functions
PatchSideDataNormOpsComplex ()
virtual ~PatchSideDataNormOpsComplex ()
int numberOfEntries (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const hier::Box &box) const
double sumControlVolumes (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const boost::shared_ptr< pdat::SideData< double > > &cvol, const hier::Box &box) const
void abs (const boost::shared_ptr< pdat::SideData< double > > &dst, const boost::shared_ptr< pdat::SideData< dcomplex > > &src, const hier::Box &box) const
double L1Norm (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double L2Norm (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double weightedL2Norm (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const boost::shared_ptr< pdat::SideData< dcomplex > > &weight, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double RMSNorm (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double weightedRMSNorm (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const boost::shared_ptr< pdat::SideData< dcomplex > > &weight, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double maxNorm (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
dcomplex dot (const boost::shared_ptr< pdat::SideData< dcomplex > > &data1, const boost::shared_ptr< pdat::SideData< dcomplex > > &data2, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
dcomplex integral (const boost::shared_ptr< pdat::SideData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &vol) const
Detailed Description
Class PatchSideDataNormOpsComplex provides a collection of common norm operations that may be applied to complex side-centered patch data. The primary intent of this class is to define part of the interface for the PatchSideDataOpsComplex class which provides access to operations that may be used to manipulate complex side-centered patch data. Each member function accepts a box argument indicating the region of index space on which the operation should be performed. The operation will be performed on the intersection of this box and those boxes corresponding to the patch data objects. Also, each operation allows an additional side-centered patch data object to be used to represent a control volume that weights the contribution of each data entry in the given norm calculation. Note that the control volume patch data must be of type double and have side-centered geometry (i.e., the same as the data itself). The use of control volumes is important when these operations are used in vector kernels where the data resides over multiple levels of spatial resolution in an AMR hierarchy. If the control volume is not given in the function call, it will be ignored in the calculation. Also, note that the depth of the control volume patch data object must be either 1 or be equal to the depth of the other data objects.
Note that a similar set of norm operations is implemented for real patch data (double and float) in the class PatchSideDataNormOpsReal.
See also:
ArrayDataNormOpsComplex
Constructor & Destructor Documentation
SAMRAI::math::PatchSideDataNormOpsComplex::PatchSideDataNormOpsComplex ()
Empty constructor and destructor.
SAMRAI::math::PatchSideDataNormOpsComplex::~PatchSideDataNormOpsComplex () [virtual]
Member Function Documentation
int SAMRAI::math::PatchSideDataNormOpsComplex::numberOfEntries (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const hier::Box & box) const
Return the number of data values for the side-centered data object in the given box. Note that it is assumed that the box refers to the cell-centered index space corresponding to the patch hierarchy.
Precondition:
data
data->getDim() == box.getDim()
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::size(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsComplex::numberOfEntries(), RMSNorm(), and weightedRMSNorm().
double SAMRAI::math::PatchSideDataNormOpsComplex::sumControlVolumes (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const boost::shared_ptr< pdat::SideData< double > > & cvol, const hier::Box & box) const
Return sum of control volume entries for the side-centered data object.
Precondition:
data && cvol
data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::min(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by RMSNorm(), SAMRAI::math::HierarchySideDataOpsComplex::sumControlVolumes(), and weightedRMSNorm().
void SAMRAI::math::PatchSideDataNormOpsComplex::abs (const boost::shared_ptr< pdat::SideData< double > > & dst, const boost::shared_ptr< pdat::SideData< dcomplex > > & src, const hier::Box & box) const
Set destination component to norm of source component. That is, each destination entry is set to .
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsComplex::abs().
double SAMRAI::math::PatchSideDataNormOpsComplex::L1Norm (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsComplex::L1Norm().
double SAMRAI::math::PatchSideDataNormOpsComplex::L2Norm (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::math::ArrayDataNormOpsComplex::L2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L2NormWithControlVolume(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by RMSNorm().
double SAMRAI::math::PatchSideDataNormOpsComplex::weightedL2Norm (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const boost::shared_ptr< pdat::SideData< dcomplex > > & weight, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const
Return discrete weighted -norm of the data using the control volume to weight the contribution of the data and weight entries to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data && weight
(data->getDim() == weight->getDim()) && (data->getDim() == box.getDim())
data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), weight->getDirectionVector())
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, TBOX_ASSERT_OBJDIM_EQUALITY3, SAMRAI::pdat::SideGeometry::toSideBox(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
Referenced by SAMRAI::math::HierarchySideDataOpsComplex::weightedL2Norm(), and weightedRMSNorm().
double SAMRAI::math::PatchSideDataNormOpsComplex::RMSNorm (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const
Return discrete root mean squared norm of the data. If the control volume is not NULL, the return value is the -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the -norm divided by the square root of the number of data entries.
Precondition:
data
References L2Norm(), numberOfEntries(), sumControlVolumes(), and TBOX_ASSERT.
double SAMRAI::math::PatchSideDataNormOpsComplex::weightedRMSNorm (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const boost::shared_ptr< pdat::SideData< dcomplex > > & weight, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const
Return discrete weighted root mean squared norm of the data. If the control volume is not NULL, the return value is the weighted -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the weighted -norm divided by the square root of the number of data entries.
Precondition:
data && weight
References numberOfEntries(), sumControlVolumes(), TBOX_ASSERT, and weightedL2Norm().
double SAMRAI::math::PatchSideDataNormOpsComplex::maxNorm (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const
Return the -norm of the data using the control volume to weight the contribution of each data entry to the maximum. That is, the return value is , where the max is over the data elements where . If the control volume is NULL, it is ignored during the computation of the maximum.
Precondition:
data
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsComplex::maxNorm().
dcomplex SAMRAI::math::PatchSideDataNormOpsComplex::dot (const boost::shared_ptr< pdat::SideData< dcomplex > > & data1, const boost::shared_ptr< pdat::SideData< dcomplex > > & data2, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const
Return the dot product of the two data arrays using the control volume to weight the contribution of each product to the sum. That is, the return value is the sum . If the control volume is NULL, it is ignored during the summation.
Precondition:
data1 && data2
data1->getDirectionVector() == data2->getDirectionVector()
!cvol || (data1->getDirectionVector() == hier::IntVector::min(data1->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsComplex::dot().
dcomplex SAMRAI::math::PatchSideDataNormOpsComplex::integral (const boost::shared_ptr< pdat::SideData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & vol) const
Return the integral of the function represented by the data array. The return value is the sum .
Precondition:
data
data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), vol->getDirectionVector())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::HierarchySideDataOpsComplex::integral().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchSideDataNormOpsComplex.h
source/SAMRAI/math/PatchSideDataNormOpsComplex.C