SAMRAI: SAMRAI::hier::BoxLevel Class Reference
SAMRAI::hier::BoxLevel Class Reference
A distributed set of Box objects which reside in the same index space.
#include <source/SAMRAI/hier/BoxLevel.h>
Classes
class Outputter
A class for outputting BoxLevel.
Public Types
enum ParallelState { DISTRIBUTED, GLOBALIZED }
Names of parallel states.
Public Member Functions
BoxLevel (const tbox::Dimension &dim, tbox::Database &restart_db, const boost::shared_ptr< const BaseGridGeometry > &grid_geom)
Construct a BoxLevel which will be initialized from the supplied restart database.
BoxLevel (const BoxLevel &rhs)
Copy constructor.
BoxLevel (const IntVector &ratio, const boost::shared_ptr< const BaseGridGeometry > &grid_geom, const tbox::SAMRAI_MPI &mpi=tbox::SAMRAI_MPI::getSAMRAIWorld(), const ParallelState parallel_state=DISTRIBUTED)
Constructs an empty, initialized object.
~BoxLevel ()
Destructor.
BoxLevel & operator= (const BoxLevel &rhs)
Assignment operator duplicates all internal data, including parallel mode.
bool operator== (const BoxLevel &rhs) const
Equality comparison.
bool operator!= (const BoxLevel &rhs) const
Inequality comparison.
void invalidateGlobalData ()
Sets d_global_data_up_to_date to false. Must be called after calls to addBox or eraseBox.
void clearPersistentOverlapConnectors ()
Deallocate persistent overlap Connectors, if there are any.
const Connector & findConnector (const BoxLevel &head, const IntVector &min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only=false) const
Find an overlap Connector with the given head and minimum Connector width. If the specified Connector is not found, take the specified action.
const Connector & findConnectorWithTranspose (const BoxLevel &head, const IntVector &min_connector_width, const IntVector &transpose_min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only=false) const
Find an overlap Connector with its transpose with the given head and minimum Connector widths. If the specified Connector is not found, take the specified action.
const Connector & createConnector (const BoxLevel &head, const IntVector &connector_width) const
Create an overlap Connector, computing relationships by globalizing data.
const Connector & createConnectorWithTranspose (const BoxLevel &head, const IntVector &connector_width, const IntVector &transpose_connector_width) const
Create an overlap Connector with its transpose, computing relationships by globalizing data.
void cacheConnector (boost::shared_ptr< Connector > &connector) const
Cache the supplied overlap Connector and its transpose if it exists.
bool hasConnector (const BoxLevel &head, const IntVector &min_connector_width, bool exact_width_only=false) const
Returns whether the object has overlap Connectors with the given head and minimum Connector width.
const boost::shared_ptr
< BoxLevelHandle > & getBoxLevelHandle () const
Get the handle with which Connectors reference the BoxLevel instead of referencing the BoxLevel itself. Not for general use.
void lock ()
Effectively makes a non-const BoxLevel const. Prevents any non-const method from executing.
bool locked ()
Returns true if the BoxLevel is locked.
Initialization and clearing methods
void initialize (const IntVector &ratio, const boost::shared_ptr< const BaseGridGeometry > &grid_geom, const tbox::SAMRAI_MPI &mpi=tbox::SAMRAI_MPI::getSAMRAIWorld(), const ParallelState parallel_state=DISTRIBUTED)
Initialize the BoxLevel without and Boxes.
void swapInitialize (BoxContainer &boxes, const IntVector &ratio, const boost::shared_ptr< const BaseGridGeometry > &grid_geom, const tbox::SAMRAI_MPI &mpi=tbox::SAMRAI_MPI::getSAMRAIWorld(), const ParallelState parallel_state=DISTRIBUTED)
Initialize the BoxLevel.
void finalize ()
Removes non-local boxes; computes bounding box, local number of boxes, local number of cells, max/min box size. To be called after all Boxes in a BoxLevel have been added to indicate that the BoxLevel is fully defined and ready to be used.
bool isInitialized () const
Returns True if the object has been initialized.
void removePeriodicImageBoxes ()
Remove all the periodic image boxes in the BoxLevel.
void clear ()
Clear the internal state of the BoxLevel.
void clearForBoxChanges (bool isInvalid=true)
Clear the globalized version and the persistent overlap connectors for data consistency.
Parallelism
void setParallelState (const ParallelState parallel_state)
Set the parallel state.
ParallelState getParallelState () const
Returns the ParallelState of the object.
void cacheGlobalReducedData () const
If global reduced data (global Box count, global cell count and global bounding box) have not been updated, compute and cache them (communication required).
const BoxLevel & getGlobalizedVersion () const
Return the globalized version of the BoxLevel, creating it if needed.
void deallocateGlobalizedVersion () const
Deallocate the internal globalized version of the BoxLevel, if there is any.
const tbox::SAMRAI_MPI & getMPI () const
Returns the SAMRAI_MPI communicator over which the Boxes are distributed.
Accessors
const BoxContainer & getBoxes () const
Returns the container of local Boxes.
const BoxContainer & getGlobalBoxes () const
Returns the container of global Boxes.
void getGlobalBoxes (BoxContainer &global_boxes) const
Fill the container with the global Boxes.
LocalId getFirstLocalId () const
Returns the first LocalId, or one with a value of -1 if no local Box exists.
LocalId getLastLocalId () const
Returns the last LocalId, or one with a value of -1 if no local Box exists.
const IntVector & getRefinementRatio () const
Get const access to BoxLevel's refinement ratio (with respect to a reference level).
size_t getLocalNumberOfBoxes () const
Return local number of boxes.
size_t getLocalNumberOfBoxes (int rank) const
Return number of boxes local to the given rank.
int getGlobalNumberOfBoxes () const
Return global number of Boxes.
int getMaxNumberOfBoxes () const
Return maximum number of Boxes over all processes.
int getMinNumberOfBoxes () const
Return maximum number of Boxes over all processes.
size_t getLocalNumberOfCells () const
Return local number of cells.
int getMaxNumberOfCells () const
Return maximum number of cells over all processes.
int getMinNumberOfCells () const
Return maximum number of cells over all processes.
size_t getLocalNumberOfCells (int rank) const
Return number of cells local to the given rank.
long int getGlobalNumberOfCells () const
Return global number of cells.
const Box & getLocalBoundingBox (int block_number) const
Return bounding box for local Boxes in a block.
const Box & getGlobalBoundingBox (int block_number) const
Return bounding box for global Boxes in a block.
const IntVector & getLocalMaxBoxSize (int block_number) const
Return size of the largest local Box in a block.
const IntVector & getLocalMinBoxSize (int block_number) const
Return size of the smallest local Box in a block.
const IntVector & getGlobalMaxBoxSize (int block_number) const
Return size of the largest Box globally in a block.
const IntVector & getGlobalMinBoxSize (int block_number) const
Return size of the smallest Box globally in a block.
const tbox::Dimension & getDim () const
Return the dimension of this object.
const boost::shared_ptr< const
BaseGridGeometry > & getGridGeometry () const
Return the grid geometry associated with this object.
Methods to modify all Boxes.
void refineBoxes (BoxLevel &finer, const IntVector &ratio, const IntVector &final_ratio) const
Refine all Boxes of this BoxLevel by ratio placing result into finer making finer's ratio final_ratio.
void coarsenBoxes (BoxLevel &coarser, const IntVector &ratio, const IntVector &final_ratio) const
Coarsen all Boxes of this BoxLevel by ratio placing result into coarser making coarser's ratio final_ratio.
Individual Box methods.
BoxContainer::const_iterator addBox (const Box &box, const BlockId &block_id)
Create new local Box from given Box and add it to this level.
void addBox (const Box &box)
Add a Box to this level.
void addBoxWithoutUpdate (const Box &box)
Add a Box to this level without updating summary data such as local number of boxes/cells, bounding box, max/min box size. Meant to be used during the construction of a BoxLevel as Boxes belonging to the level are found. finalize() should be called at the end of construction making use of addBoxWithoutUpdate.
void addPeriodicBox (const Box &existing_box, const PeriodicId &shift_number)
Insert given periodic image of an existing Box.
void eraseBox (BoxContainer::iterator &ibox)
Erase the existing Box specified by its iterator.
void eraseBox (const Box &box)
Erase the Box matching the one given.
void eraseBoxWithoutUpdate (const Box &box)
Erases the Box matching the supplied Box from this level without updating summary data such as local number of boxes/cells, bounding box, max/min box size. Meant to be used during the construction of a BoxLevel as Boxes not belonging to the level are found. finalize() should be called at the end of construction making use of eraseBoxWithoutUpdate.
BoxContainer::const_iterator getBox (const Box &box) const
Find the Box matching the one given.
BoxContainer::const_iterator getBox (const BoxId &box_id) const
Find the Box specified by the given BoxId and periodic shift.
BoxContainer::const_iterator getBoxStrict (const Box &box) const
Find the Box matching the one given.
BoxContainer::const_iterator getBoxStrict (const BoxId &box_id) const
Find the Box specified by the given BoxId.
bool getSpatiallyEqualBox (const Box &box_to_match, const BlockId &block_id, Box &matching_box) const
Find the Box with the given BlockId which is spatially equal to the supplied Box.
bool hasBox (const BoxId &box_id) const
Returns true when the object has a Box specified by the BoxId.
bool hasBox (const GlobalId &global_id, const PeriodicId &periodic_id) const
Returns true when the object has a Box consistent with all of the arguments.
bool hasBox (const Box &box) const
Returns true when this BoxLevel has a Box matching the BoxId of the given box.
IO support.
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write the BoxLevel to a restart database.
Methods for outputs, error checking and debugging.
void recursivePrint (std::ostream &os, const std::string &border, int detail_depth=2) const
Print Box info from this level.
Outputter format (const std::string &border=std::string(), int detail_depth=2) const
Return a object that can format the BoxLevel for inserting into output streams.
Outputter formatStatistics (const std::string &border=std::string()) const
Return a object that can format the BoxLevel for inserting its global statistics into output streams.
Static Public Member Functions
static void swap (BoxLevel &level_a, BoxLevel &level_b)
Swap the contents of two BoxLevel objects.
Friends
class PersistentOverlapConnectors
Detailed Description
A distributed set of Box objects which reside in the same index space.
TODO: Are we eliminating DLBG terminology?
This class is a part of the distributed layered box graph (DLBG) for managing SAMR meshes in parallel. A BoxLevel is a set of boxes in the same index space. Relationships (e.g., neighbor adjacency) among boxes is contained in a Connector object. Also, each BoxLevel has an refinement ratio vector describing the relationship of the index space to that of a reference level in a patch hierarchy (typically the coarsest level or level zero).
Like a PatchLevel, a BoxLevel is a parallel object. The Boxes of a BoxLevel may be distributed across all the processors in an MPI communicator and can be in one of two parallel states:
DISTRIBUTED: Each MPI process knows only the Boxes in the set that are "owned" by that process. This is analogous to a PatchLevel which owns only the Patches that reside on a process.
GLOBALIZED: All processes know all Boxes in the set. This is analogous to PatchLevel BoxContainer state when it is globalized (
See also:
PatchLevel::getBoxes()).
Performance notes
The parallel state is changed by calling setParallelState(). Going from DISTRIBUTED to GLOBALIZED state is an expensive operation requiring all-to-all communication. Using this state can incur a significant performance penalty.
The GLOBALIZED state requires more memory.
Transitioning from GLOBALIZED state to DISTRIBUTED state is cheap.
Note:
The general attributes of a BoxLevel are
the set of Box objects with unique BoxIds,
the refinement ratio defining their index space, and
the parallel state.
Box object uniqueness is based on the Box equality operator, which compares owner MPI ranks and local indices. Therefore, a valid BoxLevel does not contain two Boxes with the same owner and index.
Member Enumeration Documentation
enum SAMRAI::hier::BoxLevel::ParallelState
Names of parallel states.
Enumerator:
DISTRIBUTED
GLOBALIZED
Constructor & Destructor Documentation
SAMRAI::hier::BoxLevel::BoxLevel (const tbox::Dimension & dim, tbox::Database & restart_db, const boost::shared_ptr< const BaseGridGeometry > & grid_geom)
Construct a BoxLevel which will be initialized from the supplied restart database.
Parameters:
[in] dim
[in] restart_db
[in] grid_geom
SAMRAI::hier::BoxLevel::BoxLevel (const BoxLevel & rhs)
Copy constructor.
New object has the same parallel state as original.
Persistent Connectors are not duplicated. This decision was based on expected usage, which is that copies are either for short term usage or meant to be changed in some way and will invalidate Connectors.
Parameters:
[in] rhs
SAMRAI::hier::BoxLevel::BoxLevel (const IntVector & ratio, const boost::shared_ptr< const BaseGridGeometry > & grid_geom, const tbox::SAMRAI_MPI & mpi = tbox::SAMRAI_MPI::getSAMRAIWorld(), const ParallelState parallel_state = DISTRIBUTED)
Constructs an empty, initialized object.
See also:
addBox()
initialize()
Parameters:
[in] ratio
[in] grid_geom
[in] mpi
[in] parallel_state
References initialize().
SAMRAI::hier::BoxLevel::~BoxLevel ()
Destructor.
Deallocate internal data.
References clear().
Member Function Documentation
void SAMRAI::hier::BoxLevel::initialize (const IntVector & ratio, const boost::shared_ptr< const BaseGridGeometry > & grid_geom, const tbox::SAMRAI_MPI & mpi = tbox::SAMRAI_MPI::getSAMRAIWorld(), const ParallelState parallel_state = DISTRIBUTED)
Initialize the BoxLevel without and Boxes.
The content and state of the object before calling this function is discarded.
See also:
addBox()
initialize(const BoxContainer&, const IntVector&, const tbox::SAMRAI_MPI&, const ParallelState)
Parameters:
[in] ratio
[in] grid_geom
[in] mpi
[in] parallel_state
References SAMRAI::hier::BoxContainer::clear(), locked(), SAMRAI::hier::BoxContainer::order(), and TBOX_ERROR.
Referenced by BoxLevel(), and SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel().
void SAMRAI::hier::BoxLevel::swapInitialize (BoxContainer & boxes, const IntVector & ratio, const boost::shared_ptr< const BaseGridGeometry > & grid_geom, const tbox::SAMRAI_MPI & mpi = tbox::SAMRAI_MPI::getSAMRAIWorld(), const ParallelState parallel_state = DISTRIBUTED)
Initialize the BoxLevel.
Similar to initialize(const BoxContainer&, const IntVector&, const tbox::SAMRAI_MPI&, const ParallelState), except that the boxes are mutable.
The state of the object before calling this function is discarded. The Box content before calling this function is returned via the boxes argument.
See also:
initializePrivate()
Parameters:
[in,out] boxes On input, this should contain the Boxes to place in the BoxLevel. On output, it contains the Boxes that were in the BoxLevel before the call.
[in] boxes
[in] ratio
[in] grid_geom
[in] mpi
[in] parallel_state
Precondition:
&boxes != &getBoxes()
References locked(), SAMRAI::hier::BoxContainer::order(), SAMRAI::hier::BoxContainer::swap(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::BoxLevel::finalize ()
Removes non-local boxes; computes bounding box, local number of boxes, local number of cells, max/min box size. To be called after all Boxes in a BoxLevel have been added to indicate that the BoxLevel is fully defined and ready to be used.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::erase(), SAMRAI::tbox::SAMRAI_MPI::getRank(), locked(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages().
bool SAMRAI::hier::BoxLevel::isInitialized () const [inline]
Returns True if the object has been initialized.
Referenced by SAMRAI::hier::BoxLevelStatistics::BoxLevelStatistics(), cacheGlobalReducedData(), clear(), getFirstLocalId(), getGlobalizedVersion(), getGlobalNumberOfBoxes(), getGlobalNumberOfCells(), getLastLocalId(), getLocalNumberOfBoxes(), getLocalNumberOfCells(), getMaxNumberOfBoxes(), getMaxNumberOfCells(), getMinNumberOfBoxes(), getMinNumberOfCells(), recursivePrint(), removePeriodicImageBoxes(), SAMRAI::hier::Connector::setBase(), SAMRAI::hier::Connector::setHead(), setParallelState(), and swap().
void SAMRAI::hier::BoxLevel::removePeriodicImageBoxes ()
Remove all the periodic image boxes in the BoxLevel.
References clearForBoxChanges(), GLOBALIZED, isInitialized(), locked(), SAMRAI::hier::BoxContainer::removePeriodicImageBoxes(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel().
void SAMRAI::hier::BoxLevel::clear ()
Clear the internal state of the BoxLevel.
The BoxLevel will be in an uninitialized state after a call to this method.
References SAMRAI::hier::BoxContainer::clear(), clearForBoxChanges(), DISTRIBUTED, isInitialized(), locked(), MPI_COMM_NULL, and TBOX_ERROR.
Referenced by ~BoxLevel().
void SAMRAI::hier::BoxLevel::clearForBoxChanges (bool isInvalid = true) [inline]
Clear the globalized version and the persistent overlap connectors for data consistency.
Most of the time, this method is automatically called by methods that know when some data is stale and needs to be cleared. For example, adding a box makes the global number of boxes stale. However, sometimes it is necessary to call this method manually. For example, when only some processes add boxes while others do not, resulting in some processes not knowing that the global number of boxes is inconsistent.
Parameters:
[in] isInvalid A flag indicating that boxes have been (or will be) removed, thus invalidating the handle.
References clearPersistentOverlapConnectors(), deallocateGlobalizedVersion(), locked(), and TBOX_ERROR.
Referenced by addBox(), addPeriodicBox(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), clear(), eraseBox(), and removePeriodicImageBoxes().
void SAMRAI::hier::BoxLevel::setParallelState (const ParallelState parallel_state)
Set the parallel state.
This method is potentially expensive. Acquiring remote Box information (when going to GLOBALIZED mode) triggers all-gather communication. More memory is required to store additional Boxes.
Data not used by the new state gets deallocated.
Parameters:
[in] parallel_state
Precondition:
isInitialized()
References SAMRAI::hier::BoxContainer::clear(), DISTRIBUTED, GLOBALIZED, isInitialized(), locked(), and TBOX_ERROR.
Referenced by getGlobalizedVersion(), and SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel().
ParallelState SAMRAI::hier::BoxLevel::getParallelState () const [inline]
Returns the ParallelState of the object.
Referenced by addBoxWithoutUpdate(), SAMRAI::hier::Connector::checkConsistencyWithHead(), deallocateGlobalizedVersion(), SAMRAI::hier::Connector::finalizeContext(), getBox(), getGlobalizedVersion(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), and recursivePrint().
void SAMRAI::hier::BoxLevel::cacheGlobalReducedData () const
If global reduced data (global Box count, global cell count and global bounding box) have not been updated, compute and cache them (communication required).
After this method is called, data requiring global reduction can be accessed without further communications, until the object changes.
Sets d_global_data_up_to_date to true;
Precondition:
isInitialized()
References SAMRAI::tbox::SAMRAI_MPI::Allreduce(), getDim(), getLocalNumberOfBoxes(), getLocalNumberOfCells(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::tbox::Dimension::getValue(), GLOBALIZED, isInitialized(), MPI_INT, MPI_LONG, MPI_MAX, MPI_SUM, SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), and TBOX_ASSERT.
Referenced by getGlobalBoundingBox(), getGlobalMaxBoxSize(), getGlobalMinBoxSize(), getGlobalNumberOfBoxes(), getGlobalNumberOfCells(), getMaxNumberOfBoxes(), getMaxNumberOfCells(), getMinNumberOfBoxes(), and getMinNumberOfCells().
const BoxLevel & SAMRAI::hier::BoxLevel::getGlobalizedVersion () const
Return the globalized version of the BoxLevel, creating it if needed.
If the BoxLevel is in globalized state, return *this. If not, create and cache a globalized version (if necessary) and return that.
The cached version remains until it is removed by deallocateGlobalizedVersion() or a method that can potentially change the Boxes is called. Note that globalizing and globalized data is not scalable. Use only when necessary.
Obviously, when the globalized version must be created (when the BoxLevel is in DISTRIBUTED state and there is no cached version yet), all processes must make this call at the same point.
Precondition:
isInitialized()
Postcondition:
d_globalized_version->getParallelState() == GLOBALIZED
References getParallelState(), GLOBALIZED, isInitialized(), setParallelState(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::Connector::checkConsistencyWithHead(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doTransposeWork(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::hier::Connector::findOverlapErrors(), and SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps().
void SAMRAI::hier::BoxLevel::deallocateGlobalizedVersion () const [inline]
Deallocate the internal globalized version of the BoxLevel, if there is any.
Precondition:
(d_globalized_version == 0) || (d_globalized_version->getParallelState() == GLOBALIZED)
References getParallelState(), GLOBALIZED, and TBOX_ASSERT.
Referenced by clearForBoxChanges(), and operator=().
const tbox::SAMRAI_MPI& SAMRAI::hier::BoxLevel::getMPI () const [inline]
Returns the SAMRAI_MPI communicator over which the Boxes are distributed.
Referenced by SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps(), SAMRAI::mesh::BoxTransitSet::assignToLocalAndPopulateMaps(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::Connector::doTransposeWork(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), getBox(), SAMRAI::hier::Connector::getMPI(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::mesh::BoxTransitSet::putInBoxLevel(), SAMRAI::hier::Connector::setBase(), and SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel().
BoxLevel & SAMRAI::hier::BoxLevel::operator= (const BoxLevel & rhs)
Assignment operator duplicates all internal data, including parallel mode.
Assignment is a modifying operation, causing the PersistentOverlapConnectors to be cleared.
Persistent Connectors are not duplicated. This decision was based on expected usage, which is that copies are either for short term usage or meant to be changed in some way (thus invalidating current Connectors anyway).
See also:
getPersistentOverlapConnectors()
Parameters:
[in] rhs
References clearPersistentOverlapConnectors(), deallocateGlobalizedVersion(), locked(), and TBOX_ERROR.
void SAMRAI::hier::BoxLevel::swap (BoxLevel & level_a, BoxLevel & level_b) [static]
Swap the contents of two BoxLevel objects.
Swapping is a modifying operation, so the PersistentOverlapConnectors of the operands are cleared.
Persistent Connectors are not swapped. This decision was based on expected usage, which is that copies are either for short term usage or meant to be changed in some way (thus invalidating current Connectors anyway).
Parameters:
[in,out] level_a
[in,out] level_b
Precondition:
(&level_a == &level_b) || !level_a.isInitialized() || !level_b.isInitialized() || (level_a.getDim() == level_b.getDim())
References clearPersistentOverlapConnectors(), getDim(), getGridGeometry(), isInitialized(), locked(), MPI_COMM_NULL, SAMRAI::hier::BoxContainer::swap(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
bool SAMRAI::hier::BoxLevel::operator== (const BoxLevel & rhs) const
Equality comparison.
All data required to initialize the object is compared, except for the parallel state. Thus equality here means just the local parts are equal. BEWARE! This means that one processor may see the equality differently from another.
The cost for the comparison is on the order of the local Box count. An object may be compared to itself, an efficient operation that always returns true.
Parameters:
[in] rhs
References getBoxes().
bool SAMRAI::hier::BoxLevel::operator!= (const BoxLevel & rhs) const
Inequality comparison.
All data required to initialize the object is compared, except for the parallel state. Thus equality here means just the local parts are equal. BEWARE! This means that one processor may see the inequality differently from another.
The cost for the comparison is on the order of the local Box count. However, an object may be compared to itself, an efficient operation that always returns false.
Parameters:
[in] rhs
References getBoxes().
const BoxContainer& SAMRAI::hier::BoxLevel::getBoxes () const [inline]
Returns the container of local Boxes.
Important
The BoxContainer returned contains periodic image Boxes (if any). To iterate through real Boxes only, see RealBoxConstIterator.
You cannot directly modify the BoxContainer because it may invalidate other internal data. Use other methods for modifying the BoxContainer.
Note:
It is possible that one may wish to perform repeated searches on the Boxes in the BoxContainer returned by this method. As noted in BoxContainer's documentation, it may be advantageous to call the makeTree method on the BoxContainer in this case. If you do, remember that the GridGeometry passed to makeTree must be the GridGeometry held by this BoxLevel. Thus the proper use of makeTree with the result of a call to this method will look like:
    *    box_level.getBoxes().makeTree(box_level.getGridGeometry());
    *
See also:
getGlobalNumberOfBoxes()
getLocalNumberOfBoxes()
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), getFirstLocalId(), getLastLocalId(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), operator!=(), operator==(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and putToRestart().
const BoxContainer& SAMRAI::hier::BoxLevel::getGlobalBoxes () const [inline]
Returns the container of global Boxes.
Note:
It is possible that one may wish to perform repeated searches on the Boxes in the BoxContainer returned by this method. As noted in BoxContainer's documentation, it may be advantageous to call the makeTree method on the BoxContainer in this case. If you do, remember that the GridGeometry passed to makeTree must be the GridGeometry held by this BoxLevel. Thus the proper use of makeTree with the result of a call to this method will look like:
    *    box_level.getBoxes().makeTree(box_level.getGridGeometry());
    *
Referenced by SAMRAI::hier::Connector::checkConsistencyWithHead(), SAMRAI::hier::Connector::doTransposeWork(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel().
void SAMRAI::hier::BoxLevel::getGlobalBoxes (BoxContainer & global_boxes) const
Fill the container with the global Boxes.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), and SAMRAI::hier::BoxContainer::pushBack().
LocalId SAMRAI::hier::BoxLevel::getFirstLocalId () const
Returns the first LocalId, or one with a value of -1 if no local Box exists.
Precondition:
isInitialized()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), getBoxes(), SAMRAI::hier::BoxContainer::isEmpty(), isInitialized(), and TBOX_ASSERT.
LocalId SAMRAI::hier::BoxLevel::getLastLocalId () const
Returns the last LocalId, or one with a value of -1 if no local Box exists.
Precondition:
isInitialized()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), getBoxes(), SAMRAI::hier::BoxContainer::isEmpty(), isInitialized(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), and SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes().
const IntVector& SAMRAI::hier::BoxLevel::getRefinementRatio () const [inline]
Get const access to BoxLevel's refinement ratio (with respect to a reference level).
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::Connector::checkConsistencyWithHead(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::Connector::finalizeContext(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::hier::Connector::isTransposeOf(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::PatchHierarchy::makeNewPatchLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::hier::PatchLevel::PatchLevel(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::hier::Connector::recursivePrint(), recursivePrint(), and SAMRAI::hier::Connector::shrinkWidth().
size_t SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes () const [inline]
Return local number of boxes.
Periodic image Boxes are excluded.
Precondition:
isInitialized()
References isInitialized(), and TBOX_ASSERT.
Referenced by cacheGlobalReducedData(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), and SAMRAI::hier::Connector::recursivePrint().
size_t SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes (int rank) const
Return number of boxes local to the given rank.
Periodic image Boxes are excluded.
Parameters:
[in] rank
Precondition:
isInitialized()
(getParallelState() == GLOBALIZED) || (rank == getMPI().getRank())
(rank >= 0) && (rank < getMPI().getSize())
References SAMRAI::hier::BoxContainer::begin(), DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSize(), isInitialized(), TBOX_ASSERT, and TBOX_ERROR.
int SAMRAI::hier::BoxLevel::getGlobalNumberOfBoxes () const [inline]
Return global number of Boxes.
This requires a global reduction, if the global-reduced data has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Periodic image Boxes are excluded.
Precondition:
isInitialized()
References cacheGlobalReducedData(), isInitialized(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel().
int SAMRAI::hier::BoxLevel::getMaxNumberOfBoxes () const [inline]
Return maximum number of Boxes over all processes.
This requires a global reduction, if the global-reduced data has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Periodic image Boxes are excluded.
Precondition:
isInitialized()
References cacheGlobalReducedData(), isInitialized(), and TBOX_ASSERT.
int SAMRAI::hier::BoxLevel::getMinNumberOfBoxes () const [inline]
Return maximum number of Boxes over all processes.
This requires a global reduction, if the global-reduced data has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Periodic image Boxes are excluded.
Precondition:
isInitialized()
References cacheGlobalReducedData(), isInitialized(), and TBOX_ASSERT.
size_t SAMRAI::hier::BoxLevel::getLocalNumberOfCells () const [inline]
Return local number of cells.
Cells in periodic image Boxes are excluded.
Precondition:
isInitialized()
References isInitialized(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps(), and cacheGlobalReducedData().
int SAMRAI::hier::BoxLevel::getMaxNumberOfCells () const [inline]
Return maximum number of cells over all processes.
This requires a global reduction, if the global-reduced data has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Periodic image Boxes are excluded.
Precondition:
isInitialized()
References cacheGlobalReducedData(), isInitialized(), and TBOX_ASSERT.
int SAMRAI::hier::BoxLevel::getMinNumberOfCells () const [inline]
Return maximum number of cells over all processes.
This requires a global reduction, if the global-reduced data has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Periodic image Boxes are excluded.
Precondition:
isInitialized()
References cacheGlobalReducedData(), isInitialized(), and TBOX_ASSERT.
size_t SAMRAI::hier::BoxLevel::getLocalNumberOfCells (int rank) const
Return number of cells local to the given rank.
Cells in periodic image Boxes are excluded.
Parameters:
[in] rank
Precondition:
isInitialized()
(getParallelState() == GLOBALIZED) || (rank == getMPI().getRank())
(rank >= 0) && (rank < getMPI().getSize())
References SAMRAI::hier::BoxContainer::begin(), DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSize(), isInitialized(), TBOX_ASSERT, and TBOX_ERROR.
long int SAMRAI::hier::BoxLevel::getGlobalNumberOfCells () const [inline]
Return global number of cells.
This requires a global reduction if the global-reduced data has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Cells in periodic image Boxes are excluded.
Precondition:
isInitialized()
References cacheGlobalReducedData(), isInitialized(), and TBOX_ASSERT.
const Box& SAMRAI::hier::BoxLevel::getLocalBoundingBox (int block_number) const [inline]
Return bounding box for local Boxes in a block.
Referenced by recursivePrint().
const Box& SAMRAI::hier::BoxLevel::getGlobalBoundingBox (int block_number) const [inline]
Return bounding box for global Boxes in a block.
This requires a global reduction if the global bounding box has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
References cacheGlobalReducedData().
Referenced by recursivePrint().
const IntVector& SAMRAI::hier::BoxLevel::getLocalMaxBoxSize (int block_number) const [inline]
Return size of the largest local Box in a block.
const IntVector& SAMRAI::hier::BoxLevel::getLocalMinBoxSize (int block_number) const [inline]
Return size of the smallest local Box in a block.
const IntVector& SAMRAI::hier::BoxLevel::getGlobalMaxBoxSize (int block_number) const [inline]
Return size of the largest Box globally in a block.
This requires a global reduction if the global bounding box has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
References cacheGlobalReducedData().
const IntVector& SAMRAI::hier::BoxLevel::getGlobalMinBoxSize (int block_number) const [inline]
Return size of the smallest Box globally in a block.
This requires a global reduction if the global bounding box has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
References cacheGlobalReducedData().
const tbox::Dimension& SAMRAI::hier::BoxLevel::getDim () const [inline]
Return the dimension of this object.
References SAMRAI::hier::IntVector::getDim().
Referenced by addBox(), addPeriodicBox(), SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), cacheGlobalReducedData(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), getBox(), getBoxStrict(), hasBox(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), recursivePrint(), and swap().
const boost::shared_ptr<const BaseGridGeometry>& SAMRAI::hier::BoxLevel::getGridGeometry () const [inline]
Return the grid geometry associated with this object.
If object has never been initialized, return NULL pointer.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::Connector::finalizeContext(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::PatchHierarchy::makeNewPatchLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and swap().
void SAMRAI::hier::BoxLevel::refineBoxes (BoxLevel & finer, const IntVector & ratio, const IntVector & final_ratio) const [inline]
Refine all Boxes of this BoxLevel by ratio placing result into finer making finer's ratio final_ratio.
Parameters:
[out] finer
[in] ratio
[in] final_ratio
References GLOBALIZED, and SAMRAI::hier::BoxContainer::refine().
Referenced by SAMRAI::hier::BaseGridGeometry::computePhysicalDomain().
void SAMRAI::hier::BoxLevel::coarsenBoxes (BoxLevel & coarser, const IntVector & ratio, const IntVector & final_ratio) const [inline]
Coarsen all Boxes of this BoxLevel by ratio placing result into coarser making coarser's ratio final_ratio.
Parameters:
[out] coarser
[in] ratio
[in] final_ratio
References SAMRAI::hier::BoxContainer::coarsen(), and GLOBALIZED.
Referenced by SAMRAI::hier::BaseGridGeometry::computePhysicalDomain().
BoxContainer::const_iterator SAMRAI::hier::BoxLevel::addBox (const Box & box, const BlockId & block_id)
Create new local Box from given Box and add it to this level.
The new Box will be assigned an unused local index, so the input box need not have a valid one. To be efficient, no communication will be used. Therefore, the state must be distributed.
The new Box will have a periodic shift number corresponding to zero-shift.
Note:
It is imperative that applications which call addBox also call invalidateGlobalData. It is possible for some processes to add Boxes and for others to not. Since the addBox method sets d_global_data_up_to_date to false, some processes in this situation will have this flag set to true and others will not. This will result in a hang in cacheGlobalReducedData when global data is accessed. We could have performed and allReduce of this flag to the top of cacheGlobalReducedData but this would have added a costly call for every access of global data.
Parameters:
[in] box
[in] block_id
Returns:
iterator to the new Box
Precondition:
getParallelState() == DISTRIBUTED
(box.getBlockId() == BlockId::invalidId()) || (box.getBlockId() == block_id)
References SAMRAI::hier::BoxContainer::begin(), clearForBoxChanges(), DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), getDim(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::LocalId::getZero(), SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::BlockId::invalidId(), SAMRAI::hier::BoxContainer::isEmpty(), locked(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BoxTransitSet::putInBoxLevel().
void SAMRAI::hier::BoxLevel::addBox (const Box & box)
Add a Box to this level.
CAUTION
To be efficient, no checks are made to make sure the BoxLevel representation is consistent across all processors. Setting inconsistent data leads potentially elusive bugs.
Errors
It is an error to add a periodic image of a Box that is not a part of the BoxLevel.
It is an error to add any Box that already exists.
Note:
It is imperative that applications which call addBox also call invalidateGlobalData. It is possible for some processes to add Boxes and for others to not. Since the addBox method sets d_global_data_up_to_date to false, some processes in this situation will have this flag set to true and others will not. This will result in a hang in cacheGlobalReducedData when global data is accessed. We could have performed and allReduce of this flag to the top of cacheGlobalReducedData but this would have added a costly call for every access of global data.
Parameters:
[in] box
References clearForBoxChanges(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), getDim(), SAMRAI::hier::Box::getGlobalId(), SAMRAI::hier::Box::getLocalId(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber(), GLOBALIZED, SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::Box::isPeriodicImage(), SAMRAI::hier::LocalId::isValid(), locked(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::BoxLevel::addBoxWithoutUpdate (const Box & box) [inline]
Add a Box to this level without updating summary data such as local number of boxes/cells, bounding box, max/min box size. Meant to be used during the construction of a BoxLevel as Boxes belonging to the level are found. finalize() should be called at the end of construction making use of addBoxWithoutUpdate.
Parameters:
[in] box
References getParallelState(), GLOBALIZED, SAMRAI::hier::BoxContainer::insert(), locked(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BaseGridGeometry::computePhysicalDomain().
void SAMRAI::hier::BoxLevel::addPeriodicBox (const Box & existing_box, const PeriodicId & shift_number)
Insert given periodic image of an existing Box.
Unlike adding a regular Box, it is OK to add a periodic image Box that already exists. However, that is a no-op.
CAUTION
To be efficient, no checks are made to make sure the BoxLevel representation is consistent across all processors. Setting inconsistent data leads to potentially elusive bugs.
Errors
It is an error to add a periodic image of a Box that does not exist.
TODO: Should we prevent this operation if persistent overlap Connectors are attached to this object?
Parameters:
[in] existing_box An existing Box for reference. This Box must be in the BoxLevel. The Box added is an image of the reference Box but shifted to another position.
[in] shift_number The valid shift number for the Box being added. The shift amount is taken from the PeriodicShiftCatalog.
Precondition:
shift_number != PeriodicShiftCatalog::getCatalog(getDim())->getZeroShiftNumber()
References clearForBoxChanges(), DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), getDim(), SAMRAI::hier::Box::getGlobalId(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber(), GLOBALIZED, SAMRAI::hier::BoxContainer::insert(), locked(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), and SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships().
void SAMRAI::hier::BoxLevel::eraseBox (BoxContainer::iterator & ibox)
Erase the existing Box specified by its iterator.
The given iterator MUST be a valid iterator pointing to a Box currently in this object. After erasing, the iterator is advanced to the next valid Box (or the end of its BoxContainer).
Erasing a Box also erases all of its periodic images.
TODO: Should we prevent this operation if the object has persistent overlap Connectors?
Note:
It is imperative that applications which call eraseBox also call invalidateGlobalData. It is possible for some processes to erase Boxes and for others to not. Since the eraseBox method sets d_global_data_up_to_date to false, some processes in this situation will have this flag set to true and others will not. This will result in a hang in cacheGlobalReducedData when global data is accessed. We could have performed and allReduce of this flag to the top of cacheGlobalReducedData but this would have erased a costly call for every access of global data.
Parameters:
[in] ibox The iterator of the Box to erase.
Precondition:
getParallelState() == DISTRIBUTED
ibox == getBoxes().find(*ibox)
References clearForBoxChanges(), DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::erase(), SAMRAI::hier::BoxContainer::find(), locked(), and TBOX_ERROR.
void SAMRAI::hier::BoxLevel::eraseBox (const Box & box)
Erase the Box matching the one given.
The given Box MUST match a Box currently in this object. Matching means that the BoxId's match (disregarding the spatial coordinates).
Erasing a Box also erases all of its periodic images.
TODO: Should we prevent this operation if the object has persistent overlap Connectors?
Note:
It is imperative that applications which call eraseBox also call invalidateGlobalData. It is possible for some processes to erase Boxes and for others to not. Since the eraseBox method sets d_global_data_up_to_date to false, some processes in this situation will have this flag set to true and others will not. This will result in a hang in cacheGlobalReducedData when global data is accessed. We could have performed and allReduce of this flag to the top of cacheGlobalReducedData but this would have erased a costly call for every access of global data.
Parameters:
[in] box
Precondition:
getParallelState() == DISTRIBUTED
getBoxes().find(box) != getBoxes().end()
References clearForBoxChanges(), DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::erase(), SAMRAI::hier::BoxContainer::find(), locked(), and TBOX_ERROR.
void SAMRAI::hier::BoxLevel::eraseBoxWithoutUpdate (const Box & box) [inline]
Erases the Box matching the supplied Box from this level without updating summary data such as local number of boxes/cells, bounding box, max/min box size. Meant to be used during the construction of a BoxLevel as Boxes not belonging to the level are found. finalize() should be called at the end of construction making use of eraseBoxWithoutUpdate.
Parameters:
[in] box
References SAMRAI::hier::BoxContainer::erase(), locked(), and TBOX_ERROR.
BoxContainer::const_iterator SAMRAI::hier::BoxLevel::getBox (const Box & box) const [inline]
Find the Box matching the one given.
Only the BoxId matters in matching, so the actual Box can be anything.
If box is not a local Box, the state must be GLOBALIZED.
Parameters:
[in] box
Returns:
Iterator to the box, or getBoxes(owner).end() if box does not exist in set.
Precondition:
(box.getOwnerRank() == getMPI().getRank()) || (getParallelState() == GLOBALIZED)
References SAMRAI::hier::BoxContainer::find(), getMPI(), SAMRAI::hier::Box::getOwnerRank(), getParallelState(), SAMRAI::tbox::SAMRAI_MPI::getRank(), GLOBALIZED, and TBOX_ERROR.
Referenced by SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), getBox(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::hier::Connector::recursivePrint().
BoxContainer::const_iterator SAMRAI::hier::BoxLevel::getBox (const BoxId & box_id) const [inline]
Find the Box specified by the given BoxId and periodic shift.
If box is not a local Box, the state must be GLOBALIZED.
Parameters:
[in] box_id
Returns:
Iterator to the box, or getBoxes(owner).end() if box does not exist in set.
References getBox(), and getDim().
BoxContainer::const_iterator SAMRAI::hier::BoxLevel::getBoxStrict (const Box & box) const
Find the Box matching the one given.
Only the BoxId matters in matching, so the actual Box can be anything.
If box is not owned by the local process, the state must be GLOBALIZED.
You cannot directly modify the BoxContainer because it may invalidate other internal data. Use other methods for modifying the BoxContainer.
Parameters:
[in] box
Returns:
Iterator to the box.
Precondition:
((box.getOwnerRank() == getMPI().getRank()) && (getBoxes().find(box) != getBoxes().end())) || ((box.getOwnerRank() != getMPI().getRank()) && (getParallelState() == GLOBALIZED) && (getGlobalBoxes().find(box) != getGlobalBoxes().end()))
References SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), GLOBALIZED, and TBOX_ERROR.
Referenced by SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::MappingConnector::findMappingErrors(), and SAMRAI::hier::Connector::shrinkWidth().
BoxContainer::const_iterator SAMRAI::hier::BoxLevel::getBoxStrict (const BoxId & box_id) const
Find the Box specified by the given BoxId.
You cannot directly modify the BoxContainer because it may invalidate other internal data. Use other methods for modifying the BoxContainer.
Parameters:
[in] box_id
Returns:
Iterator to the box.
Precondition:
(box_id.getOwnerRank() == getMPI().getRank()) || (getParallelState() == GLOBALIZED)
box with supplied BoxId exists in the BoxLevel
References SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::find(), getDim(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), GLOBALIZED, and TBOX_ERROR.
bool SAMRAI::hier::BoxLevel::getSpatiallyEqualBox (const Box & box_to_match, const BlockId & block_id, Box & matching_box) const
Find the Box with the given BlockId which is spatially equal to the supplied Box.
Parameters:
[in] box_to_match
[in] block_id
[out] matching_box If there is a box with the supplied BlockId spatially equal to box_to_match then this is set to that Box.
Returns:
true if a match is found.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), and SAMRAI::hier::Box::isSpatiallyEqual().
bool SAMRAI::hier::BoxLevel::hasBox (const BoxId & box_id) const [inline]
Returns true when the object has a Box specified by the BoxId.
Parameters:
[in] box_id
References getDim().
Referenced by SAMRAI::hier::Connector::checkConsistencyWithBase(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::Connector::finalizeContext(), SAMRAI::hier::MappingConnector::findMappingErrors(), and hasBox().
bool SAMRAI::hier::BoxLevel::hasBox (const GlobalId & global_id, const PeriodicId & periodic_id) const [inline]
Returns true when the object has a Box consistent with all of the arguments.
Parameters:
[in] global_id
[in] periodic_id
References getDim(), and hasBox().
bool SAMRAI::hier::BoxLevel::hasBox (const Box & box) const
Returns true when this BoxLevel has a Box matching the BoxId of the given box.
Parameters:
[in] box
Precondition:
(box.getOwnerRank() == getMPI().getRank()) || (getParallelState() == GLOBALIZED)
References DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), and TBOX_ERROR.
void SAMRAI::hier::BoxLevel::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Write the BoxLevel to a restart database.
Write only local parts regardless of parallel state (to avoid writing tons of repetitive data).
Parameters:
[in,out] restart_db
References getBoxes(), SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::tbox::Dimension::getValue(), and SAMRAI::hier::BoxContainer::putToRestart().
void SAMRAI::hier::BoxLevel::invalidateGlobalData () [inline]
Sets d_global_data_up_to_date to false. Must be called after calls to addBox or eraseBox.
See also:
addBox()
eraseBox()
References locked(), and TBOX_ERROR.
void SAMRAI::hier::BoxLevel::clearPersistentOverlapConnectors () [inline]
Deallocate persistent overlap Connectors, if there are any.
Referenced by clearForBoxChanges(), operator=(), and swap().
const Connector& SAMRAI::hier::BoxLevel::findConnector (const BoxLevel & head, const IntVector & min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only = false) const [inline]
Find an overlap Connector with the given head and minimum Connector width. If the specified Connector is not found, take the specified action.
If multiple Connectors fit the criteria, the one with the smallest ghost cell width (based on the algebraic sum of the components) is selected.
Parameters:
[in] head Find the overlap Connector with this specified head.
[in] min_connector_width Find the overlap Connector satisfying this minimum Connector width.
[in] not_found_action Action to take if Connector is not found.
[in] exact_width_only If true, reject Connectors that do not match the requested width exactly.
Returns:
The Connector which matches the search criterion.
Precondition:
isInitialized()
head.isInitialized()
Referenced by SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), and SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets().
const Connector& SAMRAI::hier::BoxLevel::findConnectorWithTranspose (const BoxLevel & head, const IntVector & min_connector_width, const IntVector & transpose_min_connector_width, ConnectorNotFoundAction not_found_action, bool exact_width_only = false) const [inline]
Find an overlap Connector with its transpose with the given head and minimum Connector widths. If the specified Connector is not found, take the specified action.
If multiple Connectors fit the criteria, the one with the smallest ghost cell width (based on the algebraic sum of the components) is selected.
Parameters:
[in] head Find the overlap Connector with this specified head.
[in] min_connector_width Find the overlap Connector satisfying this minimum Connector width.
[in] transpose_min_connector_width Find the transpose overlap Connector satisfying this minimum Connector width.
[in] not_found_action Action to take if Connector is not found.
[in] exact_width_only If true, reject Connectors that do not match the requested width exactly.
Returns:
The Connector which matches the search criterion.
Precondition:
isInitialized()
head.isInitialized()
const Connector& SAMRAI::hier::BoxLevel::createConnector (const BoxLevel & head, const IntVector & connector_width) const [inline]
Create an overlap Connector, computing relationships by globalizing data.
The base will be this BoxLevel. Find Connector relationships using a (non-scalable) global search.
See also:
hier::Connector
hier::Connector::initialize()
Parameters:
[in] head This BoxLevel will be the head.
[in] connector_width
Returns:
A const reference to the newly created overlap Connector.
Precondition:
isInitialized()
head.isInitialized()
const Connector& SAMRAI::hier::BoxLevel::createConnectorWithTranspose (const BoxLevel & head, const IntVector & connector_width, const IntVector & transpose_connector_width) const [inline]
Create an overlap Connector with its transpose, computing relationships by globalizing data.
The base will be this BoxLevel. Find Connector relationships using a (non-scalable) global search.
See also:
hier::Connector
hier::Connector::initialize()
Parameters:
[in] head This BoxLevel will be the head.
[in] connector_width
[in] transpose_connector_width
Returns:
A const reference to the newly created overlap Connector.
Precondition:
isInitialized()
head.isInitialized()
void SAMRAI::hier::BoxLevel::cacheConnector (boost::shared_ptr< Connector > & connector) const [inline]
Cache the supplied overlap Connector and its transpose if it exists.
Parameters:
[in] connector
Precondition:
isInitialized()
connector
bool SAMRAI::hier::BoxLevel::hasConnector (const BoxLevel & head, const IntVector & min_connector_width, bool exact_width_only = false) const [inline]
Returns whether the object has overlap Connectors with the given head and minimum Connector width.
TODO: does the following comment mean that this must be called before the call to findConnector?
If this returns true, the Connector fitting the specification exists and findConnector() will not throw an assertion.
Parameters:
[in] head Find the overlap Connector with this specified head.
[in] min_connector_width Find the overlap Connector satisfying this minimum ghost cell width.
[in] exact_width_only If true, reject Connectors that do not match the requested width exactly.
Returns:
True if a Connector is found, otherwise false.
const boost::shared_ptr<BoxLevelHandle>& SAMRAI::hier::BoxLevel::getBoxLevelHandle () const [inline]
Get the handle with which Connectors reference the BoxLevel instead of referencing the BoxLevel itself. Not for general use.
Connectors referencing their base and head BoxLevels should reference their handles instead of the BoxLevels themselves. As long as the BoxLevel does not change in a way that can invalidate Connector data, you can access the BoxLevel from the BoxLevelHandle.
If the BoxLevel go out of scope before the Connector disconnects, this boost::shared_ptr object will stay around until all Connectors have disconnected.
Operations that can invalidate Connector data are those that remove information from the BoxLevel. These are:
initialize()
swapInitialize()
swap()
clear()
operator=() (assignment) (Exception: assigning to self is a no-op, which does not invalidate Connector data.
eraseBox() (Note that adding a Box does not invalidate Connector data.)
going out of scope
See also:
BoxLevelHandle.
Returns:
A boost::shared_ptr to the BoxLevelHandle
Precondition:
!d_handle || (d_handle->d_box_level == this)
References TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelHandle::getBoxLevel(), SAMRAI::hier::Connector::setBase(), and SAMRAI::hier::Connector::setHead().
void SAMRAI::hier::BoxLevel::lock () [inline]
Effectively makes a non-const BoxLevel const. Prevents any non-const method from executing.
bool SAMRAI::hier::BoxLevel::locked () [inline]
Returns true if the BoxLevel is locked.
Referenced by addBox(), addBoxWithoutUpdate(), addPeriodicBox(), clear(), clearForBoxChanges(), eraseBox(), eraseBoxWithoutUpdate(), finalize(), initialize(), invalidateGlobalData(), operator=(), removePeriodicImageBoxes(), setParallelState(), swap(), and swapInitialize().
void SAMRAI::hier::BoxLevel::recursivePrint (std::ostream & os, const std::string & border, int detail_depth = 2) const
Print Box info from this level.
Parameters:
[in,out] os The output stream
[in] border
[in] detail_depth
References SAMRAI::hier::BoxContainer::begin(), DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), getDim(), getGlobalBoundingBox(), getLocalBoundingBox(), getParallelState(), SAMRAI::tbox::SAMRAI_MPI::getRank(), getRefinementRatio(), SAMRAI::tbox::SAMRAI_MPI::getSize(), GLOBALIZED, isInitialized(), and SAMRAI::hier::Box::numberCells().
Referenced by SAMRAI::hier::operator<<().
BoxLevel::Outputter SAMRAI::hier::BoxLevel::format (const std::string & border = std::string(), int detail_depth = 2) const
Return a object that can format the BoxLevel for inserting into output streams.
Usage example:
    tbox::plog << "my box_level:\n" << box_level.format() << endl;
Parameters:
[in] border
[in] detail_depth
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::MappingConnector::assertMappingValidity(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::Connector::finalizeContext(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::PatchHierarchy::logMetadataStatistics(), and SAMRAI::hier::MappingConnectorAlgorithm::modify().
BoxLevel::Outputter SAMRAI::hier::BoxLevel::formatStatistics (const std::string & border = std::string()) const
Return a object that can format the BoxLevel for inserting its global statistics into output streams.
Usage example:
    std::cout << "my box_level statistics:\n"
              << box_level.formatStatistics("  ") << std::endl;
Parameters:
[in] border
Referenced by SAMRAI::hier::PatchHierarchy::logMetadataStatistics().
Friends And Related Function Documentation
friend class PersistentOverlapConnectors [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxLevel.h
source/SAMRAI/hier/BoxLevel.C