SAMRAI: SAMRAI::hier::PatchBoundaries Class Reference
SAMRAI::hier::PatchBoundaries Class Reference
Class PatchBoundaries is a container class for storing BoundaryBox objects for a single patch.
#include <source/SAMRAI/hier/PatchBoundaries.h>
Public Member Functions
PatchBoundaries (const tbox::Dimension &dim)
Explicit constructor requires dimension argument.
PatchBoundaries (const PatchBoundaries &r)
Copy constructor.
PatchBoundaries & operator= (const PatchBoundaries &r)
Assignment operator.
std::vector< BoundaryBox > & operator[] (unsigned int i)
Vector access operator.
const std::vector< BoundaryBox > & operator[] (unsigned int i) const
Const Vector access operator.
std::vector< std::vector
< BoundaryBox > > & getVectors ()
Get copy of the internal vectors.
const std::vector< std::vector
< BoundaryBox > > & getVectors () const
Get const copy of the internal vectors.
const tbox::Dimension & getDim () const
Detailed Description
Class PatchBoundaries is a container class for storing BoundaryBox objects for a single patch.
See also:
hier::BoundaryBox
Constructor & Destructor Documentation
SAMRAI::hier::PatchBoundaries::PatchBoundaries (const tbox::Dimension & dim) [explicit]
Explicit constructor requires dimension argument.
Parameters:
[in] dim
SAMRAI::hier::PatchBoundaries::PatchBoundaries (const PatchBoundaries & r)
Copy constructor.
Parameters:
[in] r Patchboundaries object to be copied in constructor.
References SAMRAI::tbox::Dimension::getValue().
Member Function Documentation
PatchBoundaries& SAMRAI::hier::PatchBoundaries::operator= (const PatchBoundaries & r) [inline]
Assignment operator.
Parameters:
[in] r Patchboundaries object to be copied in assignment.
References getDim(), and SAMRAI::tbox::Dimension::getValue().
std::vector<BoundaryBox>& SAMRAI::hier::PatchBoundaries::operator[] (unsigned int i) [inline]
Vector access operator.
Parameters:
[in] i Vector index.
Precondition:
i < getDim().getValue()
References getDim(), and TBOX_ASSERT.
const std::vector<BoundaryBox>& SAMRAI::hier::PatchBoundaries::operator[] (unsigned int i) const [inline]
Const Vector access operator.
Parameters:
[in] i Vector index.
Precondition:
i < getDim().getValue()
References getDim(), and TBOX_ASSERT.
std::vector<std::vector<BoundaryBox> >& SAMRAI::hier::PatchBoundaries::getVectors () [inline]
Get copy of the internal vectors.
Returns:
Copy of the internal vectors.
Referenced by SAMRAI::hier::PatchGeometry::getPatchBoundaries().
const std::vector<std::vector<BoundaryBox> >& SAMRAI::hier::PatchBoundaries::getVectors () const [inline]
Get const copy of the internal vectors.
Returns:
Const copy of the internal vectors.
const tbox::Dimension& SAMRAI::hier::PatchBoundaries::getDim () const [inline]
Referenced by operator=(), and operator[]().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchBoundaries.h
source/SAMRAI/hier/PatchBoundaries.C