SAMRAI: SAMRAI::hier::BaseGridGeometry::Neighbor Class Reference
SAMRAI::hier::BaseGridGeometry::Neighbor Class Reference
Class to represent the neighbor of a given block.
#include <source/SAMRAI/hier/BaseGridGeometry.h>
Public Member Functions
Neighbor (const BlockId &block_id, const BoxContainer &domain, const Transformation &transformation)
Constructor.
const BlockId & getBlockId () const
Get the block number of the neighboring block.
const BoxContainer & getTransformedDomain () const
Get the neighboring block's domain in the current block's index space.
const Transformation & getTransformation () const
Get the Transformation for the neighbor relationship.
Transformation::RotationIdentifier getRotationIdentifier () const
Get the rotation identifier for the neighbor relationship.
const IntVector & getShift () const
Get the shift for the neighbor relationship.
void setSingularity (bool is_singularity)
Set the flag telling if that the neighboring blocks touch each other at an enhanced connectivity singularity.
bool isSingularity () const
Tell if the neighboring blocks touch each other at an enhanced connectivity singularity.
Detailed Description
Class to represent the neighbor of a given block.
Constructor & Destructor Documentation
SAMRAI::hier::BaseGridGeometry::Neighbor::Neighbor (const BlockId & block_id, const BoxContainer & domain, const Transformation & transformation)
Constructor.
Parameters:
[in] block_id The block id of the neighboring block
[in] domain The neighboring block's domain in the current block's index space
[in] transformation The transformation needed to align the neighboring index spaces
Member Function Documentation
const BlockId& SAMRAI::hier::BaseGridGeometry::Neighbor::getBlockId () const [inline]
Get the block number of the neighboring block.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BaseGridGeometry::printClassData(), and SAMRAI::hier::BaseGridGeometry::putToRestart().
const BoxContainer& SAMRAI::hier::BaseGridGeometry::Neighbor::getTransformedDomain () const [inline]
Get the neighboring block's domain in the current block's index space.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), and SAMRAI::hier::BaseGridGeometry::putToRestart().
const Transformation& SAMRAI::hier::BaseGridGeometry::Neighbor::getTransformation () const [inline]
Get the Transformation for the neighbor relationship.
Referenced by SAMRAI::hier::BaseGridGeometry::putToRestart().
Transformation::RotationIdentifier SAMRAI::hier::BaseGridGeometry::Neighbor::getRotationIdentifier () const [inline]
Get the rotation identifier for the neighbor relationship.
References SAMRAI::hier::Transformation::getRotation().
Referenced by SAMRAI::hier::BaseGridGeometry::transformBox(), and SAMRAI::hier::BaseGridGeometry::transformBoxContainer().
const IntVector& SAMRAI::hier::BaseGridGeometry::Neighbor::getShift () const [inline]
Get the shift for the neighbor relationship.
References SAMRAI::hier::Transformation::getOffset().
Referenced by SAMRAI::hier::BaseGridGeometry::transformBox(), and SAMRAI::hier::BaseGridGeometry::transformBoxContainer().
void SAMRAI::hier::BaseGridGeometry::Neighbor::setSingularity (bool is_singularity) [inline]
Set the flag telling if that the neighboring blocks touch each other at an enhanced connectivity singularity.
bool SAMRAI::hier::BaseGridGeometry::Neighbor::isSingularity () const [inline]
Tell if the neighboring blocks touch each other at an enhanced connectivity singularity.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::BaseGridGeometry::printClassData(), and SAMRAI::hier::BaseGridGeometry::putToRestart().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BaseGridGeometry.h
source/SAMRAI/hier/BaseGridGeometry.C