SAMRAI: SAMRAI::pdat::OuternodeGeometry Class Reference
SAMRAI::pdat::OuternodeGeometry Class Reference
#include <source/SAMRAI/pdat/OuternodeGeometry.h>
Public Types
typedef NodeOverlap Overlap
Public Member Functions
OuternodeGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct an outernode geometry object given an AMR index space box and ghost cell width.
virtual ~OuternodeGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in node-centered index space on the boundaries of the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a NodeOverlap object based on the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this outernode box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this outernode box geometry object.
Detailed Description
Class OuternodeGeometry manages the mapping between the AMR index and the outernode geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between outernode box geometries and node or outernode box geometries for communication operations.
See header file for OuternodeData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
NodeGeometry
NodeOverlap
Member Typedef Documentation
typedef NodeOverlap SAMRAI::pdat::OuternodeGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::OuternodeGeometry::OuternodeGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct an outernode geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::OuternodeGeometry::~OuternodeGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OuternodeGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in node-centered index space on the boundaries of the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::OuternodeGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a NodeOverlap object based on the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::pushBack(), and SAMRAI::pdat::NodeGeometry::toNodeBox().
const hier::Box& SAMRAI::pdat::OuternodeGeometry::getBox () const [inline]
Return the box for this outernode box geometry object.
const hier::IntVector& SAMRAI::pdat::OuternodeGeometry::getGhosts () const [inline]
Return the ghost cell width for this outernode box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OuternodeGeometry.h
source/SAMRAI/pdat/OuternodeGeometry.C