SAMRAI: SAMRAI::pdat::FaceIterator Class Reference
SAMRAI::pdat::FaceIterator Class Reference
#include <source/SAMRAI/pdat/FaceIterator.h>
Public Member Functions
FaceIterator (const FaceIterator &iterator)
FaceIterator & operator= (const FaceIterator &iterator)
~FaceIterator ()
const FaceIndex & operator* () const
const FaceIndex * operator-> () const
FaceIterator & operator++ ()
FaceIterator operator++ (int)
bool operator== (const FaceIterator &iterator) const
bool operator!= (const FaceIterator &iterator) const
Friends
FaceIterator FaceGeometry::begin (const hier::Box &box, tbox::Dimension::dir_t axis)
FaceIterator FaceGeometry::end (const hier::Box &box, tbox::Dimension::dir_t axis)
Detailed Description
Class FaceIterator is an iterator that provides methods for stepping through the index space associated with a face centered box. The indices are enumerated in column-major (e.g., Fortran) order. The iterator should be used as follows:
 * hier::Box box;
 * ...
 * FaceIterator cend(box, axis, false);
 * for (FaceIterator c(box, axis, true); c != cend; ++c) {
 *    // use index c of the box
 * }
 *
Note that the face iterator may not compile to efficient code, depending on your compiler. Many compilers are not smart enough to optimize the looping constructs and indexing operations.
See also:
pdat::FaceData
pdat::FaceGeometry
pdat::FaceIndex
Constructor & Destructor Documentation
SAMRAI::pdat::FaceIterator::FaceIterator (const FaceIterator & iterator)
Copy constructor for the face iterator
SAMRAI::pdat::FaceIterator::~FaceIterator ()
Destructor for the face iterator.
Member Function Documentation
FaceIterator& SAMRAI::pdat::FaceIterator::operator= (const FaceIterator & iterator) [inline]
Assignment operator for the face iterator.
const FaceIndex& SAMRAI::pdat::FaceIterator::operator* () const [inline]
Extract the face index corresponding to the iterator position in the box.
const FaceIndex* SAMRAI::pdat::FaceIterator::operator-> () const [inline]
Extract a pointer to the face index corresponding to the iterator position in the box.
FaceIterator & SAMRAI::pdat::FaceIterator::operator++ ()
Pre-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
FaceIterator SAMRAI::pdat::FaceIterator::operator++ (int)
Post-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
bool SAMRAI::pdat::FaceIterator::operator== (const FaceIterator & iterator) const [inline]
Test two iterators for equality (same index value).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
bool SAMRAI::pdat::FaceIterator::operator!= (const FaceIterator & iterator) const [inline]
Test two iterators for inequality (different index values).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
Friends And Related Function Documentation
FaceIterator FaceGeometry::begin (const hier::Box & box, tbox::Dimension::dir_t axis) [friend]
FaceIterator FaceGeometry::end (const hier::Box & box, tbox::Dimension::dir_t axis) [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/FaceIterator.h
source/SAMRAI/pdat/FaceIterator.C