SAMRAI: SAMRAI::hier::BoundaryBox Class Reference
SAMRAI::hier::BoundaryBox Class Reference
Class BoundaryBox is is used to describe boundaries of a patch.
#include <source/SAMRAI/hier/BoundaryBox.h>
Public Types
enum BoundaryOrientation { LOWER = -1, MIDDLE = 0, UPPER = 1 }
Enumerated type BoundaryOrientation is used to indicate where a boundary box is located relative to a patch in a particular coordinate direction. MIDDLE means a boundary box is neither on the upper or lower side of a patch in the given coordinate direction. For example, an edge boundary box on the right side of a patch in 2d is neither on the upper or lower side of the patch in the J coordinate direction, so its BoundaryOrientation value would be MIDDLE. The same boundary box would be UPPER in the I coordinate direction.
Public Member Functions
BoundaryBox (const tbox::Dimension &dim)
Constructor that builds an undefined boundary box, with invalid values other than dimension.
BoundaryBox (const Box &box, const int bdry_type, const int location_index)
Construct a boundary box described by arguments.
BoundaryBox (const BoundaryBox &boundary_box)
Copy constructor.
~BoundaryBox ()
The destructor for BoundaryBox.
const Box & getBox () const
Return the Box member of the boundary box.
int getBoundaryType () const
Return the boundary type (codimension) of the boundary box.
int getLocationIndex () const
Return the location index for the boundary box.
void setIsMultiblockSingularity (bool is_mblk_singularity)
Set the multiblock singularity flag to the argument value.
bool getIsMultiblockSingularity () const
Get the value of the multiblock singularity flag.
BoundaryBox & operator= (const BoundaryBox &boundary_box)
The assignment operator copies all data components.
BoundaryOrientation getBoundaryOrientation (const int dir) const
Get which side of a patch the boundary box is on.
const tbox::Dimension & getDim () const
Return the dimension of this object.
Detailed Description
Class BoundaryBox is is used to describe boundaries of a patch.
Objects of this type are held by a PatchGeometry object. The BoundaryBox consists of a Box, a boundary type (codimension), and a location index. The Box is one cell wide in at least one direction and is located just outside of a patch boundary. For example, a bondary box along a patch face is one cell wide in the coordinate direction normal to the patch face. The boundary type identifies the type of patch bounadry: face, edge, or corner (node). The location index specifies the location of the boundary box in relation to the patch boundary. See the getBoundaryType() and getLocationIndex() methods for more information.
See also:
hier::Box
hier::PatchGeometry
hier::BoundaryLookupTable
Member Enumeration Documentation
enum SAMRAI::hier::BoundaryBox::BoundaryOrientation
Enumerated type BoundaryOrientation is used to indicate where a boundary box is located relative to a patch in a particular coordinate direction. MIDDLE means a boundary box is neither on the upper or lower side of a patch in the given coordinate direction. For example, an edge boundary box on the right side of a patch in 2d is neither on the upper or lower side of the patch in the J coordinate direction, so its BoundaryOrientation value would be MIDDLE. The same boundary box would be UPPER in the I coordinate direction.
Enumerator:
LOWER
MIDDLE
UPPER
Constructor & Destructor Documentation
SAMRAI::hier::BoundaryBox::BoundaryBox (const tbox::Dimension & dim) [explicit]
Constructor that builds an undefined boundary box, with invalid values other than dimension.
Parameters:
[in] dim Dimension
SAMRAI::hier::BoundaryBox::BoundaryBox (const Box & box, const int bdry_type, const int location_index)
Construct a boundary box described by arguments.
Assertions: bdry_type must be between 1 and dim, inclusive. location_index must be non-negative and less than the location index max, which is the total number of boundaries of a particular codimension that a single patch has. This max value can be obtained from the class BoundaryLookupTable using the getMaxLocationIndices method.
Parameters:
[in] box
[in] bdry_type
[in] location_index
Precondition:
(bdry_type >= 1) && (bdry_type <= d_dim.getValue())
location_index >= 0
location_index < BoundaryLookupTable::getLookupTable(box.getDim())->getMaxLocationIndices()[bdry_type - 1]
References SAMRAI::hier::BoundaryLookupTable::getLookupTable(), SAMRAI::hier::BoundaryLookupTable::getMaxLocationIndices(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
SAMRAI::hier::BoundaryBox::BoundaryBox (const BoundaryBox & boundary_box)
Copy constructor.
Parameters:
[in] boundary_box
SAMRAI::hier::BoundaryBox::~BoundaryBox ()
The destructor for BoundaryBox.
Member Function Documentation
const Box& SAMRAI::hier::BoundaryBox::getBox () const [inline]
Return the Box member of the boundary box.
Returns:
The Box
Referenced by SAMRAI::hier::BoundaryBoxUtils::extendBoxOutward(), SAMRAI::hier::PatchGeometry::getBoundaryFillBox(), SAMRAI::hier::BoundaryBoxUtils::getSurfaceBoxFromBoundaryBox(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs(), SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth(), and SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox().
int SAMRAI::hier::BoundaryBox::getBoundaryType () const [inline]
Return the boundary type (codimension) of the boundary box.
    * Convention:
    * ===========
    *
    * 1d
    * --
    * 1 = node
    *
    * 2d
    * --
    * 1 = edge
    * 2 = node
    *
    * 3d
    * --
    * 1 = face
    * 2 = edge
    * 3 = node
    *
Returns:
boundary type value
Referenced by SAMRAI::hier::PatchGeometry::getBoundaryFillBox(), SAMRAI::hier::BoundaryBoxUtils::getSurfaceBoxFromBoundaryBox(), and SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox().
int SAMRAI::hier::BoundaryBox::getLocationIndex () const [inline]
Return the location index for the boundary box.
The location index is an integer which indicates the location of the the boundary box in relation to the location of the associated patch. The conventions for the location index depend on the dimension of the problem and the boundary type (codimension) of the BoundaryBox.
    * Conventions:
    * ============
    *
    * 1d
    * --
    * node (codimension 1):
    * x_lo : 0
    * x_hi : 1
    *
    * 2d
    * --
    * edge (codimension 1):
    * x_lo: 0
    * x_hi: 1
    * y_lo: 2
    * y_hi: 3
    *
    * node (codimension 2):
    * x_lo, y_lo: 0
    * x_hi, y_lo: 1
    * x_lo, y_hi: 2
    * x_hi, y_hi: 3
    *
    * 3d
    * --
    *
    * face (codimension 1):
    * x_lo: 0
    * x_hi: 1
    * y_lo: 2
    * y_hi: 3
    * z_lo: 4
    * z_hi: 5
    *
    * edge (codimension 2):
    * x_lo, y_lo: 0
    * x_hi, y_lo: 1
    * x_lo, y_hi: 2
    * x_hi, y_hi: 3
    * x_lo, z_lo: 4
    * x_hi, z_lo: 5
    * x_lo, z_hi: 6
    * x_hi, z_hi: 7
    * y_lo, z_lo: 8
    * y_hi, z_lo: 9
    * y_lo, z_hi: 10
    * y_hi, z_hi: 11
    *
    * node (codimension 3):
    * x_lo, y_lo, z_lo: 0
    * x_hi, y_lo, z_lo: 1
    * x_lo, y_hi, z_lo: 2
    * x_hi, y_hi, z_lo: 3
    * x_lo, y_lo, z_hi: 4
    * x_hi, y_lo, z_hi: 5
    * x_lo, y_hi, z_hi: 6
    * x_hi, y_hi, z_hi: 7
    *
    *
Returns:
The location index
Referenced by SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::hier::PatchGeometry::getBoundaryFillBox(), SAMRAI::hier::BoundaryBoxUtils::getSurfaceBoxFromBoundaryBox(), SAMRAI::hier::BoundaryBoxUtils::normalDir(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs(), SAMRAI::solv::LocationIndexRobinBcCoefs::setBcCoefs(), SAMRAI::solv::GhostCellRobinBcCoefs::setBcCoefs(), and SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox().
void SAMRAI::hier::BoundaryBox::setIsMultiblockSingularity (bool is_mblk_singularity) [inline]
Set the multiblock singularity flag to the argument value.
In multiblock problems, the code setting up multiblock hierarchies and patch levels will set this value to true when creating a BoundaryBox that represents a patch boundary at a multiblock singularity.
Parameters:
[in] is_mblk_singularity
bool SAMRAI::hier::BoundaryBox::getIsMultiblockSingularity () const [inline]
Get the value of the multiblock singularity flag.
Returns:
The singularity flag value.
BoundaryBox& SAMRAI::hier::BoundaryBox::operator= (const BoundaryBox & boundary_box) [inline]
The assignment operator copies all data components.
Parameters:
[in] boundary_box
BoundaryBox::BoundaryOrientation SAMRAI::hier::BoundaryBox::getBoundaryOrientation (const int dir) const
Get which side of a patch the boundary box is on.
Returns BoundaryOrientation value indicating whether the boundary box is on the upper or lower side of the patch in the given coordinate direction, or in the middle (neither upper nor lower).
Returns:
BoundaryOrientation value LOWER, MIDDLE, or UPPER
Parameters:
[in] dir Coordinate direction on which to query
Precondition:
dir < getDim().getValue()
References SAMRAI::hier::BoundaryLookupTable::getLookupTable(), SAMRAI::tbox::Dimension::getValue(), LOWER, MIDDLE, TBOX_ASSERT, and UPPER.
const tbox::Dimension& SAMRAI::hier::BoundaryBox::getDim () const [inline]
Return the dimension of this object.
Returns:
The dimension
Referenced by SAMRAI::hier::BoundaryBoxUtils::extendBoxOutward(), SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth(), and SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoundaryBox.h
source/SAMRAI/hier/BoundaryBox.C