SAMRAI: SAMRAI::algs::MethodOfLinesPatchStrategy Class Reference
SAMRAI::algs::MethodOfLinesPatchStrategy Class Reference
#include <source/SAMRAI/algs/MethodOfLinesPatchStrategy.h>
Public Member Functions
MethodOfLinesPatchStrategy ()
virtual ~MethodOfLinesPatchStrategy ()=0
virtual void registerModelVariables (MethodOfLinesIntegrator *integrator)=0
virtual void initializeDataOnPatch (hier::Patch &patch, const double time, const bool initial_time) const =0
virtual double computeStableDtOnPatch (hier::Patch &patch, const double time) const =0
virtual void singleStep (hier::Patch &patch, const double dt, const double alpha_1, const double alpha_2, const double beta) const =0
virtual void tagGradientDetectorCells (hier::Patch &patch, const double regrid_time, const bool initial_error, const int tag_index, const bool uses_richardson_extrapolation_too)=0
virtual void setPhysicalBoundaryConditions (hier::Patch &patch, const double fill_time, const hier::IntVector &ghost_width_to_fill)=0
boost::shared_ptr
< hier::VariableContext > getInteriorWithGhostsContext () const
boost::shared_ptr
< hier::VariableContext > getInteriorContext () const
void setInteriorWithGhostsContext (const boost::shared_ptr< hier::VariableContext > &context)
void setInteriorContext (const boost::shared_ptr< hier::VariableContext > &context)
Detailed Description
Class MethodOfLinesPatchStrategy is an abstract type defining the interface for operations invoked during the integration routines defined in the MethodOfLinesIntegrator class. This class is derived from the xfer::RefinePatchStrategy and xfer::CoarsenPatchStrategy abstract base classes. These base classes define the interfaces for user-defined interlevel data refining and coarsening operations and the specification of physical boundary conditions.
See also:
algs::MethodOfLinesIntegrator
xfer::RefinePatchStrategy
xfer::CoarsenPatchStrategy
Constructor & Destructor Documentation
SAMRAI::algs::MethodOfLinesPatchStrategy::MethodOfLinesPatchStrategy ()
Blank constructor for MethodOfLinesPatchStrategy.
SAMRAI::algs::MethodOfLinesPatchStrategy::~MethodOfLinesPatchStrategy () [pure virtual]
Virtual destructor for MethodOfLinesPatchStrategy.
Member Function Documentation
virtual void SAMRAI::algs::MethodOfLinesPatchStrategy::registerModelVariables (MethodOfLinesIntegrator * integrator) [pure virtual]
Register variables specific to the problem to be solved with the integrator using the registerVariable function. This defines the way data for each quantity will be manipulated on the patches. For more information, refer to MethodOfLinesIntegrator::registerVariable.
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::initializeIntegrator().
virtual void SAMRAI::algs::MethodOfLinesPatchStrategy::initializeDataOnPatch (hier::Patch & patch, const double time, const bool initial_time) const [pure virtual]
Set the initial data on a patch interior (i.e., NO GHOST CELLS). Setting "initial_time" true will initialize data at time. Setting it false will interpolate data from the appropriate coarser patch.
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::initializeLevelData().
virtual double SAMRAI::algs::MethodOfLinesPatchStrategy::computeStableDtOnPatch (hier::Patch & patch, const double time) const [pure virtual]
Compute the stable time increment for a patch.
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::getTimestep().
virtual void SAMRAI::algs::MethodOfLinesPatchStrategy::singleStep (hier::Patch & patch, const double dt, const double alpha_1, const double alpha_2, const double beta) const [pure virtual]
Advance a single Runge Kutta step.
Parameters:
patch patch that RK step is being applied
dt timestep
alpha_1 first coefficient applied in the RK step
alpha_2 second coefficient
beta third coefficient
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::advanceHierarchy().
virtual void SAMRAI::algs::MethodOfLinesPatchStrategy::tagGradientDetectorCells (hier::Patch & patch, const double regrid_time, const bool initial_error, const int tag_index, const bool uses_richardson_extrapolation_too) [pure virtual]
Using a user-specified gradient detection scheme, determine cells which have high gradients and, consequently, should be refined.
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::applyGradientDetector().
virtual void SAMRAI::algs::MethodOfLinesPatchStrategy::setPhysicalBoundaryConditions (hier::Patch & patch, const double fill_time, const hier::IntVector & ghost_width_to_fill) [pure virtual]
Set user-defined boundary conditions at the physical domain boundary.
Implements SAMRAI::xfer::RefinePatchStrategy.
boost::shared_ptr<hier::VariableContext> SAMRAI::algs::MethodOfLinesPatchStrategy::getInteriorWithGhostsContext () const [inline]
The method of lines integrator controls the context for the data to be used in the numerical routines implemented in the concrete patch strategy. These accessor methods allow the patch strategy to access the particular data contexts used in the integrator.
Return pointer to data context with ghost cells.
boost::shared_ptr<hier::VariableContext> SAMRAI::algs::MethodOfLinesPatchStrategy::getInteriorContext () const [inline]
Return pointer to data context with NO ghosts.
void SAMRAI::algs::MethodOfLinesPatchStrategy::setInteriorWithGhostsContext (const boost::shared_ptr< hier::VariableContext > & context) [inline]
Set pointer to data context with ghosts.
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::MethodOfLinesIntegrator().
void SAMRAI::algs::MethodOfLinesPatchStrategy::setInteriorContext (const boost::shared_ptr< hier::VariableContext > & context) [inline]
Set pointer to data context with NO ghosts.
Referenced by SAMRAI::algs::MethodOfLinesIntegrator::MethodOfLinesIntegrator().
The documentation for this class was generated from the following files:
source/SAMRAI/algs/MethodOfLinesPatchStrategy.h
source/SAMRAI/algs/MethodOfLinesPatchStrategy.C