SAMRAI: SAMRAI::mesh::CascadePartitionerTree Class Reference
SAMRAI::mesh::CascadePartitionerTree Class Reference
A binary-tree of process groups in the CascadePartitioner algorithm. This class is used internally in the CascadePartioner class. It should not be used otherwise.
#include <source/SAMRAI/mesh/CascadePartitionerTree.h>
Public Member Functions
CascadePartitionerTree (const CascadePartitioner &partitioner)
Construct the tree for the given CascadePartitioner by constructing the root and recursively constructing its children.
~CascadePartitionerTree ()
void distributeLoad ()
Distribute the load using the cascade algorithm.
void printClassData (std::ostream &co, const std::string &border) const
int generationNum () const
Generation number (generation 0 contains all ranks).
size_t size () const
Size of group (number of processes in it).
bool containsRank (int rank) const
Whether group contains a given rank.
Detailed Description
A binary-tree of process groups in the CascadePartitioner algorithm. This class is used internally in the CascadePartioner class. It should not be used otherwise.
In cascade partitioner, the MPI ranks are recursively split into groups, forming the nodes of a binary tree. The root branch contains all ranks. The leaves are single-process groups. Each group is represented by a CascadePartitionerTree.
Terminology: The root group includes all ranks. It splits into lower and upper groups (also called branches). The lower branch has the lower ranks. If the group has an odd number of ranks, the upper branch has one rank more than the lower. The branch containing the local process is also known as the "near branch"; the one not containing the local process is the "far branch".
Constructor & Destructor Documentation
SAMRAI::mesh::CascadePartitionerTree::CascadePartitionerTree (const CascadePartitioner & partitioner)
Construct the tree for the given CascadePartitioner by constructing the root and recursively constructing its children.
References SAMRAI::tbox::plog, and printClassData().
SAMRAI::mesh::CascadePartitionerTree::~CascadePartitionerTree ()
Member Function Documentation
void SAMRAI::mesh::CascadePartitionerTree::distributeLoad ()
Distribute the load using the cascade algorithm.
References SAMRAI::mesh::TransitLoad::getSumLoad(), and SAMRAI::tbox::plog.
void SAMRAI::mesh::CascadePartitionerTree::printClassData (std::ostream & co, const std::string & border) const
References SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::mesh::TransitLoad::getSumLoad(), and size().
Referenced by CascadePartitionerTree().
int SAMRAI::mesh::CascadePartitionerTree::generationNum () const [inline]
Generation number (generation 0 contains all ranks).
size_t SAMRAI::mesh::CascadePartitionerTree::size () const [inline]
Size of group (number of processes in it).
Referenced by printClassData().
bool SAMRAI::mesh::CascadePartitionerTree::containsRank (int rank) const [inline]
Whether group contains a given rank.
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/CascadePartitionerTree.h
source/SAMRAI/mesh/CascadePartitionerTree.C