SAMRAI: SAMRAI::hier::BoundaryBoxUtils Class Reference
SAMRAI::hier::BoundaryBoxUtils Class Reference
Perform shifts, extensions, etc on a BoundaryBox using the box's location index and type.
#include <source/SAMRAI/hier/BoundaryBoxUtils.h>
Public Member Functions
BoundaryBoxUtils (const BoundaryBox &bbox)
Construct with a boundary box.
~BoundaryBoxUtils ()
Destructor.
void setBoundaryBox (const BoundaryBox &bbox)
Reset boundary box.
const BoundaryBox & getBoundaryBox () const
Get boundary box.
const IntVector & getOutwardShift () const
Get the outward direction in logical space.
void stretchBoxToGhostWidth (Box &box, const IntVector &ghost_cell_width) const
Stretch box outward by the given ghost cell width.
void extendBoxOutward (Box &box, const IntVector &extension) const
Extend box outward by the given amount.
int normalDir () const
Return the direction normal to the BoundaryBox.
BoundaryBox trimBoundaryBox (const Box &limit_box) const
Trim a boundary box so that it does not stick out past a limiting box in direction transverse to the boundary normal.
Box getSurfaceBoxFromBoundaryBox () const
Return box describing the index space of the outer surface of a boundary box.
Detailed Description
Perform shifts, extensions, etc on a BoundaryBox using the box's location index and type.
See also:
hier::BoundaryBox
Constructor & Destructor Documentation
SAMRAI::hier::BoundaryBoxUtils::BoundaryBoxUtils (const BoundaryBox & bbox) [explicit]
Construct with a boundary box.
Parameters:
[in] bbox boundary box
See also:
setBoundaryBox()
SAMRAI::hier::BoundaryBoxUtils::~BoundaryBoxUtils ()
Destructor.
Member Function Documentation
void SAMRAI::hier::BoundaryBoxUtils::setBoundaryBox (const BoundaryBox & bbox) [inline]
Reset boundary box.
All utility operations refer to this box.
Parameters:
[in] bbox boundary box
const BoundaryBox& SAMRAI::hier::BoundaryBoxUtils::getBoundaryBox () const [inline]
Get boundary box.
Returns:
The boundary box
Referenced by normalDir().
const IntVector& SAMRAI::hier::BoundaryBoxUtils::getOutwardShift () const [inline]
Get the outward direction in logical space.
Each component of the returned outward direction will have one of these values:
-1 if the outward direction is toward the lower indices
0 for the direction is orthogonal to the outward direction.
1 if the outward direction is toward the higher indices
The number of non-zero components should equal the boundary type (codimension).
Returns:
IntVector containing the outward direction values
void SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth (Box & box, const IntVector & ghost_cell_width) const
Stretch box outward by the given ghost cell width.
The number of directions affected is the same as the codimension of the boundary.
Note that the BoundaryBox is defined to be one cell wide. The output of this method is the box held by the BoundaryBox, stretched to cover the given ghost cell width. This means that if ghost_cell_width is one, the output is identical to the BoundaryBox. If the ghost width is zero in any direction, the output will shrink to nothing in that direction.
Parameters:
[out] box The stretched box.
[in] ghost_cell_width Ghost width to stretch the box.
Precondition:
getBoundaryBox().getDim() == box.getDim()
ghost_cell_width >= IntVector::getZero(getBoundaryBox().getDim())
References SAMRAI::hier::BoundaryBox::getBox(), SAMRAI::hier::BoundaryBox::getDim(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Box::growLower(), SAMRAI::hier::Box::growUpper(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::hier::Box::upper().
void SAMRAI::hier::BoundaryBoxUtils::extendBoxOutward (Box & box, const IntVector & extension) const
Extend box outward by the given amount.
The output box is the box held by the BoundaryBox extended outward according to the values in the extension IntVector. If any coordinate direction has a zero value in the IntVector returned by getOutwardShift(), the box will not be extended in that direction. The number of directions that will be extended is equal to the codimension of the BoundaryBox.
Parameters:
[out] box The extended box
[in] extension IntVector telling how many cells to extend the box in each coordinate direction.
Precondition:
getBoundaryBox().getDim() == box.getDim()
References SAMRAI::hier::BoundaryBox::getBox(), SAMRAI::hier::BoundaryBox::getDim(), SAMRAI::hier::Box::growLower(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
int SAMRAI::hier::BoundaryBoxUtils::normalDir () const [inline]
Return the direction normal to the BoundaryBox.
The normal direction is defined only for surface boundaries (codimension 1). A -1 is returned for all other boundary types.
Returns:
The normal direction.
References getBoundaryBox(), and SAMRAI::hier::BoundaryBox::getLocationIndex().
BoundaryBox SAMRAI::hier::BoundaryBoxUtils::trimBoundaryBox (const Box & limit_box) const
Trim a boundary box so that it does not stick out past a limiting box in direction transverse to the boundary normal.
This method affects the only box directions parallel to the boundary. For methods affecting other box directions, see stretchBoxToGhostWidth().
The boundary type of the BoundaryBox that was given to the BoundaryBoxUtils constructor must be less than dim.
Parameters:
[in] limit_box Box to not stick out past
Returns:
New trimmed boundary box.
Precondition:
getBoundaryBox().getDim() == limit_box.getDim()
getBoundaryBox().getBoundaryType() < getBoundaryBox().getDim().getValue())
References SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoundaryBox::getBoundaryType(), SAMRAI::hier::BoundaryBox::getBox(), SAMRAI::hier::BoundaryBox::getDim(), SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::hier::Box::lower(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::hier::Box::upper().
Box SAMRAI::hier::BoundaryBoxUtils::getSurfaceBoxFromBoundaryBox () const
Return box describing the index space of the outer surface of a boundary box.
Define a box describing the indices of the surface of the the input boundary box. A surface is a face in 3D and an edge in 2D. These surfaces lie on the boundary itself.
The input boundary_box must be of type 1 (see hier::BoundaryBox::getBoundaryType()).
This is a utility function for working with the surface indices corresponding to a boundary box.
Returns:
a box to define the side indices corresponding to the BoundaryBox
Precondition:
getBoundaryBox().getBoundaryType() == 1
References SAMRAI::hier::BoundaryBox::getBoundaryType(), SAMRAI::hier::BoundaryBox::getBox(), SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::hier::Box::shift(), and TBOX_ERROR.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoundaryBoxUtils.h
source/SAMRAI/hier/BoundaryBoxUtils.C