SAMRAI: SAMRAI::xfer::PatchLevelEnhancedFillPattern Class Reference
SAMRAI::xfer::PatchLevelEnhancedFillPattern Class Reference
Class PatchLevelEnhancedFillPattern is an implementation of the abstract base class PatchLevelFillPattern.
#include <source/SAMRAI/xfer/PatchLevelEnhancedFillPattern.h>
Public Member Functions
PatchLevelEnhancedFillPattern ()
Default constructor.
virtual ~PatchLevelEnhancedFillPattern ()
Destructor.
void computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > &fill_box_level, boost::shared_ptr< hier::Connector > &dst_to_fill, const hier::BoxLevel &dst_box_level, const hier::IntVector &fill_ghost_width, bool data_on_patch_border)
Compute the boxes representing the region that will be filled by a RefineSchedule.
bool needsToCommunicateDestinationFillBoxes () const
Return true because source patch owner cannot compute fill boxes across block boundaries.
void computeDestinationFillBoxesOnSourceProc (FillSet &dst_fill_boxes_on_src_proc, const hier::BoxLevel &dst_box_level, const hier::Connector &src_to_dst, const hier::IntVector &fill_ghost_width)
Virtual method to compute the destination fill boxes.
bool doesSourceLevelCommunicateToDestination () const
Tell RefineSchedule not to communicate data directly from source to destination level.
int getMaxFillBoxes () const
Return the maximum number of fill boxes.
bool fillingCoarseFineGhosts () const
Returns true because this fill pattern fills coarse fine ghost data.
bool fillingEnhancedConnectivityOnly () const
Returns true because this fill pattern is specialized for enhanced connectivity only.
Detailed Description
Class PatchLevelEnhancedFillPattern is an implementation of the abstract base class PatchLevelFillPattern.
This class is used by the RefineSchedule to restrict filling to only patches in ghost regions across an ehanced connectivity block boundary. It is intended for users who wish to handle the filling of data at these singularities separately from the filling of all other data.
See also:
xfer::RefineSchedule
Constructor & Destructor Documentation
SAMRAI::xfer::PatchLevelEnhancedFillPattern::PatchLevelEnhancedFillPattern ()
Default constructor.
SAMRAI::xfer::PatchLevelEnhancedFillPattern::~PatchLevelEnhancedFillPattern () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > & fill_box_level, boost::shared_ptr< hier::Connector > & dst_to_fill, const hier::BoxLevel & dst_box_level, const hier::IntVector & fill_ghost_width, bool data_on_patch_border) [virtual]
Compute the boxes representing the region that will be filled by a RefineSchedule.
The fill boxes will exist only for destination patches that touch a block boundary at enhanced connectivity. The fill boxes will be the portion of the ghost regions of those patches lying across the enhanced connectivity boundary.
Parameters:
[out] fill_box_level Output BoxLevel to be filled
[out] dst_to_fill Output Connector between dst_box_level and fill_box_level
[in] dst_box_level destination level
[in] fill_ghost_width Ghost width being filled by refine schedule
[in] data_on_patch_border true if there is data living on patch borders
Precondition:
dst_box_level.getDim() == fill_ghost_width.getDim()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::Box::grow(), NULL_USE, SAMRAI::hier::BoxContainer::pushBack(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::xfer::PatchLevelEnhancedFillPattern::needsToCommunicateDestinationFillBoxes () const [virtual]
Return true because source patch owner cannot compute fill boxes across block boundaries.
Returns:
true.
Implements SAMRAI::xfer::PatchLevelFillPattern.
Referenced by computeDestinationFillBoxesOnSourceProc().
void SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeDestinationFillBoxesOnSourceProc (FillSet & dst_fill_boxes_on_src_proc, const hier::BoxLevel & dst_box_level, const hier::Connector & src_to_dst, const hier::IntVector & fill_ghost_width) [virtual]
Virtual method to compute the destination fill boxes.
Since needsToCommunicateDestinationFillBoxes() returns true, this method should never be called. It is implemented here to satisfy the pure virtual interface from the base class. An error will result if this is ever called.
Precondition:
needsToCommunicateDestinationFillBoxes()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References needsToCommunicateDestinationFillBoxes(), NULL_USE, and TBOX_ERROR.
bool SAMRAI::xfer::PatchLevelEnhancedFillPattern::doesSourceLevelCommunicateToDestination () const [virtual]
Tell RefineSchedule not to communicate data directly from source to destination level.
With this fill pattern, the RefineSchedule does not attempt to fill as much of the destination level as possible from the source level at the same level of resolution. By returning 'false', this method tells the RefineSchedule to skip that step.
Returns:
false
Implements SAMRAI::xfer::PatchLevelFillPattern.
int SAMRAI::xfer::PatchLevelEnhancedFillPattern::getMaxFillBoxes () const [virtual]
Return the maximum number of fill boxes.
This will not return a valid value until computeFillBoxesAndNeighborhoodSets is fully implemented. An error will occur if this method is called
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelEnhancedFillPattern::fillingCoarseFineGhosts () const [virtual]
Returns true because this fill pattern fills coarse fine ghost data.
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelEnhancedFillPattern::fillingEnhancedConnectivityOnly () const [virtual]
Returns true because this fill pattern is specialized for enhanced connectivity only.
Implements SAMRAI::xfer::PatchLevelFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/PatchLevelEnhancedFillPattern.h
source/SAMRAI/xfer/PatchLevelEnhancedFillPattern.C