SAMRAI: SAMRAI::solv::NonlinearSolverStrategy Class Reference
SAMRAI::solv::NonlinearSolverStrategy Class Reference
Abstract base class defining interface between an algs::ImplicitIntegrator object and a nonlinear solver used to advance the solution in time.
#include <source/SAMRAI/solv/NonlinearSolverStrategy.h>
Public Member Functions
NonlinearSolverStrategy ()
virtual ~NonlinearSolverStrategy ()
virtual void initialize (const boost::shared_ptr< SAMRAIVectorReal< double > > &solution)=0
virtual int solve ()=0
Detailed Description
Abstract base class defining interface between an algs::ImplicitIntegrator object and a nonlinear solver used to advance the solution in time.
The interface follows the Strategy design pattern. The methods declared in the interface are provided in a concrete solver derived from this base class.
See also:
algs::ImplicitIntegrator
Constructor & Destructor Documentation
SAMRAI::solv::NonlinearSolverStrategy::NonlinearSolverStrategy ()
Empty constructor for algs::NonlinearSolverStrategy.
SAMRAI::solv::NonlinearSolverStrategy::~NonlinearSolverStrategy () [virtual]
Empty constructor for algs::NonlinearSolverStrategy.
Member Function Documentation
virtual void SAMRAI::solv::NonlinearSolverStrategy::initialize (const boost::shared_ptr< SAMRAIVectorReal< double > > & solution) [pure virtual]
Initialize the solver state. The vector argument represents the solution of the nonlinear system. In general, this routine must be called before the solve() routine is invoked.
Implemented in SAMRAI::solv::KINSOL_SAMRAIContext, and SAMRAI::solv::SNES_SAMRAIContext.
Referenced by SAMRAI::algs::ImplicitIntegrator::advanceSolution(), and SAMRAI::algs::ImplicitIntegrator::initialize().
virtual int SAMRAI::solv::NonlinearSolverStrategy::solve () [pure virtual]
Solve the nonlinear problem and return the integer code defined by the particular nonlinear solver package in use (e.g., indicating success or failure of solution process). In general, the initialize() routine must be called before this solve function.
Implemented in SAMRAI::solv::KINSOL_SAMRAIContext, and SAMRAI::solv::SNES_SAMRAIContext.
Referenced by SAMRAI::algs::ImplicitIntegrator::advanceSolution().
The documentation for this class was generated from the following files:
source/SAMRAI/solv/NonlinearSolverStrategy.h
source/SAMRAI/solv/NonlinearSolverStrategy.C