SAMRAI: SAMRAI::pdat::CellDataFactory< TYPE > Class Template Reference
SAMRAI::pdat::CellDataFactory< TYPE > Class Template Reference
#include <source/SAMRAI/pdat/CellDataFactory.h>
Public Member Functions
CellDataFactory (int depth, const hier::IntVector &ghosts)
virtual ~CellDataFactory ()
virtual boost::shared_ptr
< hier::PatchDataFactory > cloneFactory (const hier::IntVector &ghosts)
Abstract virtual function to clone a patch data factory.
virtual boost::shared_ptr
< hier::PatchData > allocate (const hier::Patch &patch) const
virtual boost::shared_ptr
< hier::BoxGeometry > getBoxGeometry (const hier::Box &box) const
int getDepth () const
virtual size_t getSizeOfMemory (const hier::Box &box) const
bool fineBoundaryRepresentsVariable () const
bool dataLivesOnPatchBorder () const
bool validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > &dst_pdf) const
Detailed Description
template<class TYPE>
class SAMRAI::pdat::CellDataFactory< TYPE >
Class CellDataFactory is a factory class used to allocate new instances of CellData objects. It is a subclass of the patch data factory class and cell data is a subclass of patch data. Both the factory and data classes are templated on the type of the contained object (e.g., double or int).
See also:
CellData
PatchDataFactory
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::CellDataFactory< TYPE >::CellDataFactory (int depth, const hier::IntVector & ghosts) [inline]
The default constructor for the cell data factory class. The ghost cell width and depth (number of components) arguments give the defaults for all cell data objects created with this factory.
Precondition:
depth > 0
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), and TBOX_ASSERT.
template<class TYPE > SAMRAI::pdat::CellDataFactory< TYPE >::~CellDataFactory () [inline, virtual]
Virtual destructor for the cell data factory class.
Member Function Documentation
template<class TYPE > boost::shared_ptr< hier::PatchDataFactory > SAMRAI::pdat::CellDataFactory< TYPE >::cloneFactory (const hier::IntVector & ghosts) [inline, virtual]
Abstract virtual function to clone a patch data factory.
This will return a new instantiation of the abstract factory with the same properties. The properties of the cloned factory can then be changed without modifying the original.
Parameters:
ghosts default ghost cell width for concrete classes created from the factory.
Precondition:
getDim() == ghosts.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::PatchData > SAMRAI::pdat::CellDataFactory< TYPE >::allocate (const hier::Patch & patch) const [inline, virtual]
Virtual factory function to allocate a concrete cell data object. The default information about the object (e.g., ghost cell width) is taken from the factory.
Precondition:
getDim() == patch.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::PatchDataFactory::d_ghosts, SAMRAI::hier::Patch::getBox(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::BoxGeometry > SAMRAI::pdat::CellDataFactory< TYPE >::getBoxGeometry (const hier::Box & box) const [inline, virtual]
Allocate the box geometry object associated with the patch data. This information will be used in the computation of intersections and data dependencies between objects.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::PatchDataFactory::d_ghosts, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > int SAMRAI::pdat::CellDataFactory< TYPE >::getDepth () const [inline]
Get the depth (number of components). This is the depth that will be used in the instantiation of cell data objects.
template<class TYPE > size_t SAMRAI::pdat::CellDataFactory< TYPE >::getSizeOfMemory (const hier::Box & box) const [inline, virtual]
Calculate the amount of memory needed to store the cell data object, including object data and dynamically allocated data.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::tbox::MemoryUtilities::align(), SAMRAI::hier::PatchDataFactory::d_ghosts, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::CellDataFactory< TYPE >::fineBoundaryRepresentsVariable () const [inline, virtual]
Return a boolean true value indicating that the cell data quantities will always be treated as though fine values represent them on coarse-fine interfaces. See the CellVariable<TYPE> class header file for more information.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::CellDataFactory< TYPE >::dataLivesOnPatchBorder () const [inline, virtual]
Return false since the cell data index space matches the cell-centered index space for AMR patches. Thus, cell data does not live on patch borders.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::CellDataFactory< TYPE >::validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > & dst_pdf) const [inline]
Return whether it is valid to copy this CellDataFactory to the supplied destination patch data factory. It will return true if dst_pdf is a CellDataFactory, false otherwise.
Precondition:
getDim() == dst_pdf->getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/CellDataFactory.h
source/SAMRAI/pdat/CellDataFactory.C