SAMRAI: SAMRAI::hier::FlattenedHierarchy Class Reference
SAMRAI::hier::FlattenedHierarchy Class Reference
A flattened representation of a hierarchy.
#include <source/SAMRAI/hier/FlattenedHierarchy.h>
Public Member Functions
FlattenedHierarchy (const PatchHierarchy &hierarchy, int coarsest_level, int finest_level)
Constructor of FlattenedHierarchy.
~FlattenedHierarchy ()
Destructor.
int getCoarsestLevelNumber () const
Get the coarsest level number represented by this object.
int getFinestLevelNumber () const
Get the finest level number represented by this object.
const BoxContainer & getVisibleBoxes (const Box &box, int ln) const
Get the visible boxes for a given Box.
const PatchHierarchy & getPatchHierarchy () const
UncoveredBoxIterator beginUncovered ()
Returns an iterator to the first uncovered Box in this hierarchy.
UncoveredBoxIterator endUncovered ()
Returns an iterator to the last uncovered Box in this hierarchy.
Detailed Description
A flattened representation of a hierarchy.
Class FlattenedHierarchy provides a way to view a PatchHierarchy or a subset of levels of PatchHierarchy in a "flattened" representation. In this representation, only the finest existing mesh is visible at any given location in the problem space.
For any Patch in a PatchHierarchy, an associated container of visible boxes is created. If the Patch has no Patches from a finer level covering any of its index space, then the container will simply hold a box that is spatially equivalent to the Patch itself. If the Patch's index space is entirely covered by Patches on a finer level, the container will be empty. If the Patch's index space is partially covered by a finer level, then the container will hold boxes that compose the uncovered parts of the Patch.
Constructor & Destructor Documentation
SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy (const PatchHierarchy & hierarchy, int coarsest_level, int finest_level)
Constructor of FlattenedHierarchy.
A FlattenedHierarchy is constructed based on the given PatchHierarchy and a range of levels. The range of levels may include the entire hierarchy or a subset of its levels. Any levels outside of the given range will be treated by this class as if they do not exist.
If the coarsest and finest level numbers are equal, the flattened representation will be equivalent to the boxes of the level.
Parameters:
hierarchy PatchHierarchy that will be represented
coarsest_level The coarsest level that will be used
finest_level The finest level that will be used
Precondition:
coarsest_level >= 0;
coarsest_level <= finest_level
finest_level < hierarchy->getNumberOfLevels()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coalesce(), SAMRAI::hier::BoxContainer::coarsen(), SAMRAI::hier::CONNECTOR_IMPLICIT_CREATION_RULE, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::PatchHierarchy::getDim(), SAMRAI::hier::Connector::getNeighborBoxes(), SAMRAI::hier::PatchHierarchy::getNumberOfLevels(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::hier::PatchHierarchy::getPatchLevel(), SAMRAI::hier::Connector::getRatio(), SAMRAI::hier::Connector::hasNeighborSet(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::BoxContainer::pushBack(), SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), SAMRAI::hier::BoxContainer::removeIntersections(), and TBOX_ASSERT.
SAMRAI::hier::FlattenedHierarchy::~FlattenedHierarchy ()
Destructor.
Member Function Documentation
int SAMRAI::hier::FlattenedHierarchy::getCoarsestLevelNumber () const [inline]
Get the coarsest level number represented by this object.
int SAMRAI::hier::FlattenedHierarchy::getFinestLevelNumber () const [inline]
Get the finest level number represented by this object.
const BoxContainer& SAMRAI::hier::FlattenedHierarchy::getVisibleBoxes (const Box & box, int ln) const [inline]
Get the visible boxes for a given Box.
The visible boxes represent the parts of the Box that cover space that is not covered by finer levels in the hierarchy. If the entire index space of the Box is covered by a finer level, the returned BoxContainer will be empty.
Parameters:
box The Box for a local patch on the PatchLevel having level number ln.
ln Level number of the box's level of resolution
Precondition:
ln <= d_finest_level && ln >= d_coarsest_level
References SAMRAI::hier::Box::getBoxId(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::UncoveredBoxIterator::operator=(), and SAMRAI::hier::UncoveredBoxIterator::UncoveredBoxIterator().
const PatchHierarchy& SAMRAI::hier::FlattenedHierarchy::getPatchHierarchy () const [inline]
UncoveredBoxIterator SAMRAI::hier::FlattenedHierarchy::beginUncovered () [inline]
Returns an iterator to the first uncovered Box in this hierarchy.
UncoveredBoxIterator SAMRAI::hier::FlattenedHierarchy::endUncovered () [inline]
Returns an iterator to the last uncovered Box in this hierarchy.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/FlattenedHierarchy.h
source/SAMRAI/hier/FlattenedHierarchy.C