SAMRAI: SAMRAI::pdat::OuteredgeDataFactory< TYPE > Class Template Reference
SAMRAI::pdat::OuteredgeDataFactory< TYPE > Class Template Reference
Class OuteredgeDataFactory<TYPE> is a factory class used to allocate new instances of OuteredgeData<TYPE> objects. It is a subclass of the patch data factory class and outeredge data is a subclass of patch data. Both the factory and data classes are templated on the type of the contained object (e.g., double or int).
#include <source/SAMRAI/pdat/OuteredgeDataFactory.h>
Public Member Functions
OuteredgeDataFactory (const tbox::Dimension &dim, int depth)
The default constructor for the outeredge data factory class.
virtual ~OuteredgeDataFactory ()
Virtual destructor for the outeredge data factory class.
virtual boost::shared_ptr
< hier::PatchDataFactory > cloneFactory (const hier::IntVector &ghosts)
Abstract virtual function to clone a patch data factory.
virtual boost::shared_ptr
< hier::PatchData > allocate (const hier::Patch &patch) const
Virtual factory function to allocate a concrete outeredge data object.
virtual boost::shared_ptr
< hier::BoxGeometry > getBoxGeometry (const hier::Box &box) const
Allocate the box geometry object associated with the patch data.
int getDepth () const
Get the depth (number of components).
virtual size_t getSizeOfMemory (const hier::Box &box) const
Calculate the amount of memory needed to store the outeredge data object, including object data and dynamically allocated data.
bool fineBoundaryRepresentsVariable () const
bool dataLivesOnPatchBorder () const
bool validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > &dst_pdf) const
Detailed Description
template<class TYPE>
class SAMRAI::pdat::OuteredgeDataFactory< TYPE >
Class OuteredgeDataFactory<TYPE> is a factory class used to allocate new instances of OuteredgeData<TYPE> objects. It is a subclass of the patch data factory class and outeredge data is a subclass of patch data. Both the factory and data classes are templated on the type of the contained object (e.g., double or int).
See also:
pdat::OuteredgeData
pdat::PatchDataFactory
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::OuteredgeDataFactory< TYPE >::OuteredgeDataFactory (const tbox::Dimension & dim, int depth) [inline]
The default constructor for the outeredge data factory class.
The depth (number of components) gives the default for all of the outeredge data objects created with this factory.
Precondition:
depth > 0
References TBOX_ASSERT.
template<class TYPE > SAMRAI::pdat::OuteredgeDataFactory< TYPE >::~OuteredgeDataFactory () [inline, virtual]
Virtual destructor for the outeredge data factory class.
Member Function Documentation
template<class TYPE > boost::shared_ptr< hier::PatchDataFactory > SAMRAI::pdat::OuteredgeDataFactory< TYPE >::cloneFactory (const hier::IntVector & ghosts) [inline, virtual]
Abstract virtual function to clone a patch data factory.
This will return a new instantiation of the abstract factory with the same properties. The properties of the cloned factory can then be changed without modifying the original.
Parameters:
ghosts default ghost cell width for concrete classes created from the factory.
Precondition:
getDim() == ghosts.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::IntVector::getDim(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::PatchData > SAMRAI::pdat::OuteredgeDataFactory< TYPE >::allocate (const hier::Patch & patch) const [inline, virtual]
Virtual factory function to allocate a concrete outeredge data object.
The default information about the object (e.g., depth) is taken from the factory.
Precondition:
getDim() == patch.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::Patch::getBox(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::BoxGeometry > SAMRAI::pdat::OuteredgeDataFactory< TYPE >::getBoxGeometry (const hier::Box & box) const [inline, virtual]
Allocate the box geometry object associated with the patch data.
This information will be used in the computation of intersections and data dependencies between objects.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::PatchDataFactory::getDim(), SAMRAI::hier::IntVector::getZero(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > int SAMRAI::pdat::OuteredgeDataFactory< TYPE >::getDepth () const [inline]
Get the depth (number of components).
This is the depth that will be used in the instantiation of outeredge data objects.
template<class TYPE > size_t SAMRAI::pdat::OuteredgeDataFactory< TYPE >::getSizeOfMemory (const hier::Box & box) const [inline, virtual]
Calculate the amount of memory needed to store the outeredge data object, including object data and dynamically allocated data.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::tbox::MemoryUtilities::align(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::OuteredgeDataFactory< TYPE >::fineBoundaryRepresentsVariable () const [inline, virtual]
Return a boolean true value indicating that fine data for the outeredge quantity will take precedence on coarse-fine interfaces. See the OuteredgeVariable<TYPE> class header file for more information.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::OuteredgeDataFactory< TYPE >::dataLivesOnPatchBorder () const [inline, virtual]
Return true since the outeredge data index space extends beyond the interior of patches. That is, outeredge data lives on patch borders.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::OuteredgeDataFactory< TYPE >::validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > & dst_pdf) const [inline]
Return whether it is valid to copy this OuteredgeDataFactory to the supplied destination patch data factory. It will return true if dst_pdf is EdgeDataFactory or OuteredgeDataFactory, false otherwise.
Precondition:
getDim() == dst_pdf->getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OuteredgeDataFactory.h
source/SAMRAI/pdat/OuteredgeDataFactory.C