SAMRAI: SAMRAI::math::PatchEdgeDataOpsComplex Class Reference
SAMRAI::math::PatchEdgeDataOpsComplex Class Reference
#include <source/SAMRAI/math/PatchEdgeDataOpsComplex.h>
Public Member Functions
PatchEdgeDataOpsComplex ()
virtual ~PatchEdgeDataOpsComplex ()
void copyData (const boost::shared_ptr< pdat::EdgeData< dcomplex > > &dst, const boost::shared_ptr< pdat::EdgeData< dcomplex > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::EdgeData< dcomplex > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::EdgeData< dcomplex > > &dst, const dcomplex &alpha, const hier::Box &box) const
Detailed Description
Class PatchEdgeDataOpsComplex provides a collection of operations that may be used to manipulate complex edge-centered patch data. The operations include basic arithmetic and norms. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base classes PatchEdgeDataBasicOps, PatchEdgeDataNormOpsComplex from which it is derived. The name of each of these base classes is indicative of the set of edge-centered patch data operations that it provides.
A similar set of operations is implemented for real (double and float) and integer patch data in the classes PatchEdgeDataOpsReal and PatchEdgeDataOpsInteger, repsectively.
See also:
math::PatchEdgeDataBasicOps
math::PatchEdgeDataNormOpsComplex
Constructor & Destructor Documentation
SAMRAI::math::PatchEdgeDataOpsComplex::PatchEdgeDataOpsComplex ()
Empty constructor and destructor.
SAMRAI::math::PatchEdgeDataOpsComplex::~PatchEdgeDataOpsComplex () [virtual]
Member Function Documentation
void SAMRAI::math::PatchEdgeDataOpsComplex::copyData (const boost::shared_ptr< pdat::EdgeData< dcomplex > > & dst, const boost::shared_ptr< pdat::EdgeData< dcomplex > > & src, const hier::Box & box) const
Copy dst data to src data over given box.
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::EdgeGeometry::toEdgeBox().
Referenced by SAMRAI::math::HierarchyEdgeDataOpsComplex::copyData().
void SAMRAI::math::PatchEdgeDataOpsComplex::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::EdgeData<dcomplex> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::EdgeData<dcomplex> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyEdgeDataOpsComplex::swapData().
void SAMRAI::math::PatchEdgeDataOpsComplex::printData (const boost::shared_ptr< pdat::EdgeData< dcomplex > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyEdgeDataOpsComplex::printData().
void SAMRAI::math::PatchEdgeDataOpsComplex::setToScalar (const boost::shared_ptr< pdat::EdgeData< dcomplex > > & dst, const dcomplex & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyEdgeDataOpsComplex::setToScalar().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchEdgeDataOpsComplex.h
source/SAMRAI/math/PatchEdgeDataOpsComplex.C