SAMRAI: SAMRAI::tbox::TimerManager Class Reference
SAMRAI::tbox::TimerManager Class Reference
#include <source/SAMRAI/tbox/TimerManager.h>
Public Member Functions
boost::shared_ptr< Timer > getTimer (const std::string &name, bool ignore_timer_input=false)
bool checkTimerExists (boost::shared_ptr< Timer > &timer, const std::string &name) const
bool checkTimerRunning (const std::string &name) const
void resetAllTimers ()
void print (std::ostream &os=plog)
Static Public Member Functions
static void createManager (const boost::shared_ptr< Database > &input_db=boost::shared_ptr< Database >())
static TimerManager * getManager ()
Protected Member Functions
TimerManager (const boost::shared_ptr< Database > &input_db=boost::shared_ptr< Database >())
~TimerManager ()
void registerSingletonSubclassInstance (TimerManager *subclass_instance)
void startTime (Timer *timer)
void stopTime (Timer *timer)
Friends
class Timer
Detailed Description
Class TimerManager is a Singleton class that manages a list of timer objects to do performance analysis in SAMRAI library modules and application codes built with SAMRAI.
Typically, entries in the input file guide timer invocation and output generation. Within the source code, timer objects are retrieved as follows:
boost::shared_ptr<Timer> name_timer = TimerManager::getManager->getTimer("name");
Here `name' is the name string identifier for the timer.
Input Parameters
Definitions:
print_exclusive Specifies whether to track and print exclusive times. Exclusive times are convenient for identifying time spent inside nested routines. This option should be used with some discretion because the extra overhead to manage the nested list of timers is between four and seven times more expensive than doing simple start/stop operations (as is done with the print_total option). For this reason, we leave it off by default.
print_total Specifies whether to print total (i.e. non-nested) time. This is the least expensive way to time parts of the code. The overhead associated with each start/stop sequence is about one-half a millionth of a second.
print_processor Print times measured on individual processors.
print_max Print maximum time spent on any processor, and the processor ID that incurred the time.
print_summed Print time summed across all processors.
print_user Print user time (measured by system clock).
print_sys Print system time (measured by system clock).
print_wall Print wallclock time.
print_percentage Prints the percentage of total time with each timer.
print_concurrent Prints the concurrent timer tree, as determined during exclusive timing. That is, for each timer, it prints the list of names of the timers in nested routines it calls.
print_timer_overhead Prints some overhead stats associated with the timers. Information like the number of times a start/stop sequence was called for the timer, and the predicted overhead time associated with the timer. This is a convenient option to occasionally check to make sure the timers themselves are not affecting the performance of your calculation.
print_threshold Timers that use up less than (print_threshold) percent of the overall run time are not printed. This can be a convenient option to limit output if you have many timers invoked.
timer_list List of timers to be invoked. The timers can be listed individually in package::class::method format or the entries may contain wildcards to turn on a set of timers in a given package or class:
timer_list = "pkg1::*::*", "pkg2::class2::*", ...
Details:
parameter
type
default
range
opt/req
behavior on restart
print_exclusive
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_total
bool
TRUE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_processor
bool
TRUE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_max
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_summed
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_user
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_sys
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_wall
bool
TRUE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_percentage
bool
TRUE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_concurrent
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_timer_overhead
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
print_threshold
double
0.25
any double
opt
Not written to restart. Value in input db used.
timer_list
array of strings
none
N/A
opt
Not written to restart. Value in input db used.
A sample input file entry might look like:
    print_exclusive      = TRUE <br>
    print_timer_overhead = TRUE <br>
    timer_list = "algs::HyperbolicLevelIntegrator::advanceLevel()", <br>
                 "mesh::GriddingAlgorithm::*", <br>
                 "xfer::*::*" <br>
TimerManager expects timer names to be in a certain format to preserve the wildcard naming capability (i.e. to turn on entire package or class of timers). See the PDF document in /SAMRAI/docs/userdocs/Timing-Instrumentation.pdf for a discussion of how to add timers that maintain this format as well as a catalog of available timers currently implemented in the library.
Timing recursive function calls will yeild erroneous results and may lead to memory problems. We recommend {not to use timers to time recursive function calls}.
See also:
tbox::Timer
Constructor & Destructor Documentation
SAMRAI::tbox::TimerManager::TimerManager (const boost::shared_ptr< Database > & input_db = boost::shared_ptr<Database>()) [explicit, protected]
The constructor for TimerManager is protected. Consistent with the definition of a Singleton class, only a timer manager object can have access to the constructor for the class.
SAMRAI::tbox::TimerManager::~TimerManager () [protected]
TimerManager is a Singleton class; its destructor is protected.
Member Function Documentation
void SAMRAI::tbox::TimerManager::createManager (const boost::shared_ptr< Database > & input_db = boost::shared_ptr<Database>()) [static]
Create the singleton instance of the timer manager. If the input database pointer is null, no information will be read from the input file.
Generally, this routine should only be called once during program execution. If the timer manager has been previously created (e.g., by an earlier call to this routine) the rules for activating timers in the input_db will be applied to the existing timers.
Referenced by getManager().
TimerManager * SAMRAI::tbox::TimerManager::getManager () [static]
Return a pointer to the singleton instance of the timer manager. All access to the TimerManager object is through the getManager() function. For example, to add a timer with the name "my_timer" to the timer manager, use the following call: TimerManager::getManager()->addTimer("my_timer").
References createManager(), and TBOX_WARNING.
Referenced by SAMRAI::pdat::CellData< TYPE >::CellData(), SAMRAI::solv::FACPreconditioner::FACPreconditioner(), SAMRAI::solv::GhostCellRobinBcCoefs::GhostCellRobinBcCoefs(), SAMRAI::mesh::TileClustering::setTimerPrefix(), SAMRAI::mesh::BergerRigoutsos::setTimerPrefix(), SAMRAI::solv::SimpleCellRobinBcCoefs::SimpleCellRobinBcCoefs(), SAMRAI::tbox::Timer::start(), and SAMRAI::tbox::Timer::stop().
boost::shared_ptr< Timer > SAMRAI::tbox::TimerManager::getTimer (const std::string & name, bool ignore_timer_input = false)
Return pointer to timer object with the given name string. If a timer with the given name already appears in the database of timers, the timer with that name will be returned. Otherwise, a new timer will be created with that name. Typically, only a timer specified (to be turned on) in the input file will be active. Timer names are parsed according to the input data parsing criteria (described at the top of this class header). One may override this functionality by adding the timer with a `true' argument. This argument allows one to override the input file criteria and turn the timer on anyway.
Precondition:
!name.empty()
References TBOX_ASSERT, and Timer.
Referenced by SAMRAI::mesh::TileClustering::setTimerPrefix().
bool SAMRAI::tbox::TimerManager::checkTimerExists (boost::shared_ptr< Timer > & timer, const std::string & name) const
Return true if a timer whose name matches the argument string exists in the database of timers controlled by the manager. If a match is found, the timer pointer in the argument list is set to that timer. Otherwise, return false and return a null pointer.
Precondition:
!name.empty()
References TBOX_ASSERT.
bool SAMRAI::tbox::TimerManager::checkTimerRunning (const std::string & name) const
Return true if a timer whose name matches the argument string exists in the database of timers and is currently running. Otherwise, return false.
Precondition:
!name.empty()
References TBOX_ASSERT.
void SAMRAI::tbox::TimerManager::resetAllTimers ()
Reset the times in all timers to zero.
void SAMRAI::tbox::TimerManager::print (std::ostream & os = plog)
Print the timing statistics to the specified output stream.
References SAMRAI::tbox::SAMRAI_MPI::getRank(), and SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld().
void SAMRAI::tbox::TimerManager::registerSingletonSubclassInstance (TimerManager * subclass_instance) [protected]
Initialize Singleton instance with instance of subclass. This function is used to make the singleton object unique when inheriting from this base class.
Precondition:
!s_timer_manager_instance
References TBOX_ERROR.
void SAMRAI::tbox::TimerManager::startTime (Timer * timer) [protected]
Mark given timer as running in timer database. If exclusive time option is set, start exclusive time for given timer. Also stop exclusive time for timer on top of exclusive timer stack and push given timer on to that stack.
Precondition:
timer != 0
References SAMRAI::tbox::Timer::isActive(), SAMRAI::tbox::Timer::startExclusive(), and TBOX_ASSERT.
Referenced by SAMRAI::tbox::Timer::start().
void SAMRAI::tbox::TimerManager::stopTime (Timer * timer) [protected]
Mark given timer as not running in timer database. If exclusive time option is set, stop exclusive time for given timer. Also, pop timer off top of exclusive timer stack and start exclusive timer for new top of stack timer.
Precondition:
timer != 0
References SAMRAI::tbox::Timer::stopExclusive(), and TBOX_ASSERT.
Referenced by SAMRAI::tbox::Timer::stop().
Friends And Related Function Documentation
friend class Timer [friend]
Referenced by getTimer().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/TimerManager.h
source/SAMRAI/tbox/TimerManager.C