SAMRAI: SAMRAI::xfer::CoarsenClasses Class Reference
SAMRAI::xfer::CoarsenClasses Class Reference
Maintain a collection of coarsen items and organize them into equivalence classes.
#include <source/SAMRAI/xfer/CoarsenClasses.h>
Classes
class Data
Nested class used to describe a coarsening operation between patch data components on an AMR hierarchy.
Public Member Functions
CoarsenClasses ()
The default constructor creates an empty array of coarsen classes.
~CoarsenClasses ()
The destructor destroys the coarsen data items owned by this object.
int getNumberOfEquivalenceClasses () const
int getNumberOfCoarsenItems () const
Return total number of coarsen items that have been registered and stored in the CoarsenClasses object.
const CoarsenClasses::Data & getClassRepresentative (int equiv_class_index) const
Get representative item for a given equivalence class index.
CoarsenClasses::Data & getCoarsenItem (const int coarsen_item_array_id)
Get a coarsen item from the array of all coarsen items held by this object.
std::list< int >::iterator getIterator (int equiv_class_index)
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
std::list< int >::iterator getIteratorEnd (int equiv_class_index)
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
void insertEquivalenceClassItem (CoarsenClasses::Data &data, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >())
Given a CoarsenClasses::Data object, insert it into the proper equivalence class.
bool itemIsValid (const CoarsenClasses::Data &data_item, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >()) const
Check coarsen data item for validity.
bool classesMatch (const boost::shared_ptr< CoarsenClasses > &test_classes, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >()) const
Compare CoarsenClasses object with another CoarsenClasses object; return true if they match, else false.
bool itemsAreEquivalent (const CoarsenClasses::Data &data1, const CoarsenClasses::Data &data2, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >()) const
Compare CoarsenClasses::Data objects for equivalence; return true if equivalent, else false.
int getCoarsenItemArraySize () const
Get the size that has been allocated for the array storing coarsen items.
void increaseCoarsenItemArraySize (const int size, const tbox::Dimension &dim)
Increase the allocated size of the array storing coarsen items.
void printClassData (std::ostream &stream) const
Print data for all coarsen items to the specified output stream.
void printCoarsenItem (std::ostream &stream, const CoarsenClasses::Data &data) const
Print single coarsen item to the specified output stream.
Detailed Description
Maintain a collection of coarsen items and organize them into equivalence classes.
CoarsenClasses is used by the CoarsenSchedule and CoarsenAlgorithm classes to manage coarsen data items that describe coarsening of patch data between two levels in an AMR hierarchy. Specifically, this class organizes these items into equivalence clases, so that items are grouped together if they have the same data communication dependencies. See documentation for the method itemsAreEquivalent() for definition of equivalence.
Constructor & Destructor Documentation
SAMRAI::xfer::CoarsenClasses::CoarsenClasses ()
The default constructor creates an empty array of coarsen classes.
SAMRAI::xfer::CoarsenClasses::~CoarsenClasses ()
The destructor destroys the coarsen data items owned by this object.
Member Function Documentation
int SAMRAI::xfer::CoarsenClasses::getNumberOfEquivalenceClasses () const [inline]
Return number of equivalence classes maintained by this object.
Referenced by classesMatch(), getClassRepresentative(), getIterator(), and getIteratorEnd().
int SAMRAI::xfer::CoarsenClasses::getNumberOfCoarsenItems () const [inline]
Return total number of coarsen items that have been registered and stored in the CoarsenClasses object.
const CoarsenClasses::Data& SAMRAI::xfer::CoarsenClasses::getClassRepresentative (int equiv_class_index) const [inline]
Get representative item for a given equivalence class index.
Returns:
Given an index of an existing equivalence class, one item from that class is returned.
Parameters:
[in] equiv_class_index
Precondition:
(equiv_class_index >= 0) && (equiv_class_index < getNumberOfEquivalenceClasses())
References getNumberOfEquivalenceClasses(), and TBOX_ASSERT.
Referenced by classesMatch().
CoarsenClasses::Data& SAMRAI::xfer::CoarsenClasses::getCoarsenItem (const int coarsen_item_array_id) [inline]
Get a coarsen item from the array of all coarsen items held by this object.
The internal storage of the coarsen items held by this class is not controlled by the user, so this method is intended for use when looping over all of the items, from 0 to getNumberOfCoarsenItems()-1, or when looping over the integers in the List obtained from getIterator().
Returns:
A coarsen classes data object identified by an integer id.
Parameters:
[in] coarsen_item_array_id
std::list<int>::iterator SAMRAI::xfer::CoarsenClasses::getIterator (int equiv_class_index) [inline]
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
The number of quivalence classes can be determined via the getNumberOfEquivalenceClasses() member function. Valid integer arguments are from 0 to getNumberOfEquivalenceClasses()-1.
Note:
The list should not be modified through this iterator.
Returns:
The iterator iterates over a list of integers which are array ids that can be passed into getCoarsenItem(). The array ids in a single list all correspond to coarsen items in a single equivalence class.
Parameters:
[in] equiv_class_index
Precondition:
(equiv_class_index >= 0) && (equiv_class_index < getNumberOfEquivalenceClasses())
References getNumberOfEquivalenceClasses(), and TBOX_ASSERT.
std::list<int>::iterator SAMRAI::xfer::CoarsenClasses::getIteratorEnd (int equiv_class_index) [inline]
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
The number of quivalence classes can be determined via the getNumberOfEquivalenceClasses() member function. Valid integer arguments are from 0 to getNumberOfEquivalenceClasses()-1.
Note:
The list should not be modified through this iterator.
Returns:
The iterator iterates over a list of integers which are array ids that can be passed into getCoarsenItem(). The array ids in a single list all correspond to coarsen items in a single equivalence class.
Parameters:
[in] equiv_class_index
Precondition:
(equiv_class_index >= 0) && (equiv_class_index < getNumberOfEquivalenceClasses())
References getNumberOfEquivalenceClasses(), and TBOX_ASSERT.
void SAMRAI::xfer::CoarsenClasses::insertEquivalenceClassItem (CoarsenClasses::Data & data, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>())
Given a CoarsenClasses::Data object, insert it into the proper equivalence class.
If the item belongs in an existing equivalence class, it will be added to that class. Otherwise, a new equivalence class will be created for this item. The integer class index in the data item will set to the index of the equivalence class into which it is inserted.
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Parameters:
[in,out] data
[in] descriptor
Precondition:
itemIsValid(data, descriptor)
References SAMRAI::xfer::CoarsenClasses::Data::d_class_index, SAMRAI::xfer::CoarsenClasses::Data::d_gcw_to_coarsen, SAMRAI::hier::IntVector::getDim(), itemIsValid(), SAMRAI::tbox::perr, printCoarsenItem(), and TBOX_ERROR.
bool SAMRAI::xfer::CoarsenClasses::itemIsValid (const CoarsenClasses::Data & data_item, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>()) const
Check coarsen data item for validity.
A coarsen data item is invalid if any of its patch data ids are negative, or if its source data does not have sufficient ghost width for the stencil of the coarsen operator, or if copying from the source to the destination data is not valid.
An error will occur with a descriptive message if the item is invalid.
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Returns:
True if the item is valid; else false.
Parameters:
[in] data_item
[in] descriptor
References SAMRAI::xfer::CoarsenClasses::Data::d_dst, SAMRAI::xfer::CoarsenClasses::Data::d_opcoarsen, SAMRAI::xfer::CoarsenClasses::Data::d_src, SAMRAI::hier::VariableDatabase::getDatabase(), and TBOX_ERROR.
Referenced by insertEquivalenceClassItem().
bool SAMRAI::xfer::CoarsenClasses::classesMatch (const boost::shared_ptr< CoarsenClasses > & test_classes, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>()) const
Compare CoarsenClasses object with another CoarsenClasses object; return true if they match, else false.
This method checks whether all equivalence classes match between this CoarsenClasses object and the argument object. To match, the number of equivalence classes held by the objects must be the same and each equivalence class in this object must match the class with the same equivalence class number in the argument object. Two classes match if they have the same number of items and their representative items are equialvent as defined by the method itemsAreEquivalent().
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Returns:
true if test_classes matches this object.
Parameters:
[in] test_classes CoarsenClasses object to compare with this.
[in] descriptor
References getClassRepresentative(), getNumberOfEquivalenceClasses(), itemsAreEquivalent(), and NULL_USE.
bool SAMRAI::xfer::CoarsenClasses::itemsAreEquivalent (const CoarsenClasses::Data & data1, const CoarsenClasses::Data & data2, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>()) const
Compare CoarsenClasses::Data objects for equivalence; return true if equivalent, else false.
Two CoarsenClasses::Data objects are equivalent if and only if the following conditions hold:
Each corresponding patch data component (d_dst and d_src) must have the same patch data type and ghost cell width.
d_fine_bdry_reps_var flag must have the same value for each object.
The coarsening operator ptr d_opcoarsen must be null or non-null for both objects. If non-null, both operators must have the same stencil width.
The same variable fill pattern is used.
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Returns:
true if test_classes matches this object.
Parameters:
[in] data1 CoarsenClasses::Data object to compare.
[in] data2 CoarsenClasses::Data object to compare.
[in] descriptor
References SAMRAI::xfer::CoarsenClasses::Data::d_dst, SAMRAI::xfer::CoarsenClasses::Data::d_fine_bdry_reps_var, SAMRAI::xfer::CoarsenClasses::Data::d_gcw_to_coarsen, SAMRAI::xfer::CoarsenClasses::Data::d_opcoarsen, SAMRAI::xfer::CoarsenClasses::Data::d_src, SAMRAI::xfer::CoarsenClasses::Data::d_var_fill_pattern, and SAMRAI::hier::VariableDatabase::getDatabase().
Referenced by classesMatch().
int SAMRAI::xfer::CoarsenClasses::getCoarsenItemArraySize () const [inline]
Get the size that has been allocated for the array storing coarsen items.
Note that this is not necessarily the same as the number of registered coarsen items, which can be retrieved using getNumberOfCoarsenItems(). The coarsen item array is allocated to a default size and grown when necessary or when increaseCoarsenItemArraySize() is called.
void SAMRAI::xfer::CoarsenClasses::increaseCoarsenItemArraySize (const int size, const tbox::Dimension & dim) [inline]
Increase the allocated size of the array storing coarsen items.
This should be used in cases where there is a large number of coarsen items being registered with the CoarsenAlgorithm, to avoid frequent resizing of the array. If the size argument is less than the current allocated size of the array, then the size of the array is not changed.
Parameters:
[in] size
[in] dim
void SAMRAI::xfer::CoarsenClasses::printClassData (std::ostream & stream) const
Print data for all coarsen items to the specified output stream.
Parameters:
[out] stream
References printCoarsenItem().
void SAMRAI::xfer::CoarsenClasses::printCoarsenItem (std::ostream & stream, const CoarsenClasses::Data & data) const
Print single coarsen item to the specified output stream.
Parameters:
[out] stream
[in] data
References SAMRAI::xfer::CoarsenClasses::Data::d_dst, SAMRAI::xfer::CoarsenClasses::Data::d_fine_bdry_reps_var, SAMRAI::xfer::CoarsenClasses::Data::d_gcw_to_coarsen, SAMRAI::xfer::CoarsenClasses::Data::d_opcoarsen, SAMRAI::xfer::CoarsenClasses::Data::d_src, SAMRAI::xfer::CoarsenClasses::Data::d_tag, and SAMRAI::hier::VariableDatabase::getDatabase().
Referenced by insertEquivalenceClassItem(), and printClassData().
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/CoarsenClasses.h
source/SAMRAI/xfer/CoarsenClasses.C