SAMRAI: SAMRAI::mesh::TreeLoadBalancer Class Reference
SAMRAI::mesh::TreeLoadBalancer Class Reference
Provides load balancing routines for AMR hierarchy by implemementing the LoadBalancerStrategy.
#include <source/SAMRAI/mesh/TreeLoadBalancer.h>
Public Member Functions
TreeLoadBalancer (const tbox::Dimension &dim, const std::string &name, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >(), const boost::shared_ptr< tbox::RankTreeStrategy > &rank_tree=boost::shared_ptr< tbox::RankTreeStrategy >())
Initializing constructor sets object state to default or, if database provided, to parameters in database.
virtual ~TreeLoadBalancer ()
Virtual destructor releases all internal storage.
void setSAMRAI_MPI (const tbox::SAMRAI_MPI &samrai_mpi)
Set the internal SAMRAI_MPI to a duplicate of the given SAMRAI_MPI.
void freeMPICommunicator ()
Free the internal MPI communicator, if any has been set.
void setWorkloadPatchDataIndex (int data_id, int level_number=-1)
Configure the load balancer to use the data stored in the hierarchy at the specified descriptor index for estimating the workload on each cell.
bool getLoadBalanceDependsOnPatchData (int level_number) const
Return true if load balancing procedure for given level depends on patch data on mesh; otherwise return false.
void loadBalanceBoxLevel (hier::BoxLevel &balance_box_level, hier::Connector *balance_to_anchor, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int level_number, const hier::IntVector &min_size, const hier::IntVector &max_size, const hier::BoxLevel &domain_box_level, const hier::IntVector &bad_interval, const hier::IntVector &cut_factor, const tbox::RankGroup &rank_group=tbox::RankGroup()) const
void printStatistics (std::ostream &output_stream=tbox::plog) const
Write out statistics recorded for the most recent load balancing result.
void setCommGraphWriter (const boost::shared_ptr< tbox::CommGraphWriter > &comm_graph_writer)
Enable or disable saving of tree data for diagnostics.
const std::string & getObjectName () const
Get the name of this object.
Detailed Description
Provides load balancing routines for AMR hierarchy by implemementing the LoadBalancerStrategy.
This class implements a tree-based load balancer. The MPI processes are arranged in a tree. Work load is transmitted from process to process along the edges of the tree.
Currently, only uniform load balancing is supported. Eventually, non-uniform load balancing should be supported. (Non-uniform load balancing is supported by the CutAndPackLoadBalancer class.)
Input Parameters
Definitions:
flexible_load_tolerance Fraction of ideal load a process can take on in order to reduce box cutting and load movement. Higher values often reduce partitioning time and box count but produce less balanced work loads. Surplus work greater than this tolerance can still result due to other constraints, such as minimum box size.
tile_size Tile size when using tile mode. Tile mode restricts box cuts to tile boundaries. Default is 1, which is equivalent to no restriction.
max_spread_procs This parameter limits how many processes may receive the load of one process in a load distribution cycle. If a process has too much initial load, this limit causes the load to distribute the load over multiple cycles. It alleviates the bottle-neck of one process having to work with too many other processes in any cycle.
Details:
parameter
type
default
range
opt/req
behavior on restart
flexible_load_tolerance
double
0.05
0-1
opt
Not written to restart. Value in input db used.
tile_size
IntVector
1
1-
opt
Not written to restart. Value in input db used.
max_spread_procs
int
500
> 1
opt
Not written to restart. Value in input db used.
Constructor & Destructor Documentation
SAMRAI::mesh::TreeLoadBalancer::TreeLoadBalancer (const tbox::Dimension & dim, const std::string & name, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>(), const boost::shared_ptr< tbox::RankTreeStrategy > & rank_tree = boost::shared_ptr<tbox::RankTreeStrategy>())
Initializing constructor sets object state to default or, if database provided, to parameters in database.
Parameters:
[in] dim
[in] name User-defined identifier used for diagnostic reports and timer names.
[in] input_db (optional) database pointer providing parameters from input file. This pointer may be null indicating no input is used.
[in] rank_tree How to arange a contiguous range of MPI ranks into a tree. If omitted, we use a tbox::CenteredRankTree.
Precondition:
!name.empty()
References SAMRAI::hier::MappingConnectorAlgorithm::setTimerPrefix(), and TBOX_ASSERT.
SAMRAI::mesh::TreeLoadBalancer::~TreeLoadBalancer () [virtual]
Virtual destructor releases all internal storage.
References freeMPICommunicator().
Member Function Documentation
void SAMRAI::mesh::TreeLoadBalancer::setSAMRAI_MPI (const tbox::SAMRAI_MPI & samrai_mpi)
Set the internal SAMRAI_MPI to a duplicate of the given SAMRAI_MPI.
The given SAMRAI_MPI must have a valid communicator.
The given SAMRAI_MPI is duplicated for private use. This requires a global communication, so all processes in the communicator must call it. The advantage of a duplicate communicator is that it ensures the communications for the object won't accidentally interact with unrelated communications.
If the duplicate SAMRAI_MPI it is set, the TreeLoadBalancer will only balance BoxLevels with congruent SAMRAI_MPI objects and will use the duplicate SAMRAI_MPI for communications. Otherwise, the SAMRAI_MPI of the BoxLevel will be used. The duplicate MPI communicator is freed when the object is destructed, or freeMPICommunicator() is called.
Precondition:
samrai_mpi.getCommunicator() != tbox::SAMRAI_MPI::commNull
References SAMRAI::tbox::SAMRAI_MPI::commNull, SAMRAI::tbox::SAMRAI_MPI::dupCommunicator(), SAMRAI::tbox::SAMRAI_MPI::freeCommunicator(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::hier::MappingConnectorAlgorithm::setSAMRAI_MPI(), and TBOX_ERROR.
void SAMRAI::mesh::TreeLoadBalancer::freeMPICommunicator ()
Free the internal MPI communicator, if any has been set.
This is automatically done by the destructor, if needed.
See also:
setSAMRAI_MPI().
References SAMRAI::tbox::SAMRAI_MPI::commNull, SAMRAI::tbox::SAMRAI_MPI::Finalized(), SAMRAI::tbox::SAMRAI_MPI::freeCommunicator(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), MPI_COMM_NULL, and SAMRAI::tbox::SAMRAI_MPI::setCommunicator().
Referenced by ~TreeLoadBalancer().
void SAMRAI::mesh::TreeLoadBalancer::setWorkloadPatchDataIndex (int data_id, int level_number = -1)
Configure the load balancer to use the data stored in the hierarchy at the specified descriptor index for estimating the workload on each cell.
Note: This method currently does not affect the results because this class does not yet support uniform load balancing.
Parameters:
data_id Integer value of patch data identifier for workload estimate on each cell. An invalid value (i.e., < 0) indicates that a spatially-uniform work estimate will be used. The default value is -1 (undefined) implying the uniform work estimate.
level_number Optional integer number for level on which data id is used. If no value is given, the data will be used for all levels.
Precondition:
hier::VariableDatabase::getDatabase()->getPatchDescriptor()->getPatchDataFactory(data_id) is actually a boost::shared_ptr<pdat::CellDataFactory<double> >
References BOOST_CAST, SAMRAI::hier::VariableDatabase::getDatabase(), and TBOX_ASSERT.
bool SAMRAI::mesh::TreeLoadBalancer::getLoadBalanceDependsOnPatchData (int level_number) const [virtual]
Return true if load balancing procedure for given level depends on patch data on mesh; otherwise return false.
Parameters:
[in] level_number Integer patch level number.
Implements SAMRAI::mesh::LoadBalanceStrategy.
void SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel (hier::BoxLevel & balance_box_level, hier::Connector * balance_to_anchor, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int level_number, const hier::IntVector & min_size, const hier::IntVector & max_size, const hier::BoxLevel & domain_box_level, const hier::IntVector & bad_interval, const hier::IntVector & cut_factor, const tbox::RankGroup & rank_group = tbox::RankGroup()) const [virtual]
Given a BoxLevel, representing the domain of a specified level in the AMR hierarchy, generate a new BoxLevel from which the patches for the level may be formed and update two Connectors incident on the changed BoxLevel. The union of the boxes in the balance_box_level is the same before and after the the method call.
Parameters:
[in,out] balance_box_level Input BoxLevel. On input, this is the pre-balance BoxLevel. On output, it is the balanced BoxLevel.
[in,out] balance_to_anchor Connector between the balance_box_level and some given "anchor box_level". This must be accurate on input. On putput, connects the newly balanced balance_box_level to the anchor box_level. If set to NULL, this parameter is ignored and Connector update is skipped.
[in] hierarchy The hierarchy where the work distribution data lives.
[in] level_number The number of the level where the work distribution data lives.
[in] min_size hier::IntVector representing mimimum box size.
[in] max_size hier::IntVector representing maximum box size.
[in] domain_box_level Description of the domain.
[in] bad_interval hier::IntVector indicating the length of an interval of cells along each side of the box where chopping the box may produce boxes with certain "bad" properties. For example, this is primiarily used to avoid generating ghost regions for patches that intersect the domain boundary in ways that may it difficult for a use to provide boundary values. Thus, it is typically related to the maximum ghost cell width in the problem. See hier::BoxUtilities header file for more information.
[in] cut_factor hier::IntVector indicating factor for chopping each side of a box; i.e., after chopping a box, the number of cells along each direction of each piece must be an integer multiple of the corresponding entry in the cut factor vector. For example, the cut factor may be related to the coarsen ratio between levels in the hierarchy in which case it may be used to produce boxes that can be coarsened by a certain factor if needed. See hier::BoxUtilities header file for more information.
[in] rank_group Input tbox::RankGroup indicating a set of ranks on which all boxes in the output balance_box_level will be restricted. Some child classes may not make use of this argument.
Note: This implementation does not yet support non-uniform load balancing.
Precondition:
!balance_to_anchor || balance_to_anchor->hasTranspose()
!balance_to_anchor || balance_to_anchor->isTransposeOf(balance_to_anchor->getTranspose())
(d_dim == balance_box_level.getDim()) && (d_dim == min_size.getDim()) && (d_dim == max_size.getDim()) && (d_dim == domain_box_level.getDim()) && (d_dim == bad_interval.getDim()) && (d_dim == cut_factor.getDim())
!hierarchy || (d_dim == hierarchy->getDim())
!d_mpi_is_dupe || (d_mpi.getSize() == balance_box_level.getMPI().getSize())
!d_mpi_is_dupe || (d_mpi.getSize() == balance_box_level.getMPI().getRank())
Implements SAMRAI::mesh::LoadBalanceStrategy.
References SAMRAI::tbox::SAMRAI_MPI::AllReduce(), SAMRAI::tbox::SAMRAI_MPI::Allreduce(), SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::tbox::RankGroup::containsAllRanks(), SAMRAI::hier::Connector::format(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::BoxLevel::getParallelState(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::Connector::hasTranspose(), SAMRAI::tbox::SAMRAI_MPI::isCongruentWith(), SAMRAI::hier::Connector::isTransposeOf(), MPI_DOUBLE, MPI_MAX, MPI_SUM, NULL_USE, SAMRAI::tbox::perr, SAMRAI::tbox::plog, SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::mesh::BalanceUtilities::reduceAndReportLoadBalance(), SAMRAI::hier::BoxLevel::removePeriodicImageBoxes(), SAMRAI::hier::Connector::removePeriodicRelationships(), SAMRAI::hier::Connector::setBase(), SAMRAI::tbox::RankGroup::size(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, TBOX_ASSERT_DIM_OBJDIM_EQUALITY6, and TBOX_ERROR.
void SAMRAI::mesh::TreeLoadBalancer::printStatistics (std::ostream & output_stream = tbox::plog) const
Write out statistics recorded for the most recent load balancing result.
Parameters:
[in] output_stream
References SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and SAMRAI::mesh::BalanceUtilities::reduceAndReportLoadBalance().
void SAMRAI::mesh::TreeLoadBalancer::setCommGraphWriter (const boost::shared_ptr< tbox::CommGraphWriter > & comm_graph_writer) [inline]
Enable or disable saving of tree data for diagnostics.
Parameters:
[in] comm_graph_writer External CommGraphWriter to save tree data to. Use 0 to disable saving.
const std::string& SAMRAI::mesh::TreeLoadBalancer::getObjectName () const [inline]
Get the name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/TreeLoadBalancer.h
source/SAMRAI/mesh/TreeLoadBalancer.C