SAMRAI: SAMRAI::hier::ComponentSelector Class Reference
SAMRAI::hier::ComponentSelector Class Reference
Bit vector used to indicate on which patch data elements to apply operations.
#include <source/SAMRAI/hier/ComponentSelector.h>
Public Member Functions
ComponentSelector (const bool flag=false)
Create a ComponentSelector with all values initialized to the specified flag value.
ComponentSelector (const ComponentSelector &flags)
Copy constructor that create a component selector identical to the argument.
~ComponentSelector ()
The destructor for a component selector does nothing interesting.
int getSize () const
Get the size of the ComponentSelector.
ComponentSelector & operator= (const ComponentSelector &flags)
Copy assignment operator.
bool operator== (const ComponentSelector &flags) const
Equality operator. Two ComponentSelector objects are equal when all their bits are the same.
bool operator!= (const ComponentSelector &flags) const
Inequality operator. Two ComponentSelector objects are unequal if any of their bits are different.
ComponentSelector operator| (const ComponentSelector &flags) const
Generate and return a component selector set to the bitwise logical OR of this component selector and the argument component selector.
ComponentSelector operator& (const ComponentSelector &flags) const
Generate a component selector set to the bitwise logical AND of this component selector and the argument component selector.
ComponentSelector operator! () const
Generate a component selector set to the bitwise logical negation of this component selector.
ComponentSelector & operator|= (const ComponentSelector &flags)
Set all bits in this component selector to the bitwise logical OR of this component selector and the argument component selector.
ComponentSelector & operator&= (const ComponentSelector &flags)
Set all bits in this component selector to the bitwise logical AND of this component selector and the argument component selector.
bool isSet (const int i) const
Check whether the specified bit vector position is true.
void setFlag (const int i)
Set the specified bit vector position to true.
void clrFlag (const int i)
Set the specified bit vector position to false.
void setAllFlags ()
Set all bit vector positions to true.
void clrAllFlags ()
Set all bit vector positions to false.
int getMaxIndex () const
Get the index of the highest set position.
bool any () const
check if any bits in the vector are set to true.
bool none () const
check if no bits in the vector are set to true.
void printClassData (std::ostream &os=tbox::plog) const
Print the bit vector data to the specified output stream.
Detailed Description
Bit vector used to indicate on which patch data elements to apply operations.
Class ComponentSelector implements a bit vector of a fixed length and is typically used to apply operations on subsets of entries in the patch data array owned by a patch (e.g., allocate/deallocate). All ComponentSelector objects have the same bit vector length that is established by the SAMRAIManager utility. See the documentation of the SAMRAIManager utility for information about changing this maximum value.
See also:
tbox::SAMRAIManager
Constructor & Destructor Documentation
SAMRAI::hier::ComponentSelector::ComponentSelector (const bool flag = false) [explicit]
Create a ComponentSelector with all values initialized to the specified flag value.
Parameters:
[in] flag Default: false
References SAMRAI::tbox::SAMRAIManager::getMaxNumberPatchDataEntries().
SAMRAI::hier::ComponentSelector::ComponentSelector (const ComponentSelector & flags)
Copy constructor that create a component selector identical to the argument.
SAMRAI::hier::ComponentSelector::~ComponentSelector ()
The destructor for a component selector does nothing interesting.
Member Function Documentation
int SAMRAI::hier::ComponentSelector::getSize () const [inline]
Get the size of the ComponentSelector.
Returns:
total number of flags (i.e., bits) in this component selector.
Referenced by clrFlag(), isSet(), SAMRAI::algs::OuternodeSumTransactionFactory::preprocessScratchSpace(), SAMRAI::algs::OuteredgeSumTransactionFactory::preprocessScratchSpace(), printClassData(), and setFlag().
ComponentSelector& SAMRAI::hier::ComponentSelector::operator= (const ComponentSelector & flags) [inline]
Copy assignment operator.
bool SAMRAI::hier::ComponentSelector::operator== (const ComponentSelector & flags) const [inline]
Equality operator. Two ComponentSelector objects are equal when all their bits are the same.
bool SAMRAI::hier::ComponentSelector::operator!= (const ComponentSelector & flags) const [inline]
Inequality operator. Two ComponentSelector objects are unequal if any of their bits are different.
ComponentSelector SAMRAI::hier::ComponentSelector::operator| (const ComponentSelector & flags) const
Generate and return a component selector set to the bitwise logical OR of this component selector and the argument component selector.
Parameters:
[in] flags The ComponentSelector used to apply the logical OR operation
Returns:
The ComponentSelector which is the logical OR of this component.
ComponentSelector SAMRAI::hier::ComponentSelector::operator& (const ComponentSelector & flags) const
Generate a component selector set to the bitwise logical AND of this component selector and the argument component selector.
Parameters:
[in] flags The ComponentSelector used to apply the logical AND operation
Returns:
The ComponentSelector which is the logical AND of this component.
ComponentSelector SAMRAI::hier::ComponentSelector::operator! () const
Generate a component selector set to the bitwise logical negation of this component selector.
Returns:
The ComponentSelector which is the logical negation of this component.
ComponentSelector & SAMRAI::hier::ComponentSelector::operator|= (const ComponentSelector & flags)
Set all bits in this component selector to the bitwise logical OR of this component selector and the argument component selector.
This is a modifying operation on this ComponentSelector.
Returns:
This selector, modified.
ComponentSelector & SAMRAI::hier::ComponentSelector::operator&= (const ComponentSelector & flags)
Set all bits in this component selector to the bitwise logical AND of this component selector and the argument component selector.
This is a modifying operation on this ComponentSelector.
Returns:
This selector, modified.
bool SAMRAI::hier::ComponentSelector::isSet (const int i) const [inline]
Check whether the specified bit vector position is true.
Parameters:
[in] i The position in the bit vector to check.
Returns:
True if the bit at position i is set to true.
Precondition:
(i >= 0) && (i < getSize())
References getSize(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::Patch::allocatePatchData(), SAMRAI::hier::Patch::deallocatePatchData(), SAMRAI::hier::Patch::getSizeOfPatchData(), SAMRAI::hier::PatchDataRestartManager::isPatchDataRegisteredForRestart(), SAMRAI::algs::OuternodeSumTransactionFactory::preprocessScratchSpace(), SAMRAI::algs::OuteredgeSumTransactionFactory::preprocessScratchSpace(), printClassData(), and SAMRAI::hier::Patch::setTime().
void SAMRAI::hier::ComponentSelector::setFlag (const int i) [inline]
Set the specified bit vector position to true.
Parameters:
[in] i The position in the bit vector to set to true.
Precondition:
(i >= 0) && (i < getSize())
References getSize(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::Patch::getFromRestart(), SAMRAI::hier::PatchDataRestartManager::registerPatchDataForRestart(), SAMRAI::algs::PatchBoundaryEdgeSum::registerSum(), and SAMRAI::algs::MethodOfLinesIntegrator::registerVariable().
void SAMRAI::hier::ComponentSelector::clrFlag (const int i) [inline]
Set the specified bit vector position to false.
Parameters:
[in] i The position in the bit vector to set to false.
Precondition:
(i >= 0) && (i < getSize())
References getSize(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::PatchDataRestartManager::unregisterPatchDataForRestart().
void SAMRAI::hier::ComponentSelector::setAllFlags () [inline]
Set all bit vector positions to true.
void SAMRAI::hier::ComponentSelector::clrAllFlags () [inline]
Set all bit vector positions to false.
int SAMRAI::hier::ComponentSelector::getMaxIndex () const [inline]
Get the index of the highest set position.
Referenced by SAMRAI::hier::Patch::getSizeOfPatchData().
bool SAMRAI::hier::ComponentSelector::any () const
check if any bits in the vector are set to true.
Returns:
True if any bit in the vector is set true, otherwise false.
Referenced by none().
bool SAMRAI::hier::ComponentSelector::none () const [inline]
check if no bits in the vector are set to true.
This is essentially determining if all bits are false.
Returns:
True if no bits in the vector are set to true, otherwise false.
References any().
void SAMRAI::hier::ComponentSelector::printClassData (std::ostream & os = tbox::plog) const
Print the bit vector data to the specified output stream.
References getSize(), and isSet().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/ComponentSelector.h
source/SAMRAI/hier/ComponentSelector.C