SAMRAI: SAMRAI::pdat::SideIndex Class Reference
SAMRAI::pdat::SideIndex Class Reference
#include <source/SAMRAI/pdat/SideIndex.h>
Public Types
enum {
X = 0, Y = 1, Z = 2, Lower = 0,
Upper = 1
}
Public Member Functions
SideIndex (const tbox::Dimension &dim)
SideIndex (const hier::Index &rhs, const int axis, const int side)
SideIndex (const SideIndex &rhs)
SideIndex & operator= (const SideIndex &rhs)
~SideIndex ()
int getAxis () const
void setAxis (const int axis)
hier::Index toCell (const int side) const
SideIndex & operator+= (const hier::IntVector &rhs)
SideIndex operator+ (const hier::IntVector &rhs) const
SideIndex & operator+= (const int rhs)
SideIndex operator+ (const int rhs) const
SideIndex & operator-= (const hier::IntVector &rhs)
SideIndex operator- (const hier::IntVector &rhs) const
SideIndex & operator-= (const int rhs)
SideIndex operator- (const int rhs) const
SideIndex & operator*= (const hier::IntVector &rhs)
SideIndex operator* (const hier::IntVector &rhs) const
SideIndex & operator*= (const int rhs)
SideIndex operator* (const int rhs) const
bool operator== (const SideIndex &rhs) const
bool operator!= (const SideIndex &rhs) const
Detailed Description
Class SideIndex implements a simple n-dimensional integer vector for side centered variables. Side indices contain an integer index location in AMR index space along with the designated side axis (X=0, Y=1, or Z=2). See the side box geometry class for more information about the mapping between the AMR index space and the side indices.
See also:
hier::Index
pdat::SideData
pdat::SideGeometry
pdat::SideIterator
Member Enumeration Documentation
anonymous enum
Enumerator:
X
Y
Z
Lower
Upper
Constructor & Destructor Documentation
SAMRAI::pdat::SideIndex::SideIndex (const tbox::Dimension & dim) [explicit]
The default constructor for a side index creates an uninitialized index.
SAMRAI::pdat::SideIndex::SideIndex (const hier::Index & rhs, const int axis, const int side)
Construct a side index from a regular index, axis, and side. The axis can be one of SideIndex::X (0), SideIndex::Y (1), or SideIndex::Z (2). The side argument can be one of the constants SideIndex::Lower (0) or SideIndex::Upper (1).
SAMRAI::pdat::SideIndex::SideIndex (const SideIndex & rhs)
The copy constructor creates a side index equal to the argument.
SAMRAI::pdat::SideIndex::~SideIndex ()
The side index destructor does nothing interesting.
Member Function Documentation
SideIndex& SAMRAI::pdat::SideIndex::operator= (const SideIndex & rhs) [inline]
The assignment operator sets the side index equal to the argument.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
int SAMRAI::pdat::SideIndex::getAxis () const [inline]
Get the axis for which this side index is defined (X=0, Y=1, Z=2).
Referenced by SAMRAI::pdat::SideData< TYPE >::operator()(), SAMRAI::pdat::OutersideData< TYPE >::operator()(), and SAMRAI::pdat::SideGeometry::transform().
void SAMRAI::pdat::SideIndex::setAxis (const int axis) [inline]
Set the side axis (X=0, Y=1, Z=2).
Referenced by SAMRAI::pdat::SideGeometry::transform().
hier::Index SAMRAI::pdat::SideIndex::toCell (const int side) const
Convert the side index into the index on the left hand side (argument side == 0) or the right hand side (argument side == 1).
References SAMRAI::hier::IntVector::getDim(), and SAMRAI::tbox::Dimension::getValue().
SideIndex& SAMRAI::pdat::SideIndex::operator+= (const hier::IntVector & rhs) [inline]
Plus-equals operator for a side index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator+=().
SideIndex SAMRAI::pdat::SideIndex::operator+ (const hier::IntVector & rhs) const [inline]
Plus operator for a side index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
SideIndex& SAMRAI::pdat::SideIndex::operator+= (const int rhs) [inline]
Plus-equals operator for a side index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator+=().
SideIndex SAMRAI::pdat::SideIndex::operator+ (const int rhs) const [inline]
Plus operator for a side index and an integer.
Reimplemented from SAMRAI::hier::Index.
SideIndex& SAMRAI::pdat::SideIndex::operator-= (const hier::IntVector & rhs) [inline]
Minus-equals operator for a side index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator-=().
SideIndex SAMRAI::pdat::SideIndex::operator- (const hier::IntVector & rhs) const [inline]
Minus operator for a side index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
SideIndex& SAMRAI::pdat::SideIndex::operator-= (const int rhs) [inline]
Minus-equals operator for a side index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator-=().
SideIndex SAMRAI::pdat::SideIndex::operator- (const int rhs) const [inline]
Minus operator for a side index and an integer.
Reimplemented from SAMRAI::hier::Index.
SideIndex& SAMRAI::pdat::SideIndex::operator*= (const hier::IntVector & rhs) [inline]
Times-equals operator for a side index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator*=().
SideIndex SAMRAI::pdat::SideIndex::operator* (const hier::IntVector & rhs) const [inline]
Times operator for a side index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
SideIndex& SAMRAI::pdat::SideIndex::operator*= (const int rhs) [inline]
Times-equals operator for a side index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator*=().
SideIndex SAMRAI::pdat::SideIndex::operator* (const int rhs) const [inline]
Times operator for a side index and an integer.
Reimplemented from SAMRAI::hier::Index.
bool SAMRAI::pdat::SideIndex::operator== (const SideIndex & rhs) const [inline]
Returns true if two side index objects are equal. All components and the corresponding side axes must be the same for equality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::IntVector.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::pdat::SideIndex::operator!= (const SideIndex & rhs) const [inline]
Returns true if two side index objects are not equal. Any of the components or axes may be different for inequality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::IntVector.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/SideIndex.h
source/SAMRAI/pdat/SideIndex.C