SAMRAI: SAMRAI::pdat::SideData< TYPE > Class Template Reference
SAMRAI::pdat::SideData< TYPE > Class Template Reference
Class SideData<TYPE> provides an implementation for data defined at cell sides (faces) on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a side data object represents data of some template TYPE and depth on the sides (faces) of the cells in the box. Here, depth indicates the number of data values at each side index location. The SideGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and side-centered data.
#include <source/SAMRAI/pdat/SideData.h>
Public Types
typedef SideIterator iterator
Public Member Functions
SideData (const hier::Box &box, int depth, const hier::IntVector &ghosts, const hier::IntVector &directions)
The constructor for a side data object.
SideData (const hier::Box &box, int depth, const hier::IntVector &ghosts)
Same as previous constructor but with directions vector of 1's.
virtual ~SideData ()
The virtual destructor for a side data object.
const hier::IntVector & getDirectionVector () const
Return constant reference to vector describing which coordinate directions have data associated with this side data object.
int getDepth () const
Return the depth (e.g., the number of components in each spatial location) of the array.
TYPE * getPointer (int side_normal, int depth=0)
Get a pointer to the beginning of a particular side normal and depth component of the side centered array.
const TYPE * getPointer (int side_normal, int depth=0) const
Get a const pointer to the beginning of a particular side normal and depth component of the side centered array.
TYPE & operator() (const SideIndex &i, int depth=0)
Return a reference to the data entry corresponding to a given side index and depth.
const TYPE & operator() (const SideIndex &i, int depth=0) const
Return a const reference to the data entry corresponding to a given side index and depth.
ArrayData< TYPE > & getArrayData (int side_normal)
Return a reference to the array data object for the given side normal of the side centered data object.
const ArrayData< TYPE > & getArrayData (int side_normal) const
Return a const reference to the array data object for the given side normal of the side centered data object.
virtual void copy (const hier::PatchData &src)
A fast copy from source to destination (i.e., this) patch data object.
virtual void copy2 (hier::PatchData &dst) const
A fast copy from source (i.e., this) to destination patch data object.
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Copy data from source to destination (i.e., this) patch data object on the given overlap.
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
Copy data from source (i.e., this) to destination patch data object on the given overlap.
void copyOnBox (const SideData< TYPE > &src, const hier::Box &box)
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
void copyDepth (int dst_depth, const SideData< TYPE > &src, int src_depth)
Fast copy (i.e., source and this side data objects are defined over the same box) to this destination side data object from the given source side data object at the specified depths.
virtual bool canEstimateStreamSizeFromBox () const
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
virtual size_t getDataStreamSize (const hier::BoxOverlap &overlap) const
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an SideOverlap of the same DIM.
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an SideOverlap of the same DIM.
void fill (const TYPE &t, int d=0)
Fill all values at depth d with the value t.
void fill (const TYPE &t, const hier::Box &box, int d=0)
Fill all values at depth d within the box with the value t.
void fillAll (const TYPE &t)
Fill all depth components with value t.
void fillAll (const TYPE &t, const hier::Box &box)
Fill all depth components within the box with value t.
void print (const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all side data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
void print (const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all side data values at the given array depth in the specified box.
void printAxis (tbox::Dimension::dir_t side_normal, const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all side centered data values for specified side normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
void printAxis (tbox::Dimension::dir_t side_normal, const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all side centered data values for specified side normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Static Public Member Functions
static size_t getSizeOfData (const hier::Box &box, int depth, const hier::IntVector &ghosts, const hier::IntVector &directions)
Calculate the amount of memory needed to represent side- centered data over a CELL-centered AMR index space box.
Detailed Description
template<class TYPE>
class SAMRAI::pdat::SideData< TYPE >
Class SideData<TYPE> provides an implementation for data defined at cell sides (faces) on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a side data object represents data of some template TYPE and depth on the sides (faces) of the cells in the box. Here, depth indicates the number of data values at each side index location. The SideGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and side-centered data.
IMPORTANT: The FaceData<TYPE> class provides the same storage as this side data class, except that the coordinate directions of the individual arrays are permuted in the face data implementation.
Side data is stored in DIM arrays, each of which contains the data for the sides normal to a corresponding coordinate direction. Memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory. For example, a three-dimensional side data object created over a CELL-centered AMR index space [l0:u0,l1:u1,l2:u2] allocates three data arrays sized as follows:
 *
 * side normal 0
 *   [ l0 : u0+1 ,
 *     l1 : u1 ,
 *     l2 : u2 , d ]   ,
 *
 * side normal 1
 *   [ l0 : u0 ,
 *     l1 : u1+1 ,
 *     l2 : u2 , d ]   ,
 *
 * side normal 2
 *   [ l0 : u0 ,
 *     l1 : u1 ,
 *     l2 : u2+1 , d ]   ,
 *
 *
Here the side normal directions 0, 1, 2 can be thought of as the x, y, and z side normal directions, respectively, and d is the depth index (i.e., number of values at each side index location). Other spatial dimensions are represented similarly.
Note also that it is possible to create a side data object for managing data at cell sides associated with a single coordinate direction only. See the constructor for more information. All operations are defined only for the case where data storage is alike between two side data objects.
The data type TYPE must define a default constructor (that takes no arguments) and also the assignment operator.
See also:
pdat::ArrayData
hier::PatchData
pdat::SideDataFactory
pdat::SideIndex
pdat::SideIterator
pdat::SideGeometry
Member Typedef Documentation
template<class TYPE> typedef SideIterator SAMRAI::pdat::SideData< TYPE >::iterator
The side iterator iterates over the elements on one axis of a side centered box geometry. This typedef is a convenience for using the SideIterator class.
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::SideData< TYPE >::SideData (const hier::Box & box, int depth, const hier::IntVector & ghosts, const hier::IntVector & directions) [inline]
The constructor for a side data object.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the side data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the side data will be allocated.
directions const IntVector reference indicating which coordinate directions will have data associated with them.
Precondition:
(box.getDim() == ghosts.getDim()) && (box.getDim() == directions.getDim())
depth > 0
ghosts.min() >= 0
directions.min() >= 0
References SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::getEmptyBox(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > SAMRAI::pdat::SideData< TYPE >::SideData (const hier::Box & box, int depth, const hier::IntVector & ghosts) [inline]
Same as previous constructor but with directions vector of 1's.
Precondition:
box.getDim() == ghosts.getDim()
depth > 0
ghosts.min() >= 0
References SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > SAMRAI::pdat::SideData< TYPE >::~SideData () [inline, virtual]
The virtual destructor for a side data object.
Member Function Documentation
template<class TYPE > size_t SAMRAI::pdat::SideData< TYPE >::getSizeOfData (const hier::Box & box, int depth, const hier::IntVector & ghosts, const hier::IntVector & directions) [inline, static]
Calculate the amount of memory needed to represent side- centered data over a CELL-centered AMR index space box.
This function assumes that the amount of memory needed for TYPE is sizeof(TYPE). If this is not the case, then a specialized function must be defined.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the side data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the side data will be allocated.
directions const IntVector reference indicating which coordinate directions are assumed to have data for the purposes of the calculation.
Precondition:
(box.getDim() == ghosts.getDim()) && (box.getDim() == directions.getDim())
depth > 0
directions.min() >= 0
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::grow(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > const hier::IntVector & SAMRAI::pdat::SideData< TYPE >::getDirectionVector () const [inline]
Return constant reference to vector describing which coordinate directions have data associated with this side data object.
A vector entry of zero indicates that there is no data array allocated for the corresponding coordinate direction. A non-zero value indicates that a valid data array is maintained for that coordinate direction.
Referenced by SAMRAI::pdat::SideData< TYPE >::copy(), and SAMRAI::pdat::SideData< TYPE >::copy2().
template<class TYPE > int SAMRAI::pdat::SideData< TYPE >::getDepth () const [inline]
Return the depth (e.g., the number of components in each spatial location) of the array.
template<class TYPE > TYPE * SAMRAI::pdat::SideData< TYPE >::getPointer (int side_normal, int depth = 0) [inline]
Get a pointer to the beginning of a particular side normal and depth component of the side centered array.
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
getDirectionVector()(side_normal)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch().
template<class TYPE > const TYPE * SAMRAI::pdat::SideData< TYPE >::getPointer (int side_normal, int depth = 0) const [inline]
Get a const pointer to the beginning of a particular side normal and depth component of the side centered array.
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
getDirectionVector()(side_normal)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::SideData< TYPE >::operator() (const SideIndex & i, int depth = 0) [inline]
Return a reference to the data entry corresponding to a given side index and depth.
Precondition:
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
getDirectionVector()(i.getAxis())
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::SideIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > const TYPE & SAMRAI::pdat::SideData< TYPE >::operator() (const SideIndex & i, int depth = 0) const [inline]
Return a const reference to the data entry corresponding to a given side index and depth.
Precondition:
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
getDirectionVector()(i.getAxis())
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::SideIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > ArrayData< TYPE > & SAMRAI::pdat::SideData< TYPE >::getArrayData (int side_normal) [inline]
Return a reference to the array data object for the given side normal of the side centered data object.
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
getDirectionVector()(side_normal)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::OutersideData< TYPE >::copy(), SAMRAI::pdat::OutersideData< TYPE >::copy2(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth2(), and SAMRAI::pdat::SideData< TYPE >::copyOnBox().
template<class TYPE > const ArrayData< TYPE > & SAMRAI::pdat::SideData< TYPE >::getArrayData (int side_normal) const [inline]
Return a const reference to the array data object for the given side normal of the side centered data object.
Precondition:
(side_normal >= 0) && (side_normal < getDim().getValue())
getDirectionVector()(side_normal)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy from source to destination (i.e., this) patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, source data must be an SideData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDirectionVector().getDim() == src.getDim()
References SAMRAI::hier::PatchData::copy2(), SAMRAI::hier::Box::empty(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideData< TYPE >::getDirectionVector(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy from source (i.e., this) to destination patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, destination data must be an SideData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDirectionVector().getDim() == dst.getDim()
dynamic_cast<SideData<TYPE> *>(&dst) != 0
(dynamic_cast<SideData<TYPE> *>(&dst))->getDirectionVector() == getDirectionVector()
References SAMRAI::hier::Box::empty(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideData< TYPE >::getDirectionVector(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from source to destination (i.e., this) patch data object on the given overlap.
Currently, source data must be SideData of the same DIM and TYPE and the overlap must be a SideOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDirectionVector().getDim() == src.getDim()
References SAMRAI::hier::PatchData::copy2(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideData< TYPE >::getDirectionVector(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from source (i.e., this) to destination patch data object on the given overlap.
Currently, destination data must be SideData of the same DIM and TYPE and the overlap must be a SideOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDirectionVector().getDim() == dst.getDim()
dynamic_cast<SideData<TYPE> *>(&dst) != 0
dynamic_cast<const SideOverlap *>(&overlap) != 0
(dynamic_cast<SideData<TYPE> *>(&dst))->getDirectionVector() == getDirectionVector()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideData< TYPE >::getDirectionVector(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::copyOnBox (const SideData< TYPE > & src, const hier::Box & box) [inline]
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
Precondition:
(getDim() == src.getDim()) && (getDim() == box.getDim())
References SAMRAI::pdat::SideData< TYPE >::getArrayData(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::copyDepth (int dst_depth, const SideData< TYPE > & src, int src_depth) [inline]
Fast copy (i.e., source and this side data objects are defined over the same box) to this destination side data object from the given source side data object at the specified depths.
Precondition:
getDirectionVector.getDim() == src.getDim()
src.getDirectionVector() == getDirectionVector()
References SAMRAI::hier::Box::empty(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::SideData< TYPE >::canEstimateStreamSizeFromBox () const [inline, virtual]
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Implements SAMRAI::hier::PatchData.
template<class TYPE > size_t SAMRAI::pdat::SideData< TYPE >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Precondition:
dynamic_cast<const SideOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::SideOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an SideOverlap of the same DIM.
Precondition:
dynamic_cast<const SideOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::empty(), SAMRAI::pdat::SideOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::pdat::SideOverlap::getTransformation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an SideOverlap of the same DIM.
Precondition:
dynamic_cast<const SideOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::empty(), SAMRAI::pdat::SideOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::SideOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::fill (const TYPE & t, int d = 0) [inline]
Fill all values at depth d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::fill (const TYPE & t, const hier::Box & box, int d = 0) [inline]
Fill all values at depth d within the box with the value t.
Precondition:
getDirectionVector().getDim() == box.getDim()
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all depth components with value t.
References SAMRAI::hier::PatchData::getDim(), and SAMRAI::tbox::Dimension::getValue().
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all depth components within the box with value t.
Precondition:
getDirectionVector().getDim() == box.getDim()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::print (const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all side data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDirectionVector().getDim() == box.getDim()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::SideData< TYPE >::printAxis(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::print (const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all side data values at the given array depth in the specified box.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
depth integer depth component
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDirectionVector().getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::SideData< TYPE >::printAxis(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::printAxis (tbox::Dimension::dir_t side_normal, const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all side centered data values for specified side normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
Parameters:
side_normal integer side normal coordinate direction
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDirectionVector().getDim() == box.getDim()
(side_normal >= 0) && (side_normal < getDim().getValue())
References SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::SideData< TYPE >::print().
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::printAxis (tbox::Dimension::dir_t side_normal, const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all side centered data values for specified side normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
Parameters:
side_normal integer side normal coordinate direction
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to side index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDirectionVector().getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
(side_normal >= 0) && (side_normal < getDim().getValue())
References SAMRAI::pdat::SideGeometry::begin(), SAMRAI::pdat::SideGeometry::end(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check that class version and restart file version are equal. If so, read data members from the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::SideData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number and other data members to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/SideData.h
source/SAMRAI/pdat/SideData.C