SAMRAI: SAMRAI::hier::BoxContainer Class Reference
SAMRAI::hier::BoxContainer Class Reference
A container for Boxes.
#include <source/SAMRAI/hier/BoxContainer.h>
Classes
class BoxContainerConstIterator
A immutable iterator over the boxes in a BoxContainer.
class BoxContainerIterator
A mutable iterator over the boxes in a BoxContainer.
class Outputter
Intermediary between BoxContainer and output streams, adding ability to control the output. See BoxContainer::format().
Public Types
typedef BoxContainerIterator iterator
The iterator for class BoxContainer.
typedef BoxContainerConstIterator const_iterator
The const iterator for class BoxContainer.
Public Member Functions
bool operator== (const BoxContainer &rhs) const
Equality operator.
bool isIdEqual (const BoxContainer &other) const
Check for equality of BoxIds in ordered containers.
bool isSpatiallyEqual (const BoxContainer &other) const
Check for spatial equality of all boxes.
bool operator!= (const BoxContainer &rhs) const
Inequality operator.
void makeTree (const BaseGridGeometry *grid_geometry=0, const int min_number=10) const
Create a search tree representation of the boxes in this container.
bool hasTree () const
Query if the search tree representation exists.
bool hasBoxInBlock (const BlockId &block_id) const
Query if this BoxContainer contains any Box with the given BlockId.
void findOverlapBoxes (BoxContainer &overlap_boxes, const Box &box) const
Find all boxes that intersect with a given box.
void findOverlapBoxes (std::vector< const Box * > &overlap_boxes, const Box &box) const
Find all boxes that intersect with a given box.
void findOverlapBoxes (BoxContainer &overlap_boxes, const Box &box, const IntVector &refinement_ratio, bool include_singularity_block_neighbors=false) const
Find all boxes that intersect with a given box.
void findOverlapBoxes (std::vector< const Box * > &overlap_boxes, const Box &box, const IntVector &refinement_ratio, bool include_singularity_block_neighbors=false) const
bool hasOverlap (const Box &box) const
Determine if a given box intersects with the BoxContainer.
BoxContainer ()
Default constructor creates empty container in unordered state.
BoxContainer (const bool ordered)
Creates empty container in state determined by boolean.
BoxContainer (const_iterator first, const_iterator last, const bool ordered=false)
Create container containing members from another container.
BoxContainer (const Box &box, const bool ordered=false)
Create a container with 1 box.
BoxContainer (const BoxContainer &other)
Copy constructor from another BoxContainer.
BoxContainer (const std::vector< tbox::DatabaseBox > &other)
Copy constructor from an array of tbox::DatabaseBox objects.
BoxContainer (const BoxContainer &other, const BlockId &block_id)
Constructor that copies only Boxes having the given BlockId from the other container.
BoxContainer & operator= (const BoxContainer &rhs)
Assignment from other BoxContainer.
BoxContainer & operator= (const std::vector< tbox::DatabaseBox > &rhs)
Assignment from an array of tbox::DatabaseBox objects.
~BoxContainer ()
The destructor releases all storage.
int size () const
Return the number of boxes in the container.
bool isEmpty () const
Returns true if there are no boxes in the container.
bool empty () const
Returns true if there are no boxes in the container.
const_iterator begin () const
Return a const_iterator pointing to the start of the container.
const_iterator end () const
Return a const_iterator pointing to the end of the container.
iterator begin ()
Return an iterator pointing to the start of the container.
iterator end ()
Return an iterator pointing to the end of the container.
BoxContainerSingleBlockIterator begin (const BlockId &block_id) const
Return a BoxContainerSingleBlockIterator pointing to the first box in the container with the given BlockId.
BoxContainerSingleBlockIterator end (const BlockId &block_id) const
Return a BoxContainerSingleBlockIterator pointing to the end of the container.
BoxContainerSingleOwnerIterator begin (const int &owner_rank) const
Return a BoxContainerSingleOwnerIterator pointing to the first box in the container having the given owner.
BoxContainerSingleOwnerIterator end (const int &owner_rank) const
Return a BoxContainerSingleOwnerIterator pointing to the end of the container.
RealBoxConstIterator realBegin () const
Return a RealBoxConstIterator pointing to the first real (non-periodic) box in the container.
RealBoxConstIterator realEnd () const
Return a RealBoxConstIterator pointing to the end of the container.
const Box & front () const
Returns the first element in the container.
const Box & back () const
Returns the first element in the container.
void erase (iterator iter)
Remove the member of the container pointed to by "iter".
void erase (iterator first, iterator last)
Remove the members of the container in the range [first, last).
void clear ()
Removes all the members of the container.
void swap (BoxContainer &other)
Swap all contents and state with another BoxContainer.
void getOwners (std::set< int > &owners) const
Get all of the ranks that own Boxes in this container.
void grow (const IntVector &ghosts)
Grow boxes in the container by the specified ghost cell width.
void shift (const IntVector &offset)
Shift boxes in the container by the specified offset.
void refine (const IntVector &ratio)
Refine boxes in container by the specified refinement ratio.
void coarsen (const IntVector &ratio)
Coarsen boxes in container by the specified coarsening ratio.
size_t getTotalSizeOfBoxes () const
Count total number of indices in the boxes in the container.
bool contains (const Index &idx, const BlockId &block_id) const
Determine if "idx" lies within bounds of boxes in container.
Box getBoundingBox () const
Returns the bounding box for all the boxes in the container.
Box getBoundingBox (const BlockId &block_id) const
Returns the bounding box for all the boxes in the container having the given BlockId.
bool boxesIntersect () const
Check for non-empty intersection among boxes in container.
void order ()
Changes state of this container to ordered.
void unorder ()
Changes state of this container to unordered.
bool isOrdered () const
Return whether this container is ordered.
void pushFront (const Box &item)
Adds "item" to the "front" of the container.
void pushBack (const Box &item)
Adds "item" to the "end" of the container.
void push_front (const Box &item)
STL-named version of pushFront().
void push_back (const Box &item)
STL-named version of pushBack().
void insertBefore (iterator iter, const Box &item)
Add "item" to specific place in the container.
void insertAfter (iterator iter, const Box &item)
Add "item" to specific place in the container.
void spliceFront (BoxContainer &boxes)
Prepends the Boxes in "boxes" to this BoxContainer.
void spliceBack (BoxContainer &boxes)
Appends the Boxes in "boxes" to this BoxContainer.
void popFront ()
Remove the first member of the unordered container.
void popBack ()
Remove the last member of the unordered container.
void simplify ()
Place the boxes in the container into a canonical ordering.
void coalesce ()
Combine any boxes in the container which may be coalesced.
void rotate (const Transformation::RotationIdentifier rotation_ident)
Rotate boxes in container according to a RotationIdentifier.
void removeIntersections (const Box &takeaway)
Remove from each box the portions that intersect takeaway.
void removeIntersections (const BoxContainer &takeaway)
Remove from each box portions intersecting boxes in takeaway.
void removeIntersections (const IntVector &refinement_ratio, const BoxContainer &takeaway, const bool include_singularity_block_neighbors=false)
Remove from each box portions intersecting boxes in takeaway.
void removeIntersections (const Box &box, const Box &takeaway)
Remove from box the portions intersecting takeaway.
void intersectBoxes (const Box &keep)
Keep the intersection of the container's boxes and keep.
void intersectBoxes (const BoxContainer &keep)
Keep the intersection of the container's boxes and keep's boxes.
void intersectBoxes (const IntVector &refinement_ratio, const BoxContainer &keep, bool include_singularity_block_neighbors=false)
Keep the intersection of the container's boxes and keep's boxes.
bool insert (const Box &box)
Insert a single Box.
iterator insert (iterator position, const Box &box)
Insert a single Box.
void insert (const_iterator first, const_iterator last)
Insert all Boxes within a range.
iterator find (const Box &box) const
Find a box in an ordered container.
iterator lowerBound (const Box &box) const
Get lower bound iterator for a given Box.
iterator upperBound (const Box &box) const
Get upper bound iterator for a given Box.
int erase (const Box &box)
Erase a Box from the container.
void separatePeriodicImages (std::vector< Box > &real_box_vector, std::vector< Box > &periodic_image_box_vector, const PeriodicShiftCatalog &shift_catalog) const
Copy the members of this BoxContainer into two vector<Box> objects, one containing real Boxes and one containing their periodic images.
void removePeriodicImageBoxes ()
Any members of this container that are periodic images will be erased.
void unshiftPeriodicImageBoxes (BoxContainer &output_boxes, const IntVector &refinement_ratio, const PeriodicShiftCatalog &shift_catalog) const
Place unshifted versions of Boxes into a BoxContainer.
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write the BoxContainer to a restart database.
void getFromRestart (tbox::Database &restart_db)
Read the BoxContainer from a restart database.
operator std::vector< tbox::DatabaseBox > () const
Conversion from BoxContainer to std::vector<tbox::DatabaseBox>.
void print (std::ostream &os=tbox::plog, const std::string &border=std::string()) const
Print each box in the container to the specified output stream.
Outputter format (const std::string &border=std::string(), int detail_depth=2) const
Return a object to that can format the BoxContainer for inserting into output streams.
Friends
class BoxContainerIterator
class BoxContainerConstIterator
Detailed Description
A container for Boxes.
The BoxContainer stores a collection of Boxes and provides methods for access and manipulation of that collection.
A BoxContainer exists in either an "ordered" or "unordered" state. The ordered state means that the Boxes have been ordered according to the comparison operators defined in the BoxId class, while the unordered state has no meaningful ordering of the Boxes besides the sequence that the Boxes were added to the container. Additionally the ordered state requires that all Boxes in the container have a valid and unique BoxId, while there is no such restriction for unordered containers.
An ordered container can always have its state switched to unordered by a call to the unorder() method. An unordered container can also have its state switched to ordered by a call to the order() method, but only under certain conditions specified below in the comments for order().
Certain methods in this class can only be called on ordered containers while others can only be called on unordered containers. Violating these restrictions will result in a run-time error.
Regardless of unordered/unordered state, all Boxes within a BoxContainer must be of the same Dimension. If a new Box added to a container has a different Dimension than the Boxes already in the container, an assertion failure will occur.
An option exists to create an internal search tree representation based on the spatial coordinates of the Boxes in the container. This option can be used to reduce the cost of searching operations in the methods removeIntersections(), intersectBoxes(), findOverlapBoxes() and hasOverlap(). This option is invoked by calling the method makeTree(). This option should only be used in cases where the listed search methods will be called multiple times on the same unchanging BoxContainer. The cost of building the tree representaion is O(N(log(N)), while the tree reduces the cost of the search operations to O(log(N)) rather than O(N), thus it is adviseable to only use the tree representation when the reduction in search cost is expected to outweigh the increased cost of building the tree.
Constructing the tree represenation via makeTree() will change nothing about the Boxes stored in the container, nor will it change the ordered/unordered state of the container.
See also:
BoxId
Member Typedef Documentation
typedef BoxContainerIterator SAMRAI::hier::BoxContainer::iterator
The iterator for class BoxContainer.
typedef BoxContainerConstIterator SAMRAI::hier::BoxContainer::const_iterator
The const iterator for class BoxContainer.
Constructor & Destructor Documentation
SAMRAI::hier::BoxContainer::BoxContainer ()
Default constructor creates empty container in unordered state.
SAMRAI::hier::BoxContainer::BoxContainer (const bool ordered) [explicit]
Creates empty container in state determined by boolean.
Parameters:
[in] ordered Container will be ordered if true, unordered if false.
SAMRAI::hier::BoxContainer::BoxContainer (const_iterator first, const_iterator last, const bool ordered = false)
Create container containing members from another container.
Members in the range [first, last) are copied to new container.
Parameters:
[in] first
[in] last
[in] ordered Container will be ordered if true, unordered if false.
References order(), and pushBack().
SAMRAI::hier::BoxContainer::BoxContainer (const Box & box, const bool ordered = false) [explicit]
Create a container with 1 box.
Parameters:
[in] box Box to copy into new container.
[in] ordered Container will be ordered if true, unordered if false.
References order().
SAMRAI::hier::BoxContainer::BoxContainer (const BoxContainer & other)
Copy constructor from another BoxContainer.
All boxes and the ordered/unordered state will be copied to the new BoxContainer.
Parameters:
[in] other
References makeTree(), and order().
SAMRAI::hier::BoxContainer::BoxContainer (const std::vector< tbox::DatabaseBox > & other) [explicit]
Copy constructor from an array of tbox::DatabaseBox objects.
The new BoxContainer will be unordered.
Parameters:
[in] other
References pushBack().
SAMRAI::hier::BoxContainer::BoxContainer (const BoxContainer & other, const BlockId & block_id)
Constructor that copies only Boxes having the given BlockId from the other container.
The unordered or ordered state will be the same as that of the argument container.
Parameters:
[in] other
[in] block_id
References begin(), end(), order(), and pushBack().
SAMRAI::hier::BoxContainer::~BoxContainer ()
The destructor releases all storage.
Member Function Documentation
BoxContainer & SAMRAI::hier::BoxContainer::operator= (const BoxContainer & rhs)
Assignment from other BoxContainer.
All boxes and the ordered/unordered state will be copied to the assigned BoxContainer. Any previous state of the assigned BoxContainer is discarded.
Parameters:
[in] rhs
References clear(), and order().
BoxContainer & SAMRAI::hier::BoxContainer::operator= (const std::vector< tbox::DatabaseBox > & rhs)
Assignment from an array of tbox::DatabaseBox objects.
The assigned BoxContainer will be unordered. Any previous state of the assigned BoxContainer is discarded.
Parameters:
[in] rhs
References clear(), and pushBack().
int SAMRAI::hier::BoxContainer::size () const [inline]
Return the number of boxes in the container.
Returns:
The number of boxes in the container.
Referenced by boxesIntersect(), SAMRAI::geom::CartesianGridGeometry::CartesianGridGeometry(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::hier::AssumedPartition::findOverlaps(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), getTotalSizeOfBoxes(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::BaseGridGeometry::initializePeriodicShift(), SAMRAI::mesh::BoxTransitSet::insertAll(), isIdEqual(), isSpatiallyEqual(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::BaseConnectorAlgorithm::packReferencedNeighbors(), SAMRAI::hier::AssumedPartition::partition(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), print(), SAMRAI::hier::BaseGridGeometry::printClassData(), putToRestart(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), separatePeriodicImages(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::mesh::BalanceUtilities::sortDescendingBoxWorkloads(), and SAMRAI::mesh::BalanceUtilities::spatialBinPack().
bool SAMRAI::hier::BoxContainer::isEmpty () const [inline]
Returns true if there are no boxes in the container.
Archaic syntax. Synonymous with empty(). Retained for backward compatibility.
See also:
empty()
References empty().
bool SAMRAI::hier::BoxContainer::empty () const [inline]
Returns true if there are no boxes in the container.
This version follows the naming standards used in STL.
Returns:
True if the container is empty.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BaseGridGeometry::BaseGridGeometry(), SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::hier::BaseGridGeometry::chopDomain(), coalesce(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::pdat::CellGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::BoxUtilities::extendBoxesToDomainBoundary(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), findOverlapBoxes(), SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), getBoundingBox(), SAMRAI::hier::BoxLevel::getFirstLocalId(), SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::pdat::SideOverlap::getSourceBoxContainer(), SAMRAI::pdat::NodeOverlap::getSourceBoxContainer(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), SAMRAI::pdat::EdgeOverlap::getSourceBoxContainer(), SAMRAI::pdat::CellOverlap::getSourceBoxContainer(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), insert(), insertBefore(), intersectBoxes(), isEmpty(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), makeTree(), SAMRAI::pdat::SideData< TYPE >::packStream(), SAMRAI::pdat::OuterfaceData< TYPE >::packStream(), SAMRAI::pdat::EdgeData< TYPE >::packStream(), pushBack(), pushFront(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), removeIntersections(), removePeriodicImageBoxes(), rotate(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), separatePeriodicImages(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), simplify(), spliceBack(), spliceFront(), SAMRAI::pdat::SideData< TYPE >::unpackStream(), SAMRAI::pdat::FaceData< TYPE >::unpackStream(), SAMRAI::pdat::EdgeData< TYPE >::unpackStream(), and unshiftPeriodicImageBoxes().
const_iterator SAMRAI::hier::BoxContainer::begin () const [inline]
Return a const_iterator pointing to the start of the container.
Returns:
An immutable iterator pointing to the first box.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), SAMRAI::hier::BaseGridGeometry::BaseGridGeometry(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), BoxContainer(), boxesIntersect(), SAMRAI::hier::BoxNeighborhoodCollection::BoxNeighborhoodCollection(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), coalesce(), coarsen(), SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::mesh::BalanceBoxBreaker::computeWidthScore(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), contains(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::BoxContainerSingleBlockIterator::count(), SAMRAI::hier::BoxNeighborhoodCollection::erase(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::BoxLevel::finalize(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), findOverlapBoxes(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), getBoundingBox(), SAMRAI::hier::PatchLevel::getBoxes(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), SAMRAI::hier::BoxLevel::getFirstLocalId(), SAMRAI::hier::BoxLevel::getGlobalBoxes(), SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes(), SAMRAI::hier::BoxLevel::getLocalNumberOfCells(), getOwners(), SAMRAI::pdat::SideOverlap::getSourceBoxContainer(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), SAMRAI::pdat::EdgeOverlap::getSourceBoxContainer(), SAMRAI::hier::BoxLevel::getSpatiallyEqualBox(), getTotalSizeOfBoxes(), grow(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), hasBoxInBlock(), hasOverlap(), SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), SAMRAI::mesh::VoucherTransitLoad::insertAll(), SAMRAI::mesh::BoxTransitSet::insertAll(), intersectBoxes(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::UncoveredBoxIterator::operator=(), order(), SAMRAI::hier::BaseConnectorAlgorithm::packReferencedNeighbors(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::OuterfaceData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream(), SAMRAI::pdat::ArrayData< TYPE >::packStream(), SAMRAI::hier::AssumedPartition::partition(), SAMRAI::xfer::RefinePatchStrategy::postprocessRefineBoxes(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::xfer::RefinePatchStrategy::preprocessRefineBoxes(), SAMRAI::pdat::CellOverlap::print(), print(), SAMRAI::hier::BaseGridGeometry::printClassData(), putToRestart(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::hier::BoxLevel::recursivePrint(), refine(), SAMRAI::hier::BaseGridGeometry::registerNeighbors(), removeIntersections(), removePeriodicImageBoxes(), rotate(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), separatePeriodicImages(), SAMRAI::geom::CartesianGridGeometry::setGeometryData(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::pdat::SideGeometry::setUpOverlap(), SAMRAI::pdat::OutersideGeometry::setUpOverlap(), SAMRAI::pdat::OuternodeGeometry::setUpOverlap(), SAMRAI::pdat::OuterfaceGeometry::setUpOverlap(), SAMRAI::pdat::OuteredgeGeometry::setUpOverlap(), SAMRAI::pdat::NodeGeometry::setUpOverlap(), SAMRAI::pdat::FaceGeometry::setUpOverlap(), SAMRAI::pdat::EdgeGeometry::setUpOverlap(), shift(), SAMRAI::hier::Connector::shrinkWidth(), simplify(), SAMRAI::mesh::BalanceUtilities::sortDescendingBoxWorkloads(), SAMRAI::mesh::BalanceUtilities::spatialBinPack(), spliceFront(), SAMRAI::pdat::ArrayData< TYPE >::sum(), SAMRAI::hier::BaseGridGeometry::transformBoxContainer(), SAMRAI::hier::UncoveredBoxIterator::UncoveredBoxIterator(), SAMRAI::pdat::OutersideData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStream(), SAMRAI::pdat::OuterfaceData< TYPE >::unpackStream(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::unpackStream(), SAMRAI::pdat::ArrayData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStreamAndSum(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum(), SAMRAI::pdat::ArrayData< TYPE >::unpackStreamAndSum(), and unshiftPeriodicImageBoxes().
const_iterator SAMRAI::hier::BoxContainer::end () const [inline]
Return a const_iterator pointing to the end of the container.
Returns:
An immutable iterator pointing beyond the last box.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), SAMRAI::hier::BaseGridGeometry::BaseGridGeometry(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), BoxContainer(), boxesIntersect(), SAMRAI::hier::BoxNeighborhoodCollection::BoxNeighborhoodCollection(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::Connector::checkConsistencyWithHead(), coalesce(), coarsen(), SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::mesh::BalanceBoxBreaker::computeWidthScore(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), contains(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::BoxContainerSingleBlockIterator::count(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::BoxNeighborhoodCollection::erase(), SAMRAI::hier::BoxLevel::eraseBox(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::BoxLevel::finalize(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), findOverlapBoxes(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), getBoundingBox(), SAMRAI::hier::PatchLevel::getBoxes(), SAMRAI::hier::BoxLevel::getBoxStrict(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), SAMRAI::hier::BoxLevel::getFirstLocalId(), getFromRestart(), SAMRAI::hier::BoxLevel::getGlobalBoxes(), SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes(), SAMRAI::hier::BoxLevel::getLocalNumberOfCells(), getOwners(), SAMRAI::pdat::SideOverlap::getSourceBoxContainer(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), SAMRAI::pdat::EdgeOverlap::getSourceBoxContainer(), SAMRAI::hier::BoxLevel::getSpatiallyEqualBox(), getTotalSizeOfBoxes(), grow(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), SAMRAI::hier::BoxLevel::hasBox(), hasBoxInBlock(), hasOverlap(), SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), insertAfter(), SAMRAI::mesh::VoucherTransitLoad::insertAll(), SAMRAI::mesh::BoxTransitSet::insertAll(), SAMRAI::mesh::BoxTransitSet::insertAllWithExistingLoads(), intersectBoxes(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::hier::RealBoxConstIterator::operator++(), SAMRAI::hier::BoxContainerSingleOwnerIterator::operator++(), SAMRAI::hier::BoxContainerSingleBlockIterator::operator++(), SAMRAI::hier::UncoveredBoxIterator::operator=(), order(), SAMRAI::hier::BaseConnectorAlgorithm::packReferencedNeighbors(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::OuterfaceData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream(), SAMRAI::pdat::ArrayData< TYPE >::packStream(), SAMRAI::hier::AssumedPartition::partition(), SAMRAI::xfer::RefinePatchStrategy::postprocessRefineBoxes(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::xfer::RefinePatchStrategy::preprocessRefineBoxes(), SAMRAI::pdat::CellOverlap::print(), print(), SAMRAI::hier::BaseGridGeometry::printClassData(), putToRestart(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::hier::BoxLevel::recursivePrint(), refine(), SAMRAI::hier::BaseGridGeometry::registerNeighbors(), removeIntersections(), removePeriodicImageBoxes(), rotate(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), separatePeriodicImages(), SAMRAI::geom::CartesianGridGeometry::setGeometryData(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::pdat::SideGeometry::setUpOverlap(), SAMRAI::pdat::OutersideGeometry::setUpOverlap(), SAMRAI::pdat::OuternodeGeometry::setUpOverlap(), SAMRAI::pdat::OuterfaceGeometry::setUpOverlap(), SAMRAI::pdat::OuteredgeGeometry::setUpOverlap(), SAMRAI::pdat::NodeGeometry::setUpOverlap(), SAMRAI::pdat::FaceGeometry::setUpOverlap(), SAMRAI::pdat::EdgeGeometry::setUpOverlap(), shift(), SAMRAI::hier::Connector::shrinkWidth(), simplify(), SAMRAI::mesh::BalanceUtilities::sortDescendingBoxWorkloads(), SAMRAI::mesh::BalanceUtilities::spatialBinPack(), SAMRAI::pdat::ArrayData< TYPE >::sum(), SAMRAI::hier::BaseGridGeometry::transformBoxContainer(), SAMRAI::hier::UncoveredBoxIterator::UncoveredBoxIterator(), SAMRAI::pdat::OutersideData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStream(), SAMRAI::pdat::OuterfaceData< TYPE >::unpackStream(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::unpackStream(), SAMRAI::pdat::ArrayData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStreamAndSum(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum(), SAMRAI::pdat::ArrayData< TYPE >::unpackStreamAndSum(), and unshiftPeriodicImageBoxes().
iterator SAMRAI::hier::BoxContainer::begin () [inline]
Return an iterator pointing to the start of the container.
Returns:
A mutable iterator pointing to the first box.
iterator SAMRAI::hier::BoxContainer::end () [inline]
Return an iterator pointing to the end of the container.
Returns:
A mutable iterator pointing beyond the last box.
BoxContainerSingleBlockIterator SAMRAI::hier::BoxContainer::begin (const BlockId & block_id) const
Return a BoxContainerSingleBlockIterator pointing to the first box in the container with the given BlockId.
Parameters:
block_id The BlockId of the boxes we want.
Returns:
A mutable iterator pointing to the first box with the given BlockId.
BoxContainerSingleBlockIterator SAMRAI::hier::BoxContainer::end (const BlockId & block_id) const
Return a BoxContainerSingleBlockIterator pointing to the end of the container.
Parameters:
block_id The BlockId of the boxes we want.
Returns:
A mutable iterator pointing beyond the last box.
BoxContainerSingleOwnerIterator SAMRAI::hier::BoxContainer::begin (const int & owner_rank) const
Return a BoxContainerSingleOwnerIterator pointing to the first box in the container having the given owner.
Parameters:
owner_rank The processaor whose boxes we want.
Returns:
A mutable iterator pointing to the first box having the given owner.
BoxContainerSingleOwnerIterator SAMRAI::hier::BoxContainer::end (const int & owner_rank) const
Return a BoxContainerSingleOwnerIterator pointing to the end of the container.
Parameters:
owner_rank The processaor whose boxes we want.
Returns:
A mutable iterator pointing beyond the last box.
RealBoxConstIterator SAMRAI::hier::BoxContainer::realBegin () const
Return a RealBoxConstIterator pointing to the first real (non-periodic) box in the container.
Returns:
A mutable iterator pointing to the first non-periodic box.
Referenced by SAMRAI::hier::BoxLevel::cacheGlobalReducedData(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::PatchLevel::PatchLevel(), SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel(), and SAMRAI::hier::PatchLevel::setRefinedPatchLevel().
RealBoxConstIterator SAMRAI::hier::BoxContainer::realEnd () const
Return a RealBoxConstIterator pointing to the end of the container.
Returns:
A mutable iterator pointing beyond the last box.
Referenced by SAMRAI::hier::BoxLevel::cacheGlobalReducedData(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelFullFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::PatchLevel::PatchLevel(), SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel(), and SAMRAI::hier::PatchLevel::setRefinedPatchLevel().
const Box& SAMRAI::hier::BoxContainer::front () const [inline]
Returns the first element in the container.
Returns:
A const reference to the first Box in the container.
Referenced by SAMRAI::hier::BoxUtilities::chopBox(), coalesce(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::BoxUtilities::extendBoxesToDomainBoundary(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::pdat::NodeOverlap::getSourceBoxContainer(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), insert(), insertBefore(), intersectBoxes(), pushBack(), pushFront(), simplify(), SAMRAI::mesh::BalanceUtilities::sortDescendingBoxWorkloads(), SAMRAI::mesh::BalanceUtilities::spatialBinPack(), spliceBack(), and spliceFront().
const Box& SAMRAI::hier::BoxContainer::back () const [inline]
Returns the first element in the container.
Returns:
A const reference to the last Box in the container.
Referenced by SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), and SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel().
void SAMRAI::hier::BoxContainer::erase (iterator iter)
Remove the member of the container pointed to by "iter".
Can be called on ordered or unordered containers.
Parameters:
[in] iter
References SAMRAI::hier::Box::getBoxId().
Referenced by coalesce(), erase(), SAMRAI::hier::BoxLevel::eraseBox(), SAMRAI::hier::BoxLevel::eraseBoxWithoutUpdate(), SAMRAI::hier::BoxLevel::finalize(), intersectBoxes(), removeIntersections(), removePeriodicImageBoxes(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), and simplify().
void SAMRAI::hier::BoxContainer::erase (iterator first, iterator last)
Remove the members of the container in the range [first, last).
Can be called on ordered or unordered containers.
Parameters:
[in] first
[in] last
References erase().
void SAMRAI::hier::BoxContainer::clear () [inline]
Removes all the members of the container.
Can be called on unordered or unordered containers. Sets the state to unordered.
Referenced by SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::mesh::BalanceBoxBreaker::burstBox(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::hier::BoxLevel::clear(), SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::hier::PatchLevel::getBoxes(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), intersectBoxes(), operator=(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), SAMRAI::hier::BoxLevel::setParallelState(), and SAMRAI::hier::BaseGridGeometry::setPhysicalDomain().
void SAMRAI::hier::BoxContainer::swap (BoxContainer & other) [inline]
Swap all contents and state with another BoxContainer.
This container and other container exchange all member Boxes and ordered/unordered state.
Parameters:
[in,out] other Other container for swap.
Referenced by SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), SAMRAI::hier::BoxLevel::swap(), and SAMRAI::hier::BoxLevel::swapInitialize().
void SAMRAI::hier::BoxContainer::getOwners (std::set< int > & owners) const
Get all of the ranks that own Boxes in this container.
The rank of every member of this container is inserted into the set.
Parameters:
[out] owners
Precondition:
isOrdered() || for each box in container has valid BoxId
References begin(), end(), and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::grow (const IntVector & ghosts)
Grow boxes in the container by the specified ghost cell width.
Parameters:
[in] ghosts
References begin(), and end().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), and SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput().
void SAMRAI::hier::BoxContainer::shift (const IntVector & offset)
Shift boxes in the container by the specified offset.
Parameters:
[in] offset
References begin(), and end().
Referenced by SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::BaseGridGeometry::registerNeighbors(), and SAMRAI::hier::BaseGridGeometry::transformBoxContainer().
void SAMRAI::hier::BoxContainer::refine (const IntVector & ratio)
Refine boxes in container by the specified refinement ratio.
Parameters:
[in] ratio
References begin(), and end().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry(), SAMRAI::hier::PatchHierarchy::makeRefinedPatchHierarchy(), SAMRAI::hier::BoxLevel::refineBoxes(), and SAMRAI::hier::PatchLevel::setRefinedPatchLevel().
void SAMRAI::hier::BoxContainer::coarsen (const IntVector & ratio)
Coarsen boxes in container by the specified coarsening ratio.
Parameters:
[in] ratio
References begin(), and end().
Referenced by SAMRAI::hier::BoxLevel::coarsenBoxes(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::hier::PatchHierarchy::makeCoarsenedPatchHierarchy(), and SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel().
size_t SAMRAI::hier::BoxContainer::getTotalSizeOfBoxes () const
Count total number of indices in the boxes in the container.
Returns:
Total number of indices of all boxes in the container.
References begin(), end(), and size().
Referenced by SAMRAI::pdat::ArrayData< TYPE >::getDataStreamSize(), SAMRAI::pdat::ArrayData< TYPE >::packStream(), SAMRAI::pdat::ArrayData< TYPE >::unpackStream(), and SAMRAI::pdat::ArrayData< TYPE >::unpackStreamAndSum().
bool SAMRAI::hier::BoxContainer::contains (const Index & idx, const BlockId & block_id) const
Determine if "idx" lies within bounds of boxes in container.
Only boxes of the given BlockId will be checked.
Returns:
true if idx lies within bounds of boxes in container.
Parameters:
[in] idx
[in] block_id
Precondition:
each box in container must have a valid BlockId
References begin(), end(), and TBOX_ASSERT.
Box SAMRAI::hier::BoxContainer::getBoundingBox () const
Returns the bounding box for all the boxes in the container.
Precondition:
!empty()
each Box in container has same BlockId
References begin(), empty(), end(), SAMRAI::hier::Box::getBlockId(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), and SAMRAI::hier::BaseGridGeometry::setPhysicalDomain().
Box SAMRAI::hier::BoxContainer::getBoundingBox (const BlockId & block_id) const
Returns the bounding box for all the boxes in the container having the given BlockId.
Parameters:
[in] block_id
Precondition:
!empty()
References begin(), empty(), end(), TBOX_ERROR, and TBOX_WARNING.
bool SAMRAI::hier::BoxContainer::boxesIntersect () const
Check for non-empty intersection among boxes in container.
Returns:
Returns true if there exists any non-empty intersection among the boxes in the container.
References begin(), end(), and size().
void SAMRAI::hier::BoxContainer::order ()
Changes state of this container to ordered.
If called on a container that is already ordered, nothing changes.
Precondition:
each box in container must have valid and unique BoxId
References begin(), end(), and TBOX_ERROR.
Referenced by BoxContainer(), SAMRAI::hier::BaseGridGeometry::chopDomain(), SAMRAI::hier::BoxLevel::initialize(), insert(), operator=(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), and SAMRAI::hier::BoxLevel::swapInitialize().
void SAMRAI::hier::BoxContainer::unorder ()
Changes state of this container to unordered.
This method can be called on any container.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::hier::BaseGridGeometry::registerNeighbors(), and SAMRAI::hier::AssumedPartitionBox::selfCheck().
bool SAMRAI::hier::BoxContainer::isOrdered () const [inline]
Return whether this container is ordered.
Returns:
True if ordered, false if unordered.
Referenced by SAMRAI::hier::BoxUtilities::chopBoxes(), findOverlapBoxes(), and SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors().
void SAMRAI::hier::BoxContainer::pushFront (const Box & item) [inline]
Adds "item" to the "front" of the container.
Makes "item" the member of the container that will be returned by front() in an unordered container.
Parameters:
[in] item
Precondition:
empty() || (front().getDim() == item.getDim())
!isOrdered()
References empty(), front(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by push_front(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), and SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform().
void SAMRAI::hier::BoxContainer::pushBack (const Box & item) [inline]
Adds "item" to the "end" of the container.
Makes "item" the member of the container that will be returned by back() in an unordered container.
Parameters:
[in] item
Precondition:
empty() || (front().getDim() == item.getDim())
!isOrdered()
References empty(), front(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by BoxContainer(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::pdat::CellGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchLevelEnhancedFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::BoxUtilities::extendBoxesToDomainBoundary(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), findOverlapBoxes(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::PatchLevel::getBoxes(), SAMRAI::hier::BoxLevel::getGlobalBoxes(), SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), insertAfter(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), operator=(), push_back(), SAMRAI::hier::AssumedPartitionBox::recursivePrint(), removeIntersections(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::pdat::OuternodeGeometry::setUpOverlap(), SAMRAI::pdat::NodeGeometry::setUpOverlap(), and simplify().
void SAMRAI::hier::BoxContainer::push_front (const Box & item) [inline]
STL-named version of pushFront().
References pushFront().
void SAMRAI::hier::BoxContainer::push_back (const Box & item) [inline]
STL-named version of pushBack().
References pushBack().
Referenced by SAMRAI::mesh::BalanceBoxBreaker::burstBox(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::hier::AssumedPartitionBox::getAllBoxes(), SAMRAI::hier::AssumedPartition::getAllBoxes(), and SAMRAI::hier::BoxUtilities::growBoxWithinDomain().
void SAMRAI::hier::BoxContainer::insertBefore (iterator iter, const Box & item) [inline]
Add "item" to specific place in the container.
Places "item" immediately before the member of the container pointed to by "iter" in an unordered container.
Parameters:
[in] iter Location to add item before.
[in] item Box to add to container.
Precondition:
empty() || (front().getDim() == item.getDim())
!isOrdered()
References empty(), front(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by insertAfter().
void SAMRAI::hier::BoxContainer::insertAfter (iterator iter, const Box & item) [inline]
Add "item" to specific place in the container.
Places "item" immediately after the member of the container pointed to by "iter" in an unordered container.
Parameters:
[in] iter Location to add item after.
[in] item Box to add to container.
Precondition:
empty() || (front().getDim() == item.getDim())
!isOrdered()
References end(), insertBefore(), pushBack(), and TBOX_ERROR.
Referenced by intersectBoxes().
void SAMRAI::hier::BoxContainer::spliceFront (BoxContainer & boxes) [inline]
Prepends the Boxes in "boxes" to this BoxContainer.
"boxes" will be empty following this operation.
Parameters:
[in] boxes
Precondition:
empty() || (front().getDim() == item.getDim())
!isOrdered()
Postcondition:
boxes.empty()
References begin(), empty(), front(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), SAMRAI::hier::BaseGridGeometry::getDomainOutsideBlock(), and spliceBack().
void SAMRAI::hier::BoxContainer::spliceBack (BoxContainer & boxes) [inline]
Appends the Boxes in "boxes" to this BoxContainer.
"boxes" will be empty following this operation.
Parameters:
[in] boxes
Precondition:
empty() || (front().getDim() == item.getDim())
!isOrdered()
Postcondition:
boxes.empty()
References empty(), front(), spliceFront(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), and SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform().
void SAMRAI::hier::BoxContainer::popFront () [inline]
Remove the first member of the unordered container.
Precondition:
!isOrdered()
References TBOX_ERROR.
Referenced by SAMRAI::hier::BoxUtilities::chopBox(), SAMRAI::hier::BoxUtilities::extendBoxesToDomainBoundary(), and SAMRAI::hier::BoxUtilities::growBoxesWithinDomain().
void SAMRAI::hier::BoxContainer::popBack () [inline]
Remove the last member of the unordered container.
Precondition:
!isOrdered()
References TBOX_ERROR.
void SAMRAI::hier::BoxContainer::simplify ()
Place the boxes in the container into a canonical ordering.
The canonical ordering for boxes is defined such that boxes that lie next to each other in higher directions are coalesced together before boxes that lie next to each other in lower directions. This ordering provides a standard representation that can be used to compare box containers. The canonical ordering also does not allow any overlap between the boxes in the container. This routine is potentially expensive, since the running time is for N boxes. None of the domain calculus routines call simplify(); all calls to simplify the boxes must be explicit. Note that this routine is distinct from coalesce(), which is not guaranteed to produce a canonical ordering.
Precondition:
!isOrdered()
empty() || all Boxes in container have same BlockId
References begin(), SAMRAI::hier::Box::empty(), empty(), end(), erase(), front(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::lower(), pushBack(), TBOX_ASSERT, TBOX_ERROR, and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), and SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput().
void SAMRAI::hier::BoxContainer::coalesce ()
Combine any boxes in the container which may be coalesced.
Two boxes may be coalesced if their union is a box (recall that boxes are not closed under index set unions). Empty boxes in the container are removed during this process. Note that this is potentially an expensive calculation (e.g., it will require box comparisons for a box container with boxes in the worst possible case). So this routine should be used sparingly. Also note that this routine is different than simplify() since it does not produce a canonical ordering. In particular, this routine processes the boxes in the order in which they appear in the container, rather than attempting to coalesce boxes along specific coordinate directions before others.
Precondition:
!isOrdered()
empty() || all Boxes in container have same BlockId
References begin(), empty(), end(), erase(), front(), SAMRAI::hier::Box::getBlockId(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), and SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput().
void SAMRAI::hier::BoxContainer::rotate (const Transformation::RotationIdentifier rotation_ident)
Rotate boxes in container according to a RotationIdentifier.
Note:
Works only in 2D or 3D.
Parameters:
[in] rotation_ident
Precondition:
each Box in container has dim 2 or 3
each Box in container has same BlockId
References begin(), empty(), end(), SAMRAI::tbox::Dimension::getValue(), NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::hier::BaseGridGeometry::registerNeighbors(), and SAMRAI::hier::BaseGridGeometry::transformBoxContainer().
void SAMRAI::hier::BoxContainer::removeIntersections (const Box & takeaway)
Remove from each box the portions that intersect takeaway.
This operation can be thought of as a set difference defined over the abstract AMR box index space. Performing the set difference will require time for a container with boxes. For each box, b, in this container this operation computes b-(b^takeaway) where '^' indicates intersection.
Parameters:
[in] takeaway What to exclude from each box in the container.
Precondition:
!isOrdered()
References begin(), empty(), end(), erase(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::intersects(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::CellGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), removeIntersections(), and SAMRAI::hier::AssumedPartitionBox::selfCheck().
void SAMRAI::hier::BoxContainer::removeIntersections (const BoxContainer & takeaway)
Remove from each box portions intersecting boxes in takeaway.
For each box, b, in this container and for each box, t, in takeaway this operation computes b-(b^t) where '^' indicates intersection.
This only works if all boxes in this BoxContainer and the takeaway BoxContainer have the same BlockId. An error will occur otherwise.
Parameters:
[in] takeaway What to exclude from each box in the container.
Precondition:
!isOrdered()
References begin(), empty(), end(), removeIntersections(), and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::removeIntersections (const IntVector & refinement_ratio, const BoxContainer & takeaway, const bool include_singularity_block_neighbors = false)
Remove from each box portions intersecting boxes in takeaway.
Uses refinement ratio and grid geometry to handle intersections across block boundaries if needed.
Parameters:
[in] refinement_ratio All boxes in this BoxContainer are assumed to exist in index space that has this refinement ratio relative to the coarse-level domain.
[in] takeaway The boxes to take away from this BoxContainer. An error will occur if makeTree with a non-null BaseGridGeometry argument has not been previously called on this container.
[in] include_singularity_block_neighbors If true, intersections with neighboring blocks that touch only across an enhanced connectivity singularity will be removed. If false, those intersections are ignored.
Precondition:
!isOrdered()
takeaway.hasTree()
References begin(), empty(), end(), and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::removeIntersections (const Box & box, const Box & takeaway)
Remove from box the portions intersecting takeaway.
This is special version for the case where the container is empty initially. Upon completion this container contains the result of the removal from box of the intersection of box with takeaway. If the boxes do not intersect, box is simply added to this container. This routine is primarily suited for applications which are looking only for the intersection of two boxes. This operation computes box-(box^takeaway) where '^' indicates intersection.
Parameters:
[in] box
[in] takeaway
Precondition:
!isOrdered()
empty()
box.getBlockId() == takeaway.getBlockId()
References empty(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::intersects(), pushBack(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::intersectBoxes (const Box & keep)
Keep the intersection of the container's boxes and keep.
Performing the intersection will require time for a container with boxes. The complement of removeIntersections.
Parameters:
[in] keep
Precondition:
!isOrdered()
References begin(), empty(), end(), erase(), SAMRAI::hier::Box::intersect(), and TBOX_ERROR.
Referenced by SAMRAI::pdat::SecondLayerNodeVariableFillPattern::calculateOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::calculateOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::calculateOverlap(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::CellGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchInteriorVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::xfer::BoxGeometryVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerCellVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerCellNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), intersectBoxes(), and SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput().
void SAMRAI::hier::BoxContainer::intersectBoxes (const BoxContainer & keep)
Keep the intersection of the container's boxes and keep's boxes.
Intersect the boxes in the current container against the boxes in the specified container. The intersection calculation will require time for containers with boxes. The complement of removeIntersections.
This only works if all boxes in this BoxContainer and the keep BoxContainer have the same BlockId. An error will occur otherwise.
Parameters:
[in] keep
Precondition:
!isOrdered()
References begin(), empty(), end(), erase(), insertAfter(), SAMRAI::hier::Box::intersect(), intersectBoxes(), and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::intersectBoxes (const IntVector & refinement_ratio, const BoxContainer & keep, bool include_singularity_block_neighbors = false)
Keep the intersection of the container's boxes and keep's boxes.
Uses refinement ratio and grid geometry to handle intersections across block boundaries if needed.
Parameters:
[in] refinement_ratio All boxes in this BoxContainer are assumed to exist in index space that has this refinement ratio relative to the coarse-level domain.
[in] keep The boxes to intersect with this BoxContainer. An error will occur if makeTree with a non-null BaseGridGeometry argument has not been previously called on this container.
[in] include_singularity_block_neighbors If true, intersections with neighboring blocks that touch only across an enhanced connectivity singularity will be kept. If false, those intersections are ignored.
Precondition:
!isOrdered()
keep.hasTree()
References begin(), clear(), SAMRAI::hier::Box::empty(), empty(), end(), erase(), front(), SAMRAI::hier::Box::getBlockId(), insertAfter(), SAMRAI::hier::Box::intersect(), and TBOX_ERROR.
bool SAMRAI::hier::BoxContainer::insert (const Box & box)
Insert a single Box.
The insert methods are used to add Boxes to ordered containers. They may be called on an unordered container only if the size of the unordered container is zero. If called on such an empty unordered container, the state of the container will be changed to ordered. A run-time error will occur if called on a non-empty unordered container.
The Box will be added to the container unless the container already contains a Box with the same BoxId. If a Box with the same BoxId does already exist in the contianer, the container will not be changed.
Returns:
True if the container did not already have a Box with the same BoxId, false otherwise.
Parameters:
[in] box Box to attempt to insert into the container.
Precondition:
box.getBoxId().isValid()
empty() || (front().getDim() == box.getDim())
empty() || isOrdered()
References empty(), front(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxId::isValid(), SAMRAI::hier::Box::lockId(), order(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxLevel::addBoxWithoutUpdate(), SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), findOverlapBoxes(), SAMRAI::hier::AssumedPartitionBox::findOverlaps(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), getFromRestart(), SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors(), SAMRAI::hier::BoxNeighborhoodCollection::getPeriodicNeighbors(), SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors(), and unshiftPeriodicImageBoxes().
BoxContainer::iterator SAMRAI::hier::BoxContainer::insert (iterator position, const Box & box)
Insert a single Box.
The Box will be added to the container unless the container already contains a Box with the same BoxId. If a Box with the same BoxId does already exist in the contianer, the container will not be changed.
This version of insert includes an iterator argument pointing somewhere in this container. This iterator indicates a position in the ordered container where the search for the proper place to insert the given Box will begin.
The iterator argument does not determine the place the Box will end up in the ordered container, as that is always determined by BoxId; it is intended only to provide a means of optimization when the calling code knows something about the ordering of the container.
Returns:
iterator pointing to the newly-added Box if the container did not already have a Box with the same BoxId. If the container did have a Box with the same BoxId, the returned iterator points to that Box.
Parameters:
[in] position Location to begin searching for place to insert Box
[in] box Box to attempt to insert into the container
Precondition:
box.getBoxId().isValid()
box.getBlockId() != BlockId::invalidId()
empty() || (front().getDim() == box.getDim())
empty() || isOrdered()
References empty(), front(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BlockId::invalidId(), SAMRAI::hier::BoxId::isValid(), order(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::insert (const_iterator first, const_iterator last)
Insert all Boxes within a range.
Boxes in the range [first, last) are added to the ordered container, as long as they do not have a BoxId matching that of a Box already in the container.
Parameters:
[in] first
[in] last
Precondition:
empty() || isOrdered()
for each box in [first, last), box.getBoxId().isValid() && (empty || front().getDim() == box.getDim())
References empty(), front(), order(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
iterator SAMRAI::hier::BoxContainer::find (const Box & box) const [inline]
Find a box in an ordered container.
Search for a Box having the same BoxId as the given box argument. This may only be called on an ordered container.
Returns:
If a Box with the same BoxId as the argument is found, the iterator points to that Box in this container, otherwise end() for this container is returned.
Parameters:
[in] box Box serving as key for the find operation. Only its BoxId is compared to members of this container.
Precondition:
isOrdered()
References TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::hier::Connector::checkConsistencyWithHead(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::hier::Connector::doTransposeWork(), SAMRAI::hier::BoxLevel::eraseBox(), SAMRAI::hier::SingularityFinder::findSingularities(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::BoxLevel::getBoxStrict(), SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::mesh::BoxTransitSet::insertAllWithExistingLoads(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), and SAMRAI::hier::AssumedPartitionBox::selfCheck().
iterator SAMRAI::hier::BoxContainer::lowerBound (const Box & box) const [inline]
Get lower bound iterator for a given Box.
This may only be called on an ordered container.
Returns:
iterator pointing to the first member of this container with a BoxId value greater than or equal to the BoxId of the argument Box.
Parameters:
[in] box Box serving as key for the lower bound search.
Precondition:
isOrdered()
References TBOX_ERROR.
iterator SAMRAI::hier::BoxContainer::upperBound (const Box & box) const [inline]
Get upper bound iterator for a given Box.
Returns:
iterator pointing to the first member of this container with a BoxId value greater than the BoxId of the argument Box. Will return end() if there are no members with a greater BoxId value.
Parameters:
[in] box Box serving as key for the upper bound search.
Precondition:
isOrdered()
References TBOX_ERROR.
int SAMRAI::hier::BoxContainer::erase (const Box & box)
Erase a Box from the container.
If a member of the container has the same BoxId as the argument Box, it will be erased from the container. If no such member is found, the container is unchanged.
Returns:
1 if a Box is erased, 0 otherwise.
Parameters:
[in] box Box serving as key to find a Box to be erased.
Precondition:
isOrdered()
References SAMRAI::hier::Box::getBoxId(), and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::separatePeriodicImages (std::vector< Box > & real_box_vector, std::vector< Box > & periodic_image_box_vector, const PeriodicShiftCatalog & shift_catalog) const
Copy the members of this BoxContainer into two vector<Box> objects, one containing real Boxes and one containing their periodic images.
Put the results in the output vectors. For flexibility and efficiency, the output containers are NOT cleared first, so users may want to clear them before calling this method.
Parameters:
[out] real_box_vector
[out] periodic_image_box_vector
[in] shift_catalog PeriodicShiftCatalog object that maps the PeriodicId to a specific shift.
Precondition:
isOrdered()
References begin(), empty(), end(), SAMRAI::hier::Box::getPeriodicId(), SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber(), size(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap().
void SAMRAI::hier::BoxContainer::removePeriodicImageBoxes ()
Any members of this container that are periodic images will be erased.
Precondition:
empty() || isOrdered()
References begin(), empty(), end(), erase(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevel::removePeriodicImageBoxes().
void SAMRAI::hier::BoxContainer::unshiftPeriodicImageBoxes (BoxContainer & output_boxes, const IntVector & refinement_ratio, const PeriodicShiftCatalog & shift_catalog) const
Place unshifted versions of Boxes into a BoxContainer.
For all members of this container that are periodic images, create an unshifted copy the member box and add insert it the output container. Additionally, insert all members of the container that are not periodic images to the output container.
For flexibility and efficiency, the output container is NOT cleared first, so users may want to clear it before calling this method.
Parameters:
[out] output_boxes
[in] refinement_ratio Refinement ratio where the boxes live.
[in] shift_catalog PeriodicShiftCatalog object that maps the PeriodicId to a specific shift.
Precondition:
isOrdered()
References begin(), empty(), end(), SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber(), insert(), and TBOX_ERROR.
Referenced by SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), and SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc().
bool SAMRAI::hier::BoxContainer::operator== (const BoxContainer & rhs) const
Equality operator.
If the container is ordered, then this checks if all boxes have identical BoxIds and are spatially equal to the boxes in rhs. If unordered, then this checks only the spatial equality of the boxes.
Addtionally to be considered equal, both containers must contain the same number of boxes and have the same ordered/unordered state.
Returns:
true only if the containers meet the equality conditions.
Parameters:
[in] rhs
References isIdEqual(), and isSpatiallyEqual().
bool SAMRAI::hier::BoxContainer::isIdEqual (const BoxContainer & other) const
Check for equality of BoxIds in ordered containers.
An error will occur if this operator is called with either BoxContainer in unordered state.
Returns:
true if both containers are the same size and the boxes have identical BoxIds.
Parameters:
[in] other
Precondition:
isOrdered() && other.isOrdered()
References size(), and TBOX_ERROR.
Referenced by operator==().
bool SAMRAI::hier::BoxContainer::isSpatiallyEqual (const BoxContainer & other) const
Check for spatial equality of all boxes.
Returns:
true if both containers are the same size and the boxes are spatially equal (same extents and same BlockId).
Parameters:
[in] other
References size().
Referenced by operator==().
bool SAMRAI::hier::BoxContainer::operator!= (const BoxContainer & rhs) const [inline]
Inequality operator.
Returns:
Return true if operator== would return false.
Parameters:
[in] rhs
void SAMRAI::hier::BoxContainer::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Write the BoxContainer to a restart database.
References begin(), end(), and size().
Referenced by SAMRAI::hier::BoxLevel::putToRestart(), and SAMRAI::hier::BaseGridGeometry::putToRestart().
void SAMRAI::hier::BoxContainer::getFromRestart (tbox::Database & restart_db)
Read the BoxContainer from a restart database.
References end(), SAMRAI::tbox::Database::getDatabaseBoxVector(), SAMRAI::tbox::Database::getInteger(), SAMRAI::tbox::Database::getIntegerVector(), insert(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::setId(), and TBOX_ERROR.
SAMRAI::hier::BoxContainer::operator std::vector< tbox::DatabaseBox > () const
Conversion from BoxContainer to std::vector<tbox::DatabaseBox>.
void SAMRAI::hier::BoxContainer::print (std::ostream & os = tbox::plog, const std::string & border = std::string()) const
Print each box in the container to the specified output stream.
Parameters:
[in] os
[in] border
References begin(), end(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), and size().
Referenced by SAMRAI::hier::operator<<(), and SAMRAI::hier::BaseGridGeometry::printClassData().
BoxContainer::Outputter SAMRAI::hier::BoxContainer::format (const std::string & border = std::string(), int detail_depth = 2) const
Return a object to that can format the BoxContainer for inserting into output streams.
Usage example (printing with a tab indentation):
    *    cout << "my boxes:\n" << boxes.format("\t") << endl;
    *
Parameters:
[in] border Left border of the output
[in] detail_depth How much detail to print.
Referenced by SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::hier::BaseConnectorAlgorithm::packReferencedNeighbors(), SAMRAI::hier::AssumedPartitionBox::recursivePrint(), and SAMRAI::hier::AssumedPartitionBox::selfCheck().
void SAMRAI::hier::BoxContainer::makeTree (const BaseGridGeometry * grid_geometry = 0, const int min_number = 10) const
Create a search tree representation of the boxes in this container.
If the size of this container is greater than the min_number argument, then an internal BoxTree representation of the boxes will be created and held by the container.
This method may only be used if all members of this container have the same BlockId. An assertion failure will occur if this condition is not met.
The building of the tree is an O(N log(N)) operation, but it reduces the cost of the search methods findOverlapBoxes() and hasOverlap() to O(log(N)), rather than O(N). The tree representation is intended for when these search methods are called multiple times on the same BoxContainer which is not changing, so that the benefit of more efficient search should outweigh the cost of building the tree.
The min_number argument is used to indicate a container size below which there is no benefit from building the tree, so no tree is created when the size is less than or equal to this value.
If a tree representation has been created via this method, and then any other BoxContainer method is called that changes the container by adding or removing boxes, or by changing the spatial coordinates of the boxes, the tree representation is destroyed.
A non-null pointer to a BaseGridGeometry must be provided if this container is going to be used in any of the methods that handle multiblock transformations. If this container is used only in a single-block context, no BaseGridGeometry argument is necessary.
Note:
The grid_geometry argument is required for multiblock. It must be the GridGeometry from which the Boxes stored in the container came from.
Parameters:
[in] grid_geometry To handle multiblock transformations if needed.
[in] min_number
Precondition:
min_number > 0
References empty(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), BoxContainer(), SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), and SAMRAI::hier::AssumedPartitionBox::selfCheck().
bool SAMRAI::hier::BoxContainer::hasTree () const [inline]
Query if the search tree representation exists.
Referenced by SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes().
bool SAMRAI::hier::BoxContainer::hasBoxInBlock (const BlockId & block_id) const
Query if this BoxContainer contains any Box with the given BlockId.
This is an efficient query if the the tree representation of this container has been constructed. If not, it requires a linear search over the entire container and may not be efficient.
References begin(), and end().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary().
void SAMRAI::hier::BoxContainer::findOverlapBoxes (BoxContainer & overlap_boxes, const Box & box) const
Find all boxes that intersect with a given box.
Every Box in this BoxContainer that intersects with the box argument will be added to the overlap_boxes output container. The output container will retain the same ordered/unordered state that it had prior to being passed into this method.
If this method is used multiple times on the same BoxContainer, it is recommended for efficiency's sake to call makeTree() on this BoxContainer before calling this method.
Parameters:
[out] overlap_boxes
[in] box
References begin(), end(), insert(), SAMRAI::hier::Box::intersects(), isOrdered(), and pushBack().
Referenced by SAMRAI::mesh::TileClustering::findBoxesContainingTags(), and SAMRAI::hier::AssumedPartitionBox::selfCheck().
void SAMRAI::hier::BoxContainer::findOverlapBoxes (std::vector< const Box * > & overlap_boxes, const Box & box) const
Find all boxes that intersect with a given box.
A pointer to every Box in this BoxContainer that intersects with the box argument will be copied to the overlap_boxes output vector. The vector is not sorted in any way.
If this method is used multiple times on the same BoxContainer, it is recommended for efficiency's sake to call makeTree() on this BoxContainer before calling this method.
Parameters:
[out] overlap_boxes
[in] box
Precondition:
!hasTree() || (d_tree->getNumberBlocksInTree() == 1)
References begin(), end(), SAMRAI::hier::Box::intersects(), and TBOX_ASSERT.
void SAMRAI::hier::BoxContainer::findOverlapBoxes (BoxContainer & overlap_boxes, const Box & box, const IntVector & refinement_ratio, bool include_singularity_block_neighbors = false) const
Find all boxes that intersect with a given box.
Uses refinement ratio and grid geometry to handle intersections across block boundaries if needed. The makeTree method with a non-null BaseGridGeometry pointer must be called on this container before calling this version of findOverlapBoxes.
Every Box in this BoxContainer that intersects with the box argument will be copied to the overlap_boxes output container. The output container will retain the same ordered/unordered state that it had prior to being passed into this method.
Parameters:
[out] overlap_boxes
[in] box
[in] refinement_ratio All boxes in this BoxContainer are assumed to exist in index space that has this refinement ratio relative to the coarse-level domain.
[in] include_singularity_block_neighbors If true, intersections with neighboring blocks that touch only across an enhanced connectivity singularity will be added to output. If false, those intersections are ignored.
Precondition:
hasTree()
References empty(), and TBOX_ERROR.
void SAMRAI::hier::BoxContainer::findOverlapBoxes (std::vector< const Box * > & overlap_boxes, const Box & box, const IntVector & refinement_ratio, bool include_singularity_block_neighbors = false) const
References empty(), and TBOX_ERROR.
bool SAMRAI::hier::BoxContainer::hasOverlap (const Box & box) const
Determine if a given box intersects with the BoxContainer.
If this method is used multiple times on the same BoxContainer, it is recommended for efficiency's sake to call makeTree() on this BoxContainer before calling this method.
This only works if all boxes in this BoxContainer have the same BlockId, and the argument box also has that same BlockId. An error will occur if these conditions are not met.
Returns:
True if box intersects with any member of the BoxContainer, false otherwise.
Parameters:
[in] box
References begin(), end(), and SAMRAI::hier::Box::intersects().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages(), and SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships().
Friends And Related Function Documentation
friend class BoxContainerIterator [friend]
friend class BoxContainerConstIterator [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxContainer.h
source/SAMRAI/hier/BoxContainer.C