SAMRAI: SAMRAI::hier::PatchHierarchy Class Reference
SAMRAI::hier::PatchHierarchy Class Reference
Class PatchHierarchy maintains the patch levels that define the AMR hierarchy.
#include <source/SAMRAI/hier/PatchHierarchy.h>
Classes
class ConnectorWidthRequestorStrategy
Abstract base class defining a Strategy pattern interface for providing Connector width information to the PatchHierarchy.
Public Member Functions
PatchHierarchy (const std::string &object_name, const boost::shared_ptr< BaseGridGeometry > &geometry, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
Constructor initializing the state of PatchHierarchy.
~PatchHierarchy ()
Destructor for PatchHierarchy.
boost::shared_ptr< PatchHierarchy > makeRefinedPatchHierarchy (const std::string &fine_hierarchy_name, const IntVector &refine_ratio) const
Create a refined version of this patch hierarchy.
boost::shared_ptr< PatchHierarchy > makeCoarsenedPatchHierarchy (const std::string &coarse_hierarchy_name, const IntVector &coarsen_ratio) const
Create a coarsened version of this patch hierarchy.
virtual void makeNewPatchLevel (const int level_number, const BoxLevel &new_box_level)
Construct new PatchLevel in hierarchy at given level number.
virtual void makeNewPatchLevel (const int level_number, const boost::shared_ptr< BoxLevel > new_box_level)
Construct new PatchLevel in hierarchy at given level number.
virtual void removePatchLevel (const int level)
Remove a patch level.
boost::shared_ptr< PatchLevel > getPatchLevel (const int level) const
Get a PatchLevel from the hierarchy.
boost::shared_ptr
< PatchDescriptor > getPatchDescriptor () const
Get the patch descriptor.
bool levelExists (const int level) const
Check if the level exists.
bool finerLevelExists (const int level) const
Check if a finer level exists.
int getNumberOfLevels () const
Get the number of levels in the hierarchy.
int getFinestLevelNumber () const
Get the finest level in the hierarchy.
size_t getNumberBlocks () const
bool levelCanBeRefined (const int level_number) const
Check whether specified level can be refined.
const boost::shared_ptr
< BoxLevel > & getBoxLevel (const int level) const
Return a pointer to the specified BoxLevel.
const BoxLevel & getDomainBoxLevel () const
Access the domain description as a BoxLevel.
const tbox::SAMRAI_MPI & getMPI () const
Returns the SAMRAI_MPI communicator over which the domain BoxLevel is distributed.
void setPatchFactory (const boost::shared_ptr< PatchFactory > &factory)
Set the factory used to create patch objects.
void setPatchLevelFactory (const boost::shared_ptr< PatchLevelFactory > &factory)
Set the factory used to create patch level objects.
boost::shared_ptr
< BaseGridGeometry > getGridGeometry () const
Get the grid geometry.
void logMetadataStatistics (const char *note, int ln, int cycle, double level_time, bool log_fine_connector, bool log_coarse_connector) const
Log metadata statistics.
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Writes the state of the PatchHierarchy object and the PatchLevels it contains to the restart database.
void initializeHierarchy ()
Read in the entire hierarchy from the restart database.
const tbox::Dimension & getDim () const
Get the dimension of this object.
int recursivePrint (std::ostream &os, const std::string &border=std::string(), int depth=0)
Print a patch hierarchy to a specified degree of detail.
const std::string & getObjectName () const
Get the name of this object.
UncoveredBoxIterator beginUncovered ()
Returns an iterator to the first uncovered Box in this hierarchy.
UncoveredBoxIterator endUncovered ()
Returns an iterator to the last uncovered Box in this hierarchy.
Methods related to the hierarchy parameters
void setMaxNumberOfLevels (int max_levels)
Set the maximum number of levels allowed on the hierarchy.
int getMaxNumberOfLevels () const
Get the maximum number of levels allowed on the hierarchy.
void setRatioToCoarserLevel (const IntVector &ratio, int level)
Set the ratio to coarser level.
const IntVector & getRatioToCoarserLevel (int level) const
Get the ratio between specified level and next coarser level.
void setSmallestPatchSize (const IntVector &size, int level)
Set the smallest patch size on the given level.
const IntVector & getSmallestPatchSize (int level) const
Get the smallest patch size on the given level.
void setLargestPatchSize (const IntVector &size, int level)
Set the largest patch size on the given level.
const IntVector & getLargestPatchSize (int level) const
Get the largest patch size.
int getProperNestingBuffer (int ln) const
Get the proper nesting buffer for a specific level.
bool allowPatchesSmallerThanGhostWidth () const
Get flag for allowing patches smaller than ghost width.
bool allowPatchesSmallerThanMinimumSize () const
Get flag for allowing patches smaller than user-provided minimum size.
Connector width coordination between hierarchy builders and users.
void registerConnectorWidthRequestor (const ConnectorWidthRequestorStrategy &cwrs)
Register the ConnectorWidthRequestorStrategy with the hierarchy.
IntVector getRequiredConnectorWidth (int base_ln, int head_ln, bool commit=false) const
Get the width required of the Connector from the base to the head levels, as specified by the given level numbers.
static void registerAutoConnectorWidthRequestorStrategy (const ConnectorWidthRequestorStrategy &cwrs)
Add a ConnectorWidthRequestorStrategy implementation to the set of implementations that, by default, gets registered to all PatchHierarchy objects.
Detailed Description
Class PatchHierarchy maintains the patch levels that define the AMR hierarchy.
Input Parameters
For ratio_to_coarser, smallest_patch_size, and largest_patch_size assume that we have N levels numbered coarsest to finest as 0,..., N-1. For these inputs, the value for a level must be given as ``level_n = value'' where n is the level number. When more values are given than needed for the maximum number of levels, extra values are ignored. When fewer values are given, the last value provided will be used on each level without a specified input value. See example input below.
Definitions:
max_levels specifies maximum number of levels allowed in the AMR patch hierarchy.
ratio_to_coarser A set of max_levels - 1 integer arrays each with length = DIM, each of which indicates the ratio of the index space of a patch level to that of the next coarser level in the hierarchy. The input is given for each level n, where n (= 1, 2,..., N-1) is the level number.
smallest_patch_size A set of max_levels integer vectors each with length = DIM, each of which indicates the size of smallest patch allowed on the level in the hierarchy. The smallest patch allowed must be at least as large as the maximum ghost cell width for all variables in the problem. If some smaller patch size is given in input, then it will be overridden by the maximum ghost width. If no input is given, a default of the maximum ghost cell width over all variables is used. The input is given for each level n, where n (= 0, 1,..., N-1) is the level number.
largest_patch_size A set of max_levels integer vectors each with length = DIM, each of which indicates the size of largest patch allowed on the level in the hierarchy. Negative values for patch size corresponds to no upper limit on patch size. The input is given for each level n, where n (= 0, 1,..., N-1) is the level number.
proper_nesting_buffer A set of max_levels - 1 integer values specifying the number of coarse cells by which the next finer level is nested within the interior of the union of the patches on the next coarser level. The input is given for each level n, where n (= 0, 1,..., N-2) is the level number.
allow_patches_smaller_than_ghostwidth indicates whether patches are allowed that are smaller than the maximum variable ghost width along some coordinate direction. Recall that when a smallest patch size provided in the input file is smaller than the maximum ghost width of all the registered variables, then by default the smallest patch size will be set to the maximum ghost width. Set this flag to TRUE to override this default behavior and to allow the smallest patch size given in the input to remain in effect.
allow_patches_smaller_than_minimum_size_to_prevent_overlaps indicates whether patches are allowed to be smaller than the minimum patch size to prevent overlapping patches. In order to enforce minimum patch size restrictions, boxes may be grown during adaptive gridding operations. This may lead to patches whose boxes overlap. This may be a problem for some applications. If overlaps are undesirable and you are willing to relax the minimum size constraints, set this parameter TRUE.
Details:
parameter
type
default
range
opt/req
behavior on restart
max_levels
int
>0
1
opt
May be made smaller by input db on restart
ratio_to_coarser
max_levels-1 int[]
all values 1
all values >0
opt
May not be modified by input db on restart
smallest_patch_size
max_levels int[]
all values 1
all values >0
opt
Parameter read from restart db may be overridden by input db
largest_patch_size
max_levels int[]
all values max int
each value >=0 must be >= corresponding smallest_patch_size value
opt
Parameter read from restart db may be overridden by input db
proper_nesting_buffer
int[]
all values 1
all values >=0
opt
May not be modified by input db on restart
allow_patches_smaller_than_ghostwidth
bool
FALSE
TRUE, FALSE
opt
May not be modified by input db on restart
allow_patches_smaller_than_minimum_size_to_prevent_overlap
bool
FALSE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
The following represents sample input data for a three-dimensional problem:
   // Required input: maximum number of levels in patch hierarchy
   max_levels = 4
   // Required input: vector ratio between each finer level and next coarser
   ratio_to_coarser {
      level_1 = 2, 2, 2
      level_2 = 2, 2, 2
      level_3 = 4, 4, 4
   }
   // Optional input: int vector for largest patch size on each level.
   largest_patch_size {
      level_0 = 40, 40, 40
      level_1 = 30, 30, 30
      // all finer levels will use same values as level_1...
   }
   // Optional input: int vector for smallest patch size on each level.
   smallest_patch_size {
      level_0 = 16, 16, 16
      // all finer levels will use same values as level_0...
   }
   // Optional input:  buffer of one cell used on each level
   proper_nesting_buffer = 1
See also:
PatchLevel
PatchDescriptor
Constructor & Destructor Documentation
SAMRAI::hier::PatchHierarchy::PatchHierarchy (const std::string & object_name, const boost::shared_ptr< BaseGridGeometry > & geometry, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>())
Constructor initializing the state of PatchHierarchy.
The constructor for the PatchHierarchy initializes the number of levels to zero, sets the geometry for the PatchHierarchy, and registers the PatchHierarchy for restart with the specified name.
Parameters:
[in] object_name
[in] geometry
[in] input_db Input database specifying hierarchy parameters.
Precondition:
!object_name.empty()
geometry
References getGridGeometry(), SAMRAI::tbox::RestartManager::getManager(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::hier::BoxLevel::GLOBALIZED, and TBOX_ASSERT.
Referenced by makeCoarsenedPatchHierarchy(), and makeRefinedPatchHierarchy().
SAMRAI::hier::PatchHierarchy::~PatchHierarchy ()
Destructor for PatchHierarchy.
References SAMRAI::tbox::RestartManager::getManager().
Member Function Documentation
boost::shared_ptr< PatchHierarchy > SAMRAI::hier::PatchHierarchy::makeRefinedPatchHierarchy (const std::string & fine_hierarchy_name, const IntVector & refine_ratio) const
Create a refined version of this patch hierarchy.
Create and return pointer to a patch hierarchy that is a refined version of this patch hierarchy object. That is, the data members of the returned patch hierarchy are set by refining information on this hierarchy using the given ratio. The refined hierarchy will cover the same physical space as this hierarchy and will have the same number of levels and same mapping of patches to processors on each level. However, the index space of each level will be refined by the specified ratio.
Note:
This function does not allocate patch data so this must be done before any data operations can be performed on the new hierarchy.
Returns:
The refined patch hierarchy.
Parameters:
[in] fine_hierarchy_name
[in] refine_ratio
Precondition:
getDim() == refine_ratio.getDim()
!fine_hierarchy_name.empty()
fine_hierarchy_name != getObjectName()
refine_ratio > IntVector::getZero(refine_ratio.getDim())
References getBoxLevel(), SAMRAI::hier::IntVector::getDim(), getMPI(), SAMRAI::hier::IntVector::getZero(), PatchHierarchy(), SAMRAI::hier::BoxContainer::refine(), TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY1.
boost::shared_ptr< PatchHierarchy > SAMRAI::hier::PatchHierarchy::makeCoarsenedPatchHierarchy (const std::string & coarse_hierarchy_name, const IntVector & coarsen_ratio) const
Create a coarsened version of this patch hierarchy.
Create and return pointer to a patch hierarchy that is a coarsened version of this patch hierarchy object. That is, the data members of the returned patch hierarchy are set by coarsening information on this hierarchy by the given ratio. The coarsened hierarchy will cover the same physical space as this hierarchy and will have the same number of levels and same mapping of patches to processors on each level. However, the index space of each level will be coarsened by the specified ratio.
Note:
This function does not allocate patch data so this must be done before any data operations can be performed on the new hierarchy.
Returns:
boost::shared_ptr to the coarsened patch hierarchy.
Parameters:
[in] coarse_hierarchy_name
[in] coarsen_ratio
Precondition:
getDim() == coarsen_ratio.getDim()
!coarse_hierarchy_name.empty()
coarse_hierarchy_name != getObjectName()
coarsen_ratio > IntVector::getZero(coarsen_ratio.getDim())
References SAMRAI::hier::BoxContainer::coarsen(), getBoxLevel(), SAMRAI::hier::IntVector::getDim(), getMPI(), SAMRAI::hier::IntVector::getZero(), PatchHierarchy(), TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY1.
void SAMRAI::hier::PatchHierarchy::makeNewPatchLevel (const int level_number, const BoxLevel & new_box_level) [virtual]
Construct new PatchLevel in hierarchy at given level number.
This method results in the new PatchLevel making a COPY of the supplied BoxLevel. If the caller intends to modify the supplied BoxLevel for other purposes after making the new PatchLevel, then this method must be used rather than the method taking a boost::shared_ptr<BoxLevel>.
Boxes, their mappings and the refinement ratio are obtained from new_box_level.
Parameters:
[in] level_number
[in] new_box_level
Precondition:
getDim() == new_box_level.getDim()
level_number >= 0 && ln < getMaxNumberOfLevels()
new_box_level.getRefinementRatio() > IntVector::getZero(getDim())
References SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ERROR.
void SAMRAI::hier::PatchHierarchy::makeNewPatchLevel (const int level_number, const boost::shared_ptr< BoxLevel > new_box_level) [virtual]
Construct new PatchLevel in hierarchy at given level number.
This method results in the new PatchLevel ACQUIRING the supplied BoxLevel. If the caller will not modify the supplied BoxLevel for other purposes after making the new PatchLevel, then this method may be used rather than the method taking a BoxLevel&. Use of this method where permitted is more efficient as it avoids copying an entire BoxLevel. Note that this method results in the supplied BoxLevel being locked so that any attempt by the caller to modify it after calling this method will result in an unrecoverable error.
Boxes, their mappings and the refinement ratio are obtained from new_box_level.
Parameters:
[in] level_number
[in] new_box_level
Precondition:
getDim() == new_box_level->getDim()
level_number >= 0 && ln < getMaxNumberOfLevels()
new_box_level->getRefinementRatio() > IntVector::getZero(getDim())
References SAMRAI::hier::IntVector::getZero(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ERROR.
void SAMRAI::hier::PatchHierarchy::removePatchLevel (const int level) [virtual]
Remove a patch level.
Remove PatchLevel from the hierarchy and adjust number of levels accordingly.
Parameters:
[in] level
Precondition:
(level >= 0) && (level < getNumberOfLevels())
References TBOX_ASSERT.
boost::shared_ptr<PatchLevel> SAMRAI::hier::PatchHierarchy::getPatchLevel (const int level) const [inline]
Get a PatchLevel from the hierarchy.
Returns:
a pointer to the specified patch level.
Parameters:
[in] level
Precondition:
(level >= 0) && (level < getNumberOfLevels())
References getNumberOfLevels(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors(), logMetadataStatistics(), and recursivePrint().
boost::shared_ptr<PatchDescriptor> SAMRAI::hier::PatchHierarchy::getPatchDescriptor () const [inline]
Get the patch descriptor.
Returns:
a pointer to the patch descriptor used for the patches in the patch hierarchy.
Referenced by SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths(), and SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths().
bool SAMRAI::hier::PatchHierarchy::levelExists (const int level) const [inline]
Check if the level exists.
Returns:
True if the hierarchy contains a patch level with the given level number; otherwise false.
Parameters:
[in] level
References getNumberOfLevels().
bool SAMRAI::hier::PatchHierarchy::finerLevelExists (const int level) const [inline]
Check if a finer level exists.
Returns:
True if the hierarchy contains a patch level with level number level + 1 (i.e., finer than level with given number); otherwise, false.
Parameters:
[in] level
References getNumberOfLevels().
int SAMRAI::hier::PatchHierarchy::getNumberOfLevels () const [inline]
Get the number of levels in the hierarchy.
Returns:
The number of levels that currently exist in the hierarchy.
Referenced by finerLevelExists(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), getFinestLevelNumber(), getPatchLevel(), SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors(), levelExists(), and recursivePrint().
int SAMRAI::hier::PatchHierarchy::getFinestLevelNumber () const [inline]
Get the finest level in the hierarchy.
Returns:
The level number of the finest resolution patch level currently existing in the hierarchy.
References getNumberOfLevels().
size_t SAMRAI::hier::PatchHierarchy::getNumberBlocks () const [inline]
Referenced by SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths().
bool SAMRAI::hier::PatchHierarchy::levelCanBeRefined (const int level_number) const [inline]
Check whether specified level can be refined.
Returns:
true if level associated with the specified level number can be refined; i.e., the level number is less than that of the finest level allowed in the hierarchy. Otherwise, false is returned.
Precondition:
level_number >= 0
References getMaxNumberOfLevels(), and TBOX_ASSERT.
const boost::shared_ptr<BoxLevel>& SAMRAI::hier::PatchHierarchy::getBoxLevel (const int level) const [inline]
Return a pointer to the specified BoxLevel.
Returns:
The BoxLevel owned by PatchLevel number level.
Parameters:
[in] level
Referenced by makeCoarsenedPatchHierarchy(), and makeRefinedPatchHierarchy().
void SAMRAI::hier::PatchHierarchy::registerConnectorWidthRequestor (const ConnectorWidthRequestorStrategy & cwrs)
Register the ConnectorWidthRequestorStrategy with the hierarchy.
Used to adjust the results of getRequiredConnectorWidth(). This method can be called multiple times to provide as much connector width information for any object that requires a connector width constraint. The largest Connector width over all provided will be used in the hierarchy.
Important
All registrations must occur before the first call to getRequiredConnectorWidth().
Parameters:
[in] cwrs The connector width requester strategy instance.
Precondition:
d_connector_widths_committed
References TBOX_ERROR.
IntVector SAMRAI::hier::PatchHierarchy::getRequiredConnectorWidth (int base_ln, int head_ln, bool commit = false) const
Get the width required of the Connector from the base to the head levels, as specified by the given level numbers.
The two level numbers must differ by no more than one.
The commit flag tells the hierarchy whether the calling code is commiting to the required widths in such a way that would break if this method later returns a bigger value. Once this method is called with commit = true, the hierarchy will always return the same width for the same pair of level numbers. Thus the hierarchy would not allow any changes that could result in changing the required widths.
Returns:
The widths required from the base to head levels.
Parameters:
[in] base_ln
[in] head_ln
[in] commit Set to true if you want all future return values to be the same for the same level numbers.
Precondition:
(head_ln >= 0) && (head_ln < getMaxNumberOfLevels())
(base_ln >= 0) && (base_ln < getMaxNumberOfLevels())
abs(base_ln - head_ln) <= 1
References TBOX_ASSERT, and TBOX_ERROR.
Referenced by initializeHierarchy(), and logMetadataStatistics().
void SAMRAI::hier::PatchHierarchy::registerAutoConnectorWidthRequestorStrategy (const ConnectorWidthRequestorStrategy & cwrs) [static]
Add a ConnectorWidthRequestorStrategy implementation to the set of implementations that, by default, gets registered to all PatchHierarchy objects.
Parameters:
[in] cwrs ConnectorWidthRequestorStrategy to be registered.
const BoxLevel& SAMRAI::hier::PatchHierarchy::getDomainBoxLevel () const [inline]
Access the domain description as a BoxLevel.
The domain BoxLevel is maintained in Globalized mode with processor 0 owning all boxes.
Returns:
The domain description as a BoxLevel
Referenced by SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary().
const tbox::SAMRAI_MPI& SAMRAI::hier::PatchHierarchy::getMPI () const [inline]
Returns the SAMRAI_MPI communicator over which the domain BoxLevel is distributed.
Referenced by makeCoarsenedPatchHierarchy(), and makeRefinedPatchHierarchy().
void SAMRAI::hier::PatchHierarchy::setMaxNumberOfLevels (int max_levels) [inline]
Set the maximum number of levels allowed on the hierarchy.
This method can only be called when the hierarchy has no PatchLevels.
If this increases the max number of levels, the missing smallest patch size, largest patch size and ratio to coarser level are taken from the values for the current finest level. These values can be changed afterward using set methods below.
Parameters:
[in] max_levels
int SAMRAI::hier::PatchHierarchy::getMaxNumberOfLevels () const [inline]
Get the maximum number of levels allowed on the hierarchy.
This number is set by setMaxNumberOfLevels() or in the input database.
Returns:
The maximum number of levels allowed on the hierarchy.
Referenced by SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::StandardTagAndInitializeConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::algs::TimeRefinementIntegratorConnectorWidthRequestor::computeRequiredConnectorWidths(), getLargestPatchSize(), getProperNestingBuffer(), getRatioToCoarserLevel(), getSmallestPatchSize(), levelCanBeRefined(), setLargestPatchSize(), setRatioToCoarserLevel(), and setSmallestPatchSize().
void SAMRAI::hier::PatchHierarchy::setRatioToCoarserLevel (const IntVector & ratio, int level) [inline]
Set the ratio to coarser level.
Parameters:
[in] ratio Refinement ratio in each direction
[in] level
Precondition:
(level > 0) && (level < getMaxNumberOfLevels())
References getMaxNumberOfLevels(), and TBOX_ASSERT.
const IntVector& SAMRAI::hier::PatchHierarchy::getRatioToCoarserLevel (int level) const [inline]
Get the ratio between specified level and next coarser level.
Returns:
The ratio between specified level and @ level-1
Parameters:
[in] level
Precondition:
level < getMaxNumberOfLevels()
References getMaxNumberOfLevels(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::StandardTagAndInitializeConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths(), and SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredFineConnectorWidthsForRecursiveRefinement().
void SAMRAI::hier::PatchHierarchy::setSmallestPatchSize (const IntVector & size, int level) [inline]
Set the smallest patch size on the given level.
Parameters:
[in] size Smallest size in each direction
[in] level
Precondition:
(level >= 0) && (level < getMaxNumberOfLevels())
References getMaxNumberOfLevels(), and TBOX_ASSERT.
const IntVector& SAMRAI::hier::PatchHierarchy::getSmallestPatchSize (int level) const [inline]
Get the smallest patch size on the given level.
Returns:
The smallest patch size allowed on the given level.
Parameters:
[in] level
Precondition:
(level >= 0) && (level < getMaxNumberOfLevels())
References getMaxNumberOfLevels(), and TBOX_ASSERT.
void SAMRAI::hier::PatchHierarchy::setLargestPatchSize (const IntVector & size, int level) [inline]
Set the largest patch size on the given level.
Parameters:
[in] size Largest size in each direction.
[in] level
Precondition:
(level >= 0) && (level < getMaxNumberOfLevels())
References getMaxNumberOfLevels(), and TBOX_ASSERT.
const IntVector& SAMRAI::hier::PatchHierarchy::getLargestPatchSize (int level) const [inline]
Get the largest patch size.
Returns:
The largest patch size allowed on the given level.
Parameters:
[in] level
Precondition:
(level >= 0) && (level < getMaxNumberOfLevels())
References getMaxNumberOfLevels(), and TBOX_ASSERT.
int SAMRAI::hier::PatchHierarchy::getProperNestingBuffer (int ln) const [inline]
Get the proper nesting buffer for a specific level.
The proper nesting requirement is that level ln+1 must nest in level ln by getProperNestingBuffer(ln) cells. The nesting requirement does not apply where level ln+1 touches a physical boundary.
If ln >= getMaxNumberOfLevels()-1, the return value will be -1.
Returns:
The proper nesting buffer
Parameters:
[in] ln
Precondition:
(ln >= 0) && (ln < getMaxNumberOfLevels())
References getMaxNumberOfLevels(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths().
bool SAMRAI::hier::PatchHierarchy::allowPatchesSmallerThanGhostWidth () const [inline]
Get flag for allowing patches smaller than ghost width.
bool SAMRAI::hier::PatchHierarchy::allowPatchesSmallerThanMinimumSize () const [inline]
Get flag for allowing patches smaller than user-provided minimum size.
void SAMRAI::hier::PatchHierarchy::setPatchFactory (const boost::shared_ptr< PatchFactory > & factory) [inline]
Set the factory used to create patch objects.
If a factory is not specified, then the default factory will create patch objects of type Patch.
Parameters:
[in] factory
void SAMRAI::hier::PatchHierarchy::setPatchLevelFactory (const boost::shared_ptr< PatchLevelFactory > & factory) [inline]
Set the factory used to create patch level objects.
If a factory is not specified, then the default factory will create patch level objects of type PatchLevel.
Parameters:
[in] factory
boost::shared_ptr<BaseGridGeometry> SAMRAI::hier::PatchHierarchy::getGridGeometry () const [inline]
Get the grid geometry.
Returns:
a pointer to the grid geometry object.
Referenced by SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary(), SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredFineConnectorWidthsForRecursiveRefinement(), and PatchHierarchy().
void SAMRAI::hier::PatchHierarchy::logMetadataStatistics (const char * note, int ln, int cycle, double level_time, bool log_fine_connector, bool log_coarse_connector) const
Log metadata statistics.
This is for diagnostic purposes, to be used by developers. Log the statistics for a given level in the hierarchy and Connectors from it.
Parameters:
note Note to be written out.
ln Level number to log
cycle
level_time
log_fine_connector
log_coarse_connector
References SAMRAI::hier::CONNECTOR_CREATE, SAMRAI::hier::Connector::format(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::Connector::formatStatistics(), SAMRAI::hier::BoxLevel::formatStatistics(), getPatchLevel(), getRequiredConnectorWidth(), SAMRAI::tbox::Utilities::levelToString(), and SAMRAI::tbox::plog.
void SAMRAI::hier::PatchHierarchy::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Writes the state of the PatchHierarchy object and the PatchLevels it contains to the restart database.
Note:
Only those patch data which have been registered for restart with the VariableDatabase will be written to the database. This method implements the pure virtual method in tbox::Serializable class which is used by the tbox::RestartManager for writing the PatchHierarchy to a restart file.
Parameters:
[out] restart_db
Precondition:
restart_db
References SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), SAMRAI::tbox::Utilities::levelToString(), and TBOX_ASSERT.
void SAMRAI::hier::PatchHierarchy::initializeHierarchy ()
Read in the entire hierarchy from the restart database.
Note:
Warning messages will be printed to the log file if any patch data component specified in the component_selector cannot be found in the database.
This method handles the memory allocation for each PatchLevel it reads in.
Assertions
The number of levels (if given) must be greater than zero.
References SAMRAI::hier::CONNECTOR_CREATE, SAMRAI::tbox::RestartManager::getManager(), getRequiredConnectorWidth(), SAMRAI::tbox::Utilities::levelToString(), and TBOX_ERROR.
const tbox::Dimension& SAMRAI::hier::PatchHierarchy::getDim () const [inline]
Get the dimension of this object.
Returns:
the dimension of this object.
Referenced by SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::StandardTagAndInitializeConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::algs::TimeRefinementIntegratorConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredFineConnectorWidthsForRecursiveRefinement(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), and SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors().
int SAMRAI::hier::PatchHierarchy::recursivePrint (std::ostream & os, const std::string & border = std::string(), int depth = 0)
Print a patch hierarchy to a specified degree of detail.
The amount of detail is controlled by the value of depth.
depth <= 0 means only the number of levels will be printed. depth == 1 means information about each level of the hierarchy will be printed, as well as the total number of patches and cells in the hierarchy. depth >= 2 will print everything that is printed for depth == 1, plus details about each patch on each level.
If depth >= 1, global communication steps will be invoked, which can have negative effects on scaling performance.
Returns:
0. Always.
Parameters:
[in,out] os The output stream
[in] border string around output text
[in] depth
References getNumberOfLevels(), and getPatchLevel().
const std::string& SAMRAI::hier::PatchHierarchy::getObjectName () const [inline]
Get the name of this object.
Returns:
The name of this object.
UncoveredBoxIterator SAMRAI::hier::PatchHierarchy::beginUncovered () [inline]
Returns an iterator to the first uncovered Box in this hierarchy.
UncoveredBoxIterator SAMRAI::hier::PatchHierarchy::endUncovered () [inline]
Returns an iterator to the last uncovered Box in this hierarchy.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchHierarchy.h
source/SAMRAI/hier/PatchHierarchy.C