SAMRAI: SAMRAI::tbox::BalancedDepthFirstTree Class Reference
SAMRAI::tbox::BalancedDepthFirstTree Class Reference
Implementation of RankTreeStrategy aranging ranks in a balanced, depth-first tree.
#include <source/SAMRAI/tbox/BalancedDepthFirstTree.h>
Public Member Functions
BalancedDepthFirstTree ()
Constructor.
BalancedDepthFirstTree (int first_rank, int last_rank, int rank, bool do_left_leaf_switch=true)
Initializing constructor.
~BalancedDepthFirstTree ()
Destructor.
void setupTree (const RankGroup &rank_group, int my_rank)
Set up the tree.
int getRank () const
Access the rank used to initialize.
int getParentRank () const
Access the parent rank.
int getChildRank (unsigned int child_number) const
Access a child rank.
unsigned int getNumberOfChildren () const
Return the number of children.
unsigned int getChildNumber () const
Return the child number, or invalidChildNumber() if is root of the tree.
unsigned int getDegree () const
Return the degree of the tree (the maximum number of children each node may have).
unsigned int getGenerationNumber () const
Return the generation number.
int getRootRank () const
Return the rank of the root of the tree.
void setLeftLeafSwitching (bool do_left_leaf_switch)
Whether to do left-leaf-switch, which puts all leaves within one rank of their parents.
Detailed Description
Implementation of RankTreeStrategy aranging ranks in a balanced, depth-first tree.
An example of a tree created is
 *                     0
 *                    / \
 *                   /   \
 *                  /     \
 *                 1       8
 *                / \     / \
 *               2   5   9   12
 *              /|  /|  / \  |\
 *             3 4 6 7 10 11 13...
 *
The tree is as balanced as possible. Nodes that are close together in the tree tends to be close together in natural ordering. Without knowing about the underlying message passing network structure, we assume that close natural ordering usually means close together on the network. Thus nodes close together in the tree are also close together on the network. Thus, communication between nearest neighbors in the tree tend to be faster.
The tree formed by this class has the property that each and every subtree is composed nodes with contiguous natural ordering. This again benefits communication.
Constructor & Destructor Documentation
SAMRAI::tbox::BalancedDepthFirstTree::BalancedDepthFirstTree ()
Constructor.
SAMRAI::tbox::BalancedDepthFirstTree::BalancedDepthFirstTree (int first_rank, int last_rank, int rank, bool do_left_leaf_switch = true)
Initializing constructor.
Parameters:
[in] first_rank
[in] last_rank
[in] rank
[in] do_left_leaf_switch See setLeftLeafSwitching()
SAMRAI::tbox::BalancedDepthFirstTree::~BalancedDepthFirstTree ()
Destructor.
Deallocate internal data.
Member Function Documentation
void SAMRAI::tbox::BalancedDepthFirstTree::setupTree (const RankGroup & rank_group, int my_rank) [virtual]
Set up the tree.
Set up the tree for the processors in the given RankGroup. Prepare to provide tree data for the given rank.
Parameters:
[in] rank_group
[in] my_rank The rank whose parent and children are sought, usually the local process.
Precondition:
(first_rank <= rank) && (rank <= last_rank)
Implements SAMRAI::tbox::RankTreeStrategy.
References SAMRAI::tbox::RankGroup::getMapIndex(), SAMRAI::tbox::RankGroup::isMember(), SAMRAI::tbox::RankGroup::size(), and TBOX_ASSERT.
int SAMRAI::tbox::BalancedDepthFirstTree::getRank () const [inline, virtual]
Access the rank used to initialize.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::BalancedDepthFirstTree::getParentRank () const [inline, virtual]
Access the parent rank.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::BalancedDepthFirstTree::getChildRank (unsigned int child_number) const [inline, virtual]
Access a child rank.
Implements SAMRAI::tbox::RankTreeStrategy.
References SAMRAI::tbox::RankTreeStrategy::getInvalidRank().
unsigned int SAMRAI::tbox::BalancedDepthFirstTree::getNumberOfChildren () const [inline, virtual]
Return the number of children.
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::BalancedDepthFirstTree::getChildNumber () const [inline, virtual]
Return the child number, or invalidChildNumber() if is root of the tree.
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::BalancedDepthFirstTree::getDegree () const [inline, virtual]
Return the degree of the tree (the maximum number of children each node may have).
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::BalancedDepthFirstTree::getGenerationNumber () const [inline, virtual]
Return the generation number.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::BalancedDepthFirstTree::getRootRank () const [inline, virtual]
Return the rank of the root of the tree.
Implements SAMRAI::tbox::RankTreeStrategy.
void SAMRAI::tbox::BalancedDepthFirstTree::setLeftLeafSwitching (bool do_left_leaf_switch) [inline]
Whether to do left-leaf-switch, which puts all leaves within one rank of their parents.
Without left-leaf-switching, about half of the leaves are within one rank of their parents. The other half are within 2 ranks of their parents. On the downside, switching moves the leaves' parents a little farther away from the grandparents.
Default choice is true. To change the choice, this call must be made before setupTree().
References SAMRAI::tbox::RankTreeStrategy::getInvalidRank(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/BalancedDepthFirstTree.h
source/SAMRAI/tbox/BalancedDepthFirstTree.C