SAMRAI: SAMRAI::hier::HierarchyNeighbors Class Reference
SAMRAI::hier::HierarchyNeighbors Class Reference
Class providing basic information about the neighors of a Patch within a PatchHierarchy.
#include <source/SAMRAI/hier/HierarchyNeighbors.h>
Public Member Functions
HierarchyNeighbors (const PatchHierarchy &hierarchy, int coarsest_level, int finest_level)
Constructor of HierarchyNeighbors.
~HierarchyNeighbors ()
Destructor.
int getCoarsestLevelNumber () const
Get the coarsest level number represented by this object.
int getFinestLevelNumber () const
Get the finest level number represented by this object.
const BoxContainer & getFinerLevelNeighbors (const Box &box, int ln) const
Get neighbors from the next finer level.
const BoxContainer & getCoarserLevelNeighbors (const Box &box, int ln) const
Get neighbors from the next coarser level.
const BoxContainer & getSameLevelNeighbors (const Box &box, int ln) const
Get neighbors from the same level.
Detailed Description
Class providing basic information about the neighors of a Patch within a PatchHierarchy.
When a Patch exists within a PatchHierarchy, it is often useful to know what other Patches in the hierarchy are its neighbors--meaning those Patches on the same or an adjacent level that either overlap the first Patch in space or touch it along a Patch boundary. This class provides a basic interface for identifying the neightbors of a given local Patch.
In this class a neighbor of a Patch is defined only one that touches the first Patch in index space in some way, either by overlapping or by adjacency at a Patch boundary. See the class Connector for a means to find neighbor relationships defined more broadly, such as Patches that are near to each other within a defined width of cells but do not touch.
See also:
Connector
Constructor & Destructor Documentation
SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors (const PatchHierarchy & hierarchy, int coarsest_level, int finest_level)
Constructor of HierarchyNeighbors.
HierarchyNeighbors is constructed based on the given PatchHierarchy and a range of levels. The range of levels may include the entire hierarchy or a subset of its levels. Any levels outside of the given range will be treated by this class as if they do not exist.
The coarsest and finest level numbers may be equal, but when this is so, this class should only be used to find neighbors on the same level.
Parameters:
hierarchy PatchHierarchy that will be used
coarsest_level The coarsest level that will be used
finest_level The finest level that will be used
Precondition:
coarsest_level >= 0;
coarsest_level <= finest_level
finest_level < hierarchy->getNumberOfLevels()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::CONNECTOR_IMPLICIT_CREATION_RULE, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::PatchHierarchy::getDim(), SAMRAI::hier::Connector::getNeighborBoxes(), SAMRAI::hier::PatchHierarchy::getNumberOfLevels(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::PatchHierarchy::getPatchLevel(), SAMRAI::hier::Connector::hasNeighborSet(), SAMRAI::hier::BoxContainer::insert(), and TBOX_ASSERT.
SAMRAI::hier::HierarchyNeighbors::~HierarchyNeighbors ()
Destructor.
Member Function Documentation
int SAMRAI::hier::HierarchyNeighbors::getCoarsestLevelNumber () const [inline]
Get the coarsest level number represented by this object.
int SAMRAI::hier::HierarchyNeighbors::getFinestLevelNumber () const [inline]
Get the finest level number represented by this object.
const BoxContainer& SAMRAI::hier::HierarchyNeighbors::getFinerLevelNeighbors (const Box & box, int ln) const [inline]
Get neighbors from the next finer level.
Given a Box from a local Patch on a given level, this returns a container holding the neighboring boxes on the next finer level. The container will be empty if the Patch has no neighbors on the finer level.
An error will occur if the Box does not represent a local Patch on the given level.
Parameters:
box Box representing a Patch
ln Level number of the level holding the Patch. Both ln and ln+1 must be within the range of levels used to construct this object.
Precondition:
ln >= d_coarsest_level && ln < d_finest_level
References SAMRAI::hier::Box::getBoxId(), TBOX_ASSERT, and TBOX_ERROR.
const BoxContainer& SAMRAI::hier::HierarchyNeighbors::getCoarserLevelNeighbors (const Box & box, int ln) const [inline]
Get neighbors from the next coarser level.
Given a Box from a local Patch on a given level, this returns a container holding the neighboring boxes on the next coarser level.
An error will occur if the Box does not represent a local Patch on the given level.
Parameters:
box Box representing a Patch
ln Level number of the level holding the Patch. Both ln and ln-1 must be within the range of levels used to construct this object.
Precondition:
ln <= d_finest_level && ln >= d_coarsest_level
References SAMRAI::hier::Box::getBoxId(), TBOX_ASSERT, and TBOX_ERROR.
const BoxContainer& SAMRAI::hier::HierarchyNeighbors::getSameLevelNeighbors (const Box & box, int ln) const [inline]
Get neighbors from the same level.
Given a Box which represents a local Patch on a given level, this returns a container holding the neighboring boxes on that level. The container will be empty if the Patch has no neighbors.
An error will occur if the Box does not represent a local Patch on the given level.
Parameters:
box Box representing a Patch
ln Level number of the level holding the Patch
Precondition:
ln <= d_finest_level && ln >= d_coarsest_level
References SAMRAI::hier::Box::getBoxId(), TBOX_ASSERT, and TBOX_ERROR.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/HierarchyNeighbors.h
source/SAMRAI/hier/HierarchyNeighbors.C