SAMRAI: SAMRAI::math::PatchFaceDataOpsComplex Class Reference
SAMRAI::math::PatchFaceDataOpsComplex Class Reference
#include <source/SAMRAI/math/PatchFaceDataOpsComplex.h>
Public Member Functions
PatchFaceDataOpsComplex ()
virtual ~PatchFaceDataOpsComplex ()
void copyData (const boost::shared_ptr< pdat::FaceData< dcomplex > > &dst, const boost::shared_ptr< pdat::FaceData< dcomplex > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::FaceData< dcomplex > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::FaceData< dcomplex > > &dst, const dcomplex &alpha, const hier::Box &box) const
Detailed Description
Class PatchFaceDataOpsComplex provides a collection of operations that may be used to manipulate complex face-centered patch data. The operations include basic arithmetic and norms. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base classes PatchFaceDataBasicOps, PatchFaceDataNormOpsComplex from which it is derived. The name of each of these base classes is indicative of the set of face-centered patch data operations that it provides.
A similar set of operations is implemented for real (double and float) and integer patch data in the classes PatchFaceDataOpsReal and PatchFaceDataOpsInteger, repsectively.
See also:
PatchFaceDataBasicOps
PatchFaceDataNormOpsComplex
Constructor & Destructor Documentation
SAMRAI::math::PatchFaceDataOpsComplex::PatchFaceDataOpsComplex ()
Empty constructor and destructor.
SAMRAI::math::PatchFaceDataOpsComplex::~PatchFaceDataOpsComplex () [virtual]
Member Function Documentation
void SAMRAI::math::PatchFaceDataOpsComplex::copyData (const boost::shared_ptr< pdat::FaceData< dcomplex > > & dst, const boost::shared_ptr< pdat::FaceData< dcomplex > > & src, const hier::Box & box) const
Copy dst data to src data over given box.
Precondition:
data && src
(data->getDim() == src->getDim()) && (data->getDim() == box.getDim())
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::FaceGeometry::toFaceBox().
Referenced by SAMRAI::math::HierarchyFaceDataOpsComplex::copyData().
void SAMRAI::math::PatchFaceDataOpsComplex::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::FaceData<dcomplex> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::FaceData<dcomplex> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyFaceDataOpsComplex::swapData().
void SAMRAI::math::PatchFaceDataOpsComplex::printData (const boost::shared_ptr< pdat::FaceData< dcomplex > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyFaceDataOpsComplex::printData().
void SAMRAI::math::PatchFaceDataOpsComplex::setToScalar (const boost::shared_ptr< pdat::FaceData< dcomplex > > & dst, const dcomplex & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyFaceDataOpsComplex::setToScalar().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchFaceDataOpsComplex.h
source/SAMRAI/math/PatchFaceDataOpsComplex.C