SAMRAI: SAMRAI::pdat::EdgeIterator Class Reference
SAMRAI::pdat::EdgeIterator Class Reference
#include <source/SAMRAI/pdat/EdgeIterator.h>
Public Member Functions
EdgeIterator (const EdgeIterator &iterator)
EdgeIterator & operator= (const EdgeIterator &iterator)
~EdgeIterator ()
const EdgeIndex & operator* () const
const EdgeIndex * operator-> () const
EdgeIterator & operator++ ()
EdgeIterator operator++ (int)
bool operator== (const EdgeIterator &iterator) const
bool operator!= (const EdgeIterator &iterator) const
Friends
EdgeIterator EdgeGeometry::begin (const hier::Box &box, int axis)
EdgeIterator EdgeGeometry::end (const hier::Box &box, int axis)
Detailed Description
Class EdgeIterator is an iterator that provides methods for stepping through the index space associated with a edge centered box. The indices are enumerated in column-major (e.g., Fortran) order. The iterator should be used as follows:
 * hier::Box box;
 * ...
 * EdgeIterator cend(box, axis, false);
 * for (EdgeIterator c(box, axis, true); c != cend; ++c) {
 *    // use index c of the box
 * }
 *
Note that the edge iterator may not compile to efficient code, depending on your compiler. Many compilers are not smart enough to optimize the looping constructs and indexing operations.
See also:
pdat::EdgeData
pdat::EdgeGeometry
pdat::EdgeIndex
Constructor & Destructor Documentation
SAMRAI::pdat::EdgeIterator::EdgeIterator (const EdgeIterator & iterator)
Copy constructor for the edge iterator
SAMRAI::pdat::EdgeIterator::~EdgeIterator ()
Destructor for the edge iterator.
Member Function Documentation
EdgeIterator& SAMRAI::pdat::EdgeIterator::operator= (const EdgeIterator & iterator) [inline]
Assignment operator for the edge iterator.
const EdgeIndex& SAMRAI::pdat::EdgeIterator::operator* () const [inline]
Extract the edge index corresponding to the iterator position in the box.
const EdgeIndex* SAMRAI::pdat::EdgeIterator::operator-> () const [inline]
Extract a pointer to the edge index corresponding to the iterator position in the box.
EdgeIterator & SAMRAI::pdat::EdgeIterator::operator++ ()
Pre-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
EdgeIterator SAMRAI::pdat::EdgeIterator::operator++ (int)
Post-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
bool SAMRAI::pdat::EdgeIterator::operator== (const EdgeIterator & iterator) const [inline]
Test two iterators for equality (same index value).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
bool SAMRAI::pdat::EdgeIterator::operator!= (const EdgeIterator & iterator) const [inline]
Test two iterators for inequality (different index values).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
Friends And Related Function Documentation
EdgeIterator EdgeGeometry::begin (const hier::Box & box, int axis) [friend]
EdgeIterator EdgeGeometry::end (const hier::Box & box, int axis) [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/EdgeIterator.h
source/SAMRAI/pdat/EdgeIterator.C