SAMRAI: SAMRAI::xfer::RefineTimeTransaction Class Reference
SAMRAI::xfer::RefineTimeTransaction Class Reference
Class RefineTimeTransaction represents a single time interpolation communication transaction between two processors or a local data copy or refine schedules. Note that to there is an implicit hand-shaking between objects of this class and the RefineSchedule object that constructs them. Following the refine schedule implementation, the source patch data indices for a time transaction are always refer to the old and new source data and the destination patch data index for a time transaction is always the scratch data, all as defined in the RefineClasses class. This transaction is used by the refine schedule.
#include <source/SAMRAI/xfer/RefineTimeTransaction.h>
Public Member Functions
RefineTimeTransaction (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_box, const hier::Box &src_box, const hier::Box &box, const RefineClasses::Data **refine_data, int item_id)
virtual ~RefineTimeTransaction ()
virtual bool canEstimateIncomingMessageSize ()
virtual size_t computeIncomingMessageSize ()
virtual size_t computeOutgoingMessageSize ()
virtual int getSourceProcessor ()
virtual int getDestinationProcessor ()
virtual void packStream (tbox::MessageStream &stream)
virtual void unpackStream (tbox::MessageStream &stream)
virtual void copyLocalData ()
virtual void printClassData (std::ostream &stream) const
Static Public Member Functions
static void setTransactionTime (const double time)
Detailed Description
Class RefineTimeTransaction represents a single time interpolation communication transaction between two processors or a local data copy or refine schedules. Note that to there is an implicit hand-shaking between objects of this class and the RefineSchedule object that constructs them. Following the refine schedule implementation, the source patch data indices for a time transaction are always refer to the old and new source data and the destination patch data index for a time transaction is always the scratch data, all as defined in the RefineClasses class. This transaction is used by the refine schedule.
See also:
xfer::RefineSchedule
xfer::RefineClasses
tbox::Schedule
tbox::Transaction
Constructor & Destructor Documentation
SAMRAI::xfer::RefineTimeTransaction::RefineTimeTransaction (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_box, const hier::Box & src_box, const hier::Box & box, const RefineClasses::Data ** refine_data, int item_id)
Construct a transaction with the specified source and destination levels, patches, and patch data components found in the refine class item with the given id owned by the calling refine schedule. In general, this constructor is called by a RefineSchedule object for each data transaction (involving time interpolation) that must occur. This transaction will be responsible for one of the following: (1) performing a local copy, (2) packing a message stream from the source, or (3) unpacking a message stream from the destination. The transaction will perform time interpolation between the source old and new times using the time interpolation operator found in the refine class item.
Parameters:
dst_level boost::shared_ptr to destination patch level.
src_level boost::shared_ptr to source patch level.
overlap boost::shared_ptr to overlap region between patches.
dst_box Destination Box in destination patch level.
src_box Source Box in source patch level.
box hier::Box region in which to time interpolate.
refine_data Pointer to array of refine data items
item_id Integer id of refine data item owned by refine schedule.
Precondition:
dst_level
src_level
overlap
dst_box.getLocalId() >= 0
src_box.getLocalId() >= 0
refine_data != 0
item_id >= 0
(dst_level->getDim() == src_level->getDim()) && (dst_level->getDim() == dst_box.getDim()) && (dst_level->getDim() == src_box.getDim()) && (dst_level->getDim() == box.getDim())
References SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::Box::getLocalId(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY5.
SAMRAI::xfer::RefineTimeTransaction::~RefineTimeTransaction () [virtual]
The virtual destructor for time transaction releases all memory associated with the transaction.
Member Function Documentation
static void SAMRAI::xfer::RefineTimeTransaction::setTransactionTime (const double time) [inline, static]
Static member function to set the transaction time that will be shared by all object instances of this time transaction class during time interpolation. This transaction time must be set before any transactions are executed.
bool SAMRAI::xfer::RefineTimeTransaction::canEstimateIncomingMessageSize () [virtual]
Return a boolean indicating whether this transaction can estimate the size of an incoming message. If this is false, then a different communications protocol kicks in and the message size is transmitted between boxes.
Implements SAMRAI::tbox::Transaction.
size_t SAMRAI::xfer::RefineTimeTransaction::computeIncomingMessageSize () [virtual]
Return the integer amount of buffer space (in bytes) needed for the incoming message. This routine is only called if the transaction can estimate the size of the incoming message.
Implements SAMRAI::tbox::Transaction.
size_t SAMRAI::xfer::RefineTimeTransaction::computeOutgoingMessageSize () [virtual]
Return the integer buffer space needed (in bytes) for the outgoing message.
Implements SAMRAI::tbox::Transaction.
int SAMRAI::xfer::RefineTimeTransaction::getSourceProcessor () [virtual]
Return the sending processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
int SAMRAI::xfer::RefineTimeTransaction::getDestinationProcessor () [virtual]
Return the receiving processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::RefineTimeTransaction::packStream (tbox::MessageStream & stream) [virtual]
Pack the transaction data into the message stream.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::xfer::RefineClasses::Data::d_src_told, SAMRAI::hier::Box::getDim(), and SAMRAI::tbox::SAMRAI_MPI::getInvalidRank().
void SAMRAI::xfer::RefineTimeTransaction::unpackStream (tbox::MessageStream & stream) [virtual]
Unpack the transaction data from the message stream.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::RefineTimeTransaction::copyLocalData () [virtual]
Perform the local data copy for the transaction.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::xfer::RefineClasses::Data::d_scratch, SAMRAI::xfer::RefineClasses::Data::d_src_told, SAMRAI::hier::Box::getDim(), SAMRAI::tbox::SAMRAI_MPI::getInvalidRank(), and SAMRAI::hier::IntVector::getZero().
void SAMRAI::xfer::RefineTimeTransaction::printClassData (std::ostream & stream) const [virtual]
Print out transaction information.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::xfer::RefineClasses::Data::d_optime, SAMRAI::xfer::RefineClasses::Data::d_scratch, SAMRAI::xfer::RefineClasses::Data::d_src_tnew, and SAMRAI::xfer::RefineClasses::Data::d_src_told.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/RefineTimeTransaction.h
source/SAMRAI/xfer/RefineTimeTransaction.C