SAMRAI: SAMRAI::hier::Index Class Reference
SAMRAI::hier::Index Class Reference
#include <source/SAMRAI/hier/Index.h>
Public Member Functions
Index (const tbox::Dimension &dim)
Creates an uninitialized vector.
Index (const tbox::Dimension &dim, const int i)
Construct an index with all components equal to the argument.
Index (const int i, const int j)
Construct a two-dimensional index with the value (i,j).
Index (const int i, const int j, const int k)
Construct a three-dimensional index with the value (i,j,k).
Index (const std::vector< int > &i)
Construct an n-dimensional index with the values copied from the integer tbox::Array i of size n.
Index (const Index &rhs)
The copy constructor creates an index equal to the argument.
Index (const IntVector &rhs)
Construct an index equal to the argument IntVector.
Index (const tbox::Dimension &dim, const int array[])
Construct an index equal to the argument array.
Index & operator= (const Index &rhs)
The assignment operator sets the index equal to the argument.
Index & operator= (const IntVector &rhs)
The assignment operator sets the index equal to the argument IntVector.
virtual ~Index ()
The index destructor does nothing interesting.
Index & operator+= (const IntVector &rhs)
Plus-equals operator for an index and an integer vector.
Index operator+ (const IntVector &rhs) const
Plus operator for an index and an integer vector.
Index & operator+= (const int rhs)
Plus-equals operator for an index and an integer.
Index operator+ (const int rhs) const
Plus operator for an index and an integer.
Index & operator-= (const IntVector &rhs)
Minus-equals operator for an index and an integer vector.
Index operator- (const IntVector &rhs) const
Minus operator for an index and an integer vector.
Index & operator-= (const int rhs)
Minus-equals operator for an index and an integer.
Index operator- (const int rhs) const
Minus operator for an index and an integer.
Index & operator*= (const IntVector &rhs)
Times-equals operator for an index and an integer vector.
Index operator* (const IntVector &rhs) const
Times operator for an index and an integer vector.
Index & operator*= (const int rhs)
Times-equals operator for an index and an integer.
Index operator* (const int rhs) const
Times operator for an index and an integer.
Index & operator/= (const IntVector &rhs)
Assign-quotient operator for an index and an integer vector.
Index operator/ (const IntVector &rhs) const
Quotient operator for an index and an integer vector.
Index & operator/= (const int rhs)
Assign-quotient operator for an index and an integer.
Index operator/ (const int rhs) const
Quotient operator for an index and an integer.
void min (const Index &rhs)
Return the component-wise minimum of two integer vector objects.
Index & coarsen (const IntVector &ratio)
Coarsen the Index by a given ratio.
Static Public Member Functions
static const Index & getZeroIndex (const tbox::Dimension &dim)
Return an Index of zeros of the specified dimension.
static const Index & getOneIndex (const tbox::Dimension &dim)
Return an Index of ones of the specified dimension.
static const Index & getMinIndex (const tbox::Dimension &dim)
Return an Index with minimum index values for the specified dimension.
static const Index & getMaxIndex (const tbox::Dimension &dim)
Return an Index with maximum index values for the specified dimension.
static Index coarsen (const Index &index, const IntVector &ratio)
Coarsen an Index by a given ratio.
static Index min (const Index &a, const Index &b)
Utility function to take the minimum of two Index objects.
Detailed Description
Class Index implements a simple n-dimensional integer vector in the AMR index space. Index is used as lower and upper bounds when creating a box and also when iterating over the cells in a box. An index is essentially an integer vector but it carries along the notion of indexing into AMR's abstract index space.
See also:
hier::Box
hier::BoxIterator
hier::IntVector
Constructor & Destructor Documentation
SAMRAI::hier::Index::Index (const tbox::Dimension & dim) [explicit]
Creates an uninitialized vector.
SAMRAI::hier::Index::Index (const tbox::Dimension & dim, const int i)
Construct an index with all components equal to the argument.
SAMRAI::hier::Index::Index (const int i, const int j)
Construct a two-dimensional index with the value (i,j).
References SAMRAI::tbox::Dimension::getMaxDimension(), and TBOX_DIM_ASSERT.
SAMRAI::hier::Index::Index (const int i, const int j, const int k)
Construct a three-dimensional index with the value (i,j,k).
References SAMRAI::tbox::Dimension::getMaxDimension(), and TBOX_DIM_ASSERT.
SAMRAI::hier::Index::Index (const std::vector< int > & i) [explicit]
Construct an n-dimensional index with the values copied from the integer tbox::Array i of size n.
SAMRAI::hier::Index::Index (const Index & rhs)
The copy constructor creates an index equal to the argument.
SAMRAI::hier::Index::Index (const IntVector & rhs) [explicit]
Construct an index equal to the argument IntVector.
SAMRAI::hier::Index::Index (const tbox::Dimension & dim, const int array[])
Construct an index equal to the argument array.
SAMRAI::hier::Index::~Index () [virtual]
The index destructor does nothing interesting.
Member Function Documentation
Index& SAMRAI::hier::Index::operator= (const Index & rhs) [inline]
The assignment operator sets the index equal to the argument.
An assignment to an uninitialized Index is allowed but assigning from an uninitialized Index will result in an assert.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::IntVector.
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator=().
Index& SAMRAI::hier::Index::operator= (const IntVector & rhs) [inline]
The assignment operator sets the index equal to the argument IntVector.
Precondition:
getDim() == rhs.getDim()
References operator=(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Index& SAMRAI::hier::Index::operator+= (const IntVector & rhs) [inline]
Plus-equals operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator+=().
Index SAMRAI::hier::Index::operator+ (const IntVector & rhs) const [inline]
Plus operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Index& SAMRAI::hier::Index::operator+= (const int rhs) [inline]
Plus-equals operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References operator+=().
Index SAMRAI::hier::Index::operator+ (const int rhs) const [inline]
Plus operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
Index& SAMRAI::hier::Index::operator-= (const IntVector & rhs) [inline]
Minus-equals operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator-=().
Index SAMRAI::hier::Index::operator- (const IntVector & rhs) const [inline]
Minus operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Index& SAMRAI::hier::Index::operator-= (const int rhs) [inline]
Minus-equals operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References operator-=().
Index SAMRAI::hier::Index::operator- (const int rhs) const [inline]
Minus operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
Index& SAMRAI::hier::Index::operator*= (const IntVector & rhs) [inline]
Times-equals operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator*=().
Index SAMRAI::hier::Index::operator* (const IntVector & rhs) const [inline]
Times operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Index& SAMRAI::hier::Index::operator*= (const int rhs) [inline]
Times-equals operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
References operator*=().
Index SAMRAI::hier::Index::operator* (const int rhs) const [inline]
Times operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
Reimplemented in SAMRAI::pdat::CellIndex, SAMRAI::pdat::EdgeIndex, SAMRAI::pdat::FaceIndex, SAMRAI::pdat::NodeIndex, and SAMRAI::pdat::SideIndex.
Index& SAMRAI::hier::Index::operator/= (const IntVector & rhs) [inline]
Assign-quotient operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator/=().
Index SAMRAI::hier::Index::operator/ (const IntVector & rhs) const [inline]
Quotient operator for an index and an integer vector.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Index& SAMRAI::hier::Index::operator/= (const int rhs) [inline]
Assign-quotient operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
References operator/=().
Index SAMRAI::hier::Index::operator/ (const int rhs) const [inline]
Quotient operator for an index and an integer.
Reimplemented from SAMRAI::hier::IntVector.
void SAMRAI::hier::Index::min (const Index & rhs) [inline]
Return the component-wise minimum of two integer vector objects.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::IntVector.
References SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::Box::intersect(), min(), SAMRAI::hier::Box::operator*(), SAMRAI::hier::Box::operator*=(), and SAMRAI::hier::Box::operator+=().
Index& SAMRAI::hier::Index::coarsen (const IntVector & ratio) [inline]
Coarsen the Index by a given ratio.
For positive indices, this is the same as dividing by the ratio.
Precondition:
getDim() == ratio.getDim()
References SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by coarsen().
static const Index& SAMRAI::hier::Index::getZeroIndex (const tbox::Dimension & dim) [inline, static]
Return an Index of zeros of the specified dimension.
Can be used to avoid object creation overheads.
References SAMRAI::tbox::Dimension::getValue().
static const Index& SAMRAI::hier::Index::getOneIndex (const tbox::Dimension & dim) [inline, static]
Return an Index of ones of the specified dimension.
Can be used to avoid object creation overheads.
References SAMRAI::tbox::Dimension::getValue().
static const Index& SAMRAI::hier::Index::getMinIndex (const tbox::Dimension & dim) [inline, static]
Return an Index with minimum index values for the specified dimension.
Can be used to avoid object creation overheads.
References SAMRAI::tbox::Dimension::getValue().
static const Index& SAMRAI::hier::Index::getMaxIndex (const tbox::Dimension & dim) [inline, static]
Return an Index with maximum index values for the specified dimension.
Can be used to avoid object creation overheads.
References SAMRAI::tbox::Dimension::getValue().
static Index SAMRAI::hier::Index::coarsen (const Index & index, const IntVector & ratio) [inline, static]
Coarsen an Index by a given ratio.
For positive indices, this is the same as dividing by the ratio.
Precondition:
index.getDim() == ratio.getDim()
References coarsen(), SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
static Index SAMRAI::hier::Index::min (const Index & a, const Index & b) [inline, static]
Utility function to take the minimum of two Index objects.
Precondition:
a.getDim() == b.getDim()
Reimplemented from SAMRAI::hier::IntVector.
References min(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/Index.h
source/SAMRAI/hier/Index.C