SAMRAI: SAMRAI::solv::CVODESolver Class Reference
SAMRAI::solv::CVODESolver Class Reference
Class CVODESolver serves as a C++ wrapper for the CVODE ordinary differential equation solver package.
#include <source/SAMRAI/solv/CVODESolver.h>
Public Member Functions
CVODESolver (const std::string &object_name, CVODEAbstractFunctions *my_functions, const bool uses_preconditioner)
virtual ~CVODESolver ()
void initialize (SundialsAbstractVector *solution)
int solve ()
void setLogFileData (const std::string &log_fname=std::string())
void setCVODEFunctions (CVODEAbstractFunctions *my_functions, const bool uses_preconditioner)
CVODEAbstractFunctions * getCVODEFunctions () const
void setLinearMultistepMethod (int linear_multistep_method)
void setIterationType (int iteration_type)
void setToleranceType (int tolerance_type)
void setRelativeTolerance (double relative_tolerance)
void setAbsoluteTolerance (double absolute_tolerance)
void setAbsoluteTolerance (SundialsAbstractVector *absolute_tolerance)
void setSteppingMethod (int stepping_method)
void setInitialValueOfIndependentVariable (double t_0)
void setFinalValueOfIndependentVariable (double t_f, bool cvode_needs_initialization)
void setInitialConditionVector (SundialsAbstractVector *ic_vector)
void setMaximumLinearMultistepMethodOrder (int max_order)
void setMaximumNumberOfInternalSteps (int max_num_internal_steps)
void setMaximumNumberOfNilStepWarnings (int max_num_warnings)
void setInitialStepSize (double init_step_size)
void setMaximumAbsoluteStepSize (double max_step_size)
void setMinimumAbsoluteStepSize (double min_step_size)
void setPreconditioningType (int precondition_type)
void setGramSchmidtType (int gs_type)
void setMaxKrylovDimension (int max_krylov_dim)
void setCVSpgmrToleranceScaleFactor (double tol_scale_factor)
SundialsAbstractVector * getSolutionVector () const
int getDkyVector (double t, int k, SundialsAbstractVector *dky) const
double getActualFinalValueOfIndependentVariable () const
void printStatistics (std::ostream &os) const
void printCVODEStatistics (std::ostream &os) const
int getNumberOfInternalStepsTaken () const
int getNumberOfRHSFunctionCalls () const
int getNumberOfLinearSolverSetupCalls () const
int getNumberOfNewtonIterations () const
int getNumberOfNonlinearConvergenceFailures () const
int getNumberOfLocalErrorTestFailures () const
int getOrderUsedDuringLastInternalStep () const
int getOrderToBeUsedDuringNextInternalStep () const
int getCVODEMemoryUsageForDoubles () const
int getCVODEMemoryUsageForIntegers () const
double getStepSizeForLastInternalStep () const
double getStepSizeForNextInternalStep () const
double getCurrentInternalValueOfIndependentVariable () const
double getCVODESuggestedToleranceScalingFactor () const
void printCVSpgmrStatistics (std::ostream &os) const
int getNumberOfPreconditionerEvaluations () const
int getNumberOfLinearIterations () const
int getNumberOfPrecondSolveCalls () const
int getNumberOfLinearConvergenceFailures () const
int getCVSpgmrMemoryUsageForDoubles () const
int getCVSpgmrMemoryUsageForIntegers () const
virtual void printClassData (std::ostream &os) const
const std::string & getObjectName () const
Detailed Description
Class CVODESolver serves as a C++ wrapper for the CVODE ordinary differential equation solver package.
It is intended to be sufficiently generic to be used independently of the SAMRAI framework. This class declares one private static member function to link the user-defined routine for right-hand side function evaluation and two private statice member functions to link the user-defined preconditioner setup and solve routines. The implementation of these functions is defined by the user in a subclass of the abstract base class CVODEAbstractFunctions. The vector objects used within the solver are given in a subclass of the abstract class SundialsAbstractVector. The SundialsAbstractVector class defines the vector kernel operations required by the CVODE package so that they may be easily supplied by a user who opts not to use the vector kernel supplied by the CVODE package. (It should be noted that the vector kernel used by CVODE is the same as the one used by the other packages in the Sundials of solvers).
Note that this class provides no input or restart capabilities and relies on CVODE for output reporting.
CVODESolver Usage:
In order to use the CVODESolver, the user must provide a concrete subclass of CVODEAbstractFunctions abstract base class which defines the evaluateRHSFunction(), CVSpgmrPrecondSet(), and CVSpgmrPrecondSolve() methods.
Solving a system of ODEs using this CVODE C++ interface requires four main stages. First, a CVODESolver object is created with a user-specified name and CVODEAbstractFunctions object. Second, the user must specify the integration parameters that s/he wishes to use. Next, the user must call the CVODESolver method initialize(solution_vector) with the SundialsAbstractVector that s/he wants to put the solution in. Finally, the solve() method is invoked to solve the system of ODEs to the specified value of the independent variable.
The following is a list of integration parameters that must be specified by the user before calling the solve() method:
Either relative or absolute tolerance must be set - setRelativeTolerance(relative_tolerance), setAbsoluteTolerance(absolute_tolerance)
Initial value of independent variable - setInitialValueOfIndependentVariable(init_time)
Final value of independent variable - setFinalValueOfIndependentVariable(final_time cvode_needs_initialization)
Initial condition vector - setInitialConditionVector(ic_vector)
The following is a list of default values for integration parameters:
Linear Multistep Method BDF
Iteration Type FUNCTIONAL
Tolerance Type SS (scalar relative and scalar absolute tolerances)
Relative Tolerance 0.0
Scalar Absolute Tolerance 0.0
Vector Absolute Tolerance NULL
Stepping Method NORMAL
Maximum Order for Multistep Method 12 for ADAMS, 5 for BDF
Maximum Number of Internal Steps 500
Maximum Number of NIL Step Warnings 10
Initial Step Size determined by CVODE
Maximum Absolute Value of Step Size infinity
Minimum Absolute Value of Step Size 0.0
CVSpgmr Preconditioning Type NONE
CVSpgmr Gram Schmidt Algorithm MODIFIED_GS
CVSpgmr Maximum Krylov Dimension MIN(num_equations, CVSPGMR_MAXL=5)
CVSpgmr Tolerance Scale Factor CVSPGMR_DELT = 0.05.
CVODE was developed in the Center for Applied Scientific Computing (CASC) at Lawrence Livermore National Laboratory (LLNL). Many of the comments in this class were taken verbatim from CVODE header files. For more information about CVODE and a complete description of the operations and data structures used by this class, see S.D. Cohen and A.C. Hindmarsh, "CVODE User Guide", UCRL-MA-118618, Lawrence Livermore National Laboratory, 1994.
See also:
solv::CVODEAbstractFunctions
solv::SundialsAbstractVector
Constructor & Destructor Documentation
SAMRAI::solv::CVODESolver::CVODESolver (const std::string & object_name, CVODEAbstractFunctions * my_functions, const bool uses_preconditioner)
Constructor for CVODESolver sets default CVODE parameters and initializes the solver package with user-supplied functions CVODESolver parameters may be changed later using member functions described below.
Notes:
The solution vector is not passed into the constructor. Before the solver can be used, the initialize() function must be called.
Precondition:
!object_name.empty()
my_functions != 0
References setAbsoluteTolerance(), setCVSpgmrToleranceScaleFactor(), setGramSchmidtType(), setIterationType(), setLinearMultistepMethod(), setMaxKrylovDimension(), setPreconditioningType(), setRelativeTolerance(), setSteppingMethod(), setToleranceType(), and TBOX_ASSERT.
SAMRAI::solv::CVODESolver::~CVODESolver () [virtual]
Virtual destructor for CVODESolver closes the CVODE log file and frees the memory allocated for the CVODE memory record.
Member Function Documentation
void SAMRAI::solv::CVODESolver::initialize (SundialsAbstractVector * solution) [inline]
Initialize solver with solution vector. The solution vector is required to initialize the memory record used internally within CVODE. This routine must be called before the solver can be used.
Precondition:
solution != 0
d_solution_vector == 0
References TBOX_ASSERT.
int SAMRAI::solv::CVODESolver::solve () [inline]
Integrate ODE system specified t_f. The integer return value is a termination code defined by CVODE. The following is a table of termination codes and a brief description of their meanings.
CVODE Termination Codes:
SUCCESS (=0) CVode succeeded.
CVODE_NO_MEM (=-1) The cvode_mem argument was NULL.
ILL_INPUT (=-2) One of the inputs to CVode is illegal. This includes the situation when a component of the error weight vectors becomes < 0 during internal time-stepping. The ILL_INPUT flag will also be returned if the linear solver routine CV--- (called by the user after calling CVodeMalloc) failed to set one of the linear solver-related fields in cvode_mem or if the linear solver's init routine failed. In any case, the user should see the printed error message for more details.
TOO_MUCH_WORK (=-3) The solver took maxstep internal steps but could not reach t_f. The default value for mxstep is MXSTEP_DEFAULT = 500.
TOO_MUCH_ACC (=-4) The solver could not satisfy the accuracy demanded by the user for some internal step.
ERR_FAILURE (=-5) Error test failures occurred too many times (= MXNEF = 7) during one internal time step or occurred with |h| = hmin.
CONV_FAILURE (=-6) Convergence test failures occurred too many times (= MXNCF = 10) during one internal time step or occurred with |h| = hmin.
SETUP_FAILURE (=-7) The linear solver's setup routine failed in an unrecoverable manner.
SOLVE_FAILURE (=-8) The linear solver's solve routine failed in an unrecoverable manner.
See cvode.h header file for more information about return values.
If CVODE or CVSpgmr requires re-initialization, it is automatically done before the solve. This may be required if any of the CVODE or CVSpgmr data parameters have changed since the last call to the solver.
Precondition:
d_user_t_f > d_t_0
References SAMRAI::solv::SundialsAbstractVector::getNVector(), and TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setLogFileData (const std::string & log_fname = std::string()) [inline]
Accessor function for setting CVODE output log file name and output printing options. Output file name and options may be changed throughout run as desired.
void SAMRAI::solv::CVODESolver::setCVODEFunctions (CVODEAbstractFunctions * my_functions, const bool uses_preconditioner) [inline]
Set CVODESolver to use my_functions as the concrete subclass of the CVODEAbstractFunctions class that defines the right-hand side evaluation and preconditioner functions. The uses_preconditioner argument indicates whether or not the the user has defined preconditioner routines in their concrete subclass of the CVODEAbstractFunctions class.
Precondition:
my_functions != 0
References TBOX_ASSERT.
CVODEAbstractFunctions* SAMRAI::solv::CVODESolver::getCVODEFunctions () const [inline]
Return pointer to object that provides user-defined functions for CVODE and CVSpgmr.
void SAMRAI::solv::CVODESolver::setLinearMultistepMethod (int linear_multistep_method) [inline]
Set linear multistep method. The user can specify either ADAMS or BDF (backward differentiation formula) methods The BDF method is recommended for stiff problems, and the ADAMS method is recommended for nonstiff problems.
Note: the enumeration constants ADAMS and BDF are defined in cvode.h.
Precondition:
(linear_multistep_method == CV_ADAMS) || (linear_multistep_method == CV_BDF)
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setIterationType (int iteration_type) [inline]
Set iteration type. The user can specify either FUNCTIONAL iteration, which does not require linear algebra, or a NEWTON iteration, which requires the solution of linear systems. In the NEWTON case, the user must also specify a CVODE linear solver. NEWTON is recommended in case of stiff problems.
Note: the enumeration constants FUNCTIONAL and NEWTON are defined in cvode.h.
Precondition:
(iteration_type == CV_FUNCTIONAL) || (iteration_type == CV_NEWTON)
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setToleranceType (int tolerance_type) [inline]
Set tolerance type. This parameter specifies the relative and absolute tolerance types to be used. The SS tolerance type means a scalar relative and absolute tolerance, while the SV tolerance type means a scalar relative tolerance and a vector absolute tolerance (a potentially different absolute tolerance for each vector component).
Note: the enumeration constants SS and SV are defined in cvode.h.
Precondition:
(tolerance_type == CV_SS) || (tolerance_type == CV_SV)
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setRelativeTolerance (double relative_tolerance) [inline]
Set the relative tolerance level.
Note that pure absolute tolerance can be used by setting the relative tolerance to 0. However, it is an error to simultaneously set relative and absolute tolerances to 0.
Precondition:
relative_tolerance >= 0.0
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setAbsoluteTolerance (double absolute_tolerance) [inline]
Set the scalar absolute tolerance level.
Note that pure relative tolerance can be used by setting the absolute tolerance to 0. However, it is an error to simultaneously set relative and absolute tolerances to 0.
Precondition:
absolute_tolerance >= 0.0
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setAbsoluteTolerance (SundialsAbstractVector * absolute_tolerance) [inline]
Set the vector absolute tolerance level.
Note that pure relative tolerance can be used by setting the absolute tolerance to 0. However, it is an error to simultaneously set relative and absolute tolerances to 0.
Precondition:
absolute_tolerance != 0
absolute_tolerance->vecMin() >= 0.0
References TBOX_ASSERT, and SAMRAI::solv::SundialsAbstractVector::vecMin().
void SAMRAI::solv::CVODESolver::setSteppingMethod (int stepping_method) [inline]
Set stepping method to use for integration. There are stepping methods: NORMAL and ONE_STEP. The NORMAL method has the solver take internal steps until it has reached or just passed the user specified t_f parameter. The solver then interpolates in order to return an approximate value of y(t_f). The ONE_STEP option tells the solver to just take one internal step and return the solution at the point reached by that step.
Note: the enumeration constants NORMAL and ONE_STEP are defined in cvode.h.
Precondition:
(stepping_method == CV_NORMAL) || (stepping_method == CV_ONE_STEP)
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setInitialValueOfIndependentVariable (double t_0) [inline]
Set initial value for independent variable.
void SAMRAI::solv::CVODESolver::setFinalValueOfIndependentVariable (double t_f, bool cvode_needs_initialization) [inline]
Set final value for independent variable (i.e. the value of independent variable to integrate the system to). The boolean argument specifies whether CVODE should be re-initialized (i.e. on first step) or if we are taking subsequent steps in a sequence, in which case it is not initialized.
void SAMRAI::solv::CVODESolver::setInitialConditionVector (SundialsAbstractVector * ic_vector) [inline]
Set initial condition vector.
Precondition:
ic_vector != 0
References TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setMaximumLinearMultistepMethodOrder (int max_order) [inline]
Set maximum order for the linear multistep method. By default, this is set to 12 for ADAMS methods and 5 for BDF methods.
Precondition:
max_order >= 0
References TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setMaximumNumberOfInternalSteps (int max_num_internal_steps) [inline]
Set maximum number of internal steps to be taken by the solver in its attempt to reach t_f. By default, this is set to 500.
Precondition:
max_num_internal_steps >= 0
References TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setMaximumNumberOfNilStepWarnings (int max_num_warnings) [inline]
Set maximum number of warning messages issued by the solver that (t + h == t) on the next internal step. By default, this is set to 10.
Precondition:
max_num_warnings >= 0
References TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setInitialStepSize (double init_step_size) [inline]
Set initial step size.
Precondition:
init_step_size >= 0.0
References TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setMaximumAbsoluteStepSize (double max_step_size) [inline]
Set maximum absolute value of step size allowed. By default, there is no upper bound on the absolute value of step size.
Precondition:
max_step_size >= 0.0
References TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setMinimumAbsoluteStepSize (double min_step_size) [inline]
Set minimum absolute value of step size allowed. By default, this is set to 0.0.
Precondition:
min_step_size >= 0.0
References TBOX_ASSERT.
void SAMRAI::solv::CVODESolver::setPreconditioningType (int precondition_type) [inline]
Set the preconditioning type to be used by CVSpgmr. This must be one of the four enumeration constants NONE, LEFT, RIGHT, or BOTH defined in iterativ.h. These correspond to no preconditioning, left preconditioning only, right preconditioning only, and both left and right preconditioning, respectively.
Precondition:
(precondition_type == PREC_NONE) || (precondition_type == PREC_LEFT) || (precondition_type == PREC_RIGHT) || (precondition_type == PREC_BOTH)
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setGramSchmidtType (int gs_type) [inline]
Set the Gram-Schmidt orthogonalization type to be used by CVSpgmr. This must be one of the two enumeration constants MODIFIED_GS or CLASSICAL_GS defined in iterativ.h. These correspond to using modified Gram-Schmidt and classical Gram-Schmidt, respectively.
Precondition:
(gs_type == CLASSICAL_GS) || (gs_type == MODIFIED_GS)
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setMaxKrylovDimension (int max_krylov_dim) [inline]
Set the maximum Krylov dimension to be used by CVSpgmr. This is an optional input to the CVSPGMR solver. Pass 0 to use the default value MIN(num_equations, CVSPGMR_MAXL=5).
Precondition:
max_krylov_dim >= 0
References TBOX_ASSERT.
Referenced by CVODESolver().
void SAMRAI::solv::CVODESolver::setCVSpgmrToleranceScaleFactor (double tol_scale_factor) [inline]
Set the factor by which the tolerance on the nonlinear iteration is multiplied to get a tolerance on the linear iteration. This is an optional input to the CVSPGMR solver. Pass 0 to use the default value CVSPGMR_DELT = 0.05.
Precondition:
tol_scale_factor >= 0
References TBOX_ASSERT.
Referenced by CVODESolver().
SundialsAbstractVector* SAMRAI::solv::CVODESolver::getSolutionVector () const [inline]
Get solution vector.
int SAMRAI::solv::CVODESolver::getDkyVector (double t, int k, SundialsAbstractVector * dky) const [inline]
Get k-th derivative vector at the specified value of the independent variable, t. The integer return value is return code the CVODE CVodeDky() function. The following is a table of termination codes and a brief description of their meanings.
CVodeDky Return Codes:
OKAY (=0) CVodeDky succeeded.
BAD_K (=-1)
BAD_T (=-2)
BAD_DKY (=-3)
DKY_NO_MEM (=-4)
Important Notes:
t must lie in the interval [t_cur - h, t_cur] where t_cur is the current internal time reached and h is the last internal step size successfully used by the solver.
k may take on value 0, 1, . . . q where q is the order of the current linear multistep method being used.
the dky vector must be allocated by the user.
it is only leagal to call this method after a successful return from the solve() method.
References SAMRAI::solv::SundialsAbstractVector::getNVector().
double SAMRAI::solv::CVODESolver::getActualFinalValueOfIndependentVariable () const [inline]
Get actual value of the independent variable that CVODE integrated to (i.e. the value of t that actually corresponds to the solution vector y).
void SAMRAI::solv::CVODESolver::printStatistics (std::ostream & os) const [inline]
Print CVODE and CVSpgmr statistics.
References printCVODEStatistics(), and printCVSpgmrStatistics().
void SAMRAI::solv::CVODESolver::printCVODEStatistics (std::ostream & os) const
Print CVODE statistics to the stream.
The abbreviations printed out refer to the following quantities:
lenrw size (in double words) of memory used for doubles
leniw size (in integer words) of memory used for integers
nst cumulative number of internal steps taken by solver
nfe number of right-hand side function evaluations
nni number of NEWTON iterations performed
nsetups number of calls made to linear solver's setup routine
netf number of local error test failures
ncfn number of nonlinear convergence failures
qu order used during the last internal step
qcur order to be used on the next internal step
hu step size for the last internal step
hcur step size to be attempted on the next internal step
tcur current internal value of t reached by the solver
tolsf suggested tolerance scaling factor
References getCurrentInternalValueOfIndependentVariable(), getCVODEMemoryUsageForDoubles(), getCVODEMemoryUsageForIntegers(), getCVODESuggestedToleranceScalingFactor(), getNumberOfInternalStepsTaken(), getNumberOfLinearSolverSetupCalls(), getNumberOfLocalErrorTestFailures(), getNumberOfNewtonIterations(), getNumberOfNonlinearConvergenceFailures(), getNumberOfRHSFunctionCalls(), getOrderToBeUsedDuringNextInternalStep(), getOrderUsedDuringLastInternalStep(), getStepSizeForLastInternalStep(), and getStepSizeForNextInternalStep().
Referenced by printStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfInternalStepsTaken () const [inline]
Return the cumulative number of internal steps taken by the solver.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfRHSFunctionCalls () const [inline]
Return the number of calls to the right-hand side function.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfLinearSolverSetupCalls () const [inline]
Return the number of calls made to linear solver setup routines.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfNewtonIterations () const [inline]
Return the number of NEWTON iterations performed.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfNonlinearConvergenceFailures () const [inline]
Return the number of nonlinear convergence failures that have occurred.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfLocalErrorTestFailures () const [inline]
Return the number of local error test failures.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getOrderUsedDuringLastInternalStep () const [inline]
Return the order of the linear multistep method used during the last internal step.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getOrderToBeUsedDuringNextInternalStep () const [inline]
Return the order of the linear multistep method to be used during the next internal step.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getCVODEMemoryUsageForDoubles () const [inline]
Return the size (in LLNL_REAL words) of memory used for LLNL_REALS.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
int SAMRAI::solv::CVODESolver::getCVODEMemoryUsageForIntegers () const [inline]
Return the size (in integer words) of memory used for integers.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
double SAMRAI::solv::CVODESolver::getStepSizeForLastInternalStep () const [inline]
Return the step size for the last internal step.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printClassData(), and printCVODEStatistics().
double SAMRAI::solv::CVODESolver::getStepSizeForNextInternalStep () const [inline]
Return the step size to be used in the next internal step.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
double SAMRAI::solv::CVODESolver::getCurrentInternalValueOfIndependentVariable () const [inline]
Return the current internal value of the independent variable reached by the solver.
Note: if the solver was not set to collect statistics, the minimum double value (as defined in float.h) is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
double SAMRAI::solv::CVODESolver::getCVODESuggestedToleranceScalingFactor () const [inline]
Return the suggested tolerance scaling factor.
Note: if the solver was not set to collect statistics, a value of -1 is returned.
References CVODE_SAMRAI_ERROR.
Referenced by printCVODEStatistics().
void SAMRAI::solv::CVODESolver::printCVSpgmrStatistics (std::ostream & os) const
Print CVSpgmr statistics to the stream.
The abbreviations printed out refer to the following quantities:
spgmr_lrw size (in double words) of memory used for doubles
spgmr_liw size (in integer words) of memory used for integers
nli number of linear iterations
ncfl number of linear convergence failures
npe number of preconditioner evaluations
nps number of calls to CVSpgmrPrecondSolve()
References getCVSpgmrMemoryUsageForDoubles(), getCVSpgmrMemoryUsageForIntegers(), getNumberOfLinearConvergenceFailures(), getNumberOfLinearIterations(), getNumberOfPreconditionerEvaluations(), getNumberOfPrecondSolveCalls(), and SAMRAI::tbox::Utilities::intToString().
Referenced by printStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfPreconditionerEvaluations () const [inline]
Return the number of preconditioner evaluations.
References CVODE_SAMRAI_ERROR.
Referenced by printCVSpgmrStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfLinearIterations () const [inline]
Return the number of linear iterations.
References CVODE_SAMRAI_ERROR.
Referenced by printCVSpgmrStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfPrecondSolveCalls () const [inline]
Return the number of CVSpgmrPrecondSolve() calls.
References CVODE_SAMRAI_ERROR.
Referenced by printCVSpgmrStatistics().
int SAMRAI::solv::CVODESolver::getNumberOfLinearConvergenceFailures () const [inline]
Return the number of linear convergence failures.
References CVODE_SAMRAI_ERROR.
Referenced by printCVSpgmrStatistics().
int SAMRAI::solv::CVODESolver::getCVSpgmrMemoryUsageForDoubles () const [inline]
Return the size (in double words) of memory used for doubles.
References CVODE_SAMRAI_ERROR.
Referenced by printCVSpgmrStatistics().
int SAMRAI::solv::CVODESolver::getCVSpgmrMemoryUsageForIntegers () const [inline]
Return the size (in integer words) of memory used for integers.
References CVODE_SAMRAI_ERROR.
Referenced by printCVSpgmrStatistics().
void SAMRAI::solv::CVODESolver::printClassData (std::ostream & os) const [virtual]
Print out all data members for this object.
References getStepSizeForLastInternalStep(), and SAMRAI::solv::SundialsAbstractVector::printVector().
const std::string& SAMRAI::solv::CVODESolver::getObjectName () const [inline]
Returns the object name.
The documentation for this class was generated from the following files:
source/SAMRAI/solv/CVODESolver.h
source/SAMRAI/solv/CVODESolver.C