SAMRAI: SAMRAI::pdat::CellIndex Class Reference
SAMRAI::pdat::CellIndex Class Reference
#include <source/SAMRAI/pdat/CellIndex.h>
Public Member Functions
CellIndex (const tbox::Dimension &dim)
CellIndex (const hier::Index &rhs)
CellIndex (const CellIndex &rhs)
CellIndex & operator= (const CellIndex &rhs)
~CellIndex ()
CellIndex & operator+= (const hier::IntVector &rhs)
CellIndex operator+ (const hier::IntVector &rhs) const
CellIndex & operator+= (const int rhs)
CellIndex operator+ (const int rhs) const
CellIndex & operator-= (const hier::IntVector &rhs)
CellIndex operator- (const hier::IntVector &rhs) const
CellIndex & operator-= (const int rhs)
CellIndex operator- (const int rhs) const
CellIndex & operator*= (const hier::IntVector &rhs)
CellIndex operator* (const hier::IntVector &rhs) const
CellIndex & operator*= (const int rhs)
CellIndex operator* (const int rhs) const
bool operator== (const CellIndex &rhs) const
bool operator!= (const CellIndex &rhs) const
Detailed Description
Class CellIndex implements a simple n-dimensional integer vector for cell centered variables. Cell indices contain an integer index location in AMR index space and are identical to the AMR indices.
See also:
hier::Index
CellData
CellGeometry
CellIterator
Constructor & Destructor Documentation
SAMRAI::pdat::CellIndex::CellIndex (const tbox::Dimension & dim) [explicit]
The default constructor for a cell index creates an uninitialized index.
SAMRAI::pdat::CellIndex::CellIndex (const hier::Index & rhs) [explicit]
Construct a cell index from a regular AMR index.
SAMRAI::pdat::CellIndex::CellIndex (const CellIndex & rhs)
The copy constructor creates a cell index equal to the argument.
SAMRAI::pdat::CellIndex::~CellIndex ()
The cell index destructor does nothing interesting.
Member Function Documentation
CellIndex& SAMRAI::pdat::CellIndex::operator= (const CellIndex & rhs) [inline]
The assignment operator sets the cell index equal to the argument.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
CellIndex& SAMRAI::pdat::CellIndex::operator+= (const hier::IntVector & rhs) [inline]
Plus-equals operator for a cell index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator+=().
CellIndex SAMRAI::pdat::CellIndex::operator+ (const hier::IntVector & rhs) const [inline]
Plus operator for a cell index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
CellIndex& SAMRAI::pdat::CellIndex::operator+= (const int rhs) [inline]
Plus-equals operator for a cell index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator+=().
CellIndex SAMRAI::pdat::CellIndex::operator+ (const int rhs) const [inline]
Plus operator for a cell index and an integer.
Reimplemented from SAMRAI::hier::Index.
CellIndex& SAMRAI::pdat::CellIndex::operator-= (const hier::IntVector & rhs) [inline]
Minus-equals operator for a cell index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator-=().
CellIndex SAMRAI::pdat::CellIndex::operator- (const hier::IntVector & rhs) const [inline]
Minus operator for a cell index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
CellIndex& SAMRAI::pdat::CellIndex::operator-= (const int rhs) [inline]
Minus-equals operator for a cell index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator-=().
CellIndex SAMRAI::pdat::CellIndex::operator- (const int rhs) const [inline]
Minus operator for a cell index and an integer.
Reimplemented from SAMRAI::hier::Index.
CellIndex& SAMRAI::pdat::CellIndex::operator*= (const hier::IntVector & rhs) [inline]
Times-equals operator for a cell index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator*=().
CellIndex SAMRAI::pdat::CellIndex::operator* (const hier::IntVector & rhs) const [inline]
Times operator for a cell index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
CellIndex& SAMRAI::pdat::CellIndex::operator*= (const int rhs) [inline]
Times-equals operator for a cell index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator*=().
CellIndex SAMRAI::pdat::CellIndex::operator* (const int rhs) const [inline]
Times operator for a cell index and an integer.
Reimplemented from SAMRAI::hier::Index.
bool SAMRAI::pdat::CellIndex::operator== (const CellIndex & rhs) const [inline]
Returns true if two cell index objects are equal. All components must be the same for equality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::pdat::CellIndex::operator!= (const CellIndex & rhs) const [inline]
Returns true if two cell index objects are not equal. Any of the components may be different for inequality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/CellIndex.h
source/SAMRAI/pdat/CellIndex.C