SAMRAI: SAMRAI::hier::Transformation Class Reference
SAMRAI::hier::Transformation Class Reference
Class Transformation represents generalized transformations between coordinate systems or within coordinate systems.
#include <source/SAMRAI/hier/Transformation.h>
Public Types
enum RotationIdentifier {
NO_ROTATE = 0, IUP = 0, IDOWN = 1, IUP_JUP = 0,
JUP_IDOWN = 1, IDOWN_JDOWN = 2, JDOWN_IUP = 3, IUP_JUP_KUP = 0,
KUP_IUP_JUP = 1, JUP_KUP_IUP = 2, IDOWN_KUP_JUP = 3, KUP_JUP_IDOWN = 4,
JUP_IDOWN_KUP = 5, KDOWN_JUP_IUP = 6, IUP_KDOWN_JUP = 7, JUP_IUP_KDOWN = 8,
KDOWN_IDOWN_JUP = 9, IDOWN_JUP_KDOWN = 10, JUP_KDOWN_IDOWN = 11, JDOWN_IUP_KUP = 12,
IUP_KUP_JDOWN = 13, KUP_JDOWN_IUP = 14, JDOWN_KUP_IDOWN = 15, IDOWN_JDOWN_KUP = 16,
KUP_IDOWN_JDOWN = 17, JDOWN_KDOWN_IUP = 18, KDOWN_IUP_JDOWN = 19, IUP_JDOWN_KDOWN = 20,
JDOWN_IDOWN_KDOWN = 21, KDOWN_JDOWN_IDOWN = 22, IDOWN_KDOWN_JDOWN = 23
}
Type that identifies the rotation relationship between two blocks.
Public Member Functions
Transformation (const RotationIdentifier rotation, const IntVector &offset, const BlockId &begin_block, const BlockId &end_block)
Constructor to set rotation and offset.
Transformation (const IntVector &offset)
Constructor that sets only offset.
Transformation (const Transformation &copy_trans)
Copy constructor.
~Transformation ()
Destructor.
RotationIdentifier getRotation () const
Get the rotation.
const IntVector & getOffset () const
Get the offset.
void transform (Box &box) const
Transform the Box in the way defined by this object.
void inverseTransform (Box &box) const
Apply the inverse of this object's transformation to the Box.
Transformation getInverseTransformation () const
Get a Tranformation object that defines the inverse of this tranformation.
Transformation & operator= (const Transformation &rhs)
Assignment operator.
const BlockId & getBeginBlock () const
Get the BlockId for the Box before transformation.
const BlockId & getEndBlock () const
Get the BlockId for the Box after transformation.
Static Public Member Functions
static RotationIdentifier getRotationIdentifier (const std::vector< std::string > &rotation_string, const tbox::Dimension &dim)
Map a string-based identifier of a rotation operation to a RotationIdentifier value.
static RotationIdentifier getReverseRotationIdentifier (const RotationIdentifier rotation, const tbox::Dimension &dim)
static method to get a reverse rotation identifier
static void calculateReverseShift (IntVector &back_shift, const IntVector &shift, const RotationIdentifier rotation)
static method to get a reverse shift.
static void rotateIndex (int *index, const tbox::Dimension &dim, const RotationIdentifier rotation)
rotate a cell centered index from one index space to another
static void rotateIndex (Index &index, const RotationIdentifier rotation)
rotate a cell centered index from one index space to another
Detailed Description
Class Transformation represents generalized transformations between coordinate systems or within coordinate systems.
Transformation is used to provide a way to handle communication of data between patches that lie on different coordinate systems (such as different blocks in a multiblock mesh) or communication between opposite sides of a periodic mesh. This class is able to transform the index space of a source patch to the index space of a destination patch (or vice versa) so that the overlap between data on the patches can be computed.
Transformation can also handle the trival case where the source and destination index spaces need no transformation.
The Transformation is represented by a RotationIdentifier and an offset IntVector. When transforming a Box, this class rotates the Box around the origin according to RotationIdentifier, and then shifts the Box by the offset. When dealing with periodic conditions, there rotation is always the zero value NO_ROTATE and only the offset shift is invoked. For trivial transformations, the rotation is NO_ROTATE and the IntVector is a zero vector.
See also:
BoxOverlap
BoxGeometry
VariableFillPattern
Member Enumeration Documentation
enum SAMRAI::hier::Transformation::RotationIdentifier
Type that identifies the rotation relationship between two blocks.
Enumerator:
NO_ROTATE
IUP
IDOWN
IUP_JUP
JUP_IDOWN
IDOWN_JDOWN
JDOWN_IUP
IUP_JUP_KUP
KUP_IUP_JUP
JUP_KUP_IUP
IDOWN_KUP_JUP
KUP_JUP_IDOWN
JUP_IDOWN_KUP
KDOWN_JUP_IUP
IUP_KDOWN_JUP
JUP_IUP_KDOWN
KDOWN_IDOWN_JUP
IDOWN_JUP_KDOWN
JUP_KDOWN_IDOWN
JDOWN_IUP_KUP
IUP_KUP_JDOWN
KUP_JDOWN_IUP
JDOWN_KUP_IDOWN
IDOWN_JDOWN_KUP
KUP_IDOWN_JDOWN
JDOWN_KDOWN_IUP
KDOWN_IUP_JDOWN
IUP_JDOWN_KDOWN
JDOWN_IDOWN_KDOWN
KDOWN_JDOWN_IDOWN
IDOWN_KDOWN_JDOWN
Constructor & Destructor Documentation
SAMRAI::hier::Transformation::Transformation (const RotationIdentifier rotation, const IntVector & offset, const BlockId & begin_block, const BlockId & end_block)
Constructor to set rotation and offset.
If begin_block and end_block have different values, all Boxes transformed by an object constructed with this constructor will have their BlockIds changed from begin_block to end_block.
Parameters:
[in] rotation specifies rotation, if any, between blocks
[in] offset offset to be applied after rotation
[in] begin_block Block before the transformation
[in] end_block Block after the transformation
SAMRAI::hier::Transformation::Transformation (const IntVector & offset) [explicit]
Constructor that sets only offset.
The RotationIdentifier is set to NO_ROTATE. This constructor should be used in cases where the calling code knows that the Transformation is trivial or periodic. Pass in a zero IntVector to construct a trivial Transformation.
Any Boxes transformed by an object constructed with this constructor will not have their BlockIds changed.
Parameters:
[in] offset
SAMRAI::hier::Transformation::Transformation (const Transformation & copy_trans)
Copy constructor.
Parameters:
[in] copy_trans
SAMRAI::hier::Transformation::~Transformation ()
Destructor.
Member Function Documentation
RotationIdentifier SAMRAI::hier::Transformation::getRotation () const [inline]
Get the rotation.
Referenced by SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::OuterfaceData< TYPE >::copy2(), SAMRAI::hier::BaseGridGeometry::Neighbor::getRotationIdentifier(), SAMRAI::pdat::SideOverlap::getSourceBoxContainer(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), SAMRAI::pdat::SideData< TYPE >::packStream(), SAMRAI::pdat::NodeData< TYPE >::packStream(), SAMRAI::pdat::FaceData< TYPE >::packStream(), SAMRAI::pdat::EdgeData< TYPE >::packStream(), SAMRAI::pdat::CellData< TYPE >::packStream(), SAMRAI::hier::BaseGridGeometry::putToRestart(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::pdat::EdgeGeometry::transform(), and SAMRAI::pdat::CellGeometry::transform().
const IntVector& SAMRAI::hier::Transformation::getOffset () const [inline]
Get the offset.
Referenced by SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::OuterfaceData< TYPE >::copy2(), SAMRAI::pdat::EdgeOverlap::EdgeOverlap(), SAMRAI::pdat::FaceOverlap::FaceOverlap(), SAMRAI::hier::BaseGridGeometry::Neighbor::getShift(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), SAMRAI::pdat::SideOverlap::getSourceOffset(), SAMRAI::pdat::NodeOverlap::getSourceOffset(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::pdat::EdgeOverlap::getSourceOffset(), SAMRAI::pdat::CellOverlap::getSourceOffset(), SAMRAI::hier::BaseGridGeometry::putToRestart(), SAMRAI::pdat::SideGeometry::setUpOverlap(), SAMRAI::pdat::OutersideGeometry::setUpOverlap(), SAMRAI::pdat::OuterfaceGeometry::setUpOverlap(), SAMRAI::pdat::OuteredgeGeometry::setUpOverlap(), SAMRAI::pdat::FaceGeometry::setUpOverlap(), SAMRAI::pdat::EdgeGeometry::setUpOverlap(), SAMRAI::pdat::SideOverlap::SideOverlap(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::pdat::EdgeGeometry::transform(), and SAMRAI::pdat::CellGeometry::transform().
void SAMRAI::hier::Transformation::transform (Box & box) const
Transform the Box in the way defined by this object.
Parameters:
[in,out] box The Box will be transformed
Precondition:
(box.getBlockId() == getBeginBlock()) || (getBeginBlock() == BlockId::invalidId())
References SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BlockId::invalidId(), SAMRAI::hier::Box::rotate(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::SideGeometry::computeDestinationBoxes(), SAMRAI::pdat::NodeGeometry::computeDestinationBoxes(), SAMRAI::pdat::FaceGeometry::computeDestinationBoxes(), SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes(), SAMRAI::pdat::CellGeometry::computeDestinationBoxes(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), SAMRAI::pdat::SideOverlap::getSourceBoxContainer(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), and SAMRAI::pdat::EdgeGeometry::transform().
void SAMRAI::hier::Transformation::inverseTransform (Box & box) const
Apply the inverse of this object's transformation to the Box.
If transform() and inverseTransform() are called consecutively on a Box, the Box will end up in its original state.
Parameters:
[in,out] box
Precondition:
(box.getBlockId() == getBeginBlock()) || (getBeginBlock() == BlockId::invalidId())
References calculateReverseShift(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::IntVector::getDim(), getReverseRotationIdentifier(), SAMRAI::hier::BlockId::invalidId(), SAMRAI::hier::Box::rotate(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::NodeOverlap::getSourceBoxContainer(), SAMRAI::pdat::CellOverlap::getSourceBoxContainer(), and SAMRAI::pdat::ArrayData< TYPE >::packStream().
Transformation SAMRAI::hier::Transformation::getInverseTransformation () const
Get a Tranformation object that defines the inverse of this tranformation.
References calculateReverseShift(), SAMRAI::hier::IntVector::getDim(), and getReverseRotationIdentifier().
Referenced by SAMRAI::pdat::SideOverlap::getSourceBoxContainer(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), and SAMRAI::pdat::EdgeOverlap::getSourceBoxContainer().
Transformation& SAMRAI::hier::Transformation::operator= (const Transformation & rhs) [inline]
Assignment operator.
const BlockId& SAMRAI::hier::Transformation::getBeginBlock () const [inline]
Get the BlockId for the Box before transformation.
Referenced by SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::FaceOverlap::getSourceBoxContainer(), SAMRAI::pdat::FaceData< TYPE >::packStream(), and SAMRAI::hier::BaseGridGeometry::putToRestart().
const BlockId& SAMRAI::hier::Transformation::getEndBlock () const [inline]
Get the BlockId for the Box after transformation.
Referenced by SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::FaceData< TYPE >::packStream(), and SAMRAI::hier::BaseGridGeometry::putToRestart().
Transformation::RotationIdentifier SAMRAI::hier::Transformation::getRotationIdentifier (const std::vector< std::string > & rotation_string, const tbox::Dimension & dim) [static]
Map a string-based identifier of a rotation operation to a RotationIdentifier value.
The rotation_string array must have each entry intended to be used to create a value of the enumerated type RotationIdentifier. For example, to create the value JUP_IDOWN_KUP, the strings in the array should be "J_UP", "I_DOWN", and "K_UP", in that order. See the comments for the RotationIdentifier definition for the explanation of the meaning of the RotationIdentifier values.
A run-time error will occur if the strings do not match the format needed to create a valid Transformation::RotationIdentifier value.
Returns:
RotationIdentifier determined by the strings.
Parameters:
[in] rotation_string
[in] dim
Precondition:
rotation_string.size() == dim.getValue()
(dim.getValue() == 1) || (dim.getValue() == 2) || (dim.getValue() == 3)
References SAMRAI::tbox::Dimension::getValue(), IDOWN, IDOWN_JDOWN, IDOWN_JDOWN_KUP, IDOWN_JUP_KDOWN, IDOWN_KDOWN_JDOWN, IDOWN_KUP_JUP, IUP, IUP_JDOWN_KDOWN, IUP_JUP, IUP_JUP_KUP, IUP_KDOWN_JUP, IUP_KUP_JDOWN, JDOWN_IDOWN_KDOWN, JDOWN_IUP, JDOWN_IUP_KUP, JDOWN_KDOWN_IUP, JDOWN_KUP_IDOWN, JUP_IDOWN, JUP_IDOWN_KUP, JUP_IUP_KDOWN, JUP_KDOWN_IDOWN, JUP_KUP_IUP, KDOWN_IDOWN_JUP, KDOWN_IUP_JDOWN, KDOWN_JDOWN_IDOWN, KDOWN_JUP_IUP, KUP_IDOWN_JDOWN, KUP_IUP_JUP, KUP_JDOWN_IUP, KUP_JUP_IDOWN, NO_ROTATE, TBOX_ASSERT, and TBOX_ERROR.
Transformation::RotationIdentifier SAMRAI::hier::Transformation::getReverseRotationIdentifier (const RotationIdentifier rotation, const tbox::Dimension & dim) [static]
static method to get a reverse rotation identifier
A rotation identifier signifies a specific rotation of an index space. For each rotation there is another rotation that rotates in the exact opposite manner. This routine returns the identifier of the reverse rotation corresponding to the given rotation.
Returns:
The RotationIdentifier opposite the input parameter
Parameters:
[in] rotation Rotation for which the reverse rotation is sought
[in] dim Dimension being used
Precondition:
(dim.getValue() == 1) || (dim.getValue() == 2) || (dim.getValue() == 3)
References SAMRAI::tbox::Dimension::getValue(), IDOWN_JDOWN_KUP, IDOWN_JUP_KDOWN, IDOWN_KDOWN_JDOWN, IDOWN_KUP_JUP, IUP_JDOWN_KDOWN, IUP_JUP_KUP, IUP_KDOWN_JUP, IUP_KUP_JDOWN, JDOWN_IDOWN_KDOWN, JDOWN_IUP_KUP, JDOWN_KDOWN_IUP, JDOWN_KUP_IDOWN, JUP_IDOWN_KUP, JUP_IUP_KDOWN, JUP_KDOWN_IDOWN, JUP_KUP_IUP, KDOWN_IDOWN_JUP, KDOWN_IUP_JDOWN, KDOWN_JDOWN_IDOWN, KDOWN_JUP_IUP, KUP_IDOWN_JDOWN, KUP_IUP_JUP, KUP_JDOWN_IUP, KUP_JUP_IDOWN, NO_ROTATE, and TBOX_ERROR.
Referenced by calculateReverseShift(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), getInverseTransformation(), inverseTransform(), and SAMRAI::hier::BaseGridGeometry::registerNeighbors().
void SAMRAI::hier::Transformation::calculateReverseShift (IntVector & back_shift, const IntVector & shift, const RotationIdentifier rotation) [static]
static method to get a reverse shift.
Given a rotation and shift that define the relationship between two neighboring blocks, get a reverse shift that, combined with the reverse rotation from getReverseRotationIdentifier, can be used to reverse the effect of the original rotation and shift.
Parameters:
[out] back_shift
[in] shift
[in] rotation
Precondition:
back_shift.getDim() == shift.getDim()
(dim.getValue() == 1) || (dim.getValue() == 2) || (dim.getValue() == 3)
References SAMRAI::hier::IntVector::getDim(), getReverseRotationIdentifier(), IDOWN, IDOWN_JDOWN, IDOWN_JDOWN_KUP, IDOWN_JUP_KDOWN, IDOWN_KDOWN_JDOWN, IDOWN_KUP_JUP, IUP, IUP_JDOWN_KDOWN, IUP_JUP, IUP_JUP_KUP, IUP_KDOWN_JUP, IUP_KUP_JDOWN, JDOWN_IDOWN_KDOWN, JDOWN_IUP, JDOWN_IUP_KUP, JDOWN_KDOWN_IUP, JDOWN_KUP_IDOWN, JUP_IDOWN, JUP_IDOWN_KUP, JUP_IUP_KDOWN, JUP_KDOWN_IDOWN, JUP_KUP_IUP, KDOWN_IDOWN_JUP, KDOWN_IUP_JDOWN, KDOWN_JDOWN_IDOWN, KDOWN_JUP_IUP, KUP_IDOWN_JDOWN, KUP_IUP_JUP, KUP_JDOWN_IUP, KUP_JUP_IDOWN, NO_ROTATE, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), getInverseTransformation(), inverseTransform(), and SAMRAI::hier::BaseGridGeometry::registerNeighbors().
void SAMRAI::hier::Transformation::rotateIndex (int * index, const tbox::Dimension & dim, const RotationIdentifier rotation) [static]
rotate a cell centered index from one index space to another
The parameter index is an int pointer with points to an array of int data, length DIM. It signifies an ijk location in a cell centered index space. According to the rotation number, the location will be rotated around the origin, with the new values overwriting the original values in the array pointed to by index.
Parameters:
index array identifying a cell centered point in index space
dim Dimension of the index and the hierarchy where it is located
rotation identifier of the rotation that will be applied to index
Precondition:
(dim.getValue() == 1) || (dim.getValue() == 2) || (dim.getValue() == 3)
References SAMRAI::tbox::Dimension::getValue(), IDOWN, IDOWN_JDOWN_KUP, IDOWN_JUP_KDOWN, IDOWN_KDOWN_JDOWN, IDOWN_KUP_JUP, IUP, IUP_JDOWN_KDOWN, IUP_JUP_KUP, IUP_KDOWN_JUP, IUP_KUP_JDOWN, JDOWN_IDOWN_KDOWN, JDOWN_IUP_KUP, JDOWN_KDOWN_IUP, JDOWN_KUP_IDOWN, JUP_IDOWN_KUP, JUP_IUP_KDOWN, JUP_KDOWN_IDOWN, JUP_KUP_IUP, KDOWN_IDOWN_JUP, KDOWN_IUP_JDOWN, KDOWN_JDOWN_IDOWN, KDOWN_JUP_IUP, KUP_IDOWN_JDOWN, KUP_IUP_JUP, KUP_JDOWN_IUP, KUP_JUP_IDOWN, and TBOX_ERROR.
Referenced by rotateIndex().
static void SAMRAI::hier::Transformation::rotateIndex (Index & index, const RotationIdentifier rotation) [inline, static]
rotate a cell centered index from one index space to another
According to the rotation number, the location of the given cell centered Index will be rotated around the origin, overwriting the original value of the Index.
Parameters:
index a cell centered point in index space
rotation identifier of the rotation that will be applied to index
References SAMRAI::hier::IntVector::getDim(), and rotateIndex().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/Transformation.h
source/SAMRAI/hier/Transformation.C