SAMRAI: SAMRAI::pdat::FaceIndex Class Reference
SAMRAI::pdat::FaceIndex Class Reference
#include <source/SAMRAI/pdat/FaceIndex.h>
Public Types
enum {
X = 0, Y = 1, Z = 2, Lower = 0,
Upper = 1
}
Public Member Functions
FaceIndex (const tbox::Dimension &dim)
FaceIndex (const hier::Index &rhs, const int axis, const int face)
FaceIndex (const FaceIndex &rhs)
FaceIndex & operator= (const FaceIndex &rhs)
~FaceIndex ()
int getAxis () const
void setAxis (const int axis)
hier::Index toCell (const int face) const
FaceIndex & operator+= (const hier::IntVector &rhs)
FaceIndex operator+ (const hier::IntVector &rhs) const
FaceIndex & operator+= (const int rhs)
FaceIndex operator+ (const int rhs) const
FaceIndex & operator-= (const hier::IntVector &rhs)
FaceIndex operator- (const hier::IntVector &rhs) const
FaceIndex & operator-= (const int rhs)
FaceIndex operator- (const int rhs) const
FaceIndex & operator*= (const hier::IntVector &rhs)
FaceIndex operator* (const hier::IntVector &rhs) const
FaceIndex & operator*= (const int rhs)
FaceIndex operator* (const int rhs) const
bool operator== (const FaceIndex &rhs) const
bool operator!= (const FaceIndex &rhs) const
Detailed Description
Class FaceIndex implements a simple n-dimensional integer vector for face centered variables. Face indices contain an integer index location in AMR index space along with the designated face axis (X=0, Y=1, or Z=2). See the face box geometry class for more information about the mapping between the AMR index space and the face indices.
See also:
hier::Index
FaceData
FaceGeometry
FaceIterator
Member Enumeration Documentation
anonymous enum
Enumerator:
X
Y
Z
Lower
Upper
Constructor & Destructor Documentation
SAMRAI::pdat::FaceIndex::FaceIndex (const tbox::Dimension & dim) [explicit]
The default constructor for a face index creates an uninitialized index.
SAMRAI::pdat::FaceIndex::FaceIndex (const hier::Index & rhs, const int axis, const int face)
Construct a face index from a regular index, axis, and face. The axis can be one of FaceIndex::X (0), FaceIndex::Y (1), or FaceIndex::Z (2). The face argument can be one of the constants FaceIndex::Lower (0) or FaceIndex::Upper (1).
References SAMRAI::hier::Index::getDim(), and SAMRAI::tbox::Dimension::getValue().
SAMRAI::pdat::FaceIndex::FaceIndex (const FaceIndex & rhs)
The copy constructor creates a face index equal to the argument.
SAMRAI::pdat::FaceIndex::~FaceIndex ()
The face index destructor does nothing interesting.
Member Function Documentation
FaceIndex& SAMRAI::pdat::FaceIndex::operator= (const FaceIndex & rhs) [inline]
The assignment operator sets the face index equal to the argument.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
int SAMRAI::pdat::FaceIndex::getAxis () const [inline]
Get the axis for which this face index is defined (X=0, Y=1, Z=2).
Referenced by SAMRAI::pdat::OuterfaceData< TYPE >::operator()(), SAMRAI::pdat::FaceData< TYPE >::operator()(), and SAMRAI::pdat::FaceGeometry::transform().
void SAMRAI::pdat::FaceIndex::setAxis (const int axis) [inline]
Set the face axis (X=0, Y=1, Z=2).
Referenced by SAMRAI::pdat::FaceGeometry::transform().
hier::Index SAMRAI::pdat::FaceIndex::toCell (const int face) const
Convert the face index into the index on the left hand face (argument face == 0) or the right hand face (argument face == 1).
References SAMRAI::hier::Index::getDim(), and SAMRAI::tbox::Dimension::getValue().
FaceIndex& SAMRAI::pdat::FaceIndex::operator+= (const hier::IntVector & rhs) [inline]
Plus-equals operator for a face index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator+=().
FaceIndex SAMRAI::pdat::FaceIndex::operator+ (const hier::IntVector & rhs) const [inline]
Plus operator for a face index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
FaceIndex& SAMRAI::pdat::FaceIndex::operator+= (const int rhs) [inline]
Plus-equals operator for a face index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator+=().
FaceIndex SAMRAI::pdat::FaceIndex::operator+ (const int rhs) const [inline]
Plus operator for a face index and an integer.
Reimplemented from SAMRAI::hier::Index.
FaceIndex& SAMRAI::pdat::FaceIndex::operator-= (const hier::IntVector & rhs) [inline]
Minus-equals operator for a face index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator-=().
FaceIndex SAMRAI::pdat::FaceIndex::operator- (const hier::IntVector & rhs) const [inline]
Minus operator for a face index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
FaceIndex& SAMRAI::pdat::FaceIndex::operator-= (const int rhs) [inline]
Minus-equals operator for a face index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator-=().
FaceIndex SAMRAI::pdat::FaceIndex::operator- (const int rhs) const [inline]
Minus operator for a face index and an integer.
Reimplemented from SAMRAI::hier::Index.
FaceIndex& SAMRAI::pdat::FaceIndex::operator*= (const hier::IntVector & rhs) [inline]
Times-equals operator for a face index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by operator*=().
FaceIndex SAMRAI::pdat::FaceIndex::operator* (const hier::IntVector & rhs) const [inline]
Times operator for a face index and an integer vector.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
FaceIndex& SAMRAI::pdat::FaceIndex::operator*= (const int rhs) [inline]
Times-equals operator for a face index and an integer.
Reimplemented from SAMRAI::hier::Index.
References operator*=().
FaceIndex SAMRAI::pdat::FaceIndex::operator* (const int rhs) const [inline]
Times operator for a face index and an integer.
Reimplemented from SAMRAI::hier::Index.
bool SAMRAI::pdat::FaceIndex::operator== (const FaceIndex & rhs) const [inline]
Returns true if two face index objects are equal. All components and the corresponding face axes must be the same for equality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::pdat::FaceIndex::operator!= (const FaceIndex & rhs) const [inline]
Returns true if two face index objects are not equal. Any of the components or axes may be different for inequality.
Precondition:
getDim() == rhs.getDim()
Reimplemented from SAMRAI::hier::Index.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/FaceIndex.h
source/SAMRAI/pdat/FaceIndex.C