SAMRAI: SAMRAI::solv::CartesianRobinBcHelper Class Reference
SAMRAI::solv::CartesianRobinBcHelper Class Reference
Helper utility for setting Robin boundary conditions.
#include <source/SAMRAI/solv/CartesianRobinBcHelper.h>
Public Member Functions
CartesianRobinBcHelper (const tbox::Dimension &dim, std::string object_name=std::string(), RobinBcCoefStrategy *coef_strategy=0)
Constructor using.
virtual ~CartesianRobinBcHelper (void)
Destructor.
const std::string & getObjectName () const
Get the name of this object.
const tbox::Dimension & getDim () const
Return the dimension of this object.
virtual void setPhysicalBoundaryConditions (hier::Patch &patch, const double fill_time, const hier::IntVector &ghost_width_to_fill)
Pure virtual function interface for physical boundary filling.
hier::IntVector getRefineOpStencilWidth (const tbox::Dimension &dim) const
Return maximum stencil width needed for user-defined data refinement operations performed by this object.
virtual void preprocessRefineBoxes (hier::Patch &fine, const hier::Patch &coarse, const hier::BoxContainer &fine_boxes, const hier::IntVector &ratio)
virtual void preprocessRefine (hier::Patch &fine, const hier::Patch &coarse, const hier::Box &fine_box, const hier::IntVector &ratio)
Perform user-defined patch data refinement operations.
virtual void postprocessRefineBoxes (hier::Patch &fine, const hier::Patch &coarse, const hier::BoxContainer &fine_boxes, const hier::IntVector &ratio)
virtual void postprocessRefine (hier::Patch &fine, const hier::Patch &coarse, const hier::Box &fine_box, const hier::IntVector &ratio)
Perform user-defined patch data refinement operations.
Functions to set boundary condition values
void setBoundaryValuesInCells (hier::Patch &patch, const double fill_time, const hier::IntVector &ghost_width_to_fill, int target_data_id, bool homogeneous_bc=false) const
Set the physical boundary condition by setting the value of the first ghost cells.
void setBoundaryValuesInCells (hier::PatchLevel &level, const double fill_time, const hier::IntVector &ghost_width_to_fill, int target_data_id, bool homogeneous_bc=false) const
Set ghost cells for an entire level.
void setBoundaryValuesAtNodes (hier::Patch &patch, const double fill_time, int target_data_id, bool homogeneous_bc=false) const
Set the physical boundary condition by setting the value of the boundary nodes.
Ways to provide the Robin bc coefficients
void setCoefImplementation (const RobinBcCoefStrategy *coef_strategy)
Provide an implementation of the RobinBcCoefStrategy for determining the boundary coefficients.
void setTargetDataId (int target_data_id)
Set the data id that should be filled when setting physical boundary conditions.
void setHomogeneousBc (bool homogeneous_bc)
Set whether boundary filling should assume homogeneous conditions.
Detailed Description
Helper utility for setting Robin boundary conditions.
This class is intended as a helper for performing the tedious task of setting boundary values for scalar quantities for the general case of boundary conditions known as the Robin boundary condition.
It uses the Robin boundary condition coefficients specified by a RobinBcCoefStrategy object to determine the boundary value to set. The exact value set depends on the allignment of the data and is derived from various discrete approximations of the Robin formula. This class currently supports cell-centered alignment and will support node-centered alignment in the future.
See RobinBcCoefStrategy for the description of the Robin boundary condition.
This class inherits and implements virtual functions from xfer::RefinePatchStrategy so it may be used to help create communication schedules if desired.
Constructor & Destructor Documentation
SAMRAI::solv::CartesianRobinBcHelper::CartesianRobinBcHelper (const tbox::Dimension & dim, std::string object_name = std::string(), RobinBcCoefStrategy * coef_strategy = 0) [explicit]
Constructor using.
Requires a concrete implementation of RobinBcCoefStrategy.
Parameters:
dim
object_name Name of the object, for general referencing.
coef_strategy Coefficients strategy being helped.
virtual SAMRAI::solv::CartesianRobinBcHelper::~CartesianRobinBcHelper (void) [virtual]
Destructor.
Member Function Documentation
virtual void SAMRAI::solv::CartesianRobinBcHelper::setPhysicalBoundaryConditions (hier::Patch & patch, const double fill_time, const hier::IntVector & ghost_width_to_fill) [virtual]
Pure virtual function interface for physical boundary filling.
Set data in ghost regions at patch boundaries that touch the physical domain boundary. The specific data values set in physical boundary ghost regions are determined by the boundary conditions needed by the user application. The patch data components that should be set in this function correspond to the "scratch" components specified in calls to the registerRefine() function in the RefineAlgorithm class.
Parameters:
[out] patch Patch on which to fill boundary data.
[in] fill_time Simulation time for boundary filling.
[in] ghost_width_to_fill Maximum ghost width to fill over all registered scratch components.
Implements SAMRAI::xfer::RefinePatchStrategy.
hier::IntVector SAMRAI::solv::CartesianRobinBcHelper::getRefineOpStencilWidth (const tbox::Dimension & dim) const [virtual]
Return maximum stencil width needed for user-defined data refinement operations performed by this object.
This is needed to determine the correct interpolatin data dependencies and to ensure that the data has a sufficient amount of ghost width.
For any user-defined interpolation operations implemented in the preprocess or postprocess methods, return the maximum stencil needed on a coarse patch to refine data to a fine patch. If your implementation doesn't work with the given dimension, return zero.
Implements SAMRAI::xfer::RefinePatchStrategy.
virtual void SAMRAI::solv::CartesianRobinBcHelper::preprocessRefineBoxes (hier::Patch & fine, const hier::Patch & coarse, const hier::BoxContainer & fine_boxes, const hier::IntVector & ratio) [virtual]
Perform user-defined patch data refinement operations on a list of boxes.
This member function is called before standard refining operations (expressed using concrete subclasses of the RefineOperator base class).
The default implementation of this virtual function loops over the box list and calls the preprocessRefine() method for a single box.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_boxes List of box regions on fine patch into which data is refined.
[in] ratio Refinement ratio between coarse and fine patches.
Precondition:
(fine.getDim() == coarse.getDim()) && (fine.getDim() == ratio.getDim())
Reimplemented from SAMRAI::xfer::RefinePatchStrategy.
virtual void SAMRAI::solv::CartesianRobinBcHelper::preprocessRefine (hier::Patch & fine, const hier::Patch & coarse, const hier::Box & fine_box, const hier::IntVector & ratio) [virtual]
Perform user-defined patch data refinement operations.
This member function is called before standard refine operations (expressed using concrete subclasses of the RefineOperator base class). The preprocess function must refine data from the scratch components on the coarse patch into the scratch components of the fine patch on the specified fine box region. Recall that the scratch components are specified in calls to the registerRefine() function in the RefineAlgorithm class.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_box Box region on fine patch into which data is refined.
[in] ratio Refinement ratio between coarse and fine patches.
Implements SAMRAI::xfer::RefinePatchStrategy.
virtual void SAMRAI::solv::CartesianRobinBcHelper::postprocessRefineBoxes (hier::Patch & fine, const hier::Patch & coarse, const hier::BoxContainer & fine_boxes, const hier::IntVector & ratio) [virtual]
Perform user-defined patch data refinement operations on a list of boxes.
This member function is called after standard refining operations (expressed using concrete subclasses of the RefineOperator base class).
The default implementation of this virtual function loops over the box list and calls the postprocessRefine() method for a single box.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_boxes List of box regions on fine patch into which data is refined.
[in] ratio Refinement ratio between coarse and fine patches.
Precondition:
(fine.getDim() == coarse.getDim()) && (fine.getDim() == ratio.getDim())
Reimplemented from SAMRAI::xfer::RefinePatchStrategy.
virtual void SAMRAI::solv::CartesianRobinBcHelper::postprocessRefine (hier::Patch & fine, const hier::Patch & coarse, const hier::Box & fine_box, const hier::IntVector & ratio) [virtual]
Perform user-defined patch data refinement operations.
This member function is called after standard refine operations (expressed using concrete subclasses of the RefineOperator base class). The preprocess function must refine data from the scratch components on the coarse patch into the scratch components of the fine patch on the specified fine box region. Recall that the scratch components are specified in calls to the registerRefine() function in the RefineAlgorithm class.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_box Box region on fine patch into which data is refined. *
[in] ratio Refinement ratio between coarse and fine patches.
Implements SAMRAI::xfer::RefinePatchStrategy.
void SAMRAI::solv::CartesianRobinBcHelper::setBoundaryValuesInCells (hier::Patch & patch, const double fill_time, const hier::IntVector & ghost_width_to_fill, int target_data_id, bool homogeneous_bc = false) const
Set the physical boundary condition by setting the value of the first ghost cells.
This function has an interface similar to the virtual function xfer::RefinePatchStrategy::setPhysicalBoundaryConditions(), and it may be used to help implement that function, but it does not serve the same purpose. The primary differences are:
It specializes to cell-centered variables.
Only one ghost cell width is filled. Setting a Robin boundary condition for cell-centered quantities requires only one ghost cell to be set. (More ghost cells can be filled by continuing the linear distribution of data beyond the first cell, but that is not implemented at this time.)
User must specify the index of the data whose ghost cells need to be filled. This index is used to determine the variable for which to set the boundary coefficients and to get the data to be set.
This function calls RobinBcStrategy::setBcCoefs() to get the coefficients, then it sets the values in the first ghost cell on the boundary.
To determine the value for the ghost cell, a linear approximation in the direction normal to the boundary is assumed. We write the following discrete approximations:
where the subscript b stands for the the boundary, i stands for the first cell inside the boundary and o stands for the first cell outside the boundary and h is the grid spacing normal to the boundary. Applying this to the Robin formula gives
or equivalently
After setting the edge (face in 3D) boundary conditions, linear approximations are used to set the boundary conditions of higher boundary types (nodes in 2D, edges and nodes in 3D).
In some cases, the calling function wants to set the boundary condition homogeneously, with g=0. This is useful in problems where the the solution of the homogeneous problem is required in solving the inhomogeneous problem. This function respects such requests specified through the argument homogeneous_bc.
void SAMRAI::solv::CartesianRobinBcHelper::setBoundaryValuesInCells (hier::PatchLevel & level, const double fill_time, const hier::IntVector & ghost_width_to_fill, int target_data_id, bool homogeneous_bc = false) const
Set ghost cells for an entire level.
Loop through all patches on the given level and call setBoundaryValuesInCells(hier::Patch &patch, const double fill_time , const hier::IntVector &ghost_width_to_fill , int target_data_id , bool homogeneous_bc=false) for each.
Parameters:
level PatchLevel on which to set boundary condition
fill_time Solution time corresponding to filling
ghost_width_to_fill Max ghost width requiring fill
target_data_id hier::Patch data index of data to be set. This data must be a cell-centered double.
homogeneous_bc Set a homogeneous boundary condition. This means g=0 for the boundary.
Precondition:
level.getDim() == ghost_width_to_fill.getDim()
void SAMRAI::solv::CartesianRobinBcHelper::setBoundaryValuesAtNodes (hier::Patch & patch, const double fill_time, int target_data_id, bool homogeneous_bc = false) const
Set the physical boundary condition by setting the value of the boundary nodes.
This function is not yet implemented!
There are some decisions that must be made before the implementation can be written.
Do we set the values on the boundary or one cell away from the boundary?
What is the discrete formulation we should use to compute the value to be set?
This function has an interface similar to the virtual function xfer::RefinePatchStrategy::setPhysicalBoundaryConditions(), and it may be used to help implement that function, but it does not serve the same purpose. The primary differences are:
It specializes to node-centered variables.
User must specify the index of the data whose ghost cells need to be filled. This index is used to determine the variable for which to set the boundary coefficients and to get the data to be set.
This function calls RobinBcStrategy::setBcCoefs() to get the coefficients, then it sets the values at the boundary nodes.
In some cases, the calling function wants to set the boundary condition homogeneously, with g=0. This is useful in problems where the the solution of the homogeneous problem is required to solving the inhomogeneous problem. This function respects such requests specified through the argument homogeneous_bc.
Parameters:
patch hier::Patch on which to set boundary condition
fill_time Solution time corresponding to filling
target_data_id hier::Patch data index of data to be set.
homogeneous_bc Set a homogeneous boundary condition. This means g=0 for the boundary.
void SAMRAI::solv::CartesianRobinBcHelper::setCoefImplementation (const RobinBcCoefStrategy * coef_strategy) [inline]
Provide an implementation of the RobinBcCoefStrategy for determining the boundary coefficients.
Provide the implementation that can be used to set the Robin bc coefficients.
Parameters:
coef_strategy Pointer to a concrete inmplementation of the coefficient strategy.
Precondition:
coef_strategy
References TBOX_ERROR.
Referenced by SAMRAI::solv::CellPoissonFACOps::setPhysicalBcCoefObject().
void SAMRAI::solv::CartesianRobinBcHelper::setTargetDataId (int target_data_id) [inline]
Set the data id that should be filled when setting physical boundary conditions.
When setPhysicalBoundaryConditions is called, the data specified will be set. This information is required because the it is not passed in through the argument list of setPhysicalBounaryConditions.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeCompositeResidualOnLevel(), SAMRAI::solv::CellPoissonFACOps::prolongErrorAndCorrect(), and SAMRAI::solv::CellPoissonFACOps::restrictSolution().
void SAMRAI::solv::CartesianRobinBcHelper::setHomogeneousBc (bool homogeneous_bc) [inline]
Set whether boundary filling should assume homogeneous conditions.
In certain circumstances, only the value of a is needed, while the value of g is temporarily not required and taken to be zero. (An example is in setting the boundary condition for error value in an iterative method.) In such cases, use this function to set a flag that will cause a null pointer to be given to setBcCoefs() to indicate that fact.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeCompositeResidualOnLevel(), SAMRAI::solv::CellPoissonFACOps::prolongErrorAndCorrect(), and SAMRAI::solv::CellPoissonFACOps::restrictSolution().
const std::string& SAMRAI::solv::CartesianRobinBcHelper::getObjectName () const [inline]
Get the name of this object.
Returns:
The name of this object.
const tbox::Dimension& SAMRAI::solv::CartesianRobinBcHelper::getDim () const [inline]
Return the dimension of this object.
The documentation for this class was generated from the following file:
source/SAMRAI/solv/CartesianRobinBcHelper.h