SAMRAI: SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY > Class Template Reference
SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY > Class Template Reference
#include <source/SAMRAI/pdat/IndexData.h>
Public Types
typedef IndexIterator< TYPE,
BOX_GEOMETRY > iterator
Public Member Functions
IndexData (const hier::Box &box, const hier::IntVector &ghosts)
virtual ~IndexData ()
virtual void copy (const hier::PatchData &src)
virtual void copy2 (hier::PatchData &dst) const
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
virtual bool canEstimateStreamSizeFromBox () const
virtual int getDataStreamSize (const hier::BoxOverlap &overlap) const
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
void appendItem (const hier::Index &index, const TYPE &item)
void appendItemPointer (const hier::Index &index, TYPE *item)
void addItem (const hier::Index &index, const TYPE &item)
void addItemPointer (const hier::Index &index, TYPE *item)
void replaceAddItem (const hier::Index &index, const TYPE &item)
void replaceAddItemPointer (const hier::Index &index, TYPE *item)
void replaceAppendItem (const hier::Index &index, const TYPE &item)
void replaceAppendItemPointer (const hier::Index &index, TYPE *item)
void removeItem (const hier::Index &index)
int getNumberOfItems () const
void removeInsideBox (const hier::Box &box)
void removeOutsideBox (const hier::Box &box)
void removeGhostItems ()
void removeAllItems ()
bool isElement (const hier::Index &index) const
TYPE * getItem (const hier::Index &index) const
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Friends
class IndexIterator< TYPE, BOX_GEOMETRY >
Detailed Description
template<class TYPE, class BOX_GEOMETRY>
class SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >
IndexData is used for storing sparse data. The iteration over the data preserves insertion order similar to a linked list, hence data may be inserted at the front (AddItem) or tail (AppendItem).
For example, this class is used to represent embedded * boundary features as a regular patch data type using the BoundaryCell class as the template type. The iteration ordering property is used to visit the boundary cells in a well defined way.
Additional insertion methods are provided for optimization in specific use cases. An extra constructor call can be avoided if the "Pointer" versions of Add/AppendItem are used. These methods assume that the items are being "given" to IndexData thus IndexData will delete them when needed. The items must be dynamically allocated for this to work correctly, E.G.
index_data.addItemPointer(someIndex, new ItemToInsert());
The "replace" versions of the insert routines may be used when one wishes to preserve the existing iteration ordering. If an item already exists the replace insert will delete the old item and put the item provided in it's place (inserting it into that location in the linked list).
If one does not care about the iteration order and is frequently updating the items stored, the "replace" versions are significantly faster.
The template parameter TYPE * defines the storage at each index location. IndexData is derived from * hier::PatchData.
The data type TYPE must define the following five methods which are require by this class:
- Default constructor (taking no arguments).
- Assignment operator; i.e., TYPE& operator=(const TYPE& rhs)
- Copy; copySourceItem(const hier::Index& index, const hier::IntVector& src_offset, const TYPE& src_item)
- Return size of data; size_t getDataStreamSize()
- Pack data into message stream; i.e., packStream(MessageStream& stream,
- Unpack data from message stream; i.e., unpackStream(MessageStream& stream, const hier::IntVector& offset)
- Write to restart; putToRestart(boost::shared_ptr<tbox::Database>& restart_db)
- Retrieve from restart; getFromRestart(boost::shared_ptr<tbox::Database>& restart_db)
The BOX_GEOMETRY template parameter defines the geometry. BOX_GEOMETRY must have a nested class name Overlap that implements he following methods:
- getSourceOffset
- getDestinationBoxList
More information about the templated TYPE is provided in the IndexData README file.
IndexData objects are created by the IndexDataFactory factory object just as all other patch data types.
See also:
pdat::IndexData
hier::PatchData
pdat::IndexDataFactory
Member Typedef Documentation
template<class TYPE, class BOX_GEOMETRY> typedef IndexIterator<TYPE, BOX_GEOMETRY> SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::iterator
Define the iterator.
Constructor & Destructor Documentation
template<class TYPE , class BOX_GEOMETRY > SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::IndexData (const hier::Box & box, const hier::IntVector & ghosts) [inline]
The constructor for an IndexData object. The box describes the interior of the index space and the ghosts vector describes the ghost nodes in each coordinate direction.
Precondition:
box.getDim() == ghosts.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::~IndexData () [inline, virtual]
The virtual destructor for an IndexData object.
References SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeAllItems().
Member Function Documentation
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy between the source and destination. All data is copied from the source into the destination where there is overlap in the index space.
Precondition:
getDim() == src.getDim()
dynamic_cast<const IndexData<TYPE, BOX_GEOMETRY> *>(&src) != 0
References SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItem(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeInsideBox(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy between the source and destination. All data is copied from the source into the destination where there is overlap in the index space.
Precondition:
getDim() == dst.getDim()
References SAMRAI::hier::PatchData::copy(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from the source into the destination using the designated overlap descriptor. The overlap description should have been computed previously from computeIntersection().
Precondition:
getDim() == src.getDim()
dynamic_cast<const IndexData<TYPE, BOX_GEOMETRY> *>(&src) != 0
dynamic_cast<const typename BOX_GEOMETRY::Overlap *>(&overlap) != 0
References SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItem(), SAMRAI::hier::Box::contains(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::hier::Box::offset(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeInsideBox(), SAMRAI::hier::Box::shift(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from the source into the destination using the designated overlap descriptor. The overlap description should have been computed previously from computeIntersection().
Precondition:
getDim() == dst.getDim()
References SAMRAI::hier::PatchData::copy(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > bool SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::canEstimateStreamSizeFromBox () const [inline, virtual]
Determines whether the hier::PatchData subclass can estinate the necessary stream size using only index space information.
Implements SAMRAI::hier::PatchData.
template<class TYPE , class BOX_GEOMETRY > int SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Calculate the number of bytes needed to stream the data lying in the specified box domain.
Precondition:
dynamic_cast<const typename BOX_GEOMETRY::Overlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::Box::begin(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::end(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::PatchData::getBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getItem(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Pack data lying on the specified index set into the output stream.
Precondition:
dynamic_cast<const typename BOX_GEOMETRY::Overlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::contains(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::PatchData::getBox(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::MessageStream::pack(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from the message stream into the specified index set.
Precondition:
dynamic_cast<const typename BOX_GEOMETRY::Overlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItem(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeInsideBox(), TBOX_ASSERT, and SAMRAI::tbox::MessageStream::unpack().
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItem (const hier::Index & index, const TYPE & item) [inline]
Add a new item to the tail of the irregular index set.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::isElement(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getFromRestart().
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItemPointer (const hier::Index & index, TYPE * item) [inline]
Add a pointer to a new item to the tail of the irregular index set. IndexData will delete the item when it is no longer needed by IndexData. Due to this behavior item must be dynamically created (e.g. new) so that it may be deleted.
NOTE: This is an optimization to avoid an extra constructor call. It should be used with caution, the caller MUST NOT delete the referenced item. Think of this as giving up control of the item to IndexData.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::isElement(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItem (const hier::Index & index, const TYPE & item) [inline]
Add a new item to the head of the irregular index set
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::isElement(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::unpackStream().
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItemPointer (const hier::Index & index, TYPE * item) [inline]
Add a pointer to a new item to the head of the irregular index set. IndexData will delete the item when it is no longer needed by IndexData. Due to this behavior item must be dynamically created (e.g. new) so that it may be deleted.
NOTE: This is an optimization to avoid an extra constructor call. It should be used with caution, the caller MUST NOT delete the referenced item. Think of this as giving up control of the item to IndexData.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::isElement(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAddItem (const hier::Index & index, const TYPE & item) [inline]
Remove (deallocate) the item in the irregular index set located at the specified hier::Index and replace it with a new item.
This preserves the iteration order of the orginal insertions.
If an item does not already exist at index this is equivelent to addItem.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAddItemPointer (const hier::Index & index, TYPE * item) [inline]
Remove (deallocate) the item in the irregular index set located at the specified hier::Index and replace it with a new item.
This preserves the iteration order of the original insertions.
If an item does not already exist at index this is equivelent to addItemPointer.
See addItemPointer for additional comments on pointer semantics.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAppendItem (const hier::Index & index, const TYPE & item) [inline]
Remove (deallocate) the item in the irregular index set located at the specified hier::Index and replace it with a new item.
This preserves the iteration order of the orginal insertions.
If an item does not already exist at index this is equivelent to appendItem.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAppendItemPointer (const hier::Index & index, TYPE * item) [inline]
Remove (deallocate) the item in the irregular index set located at the specified hier::Index and replace it with a new item.
This preserves the iteration order of the original insertions.
If an item does not already exist at index this is equivelent to appendItemPointer.
See addItemPointer for additional comments on pointer semantics.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem (const hier::Index & index) [inline]
Remove (deallocate) the item in the irregular index set located at the specified hier::Index.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
(hier::PatchData::getGhostBox().offset(index) >= 0) && (hier::PatchData::getGhostBox().offset(index) <= hier::PatchData::getGhostBox().size())
References SAMRAI::hier::PatchData::getGhostBox(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItemPointer(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItemPointer(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeInsideBox(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeOutsideBox().
template<class TYPE , class BOX_GEOMETRY > int SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getNumberOfItems () const [inline]
Return the number of data items (i.e. the number of indices) in the index data list.
Precondition:
offset >= 0 && offset <= hier::PatchData::getGhostBox().size()
d_data[offset] != 0
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeInsideBox (const hier::Box & box) [inline]
Remove (deallocate) any items in the irregular index set located in the index space of the hier::Box.
Precondition:
getDim() == box.getDim()
References SAMRAI::hier::Box::contains(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeAllItems(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::unpackStream().
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeOutsideBox (const hier::Box & box) [inline]
Remove (deallocate) any items in the irregular index set located outside of the index space of the hier::Box.
Precondition:
getDim() == box.getDim()
References SAMRAI::hier::Box::contains(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeGhostItems().
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeGhostItems () [inline]
Remove (deallocate) the items in the irregular index set located in the ghost region of the patch.
References SAMRAI::hier::PatchData::getBox(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeOutsideBox().
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeAllItems () [inline]
Remove (deallocate) all items in the irregular index set.
References SAMRAI::hier::PatchData::getGhostBox(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeInsideBox().
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::~IndexData().
template<class TYPE , class BOX_GEOMETRY > bool SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::isElement (const hier::Index & index) const [inline]
Returns true if there is an element of the irregular index set at the specified hier::Index.
Precondition:
getDim() == index.getDim()
hier::PatchData::getGhostBox().contains(index)
References SAMRAI::hier::PatchData::getGhostBox(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItemPointer(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItemPointer(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getItem().
template<class TYPE , class BOX_GEOMETRY > TYPE * SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getItem (const hier::Index & index) const [inline]
Given an index, return a pointer to the item located at that index. If there is no item at the index, null is returned.
Precondition:
getDim() == index.getDim()
References SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::isElement(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::putToRestart().
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check to make sure that the class version number is the same as the restart file version number.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItem(), SAMRAI::hier::IntVector::getFromRestart(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE , class BOX_GEOMETRY > void SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getItem(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), and TBOX_ASSERT.
Friends And Related Function Documentation
template<class TYPE, class BOX_GEOMETRY> friend class IndexIterator< TYPE, BOX_GEOMETRY > [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/IndexData.h
source/SAMRAI/pdat/IndexData.C