SAMRAI: SAMRAI::hier::BaseConnectorAlgorithm Class Reference
SAMRAI::hier::BaseConnectorAlgorithm Class Reference
#include <source/SAMRAI/hier/BaseConnectorAlgorithm.h>
Protected Member Functions
BaseConnectorAlgorithm ()
Constructor.
virtual ~BaseConnectorAlgorithm ()
Destructor.
void setupCommunication (tbox::AsyncCommPeer< int > *&all_comms, tbox::AsyncCommStage &comm_stage, const tbox::SAMRAI_MPI &mpi, const std::set< int > &incoming_ranks, const std::set< int > &outgoing_ranks, const boost::shared_ptr< tbox::Timer > &mpi_wait_timer, int &operation_mpi_tag, bool print_steps) const
Set up communication objects for use in privateBridge/Modify.
void packReferencedNeighbors (std::vector< int > &send_mesg, int idx_offset_to_ref, const BoxContainer &referenced_new_head_nabrs, const BoxContainer &referenced_new_base_nabrs, const tbox::Dimension &dim, bool print_steps) const
Pack referenced neighbors discovered during privateBridge/Modify into message for one processor.
void receiveAndUnpack (Connector &new_base_to_new_head, Connector *new_head_to_new_base, const std::set< int > &incoming_ranks, tbox::AsyncCommPeer< int > *all_comms, tbox::AsyncCommStage &comm_stage, const boost::shared_ptr< tbox::Timer > &receive_and_unpack_timer, bool print_steps) const
Receive messages and unpack info sent from other processes.
Constructor & Destructor Documentation
SAMRAI::hier::BaseConnectorAlgorithm::BaseConnectorAlgorithm () [protected]
Constructor.
SAMRAI::hier::BaseConnectorAlgorithm::~BaseConnectorAlgorithm () [protected, virtual]
Destructor.
Member Function Documentation
void SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication (tbox::AsyncCommPeer< int > *& all_comms, tbox::AsyncCommStage & comm_stage, const tbox::SAMRAI_MPI & mpi, const std::set< int > & incoming_ranks, const std::set< int > & outgoing_ranks, const boost::shared_ptr< tbox::Timer > & mpi_wait_timer, int & operation_mpi_tag, bool print_steps) const [protected]
Set up communication objects for use in privateBridge/Modify.
References SAMRAI::tbox::AsyncCommPeer< TYPE >::beginRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getPeerRank(), SAMRAI::tbox::AsyncCommPeer< TYPE >::initialize(), SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), SAMRAI::tbox::AsyncCommPeer< TYPE >::limitFirstDataLength(), SAMRAI::tbox::plog, SAMRAI::tbox::AsyncCommStage::Member::pushToCompletionQueue(), SAMRAI::tbox::AsyncCommStage::setCommunicationWaitTimer(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPI(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPITag(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::setPeerRank().
void SAMRAI::hier::BaseConnectorAlgorithm::packReferencedNeighbors (std::vector< int > & send_mesg, int idx_offset_to_ref, const BoxContainer & referenced_new_head_nabrs, const BoxContainer & referenced_new_base_nabrs, const tbox::Dimension & dim, bool print_steps) const [protected]
Pack referenced neighbors discovered during privateBridge/Modify into message for one processor.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::commBufferSize(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::format(), SAMRAI::tbox::plog, SAMRAI::hier::Box::putToIntBuffer(), SAMRAI::hier::BoxContainer::size(), and TBOX_ASSERT.
void SAMRAI::hier::BaseConnectorAlgorithm::receiveAndUnpack (Connector & new_base_to_new_head, Connector * new_head_to_new_base, const std::set< int > & incoming_ranks, tbox::AsyncCommPeer< int > * all_comms, tbox::AsyncCommStage & comm_stage, const boost::shared_ptr< tbox::Timer > & receive_and_unpack_timer, bool print_steps) const [protected]
Receive messages and unpack info sent from other processes.
References SAMRAI::tbox::AsyncCommStage::advanceSome(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getPeerRank(), SAMRAI::tbox::AsyncCommStage::hasCompletedMembers(), SAMRAI::tbox::plog, SAMRAI::tbox::AsyncCommStage::popCompletionQueue(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BaseConnectorAlgorithm.h
source/SAMRAI/hier/BaseConnectorAlgorithm.C