SAMRAI: SAMRAI::xfer::RefineSchedule Class Reference
SAMRAI::xfer::RefineSchedule Class Reference
Class RefineSchedule performs the communication operations that refine data to, copy data to, or fill physical boundary data on a destination patch level.
#include <source/SAMRAI/xfer/RefineSchedule.h>
Public Member Functions
RefineSchedule (const boost::shared_ptr< PatchLevelFillPattern > &dst_level_fill_pattern, const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< RefineClasses > &refine_classes, const boost::shared_ptr< RefineTransactionFactory > &transaction_factory, RefinePatchStrategy *patch_strategy, bool use_time_interpolation=false)
Constructor that creates a refine schedule to copy data from the interiors of the source patch data on the source level into the interiors and ghosts of destination patch data on the destination level.
RefineSchedule (const boost::shared_ptr< PatchLevelFillPattern > &dst_level_fill_pattern, const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, int next_coarser_level, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const boost::shared_ptr< RefineClasses > &refine_classes, const boost::shared_ptr< RefineTransactionFactory > &transaction_factory, RefinePatchStrategy *patch_strategy, bool use_time_refinement=false)
Constructor that creates a refine schedule to fill destination patch data on the destination level from source patch data on the source level as well as interpolated data from coarser levels.
~RefineSchedule ()
void reset (const boost::shared_ptr< RefineClasses > &refine_classes)
Reset this refine schedule to perform data transfers asssociated with refine class items in function argument.
void fillData (double fill_time, bool do_physical_boundary_fill=true) const
Execute the stored communication schedule and perform the data movement.
const boost::shared_ptr
< RefineClasses > & getEquivalenceClasses () const
Return refine equivalence classes.
void setDeterministicUnpackOrderingFlag (bool flag)
Set whether to unpack messages in a deterministic order.
void printClassData (std::ostream &stream) const
Print the refine schedule data to the specified data stream.
Detailed Description
Class RefineSchedule performs the communication operations that refine data to, copy data to, or fill physical boundary data on a destination patch level.
Source data is copied into the provided scratch space for temporary processing. The scratch space must contain sufficient ghost cells to accommodate the stencil width of the given interpolation operators and any physical boundary data that must be filled. The scratch data is copied into the destination space at the end of the process. The communication schedule is executed by calling member function fillData().
Each schedule object is typically created by a refine algorithm and represents the communication dependencies for a particular configuration of the AMR hierarchy. The communication schedule is only valid for that particular configuration and must be regenerated when the AMR patch hierarchy changes. However, as long as the patch levels involved in the creation of the schedule remain unchanged, the schedule may be used for multiple communication cycles. For more information about creating refine schedules, see the RefineAlgorithm header file.
Some constructors accept the argument dst_level_fill_pattern. This is a PatchLevelFillPattern which controls which types of cells are filled and which are omitted from the filling process. Concrete implementations of PatchLevelFillPattern are:
PatchLevelFullFillPattern - Fill interior and ghost cells.
PatchLevelInteriorFillPattern - Fill interior cells only.
PatchLevelBorderFillPattern - Fill ghosts on level borders only.
PatchLevelBorderAndInteriorFillPattern - Fill interior and ghosts on level borders.
See also:
RefineAlgorithm
RefinePatchStrategy
RefineClasses
Constructor & Destructor Documentation
SAMRAI::xfer::RefineSchedule::RefineSchedule (const boost::shared_ptr< PatchLevelFillPattern > & dst_level_fill_pattern, const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< RefineClasses > & refine_classes, const boost::shared_ptr< RefineTransactionFactory > & transaction_factory, RefinePatchStrategy * patch_strategy, bool use_time_interpolation = false)
Constructor that creates a refine schedule to copy data from the interiors of the source patch data on the source level into the interiors and ghosts of destination patch data on the destination level.
The fill pattern supplied may restrict the data that will be copied.
Only data on the intersection of the source and destination patch data will be copied; no interpolation from coarser levels will be done. The source and destination patch levels must reside in the same index space. However, the levels do not have to be in the same AMR patch hierarchy. Generally, this constructor is called by a RefineAlgorithm object.
Parameters:
[in] dst_level_fill_pattern Indicates which parts of the destination level to fill.
[in] dst_level boost::shared_ptr to destination patch level.
[in] src_level boost::shared_ptr to source patch level.
[in] refine_classes boost::shared_ptr to structure containing patch data and operator information. In general, this is constructed by the calling RefineAlgorithm object.
[in] transaction_factory boost::shared_ptr to a factory object that will create data transactions.
[in] patch_strategy Pointer to a refine patch strategy object that provides user-defined physical boundary filling operations. This pointer may be null, in which case no boundary filling operations will occur. If your mesh has a singularity, the object this points to should have also inherited from SingularityPatchStrategy.
[in] use_time_interpolation Boolean flag indicating whether to use time interpolation when setting data on the destination level. Default is no time interpolation.
Precondition:
dst_level
src_level
refine_classes
transaction_factory
dst_level->getDim() == src_level->getDim()
dst_level->getGridGeometry()->getNumberOfBlockSingularities() == 0 || d_singularity_patch_strategy
References SAMRAI::hier::Connector::assertOverlapCorrectness(), SAMRAI::hier::CONNECTOR_IMPLICIT_CREATION_RULE, SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::Connector::getTranspose(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
SAMRAI::xfer::RefineSchedule::RefineSchedule (const boost::shared_ptr< PatchLevelFillPattern > & dst_level_fill_pattern, const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, int next_coarser_level, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const boost::shared_ptr< RefineClasses > & refine_classes, const boost::shared_ptr< RefineTransactionFactory > & transaction_factory, RefinePatchStrategy * patch_strategy, bool use_time_refinement = false)
Constructor that creates a refine schedule to fill destination patch data on the destination level from source patch data on the source level as well as interpolated data from coarser levels.
The fill pattern supplied may restrict the data that will be copied.
Only data on the intersection of the source and destination patch data will be copied. If portions of the destination level remain unfilled, then the algorithm recursively fills those unfilled portions by interpolating source data from coarser levels in the AMR hierarchy. The source and destination patch levels must reside in the same index space. However, the levels do not have to be in the same AMR patch hierarchy. In general, this constructor is called by a RefineAlgorithm object.
Parameters:
[in] dst_level_fill_pattern Indicates which parts of the destination level to fill.
[in] dst_level boost::shared_ptr to destination patch level. This level may be a level on the hierarchy or a coarsened version.
[in] src_level boost::shared_ptr to source patch level; must be in same index space as destination level. This pointer may be null, in which case the destination level will be filled only using data interpolated from coarser levels in the AMR hierarchy.
[in] next_coarser_level Level number of next coarser level in AMR patch hierarchy relative to the destination level. Note that when the destination level has number zero (i.e., the coarsest level), this value should be less than zero.
[in] hierarchy boost::shared_ptr to patch hierarchy. This pointer may be null only if the next_coarser_level value is < 0, indicating that there is no level in the hierarchy coarser than the destination level.
[in] refine_classes boost::shared_ptr to structure containing patch data and operator information. In general, this is constructed by the calling RefineAlgorithm object.
[in] transaction_factory boost::shared_ptr to a factory object that will create data transactions.
[in] patch_strategy Pointer to a refine patch strategy object that provides user-defined physical boundary filling operations. This pointer may be null, in which case no boundary filling or user-defined refine operations will occur. If your mesh has a singularity, the object this points to should have also inherited from SingularityPatchStrategy.
[in] use_time_refinement Boolean flag indicating whether to use time interpolation when setting data on the destination level. Default is no time interpolation.
Precondition:
dst_level
(next_coarser_level == -1) || hierarchy
refine_classes
!src_level || (dst_level->getDim() == src_level.getDim())
!hierarchy || (dst_level->getDim() == hierarchy.getDim())
dst_level->getGridGeometry()->getNumberOfBlockSingularities() == 0 || d_singularity_patch_strategy
References SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredFineConnectorWidthsForRecursiveRefinement(), SAMRAI::hier::CONNECTOR_IMPLICIT_CREATION_RULE, SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::IntVector::getNumBlocks(), SAMRAI::tbox::perr, SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::setGhostCellWidthFactor(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
SAMRAI::xfer::RefineSchedule::~RefineSchedule ()
Destructor for the schedule releases all internal storage.
Member Function Documentation
void SAMRAI::xfer::RefineSchedule::reset (const boost::shared_ptr< RefineClasses > & refine_classes)
Reset this refine schedule to perform data transfers asssociated with refine class items in function argument.
In general, this function is called by a RefineAlgorithm object, which first checks that the refine_classes parameter is in a state consistent with the RefineSchedule object.
Parameters:
[in] refine_classes boost::shared_ptr to structure containing patch data and operator information. In general, this is constructed by the calling RefineAlgorithm object. This pointer must be non-null.
Precondition:
refine_classes
References TBOX_ASSERT.
void SAMRAI::xfer::RefineSchedule::fillData (double fill_time, bool do_physical_boundary_fill = true) const
Execute the stored communication schedule and perform the data movement.
Parameters:
[in] fill_time Time for filling operation.
[in] do_physical_boundary_fill Boolean flag that can be used to bypass the physical boundary data filling operations on the destination level. The default value is true indicating that boundary data will be filled (assuming a non-null refine patch strategy pointer was passed to the createSchedule() function. Note that even when the value is false, boundary routines may be called on levels coarser than the destination level if such data is needed for proper interpolation.
const boost::shared_ptr<RefineClasses>& SAMRAI::xfer::RefineSchedule::getEquivalenceClasses () const [inline]
Return refine equivalence classes.
The equivalence class information is used in schedule classes.
void SAMRAI::xfer::RefineSchedule::setDeterministicUnpackOrderingFlag (bool flag)
Set whether to unpack messages in a deterministic order.
By default message unpacking is ordered by receive time, which is not deterministic. If your results are dependent on unpack ordering and you want deterministic results, set this flag to true.
Parameters:
[in] flag
void SAMRAI::xfer::RefineSchedule::printClassData (std::ostream & stream) const
Print the refine schedule data to the specified data stream.
Parameters:
[out] stream Output data stream.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/RefineSchedule.h
source/SAMRAI/xfer/RefineSchedule.C