SAMRAI: SAMRAI::pdat::OuteredgeData< TYPE > Class Template Reference
SAMRAI::pdat::OuteredgeData< TYPE > Class Template Reference
Class OuteredgeData<TYPE> provides an implementation for data defined at cell edges on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outeredge data object represents data of some template TYPE and depth on the cell edges on the boundary of the box. Here, depth indicates the number of data values at each edge index location. The OuteredgedgeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outeredge-centered data.
#include <source/SAMRAI/pdat/OuteredgeData.h>
Public Member Functions
OuteredgeData (const hier::Box &box, int depth)
Constructor for an outeredge data object.
virtual ~OuteredgeData ()
Virtual destructor for a outeredge data object.
int getDepth () const
Return the depth (i.e., the number of data values for each spatial location) of the array.
bool dataExists (int axis, int face_normal) const
Returns true if outeredge data exists for the given axis and face normal direction; false otherwise.
hier::Box getDataBox (int axis, int face_normal, int side)
Return the box of valid edge indices for outeredge data. Note: the returned box will reside in the edge index space.
TYPE * getPointer (int axis, int face_normal, int side, int depth=0)
Get a pointer to the beginning of a particular axis, face normal, side, and depth component of the outeredge centered array.
const TYPE * getPointer (int axis, int face_normal, int side, int depth=0) const
Get a const pointer to the beginning of a particular axis, face normal, side, and depth component of the outeredge centered array.
TYPE & operator() (const EdgeIndex &i, int depth=0)
Return a reference to data entry corresponding to a given edge index and depth.
const TYPE & operator() (const EdgeIndex &i, int depth=0) const
Return a const reference to data entry corresponding to a given edge index and depth.
ArrayData< TYPE > & getArrayData (int axis, int face_normal, int side)
Return a reference to the array data object for given axis, face normal, and side index of the outeredge centered array.
const ArrayData< TYPE > & getArrayData (int axis, int face_normal, int side) const
Return a const reference to the array data object for given axis, face normal, and side index of the outeredge centered array.
virtual void copy (const hier::PatchData &src)
A fast copy from source to destination (i.e., this) patch data object.
virtual void copy2 (hier::PatchData &dst) const
A fast copy from source (i.e., this) to destination patch data object.
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Copy data from source to destination (i.e., this) patch data object on the given overlap.
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
Copy data from source (i.e., this) to destination patch data object on the given overlap.
void copyDepth (int dst_depth, const EdgeData< TYPE > &src, int src_depth)
Fast copy (i.e., assumes edge and outeredge data objects are defined over the same box) from the given edge source data object to this destination outeredge data object at the specified depths.
void copyDepth2 (int dst_depth, EdgeData< TYPE > &dst, int src_depth) const
Fast copy (i.e., assumes edge and outeredge data objects are defined over the same box) to the given edge destination data object from this source outeredge data object at the specified depths.
virtual void sum (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Add data from source to destination (i.e., this) patch data object on the given overlap.
virtual bool canEstimateStreamSizeFromBox () const
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
virtual size_t getDataStreamSize (const hier::BoxOverlap &overlap) const
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an EdgeOverlap of the same DIM.
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an EdgeOverlap of the same DIM.
virtual void unpackStreamAndSum (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream and add into this patch data object over the specified box overlap region.
void fill (const TYPE &t, int d=0)
Fill all values at depth d with the value t.
void fill (const TYPE &t, const hier::Box &box, int d=0)
Fill all values at depth d within the box with the value t.
void fillAll (const TYPE &t)
Fill all depth components with value t.
void fillAll (const TYPE &t, const hier::Box &box)
Fill all depth components within the box with value t.
void print (const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all outeredge data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
void print (const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all outeredge data values at the given array depth in the specified box.
void printAxisSide (int axis, int face_normal, int side, const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all outeredge centered data values for specified axis, face_normal, and side residing in the specified box. If the depth of the data is greater than one, all depths are printed.
void printAxisSide (int axis, int face_normal, int side, const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all outeredge centered data values for specified axis, face_normal, side, and depth residing in the specified box.
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
Check that class version and restart file version are equal. If so, read data members from the restart database.
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write out the class version number and other data members to the restart database.
Static Public Member Functions
static size_t getSizeOfData (const hier::Box &box, int depth)
Calculate the amount of memory needed to represent outeredge- centered data over a CELL-centered AMR index space box.
Detailed Description
template<class TYPE>
class SAMRAI::pdat::OuteredgeData< TYPE >
Class OuteredgeData<TYPE> provides an implementation for data defined at cell edges on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outeredge data object represents data of some template TYPE and depth on the cell edges on the boundary of the box. Here, depth indicates the number of data values at each edge index location. The OuteredgedgeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outeredge-centered data.
Outeredge data is stored in 2*DIM*(DIM-2) arrays, each of which contains data associated with edge indices in a coordinate axis direction, an outward pointing face normal direction, and an upper or lower box face in the face normal direction. The data layout in the outernode data arrays matches the corresponding array sections provided by the node data implementation. Note that outeredge data is NOT defined when the axis and face normal are equal. This is consistent with the edge data representation. Where an edge index falls on more than one box face (patch boundary edges and corners), the outeredge data value belongs to only one data array so that there are no redundant data values. Specifically, when DIM > 2, outeredge data boxes are "trimmed" for each axis edge direction so that each edge index that lives on more than one face on the box boundary will be associated with the largest face normal direction and only that face. Within each array, data is stored in (i,...,k,d) order, where i,...,k indicates a spatial index and the d indicates the component depth at that location. Memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory.
To illustrate the outeredge data layout, in particular the "box trimming" that prevents redundant data values, we describe the data for a three-dimensional outeredge data object instantiated over a box [l0:u0,l1:u1,l2:u2] in the standard SAMRAI cell-centered AMR index space. Note: no boxes are trimmed when DIM < 3.
 *
 *    a = edge axis (corresponds to the standard EdgeData axis)
 *    f = face normal dir
 *    s = lower/upper face
 *    d = data depth (i.e., number of values at each edge index point).
 *
 *    Here axis and face normal values 0, 1, and 2 can be thought of as X, Y, Z
 *    respectively.
 *
 *        (a,f,s)
 *    axis 0:
 *        (0,0,[0,1])  DATA IS NOT DEFINED when a == f
 *        (0,1,0)      [l0:u0, l1:l1,     l2+1:u2,   d]
 *        (0,1,1)      [l0:u0, u1+1:u1+1, l2+1:u2,   d]
 *        (0,2,0)      [l0:u0, l1:u1+1,   l2:l2,     d]
 *        (0,2,1)      [l0:u0, l1:u1+1,   u2+1:u2+1, d]
 *        Note: Edge indices are duplicated at the intersection of faces normal
 *              to directions 1 and 2.
 *              So boxes for face normal direction 1 are trimmed in direction 2
 *              so that edge indices shared with faces in direction 2 only
 *              appear in face normal direction 2 boxes.
 *
 *    axis 1:
 *        (1,0,0)      [l0:l0,     l1:u1, l2+1:u2,   d]
 *        (1,0,1)      [u0+1:u0+1, l1:u1, l2+1:u2,   d]
 *        (1,1,[0,1])  DATA IS NOT DEFINED when a == f
 *        (1,2,0)      [l0:u0+1,   l1:u1, l2:l2,     d]
 *        (1,2,1)      [l0:u0+1,   l1:u1, u2+1:u2+1, d]
 *        Note: Edge indices are duplicated at the intersection of faces normal
 *              to directions 0 and 2.
 *              So boxes for face normal direction 0 are trimmed in direction 2
 *              so that edge indices shared with faces in direction 2 only
 *              appear in face normal direction 2 boxes.
 *
 *    axis 2:
 *        (2,0,0)      [l0:l0,     l1+1:u1,   l2:u2, d]
 *        (2,0,1)      [u0+1:u0+1, l1+1:u1,   l2:u2, d]
 *        (2,1,0)      [l0:u0+1,   l1:l1,     l2:u2, d]
 *        (2,1,1)      [l0:u0+1,   u1+1:u1+1, l2:u2, d]
 *        (2,2,[0,1])  DATA IS NOT DEFINED when a == f
 *        Note: Edge indices are duplicated at the intersection of faces normal
 *              to directions 0 and 1.
 *              So boxes for face normal direction 0 are trimmed in direction 1
 *              so that edge indices shared with faces in direction 1 only
 *              appear in face normal direction 1 boxes.
 *
 *
Other spatial dimensions are represented similarly.
The data type TYPE must define a default constructor (that takes no arguments) and also the assignment operator.
See also:
pdat::ArrayData
hier::PatchData
pdat::OuteredgeDataFactory
pdat::OuteredgeGeometry
pdat::EdgeIterator
pdat::EdgeIndex
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::OuteredgeData< TYPE >::OuteredgeData (const hier::Box & box, int depth) [inline]
Constructor for an outeredge data object.
Note: Outeredge data always has ghost cell width of zero.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the outeredge data object will be created.
depth gives the number of data values for each spatial location in the array.
Precondition:
depth > 0
References SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox().
template<class TYPE > SAMRAI::pdat::OuteredgeData< TYPE >::~OuteredgeData () [inline, virtual]
Virtual destructor for a outeredge data object.
Member Function Documentation
template<class TYPE > size_t SAMRAI::pdat::OuteredgeData< TYPE >::getSizeOfData (const hier::Box & box, int depth) [inline, static]
Calculate the amount of memory needed to represent outeredge- centered data over a CELL-centered AMR index space box.
This function assumes that the amount of memory needed for TYPE is sizeof(TYPE). If this is not the case, then a specialized function must be defined.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the outeredge data object will be created. Note: the ghost cell width is assumed to be zero.
depth gives the number of data values for each spatial location in the array.
Precondition:
depth > 0
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox().
template<class TYPE > int SAMRAI::pdat::OuteredgeData< TYPE >::getDepth () const [inline]
Return the depth (i.e., the number of data values for each spatial location) of the array.
template<class TYPE > bool SAMRAI::pdat::OuteredgeData< TYPE >::dataExists (int axis, int face_normal) const [inline]
Returns true if outeredge data exists for the given axis and face normal direction; false otherwise.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
Precondition:
(axis >= 0) && (axis < getDim().getValue())
(face_normal >= 0) && (face_normal < getDim().getValue())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > hier::Box SAMRAI::pdat::OuteredgeData< TYPE >::getDataBox (int axis, int face_normal, int side) [inline]
Return the box of valid edge indices for outeredge data. Note: the returned box will reside in the edge index space.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outeredge data array
References SAMRAI::hier::PatchData::getGhostBox(), and SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox().
template<class TYPE > TYPE * SAMRAI::pdat::OuteredgeData< TYPE >::getPointer (int axis, int face_normal, int side, int depth = 0) [inline]
Get a pointer to the beginning of a particular axis, face normal, side, and depth component of the outeredge centered array.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outeredge data array
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
Precondition:
(axis >= 0) && (axis < getDim().getValue())
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > const TYPE * SAMRAI::pdat::OuteredgeData< TYPE >::getPointer (int axis, int face_normal, int side, int depth = 0) const [inline]
Get a const pointer to the beginning of a particular axis, face normal, side, and depth component of the outeredge centered array.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outeredge data array
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
Precondition:
(axis >= 0) && (axis < getDim().getValue())
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::OuteredgeData< TYPE >::operator() (const EdgeIndex & i, int depth = 0) [inline]
Return a reference to data entry corresponding to a given edge index and depth.
Parameters:
i const reference to EdgeIndex, MUST be an index on the outeredge of the box.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
Precondition:
getDim() == i.getDim()
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::EdgeIndex::getAxis(), SAMRAI::hier::PatchData::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > const TYPE & SAMRAI::pdat::OuteredgeData< TYPE >::operator() (const EdgeIndex & i, int depth = 0) const [inline]
Return a const reference to data entry corresponding to a given edge index and depth.
Parameters:
i const reference to EdgeIndex, MUST be an index on the outeredge of the box.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
Precondition:
getDim() == i.getDim()
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::EdgeIndex::getAxis(), SAMRAI::hier::PatchData::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > ArrayData< TYPE > & SAMRAI::pdat::OuteredgeData< TYPE >::getArrayData (int axis, int face_normal, int side) [inline]
Return a reference to the array data object for given axis, face normal, and side index of the outeredge centered array.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outeredge data array
Precondition:
(axis >= 0) && (axis < getDim().getValue())
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > const ArrayData< TYPE > & SAMRAI::pdat::OuteredgeData< TYPE >::getArrayData (int axis, int face_normal, int side) const [inline]
Return a const reference to the array data object for given axis, face normal, and side index of the outeredge centered array.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outeredge data array
Precondition:
(axis >= 0) && (axis < getDim().getValue())
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy from source to destination (i.e., this) patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, source data must be either EdgeData or OuteredgeData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
dynamic_cast<const EdgeData<TYPE> *>(&src) != 0 || dynamic_cast<const OuteredgeData<TYPE> *>(&src) != 0
References TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy from source (i.e., this) to destination patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, destination data must be either EdgeData or OuteredgeData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<EdgeData<TYPE> *>(&dst) != 0 || dynamic_cast<OuteredgeData<TYPE> *>(&dst) != 0
References TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from source to destination (i.e., this) patch data object on the given overlap.
Currently, source data must be either EdgeData or OuteredgeData of the same DIM and TYPE and the overlap must be an EdgeOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
dynamic_cast<const EdgeOverlap *>(&overlap) != 0
dynamic_cast<const EdgeData<TYPE> *>(&src) != 0 || dynamic_cast<const OuteredgeData<TYPE> *>(&src) != 0
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from source (i.e., this) to destination patch data object on the given overlap.
Currently, destination data must be either EdgeData or OuteredgeData of the same DIM and TYPE and the overlap must be an EdgeOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<const EdgeOverlap *>(&overlap) != 0
dynamic_cast<EdgeData<TYPE> *>(&dst) != 0 || dynamic_cast<OuteredgeData<TYPE> *>(&dst) != 0
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth (int dst_depth, const EdgeData< TYPE > & src, int src_depth) [inline]
Fast copy (i.e., assumes edge and outeredge data objects are defined over the same box) from the given edge source data object to this destination outeredge data object at the specified depths.
Precondition:
getDim() == src.getDim()
References SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::pdat::EdgeData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth2 (int dst_depth, EdgeData< TYPE > & dst, int src_depth) const [inline]
Fast copy (i.e., assumes edge and outeredge data objects are defined over the same box) to the given edge destination data object from this source outeredge data object at the specified depths.
Precondition:
getDim() == dst.getDim()
References SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::pdat::EdgeData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::sum (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Add data from source to destination (i.e., this) patch data object on the given overlap.
Currently, source data must be OuteredgeData of the same DIM and TYPE and the overlap must be an EdgeOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
dynamic_cast<const EdgeOverlap *>(&overlap) != 0
dynamic_cast<const OuteredgeData<TYPE> *>(&src) != 0
References SAMRAI::pdat::EdgeOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::EdgeOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::OuteredgeData< TYPE >::canEstimateStreamSizeFromBox () const [inline, virtual]
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Implements SAMRAI::hier::PatchData.
template<class TYPE > size_t SAMRAI::pdat::OuteredgeData< TYPE >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Precondition:
dynamic_cast<const EdgeOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::EdgeOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::EdgeOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an EdgeOverlap of the same DIM.
Precondition:
dynamic_cast<const EdgeOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::pdat::EdgeOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::EdgeOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an EdgeOverlap of the same DIM.
Precondition:
dynamic_cast<const EdgeOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::pdat::EdgeOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::EdgeOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream and add into this patch data object over the specified box overlap region.
Precondition:
dynamic_cast<const EdgeOverlap *>(&overlap) != 0
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::pdat::EdgeOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::EdgeOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::fill (const TYPE & t, int d = 0) [inline]
Fill all values at depth d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::fill (const TYPE & t, const hier::Box & box, int d = 0) [inline]
Fill all values at depth d within the box with the value t.
Precondition:
getDim() == box.getDim()
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::EdgeGeometry::toEdgeBox().
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all depth components with value t.
References SAMRAI::hier::PatchData::getDim(), and SAMRAI::tbox::Dimension::getValue().
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all depth components within the box with value t.
Precondition:
getDim() == box.getDim()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::EdgeGeometry::toEdgeBox().
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::print (const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outeredge data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to edge index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::print (const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outeredge data values at the given array depth in the specified box.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to edge index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::OuteredgeData< TYPE >::printAxisSide(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::printAxisSide (int axis, int face_normal, int side, const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outeredge centered data values for specified axis, face_normal, and side residing in the specified box. If the depth of the data is greater than one, all depths are printed.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outeredge data array
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to edge index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(axis >= 0) && (axis < getDim().getValue())
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::OuteredgeData< TYPE >::print().
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::printAxisSide (int axis, int face_normal, int side, const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outeredge centered data values for specified axis, face_normal, side, and depth residing in the specified box.
Parameters:
axis integer edge data coordinate axis, must satisfy 0 <= axis < DIM
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outeredge data array
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to edge index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
(axis >= 0) && (axis < getDim().getValue())
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::Box::begin(), SAMRAI::hier::Box::end(), SAMRAI::hier::PatchData::getDim(), NULL_USE, TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::EdgeGeometry::toEdgeBox().
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check that class version and restart file version are equal. If so, read data members from the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OuteredgeData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number and other data members to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OuteredgeData.h
source/SAMRAI/pdat/OuteredgeData.C