SAMRAI: SAMRAI::solv::GhostCellRobinBcCoefs Class Reference
SAMRAI::solv::GhostCellRobinBcCoefs Class Reference
A prefabricated Robin boundary condition coefficients for the case where cell-centered data is fixed at the first ghost-cell centers.
#include <source/SAMRAI/solv/GhostCellRobinBcCoefs.h>
Public Member Functions
GhostCellRobinBcCoefs (const tbox::Dimension &dim, std::string object_name="")
Constructor.
virtual ~GhostCellRobinBcCoefs ()
Destructor.
void setBcCoefs (const boost::shared_ptr< pdat::ArrayData< double > > &acoef_data, const boost::shared_ptr< pdat::ArrayData< double > > &bcoef_data, const boost::shared_ptr< pdat::ArrayData< double > > &gcoef_data, const boost::shared_ptr< hier::Variable > &variable, const hier::Patch &patch, const hier::BoundaryBox &bdry_box, double fill_time=0.0) const
Function to fill arrays of Robin boundary condition coefficients at a patch boundary.
hier::IntVector numberOfExtensionsFillable () const
void setGhostDataId (int ghost_data_id, hier::IntVector extensions_fillable)
Set the patch data index of the data providing ghost cell values.
const std::string & getObjectName () const
Get the name of this object.
Detailed Description
A prefabricated Robin boundary condition coefficients for the case where cell-centered data is fixed at the first ghost-cell centers.
This class is intended to make the use of the Robin boundary condition utterly trivial for users who who already have the correct values set in the ghost cells. The motivation for this seemingly needless task is to interpret the requirement that solution is fixed at ghost cell centers to solvers that do not operate directly on the ghost cell values. An example is linear solvers that operate on Ax=b and require that the boundary condition be written as changes to A and b.
This implementation of the strategy class RobinBcCoefStrategy can be used when ghost cell values are known and have been written to the ghost cells of the data being set. You provide the patch data index to the cell-centered data, defined with a non-zero ghost cell width, where the ghost cell values can be found.
This implementation corresponds to a specific discretization of the Robin formula described in RobinBcCoefStrategy. It assumes a linear variation of the data between the first interior and first ghost cells. It sets up the coefficients such that this linear extrapolation gives the correct value at the ghost cell center. This results in the coefficient a being 1.0/(1+0.5*h) and g being the a times the ghost cell value. h is the grid spacing normal to the boundary.
Constructor & Destructor Documentation
SAMRAI::solv::GhostCellRobinBcCoefs::GhostCellRobinBcCoefs (const tbox::Dimension & dim, std::string object_name = "") [explicit]
Constructor.
Parameters:
dim
object_name Name of object for output purposes.
References SAMRAI::tbox::TimerManager::getManager().
SAMRAI::solv::GhostCellRobinBcCoefs::~GhostCellRobinBcCoefs () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::solv::GhostCellRobinBcCoefs::setBcCoefs (const boost::shared_ptr< pdat::ArrayData< double > > & acoef_data, const boost::shared_ptr< pdat::ArrayData< double > > & bcoef_data, const boost::shared_ptr< pdat::ArrayData< double > > & gcoef_data, const boost::shared_ptr< hier::Variable > & variable, const hier::Patch & patch, const hier::BoundaryBox & bdry_box, double fill_time = 0.0) const [virtual]
Function to fill arrays of Robin boundary condition coefficients at a patch boundary.
This implementation of the virtual function RobinBcCoefStrategy::setBcCoefs() sets up the coefficients as described in the above notes.
Parameters:
acoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box. If this is a null pointer, then the calling function is not interested in a, and you can disregard it.
bcoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box.
gcoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box.
variable variable to set the coefficients for.
patch patch requiring bc coefficients
bdry_box boundary box showing where on the boundary the coefficient data is needed.
fill_time solution time corresponding to filling, for use when coefficients are time-dependent.
Precondition:
(d_dim == variable->getDim()) && (d_dim == patch.getDim()) && (d_dim == bdry_box.getDim())
!acoef_data || (d_dim == acoef_data->getDim())
!bcoef_data || (d_dim == bcoef_data->getDim())
!gcoef_data || (d_dim == gcoef_data->getDim())
!gcoef_data || (d_ghost_data_id != -1)
Implements SAMRAI::solv::RobinBcCoefStrategy.
References BOOST_CAST, SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::hier::Patch::getPatchData(), SAMRAI::hier::Patch::getPatchGeometry(), NULL_USE, SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, TBOX_ASSERT_DIM_OBJDIM_EQUALITY3, and TBOX_ERROR.
hier::IntVector SAMRAI::solv::GhostCellRobinBcCoefs::numberOfExtensionsFillable () const [virtual]
Implements SAMRAI::solv::RobinBcCoefStrategy.
void SAMRAI::solv::GhostCellRobinBcCoefs::setGhostDataId (int ghost_data_id, hier::IntVector extensions_fillable)
Set the patch data index of the data providing ghost cell values.
The index must correspond to cell-centered double data with the given ghost width.
Parameters:
ghost_data_id patch data index of ghost data
extensions_fillable the number of extensions past edge of a patch that has valid ghost cell values.
Precondition:
d_dim == extensions_fillable.getDim()
References BOOST_CAST, SAMRAI::hier::VariableDatabase::getDatabase(), SAMRAI::hier::VariableDatabase::mapIndexToVariable(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ERROR.
const std::string& SAMRAI::solv::GhostCellRobinBcCoefs::getObjectName () const [inline]
Get the name of this object.
Returns:
The name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/solv/GhostCellRobinBcCoefs.h
source/SAMRAI/solv/GhostCellRobinBcCoefs.C