SAMRAI: SAMRAI::pdat::NodeOverlap Class Reference
SAMRAI::pdat::NodeOverlap Class Reference
#include <source/SAMRAI/pdat/NodeOverlap.h>
Public Member Functions
NodeOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation)
virtual ~NodeOverlap ()
virtual bool isOverlapEmpty () const
virtual const hier::BoxContainer & getDestinationBoxContainer () const
virtual void getSourceBoxContainer (hier::BoxContainer &src_boxes) const
Get a BoxContainer representing the source boxes of the overlap.
virtual const hier::IntVector & getSourceOffset () const
virtual const
hier::Transformation & getTransformation () const
Refturn the transformation between the destination and source index spaces.
Detailed Description
Class NodeOverlap represents the intersection between two node centered geometry boxes. It is a subclass of hier::BoxOverlap and records the portions of index space that needs to be copied between two objects with node centered geometry.
See also:
hier::BoxOverlap
pdat::NodeOverlap
Constructor & Destructor Documentation
SAMRAI::pdat::NodeOverlap::NodeOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation)
The constructor takes the list of boxes and the tranformation from source to destination index spaces. This information is used later in the generation of communication schedules.
SAMRAI::pdat::NodeOverlap::~NodeOverlap () [virtual]
The virtual destructor does nothing interesting except deallocate box data.
Member Function Documentation
bool SAMRAI::pdat::NodeOverlap::isOverlapEmpty () const [virtual]
Return whether there is an empty intersection between the two node centered boxes. This method over-rides the virtual function in the hier::BoxOverlap base class.
Implements SAMRAI::hier::BoxOverlap.
const hier::BoxContainer & SAMRAI::pdat::NodeOverlap::getDestinationBoxContainer () const [virtual]
Return the list of boxes (in node centered index space) that constitute the intersection. The boxes are given in the destination coordinate space and must be shifted by -(getSourceOffset()) to lie in the source index space.
Referenced by SAMRAI::pdat::OuternodeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::NodeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::NodeData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::sum(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStream(), SAMRAI::pdat::NodeData< TYPE >::unpackStream(), and SAMRAI::pdat::OuternodeData< TYPE >::unpackStreamAndSum().
void SAMRAI::pdat::NodeOverlap::getSourceBoxContainer (hier::BoxContainer & src_boxes) const [virtual]
Get a BoxContainer representing the source boxes of the overlap.
The src_boxes container will be filled with the node-centered source boxes of the overlap in the source coordinate space.
Parameters:
[out] src_boxes
Precondition:
src_boxes.isEmpty()
References SAMRAI::hier::BoxContainer::front(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::hier::BoxContainer::isEmpty(), and TBOX_ASSERT.
const hier::IntVector & SAMRAI::pdat::NodeOverlap::getSourceOffset () const [virtual]
Return the offset between the destination and source index spaces. The destination index space is the source index spaced shifted by this amount.
Implements SAMRAI::hier::BoxOverlap.
References SAMRAI::hier::Transformation::getOffset().
Referenced by SAMRAI::pdat::OuternodeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::NodeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::sum(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStream(), SAMRAI::pdat::NodeData< TYPE >::unpackStream(), and SAMRAI::pdat::OuternodeData< TYPE >::unpackStreamAndSum().
const hier::Transformation & SAMRAI::pdat::NodeOverlap::getTransformation () const [virtual]
Refturn the transformation between the destination and source index spaces.
The destination index space is the source index space rotated and shifted by the returned transformation.
Returns:
The transformation.
Implements SAMRAI::hier::BoxOverlap.
Referenced by SAMRAI::pdat::NodeData< TYPE >::packStream().
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/NodeOverlap.h
source/SAMRAI/pdat/NodeOverlap.C