SAMRAI: SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern Class Reference
SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern Class Reference
PatchLevelFillPattern implementation for filling at PatchLevel boundaries and interiors.
#include <source/SAMRAI/xfer/PatchLevelBorderAndInteriorFillPattern.h>
Public Member Functions
PatchLevelBorderAndInteriorFillPattern ()
Default constructor.
virtual ~PatchLevelBorderAndInteriorFillPattern ()
Destructor.
void computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > &fill_box_level, boost::shared_ptr< hier::Connector > &dst_to_fill, const hier::BoxLevel &dst_box_level, const hier::IntVector &fill_ghost_width, bool data_on_patch_border)
Compute the boxes to be filled and related communication data.
bool needsToCommunicateDestinationFillBoxes () const
Return true to indicate source patch owners cannot compute fill boxes without using communication.
void computeDestinationFillBoxesOnSourceProc (FillSet &dst_fill_boxes_on_src_proc, const hier::BoxLevel &dst_box_level, const hier::Connector &src_to_dst, const hier::IntVector &fill_ghost_width)
Virtual method to compute the destination fill boxes.
bool doesSourceLevelCommunicateToDestination () const
Tell RefineSchedule to communicate data directly from source level to destination level.
int getMaxFillBoxes () const
Return the maximum number of fill boxes.
bool fillingCoarseFineGhosts () const
Returns true because this fill pattern fills coarse fine ghost data.
bool fillingEnhancedConnectivityOnly () const
Returns false because this fill pattern is not specialized for enhanced connectivity only.
Detailed Description
PatchLevelFillPattern implementation for filling at PatchLevel boundaries and interiors.
For documentation on this interface see PatchLevelFillPattern
The fill boxes will consist of the interior of the destination level as well as ghost regions lying outside of the level interior at physical and coarse-fine boundaries. Ghost regions that overlap the interiors of other boxes on the destination level will not be included.
Constructor & Destructor Documentation
SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::PatchLevelBorderAndInteriorFillPattern ()
Default constructor.
SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::~PatchLevelBorderAndInteriorFillPattern () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets (boost::shared_ptr< hier::BoxLevel > & fill_box_level, boost::shared_ptr< hier::Connector > & dst_to_fill, const hier::BoxLevel & dst_box_level, const hier::IntVector & fill_ghost_width, bool data_on_patch_border) [virtual]
Compute the boxes to be filled and related communication data.
The computed fill_box_level will cover the ghost regions around the boxes of dst_box_level at coarse-fine and physical boundaries, as well as the interior of the boxes of dst_box_level. The width of the ghost regions will be determined by fill_ghost_width.
Parameters:
[out] fill_box_level Output BoxLevel to be filled
[out] dst_to_fill Output Connector between dst_box_level and fill_box_level
[in] dst_box_level destination level
[in] fill_ghost_width Ghost width being filled by refine schedule
[in] data_on_patch_border true if there is data living on patch borders
Precondition:
dst_box_level.getDim() == fill_ghost_width.getDim()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::CONNECTOR_IMPLICIT_CREATION_RULE, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxLevel::findConnector(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), SAMRAI::hier::BoxContainer::removeIntersections(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::needsToCommunicateDestinationFillBoxes () const [virtual]
Return true to indicate source patch owners cannot compute fill boxes without using communication.
Implements SAMRAI::xfer::PatchLevelFillPattern.
Referenced by computeDestinationFillBoxesOnSourceProc().
void SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeDestinationFillBoxesOnSourceProc (FillSet & dst_fill_boxes_on_src_proc, const hier::BoxLevel & dst_box_level, const hier::Connector & src_to_dst, const hier::IntVector & fill_ghost_width) [virtual]
Virtual method to compute the destination fill boxes.
Unimplemented for this class as needsToCommunicateDestinationFillBoxes() returns true.
Parameters:
[out] dst_fill_boxes_on_src_proc FillSet storing the destination neighbors of the source mapped boxes
[in] dst_box_level destination level
[in] src_to_dst Connector of source to destination
[in] fill_ghost_width Ghost width being filled by refine schedule
Precondition:
needsToCommunicateDestinationFillBoxes()
Implements SAMRAI::xfer::PatchLevelFillPattern.
References needsToCommunicateDestinationFillBoxes(), NULL_USE, and TBOX_ERROR.
bool SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::doesSourceLevelCommunicateToDestination () const [virtual]
Tell RefineSchedule to communicate data directly from source level to destination level.
RefineSchedule should attempt to fill as much of the destination level as possible from the source level at the same level of resolution for this fill pattern.
Returns:
true
Implements SAMRAI::xfer::PatchLevelFillPattern.
int SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::getMaxFillBoxes () const [virtual]
Return the maximum number of fill boxes.
Returns:
maximum number of fill boxes.
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::fillingCoarseFineGhosts () const [virtual]
Returns true because this fill pattern fills coarse fine ghost data.
Implements SAMRAI::xfer::PatchLevelFillPattern.
bool SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::fillingEnhancedConnectivityOnly () const [virtual]
Returns false because this fill pattern is not specialized for enhanced connectivity only.
Implements SAMRAI::xfer::PatchLevelFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/PatchLevelBorderAndInteriorFillPattern.h
source/SAMRAI/xfer/PatchLevelBorderAndInteriorFillPattern.C