SAMRAI: SAMRAI::tbox::Database Class Reference
SAMRAI::tbox::Database Class Reference
Class Database is an abstract base class for the input, restart, and visualization databases.
#include <source/SAMRAI/tbox/Database.h>
Public Types
enum DataType {
SAMRAI_INVALID, SAMRAI_DATABASE, SAMRAI_BOOL, SAMRAI_CHAR,
SAMRAI_INT, SAMRAI_COMPLEX, SAMRAI_DOUBLE, SAMRAI_FLOAT,
SAMRAI_STRING, SAMRAI_BOX
}
Public Member Functions
Database ()
virtual ~Database ()
virtual bool create (const std::string &name)=0
virtual bool open (const std::string &name, const bool read_write_mode=false)=0
virtual bool close ()=0
virtual bool keyExists (const std::string &key)=0
virtual std::vector< std::string > getAllKeys ()=0
virtual enum DataType getArrayType (const std::string &key)=0
Return the type of data associated with the key.
virtual size_t getArraySize (const std::string &key)=0
Return the size of the array associated with the key.
virtual bool isDatabase (const std::string &key)=0
virtual boost::shared_ptr
< Database > putDatabase (const std::string &key)=0
virtual boost::shared_ptr
< Database > getDatabase (const std::string &key)=0
virtual boost::shared_ptr
< Database > getDatabaseWithDefault (const std::string &key, const boost::shared_ptr< Database > &defaultvalue)
virtual bool isBool (const std::string &key)=0
virtual void putBool (const std::string &key, const bool &data)
virtual void putBoolVector (const std::string &key, const std::vector< bool > &data)
virtual void putBoolArray (const std::string &key, const bool *const data, const size_t nelements)=0
virtual bool getBool (const std::string &key)
virtual bool getBoolWithDefault (const std::string &key, const bool &defaultvalue)
virtual std::vector< bool > getBoolVector (const std::string &key)=0
virtual void getBoolArray (const std::string &key, bool *data, const size_t nelements)
virtual bool isDatabaseBox (const std::string &key)=0
virtual void putDatabaseBox (const std::string &key, const DatabaseBox &data)
virtual void putDatabaseBoxVector (const std::string &key, const std::vector< DatabaseBox > &data)
virtual void putDatabaseBoxArray (const std::string &key, const DatabaseBox *const data, const size_t nelements)=0
virtual DatabaseBox getDatabaseBox (const std::string &key)
virtual DatabaseBox getDatabaseBoxWithDefault (const std::string &key, const DatabaseBox &defaultvalue)
virtual std::vector< DatabaseBox > getDatabaseBoxVector (const std::string &key)=0
virtual void getDatabaseBoxArray (const std::string &key, DatabaseBox *data, const size_t nelements)
virtual bool isChar (const std::string &key)=0
virtual void putChar (const std::string &key, const char &data)
virtual void putCharVector (const std::string &key, const std::vector< char > &data)
virtual void putCharArray (const std::string &key, const char *const data, const size_t nelements)=0
virtual char getChar (const std::string &key)
virtual char getCharWithDefault (const std::string &key, const char &defaultvalue)
virtual std::vector< char > getCharVector (const std::string &key)=0
virtual void getCharArray (const std::string &key, char *data, const size_t nelements)
virtual bool isComplex (const std::string &key)=0
virtual void putComplex (const std::string &key, const dcomplex &data)
virtual void putComplexVector (const std::string &key, const std::vector< dcomplex > &data)
virtual void putComplexArray (const std::string &key, const dcomplex *const data, const size_t nelements)=0
virtual dcomplex getComplex (const std::string &key)
virtual dcomplex getComplexWithDefault (const std::string &key, const dcomplex &defaultvalue)
virtual std::vector< dcomplex > getComplexVector (const std::string &key)=0
virtual void getComplexArray (const std::string &key, dcomplex *data, const size_t nelements)
virtual bool isDouble (const std::string &key)=0
virtual void putDouble (const std::string &key, const double &data)
virtual void putDoubleVector (const std::string &key, const std::vector< double > &data)
virtual void putDoubleArray (const std::string &key, const double *const data, const size_t nelements)=0
virtual double getDouble (const std::string &key)
virtual double getDoubleWithDefault (const std::string &key, const double &defaultvalue)
virtual std::vector< double > getDoubleVector (const std::string &key)=0
virtual void getDoubleArray (const std::string &key, double *data, const size_t nelements)
virtual bool isFloat (const std::string &key)=0
virtual void putFloat (const std::string &key, const float &data)
virtual void putFloatVector (const std::string &key, const std::vector< float > &data)
virtual void putFloatArray (const std::string &key, const float *const data, const size_t nelements)=0
virtual float getFloat (const std::string &key)
virtual float getFloatWithDefault (const std::string &key, const float &defaultvalue)
virtual std::vector< float > getFloatVector (const std::string &key)=0
virtual void getFloatArray (const std::string &key, float *data, const size_t nelements)
virtual bool isInteger (const std::string &key)=0
virtual void putInteger (const std::string &key, const int &data)
virtual void putIntegerVector (const std::string &key, const std::vector< int > &data)
virtual void putIntegerArray (const std::string &key, const int *const data, const size_t nelements)=0
virtual int getInteger (const std::string &key)
virtual int getIntegerWithDefault (const std::string &key, const int &defaultvalue)
virtual std::vector< int > getIntegerVector (const std::string &key)=0
virtual void getIntegerArray (const std::string &key, int *data, const size_t nelements)
virtual bool isString (const std::string &key)=0
virtual void putString (const std::string &key, const std::string &data)
virtual void putStringVector (const std::string &key, const std::vector< std::string > &data)
virtual void putStringArray (const std::string &key, const std::string *const data, const size_t nelements)=0
virtual std::string getString (const std::string &key)
virtual std::string getStringWithDefault (const std::string &key, const std::string &defaultvalue)
virtual std::vector< std::string > getStringVector (const std::string &key)=0
virtual void getStringArray (const std::string &key, std::string *data, const size_t nelements)
void getScalar (const std::string &key, bool &scalar)
void putScalar (const std::string &key, const bool scalar)
void getVector (const std::string &key, std::vector< bool > &array)
void putVector (const std::string &key, const std::vector< bool > &array)
void getScalar (const std::string &key, char &scalar)
void putScalar (const std::string &key, const char scalar)
void getVector (const std::string &key, std::vector< char > &array)
void putVector (const std::string &key, const std::vector< char > &array)
void getScalar (const std::string &key, dcomplex &scalar)
void putScalar (const std::string &key, const dcomplex scalar)
void getVector (const std::string &key, std::vector< dcomplex > &array)
void putVector (const std::string &key, const std::vector< dcomplex > &array)
void getScalar (const std::string &key, float &scalar)
void putScalar (const std::string &key, const float scalar)
void getVector (const std::string &key, std::vector< float > &array)
void putVector (const std::string &key, const std::vector< float > &array)
void getScalar (const std::string &key, double &scalar)
void putScalar (const std::string &key, const double scalar)
void getVector (const std::string &key, std::vector< double > &array)
void putVector (const std::string &key, const std::vector< double > &array)
void getScalar (const std::string &key, int &scalar)
void putScalar (const std::string &key, const int scalar)
void getVector (const std::string &key, std::vector< int > &array)
void putVector (const std::string &key, const std::vector< int > &array)
virtual bool isVector (const std::string &key)
template<class TYPE >
void getObjectVector (const std::string &key, std::vector< TYPE > &vector)
template<class TYPE >
void putObjectVector (const std::string &key, const std::vector< TYPE > &vector)
virtual std::string getName ()=0
Returns the name of this database.
virtual void printClassData (std::ostream &os=pout)=0
Detailed Description
Class Database is an abstract base class for the input, restart, and visualization databases.
SAMRAI databases store (key,value) pairs in a hierarchical database. Each value may be another database or a boolean, box, character, double complex, double, float, integer, or string. DatabaseBoxes are stored using the toolbox box structure.
Data is entered into the database through methods of the general form putTYPE(key, TYPE) or putTYPEArray(key, TYPE array), where TYPE is the type of value created. If the specified key already exists in the database, then the existing key is silently deleted.
Data is extracted from the database through methods of the general form TYPE = getTYPE(key), where TYPE is the type of value to be returned from the database. There are two general lookup methods. In the first, a default value is provided (for scalars only). If the specified key is not found in the database, then the specified default is returned. In the second form, no default is provided, and the database exists with an error message and program exits if the key is not found. The array version of getTYPE() works in a similar fashion.
Member Enumeration Documentation
enum SAMRAI::tbox::Database::DataType
Enumerated type indicating what type of values is stored in a database entry. Returned from getType() method.
Note: The SAMRAI_ prefix is needed since some poorly written packages do "#define CHAR" etc.
Enumerator:
SAMRAI_INVALID
SAMRAI_DATABASE
SAMRAI_BOOL
SAMRAI_CHAR
SAMRAI_INT
SAMRAI_COMPLEX
SAMRAI_DOUBLE
SAMRAI_FLOAT
SAMRAI_STRING
SAMRAI_BOX
Constructor & Destructor Documentation
SAMRAI::tbox::Database::Database ()
The constructor for the database base class does nothing interesting.
SAMRAI::tbox::Database::~Database () [virtual]
The virtual destructor for the database base class does nothing interesting.
Member Function Documentation
virtual bool SAMRAI::tbox::Database::create (const std::string & name) [pure virtual]
Create a new database file.
Returns true if successful.
Parameters:
name name of database. Normally a filename.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
virtual bool SAMRAI::tbox::Database::open (const std::string & name, const bool read_write_mode = false) [pure virtual]
Open an existing database file.
Returns true if successful.
Parameters:
name name of database. Normally a filename.
read_write_mode Open the database in read-write mode instead of read-only mode.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
virtual bool SAMRAI::tbox::Database::close () [pure virtual]
Close the database.
Returns true if successful.
If the database is currently open then close it. This should flush all data to the file (if the database is on disk).
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
virtual bool SAMRAI::tbox::Database::keyExists (const std::string & key) [pure virtual]
Return true if the specified key exists in the database and false otherwise.
Parameters:
key Key name to lookup.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getBoolWithDefault(), getCharWithDefault(), getComplexWithDefault(), getDatabaseBoxWithDefault(), getDatabaseWithDefault(), getDoubleWithDefault(), getFloatWithDefault(), getIntegerWithDefault(), and getStringWithDefault().
virtual std::vector<std::string> SAMRAI::tbox::Database::getAllKeys () [pure virtual]
Return all keys in the database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
virtual enum DataType SAMRAI::tbox::Database::getArrayType (const std::string & key) [pure virtual]
Return the type of data associated with the key.
If the key does not exist, then INVALID is returned
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
virtual size_t SAMRAI::tbox::Database::getArraySize (const std::string & key) [pure virtual]
Return the size of the array associated with the key.
If the key does not exist, then zero is returned. If the key is a database then zero is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by SAMRAI::hier::IntVector::getFromRestart().
virtual bool SAMRAI::tbox::Database::isDatabase (const std::string & key) [pure virtual]
Return whether the specified key represents a database entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
virtual boost::shared_ptr<Database> SAMRAI::tbox::Database::putDatabase (const std::string & key) [pure virtual]
Create a new database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
virtual boost::shared_ptr<Database> SAMRAI::tbox::Database::getDatabase (const std::string & key) [pure virtual]
Get the database with the specified key name. If the specified key does not exist in the database or it is not a database, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getDatabaseWithDefault(), and SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart().
boost::shared_ptr< Database > SAMRAI::tbox::Database::getDatabaseWithDefault (const std::string & key, const boost::shared_ptr< Database > & defaultvalue) [virtual]
Get a database in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a database, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
References getDatabase(), keyExists(), and TBOX_ASSERT.
virtual bool SAMRAI::tbox::Database::isBool (const std::string & key) [pure virtual]
Return whether the specified key represents a boolean entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
void SAMRAI::tbox::Database::putBool (const std::string & key, const bool & data) [virtual]
Create a boolean scalar entry in the database with the specified key name. If thoe key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Value to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putBoolArray(), and TBOX_ASSERT.
Referenced by putScalar().
void SAMRAI::tbox::Database::putBoolVector (const std::string & key, const std::vector< bool > & data) [virtual]
Create a boolean vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
References getName(), putBoolArray(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by putVector().
virtual void SAMRAI::tbox::Database::putBoolArray (const std::string & key, const bool *const data, const size_t nelements) [pure virtual]
Create a boolean array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putBool(), and putBoolVector().
bool SAMRAI::tbox::Database::getBool (const std::string & key) [virtual]
Get a boolean entry in the database with the specified key name. If the specified key does not exist in the database or is not a boolean scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getBoolArray(), and TBOX_ASSERT.
Referenced by getScalar().
bool SAMRAI::tbox::Database::getBoolWithDefault (const std::string & key, const bool & defaultvalue) [virtual]
Get a boolean entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a boolean scalar, then an error message is printed and the program exits.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getBoolVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<bool> SAMRAI::tbox::Database::getBoolVector (const std::string & key) [pure virtual]
Get a boolean entry from the database with the specified key name. If the specified key does not exist in the database or is not a boolean vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getBoolArray(), getBoolWithDefault(), and getVector().
void SAMRAI::tbox::Database::getBoolArray (const std::string & key, bool * data, const size_t nelements) [virtual]
Get a boolean entry from the database with the specified key name. If the specified key does not exist in the database or is not a boolean array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getBoolVector(), getName(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getBool().
virtual bool SAMRAI::tbox::Database::isDatabaseBox (const std::string & key) [pure virtual]
Return whether the specified key represents a box entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
void SAMRAI::tbox::Database::putDatabaseBox (const std::string & key, const DatabaseBox & data) [virtual]
Create a box scalar entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Data to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putDatabaseBoxArray(), and TBOX_ASSERT.
void SAMRAI::tbox::Database::putDatabaseBoxVector (const std::string & key, const std::vector< DatabaseBox > & data) [virtual]
Create a box array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), putDatabaseBoxArray(), TBOX_ASSERT, and TBOX_ERROR.
virtual void SAMRAI::tbox::Database::putDatabaseBoxArray (const std::string & key, const DatabaseBox *const data, const size_t nelements) [pure virtual]
Create a box array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putDatabaseBox(), and putDatabaseBoxVector().
DatabaseBox SAMRAI::tbox::Database::getDatabaseBox (const std::string & key) [virtual]
Get a box entry in the database with the specified key name. If the specified key does not exist in the database or is not a box scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getDatabaseBoxArray(), and TBOX_ASSERT.
DatabaseBox SAMRAI::tbox::Database::getDatabaseBoxWithDefault (const std::string & key, const DatabaseBox & defaultvalue) [virtual]
Get a box entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a box scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getDatabaseBoxVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<DatabaseBox> SAMRAI::tbox::Database::getDatabaseBoxVector (const std::string & key) [pure virtual]
Get a box entry from the database with the specified key name. If the specified key does not exist in the database or is not a box vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getDatabaseBoxArray(), getDatabaseBoxWithDefault(), and SAMRAI::hier::BoxContainer::getFromRestart().
void SAMRAI::tbox::Database::getDatabaseBoxArray (const std::string & key, DatabaseBox * data, const size_t nelements) [virtual]
Get a box entry from the database with the specified key name. If the specified key does not exist in the database or is not a box array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getDatabaseBoxVector(), getName(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getDatabaseBox().
virtual bool SAMRAI::tbox::Database::isChar (const std::string & key) [pure virtual]
Return whether the specified key represents a character entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
void SAMRAI::tbox::Database::putChar (const std::string & key, const char & data) [virtual]
Create a character scalar entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Value to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putCharArray(), and TBOX_ASSERT.
Referenced by putScalar().
void SAMRAI::tbox::Database::putCharVector (const std::string & key, const std::vector< char > & data) [virtual]
Create a character vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), putCharArray(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by putVector().
virtual void SAMRAI::tbox::Database::putCharArray (const std::string & key, const char *const data, const size_t nelements) [pure virtual]
Create a character array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putChar(), and putCharVector().
char SAMRAI::tbox::Database::getChar (const std::string & key) [virtual]
Get a character entry in the database with the specified key name. If the specified key does not exist in the database or is not an character scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getCharArray(), and TBOX_ASSERT.
Referenced by getScalar().
char SAMRAI::tbox::Database::getCharWithDefault (const std::string & key, const char & defaultvalue) [virtual]
Get a character entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a character scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getCharVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<char> SAMRAI::tbox::Database::getCharVector (const std::string & key) [pure virtual]
Get a character entry from the database with the specified key name. If the specified key does not exist in the database or is not a character vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getCharArray(), getCharWithDefault(), and getVector().
void SAMRAI::tbox::Database::getCharArray (const std::string & key, char * data, const size_t nelements) [virtual]
Get a character entry from the database with the specified key name. If the specified key does not exist in the database or is not a character array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getCharVector(), getName(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getChar().
virtual bool SAMRAI::tbox::Database::isComplex (const std::string & key) [pure virtual]
Return whether the specified key represents a complex entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
void SAMRAI::tbox::Database::putComplex (const std::string & key, const dcomplex & data) [virtual]
Create a complex scalar entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Value to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putComplexArray(), and TBOX_ASSERT.
Referenced by putScalar().
void SAMRAI::tbox::Database::putComplexVector (const std::string & key, const std::vector< dcomplex > & data) [virtual]
Create a complex vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), putComplexArray(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by putVector().
virtual void SAMRAI::tbox::Database::putComplexArray (const std::string & key, const dcomplex *const data, const size_t nelements) [pure virtual]
Create a complex array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putComplex(), and putComplexVector().
dcomplex SAMRAI::tbox::Database::getComplex (const std::string & key) [virtual]
Get a complex entry in the database with the specified key name. If the specified key does not exist in the database or is not a complex scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getComplexArray(), and TBOX_ASSERT.
Referenced by getScalar().
dcomplex SAMRAI::tbox::Database::getComplexWithDefault (const std::string & key, const dcomplex & defaultvalue) [virtual]
Get a complex entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a complex scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getComplexVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<dcomplex> SAMRAI::tbox::Database::getComplexVector (const std::string & key) [pure virtual]
Get a complex entry from the database with the specified key name. If the specified key does not exist in the database or is not a complex vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getComplexArray(), getComplexWithDefault(), and getVector().
void SAMRAI::tbox::Database::getComplexArray (const std::string & key, dcomplex * data, const size_t nelements) [virtual]
Get a complex entry from the database with the specified key name. If the specified key does not exist in the database or is not a complex array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getComplexVector(), getName(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getComplex().
virtual bool SAMRAI::tbox::Database::isDouble (const std::string & key) [pure virtual]
Return whether the specified key represents a double entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
void SAMRAI::tbox::Database::putDouble (const std::string & key, const double & data) [virtual]
Create a double scalar entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Value to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putDoubleArray(), and TBOX_ASSERT.
Referenced by putScalar().
void SAMRAI::tbox::Database::putDoubleVector (const std::string & key, const std::vector< double > & data) [virtual]
Create a double vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), putDoubleArray(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by putVector().
virtual void SAMRAI::tbox::Database::putDoubleArray (const std::string & key, const double *const data, const size_t nelements) [pure virtual]
Create a double array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putDouble(), and putDoubleVector().
double SAMRAI::tbox::Database::getDouble (const std::string & key) [virtual]
Get a double entry in the database with the specified key name. If the specified key does not exist in the database or is not a double scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getDoubleArray(), and TBOX_ASSERT.
Referenced by getScalar().
double SAMRAI::tbox::Database::getDoubleWithDefault (const std::string & key, const double & defaultvalue) [virtual]
Get a double entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a double scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getDoubleVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<double> SAMRAI::tbox::Database::getDoubleVector (const std::string & key) [pure virtual]
Get a double entry from the database with the specified key name. If the specified key does not exist in the database or is not a double vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getDoubleArray(), getDoubleWithDefault(), and getVector().
void SAMRAI::tbox::Database::getDoubleArray (const std::string & key, double * data, const size_t nelements) [virtual]
Get a double entry from the database with the specified key name. If the specified key does not exist in the database or is not a double array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getDoubleVector(), getName(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getDouble().
virtual bool SAMRAI::tbox::Database::isFloat (const std::string & key) [pure virtual]
Return whether the specified key represents a float entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
void SAMRAI::tbox::Database::putFloat (const std::string & key, const float & data) [virtual]
Create a float scalar entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Value to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putFloatArray(), and TBOX_ASSERT.
Referenced by putScalar().
void SAMRAI::tbox::Database::putFloatVector (const std::string & key, const std::vector< float > & data) [virtual]
Create a float vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), putFloatArray(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by putVector().
virtual void SAMRAI::tbox::Database::putFloatArray (const std::string & key, const float *const data, const size_t nelements) [pure virtual]
Create a float array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putFloat(), and putFloatVector().
float SAMRAI::tbox::Database::getFloat (const std::string & key) [virtual]
Get a float entry in the database with the specified key name. If the specified key does not exist in the database or is not a float scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getFloatArray(), and TBOX_ASSERT.
Referenced by getScalar().
float SAMRAI::tbox::Database::getFloatWithDefault (const std::string & key, const float & defaultvalue) [virtual]
Get a float entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a float scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getFloatVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<float> SAMRAI::tbox::Database::getFloatVector (const std::string & key) [pure virtual]
Get a float entry from the database with the specified key name. If the specified key does not exist in the database or is not a float vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getFloatArray(), getFloatWithDefault(), and getVector().
void SAMRAI::tbox::Database::getFloatArray (const std::string & key, float * data, const size_t nelements) [virtual]
Get a float entry from the database with the specified key name. If the specified key does not exist in the database or is not a float array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getFloatVector(), getName(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getFloat().
virtual bool SAMRAI::tbox::Database::isInteger (const std::string & key) [pure virtual]
Return whether the specified key represents an integer entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by isVector().
void SAMRAI::tbox::Database::putInteger (const std::string & key, const int & data) [virtual]
Create an integer scalar entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Value to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putIntegerArray(), and TBOX_ASSERT.
Referenced by putObjectVector(), and putScalar().
void SAMRAI::tbox::Database::putIntegerVector (const std::string & key, const std::vector< int > & data) [virtual]
Create an integer vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), putIntegerArray(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by putVector().
virtual void SAMRAI::tbox::Database::putIntegerArray (const std::string & key, const int *const data, const size_t nelements) [pure virtual]
Create an integer array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putInteger(), putIntegerVector(), and SAMRAI::hier::IntVector::putToRestart().
int SAMRAI::tbox::Database::getInteger (const std::string & key) [virtual]
Get an integer entry in the database with the specified key name. If the specified key does not exist in the database or is not an integer scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getIntegerArray(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::BoxContainer::getFromRestart(), getObjectVector(), and getScalar().
int SAMRAI::tbox::Database::getIntegerWithDefault (const std::string & key, const int & defaultvalue) [virtual]
Get an integer entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not an integer scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getIntegerVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<int> SAMRAI::tbox::Database::getIntegerVector (const std::string & key) [pure virtual]
Get an integer entry from the database with the specified key name. If the specified key does not exist in the database or is not an integer vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::BoxContainer::getFromRestart(), getIntegerArray(), getIntegerWithDefault(), and getVector().
void SAMRAI::tbox::Database::getIntegerArray (const std::string & key, int * data, const size_t nelements) [virtual]
Get an integer entry from the database with the specified key name. If the specified key does not exist in the database or is not an integer array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getIntegerVector(), getName(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::IntVector::getFromRestart(), and getInteger().
virtual bool SAMRAI::tbox::Database::isString (const std::string & key) [pure virtual]
Return whether the specified key represents a std::string entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
void SAMRAI::tbox::Database::putString (const std::string & key, const std::string & data) [virtual]
Create a string scalar entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Value to put into database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References putStringArray(), and TBOX_ASSERT.
void SAMRAI::tbox::Database::putStringVector (const std::string & key, const std::vector< std::string > & data) [virtual]
Create a string vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Vector with data to put into database.
Precondition:
!key.empty()
data.size() > 0
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), putStringArray(), TBOX_ASSERT, and TBOX_ERROR.
virtual void SAMRAI::tbox::Database::putStringArray (const std::string & key, const std::string *const data, const size_t nelements) [pure virtual]
Create a string array entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by putString(), and putStringVector().
std::string SAMRAI::tbox::Database::getString (const std::string & key) [virtual]
Get a string entry in the database with the specified key name. If the specified key does not exist in the database or is not an string scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getStringArray(), and TBOX_ASSERT.
std::string SAMRAI::tbox::Database::getStringWithDefault (const std::string & key, const std::string & defaultvalue) [virtual]
Get a string entry in the database with the specified key name. If the specified key does not exist in the database, then the default value is returned. If the key exists but is not a string scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
defaultvalue Default value to return if not found.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getStringVector(), keyExists(), and TBOX_ASSERT.
virtual std::vector<std::string> SAMRAI::tbox::Database::getStringVector (const std::string & key) [pure virtual]
Get a string entry from the database with the specified key name. If the specified key does not exist in the database or is not a string vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getStringArray(), and getStringWithDefault().
void SAMRAI::tbox::Database::getStringArray (const std::string & key, std::string * data, const size_t nelements) [virtual]
Get a string entry from the database with the specified key name. If the specified key does not exist in the database or is not a string array, then an error message is printed and the program exits. The specified number of elements must match exactly the number of elements in the array in the database.
Parameters:
key Key name in database.
data Array with data to put into database.
nelements Number of elements to write from array.
Precondition:
!key.empty()
Reimplemented in SAMRAI::tbox::MemoryDatabase.
References getName(), getStringVector(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getString().
void SAMRAI::tbox::Database::getScalar (const std::string & key, bool & scalar) [inline]
Get a bool entry in the database with the specified key name. If the specified key does not exist in the database or is not an bool scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Returns scalar that was read.
References getBool().
void SAMRAI::tbox::Database::putScalar (const std::string & key, const bool scalar) [inline]
Get a bool entry from the database with the specified key name. If the specified key does not exist in the database or is not a bool array, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Value to put into database.
References putBool().
void SAMRAI::tbox::Database::getVector (const std::string & key, std::vector< bool > & array) [inline]
Get a bool entry from the database with the specified key name. If the specified key does not exist in the database or is not a bool vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
array Returns vector that was read.
References getBoolVector().
void SAMRAI::tbox::Database::putVector (const std::string & key, const std::vector< bool > & array) [inline]
Create a bool vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
array Vector to put into database.
References putBoolVector().
void SAMRAI::tbox::Database::getScalar (const std::string & key, char & scalar) [inline]
Get a char entry in the database with the specified key name. If the specified key does not exist in the database or is not an char scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Returns scalar that was read.
References getChar().
void SAMRAI::tbox::Database::putScalar (const std::string & key, const char scalar) [inline]
Get a char entry from the database with the specified key name. If the specified key does not exist in the database or is not a char array, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Value to put into database.
References putChar().
void SAMRAI::tbox::Database::getVector (const std::string & key, std::vector< char > & array) [inline]
Get a char entry from the database with the specified key name. If the specified key does not exist in the database or is not a char vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
array Returns array that was read.
References getCharVector().
void SAMRAI::tbox::Database::putVector (const std::string & key, const std::vector< char > & array) [inline]
Create an char vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
array Vector to put into database.
References putCharVector().
void SAMRAI::tbox::Database::getScalar (const std::string & key, dcomplex & scalar) [inline]
Get a complex entry in the database with the specified key name. If the specified key does not exist in the database or is not an complex scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Returns scalar that was read.
References getComplex().
void SAMRAI::tbox::Database::putScalar (const std::string & key, const dcomplex scalar) [inline]
Get a complex entry from the database with the specified key name. If the specified key does not exist in the database or is not a complex array, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Value to put into database.
References putComplex().
void SAMRAI::tbox::Database::getVector (const std::string & key, std::vector< dcomplex > & array) [inline]
Get a complex entry from the database with the specified key name. If the specified key does not exist in the database or is not a complex vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
array Returns array that was read.
References getComplexVector().
void SAMRAI::tbox::Database::putVector (const std::string & key, const std::vector< dcomplex > & array) [inline]
Create a complex vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
array Vector to put into database.
References putComplexVector().
void SAMRAI::tbox::Database::getScalar (const std::string & key, float & scalar) [inline]
Get a float entry in the database with the specified key name. If the specified key does not exist in the database or is not an float scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Returns scalar that was read.
References getFloat().
void SAMRAI::tbox::Database::putScalar (const std::string & key, const float scalar) [inline]
Get a float entry from the database with the specified key name. If the specified key does not exist in the database or is not a float array, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Value to put into database.
References putFloat().
void SAMRAI::tbox::Database::getVector (const std::string & key, std::vector< float > & array) [inline]
Get a float entry from the database with the specified key name. If the specified key does not exist in the database or is not a float vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
array Returns vector that was read.
References getFloatVector().
void SAMRAI::tbox::Database::putVector (const std::string & key, const std::vector< float > & array) [inline]
Create a float vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
array Vector to put into database.
References putFloatVector().
void SAMRAI::tbox::Database::getScalar (const std::string & key, double & scalar) [inline]
Get a double entry in the database with the specified key name. If the specified key does not exist in the database or is not an double scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Returns scalar that was read.
References getDouble().
void SAMRAI::tbox::Database::putScalar (const std::string & key, const double scalar) [inline]
Get a double entry from the database with the specified key name. If the specified key does not exist in the database or is not a double array, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Value to put into database.
References putDouble().
void SAMRAI::tbox::Database::getVector (const std::string & key, std::vector< double > & array) [inline]
Get a double entry from the database with the specified key name. If the specified key does not exist in the database or is not a double vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
array Returns vector that was read.
References getDoubleVector().
void SAMRAI::tbox::Database::putVector (const std::string & key, const std::vector< double > & array) [inline]
Create an double vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
array Vector to put into database.
References putDoubleVector().
void SAMRAI::tbox::Database::getScalar (const std::string & key, int & scalar) [inline]
Get a integer entry in the database with the specified key name. If the specified key does not exist in the database or is not an integer scalar, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Returns scalar that was read.
References getInteger().
void SAMRAI::tbox::Database::putScalar (const std::string & key, const int scalar) [inline]
Get a integer entry from the database with the specified key name. If the specified key does not exist in the database or is not a integer array, then an error message is printed and the program exits.
Parameters:
key Key name in database.
scalar Value to put into database.
References putInteger().
void SAMRAI::tbox::Database::getVector (const std::string & key, std::vector< int > & array) [inline]
Get a integer entry from the database with the specified key name. If the specified key does not exist in the database or is not a integer vector, then an error message is printed and the program exits.
Parameters:
key Key name in database.
array Returns vector that was read.
References getIntegerVector().
void SAMRAI::tbox::Database::putVector (const std::string & key, const std::vector< int > & array) [inline]
Create an integer vector entry in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
Parameters:
key Key name in database.
array Vector to put into database.
References putIntegerVector().
bool SAMRAI::tbox::Database::isVector (const std::string & key) [virtual]
Return whether the specified key represents a vector entry. If the key does not exist, then false is returned.
Parameters:
key Key name in database.
References isInteger().
template<class TYPE > void SAMRAI::tbox::Database::getObjectVector (const std::string & key, std::vector< TYPE > & vector) [inline]
Get a std::vector<TYPE> of a collection of objects (as opposed to primitives) from the database with the specified key name. If the specified key does not exist in the database or is not a vector, then an error message is printed and the program exits.
TYPE must implement the Database::Serializable interface.
Parameters:
key Key name in database.
vector Returns the filled in vector.
References getInteger(), and SAMRAI::tbox::Utilities::intToString().
template<class TYPE > void SAMRAI::tbox::Database::putObjectVector (const std::string & key, const std::vector< TYPE > & vector) [inline]
Create a vector entry of a collection of objects (as opposed to primitives) in the database with the specified key name. If the key already exists in the database, then the old key record is deleted and the new one is silently created in its place.
TYPE must implement the Database::Serializable interface.
Parameters:
key Key name in database.
vector Vector to put into database.
References SAMRAI::tbox::Utilities::intToString(), and putInteger().
virtual std::string SAMRAI::tbox::Database::getName () [pure virtual]
Returns the name of this database.
The name for the root of the database is the name supplied when creating it. Names for nested databases are the keyname of the database.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
Referenced by getBoolArray(), getCharArray(), getComplexArray(), getDatabaseBoxArray(), getDoubleArray(), getFloatArray(), getIntegerArray(), getStringArray(), putBoolVector(), putCharVector(), putComplexVector(), putDatabaseBoxVector(), putDoubleVector(), putFloatVector(), putIntegerVector(), and putStringVector().
virtual void SAMRAI::tbox::Database::printClassData (std::ostream & os = pout) [pure virtual]
Print the current database to the specified output stream. If no output stream is specified, then data is written to stream pout.
Parameters:
os Output stream.
Implemented in SAMRAI::tbox::HDFDatabase, SAMRAI::tbox::MemoryDatabase, SAMRAI::tbox::NullDatabase, and SAMRAI::tbox::SiloDatabase.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Database.h
source/SAMRAI/tbox/Database.C