SAMRAI: SAMRAI::tbox::AsyncCommGroup Class Reference
SAMRAI::tbox::AsyncCommGroup Class Reference
Supports all-to-one and one-to-all asynchronous communication operations within a given group of processes by sending messages along the branches of a conceptual tree.
#include <source/SAMRAI/tbox/AsyncCommGroup.h>
Public Member Functions
AsyncCommGroup ()
Default constructor does not set up anything. You must initialize() the object before using it.
AsyncCommGroup (const size_t nchild, AsyncCommStage *stage, AsyncCommStage::Handler *handler=0)
Construct communication group.
virtual ~AsyncCommGroup ()
Destructor.
void initialize (const int nchild, AsyncCommStage *stage, AsyncCommStage::Handler *handler=0)
Initialize the object.
void setMPITag (const int mpi_tag)
Set the MPI tag used for communication within the group.
int getMPITag () const
Returns the MPI tag used for communication within the group.
int getGroupSize () const
Returns the size of the group.
TaskOp getNextTaskOp () const
Returns next task in a current communication operation.
BaseOp getBaseOp () const
Returns operation being performed.
int getParentRank () const
Rank of parent process in the group.
void setUseMPICollectiveForFullGroups (bool use_mpi_collective=true)
Set whether to use native MPI collective function calls when group includes all ranks in the MPI communicator.
void setUseBlockingSendToParent (const bool flag)
Set whether sends to parents should be blocking.
void setUseBlockingSendToChildren (const bool flag)
Set whether sends to children should be blocking.
int getNumberOfChildren () const
void logCurrentState (std::ostream &co) const
Define the communication group
void setGroupAndRootIndex (const SAMRAI_MPI &mpi, const int *group_ranks, const int group_size, const int root_index)
Setup the tree for the given group of processes. The root process is specified by its index in the group array.
void setGroupAndRootRank (const SAMRAI_MPI &mpi, const int *group_ranks, const int group_size, const int root_rank)
Setup the group for the given group. The root process is specified by its rank.
Communication methods
bool beginBcast (int *buffer, int size)
Begin a broadcast communication.
bool checkBcast ()
Check the current broadcast communication and complete the broadcast if all MPI requests are fulfilled.
bool beginGather (int *buffer, int size)
Begin a gather communication.
bool checkGather ()
Check the current gather communication and complete the gather if all MPI requests are fulfilled.
bool beginSumReduce (int *buffer, int size)
Begin a sum reduce communication.
bool checkSumReduce ()
Check the current sum reduce communication and complete the sum reduce if all MPI requests are fulfilled.
bool proceedToNextWait ()
Check the current communication and complete it if all MPI requests are fulfilled.
bool isDone () const
Whether the last communication operation has finished.
void completeCurrentOperation ()
Wait for the current operation to complete.
Detailed Description
Supports all-to-one and one-to-all asynchronous communication operations within a given group of processes by sending messages along the branches of a conceptual tree.
This class was created to perform certain group communications without using MPI global communications, which require creating new MPI communicators (can be expensive) and does not support asynchronous operations (until MPI-2).
The supported communications are asynchronous in that you can start one and wait for it or check back on it occassionally until it completes. Simultaneous Asynchronous operations of many groups can be done by using a AsyncCommStage to allocate the groups and to check for completed communications.
Supported operations are currently broadcast, gather and sum reduce. Only integer data is supported.
A tree is an acyclic graph in which a node at position pos has nchild children, and the following positions for its
parent: (pos-1)/nchild
first (oldest) child: pos*nchild+1
last (youngest) child: (pos+1)*nchild
For example, nchild=2 corresponds to a binary tree.
Communication is done by sending messages toward the root (for all-to-one operations) or leaves (for one-to-all operations). For the former, we receive data from the children and send to the parent. For the latter, we receive from the parent and send to the children. Thus every communication involves a receive and a send (except at the root and leaf nodes of the tree).
Using a tree generally gives better performance than having all processes in the the tree communicate directly with the root process. Using MPI communicators corresponding to the groups may faster than using this class, but the cost of creating MPI communicators MAY be expensive.
This class supports communication and uses MPI for message passing. If MPI is disabled, the job of this class disappears and the class is effectively empty. The public interfaces still remain so the class can compile, but the implementations are trivial.
Constructor & Destructor Documentation
SAMRAI::tbox::AsyncCommGroup::AsyncCommGroup ()
Default constructor does not set up anything. You must initialize() the object before using it.
SAMRAI::tbox::AsyncCommGroup::AsyncCommGroup (const size_t nchild, AsyncCommStage * stage, AsyncCommStage::Handler * handler = 0)
Construct communication group.
The number of children per node is flexible.
Parameters:
nchild Number of children per tree node in the group, i.e., nchild=2 is a binary tree.
stage
handler
Postcondition:
nchild == numberOfRequests()
References SAMRAI::tbox::AsyncCommStage::Member::numberOfRequests(), and TBOX_ASSERT.
SAMRAI::tbox::AsyncCommGroup::~AsyncCommGroup () [virtual]
Destructor.
Precondition:
isDone()
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), isDone(), and TBOX_ERROR.
Member Function Documentation
void SAMRAI::tbox::AsyncCommGroup::initialize (const int nchild, AsyncCommStage * stage, AsyncCommStage::Handler * handler = 0)
Initialize the object.
Attach self to the given stage and set the Handler.
Parameters:
nchild Number of children per tree node in the group, i.e., nchild=2 is a binary tree.
stage The required stage used for completing non-blocking message passing calls.
handler Optional handler (see AsyncCommStage::Member).
Precondition:
isDone()
References SAMRAI::tbox::AsyncCommStage::Member::attachStage(), isDone(), SAMRAI::tbox::AsyncCommStage::Member::setHandler(), and TBOX_ERROR.
void SAMRAI::tbox::AsyncCommGroup::setGroupAndRootIndex (const SAMRAI_MPI & mpi, const int * group_ranks, const int group_size, const int root_index)
Setup the tree for the given group of processes. The root process is specified by its index in the group array.
The root rank is specified by dereferencing group array with root_index.
Precondition:
getNextTaskOp() == none
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), getNextTaskOp(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSize(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by setGroupAndRootRank().
void SAMRAI::tbox::AsyncCommGroup::setGroupAndRootRank (const SAMRAI_MPI & mpi, const int * group_ranks, const int group_size, const int root_rank)
Setup the group for the given group. The root process is specified by its rank.
The rank of the root is root_rank, which must be one of the ranks given in the group.
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), setGroupAndRootIndex(), and TBOX_ERROR.
void SAMRAI::tbox::AsyncCommGroup::setMPITag (const int mpi_tag)
Set the MPI tag used for communication within the group.
Attention:
This class is NOT (and cannot be) responsible for ensuring that the MPI communicator and tag are sufficient to select the correct messages. Please specify appropriate values for the MPI communicator and tag. Very elusive bugs can occur if incorrect messages are received. To be safe, it is best to create a new communicator to avoid interference with other communications within SAMRAI.
Precondition:
isDone()
References isDone(), and TBOX_ERROR.
int SAMRAI::tbox::AsyncCommGroup::getMPITag () const [inline]
Returns the MPI tag used for communication within the group.
int SAMRAI::tbox::AsyncCommGroup::getGroupSize () const [inline]
Returns the size of the group.
TaskOp SAMRAI::tbox::AsyncCommGroup::getNextTaskOp () const [inline]
Returns next task in a current communication operation.
Referenced by beginBcast(), beginGather(), beginSumReduce(), checkBcast(), isDone(), and setGroupAndRootIndex().
BaseOp SAMRAI::tbox::AsyncCommGroup::getBaseOp () const [inline]
Returns operation being performed.
Referenced by checkBcast(), and checkGather().
int SAMRAI::tbox::AsyncCommGroup::getParentRank () const [inline]
Rank of parent process in the group.
void SAMRAI::tbox::AsyncCommGroup::setUseMPICollectiveForFullGroups (bool use_mpi_collective = true)
Set whether to use native MPI collective function calls when group includes all ranks in the MPI communicator.
This option is off by default to avoid MPI lock-ups. If you use it, make sure all processors can get to the collective operation to avoid lock-ups.
Precondition:
isDone()
References isDone(), and TBOX_ERROR.
void SAMRAI::tbox::AsyncCommGroup::setUseBlockingSendToParent (const bool flag) [inline]
Set whether sends to parents should be blocking.
The default is to use blocking send to parent. Because there is just one parent, short messages can be buffered by MPI to improve the performance of blocking sends. Blocking sends need not be checked for completion.
void SAMRAI::tbox::AsyncCommGroup::setUseBlockingSendToChildren (const bool flag) [inline]
Set whether sends to children should be blocking.
The default is to use nonblocking send to children. Nonblocking sends to children are generally appropriate as there are multiple children.
bool SAMRAI::tbox::AsyncCommGroup::beginBcast (int * buffer, int size)
Begin a broadcast communication.
Root process of broadcast may send less data (smaller size) than receivers of broadcast, in which case the missing data is considered irrelevant by the root.
If this method returns false, checkBcast() must be called until it returns true before any change in object state is allowed.
Returns:
Whether operation is completed.
Precondition:
getNextTaskOp() == none
References checkBcast(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), getNextTaskOp(), SAMRAI::tbox::SAMRAI_MPI::getSize(), and TBOX_ERROR.
bool SAMRAI::tbox::AsyncCommGroup::checkBcast ()
Check the current broadcast communication and complete the broadcast if all MPI requests are fulfilled.
If no communication is in progress, this call does nothing.
Returns:
Whether operation is completed.
Precondition:
getBaseOp() == bcast
Postcondition:
(getParentRank() != -1) || (getNextTaskOp() != recv_check)
References SAMRAI::tbox::SAMRAI_MPI::Get_count(), getBaseOp(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), getNextTaskOp(), SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer(), SAMRAI::tbox::SAMRAI_MPI::Irecv(), SAMRAI::tbox::SAMRAI_MPI::Isend(), MPI_ERR_IN_STATUS, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_ERROR, MPI_INT, MPI_REQUEST_NULL, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_SOURCE, MPI_SUCCESS, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_TAG, SAMRAI::tbox::plog, SAMRAI::tbox::SAMRAI_MPI::Send(), TBOX_ASSERT, TBOX_ERROR, and SAMRAI::tbox::SAMRAI_MPI::Test().
Referenced by beginBcast(), and proceedToNextWait().
bool SAMRAI::tbox::AsyncCommGroup::beginGather (int * buffer, int size)
Begin a gather communication.
The gather operation mimics the results of MPI_Gather.
Sending processes of gather may send less data (smaller size) than receivers, in which case the missing data is considered irrelevant by the sender.
If this method returns false, checkGather() must be called until it returns true before any change in object state is allowed.
On non-root processes, buffer should contain the data to be gathered. On the root process, it should have enough space for all the data from all the processes in the group.
Parameters:
buffer Data to gather.
size Number of items contributed by each process. This must be the same across processes. However, the root's actual usable buffer must be big enough to hold the gathered data (size times the number of processes in the group).
Returns:
Whether operation is completed.
Precondition:
getNextTaskOp() == none
References checkGather(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), getNextTaskOp(), SAMRAI::tbox::SAMRAI_MPI::getSize(), and TBOX_ERROR.
bool SAMRAI::tbox::AsyncCommGroup::checkGather ()
Check the current gather communication and complete the gather if all MPI requests are fulfilled.
Returns:
Whether operation is completed.
Precondition:
getBaseOp() == gather
References SAMRAI::tbox::SAMRAI_MPI::Get_count(), getBaseOp(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer(), SAMRAI::tbox::SAMRAI_MPI::Irecv(), SAMRAI::tbox::SAMRAI_MPI::Isend(), MPI_ERR_IN_STATUS, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_ERROR, MPI_INT, MPI_REQUEST_NULL, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_SOURCE, MPI_SUCCESS, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_TAG, SAMRAI::tbox::plog, SAMRAI::tbox::SAMRAI_MPI::Send(), TBOX_ASSERT, TBOX_ERROR, and SAMRAI::tbox::SAMRAI_MPI::Test().
Referenced by beginGather(), and proceedToNextWait().
bool SAMRAI::tbox::AsyncCommGroup::beginSumReduce (int * buffer, int size)
Begin a sum reduce communication.
Assume all messages are the same size.
If this method returns false, checkSumReduce() must be called until it returns true before any change in object state is allowed.
Buffer should contain the data to be gathered.
Returns:
Whether operation is completed.
Precondition:
getNextTaskOp() == none
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), getNextTaskOp(), and TBOX_ERROR.
bool SAMRAI::tbox::AsyncCommGroup::checkSumReduce () [inline]
Check the current sum reduce communication and complete the sum reduce if all MPI requests are fulfilled.
Returns:
Whether operation is completed.
bool SAMRAI::tbox::AsyncCommGroup::proceedToNextWait () [virtual]
Check the current communication and complete it if all MPI requests are fulfilled.
Implements SAMRAI::tbox::AsyncCommStage::Member.
References checkBcast(), checkGather(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), and TBOX_ERROR.
Referenced by completeCurrentOperation().
bool SAMRAI::tbox::AsyncCommGroup::isDone () const [virtual]
Whether the last communication operation has finished.
This means more than just whether there is pending MPI requests such as that returned by hasPendingRequests(). The communication may be more complex, requiring several messages and copying of the received message into the correct buffer.
Precondition:
(getNextTaskOp() != none) || !hasPendingRequests()
Implements SAMRAI::tbox::AsyncCommStage::Member.
References getNextTaskOp(), SAMRAI::tbox::AsyncCommStage::Member::hasPendingRequests(), and TBOX_ASSERT.
Referenced by initialize(), setMPITag(), setUseMPICollectiveForFullGroups(), ~AsyncCommGroup(), and SAMRAI::mesh::BergerRigoutsosNode::~BergerRigoutsosNode().
void SAMRAI::tbox::AsyncCommGroup::completeCurrentOperation () [virtual]
Wait for the current operation to complete.
Implements SAMRAI::tbox::AsyncCommStage::Member.
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer(), MPI_SUCCESS, proceedToNextWait(), TBOX_ERROR, and SAMRAI::tbox::SAMRAI_MPI::Waitall().
int SAMRAI::tbox::AsyncCommGroup::getNumberOfChildren () const [inline]
void SAMRAI::tbox::AsyncCommGroup::logCurrentState (std::ostream & co) const
References SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), and SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/AsyncCommGroup.h
source/SAMRAI/tbox/AsyncCommGroup.C