SAMRAI: SAMRAI::math::PatchCellDataNormOpsComplex Class Reference
SAMRAI::math::PatchCellDataNormOpsComplex Class Reference
#include <source/SAMRAI/math/PatchCellDataNormOpsComplex.h>
Public Member Functions
PatchCellDataNormOpsComplex ()
virtual ~PatchCellDataNormOpsComplex ()
size_t numberOfEntries (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const hier::Box &box) const
double sumControlVolumes (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const boost::shared_ptr< pdat::CellData< double > > &cvol, const hier::Box &box) const
void abs (const boost::shared_ptr< pdat::CellData< double > > &dst, const boost::shared_ptr< pdat::CellData< dcomplex > > &src, const hier::Box &box) const
double L1Norm (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &cvol=boost::shared_ptr< pdat::CellData< double > >()) const
double L2Norm (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &cvol=boost::shared_ptr< pdat::CellData< double > >()) const
double weightedL2Norm (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const boost::shared_ptr< pdat::CellData< dcomplex > > &weight, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &cvol=boost::shared_ptr< pdat::CellData< double > >()) const
double RMSNorm (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &cvol=boost::shared_ptr< pdat::CellData< double > >()) const
double weightedRMSNorm (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const boost::shared_ptr< pdat::CellData< dcomplex > > &weight, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &cvol=boost::shared_ptr< pdat::CellData< double > >()) const
double maxNorm (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &cvol=boost::shared_ptr< pdat::CellData< double > >()) const
dcomplex dot (const boost::shared_ptr< pdat::CellData< dcomplex > > &data1, const boost::shared_ptr< pdat::CellData< dcomplex > > &data2, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &cvol=boost::shared_ptr< pdat::CellData< double > >()) const
dcomplex integral (const boost::shared_ptr< pdat::CellData< dcomplex > > &data, const hier::Box &box, const boost::shared_ptr< pdat::CellData< double > > &vol) const
Detailed Description
Class PatchCellDataNormOpsComplex provides a collection of common norm operations that may be applied to complex cell-centered patch data. The primary intent of this class is to define part of the interface for the PatchCellDataOpsComplex class which provides access to operations that may be used to manipulate complex cell-centered patch data. Each member function accepts a box argument indicating the region of index space on which the operation should be performed. The operation will be performed on the intersection of this box and those boxes corresponding to the patch data objects. Also, each operation allows an additional cell-centered patch data object to be used to represent a control volume that weights the contribution of each data entry in the given norm calculation. Note that the control volume patch data must be of type double and have cell-centered geometry (i.e., the same as the data itself). The use of control volumes is important when these operations are used in vector kernels where the data resides over multiple levels of spatial resolution in an AMR hierarchy. If the control volume is not given in the function call, it will be ignored in the calculation. Also, note that the depth of the control volume patch data object must be either 1 or be equal to the depth of the other data objects.
Note that a similar set of norm operations is implemented for real patch data (double and float) in the class PatchCellDataNormOpsReal.
See also:
ArrayDataNormOpsComplex
Constructor & Destructor Documentation
SAMRAI::math::PatchCellDataNormOpsComplex::PatchCellDataNormOpsComplex ()
Empty constructor and destructor.
SAMRAI::math::PatchCellDataNormOpsComplex::~PatchCellDataNormOpsComplex () [virtual]
Member Function Documentation
size_t SAMRAI::math::PatchCellDataNormOpsComplex::numberOfEntries (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const hier::Box & box) const [inline]
Return the number of data values for the cell-centered data object in the given box.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::numberOfEntries(), RMSNorm(), and weightedRMSNorm().
double SAMRAI::math::PatchCellDataNormOpsComplex::sumControlVolumes (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const boost::shared_ptr< pdat::CellData< double > > & cvol, const hier::Box & box) const [inline]
Return sum of control volume entries for the cell-centered data object.
Precondition:
data && cvol
(data->getDim() == cvol->getDim() && (data->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by RMSNorm(), SAMRAI::math::HierarchyCellDataOpsComplex::sumControlVolumes(), and weightedRMSNorm().
void SAMRAI::math::PatchCellDataNormOpsComplex::abs (const boost::shared_ptr< pdat::CellData< double > > & dst, const boost::shared_ptr< pdat::CellData< dcomplex > > & src, const hier::Box & box) const [inline]
Set destination component to norm of source component. That is, each destination entry is set to .
Precondition:
dst && src
(dst->getDim() == src->getDim() && (dst->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::abs(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::abs().
double SAMRAI::math::PatchCellDataNormOpsComplex::L1Norm (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & cvol = boost::shared_ptr<pdat::CellData<double> >()) const
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::L1Norm().
double SAMRAI::math::PatchCellDataNormOpsComplex::L2Norm (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & cvol = boost::shared_ptr<pdat::CellData<double> >()) const
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::L2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L2NormWithControlVolume(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by RMSNorm().
double SAMRAI::math::PatchCellDataNormOpsComplex::weightedL2Norm (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const boost::shared_ptr< pdat::CellData< dcomplex > > & weight, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & cvol = boost::shared_ptr<pdat::CellData<double> >()) const
Return discrete weighted -norm of the data using the control volume to weight the contribution of the data and weight entries to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data && weight
(data->getDim() == weight->getDim()) && (data->getDim() == box.getDim())
!cvol || (data->getDim() == cvol->getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, TBOX_ASSERT_OBJDIM_EQUALITY3, SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::weightedL2Norm(), and weightedRMSNorm().
double SAMRAI::math::PatchCellDataNormOpsComplex::RMSNorm (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & cvol = boost::shared_ptr<pdat::CellData<double> >()) const
Return discrete root mean squared norm of the data. If the control volume is not NULL, the return value is the -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the -norm divided by the square root of the number of data entries.
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
References L2Norm(), numberOfEntries(), sumControlVolumes(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
double SAMRAI::math::PatchCellDataNormOpsComplex::weightedRMSNorm (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const boost::shared_ptr< pdat::CellData< dcomplex > > & weight, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & cvol = boost::shared_ptr<pdat::CellData<double> >()) const
Return discrete weighted root mean squared norm of the data. If the control volume is not NULL, the return value is the weighted -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the weighted -norm divided by the square root of the number of data entries.
Precondition:
data && weight
(data->getDim() == weight->getDim()) && (data->getDim() == box.getDim())
!cvol || (data->getDim() == cvol->getDim())
References numberOfEntries(), sumControlVolumes(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, TBOX_ASSERT_OBJDIM_EQUALITY3, and weightedL2Norm().
double SAMRAI::math::PatchCellDataNormOpsComplex::maxNorm (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & cvol = boost::shared_ptr<pdat::CellData<double> >()) const
Return the -norm of the data using the control volume to weight the contribution of each data entry to the maximum. That is, the return value is , where the max is over the data elements where . If the control volume is NULL, it is ignored during the computation of the maximum.
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::maxNorm().
dcomplex SAMRAI::math::PatchCellDataNormOpsComplex::dot (const boost::shared_ptr< pdat::CellData< dcomplex > > & data1, const boost::shared_ptr< pdat::CellData< dcomplex > > & data2, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & cvol = boost::shared_ptr<pdat::CellData<double> >()) const
Return the dot product of the two data arrays using the control volume to weight the contribution of each product to the sum. That is, the return value is the sum . If the control volume is NULL, it is ignored during the summation.
Precondition:
data1 && data2
(data1->getDim() == data2->getDim()) && (data1->getDim() == box.getDim())
!cvol || (data1->getDim() == cvol->getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::dot().
dcomplex SAMRAI::math::PatchCellDataNormOpsComplex::integral (const boost::shared_ptr< pdat::CellData< dcomplex > > & data, const hier::Box & box, const boost::shared_ptr< pdat::CellData< double > > & vol) const [inline]
Return the integral of the function represented by the data array. The return value is the sum .
Precondition:
data && vol
(data->getDim() == vol->getDim() && (data->getDim() == box.getDim())
References SAMRAI::math::ArrayDataNormOpsComplex::integral(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::HierarchyCellDataOpsComplex::integral().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchCellDataNormOpsComplex.h
source/SAMRAI/math/PatchCellDataNormOpsComplex.C