SAMRAI: SAMRAI::tbox::SAMRAI_MPI Class Reference
SAMRAI::tbox::SAMRAI_MPI Class Reference
Provides C++ wrapper around MPI routines.
#include <source/SAMRAI/tbox/SAMRAI_MPI.h>
Classes
struct Status
Dummy definition of Status to match the MPI standard.
Public Types
typedef int Comm
Aliases for MPI data type names.
typedef int Datatype
typedef int Group
typedef int Op
typedef int Request
Public Member Functions
SAMRAI_MPI (const Comm &comm)
Constructor.
SAMRAI_MPI (const SAMRAI_MPI &other)
Copy constructor.
int getRank () const
Get the local process rank from the last time the internal communicator was set.
int getSize () const
Get the size (number of processes) of the internal communicator the last time it was set.
const Comm & getCommunicator () const
Get the internal communicator.
void setCommunicator (const Comm &comm)
Set the internal communicator.
void dupCommunicator (const SAMRAI_MPI &other)
Duplicate and internally use the communicator of a given SAMRAI_MPI object.
void freeCommunicator ()
Free the internal communicator and set it to MPI_COMM_NULL.
int compareCommunicator (const SAMRAI_MPI &other) const
Compare with another SAMRAI_MPI's communicator.
bool hasNullCommunicator () const
Whether the communicator is MPI_COMM_NULL.
bool isCongruentWith (const SAMRAI_MPI &other) const
Whether the communicator is congruent with another's.
SAMRAI_MPI & operator= (const SAMRAI_MPI &rhs)
Assignment operator.
bool operator== (const SAMRAI_MPI &rhs) const
Equality comparison operator (compares MPI communicator).
bool operator!= (const SAMRAI_MPI &rhs) const
Inequality comparison operator (compares MPI communicator).
MPI wrappers bound to SAMRAI_MPI objects.
int Allgather (void *sendbuf, int sendcount, Datatype sendtype, void *recvbuf, int recvcount, Datatype recvtype) const
MPI wrappers for methods associated with an MPI communicator.
int Allgatherv (void *sendbuf, int sendcvount, Datatype sendtype, void *recvbuf, int *recvcounts, int *displs, Datatype recvtype) const
int Allreduce (void *sendbuf, void *recvbuf, int count, Datatype datatype, Op op) const
int Attr_get (int keyval, void *attribute_val, int *flag) const
int Barrier () const
MPI Barrier (does nothing when MPI is disabled).
int Bcast (void *buffer, int count, Datatype datatype, int root) const
MPI Bcast (does nothing when MPI is disabled).
int Comm_dup (Comm *newcomm) const
int Comm_rank (int *rank) const
MPI Comm_rank (Set rank to 0 when MPI is disabled).
int Comm_size (int *size) const
MPI Comm_size (Set size to 1 when MPI is disabled).
int Gather (void *sendbuf, int sendcount, Datatype sendtype, void *recvbuf, int recvcount, Datatype recvtype, int root) const
int Gatherv (void *sendbuf, int sendcount, Datatype sendtype, void *recvbuf, int *recvcounts, int *displs, Datatype recvtype, int root) const
int Iprobe (int source, int tag, int *flag, Status *status) const
int Isend (void *buf, int count, Datatype datatype, int dest, int tag, Request *req) const
int Irecv (void *buf, int count, Datatype datatype, int source, int tag, Request *request) const
int Probe (int source, int tag, Status *status) const
int Recv (void *buf, int count, Datatype datatype, int source, int tag, Status *status) const
int Reduce (void *sendbuf, void *recvbuf, int count, Datatype datatype, Op op, int root) const
int Send (void *buf, int count, Datatype datatype, int dest, int tag) const
int Sendrecv (void *sendbuf, int sendcount, Datatype sendtype, int dest, int sendtag, void *recvbuf, int recvcount, Datatype recvtype, int source, int recvtag, Status *status) const
int Scan (void *sendbuf, void *recvbuf, int count, Datatype datatype, Op op) const
Specialized reductions for certain common types.
int AllReduce (int *x, int count, Op op, int *ranks_of_extrema=0) const
Specialized Allreduce for integers.
int AllReduce (double *x, int count, Op op, int *ranks_of_extrema=0) const
Specialized Allreduce for doubles.
int AllReduce (float *x, int count, Op op, int *ranks_of_extrema=0) const
Specialized Allreduce for floats.
Generic high-level operations not in MPI interfaces.
int parallelPrefixSum (int *x, int count, int tag) const
Parallel prefix sum for integers.
bool hasReceivableMessage (Status *status=0, int source=MPI_ANY_SOURCE, int tag=MPI_ANY_TAG) const
Check whether there a message waiting to be received.
Static Public Member Functions
static const SAMRAI_MPI & getSAMRAIWorld ()
Get the primary SAMRAI_MPI object owned by SAMRAI.
static int getInvalidRank ()
Get a static invalid rank number.
static void setCallAbortInSerialInsteadOfExit (bool flag=true)
Set flag indicating whether exit or MPI_Abort is called when running with one processor.
static void setCallAbortInParallelInsteadOfMPIAbort (bool flag=true)
Set flag indicating whether MPI_Abort or abort is called when running with more than one processor.
static void abort ()
Call MPI_Abort or exit depending on whether running with one or more processes and value set by function above, if called.
static void disableMPI ()
Disable MPI usage and run in sequential mode.
static bool usingMPI ()
Whether SAMRAI is using MPI (configured, compiled and initialized).
static void init (int *argc, char **argv[])
Initialize MPI and SAMRAI_MPI.
static void init (Comm comm)
Initialize SAMRAI_MPI when MPI is already initialized.
static void initMPIDisabled ()
Initialize SAMRAI_MPI to work without MPI.
static void finalize ()
Shut down SAMRAI_MPI and, if appropriate, shut down MPI.
Static MPI wrappers matching MPI interfaces.
static int Comm_rank (Comm comm, int *rank)
MPI wrappers that don't use the internal communicator.
static int Comm_size (Comm comm, int *size)
static int Comm_compare (Comm comm1, Comm comm2, int *result)
static int Comm_free (Comm *comm)
static int Finalized (int *flag)
static int Get_count (Status *status, Datatype datatype, int *count)
static int Request_free (Request *request)
static int Test (Request *request, int *flag, Status *status)
static int Test_cancelled (Status *status, int *flag)
static int Wait (Request *request, Status *status)
static int Waitall (int count, Request *reqs, Status *stats)
static int Waitany (int count, Request *array_of_requests, int *index, Status *status)
static int Waitsome (int incount, Request *array_of_requests, int *outcount, int *array_of_indices, Status *array_of_statuses)
static double Wtime ()
MPI Wtime (if MPI is enabled) or an alternate time calculation.
Static Public Attributes
static const Comm commWorld = MPI_COMM_WORLD
static const Comm commNull = MPI_COMM_NULL
Detailed Description
Provides C++ wrapper around MPI routines.
SAMRAI_MPI provides a single point of access in SAMRAI for using MPI function calls and for the run-time decision whether to use MPI. The purpose of having a single point is to facilitate writing code that is not cluttered by the repetitive logic absorbed into this class. Codes accessing MPI through this class should work whether SAMRAI is configured with or without MPI and whether MPI is enabled at run time.
This class provides two sets of interfaces:
Methods closely matching the MPI interfaces associated with a communicator. The communicator is set during object construction and is removed from the argument list of the MPI-like interfaces.
Static methods exactly matching the MPI interfaces not associated with any specific communicator.
If SAMRAI has MPI enabled, the MPI wrappers in this class delegate to the real MPI methods. Otherwise, they are no-ops and will throw an assertion if used, except for those specifically identified as able to work without MPI enabled. The purpose of these interfaces are strictly to check whether MPI was configured into SAMRAI and SAMRAI is using MPI at run time. They are not "single-process implementations" of the MPI standard.
This class also manages a central SAMRAI_MPI object meant for SAMRAI's general use. See getSAMRAIWorld() and init().
Member Typedef Documentation
typedef int SAMRAI::tbox::SAMRAI_MPI::Comm
Aliases for MPI data type names.
Define aliases for MPI types that can be used whether SAMRAI is configured with or without MPI. Without MPI, these types are "dummies", used to allow the code to be compiled without changes.
typedef int SAMRAI::tbox::SAMRAI_MPI::Datatype
typedef int SAMRAI::tbox::SAMRAI_MPI::Group
typedef int SAMRAI::tbox::SAMRAI_MPI::Op
typedef int SAMRAI::tbox::SAMRAI_MPI::Request
Constructor & Destructor Documentation
SAMRAI::tbox::SAMRAI_MPI::SAMRAI_MPI (const Comm & comm) [explicit]
Constructor.
The given MPI communicator will be used for all communications invoked by this object.
Note that the object will NOT automatically free the communicator. To manually free the communicator, use freeCommunicator().
If the specified communicator is MPI_COMM_NULL, the rank (see getRank()) and size (see getSize()) are set to invalid values. Otherwise, the rank and size are set using the given communicator. If MPI is enabled but MPI has not been initialized, the rank and size are set to invalid values. If MPI is not enabled, the rank is set to 0 and size to 1.
Parameters:
[in] comm
References MPI_COMM_NULL.
SAMRAI::tbox::SAMRAI_MPI::SAMRAI_MPI (const SAMRAI_MPI & other)
Copy constructor.
Member Function Documentation
static const SAMRAI_MPI& SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld () [inline, static]
Get the primary SAMRAI_MPI object owned by SAMRAI.
This is SAMRAI's primary communication object set up when SAMRAI_MPI is initialized. It is used for basic communications that are not associated with another communication object. Various parts of the SAMRAI library may create and use (and destroy) communicators that are derived from this object.
The use of this object outside of the SAMRAI library should be carefully limited to avoid mixing messages.
After SAMRAI_MPI::init() and before SAMRAI_MPI::finalize(), the object returned is useable. Otherwise it is intentionally invalid.
See also:
init()
Referenced by abort(), SAMRAI::tbox::Timer::barrierAndStart(), SAMRAI::tbox::Timer::barrierAndStop(), SAMRAI::tbox::Statistician::checkStatsForConsistency(), SAMRAI::tbox::Timer::computeLoadBalanceEfficiency(), SAMRAI::tbox::Timer::computeMaxWallclock(), SAMRAI::tbox::Statistician::finalize(), SAMRAI::tbox::Statistician::getGlobalPatchStatMax(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProcId(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchId(), SAMRAI::tbox::Statistician::getGlobalPatchStatMin(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProcId(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchId(), SAMRAI::tbox::Statistician::getGlobalPatchStatNumberPatches(), SAMRAI::tbox::Statistician::getGlobalPatchStatNumberPatchesOnProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatPatchMapping(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSum(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMax(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMaxId(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMin(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMinId(), SAMRAI::tbox::Statistician::getGlobalPatchStatSequenceLength(), SAMRAI::tbox::Statistician::getGlobalPatchStatSum(), SAMRAI::tbox::Statistician::getGlobalPatchStatValue(), SAMRAI::tbox::Statistician::getGlobalProcStatMax(), SAMRAI::tbox::Statistician::getGlobalProcStatMaxProcessorId(), SAMRAI::tbox::Statistician::getGlobalProcStatMin(), SAMRAI::tbox::Statistician::getGlobalProcStatMinProcessorId(), SAMRAI::tbox::Statistician::getGlobalProcStatSequenceLength(), SAMRAI::tbox::Statistician::getGlobalProcStatSum(), SAMRAI::tbox::Statistician::getGlobalProcStatValue(), SAMRAI::tbox::PIO::initialize(), SAMRAI::tbox::RestartManager::openRestartFile(), SAMRAI::tbox::Statistic::packStream(), SAMRAI::tbox::InputManager::parseInputFile(), SAMRAI::hier::PatchHierarchy::PatchHierarchy(), SAMRAI::tbox::TimerManager::print(), SAMRAI::tbox::Statistician::printAllGlobalStatData(), SAMRAI::tbox::Statistician::printAllSummedGlobalStatData(), SAMRAI::tbox::Statistic::printClassData(), SAMRAI::tbox::Statistician::printGlobalPatchStatData(), SAMRAI::tbox::Statistician::printGlobalPatchStatDataFormatted(), SAMRAI::tbox::Statistician::printGlobalProcStatData(), SAMRAI::tbox::Statistician::printGlobalProcStatDataFormatted(), SAMRAI::tbox::MemoryUtilities::printMaxMemory(), SAMRAI::tbox::Statistician::printSpreadSheetOutput(), SAMRAI::tbox::Statistician::printSpreadSheetOutputForProcessor(), SAMRAI::mesh::TreeLoadBalancer::printStatistics(), SAMRAI::mesh::ChopAndPackLoadBalancer::printStatistics(), SAMRAI::mesh::CascadePartitioner::printStatistics(), SAMRAI::hier::BoxTree::printStatistics(), SAMRAI::hier::ProcessorMapping::ProcessorMapping(), SAMRAI::tbox::Parser::pushIncludeFile(), SAMRAI::tbox::Utilities::recursiveMkdir(), SAMRAI::tbox::Statistic::unpackStream(), SAMRAI::appu::VisItDataWriter::VisItDataWriter(), SAMRAI::tbox::RestartManager::writeRestartFile(), and SAMRAI::tbox::Parser::yyinput().
static int SAMRAI::tbox::SAMRAI_MPI::getInvalidRank () [inline, static]
Get a static invalid rank number.
This value is intended to be used by other classes as an invalid rank number rather than using a hard-coded "magic" negative integer value.
Referenced by SAMRAI::xfer::RefineTimeTransaction::copyLocalData(), SAMRAI::hier::AssumedPartitionBox::getOwner(), SAMRAI::hier::AssumedPartition::getOwner(), SAMRAI::hier::BoxId::isValid(), SAMRAI::xfer::RefineTimeTransaction::packStream(), and SAMRAI::hier::AssumedPartitionBox::selfCheck().
int SAMRAI::tbox::SAMRAI_MPI::getRank () const [inline]
Get the local process rank from the last time the internal communicator was set.
Referenced by SAMRAI::hier::BoxLevel::addBox(), SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::tbox::Schedule::addTransaction(), SAMRAI::tbox::Schedule::appendTransaction(), SAMRAI::hier::Connector::assertOverlapCorrectness(), SAMRAI::mesh::BoxTransitSet::assignToLocal(), SAMRAI::tbox::CenteredRankTree::CenteredRankTree(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::Connector::doTransposeWork(), SAMRAI::hier::Connector::eraseLocalNeighborhood(), SAMRAI::hier::Connector::eraseNeighbor(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::tbox::Statistician::finalize(), SAMRAI::hier::BoxLevel::finalize(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::BoxLevel::getBoxStrict(), SAMRAI::tbox::Statistician::getGlobalPatchStatMax(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProcId(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchId(), SAMRAI::tbox::Statistician::getGlobalPatchStatMin(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProcId(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchId(), SAMRAI::tbox::Statistician::getGlobalPatchStatNumberPatches(), SAMRAI::tbox::Statistician::getGlobalPatchStatNumberPatchesOnProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatPatchMapping(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSum(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMax(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMaxId(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMin(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMinId(), SAMRAI::tbox::Statistician::getGlobalPatchStatSequenceLength(), SAMRAI::tbox::Statistician::getGlobalPatchStatSum(), SAMRAI::tbox::Statistician::getGlobalPatchStatValue(), SAMRAI::tbox::Statistician::getGlobalProcStatMax(), SAMRAI::tbox::Statistician::getGlobalProcStatMaxProcessorId(), SAMRAI::tbox::Statistician::getGlobalProcStatMin(), SAMRAI::tbox::Statistician::getGlobalProcStatMinProcessorId(), SAMRAI::tbox::Statistician::getGlobalProcStatSequenceLength(), SAMRAI::tbox::Statistician::getGlobalProcStatSum(), SAMRAI::tbox::Statistician::getGlobalProcStatValue(), SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes(), SAMRAI::hier::BoxLevel::getLocalNumberOfCells(), SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::hier::Connector::hasLocalNeighbor(), SAMRAI::hier::Connector::insertLocalNeighbor(), SAMRAI::hier::Connector::insertNeighbors(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::Connector::makeEmptyLocalNeighborhood(), SAMRAI::tbox::RestartManager::openRestartFile(), SAMRAI::tbox::Statistic::packStream(), SAMRAI::tbox::InputManager::parseInputFile(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::tbox::TimerManager::print(), SAMRAI::tbox::Statistician::printAllGlobalStatData(), SAMRAI::tbox::Statistician::printAllSummedGlobalStatData(), SAMRAI::tbox::Statistic::printClassData(), SAMRAI::tbox::Statistician::printGlobalPatchStatData(), SAMRAI::tbox::Statistician::printGlobalPatchStatDataFormatted(), SAMRAI::tbox::Statistician::printGlobalProcStatData(), SAMRAI::tbox::Statistician::printGlobalProcStatDataFormatted(), SAMRAI::tbox::MemoryUtilities::printMaxMemory(), SAMRAI::tbox::Statistician::printSpreadSheetOutput(), SAMRAI::tbox::Statistician::printSpreadSheetOutputForProcessor(), SAMRAI::hier::ProcessorMapping::ProcessorMapping(), SAMRAI::tbox::Parser::pushIncludeFile(), SAMRAI::mesh::BoxTransitSet::putInBoxLevel(), SAMRAI::hier::BoxLevel::putToRestart(), SAMRAI::tbox::Utilities::recursiveMkdir(), SAMRAI::hier::Connector::recursivePrint(), SAMRAI::hier::BoxLevel::recursivePrint(), SAMRAI::tbox::AsyncCommGroup::setGroupAndRootIndex(), SAMRAI::tbox::Statistic::unpackStream(), SAMRAI::tbox::RestartManager::writeRestartFile(), and SAMRAI::tbox::Parser::yyinput().
int SAMRAI::tbox::SAMRAI_MPI::getSize () const [inline]
Get the size (number of processes) of the internal communicator the last time it was set.
Referenced by abort(), SAMRAI::hier::Connector::assertOverlapCorrectness(), SAMRAI::tbox::AsyncCommGroup::beginBcast(), SAMRAI::tbox::AsyncCommGroup::beginGather(), SAMRAI::hier::Connector::cacheGlobalReducedData(), SAMRAI::hier::BoxLevel::cacheGlobalReducedData(), SAMRAI::tbox::CenteredRankTree::CenteredRankTree(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::tbox::Timer::computeLoadBalanceEfficiency(), SAMRAI::tbox::Timer::computeMaxWallclock(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::mesh::CascadePartitionerTree::distributeLoad(), SAMRAI::tbox::Statistician::finalize(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatMaxPatchesPerProcId(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatMinPatchesPerProcId(), SAMRAI::tbox::Statistician::getGlobalPatchStatNumberPatchesOnProc(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSum(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMax(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMaxId(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMin(), SAMRAI::tbox::Statistician::getGlobalPatchStatProcessorSumMinId(), SAMRAI::tbox::Statistician::getGlobalProcStatValue(), SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes(), SAMRAI::hier::BoxLevel::getLocalNumberOfCells(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::hier::BoxLevelStatistics::printBoxStats(), SAMRAI::mesh::CascadePartitionerTree::printClassData(), SAMRAI::tbox::Statistician::printGlobalProcStatData(), SAMRAI::tbox::Statistician::printGlobalProcStatDataFormatted(), SAMRAI::tbox::MemoryUtilities::printMaxMemory(), SAMRAI::hier::ConnectorStatistics::printNeighborStats(), SAMRAI::hier::BoxTree::printStatistics(), SAMRAI::hier::ProcessorMapping::ProcessorMapping(), SAMRAI::hier::BoxLevel::putToRestart(), SAMRAI::hier::Connector::recursivePrint(), SAMRAI::hier::BoxLevel::recursivePrint(), SAMRAI::mesh::BalanceUtilities::reduceAndReportLoadBalance(), and SAMRAI::tbox::AsyncCommGroup::setGroupAndRootIndex().
const Comm& SAMRAI::tbox::SAMRAI_MPI::getCommunicator () const [inline]
Get the internal communicator.
Referenced by abort(), SAMRAI::tbox::AsyncCommGroup::beginBcast(), SAMRAI::tbox::AsyncCommGroup::beginGather(), SAMRAI::tbox::AsyncCommPeer< TYPE >::beginRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::beginSend(), SAMRAI::tbox::AsyncCommGroup::beginSumReduce(), SAMRAI::tbox::AsyncCommGroup::checkBcast(), SAMRAI::tbox::AsyncCommGroup::checkGather(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation(), SAMRAI::tbox::AsyncCommGroup::completeCurrentOperation(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), SAMRAI::mesh::TreeLoadBalancer::freeMPICommunicator(), SAMRAI::mesh::CascadePartitioner::freeMPICommunicator(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::tbox::AsyncCommPeer< TYPE >::logCurrentState(), SAMRAI::tbox::AsyncCommGroup::logCurrentState(), SAMRAI::tbox::AsyncCommPeer< TYPE >::proceedToNextWait(), SAMRAI::tbox::AsyncCommGroup::proceedToNextWait(), SAMRAI::hier::BoxLevel::recursivePrint(), SAMRAI::tbox::AsyncCommGroup::setGroupAndRootIndex(), SAMRAI::tbox::AsyncCommGroup::setGroupAndRootRank(), SAMRAI::mesh::TreeLoadBalancer::setSAMRAI_MPI(), SAMRAI::mesh::CascadePartitioner::setSAMRAI_MPI(), SAMRAI::mesh::BergerRigoutsos::useDuplicateMPI(), SAMRAI::tbox::AsyncCommGroup::~AsyncCommGroup(), SAMRAI::tbox::AsyncCommPeer< TYPE >::~AsyncCommPeer(), and SAMRAI::mesh::BergerRigoutsos::~BergerRigoutsos().
void SAMRAI::tbox::SAMRAI_MPI::setCommunicator (const Comm & comm)
Set the internal communicator.
Note that this call does does automatically free the existing communicator. To manually free communicators, see freeCommunicator().
Parameters:
[in] comm
References MPI_COMM_NULL.
Referenced by SAMRAI::hier::Connector::clear(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), SAMRAI::mesh::TreeLoadBalancer::freeMPICommunicator(), SAMRAI::mesh::CascadePartitioner::freeMPICommunicator(), and init().
void SAMRAI::tbox::SAMRAI_MPI::dupCommunicator (const SAMRAI_MPI & other)
Duplicate and internally use the communicator of a given SAMRAI_MPI object.
Note that this call does not automatically free the existing communicator. The duplicate communicator will also NOT be automatically freed. To manually free communicators, see freeCommunicator().
If SAMRAI isn't configured with MPI, the duplicate is an identical copy.
Parameters:
[in] other Contains the communicator to be duplicated.
References Comm_dup(), MPI_SUCCESS, TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::mesh::TreeLoadBalancer::setSAMRAI_MPI(), SAMRAI::mesh::CascadePartitioner::setSAMRAI_MPI(), SAMRAI::hier::OverlapConnectorAlgorithm::setSAMRAI_MPI(), SAMRAI::hier::MappingConnectorAlgorithm::setSAMRAI_MPI(), SAMRAI::mesh::BergerRigoutsos::useDuplicateMPI(), and SAMRAI::appu::VisItDataWriter::VisItDataWriter().
void SAMRAI::tbox::SAMRAI_MPI::freeCommunicator ()
Free the internal communicator and set it to MPI_COMM_NULL.
If the internal communicator is already MPI_COMM_NULL, do nothing.
References Comm_free(), MPI_COMM_NULL, TBOX_ASSERT, and usingMPI().
Referenced by SAMRAI::mesh::TreeLoadBalancer::freeMPICommunicator(), SAMRAI::mesh::CascadePartitioner::freeMPICommunicator(), SAMRAI::mesh::TreeLoadBalancer::setSAMRAI_MPI(), SAMRAI::mesh::CascadePartitioner::setSAMRAI_MPI(), SAMRAI::hier::OverlapConnectorAlgorithm::setSAMRAI_MPI(), SAMRAI::hier::MappingConnectorAlgorithm::setSAMRAI_MPI(), SAMRAI::mesh::BergerRigoutsos::useDuplicateMPI(), SAMRAI::mesh::BergerRigoutsos::~BergerRigoutsos(), SAMRAI::hier::MappingConnectorAlgorithm::~MappingConnectorAlgorithm(), SAMRAI::hier::OverlapConnectorAlgorithm::~OverlapConnectorAlgorithm(), and SAMRAI::appu::VisItDataWriter::~VisItDataWriter().
int SAMRAI::tbox::SAMRAI_MPI::compareCommunicator (const SAMRAI_MPI & other) const
Compare with another SAMRAI_MPI's communicator.
If MPI is enabled, compare using Comm_compare, and return the result. Otherwise, return MPI_IDENT if the two communicators are the same and MPI_CONGRUENT if they are not. (No other choice makes sense when MPI is disabled.)
Performance of this method depends on underlying MPI implementation and may not scale.
References Comm_compare(), MPI_CONGRUENT, MPI_IDENT, MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by isCongruentWith().
bool SAMRAI::tbox::SAMRAI_MPI::hasNullCommunicator () const [inline]
Whether the communicator is MPI_COMM_NULL.
References MPI_COMM_NULL.
Referenced by SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), and SAMRAI::hier::MappingConnectorAlgorithm::modify().
bool SAMRAI::tbox::SAMRAI_MPI::isCongruentWith (const SAMRAI_MPI & other) const [inline]
Whether the communicator is congruent with another's.
Performance of this method depends on underlying MPI implementation and may not scale.
References compareCommunicator(), MPI_COMM_NULL, MPI_CONGRUENT, and MPI_IDENT.
Referenced by SAMRAI::hier::Connector::finalizeContext(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), and SAMRAI::hier::MappingConnectorAlgorithm::modify().
SAMRAI_MPI& SAMRAI::tbox::SAMRAI_MPI::operator= (const SAMRAI_MPI & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs
bool SAMRAI::tbox::SAMRAI_MPI::operator== (const SAMRAI_MPI & rhs) const [inline]
Equality comparison operator (compares MPI communicator).
Parameters:
[in] rhs
bool SAMRAI::tbox::SAMRAI_MPI::operator!= (const SAMRAI_MPI & rhs) const [inline]
Inequality comparison operator (compares MPI communicator).
Parameters:
[in] rhs
int SAMRAI::tbox::SAMRAI_MPI::Comm_rank (Comm comm, int * rank) [static]
MPI wrappers that don't use the internal communicator.
The purpose of these wrappers is to provide a single place for compile- and run-time toggling of MPI code. The signatures and return values of these methods are identical to the MPI C bindings. These methods will throw an assertion if they are called when MPI is not enabled.
Precondition:
s_mpi_is_initialized
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::PIO::initialize().
int SAMRAI::tbox::SAMRAI_MPI::Comm_size (Comm comm, int * size) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::RankGroup::getMapIndex(), SAMRAI::tbox::RankGroup::RankGroup(), and SAMRAI::tbox::RankGroup::size().
int SAMRAI::tbox::SAMRAI_MPI::Comm_compare (Comm comm1, Comm comm2, int * result) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by compareCommunicator().
int SAMRAI::tbox::SAMRAI_MPI::Comm_free (Comm * comm) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by freeCommunicator().
int SAMRAI::tbox::SAMRAI_MPI::Finalized (int * flag) [static]
References MPI_SUCCESS.
Referenced by SAMRAI::mesh::TreeLoadBalancer::freeMPICommunicator(), SAMRAI::mesh::CascadePartitioner::freeMPICommunicator(), and SAMRAI::mesh::BergerRigoutsos::~BergerRigoutsos().
int SAMRAI::tbox::SAMRAI_MPI::Get_count (Status * status, Datatype datatype, int * count) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommGroup::checkBcast(), SAMRAI::tbox::AsyncCommGroup::checkGather(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), and SAMRAI::hier::Connector::computeTransposeOf().
int SAMRAI::tbox::SAMRAI_MPI::Request_free (Request * request) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Test (Request * request, int * flag, Status * status) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommGroup::checkBcast(), SAMRAI::tbox::AsyncCommGroup::checkGather(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend().
int SAMRAI::tbox::SAMRAI_MPI::Test_cancelled (Status * status, int * flag) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Wait (Request * request, Status * status) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by parallelPrefixSum().
int SAMRAI::tbox::SAMRAI_MPI::Waitall (int count, Request * reqs, Status * stats) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation(), SAMRAI::tbox::AsyncCommGroup::completeCurrentOperation(), and SAMRAI::hier::Connector::computeTransposeOf().
int SAMRAI::tbox::SAMRAI_MPI::Waitany (int count, Request * array_of_requests, int * index, Status * status) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommStage::advanceAny().
int SAMRAI::tbox::SAMRAI_MPI::Waitsome (int incount, Request * array_of_requests, int * outcount, int * array_of_indices, Status * array_of_statuses) [static]
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommStage::advanceSome().
double SAMRAI::tbox::SAMRAI_MPI::Wtime () [static]
MPI Wtime (if MPI is enabled) or an alternate time calculation.
Returns:
If MPI is running, use Wtime. If not, but POSIX time is available, use that. Else return 0.0.
Referenced by SAMRAI::tbox::Clock::timestamp().
int SAMRAI::tbox::SAMRAI_MPI::Allgather (void * sendbuf, int sendcount, Datatype sendtype, void * recvbuf, int recvcount, Datatype recvtype) const
MPI wrappers for methods associated with an MPI communicator.
The purpose of these wrappers is to provide a single place for compile- and run-time toggling of MPI code. The signatures and return values of these methods are identical to the MPI C bindings, except that the communicators are omitted. The communicator used is that associated with the SAMRAI_MPI object (typically passed to the constructor). These methods throw an assertion if called while MPI is not enabled, except where noted.
Precondition:
s_mpi_is_initialized
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Allgatherv (void * sendbuf, int sendcvount, Datatype sendtype, void * recvbuf, int * recvcounts, int * displs, Datatype recvtype) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Allreduce (void * sendbuf, void * recvbuf, int count, Datatype datatype, Op op) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by AllReduce(), SAMRAI::hier::Connector::assertOverlapCorrectness(), SAMRAI::hier::Connector::cacheGlobalReducedData(), SAMRAI::hier::BoxLevel::cacheGlobalReducedData(), SAMRAI::tbox::Timer::computeLoadBalanceEfficiency(), SAMRAI::tbox::Timer::computeMaxWallclock(), SAMRAI::hier::MappingConnector::findMappingErrors(), and SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel().
int SAMRAI::tbox::SAMRAI_MPI::Attr_get (int keyval, void * attribute_val, int * flag) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Barrier () const
MPI Barrier (does nothing when MPI is disabled).
References MPI_SUCCESS.
Referenced by SAMRAI::tbox::Timer::barrierAndStart(), SAMRAI::tbox::Timer::barrierAndStop(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), hasReceivableMessage(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::tbox::Utilities::recursiveMkdir().
int SAMRAI::tbox::SAMRAI_MPI::Bcast (void * buffer, int count, Datatype datatype, int root) const
MPI Bcast (does nothing when MPI is disabled).
References MPI_SUCCESS, and NULL_USE.
Referenced by SAMRAI::tbox::InputManager::parseInputFile(), SAMRAI::tbox::Parser::pushIncludeFile(), and SAMRAI::tbox::Parser::yyinput().
int SAMRAI::tbox::SAMRAI_MPI::Comm_dup (Comm * newcomm) const
References commNull, MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by dupCommunicator().
int SAMRAI::tbox::SAMRAI_MPI::Comm_rank (int * rank) const
MPI Comm_rank (Set rank to 0 when MPI is disabled).
References MPI_SUCCESS, and NULL_USE.
int SAMRAI::tbox::SAMRAI_MPI::Comm_size (int * size) const
MPI Comm_size (Set size to 1 when MPI is disabled).
References MPI_SUCCESS, and NULL_USE.
int SAMRAI::tbox::SAMRAI_MPI::Gather (void * sendbuf, int sendcount, Datatype sendtype, void * recvbuf, int recvcount, Datatype recvtype, int root) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Gatherv (void * sendbuf, int sendcount, Datatype sendtype, void * recvbuf, int * recvcounts, int * displs, Datatype recvtype, int root) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Iprobe (int source, int tag, int * flag, Status * status) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by hasReceivableMessage().
int SAMRAI::tbox::SAMRAI_MPI::Isend (void * buf, int count, Datatype datatype, int dest, int tag, Request * req) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommGroup::checkBcast(), SAMRAI::tbox::AsyncCommGroup::checkGather(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::hier::Connector::computeTransposeOf(), and parallelPrefixSum().
int SAMRAI::tbox::SAMRAI_MPI::Irecv (void * buf, int count, Datatype datatype, int source, int tag, Request * request) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommGroup::checkBcast(), SAMRAI::tbox::AsyncCommGroup::checkGather(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), and parallelPrefixSum().
int SAMRAI::tbox::SAMRAI_MPI::Probe (int source, int tag, Status * status) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::hier::Connector::computeTransposeOf().
int SAMRAI::tbox::SAMRAI_MPI::Recv (void * buf, int count, Datatype datatype, int source, int tag, Status * status) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::hier::Connector::computeTransposeOf(), and SAMRAI::tbox::MemoryUtilities::printMaxMemory().
int SAMRAI::tbox::SAMRAI_MPI::Reduce (void * sendbuf, void * recvbuf, int count, Datatype datatype, Op op, int root) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Send (void * buf, int count, Datatype datatype, int dest, int tag) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommGroup::checkBcast(), SAMRAI::tbox::AsyncCommGroup::checkGather(), and SAMRAI::tbox::MemoryUtilities::printMaxMemory().
int SAMRAI::tbox::SAMRAI_MPI::Sendrecv (void * sendbuf, int sendcount, Datatype sendtype, int dest, int sendtag, void * recvbuf, int recvcount, Datatype recvtype, int source, int recvtag, Status * status) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::Scan (void * sendbuf, void * recvbuf, int count, Datatype datatype, Op op) const
References MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap().
int SAMRAI::tbox::SAMRAI_MPI::AllReduce (int * x, int count, Op op, int * ranks_of_extrema = 0) const
Specialized Allreduce for integers.
If MPI_MINLOC or MPI_MAXLOC is given as the operator, the ranks_of_extrema argument must be provided with space allocated for count integers.
Returns:
MPI error code
Parameters:
[in,out] x Array of integers to reduce.
[in] count Number of items in x.
[in] op A valid MPI reduce operation.
[out] ranks_of_extrema Ranks associated with min or max of x (if op indicates min or max operation).
Precondition:
(op != MPI_MINLOC && op != MPI_MAXLOC) || (ranks_of_extrema != 0)
s_mpi_is_initialized
References Allreduce(), MPI_2INT, MPI_INT, MPI_MAX, MPI_MAXLOC, MPI_MIN, MPI_MINLOC, MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
Referenced by SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxTree::printStatistics(), and SAMRAI::mesh::BalanceUtilities::reduceAndReportLoadBalance().
int SAMRAI::tbox::SAMRAI_MPI::AllReduce (double * x, int count, Op op, int * ranks_of_extrema = 0) const
Specialized Allreduce for doubles.
If MPI_MINLOC or MPI_MAXLOC is given as the operator, the ranks_of_extrema argument must be provided with space allocated for count integers.
Parameters:
[in,out] x Array of doubles to reduce.
[in] count Number of items in x.
[in] op A valid MPI reduce operation.
[out] ranks_of_extrema Ranks associated with min or max of x (if op indicates min or max operation).
Precondition:
(op != MPI_MINLOC && op != MPI_MAXLOC) || (ranks_of_extrema != 0)
s_mpi_is_initialized
References Allreduce(), MPI_DOUBLE, MPI_DOUBLE_INT, MPI_MAX, MPI_MAXLOC, MPI_MIN, MPI_MINLOC, MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::AllReduce (float * x, int count, Op op, int * ranks_of_extrema = 0) const
Specialized Allreduce for floats.
If MPI_MINLOC or MPI_MAXLOC is given as the operator, the ranks_of_extrema argument must be provided with space allocated for count integers.
Parameters:
[in,out] x Array of floats to reduce.
[in] count Number of items in x.
[in] op A valid MPI reduce operation.
[out] ranks_of_extrema Ranks associated with min or max of x (if op indicates min or max operation).
Precondition:
(op != MPI_MINLOC && op != MPI_MAXLOC) || (ranks_of_extrema != 0)
s_mpi_is_initialized
References Allreduce(), MPI_FLOAT, MPI_FLOAT_INT, MPI_MAX, MPI_MAXLOC, MPI_MIN, MPI_MINLOC, MPI_SUCCESS, NULL_USE, and TBOX_ERROR.
int SAMRAI::tbox::SAMRAI_MPI::parallelPrefixSum (int * x, int count, int tag) const
Parallel prefix sum for integers.
Given an input x, the output is the sum of x from process 0 up to and including the local process's x. This implementation allows an array of x, each of which is summed independently of the other.
Parameters:
[in,out] x Array of integers to sum.
[in] count Number of items in x. Must be the same on all processes.
[in] tag MPI tag for communication.
Returns:
MPI_SUCCESS or an MPI error code.
References Irecv(), Isend(), MPI_INT, MPI_SUCCESS, NULL_USE, and Wait().
bool SAMRAI::tbox::SAMRAI_MPI::hasReceivableMessage (Status * status = 0, int source = MPI_ANY_SOURCE, int tag = MPI_ANY_TAG) const
Check whether there a message waiting to be received.
This is a convenience (non-essential) interface for use in debugging communication code. It checks whether there are any waiting to be received. It uses a non-blocking check; a false doesn't mean no messages are coming; it means no messages have arrived. The checking includes barriers, making this a collective operation.
Parameters:
[in,out] status
[in] source
[in] tag
Returns:
Whether any messages matching the source and tag are waiting to be received.
References Barrier(), Iprobe(), MPI_SUCCESS, and TBOX_ERROR.
Referenced by SAMRAI::tbox::Schedule::communicate(), SAMRAI::hier::Connector::computeTransposeOf(), and SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition().
static void SAMRAI::tbox::SAMRAI_MPI::setCallAbortInSerialInsteadOfExit (bool flag = true) [inline, static]
Set flag indicating whether exit or MPI_Abort is called when running with one processor.
Calling this function influences the behavior of calls to SAMRAI_MPI::abort(). If the value set is true, it means that system abort() will be called. Passing false means exit(-1) will be called.
Referenced by init(), and initMPIDisabled().
static void SAMRAI::tbox::SAMRAI_MPI::setCallAbortInParallelInsteadOfMPIAbort (bool flag = true) [inline, static]
Set flag indicating whether MPI_Abort or abort is called when running with more than one processor.
Calling this function influences the behavior of calls to SAMRAI_MPI::abort(). If the value set is true, it means that system abort() will be called. Passing false means MPI_Abort will be called.
Referenced by init(), and initMPIDisabled().
void SAMRAI::tbox::SAMRAI_MPI::abort () [static]
Call MPI_Abort or exit depending on whether running with one or more processes and value set by function above, if called.
The default is to call exit(-1) if running with one processor and to call MPI_Abort() otherwise. This function avoids having to guard abort calls in application code.
References getCommunicator(), getSAMRAIWorld(), and getSize().
static void SAMRAI::tbox::SAMRAI_MPI::disableMPI () [static]
Disable MPI usage and run in sequential mode.
The default setting is to enable MPI at run-time if SAMRAI was configured with MPI and to disable if SAMRAI was not configured with MPI. This method disables MPI in the former case.
If MPI is disabled for SAMRAI, the communication interfaces in this class are no-ops and will throw an assertion if used, except for those interfaces specifically described as working in sequential mode.
Disabling MPI must be done before calling SAMRAI_MPI::init().
static bool SAMRAI::tbox::SAMRAI_MPI::usingMPI () [inline, static]
Whether SAMRAI is using MPI (configured, compiled and initialized).
See also:
disableMPI().
Referenced by SAMRAI::tbox::AsyncCommStage::advanceAny(), SAMRAI::tbox::AsyncCommStage::advanceSome(), freeCommunicator(), and SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap().
void SAMRAI::tbox::SAMRAI_MPI::init (int * argc, char ** argv[]) [static]
Initialize MPI and SAMRAI_MPI.
This initialization sets up getSAMRAIWorld() to return an SAMRAI_MPI object with a communicator duplicated from MPI_COMM_WORLD.
Use only one of the three initialization methods.
Parameters:
[in] argc Pointer to parameter from main()
[in] argv Pointer to parameter from main()
References MPI_COMM_WORLD, NULL_USE, setCallAbortInParallelInsteadOfMPIAbort(), setCallAbortInSerialInsteadOfExit(), and setCommunicator().
void SAMRAI::tbox::SAMRAI_MPI::init (Comm comm) [static]
Initialize SAMRAI_MPI when MPI is already initialized.
This initialization sets up getSAMRAIWorld() to return an SAMRAI_MPI object with a communicator duplicated from the one passed in.
Use only one of the three initialization methods.
Parameters:
comm An MPI Communicator to be duplicated for SAMRAI use.
References MPI_COMM_NULL, setCallAbortInParallelInsteadOfMPIAbort(), setCallAbortInSerialInsteadOfExit(), and setCommunicator().
void SAMRAI::tbox::SAMRAI_MPI::initMPIDisabled () [static]
Initialize SAMRAI_MPI to work without MPI.
This initialization sets up SAMRAI to run in sequential mode.
Use only one of the three initialization methods.
References MPI_COMM_WORLD, setCallAbortInParallelInsteadOfMPIAbort(), and setCallAbortInSerialInsteadOfExit().
void SAMRAI::tbox::SAMRAI_MPI::finalize () [static]
Shut down SAMRAI_MPI and, if appropriate, shut down MPI.
This method frees the MPI communicator duplicated for SAMRAI use. If this class has started MPI with the first init() method, finalize() will also shut down MPI.
References MPI_COMM_NULL.
Member Data Documentation
const SAMRAI_MPI::Comm SAMRAI::tbox::SAMRAI_MPI::commWorld = MPI_COMM_WORLD [static]
const SAMRAI_MPI::Comm SAMRAI::tbox::SAMRAI_MPI::commNull = MPI_COMM_NULL [static]
Referenced by Comm_dup(), SAMRAI::mesh::TreeLoadBalancer::freeMPICommunicator(), SAMRAI::mesh::CascadePartitioner::freeMPICommunicator(), SAMRAI::mesh::TreeLoadBalancer::setSAMRAI_MPI(), and SAMRAI::mesh::CascadePartitioner::setSAMRAI_MPI().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/SAMRAI_MPI.h
source/SAMRAI/tbox/SAMRAI_MPI.C