SAMRAI: SAMRAI::solv::CellPoissonFACSolver Class Reference
SAMRAI::solv::CellPoissonFACSolver Class Reference
Class for solving scalar Poisson's equation on SAMR grid, wrapping up lower-level components (FAC cycling, Poisson equation operations and boundary conditions) in a single high-level interface.
#include <source/SAMRAI/solv/CellPoissonFACSolver.h>
Public Member Functions
CellPoissonFACSolver (const tbox::Dimension &dim, const std::string &object_name, const boost::shared_ptr< FACPreconditioner > &fac_precond, const boost::shared_ptr< CellPoissonFACOps > &fac_ops, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
Construct a solver.
~CellPoissonFACSolver ()
Destructor.
bool solveSystem (const int solution, const int rhs, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, int coarse_ln=-1, int fine_ln=-1)
Solve Poisson's equation, assuming an uninitialized solver state.
bool solveSystem (const int solution, const int rhs)
Solve Poisson's equation using the current solver state set by initializeSolverState().
void setBoundaries (const std::string &boundary_type, const int fluxes=-1, const int flags=-1, int *bdry_types=0)
Specify the boundary conditions that are to be used at the physical domain boundary.
void setBcObject (const RobinBcCoefStrategy *bc_object)
Override internal implementation to set boundary condition coefficients with user-provided implementation.
void initializeSolverState (const int solution, const int rhs, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int coarse_level=-1, const int fine_level=-1)
Prepare the solver's internal state for solving.
void deallocateSolverState ()
Remove the solver's internal state data.
const std::string & getObjectName () const
Get the name of this object.
Specifying PDE parameters
void setDPatchDataId (int id)
Set the patch data index for variable D.
void setDConstant (double scalar)
Set the scalar value variable D.
void setCPatchDataId (int id)
Set the scalar value variable C.
void setCConstant (double scalar)
Set the patch data index for variable C.
Functions to get data on last solve.
int getNumberOfIterations () const
Return FAC iteration count from last (or current if there is one) FAC iteration process.
void getConvergenceFactors (double &avg_factor, double &final_factor) const
Get average convergance rate and convergence rate of the last (or current if there is one) FAC solve.
double getResidualNorm () const
Return residual norm from the just-completed FAC iteration.
Detailed Description
Class for solving scalar Poisson's equation on SAMR grid, wrapping up lower-level components (FAC cycling, Poisson equation operations and boundary conditions) in a single high-level interface.
We solve the equation div(D grad(u)) + Cu = f where D is a side-centered array and C is a cell-centered array. u and f are also cell-centered. Boundary conditions supported are Dirichlet, Neumann and mixed (Dirichlet on some faces and Neumann on others).
This class is a wrapper, providing a single class that coordinates three major components: the FAC solver, the cell-centered Poisson FAC operator and a default Robin bc coefficient implelemtation. It is perfectly acceptable to use those classes outside of this class.
The underlying solver is an FAC solver using cell-centered discretization. The difference scheme is second-order central-difference. On coarse-fine boundaries within the solution levels, the composite grid operator uses, by default, the discretization method of Ewing, Lazarov and Vassilevski ("Local Refinement Techniques for Elliptic Problems on Cell-Centered Grids, I. Error Analysis", Mathematics of Computation, Vol. 56, No. 194, April 1991, pp. 437-461).
Typical use of this class is:
Construct a CellPoissonFACSolver object, providing it the hierarchy and range of levels participating in the solve.
Set the parameters C and D using the functions named setC... and setD... By default, D=1 and C=0 everywhere.
Call setBoundaries() to state the types boundary conditions, along with supplemental data for setting those boundary conditions.
Call initializeSolverState() to set up information internal to the solver. This is step is not required but will save setup costs if you are making multiple solves. This commits the object to the current hierarchy state and the specific types of boundary conditions you selected, It does NOT commit to the specific values of the boundary condition. A hierarchy change (through adaption or other means) invalidates the state, thus you must reinitialize or deallocateSolverState() the state before another solve.
Solve the equation with solveSystem(). You provide the patch data indices for the solution u and the right hand side f. u must have at least one ghost cell and where a Dirichlet boundary condition applies, those cells must be set to the value on the boundary. If only Neumann boundary conditions are used, the ghost cell values do not matter.
Call deallocateSolverState() to free up internal resources, if initializeSolverState() was called before the solve.
After the solve, information on the solve can be obtained by calling one of these functions:
getNumberOfIterations() gives the number of FAC cycles used.
getConvergenceFactors() gives the average and final convergence factors for the solve.
getResidualNorm() gives the final residual
Finer solver controls can be set using the functions in this class.
Input Parameters
Definitions:
enable_logging turn logging on or off
Details:
parameter
type
default
range
opt/req
behavior on restart
enable_logging
bool
FALSE
TRUE, FALSE
opt
Not written to restart. Value in input db used.
Constructor & Destructor Documentation
SAMRAI::solv::CellPoissonFACSolver::CellPoissonFACSolver (const tbox::Dimension & dim, const std::string & object_name, const boost::shared_ptr< FACPreconditioner > & fac_precond, const boost::shared_ptr< CellPoissonFACOps > & fac_ops, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>())
Construct a solver.
If the database is not NULL, initial settings will be set using the database. The solver is uninitialized until initializeSolverState() is called.
Parameters:
dim
object_name Name of object used in outputs
fac_precond
fac_ops
input_db tbox::Database for initialization (may be NULL)
References SAMRAI::hier::VariableDatabase::getDatabase(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::VariableDatabase::getVariable(), SAMRAI::hier::IntVector::getZero(), and SAMRAI::hier::VariableDatabase::registerInternalSAMRAIVariable().
SAMRAI::solv::CellPoissonFACSolver::~CellPoissonFACSolver ()
Destructor.
References deallocateSolverState(), SAMRAI::hier::VariableDatabase::getDatabase(), and SAMRAI::tbox::Dimension::getValue().
Member Function Documentation
bool SAMRAI::solv::CellPoissonFACSolver::solveSystem (const int solution, const int rhs, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, int coarse_ln = -1, int fine_ln = -1)
Solve Poisson's equation, assuming an uninitialized solver state.
Here, u is the "solution" patch data index and f is the right hand side patch data index. The return value is true if the solver converged and false otherwise.
This function is a wrapper. It simply initializes the solver state, call the solveSystem(const int,const int) for the initialized solver then deallocates the solver state.
Upon return from this function, solution will contain the result of the solve.
See initializeSolverState() for opportunities to save overhead when using multiple consecutive solves.
See also:
solveSystem(const int,const int)
Parameters:
solution hier::Patch data index for solution u
rhs hier::Patch data index for right hand side f
hierarchy The patch hierarchy to solve on
coarse_ln The coarsest level in the solve.
fine_ln The finest level in the solve.
Returns:
whether solver converged to specified level
See also:
initializeSolverState
Precondition:
hierarchy
d_dim == hierarchy->getDim()
!d_solver_is_initialized
References deallocateSolverState(), initializeSolverState(), SAMRAI::tbox::plog, SAMRAI::solv::PoissonSpecifications::printClassData(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ERROR.
bool SAMRAI::solv::CellPoissonFACSolver::solveSystem (const int solution, const int rhs)
Solve Poisson's equation using the current solver state set by initializeSolverState().
When the solver state has been initialized, this function may be called repeadedly with different values on the rhs. There is some cost savings for multiple solves when this is done.
Before calling this function, the solution and right-hand-side quantities should be set properly by the user on all patch interiors on the range of levels covered by the FAC iteration. All data for these patch data index should be allocated. Thus, the user is responsible for managing the storage for the solution and right-hand-side.
Returns:
whether solver converged to specified level
See also:
solveSystem(const int, const int, boost::shared_ptr< hier::PatchHierarchy >, int, int);
Precondition:
d_solver_is_initialized
(solution >= 0) || (rhs >= 0)
References SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), and TBOX_ERROR.
void SAMRAI::solv::CellPoissonFACSolver::setBoundaries (const std::string & boundary_type, const int fluxes = -1, const int flags = -1, int * bdry_types = 0)
Specify the boundary conditions that are to be used at the physical domain boundary.
This method is used to set up the default SimpleCellRobinBcCoefs object for specifying boundary conditions. Note that you may alternatively provide your own implementation of the Robin boundary condition coefficients using the setBcObject() method.
The boundary conditions specified as the std::string argument "boundary_type." The boundary type argument can be "Dirichlet", "Neumann", or "Mixed".
If using Dirichlet boundary conditions, then before the solver is called, the storage for the unknown u must have a box_level of ghost cells at least one cell wide that includes the Dirichlet boundary values.
If using Neumann boundary conditions, then before the solver is called, the outerface boundary flux data must be set for the Neumann conditions. The fluxes argument gives the patch data index of this flux data.
The mixed boundary type is for a mixture of Dirichlet and Neumann boundary conditions are used at the physical domain boundary. The fluxes argument gives the patch data index of the outerface data that specifies the flux data for the Neumann conditions. The flags array is an outerface data array of integer flags that specifies whether Dirichlet (flag == zero) or Neumann (flag == one) conditions are to be used at a particular cell boundary face. Note that the flag data must be set before the matrix entries can be computed and the flux data must be set before the solver is called. The bdry_types argument can be used if the boundary conditions are mixed but one or more of the faces of the physical boundary are entirely either Dirichlet or Neumann boundaries. The bdry_types argument should be an array of 2*DIM integers, specifying the boundary conditions on each side of the physical domain. It should be ordered {x_lo, x_hi, y_lo, y_hi, z_lo, z_hi}, with the values for each face being 0 for Dirichlet conditions, 1 for Neumann conditions, and 2 for mixed boundary conditions. The bdry_type argument is never required, but if used it can sometimes make the PoissonHYPRESolver class more efficient.
Precondition:
(d_bc_object == 0) || (d_bc_object == &d_simple_bc)
References SAMRAI::solv::SimpleCellRobinBcCoefs::setBoundaries(), and TBOX_ERROR.
void SAMRAI::solv::CellPoissonFACSolver::setBcObject (const RobinBcCoefStrategy * bc_object) [inline]
Override internal implementation to set boundary condition coefficients with user-provided implementation.
This function is used to override the default internal object for setting Robin boundary condition coefficients. You should override when you need to avoid the limitations of the SimpleCellRobinBcCoefs class or you prefer to use your own implementation.
Note that an important limitation of the SimpleCellRobinBcCoefs class is the inability to support linear interpolation in the prolongation step.
Once the boundary condition object is overwritten by this method, you must no longer call the setBoundaries() method.
Precondition:
bc_object
References TBOX_ERROR.
void SAMRAI::solv::CellPoissonFACSolver::setDPatchDataId (int id) [inline]
Set the patch data index for variable D.
In addition, disregard any previous D specified by setDConstant().
References SAMRAI::solv::PoissonSpecifications::setDPatchDataId().
void SAMRAI::solv::CellPoissonFACSolver::setDConstant (double scalar) [inline]
Set the scalar value variable D.
In addition, disregard any previous D specified by setDPatchDataId().
References SAMRAI::solv::PoissonSpecifications::setDConstant().
void SAMRAI::solv::CellPoissonFACSolver::setCPatchDataId (int id) [inline]
Set the scalar value variable C.
In addition, disregard any previous C specified by setCConstant().
References SAMRAI::solv::PoissonSpecifications::setCPatchDataId().
void SAMRAI::solv::CellPoissonFACSolver::setCConstant (double scalar) [inline]
Set the patch data index for variable C.
In addition, disregard any previous C specified by setCConstant().
References SAMRAI::solv::PoissonSpecifications::setCConstant(), and SAMRAI::solv::PoissonSpecifications::setCZero().
void SAMRAI::solv::CellPoissonFACSolver::initializeSolverState (const int solution, const int rhs, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int coarse_level = -1, const int fine_level = -1)
Prepare the solver's internal state for solving.
In the interest of efficiency, this class may prepare and cache some hierarchy-dependent objects. Though it is not required, initializing the solver state makes for greater efficiency when you are doing multiple solves on the same system of equation. If you do not initialize the state, it is initialized and deallocated each time you call solveSystem(const int, const int). The state must be reinitialized if the hierarchy or a boundary condition type changes.
To unset the data set in this function, see deallocateSolverState().
The solution and rhs patch data indices in the argument list are used to determine the form of the data you plan to use in the solve. They need not be the same data you solve on, but they should be similar. Both must represent cell-centered double data. The solution must have at least one ghost cell width, though this is not checked in the initialize phase, because data is not required yet.
Parameters:
solution solution patch data index for u
rhs right hand side patch data index for f
hierarchy The patch hierarchy to solve on
coarse_level The coarsest level in the solve
fine_level The finest level in the solve
Precondition:
hierarchy
d_dim == hierarchy->getDim()
d_bc_object != 0
(solution >= 0) || (rhs >= 0)
References SAMRAI::solv::PoissonSpecifications::dIsConstant(), SAMRAI::solv::PoissonSpecifications::getDConstant(), SAMRAI::solv::PoissonSpecifications::getDPatchDataId(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::solv::SimpleCellRobinBcCoefs::setDiffusionCoefConstant(), SAMRAI::solv::SimpleCellRobinBcCoefs::setDiffusionCoefId(), SAMRAI::solv::SimpleCellRobinBcCoefs::setHierarchy(), TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ERROR.
Referenced by solveSystem().
void SAMRAI::solv::CellPoissonFACSolver::deallocateSolverState ()
Remove the solver's internal state data.
Remove all hierarchy-dependent data set by initializeSolverState. It is safe to call deallocateSolverState() even state is already deallocated, but nothing is done in that case.
See also:
initializeSolverState()
References SAMRAI::tbox::Dimension::getValue().
Referenced by solveSystem(), and ~CellPoissonFACSolver().
int SAMRAI::solv::CellPoissonFACSolver::getNumberOfIterations () const [inline]
Return FAC iteration count from last (or current if there is one) FAC iteration process.
void SAMRAI::solv::CellPoissonFACSolver::getConvergenceFactors (double & avg_factor, double & final_factor) const [inline]
Get average convergance rate and convergence rate of the last (or current if there is one) FAC solve.
Parameters:
avg_factor average convergence factor over current FAC cycles
final_factor convergence factor of the last FAC cycle
double SAMRAI::solv::CellPoissonFACSolver::getResidualNorm () const [inline]
Return residual norm from the just-completed FAC iteration.
The norm return value is computed as the maximum norm over all patch levels involved in the solve. The value corresponds to the norm applied in the user-defined residual computation.
The latest computed norm is the one returned.
const std::string& SAMRAI::solv::CellPoissonFACSolver::getObjectName () const [inline]
Get the name of this object.
Returns:
The name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/solv/CellPoissonFACSolver.h
source/SAMRAI/solv/CellPoissonFACSolver.C