SAMRAI: SAMRAI::math::ArrayDataBasicOps< TYPE > Class Template Reference
SAMRAI::math::ArrayDataBasicOps< TYPE > Class Template Reference
#include <source/SAMRAI/math/ArrayDataBasicOps.h>
Public Member Functions
ArrayDataBasicOps ()
~ArrayDataBasicOps ()
void scale (pdat::ArrayData< TYPE > &dst, const TYPE &alpha, const pdat::ArrayData< TYPE > &src, const hier::Box &box) const
void addScalar (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src, const TYPE &alpha, const hier::Box &box) const
void add (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src1, const pdat::ArrayData< TYPE > &src2, const hier::Box &box) const
void subtract (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src1, const pdat::ArrayData< TYPE > &src2, const hier::Box &box) const
void multiply (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src1, const pdat::ArrayData< TYPE > &src2, const hier::Box &box) const
void divide (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src1, const pdat::ArrayData< TYPE > &src2, const hier::Box &box) const
void reciprocal (pdat::ArrayData< TYPE > &dst, const pdat::ArrayData< TYPE > &src, const hier::Box &box) const
void linearSum (pdat::ArrayData< TYPE > &dst, const TYPE &alpha, const pdat::ArrayData< TYPE > &src1, const TYPE &beta, const pdat::ArrayData< TYPE > &src2, const hier::Box &box) const
void axpy (pdat::ArrayData< TYPE > &dst, const TYPE &alpha, const pdat::ArrayData< TYPE > &src1, const pdat::ArrayData< TYPE > &src2, const hier::Box &box) const
void axmy (pdat::ArrayData< TYPE > &dst, const TYPE &alpha, const pdat::ArrayData< TYPE > &src1, const pdat::ArrayData< TYPE > &src2, const hier::Box &box) const
TYPE min (const pdat::ArrayData< TYPE > &data, const hier::Box &box) const
TYPE max (const pdat::ArrayData< TYPE > &data, const hier::Box &box) const
void setRandomValues (pdat::ArrayData< TYPE > &dst, const TYPE &width, const TYPE &low, const hier::Box &box) const
Detailed Description
template<class TYPE>
class SAMRAI::math::ArrayDataBasicOps< TYPE >
Class ArrayDataBasicOps implements a set of basic operations that apply to numerical data maintained as pdat::ArrayData<TYPE> objects. These operations include simple arithmetic operations as well as min and max, etc. This class provides a single implementation of these operations that may used to manipulate any of the standard array-based patch data types defined on a patch. Note that each member function accepts a box argument which specifies the portion of the array data on which the associated operation is performed. The actual index region on which the operation occurs is the intersection of this box and the boxes of all the pdat::ArrayData<TYPE> objects involved.
These operations typically apply only to the numerical standard built-in types, such as double, float, and int, and the complex type (which may or may not be a built-in type depending on the C++ compiler). Thus, this templated class should only be used to instantiate objects with those types as the template parameter. Those operations whose implementations depend of the data type are specialized for each numerical type. To use this class with other standard types or user-defined types (which may or may not make sense), the member functions must be specialized so that the correct operations are performed.
See also:
pdat::ArrayData
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::math::ArrayDataBasicOps< TYPE >::ArrayDataBasicOps () [inline]
Empty constructor and destructor.
template<class TYPE > SAMRAI::math::ArrayDataBasicOps< TYPE >::~ArrayDataBasicOps () [inline]
Member Function Documentation
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::scale (pdat::ArrayData< TYPE > & dst, const TYPE & alpha, const pdat::ArrayData< TYPE > & src, const hier::Box & box) const [inline]
Set dst = alpha * src, elementwise.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == box.getDim())
(alpha == tbox::MathUtilities<TYPE>::getZero()) || (alpha == tbox::MathUtilities<TYPE>::getOne()) || (dst.getDepth() == src.getDepth())
References SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::fillAll(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), and SAMRAI::solv::GhostCellRobinBcCoefs::setBcCoefs().
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src, const TYPE & alpha, const hier::Box & box) const [inline]
Set dst = src + alpha, elementwise.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == box.getDim())
(alpha == tbox::MathUtilities<TYPE>::getZero()) || (dst.getDepth() == src.getDepth())
References SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::add (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src1, const pdat::ArrayData< TYPE > & src2, const hier::Box & box) const [inline]
Set dst = src1 + src2, elementwise.
Precondition:
(dst.getDim() == src1.getDim()) && (dst.getDim() == src2.getDim()) && (dst.getDim() == box.getDim())
(dst.getDepth() == src1.getDepth()) && (dst.getDepth() == src2.getDepth())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
Referenced by SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy().
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src1, const pdat::ArrayData< TYPE > & src2, const hier::Box & box) const [inline]
Set dst = src1 - src2, elementwise.
Precondition:
(dst.getDim() == src1.getDim()) && (dst.getDim() == src2.getDim()) && (dst.getDim() == box.getDim())
(dst.getDepth() == src1.getDepth()) && (dst.getDepth() == src2.getDepth())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
Referenced by SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), and SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy().
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src1, const pdat::ArrayData< TYPE > & src2, const hier::Box & box) const [inline]
Set dst = src1 * src2, elementwise.
Precondition:
(dst.getDim() == src1.getDim()) && (dst.getDim() == src2.getDim()) && (dst.getDim() == box.getDim())
(dst.getDepth() == src1.getDepth()) && (dst.getDepth() == src2.getDepth())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::divide (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src1, const pdat::ArrayData< TYPE > & src2, const hier::Box & box) const [inline]
Set dst = src1 / src2, elementwise. No check for division by zero.
Precondition:
(dst.getDim() == src1.getDim()) && (dst.getDim() == src2.getDim()) && (dst.getDim() == box.getDim())
(dst.getDepth() == src1.getDepth()) && (dst.getDepth() == src2.getDepth())
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal (pdat::ArrayData< TYPE > & dst, const pdat::ArrayData< TYPE > & src, const hier::Box & box) const [inline]
Set dst = 1 / src, elementwise. No check for division by zero.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == box.getDim())
dst.getDepth() == src.getDepth()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum (pdat::ArrayData< TYPE > & dst, const TYPE & alpha, const pdat::ArrayData< TYPE > & src1, const TYPE & beta, const pdat::ArrayData< TYPE > & src2, const hier::Box & box) const [inline]
Set dst = alpha * src1 + beta * src2, elementwise.
Precondition:
(dst.getDim() == src1.getDim()) && (dst.getDim() == src2.getDim()) && (dst.getDim() == box.getDim())
(dst.getDepth() == src1.getDepth()) && (dst.getDepth() == src2.getDepth())
References SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::fillAll(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy (pdat::ArrayData< TYPE > & dst, const TYPE & alpha, const pdat::ArrayData< TYPE > & src1, const pdat::ArrayData< TYPE > & src2, const hier::Box & box) const [inline]
Set dst = alpha * src1 + src2, elementwise.
Precondition:
(dst.getDim() == src1.getDim()) && (dst.getDim() == src2.getDim()) && (dst.getDim() == box.getDim())
(alpha == tbox::MathUtilities<TYPE>::getZero()) || (alpha == tbox::MathUtilities<TYPE>::getOne()) || (alpha == -tboxMathUtilities<TYPE>::getOne()) || ((dst.getDepth() == src1.getDepth()) && (dst.getDepth() == src2.getDepth()))
References SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
Referenced by SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum().
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy (pdat::ArrayData< TYPE > & dst, const TYPE & alpha, const pdat::ArrayData< TYPE > & src1, const pdat::ArrayData< TYPE > & src2, const hier::Box & box) const [inline]
Set dst = alpha * src1 - src2, elementwise.
Precondition:
(dst.getDim() == src1.getDim()) && (dst.getDim() == src2.getDim()) && (dst.getDim() == box.getDim())
(alpha == tbox::MathUtilities<TYPE>::getZero()) || (alpha == tbox::MathUtilities<TYPE>::getOne()) || ((dst.getDepth() == src1.getDepth()) && (dst.getDepth() == src2.getDepth()))
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::hier::Box::size(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
Referenced by SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum().
template<class TYPE> TYPE SAMRAI::math::ArrayDataBasicOps< TYPE >::min (const pdat::ArrayData< TYPE > & data, const hier::Box & box) const [inline]
Return the minimum array data entry. If data is complex, return the array data entry with the minimum norm.
Precondition:
data.getDim() == box.getDim()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE> TYPE SAMRAI::math::ArrayDataBasicOps< TYPE >::max (const pdat::ArrayData< TYPE > & data, const hier::Box & box) const [inline]
Return the maximum array data entry. If data is complex, return the array data entry with the maximum norm.
Precondition:
data.getDim() == box.getDim()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE> void SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues (pdat::ArrayData< TYPE > & dst, const TYPE & width, const TYPE & low, const hier::Box & box) const [inline]
Set dst to random values. If the data is int, each element of dst is set as dst = mrand48(). If the data is double or float, each element of dst is set as dst = width * drand48() + low. If the data is complex, each element of dst is set as dst = dcomplex(rval, ival), where rval = real(width) * drand48() + real(low), and ival = imag(width) * drand48() + imag(low).
Precondition:
dst.getDim() == box.getDim()
References SAMRAI::hier::Box::empty(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/math/ArrayDataBasicOps.h
source/SAMRAI/math/ArrayDataBasicOps.C