SAMRAI: SAMRAI::mesh::GriddingAlgorithm Class Reference
SAMRAI::mesh::GriddingAlgorithm Class Reference
Class GriddingAlgorithm manages AMR patch hierarchy construction operations in SAMRAI. Specifically, it provides AMR patch hierarchy generation and regridding routines that may be used with a variety of AMR solution algorithms and application codes.
#include <source/SAMRAI/mesh/GriddingAlgorithm.h>
Public Member Functions
GriddingAlgorithm (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db, const boost::shared_ptr< TagAndInitializeStrategy > &level_strategy, const boost::shared_ptr< BoxGeneratorStrategy > &generator, const boost::shared_ptr< LoadBalanceStrategy > &balancer, const boost::shared_ptr< LoadBalanceStrategy > &balancer_zero=boost::shared_ptr< LoadBalanceStrategy >())
The constructor for GriddingAlgorithm configures the gridding algorithm with the patch hierarchy and concrete algorithm strategy objects in the argument list.
virtual ~GriddingAlgorithm ()
Destructor.
void makeCoarsestLevel (const double level_time)
Create or rebalance the coarsest level.
void makeFinerLevel (const int tag_buffer, const bool initial_cycle, const int cycle, const double level_time, const double regrid_start_time=0.0)
Attempt to create a new level in the hierarchy finer than the finest level currently residing in the hierarchy.
void regridAllFinerLevels (const int level_number, const std::vector< int > &tag_buffer, const int cycle, const double level_time, const std::vector< double > &regrid_start_time=std::vector< double >(), const bool level_is_coarsest_to_sync=true)
Attempt to regrid each level in the PatchHierarchy that is finer than the specified level.
virtual boost::shared_ptr
< TagAndInitializeStrategy > getTagAndInitializeStrategy () const
Return pointer to level gridding strategy data member.
virtual boost::shared_ptr
< LoadBalanceStrategy > getLoadBalanceStrategy () const
Return pointer to load balance strategy data member.
virtual boost::shared_ptr
< LoadBalanceStrategy > getLoadBalanceStrategyZero () const
Return pointer to load balance strategy specialized for balancing level zero.
boost::shared_ptr
< hier::PatchHierarchy > getPatchHierarchy () const
Return pointer to PatchHierarchy data member.
void printClassData (std::ostream &os) const
Print all data members of the class instance to given output stream.
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write object state out to the given restart database.
void printStatistics (std::ostream &s=tbox::plog) const
const std::string & getObjectName () const
Get the name of this object.
Detailed Description
Class GriddingAlgorithm manages AMR patch hierarchy construction operations in SAMRAI. Specifically, it provides AMR patch hierarchy generation and regridding routines that may be used with a variety of AMR solution algorithms and application codes.
The three main functions provided by this class are:
makeCoarsestLevel() This routine constructs or repartitions the coarsest hierarchy level (level 0).
makeFinerLevel() This routine will attempt to add a new finest level to the hierarchy if the maximum number of levels allows it and cells on the current finest level are tagged for refinement.
regridAllFinerLevels() This routine will regrid all levels finer than some specified level based on cells that are tagged for refinement on each level finer than and including the given level. This routine may add a new finest hierarchy level if the maximum number of levels allows it and cells on the current finest level are tagged for refinement. Levels may also be removed from the hierarchy if no cells are tagged.
These basic AMR operations are used to generate levels in the AMR patch hierarchy at the beginning of a simulation, and regridding collections of levels during an adaptive calculation. More details are found in the comments accompanying each member function below.
Other objects passed to the constructor provide the gridding algorithm with particular operations needed during meshing operations. Operations that tag cells for refinement on a patch level and initialize data on new levels are provided by the TagAndInitializeStrategy argument. Operations that cluster tagged cells into a boxes are provided by the BoxGeneratorStrategy argument. Routines that load balance patches on a level are provided by the LoadBalanceStrategy constructor argument.
Input Parameters
Definitions:
check_overflow_nesting
check_proper_nesting
check_nonrefined_tags controls how to resolve user-specified tags that violate proper nesting. If a tag violates the nesting requirements, its location in index space will not be refined when creating the finer level. This flag allows the user to determine what to do when this occurs.
Set to one of these characters:
'i' - violating tags will be quietly disregarded.
'w' - violating tags will cause a warning and be disregarded.
'e' - violating tags will cause an unrecoverable assertion.
It is fastest to ignore non-nesting tags because no checking has to be done.
check_overlapping_patches controls checking for overlapping patches on a new level.
Set to one of these characters:
'i' - there is no check for overlapping patches, and they will be quietly disregarded.
'w' - overlapping patches will cause a warning and be disregarded.
'e' - violating tags will cause an unrecoverable assertion.
The check for overlapping patches may be and should be bypassed by applications that can tolerate overlaps. To prevent the creation of levels with overlapping patches, see the PatchHierarchy input flag "allow_patches_smaller_than_minimum_size_to_prevent_overlaps".
check_nonnesting_user_boxes controls how user-specified refinement boxes that violate proper nesting are handled.
Set to one of these characters:
'i' - nesting violations will be quietly disregarded.
'w' - nesting violations will cause a warning but the code will continue anyway.
'e' - nesting violations will cause an unrecoverable assertion
We highly recommend making nesting violation an error. The code may work anyway, but there are no guarantees.
sequentialize_patch_indices whether patch indices will be globally sequentialized. This is not scalable, but is required for writing correct VisIt files. Due to the current VisIt requirement, this is currently true by default. It will evetually be set back to false after we remove the VisIt requirement.
enforce_proper_nesting
Details:
parameter
type
default
range
opt/req
behavior on restart
check_overflow_nesting
bool
FALSE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
check_proper_nesting
bool
FALSE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
check_nonrefined_tags
string
"WARN"
"WARN", "IGNORE", "ERROR"
opt
Parameter read from restart db may be overridden by input db
check_overlapping_patches
string
"IGNORE"
"WARN", "IGNORE", "ERROR"
opt
Parameter read from restart db may be overridden by input db
check_nonnesting_user_boxes
string
"ERROR"
"WARN", "IGNORE", "ERROR"
opt
Parameter read from restart db may be overridden by input db
sequentialize_patch_indices
bool
TRUE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
enforce_proper_nesting
bool
TRUE
TRUE, FALSE
opt
Parameter read from restart db may be overridden by input db
All values read in from a restart database may be overriden by input database values. If no new input database value is given, the restart database value is used.
See also:
mesh::TagAndInitializeStrategy
mesh::LoadBalanceStrategy
mesh::BoxGeneratorStrategy
Constructor & Destructor Documentation
SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db, const boost::shared_ptr< TagAndInitializeStrategy > & level_strategy, const boost::shared_ptr< BoxGeneratorStrategy > & generator, const boost::shared_ptr< LoadBalanceStrategy > & balancer, const boost::shared_ptr< LoadBalanceStrategy > & balancer_zero = boost::shared_ptr<LoadBalanceStrategy>())
The constructor for GriddingAlgorithm configures the gridding algorithm with the patch hierarchy and concrete algorithm strategy objects in the argument list.
Gridding parameters are initialized from values provided in the specified input and in the restart database corresponding to the specified object_name argument.
Parameters:
[in] hierarchy The hierarchy that this GriddingAlgorithm will work on. The pointer is cached. All hierarchy operations will be on this hierarchy.
[in] object_name For registering the object in the restart database.
[in] input_db
[in] level_strategy
[in] generator
[in] balancer Load balancer
[in] balancer_zero Special load balancer to use for level zero. If omitted, will use balancer instead.
Precondition:
hierarchy
!object_name.empty()
tag_init_strategy
generator
balancer
References SAMRAI::hier::VariableDatabase::getDatabase(), SAMRAI::tbox::RestartManager::getManager(), SAMRAI::hier::IntVector::getOne(), SAMRAI::tbox::Statistician::getStatistician(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::VariableDatabase::getVariable(), SAMRAI::hier::IntVector::getZero(), SAMRAI::tbox::Utilities::intToString(), SAMRAI::hier::VariableDatabase::registerInternalSAMRAIVariable(), SAMRAI::mesh::MultiblockGriddingTagger::setScratchTagPatchDataIndex(), SAMRAI::hier::BoxLevelConnectorUtils::setTimerPrefix(), SAMRAI::hier::MappingConnectorAlgorithm::setTimerPrefix(), SAMRAI::hier::OverlapConnectorAlgorithm::setTimerPrefix(), and TBOX_ASSERT.
SAMRAI::mesh::GriddingAlgorithm::~GriddingAlgorithm () [virtual]
Destructor.
References SAMRAI::tbox::RestartManager::getManager().
Member Function Documentation
void SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel (const double level_time) [virtual]
Create or rebalance the coarsest level.
This is an implementation of interface defined in GriddingAlgorithmStrategy.
This routine will attempt to construct the coarsest level in the AMR patch hierarchy (i.e., level 0). If level 0 does not already exist, then the domain specification is checked against the constraints of the grid generation procedures. Recall that the domain specification is maintained by the grid geometry object associated with the hierarchy. Generally, an unrecoverable assertion will result if the constraints are not satisfied.
If level 0 already exists in the hierarchy, then the routine will generate a new level zero by re-applying the load balancing procedure to the existing level. Data will be moved from the old level to the new level and the pre-existing level 0 will be discarded. Note that this routine is different than the routine makeFinerLevel() below, which is used to construct levels finer than level zero. In particular, this routine does not select cells for refinement, whereas the other routine does.
Parameters:
[in] level_time Simulation time.
Precondition:
d_hierarchy->getMaxNumberOfLevels() > 0
Implements SAMRAI::mesh::GriddingAlgorithmStrategy.
References SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::IntVector::max(), SAMRAI::hier::Connector::setBase(), SAMRAI::hier::Connector::setHead(), SAMRAI::hier::Connector::setTranspose(), and TBOX_ASSERT.
void SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel (const int tag_buffer, const bool initial_cycle, const int cycle, const double level_time, const double regrid_start_time = 0.0) [virtual]
Attempt to create a new level in the hierarchy finer than the finest level currently residing in the hierarchy.
This is an implementation of interface method GriddingAlgorithmStrategy::makeFinerLevel().
The tag buffer indicates the number of cells by which cells selected for refinement should be buffered before new finer level boxes are constructed. All tagged cells should be refined except where refinement would violate proper nesting. The buffer is meant to keep phenomena of interest on refined regions of the mesh until adaptive regridding occurs next. Callers of this method should take into account how the simulation may evolve before regridding occurs (e.g., number of timesteps taken) when calculating the tag_buffer.
Parameters:
[in] tag_buffer See above text.
[in] initial_cycle See above text
[in] cycle See above text.
[in] level_time See above text..
[in] regrid_start_time The simulation time when the regridding operation began (this parameter is ignored except when using Richardson extrapolation)
Precondition:
d_hierarchy
d_hierarchy->getPatchLevel(d_hierarchy->getFinestLevelNumber())
tag_buffer >= 0
Implements SAMRAI::mesh::GriddingAlgorithmStrategy.
References SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::hier::BoxLevelConnectorUtils::computeExternalParts(), SAMRAI::hier::Connector::format(), SAMRAI::hier::Connector::getRatio(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::IntVector::max(), SAMRAI::tbox::plog, TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::mesh::GriddingAlgorithm::regridAllFinerLevels (const int level_number, const std::vector< int > & tag_buffer, const int cycle, const double level_time, const std::vector< double > & regrid_start_time = std::vector<double>(), const bool level_is_coarsest_to_sync = true) [virtual]
Attempt to regrid each level in the PatchHierarchy that is finer than the specified level.
This method implements the virtual interface GriddingAlgorithmStrategy::regridAllFinerLevels().
Note that the current algorithm permits at most one new finest level to be added to the hierarchy with each invocation of the regridding process. This constraint, though seemingly restrictive makes the process of maintaining properly nested levels much easier.
Note that the current algorithm permits at most one new finest level to be added to the hierarchy with each call to this method. This constraint, though seemingly restrictive makes the process of maintaining properly nested levels much easier.
Parameters:
[in] level_number Coarsest level on which cells will be tagged for refinement
[in] tag_buffer Size of buffer on each level around tagged cells that will be covered by the next finer level
[in] cycle Simulaition cycle when regridding occurs
[in] level_time Simulation time of the level corresponding to level_num when regridding occurs
[in] regrid_start_time The simulation time when the regridding operation began on each level (this parameter is ignored except when using Richardson extrapolation)
[in] level_is_coarsest_to_sync Level is the coarsest to sync
Precondition:
(level_number >= 0) && (level_number <= d_hierarchy->getFinestLevelNumber())
d_hierarchy->getPatchLevel(level_number)
tag_buffer.size() >= level_number + 1
for each member, tb, of tag_buffer, tb >= 0
Implements SAMRAI::mesh::GriddingAlgorithmStrategy.
References SAMRAI::tbox::plog, TBOX_ASSERT, and TBOX_ERROR.
boost::shared_ptr< TagAndInitializeStrategy > SAMRAI::mesh::GriddingAlgorithm::getTagAndInitializeStrategy () const [virtual]
Return pointer to level gridding strategy data member.
Access to this member is useful when an integrator implementation needs to know if the error estimator uses time integration.
Returns:
pointer to TagAndInitializeStrategy data member.
Implements SAMRAI::mesh::GriddingAlgorithmStrategy.
boost::shared_ptr< LoadBalanceStrategy > SAMRAI::mesh::GriddingAlgorithm::getLoadBalanceStrategy () const [virtual]
Return pointer to load balance strategy data member.
boost::shared_ptr< LoadBalanceStrategy > SAMRAI::mesh::GriddingAlgorithm::getLoadBalanceStrategyZero () const [virtual]
Return pointer to load balance strategy specialized for balancing level zero.
Returns:
pointer to load balance strategy specialized for the case where one processor owns all the initial loads.
boost::shared_ptr< hier::PatchHierarchy > SAMRAI::mesh::GriddingAlgorithm::getPatchHierarchy () const [virtual]
Return pointer to PatchHierarchy data member.
Implements SAMRAI::mesh::GriddingAlgorithmStrategy.
void SAMRAI::mesh::GriddingAlgorithm::printClassData (std::ostream & os) const
Print all data members of the class instance to given output stream.
void SAMRAI::mesh::GriddingAlgorithm::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Write object state out to the given restart database.
Precondition:
restart_db
References TBOX_ASSERT.
void SAMRAI::mesh::GriddingAlgorithm::printStatistics (std::ostream & s = tbox::plog) const
References SAMRAI::tbox::Statistic::getInstanceId(), SAMRAI::tbox::Statistic::getName(), SAMRAI::tbox::Statistician::getStatistician(), and SAMRAI::tbox::Statistic::getStatSequenceLength().
const std::string& SAMRAI::mesh::GriddingAlgorithm::getObjectName () const [inline]
Get the name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/GriddingAlgorithm.h
source/SAMRAI/mesh/GriddingAlgorithm.C