SAMRAI: SAMRAI::tbox::RestartManager Class Reference
SAMRAI::tbox::RestartManager Class Reference
#include <source/SAMRAI/tbox/RestartManager.h>
Public Member Functions
bool isFromRestart ()
bool openRestartFile (const std::string &root_dirname, const int restore_num, const int num_nodes)
void closeRestartFile ()
boost::shared_ptr< Database > getRootDatabase ()
bool hasRootDatabase ()
Returns true if the root of the database has been set.
void setRootDatabase (const boost::shared_ptr< Database > &database)
void setDatabaseFactory (const boost::shared_ptr< DatabaseFactory > &database_factory)
bool hasDatabaseFactory ()
Returns true if the database for restore or dumps has been set.
void registerRestartItem (const std::string &name, Serializable *obj)
void unregisterRestartItem (const std::string &name)
void clearRestartItems ()
void writeRestartFile (const std::string &root_dirname)
void writeRestartFile (const std::string &root_dirname, const int restore_num)
void writeRestartToDatabase ()
Static Public Member Functions
static RestartManager * getManager ()
Protected Member Functions
RestartManager ()
~RestartManager ()
void registerSingletonSubclassInstance (RestartManager *subclass_instance)
Detailed Description
Class RestartManager coordinates SAMRAI restart files (currently implemented using the HDF database class) and the objects comprising SAMRAI-based application code. The manager class orchestrates opening and closing the database, stores data to be written out for restart, and writes out the restart data to the database. Note that the restart manager is a Singleton class that acts as a single point of control for restart capabilities. As such its constructor and destructor are protected members; they are not to be called outside of this class.
The general procedure for starting a simulation from a restart file is as follows.
Open the restart file using openRestartFile("filename").
Get root of restart database using getRootDatabase().
Initialize simulation objects using the restart constructor for the objects.
Close the restart file using closeRestartFile().
Technically, there is no need to close the restart file because this will automatically be taken care of by the destructor for the database object.
It is important to note in the initialization process, some objects will need to be constructed in the "empty" state and filled in later using some sort of getFromRestart() method.
The process for writing out state to a restart file is somewhat more complicated. The following things need to be taken care of.
Each object that has state that needs to be saved for restart must be derived from the Serializable class (which responds to the putToRestart() method).
Any object that needs to save its state to the restart file must be registered with the restart manager using the registerRestartItem() method. NOTE THAT NO TWO RESTARTABLE OBJECTS ARE ALLOWED TO HAVE THE SAME NAME STRING IDENTIFIER.
The patchdata to be written to restart need to be specified using the VariableDatabase::setPatchdataForRestart() method. This is usually taken care of by the numerical algorithm object.
When all these items are accounted for, writing to the restart file is accomplished using a writeRestartFile() method. There are two writeRestartFile() methods available. One takes only a restart directory name as an argument whereas the other takes both a restart directory name and a restore number for its arguments. See comments for member functions for more details.
See also:
tbox::Database
Constructor & Destructor Documentation
SAMRAI::tbox::RestartManager::RestartManager () [protected]
The constructor for RestartManager is protected. Consistent with the definition of a Singleton class, only the manager object has access to the constructor for the class.
The constructor for RestartManager initializes the root data base to a NullDatabase and sets the restart flag to false.
References clearRestartItems().
SAMRAI::tbox::RestartManager::~RestartManager () [protected]
The destructor for the restart manager is protected, since only the singleton class and subclasses may destroy the manager objects.
Member Function Documentation
RestartManager * SAMRAI::tbox::RestartManager::getManager () [static]
Return a pointer to the single instance of the restart manager. All access to the restart manager object is through getManager().
Note that when the manager is accessed for the first time, the Singleton instance is registered with the StartupShutdownManager class which destroys such objects at program completion. Thus, users of this class do not explicitly allocate or deallocate the Singleton instance.
Referenced by SAMRAI::hier::BaseGridGeometry::BaseGridGeometry(), SAMRAI::geom::CartesianGridGeometry::CartesianGridGeometry(), SAMRAI::tbox::StatisticRestartDatabase::getFromRestart(), SAMRAI::solv::KINSOL_SAMRAIContext::getFromRestart(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), SAMRAI::algs::ImplicitIntegrator::ImplicitIntegrator(), SAMRAI::hier::PatchHierarchy::initializeHierarchy(), SAMRAI::algs::TimeRefinementIntegrator::initializeHierarchy(), SAMRAI::solv::KINSOL_SAMRAIContext::KINSOL_SAMRAIContext(), SAMRAI::algs::MethodOfLinesIntegrator::MethodOfLinesIntegrator(), SAMRAI::hier::PatchHierarchy::PatchHierarchy(), SAMRAI::solv::SNES_SAMRAIContext::SNES_SAMRAIContext(), SAMRAI::tbox::StatisticRestartDatabase::StatisticRestartDatabase(), SAMRAI::algs::TimeRefinementIntegrator::TimeRefinementIntegrator(), SAMRAI::hier::BaseGridGeometry::~BaseGridGeometry(), SAMRAI::mesh::GriddingAlgorithm::~GriddingAlgorithm(), SAMRAI::solv::KINSOL_SAMRAIContext::~KINSOL_SAMRAIContext(), SAMRAI::algs::MethodOfLinesIntegrator::~MethodOfLinesIntegrator(), SAMRAI::hier::PatchHierarchy::~PatchHierarchy(), SAMRAI::tbox::StatisticRestartDatabase::~StatisticRestartDatabase(), and SAMRAI::algs::TimeRefinementIntegrator::~TimeRefinementIntegrator().
bool SAMRAI::tbox::RestartManager::isFromRestart () [inline]
Returns true if the run is from a restart file (i.e. a restart file has been opened from main()). Returns false otherwise.
Referenced by SAMRAI::tbox::StatisticRestartDatabase::StatisticRestartDatabase().
bool SAMRAI::tbox::RestartManager::openRestartFile (const std::string & root_dirname, const int restore_num, const int num_nodes)
Attempts to mount, for reading, the restart file for the processor. If there is no error opening the file, then the restart manager mounts the restart file. Returns true if open is successful; false otherwise.
Precondition:
hasDatabaseFactory()
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), hasDatabaseFactory(), SAMRAI::tbox::Utilities::intToString(), SAMRAI::tbox::Utilities::nodeToString(), SAMRAI::tbox::Utilities::processorToString(), and TBOX_ERROR.
void SAMRAI::tbox::RestartManager::closeRestartFile ()
Closes the restart file.
boost::shared_ptr<Database> SAMRAI::tbox::RestartManager::getRootDatabase () [inline]
Returns a boost::shared_ptr to the root of the database.
bool SAMRAI::tbox::RestartManager::hasRootDatabase () [inline]
Returns true if the root of the database has been set.
Referenced by writeRestartToDatabase().
void SAMRAI::tbox::RestartManager::setRootDatabase (const boost::shared_ptr< Database > & database) [inline]
Sets the database for restore or dumps.
void SAMRAI::tbox::RestartManager::setDatabaseFactory (const boost::shared_ptr< DatabaseFactory > & database_factory) [inline]
Sets the database for restore or dumps.
bool SAMRAI::tbox::RestartManager::hasDatabaseFactory () [inline]
Returns true if the database for restore or dumps has been set.
Referenced by openRestartFile(), and writeRestartFile().
void SAMRAI::tbox::RestartManager::registerRestartItem (const std::string & name, Serializable * obj)
Registers an object for restart with the given name.
Precondition:
!name.empty()
obj != 0
References TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::tbox::StatisticRestartDatabase::StatisticRestartDatabase().
void SAMRAI::tbox::RestartManager::unregisterRestartItem (const std::string & name)
Removes the object with the specified name from the list of restartable items.
Precondition:
!name.empty()
References TBOX_ASSERT.
Referenced by SAMRAI::tbox::StatisticRestartDatabase::~StatisticRestartDatabase().
void SAMRAI::tbox::RestartManager::clearRestartItems () [inline]
Clear all restart items managed by the restart manager.
Referenced by RestartManager().
void SAMRAI::tbox::RestartManager::writeRestartFile (const std::string & root_dirname) [inline]
Write all objects registered to as restart objects to the restart database. The string argument is the name of the root of restart directory.
Note: This method creates/uses a restart directory structure with 00000 as the restore number.
Referenced by writeRestartFile(), and writeRestartToDatabase().
void SAMRAI::tbox::RestartManager::writeRestartFile (const std::string & root_dirname, const int restore_num)
Write all objects registered to as restart objects to the restart database. The string argument is the name of the root of restart directory. The integer argument is the identification number associated with the restart files generated.
Precondition:
hasDatabaseFactory()
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), hasDatabaseFactory(), SAMRAI::tbox::Utilities::processorToString(), TBOX_ERROR, and writeRestartFile().
void SAMRAI::tbox::RestartManager::writeRestartToDatabase ()
Write all objects registered to as restart objects to the restart database.
Precondition:
hasRootDatabase()
References hasRootDatabase(), TBOX_ERROR, and writeRestartFile().
void SAMRAI::tbox::RestartManager::registerSingletonSubclassInstance (RestartManager * subclass_instance) [protected]
Initialize Singleton instance with instance of subclass. This function is used to make the singleton object unique when inheriting from this base class.
Precondition:
!s_manager_instance
References TBOX_ERROR.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/RestartManager.h
source/SAMRAI/tbox/RestartManager.C