SAMRAI: SAMRAI::xfer::RefineCopyTransaction Class Reference
SAMRAI::xfer::RefineCopyTransaction Class Reference
Class RefineCopyTransaction represents a single copy communication transaction between two processors or a local data copy for refine schedules. Note that to there is an implicit hand-shaking between objects of this class and the RefineSchedule object that constructs them. Following the refine schedule implementation, the source patch data index for a copy transaction always refers to the source data and the destination patch data index for a copy transaction is always the scratch data, all as defined in the RefineClasses class.
#include <source/SAMRAI/xfer/RefineCopyTransaction.h>
Public Member Functions
RefineCopyTransaction (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_box, const hier::Box &src_box, const RefineClasses::Data **refine_data, int item_id)
virtual ~RefineCopyTransaction ()
virtual bool canEstimateIncomingMessageSize ()
virtual size_t computeIncomingMessageSize ()
virtual size_t computeOutgoingMessageSize ()
virtual int getSourceProcessor ()
virtual int getDestinationProcessor ()
virtual void packStream (tbox::MessageStream &stream)
virtual void unpackStream (tbox::MessageStream &stream)
virtual void copyLocalData ()
virtual void printClassData (std::ostream &stream) const
Detailed Description
Class RefineCopyTransaction represents a single copy communication transaction between two processors or a local data copy for refine schedules. Note that to there is an implicit hand-shaking between objects of this class and the RefineSchedule object that constructs them. Following the refine schedule implementation, the source patch data index for a copy transaction always refers to the source data and the destination patch data index for a copy transaction is always the scratch data, all as defined in the RefineClasses class.
See also:
xfer::RefineSchedule
xfer::RefineClasses
tbox::Schedule
tbox::Transaction
Constructor & Destructor Documentation
SAMRAI::xfer::RefineCopyTransaction::RefineCopyTransaction (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_box, const hier::Box & src_box, const RefineClasses::Data ** refine_data, int item_id)
Construct a transaction with the specified source and destination levels, patches, and patch data components found in the refine class item with the given id owned by the calling refine schedule. In general, this constructor is called by a RefineSchedule object for each data transaction (not involving time interpolation) that must occur. This transaction will be responsible for one of the following: (1) a local data copy, (2) packing a message stream with source patch data, or (3) unpacking destination patch data from a message stream.
Parameters:
dst_level boost::shared_ptr to destination patch level.
src_level boost::shared_ptr to source patch level.
overlap boost::shared_ptr to overlap region between patches.
dst_box Destination Box in destination patch level.
src_box Source Box in source patch level.
refine_data Pointer to array of refine data items
item_id Integer id of refine data item owned by refine schedule.
Precondition:
dst_level
src_level
overlap
dst_box.getLocalId() >= 0
src_box.getLocalId() >= 0
refine_data != 0
refine_item_id >= 0
(dst_level->getDim() == src_level->getDim()) && (dst_level->getDim() == dst_box.getDim()) && (dst_level->getDim() == src_box.getDim())
References SAMRAI::hier::Box::getGlobalId(), SAMRAI::hier::Box::getLocalId(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
SAMRAI::xfer::RefineCopyTransaction::~RefineCopyTransaction () [virtual]
The virtual destructor for the copy transaction releases all memory associated with the transaction.
Member Function Documentation
bool SAMRAI::xfer::RefineCopyTransaction::canEstimateIncomingMessageSize () [virtual]
Return a boolean indicating whether this transaction can estimate the size of an incoming message. If this is false, then a different communication protocol kicks in and the message size is transmitted between boxes.
Implements SAMRAI::tbox::Transaction.
size_t SAMRAI::xfer::RefineCopyTransaction::computeIncomingMessageSize () [virtual]
Return the integer buffer space (in bytes) needed for the incoming message. This routine is only called if the transaction can estimate the size of the incoming message. See canEstimateIncomingMessageSize().
Implements SAMRAI::tbox::Transaction.
size_t SAMRAI::xfer::RefineCopyTransaction::computeOutgoingMessageSize () [virtual]
Return the integer buffer space (in bytes) needed for the outgoing message.
Implements SAMRAI::tbox::Transaction.
int SAMRAI::xfer::RefineCopyTransaction::getSourceProcessor () [virtual]
Return the sending processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
int SAMRAI::xfer::RefineCopyTransaction::getDestinationProcessor () [virtual]
Return the receiving processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::RefineCopyTransaction::packStream (tbox::MessageStream & stream) [virtual]
Pack the transaction data into the message stream.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::RefineCopyTransaction::unpackStream (tbox::MessageStream & stream) [virtual]
Unpack the transaction data from the message stream.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::RefineCopyTransaction::copyLocalData () [virtual]
Perform the local data copy for the transaction.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::PatchData::copy().
void SAMRAI::xfer::RefineCopyTransaction::printClassData (std::ostream & stream) const [virtual]
Print out transaction information.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::xfer::RefineClasses::Data::d_scratch, and SAMRAI::xfer::RefineClasses::Data::d_src.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/RefineCopyTransaction.h
source/SAMRAI/xfer/RefineCopyTransaction.C