SAMRAI: SAMRAI::pdat::NodeIterator Class Reference
SAMRAI::pdat::NodeIterator Class Reference
#include <source/SAMRAI/pdat/NodeIterator.h>
Public Member Functions
NodeIterator (const NodeIterator &iterator)
NodeIterator & operator= (const NodeIterator &iterator)
~NodeIterator ()
const NodeIndex & operator* () const
const NodeIndex * operator-> () const
NodeIterator & operator++ ()
NodeIterator operator++ (int)
bool operator== (const NodeIterator &iterator) const
bool operator!= (const NodeIterator &iterator) const
Friends
NodeIterator NodeGeometry::begin (const hier::Box &box)
NodeIterator NodeGeometry::end (const hier::Box &box)
Detailed Description
Class NodeIterator is an iterator that provides methods for stepping through the index space associated with a node centered box. The indices are enumerated in column-major (e.g., Fortran) order. The iterator should be used as follows:
 * hier::Box box;
 * ...
 * NodeIterator cend(box, false);
 * for (NodeIterator c(box, true); c != cend; ++c) {
 *    // use index c of the box
 * }
 *
Note that the node iterator may not compile to efficient code, depending on your compiler. Many compilers are not smart enough to optimize the looping constructs and indexing operations.
See also:
NodeData
NodeGeometry
NodeIndex
Constructor & Destructor Documentation
SAMRAI::pdat::NodeIterator::NodeIterator (const NodeIterator & iterator)
Copy constructor for the node iterator
SAMRAI::pdat::NodeIterator::~NodeIterator ()
Destructor for the node iterator.
Member Function Documentation
NodeIterator& SAMRAI::pdat::NodeIterator::operator= (const NodeIterator & iterator) [inline]
Assignment operator for the node iterator.
const NodeIndex& SAMRAI::pdat::NodeIterator::operator* () const [inline]
Extract the node index corresponding to the iterator position in the box.
const NodeIndex* SAMRAI::pdat::NodeIterator::operator-> () const [inline]
Extract a pointer to the node index corresponding to the iterator position in the box.
NodeIterator & SAMRAI::pdat::NodeIterator::operator++ ()
Pre-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
NodeIterator SAMRAI::pdat::NodeIterator::operator++ (int)
Post-increment the iterator to point to the next index in the box.
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
bool SAMRAI::pdat::NodeIterator::operator== (const NodeIterator & iterator) const [inline]
Test two iterators for equality (same index value).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
bool SAMRAI::pdat::NodeIterator::operator!= (const NodeIterator & iterator) const [inline]
Test two iterators for inequality (different index values).
References SAMRAI::hier::Box::isIdEqual(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
Friends And Related Function Documentation
NodeIterator NodeGeometry::begin (const hier::Box & box) [friend]
NodeIterator NodeGeometry::end (const hier::Box & box) [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/NodeIterator.h
source/SAMRAI/pdat/NodeIterator.C