SAMRAI: SAMRAI::pdat::NodeData< TYPE > Class Template Reference
SAMRAI::pdat::NodeData< TYPE > Class Template Reference
Class NodeData<TYPE> provides an implementation for data defined at nodes on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a node data object represents data of some template TYPE and depth at the nodes of the cells in the box. Here, depth indicates the number of data values at each node index location. The NodeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and node-centered data.
#include <source/SAMRAI/pdat/NodeData.h>
Public Types
typedef NodeIterator iterator
Public Member Functions
NodeData (const hier::Box &box, int depth, const hier::IntVector &ghosts)
The constructor for a node data object.
virtual ~NodeData ()
The virtual destructor for a node data object.
int getDepth () const
Return the depth (e.g., the number of components in each spatial location) of the array.
TYPE * getPointer (int depth=0)
Get a pointer to the beginning of a particular depth component of the node centered array.
const TYPE * getPointer (int depth=0) const
Get a const pointer to the beginning of a particular depth component of the node centered array.
TYPE & operator() (const NodeIndex &i, int depth=0)
Return a reference to the data entry corresponding to a given node index and depth.
const TYPE & operator() (const NodeIndex &i, int depth=0) const
Return a const reference to the data entry corresponding to a given node index and depth.
ArrayData< TYPE > & getArrayData ()
Return a reference to the array data object of the node centered array.
const ArrayData< TYPE > & getArrayData () const
Return a const reference to the array data object of the node centered array.
virtual void copy (const hier::PatchData &src)
A fast copy from source to destination (i.e., this) patch data object.
virtual void copy2 (hier::PatchData &dst) const
A fast copy from source (i.e., this) to destination patch data object.
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Copy data from source to destination (i.e., this) patch data object on the given overlap.
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
Copy data from source (i.e., this) to destination patch data object on the given overlap.
void copyOnBox (const NodeData< TYPE > &src, const hier::Box &box)
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
void copyDepth (int dst_depth, const NodeData< TYPE > &src, int src_depth)
Fast copy (i.e., source and this node data objects are defined over the same box) from the given node source data object to this destination node data object at the specified depths.
virtual bool canEstimateStreamSizeFromBox () const
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
virtual size_t getDataStreamSize (const hier::BoxOverlap &overlap) const
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be a NodeOverlap of the same DIM.
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be a NodeOverlap of the same DIM.
void fill (const TYPE &t, int d=0)
Fill all values at depth d with the value t.
void fill (const TYPE &t, const hier::Box &box, int d=0)
Fill all values at depth d within the box with the value t.
void fillAll (const TYPE &t)
Fill all depth components with value t.
void fillAll (const TYPE &t, const hier::Box &box)
Fill all depth components within the box with value t.
void print (const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all node data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
void print (const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all node data values at the given array depth in the specified box.
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
Check that class version and restart file version are equal. If so, read data members from the restart database.
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write out the class version number and other data members to the restart database.
Static Public Member Functions
static size_t getSizeOfData (const hier::Box &box, int depth, const hier::IntVector &ghosts)
Calculate the amount of memory needed to represent node- centered data over a CELL-centered AMR index space box.
Detailed Description
template<class TYPE>
class SAMRAI::pdat::NodeData< TYPE >
Class NodeData<TYPE> provides an implementation for data defined at nodes on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a node data object represents data of some template TYPE and depth at the nodes of the cells in the box. Here, depth indicates the number of data values at each node index location. The NodeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and node-centered data.
A node data array is stored in (i,...,k,d) order, where i,...,k indicates spatial indices and the d indicates the component depth at that locaion. Memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory. For example, a three-dimensional node data object created over a CELL-centered AMR index space box [l0:u0,l1:u1,l2:u2] allocates a data array sized as
 *
 *   [ l0 : u0+1 ,
 *     l1 : u1+1,
 *     l2 : u2+1 , d ]
 *
 *
Other spatial dimensions are represented similarly.
The data type TYPE must define a default constructor (that takes no arguments) and also the assignment operator.
See also:
ArrayData
hier::PatchData
NodeDataFactory
NodeIndex
NodeIterator
NodeGeometry
Member Typedef Documentation
template<class TYPE> typedef NodeIterator SAMRAI::pdat::NodeData< TYPE >::iterator
The node iterator iterates over the elements of a node centered box geometry. This typedef is a convenience for using the NodeIterator class.
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::NodeData< TYPE >::NodeData (const hier::Box & box, int depth, const hier::IntVector & ghosts) [inline]
The constructor for a node data object.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the node data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the node data will be allocated.
Precondition:
box.getDim() == ghosts.getDim()
depth > 0
ghosts.min() >= 0
References SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::NodeGeometry::toNodeBox().
template<class TYPE > SAMRAI::pdat::NodeData< TYPE >::~NodeData () [inline, virtual]
The virtual destructor for a node data object.
Member Function Documentation
template<class TYPE > size_t SAMRAI::pdat::NodeData< TYPE >::getSizeOfData (const hier::Box & box, int depth, const hier::IntVector & ghosts) [inline, static]
Calculate the amount of memory needed to represent node- centered data over a CELL-centered AMR index space box.
This function assumes that the amount of memory needed for TYPE is sizeof(TYPE). If this is not the case, then a specialized function must be defined.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the node data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the node data will be allocated.
Precondition:
box.getDim() == ghosts.getDim()
depth > 0
References SAMRAI::hier::Box::grow(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::NodeGeometry::toNodeBox().
template<class TYPE > int SAMRAI::pdat::NodeData< TYPE >::getDepth () const [inline]
Return the depth (e.g., the number of components in each spatial location) of the array.
template<class TYPE > TYPE * SAMRAI::pdat::NodeData< TYPE >::getPointer (int depth = 0) [inline]
Get a pointer to the beginning of a particular depth component of the node centered array.
Precondition:
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT.
template<class TYPE > const TYPE * SAMRAI::pdat::NodeData< TYPE >::getPointer (int depth = 0) const [inline]
Get a const pointer to the beginning of a particular depth component of the node centered array.
Precondition:
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::NodeData< TYPE >::operator() (const NodeIndex & i, int depth = 0) [inline]
Return a reference to the data entry corresponding to a given node index and depth.
Precondition:
getDim() == i.getDim()
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > const TYPE & SAMRAI::pdat::NodeData< TYPE >::operator() (const NodeIndex & i, int depth = 0) const [inline]
Return a const reference to the data entry corresponding to a given node index and depth.
Precondition:
getDim() == i.getDim()
(depth >= 0) && (depth < getDepth())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > ArrayData< TYPE > & SAMRAI::pdat::NodeData< TYPE >::getArrayData () [inline]
Return a reference to the array data object of the node centered array.
Referenced by SAMRAI::pdat::OuternodeData< TYPE >::copyDepth(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth2(), and SAMRAI::pdat::NodeData< TYPE >::copyOnBox().
template<class TYPE > const ArrayData< TYPE > & SAMRAI::pdat::NodeData< TYPE >::getArrayData () const [inline]
Return a const reference to the array data object of the node centered array.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy from source to destination (i.e., this) patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, source data must be a NodeData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
References SAMRAI::hier::PatchData::copy2(), SAMRAI::hier::Box::empty(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy from source (i.e., this) to destination patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, destination data must be a NodeData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<NodeData<TYPE> *>(&dst) != 0
References SAMRAI::hier::Box::empty(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from source to destination (i.e., this) patch data object on the given overlap.
Currently, source data must be NodeData of the same DIM and TYPE and the overlap must be a NodeOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
References SAMRAI::hier::PatchData::copy2(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from source (i.e., this) to destination patch data object on the given overlap.
Currently, destination data must be NodeData of the same DIM and TYPE and the overlap must be a NodeOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<NodeData<TYPE> *>(&dst) != 0
dynamic_cast<const NodeOverlap *>(&overlap) != 0
References SAMRAI::hier::Transformation::NO_ROTATE, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::copyOnBox (const NodeData< TYPE > & src, const hier::Box & box) [inline]
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
Precondition:
(getDim() == src.getDim()) && (getDim() == box.getDim())
References SAMRAI::pdat::NodeData< TYPE >::getArrayData(), TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::NodeGeometry::toNodeBox().
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::copyDepth (int dst_depth, const NodeData< TYPE > & src, int src_depth) [inline]
Fast copy (i.e., source and this node data objects are defined over the same box) from the given node source data object to this destination node data object at the specified depths.
Precondition:
getDim() == src.getDim()
References SAMRAI::hier::Box::empty(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::NodeData< TYPE >::canEstimateStreamSizeFromBox () const [inline, virtual]
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Implements SAMRAI::hier::PatchData.
template<class TYPE > size_t SAMRAI::pdat::NodeData< TYPE >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Precondition:
dynamic_cast<const NodeOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::NodeOverlap::getDestinationBoxContainer(), SAMRAI::pdat::NodeOverlap::getSourceOffset(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be a NodeOverlap of the same DIM.
Precondition:
dynamic_cast<const NodeOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::NodeOverlap::getDestinationBoxContainer(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::pdat::NodeOverlap::getTransformation(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be a NodeOverlap of the same DIM.
Precondition:
dynamic_cast<const NodeOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::NodeOverlap::getDestinationBoxContainer(), SAMRAI::pdat::NodeOverlap::getSourceOffset(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::fill (const TYPE & t, int d = 0) [inline]
Fill all values at depth d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::fill (const TYPE & t, const hier::Box & box, int d = 0) [inline]
Fill all values at depth d within the box with the value t.
Precondition:
getDim() == box.getDim()
(d >= 0) && (d < getDepth())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::NodeGeometry::toNodeBox().
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all depth components with value t.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all depth components within the box with value t.
Precondition:
getDim() == box.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::NodeGeometry::toNodeBox().
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::print (const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all node data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to node index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::print (const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all node data values at the given array depth in the specified box.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to node index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::NodeGeometry::begin(), SAMRAI::pdat::NodeGeometry::end(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check that class version and restart file version are equal. If so, read data members from the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::NodeData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number and other data members to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/NodeData.h
source/SAMRAI/pdat/NodeData.C