SAMRAI: SAMRAI::tbox::ReferenceCounter Class Reference
SAMRAI::tbox::ReferenceCounter Class Reference
#include <source/SAMRAI/tbox/ReferenceCounter.h>
Public Member Functions
ReferenceCounter ()
~ReferenceCounter ()
bool deleteReference ()
void addReference ()
void * operator new (size_t bytes)
void operator delete (void *what)
Static Public Member Functions
static bool isFinalized ()
Detailed Description
Class ReferenceCounter manages the shared reference counter and arena resources used by Array. It uses a local free pool of objects to speed memory allocation and deallocation. The locally cached free pool can be freed by calling freeCachedCopies().
{Do not subclass!} Changing the size of a ReferenceCounter object will cause my simple memory allocation mechanism to break in horrible and disgusting ways.
See also:
Array
Constructor & Destructor Documentation
SAMRAI::tbox::ReferenceCounter::ReferenceCounter ()
Create a ReferenceCounter. The number of references is set to one.
SAMRAI::tbox::ReferenceCounter::~ReferenceCounter ()
Destructor for ReferenceCounter. The destructor releases the managed memory arena if its count has gone to zero.
Member Function Documentation
bool SAMRAI::tbox::ReferenceCounter::deleteReference () [inline]
Decrement the number of references. True is returned if the reference count has gone to zero; false otherwise.
Referenced by SAMRAI::tbox::Array< TYPE >::clear(), SAMRAI::tbox::Array< TYPE >::erase(), SAMRAI::tbox::Array< TYPE >::operator=(), SAMRAI::tbox::Array< TYPE >::setNull(), and SAMRAI::tbox::Array< TYPE >::~Array().
void SAMRAI::tbox::ReferenceCounter::addReference () [inline]
Increment the number of references.
Referenced by SAMRAI::tbox::Array< TYPE >::Array(), and SAMRAI::tbox::Array< TYPE >::operator=().
void * SAMRAI::tbox::ReferenceCounter::operator new (size_t bytes)
Class-specific operator new. Data is allocated off of an internal free list to speed memory allocation.
References isFinalized().
void SAMRAI::tbox::ReferenceCounter::operator delete (void * what)
Class-specific operator delete. Freed data is returned to an internal free list for re-use by operator new.
References isFinalized().
static bool SAMRAI::tbox::ReferenceCounter::isFinalized () [inline, static]
Returns true if ReferenceCounter class has been be stopped. This method is used only for a debugging check assert in the pointer class and should not normally be used.
Referenced by operator delete(), and operator new().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/ReferenceCounter.h
source/SAMRAI/tbox/ReferenceCounter.C