SAMRAI: SAMRAI::xfer::CoarsenCopyTransaction Class Reference
SAMRAI::xfer::CoarsenCopyTransaction Class Reference
Class CoarsenCopyTransaction represents a single copy communication transaction between two processors or a local data copy for coaren schedules. Note that to there is an implicit hand-shaking between objects of this class and the CoarsenSchedule object that constructs them. Following the coarsen schedule implementation, the source patch data index for a copy transaction always refers to the source data, and the destination patch data index for a copy transaction is always the destination data, all as defined in the CoarsenClasses class.
#include <source/SAMRAI/xfer/CoarsenCopyTransaction.h>
Public Member Functions
CoarsenCopyTransaction (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_box, const hier::Box &src_box, const CoarsenClasses::Data **coarsen_data, int item_id)
virtual ~CoarsenCopyTransaction ()
virtual bool canEstimateIncomingMessageSize ()
virtual size_t computeIncomingMessageSize ()
virtual size_t computeOutgoingMessageSize ()
virtual int getSourceProcessor ()
virtual int getDestinationProcessor ()
virtual void packStream (tbox::MessageStream &stream)
virtual void unpackStream (tbox::MessageStream &stream)
virtual void copyLocalData ()
virtual void printClassData (std::ostream &stream) const
Detailed Description
Class CoarsenCopyTransaction represents a single copy communication transaction between two processors or a local data copy for coaren schedules. Note that to there is an implicit hand-shaking between objects of this class and the CoarsenSchedule object that constructs them. Following the coarsen schedule implementation, the source patch data index for a copy transaction always refers to the source data, and the destination patch data index for a copy transaction is always the destination data, all as defined in the CoarsenClasses class.
See also:
xfer::CoarsenSchedule
xfer::CoarsenClasses
tbox::Schedule
tbox::Transaction
Constructor & Destructor Documentation
SAMRAI::xfer::CoarsenCopyTransaction::CoarsenCopyTransaction (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_box, const hier::Box & src_box, const CoarsenClasses::Data ** coarsen_data, int item_id)
Construct a transaction with the specified source and destination levels, patches, and patch data components found in the coarsen class item with the given id owned by the calling coarsen schedule. In general, this constructor is called by a CoarsenSchedule object for each data transaction (not involving time interpolation) that must occur. This transaction will be responsible for one of the following: (1) a local data copy, (2) packing a message stream with source patch data, or (3) unpacking destination patch data from a message stream.
Parameters:
dst_level boost::shared_ptr to destination patch level.
src_level boost::shared_ptr to source patch level.
overlap boost::shared_ptr to overlap region between patches.
dst_box Destination Box in destination patch level.
src_box Source Box in source patch level.
coarsen_data Pointer to array of coarsen data items
item_id Integer id of coarsen data item owned by coarsen schedule.
Precondition:
dst_level
src_level
overlap
(dst_level->getDim() == src_level->getDim()) && (dst_level->getDim() == dst_box.getDim()) && (dst_level->getDim() == src_box.getDim())
dst_box.getLocalId() >= 0
src_box.getLocalId() >= 0
coarsen_data != 0
item_id >= 0
References SAMRAI::hier::Box::getGlobalId(), SAMRAI::hier::Box::getLocalId(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
SAMRAI::xfer::CoarsenCopyTransaction::~CoarsenCopyTransaction () [virtual]
The virtual destructor for the copy transaction releases all memory associated with the transaction.
Member Function Documentation
bool SAMRAI::xfer::CoarsenCopyTransaction::canEstimateIncomingMessageSize () [virtual]
Return a boolean indicating whether this transaction can estimate the size of an incoming message. If this is false, then a different communication protocol kicks in and the message size is transmitted between boxes.
Implements SAMRAI::tbox::Transaction.
size_t SAMRAI::xfer::CoarsenCopyTransaction::computeIncomingMessageSize () [virtual]
Return the integer buffer space (in bytes) needed for the incoming message. This routine is only called if the transaction can estimate the size of the incoming message. See canEstimateIncomingMessageSize().
Implements SAMRAI::tbox::Transaction.
size_t SAMRAI::xfer::CoarsenCopyTransaction::computeOutgoingMessageSize () [virtual]
Return the integer buffer space (in bytes) needed for the outgoing message.
Implements SAMRAI::tbox::Transaction.
int SAMRAI::xfer::CoarsenCopyTransaction::getSourceProcessor () [virtual]
Return the sending processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
int SAMRAI::xfer::CoarsenCopyTransaction::getDestinationProcessor () [virtual]
Return the receiving processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::CoarsenCopyTransaction::packStream (tbox::MessageStream & stream) [virtual]
Pack the transaction data into the message stream.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::CoarsenCopyTransaction::unpackStream (tbox::MessageStream & stream) [virtual]
Unpack the transaction data from the message stream.
Implements SAMRAI::tbox::Transaction.
void SAMRAI::xfer::CoarsenCopyTransaction::copyLocalData () [virtual]
Perform the local data copy for the transaction.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::PatchData::copy().
void SAMRAI::xfer::CoarsenCopyTransaction::printClassData (std::ostream & stream) const [virtual]
Print out transaction information.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::xfer::CoarsenClasses::Data::d_dst, and SAMRAI::xfer::CoarsenClasses::Data::d_src.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/CoarsenCopyTransaction.h
source/SAMRAI/xfer/CoarsenCopyTransaction.C