SAMRAI: SAMRAI::algs::OuteredgeSumTransaction Class Reference
SAMRAI::algs::OuteredgeSumTransaction Class Reference
Class OuteredgeSumTransaction represents a single outeredge data sum communication transaction between two processors or a local data sum for refine schedules. Note that to there is an implicit hand-shaking between objects of this class and the xfer::RefineSchedule object that constructs them. Following the refine schedule implementation, the source patch data index for a transaction always refers to the source data and the destination patch data index for a transaction is always the scratch data, all as defined in the xfer::RefineClasses class.
#include <source/SAMRAI/algs/OuteredgeSumTransaction.h>
Public Member Functions
OuteredgeSumTransaction (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_node, const hier::Box &src_node, const xfer::RefineClasses::Data **refine_data, int item_id)
virtual ~OuteredgeSumTransaction ()
virtual bool canEstimateIncomingMessageSize ()
virtual size_t computeIncomingMessageSize ()
virtual size_t computeOutgoingMessageSize ()
virtual int getSourceProcessor ()
virtual int getDestinationProcessor ()
virtual void packStream (tbox::MessageStream &stream)
virtual void unpackStream (tbox::MessageStream &stream)
virtual void copyLocalData ()
virtual void printClassData (std::ostream &stream) const
Detailed Description
Class OuteredgeSumTransaction represents a single outeredge data sum communication transaction between two processors or a local data sum for refine schedules. Note that to there is an implicit hand-shaking between objects of this class and the xfer::RefineSchedule object that constructs them. Following the refine schedule implementation, the source patch data index for a transaction always refers to the source data and the destination patch data index for a transaction is always the scratch data, all as defined in the xfer::RefineClasses class.
See also:
xfer::RefineSchedule
xfer::RefineClasses
tbox::Schedule
tbox::Transaction
Constructor & Destructor Documentation
SAMRAI::algs::OuteredgeSumTransaction::OuteredgeSumTransaction (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_node, const hier::Box & src_node, const xfer::RefineClasses::Data ** refine_data, int item_id)
Construct a transaction with the specified source and destination levels, patches, and patch data components found in the refine class item with the given id owned by the calling refine schedule. In general, this constructor is called by a xfer::RefineSchedule object for each data transaction (specifically summing outeredge data) that must occur. This transaction will be responsible for one of the following: (1) a local data copy and sum, or (2) packing a message stream with source patch data, or (3) unpacking and summing destination patch data from a message stream.
Parameters:
dst_level boost::shared_ptr to destination patch level.
src_level boost::shared_ptr to source patch level.
overlap boost::shared_ptr to overlap region between patches.
dst_node Destination box.
src_node Source box.
refine_data Pointer to array of refine data items
item_id Integer id of refine data item owned by refine schedule.
Precondition:
dst_level
src_level
overlap
dst_node.getLocalId() >= 0
src_node.getLocalId() >= 0
refine_data != 0
item_id >= 0
(dst_level->getDim() == src_level->getDim()) && (dst_level->getDim() == dst_node.getDim()) && (dst_level->getDim() == src_node.getDim())
References SAMRAI::hier::Box::getLocalId(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
SAMRAI::algs::OuteredgeSumTransaction::~OuteredgeSumTransaction () [virtual]
The virtual destructor for the copy transaction releases all memory associated with the transaction.
Member Function Documentation
bool SAMRAI::algs::OuteredgeSumTransaction::canEstimateIncomingMessageSize () [virtual]
Return a boolean indicating whether this transaction can estimate the size of an incoming message. If this is false, then a different communication protocol kicks in and the message size is transmitted between edges.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::Box::getGlobalId(), and SAMRAI::hier::Box::getOwnerRank().
size_t SAMRAI::algs::OuteredgeSumTransaction::computeIncomingMessageSize () [virtual]
Return the integer buffer space (in bytes) needed for the incoming message. This routine is only called if the transaction can estimate the size of the incoming message. See canEstimateIncomingMessageSize().
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::Box::getGlobalId().
size_t SAMRAI::algs::OuteredgeSumTransaction::computeOutgoingMessageSize () [virtual]
Return the integer buffer space (in bytes) needed for the outgoing message.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::Box::getGlobalId().
int SAMRAI::algs::OuteredgeSumTransaction::getSourceProcessor () [virtual]
Return the sending processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::Box::getOwnerRank().
int SAMRAI::algs::OuteredgeSumTransaction::getDestinationProcessor () [virtual]
Return the receiving processor number for the communications transaction.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::Box::getOwnerRank().
void SAMRAI::algs::OuteredgeSumTransaction::packStream (tbox::MessageStream & stream) [virtual]
Pack the transaction data into the message stream.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::hier::Box::getGlobalId().
void SAMRAI::algs::OuteredgeSumTransaction::unpackStream (tbox::MessageStream & stream) [virtual]
Unpack the transaction data from the message stream.
Precondition:
d_dst_level->getPatch(d_dst_node.getGlobalId())->getPatchData(_refine_data[d_item_id]->d_scratch) is actually a boost::shared_ptr<pdat::OuteredgeData<double> >
Implements SAMRAI::tbox::Transaction.
References BOOST_CAST, SAMRAI::hier::Box::getGlobalId(), and TBOX_ASSERT.
void SAMRAI::algs::OuteredgeSumTransaction::copyLocalData () [virtual]
Perform the local data copy for the transaction.
Precondition:
d_dst_level->getPatch(d_dst_node.getGlobalId())->getPatchData(d_refine_data[d_item_id]->d_scratch) is actually a boost::shared_ptr<pdat::OuteredgeData<double> >
d_src_level->getPatch(d_src_node.getGlobalId())->getPatchData(d_refine_data[d_item_id]->d_src) is actually a boost::shared_ptr<pdat::OuteredgeData<double> >
Implements SAMRAI::tbox::Transaction.
References BOOST_CAST, SAMRAI::hier::Box::getGlobalId(), and TBOX_ASSERT.
void SAMRAI::algs::OuteredgeSumTransaction::printClassData (std::ostream & stream) const [virtual]
Print out transaction information.
Implements SAMRAI::tbox::Transaction.
References SAMRAI::xfer::RefineClasses::Data::d_scratch, and SAMRAI::xfer::RefineClasses::Data::d_src.
The documentation for this class was generated from the following files:
source/SAMRAI/algs/OuteredgeSumTransaction.h
source/SAMRAI/algs/OuteredgeSumTransaction.C