SAMRAI: SAMRAI::hier::PatchData Class Reference
SAMRAI::hier::PatchData Class Reference
#include <source/SAMRAI/hier/PatchData.h>
Public Member Functions
PatchData (const Box &domain, const IntVector &ghosts)
virtual ~PatchData ()
const Box & getBox () const
const Box & getGhostBox () const
const IntVector & getGhostCellWidth () const
void setTime (const double timestamp)
double getTime () const
virtual void copy (const PatchData &src)=0
virtual void copy2 (PatchData &dst) const =0
virtual void copy (const PatchData &src, const BoxOverlap &overlap)=0
virtual void copy2 (PatchData &dst, const BoxOverlap &overlap) const =0
virtual bool canEstimateStreamSizeFromBox () const =0
virtual int getDataStreamSize (const BoxOverlap &overlap) const =0
virtual void packStream (tbox::MessageStream &stream, const BoxOverlap &overlap) const =0
virtual void unpackStream (tbox::MessageStream &stream, const BoxOverlap &overlap)=0
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
const tbox::Dimension & getDim () const
Return the dimension of this object.
Protected Member Functions
void setGhostBox (const Box &ghost_box)
Detailed Description
Class PatchData is a pure virtual base class for the data storage defined over a box. Patch data objects are generally contained within a patch. Patch data defines the abstract virtual functions for data management and communication that must be supplied by the subclasses. Subclasses implement the virtual functions as appropriate for the derived type; for example, cell centered objects will copy data differently than face centered objects.
Patch data objects are created by patch data factories and associated subclasses. This separation into abstract factory and concrete implementation subclasses facilitates the creation of new patch data subtypes. See the Design Patterns book for more details about the Abstract Factory pattern.
The copy and pack/unpack functions in the patch data object take box overlap descriptions that describe the index space over which data is to be copied or packed/unpacked. Box overlaps are computed by the box geometry classes, which are accessed through the patch data factories. Box geometry classes are created by the patch data factories instead of the patch data objects because patch data objects are distributed across memory with patches and therefore may not exist on a particular processor. Patch data factories are guaranteed to exist on all processors independent of the patch-to-processor mapping.
See also:
hier::BoxOverlap
hier::BoxGeometry
hier::Patch
hier::PatchDataFactory
hier::PatchDescriptor
Constructor & Destructor Documentation
SAMRAI::hier::PatchData::PatchData (const Box & domain, const IntVector & ghosts)
The constructor for a patch data object. Patch data objects will manage the interior box over which they are defined and the associated ghost cell width.
Precondition:
domain.getDim() == ghosts.getDim()
References SAMRAI::hier::Box::grow(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::hier::PatchData::~PatchData () [virtual]
The virtual destructor for a patch data object.
Member Function Documentation
const Box& SAMRAI::hier::PatchData::getBox () const [inline]
Return the box over which this patch data object is defined. All objects in the same patch are defined over the same box, although the patch data objects may interpret how to allocate storage for that box in different ways.
Referenced by SAMRAI::pdat::FaceData< TYPE >::copy(), SAMRAI::pdat::OutersideData< TYPE >::copy2(), SAMRAI::pdat::OuterfaceData< TYPE >::copy2(), SAMRAI::pdat::FaceData< TYPE >::copy2(), SAMRAI::pdat::OuternodeData< TYPE >::getDataBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getDataStreamSize(), SAMRAI::pdat::OuternodeData< TYPE >::operator()(), SAMRAI::pdat::OuteredgeData< TYPE >::operator()(), SAMRAI::pdat::OuterfaceData< TYPE >::packStream(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::packStream(), and SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeGhostItems().
const Box& SAMRAI::hier::PatchData::getGhostBox () const [inline]
Return the ghost cell box. The ghost cell box is defined to be the interior box grown by the ghost cell width.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::addItemPointer(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::appendItemPointer(), SAMRAI::pdat::CellData< TYPE >::CellData(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy(), SAMRAI::pdat::EdgeData< TYPE >::EdgeData(), SAMRAI::pdat::FaceData< TYPE >::FaceData(), SAMRAI::pdat::OuteredgeData< TYPE >::getDataBox(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::isElement(), SAMRAI::pdat::NodeData< TYPE >::NodeData(), SAMRAI::pdat::OuteredgeData< TYPE >::OuteredgeData(), SAMRAI::pdat::OuterfaceData< TYPE >::OuterfaceData(), SAMRAI::pdat::OutersideData< TYPE >::OutersideData(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeAllItems(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::removeItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAddItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAddItemPointer(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAppendItem(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::replaceAppendItemPointer(), and SAMRAI::pdat::SideData< TYPE >::SideData().
const IntVector& SAMRAI::hier::PatchData::getGhostCellWidth () const [inline]
Get the ghost cell width associated with this patch data object.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), and SAMRAI::pdat::OuternodeData< TYPE >::getDataBox().
void SAMRAI::hier::PatchData::setTime (const double timestamp) [inline]
Set the simulation time stamp for the patch data type. The simulation time is initialized to zero when the patch data type is created.
double SAMRAI::hier::PatchData::getTime () const [inline]
Get the simulation time stamp for the patch data type.
virtual void SAMRAI::hier::PatchData::copy (const PatchData & src) [pure virtual]
A fast copy between the source and destination. Data is copied from the source into the destination where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). If this copy does not understand how to copy data from the argument, then copy2() is called on the source object.
Referenced by SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::copy2(), SAMRAI::xfer::RefineCopyTransaction::copyLocalData(), and SAMRAI::xfer::CoarsenCopyTransaction::copyLocalData().
virtual void SAMRAI::hier::PatchData::copy2 (PatchData & dst) const [pure virtual]
A fast copy between the source and destination. Data is copied from the source into the destination where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). If this copy does not understand how to copy data from the destination, then it may throw an assertion (aka dump core in a failed assertion).
Referenced by SAMRAI::pdat::SideData< TYPE >::copy(), SAMRAI::pdat::NodeData< TYPE >::copy(), SAMRAI::pdat::FaceData< TYPE >::copy(), SAMRAI::pdat::EdgeData< TYPE >::copy(), and SAMRAI::pdat::CellData< TYPE >::copy().
virtual void SAMRAI::hier::PatchData::copy (const PatchData & src, const BoxOverlap & overlap) [pure virtual]
Copy data from the source into the destination using the designated overlap descriptor. The overlap description will have been computed using the appropriate box geometry objects. If this member function cannot complete the copy from source (e.g., if it doesn't understand the type of source), then copy2() is called on the source object.
virtual void SAMRAI::hier::PatchData::copy2 (PatchData & dst, const BoxOverlap & overlap) const [pure virtual]
Copy data from the source into the destination using the designated overlap descriptor. The overlap description will have been computed using the appropriate box geometry objects If this member function cannot complete the copy from the destination, then it may throw an assertion (aka dump core in a failed assertion).
virtual bool SAMRAI::hier::PatchData::canEstimateStreamSizeFromBox () const [pure virtual]
Determines whether the patch data subclass can estimate the necessary stream size using only index space information. The return value will most likely be true for data types that are fixed size (such as doubles) but will be false for complex data types that allocate their own storage (such as lists of particles). This routine is used to estimate whether a processor can estimate space for incoming messages or whether it needs to receive a message size from the sending processor.
Implemented in SAMRAI::pdat::CellData< TYPE >, SAMRAI::pdat::EdgeData< TYPE >, SAMRAI::pdat::FaceData< TYPE >, SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeData< TYPE >, SAMRAI::pdat::OuteredgeData< TYPE >, SAMRAI::pdat::OuterfaceData< TYPE >, SAMRAI::pdat::OuternodeData< TYPE >, SAMRAI::pdat::OutersideData< TYPE >, and SAMRAI::pdat::SideData< TYPE >.
virtual int SAMRAI::hier::PatchData::getDataStreamSize (const BoxOverlap & overlap) const [pure virtual]
Calculate the number of bytes needed to stream the data lying in the specified box domain. This estimate must be an upper bound on the size of the data in the actual message stream. The upper bound should be close, however, since buffer space will be allocated according to these values, and excess buffer space will waste memory resources.
Implemented in SAMRAI::pdat::CellData< TYPE >, SAMRAI::pdat::EdgeData< TYPE >, SAMRAI::pdat::FaceData< TYPE >, SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeData< TYPE >, SAMRAI::pdat::OuteredgeData< TYPE >, SAMRAI::pdat::OuterfaceData< TYPE >, SAMRAI::pdat::OuternodeData< TYPE >, SAMRAI::pdat::OutersideData< TYPE >, and SAMRAI::pdat::SideData< TYPE >.
virtual void SAMRAI::hier::PatchData::packStream (tbox::MessageStream & stream, const BoxOverlap & overlap) const [pure virtual]
Pack data lying on the specified index set into the output stream. See the abstract stream virtual base class for more information about the packing operators defined for streams.
Implemented in SAMRAI::pdat::CellData< TYPE >, SAMRAI::pdat::EdgeData< TYPE >, SAMRAI::pdat::FaceData< TYPE >, SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeData< TYPE >, SAMRAI::pdat::OuteredgeData< TYPE >, SAMRAI::pdat::OuterfaceData< TYPE >, SAMRAI::pdat::OuternodeData< TYPE >, SAMRAI::pdat::OutersideData< TYPE >, and SAMRAI::pdat::SideData< TYPE >.
virtual void SAMRAI::hier::PatchData::unpackStream (tbox::MessageStream & stream, const BoxOverlap & overlap) [pure virtual]
Unpack data from the message stream into the specified index set. See the abstract stream virtual base class for more information about the packing operators defined for streams.
Implemented in SAMRAI::pdat::CellData< TYPE >, SAMRAI::pdat::EdgeData< TYPE >, SAMRAI::pdat::FaceData< TYPE >, SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeData< TYPE >, SAMRAI::pdat::OuteredgeData< TYPE >, SAMRAI::pdat::OuterfaceData< TYPE >, SAMRAI::pdat::OuternodeData< TYPE >, SAMRAI::pdat::OutersideData< TYPE >, and SAMRAI::pdat::SideData< TYPE >.
void SAMRAI::hier::PatchData::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [virtual]
Checks that class version and restart file version are equal. If so, reads in the data members common to all patch data types from restart database.
Precondition:
restart_db
Reimplemented in SAMRAI::pdat::CellData< TYPE >, SAMRAI::pdat::EdgeData< TYPE >, SAMRAI::pdat::FaceData< TYPE >, SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeData< TYPE >, SAMRAI::pdat::OuteredgeData< TYPE >, SAMRAI::pdat::OuterfaceData< TYPE >, SAMRAI::pdat::OuternodeData< TYPE >, SAMRAI::pdat::OutersideData< TYPE >, and SAMRAI::pdat::SideData< TYPE >.
References SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::PatchData::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [virtual]
Writes out the class version number to the restart database. Then, writes the data members common to all patch data types to database.
Precondition:
restart_db
Reimplemented in SAMRAI::pdat::CellData< TYPE >, SAMRAI::pdat::EdgeData< TYPE >, SAMRAI::pdat::FaceData< TYPE >, SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >, SAMRAI::pdat::NodeData< TYPE >, SAMRAI::pdat::OuteredgeData< TYPE >, SAMRAI::pdat::OuterfaceData< TYPE >, SAMRAI::pdat::OuternodeData< TYPE >, SAMRAI::pdat::OutersideData< TYPE >, and SAMRAI::pdat::SideData< TYPE >.
References SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
const tbox::Dimension& SAMRAI::hier::PatchData::getDim () const [inline]
Return the dimension of this object.
References SAMRAI::hier::Box::getDim().
Referenced by SAMRAI::pdat::SideData< TYPE >::copy(), SAMRAI::pdat::OutersideData< TYPE >::copy(), SAMRAI::pdat::OuterfaceData< TYPE >::copy(), SAMRAI::pdat::FaceData< TYPE >::copy(), SAMRAI::pdat::EdgeData< TYPE >::copy(), SAMRAI::pdat::SideData< TYPE >::copy2(), SAMRAI::pdat::OutersideData< TYPE >::copy2(), SAMRAI::pdat::OuterfaceData< TYPE >::copy2(), SAMRAI::pdat::FaceData< TYPE >::copy2(), SAMRAI::pdat::EdgeData< TYPE >::copy2(), SAMRAI::pdat::SideData< TYPE >::copyDepth(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth(), SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth(), SAMRAI::pdat::FaceData< TYPE >::copyDepth(), SAMRAI::pdat::EdgeData< TYPE >::copyDepth(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth2(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth2(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth2(), SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth2(), SAMRAI::pdat::SideData< TYPE >::copyOnBox(), SAMRAI::pdat::FaceData< TYPE >::copyOnBox(), SAMRAI::pdat::EdgeData< TYPE >::copyOnBox(), SAMRAI::pdat::OuternodeData< TYPE >::dataExists(), SAMRAI::pdat::OuteredgeData< TYPE >::dataExists(), SAMRAI::pdat::EdgeData< TYPE >::EdgeData(), SAMRAI::pdat::FaceData< TYPE >::FaceData(), SAMRAI::pdat::SideData< TYPE >::fill(), SAMRAI::pdat::OutersideData< TYPE >::fill(), SAMRAI::pdat::OuternodeData< TYPE >::fill(), SAMRAI::pdat::OuterfaceData< TYPE >::fill(), SAMRAI::pdat::OuteredgeData< TYPE >::fill(), SAMRAI::pdat::FaceData< TYPE >::fill(), SAMRAI::pdat::EdgeData< TYPE >::fill(), SAMRAI::pdat::SideData< TYPE >::fillAll(), SAMRAI::pdat::OutersideData< TYPE >::fillAll(), SAMRAI::pdat::OuternodeData< TYPE >::fillAll(), SAMRAI::pdat::OuterfaceData< TYPE >::fillAll(), SAMRAI::pdat::OuteredgeData< TYPE >::fillAll(), SAMRAI::pdat::FaceData< TYPE >::fillAll(), SAMRAI::pdat::EdgeData< TYPE >::fillAll(), SAMRAI::pdat::SideData< TYPE >::getArrayData(), SAMRAI::pdat::OutersideData< TYPE >::getArrayData(), SAMRAI::pdat::OuternodeData< TYPE >::getArrayData(), SAMRAI::pdat::OuterfaceData< TYPE >::getArrayData(), SAMRAI::pdat::OuteredgeData< TYPE >::getArrayData(), SAMRAI::pdat::FaceData< TYPE >::getArrayData(), SAMRAI::pdat::EdgeData< TYPE >::getArrayData(), SAMRAI::pdat::OuternodeData< TYPE >::getDataBox(), SAMRAI::pdat::SideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OutersideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuternodeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuterfaceData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OuteredgeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::FaceData< TYPE >::getDataStreamSize(), SAMRAI::pdat::EdgeData< TYPE >::getDataStreamSize(), SAMRAI::pdat::SideData< TYPE >::getFromRestart(), SAMRAI::pdat::OutersideData< TYPE >::getFromRestart(), SAMRAI::pdat::OuternodeData< TYPE >::getFromRestart(), SAMRAI::pdat::OuterfaceData< TYPE >::getFromRestart(), SAMRAI::pdat::OuteredgeData< TYPE >::getFromRestart(), SAMRAI::pdat::FaceData< TYPE >::getFromRestart(), SAMRAI::pdat::EdgeData< TYPE >::getFromRestart(), SAMRAI::pdat::SideData< TYPE >::getPointer(), SAMRAI::pdat::OutersideData< TYPE >::getPointer(), SAMRAI::pdat::OuternodeData< TYPE >::getPointer(), SAMRAI::pdat::OuterfaceData< TYPE >::getPointer(), SAMRAI::pdat::OuteredgeData< TYPE >::getPointer(), SAMRAI::pdat::FaceData< TYPE >::getPointer(), SAMRAI::pdat::EdgeData< TYPE >::getPointer(), SAMRAI::pdat::SideData< TYPE >::operator()(), SAMRAI::pdat::OutersideData< TYPE >::operator()(), SAMRAI::pdat::OuternodeData< TYPE >::operator()(), SAMRAI::pdat::OuterfaceData< TYPE >::operator()(), SAMRAI::pdat::OuteredgeData< TYPE >::operator()(), SAMRAI::pdat::FaceData< TYPE >::operator()(), SAMRAI::pdat::EdgeData< TYPE >::operator()(), SAMRAI::pdat::OuteredgeData< TYPE >::OuteredgeData(), SAMRAI::pdat::OuterfaceData< TYPE >::OuterfaceData(), SAMRAI::pdat::OutersideData< TYPE >::OutersideData(), SAMRAI::pdat::SideData< TYPE >::packStream(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::OuternodeData< TYPE >::packStream(), SAMRAI::pdat::OuterfaceData< TYPE >::packStream(), SAMRAI::pdat::OuteredgeData< TYPE >::packStream(), SAMRAI::pdat::FaceData< TYPE >::packStream(), SAMRAI::pdat::EdgeData< TYPE >::packStream(), SAMRAI::pdat::SideData< TYPE >::print(), SAMRAI::pdat::OutersideData< TYPE >::print(), SAMRAI::pdat::OuternodeData< TYPE >::print(), SAMRAI::pdat::OuterfaceData< TYPE >::print(), SAMRAI::pdat::OuteredgeData< TYPE >::print(), SAMRAI::pdat::FaceData< TYPE >::print(), SAMRAI::pdat::EdgeData< TYPE >::print(), SAMRAI::pdat::SideData< TYPE >::printAxis(), SAMRAI::pdat::FaceData< TYPE >::printAxis(), SAMRAI::pdat::EdgeData< TYPE >::printAxis(), SAMRAI::pdat::OuterfaceData< TYPE >::printAxisFace(), SAMRAI::pdat::OutersideData< TYPE >::printAxisSide(), SAMRAI::pdat::OuternodeData< TYPE >::printAxisSide(), SAMRAI::pdat::OuteredgeData< TYPE >::printAxisSide(), SAMRAI::pdat::SideData< TYPE >::putToRestart(), SAMRAI::pdat::OutersideData< TYPE >::putToRestart(), SAMRAI::pdat::OuternodeData< TYPE >::putToRestart(), SAMRAI::pdat::OuterfaceData< TYPE >::putToRestart(), SAMRAI::pdat::OuteredgeData< TYPE >::putToRestart(), SAMRAI::pdat::FaceData< TYPE >::putToRestart(), SAMRAI::pdat::EdgeData< TYPE >::putToRestart(), SAMRAI::pdat::SideData< TYPE >::SideData(), SAMRAI::pdat::OuternodeData< TYPE >::sum(), SAMRAI::pdat::OuteredgeData< TYPE >::sum(), SAMRAI::pdat::SideData< TYPE >::unpackStream(), SAMRAI::pdat::OutersideData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStream(), SAMRAI::pdat::OuterfaceData< TYPE >::unpackStream(), SAMRAI::pdat::OuteredgeData< TYPE >::unpackStream(), SAMRAI::pdat::FaceData< TYPE >::unpackStream(), SAMRAI::pdat::EdgeData< TYPE >::unpackStream(), SAMRAI::pdat::OuternodeData< TYPE >::unpackStreamAndSum(), and SAMRAI::pdat::OuteredgeData< TYPE >::unpackStreamAndSum().
void SAMRAI::hier::PatchData::setGhostBox (const Box & ghost_box) [inline, protected]
This protected method is used by concrete patch data subclasses to set the ghost box over which the patch data will be allocated. Note that this allows the ghost box to be inconsistant with its standard interpretation as the patch domain box grown by the ghost cell width (as set in the constructor).
This function is included to treat some special cases for concrete patch data types and should be used with caution.
Precondition:
getDim() == ghost_box.getDim()
(ghost_box * getBox()).isSpatiallyEqual(getBox())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchData.h
source/SAMRAI/hier/PatchData.C