SAMRAI: SAMRAI::hier::BoxLevelConnectorUtils Class Reference
SAMRAI::hier::BoxLevelConnectorUtils Class Reference
Utilities for common operating on BoxLevels.
#include <source/SAMRAI/hier/BoxLevelConnectorUtils.h>
Public Member Functions
BoxLevelConnectorUtils ()
Default constructor.
~BoxLevelConnectorUtils ()
Destructor.
void setSanityCheckMethodPreconditions (bool do_check)
Set whether to run expensive sanity checks on input parameters.
void setSanityCheckMethodPostconditions (bool do_check)
Set whether to run expensive sanity checks on output parameters.
void computeBoxesAroundBoundary (BoxContainer &boundary, const IntVector &refinement_ratio, const boost::shared_ptr< const BaseGridGeometry > &grid_geometry, const bool simplify_boundary_boxes=true) const
Given a set of Boxes, compute its boundary as a set of boxes located just outside it.
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
const std::string getObjectName () const
Get the name of this object.
Comparing boxes of two BoxLevels
bool baseNestsInHead (bool *locally_nests, const Connector &connector, const IntVector &base_swell, const IntVector &head_swell, const IntVector &head_nesting_margin, const BoxContainer *domain=0) const
Given an overlap Connector, determine the extent to which the Connector's base nests in its head.
bool baseNestsInHead (bool *locally_nests, const BoxLevel &base, const BoxLevel &head, const IntVector &base_swell, const IntVector &head_swell, const IntVector &head_margin, const BoxContainer *domain=0) const
Given base and head BoxLevels, determine the extent to which the base nests in the head.
void computeExternalParts (boost::shared_ptr< BoxLevel > &external, boost::shared_ptr< MappingConnector > &input_to_external, const Connector &input_to_reference, const IntVector &nesting_width, const BoxContainer &domain=BoxContainer()) const
Compute the parts of one BoxLevel that are external to another BoxLevel.
void computeInternalParts (boost::shared_ptr< BoxLevel > &internal, boost::shared_ptr< MappingConnector > &input_to_internal, const Connector &input_to_reference, const IntVector &nesting_width, const BoxContainer &domain=BoxContainer()) const
Compute the parts of one BoxLevel that are internal to another BoxLevel.
void computeNonIntersectingParts (boost::shared_ptr< BoxLevel > &remainder, boost::shared_ptr< Connector > &input_to_remainder, const Connector &input_to_takeaway) const
Compute parts of a level that do not intersect with another level.
Setting up common MappingConnectors
void makeSortingMap (boost::shared_ptr< BoxLevel > &sorted_box_level, boost::shared_ptr< MappingConnector > &output_map, const BoxLevel &unsorted_box_level, bool sort_boxes_by_corner=true, bool sequentialize_global_indices=true, LocalId initial_sequential_index=LocalId::getZero()) const
void makeRemainderMap (boost::shared_ptr< BoxLevel > &remainder, boost::shared_ptr< MappingConnector > &orig_to_remainder, const MappingConnector &orig_to_rejections) const
Adding periodic images
void addPeriodicImages (BoxLevel &box_level, const BoxContainer &domain_search_tree, const IntVector &threshold_distance) const
Add periodic images to a BoxLevel.
void addPeriodicImagesAndRelationships (BoxLevel &box_level, Connector &box_level_to_anchor, const BoxContainer &domain_search_tree, const Connector &anchor_to_anchor) const
Add periodic images to a BoxLevel and add new relationships to the periodic images.
Detailed Description
Utilities for common operating on BoxLevels.
Objects of this class can be set to perform certain sanity checks on the pre and post conditions of the methods. See setSanityCheckMethodPreconditions() and setSanityCheckMethodPostconditions().
Constructor & Destructor Documentation
SAMRAI::hier::BoxLevelConnectorUtils::BoxLevelConnectorUtils ()
Default constructor.
By default, sanity checks are disabled. To enable them, see setSanityCheckMethodPreconditions() and setSanityCheckMethodPostconditions().
References setTimerPrefix().
SAMRAI::hier::BoxLevelConnectorUtils::~BoxLevelConnectorUtils ()
Destructor.
Member Function Documentation
void SAMRAI::hier::BoxLevelConnectorUtils::setSanityCheckMethodPreconditions (bool do_check) [inline]
Set whether to run expensive sanity checks on input parameters.
Mainly for debugging.
Parameters:
[in] do_check
void SAMRAI::hier::BoxLevelConnectorUtils::setSanityCheckMethodPostconditions (bool do_check) [inline]
Set whether to run expensive sanity checks on output parameters.
Mainly for debugging.
Parameters:
[in] do_check
bool SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead (bool * locally_nests, const Connector & connector, const IntVector & base_swell, const IntVector & head_swell, const IntVector & head_nesting_margin, const BoxContainer * domain = 0) const
Given an overlap Connector, determine the extent to which the Connector's base nests in its head.
This method returns true if the base, grown by base_swell, nests inside the head, grown by head_swell, by a margin of head_nesting_margin. base_swell and head_swell should be non-negative and specified in the base and head index spaces, respectively. head_nesting_margin should be in the head index space.
The Connector width must be at least the sum of the base_swell and the (appropriately converted) head_swell and head_nesting_margin. We require and assume without verifying that the Connector is complete.
If the domain is given, non-nesting parts outside of the domain are disregarded.
Parameters:
[out] locally_nests Whether the local parts of the base nests in the head. This output may vary among the processes.
[in] connector
[in] base_swell the amount that the base is grown by, given in the base index space and non-negative
[in] head_swell the amount that the head is grown by, given in the head index space and non-negative
[in] head_nesting_margin given in the head index space.
[in] domain Domain description, in reference index space, in search tree format.
Returns:
True if the given base BoxLevel nests in the head, otherwise False.
Precondition:
(connector.getBase().getDim() == base_swell.getDim()) && (connector.getBase().getDim() == head_nesting_margin.getDim())
connector.isFinalized()
base_swell >= IntVector::getZero(connector.getBase().getDim())
head_nesting_margin >= IntVector::getZero(connector.getBase().getDim())
References SAMRAI::hier::Connector::assertOverlapCorrectness(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::IntVector::ceilingDivide(), computeExternalParts(), computeInternalParts(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::Connector::getHeadCoarserFlag(), SAMRAI::hier::Connector::getMPI(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::Connector::getRatio(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::Box::grow(), SAMRAI::hier::Connector::growLocalNeighbors(), SAMRAI::hier::Connector::isFinalized(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), SAMRAI::hier::Connector::setBase(), SAMRAI::hier::Connector::setHead(), SAMRAI::hier::Connector::setWidth(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and TBOX_ERROR.
Referenced by baseNestsInHead(), and SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel().
bool SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead (bool * locally_nests, const BoxLevel & base, const BoxLevel & head, const IntVector & base_swell, const IntVector & head_swell, const IntVector & head_margin, const BoxContainer * domain = 0) const
Given base and head BoxLevels, determine the extent to which the base nests in the head.
This method is similar to the version taking a Connector instead of the base and head BoxLevels, except that it will use the base BoxLevel's PersistentOverlapConnectors object to get the base--->head Connector. If such a Connector does not exist, the PersistentOverlapConnectors object will create it, an unscalable operation possibly requiring collective communication.
Parameters:
domain Domain description, in reference index space, in search tree format.
Returns:
Whether the given base BoxLevel nests in the head.
Parameters:
[out] locally_nests Whether the local parts of the base nests in the head. This output may vary among the processes.
[in] base
[in] head
[in] base_swell the amount that the base is grown by, given in the base index space and non-negative
[in] head_swell the amount that the head is grown by, given in the head index space and non-negative
[in] head_margin given in the head index space.
[in] domain Domain description, in reference index space, in search tree format.
Returns:
Whether the given base BoxLevel nests in the head.
Precondition:
head_nesting_margin.getDim() == base_swell.getDim()
head.getMPI() == base.getMPI()
base_swell >= IntVector::getZero(head.getDim())
head_swell >= IntVector::getZero(head.getDim())
head_nesting_margin >= IntVector::getZero(head.getDim())
(head.getRefinementRatio() <= base.getRefinementRatio()) || (head.getRefinementRatio() >= base.getRefinementRatio()) ||
References baseNestsInHead(), SAMRAI::hier::IntVector::ceilingDivide(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
void SAMRAI::hier::BoxLevelConnectorUtils::computeExternalParts (boost::shared_ptr< BoxLevel > & external, boost::shared_ptr< MappingConnector > & input_to_external, const Connector & input_to_reference, const IntVector & nesting_width, const BoxContainer & domain = BoxContainer()) const [inline]
Compute the parts of one BoxLevel that are external to another BoxLevel.
Compare an input BoxLevel to a "reference" BoxLevel. Compute the parts of the input that are external to the reference. Build the "external" BoxLevel representing the external parts. Build a MappingConnector with the input as its base and the external as its head.
A partially external input cell (possible when input is coarser than reference) is considered to be external.
For the purpose of defining what is external, the reference level can be grown by nesting_width before comparing. This feature can be used to determing which parts of the input does not nest in the reference comparison. A negative growth indicates shrinking of the reference level.
This method does not require any communication.
Parameters:
[out] external The existing state will be discarded.
[out] input_to_external The existing state will be discarded.
[in] input_to_reference Overlap Connector from input to reference BoxLevel. The width of input_to_reference must be at least one and at least the absolute value of nesting_width.
[in] nesting_width Growth of the reference BoxLevel for the purpose of comparing to input. Must be in resolution of input BoxLevel. Must be either non-negative or non-positive but not mixed. If any width is negative, then input_to_reference must have a Connector width of at least 1. Otherwise, an error is thrown (because correct results cannot be guaranteed).
[in] domain The domain representation, without periodic images, in search tree form. These boxes should be in the reference index space. If domain is given, do not shrink the reference BoxLevel where it touches the domain boundary.
Postcondition:
input_to_external.isLocal()
Referenced by baseNestsInHead(), computeNonIntersectingParts(), SAMRAI::hier::MappingConnector::findMappingErrors(), and SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel().
void SAMRAI::hier::BoxLevelConnectorUtils::computeInternalParts (boost::shared_ptr< BoxLevel > & internal, boost::shared_ptr< MappingConnector > & input_to_internal, const Connector & input_to_reference, const IntVector & nesting_width, const BoxContainer & domain = BoxContainer()) const [inline]
Compute the parts of one BoxLevel that are internal to another BoxLevel.
Compare an input BoxLevel to a "reference" box_level. Identify parts of the input that are internal to the reference BoxLevel, and store the internal parts in a BoxLevel. Set up a MappingConnector between the input and its internal parts.
A partially internal input cell (possible when input is coarser than reference) is considered to be internal.
For the purpose of defining what is external, the reference level can be grown by nesting_width before comparing. This feature can be used to determing which parts of the input does not nest in the reference comparison. A negative growth indicates shrinking of the reference level.
This method does not require any communication.
Parameters:
[out] internal The existing state will be discarded.
[out] input_to_internal The existing state will be discarded.
[in] input_to_reference Overlap Connector from input to reference BoxLevel. The width of input_to_reference must be at least one and at least the absolute value of nesting_width.
[in] nesting_width Growth of the reference BoxLevel for the purpose of comparing to input. Must be in resolution of input BoxLevel. Must be either non-negative or non-positive but not mixed. If any width is negative, then input_to_reference must have a Connector width of at least 1. Otherwise, an error is thrown (because correct results cannot be guaranteed).
[in] domain The domain representation, without periodic images, in search tree form. These boxes should be in the reference index space. If domain is given, do not shrink the reference BoxLevel where it touches the domain boundary.
Postcondition:
input_to_internal.isLocal()
Referenced by baseNestsInHead().
void SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts (boost::shared_ptr< BoxLevel > & remainder, boost::shared_ptr< Connector > & input_to_remainder, const Connector & input_to_takeaway) const
Compute parts of a level that do not intersect with another level.
Given the Connector input_to_takeaway, this method computes the parts of the base level 'input' that do not intersect the head level 'takeaway'. The results are stored in the BoxLevel 'remainder', with the input_to_remainder Connector storing the overlap relationships between 'input' and 'remainder'.
Parameters:
[out] remainder The non-intersecting parts of input level
[out] input_to_remainder Overlap connector with width zero
[in] input_to_takeaway Overlap connector, may have any width
Precondition:
input_to_takeaway is a complete overlap connector
Postcondition:
input_to_remainder.isLocal()
References SAMRAI::hier::Connector::assertOverlapCorrectness(), computeExternalParts(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getZero(), and TBOX_ASSERT.
void SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary (BoxContainer & boundary, const IntVector & refinement_ratio, const boost::shared_ptr< const BaseGridGeometry > & grid_geometry, const bool simplify_boundary_boxes = true) const
Given a set of Boxes, compute its boundary as a set of boxes located just outside it.
Parameters:
[out] boundary Boundary boxes, sorted into BoxContainers according to the BlockId.
[in] refinement_ratio Refinement ratio of boxes.
[in] grid_geometry
simplify_boundary_boxes Whether to simplify the boundary boxes after computing them.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::clear(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BaseGridGeometry::Neighbor::getBlockId(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::BaseGridGeometry::Neighbor::getTransformedDomain(), SAMRAI::hier::BoxContainer::grow(), SAMRAI::hier::BoxContainer::hasBoxInBlock(), SAMRAI::hier::BaseGridGeometry::Neighbor::isSingularity(), SAMRAI::hier::BoxContainer::makeTree(), SAMRAI::hier::BoxContainer::removeIntersections(), SAMRAI::hier::BoxContainer::spliceBack(), and SAMRAI::hier::BoxContainer::unorder().
void SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap (boost::shared_ptr< BoxLevel > & sorted_box_level, boost::shared_ptr< MappingConnector > & output_map, const BoxLevel & unsorted_box_level, bool sort_boxes_by_corner = true, bool sequentialize_global_indices = true, LocalId initial_sequential_index = LocalId::getZero()) const
References SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::Box::getGlobalId(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::Box::getLocalId(), SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::Box::getPeriodicId(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), MPI_INT, MPI_SUM, SAMRAI::tbox::SAMRAI_MPI::Scan(), SAMRAI::hier::BoxContainer::separatePeriodicImages(), TBOX_ASSERT, and SAMRAI::tbox::SAMRAI_MPI::usingMPI().
void SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap (boost::shared_ptr< BoxLevel > & remainder, boost::shared_ptr< MappingConnector > & orig_to_remainder, const MappingConnector & orig_to_rejections) const
References SAMRAI::hier::Connector::begin(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coalesce(), SAMRAI::hier::Connector::end(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Connector::findLocal(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Connector::hasNeighborSet(), SAMRAI::hier::Connector::isLocal(), SAMRAI::hier::Connector::numLocalNeighbors(), SAMRAI::hier::BoxContainer::removeIntersections(), SAMRAI::hier::BoxContainer::size(), and TBOX_ASSERT.
void SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImages (BoxLevel & box_level, const BoxContainer & domain_search_tree, const IntVector & threshold_distance) const
Add periodic images to a BoxLevel.
This method is a no-op in the case of non-periodic domains.
Any periodic image within a certain distance of the domain is added, Those farther out are not added. The threshold distance is threshold_distance.
Parameters:
[in,out] box_level BoxLevel subject to the addition of periodic Boxes.
[in] domain_search_tree Domain description in the reference index space. This tree must NOT include periodic images.
[in] threshold_distance
References SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::hier::BoxLevel::finalize(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::PeriodicShiftCatalog::getNumberOfShifts(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxContainer::hasOverlap(), SAMRAI::hier::PeriodicShiftCatalog::isPeriodic(), SAMRAI::hier::Box::shift(), and SAMRAI::hier::PeriodicShiftCatalog::shiftNumberToShiftDistance().
Referenced by SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel().
void SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships (BoxLevel & box_level, Connector & box_level_to_anchor, const BoxContainer & domain_search_tree, const Connector & anchor_to_anchor) const
Add periodic images to a BoxLevel and add new relationships to the periodic images.
This method is a no-op in the case of non-periodic domains.
Any periodic images within a certain distance of the domain is added, but the rest are not added. The threshold distance is the width of the Connector box_level_to_anchor.
This method updates the overlap Connectors between the BoxLevel getting new periodic Boxes and an "anchor" BoxLevel. New periodic overlap relationships generated are added to the overlap Connector box_level_to_anchor. If you don't need to have a Connector updated, use addPeriodicImages() instead of this method.
Preconditions: box_level<==>anchor must be transpose overlap Connectors (or communications may hang). anchor--->anchor must be a complete overlap Connector.
Parameters:
[in,out] box_level BoxLevel subject to the addition of periodic Boxes.
[in,out] box_level_to_anchor Overlap Connector to be updated with new relationships.
[in] domain_search_tree Domain description in the reference index space. This tree must NOT include periodic images.
[in] anchor_to_anchor Self overlap Connector for anchor BoxLevel. Must be a complete overlap Connector with periodic relationships. To guarantee complete periodic relationships, the anchor, grown by the width of this Connector, must nest box_level grown by the width of box_level_to_anchor.
References SAMRAI::hier::BoxLevel::addPeriodicBox(), SAMRAI::hier::Connector::assertTransposeCorrectness(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::Connector::checkConsistencyWithBase(), SAMRAI::hier::Connector::checkConsistencyWithHead(), SAMRAI::hier::Connector::checkOverlapCorrectness(), SAMRAI::hier::BoxLevel::clearForBoxChanges(), SAMRAI::hier::Connector::eraseEmptyNeighborSets(), SAMRAI::hier::Connector::format(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::PeriodicShiftCatalog::getNumberOfShifts(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::hier::Box::grow(), SAMRAI::hier::Connector::hasNeighborSet(), SAMRAI::hier::BoxContainer::hasOverlap(), SAMRAI::hier::Connector::hasTranspose(), SAMRAI::hier::Connector::isEmptyNeighborhood(), SAMRAI::hier::PeriodicShiftCatalog::isPeriodic(), SAMRAI::hier::Connector::isTransposeOf(), SAMRAI::hier::BoxContainer::makeTree(), SAMRAI::tbox::perr, SAMRAI::tbox::plog, SAMRAI::hier::BoxContainer::refine(), SAMRAI::hier::OverlapConnectorAlgorithm::setSanityCheckMethodPreconditions(), SAMRAI::hier::Box::shift(), SAMRAI::hier::PeriodicShiftCatalog::shiftNumberToShiftDistance(), TBOX_ASSERT, TBOX_ERROR, and TBOX_WARNING.
void SAMRAI::hier::BoxLevelConnectorUtils::setTimerPrefix (const std::string & timer_prefix)
Setup names of timers.
By default, timers are named "hier::BoxLevelConnectorUtils::*", where the third field is the specific steps performed by the BoxLevelConnectorUtils. You can override the first two fields with this method. Conforming to the timer naming convention, timer_prefix should have the form "*::*".
Referenced by BoxLevelConnectorUtils(), and SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm().
const std::string SAMRAI::hier::BoxLevelConnectorUtils::getObjectName () const [inline]
Get the name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxLevelConnectorUtils.h
source/SAMRAI/hier/BoxLevelConnectorUtils.C