SAMRAI: SAMRAI::hier::Patch Class Reference
SAMRAI::hier::Patch Class Reference
A container for patch data objects defined over a box.
#include <source/SAMRAI/hier/Patch.h>
Public Member Functions
Patch (const Box &box, const boost::shared_ptr< PatchDescriptor > &descriptor)
Allocate a patch container over the box.
virtual ~Patch ()
Virtual destructor for patch objects.
const Box & getBox () const
Get the box over which the patch is defined.
const GlobalId & getGlobalId () const
Get the GlobalId for this patch.
const LocalId & getLocalId () const
Get the patch's LocalId.
boost::shared_ptr
< PatchDescriptor > getPatchDescriptor () const
Get the patch descriptor.
boost::shared_ptr< PatchData > getPatchData (const int id) const
Get the patch data identified by the specified id.
boost::shared_ptr< PatchData > getPatchData (const boost::shared_ptr< Variable > &variable, const boost::shared_ptr< VariableContext > &context) const
Get the patch data associated with the specified variable and context.
void setPatchData (const int id, const boost::shared_ptr< PatchData > &data)
Set the patch data Pointer associated with the specified identifier.
bool checkAllocated (const int id) const
Check whether the specified component has been allocated.
size_t getSizeOfPatchData (const int id) const
Get the size of the patch data.
size_t getSizeOfPatchData (const ComponentSelector &components) const
Get the size of the patch data for all components specified.
void allocatePatchData (const int id, const double time=0.0)
Allocate the specified component on the patch.
void allocatePatchData (const ComponentSelector &components, const double time=0.0)
Allocate the specified components on the patch.
void deallocatePatchData (const int id)
Deallocate the specified component.
void deallocatePatchData (const ComponentSelector &components)
Deallocate the specified components.
void setPatchGeometry (const boost::shared_ptr< PatchGeometry > &geometry)
Set the geometry specification for the patch.
boost::shared_ptr< PatchGeometry > getPatchGeometry () const
Get the patch geometry.
void setTime (const double timestamp, const int id)
Set the timestamp value for the specified patch component.
void setTime (const double timestamp, const ComponentSelector &components)
Set the timestamp value for the specified patch components.
void setTime (const double timestamp)
Set the timestamp value for all allocated patch components.
int getPatchLevelNumber () const
Get the level number of the patch level in the patch hierarchy where this patch resides.
void setPatchLevelNumber (const int level_number)
Set the patch level number for this patch.
bool inHierarchy () const
Determine if the level holding this patch resides in a hierarchy.
void setPatchInHierarchy (bool in_hierarchy)
Set a flag determining if the patch resides in a hierarchy.
void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
Get the patch data items from the restart database.
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write patch data and other patch information to the restart database.
int recursivePrint (std::ostream &os, const std::string &border=std::string(), int depth=0) const
Print a patch (for debugging).
const tbox::Dimension & getDim () const
Get the dimension of this object.
int numPatchData () const
Number of PatchData objects defined on this Patch.
Friends
std::ostream & operator<< (std::ostream &s, const Patch &patch)
Output patch information (box and number of components).
Detailed Description
A container for patch data objects defined over a box.
Class Patch is a container for patch data objects defined over some box region. Since the SAMRAI convention is that the structured mesh index space is always defined as cell-centerd, the box of a patch may not match the box describing the patch data (in fact, it is not in general). Users must be clear about how they relate the patch box to the data living on the patch.
Each of the patch data objects that exist on the patch is a subclass of the patch data pure virtual base class. The construction of the patch data objects on a patch are managed via the factory classes maintained by the patch descriptor which is shared by all patches.
By default, the patch constructor does not allocate space for the various patch data components that live on the patch. Individual components or sets of components can be created or destroyed via patch member functions.
See also:
hier::Box
hier::Box
hier::PatchDescriptor
hier::PatchData
hier::PatchDataFactory
hier::PatchGeometry
Constructor & Destructor Documentation
SAMRAI::hier::Patch::Patch (const Box & box, const boost::shared_ptr< PatchDescriptor > & descriptor)
Allocate a patch container over the box.
Note:
Patch data components are not allocated/instantiated.
Parameters:
[in] box
[in] descriptor
Precondition:
box.getLocalId() >= 0
References SAMRAI::hier::Box::getLocalId(), and TBOX_ASSERT.
SAMRAI::hier::Patch::~Patch () [virtual]
Virtual destructor for patch objects.
Member Function Documentation
const Box& SAMRAI::hier::Patch::getBox () const [inline]
Get the box over which the patch is defined.
Note that the patch data objects on a patch are free to interpret this box as appropriate for the "geometry" of their data (e.g., face-centered, node-centered, etc.)
Returns:
The box over which this patch is defined.
Referenced by SAMRAI::pdat::SideDataFactory< TYPE >::allocate(), SAMRAI::pdat::OutersideDataFactory< TYPE >::allocate(), SAMRAI::pdat::OuternodeDataFactory< TYPE >::allocate(), SAMRAI::pdat::OuterfaceDataFactory< TYPE >::allocate(), SAMRAI::pdat::OuteredgeDataFactory< TYPE >::allocate(), SAMRAI::pdat::NodeDataFactory< TYPE >::allocate(), SAMRAI::pdat::IndexDataFactory< TYPE, BOX_GEOMETRY >::allocate(), SAMRAI::pdat::FaceDataFactory< TYPE >::allocate(), SAMRAI::pdat::EdgeDataFactory< TYPE >::allocate(), SAMRAI::pdat::CellDataFactory< TYPE >::allocate(), SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs(), SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch(), and SAMRAI::mesh::MultiblockGriddingTagger::setPhysicalBoundaryConditions().
const GlobalId& SAMRAI::hier::Patch::getGlobalId () const [inline]
Get the GlobalId for this patch.
The GlobalId is the patch's unique identifier within the PatchLevel. It is identical to the GlobalId of the Patch's Box.
Returns:
GlobalId for this patch.
References SAMRAI::hier::Box::getGlobalId().
Referenced by SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), and SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs().
const LocalId& SAMRAI::hier::Patch::getLocalId () const [inline]
Get the patch's LocalId.
The LocalId is the same as that of the Box used to construct the Patch.
Returns:
The LocalId of this patch.
References SAMRAI::hier::Box::getLocalId().
boost::shared_ptr<PatchDescriptor> SAMRAI::hier::Patch::getPatchDescriptor () const [inline]
Get the patch descriptor.
The patch descriptor describes the patch data types that may exist on the patch.
Returns:
the patch descriptor for this patch.
Referenced by deallocatePatchData(), and getSizeOfPatchData().
boost::shared_ptr<PatchData> SAMRAI::hier::Patch::getPatchData (const int id) const [inline]
Get the patch data identified by the specified id.
Typically, this function should only be called to access patch data objects that have already been explicitly allocated through a call to one of the patch allocation routines. A NULL pointer will be returned if the patch data object is not allocated.
Returns:
a pointer to the patch data object associated with the specified identifier.
Parameters:
[in] id
Precondition:
(id >= 0) && (id < numPatchData())
References numPatchData(), and TBOX_ASSERT.
Referenced by SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), SAMRAI::solv::SAMRAIVectorReal< TYPE >::getComponentPatchData(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs(), SAMRAI::solv::GhostCellRobinBcCoefs::setBcCoefs(), and SAMRAI::mesh::MultiblockGriddingTagger::setPhysicalBoundaryConditions().
boost::shared_ptr<PatchData> SAMRAI::hier::Patch::getPatchData (const boost::shared_ptr< Variable > & variable, const boost::shared_ptr< VariableContext > & context) const [inline]
Get the patch data associated with the specified variable and context.
Typically, this function should only be called to access patch data objects that have already been explicitly allocated through a call to one of the patch allocation routines. A NULL pointer will be returned if the patch data object is not allocated.
Returns:
a pointer to the patch data object associated with the specified variable and context.
Parameters:
[in] variable
[in] context
Precondition:
getDim() == variable->getDim()
(id >= 0) && (id < numPatchData())
References SAMRAI::hier::VariableDatabase::getDatabase(), numPatchData(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::hier::Patch::setPatchData (const int id, const boost::shared_ptr< PatchData > & data) [inline]
Set the patch data Pointer associated with the specified identifier.
Note:
This member function must be used with caution. It can only be called for patch data indices that were previously allocated through one of the patch routines. This member function does not check to see whether the patch data types are already allocated, consistent, or whether they have the same factory. So, for example, a face centered data type could be assigned to a location reserved for a cell centered data type (with potentially different box and ghost cell width).
Parameters:
[in] id
[out] data
Precondition:
getDim() == data->getDim();
(id >= 0) && (id < numPatchData())
References numPatchData(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::hier::Patch::checkAllocated (const int id) const [inline]
Check whether the specified component has been allocated.
Returns:
True if the component has been allocated.
Parameters:
[in] id
References numPatchData().
Referenced by allocatePatchData(), and putToRestart().
size_t SAMRAI::hier::Patch::getSizeOfPatchData (const int id) const [inline]
Get the size of the patch data.
Returns:
the amount of memory needed to allocate the specified component.
Parameters:
[in] id
References getPatchDescriptor().
size_t SAMRAI::hier::Patch::getSizeOfPatchData (const ComponentSelector & components) const
Get the size of the patch data for all components specified.
Returns:
the amount of memory needed to allocate the specified components.
Parameters:
[in] components
References SAMRAI::hier::ComponentSelector::getMaxIndex(), and SAMRAI::hier::ComponentSelector::isSet().
void SAMRAI::hier::Patch::allocatePatchData (const int id, const double time = 0.0)
Allocate the specified component on the patch.
Assertions
An assertion will result if the component is already allocated. This provides a key bit of debugging information that may be useful to application developers.
Parameters:
[in] id
[in] time
Precondition:
(id >= 0) && (id < getPatchDescriptor()->getMaxNumberRegisteredComponents())
References checkAllocated(), and TBOX_ASSERT.
void SAMRAI::hier::Patch::allocatePatchData (const ComponentSelector & components, const double time = 0.0)
Allocate the specified components on the patch.
Assertions
An assertion will result if any requested component is already allocated. This provides a key bit of debugging information that may be useful to application developers.
Parameters:
[in] components
[in] time
References checkAllocated(), and SAMRAI::hier::ComponentSelector::isSet().
void SAMRAI::hier::Patch::deallocatePatchData (const int id) [inline]
Deallocate the specified component.
This component will need to be reallocated before its next use.
Parameters:
[in] id
Precondition:
(id >= 0) && (id < getPatchDescriptor()->getMaxNumberRegisteredComponents())
References getPatchDescriptor(), numPatchData(), and TBOX_ASSERT.
void SAMRAI::hier::Patch::deallocatePatchData (const ComponentSelector & components)
Deallocate the specified components.
These components will need to be reallocated before their next use.
Parameters:
[in] components
References SAMRAI::hier::ComponentSelector::isSet().
void SAMRAI::hier::Patch::setPatchGeometry (const boost::shared_ptr< PatchGeometry > & geometry) [inline]
Set the geometry specification for the patch.
This includes patch boundary information and grid data.
Parameters:
[in] geometry
Referenced by SAMRAI::hier::BaseGridGeometry::setGeometryDataOnPatch(), and SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch().
boost::shared_ptr<PatchGeometry> SAMRAI::hier::Patch::getPatchGeometry () const [inline]
Get the patch geometry.
Returns:
pointer to patch geometry object.
Referenced by SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), SAMRAI::mesh::MultiblockGriddingTagger::fillSingularityBoundaryConditions(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs(), SAMRAI::solv::GhostCellRobinBcCoefs::setBcCoefs(), and SAMRAI::mesh::MultiblockGriddingTagger::setPhysicalBoundaryConditions().
void SAMRAI::hier::Patch::setTime (const double timestamp, const int id) [inline]
Set the timestamp value for the specified patch component.
Parameters:
[in] timestamp
[in] id
Precondition:
(id >= 0) && (id < numPatchData())
getPatchData(id)
References numPatchData(), and TBOX_ASSERT.
void SAMRAI::hier::Patch::setTime (const double timestamp, const ComponentSelector & components)
Set the timestamp value for the specified patch components.
Parameters:
[in] timestamp
[in] components
References SAMRAI::hier::ComponentSelector::isSet().
void SAMRAI::hier::Patch::setTime (const double timestamp)
Set the timestamp value for all allocated patch components.
Parameters:
[in] timestamp
int SAMRAI::hier::Patch::getPatchLevelNumber () const [inline]
Get the level number of the patch level in the patch hierarchy where this patch resides.
Note:
This value can be a valid level number (i.e., >=0) even when the level is not in a hierarchy. In this case the level number will be the number of the hierarchy level matching the index space of the patch level holding this patch. If the patch level does not align with the index space of a level in the hierarchy, then this value is -1.
Returns:
The valid level number >= 0 or undefined (-1) if the patch level does not align with the index space of a level in the hierarchy.
See also:
inHierarchy()
Referenced by SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), and SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs().
void SAMRAI::hier::Patch::setPatchLevelNumber (const int level_number) [inline]
Set the patch level number for this patch.
When the index space of the level owning this patch aligns with the index space of some valid hierarchy level, sets the patch level number The default level number is -1.
Parameters:
[in] level_number
bool SAMRAI::hier::Patch::inHierarchy () const [inline]
Determine if the level holding this patch resides in a hierarchy.
Returns:
True if the level holding this patch resides in a hierarchy, otherwise false.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), and SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs().
void SAMRAI::hier::Patch::setPatchInHierarchy (bool in_hierarchy) [inline]
Set a flag determining if the patch resides in a hierarchy.
Set to true if the level holding this patch resides in a hierarchy; false otherwise. The default setting is false.
Parameters:
[in] in_hierarchy The flag that indicates whether the patch resides in a hierarchy.
void SAMRAI::hier::Patch::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db)
Get the patch data items from the restart database.
Patch state is read in from the database and all patch data objects specified in the PatchDataRestartManager are created.
The class version and restart file version must be equal.
Assertions
Checks that data retrieved from the database are of the type expected, and that the patch_number read in from the database matches the patch number assigned to this Patch.
Note:
A warning will be printed to the log file if some patch data components that were requested through the PatchDataRestartManager are not found in the database.
Parameters:
[in] restart_db
Precondition:
restart_db
References SAMRAI::hier::PatchDataRestartManager::getManager(), SAMRAI::hier::Box::initialize(), SAMRAI::hier::PatchDataRestartManager::isPatchDataRegisteredForRestart(), SAMRAI::hier::PatchDataRestartManager::registeredPatchDataMatches(), SAMRAI::hier::ComponentSelector::setFlag(), TBOX_ASSERT, TBOX_ERROR, and TBOX_WARNING.
void SAMRAI::hier::Patch::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const
Write patch data and other patch information to the restart database.
Class version number and the state of the patch object are written. Patch data objects specified in the PatchDataRestartManager are also written.
Parameters:
[in] restart_db
Precondition:
restart_db
References checkAllocated(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::Box::getLocalId(), SAMRAI::hier::PatchDataRestartManager::getManager(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::LocalId::getValue(), SAMRAI::hier::PatchDataRestartManager::isPatchDataRegisteredForRestart(), and TBOX_ASSERT.
int SAMRAI::hier::Patch::recursivePrint (std::ostream & os, const std::string & border = std::string(), int depth = 0) const
Print a patch (for debugging).
Depth is kept for consistency with other recursivePrint methods, but is not used because this is the lowest level of recursion currently supported.
Parameters:
[in,out] os
[in] border
[in] depth
References SAMRAI::hier::Box::getDim(), NULL_USE, SAMRAI::hier::Box::numberCells(), and SAMRAI::hier::Box::size().
const tbox::Dimension& SAMRAI::hier::Patch::getDim () const [inline]
Get the dimension of this object.
Returns:
the dimension of this object.
References SAMRAI::hier::Box::getDim().
Referenced by SAMRAI::mesh::MultiblockGriddingTagger::setPhysicalBoundaryConditions().
int SAMRAI::hier::Patch::numPatchData () const [inline]
Number of PatchData objects defined on this Patch.
Referenced by checkAllocated(), deallocatePatchData(), getPatchData(), setPatchData(), and setTime().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & s, const Patch & patch) [friend]
Output patch information (box and number of components).
Parameters:
[in,out] s The output stream
[in] patch
The documentation for this class was generated from the following files:
source/SAMRAI/hier/Patch.h
source/SAMRAI/hier/Patch.C