SAMRAI: SAMRAI::pdat::OuterfaceData< TYPE > Class Template Reference
SAMRAI::pdat::OuterfaceData< TYPE > Class Template Reference
Class OuterfaceData<TYPE> provides an implementation for data defined at cell faces on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outerface data object represents data of some template TYPE and depth on the cell faces on the boundary of the box. Here, depth indicates the number of data values at each face index location. The OuteredgfaceGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outerface-centered data.
#include <source/SAMRAI/pdat/OuterfaceData.h>
Public Member Functions
OuterfaceData (const hier::Box &box, int depth)
Constructor for an outerface data object.
virtual ~OuterfaceData ()
Virtual destructor for a outerface data object.
int getDepth () const
Return the depth (i.e., the number of data values for each spatial location) of the array.
TYPE * getPointer (int face_normal, int side, int depth=0)
Get a pointer to the beginning of a particular face normal, side, and depth component of the outerface centered array.
const TYPE * getPointer (int face_normal, int side, int depth=0) const
Get a const pointer to the beginning of a particular face normal, side location, and depth component of the outerface centered array.
TYPE & operator() (const FaceIndex &i, int side, int depth=0)
Return a reference to data entry corresponding to a given face index, side location, and depth.
const TYPE & operator() (const FaceIndex &i, int side, int depth=0) const
Return a const reference to data entry corresponding to a given face index, side location, and depth.
ArrayData< TYPE > & getArrayData (int face_normal, int side)
Return a reference to the array data object for face normal and side location of the outerface centered array.
const ArrayData< TYPE > & getArrayData (int face_normal, int side) const
Return a const reference to the array data object for face normal and side location of the outerface centered array.
virtual void copy (const hier::PatchData &src)
A fast copy from source to destination (i.e., this) patch data object.
virtual void copy2 (hier::PatchData &dst) const
A fast copy from source (i.e., this) to destination patch data object.
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Copy data from source to destination (i.e., this) patch data object on the given overlap.
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
Copy data from source (i.e., this) to destination patch data object on the given overlap.
void copyDepth (int dst_depth, const FaceData< TYPE > &src, int src_depth)
Fast copy (i.e., assumes face and outerface data objects are defined over the same box) from the given face source data object to this destination outerface data object at the specified depths.
void copyDepth2 (int dst_depth, FaceData< TYPE > &dst, int src_depth) const
Fast copy (i.e., assumes face and outerface data objects are defined over the same box) to the given face destination data object from this source outerface data object at the specified depths.
virtual bool canEstimateStreamSizeFromBox () const
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
virtual size_t getDataStreamSize (const hier::BoxOverlap &overlap) const
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an FaceOverlap of the same DIM.
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an FaceOverlap of the same DIM.
void fill (const TYPE &t, int d=0)
Fill all values at depth d with the value t.
void fill (const TYPE &t, const hier::Box &box, int d=0)
Fill all values at depth d within the box with the value t.
void fillAll (const TYPE &t)
Fill all depth components with value t.
void fillAll (const TYPE &t, const hier::Box &box)
Fill all depth components within the box with value t.
void print (const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all outerface data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
void print (const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all outerface data values at the given array depth in the specified box.
void printAxisFace (tbox::Dimension::dir_t face_normal, int side, const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all outerface centered data values for specified face_normal and side residing in the specified box. If the depth of the data is greater than one, all depths are printed.
void printAxisFace (tbox::Dimension::dir_t face_normal, int side, const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all outerface centered data values for specified face_normal, side, and depth residing in the specified box.
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
Check that class version and restart file version are equal. If so, read data members from the restart database.
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Write out the class version number and other data members to the restart database.
Static Public Member Functions
static size_t getSizeOfData (const hier::Box &box, int depth)
Calculate the amount of memory needed to represent outerface- centered data over a CELL-centered AMR index space box.
Detailed Description
template<class TYPE>
class SAMRAI::pdat::OuterfaceData< TYPE >
Class OuterfaceData<TYPE> provides an implementation for data defined at cell faces on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outerface data object represents data of some template TYPE and depth on the cell faces on the boundary of the box. Here, depth indicates the number of data values at each face index location. The OuteredgfaceGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outerface-centered data.
Outerface data is stored in 2*DIM arrays, each of which contains data associated with face indices normal to a coordinate axis direction and an upper or lower box face in the face normal direction. The data layout in the outerface data arrays matches the corresponding array sections provided by the face data implementation. Specifically, within each array, the data indices are cyclically permuted to be consistent with the FaceData<TYPE> implementation. Also, in each of array, memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory. For example, a three-dimensional outerface data object created over a CELL-centered AMR index space [l0:u0,l1:u1,l2:u2] allocates six data arrays sized as follows:
 *
 * face normal 0:
 *   lower face      [ l0:l0     , l1:u1 , l2:u2 , d ]
 *   upper face      [ u0+1:u0+1 , l1:u1 , l2:u2 , d ]
 *
 * face normal 1:
 *   lower face      [ l1:l1     , l2:u2 , l0:u0 , d ]
 *   upper face      [ u1+1:u1+1 , l2:u2 , l0:u0 , d ]
 *
 * face normal 2:
 *   lower face      [ l2:l2     , l0:u0 , l1:u1 , d ]
 *   upper face      [ u2+1:u2+1 , l0:u0 , l1:u1 , d ]
 *
 *
Here the face normal directions 0, 1, 2 can be thought of as the x, y, and z face normal directions, respectively, and d is the depth index (i.e., number of values at each face index location). Other spatial dimensions are represented similarly.
The data type TYPE must define a default constructor (that takes no arguments) and also the assignment operator.
IMPORTANT: The OutersideData<TYPE> class provides the same storage as this outerface data class, except that the coordinate directions of the individual arrays are not permuted; i.e., OutersideData is consistent with the SideData implementation.
See also:
ArrayData
hier::PatchData
OuterfaceDataFactory
OuterfaceGeometry
FaceIterator
FaceIndex
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::OuterfaceData< TYPE >::OuterfaceData (const hier::Box & box, int depth) [inline]
Constructor for an outerface data object.
Note: Outerface data always has ghost cell width of zero.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the outerface data object will be created.
depth gives the number of data values for each spatial location in the array.
Precondition:
depth > 0
References SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, SAMRAI::pdat::FaceGeometry::toFaceBox(), and SAMRAI::hier::Box::upper().
template<class TYPE > SAMRAI::pdat::OuterfaceData< TYPE >::~OuterfaceData () [inline, virtual]
Virtual destructor for a outerface data object.
Member Function Documentation
template<class TYPE > size_t SAMRAI::pdat::OuterfaceData< TYPE >::getSizeOfData (const hier::Box & box, int depth) [inline, static]
Calculate the amount of memory needed to represent outerface- centered data over a CELL-centered AMR index space box.
This function assumes that the amount of memory needed for TYPE is sizeof(TYPE). If this is not the case, then a specialized function must be defined.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the outerface data object will be created. Note: the ghost cell width is assumed to be zero.
depth gives the number of data values for each spatial location in the array.
Precondition:
depth > 0
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, SAMRAI::pdat::FaceGeometry::toFaceBox(), and SAMRAI::hier::Box::upper().
template<class TYPE > int SAMRAI::pdat::OuterfaceData< TYPE >::getDepth () const [inline]
Return the depth (i.e., the number of data values for each spatial location) of the array.
template<class TYPE > TYPE * SAMRAI::pdat::OuterfaceData< TYPE >::getPointer (int face_normal, int side, int depth = 0) [inline]
Get a pointer to the beginning of a particular face normal, side, and depth component of the outerface centered array.
Parameters:
face_normal integer face normal direction for data
side integer lower (0) or upper (1) side of outerface data array
depth integer depth component
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > const TYPE * SAMRAI::pdat::OuterfaceData< TYPE >::getPointer (int face_normal, int side, int depth = 0) const [inline]
Get a const pointer to the beginning of a particular face normal, side location, and depth component of the outerface centered array.
Parameters:
face_normal integer face normal direction for data
side integer lower (0) or upper (1) side of outerface data array
depth integer depth component
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::OuterfaceData< TYPE >::operator() (const FaceIndex & i, int side, int depth = 0) [inline]
Return a reference to data entry corresponding to a given face index, side location, and depth.
Parameters:
i const reference to FaceIndex, MUST be an index on the outerface of the box.
side integer (lower/upper location of outerface data)
depth integer depth component
Precondition:
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::FaceIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > const TYPE & SAMRAI::pdat::OuterfaceData< TYPE >::operator() (const FaceIndex & i, int side, int depth = 0) const [inline]
Return a const reference to data entry corresponding to a given face index, side location, and depth.
Parameters:
i const reference to FaceIndex, MUST be an index on the outerface of the box.
side integer (lower/upper location of outerface data)
depth integer depth component
Precondition:
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue())
(side == 0) || (side == 1)
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::FaceIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > ArrayData< TYPE > & SAMRAI::pdat::OuterfaceData< TYPE >::getArrayData (int face_normal, int side) [inline]
Return a reference to the array data object for face normal and side location of the outerface centered array.
Parameters:
face_normal integer face normal direction for data
side integer lower (0) or upper (1) side of outerface data array
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::OuterfaceData< TYPE >::copy(), and SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs().
template<class TYPE > const ArrayData< TYPE > & SAMRAI::pdat::OuterfaceData< TYPE >::getArrayData (int face_normal, int side) const [inline]
Return a const reference to the array data object for face normal and side location of the outerface centered array.
Parameters:
face_normal integer face normal direction for data
side integer lower (0) or upper (1) side of outerface data array
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy from source to destination (i.e., this) patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, source data must be FaceData the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
dynamic_cast<const FaceData<TYPE> *>(&src) != 0
References SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::pdat::FaceData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy from source (i.e., this) to destination patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, destination data must be FaceData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<FaceData<TYPE> *>(&dst) != 0
References SAMRAI::pdat::FaceData< TYPE >::getArrayData(), SAMRAI::hier::PatchData::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from source to destination (i.e., this) patch data object on the given overlap.
IMPORTANT: this routine is not yet implemented!
References SAMRAI::pdat::OuterfaceData< TYPE >::getArrayData(), SAMRAI::pdat::FaceOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from source (i.e., this) to destination patch data object on the given overlap.
Currently, destination data must be FaceData of the same DIM and TYPE and the overlap must be a FaceOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<FaceData<TYPE> *>(&dst) != 0
dynamic_cast<const FaceOverlap *>(&overlap) != 0
overlap.getTransformation().getRotation() == hier::Transformation::NO_ROTATE
References SAMRAI::pdat::FaceData< TYPE >::getArrayData(), SAMRAI::hier::PatchData::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth (int dst_depth, const FaceData< TYPE > & src, int src_depth) [inline]
Fast copy (i.e., assumes face and outerface data objects are defined over the same box) from the given face source data object to this destination outerface data object at the specified depths.
Precondition:
getDim() == src.getDim()
References SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::pdat::FaceData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth2 (int dst_depth, FaceData< TYPE > & dst, int src_depth) const [inline]
Fast copy (i.e., assumes face and outerface data objects are defined over the same box) to the given face destination data object from this source outerface data object at the specified depths.
Precondition:
getDim() == dst.getDim()
References SAMRAI::pdat::ArrayData< TYPE >::copyDepth(), SAMRAI::pdat::FaceData< TYPE >::getArrayData(), SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::OuterfaceData< TYPE >::canEstimateStreamSizeFromBox () const [inline, virtual]
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Implements SAMRAI::hier::PatchData.
template<class TYPE > size_t SAMRAI::pdat::OuterfaceData< TYPE >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Precondition:
dynamic_cast<const FaceOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::FaceOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an FaceOverlap of the same DIM.
Precondition:
dynamic_cast<const FaceOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::PatchData::getBox(), SAMRAI::pdat::FaceOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an FaceOverlap of the same DIM.
Precondition:
dynamic_cast<const FaceOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::pdat::FaceOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::fill (const TYPE & t, int d = 0) [inline]
Fill all values at depth d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::fill (const TYPE & t, const hier::Box & box, int d = 0) [inline]
Fill all values at depth d within the box with the value t.
Precondition:
getDim() == box.getDim()
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all depth components with value t.
References SAMRAI::hier::PatchData::getDim(), and SAMRAI::tbox::Dimension::getValue().
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all depth components within the box with value t.
Precondition:
getDim() == box.getDim()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::print (const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerface data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::print (const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerface data values at the given array depth in the specified box.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::OuterfaceData< TYPE >::printAxisFace(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::printAxisFace (tbox::Dimension::dir_t face_normal, int side, const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerface centered data values for specified face_normal and side residing in the specified box. If the depth of the data is greater than one, all depths are printed.
Parameters:
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outerface data array
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::OuterfaceData< TYPE >::print().
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::printAxisFace (tbox::Dimension::dir_t face_normal, int side, const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all outerface centered data values for specified face_normal, side, and depth residing in the specified box.
Parameters:
face_normal integer face normal direction for data, must satisfy 0 <= face_normal < DIM
side integer lower (0) or upper (1) side of outerface data array
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
(face_normal >= 0) && (face_normal < getDim().getValue())
(side == 0) || (side == 1)
References SAMRAI::hier::Box::begin(), SAMRAI::hier::Box::end(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check that class version and restart file version are equal. If so, read data members from the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::OuterfaceData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number and other data members to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/OuterfaceData.h
source/SAMRAI/pdat/OuterfaceData.C