SAMRAI: SAMRAI::hier::OverlapConnectorAlgorithm Class Reference
SAMRAI::hier::OverlapConnectorAlgorithm Class Reference
Algorithms for working Connectors whose neighbor data represents overlaps.
#include <source/SAMRAI/hier/OverlapConnectorAlgorithm.h>
Public Member Functions
OverlapConnectorAlgorithm ()
Constructor.
virtual ~OverlapConnectorAlgorithm ()
Destructor.
void findOverlaps (boost::shared_ptr< Connector > &connector, const BoxLevel &base_box_level, const BoxLevel &head_box_level, const IntVector &base_width, const BoxLevel::ParallelState parallel_state=BoxLevel::DISTRIBUTED, const bool ignore_self_overlap=false) const
Create overlap Connector then discover and add overlaps from base to head to it.
void findOverlapsWithTranspose (boost::shared_ptr< Connector > &connector, const BoxLevel &base_box_level, const BoxLevel &head_box_level, const IntVector &base_width, const IntVector &transpose_base_width, const BoxLevel::ParallelState parallel_state=BoxLevel::DISTRIBUTED, const bool ignore_self_overlap=false) const
Create overlap Connector with its transpose then discover and add overlaps from base to head to it and overlaps from head to base to transpose.
void findOverlaps (Connector &connector, const bool ignore_self_overlap=false) const
Discover and add overlaps from base to head for an overlap Connector.
void findOverlaps (Connector &connector, const BoxLevel &globalized_head, const bool ignore_self_overlap=false) const
void findOverlaps_assumedPartition (Connector &connector) const
void extractNeighbors (Connector::NeighborSet &neighbors, const Connector &connector, const BoxId &box_id, const IntVector &gcw) const
For a given Connector, get the subset of overlapping neighbors defined by the given Connector width.
void extractNeighbors (Connector &other, const Connector &connector, const IntVector &gcw) const
Like extractNeighbors above except that it computes all neighborhoods of connector placing them into other.
void bridgeWithNesting (boost::shared_ptr< Connector > &west_to_east, const Connector &west_to_center, const Connector &center_to_east, const IntVector &center_growth_to_nest_west, const IntVector &center_growth_to_nest_east, const IntVector &connector_width_limit, bool compute_transpose) const
Compute the overlap Connectors between BoxLevels efficiently by using information from existing overlap Connectors.
void bridge (boost::shared_ptr< Connector > &west_to_east, const Connector &west_to_center, const Connector &center_to_east, const IntVector &connector_width_limit, bool compute_transpose) const
A version of bridge without any guarantee of nesting.
void bridge (boost::shared_ptr< Connector > &west_to_east, const Connector &west_to_center, const Connector &center_to_east, bool compute_transpose) const
A version of bridge without limiting the connector_width of the result.
void bridge (Connector &west_to_center, const Connector &center_to_east, const IntVector &connector_width_limit) const
A version of bridge without any guarantee of nesting in which an input connector and its transpose are modified to form the resulting bridge connectors.
void setBarrierBeforeCommunication (bool do_barrier)
Set whether to barrier before potential major communication.
void setSanityCheckMethodPreconditions (bool do_check)
When do_check is true, turn on sanity checks for input parameters.
void setSanityCheckMethodPostconditions (bool do_check)
When do_check is true, turn on sanity checks for outputs.
void setSAMRAI_MPI (const tbox::SAMRAI_MPI &mpi, bool make_duplicate=true)
Set the SAMRAI_MPI to use.
void setPrintSteps (bool print_steps)
When print_steps is true, print what the code is doing.
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
const std::string getObjectName () const
Get the name of this object.
Detailed Description
Algorithms for working Connectors whose neighbor data represents overlaps.
An overlap Connector is one in which neighbors represent a pair of overlapping Boxes. If a base Box grown by the Connector width overlaps a head Box, the head Box is a neighbor of the base Box. This class implements some functions for working with a overlap Connectors.
OverlapConnectorAlgorithm objects create, check and operate on overlap Connectors.
Constructor & Destructor Documentation
SAMRAI::hier::OverlapConnectorAlgorithm::OverlapConnectorAlgorithm ()
Constructor.
References setTimerPrefix().
SAMRAI::hier::OverlapConnectorAlgorithm::~OverlapConnectorAlgorithm () [virtual]
Destructor.
References SAMRAI::tbox::SAMRAI_MPI::freeCommunicator().
Member Function Documentation
void SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps (boost::shared_ptr< Connector > & connector, const BoxLevel & base_box_level, const BoxLevel & head_box_level, const IntVector & base_width, const BoxLevel::ParallelState parallel_state = BoxLevel::DISTRIBUTED, const bool ignore_self_overlap = false) const
Create overlap Connector then discover and add overlaps from base to head to it.
The Connector's neighbor information is modified.
If the Connector's head is not GLOBALIZED, a copy is made and globalized. Once a globalized head is obtained, this method simply calls findOverlaps(const BoxLevel &globalized_head).
Parameters:
[in,out] connector
[in] base_box_level
[in] head_box_level
[in] base_width
[in] parallel_state
[in] ignore_self_overlap
References SAMRAI::hier::BoxLevel::getGlobalizedVersion().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), findOverlaps(), findOverlapsWithTranspose(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel().
void SAMRAI::hier::OverlapConnectorAlgorithm::findOverlapsWithTranspose (boost::shared_ptr< Connector > & connector, const BoxLevel & base_box_level, const BoxLevel & head_box_level, const IntVector & base_width, const IntVector & transpose_base_width, const BoxLevel::ParallelState parallel_state = BoxLevel::DISTRIBUTED, const bool ignore_self_overlap = false) const
Create overlap Connector with its transpose then discover and add overlaps from base to head to it and overlaps from head to base to transpose.
The Connector's neighbor information is modified.
If the Connector's head is not GLOBALIZED, a copy is made and globalized. Once a globalized head is obtained, this method simply calls findOverlaps(const BoxLevel &globalized_head).
Parameters:
[in,out] connector
[in] base_box_level
[in] head_box_level
[in] base_width
[in] transpose_base_width
[in] parallel_state
[in] ignore_self_overlap
References findOverlaps().
void SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps (Connector & connector, const bool ignore_self_overlap = false) const
Discover and add overlaps from base to head for an overlap Connector.
The Connector's neighbor information is modified.
If the Connector's head is not GLOBALIZED, a copy is made and globalized. Once a globalized head is obtained, this method simply calls findOverlaps(const BoxLevel &globalized_head).
Parameters:
[in,out] connector
[in] ignore_self_overlap
References findOverlaps(), SAMRAI::hier::BoxLevel::getGlobalizedVersion(), and SAMRAI::hier::Connector::getHead().
void SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps (Connector & connector, const BoxLevel & globalized_head, const bool ignore_self_overlap = false) const
void SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps_assumedPartition (Connector & connector) const
References SAMRAI::hier::BoxContainer::back(), SAMRAI::hier::BoxContainer::begin(), bridgeWithNesting(), SAMRAI::hier::Connector::clear(), SAMRAI::hier::BoxContainer::clear(), SAMRAI::hier::BoxContainer::coarsen(), SAMRAI::hier::Connector::computeTransposeOf(), SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::BoxLevel::getGlobalBoundingBox(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::Connector::getRatio(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::BoxContainer::grow(), SAMRAI::tbox::SAMRAI_MPI::hasNullCommunicator(), SAMRAI::tbox::SAMRAI_MPI::hasReceivableMessage(), SAMRAI::hier::Connector::insertLocalNeighbor(), SAMRAI::hier::Connector::insertNeighbors(), SAMRAI::tbox::SAMRAI_MPI::isCongruentWith(), MPI_ANY_SOURCE, MPI_ANY_TAG, SAMRAI::tbox::plog, SAMRAI::hier::BoxContainer::push_back(), SAMRAI::hier::BoxContainer::refine(), SAMRAI::hier::Connector::setBase(), SAMRAI::hier::Connector::setHead(), SAMRAI::hier::Connector::setTranspose(), SAMRAI::hier::Connector::setWidth(), SAMRAI::hier::Box::size(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel().
void SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors (Connector::NeighborSet & neighbors, const Connector & connector, const BoxId & box_id, const IntVector & gcw) const
For a given Connector, get the subset of overlapping neighbors defined by the given Connector width.
The difference between extractNeighbors() and Connector::getNeighbors() is that extractNeighbors() extracts the subset of the currently stored neighbors associated with the given Connector width. getNeighbors() returns the entire neighbor set, which corresponds to the Connector's width. The specified Connector width must be less than or equal to the Connector's width.
Parameters:
[out] neighbors
[in] connector
[in] box_id
[in] gcw
Precondition:
gcw <= connector.getConnectorWidth()
(connector.getParallelState() == BoxLevel::GLOBALIZED) || (box_id.getOwnerRank() == connector.getMPI().getRank())
connector.getBase().hasBox(box_id)
References SAMRAI::hier::Connector::begin(), SAMRAI::hier::BoxContainer::clear(), dbgbord, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Connector::end(), SAMRAI::hier::Connector::findLocal(), SAMRAI::hier::Connector::format(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::Connector::getHeadCoarserFlag(), SAMRAI::hier::Connector::getMPI(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::hier::Connector::getParallelState(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::Connector::getRatio(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::Box::intersects(), SAMRAI::hier::Box::refine(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors (Connector & other, const Connector & connector, const IntVector & gcw) const
Like extractNeighbors above except that it computes all neighborhoods of connector placing them into other.
Parameters:
[out] other
[in] connector
[in] gcw
Precondition:
gcw <= connector.getConnectorWidth()
for the box_id of each neighborhood base box in connector, (connector.getParallelState() == BoxLevel::GLOBALIZED) || (box_id.getOwnerRank() == connector.getMPI().getRank())
for the box_id of each neighborhood base box in connector, connector.getBase().hasBox(box_id)
References SAMRAI::hier::Connector::begin(), SAMRAI::hier::Connector::clearNeighborhoods(), dbgbord, SAMRAI::hier::Connector::end(), SAMRAI::hier::Connector::format(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::Connector::getHeadCoarserFlag(), SAMRAI::hier::Connector::getMPI(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::hier::Connector::getParallelState(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::Connector::getRatio(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::hier::Connector::insertLocalNeighbor(), SAMRAI::hier::Box::intersects(), SAMRAI::hier::Connector::makeEmptyLocalNeighborhood(), SAMRAI::hier::Box::refine(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting (boost::shared_ptr< Connector > & west_to_east, const Connector & west_to_center, const Connector & center_to_east, const IntVector & center_growth_to_nest_west, const IntVector & center_growth_to_nest_east, const IntVector & connector_width_limit, bool compute_transpose) const
Compute the overlap Connectors between BoxLevels efficiently by using information from existing overlap Connectors.
Let east, west and center be BoxLevels. Given overlap Connectors between center and east and between center and west, compute overlap Connectors between east and west.
               Input:                            Output:
                                               west to east
      (west)              (east)      (west) ---------------> (east)
        \ ^                ^ /               <---------------
         \ \center  center/ /                  east to west
          \ \ to     to  / /
       west\ \west  east/ /east
        to  \ \        / /  to
       center\ \      / /center
              v \    / v
               (center)
The "bridge" is the Connectors between west and east. Bridging is an algorithm for finding their overlaps using existing overlaps incident from center. This is more efficient than findOverlaps() because it does not require acquiring, storing or searching globalized data.
Preconditions:
Four input Connectors refer to the center BoxLevel, two refer to the west, and two refer to the east. The center, east and west BoxLevels must be the same regardless of what Connector is used to get them. For example, &west_to_center.getTranspose().getHead() == &west_to_center.getBase() must be true.
Postconditions:
west and east, as referenced by the output Connectors are heads of west_to_center's transpose and center_to_east.
Widths of the output Connectors will be either center_to_east's width reduced by center_growth_to_nest_west or west_to_center's transpose's width reduced by center_growth_to_nest_east, which ever is greater. Output Connector widths are still limited by the connector_width_limit argument. All comparisons are done after the appropriate index space conversions, of course.
Note:
Although east, west and center are not explicit parameters, they are specified implicitly through the input Connectors.
The bridge operation works in the degenerate case where east and west are the same object. In that case, west_to_east and its transpose should also be the same object.
Bridging finds as many overlaps as it can, given the inputs, but can only guarantee that the output Connectors are complete overlap Connectors if there is nesting as specified by the arguments center_growth_to_nest_west and/or center_growth_to_nest_east. Nesting is not checked, because checking requires an iterative non-scalable computation. Nesting is best determined by the code that created the BoxLevels involved. Bridging is meant to be fast and scalable.
Periodic relationships are automatically generated if a head Box in its shifted position overlaps the grown base Box. However, because neighbors may be remote, we cannot scalably verify that the periodic neighbors actually exist in the heads of the output Connectors. Spurious periodic relationships may be generated when the periodic image simply has not be added to the head or when parts of east or west lie outside the domain extents. They can be discarded using Connector::removePeriodicRelationships and properly regenerated using BoxLevelConnectorUtils.
Parameters:
[out] west_to_east
[in] west_to_center
[in] center_to_east
center_growth_to_nest_west The amount by which the center BoxLevel must grow to nest the west BoxLevel. Bridging guarantees completeness if the width of center_to_east exceeds this amount. If unknown, set to negative value if unknown so it won't be considered when computing the output Connector widths.
center_growth_to_nest_east The amount by which the center BoxLevel must grow to nest the east BoxLevel. Bridging guarantees completeness if the width of west_to_center's transpose exceeds this amount. If unknown, set to negative value if unknown so it won't be considered when computing the output Connector widths.
connector_width_limit specifies the maximum Connector width to compute overlaps for. The connector_width should be in the coarser of the east and west indices. If connector_width_limit is negative, use the default connector_width, which is the larger of the west_to_center's transpose and center_to_east Connectors', coarsened into the coarser of east and west indices.
compute_transpose true if west_to_east's transpose should be computed
Precondition:
west_to_cent.hasTranspose()
cent_to_east.hasTranspose()
References SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::tbox::SAMRAI_MPI::hasNullCommunicator(), SAMRAI::hier::Connector::hasTranspose(), and TBOX_ASSERT.
Referenced by findOverlaps_assumedPartition(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel(), and SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel().
void SAMRAI::hier::OverlapConnectorAlgorithm::bridge (boost::shared_ptr< Connector > & west_to_east, const Connector & west_to_center, const Connector & center_to_east, const IntVector & connector_width_limit, bool compute_transpose) const
A version of bridge without any guarantee of nesting.
The east and west BoxLevels are assumed to nest in the center BoxLevel. If they do not, the results are not guaranteed to be complete.
The output Connector widths are the greater of the widths of center_to_east and center_to_west (converted into the proper index space, of course).
Parameters:
[out] west_to_east
[in] west_to_center
[in] center_to_east
[in] connector_width_limit
compute_transpose true if west_to_east's transpose should be computed
Precondition:
west_to_cent.hasTranspose()
cent_to_east.hasTranspose()
See also:
bridgeWithNesting(Connector& west_to_east, const Connector& west_to_center, const Connector& center_to_east, const IntVector& center_growth_to_nest_west, const IntVector& center_growth_to_nest_east, const IntVector& connector_width_limit, bool compute_transpose) const;
References SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::hier::IntVector::getZero(), SAMRAI::tbox::SAMRAI_MPI::hasNullCommunicator(), SAMRAI::hier::Connector::hasTranspose(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships().
void SAMRAI::hier::OverlapConnectorAlgorithm::bridge (boost::shared_ptr< Connector > & west_to_east, const Connector & west_to_center, const Connector & center_to_east, bool compute_transpose) const
A version of bridge without limiting the connector_width of the result.
Parameters:
[out] west_to_east
[in] west_to_center
[in] center_to_east
compute_transpose true if west_to_east's transpose should be computed
Precondition:
west_to_cent.hasTranspose()
cent_to_east.hasTranspose()
See also:
bridge(Connector& west_to_east, const Connector& west_to_center, const Connector& center_to_east, const IntVector& connector_width_limit, bool compute_transpose) const;
References SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::hier::IntVector::getZero(), SAMRAI::tbox::SAMRAI_MPI::hasNullCommunicator(), SAMRAI::hier::Connector::hasTranspose(), and TBOX_ASSERT.
void SAMRAI::hier::OverlapConnectorAlgorithm::bridge (Connector & west_to_center, const Connector & center_to_east, const IntVector & connector_width_limit) const
A version of bridge without any guarantee of nesting in which an input connector and its transpose are modified to form the resulting bridge connectors.
The east and west BoxLevels are assumed to nest in the center BoxLevel. If they do not, the results are not guaranteed to be complete.
The output Connector widths are the greater of the widths of center_to_east and west_to_center's transpose (converted into the proper index space, of course).
Parameters:
[in,out] west_to_center
[in] center_to_east
[in] connector_width_limit
Precondition:
west_to_cent.hasTranspose()
cent_to_east.hasTranspose()
See also:
bridgeWithNesting(Connector& west_to_east, const Connector& west_to_center, const Connector& center_to_east, const IntVector& center_growth_to_nest_west, const IntVector& center_growth_to_nest_east, const IntVector& connector_width_limit, bool compute_transpose) const;
References SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::hier::Connector::clearNeighborhoods(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::hier::IntVector::getZero(), SAMRAI::tbox::SAMRAI_MPI::hasNullCommunicator(), SAMRAI::hier::Connector::hasTranspose(), SAMRAI::hier::Connector::setBase(), SAMRAI::hier::Connector::setHead(), SAMRAI::hier::Connector::setWidth(), and TBOX_ASSERT.
void SAMRAI::hier::OverlapConnectorAlgorithm::setBarrierBeforeCommunication (bool do_barrier) [inline]
Set whether to barrier before potential major communication.
This developer feature makes sure all processes start major operations at the same time so that timers do not include the time waiting for slower processes to get to the starting point.
Parameters:
[in] do_barrier
void SAMRAI::hier::OverlapConnectorAlgorithm::setSanityCheckMethodPreconditions (bool do_check) [inline]
When do_check is true, turn on sanity checks for input parameters.
Note:
Sanity checks occur at the beginning of certain methods only. The checks are expensive and meant mainly for debugging.
Parameters:
[in] do_check
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships().
void SAMRAI::hier::OverlapConnectorAlgorithm::setSanityCheckMethodPostconditions (bool do_check) [inline]
When do_check is true, turn on sanity checks for outputs.
Note:
Sanity checks occur at the end of certain methods only. The checks are expensive and meant mainly for debugging.
Parameters:
[in] do_check
void SAMRAI::hier::OverlapConnectorAlgorithm::setSAMRAI_MPI (const tbox::SAMRAI_MPI & mpi, bool make_duplicate = true)
Set the SAMRAI_MPI to use.
If set, communication will use the specified SAMRAI_MPI instead of the SAMRAI_MPI from BoxLevels. This protects communication operations from accidentally interacting with unrelated communications, but it limits operations to work only with metadata objects with comptatible (congruent) SAMRAI_MPI objects.
If make_duplicate is true, the specified SAMRAI_MPI will be duplicated for exclusise use. The duplicate will be freed upon object destruction.
References SAMRAI::tbox::SAMRAI_MPI::dupCommunicator(), and SAMRAI::tbox::SAMRAI_MPI::freeCommunicator().
Referenced by SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm().
void SAMRAI::hier::OverlapConnectorAlgorithm::setPrintSteps (bool print_steps) [inline]
When print_steps is true, print what the code is doing.
Note:
Step printing may be expensive and and is meant mainly for debugging.
Parameters:
[in] print_steps
void SAMRAI::hier::OverlapConnectorAlgorithm::setTimerPrefix (const std::string & timer_prefix)
Setup names of timers.
By default, timers are named "hier::OverlapConnectorAlgorithm::*", where the third field is the specific steps performed by the MappingConnectorAlgorithm. You can override the first two fields with this method. Conforming to the timer naming convention, timer_prefix should have the form "*::*".
Referenced by SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), OverlapConnectorAlgorithm(), and SAMRAI::mesh::TileClustering::TileClustering().
const std::string SAMRAI::hier::OverlapConnectorAlgorithm::getObjectName () const [inline]
Get the name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/OverlapConnectorAlgorithm.h
source/SAMRAI/hier/OverlapConnectorAlgorithm.C