SAMRAI: SAMRAI::tbox::Schedule Class Reference
SAMRAI::tbox::Schedule Class Reference
Class Schedule is used to construct and execute a set of data communication transactions. Each transaction represents some data dependency and exchange between two processors, or locally involving a single processor.
#include <source/SAMRAI/tbox/Schedule.h>
Public Member Functions
Schedule ()
Create an empty schedule with no transactions.
~Schedule ()
The destructor deletes the schedule and all associated storage.
void addTransaction (const boost::shared_ptr< Transaction > &transaction)
Add a data transaction to the head of the list of transactions in the schedule.
void appendTransaction (const boost::shared_ptr< Transaction > &transaction)
Append a data transaction to the tail of the list of transactions in the schedule.
int getNumSendTransactions (const int rank) const
Return number of send transactions in the schedule.
int getNumRecvTransactions (const int rank) const
Return number of receive transactions in the schedule.
int getNumLocalTransactions () const
Return number of local transactions (non-communicating) in the schedule.
void setMPI (const SAMRAI_MPI &mpi)
Set the MPI communicator used for communication.
void setMPITag (const int first_tag, const int second_tag)
Specify MPI tag values to use in communication.
void setFirstMessageLength (int first_message_length)
Specify the message length (in bytes) used in the first message when the receiving processor cannot determine the message length.
void communicate ()
Perform the communication described by the schedule.
void beginCommunication ()
Begin the communication process but do not deliver data to the transaction objects.
void finalizeCommunication ()
Finish the communication and deliver the messages.
void setDeterministicUnpackOrderingFlag (bool flag)
Set whether to unpack messages in a deterministic order.
void setTimerPrefix (const std::string &timer_prefix)
Setup names of timers.
void printClassData (std::ostream &stream) const
Print class data to the specified output stream.
bool allocatedCommunicationObjects ()
Returns true if the communication objects have been allocated.
const std::string getObjectName () const
Get the name of this object.
Detailed Description
Class Schedule is used to construct and execute a set of data communication transactions. Each transaction represents some data dependency and exchange between two processors, or locally involving a single processor.
Once a communication schedule is constructed, transactions are provided to the schedule, using either the addTransaction() method or the appendTransaction() method. The schedule is then executed forcing the communication, either interprocessor or local to occur. The basic idea behind the schedule is that it enables the cost of assembling communication dependencies and data transfers to be amortized over many communication phases.
Note that since the transactions are stored in lists, the "add" and "append" mimick the semantics of the List class. That is, addTransaction() will put the transaction at the head of the list, while appendTransaction() will put the transaction at the end of the list. This flexibility is provided for situations where the order of transaction execution matters. The transactions will be executed in the order in which they appear in the list.
See also:
Transaction
Constructor & Destructor Documentation
SAMRAI::tbox::Schedule::Schedule ()
Create an empty schedule with no transactions.
References setTimerPrefix().
SAMRAI::tbox::Schedule::~Schedule ()
The destructor deletes the schedule and all associated storage.
Note that the schedule can not be deleted during a communication phase; this will result in an assertion being thrown.
Precondition:
!allocatedCommunicationObjects()
References allocatedCommunicationObjects(), and TBOX_ERROR.
Member Function Documentation
void SAMRAI::tbox::Schedule::addTransaction (const boost::shared_ptr< Transaction > & transaction)
Add a data transaction to the head of the list of transactions in the schedule.
The transaction must involve the local processor as either a source or destination or both. If the transaction does not include the local processor, then the transaction is not placed on the schedule.
Parameters:
transaction boost::shared_ptr to transaction added to the schedule.
References SAMRAI::tbox::SAMRAI_MPI::getRank().
Referenced by SAMRAI::tbox::Statistician::finalize().
void SAMRAI::tbox::Schedule::appendTransaction (const boost::shared_ptr< Transaction > & transaction)
Append a data transaction to the tail of the list of transactions in the schedule.
The transaction must involve the local processor as either a source or destination or both. If the transaction does not include the local processor, then the transaction will not be not placed on the schedule.
Parameters:
transaction boost::shared_ptr to transaction appended to the schedule.
References SAMRAI::tbox::SAMRAI_MPI::getRank().
int SAMRAI::tbox::Schedule::getNumSendTransactions (const int rank) const
Return number of send transactions in the schedule.
int SAMRAI::tbox::Schedule::getNumRecvTransactions (const int rank) const
Return number of receive transactions in the schedule.
int SAMRAI::tbox::Schedule::getNumLocalTransactions () const [inline]
Return number of local transactions (non-communicating) in the schedule.
void SAMRAI::tbox::Schedule::setMPI (const SAMRAI_MPI & mpi) [inline]
Set the MPI communicator used for communication.
By default the communicator returned by SAMRAI_MPI::getCommunicator() at the time the Schedule constructor is called is used. This method may be used to override the default communicator.
void SAMRAI::tbox::Schedule::setMPITag (const int first_tag, const int second_tag) [inline]
Specify MPI tag values to use in communication.
If you are using MPI communicators that are not sufficiently isolated from other communications, you can specify distinct tags to avoid message mix-ups. Up to two messages are sent from each communicating pairs. Specify two distinct tags.
Precondition:
first_tag >= 0
second_tag >= 0
References TBOX_ASSERT.
void SAMRAI::tbox::Schedule::setFirstMessageLength (int first_message_length) [inline]
Specify the message length (in bytes) used in the first message when the receiving processor cannot determine the message length.
A receiving transaction cannot always determine the length of data it is receiving. In this case, first a message of length first_message_length is sent. The first message includes the full length of the data that is being sent so the receiver can determine if a second message, with the remainder of the data, is needed. If the length of the data being sent is less than first_message_length, only a single message is sent.
Setting a first_message_length too small creates the need for many second messages. Setting it to an excessive length wastes memory.
This two message protocol was designed based on the observed platform-dependent MPI implementation feature where a message of a small length takes the same time as sending an empty message. A protocol of sending the message length first and then a second message with the data does not exploit this property. The message protocol SAMRAI uses of sending some small amount of data with the first message does exploit this property and will save the cost of always communicating two messages for small messages. Currently SAMRAI does not attempt to automatically determine this message length however that may be added in future versions.
first_message_length defaults to 1000.
Parameters:
first_message_length length (in bytes) of first message
Precondition:
first_message_length > 0
References TBOX_ASSERT.
void SAMRAI::tbox::Schedule::communicate ()
Perform the communication described by the schedule.
This method is simply a beginCommunication() followed by finalizeCommunication().
References beginCommunication(), finalizeCommunication(), SAMRAI::tbox::SAMRAI_MPI::hasReceivableMessage(), MPI_ANY_SOURCE, MPI_ANY_TAG, and TBOX_ERROR.
Referenced by SAMRAI::tbox::Statistician::finalize().
void SAMRAI::tbox::Schedule::beginCommunication ()
Begin the communication process but do not deliver data to the transaction objects.
This method must be followed by a call to finalizeCommunication() in order to complete the communication.
Referenced by communicate().
void SAMRAI::tbox::Schedule::finalizeCommunication ()
Finish the communication and deliver the messages.
This method must follow a communication begun by beginCommunication() and communication is completed when this method returns.
Referenced by communicate().
void SAMRAI::tbox::Schedule::setDeterministicUnpackOrderingFlag (bool flag) [inline]
Set whether to unpack messages in a deterministic order.
By default message unpacking is ordered by receive time, which is not deterministic. If your results are dependent on unpack ordering and you want deterministic results, set this flag to true.
Parameters:
[in] flag
void SAMRAI::tbox::Schedule::setTimerPrefix (const std::string & timer_prefix)
Setup names of timers.
By default, timers are named "tbox::Schedule::*", where the third field is the specific steps performed by the Schedule. You can override the first two fields with this method. Conforming to the timer naming convention, timer_prefix should have the form "*::*".
References SAMRAI::tbox::AsyncCommStage::setCommunicationWaitTimer().
Referenced by SAMRAI::tbox::Statistician::finalize(), and Schedule().
void SAMRAI::tbox::Schedule::printClassData (std::ostream & stream) const
Print class data to the specified output stream.
bool SAMRAI::tbox::Schedule::allocatedCommunicationObjects () [inline]
Returns true if the communication objects have been allocated.
Referenced by ~Schedule().
const std::string SAMRAI::tbox::Schedule::getObjectName () const [inline]
Get the name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Schedule.h
source/SAMRAI/tbox/Schedule.C