SAMRAI: SAMRAI::tbox::BreadthFirstRankTree Class Reference
SAMRAI::tbox::BreadthFirstRankTree Class Reference
Implementation of RankTreeStrategy aranging ranks in a breadth-first tree.
#include <source/SAMRAI/tbox/BreadthFirstRankTree.h>
Public Types
typedef int LocalId
Public Member Functions
BreadthFirstRankTree ()
Constructor.
BreadthFirstRankTree (int first_rank, int last_rank, int rank, unsigned int degree=2)
Initializing constructor.
~BreadthFirstRankTree ()
Destructor.
void setupTree (const RankGroup &rank_group, int my_rank)
Set up the tree.
int getRank () const
Access the rank used to initialize.
int getParentRank () const
Access the parent rank.
int getChildRank (unsigned int child_number) const
Access a child rank.
unsigned int getNumberOfChildren () const
Return the number of children.
unsigned int getChildNumber () const
Return the child number, or invalidChildNumber() if is root of the tree.
unsigned int getDegree () const
Return the degree of the tree (the maximum number of children each node may have).
unsigned int getGenerationNumber () const
Return the generation number.
int getRootRank () const
Return the rank of the root of the tree.
void setTreeDegree (unsigned int tree_degree)
Set the degree (max number of children) of the tree.
Detailed Description
Implementation of RankTreeStrategy aranging ranks in a breadth-first tree.
An example of a binary tree created is
 *                     0
 *                    / \
 *                   /   \
 *                  /     \
 *                 1       2
 *                / \     / \
 *               3   4   5   6
 *              /|  /|   |\   \
 *             7 8 9 10 11 12 13...
 *
The degree of the tree (max number of children at each node) can be set using setTreeDegree(), but that must be done before the tree is set up. The default is a binary tree (two children).
A property of the tree is that the first rank, i0, is always the root. It is a d-degree tree. The children of rank i are rank d*(i-i0) and d*(i-i0)+1. It's parent is rank (i-i0-1)/d. The tree is as balanced as possible. Node ranks are close to their siblings but not their parents. This arangement does not map well to any known communication networks, so this tree does not perform well. It is included for comparison.
Member Typedef Documentation
typedef int SAMRAI::tbox::BreadthFirstRankTree::LocalId
Constructor & Destructor Documentation
SAMRAI::tbox::BreadthFirstRankTree::BreadthFirstRankTree ()
Constructor.
SAMRAI::tbox::BreadthFirstRankTree::BreadthFirstRankTree (int first_rank, int last_rank, int rank, unsigned int degree = 2)
Initializing constructor.
Parameters:
[in] first_rank
[in] last_rank
[in] rank
[in] degree See setTreeDegree()
See also:
initialize().
SAMRAI::tbox::BreadthFirstRankTree::~BreadthFirstRankTree ()
Destructor.
Deallocate internal data.
Member Function Documentation
void SAMRAI::tbox::BreadthFirstRankTree::setupTree (const RankGroup & rank_group, int my_rank) [virtual]
Set up the tree.
Set up the tree for the processors in the given RankGroup. Prepare to provide tree data for the given rank.
Parameters:
[in] rank_group
[in] my_rank The rank whose parent and children are sought, usually the local process.
Implements SAMRAI::tbox::RankTreeStrategy.
References SAMRAI::tbox::RankGroup::getMapIndex(), SAMRAI::tbox::RankGroup::isMember(), SAMRAI::tbox::RankGroup::size(), and TBOX_ASSERT.
int SAMRAI::tbox::BreadthFirstRankTree::getRank () const [inline, virtual]
Access the rank used to initialize.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::BreadthFirstRankTree::getParentRank () const [inline, virtual]
Access the parent rank.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::BreadthFirstRankTree::getChildRank (unsigned int child_number) const [inline, virtual]
Access a child rank.
Parameters:
[in] child_number a binary tree.
Implements SAMRAI::tbox::RankTreeStrategy.
References SAMRAI::tbox::RankTreeStrategy::getInvalidRank().
unsigned int SAMRAI::tbox::BreadthFirstRankTree::getNumberOfChildren () const [inline, virtual]
Return the number of children.
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::BreadthFirstRankTree::getChildNumber () const [inline, virtual]
Return the child number, or invalidChildNumber() if is root of the tree.
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::BreadthFirstRankTree::getDegree () const [inline, virtual]
Return the degree of the tree (the maximum number of children each node may have).
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::BreadthFirstRankTree::getGenerationNumber () const [inline, virtual]
Return the generation number.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::BreadthFirstRankTree::getRootRank () const [inline, virtual]
Return the rank of the root of the tree.
Implements SAMRAI::tbox::RankTreeStrategy.
void SAMRAI::tbox::BreadthFirstRankTree::setTreeDegree (unsigned int tree_degree) [inline]
Set the degree (max number of children) of the tree.
Default choice is 2 (binary tree). To change the choice, this call must be made before setupTree().
References SAMRAI::tbox::RankTreeStrategy::getInvalidRank(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/BreadthFirstRankTree.h
source/SAMRAI/tbox/BreadthFirstRankTree.C