SAMRAI: SAMRAI::solv::SAMRAIVectorReal< TYPE > Class Template Reference
SAMRAI::solv::SAMRAIVectorReal< TYPE > Class Template Reference
#include <source/SAMRAI/solv/SAMRAIVectorReal.h>
Public Member Functions
SAMRAIVectorReal (const std::string &name, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int coarsest_level, const int finest_level)
virtual ~SAMRAIVectorReal ()
void setName (const std::string &name)
void setOutputStream (std::ostream &s)
std::ostream & getOutputStream ()
void resetLevels (const int coarsest_level, const int finest_level)
const std::string & getName () const
boost::shared_ptr
< hier::PatchHierarchy > getPatchHierarchy () const
int getCoarsestLevelNumber () const
int getFinestLevelNumber () const
int getNumberOfComponents () const
boost::shared_ptr
< hier::PatchData > getComponentPatchData (const int comp_id, const hier::Patch &patch) const
boost::shared_ptr
< hier::PatchData > getComponentPatchData (const boost::shared_ptr< hier::Variable > &var, const hier::Patch &patch) const
boost::shared_ptr< hier::Variable > getComponentVariable (const int component) const
int getComponentDescriptorIndex (const int component) const
int getControlVolumeIndex (const int component) const
boost::shared_ptr
< SAMRAIVectorReal< TYPE > > cloneVector (const std::string &name) const
void freeVectorComponents ()
void addComponent (const boost::shared_ptr< hier::Variable > &var, const int comp_data_id, const int control_vol_id=-1, const boost::shared_ptr< math::HierarchyDataOpsReal< TYPE > > &vop=boost::shared_ptr< math::HierarchyDataOpsReal< TYPE > >())
void allocateVectorData (const double timestamp=0.0)
void deallocateVectorData ()
void print (std::ostream &s=tbox::plog, const bool interior_only=true) const
void copyVector (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &src_vec, const bool interior_only=true)
void swapVectors (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &other)
Vector arithmetic functions
void setToScalar (const TYPE &alpha, const bool interior_only=true)
void scale (const TYPE &alpha, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const bool interior_only=true)
void addScalar (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const TYPE &alpha, const bool interior_only=true)
void add (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &y, const bool interior_only=true)
void subtract (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &y, const bool interior_only=true)
void multiply (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &y, const bool interior_only=true)
void divide (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &y, const bool interior_only=true)
void reciprocal (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const bool interior_only=true)
void linearSum (const TYPE &alpha, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const TYPE &beta, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &y, const bool interior_only=true)
void axpy (const TYPE &alpha, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &y, const bool interior_only=true)
void abs (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const bool interior_only=true)
TYPE min (const bool interior_only=true) const
TYPE max (const bool interior_only=true) const
void setRandomValues (const TYPE &width, const TYPE &low, const bool interior_only=true)
double L1Norm (bool local_only=false) const
double L2Norm (bool local_only=false) const
double weightedL2Norm (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &wgt) const
double RMSNorm () const
double weightedRMSNorm (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &wgt) const
double maxNorm (bool local_only=false) const
TYPE dot (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, bool local_only=false) const
int computeConstrProdPos (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x) const
void compareToScalar (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x, const TYPE &alpha)
int testReciprocal (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &x)
TYPE maxPointwiseDivide (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > &denom) const
Compute max of "conditional" quotients of two arrays.
Detailed Description
template<class TYPE>
class SAMRAI::solv::SAMRAIVectorReal< TYPE >
Class SAMRAIVectorReal allows a collection of patch data types (with double or float data, but not both) defined over a SAMRAI hierarchy to be manipulated as though they are all part of a single vector. Specifically, this class provides a set of common vector operations to manipulate all of the data components as a whole. The most obvious use of this class is in SAMRAI applications that use solver libraries, such as KINSOL, CVODE, or PETSc. Specific vector objects that can be used with these packages are defined elsewhere in SAMRAI. However, all these vactor interfaces are built using this vector class.
This class defines a vector to be any collection of patch data objects (either cell-, edge-, face-, node, or side-centered, or any combination of these) defined over a set of patch levels in an AMR hierarchy. All of the data objects must have the same underlying data type, either double or float. The vector structure is composed by adding individual variable quantities to the vector after it is constructed. When a component is added, a weighting or "control volume" component (having the same type as the vector component) may also be added to the vector. These weights are used to define the contribution of each vector entry to summing operations such as norms and dot products. For example, the weights can be used to mask out coarse level vector data entries in cells that are covered by fine cells when the coarse data are not actually part of the solution vector. The weights can also be used to map the vector operations to grid-based operations that define control volume weights. It is important to note that the centering of each control volume component must match that of the vector component with which it is associated.
Typical usage of this vector class is as follows:
(1) Construct a vector instance by specifying the patch hierarchy and range of levels over which the vector is defined. The levels must exist in the hierarchy before the vector can be used or an assertion will result. However, a vector may be created before the levels exist. The range of levels can be reset (such as after remeshing) by calling the resetLevels() function.
(2) Register each data component with the vector by providing the variable and its storage location (i.e., patch data index), and the control volume index if needed. See the addComponent() functions.
(3) Manipulate data using vector operations.
Before the vector operations can be used, the storage for each of its components must be allocated. Storage allocation is only possible through a vector object after all component variables are added to the vector (using the addComponent() function). Then, the allocateVectorData() function will allocate storage for all components when called. Alternatively, patch data objects (corresponding to the variables and vector patch data indices) may be explicitly created elsewhere. However, depending on the circumstance, this second alternative may be more confusing and require more bookkeeping on the user's part. See the documentation accompanying the addComponent() function for more information.
See also:
math::HierarchyDataOpsReal
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::solv::SAMRAIVectorReal< TYPE >::SAMRAIVectorReal (const std::string & name, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int coarsest_level, const int finest_level) [inline]
Constructor for SAMRAIVectorReal class is used to construct each unique vector within an application. That is, each vector that is used to represent a unique set of variable quantities is considered unique. This constructor is used to create a solution vector for an application or solver algorithm. The cloneVector() function is provided to generate copies of a given vector. For example, the clone function may be used by a solver to generate copies of the vector as needed; e.g., in a Krylov subspace method like GMRES.
Before the vector may be used, data components must be added to it using the adddComponent(0 function. Also, this constructor does not allocate storage for vector data. This is usually done after all components are added. The allocateVectorData() function is used for this purpose. Otherwise, existing patch data quantities can be added as vector components. In any case, storage for all components must be allocated before the vector can be used.
The range levels can be reset at any time (e.g., if the level configuration changes by re-meshing), by calling the resetLevels() member function.
Although an empty std::string may be passed as the vector name, it is recommended that a descriptive name be used to facilitate debugging and error reporting.
By default the vector component information and data will be sent to the "plog" output stream when the print() function is called. This stream can be changed at any time via the setOutputStream() function.
Precondition:
hierarchy
(coarsest_level >= 0) && (finest_level >= coarsest_level) && (finest_level <= hierarchy->getFinestLevelNumber())
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::getFinestLevelNumber(), SAMRAI::tbox::plog, and TBOX_ASSERT.
template<class TYPE > SAMRAI::solv::SAMRAIVectorReal< TYPE >::~SAMRAIVectorReal () [inline, virtual]
Virtual destructor for SAMRAIVectorReal class. The destructor destroys all vector component information. However, the destructor does not deallocate the vector component storage, nor does it return the vector patch data indices to the patch descriptor free list. The freeVectorComponents() function is provided for this task. The reason for this is that an application may create a vector based on some pre-existing patch data objects that must live beyond the destruction of the vector object.
Member Function Documentation
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::setName (const std::string & name) [inline]
Set std::string identifier for this vector object.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::setOutputStream (std::ostream & s) [inline]
Set output stream for vector object. When the print() function is called, all vector data will be sent to the given output stream.
template<class TYPE > std::ostream & SAMRAI::solv::SAMRAIVectorReal< TYPE >::getOutputStream () [inline]
Return reference to the output stream used by this vector object. This function is primarily used by classes which define interfaces between this vector class and vector kernels defined by other packages. Specifically, SAMRAI vectors and package-specific wrappers for those vectors may all access the same output stream.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::resetLevels (const int coarsest_level, const int finest_level) [inline]
Reset range of patch levels over which vector is defined. This function resets the data operations for all vector components. Note that the levels must exist in the hierarchy when this function is called or a non-recoverable assertion will result.
template<class TYPE > const std::string & SAMRAI::solv::SAMRAIVectorReal< TYPE >::getName (void) const [inline]
Return std::string identifier for this vector object.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::print().
template<class TYPE > boost::shared_ptr< hier::PatchHierarchy > SAMRAI::solv::SAMRAIVectorReal< TYPE >::getPatchHierarchy () const [inline]
Return pointer to patch hierarchy associated with the vector.
Referenced by SAMRAI::solv::FACPreconditioner::checkVectorStateCompatibility(), SAMRAI::solv::CellPoissonFACOps::computeCompositeResidualOnLevel(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), SAMRAI::solv::FACPreconditioner::initializeSolverState(), and SAMRAI::solv::CellPoissonFACOps::prolongErrorAndCorrect().
template<class TYPE > int SAMRAI::solv::SAMRAIVectorReal< TYPE >::getCoarsestLevelNumber () const [inline]
Return integer number of coarsest hierarchy level for vector.
Referenced by SAMRAI::solv::FACPreconditioner::checkVectorStateCompatibility(), SAMRAI::solv::CellPoissonFACOps::computeResidualNorm(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), and SAMRAI::solv::FACPreconditioner::initializeSolverState().
template<class TYPE > int SAMRAI::solv::SAMRAIVectorReal< TYPE >::getFinestLevelNumber () const [inline]
Return integer number of finest hierarchy level for vector.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::allocateVectorData(), SAMRAI::solv::FACPreconditioner::checkVectorStateCompatibility(), SAMRAI::solv::CellPoissonFACOps::computeResidualNorm(), SAMRAI::solv::SAMRAIVectorReal< TYPE >::deallocateVectorData(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), SAMRAI::solv::FACPreconditioner::initializeSolverState(), and SAMRAI::solv::SAMRAIVectorReal< TYPE >::SAMRAIVectorReal().
template<class TYPE > int SAMRAI::solv::SAMRAIVectorReal< TYPE >::getNumberOfComponents () const [inline]
Return integer number of patch data components in vector.
Referenced by SAMRAI::solv::FACPreconditioner::checkVectorStateCompatibility(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), and SAMRAI::solv::FACPreconditioner::initializeSolverState().
template<class TYPE > boost::shared_ptr< hier::PatchData > SAMRAI::solv::SAMRAIVectorReal< TYPE >::getComponentPatchData (const int comp_id, const hier::Patch & patch) const [inline]
Return patch data object for given vector component index.
Precondition:
(comp_id >= 0) && (comp_id < getNumberOfComponents())
References SAMRAI::hier::Patch::getPatchData(), and TBOX_ASSERT.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeCompositeResidualOnLevel().
template<class TYPE > boost::shared_ptr< hier::PatchData > SAMRAI::solv::SAMRAIVectorReal< TYPE >::getComponentPatchData (const boost::shared_ptr< hier::Variable > & var, const hier::Patch & patch) const [inline]
Return patch data object associated with given variable.
Precondition:
var
d_variableid_2_vectorcomponent_map[var->getInstanceIdentifier()] >= 0
References SAMRAI::hier::Patch::getPatchData(), and TBOX_ASSERT.
template<class TYPE > boost::shared_ptr< hier::Variable > SAMRAI::solv::SAMRAIVectorReal< TYPE >::getComponentVariable (const int component) const [inline]
Return pointer to variable for specified vector component.
Precondition:
(component >= 0) && (component < getNumberOfComponents())
References TBOX_ASSERT.
Referenced by SAMRAI::solv::FACPreconditioner::initializeSolverState().
template<class TYPE > int SAMRAI::solv::SAMRAIVectorReal< TYPE >::getComponentDescriptorIndex (const int component) const [inline]
Return patch data index for specified vector component.
Precondition:
(component >= 0) && (component < getNumberOfComponents())
References TBOX_ASSERT.
Referenced by SAMRAI::solv::CellPoissonFACOps::computeCompositeResidualOnLevel(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), SAMRAI::solv::CellPoissonFACOps::prolongErrorAndCorrect(), SAMRAI::solv::CellPoissonFACOps::restrictResidual(), SAMRAI::solv::CellPoissonFACOps::restrictSolution(), SAMRAI::solv::CellPoissonFACOps::solveCoarsestLevel(), and SAMRAI::solv::FACPreconditioner::solveSystem().
template<class TYPE > int SAMRAI::solv::SAMRAIVectorReal< TYPE >::getControlVolumeIndex (const int component) const [inline]
Return patch data index of control volume data for vector component.
Precondition:
(component >= 0) && (component < getNumberOfComponents())
References TBOX_ASSERT.
template<class TYPE > boost::shared_ptr< SAMRAIVectorReal< TYPE > > SAMRAI::solv::SAMRAIVectorReal< TYPE >::cloneVector (const std::string & name) const [inline]
Clone this vector object and return a pointer to the vector copy (i.e., a new vector). Each patch data component in the new vector will match the corresponding component in this vector object. However, the data for the components of the new vector will be assigned to different patch data indices than the original. In short, the cloned vector will have an identical structure to the original, but its data storage will be distinct. Before the new vector object can be used, its data must be allocated explicitly.
Note that this function maps the variables associated with the new vector to the new vector component data indices (i.e., patch data indices) in the variable database. Thus the mapping between variables and patch data for the new vector can be obtained from the variable database if needed.
If an empty std::string is passed in, the name of this vector object is used for the new vector.
References SAMRAI::hier::VariableDatabase::getDatabase(), and SAMRAI::hier::VariableDatabase::registerClonedPatchDataIndex().
Referenced by SAMRAI::solv::FACPreconditioner::initializeSolverState().
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::freeVectorComponents () [inline]
Destroy the storage corresponding to the vector components and free the associated patch data entries from the variable database (which will also clear the indices from the patch descriptor).
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::deallocateVectorData(), SAMRAI::hier::VariableDatabase::getDatabase(), and SAMRAI::hier::VariableDatabase::removePatchDataIndex().
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::addComponent (const boost::shared_ptr< hier::Variable > & var, const int comp_data_id, const int control_vol_id = -1, const boost::shared_ptr< math::HierarchyDataOpsReal< TYPE > > & vop = boost::shared_ptr<math::HierarchyDataOpsReal<TYPE> >()) [inline]
Add a new variable and patch data component to this vector. The integer values passed in represent the patch data indices for the vector component data and the component control volume data. If the control volume patch data index is not specified (i.e., control_vol_id < 0), no weighting will be applied in vector operations associated with the component. This routine also accepts a hierarchy data operation object for the component should the user want to provide a special set of such operations. If left unspecified (nearly all cases), the standard operations for the given variable type are used.
Note that this function maps the variable to the component data index (i.e., patch data index) in the variable database. Thus, the mapping between the variable and its patch data for the vector can be obtained from the variable database if needed.
Precondition:
hier::VariableDatabase::getDatabase()->checkVariablePatchDataIndexType(var, comp_data_id)
(comp_vol_id < 0) || (hier::VariableDatabase::getDatabase()->checkVariablePatchDataIndexType(var, comp_vol_id))
References SAMRAI::hier::VariableDatabase::checkVariablePatchDataIndexType(), SAMRAI::hier::VariableDatabase::getDatabase(), SAMRAI::hier::VariableDatabase::getPatchDescriptor(), and TBOX_ERROR.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::allocateVectorData (const double timestamp = 0.0) [inline]
Allocate data storage for all components of this vector object.
Precondition:
getPatchHierarchy
(getCoarsestLevelNumber() >= 0) && (getFinestLevelNumber() >= getCoarsestLevelNumber()) && (getFinestLevelNumber(<= d_hierarchy->getFinestLevelNumber())
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::getFinestLevelNumber(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::deallocateVectorData () [inline]
Deallocate data storage for all components of this vector object. Note that this routine will not free the associated data indices in the patch descriptor. See freeVectorComponents() function.
Precondition:
getPatchHierarchy
(getCoarsestLevelNumber() >= 0) && (getFinestLevelNumber() >= getCoarsestLevelNumber()) && (getFinestLevelNumber(<= d_hierarchy->getFinestLevelNumber())
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::getFinestLevelNumber(), and TBOX_ASSERT.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::freeVectorComponents().
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::print (std::ostream & s = tbox::plog, const bool interior_only = true) const [inline]
Print component information and data for this vector object.
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::getName().
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::copyVector (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & src_vec, const bool interior_only = true) [inline]
Copy data from source vector components to components of this vector.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::swapVectors (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & other) [inline]
Swap data components (i.e. storage) between this vector object and argument vector.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::setToScalar (const TYPE & alpha, const bool interior_only = true) [inline]
Set all components of this vector to given scalar value.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::scale (const TYPE & alpha, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const bool interior_only = true) [inline]
Set this vector to src vector multiplied by given scalar.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::addScalar (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const TYPE & alpha, const bool interior_only = true) [inline]
Set this vector to sum of given vector and scalar.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::add (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & y, const bool interior_only = true) [inline]
Set this vector to sum of two given vectors.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::subtract (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & y, const bool interior_only = true) [inline]
Set this vector to difference of two given vectors (i.e., x - y).
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::multiply (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & y, const bool interior_only = true) [inline]
Set each entry in this vector to product of corresponding entries in input vectors.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::divide (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & y, const bool interior_only = true) [inline]
Set each entry in this vector to ratio of corresponding entries in input vectors (i.e., x / y). No check for division by zero.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::reciprocal (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const bool interior_only = true) [inline]
Set each entry of this vector to reciprocal of corresponding entry in input vector. No check is made for division by zero.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::linearSum (const TYPE & alpha, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const TYPE & beta, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & y, const bool interior_only = true) [inline]
Set this vector to the linear sum , where are scalars and are vectors.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::axpy (const TYPE & alpha, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & y, const bool interior_only = true) [inline]
Set this vector to the sum , where is a scalar and are vectors.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::abs (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const bool interior_only = true) [inline]
Set each entry of this vector to absolute values of corresponding entry in input vector.
template<class TYPE > TYPE SAMRAI::solv::SAMRAIVectorReal< TYPE >::min (const bool interior_only = true) const [inline]
Return the minimum data entry in this vector. Note that this routine returns a global min over all vector components and makes no adjustment for coarser level vector data that may be masked out by the existence of underlying fine values. In particular, the control volumes are not used in this operation. This may change based on user needs.
template<class TYPE > TYPE SAMRAI::solv::SAMRAIVectorReal< TYPE >::max (const bool interior_only = true) const [inline]
Return the maximum entry of this vector. Note that this routine returns a global max over all vector components and makes no adjustment for coarser level vector data that may be masked out by the existence of underlying fine values. In particular, the control volumes are not used in this operation. This may change based on user needs.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::maxPointwiseDivide().
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::setRandomValues (const TYPE & width, const TYPE & low, const bool interior_only = true) [inline]
Set data in this vector to random values.
template<class TYPE > double SAMRAI::solv::SAMRAIVectorReal< TYPE >::L1Norm (bool local_only = false) const [inline]
Return discrete -norm of this vector using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is not defined for a component, the contribution is for that data component. Thus, to have a consistent norm calculation all components must have control volumes, or no control volumes should be used at all.
template<class TYPE > double SAMRAI::solv::SAMRAIVectorReal< TYPE >::L2Norm (bool local_only = false) const [inline]
Return discrete -norm of this vector using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is not defined for a component, the contribution is for that data component. Thus, to have a consistent norm calculation all components must have control volumes, or no control volumes should be used at all.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::RMSNorm().
template<class TYPE > double SAMRAI::solv::SAMRAIVectorReal< TYPE >::weightedL2Norm (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & wgt) const [inline]
Return discrete weighted -norm of this vector using the control volume to weight the contribution of the data and weight entries to the sum. That is, the return value is the sum . If the control volume is not defined for a component, the contribution is for that data component. Thus, to have a consistent norm calculation all components must have control volumes, or no control volumes should be used at all.
Referenced by SAMRAI::solv::SAMRAIVectorReal< TYPE >::weightedRMSNorm().
template<class TYPE > double SAMRAI::solv::SAMRAIVectorReal< TYPE >::RMSNorm () const [inline]
Return discrete root mean squared norm of this vector. If control volumes are defined for all components, the return value is the -norm divided by the square root of the sum of the control volumes. If the control volume is not defined for a component, its contribution to the norm corresponds to its -norm divided by the square root of the number of data entries. Thus, to have a consistent norm calculation all components must have control volumes, or no control volumes should be used at all.
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::L2Norm().
Referenced by SAMRAI::solv::CellPoissonFACOps::computeResidualNorm().
template<class TYPE > double SAMRAI::solv::SAMRAIVectorReal< TYPE >::weightedRMSNorm (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & wgt) const [inline]
Return discrete weighted root mean squared norm of this vector. If control volumes are defined for all components, the return value is the weighted -norm divided by the square root of the sum of the control volumes. If the control volume is not defined for a component, its contribution to the norm corresponds to its weighted -norm divided by the square root of the number of data entries. Thus, to have a consistent norm calculation all components must have control volumes, or no control volumes should be used at all.
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::weightedL2Norm().
template<class TYPE > double SAMRAI::solv::SAMRAIVectorReal< TYPE >::maxNorm (bool local_only = false) const [inline]
Return the -norm of this vector. If control volumes are defined for all components, the return value is the max norm over all data values where the control volumes are non-zero. If the control volume is not defined for a component, its contribution to the norm will take a max over all of its data values. Thus, to have a consistent norm calculation all components must have control volumes, or no control volumes should be used at all.
template<class TYPE > TYPE SAMRAI::solv::SAMRAIVectorReal< TYPE >::dot (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, bool local_only = false) const [inline]
Return the dot product of this vector with the argument vector. If control volumes are defined for all components, the return value is a weighted sum involving all data values where the control volumes are non-zero. If the control volume is not defined for a component, its contribution to the sum will involve all of its data values. Thus, to have a consistent dot product calculation all components must have control volumes, or no control volumes should be used at all.
template<class TYPE > int SAMRAI::solv::SAMRAIVectorReal< TYPE >::computeConstrProdPos (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x) const [inline]
Return 1 if and , for any in the set of vector data indices, where . Here, is a data entry in this vector. Otherwise, return 0. If the control volume is undefined for a component, all data values for the component are considered in the test. Thus, to have a consistent test all components must have control volumes, or no control volumes should be used at all.
template<class TYPE > void SAMRAI::solv::SAMRAIVectorReal< TYPE >::compareToScalar (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x, const TYPE & alpha) [inline]
Wherever in the set of vector data indices, set if , and otherwise. Here, is a data entry in this vector. If the control volume is undefined for a component, all data values for the component are involved in the comparison. Thus, to have a consistent comparison all components must have control volumes, or no control volumes should be used at all.
template<class TYPE > int SAMRAI::solv::SAMRAIVectorReal< TYPE >::testReciprocal (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & x) [inline]
Wherever in the set of vector data indices, set if , and otherwise. Here, is a data entry in this vector. If the control volume is undefined for a component, all data values for the component are involved in the operation. Thus, to have a consistent operation all components must have control volumes, or no control volumes should be used at all.
template<class TYPE > TYPE SAMRAI::solv::SAMRAIVectorReal< TYPE >::maxPointwiseDivide (const boost::shared_ptr< SAMRAIVectorReal< TYPE > > & denom) const [inline]
Compute max of "conditional" quotients of two arrays.
Return the maximum of pointwise "conditional" quotients of the numerator and denominator.
The "conditional" quotient is defined as |numerator/denominator| if the denominator is nonzero. Otherwise, it is defined as |numerator|.
Note: This method is currently intended to support the PETSc-2.1.6 vector wrapper only. Please do not use it!
References SAMRAI::solv::SAMRAIVectorReal< TYPE >::max(), and MPI_MAX.
The documentation for this class was generated from the following files:
source/SAMRAI/solv/SAMRAIVectorReal.h
source/SAMRAI/solv/SAMRAIVectorReal.C