SAMRAI: SAMRAI::math::HierarchyNodeDataOpsReal< TYPE > Class Template Reference
SAMRAI::math::HierarchyNodeDataOpsReal< TYPE > Class Template Reference
#include <source/SAMRAI/math/HierarchyNodeDataOpsReal.h>
Public Member Functions
HierarchyNodeDataOpsReal (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int coarsest_level=-1, const int finest_level=-1)
virtual ~HierarchyNodeDataOpsReal ()
void setPatchHierarchy (const boost::shared_ptr< hier::PatchHierarchy > &hierarchy)
void resetLevels (const int coarsest_level, const int finest_level)
const boost::shared_ptr
< hier::PatchHierarchy > getPatchHierarchy () const
void copyData (const int dst_id, const int src_id, const bool interior_only=true) const
void swapData (const int data1_id, const int data2_id) const
void printData (const int data_id, std::ostream &s, const bool interior_only=true) const
void setToScalar (const int data_id, const TYPE &alpha, const bool interior_only=true) const
void scale (const int dst_id, const TYPE &alpha, const int src_id, const bool interior_only=true) const
void addScalar (const int dst_id, const int src_id, const TYPE &alpha, const bool interior_only=true) const
void add (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void subtract (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void multiply (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void divide (const int dst_id, const int src1_id, const int src2_id, const bool interior_only=true) const
void reciprocal (const int dst_id, const int src_id, const bool interior_only=true) const
void linearSum (const int dst_id, const TYPE &alpha, const int src1_id, const TYPE &beta, const int src2_id, const bool interior_only=true) const
void axpy (const int dst_id, const TYPE &alpha, const int src1_id, const int src2_id, const bool interior_only=true) const
void axmy (const int dst_id, const TYPE &alpha, const int src1_id, const int src2_id, const bool interior_only=true) const
void abs (const int dst_id, const int src_id, const bool interior_only=true) const
TYPE min (const int data_id, const bool interior_only=true) const
TYPE max (const int data_id, const bool interior_only=true) const
void setRandomValues (const int data_id, const TYPE &width, const TYPE &low, const bool interior_only=true) const
int numberOfEntries (const int data_id, const bool interior_only=true) const
double sumControlVolumes (const int data_id, const int vol_id) const
double L1Norm (const int data_id, const int vol_id=-1, bool local_only=false) const
double L2Norm (const int data_id, const int vol_id=-1, bool local_only=false) const
double weightedL2Norm (const int data_id, const int weight_id, const int vol_id=-1) const
double RMSNorm (const int data_id, const int vol_id=-1) const
double weightedRMSNorm (const int data_id, const int weight_id, const int vol_id=-1) const
double maxNorm (const int data_id, const int vol_id=-1, bool local_only=false) const
TYPE dot (const int data1_id, const int data2_id, const int vol_id=-1, bool local_only=false) const
TYPE integral (const int data_id, const int vol_id) const
int computeConstrProdPos (const int data1_id, const int data2_id, const int vol_id=-1) const
void compareToScalar (const int dst_id, const int src_id, const TYPE &alpha, const int vol_id=-1) const
int testReciprocal (const int dst_id, const int src_id, const int vol_id=-1) const
TYPE maxPointwiseDivide (const int numer_id, const int denom_id, bool local_only=false) const
Compute max of "conditional" quotients of two arrays.
TYPE minPointwiseDivide (const int numer_id, const int denom_id, bool local_only=false) const
Compute min of quotients of two arrays.
Detailed Description
template<class TYPE>
class SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >
Class HierarchyNodeDataOpsReal provides a collection of operations that manipulate real (double and float) node-centered patch data components over multiple levels in an AMR hierarchy. It is derived from the abstract base class HierarchyDataOpsReal which defines the interface to similar operations for node-centered, face-centered, node-centered patch data objects where the data is either double or float. The operations include basic arithmetic, norms and ordering, and assorted miscellaneous operations. On each patch, the operations are performed by the PatchNodeDataOpsReal data member.
The patch hierarchy and set of levels within that hierarcy over which the operations will be performed are set in the constructor. However, note that the constructor accepts default arguments for the coarsest and finest level numbers. If the level numbers are not specified when calling the constructor the levels which exist in the hierarchy will be assumed in all operations. The hierarchy and levels may be changed at any time using the proper member functions.
Note that, when it makes sense, an operation accept a boolean argument which indicates whether the operation should be performed on all of the data or just those data elements corresponding to the patch interiors. If no boolean argument is provided, the default behavior is to treat only the patch interiors. Also, a similar set of operations for complex and integer node-centered data is provided in the classes HierarchyNodeDataOpsComplex and HierarchyNodeDataOpsInteger, respectively.
See also:
math::PatchNodeDataOpsReal
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::HierarchyNodeDataOpsReal (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int coarsest_level = -1, const int finest_level = -1) [inline, explicit]
The constructor for the HierarchyNodeDataOpsReal class sets the default patch hierarchy and coarsest and finest patch levels in that hierarchy over which operations will be performed. The hierarchy and operations may be reset using the member fuctions setPatchHierarchy() and resetLevels() below. If no level number arguments are given here, the levels over which the operations will be performed are those already existing in the hierarchy. If the hierarchy level configuration changes, the operations must be explicitly reset by calling the resetLevels() function.
Precondition:
hierarchy
References SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::resetLevels(), and TBOX_ASSERT.
template<class TYPE > SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::~HierarchyNodeDataOpsReal () [inline, virtual]
Virtual destructor for the HierarchyNodeDataOpsReal class.
Member Function Documentation
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::setPatchHierarchy (const boost::shared_ptr< hier::PatchHierarchy > & hierarchy) [inline, virtual]
Reset patch hierarchy over which operations occur.
Precondition:
hierarchy
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::resetLevels (const int coarsest_level, const int finest_level) [inline, virtual]
Reset range of patch levels over which operations occur.
Precondition:
getPatchHierarchy()
(coarsest_level >= 0) && (finest_level >= coarsest_level) && (finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References SAMRAI::hier::BoxUtilities::makeNonOverlappingBoxContainers(), TBOX_ASSERT, and SAMRAI::pdat::NodeGeometry::toNodeBox().
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::HierarchyNodeDataOpsReal().
template<class TYPE > const boost::shared_ptr< hier::PatchHierarchy > SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::getPatchHierarchy () const [inline, virtual]
Return const pointer to patch hierarchy associated with operations.
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::copyData (const int dst_id, const int src_id, const bool interior_only = true) const [inline, virtual]
Copy source data to destination data.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::swapData (const int data1_id, const int data2_id) const [inline, virtual]
Swap data pointers (i.e., storage) between two data components.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::printData (const int data_id, std::ostream & s, const bool interior_only = true) const [inline, virtual]
Print data over multiple levels to specified output stream.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::setToScalar (const int data_id, const TYPE & alpha, const bool interior_only = true) const [inline, virtual]
Set data component to given scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::scale (const int dst_id, const TYPE & alpha, const int src_id, const bool interior_only = true) const [inline, virtual]
Set destination to source multiplied by given scalar, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::addScalar (const int dst_id, const int src_id, const TYPE & alpha, const bool interior_only = true) const [inline, virtual]
Add scalar to each entry in source data and set destination to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::add (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [inline, virtual]
Set destination to sum of two source components, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::subtract (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [inline, virtual]
Subtract second source component from first source component pointwise and set destination data component to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::multiply (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [inline, virtual]
Set destination component to product of two source components, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::divide (const int dst_id, const int src1_id, const int src2_id, const bool interior_only = true) const [inline, virtual]
Divide first data component by second source component pointwise and set destination data component to result.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::reciprocal (const int dst_id, const int src_id, const bool interior_only = true) const [inline, virtual]
Set each entry of destination component to reciprocal of corresponding source data component entry.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::linearSum (const int dst_id, const TYPE & alpha, const int src1_id, const TYPE & beta, const int src2_id, const bool interior_only = true) const [inline, virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here are scalar values.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::axpy (const int dst_id, const TYPE & alpha, const int src1_id, const int src2_id, const bool interior_only = true) const [inline, virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here is a scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::axmy (const int dst_id, const TYPE & alpha, const int src1_id, const int src2_id, const bool interior_only = true) const [inline, virtual]
Set , where is the destination patch data component and are the first and second source components, respectively. Here is a scalar.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::abs (const int dst_id, const int src_id, const bool interior_only = true) const [inline, virtual]
Set destination data to absolute value of source data, pointwise.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > TYPE SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::min (const int data_id, const bool interior_only = true) const [inline, virtual]
Return minimum data value over all patches in the collection of levels.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_MIN, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::minPointwiseDivide().
template<class TYPE > TYPE SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::max (const int data_id, const bool interior_only = true) const [inline, virtual]
Return maximum data value over all patches in the collection of levels.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_MAX, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::maxPointwiseDivide().
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::setRandomValues (const int data_id, const TYPE & width, const TYPE & low, const bool interior_only = true) const [inline, virtual]
Set data entries to random values. See the operations in the array data operation classes for each data type for details on the generation of the random values.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > int SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::numberOfEntries (const int data_id, const bool interior_only = true) const [inline, virtual]
Return the total number of data values for the component on the set of hierarchy levels. If the boolean argument is true, the number of elements will be summed over patch interiors in a unique way which avoids multiple counting of redundant values (recall the definition of node points on a patch interior). If the boolean argument is false, all elements will be counted (including ghost values) over all patches.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_INT, MPI_SUM, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::RMSNorm(), and SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::weightedRMSNorm().
template<class TYPE > double SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::sumControlVolumes (const int data_id, const int vol_id) const [inline, virtual]
Return sum of the control volumes associated with the data component. Note that if the control volumes are set properly, this is equivalent to integrating a data component containing all ones over the collection of hierarchy levels.
Precondition:
vol_id >= 0
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_DOUBLE, MPI_SUM, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::RMSNorm(), and SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::weightedRMSNorm().
template<class TYPE > double SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::L1Norm (const int data_id, const int vol_id = -1, bool local_only = false) const [inline, virtual]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is not defined (vol_id < 0), the return value is . If local_only is true, the global reduction is not performed (thus each process will get only local results).
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_DOUBLE, MPI_SUM, and TBOX_ASSERT.
template<class TYPE > double SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::L2Norm (const int data_id, const int vol_id = -1, bool local_only = false) const [inline, virtual]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is not defined (vol_id < 0), the return value is . If local_only is true, the global reduction is not performed (thus each process will get only local results).
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::dot().
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::RMSNorm().
template<class TYPE > double SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::weightedL2Norm (const int data_id, const int weight_id, const int vol_id = -1) const [inline, virtual]
Return discrete weighted -norm of the data using the control volume to weight the contribution of the data and weight entries to the sum. That is, the return value is the sum . If the control volume is not defined (vol_id < 0), the return value is .
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_DOUBLE, MPI_SUM, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::weightedRMSNorm().
template<class TYPE > double SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::RMSNorm (const int data_id, const int vol_id = -1) const [inline, virtual]
Return discrete root mean squared norm of the data. If the control volume is defined, the return value is the -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the -norm divided by the square root of the number of data entries.
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::L2Norm(), SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::numberOfEntries(), and SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::sumControlVolumes().
template<class TYPE > double SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::weightedRMSNorm (const int data_id, const int weight_id, const int vol_id = -1) const [inline, virtual]
Return discrete weighted root mean squared norm of the data. If the control volume is define, the return value is the weighted -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the weighted -norm divided by the square root of the number of data entries.
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::sumControlVolumes(), and SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::weightedL2Norm().
template<class TYPE > double SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::maxNorm (const int data_id, const int vol_id = -1, bool local_only = false) const [inline, virtual]
Return the -norm of the data using the control volume to weight the contribution of each data entry to the maximum. That is, the return value is , where the max is over the data elements where . If the control volume is undefined (vol_id < 0), it is ignored during the computation of the maximum. If local_only is true, the global reduction is not performed (thus each process will get only local results).
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_DOUBLE, MPI_MAX, and TBOX_ASSERT.
template<class TYPE > TYPE SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::dot (const int data1_id, const int data2_id, const int vol_id = -1, bool local_only = false) const [inline, virtual]
Return the dot product of the two data arrays using the control volume to weight the contribution of each product to the sum. That is, the return value is the sum . If the control volume is undefined (vol_id < 0), it is ignored during the summation. If local_only is true, the global reduction is not performed (thus each process will get only local results).
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_SUM, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::L2Norm().
template<class TYPE > TYPE SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::integral (const int data_id, const int vol_id) const [inline]
Return the integral of the function represented by the data array. The return value is the sum .
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
References BOOST_CAST, MPI_SUM, and TBOX_ASSERT.
template<class TYPE > int SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::computeConstrProdPos (const int data1_id, const int data2_id, const int vol_id = -1) const [inline, virtual]
Return 1 if and , for any in the set of patch data indices, where . Otherwise, return 0. If the control volume is undefined (vol_id < 0), all values on the patch interiors are considered.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_INT, MPI_MIN, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::compareToScalar (const int dst_id, const int src_id, const TYPE & alpha, const int vol_id = -1) const [inline, virtual]
Wherever in the set of patch data indices, set if , and otherwise. If the control volume is undefined (vol_id < 0), all values on the patch interiors are considered.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, and TBOX_ASSERT.
template<class TYPE > int SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::testReciprocal (const int dst_id, const int src_id, const int vol_id = -1) const [inline, virtual]
Wherever in the set of patch data indices, set if , and otherwise. If anywhere, 0 is the return value. Otherwise 1 is returned. If the control volume is undefined (vol_id < 0), all values on the patch interiors are considered.
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, MPI_INT, MPI_MIN, and TBOX_ASSERT.
template<class TYPE > TYPE SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::maxPointwiseDivide (const int numer_id, const int denom_id, bool local_only = false) const [inline, virtual]
Compute max of "conditional" quotients of two arrays.
Return the maximum of pointwise "conditional" quotients of the numerator and denominator.
The "conditional" quotient is defined as |numerator/denominator| where the denominator is nonzero. Otherwise, it is defined as |numerator|.
Note: This method is currently intended to support the PETSc-2.1.6 vector wrapper only. Please do not use it!
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::max(), MPI_MAX, and TBOX_ASSERT.
template<class TYPE > TYPE SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::minPointwiseDivide (const int numer_id, const int denom_id, bool local_only = false) const [inline, virtual]
Compute min of quotients of two arrays.
Return the minimum of pointwise quotients of the numerator and denominator.
The quotient is defined as (numerator/denominator) where the denominator is nonzero. When the denominator is zero, the entry is skipped. If the denominator is always zero, the value of tbox::IEEE::getFLT_MAX() is returned (see SAMRAI::tbox::IEEE).
Note: This method is currently intended to support the SUNDIALS vector wrapper only. Please do not use it!
Precondition:
getPatchHierarchy()
(d_coarsest_level >= 0) && (d_finest_level >= d_coarsest_level) && (d_finest_level <= getPatchHierarchy()->getFinestLevelNumber())
Implements SAMRAI::math::HierarchyDataOpsReal< TYPE >.
References BOOST_CAST, SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::min(), MPI_MIN, and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/math/HierarchyNodeDataOpsReal.h
source/SAMRAI/math/HierarchyNodeDataOpsReal.C