SAMRAI: SAMRAI::hier::ConnectorStatistics Class Reference
SAMRAI::hier::ConnectorStatistics Class Reference
A utility for writing out various statistics of Connectors.
#include <source/SAMRAI/hier/ConnectorStatistics.h>
Public Member Functions
ConnectorStatistics (const Connector &connector)
Constructor.
void printNeighborStats (std::ostream &os, const std::string &border) const
Print out local and globally reduced statistics on the Boxes.
Detailed Description
A utility for writing out various statistics of Connectors.
Constructor & Destructor Documentation
SAMRAI::hier::ConnectorStatistics::ConnectorStatistics (const Connector & connector) [explicit]
Constructor.
Compute and store statistics for the given Connector. The statistics reflects the current Connector state and can be printed out afterwards. All processes in the Connector's SAMRAI_MPI must call this constructor because it requires collective communication.
Parameters:
[in] connector
Precondition:
connector.isFinalized()
References SAMRAI::hier::Connector::isFinalized(), and TBOX_ERROR.
Member Function Documentation
void SAMRAI::hier::ConnectorStatistics::printNeighborStats (std::ostream & os, const std::string & border) const
Print out local and globally reduced statistics on the Boxes.
Parameters:
[in,out] os The output stream
[in] border A string to print at the start of every line in the output.
References SAMRAI::tbox::SAMRAI_MPI::getSize().
Referenced by SAMRAI::hier::operator<<().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/ConnectorStatistics.h
source/SAMRAI/hier/ConnectorStatistics.C