SAMRAI: SAMRAI::hier::BoundaryLookupTable Class Reference
SAMRAI::hier::BoundaryLookupTable Class Reference
Singleton class to organize patch boundary information.
#include <source/SAMRAI/hier/BoundaryLookupTable.h>
Public Member Functions
const std::vector
< tbox::Dimension::dir_t > & getDirections (int loc, tbox::Dimension::dir_t codim) const
Get array of active directions for specific boundary location and codimension case.
const std::vector< int > & getMaxLocationIndices () const
Get array of maximum number of locations for each codimension boundary case.
int getMaxLocationIndex (int i) const
bool isLower (int loc, int codim, int dir_index) const
Determines if given boundary information indicates a a lower boundary region.
bool isUpper (int loc, int codim, int dir_index) const
Determines if given boundary information indicates a an upper boundary region.
const std::vector< IntVector > & getBoundaryDirections (int codim) const
Get array of boundary direction IntVectors.
const tbox::Dimension & getDim () const
Static Public Member Functions
static BoundaryLookupTable * getLookupTable (const tbox::Dimension &dim)
Return pointer to singleton instance of the boundary lookup table.
Protected Member Functions
BoundaryLookupTable (const tbox::Dimension &dim)
protected constructor
~BoundaryLookupTable ()
protected destructor
Detailed Description
Singleton class to organize patch boundary information.
Class BoundaryLookupTable is a singleton class that maintains a table that organizes all of the possible boundary region cases for a patch. It is used primarily by the grid geometry during the construction of physical boundary boxes for patches and by the PatchGeometry class to determine box regions to be filled during a physical boundary fill.
This class is useful for any situation where enumerating the cases for boundary regions around a box is needed. The main advantage of using this class is that such calculations can be programmed in a dimension-independent way.
See also:
BoundaryBox
BaseGridGeometry
PatchGeometry
Constructor & Destructor Documentation
SAMRAI::hier::BoundaryLookupTable::BoundaryLookupTable (const tbox::Dimension & dim) [explicit, protected]
protected constructor
The constructor for BoundaryLookupTable is protected. Consistent with the definition of a Singleton class, only the lookup table has access to the constructor for the class.
The constructor initializes the state of lookup table contents.
Parameters:
dim Dimension
References SAMRAI::tbox::Dimension::getValue().
Referenced by getLookupTable().
SAMRAI::hier::BoundaryLookupTable::~BoundaryLookupTable () [protected]
protected destructor
The destructor for BoundaryLookupTable is protected. See the comments for the constructor.
The destructor deallocates lookup table contents.
Member Function Documentation
static BoundaryLookupTable* SAMRAI::hier::BoundaryLookupTable::getLookupTable (const tbox::Dimension & dim) [inline, static]
Return pointer to singleton instance of the boundary lookup table.
Following the Singleton design pattern, users of this class do not explicitly allocate or deallocate the Singleton instance.
Parameters:
dim Dimension of the object.
Returns:
Pointer to lookup table instance.
References BoundaryLookupTable(), and SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::hier::BoundaryBox::BoundaryBox(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::PatchGeometry::getBoundaryFillBox(), and SAMRAI::hier::BoundaryBox::getBoundaryOrientation().
const std::vector<tbox::Dimension::dir_t>& SAMRAI::hier::BoundaryLookupTable::getDirections (int loc, tbox::Dimension::dir_t codim) const [inline]
Get array of active directions for specific boundary location and codimension case.
The active directions are those coordinate direction in which the boundary region would have to be shifted in order to be contained in the corresponding patch box (whose boundary we are interested in).
Parameters:
loc integer location index of boundary region
codim integer codimension of boundary region
Returns:
const reference to integer vector of length codim containing the active directions for this boundary case.
Precondition:
(codim > 0) && (codim <= getDim().getValue())
(loc >= 0) && (loc < getMaxLocationIndex(codim - 1))
References getDim(), getMaxLocationIndex(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), and SAMRAI::hier::PatchGeometry::getBoundaryFillBox().
const std::vector<int>& SAMRAI::hier::BoundaryLookupTable::getMaxLocationIndices () const [inline]
Get array of maximum number of locations for each codimension boundary case.
For example, a 2D patch has 4 possible locations for codimension 1 (edges) and 4 possible locations for codimension 2 (nodes). A 3D patch has 6 possible locations for codimension 1 (faces), 12 for codimension 2 (edges), and 8 for codimension 3 (nodes).
Returns:
integer vector of length dim, each entry of which indicates the maximum number of boundary locations for each codimension
Referenced by SAMRAI::hier::BoundaryBox::BoundaryBox(), SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), and SAMRAI::hier::PatchGeometry::getBoundaryFillBox().
int SAMRAI::hier::BoundaryLookupTable::getMaxLocationIndex (int i) const [inline]
Referenced by getDirections(), isLower(), and isUpper().
bool SAMRAI::hier::BoundaryLookupTable::isLower (int loc, int codim, int dir_index) const [inline]
Determines if given boundary information indicates a a lower boundary region.
A boundary region is a "lower" boundary region if the associated patch box contains higher values along the axis in the coordinate direction than the boundary region.
Parameters:
loc integer location index of boundary region
codim integer codimension of boundary region
dir_index integer spatial direction identifier, an index into the array returned by getDirections().
Returns:
bool true if the boundary type of codimension codim indexed by loc is a lower boundary in the specified direction; return false if the boundary is an upper boundary.
Precondition:
(codim > 0) && (codim <= getDim().getValue()))
(loc >= 0) && (loc < getMaxLocationIndex(codim - 1))
(dir_index >= 0) && (dir_index < codim)
References getDim(), getMaxLocationIndex(), isUpper(), and TBOX_ASSERT.
bool SAMRAI::hier::BoundaryLookupTable::isUpper (int loc, int codim, int dir_index) const [inline]
Determines if given boundary information indicates a an upper boundary region.
A boundary region is an "upper" boundary region if the associated patch box contains lower values along the axis in the coordinate direction than the boundary region.
Parameters:
loc integer location index of boundary region
codim integer codimension of boundary region
dir_index integer spatial direction identifier, an index into the array returned by getDirections().
Returns:
bool true if the boundary type of codimension codim indexed by loc is an upper boundary in the specified direction; return false if the boundary is a lower boundary.
Precondition:
(codim > 0) && (codim <= getDim().getValue())
(loc >= 0) && (loc < getMaxLocationIndex(codim - 1))
(dir_index >= 0) && (dir_index < codim)
References getDim(), getMaxLocationIndex(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes(), SAMRAI::hier::PatchGeometry::getBoundaryFillBox(), and isLower().
const std::vector<IntVector>& SAMRAI::hier::BoundaryLookupTable::getBoundaryDirections (int codim) const [inline]
Get array of boundary direction IntVectors.
For any codimension, there is a particular number of valid boundary locations. This function returns an array of IntVectors that provide information about where each boundary location lies in relation to a patch. The array's length is the number of valid locations for the given codimension, and the array is indexed by the location id's that are set up by this BoundaryLookupTable class.
For a particular location, each element of the IntVector tells whether the location is on the lower or upper side, or neither, of the patch in a specific coordinate direction. -1 indicates lower, 0 indicates neither, and 1 indicates upper.
Parameters:
codim codimension
Returns:
Vector of IntVectors, one element for each valid location
Precondition:
(codim > 0) && (codim <= getDim().getValue())
References getDim(), and TBOX_ASSERT.
const tbox::Dimension& SAMRAI::hier::BoundaryLookupTable::getDim () const [inline]
Referenced by getBoundaryDirections(), getDirections(), isLower(), and isUpper().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoundaryLookupTable.h
source/SAMRAI/hier/BoundaryLookupTable.C