SAMRAI: SAMRAI::tbox::Timer Class Reference
SAMRAI::tbox::Timer Class Reference
#include <source/SAMRAI/tbox/Timer.h>
Public Member Functions
~Timer ()
const std::string & getName () const
void start ()
void stop ()
void barrierAndStart ()
void barrierAndStop ()
void startExclusive ()
void stopExclusive ()
void reset ()
double getTotalSystemTime () const
double getTotalUserTime () const
double getTotalWallclockTime () const
double getMaxWallclockTime () const
double getExclusiveSystemTime () const
double getExclusiveUserTime () const
double getExclusiveWallclockTime () const
bool isActive () const
bool isRunning () const
int getNumberAccesses () const
double computeLoadBalanceEfficiency ()
void computeMaxWallclock ()
void putToRestart (const boost::shared_ptr< Database > &restart_db) const
void getFromRestart (const boost::shared_ptr< Database > &restart_db)
Protected Member Functions
Timer (const std::string &name)
void setActive (bool is_active)
void addConcurrentTimer (const Timer &timer)
bool isConcurrentTimer (const Timer &timer) const
Friends
class TimerManager
Detailed Description
Class Timer holds the exclusive and total start, stop, and elapsed time for timers instrumented in SAMRAI. Total time is simply the time between calls to the start() and stop() functions. Exclusive time is applicable if there are nested timers called.
System and user start and end times are stored as variables of type clock_t, defined in the sys/times.h include file. A detailed explanation of the structures used to store system and user times is given in the header for the Clock class. This routine simply accesses the functions specified in that class.
Wallclock time may be computed by the systems internal clocks which require an object of type clock_t, or by SAMRAI_MPI::Wtime() if the code is linked to MPI libraries.
In addition to running or not running, a timer may be active or inactive. An inactive timer is one that is created within a program but will never be turned on or off because it is either not specified as active in an input file or it was not explicitly made active by the user. When a timer is created, it is active by default.
Note that the constructor is protected so that timer objects can only be created by the TimerManager class.
See also:
tbox::TimerManager
Constructor & Destructor Documentation
SAMRAI::tbox::Timer::~Timer ()
Empty destructor for Timer class.
SAMRAI::tbox::Timer::Timer (const std::string & name) [explicit, protected]
The constructor for the Timer class sets timer name string and integer identifiers, and initializes the timer state.
References SAMRAI::tbox::Clock::initialize(), and reset().
Member Function Documentation
const std::string& SAMRAI::tbox::Timer::getName (void) const [inline]
Return string name for timer.
void SAMRAI::tbox::Timer::start ()
Start the timer if active.
Precondition:
!isActive() || !isRunning()
References SAMRAI::tbox::TimerManager::getManager(), SAMRAI::tbox::TimerManager::startTime(), TBOX_ERROR, and SAMRAI::tbox::Clock::timestamp().
Referenced by barrierAndStart().
void SAMRAI::tbox::Timer::stop ()
Stop the timer if active.
Precondition:
!isActive() || isRunning()
References SAMRAI::tbox::TimerManager::getManager(), SAMRAI::tbox::TimerManager::stopTime(), TBOX_ERROR, and SAMRAI::tbox::Clock::timestamp().
Referenced by barrierAndStop().
void SAMRAI::tbox::Timer::barrierAndStart ()
If active, SAMRAI_MPI::getSAMRAIWorld().Barrier() then start the timer.
References SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and start().
void SAMRAI::tbox::Timer::barrierAndStop ()
If active, SAMRAI_MPI::getSAMRAIWorld().Barrier() then stop the timer.
References SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and stop().
void SAMRAI::tbox::Timer::startExclusive ()
Start exclusive time.
References SAMRAI::tbox::Clock::timestamp().
Referenced by SAMRAI::tbox::TimerManager::startTime().
void SAMRAI::tbox::Timer::stopExclusive ()
Stop exclusive time.
References SAMRAI::tbox::Clock::timestamp().
Referenced by SAMRAI::tbox::TimerManager::stopTime().
void SAMRAI::tbox::Timer::reset ()
Reset the state of the timing information.
Referenced by Timer().
double SAMRAI::tbox::Timer::getTotalSystemTime () const [inline]
Return total system time (between starts and stops)
References SAMRAI::tbox::Clock::getClockCycle().
double SAMRAI::tbox::Timer::getTotalUserTime () const [inline]
Return total user time
References SAMRAI::tbox::Clock::getClockCycle().
double SAMRAI::tbox::Timer::getTotalWallclockTime () const [inline]
Return total wallclock time
double SAMRAI::tbox::Timer::getMaxWallclockTime () const [inline]
Return max wallclock time
double SAMRAI::tbox::Timer::getExclusiveSystemTime () const [inline]
Return exclusive system time.
References SAMRAI::tbox::Clock::getClockCycle().
double SAMRAI::tbox::Timer::getExclusiveUserTime () const [inline]
Return exclusive user time.
References SAMRAI::tbox::Clock::getClockCycle().
double SAMRAI::tbox::Timer::getExclusiveWallclockTime () const [inline]
Return exclusive wallclock time.
bool SAMRAI::tbox::Timer::isActive () const [inline]
Return true if the timer is active; false otherwise.
Referenced by SAMRAI::tbox::TimerManager::startTime().
bool SAMRAI::tbox::Timer::isRunning () const [inline]
Return true if timer is running; false otherwise.
int SAMRAI::tbox::Timer::getNumberAccesses () const [inline]
Return number of accesses to start()-stop() functions for the timer.
double SAMRAI::tbox::Timer::computeLoadBalanceEfficiency ()
Compute load balance efficiency based on wallclock (non-exclusive) time.
References SAMRAI::tbox::SAMRAI_MPI::Allreduce(), computeMaxWallclock(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), MPI_DOUBLE, and MPI_SUM.
void SAMRAI::tbox::Timer::computeMaxWallclock ()
Compute max wallclock time based on total (non-exclusive) time.
References SAMRAI::tbox::SAMRAI_MPI::Allreduce(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), MPI_DOUBLE, and MPI_MAX.
Referenced by computeLoadBalanceEfficiency().
void SAMRAI::tbox::Timer::putToRestart (const boost::shared_ptr< Database > & restart_db) const
Write timer data members to restart database.
Precondition:
restart_db
References TBOX_ASSERT.
void SAMRAI::tbox::Timer::getFromRestart (const boost::shared_ptr< Database > & restart_db)
Read restarted times from restart database.
Precondition:
restart_db
References TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::tbox::Timer::setActive (bool is_active) [inline, protected]
void SAMRAI::tbox::Timer::addConcurrentTimer (const Timer & timer) [inline, protected]
Add Timer that running concurrently with this one.
References isConcurrentTimer().
bool SAMRAI::tbox::Timer::isConcurrentTimer (const Timer & timer) const [protected]
Return if the timer is running concurrently with this one.
Referenced by addConcurrentTimer().
Friends And Related Function Documentation
friend class TimerManager [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/Timer.h
source/SAMRAI/tbox/Timer.C