SAMRAI: SAMRAI::tbox::AsyncCommStage Class Reference
SAMRAI::tbox::AsyncCommStage Class Reference
Stage multiple non-blocking MPI communications so that codes waiting for them to complete can advance as their respective MPI communication operations are completed.
#include <source/SAMRAI/tbox/AsyncCommStage.h>
Classes
struct Handler
Optional object that can be attached to each Member, for use in determining what to do after the Member completes its communication.
struct Member
Something on a stage, using MPI requests and statuses provided by the stage.
Public Member Functions
AsyncCommStage ()
Construct a stage that may begin allocating and managing Members.
~AsyncCommStage ()
Deallocate Members remaining in the stage and all internal data used to manage Members.
bool advanceAny ()
Advance to completion one Member (any Member) that is currently waiting for communication to complete.
bool advanceSome ()
Advance to completion one or more Members (any Members) that are currently waiting for communication to complete.
bool advanceAll ()
Advance all pending communications to operations.
size_t numberOfCompletedMembers () const
bool hasCompletedMembers () const
const Member * firstCompletedMember () const
Returns the first completed Member.
const Member * getMember (size_t i) const
Returns the ith managed Member.
Member * popCompletionQueue ()
void clearCompletionQueue ()
Clear the internal completion queue.
void setCommunicationWaitTimer (const boost::shared_ptr< Timer > &communication_timer)
Set optional timer for timing communication wait.
size_t numberOfMembers () const
Get the number of Members on this stage.
size_t numManagedMembers () const
Returns the number of staged and destaged Members.
bool hasPendingRequests () const
Return whether the stage has any pending communication requests.
size_t numberOfPendingMembers () const
Return the number of Members that have pending communication.
size_t numberOfPendingRequests () const
Return the number of pending SAMRAI_MPI::Request objects on the stage.
Friends
struct Member
Member is a friend so it can access private look-up and stage/destage methods. This avoids making those private methods public. This friendship is safe because Member is an integral part of the stage code.
Detailed Description
Stage multiple non-blocking MPI communications so that codes waiting for them to complete can advance as their respective MPI communication operations are completed.
An AsyncCommStage object manages multiple non-blocking MPI communications carried out by AsyncCommStage::Member objects. These classes factor out multiple non-blocking communication codes.
By being staged together, Members can overlap their communication waits conveniently. The stage determines which Member's communication requests are completed. User code then follows up the communication with whatever was waiting for that operation to complete.
The Member class defines the interfaces required to work with an AsyncCommStage. Communication operations can be a simple non-blocking MPI communication or a complex sequence of MPI communications and local computations. See Member subclasses for examples.
Use this class when you:
Have multiple communications, each performed by a different and independent AsyncCommStage::Member object.
Want the multiple communications to proceed independently and asynchronously.
Each AsyncCommStage is a registry of Member objects on the stage. To overlap the Members' communications, the stage manages space for their SAMRAI_MPI::Request's and SAMRAI_MPI::Status'es. The requests are allocated such that a single MPI_Waitany or MPI_Waitsome represents all Members registered with the stage. Thus the communications performed by the Member objects can complete in the order allowed by the arrival of MPI messages. The exact order is NOT deterministic!
To advance the communication operation of any of the allocated Member objects, use advanceAny() or advanceSome(). In general, advanceSome() has better performance than advanceAny() because it avoids the "starvation" problem. See the MPI documentation for a discussion of starvation.
This class supports communication and uses MPI for message passing. If MPI is disabled, the job of this class disappears and the class is effectively empty, except for managing the registration of Member objects. The public interfaces still remain so the class can compile, but the implementations are trivial.
Constructor & Destructor Documentation
SAMRAI::tbox::AsyncCommStage::AsyncCommStage ()
Construct a stage that may begin allocating and managing Members.
SAMRAI::tbox::AsyncCommStage::~AsyncCommStage ()
Deallocate Members remaining in the stage and all internal data used to manage Members.
References hasPendingRequests(), and TBOX_ERROR.
Member Function Documentation
bool SAMRAI::tbox::AsyncCommStage::advanceAny ()
Advance to completion one Member (any Member) that is currently waiting for communication to complete.
The completed Member is accessible through popCompletionQueue().
This method uses MPI_Waitany, which may be prone to starvation. When a process is potentially receiving multiple messages from another processor, it is better to use advanceSome(), which uses MPI_Waitsome, which avoids starvation.
Returns:
True if there are still completed Members in the completion queue.
References hasPendingRequests(), MPI_ERR_IN_STATUS, SAMRAI::tbox::SAMRAI_MPI::Status::MPI_ERROR, MPI_REQUEST_NULL, MPI_SUCCESS, MPI_UNDEFINED, TBOX_ASSERT, TBOX_ERROR, TBOX_WARNING, SAMRAI::tbox::SAMRAI_MPI::usingMPI(), and SAMRAI::tbox::SAMRAI_MPI::Waitany().
bool SAMRAI::tbox::AsyncCommStage::advanceSome ()
Advance to completion one or more Members (any Members) that are currently waiting for communication to complete.
The completed Members are accessible through popCompletionQueue().
Returns:
True if there are still completed Members in the completion queue.
References SAMRAI::tbox::AsyncCommStage::Member::hasPendingRequests(), hasPendingRequests(), SAMRAI::tbox::AsyncCommStage::Member::isDone(), MPI_ERR_IN_STATUS, MPI_REQUEST_NULL, MPI_SUCCESS, SAMRAI::tbox::plog, SAMRAI::tbox::AsyncCommStage::Member::proceedToNextWait(), TBOX_ASSERT, TBOX_ERROR, TBOX_WARNING, SAMRAI::tbox::SAMRAI_MPI::usingMPI(), and SAMRAI::tbox::SAMRAI_MPI::Waitsome().
Referenced by advanceAll(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::receiveAndUnpack().
bool SAMRAI::tbox::AsyncCommStage::advanceAll ()
Advance all pending communications to operations.
The completed Members are accessible through popCompletionQueue().
Returns:
True if there are still completed Members in the completion queue.
References advanceSome(), and hasPendingRequests().
size_t SAMRAI::tbox::AsyncCommStage::numberOfCompletedMembers () const [inline]
bool SAMRAI::tbox::AsyncCommStage::hasCompletedMembers () const [inline]
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), popCompletionQueue(), and SAMRAI::hier::BaseConnectorAlgorithm::receiveAndUnpack().
const Member* SAMRAI::tbox::AsyncCommStage::firstCompletedMember () const [inline]
Returns the first completed Member.
Referenced by popCompletionQueue().
const Member* SAMRAI::tbox::AsyncCommStage::getMember (size_t i) const [inline]
Returns the ith managed Member.
Parameters:
i
Precondition:
i < numManagedMembers()
AsyncCommStage::Member * SAMRAI::tbox::AsyncCommStage::popCompletionQueue ()
References firstCompletedMember(), hasCompletedMembers(), and TBOX_ERROR.
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::receiveAndUnpack().
void SAMRAI::tbox::AsyncCommStage::clearCompletionQueue () [inline]
Clear the internal completion queue.
See also:
popCompletionQueue(), Member::pushToCompletionQueue().
void SAMRAI::tbox::AsyncCommStage::setCommunicationWaitTimer (const boost::shared_ptr< Timer > & communication_timer) [inline]
Set optional timer for timing communication wait.
The timer is used only for the MPI communication wait. Timing does not include time the stage Members use to process the messages (the time spent in Member::proceedToNextWait()).
If not set, or NULL is given, none will be used.
Referenced by SAMRAI::mesh::CascadePartitioner::CascadePartitioner(), SAMRAI::tbox::Schedule::setTimerPrefix(), SAMRAI::mesh::BergerRigoutsos::setTimerPrefix(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
size_t SAMRAI::tbox::AsyncCommStage::numberOfMembers () const [inline]
Get the number of Members on this stage.
size_t SAMRAI::tbox::AsyncCommStage::numManagedMembers () const [inline]
Returns the number of staged and destaged Members.
bool SAMRAI::tbox::AsyncCommStage::hasPendingRequests () const
Return whether the stage has any pending communication requests.
References MPI_REQUEST_NULL.
Referenced by advanceAll(), advanceAny(), advanceSome(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), numberOfPendingMembers(), and ~AsyncCommStage().
size_t SAMRAI::tbox::AsyncCommStage::numberOfPendingMembers () const
Return the number of Members that have pending communication.
References hasPendingRequests().
size_t SAMRAI::tbox::AsyncCommStage::numberOfPendingRequests () const
Return the number of pending SAMRAI_MPI::Request objects on the stage.
References MPI_REQUEST_NULL.
Friends And Related Function Documentation
friend struct Member [friend]
Member is a friend so it can access private look-up and stage/destage methods. This avoids making those private methods public. This friendship is safe because Member is an integral part of the stage code.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/AsyncCommStage.h
source/SAMRAI/tbox/AsyncCommStage.C