SAMRAI: SAMRAI::hier::PatchDataRestartManager Class Reference
SAMRAI::hier::PatchDataRestartManager Class Reference
#include <source/SAMRAI/hier/PatchDataRestartManager.h>
Public Member Functions
bool isPatchDataRegisteredForRestart (int index) const
Check whether given patch data index is registered with the manager for restart.
void registerPatchDataForRestart (int index)
void unregisterPatchDataForRestart (int index)
bool registeredPatchDataMatches (const ComponentSelector &selected)
Static Public Member Functions
static PatchDataRestartManager * getManager ()
Detailed Description
Class PatchDataRestartManager handles registration of PatchData for restart.
Member Function Documentation
PatchDataRestartManager * SAMRAI::hier::PatchDataRestartManager::getManager () [static]
Return a pointer to the single instance of the PatchDataRestartManager. All access to the PatchDataRestartManager object is through getManager().
Note that when the manager is accessed for the first time, the Singleton instance is registered with the StartupShutdownManager class which destroys such objects at program completion. Thus, users of this class do not explicitly allocate or deallocate the Singleton instance.
Referenced by SAMRAI::hier::Patch::getFromRestart(), SAMRAI::hier::Patch::putToRestart(), and SAMRAI::algs::MethodOfLinesIntegrator::registerVariable().
bool SAMRAI::hier::PatchDataRestartManager::isPatchDataRegisteredForRestart (int index) const [inline]
Check whether given patch data index is registered with the manager for restart.
Parameters:
[in] index Integer patch data index to check.
Returns:
Boolean true if the patch data with the given index is registered for restart; otherwise false.
References SAMRAI::hier::ComponentSelector::isSet().
Referenced by SAMRAI::hier::Patch::getFromRestart(), and SAMRAI::hier::Patch::putToRestart().
void SAMRAI::hier::PatchDataRestartManager::registerPatchDataForRestart (int index) [inline]
Registers a patch data index for restart.
Parameters:
[in] index Integer patch data index to check.
References SAMRAI::hier::ComponentSelector::setFlag().
void SAMRAI::hier::PatchDataRestartManager::unregisterPatchDataForRestart (int index) [inline]
Unregisters a patch data index for restart.
Parameters:
[in] index Integer patch data index to check.
References SAMRAI::hier::ComponentSelector::clrFlag().
bool SAMRAI::hier::PatchDataRestartManager::registeredPatchDataMatches (const ComponentSelector & selected) [inline]
Returns true if the patch data components selected by "selected" are identical to the components registered in the manager and vice-versa.
Parameters:
[in] selected The patch data components that have been selected.
Referenced by SAMRAI::hier::Patch::getFromRestart().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PatchDataRestartManager.h
source/SAMRAI/hier/PatchDataRestartManager.C