SAMRAI: SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor Class Reference
SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor Class Reference
Implementation of the strategy class hier::PatchHierarchy::ConnectorWidthRequestorStrategy to tell the hier::PatchHierarchy how wide GriddingAlgorithm needs Connectors between hierarchy levels to be.
#include <source/SAMRAI/mesh/GriddingAlgorithmConnectorWidthRequestor.h>
Public Member Functions
GriddingAlgorithmConnectorWidthRequestor ()
Constructor.
void computeRequiredConnectorWidths (std::vector< hier::IntVector > &self_connector_widths, std::vector< hier::IntVector > &fine_connector_widths, const hier::PatchHierarchy &patch_hierarchy) const
Compute Connector widths that this class requires in order to work properly on a given hierarchy.
void setTagToClusterWidth (std::vector< hier::IntVector > &tag_to_cluster_width)
Plan to specify enough Connector width to support the given width between tag and cluster levels.
Detailed Description
Implementation of the strategy class hier::PatchHierarchy::ConnectorWidthRequestorStrategy to tell the hier::PatchHierarchy how wide GriddingAlgorithm needs Connectors between hierarchy levels to be.
Constructor & Destructor Documentation
SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::GriddingAlgorithmConnectorWidthRequestor ()
Constructor.
Member Function Documentation
void SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths (std::vector< hier::IntVector > & self_connector_widths, std::vector< hier::IntVector > & fine_connector_widths, const hier::PatchHierarchy & patch_hierarchy) const
Compute Connector widths that this class requires in order to work properly on a given hierarchy.
Implements the pure virtual method hier::PatchHierarchy::ConnectorWidthRequestorStrategy::computeRequiredConnectorWidths()
Parameters:
[out] self_connector_widths Array of widths for Connectors from a level to itself.
[out] fine_connector_widths Array of widths for Connectors from a level to the next finer level.
[in] patch_hierarchy
References SAMRAI::hier::PatchHierarchy::getDim(), SAMRAI::hier::PatchHierarchy::getGridGeometry(), SAMRAI::hier::PatchHierarchy::getMaxNumberOfLevels(), SAMRAI::hier::PatchHierarchy::getPatchDescriptor(), SAMRAI::hier::PatchHierarchy::getProperNestingBuffer(), SAMRAI::hier::PatchHierarchy::getRatioToCoarserLevel(), and TBOX_ASSERT.
void SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::setTagToClusterWidth (std::vector< hier::IntVector > & tag_to_cluster_width)
Plan to specify enough Connector width to support the given width between tag and cluster levels.
This is only used by the GriddingAlgorithm that owns this object.
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/GriddingAlgorithmConnectorWidthRequestor.h
source/SAMRAI/mesh/GriddingAlgorithmConnectorWidthRequestor.C