SAMRAI: SAMRAI::tbox::DatabaseBox Class Reference
SAMRAI::tbox::DatabaseBox Class Reference
#include <source/SAMRAI/tbox/DatabaseBox.h>
Public Member Functions
DatabaseBox ()
DatabaseBox (const Dimension &dim, const int *lower, const int *upper)
DatabaseBox (const DatabaseBox &box)
DatabaseBox & operator= (const DatabaseBox &box)
~DatabaseBox ()
bool empty () const
const int & getDimVal () const
void setDim (const Dimension &dim)
int & lower (const int i)
int & upper (const int i)
int lower (const int i) const
int upper (const int i) const
int operator== (const DatabaseBox &box) const
Public Attributes
DatabaseBox_POD d_data
All data members in a POD type.
Detailed Description
Class DatabaseBox represents a box of up to MAX_DIM_VAL dimensions in the AMR index space. It is defined by lower and upper bounds given by integer arrays.
This box is an auxilliary data structure used by the database routines to manipulate boxes. This box type removes cyclic dependencies among the database routines (which need a box) and the box (which needs the database routines). The box classes in the hierarchy package convert this box structure into the standard SAMRAI box class used by the AMR algorithms.
Constructor & Destructor Documentation
SAMRAI::tbox::DatabaseBox::DatabaseBox ()
The default constructor creates a zero dimension empty box.
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_dimension, SAMRAI::tbox::DatabaseBox_POD::d_hi, and SAMRAI::tbox::DatabaseBox_POD::d_lo.
SAMRAI::tbox::DatabaseBox::DatabaseBox (const Dimension & dim, const int * lower, const int * upper)
Create a box of the specified dimension describing the index space between lower and upper.
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_dimension, SAMRAI::tbox::DatabaseBox_POD::d_hi, SAMRAI::tbox::DatabaseBox_POD::d_lo, and SAMRAI::tbox::Dimension::getValue().
SAMRAI::tbox::DatabaseBox::DatabaseBox (const DatabaseBox & box)
The copy constructor copies the index space of the argument box.
References d_data.
SAMRAI::tbox::DatabaseBox::~DatabaseBox ()
The destructor does nothing interesting.
Member Function Documentation
DatabaseBox & SAMRAI::tbox::DatabaseBox::operator= (const DatabaseBox & box)
The assignment operator copies the index space of the argument box.
References d_data.
bool SAMRAI::tbox::DatabaseBox::empty () const
Return whether the box is empty. A box is empty if it has dimension zero or if any part of the upper index is less than its corresponding part of the lower index.
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_dimension, SAMRAI::tbox::DatabaseBox_POD::d_hi, and SAMRAI::tbox::DatabaseBox_POD::d_lo.
const int& SAMRAI::tbox::DatabaseBox::getDimVal () const [inline]
Return the dimension of this object.
References d_data, and SAMRAI::tbox::DatabaseBox_POD::d_dimension.
Referenced by lower(), SAMRAI::hier::Box::operator=(), SAMRAI::hier::Box::set_Box_from_DatabaseBox(), and upper().
void SAMRAI::tbox::DatabaseBox::setDim (const Dimension & dim) [inline]
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_dimension, and SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::hier::Box::DatabaseBox_from_Box(), and SAMRAI::tbox::HDFDatabase::getDatabaseBoxVector().
int& SAMRAI::tbox::DatabaseBox::lower (const int i) [inline]
Return the specified component (non-const) of the lower index of the box.
Precondition:
(i >= 0) && (i < getDimVal())
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_lo, getDimVal(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::Box::DatabaseBox_from_Box(), and SAMRAI::hier::Box::set_Box_from_DatabaseBox().
int& SAMRAI::tbox::DatabaseBox::upper (const int i) [inline]
Return the specified component (non-const) of the upper index of the box.
Precondition:
(i >= 0) && (i < getDimVal())
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_hi, getDimVal(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::Box::DatabaseBox_from_Box(), and SAMRAI::hier::Box::set_Box_from_DatabaseBox().
int SAMRAI::tbox::DatabaseBox::lower (const int i) const [inline]
Return the specified component (const) of the lower index of the box.
Precondition:
(i >= 0) && (i < getDimVal())
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_lo, getDimVal(), and TBOX_ASSERT.
int SAMRAI::tbox::DatabaseBox::upper (const int i) const [inline]
Return the specified component (const) of the upper index of the box.
Precondition:
(i >= 0) && (i < getDimVal())
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_hi, getDimVal(), and TBOX_ASSERT.
int SAMRAI::tbox::DatabaseBox::operator== (const DatabaseBox & box) const
Check whether two boxes represent the same portion of index space.
References d_data, SAMRAI::tbox::DatabaseBox_POD::d_dimension, SAMRAI::tbox::DatabaseBox_POD::d_hi, and SAMRAI::tbox::DatabaseBox_POD::d_lo.
Member Data Documentation
DatabaseBox_POD SAMRAI::tbox::DatabaseBox::d_data
All data members in a POD type.
Due to the need to compute offsets for data members and that offsets cannot be computed for non-POD data, we place all data members in a POD struct and own an object of that struct.
Data members are public so that the HDFDatabase need not mirror this structure in defining a compound type for HDF.
Referenced by DatabaseBox(), empty(), getDimVal(), lower(), operator=(), operator==(), SAMRAI::tbox::SiloDatabase::putDatabaseBoxArray(), setDim(), and upper().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/DatabaseBox.h
source/SAMRAI/tbox/DatabaseBox.C