SAMRAI: SAMRAI::pdat::FaceData< TYPE > Class Template Reference
SAMRAI::pdat::FaceData< TYPE > Class Template Reference
Class FaceData<TYPE> provides an implementation for data defined at cell faces on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a face data object represents data of some template TYPE and depth on the faces of the cells in the box. Here, depth indicates the number of data values at each face index location. The FaceGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and face-centered data.
#include <source/SAMRAI/pdat/FaceData.h>
Public Types
typedef FaceIterator iterator
Public Member Functions
FaceData (const hier::Box &box, int depth, const hier::IntVector &ghosts)
The constructor for a face data object.
virtual ~FaceData ()
The virtual destructor for a face data object.
int getDepth () const
Return the depth (e.g., the number of components in each spatial location) of the array.
TYPE * getPointer (int face_normal, int depth=0)
Get a pointer to the beginning of a particular face normal and depth component of the face centered array.
const TYPE * getPointer (int face_normal, int depth=0) const
Get a const pointer to the beginning of a particular face normal and depth component of the face centered array.
TYPE & operator() (const FaceIndex &i, int depth=0)
Return a reference to the data entry corresponding to a given face index and depth.
const TYPE & operator() (const FaceIndex &i, int depth=0) const
Return a const reference to the data entry corresponding to a given face index and depth.
ArrayData< TYPE > & getArrayData (int face_normal)
Return a reference to the array data object for the given face normal of the face centered data object.
const ArrayData< TYPE > & getArrayData (int face_normal) const
Return a const reference to the array data object for the given face normal of the face centered data object.
virtual void copy (const hier::PatchData &src)
A fast copy from source to destination (i.e., this) patch data object.
virtual void copy2 (hier::PatchData &dst) const
A fast copy from source (i.e., this) to destination patch data object.
virtual void copy (const hier::PatchData &src, const hier::BoxOverlap &overlap)
Copy data from source to destination (i.e., this) patch data object on the given overlap.
virtual void copy2 (hier::PatchData &dst, const hier::BoxOverlap &overlap) const
Copy data from source (i.e., this) to destination patch data object on the given overlap.
void copyOnBox (const FaceData< TYPE > &src, const hier::Box &box)
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
void copyDepth (int dst_depth, const FaceData< TYPE > &src, int src_depth)
Fast copy (i.e., source and this face data objects are defined over the same box) to this destination face data object from the given source face data object at the specified depths.
virtual bool canEstimateStreamSizeFromBox () const
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
virtual size_t getDataStreamSize (const hier::BoxOverlap &overlap) const
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
virtual void packStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap) const
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an FaceOverlap of the same DIM.
virtual void unpackStream (tbox::MessageStream &stream, const hier::BoxOverlap &overlap)
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an FaceOverlap of the same DIM.
void fill (const TYPE &t, int d=0)
Fill all values at depth d with the value t.
void fill (const TYPE &t, const hier::Box &box, int d=0)
Fill all values at depth d within the box with the value t.
void fillAll (const TYPE &t)
Fill all depth components with value t.
void fillAll (const TYPE &t, const hier::Box &box)
Fill all depth components within the box with value t.
void print (const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all face data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
void print (const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all face data values at the given array depth in the specified box.
void printAxis (tbox::Dimension::dir_t face_normal, const hier::Box &box, std::ostream &os=tbox::plog, int prec=12) const
Print all face centered data values for specified face normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
void printAxis (tbox::Dimension::dir_t face_normal, const hier::Box &box, int depth, std::ostream &os=tbox::plog, int prec=12) const
Print all face centered data values for specified face normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
virtual void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Static Public Member Functions
static size_t getSizeOfData (const hier::Box &box, int depth, const hier::IntVector &ghosts)
Calculate the amount of memory needed to represent face- centered data over a CELL-centered AMR index space box.
Detailed Description
template<class TYPE>
class SAMRAI::pdat::FaceData< TYPE >
Class FaceData<TYPE> provides an implementation for data defined at cell faces on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a face data object represents data of some template TYPE and depth on the faces of the cells in the box. Here, depth indicates the number of data values at each face index location. The FaceGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and face-centered data.
Face data is stored in DIM arrays, each of which contains the data for the faces normal to a corresponding coordinate direction. In addition, the array indices are permuted so that the fastest array direction is the same as the normal direction of the face. Memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory. For example, a three-dimensional face data object created over a CELL-centered AMR index space [l0:u0,l1:u1,l2:u2] allocates three data arrays sized as follows:
 *
 * face normal 0
 *   [ l0 : u0+1 ,
 *     l1 : u1 ,
 *     l2 : u2 , d ]   ,
 *
 * face normal 1
 *   [ l1 : u1+1 ,
 *     l2 : u2 ,
 *     l0 : u0 , d ]   ,
 *
 * face normal 2
 *   [ l2 : u2+1 ,
 *     l0 : u0 ,
 *     l1 : u1 , d ]   ,
 *
 *
Here the face normal directions 0, 1, 2 can be thought of as the x, y, and z face normal directions, respectively, and d is the depth index (i.e., number of values at each face index location). Other spatial dimensions are represented similarly.
The data type TYPE must define a default constructor (that takes no arguments) and also the assignment operator.
IMPORTANT: The SideData<TYPE> class provides the same storage as this face data class, except that the coordinate directions of the individual arrays are not permuted.
See also:
pdat::ArrayData
hier::PatchData
pdat::FaceDataFactory
pdat::FaceIndex
pdat::FaceIterator
pdat::FaceGeometry
Member Typedef Documentation
template<class TYPE> typedef FaceIterator SAMRAI::pdat::FaceData< TYPE >::iterator
The face iterator iterates over the elements on one face normal of a face centered box geometry. This typedef is a convenience for using the FaceIterator class.
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::FaceData< TYPE >::FaceData (const hier::Box & box, int depth, const hier::IntVector & ghosts) [inline]
The constructor for a face data object.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the face data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the face data will be allocated.
Precondition:
box.getDim() == ghosts.getDim()
depth > 0
ghosts.min() >= 0
References SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::PatchData::getGhostBox(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > SAMRAI::pdat::FaceData< TYPE >::~FaceData () [inline, virtual]
The virtual destructor for a face data object.
Member Function Documentation
template<class TYPE > size_t SAMRAI::pdat::FaceData< TYPE >::getSizeOfData (const hier::Box & box, int depth, const hier::IntVector & ghosts) [inline, static]
Calculate the amount of memory needed to represent face- centered data over a CELL-centered AMR index space box.
This function assumes that the amount of memory needed for TYPE is sizeof(TYPE). If this is not the case, then a specialized function must be defined.
Parameters:
box const Box reference describing the interior of the standard CELL-centered index box over which the face data object will be created.
depth gives the number of components for each spatial location in the array.
ghosts const IntVector reference indicating the width of the ghost cell region around the box over which the face data will be allocated.
Precondition:
box.getDim() == ghosts.getDim()
depth > 0
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::grow(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > int SAMRAI::pdat::FaceData< TYPE >::getDepth () const [inline]
Return the depth (e.g., the number of components in each spatial location) of the array.
template<class TYPE > TYPE * SAMRAI::pdat::FaceData< TYPE >::getPointer (int face_normal, int depth = 0) [inline]
Get a pointer to the beginning of a particular face normal and depth component of the face centered array.
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > const TYPE * SAMRAI::pdat::FaceData< TYPE >::getPointer (int face_normal, int depth = 0) const [inline]
Get a const pointer to the beginning of a particular face normal and depth component of the face centered array.
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::FaceData< TYPE >::operator() (const FaceIndex & i, int depth = 0) [inline]
Return a reference to the data entry corresponding to a given face index and depth.
Precondition:
getDim() == i.getDim()
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue()));
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::FaceIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > const TYPE & SAMRAI::pdat::FaceData< TYPE >::operator() (const FaceIndex & i, int depth = 0) const [inline]
Return a const reference to the data entry corresponding to a given face index and depth.
Precondition:
getDim() == i.getDim()
(i.getAxis() >= 0) && (i.getAxis() < getDim().getValue()));
(depth >= 0) && (depth < getDepth())
References SAMRAI::pdat::FaceIndex::getAxis(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > ArrayData< TYPE > & SAMRAI::pdat::FaceData< TYPE >::getArrayData (int face_normal) [inline]
Return a reference to the array data object for the given face normal of the face centered data object.
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::OuterfaceData< TYPE >::copy(), SAMRAI::pdat::OuterfaceData< TYPE >::copy2(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth2(), and SAMRAI::pdat::FaceData< TYPE >::copyOnBox().
template<class TYPE > const ArrayData< TYPE > & SAMRAI::pdat::FaceData< TYPE >::getArrayData (int face_normal) const [inline]
Return a const reference to the array data object for the given face normal of the face centered data object.
Precondition:
(face_normal >= 0) && (face_normal < getDim().getValue())
References SAMRAI::hier::PatchData::getDim(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::copy (const hier::PatchData & src) [inline, virtual]
A fast copy from source to destination (i.e., this) patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, source data must be an FaceData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
References SAMRAI::hier::PatchData::copy2(), SAMRAI::hier::Box::empty(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::copy2 (hier::PatchData & dst) const [inline, virtual]
A fast copy from source (i.e., this) to destination patch data object.
Data is copied where there is overlap in the underlying index space. The copy is performed on the interior plus the ghost cell width (for both the source and destination). Currently, destination data must be an FaceData of the same DIM and TYPE. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<FaceData<TYPE> *>(&dst) != 0
References SAMRAI::hier::Box::empty(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::copy (const hier::PatchData & src, const hier::BoxOverlap & overlap) [inline, virtual]
Copy data from source to destination (i.e., this) patch data object on the given overlap.
Currently, source data must be FaceData of the same DIM and TYPE and the overlap must be a FaceOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == src.getDim()
References SAMRAI::hier::PatchData::copy2(), SAMRAI::hier::PatchData::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::copy2 (hier::PatchData & dst, const hier::BoxOverlap & overlap) const [inline, virtual]
Copy data from source (i.e., this) to destination patch data object on the given overlap.
Currently, destination data must be FaceData of the same DIM and TYPE and the overlap must be a FaceOverlap of the same DIM. If not, then an unrecoverable error results.
Precondition:
getDim() == dst.getDim()
dynamic_cast<FaceData<TYPE> *>(&dst) != 0
dynamic_cast<const FaceOverlap *>(&overlap) != 0
References SAMRAI::hier::PatchData::getBox(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::copyOnBox (const FaceData< TYPE > & src, const hier::Box & box) [inline]
Copy data from source to destination (i.e., this) patch data object on the given CELL-centered AMR index box.
Precondition:
(getDim() == src.getDim()) && (getDim() == box.getDim())
References SAMRAI::pdat::FaceData< TYPE >::getArrayData(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::copyDepth (int dst_depth, const FaceData< TYPE > & src, int src_depth) [inline]
Fast copy (i.e., source and this face data objects are defined over the same box) to this destination face data object from the given source face data object at the specified depths.
Precondition:
getDim() == src.getDim()
References SAMRAI::hier::Box::empty(), SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::FaceData< TYPE >::canEstimateStreamSizeFromBox () const [inline, virtual]
Return true if the patch data object can estimate the stream size required to fit its data using only index space information (i.e., a box).
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Implements SAMRAI::hier::PatchData.
template<class TYPE > size_t SAMRAI::pdat::FaceData< TYPE >::getDataStreamSize (const hier::BoxOverlap & overlap) const [inline, virtual]
Return the number of bytes needed to stream the data in this patch data object lying in the specified box overlap region.
This routine is defined for the standard types (bool, char, double, float, int, and dcomplex).
Precondition:
dynamic_cast<const FaceOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::pdat::FaceOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) const [inline, virtual]
Pack data in this patch data object lying in the specified box overlap region into the stream. The overlap must be an FaceOverlap of the same DIM.
Precondition:
dynamic_cast<const FaceOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::Transformation::getBeginBlock(), SAMRAI::pdat::FaceOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::hier::Transformation::getEndBlock(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::pdat::FaceOverlap::getTransformation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxOverlap & overlap) [inline, virtual]
Unpack data from stream into this patch data object over the specified box overlap region. The overlap must be an FaceOverlap of the same DIM.
Precondition:
dynamic_cast<const FaceOverlap *>(&overlap) != 0
Implements SAMRAI::hier::PatchData.
References SAMRAI::hier::BoxContainer::empty(), SAMRAI::pdat::FaceOverlap::getDestinationBoxContainer(), SAMRAI::hier::PatchData::getDim(), SAMRAI::pdat::FaceOverlap::getSourceOffset(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::fill (const TYPE & t, int d = 0) [inline]
Fill all values at depth d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::fill (const TYPE & t, const hier::Box & box, int d = 0) [inline]
Fill all values at depth d within the box with the value t.
Precondition:
getDim() == box.getDim()
(d >= 0) && (d < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all depth components with value t.
References SAMRAI::hier::PatchData::getDim(), and SAMRAI::tbox::Dimension::getValue().
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all depth components within the box with value t.
Precondition:
getDim() == box.getDim()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::FaceGeometry::toFaceBox().
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::print (const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all face data values residing in the specified box. If the depth of the array is greater than one, all depths are printed.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::FaceData< TYPE >::printAxis(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::print (const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all face data values at the given array depth in the specified box.
Parameters:
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::pdat::FaceData< TYPE >::printAxis(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::printAxis (tbox::Dimension::dir_t face_normal, const hier::Box & box, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all face centered data values for specified face normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
Parameters:
face_normal integer face normal coordinate direction, must satisfy 0 <= face_normal < DIM
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(face_normal >= 0) && (face_normal < getDim().getValue())
References SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::FaceData< TYPE >::print().
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::printAxis (tbox::Dimension::dir_t face_normal, const hier::Box & box, int depth, std::ostream & os = tbox::plog, int prec = 12) const [inline]
Print all face centered data values for specified face normal direction residing in the specified box. If the depth of the data is greater than one, all depths are printed.
Parameters:
face_normal integer face normal coordinate direction, must satisfy 0 <= face_normal < DIM
box const reference to box over whioch to print data. Note box is assumed to reside in standard cell-centered index space and will be converted to face index space.
depth integer depth component, must satisfy 0 <= depth < actual depth of data array
os reference to output stream.
prec integer precision for printing floating point numbers (i.e., TYPE = float, double, or dcomplex). The default is 12 decimal places for double and complex floating point numbers, and the default is 6 decimal places floats. For other types, this value is ignored.
Precondition:
getDim() == box.getDim()
(depth >= 0) && (depth < getDepth())
(face_normal >= 0) && (face_normal < getDim().getValue())
References SAMRAI::pdat::FaceGeometry::begin(), SAMRAI::pdat::FaceGeometry::end(), SAMRAI::hier::PatchData::getDim(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline, virtual]
Check that class version and restart file version are equal. If so, read data members from the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::FaceData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline, virtual]
Write out the class version number and other data members to the restart database.
Precondition:
restart_db
Reimplemented from SAMRAI::hier::PatchData.
References SAMRAI::hier::PatchData::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::tbox::Utilities::intToString(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/FaceData.h
source/SAMRAI/pdat/FaceData.C