SAMRAI: SAMRAI::mesh::GraphLoadBalancer Class Reference
SAMRAI::mesh::GraphLoadBalancer Class Reference
A graph-based load balance using PT-Scotch to partition patches on a level.
#include <source/SAMRAI/mesh/GraphLoadBalancer.h>
Public Member Functions
GraphLoadBalancer (const tbox::Dimension &dim, const std::string &name, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
Initializing constructor sets object state to default or, if database provided, to parameters in database.
virtual ~GraphLoadBalancer ()
Virtual destructor releases all internal storage.
void setWorkloadPatchDataIndex (int data_id, int level_number=-1)
Configure the load balancer to use the data stored in the hierarchy at the specified descriptor index for estimating the workload on each cell.
bool getLoadBalanceDependsOnPatchData (int level_number) const
Return true if load balancing procedure for given level depends on patch data on mesh; otherwise return false.
void loadBalanceBoxLevel (hier::BoxLevel &balance_box_level, hier::Connector *balance_to_anchor, const boost::shared_ptr< hier::PatchHierarchy > &hierarchy, const int level_number, const hier::IntVector &min_size, const hier::IntVector &max_size, const hier::BoxLevel &domain_box_level, const hier::IntVector &bad_interval, const hier::IntVector &cut_factor, const tbox::RankGroup &rank_group=tbox::RankGroup()) const
const std::string & getObjectName () const
Get the name of this object.
Detailed Description
A graph-based load balance using PT-Scotch to partition patches on a level.
This class load balances by treating input boxes as weighted nodes on a graph. The PT-Scotch graph partitioning library is used to distribute these nodes across all the processors.
If SAMRAI is not configured with PT-Scotch, this class will still compile, but the load balancing calls will effectively be no-ops.
This class is primarily intended to be used as a load balancing option within the TilePartitioner class after clustering has been executed by the TileClustering class, though it is not required to be used in that context.
Currently, only uniform load balancing is supported.
target_box_size The boxes that are recevied by this load balancer as input may be very large, and may need to be chopped in order to provide a sufficient number of nodes on the graph that is used to partition the level. The load balancer will attempt to chop any boxes larger than this size into pieces as close to this size as possible. When used in conjunction with the TileClustering box generator, the recommended size is the tile size times the refinement ratio. If no input is given for this entry, an internal heuristic will choose a target box size, but the chosen value may not be well-suited to any particular problem.
coalesce_boxes After load balancing, coalesce boxes on each local processor wherever possible if this boolean is true. If coalescing is turned off, the load balancer may result in levels containing a large number of small boxes. This option can be invoked to spatially merge those boxes where possible.
tile_size Tile size when using tile mode. Tile mode restricts box cuts to tile boundaries. Default is 1, which is equivalent to no restriction.
Details:
parameter
type
default
range
opt/req
behavior on restart
target_box_size
int[]
default computed by internal heuristic
all values > 0
opt
Not written to restart. Value in input db used.
coalesce_boxes
bool
true
true/false
opt
Not written to restart. Value in input db used.
tile_size
IntVector
1
1-
opt
Not written to restart. Value in input db used.
See also:
mesh::LoadBalanceStrategy
Constructor & Destructor Documentation
SAMRAI::mesh::GraphLoadBalancer::GraphLoadBalancer (const tbox::Dimension & dim, const std::string & name, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>())
Initializing constructor sets object state to default or, if database provided, to parameters in database.
Parameters:
[in] dim
[in] name User-defined std::string identifier used for error reporting and timer names. If omitted, "GraphLoadBalancer" is used.
[in] input_db (optional) database pointer providing parameters from input file. This pointer may be null indicating no input is used.
Precondition:
!name.empty()
References TBOX_ASSERT, and TBOX_WARNING.
SAMRAI::mesh::GraphLoadBalancer::~GraphLoadBalancer () [virtual]
Virtual destructor releases all internal storage.
Member Function Documentation
void SAMRAI::mesh::GraphLoadBalancer::setWorkloadPatchDataIndex (int data_id, int level_number = -1)
Configure the load balancer to use the data stored in the hierarchy at the specified descriptor index for estimating the workload on each cell.
Note: This method currently does not affect the results because this class does not yet support uniform load balancing.
Parameters:
data_id Integer value of patch data identifier for workload estimate on each cell. An invalid value (i.e., < 0) indicates that a spatially-uniform work estimate will be used. The default value is -1 (undefined) implying the uniform work estimate.
level_number Optional integer number for level on which data id is used. If no value is given, the data will be used for all levels.
Precondition:
hier::VariableDatabase::getDatabase()->getPatchDescriptor()->getPatchDataFactory(data_id) is actually a boost::shared_ptr<pdat::CellDataFactory<double> >
bool SAMRAI::mesh::GraphLoadBalancer::getLoadBalanceDependsOnPatchData (int level_number) const [inline, virtual]
Return true if load balancing procedure for given level depends on patch data on mesh; otherwise return false.
Parameters:
[in] level_number Integer patch level number.
Implements SAMRAI::mesh::LoadBalanceStrategy.
References NULL_USE.
void SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel (hier::BoxLevel & balance_box_level, hier::Connector * balance_to_anchor, const boost::shared_ptr< hier::PatchHierarchy > & hierarchy, const int level_number, const hier::IntVector & min_size, const hier::IntVector & max_size, const hier::BoxLevel & domain_box_level, const hier::IntVector & bad_interval, const hier::IntVector & cut_factor, const tbox::RankGroup & rank_group = tbox::RankGroup()) const [virtual]
Given a BoxLevel, representing the domain of a specified level in the AMR hierarchy, generate a new BoxLevel from which the patches for the level may be formed and update two Connectors incident on the changed BoxLevel. The union of the boxes in the balance_box_level is the same before and after the the method call.
Parameters:
[in,out] balance_box_level Input BoxLevel. On input, this is the pre-balance BoxLevel. On output, it is the balanced BoxLevel.
[in,out] balance_to_anchor Connector between the balance_box_level and some given "anchor box_level". This must be accurate on input. On putput, connects the newly balanced balance_box_level to the anchor box_level.
[in] hierarchy The hierarchy where the work distribution data lives.
[in] level_number The number of the level where the work distribution data lives.
[in] min_size hier::IntVector representing mimimum box size.
[in] max_size hier::IntVector representing maximum box size.
[in] domain_box_level Description of the domain.
[in] bad_interval hier::IntVector indicating the length of an interval of cells along each side of the box where chopping the box may produce boxes with certain "bad" properties. For example, this is primiarily used to avoid generating ghost regions for patches that intersect the domain boundary in ways that may it difficult for a use to provide boundary values. Thus, it is typically related to the maximum ghost cell width in the problem. See hier::BoxUtilities header file for more information.
[in] cut_factor hier::IntVector indicating factor for chopping each side of a box; i.e., after chopping a box, the number of cells along each direction of each piece must be an integer multiple of the corresponding entry in the cut factor vector. For example, the cut factor may be related to the coarsen ratio between levels in the hierarchy in which case it may be used to produce boxes that can be coarsened by a certain factor if needed. See hier::BoxUtilities header file for more information.
[in] rank_group Input tbox::RankGroup indicating a set of ranks on which all boxes in the output balance_box_level will be restricted. Some child classes may not make use of this argument.
Note: This implementation does not yet support non-uniform load balancing.
Precondition:
!balance_to_anchor || balance_to_anchor->hasTranspose()
!balance_to_anchor || balance_to_anchor->isTransposeOf(balance_to_anchor->getTranspose())
(d_dim == balance_box_level.getDim()) && (d_dim == min_size.getDim()) && (d_dim == max_size.getDim()) && (d_dim == domain_box_level.getDim()) && (d_dim == bad_interval.getDim()) && (d_dim == cut_factor.getDim())
!hierarchy || (d_dim == hierarchy->getDim())
!d_mpi_is_dupe || (d_mpi.getSize() == balance_box_level.getMPI().getSize())
!d_mpi_is_dupe || (d_mpi.getSize() == balance_box_level.getMPI().getRank())
Implements SAMRAI::mesh::LoadBalanceStrategy.
References SAMRAI::tbox::AsyncCommStage::advanceSome(), SAMRAI::tbox::SAMRAI_MPI::AllReduce(), SAMRAI::hier::BoxContainer::back(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::tbox::AsyncCommPeer< TYPE >::beginRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::beginSend(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::hier::Connector::clearNeighborhoods(), SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation(), SAMRAI::hier::BoxLevel::DISTRIBUTED, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::tbox::MessageStream::getBufferStart(), SAMRAI::tbox::SAMRAI_MPI::getCommunicator(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::tbox::MessageStream::getCurrentSize(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::BoxLevel::getGlobalBoxes(), SAMRAI::hier::BoxLevel::getGlobalNumberOfBoxes(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxId::getLocalId(), SAMRAI::hier::Box::getLocalId(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::IntVector::getOne(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvData(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvSize(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::hier::LocalId::getValue(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::tbox::AsyncCommStage::hasCompletedMembers(), SAMRAI::tbox::AsyncCommStage::hasPendingRequests(), SAMRAI::hier::Connector::insertLocalNeighbor(), SAMRAI::tbox::AsyncCommPeer< TYPE >::isDone(), SAMRAI::hier::BoxContainer::isEmpty(), SAMRAI::hier::Connector::makeEmptyLocalNeighborhood(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), MPI_SUM, NULL_USE, SAMRAI::tbox::AsyncCommStage::popCompletionQueue(), SAMRAI::tbox::AsyncCommStage::Member::pushToCompletionQueue(), SAMRAI::tbox::MessageStream::Read, SAMRAI::hier::BoxLevel::removePeriodicImageBoxes(), SAMRAI::hier::Connector::removePeriodicRelationships(), SAMRAI::hier::Connector::setBase(), SAMRAI::hier::Connector::setHead(), SAMRAI::hier::Connector::setTranspose(), SAMRAI::hier::Connector::setWidth(), SAMRAI::hier::Box::size(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, TBOX_WARNING, and SAMRAI::hier::Box::upper().
const std::string& SAMRAI::mesh::GraphLoadBalancer::getObjectName () const [inline]
Get the name of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/GraphLoadBalancer.h
source/SAMRAI/mesh/GraphLoadBalancer.C