SAMRAI: SAMRAI::pdat::EdgeDataFactory< TYPE > Class Template Reference
SAMRAI::pdat::EdgeDataFactory< TYPE > Class Template Reference
#include <source/SAMRAI/pdat/EdgeDataFactory.h>
Public Member Functions
EdgeDataFactory (int depth, const hier::IntVector &ghosts, bool fine_boundary_represents_var)
virtual ~EdgeDataFactory ()
virtual boost::shared_ptr
< hier::PatchDataFactory > cloneFactory (const hier::IntVector &ghosts)
Abstract virtual function to clone a patch data factory.
virtual boost::shared_ptr
< hier::PatchData > allocate (const hier::Patch &patch) const
virtual boost::shared_ptr
< hier::BoxGeometry > getBoxGeometry (const hier::Box &box) const
int getDepth () const
virtual size_t getSizeOfMemory (const hier::Box &box) const
bool fineBoundaryRepresentsVariable () const
bool dataLivesOnPatchBorder () const
bool validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > &dst_pdf) const
Detailed Description
template<class TYPE>
class SAMRAI::pdat::EdgeDataFactory< TYPE >
Class EdgeDataFactory is a factory class used to allocate new instances of EdgeData objects. It is a subclass of the patch data factory class and edge data is a subclass of patch data. Both the factory and data classes are templated on the type of the contained object (e.g., double or int).
See also:
pdat::EdgeData
pdat::PatchDataFactory
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::EdgeDataFactory< TYPE >::EdgeDataFactory (int depth, const hier::IntVector & ghosts, bool fine_boundary_represents_var) [inline]
The constructor for the edge data factory class. The ghost cell width, depth (number of components), and fine boundary representation arguments give the defaults for all edge data objects created with this factory. See the EdgeVariable<TYPE> class header file for more information.
Precondition:
depth > 0
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), and TBOX_ASSERT.
template<class TYPE > SAMRAI::pdat::EdgeDataFactory< TYPE >::~EdgeDataFactory () [inline, virtual]
Virtual destructor for the edge data factory class.
Member Function Documentation
template<class TYPE > boost::shared_ptr< hier::PatchDataFactory > SAMRAI::pdat::EdgeDataFactory< TYPE >::cloneFactory (const hier::IntVector & ghosts) [inline, virtual]
Abstract virtual function to clone a patch data factory.
This will return a new instantiation of the abstract factory with the same properties. The properties of the cloned factory can then be changed without modifying the original.
Parameters:
ghosts default ghost cell width for concrete classes created from the factory.
Precondition:
getDim() == ghosts.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::PatchData > SAMRAI::pdat::EdgeDataFactory< TYPE >::allocate (const hier::Patch & patch) const [inline, virtual]
Virtual factory function to allocate a concrete edge data object. The default information about the object (e.g., ghost cell width) is taken from the factory.
Precondition:
getDim() == patch.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::PatchDataFactory::d_ghosts, SAMRAI::hier::Patch::getBox(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::BoxGeometry > SAMRAI::pdat::EdgeDataFactory< TYPE >::getBoxGeometry (const hier::Box & box) const [inline, virtual]
Allocate the box geometry object associated with the patch data. This information will be used in the computation of intersections and data dependencies between objects.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::PatchDataFactory::d_ghosts, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > int SAMRAI::pdat::EdgeDataFactory< TYPE >::getDepth () const [inline]
Get the depth (number of components). This is the depth that will be used in the instantiation of edge data objects.
template<class TYPE > size_t SAMRAI::pdat::EdgeDataFactory< TYPE >::getSizeOfMemory (const hier::Box & box) const [inline, virtual]
Calculate the amount of memory needed to store the edge data object, including object data and dynamically allocated data.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::tbox::MemoryUtilities::align(), SAMRAI::hier::PatchDataFactory::d_ghosts, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::EdgeDataFactory< TYPE >::fineBoundaryRepresentsVariable () const [inline, virtual]
Return a boolean value indicating how data for the edge quantity will be treated on coarse-fine interfaces. This value is passed into the constructor. See the EdgeVariable<TYPE> class header file for more information.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::EdgeDataFactory< TYPE >::dataLivesOnPatchBorder () const [inline, virtual]
Return true since the edge data index space extends beyond the interior of patches. That is, edge data lives on patch borders.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::EdgeDataFactory< TYPE >::validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > & dst_pdf) const [inline]
Return whether it is valid to copy this EdgeDataFactory to the supplied destination patch data factory. It will return true if dst_pdf is EdgeDataFactory or OuteredgeDataFactory, false otherwise.
Precondition:
getDim() == dst_pdf->getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/EdgeDataFactory.h
source/SAMRAI/pdat/EdgeDataFactory.C