SAMRAI: SAMRAI::xfer::RefineTransactionFactory Class Reference
SAMRAI::xfer::RefineTransactionFactory Class Reference
Abstract base class defining the interface for all concrete transaction factory objects that generate data transaction objects used with a RefineSchedule object. A concrete subclass will allocate new transaction objects. This class is an example of the ``Abstract Factory'' method described in the Design Patterns book by Gamma, et al.
#include <source/SAMRAI/xfer/RefineTransactionFactory.h>
Public Member Functions
RefineTransactionFactory ()
Default constructor.
virtual ~RefineTransactionFactory ()
Virtual destructor.
virtual boost::shared_ptr
< tbox::Transaction > allocate (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_box, const hier::Box &src_box, const RefineClasses::Data **refine_data, int item_id, const hier::Box &box, bool use_time_interpolation=false) const =0
Pure virtual function to allocate a concrete refine transaction object. This routine is called by the refine schedule during construction of the schedule.
boost::shared_ptr
< tbox::Transaction > allocate (const boost::shared_ptr< hier::PatchLevel > &dst_level, const boost::shared_ptr< hier::PatchLevel > &src_level, const boost::shared_ptr< hier::BoxOverlap > &overlap, const hier::Box &dst_box, const hier::Box &src_box, const RefineClasses::Data **refine_data, int item_id) const
virtual void setTransactionTime (double fill_time)
Virtual function to set simulation time for transaction objects. This operation is called by the refine schedule during the execution of the RefineSchedule::fillData() routine before data communication operations begin. This function is optional for the concrete transaction factory object. The default implementation is a no-op.
virtual void preprocessScratchSpace (const boost::shared_ptr< hier::PatchLevel > &level, double fill_time, const hier::ComponentSelector &preprocess_vector) const =0
Virtual function allowing transaction factory to preprocess scratch space data before transactactions use it if they need to. This function is optional for the concrete transaction factory object. The default implementation is a no-op.
Detailed Description
Abstract base class defining the interface for all concrete transaction factory objects that generate data transaction objects used with a RefineSchedule object. A concrete subclass will allocate new transaction objects. This class is an example of the ``Abstract Factory'' method described in the Design Patterns book by Gamma, et al.
To add a new type of Transaction object MyRefineTransaction:
Implement a concrete RefineTransactionFactory object as a subclass that is derived from this RefineTransactionFactory base class. Implement the abstract virtual functions as appropriate for the concrete subclass; in particular, the allocate() function must return a new instance of the desired transaction object.
The type of the transaction allocated by the concrete factory is a Transaction. Thus, the new transaction object must be derived from the Transaction base class and implement the abstract virtual functions declared by the base class.
See also:
tbox::Transaction
Constructor & Destructor Documentation
SAMRAI::xfer::RefineTransactionFactory::RefineTransactionFactory ()
Default constructor.
SAMRAI::xfer::RefineTransactionFactory::~RefineTransactionFactory () [virtual]
Virtual destructor.
Member Function Documentation
virtual boost::shared_ptr<tbox::Transaction> SAMRAI::xfer::RefineTransactionFactory::allocate (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_box, const hier::Box & src_box, const RefineClasses::Data ** refine_data, int item_id, const hier::Box & box, bool use_time_interpolation = false) const [pure virtual]
Pure virtual function to allocate a concrete refine transaction object. This routine is called by the refine schedule during construction of the schedule.
Parameters:
dst_level boost::shared_ptr to destination patch level.
src_level boost::shared_ptr to source patch level.
overlap boost::shared_ptr to overlap region between patches.
dst_box Destination Box in destination patch level.
src_box Source Box in source patch level.
refine_data Pointer to array of refine data items
item_id Integer index of RefineClass::Data item associated with transaction.
box Optional const reference to box defining region of refine transaction. Default is an empty box.
use_time_interpolation Optional boolean flag indicating whether the refine transaction involves time interpolation. Default is false.
Implemented in SAMRAI::xfer::StandardRefineTransactionFactory, SAMRAI::algs::OuteredgeSumTransactionFactory, and SAMRAI::algs::OuternodeSumTransactionFactory.
Referenced by allocate().
boost::shared_ptr<tbox::Transaction> SAMRAI::xfer::RefineTransactionFactory::allocate (const boost::shared_ptr< hier::PatchLevel > & dst_level, const boost::shared_ptr< hier::PatchLevel > & src_level, const boost::shared_ptr< hier::BoxOverlap > & overlap, const hier::Box & dst_box, const hier::Box & src_box, const RefineClasses::Data ** refine_data, int item_id) const [inline]
Reimplemented in SAMRAI::algs::OuteredgeSumTransactionFactory, and SAMRAI::algs::OuternodeSumTransactionFactory.
References allocate(), SAMRAI::hier::Box::getEmptyBox(), and TBOX_ASSERT_OBJDIM_EQUALITY4.
void SAMRAI::xfer::RefineTransactionFactory::setTransactionTime (double fill_time) [virtual]
Virtual function to set simulation time for transaction objects. This operation is called by the refine schedule during the execution of the RefineSchedule::fillData() routine before data communication operations begin. This function is optional for the concrete transaction factory object. The default implementation is a no-op.
Reimplemented in SAMRAI::xfer::StandardRefineTransactionFactory.
References NULL_USE.
virtual void SAMRAI::xfer::RefineTransactionFactory::preprocessScratchSpace (const boost::shared_ptr< hier::PatchLevel > & level, double fill_time, const hier::ComponentSelector & preprocess_vector) const [pure virtual]
Virtual function allowing transaction factory to preprocess scratch space data before transactactions use it if they need to. This function is optional for the concrete transaction factory object. The default implementation is a no-op.
Parameters:
level boost::shared_ptr to patch level holding scratch data.
fill_time Double value of simulation time corresponding to RefineSchedule operations.
preprocess_vector Const reference to ComponentSelector that indicates patch data array indices of scratch patch data objects to preprocess.
Implemented in SAMRAI::xfer::StandardRefineTransactionFactory, SAMRAI::algs::OuteredgeSumTransactionFactory, and SAMRAI::algs::OuternodeSumTransactionFactory.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/RefineTransactionFactory.h
source/SAMRAI/xfer/RefineTransactionFactory.C