SAMRAI: SAMRAI::hier::CoarseFineBoundary Class Reference
SAMRAI::hier::CoarseFineBoundary Class Reference
Utility class to construct and maintain a description of the coarse-fine boundary between a patch level and a coarser level.
#include <source/SAMRAI/hier/CoarseFineBoundary.h>
Public Member Functions
CoarseFineBoundary (const tbox::Dimension &dim)
Construct a CoarseFineBoundary object with no boundary boxes.
CoarseFineBoundary (const CoarseFineBoundary &rhs)
Copy constructor.
CoarseFineBoundary (const PatchHierarchy &hierarchy, int level_num, const IntVector &max_ghost_width)
Construct a CoarseFineBoundary object for the specified level in the given patch hierarchy.
CoarseFineBoundary (const PatchLevel &level, const Connector &box_level_to_domain, const Connector &box_level_to_self, const IntVector &max_ghost_width)
Construct a CoarseFineBoundary object for a specified level.
~CoarseFineBoundary ()
Destructor.
void clear ()
Clear all boundary data.
void printClassData (std::ostream &os) const
Print out class data.
CoarseFineBoundary & operator= (const CoarseFineBoundary &rhs)
Assignment operator.
const tbox::Dimension & getDim () const
Functions to get the computed coarse-fine boundaries.
const std::vector< BoundaryBox > & getBoundaries (const GlobalId &global_id, const int boundary_type, const BlockId &block_id=BlockId::zero()) const
Get a vector of boundary boxes of a given type for a specified patch.
const std::vector< BoundaryBox > & getNodeBoundaries (const GlobalId &global_id, const BlockId &block_id=BlockId::zero()) const
Get a vector of node boundary boxes for a specified patch.
const std::vector< BoundaryBox > & getEdgeBoundaries (const GlobalId &global_id, const BlockId &block_id=BlockId::zero()) const
Get a vector of edge boundary boxes for a specified patch.
const std::vector< BoundaryBox > & getFaceBoundaries (const GlobalId &global_id, const BlockId &block_id=BlockId::zero()) const
Get a vector of face boundary boxes for a specified patch.
Detailed Description
Utility class to construct and maintain a description of the coarse-fine boundary between a patch level and a coarser level.
A coarse-fine boundary box is a BoundaryBox object, but it is generated differently than a typical boundary box maintained by a patch geometry object. A boundary box serving as a coarse-fine boundary box describes part of the boundary of a given patch with its next coarser AMR hierarchy level. It does not intersect any other patch on the same level, nor does it lie on a physical domain boundary, except where the physical boundary is periodic and the appropriate continuation of that boundary is part of a coarser patch level.
The coarse-fine boundary is typically created from two adjacent hierarchy levels, but the description lives on (refers to the index space of) the finer level. Since the coarse-fine boundary describes the boundary to the next coarser level, the coarsest level (level zero) has no coarse-fine boundary.
Each CoarseFineBoundary object corresponds to one level, so to represent a entire hierarchy, one would need an array or list of such objects.
Constructor & Destructor Documentation
SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary (const tbox::Dimension & dim) [explicit]
Construct a CoarseFineBoundary object with no boundary boxes.
Parameters:
[in] dim Dimension
SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary (const CoarseFineBoundary & rhs)
Copy constructor.
Parameters:
[in] rhs
SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary (const PatchHierarchy & hierarchy, int level_num, const IntVector & max_ghost_width)
Construct a CoarseFineBoundary object for the specified level in the given patch hierarchy.
Note:
If level number is zero, the coarse-fine boundary will be empty.
Parameters:
[in] hierarchy
[in] level_num
[in] max_ghost_width The ghost width determines the extent of the boundary boxes along the level domain boundary, similar to regular domain boundary boxes. Note that as in the case of regular boundary boxes, each box will always be one cell wide in the direction perpendicular to the patch boundary.
Precondition:
max_ghost_width > IntVector(max_ghost_width.getDim(), -1)
References SAMRAI::hier::CONNECTOR_CREATE, SAMRAI::hier::PatchLevel::findConnector(), SAMRAI::hier::PatchLevel::getBoxLevel(), SAMRAI::hier::PatchHierarchy::getDomainBoxLevel(), SAMRAI::hier::PatchHierarchy::getGridGeometry(), SAMRAI::hier::IntVector::getNumBlocks(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::PatchHierarchy::getPatchLevel(), SAMRAI::hier::PatchLevel::getRatioToLevelZero(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::max(), and TBOX_ASSERT.
SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary (const PatchLevel & level, const Connector & box_level_to_domain, const Connector & box_level_to_self, const IntVector & max_ghost_width)
Construct a CoarseFineBoundary object for a specified level.
The coarse-fine boundary will be computed using the physical domain as the reference coarser level. The physical domain is provided to this method as the 'head' level of the box_level_to_domain Connector.
Note:
If the level covers the entire physical domain, the coarse-fine boundary will be empty.
Parameters:
[in] level
[in] box_level_to_domain
[in] box_level_to_self
[in] max_ghost_width The ghost width determines the extent of the boundary boxes along the level domain boundary, similar to regular domain boundary boxes. Note that as in the case of regular boundary boxes, each box will always be one cell wide in the direction perpendicular to the patch boundary.
Precondition:
max_ghost_width > IntVector(max_ghost_width.getDim(), -1)
References TBOX_ASSERT.
SAMRAI::hier::CoarseFineBoundary::~CoarseFineBoundary ()
Destructor.
Member Function Documentation
void SAMRAI::hier::CoarseFineBoundary::clear () [inline]
Clear all boundary data.
const std::vector< BoundaryBox > & SAMRAI::hier::CoarseFineBoundary::getBoundaries (const GlobalId & global_id, const int boundary_type, const BlockId & block_id = BlockId::zero()) const
Get a vector of boundary boxes of a given type for a specified patch.
The specified patch must exist in the level used to compute the internal state or it is an error.
Parameters:
[in] global_id
[in] boundary_type Codimension of boundaries.
[in] block_id Defaults to 0 for the single block case
Precondition:
d_initialize[block_id.getBlockValue()]
References SAMRAI::hier::BlockId::getBlockValue(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getEdgeBoundaries(), getFaceBoundaries(), and getNodeBoundaries().
const std::vector<BoundaryBox>& SAMRAI::hier::CoarseFineBoundary::getNodeBoundaries (const GlobalId & global_id, const BlockId & block_id = BlockId::zero()) const [inline]
Get a vector of node boundary boxes for a specified patch.
See also:
BoundaryBox for more information.
The specified patch must exist in the level used to compute the internal state or it is an error.
Parameters:
[in] global_id
[in] block_id Defaults to 0 for the single block case
References getBoundaries(), and getDim().
const std::vector<BoundaryBox>& SAMRAI::hier::CoarseFineBoundary::getEdgeBoundaries (const GlobalId & global_id, const BlockId & block_id = BlockId::zero()) const [inline]
Get a vector of edge boundary boxes for a specified patch.
See also:
BoundaryBox for more information.
Note that edge boxes are only meaningful if the dimension is > 1. The specified patch must exist in the level used to compute the internal state or it is an error.
Parameters:
[in] global_id
[in] block_id Defaults to 0 for the single block case
Precondition:
getDim().getValue() >= 2
References getBoundaries(), getDim(), and TBOX_ERROR.
const std::vector<BoundaryBox>& SAMRAI::hier::CoarseFineBoundary::getFaceBoundaries (const GlobalId & global_id, const BlockId & block_id = BlockId::zero()) const [inline]
Get a vector of face boundary boxes for a specified patch.
See also:
BoundaryBox for more information.
Note that face boxes are only meaningful if the dimension is > 2. The specified patch must exist in the level used to compute the internal state or it is an error.
Parameters:
[in] global_id
[in] block_id Defaults to 0 for the single block case
Precondition:
getDim().getValue() >= 3
References getBoundaries(), getDim(), and TBOX_ERROR.
void SAMRAI::hier::CoarseFineBoundary::printClassData (std::ostream & os) const
Print out class data.
Parameters:
[in] os Output stream
References SAMRAI::tbox::Dimension::getValue().
CoarseFineBoundary& SAMRAI::hier::CoarseFineBoundary::operator= (const CoarseFineBoundary & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs
const tbox::Dimension& SAMRAI::hier::CoarseFineBoundary::getDim () const [inline]
Referenced by getEdgeBoundaries(), getFaceBoundaries(), and getNodeBoundaries().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/CoarseFineBoundary.h
source/SAMRAI/hier/CoarseFineBoundary.C