SAMRAI: SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP > Class Template Reference
SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP > Class Template Reference
Struct ArrayDataOperationUtilities<TYPE, OP> provides generic looping operations for all array-based patch data types. The operations are templated on data type and the operation that will be performed on individual array elements in the innermost loop.
#include <source/SAMRAI/pdat/ArrayDataOperationUtilities.h>
Static Public Member Functions
static void doArrayDataOperationOnBox (ArrayData< TYPE > &dst, const ArrayData< TYPE > &src, const hier::Box &opbox, const hier::IntVector &src_shift, unsigned int dst_start_depth, unsigned int src_start_depth, unsigned int num_depth, const OP &op)
static void doArrayDataBufferOperationOnBox (const ArrayData< TYPE > &arraydata, const TYPE *buffer, const hier::Box &opbox, bool src_is_buffer, const OP &op)
Detailed Description
template<class TYPE, class OP>
class SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >
Struct ArrayDataOperationUtilities<TYPE, OP> provides generic looping operations for all array-based patch data types. The operations are templated on data type and the operation that will be performed on individual array elements in the innermost loop.
See also:
ArrayData
Member Function Documentation
template<class TYPE , class OP > void SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox (ArrayData< TYPE > & dst, const ArrayData< TYPE > & src, const hier::Box & opbox, const hier::IntVector & src_shift, unsigned int dst_start_depth, unsigned int src_start_depth, unsigned int num_depth, const OP & op) [inline, static]
Perform operation on a subset of data components of source and destination array data objects and put results in destination array data object.
Parameters:
dst Reference to destination array data object.
src Const reference to source array data object.
opbox Const reference to Box indicating index space region of operation.
src_shift Const reference to IntVector indicating shift required to put source index space region into destination index space region.
dst_start_depth Integer specifying starting depth component of operation in destination array.
src_start_depth Integer specifying starting depth component of operation in source array.
num_depth Integer number of depth components on which to perform operation.
op Const reference to object that performs operations on individual data array elements.
Precondition:
(dst.getDim() == src.getDim()) && (dst.getDim() == opbox.getDim()) && (dst.getDim() == src_shift.getDim())
num_depth >= 0
(0 <= dst_start_depth) && (dst_start_depth + num_depth <= dst.getDepth())
(0 <= src_start_depth) && (src_start_depth + num_depth <= src.getDepth())
References SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY4.
template<class TYPE , class OP > void SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox (const ArrayData< TYPE > & arraydata, const TYPE * buffer, const hier::Box & opbox, bool src_is_buffer, const OP & op) [inline, static]
Perform operation on all data components of array data object and corresponding buffer data, putting results in either the array data object or buffer.
Parameters:
arraydata Const reference to array data object.
buffer Const pointer to first element in buffer.
opbox Const reference to Box indicating operation region in index space of array data object.
src_is_buffer Boolean value indicating whether buffer is source data for operation; if true results will be placed in array data object, otherwise results will go in buffer.
op Const reference to object that performs operations on individual data array elements.
Precondition:
arraydata.getDim() == opbox.getDim()
buffer != 0
opbox.isSpatiallyEqual(opbox * arraydata.getBox())
References SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getDepth(), SAMRAI::pdat::ArrayData< TYPE >::getDim(), SAMRAI::pdat::ArrayData< TYPE >::getOffset(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::hier::Box::isSpatiallyEqual(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::size(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/ArrayDataOperationUtilities.h
source/SAMRAI/pdat/ArrayDataOperationUtilities.C