SAMRAI: SAMRAI::hier::PeriodicId Class Reference
SAMRAI::hier::PeriodicId Class Reference
Generic identifier for identifying the periodic shift.
#include <source/SAMRAI/hier/PeriodicId.h>
Public Member Functions
PeriodicId ()
Default constructor.
PeriodicId (const PeriodicId &other)
Copy constructor.
PeriodicId (const int &value)
Construct from a numerical value.
~PeriodicId ()
Default constructor.
PeriodicId & operator= (const PeriodicId &rhs)
Assignment operator.
PeriodicId & operator= (const int &rhs)
Assignment operator.
const int & getPeriodicValue () const
Access the numerical value.
bool isValid () const
Returns True if the value is valid.
Comparison with another PeriodicId.
bool operator== (const PeriodicId &rhs) const
Equality operator.
bool operator!= (const PeriodicId &rhs) const
Inequality operator.
bool operator< (const PeriodicId &rhs) const
Less-than operator.
bool operator> (const PeriodicId &rhs) const
Greater-than operator.
bool operator<= (const PeriodicId &rhs) const
Less-than-or-equal-to operator.
bool operator>= (const PeriodicId &rhs) const
Greater-thanor-equal-to operator.
Static Public Member Functions
static const PeriodicId & zero ()
Get the PeriodicId with a numerical value of zero.
static const PeriodicId & invalidId ()
Return the invalid value for PeriodicId.
Friends
std::ostream & operator<< (std::ostream &co, const PeriodicId &r)
Format and insert object into a stream.
Detailed Description
Generic identifier for identifying the periodic shift.
Comparison operators are provided to define sorted ordering of objects.
Constructor & Destructor Documentation
SAMRAI::hier::PeriodicId::PeriodicId ()
Default constructor.
SAMRAI::hier::PeriodicId::PeriodicId (const PeriodicId & other)
Copy constructor.
SAMRAI::hier::PeriodicId::PeriodicId (const int & value) [explicit]
Construct from a numerical value.
This method is explicit to prevent automatic conversion.
SAMRAI::hier::PeriodicId::~PeriodicId ()
Default constructor.
Member Function Documentation
PeriodicId& SAMRAI::hier::PeriodicId::operator= (const PeriodicId & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs
Returns:
*this
PeriodicId& SAMRAI::hier::PeriodicId::operator= (const int & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs
Returns:
*this
const int& SAMRAI::hier::PeriodicId::getPeriodicValue () const [inline]
Access the numerical value.
Referenced by SAMRAI::hier::Box::Box(), SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::PeriodicShiftCatalog::getOppositeShiftNumber(), SAMRAI::hier::Box::initialize(), SAMRAI::hier::BoxId::putToIntBuffer(), SAMRAI::hier::BoxId::putToMessageStream(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), and SAMRAI::hier::PeriodicShiftCatalog::shiftNumberToShiftDistance().
static const PeriodicId& SAMRAI::hier::PeriodicId::zero () [inline, static]
Get the PeriodicId with a numerical value of zero.
Referenced by SAMRAI::hier::Connector::checkConsistencyWithHead(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::Connector::find(), SAMRAI::hier::Connector::findLocal(), SAMRAI::hier::Connector::getNeighborBoxes(), SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber(), SAMRAI::hier::Connector::hasNeighborSet(), SAMRAI::hier::BoxId::isPeriodicImage(), SAMRAI::hier::Connector::neighborhoodEqual(), SAMRAI::hier::Connector::numLocalNeighbors(), and SAMRAI::hier::Connector::writeNeighborhoodToStream().
static const PeriodicId& SAMRAI::hier::PeriodicId::invalidId () [inline, static]
Return the invalid value for PeriodicId.
bool SAMRAI::hier::PeriodicId::isValid () const [inline]
Returns True if the value is valid.
Referenced by SAMRAI::hier::Box::Box(), SAMRAI::hier::BoxId::BoxId(), SAMRAI::hier::PeriodicShiftCatalog::getOppositeShiftNumber(), SAMRAI::hier::Box::initialize(), SAMRAI::hier::BoxId::isValid(), SAMRAI::hier::BoxId::operator!=(), SAMRAI::hier::BoxId::operator<(), SAMRAI::hier::BoxId::operator<=(), SAMRAI::hier::BoxId::operator==(), SAMRAI::hier::BoxId::operator>(), SAMRAI::hier::BoxId::operator>=(), and SAMRAI::hier::PeriodicShiftCatalog::shiftNumberToShiftDistance().
bool SAMRAI::hier::PeriodicId::operator== (const PeriodicId & rhs) const [inline]
Equality operator.
All comparison operators compare the numerical value.
Parameters:
[in] rhs
bool SAMRAI::hier::PeriodicId::operator!= (const PeriodicId & rhs) const [inline]
Inequality operator.
See note on comparison for operator==(const PeriodicId&);
Parameters:
[in] rhs
bool SAMRAI::hier::PeriodicId::operator< (const PeriodicId & rhs) const [inline]
Less-than operator.
See note on comparison for operator==(const PeriodicId&);
Parameters:
[in] rhs
bool SAMRAI::hier::PeriodicId::operator> (const PeriodicId & rhs) const [inline]
Greater-than operator.
See note on comparison for operator==(const PeriodicId&);
Parameters:
[in] rhs
bool SAMRAI::hier::PeriodicId::operator<= (const PeriodicId & rhs) const [inline]
Less-than-or-equal-to operator.
See note on comparison for operator==(const PeriodicId&);
Parameters:
[in] rhs
bool SAMRAI::hier::PeriodicId::operator>= (const PeriodicId & rhs) const [inline]
Greater-thanor-equal-to operator.
See note on comparison for operator==(const PeriodicId&);
Parameters:
[in] rhs
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & co, const PeriodicId & r) [friend]
Format and insert object into a stream.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/PeriodicId.h
source/SAMRAI/hier/PeriodicId.C