SAMRAI: SAMRAI::pdat::SideOverlap Class Reference
SAMRAI::pdat::SideOverlap Class Reference
#include <source/SAMRAI/pdat/SideOverlap.h>
Public Member Functions
SideOverlap (const std::vector< hier::BoxContainer > &boxes, const hier::Transformation &Transformation)
virtual ~SideOverlap ()
virtual bool isOverlapEmpty () const
virtual const hier::BoxContainer & getDestinationBoxContainer (const int axis) const
virtual void getSourceBoxContainer (hier::BoxContainer &src_boxes, int &normal_direction) const
Get a BoxContainer representing the source boxes of the overlap.
virtual const hier::IntVector & getSourceOffset () const
virtual const
hier::Transformation & getTransformation () const
Refturn the transformation between the destination and source index spaces.
Detailed Description
Class SideOverlap represents the intersection between two side centered geometry boxes. It is a subclass of hier::BoxOverlap and records the portions of index space that needs to be copied between two objects with side centered geometry.
See also:
hier::BoxOverlap
pdat::SideOverlap
Constructor & Destructor Documentation
SAMRAI::pdat::SideOverlap::SideOverlap (const std::vector< hier::BoxContainer > & boxes, const hier::Transformation & Transformation)
The constructor takes the list of boxes and the transformation from source to destination index spaces. This information is used later in the generation of communication schedules.
References SAMRAI::hier::Transformation::getOffset(), and SAMRAI::tbox::Dimension::getValue().
SAMRAI::pdat::SideOverlap::~SideOverlap () [virtual]
The virtual destructor does nothing interesting except deallocate box data.
Member Function Documentation
bool SAMRAI::pdat::SideOverlap::isOverlapEmpty () const [virtual]
Return whether there is an empty intersection between the two side centered boxes. This method over-rides the virtual function in the hier::BoxOverlap base class.
Implements SAMRAI::hier::BoxOverlap.
const hier::BoxContainer & SAMRAI::pdat::SideOverlap::getDestinationBoxContainer (const int axis) const [virtual]
Return the list of boxes (in side centered index space) that constitute the intersection. The boxes are given in the destination coordinate space and must be shifted by -(getSourceOffset()) to lie in the source index space. The axis argument represents which axis is desired: X=0, Y=1, and Z=2.
Precondition:
(axis >= 0) && (axis < d_dst_boxes.size())
References TBOX_ASSERT.
Referenced by SAMRAI::pdat::OutersideData< TYPE >::copy(), SAMRAI::pdat::SideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OutersideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::SideData< TYPE >::packStream(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::SideData< TYPE >::unpackStream(), and SAMRAI::pdat::OutersideData< TYPE >::unpackStream().
void SAMRAI::pdat::SideOverlap::getSourceBoxContainer (hier::BoxContainer & src_boxes, int & normal_direction) const [virtual]
Get a BoxContainer representing the source boxes of the overlap.
The src_boxes container will be filled with side-centered source boxes of the overlap in the source coordinate space. The given normal direction is the normal in destination space on input and in source space on output.
Parameters:
[out] src_boxes
[in,out] normal_direction
Precondition:
src_boxes.empty()
normal_direction >= 0 && normal_direction < d_dst_boxes.size()
Postcondition:
normal_direction >= 0 && normal_direction < d_dst_boxes.size()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getInverseTransformation(), SAMRAI::hier::Transformation::getRotation(), TBOX_ASSERT, SAMRAI::pdat::SideGeometry::transform(), and SAMRAI::hier::Transformation::transform().
const hier::IntVector & SAMRAI::pdat::SideOverlap::getSourceOffset () const [virtual]
Return the offset between the destination and source index spaces. The destination index space is the source index space shifted by this amount.
Implements SAMRAI::hier::BoxOverlap.
References SAMRAI::hier::Transformation::getOffset().
Referenced by SAMRAI::pdat::OutersideData< TYPE >::copy(), SAMRAI::pdat::SideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OutersideData< TYPE >::getDataStreamSize(), SAMRAI::pdat::OutersideData< TYPE >::packStream(), SAMRAI::pdat::SideData< TYPE >::unpackStream(), and SAMRAI::pdat::OutersideData< TYPE >::unpackStream().
const hier::Transformation & SAMRAI::pdat::SideOverlap::getTransformation () const [virtual]
Refturn the transformation between the destination and source index spaces.
The destination index space is the source index space rotated and shifted by the returned transformation.
Returns:
The transformation.
Implements SAMRAI::hier::BoxOverlap.
Referenced by SAMRAI::pdat::SideData< TYPE >::packStream().
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/SideOverlap.h
source/SAMRAI/pdat/SideOverlap.C