SAMRAI: SAMRAI::hier::MappingConnector Class Reference
SAMRAI::hier::MappingConnector Class Reference
A container which holds overlap relationship connections between two BoxLevels.
#include <source/SAMRAI/hier/MappingConnector.h>
Public Types
enum MappingType { LOCAL, NOT_LOCAL, UNKNOWN }
Types of mappings for use in findMappingErrors() and assertMappingValidity().
Public Member Functions
MappingConnector (const tbox::Dimension &dim)
Creates an uninitialized MappingConnector object in the distributed state.
MappingConnector (const tbox::Dimension &dim, tbox::Database &restart_db)
Creates an MappingConnector which is initialized from a restart database.
MappingConnector (const MappingConnector &other)
Copy constructor.
MappingConnector (const BoxLevel &base_box_level, const BoxLevel &head_box_level, const IntVector &base_width, const BoxLevel::ParallelState parallel_state=BoxLevel::DISTRIBUTED)
Initialize a MappingConnector with no defined relationships.
~MappingConnector ()
Destructor.
MappingConnector & operator= (const MappingConnector &rhs)
Assignment operator.
MappingConnector * createLocalTranspose () const
Create and return this MappingConnector's transpose, assuming that all relationships are local (no remote neighbors).
virtual MappingConnector * createTranspose () const
Create and return this MappingConnector's transpose.
size_t findMappingErrors (MappingType map_type=UNKNOWN) const
Check if the MappingConnector has a valid mapping.
void assertMappingValidity (MappingType map_type=UNKNOWN) const
Run findMappingErrors and abort if any errors are found.
Detailed Description
A container which holds overlap relationship connections between two BoxLevels.
Member Enumeration Documentation
enum SAMRAI::hier::MappingConnector::MappingType
Types of mappings for use in findMappingErrors() and assertMappingValidity().
Enumerator:
LOCAL
NOT_LOCAL
UNKNOWN
Constructor & Destructor Documentation
SAMRAI::hier::MappingConnector::MappingConnector (const tbox::Dimension & dim) [explicit]
Creates an uninitialized MappingConnector object in the distributed state.
Parameters:
dim The dimension of the head and base BoxLevels that this object will eventually connect.
See also:
setBase()
setHead()
setWidth()
Referenced by createLocalTranspose(), and createTranspose().
SAMRAI::hier::MappingConnector::MappingConnector (const tbox::Dimension & dim, tbox::Database & restart_db)
Creates an MappingConnector which is initialized from a restart database.
Parameters:
dim The dimension of the head and base BoxLevels that this object will eventually connect.
restart_db Restart Database written by a Connector.
See also:
setBase()
setHead()
setWidth()
SAMRAI::hier::MappingConnector::MappingConnector (const MappingConnector & other)
Copy constructor.
Parameters:
[in] other
SAMRAI::hier::MappingConnector::MappingConnector (const BoxLevel & base_box_level, const BoxLevel & head_box_level, const IntVector & base_width, const BoxLevel::ParallelState parallel_state = BoxLevel::DISTRIBUTED)
Initialize a MappingConnector with no defined relationships.
The MappingConnector's relationships are initialized to a dummy state.
Parameters:
[in] base_box_level
[in] head_box_level
[in] base_width
[in] parallel_state
Precondition:
(base_box_level.getDim() == head_box_level.getDim()) && (base_box_level.getDim() == base_width.getDim())
SAMRAI::hier::MappingConnector::~MappingConnector ()
Destructor.
Member Function Documentation
MappingConnector & SAMRAI::hier::MappingConnector::operator= (const MappingConnector & rhs)
Assignment operator.
Reimplemented from SAMRAI::hier::Connector.
MappingConnector * SAMRAI::hier::MappingConnector::createLocalTranspose () const [virtual]
Create and return this MappingConnector's transpose, assuming that all relationships are local (no remote neighbors).
If any remote neighbor is found an unrecoverable assertion is thrown.
Non-periodic relationships in are simply reversed to get the transpose relationship. For each periodic relationship we create a periodic relationship incident from the unshifted head neighbor to the shifted base neighbor. This is because all relationships must be incident from a real (unshifted) Box.
Reimplemented from SAMRAI::hier::Connector.
References SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::Connector::doLocalTransposeWork(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::Connector::getHead(), and MappingConnector().
MappingConnector * SAMRAI::hier::MappingConnector::createTranspose () const [virtual]
Create and return this MappingConnector's transpose.
Similar to createLocalTranspose(), but this method allows non-local edges. Global data is required, so this method is not scalable.
Reimplemented from SAMRAI::hier::Connector.
References SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::Connector::doTransposeWork(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::Connector::getHead(), and MappingConnector().
Referenced by findMappingErrors().
size_t SAMRAI::hier::MappingConnector::findMappingErrors (MappingType map_type = UNKNOWN) const
Check if the MappingConnector has a valid mapping.
This function can be called prior to calling modify(). It is intended to check the MappingConnector(s) argument(s) in modify() to determine if it has a valid mapping. In other words, it checks to see if the mapping can be used in modify() without logic errors. It does no other checks.
Parameters:
[in] map_type LOCAL means assume the mapping is local. NOT_LOCAL means the mapping is not local. UNKNOWN means find out whether the map is local or not (communication required) and act accordingly.
Returns:
number of errors found.
References SAMRAI::tbox::SAMRAI_MPI::Allreduce(), SAMRAI::hier::Connector::begin(), SAMRAI::hier::BoxLevelConnectorUtils::computeExternalParts(), createTranspose(), SAMRAI::hier::Connector::end(), SAMRAI::hier::Connector::format(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxLevel::getBoxStrict(), SAMRAI::hier::Connector::getConnectorWidth(), SAMRAI::hier::BoxLevel::getGlobalizedVersion(), SAMRAI::hier::Connector::getHead(), SAMRAI::hier::Connector::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::hier::Connector::hasNeighborSet(), SAMRAI::hier::Box::isSpatiallyEqual(), LOCAL, MPI_INT, MPI_MAX, NOT_LOCAL, SAMRAI::tbox::perr, SAMRAI::hier::BoxContainer::realBegin(), SAMRAI::hier::BoxContainer::realEnd(), and UNKNOWN.
Referenced by assertMappingValidity().
void SAMRAI::hier::MappingConnector::assertMappingValidity (MappingType map_type = UNKNOWN) const
Run findMappingErrors and abort if any errors are found.
Parameters:
[in] map_type LOCAL means assume the mapping is local. NOT_LOCAL means the mapping is not local. UNKNOWN means find out whether the map is local or not (communication required) and act accordingly.
References findMappingErrors(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::Connector::format(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::Connector::getHead(), SAMRAI::tbox::perr, and TBOX_ERROR.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/MappingConnector.h
source/SAMRAI/hier/MappingConnector.C