SAMRAI: SAMRAI::xfer::BoxGeometryVariableFillPattern Class Reference
SAMRAI::xfer::BoxGeometryVariableFillPattern Class Reference
Class BoxGeometryVariableFillPattern is a default implementation of the abstract base class VariableFillPattern.
#include <source/SAMRAI/xfer/BoxGeometryVariableFillPattern.h>
Public Member Functions
BoxGeometryVariableFillPattern ()
Default constructor.
virtual ~BoxGeometryVariableFillPattern ()
Destructor.
boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &dst_patch_box, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation) const
Calculate overlap between the destination and source geometries using the geometries' own overlap calculation methods.
boost::shared_ptr
< hier::BoxOverlap > computeFillBoxesOverlap (const hier::BoxContainer &fill_boxes, const hier::BoxContainer &node_fill_boxes, const hier::Box &patch_box, const hier::Box &data_box, const hier::PatchDataFactory &pdf) const
const hier::IntVector & getStencilWidth ()
Implementation of interface to get stencil width of a VariableFillPattern.
const std::string & getPatternName () const
Returns a string name identifier "BOX_GEOMETRY_FILL_PATTERN".
Detailed Description
Class BoxGeometryVariableFillPattern is a default implementation of the abstract base class VariableFillPattern.
It is used to calculate overlaps that consist of the full intersection between source and destination patches, including all ghost regions. If no VariableFillPattern object is provided when a refine operation is registered with a RefineAlgorithm, this class is used by default.
See also:
RefineAlgorithm
Constructor & Destructor Documentation
SAMRAI::xfer::BoxGeometryVariableFillPattern::BoxGeometryVariableFillPattern ()
Default constructor.
SAMRAI::xfer::BoxGeometryVariableFillPattern::~BoxGeometryVariableFillPattern () [virtual]
Destructor.
Member Function Documentation
boost::shared_ptr<hier::BoxOverlap> SAMRAI::xfer::BoxGeometryVariableFillPattern::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & dst_patch_box, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation) const [inline, virtual]
Calculate overlap between the destination and source geometries using the geometries' own overlap calculation methods.
The intersection between the given dst_geometry and src_geometry will be calculated according to the properties of those geometries.
Parameters:
[in] dst_geometry geometry object for destination box
[in] src_geometry geometry object for source box
[in] dst_patch_box box for the destination patch
[in] src_mask the source mask, the box resulting from transforming the source box
[in] fill_box the box to be filled
[in] overwrite_interior controls whether or not to include the destination box interior in the overlap.
[in] transformation the transformation from source to destination index space.
Returns:
boost::shared_ptr to the calculated overlap object
Precondition:
dst_patch_box.getDim() == src_mask.getDim()
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::BoxGeometry::calculateOverlap(), NULL_USE, and TBOX_ASSERT_OBJDIM_EQUALITY2.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::xfer::BoxGeometryVariableFillPattern::computeFillBoxesOverlap (const hier::BoxContainer & fill_boxes, const hier::BoxContainer & node_fill_boxes, const hier::Box & patch_box, const hier::Box & data_box, const hier::PatchDataFactory & pdf) const [virtual]
Computes a BoxOverlap object which defines the space to be filled by a refinement operation. For this implementation, that space is the intersection between fill_boxes (computed by the RefineSchedule) and data_box, which specifies the extent of the destination data. The patch data factory is used to compute the overlap with the appropriate data centering, consistent with the centering of the data to be filled.
Parameters:
[in] fill_boxes list representing the all of the space on a patch or its ghost region that may be filled by a refine operator (cell-centered representation)
[in] node_fill_boxes node-centered representation of fill_boxes
[in] patch_box box representing the patch where a refine operator will fill data. (cell-centered representation)
[in] data_box box representing the full extent of the region covered by a patch data object, including all ghosts (cell-centered representation)
[in] pdf patch data factory for the data that is to be filled
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::PatchDataFactory::getBoxGeometry(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::intersectBoxes(), and NULL_USE.
const hier::IntVector & SAMRAI::xfer::BoxGeometryVariableFillPattern::getStencilWidth () [virtual]
Implementation of interface to get stencil width of a VariableFillPattern.
For this class BoxGeometryVariableFillPattern, this method should never be called, since overlaps are computed based on BoxGeometry objects and not on any stencil. An error will result if this method is invoked.
Implements SAMRAI::xfer::VariableFillPattern.
References SAMRAI::hier::IntVector::getZero(), and TBOX_ERROR.
const std::string& SAMRAI::xfer::BoxGeometryVariableFillPattern::getPatternName () const [inline, virtual]
Returns a string name identifier "BOX_GEOMETRY_FILL_PATTERN".
Implements SAMRAI::xfer::VariableFillPattern.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/BoxGeometryVariableFillPattern.h
source/SAMRAI/xfer/BoxGeometryVariableFillPattern.C