SAMRAI: SAMRAI::mesh::PartitioningParams Class Reference
SAMRAI::mesh::PartitioningParams Class Reference
Light weight class holding parameters generally used in partitioning.
#include <source/SAMRAI/mesh/PartitioningParams.h>
Public Member Functions
PartitioningParams (const hier::BaseGridGeometry &grid_geometry, const hier::IntVector &ratio_to_level_zero, const hier::IntVector &min_size, const hier::IntVector &max_size, const hier::IntVector &bad_interval, const hier::IntVector &cut_factor, double flexible_load_tol)
PartitioningParams (const PartitioningParams &other)
double getMinLoad () const
const hier::IntVector & getMinBoxSize () const
const hier::IntVector & getMaxBoxSize () const
const hier::BoxContainer & getDomainBoxes (const hier::BlockId &bid) const
const hier::IntVector & getBadInterval () const
const hier::IntVector & getCutFactor () const
const tbox::Dimension & getDim () const
const double & getFlexibleLoadTol () const
const double & getLoadComparisonTol () const
Friends
std::ostream & operator<< (std::ostream &os, const PartitioningParams &pp)
Detailed Description
Light weight class holding parameters generally used in partitioning.
Constructor & Destructor Documentation
SAMRAI::mesh::PartitioningParams::PartitioningParams (const hier::BaseGridGeometry & grid_geometry, const hier::IntVector & ratio_to_level_zero, const hier::IntVector & min_size, const hier::IntVector & max_size, const hier::IntVector & bad_interval, const hier::IntVector & cut_factor, double flexible_load_tol)
References SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), and SAMRAI::hier::BaseGridGeometry::getNumberBlocks().
SAMRAI::mesh::PartitioningParams::PartitioningParams (const PartitioningParams & other)
Member Function Documentation
double SAMRAI::mesh::PartitioningParams::getMinLoad () const [inline]
References SAMRAI::hier::IntVector::getProduct().
Referenced by SAMRAI::mesh::BoxTransitSet::adjustLoad().
const hier::IntVector& SAMRAI::mesh::PartitioningParams::getMinBoxSize () const [inline]
Referenced by SAMRAI::mesh::VoucherTransitLoad::adjustLoad(), SAMRAI::mesh::BoxTransitSet::adjustLoad(), and SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes().
const hier::IntVector& SAMRAI::mesh::PartitioningParams::getMaxBoxSize () const [inline]
Referenced by SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes().
const hier::BoxContainer& SAMRAI::mesh::PartitioningParams::getDomainBoxes (const hier::BlockId & bid) const [inline]
Referenced by SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), and SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes().
const hier::IntVector& SAMRAI::mesh::PartitioningParams::getBadInterval () const [inline]
Referenced by SAMRAI::mesh::BalanceBoxBreaker::breakOffLoad(), and SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes().
const hier::IntVector& SAMRAI::mesh::PartitioningParams::getCutFactor () const [inline]
Referenced by SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes().
const tbox::Dimension& SAMRAI::mesh::PartitioningParams::getDim () const [inline]
References SAMRAI::hier::IntVector::getDim().
Referenced by SAMRAI::mesh::BoxTransitSet::getFromMessageStream().
const double& SAMRAI::mesh::PartitioningParams::getFlexibleLoadTol () const [inline]
const double& SAMRAI::mesh::PartitioningParams::getLoadComparisonTol () const [inline]
Referenced by SAMRAI::mesh::VoucherTransitLoad::adjustLoad(), SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps(), SAMRAI::mesh::BalanceUtilities::compareLoads(), and SAMRAI::mesh::VoucherTransitLoad::insertAll().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const PartitioningParams & pp) [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/mesh/PartitioningParams.h
source/SAMRAI/mesh/PartitioningParams.C