SAMRAI: SAMRAI::solv::LocationIndexRobinBcCoefs Class Reference
SAMRAI::solv::LocationIndexRobinBcCoefs Class Reference
A prefabricated Robin boundary condition coefficients for coefficients that are entirely specified by the boundary box location index.
#include <source/SAMRAI/solv/LocationIndexRobinBcCoefs.h>
Public Member Functions
LocationIndexRobinBcCoefs (const tbox::Dimension &dim, const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db=boost::shared_ptr< tbox::Database >())
Constructor using input database.
virtual ~LocationIndexRobinBcCoefs ()
Destructor.
void setBcCoefs (const boost::shared_ptr< pdat::ArrayData< double > > &acoef_data, const boost::shared_ptr< pdat::ArrayData< double > > &bcoef_data, const boost::shared_ptr< pdat::ArrayData< double > > &gcoef_data, const boost::shared_ptr< hier::Variable > &variable, const hier::Patch &patch, const hier::BoundaryBox &bdry_box, double fill_time=0.0) const
Function to fill arrays of Robin boundary condition coefficients at a patch boundary.
hier::IntVector numberOfExtensionsFillable () const
void setBoundaryValue (int location_index, double value)
Set the boundary value at a given location index.
void setBoundarySlope (int location_index, double slope)
Set the boundary slope at a given location index.
void setRawCoefficients (int location_index, double a, double b, double g)
Set the values of coefficients a and g at a given location index.
void getCoefficients (int location_index, double &a, double &b, double &g) const
Access coefficients.
const std::string & getObjectName () const
Get the name of this object.
LocationIndexRobinBcCoefs & operator= (const LocationIndexRobinBcCoefs &r)
Assignment operator.
Detailed Description
A prefabricated Robin boundary condition coefficients for coefficients that are entirely specified by the boundary box location index.
This implementation of the strategy class RobinBcCoefStrategy may be used when your Robin boundary condition coefficients are completely determined by the location index of the boundary box.
Before this class is used in to provide the boundary condition coefficients, you must specify what boundary conditions to associate with what location index. Methods for specifying these are setBoundaryValue(), setBoundarySlope() and setRawCoefficients(). The first two are for Dirichlet and Neumann boundary conditions, respectively. If the boundary condition is the more general Robin boundary condition, the third function should be used to set the coefficients a and g directly (see RobinBcCoefStrategy) for the meanings of a and g.
Input Parameters
Definitions:
boundary_N You can specify the boundary conditions for any location index through the input database. One line is required for each location index. The input parameters are "boundary_N", where N is the index of the location. Each parameter must be a std::string array so that all boundary types can be accomodated the same way. The first std::string must be one of "value", "slope" or "coefficients". If the std::string is "value" or "slope" the next std::string is the value you want to set. If the first std::string is "coefficients", the next two strings specify the values of a and b.
Details:
parameter
type
default
range
opt/req
behavior on restart
boundary_N
array of strings
none
"value", "gval"; "slope", "gval"; "coefficients", "aVal", "bVal"
req
Not written to restart. Value in input db used.
Constructor & Destructor Documentation
SAMRAI::solv::LocationIndexRobinBcCoefs::LocationIndexRobinBcCoefs (const tbox::Dimension & dim, const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db = boost::shared_ptr<tbox::Database>())
Constructor using input database.
Precondition:
input_db
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
SAMRAI::solv::LocationIndexRobinBcCoefs::~LocationIndexRobinBcCoefs () [virtual]
Destructor.
Member Function Documentation
void SAMRAI::solv::LocationIndexRobinBcCoefs::setBcCoefs (const boost::shared_ptr< pdat::ArrayData< double > > & acoef_data, const boost::shared_ptr< pdat::ArrayData< double > > & bcoef_data, const boost::shared_ptr< pdat::ArrayData< double > > & gcoef_data, const boost::shared_ptr< hier::Variable > & variable, const hier::Patch & patch, const hier::BoundaryBox & bdry_box, double fill_time = 0.0) const [virtual]
Function to fill arrays of Robin boundary condition coefficients at a patch boundary.
This implementation of the virtual function RobinBcCoefStrategy::setBcCoefs() fills the coefficient arrays with constant values set according to the location index of the boundary box.
Parameters:
acoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box. If this is a null pointer, then the calling function is not interested in a, and you can disregard it.
bcoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box.
gcoef_data boundary coefficient data. This is defined to include index range for the boundary faces on the boundary box bdry_box.
variable variable to set the coefficients for.
patch patch requiring bc coefficients
bdry_box boundary box showing where on the boundary the coefficient data is needed.
fill_time Solution time corresponding to filling, for use when coefficients are time-dependent.
Precondition:
(d_dim == patch.getDim()) && (d_dim == bdry_box.getDim())
(!acoef_data || (d_dim == acoef_data.getDim())
(!bcoef_data || (d_dim == acoef_data.betDim())
(!gcoef_data || (d_dim == acoef_data.getDim())
(bdry_box.getLocationIndex() >= 0) && (bdry_box.getLocationIndex() < 2 * d_dim.getValue())
Implements SAMRAI::solv::RobinBcCoefStrategy.
References SAMRAI::hier::BoundaryBox::getLocationIndex(), SAMRAI::tbox::Dimension::getValue(), NULL_USE, TBOX_ASSERT, TBOX_ASSERT_DIM_OBJDIM_EQUALITY1, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY2.
hier::IntVector SAMRAI::solv::LocationIndexRobinBcCoefs::numberOfExtensionsFillable () const [virtual]
Implements SAMRAI::solv::RobinBcCoefStrategy.
void SAMRAI::solv::LocationIndexRobinBcCoefs::setBoundaryValue (int location_index, double value) [inline]
Set the boundary value at a given location index.
Parameters:
location_index Set coefficients for this index.
value Boundary value at location_index.
Precondition:
(location_index >= 0) && (location_index < 2 * d_dim.getValue())
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ERROR.
void SAMRAI::solv::LocationIndexRobinBcCoefs::setBoundarySlope (int location_index, double slope) [inline]
Set the boundary slope at a given location index.
Parameters:
location_index Set coefficients for this index.
slope Boundary slope at location_index.
Precondition:
(location_index >= 0) && (location_index < 2 * d_dim.getValue())
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ERROR.
void SAMRAI::solv::LocationIndexRobinBcCoefs::setRawCoefficients (int location_index, double a, double b, double g) [inline]
Set the values of coefficients a and g at a given location index.
See RobinBcCoefStrategy for the definitions of coefficients a and g.
If the boundary condition is neither Dirichlet nor Neumann (a general Robin boundary condition), use this function to set the values of the bc coefficients.
Parameters:
location_index Set coefficients for this index.
a Value of coefficient a at given location index.
b Value of coefficient b at given location index.
g Value of coefficient g at given location index.
Precondition:
(location_index >= 0) && (location_index < 2 * d_dim.getValue())
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ERROR.
void SAMRAI::solv::LocationIndexRobinBcCoefs::getCoefficients (int location_index, double & a, double & b, double & g) const [inline]
Access coefficients.
Parameters:
location_index Set coefficients for this index.
a Value of coefficient a at given location index.
b Value of coefficient b at given location index.
g Value of coefficient g at given location index.
Precondition:
(location_index >= 0) && (location_index < 2 * d_dim.getValue())
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ERROR.
const std::string& SAMRAI::solv::LocationIndexRobinBcCoefs::getObjectName () const [inline]
Get the name of this object.
Returns:
The name of this object.
LocationIndexRobinBcCoefs & SAMRAI::solv::LocationIndexRobinBcCoefs::operator= (const LocationIndexRobinBcCoefs & r)
Assignment operator.
References SAMRAI::tbox::Dimension::getValue().
The documentation for this class was generated from the following files:
source/SAMRAI/solv/LocationIndexRobinBcCoefs.h
source/SAMRAI/solv/LocationIndexRobinBcCoefs.C