SAMRAI: SAMRAI::pdat::NodeDataFactory< TYPE > Class Template Reference
SAMRAI::pdat::NodeDataFactory< TYPE > Class Template Reference
#include <source/SAMRAI/pdat/NodeDataFactory.h>
Public Member Functions
NodeDataFactory (int depth, const hier::IntVector &ghosts, bool fine_boundary_represents_var)
virtual ~NodeDataFactory ()
virtual boost::shared_ptr
< hier::PatchDataFactory > cloneFactory (const hier::IntVector &ghosts)
Abstract virtual function to clone a patch data factory.
virtual boost::shared_ptr
< hier::PatchData > allocate (const hier::Patch &patch) const
virtual boost::shared_ptr
< hier::BoxGeometry > getBoxGeometry (const hier::Box &box) const
int getDepth () const
virtual size_t getSizeOfMemory (const hier::Box &box) const
bool fineBoundaryRepresentsVariable () const
bool dataLivesOnPatchBorder () const
bool validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > &dst_pdf) const
Detailed Description
template<class TYPE>
class SAMRAI::pdat::NodeDataFactory< TYPE >
Class NodeDataFactory is a factory class used to allocate new instances of NodeData objects. It is a subclass of the patch data factory class and node data is a subclass of patch data. Both the factory and data classes are templated on the type of the contained object (e.g., double or int).
See also:
pdat::NodeData
pdat::PatchDataFactory
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::NodeDataFactory< TYPE >::NodeDataFactory (int depth, const hier::IntVector & ghosts, bool fine_boundary_represents_var) [inline]
The constructor for the node data factory class. The ghost cell width, depth (number of components), and fine boundary representation arguments give the defaults for all edge data objects created with this factory. See the NodeVariable<TYPE> class header file for more information.
Precondition:
depth > 0
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), and TBOX_ASSERT.
template<class TYPE > SAMRAI::pdat::NodeDataFactory< TYPE >::~NodeDataFactory () [inline, virtual]
Virtual destructor for the node data factory class.
Member Function Documentation
template<class TYPE > boost::shared_ptr< hier::PatchDataFactory > SAMRAI::pdat::NodeDataFactory< TYPE >::cloneFactory (const hier::IntVector & ghosts) [inline, virtual]
Abstract virtual function to clone a patch data factory.
This will return a new instantiation of the abstract factory with the same properties. The properties of the cloned factory can then be changed without modifying the original.
Parameters:
ghosts default ghost cell width for concrete classes created from the factory.
Precondition:
getDim() == ghosts.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::PatchData > SAMRAI::pdat::NodeDataFactory< TYPE >::allocate (const hier::Patch & patch) const [inline, virtual]
Virtual factory function to allocate a concrete node data object. The default information about the object (e.g., ghost cell width) is taken from the factory.
Precondition:
getDim() == patch.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::PatchDataFactory::d_ghosts, SAMRAI::hier::Patch::getBox(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > boost::shared_ptr< hier::BoxGeometry > SAMRAI::pdat::NodeDataFactory< TYPE >::getBoxGeometry (const hier::Box & box) const [inline, virtual]
Allocate the box geometry object associated with the patch data. This information will be used in the computation of intersections and data dependencies between objects.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::hier::PatchDataFactory::d_ghosts, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > int SAMRAI::pdat::NodeDataFactory< TYPE >::getDepth () const [inline]
Get the depth (number of components). This is the depth that will be used in the instantiation of node data objects.
template<class TYPE > size_t SAMRAI::pdat::NodeDataFactory< TYPE >::getSizeOfMemory (const hier::Box & box) const [inline, virtual]
Calculate the amount of memory needed to store the node data object, including object data and dynamically allocated data.
Precondition:
getDim() == box.getDim()
Implements SAMRAI::hier::PatchDataFactory.
References SAMRAI::tbox::MemoryUtilities::align(), SAMRAI::hier::PatchDataFactory::d_ghosts, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > bool SAMRAI::pdat::NodeDataFactory< TYPE >::fineBoundaryRepresentsVariable () const [inline, virtual]
Return a boolean value indicating how data for the node quantity will be treated on coarse-fine interfaces. This value is passed into the constructor. See the NodeVariable<TYPE> class header file for more information.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::NodeDataFactory< TYPE >::dataLivesOnPatchBorder () const [inline, virtual]
Return true since the node data index space extends beyond the interior of patches. That is, node data lives on patch borders.
Implements SAMRAI::hier::PatchDataFactory.
template<class TYPE > bool SAMRAI::pdat::NodeDataFactory< TYPE >::validCopyTo (const boost::shared_ptr< hier::PatchDataFactory > & dst_pdf) const [inline]
Return whether it is valid to copy this NodeDataFactory to the supplied destination patch data factory. It will return true if dst_pdf is NodeDataFactory or OuternodeDataFactory, false otherwise.
Precondition:
getDim() == dst_pdf->getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/NodeDataFactory.h
source/SAMRAI/pdat/NodeDataFactory.C