SAMRAI: SAMRAI::hier::BoxLevelStatistics Class Reference
SAMRAI::hier::BoxLevelStatistics Class Reference
A utility for writing out various statistics of Boxes.
#include <source/SAMRAI/hier/BoxLevelStatistics.h>
Public Member Functions
BoxLevelStatistics (const BoxLevel &box_level)
Constructor.
void printBoxStats (std::ostream &os, const std::string &border) const
Print out local and globally reduced statistics on the Boxes.
Detailed Description
A utility for writing out various statistics of Boxes.
Constructor & Destructor Documentation
SAMRAI::hier::BoxLevelStatistics::BoxLevelStatistics (const BoxLevel & box_level) [explicit]
Constructor.
Compute and store statistics for the given BoxLevel. The statistics reflects the current BoxLevel state and can be printed out afterwards. All processes in the BoxLevel's SAMRAI_MPI must call this constructor because it requires collective communication.
Parameters:
[in] box_level BoxLevel to compute statistics for.
Precondition:
box_level.isInitialized()
References SAMRAI::hier::BoxLevel::isInitialized(), and TBOX_ERROR.
Member Function Documentation
void SAMRAI::hier::BoxLevelStatistics::printBoxStats (std::ostream & os, const std::string & border) const
Print out local and globally reduced statistics on the Boxes.
Parameters:
[in,out] os The output stream
[in] border A string to print at the start of every line in the output.
References SAMRAI::tbox::SAMRAI_MPI::getSize(), and SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::hier::operator<<().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxLevelStatistics.h
source/SAMRAI/hier/BoxLevelStatistics.C