SAMRAI: SAMRAI::pdat::ArrayDataAccess Class Reference
SAMRAI::pdat::ArrayDataAccess Class Reference
Utility for wrapping data from ArrayData class in an MDA_Access or MDA_AccessConst object.
#include <source/SAMRAI/pdat/ArrayDataAccess.h>
Static Public Member Functions
template<int DIM, class TYPE >
static MDA_Access< TYPE, DIM,
MDA_OrderColMajor< DIM > > access (ArrayData< TYPE > &array_data, int depth=0)
Create an MDA_Access version of an ArrayData object.
template<int DIM, class TYPE >
static MDA_AccessConst< TYPE,
DIM, MDA_OrderColMajor< DIM > > access (const ArrayData< TYPE > &array_data, int depth=0)
Create an MDA_AccessConst version of a const ArrayData object.
Detailed Description
Utility for wrapping data from ArrayData class in an MDA_Access or MDA_AccessConst object.
This, and other classes in the folder array_access are meant only for certain SAMRAI development efforts. Please do not use in user code.
Member Function Documentation
template<int DIM, class TYPE > static MDA_Access<TYPE, DIM, MDA_OrderColMajor<DIM> > SAMRAI::pdat::ArrayDataAccess::access (ArrayData< TYPE > & array_data, int depth = 0) [inline, static]
Create an MDA_Access version of an ArrayData object.
References SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
template<int DIM, class TYPE > static MDA_AccessConst<TYPE, DIM, MDA_OrderColMajor<DIM> > SAMRAI::pdat::ArrayDataAccess::access (const ArrayData< TYPE > & array_data, int depth = 0) [inline, static]
Create an MDA_AccessConst version of a const ArrayData object.
References SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
The documentation for this class was generated from the following file:
source/SAMRAI/pdat/ArrayDataAccess.h