SAMRAI: SAMRAI::hier::LocalId Class Reference
SAMRAI::hier::LocalId Class Reference
Generic identifier for identifying things on the local process.
#include <source/SAMRAI/hier/LocalId.h>
Public Member Functions
LocalId ()
Default constructor.
LocalId (const LocalId &other)
Copy constructor.
LocalId (const int &value)
Construct from a numerical value.
~LocalId ()
Default constructor.
LocalId & operator= (const LocalId &rhs)
Assignment operator.
LocalId & operator= (const int &rhs)
Assignment operator.
int & getValue ()
Access the numerical value.
const int & getValue () const
Access the numerical value.
bool isValid () const
Whether value is a valid one (not equal to getInvalidId()).
Numerical operations.
LocalId operator++ ()
Pre-increment iterator.
LocalId operator++ (int)
Post-increment iterator.
LocalId operator+ (const LocalId &rhs) const
Addition.
LocalId operator- (const LocalId &rhs) const
Subtraction.
LocalId operator* (const LocalId &rhs) const
Multiplication.
LocalId operator/ (const LocalId &rhs) const
Division.
LocalId operator% (const LocalId &rhs) const
Modulus.
LocalId & operator+= (const LocalId &rhs)
Addition and assignment.
LocalId & operator-= (const LocalId &rhs)
Subtraction and assignment.
LocalId operator+ (const int &rhs) const
Integer addition.
LocalId operator- (const int &rhs) const
Integer subtraction.
LocalId operator* (const int &rhs) const
Integer multiplication.
LocalId operator/ (const int &rhs) const
Integer division.
LocalId operator% (const int &rhs) const
Integer modulus.
LocalId & operator+= (const int &rhs)
Integer addition and assignment.
LocalId & operator-= (const int &rhs)
Integer subtraction and assignment.
Comparison with another LocalId.
bool operator== (const LocalId &rhs) const
Equality operator.
bool operator!= (const LocalId &rhs) const
Inequality operator.
bool operator< (const LocalId &rhs) const
Less-than operator.
bool operator> (const LocalId &rhs) const
Greater-than operator.
bool operator<= (const LocalId &rhs) const
Less-than-or-equal-to operator.
bool operator>= (const LocalId &rhs) const
Greater-thanor-equal-to operator.
Comparison with an integer.
bool operator== (const int &rhs) const
Equality operator.
bool operator!= (const int &rhs) const
Inequality operator.
bool operator< (const int &rhs) const
Less-than operator.
bool operator> (const int &rhs) const
Greater-than operator.
bool operator<= (const int &rhs) const
Less-than-or-equal-to operator.
bool operator>= (const int &rhs) const
Greater-thanor-equal-to operator.
Static Public Member Functions
static const LocalId & getZero ()
Get the LocalId with a numerical value of zero.
static const LocalId & getInvalidId ()
Get the designated invalid value for this class.
Friends
std::ostream & operator<< (std::ostream &co, const LocalId &r)
Format and insert object into a stream.
Detailed Description
Generic identifier for identifying things on the local process.
The LocalId can be combined with a process rank, as is done in GlobalId, to create global identifiers.
Comparison operators are provided to define the sorted ordering of objects.
Constructor & Destructor Documentation
SAMRAI::hier::LocalId::LocalId ()
Default constructor.
Referenced by operator%(), operator*(), operator+(), operator++(), operator-(), and operator/().
SAMRAI::hier::LocalId::LocalId (const LocalId & other)
Copy constructor.
SAMRAI::hier::LocalId::LocalId (const int & value) [explicit]
Construct from a numerical value.
This method is explicit to prevent automatic conversion.
SAMRAI::hier::LocalId::~LocalId ()
Default constructor.
Member Function Documentation
LocalId& SAMRAI::hier::LocalId::operator= (const LocalId & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs
Returns:
*this
LocalId& SAMRAI::hier::LocalId::operator= (const int & rhs) [inline]
Assignment operator.
Parameters:
[in] rhs
Returns:
*this
int& SAMRAI::hier::LocalId::getValue () [inline]
Access the numerical value.
Referenced by SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), isValid(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::hier::BoxId::putToIntBuffer(), SAMRAI::hier::BoxId::putToMessageStream(), SAMRAI::hier::Patch::putToRestart(), and SAMRAI::hier::BoxNeighborhoodCollection::putToRestart().
const int& SAMRAI::hier::LocalId::getValue () const [inline]
Access the numerical value.
bool SAMRAI::hier::LocalId::isValid () const [inline]
Whether value is a valid one (not equal to getInvalidId()).
References getValue().
Referenced by SAMRAI::hier::BoxLevel::addBox(), and SAMRAI::hier::operator<<().
static const LocalId& SAMRAI::hier::LocalId::getZero () [inline, static]
Get the LocalId with a numerical value of zero.
Referenced by SAMRAI::hier::BoxLevel::addBox().
static const LocalId& SAMRAI::hier::LocalId::getInvalidId () [inline, static]
Get the designated invalid value for this class.
Referenced by SAMRAI::hier::BoxId::isValid().
LocalId SAMRAI::hier::LocalId::operator++ () [inline]
Pre-increment iterator.
Pre-increment increments the value and returns the incremented state.
LocalId SAMRAI::hier::LocalId::operator++ (int) [inline]
Post-increment iterator.
Post-increment saves the value, increment it and returns an object with the saved value.
References LocalId().
LocalId SAMRAI::hier::LocalId::operator+ (const LocalId & rhs) const [inline]
Addition.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator- (const LocalId & rhs) const [inline]
Subtraction.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator* (const LocalId & rhs) const [inline]
Multiplication.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator/ (const LocalId & rhs) const [inline]
Division.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator% (const LocalId & rhs) const [inline]
Modulus.
Parameters:
[in] rhs
References LocalId().
LocalId& SAMRAI::hier::LocalId::operator+= (const LocalId & rhs) [inline]
Addition and assignment.
Parameters:
[in] rhs
LocalId& SAMRAI::hier::LocalId::operator-= (const LocalId & rhs) [inline]
Subtraction and assignment.
Parameters:
[in] rhs
LocalId SAMRAI::hier::LocalId::operator+ (const int & rhs) const [inline]
Integer addition.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator- (const int & rhs) const [inline]
Integer subtraction.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator* (const int & rhs) const [inline]
Integer multiplication.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator/ (const int & rhs) const [inline]
Integer division.
Parameters:
[in] rhs
References LocalId().
LocalId SAMRAI::hier::LocalId::operator% (const int & rhs) const [inline]
Integer modulus.
Parameters:
[in] rhs
References LocalId().
LocalId& SAMRAI::hier::LocalId::operator+= (const int & rhs) [inline]
Integer addition and assignment.
Parameters:
[in] rhs
LocalId& SAMRAI::hier::LocalId::operator-= (const int & rhs) [inline]
Integer subtraction and assignment.
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator== (const LocalId & rhs) const [inline]
Equality operator.
All comparison operators compare the numerical value.
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator!= (const LocalId & rhs) const [inline]
Inequality operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator< (const LocalId & rhs) const [inline]
Less-than operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator> (const LocalId & rhs) const [inline]
Greater-than operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator<= (const LocalId & rhs) const [inline]
Less-than-or-equal-to operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator>= (const LocalId & rhs) const [inline]
Greater-thanor-equal-to operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator== (const int & rhs) const [inline]
Equality operator.
All comparison operators compare the numerical value.
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator!= (const int & rhs) const [inline]
Inequality operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator< (const int & rhs) const [inline]
Less-than operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator> (const int & rhs) const [inline]
Greater-than operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator<= (const int & rhs) const [inline]
Less-than-or-equal-to operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
bool SAMRAI::hier::LocalId::operator>= (const int & rhs) const [inline]
Greater-thanor-equal-to operator.
See note on comparison for operator==(const LocalId&);
Parameters:
[in] rhs
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & co, const LocalId & r) [friend]
Format and insert object into a stream.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/LocalId.h
source/SAMRAI/hier/LocalId.C