SAMRAI: SAMRAI::math::PatchNodeDataOpsComplex Class Reference
SAMRAI::math::PatchNodeDataOpsComplex Class Reference
#include <source/SAMRAI/math/PatchNodeDataOpsComplex.h>
Public Member Functions
PatchNodeDataOpsComplex ()
virtual ~PatchNodeDataOpsComplex ()
void copyData (const boost::shared_ptr< pdat::NodeData< dcomplex > > &dst, const boost::shared_ptr< pdat::NodeData< dcomplex > > &src, const hier::Box &box) const
void swapData (const boost::shared_ptr< hier::Patch > &patch, const int data1_id, const int data2_id) const
void printData (const boost::shared_ptr< pdat::NodeData< dcomplex > > &data, const hier::Box &box, std::ostream &s=tbox::plog) const
void setToScalar (const boost::shared_ptr< pdat::NodeData< dcomplex > > &dst, const dcomplex &alpha, const hier::Box &box) const
Detailed Description
Class PatchNodeDataOpsComplex provides a collection of operations that may be used to manipulate complex node-centered patch data. The operations include basic arithmetic and norms. With the assertion of a few basic routines, this class inherits its interface (and thus its functionality) from the base classes PatchNodeDataBasicOps, PatchNodeDataNormOpsComplex from which it is derived. The name of each of these base classes is indicative of the set of node-centered patch data operations that it provides.
A similar set of operations is implemented for real (double and float) and integer patch data in the classes PatchNodeDataOpsReal and PatchNodeDataOpsInteger, repsectively.
See also:
PatchNodeDataBasicOps
PatchNodeDataNormOpsComplex
Constructor & Destructor Documentation
SAMRAI::math::PatchNodeDataOpsComplex::PatchNodeDataOpsComplex ()
Empty constructor and destructor.
SAMRAI::math::PatchNodeDataOpsComplex::~PatchNodeDataOpsComplex () [virtual]
Member Function Documentation
void SAMRAI::math::PatchNodeDataOpsComplex::copyData (const boost::shared_ptr< pdat::NodeData< dcomplex > > & dst, const boost::shared_ptr< pdat::NodeData< dcomplex > > & src, const hier::Box & box) const [inline]
Copy dst data to src data over given box.
Precondition:
dst && src
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::NodeGeometry::toNodeBox().
Referenced by SAMRAI::math::HierarchyNodeDataOpsComplex::copyData().
void SAMRAI::math::PatchNodeDataOpsComplex::swapData (const boost::shared_ptr< hier::Patch > & patch, const int data1_id, const int data2_id) const
Swap pointers for patch data objects. Objects are checked for consistency of depth, box, and ghost box.
Precondition:
patch
patch->getPatchData(data1_id) is actually a boost::shared_ptr<pdat::NodeData<dcomplex> >
patch->getPatchData(data2_id) is actually a boost::shared_ptr<pdat::NodeData<dcomplex> >
patch->getPatchData(data1_id)->getDepth() == patch->getPatchData(data2_id)->getDepth()
patch->getPatchData(data1_id)->getBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getBox())
patch->getPatchData(data1_id)->getGhostBox().isSpatiallyEqual(patch->getPatchData(data2_id)->getGhostBox())
References BOOST_CAST, and TBOX_ASSERT.
Referenced by SAMRAI::math::HierarchyNodeDataOpsComplex::swapData().
void SAMRAI::math::PatchNodeDataOpsComplex::printData (const boost::shared_ptr< pdat::NodeData< dcomplex > > & data, const hier::Box & box, std::ostream & s = tbox::plog) const
Print data entries over given box to given output stream.
Precondition:
data
data->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyNodeDataOpsComplex::printData().
void SAMRAI::math::PatchNodeDataOpsComplex::setToScalar (const boost::shared_ptr< pdat::NodeData< dcomplex > > & dst, const dcomplex & alpha, const hier::Box & box) const [inline]
Initialize data to given scalar over given box.
Precondition:
dst
dst->getDim() == box.getDim()
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::math::HierarchyNodeDataOpsComplex::setToScalar().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchNodeDataOpsComplex.h
source/SAMRAI/math/PatchNodeDataOpsComplex.C