SAMRAI: SAMRAI::algs::PatchBoundaryEdgeSum Class Reference
SAMRAI::algs::PatchBoundaryEdgeSum Class Reference
Class PatchBoundaryEdgeSum provides operations summing edge data values at edges that are shared by multiple patches on a single level. Note that this utility only works on a SINGLE patch level, not on a multiple levels in an AMR patch hierarchy like the PatchBoundaryNodeSum class. Unlike node data, edge data at coarse-fine boundaries are not co-located, so the sum operation is not clearly defined.
#include <source/SAMRAI/algs/PatchBoundaryEdgeSum.h>
Public Member Functions
PatchBoundaryEdgeSum (const std::string &object_name)
Constructor initializes object to default (mostly undefined) state.
~PatchBoundaryEdgeSum ()
Destructor for the schedule releases all internal storage.
void registerSum (int edge_data_id)
Register edge data with given patch data identifier for summing.
void setupSum (const boost::shared_ptr< hier::PatchLevel > &level)
Set up summation operations for edge data across shared edges on a single level.
void computeSum () const
Compute sum of edge values at each shared edge and replace each such edge value with the corresponding sum.
const std::string & getObjectName () const
Returns the object name.
Static Public Member Functions
static int getNumSharedPatchDataSlots (int max_variables_to_register)
Static function used to predetermine number of patch data slots ahared among all PatchBoundaryEdgeSum objects (i.e., static members). To get a correct count, this routine should only be called once.
static int getNumUniquePatchDataSlots (int max_variables_to_register)
Static function used to predetermine number of patch data slots unique to each PatchBoundaryEdgeSum object (i.e., non-static members). To get a correct count, this routine should be called exactly once for each object that will be constructed.
Detailed Description
Class PatchBoundaryEdgeSum provides operations summing edge data values at edges that are shared by multiple patches on a single level. Note that this utility only works on a SINGLE patch level, not on a multiple levels in an AMR patch hierarchy like the PatchBoundaryNodeSum class. Unlike node data, edge data at coarse-fine boundaries are not co-located, so the sum operation is not clearly defined.
Usage of a patch boundry edge sum involves the following sequence of steps:
Construct a patch boundry edge sum object. For example,
 *         PatchBoundaryEdgeSum my_edge_sum("My Edge Sum");
 *
Register edge data quantities to sum. For example,
 *         my_edge_sum.registerSum(edge_data_id1);
 *         my_edge_sum.registerSum(edge_data_id2);
 *         etc...
 *
Setup the sum operations for a single level. For example,
 *         my_edge_sum.setupSum(level);
 *
Execute the sum operation. For example,
 *         my_edge_sum.computeSum()
 *
The result of these operations is that each edge patch data value associated with the registered ids at patch boundaries on the level is replaced by the sum of all data values at the edge.
Constructor & Destructor Documentation
SAMRAI::algs::PatchBoundaryEdgeSum::PatchBoundaryEdgeSum (const std::string & object_name) [explicit]
Constructor initializes object to default (mostly undefined) state.
Parameters:
object_name const std::string reference for name of object used in error reporting.
Precondition:
!object_name.empty()
References TBOX_ASSERT.
SAMRAI::algs::PatchBoundaryEdgeSum::~PatchBoundaryEdgeSum ()
Destructor for the schedule releases all internal storage.
References SAMRAI::hier::VariableDatabase::getDatabase().
Member Function Documentation
static int SAMRAI::algs::PatchBoundaryEdgeSum::getNumSharedPatchDataSlots (int max_variables_to_register) [inline, static]
Static function used to predetermine number of patch data slots ahared among all PatchBoundaryEdgeSum objects (i.e., static members). To get a correct count, this routine should only be called once.
Returns:
integer number of internal patch data slots required to perform sum.
Parameters:
max_variables_to_register integer value indicating maximum number of patch data ids that will be registered with edge sum objects.
static int SAMRAI::algs::PatchBoundaryEdgeSum::getNumUniquePatchDataSlots (int max_variables_to_register) [inline, static]
Static function used to predetermine number of patch data slots unique to each PatchBoundaryEdgeSum object (i.e., non-static members). To get a correct count, this routine should be called exactly once for each object that will be constructed.
Returns:
integer number of internal patch data slots required to perform sum.
Parameters:
max_variables_to_register integer value indicating maximum number of patch data ids that will be registered with edge sum objects.
References NULL_USE.
void SAMRAI::algs::PatchBoundaryEdgeSum::registerSum (int edge_data_id)
Register edge data with given patch data identifier for summing.
Parameters:
edge_data_id integer patch data index for edge data to sum
Precondition:
!d_setup_called
edge_data_id >= 0
hier::VariableDatabase::getDatabase()->getPatchDescriptor()->getPatchDataFactory(edge_data_id) is actually a boost::shared_ptr<pdat::EdgeDataFactory<double> >
References BOOST_CAST, SAMRAI::hier::VariableDatabase::getDatabase(), SAMRAI::hier::VariableDatabase::getPatchDescriptor(), SAMRAI::hier::VariableDatabase::getVariable(), SAMRAI::hier::IntVector::getZero(), SAMRAI::tbox::Utilities::intToString(), SAMRAI::hier::VariableDatabase::registerInternalSAMRAIVariable(), SAMRAI::hier::ComponentSelector::setFlag(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::algs::PatchBoundaryEdgeSum::setupSum (const boost::shared_ptr< hier::PatchLevel > & level)
Set up summation operations for edge data across shared edges on a single level.
Parameters:
level pointer to level on which to perform edge sum
Precondition:
level
References SAMRAI::xfer::RefineAlgorithm::createSchedule(), SAMRAI::xfer::RefineAlgorithm::registerRefine(), and TBOX_ASSERT.
void SAMRAI::algs::PatchBoundaryEdgeSum::computeSum () const
Compute sum of edge values at each shared edge and replace each such edge value with the corresponding sum.
At the end of this method, all values at shared edge locations on patch boundaries will have the same value.
const std::string& SAMRAI::algs::PatchBoundaryEdgeSum::getObjectName () const [inline]
Returns the object name.
Returns:
The object name.
The documentation for this class was generated from the following files:
source/SAMRAI/algs/PatchBoundaryEdgeSum.h
source/SAMRAI/algs/PatchBoundaryEdgeSum.C