SAMRAI: SAMRAI::hier::BaseGridGeometry Class Reference
SAMRAI::hier::BaseGridGeometry Class Reference
Class BaseGridGeometry manages the index space that determines the extent of the coarse-level domain of a SAMRAI hierarchy.
#include <source/SAMRAI/hier/BaseGridGeometry.h>
Classes
class ConstNeighborIterator
Class ConstNeighborIterator iterates over the Neighbors of a block.
class Neighbor
Class to represent the neighbor of a given block.
class NeighborIterator
Class NeighborIterator iterates over the Neighbors of a block.
Public Types
typedef PatchGeometry::TwoDimBool TwoDimBool
Public Member Functions
BaseGridGeometry (const tbox::Dimension &dim, const std::string &object_name, const boost::shared_ptr< tbox::Database > &input_db, bool allow_multiblock=true)
Construct a new BaseBaseGridGeometry object and initialize from input.
BaseGridGeometry (const std::string &object_name, BoxContainer &domain)
Construct a new BaseGridGeometry object based on arguments.
virtual ~BaseGridGeometry ()
Virtual destructor.
void computePhysicalDomain (BoxContainer &domain, const IntVector &ratio_to_level_zero, const BlockId &block_id) const
Compute the box array describing the index space for a given block of the physical domain.
void computePhysicalDomainWithPeriodicImages (BoxContainer &domain, const IntVector &ratio_to_level_zero, const BlockId &block_id) const
void computePhysicalDomain (BoxLevel &box_level, const IntVector &ratio_to_level_zero, const BlockId &block_id) const
Compute the BoxLevel describing the index space for a given block of the physical domain.
void computePhysicalDomain (BoxContainer &domain_boxes, const IntVector &ratio_to_level_zero) const
Compute the BoxContainer describing the complete physical domain for all blocks.
void computePhysicalDomain (BoxLevel &box_level, const IntVector &ratio_to_level_zero) const
Compute the BoxLevel describing the complete physical domain for all blocks.
void setPhysicalDomain (const BoxContainer &domain, const size_t number_blocks)
Set the physical domain (for level zero).
const BoxContainer & getPhysicalDomain () const
Get the physical domain description on level zero.
const BoxContainer & getDomainSearchTree () const
Access the multiblock domain description as a tree without periodic images.
const BoxContainer & getPeriodicDomainSearchTree () const
Access the multiblock domain description with periodic images (if any).
bool getDomainIsSingleBox (const BlockId &block_id) const
returns whether the physical domain for a block managed by this geometry object can be represented as a single box.
void initializePeriodicShift (const IntVector &directions)
Initialize the periodic shift on the coarsest level.
IntVector getPeriodicShift (const IntVector &ratio_to_level_zero) const
Get the periodic shift in each direction for the physical domain managed by this geometry object.
const PeriodicShiftCatalog & getPeriodicShiftCatalog () const
Get the periodic shift catalog object, used for mapping between a PeriodicId and an IntVector representation of a periodic shift.
size_t getNumberBlocks () const
Get the number of blocks in the geometry.
IntVector getMaxTransferOpStencilWidth (const tbox::Dimension &dim)
Get the max stencil width of all transfer operators.
virtual boost::shared_ptr
< BaseGridGeometry > makeRefinedGridGeometry (const std::string &fine_geom_name, const IntVector &refine_ratio) const =0
Create a pointer to a refined version of this grid geometry object.
virtual boost::shared_ptr
< BaseGridGeometry > makeCoarsenedGridGeometry (const std::string &coarse_geom_name, const IntVector &coarsen_ratio) const =0
Create a pointer to a coarsened version of this grid geometry object.
virtual void setGeometryDataOnPatch (Patch &patch, const IntVector &ratio_to_level_zero, const TwoDimBool &touches_regular_bdry) const
Compute and set grid data for patch.
void computeBoundaryBoxesOnLevel (std::map< BoxId, PatchBoundaries > &boundaries, const PatchLevel &level, const IntVector &periodic_shift, const IntVector &ghost_width, const std::vector< BoxContainer > &domain, bool do_all_patches=false) const
Compute boundary boxes for each patch in patch level.
void getBoundaryBoxes (PatchBoundaries &patch_boundaries, const Box &box, const BoxContainer &domain_boxes, const IntVector &ghosts, const IntVector &periodic_shift) const
Compute boundary boxes for patch.
void adjustMultiblockPatchLevelBoundaries (PatchLevel &patch_level)
Adjust boundary data of a level to be consistent with the multiblock nature of the domain.
void addCoarsenOperator (const char *var_type_name, const boost::shared_ptr< CoarsenOperator > &coarsen_op)
Add a concrete spatial coarsening operator.
void addRefineOperator (const char *var_type_name, const boost::shared_ptr< RefineOperator > &refine_op)
Add a concrete spatial refinement operator.
void addTimeInterpolateOperator (const char *var_type_name, const boost::shared_ptr< TimeInterpolateOperator > &time_op)
Add a concrete time interpolation operator.
boost::shared_ptr
< CoarsenOperator > lookupCoarsenOperator (const boost::shared_ptr< Variable > &var, const std::string &op_name)
Lookup function for coarsening operator.
boost::shared_ptr< RefineOperator > lookupRefineOperator (const boost::shared_ptr< Variable > &var, const std::string &op_name)
Lookup function for refinement operator.
boost::shared_ptr
< TimeInterpolateOperator > lookupTimeInterpolateOperator (const boost::shared_ptr< Variable > &var, const std::string &op_name="STD_LINEAR_TIME_INTERPOLATE")
Lookup function for time interpolation operator.
void setMinTransferOpStencilWidth (const IntVector &min_value)
Set a minimum value on the value returned by getMaxTransferOpStencilWidth().
const tbox::Dimension & getDim () const
Get the dimension of this object.
const std::string & getObjectName () const
Get the name of this object.
void registerNeighbors (const BlockId &block_a, const BlockId &block_b, const Transformation::RotationIdentifier rotation_b_to_a, const IntVector &shift_b_to_a)
Register a relationship between two neighboring blocks of a multiblock domain.
void findSingularities (std::set< std::set< BlockId > > &singularity_blocks)
find the blocks that touch singularities.
void chopDomain (BoxContainer &chopped_domain)
void getDomainOutsideBlock (BoxContainer &domain_outside_block, const BlockId &block_id) const
Get a BoxContainer that contains all of the index space of all other blocks in the multiblock domain.
int getNumberOfBlockSingularities () const
Return the number of block singularities in the block configuration.
const BoxContainer & getSingularityBoxContainer (const BlockId &block_id) const
Return a BoxContainer that describes all of the singularities touched by the block indicated by block_id.
bool transformBox (Box &box, const IntVector &ratio, const BlockId &output_block, const BlockId &input_block) const
Modify a box by rotating and shifting from the index space of the transformed_block to the index space of the base_block at the resolution level defined by ratio_to_level_zero.
bool transformBox (Box &box, int level_number, const BlockId &output_block, const BlockId &input_block) const
bool transformBoxContainer (BoxContainer &boxes, const IntVector &ratio, const BlockId &output_block, const BlockId &input_block) const
Modify boxes by rotating and shifting from the index space of the input_block to the index space of the output_block at the resolution level defined by ratio_to_level_zero.
void getTransformedBlock (BoxContainer &block_boxes, const BlockId &base_block, const BlockId &transformed_block)
Get a box array that describes the coarse-level domain of the transformed_block in terms of the index space of base_block.
int getNumberOfNeighbors (const BlockId &block_id) const
Return the number of neighbors a specific block of the Multiblock domain has.
bool areNeighbors (const BlockId &block_a, const BlockId &block_b) const
Tell if the given BlockIds represent neighboring blocks.
bool areSingularityNeighbors (const BlockId &block_a, const BlockId &block_b) const
Tell if the given BlockIds represent neighboring blocks.
Transformation::RotationIdentifier getRotationIdentifier (const BlockId &dst, const BlockId &src) const
Get the rotation identifier to rotate from src to dst.\.
const IntVector & getOffset (const BlockId &dst, const BlockId &src, int level_num) const
Get the offset to shift from src to dst after rotation.
bool hasEnhancedConnectivity () const
Query if the geometry has enhanced connectivity.
bool hasIsotropicRatios () const
Query if the the refinement ratios used in this geometry are isotropic.
void setUpRatios (const std::vector< IntVector > &ratio_to_coarser)
Set the relative refinement ratios between each level and its next coarser level.
int getEquivalentLevelNumber (const IntVector &ratio_to_level_zero) const
Get a level number based on a refinement ratio.
void printClassData (std::ostream &stream) const
Print object data to the specified output stream.
virtual void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
Writes the state of the BaseGridGeometry object to the restart database.
NeighborIterator begin (const BlockId &block_id)
Create iterator pointing to the first Neighbor of the block with the supplied block id.
NeighborIterator end (const BlockId &block_id)
Create iterator pointing one past the last Neighbor of the block with the supplied block id.
NeighborIterator find (const BlockId &block_id, const BlockId &nbr_block_id)
Create iterator pointing to the Neighbor with block id nbr_block_id of the block with block id block_id.
ConstNeighborIterator begin (const BlockId &block_id) const
Create iterator pointing to the first Neighbor of the block with the supplied block id.
ConstNeighborIterator end (const BlockId &block_id) const
Create iterator pointing one past the last Neighbor of the block with the supplied block id.
ConstNeighborIterator find (const BlockId &block_id, const BlockId &nbr_block_id) const
Create iterator pointing to the Neighbor with block id nbr_block_id of the block with block id block_id.
Functions for computing boundary boxes
void findPatchesTouchingBoundaries (std::map< BoxId, TwoDimBool > &touches_regular_boundary, std::map< BoxId, TwoDimBool > &touches_periodic_boundary, const PatchLevel &level) const
For every patch on a level, find all ways a patch touches a physical or periodic boundary.
void computeBoxTouchingBoundaries (TwoDimBool &touches_regular_bdry, TwoDimBool &touches_periodic_bdry, const Box &box, const IntVector &refinement_ratio, const BoxContainer &refined_periodic_domain_tree) const
Version of findPatchTouchingBoundaries for a single box.
virtual void setGeometryOnPatches (PatchLevel &level, const IntVector &ratio_to_level_zero, const std::map< BoxId, TwoDimBool > &touches_regular_bdry, const bool defer_boundary_box_creation)
Sets geometry data for patches on a level.
void setBoundaryBoxes (PatchLevel &level)
Construct and set the boundary boxes for each patch.
Protected Member Functions
BaseGridGeometry (const std::string &object_name, BoxContainer &domain, const boost::shared_ptr< TransferOperatorRegistry > &op_reg)
Construct a new BaseGridGeometry object based on arguments.
void readBlockDataFromInput (const boost::shared_ptr< tbox::Database > &input_db)
Read multiblock metadata input from the input database.
Protected Attributes
boost::shared_ptr
< TransferOperatorRegistry > d_transfer_operator_registry
tbox::Dimension d_dim
Detailed Description
Class BaseGridGeometry manages the index space that determines the extent of the coarse-level domain of a SAMRAI hierarchy.
A BaseGridGeometry object may be used as a base class to derive child classes that manage particular grid types (e.g., Cartesian, cylindrical, etc.).
The grid geometry class is responsible for maintaining information about the index space describing the physical domain and computing this information for patches in an AMR hierarchy.
Additional Functionality
Operations performed by this class include determining which patches are adjacent to the physical domain boundary and computing boundary boxes for patches which describe how the patch touches the domain boundary (useful for filling ghost cell data for physical boundary conditions).
See also:
BoundaryBox
Member Typedef Documentation
typedef PatchGeometry::TwoDimBool SAMRAI::hier::BaseGridGeometry::TwoDimBool
Constructor & Destructor Documentation
SAMRAI::hier::BaseGridGeometry::BaseGridGeometry (const tbox::Dimension & dim, const std::string & object_name, const boost::shared_ptr< tbox::Database > & input_db, bool allow_multiblock = true)
Construct a new BaseBaseGridGeometry object and initialize from input.
This constructor for BaseGridGeometry initializes data members based on parameters read from the specified input database.
This constructor is intended for use when directly constructing a BaseGridGeometry without using a derived child class. The object will contain all index space grid information for a mesh, but nothing about the physical coordinates of the mesh.
Parameters:
[in] dim
[in] object_name
[in] input_db
[in] allow_multiblock set to false if called by inherently single block derived class such as CartesianGridGeometry
Precondition:
!object_name.empty()
input_db
References SAMRAI::tbox::RestartManager::getManager(), getObjectName(), and TBOX_ASSERT.
SAMRAI::hier::BaseGridGeometry::BaseGridGeometry (const std::string & object_name, BoxContainer & domain)
Construct a new BaseGridGeometry object based on arguments.
This constructor creates a new BaseGridGeometry object based on the arguments, rather than relying on input or restart data.
Parameters:
[in] object_name
[in] domain Each element of the array describes the index space for a block.
Precondition:
!object_name.empty()
!domain.empty()
References SAMRAI::hier::BoxContainer::begin(), d_dim, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::tbox::RestartManager::getManager(), getObjectName(), SAMRAI::hier::IntVector::getOne(), setPhysicalDomain(), and TBOX_ASSERT.
SAMRAI::hier::BaseGridGeometry::~BaseGridGeometry () [virtual]
Virtual destructor.
References SAMRAI::tbox::RestartManager::getManager(), and getObjectName().
SAMRAI::hier::BaseGridGeometry::BaseGridGeometry (const std::string & object_name, BoxContainer & domain, const boost::shared_ptr< TransferOperatorRegistry > & op_reg) [protected]
Construct a new BaseGridGeometry object based on arguments.
Parameters:
[in] object_name
[in] domain Each element of the array describes the index space for a block.
[in] op_reg
Precondition:
!object_name.empty()
!domain.empty()
References SAMRAI::hier::BoxContainer::begin(), d_dim, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::tbox::RestartManager::getManager(), getObjectName(), SAMRAI::hier::IntVector::getOne(), setPhysicalDomain(), and TBOX_ASSERT.
Member Function Documentation
void SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries (std::map< BoxId, TwoDimBool > & touches_regular_boundary, std::map< BoxId, TwoDimBool > & touches_periodic_boundary, const PatchLevel & level) const
For every patch on a level, find all ways a patch touches a physical or periodic boundary.
For every patch on the given PatchLevel, this routine determines which kinds of boundaries are touched (regular, periodic, both, or neither).
Parameters:
[out] touches_regular_boundary map to store which patches touch non-periodic boundaries.
[out] touches_periodic_boundary map to store which patches touch periodic boundaries.
[in] level containing the patches to be checked
References SAMRAI::hier::PatchLevel::begin(), computeBoxTouchingBoundaries(), d_dim, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::PatchLevel::end(), SAMRAI::hier::PatchLevel::getDim(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::PatchLevel::getRatioToLevelZero(), SAMRAI::hier::BoxContainer::makeTree(), and SAMRAI::hier::BoxContainer::refine().
void SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries (TwoDimBool & touches_regular_bdry, TwoDimBool & touches_periodic_bdry, const Box & box, const IntVector & refinement_ratio, const BoxContainer & refined_periodic_domain_tree) const
Version of findPatchTouchingBoundaries for a single box.
Parameters:
[out] touches_regular_bdry TwoDimBool to store which patches touch non-periodic boundaries.
[out] touches_periodic_bdry TwoDimBool to store which patches touch periodic boundaries.
[in] box to be checked
[in] refinement_ratio Refinement ratio of given box
[in] refined_periodic_domain_tree
References SAMRAI::hier::BoxContainer::begin(), d_dim, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::IntVector::getOne(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxContainer::grow(), SAMRAI::hier::Box::growLower(), SAMRAI::hier::Box::growUpper(), SAMRAI::hier::BoxContainer::intersectBoxes(), SAMRAI::hier::Box::lower(), SAMRAI::hier::BoxContainer::removeIntersections(), and SAMRAI::hier::Box::upper().
Referenced by findPatchesTouchingBoundaries().
void SAMRAI::hier::BaseGridGeometry::setGeometryOnPatches (PatchLevel & level, const IntVector & ratio_to_level_zero, const std::map< BoxId, TwoDimBool > & touches_regular_bdry, const bool defer_boundary_box_creation) [virtual]
Sets geometry data for patches on a level.
Using the boundary information previously computed, this method will pass the information to the concrete implementation of the geometry class, and construct boundary boxes if required.
Parameters:
[in,out] level containing the patches to be checked.
[in] ratio_to_level_zero ratio to the coarsest level.
[in] touches_regular_bdry Array storing which patches touch non-periodic boundaries.
[in] defer_boundary_box_creation Flag to indicate if boundary boxes should be created
Precondition:
(getDim() == level.getDim()) && (getDim() == ratio_to_level_zero.getDim())
ratio_to_level_zero != IntVector::getZero(getDim())
References SAMRAI::hier::PatchLevel::begin(), d_dim, SAMRAI::hier::PatchLevel::end(), SAMRAI::tbox::Dimension::getValue(), setBoundaryBoxes(), setGeometryDataOnPatch(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
void SAMRAI::hier::BaseGridGeometry::setBoundaryBoxes (PatchLevel & level)
Construct and set the boundary boxes for each patch.
Construct the boundary boxes for every patch in the level. Once constructed, the boundary boxes are set on each patch's PatchGeometry object.
Parameters:
[in,out] level The level for which boundary boxes are constructed.
Precondition:
getDim() == level.getDim()
References computeBoundaryBoxesOnLevel(), d_dim, SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::PatchLevel::getPatch(), SAMRAI::hier::PatchLevel::getPatchDescriptor(), getPeriodicShift(), SAMRAI::hier::PatchLevel::getPhysicalDomainArray(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by setGeometryOnPatches().
void SAMRAI::hier::BaseGridGeometry::computePhysicalDomain (BoxContainer & domain, const IntVector & ratio_to_level_zero, const BlockId & block_id) const
Compute the box array describing the index space for a given block of the physical domain.
The domain description does not include periodic images.
If any entry of the ratio vector is negative, the index space is coarsened with respect to the physical domain description. Otherwise, the index space is refined.
Parameters:
[out] domain The BoxContainer to be computed
[in] ratio_to_level_zero ratio to the coarsest level
[in] block_id
Precondition:
getDim() == ratio_to_level_zero.getDim()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::clear(), SAMRAI::hier::BoxContainer::coarsen(), d_dim, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxContainer::insert(), SAMRAI::hier::BoxContainer::refine(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::mesh::PartitioningParams::PartitioningParams().
void SAMRAI::hier::BaseGridGeometry::computePhysicalDomainWithPeriodicImages (BoxContainer & domain, const IntVector & ratio_to_level_zero, const BlockId & block_id) const
void SAMRAI::hier::BaseGridGeometry::computePhysicalDomain (BoxLevel & box_level, const IntVector & ratio_to_level_zero, const BlockId & block_id) const
Compute the BoxLevel describing the index space for a given block of the physical domain.
The domain description includes periodic images, if any exist.
Unlike the BoxContainer version of this function, the domain computed contains periodic image boxes. If any entry of ratio vector is negative, the index space is coarsened with respect to the physical domain description. Otherwise, the index space is refined.
Parameters:
[out] box_level The BoxLevel containing all Boxes describing the index space
[in] ratio_to_level_zero ratio to the coarsest level
[in] block_id
Precondition:
getDim() == ratio_to_level_zero.getDim()
References SAMRAI::hier::BoxLevel::addBoxWithoutUpdate(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxLevel::coarsenBoxes(), d_dim, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::IntVector::getOne(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxLevel::refineBoxes(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::hier::BaseGridGeometry::computePhysicalDomain (BoxContainer & domain_boxes, const IntVector & ratio_to_level_zero) const
Compute the BoxContainer describing the complete physical domain for all blocks.
The domain description includes periodic images, if any exist.
If any entry of the ratio vector is negative, the index space is coarsened with respect to the physical domain description. Otherwise, the index space is refined.
Parameters:
[out] domain_boxes The BoxContainer containing all Boxes describing the physical domain
[in] ratio_to_level_zero ratio to the coarsest level
Precondition:
getDim() == ratio_to_level_zero.getDim()
References SAMRAI::hier::BoxContainer::coarsen(), d_dim, SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxContainer::refine(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::hier::BaseGridGeometry::computePhysicalDomain (BoxLevel & box_level, const IntVector & ratio_to_level_zero) const
Compute the BoxLevel describing the complete physical domain for all blocks.
The domain description includes periodic images, if any exist.
If any entry of the ratio vector is negative, the index space is coarsened with respect to the physical domain description. Otherwise, the index space is refined.
Parameters:
[out] box_level The BoxLevel containing all Boxes describing the physical domain
[in] ratio_to_level_zero ratio to the coarsest level
Precondition:
getDim() == ratio_to_level_zero.getDim()
References SAMRAI::hier::BoxLevel::addBoxWithoutUpdate(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coarsen(), d_dim, SAMRAI::hier::BoxContainer::end(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxContainer::refine(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::hier::BaseGridGeometry::setPhysicalDomain (const BoxContainer & domain, const size_t number_blocks)
Set the physical domain (for level zero).
Each entry in the array of box arrays represents the physical domain for a single block
The extents of the input domain boxes are used, but their LocalId's are disregarded. BaseGridGeometry will assign new and unique LocalId's to the domain box description. Subsequent calls to getPhysicalDomain() will return boxes with the new LocalId's.
Parameters:
[in] domain The input array of BoxContainer
[in] number_blocks
Precondition:
!domain.empty()
for each box in domain: box.getBlockId().isValid() && (box.getBlockId().getBlockValue() < number_blocks)
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::clear(), d_dim, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::getBoundingBox(), SAMRAI::hier::IntVector::getOne(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::pushBack(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by BaseGridGeometry(), and SAMRAI::geom::CartesianGridGeometry::setGeometryData().
const BoxContainer& SAMRAI::hier::BaseGridGeometry::getPhysicalDomain () const [inline]
Get the physical domain description on level zero.
Returns:
const reference to physical domain description for level 0.
Referenced by SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry(), putToRestart(), and SAMRAI::geom::CartesianGridGeometry::setGeometryData().
const BoxContainer& SAMRAI::hier::BaseGridGeometry::getDomainSearchTree () const [inline]
Access the multiblock domain description as a tree without periodic images.
This tree does not contain periodic images, even if there is only one block and the domain is periodic.
Returns:
The multiblock domain description as a search tree.
const BoxContainer& SAMRAI::hier::BaseGridGeometry::getPeriodicDomainSearchTree () const [inline]
Access the multiblock domain description with periodic images (if any).
Returns:
The domain description as a search tree with periodic images (if any).
bool SAMRAI::hier::BaseGridGeometry::getDomainIsSingleBox (const BlockId & block_id) const [inline]
returns whether the physical domain for a block managed by this geometry object can be represented as a single box.
Returns:
true if the physical domain can be represented as a single box, otherwise false.
Parameters:
[in] block_id
References SAMRAI::hier::BlockId::getBlockValue().
void SAMRAI::hier::BaseGridGeometry::initializePeriodicShift (const IntVector & directions)
Initialize the periodic shift on the coarsest level.
Parameters:
[in] directions an array indicating periodic directions(1) or all others (0).
Precondition:
getDim() == directions.getDim()
Note:
The IntVector argument should be set to 1 for periodic directions and 0 for all other directions. The shift will be calculated to the number of cells in the periodic direction and zero in all other directions.
References SAMRAI::hier::BoxContainer::size(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector SAMRAI::hier::BaseGridGeometry::getPeriodicShift (const IntVector & ratio_to_level_zero) const
Get the periodic shift in each direction for the physical domain managed by this geometry object.
The returned IntVector contains the periodic shift in each direction for a domain represented by a refinement of the reference physical domain (i.e. level zero) by the given ratio vector. Entries will be zero for non-periodic directions.
Parameters:
[in] ratio_to_level_zero ratio to the coarsest level.
Returns:
The periodic shift in each direction for a domain represented by a refinement of the reference physical domain.
Precondition:
getDim() == ratio_to_level_zero.getDim()
References d_dim, SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry(), putToRestart(), and setBoundaryBoxes().
const PeriodicShiftCatalog& SAMRAI::hier::BaseGridGeometry::getPeriodicShiftCatalog () const [inline]
Get the periodic shift catalog object, used for mapping between a PeriodicId and an IntVector representation of a periodic shift.
size_t SAMRAI::hier::BaseGridGeometry::getNumberBlocks () const [inline]
Get the number of blocks in the geometry.
Referenced by SAMRAI::hier::SingularityFinder::findSingularities(), and SAMRAI::mesh::PartitioningParams::PartitioningParams().
IntVector SAMRAI::hier::BaseGridGeometry::getMaxTransferOpStencilWidth (const tbox::Dimension & dim) [inline]
Get the max stencil width of all transfer operators.
The max stencil width is required by the DLBG to determine when two nearby boxes are defined as neighbors. The DLBG in turn provides the neighbor information for various operations such as schedule construction.
Returns:
The max stencil width of all transfer operators.
References d_transfer_operator_registry.
virtual boost::shared_ptr<BaseGridGeometry> SAMRAI::hier::BaseGridGeometry::makeRefinedGridGeometry (const std::string & fine_geom_name, const IntVector & refine_ratio) const [pure virtual]
Create a pointer to a refined version of this grid geometry object.
Virtual method -- should be overridden in specialized grid geometry classes
Parameters:
[in] fine_geom_name std::string name of the geometry object
[in] refine_ratio the refinement ratio.
Returns:
The pointer to the grid geometry object.
Implemented in SAMRAI::geom::CartesianGridGeometry, and SAMRAI::geom::GridGeometry.
virtual boost::shared_ptr<BaseGridGeometry> SAMRAI::hier::BaseGridGeometry::makeCoarsenedGridGeometry (const std::string & coarse_geom_name, const IntVector & coarsen_ratio) const [pure virtual]
Create a pointer to a coarsened version of this grid geometry object.
Virtual method -- should be overridden in specialized grid geometry classes
Parameters:
[in] coarse_geom_name std::string name of the geometry object
[in] coarsen_ratio the coasening ratio
Returns:
The pointer to a coarsened version of this grid geometry object.
Implemented in SAMRAI::geom::CartesianGridGeometry, and SAMRAI::geom::GridGeometry.
void SAMRAI::hier::BaseGridGeometry::setGeometryDataOnPatch (Patch & patch, const IntVector & ratio_to_level_zero, const TwoDimBool & touches_regular_bdry) const [virtual]
Compute and set grid data for patch.
Virtual method -- should be overridden in specialized grid geometry classes
Parameters:
[in,out] patch The patch on which to set grid data and the new concrete patch geometry object.
[in] ratio_to_level_zero ratio to coarsest level
[in] touches_regular_bdry Array storing which patches touch non-periodic boundaries.
Precondition:
(getDim() == patch.getDim()) && (getDim() == ratio_to_level_zero.getDim()) && (getDim() == touches_regular_bdry.getDim())
Reimplemented in SAMRAI::geom::CartesianGridGeometry.
References d_dim, SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Patch::getBox(), getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Patch::setPatchGeometry(), TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY3.
Referenced by setGeometryOnPatches().
void SAMRAI::hier::BaseGridGeometry::computeBoundaryBoxesOnLevel (std::map< BoxId, PatchBoundaries > & boundaries, const PatchLevel & level, const IntVector & periodic_shift, const IntVector & ghost_width, const std::vector< BoxContainer > & domain, bool do_all_patches = false) const
Compute boundary boxes for each patch in patch level.
Boundary boxes for each patch in a patch level will be computed and assign to boundary box arrays. These arrays are assumed to be of length
    DIM * num_patches
.
The DIM arrays of boundary boxes for each patch will be stored in groups of DIM. For example in 3D, with n patches on the level, the array of boundary box arrays will be ordered as follows:
 (patch 0 face array, patch 0 edge array, patch 0 box array,
  patch 1 face array, patch 1 edge array, patch 1 box array, . . . ,
  patch n-1 face array, patch n-1 edge array, patch n-1 box array)
Note:
The optional argument do_all_patches defaults to false: the boundary box computation is executed only on patches that touch a non-periodic boundary. When this routine is called during patch level construction to describe a physical boundary, it is known that only patches that touch a non-periodic boundary will have non-empty sets of boundary boxes, so for efficiency's sake the boundary box box computation is supressed for all other patches.
When this routine is called to create boundary boxes that describe a coarse-fine boundary, the computation must occur for every patch, so do_all_patches must be set to true.
Parameters:
[out] boundaries output boundary description
[in] level level on which to generate boundaries
[in] periodic_shift periodic shift for the level (see getPeriodicShift())
[in] ghost_width ghost width to compute geometry for the domain
[in] domain Physical domain (in index space of level) for computing boundary boxes.
[in] do_all_patches Flag to indicate boundary box computation on all patches, even those known to not touch a boundary
Precondition:
(getDim() == level.getDim()) && (getDim() == periodic_shift.getDim()) && (getDim() == ghost_width.getDim())
ghost_width >= IntVector::getZero(ghost_width.getDim())
References SAMRAI::hier::PatchLevel::begin(), d_dim, SAMRAI::hier::PatchLevel::end(), getBoundaryBoxes(), SAMRAI::hier::IntVector::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY3.
Referenced by setBoundaryBoxes().
void SAMRAI::hier::BaseGridGeometry::getBoundaryBoxes (PatchBoundaries & patch_boundaries, const Box & box, const BoxContainer & domain_boxes, const IntVector & ghosts, const IntVector & periodic_shift) const
Compute boundary boxes for patch.
Decompose patch boundary region into pieces depending on spatial directions. Boxes are extended along the boundary to the edge of the ghost box_level if necessary.
Parameters:
[out] patch_boundaries output boundaries
[in] box
[in] domain_boxes
[in] ghosts
[in] periodic_shift
Precondition:
(getDim() == box.getDim()) && (getDim() == ghosts.getDim()) && (getDim() == periodic_shift.getDim())
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coalesce(), d_dim, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoundaryLookupTable::getDirections(), SAMRAI::hier::BoundaryLookupTable::getLookupTable(), SAMRAI::hier::BoundaryLookupTable::getMaxLocationIndices(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxContainer::grow(), SAMRAI::hier::BoxContainer::hasTree(), SAMRAI::hier::BoxContainer::intersectBoxes(), SAMRAI::hier::BoundaryLookupTable::isUpper(), SAMRAI::hier::Box::lower(), SAMRAI::hier::BoxContainer::makeTree(), SAMRAI::hier::BoxContainer::removeIntersections(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), SAMRAI::hier::BoxContainer::shift(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT_OBJDIM_EQUALITY4, and SAMRAI::hier::Box::upper().
Referenced by computeBoundaryBoxesOnLevel().
void SAMRAI::hier::BaseGridGeometry::adjustMultiblockPatchLevelBoundaries (PatchLevel & patch_level)
Adjust boundary data of a level to be consistent with the multiblock nature of the domain.
In a multiblock problem, the PatchLevels contain patches that were constructed independent of any knowledge of the multiblock nature of the complete domain. Thus the patches will contain boundary data that recognizes no difference between a physical domain boundary and a block boundary. Calling this method will adjust the boundary data on all patches in the given level such that the true boundaries of the domain are represented.
Parameters:
[in,out] patch_level Level where boundaries need to be adjusted.
Precondition:
getDim() == patch_level.getDim()
patch_level.getGridGeometry()->getNumberBlocks() == getNumberBlocks()
TODO: Incorporate into regular boundary box computation once PatchLevel is multiblock-aware.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coalesce(), d_dim, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::PatchLevel::getBoxLevel(), SAMRAI::hier::PatchLevel::getGridGeometry(), SAMRAI::hier::PatchLevel::getPatch(), SAMRAI::hier::PatchLevel::getPatchDescriptor(), SAMRAI::hier::PatchLevel::getPhysicalDomain(), SAMRAI::hier::PatchLevel::getRatioToLevelZero(), SAMRAI::hier::BoxContainer::refine(), SAMRAI::hier::BoxContainer::spliceFront(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::hier::BaseGridGeometry::addCoarsenOperator (const char * var_type_name, const boost::shared_ptr< CoarsenOperator > & coarsen_op) [inline]
Add a concrete spatial coarsening operator.
Parameters:
[in] var_type_name The type name of the variable with which coarsen_op is associated.
[in] coarsen_op The concrete coarsening operator to add to the lookup list.
References d_transfer_operator_registry.
Referenced by SAMRAI::geom::GridGeometry::buildOperators(), and SAMRAI::geom::CartesianGridGeometry::buildOperators().
void SAMRAI::hier::BaseGridGeometry::addRefineOperator (const char * var_type_name, const boost::shared_ptr< RefineOperator > & refine_op) [inline]
Add a concrete spatial refinement operator.
Parameters:
[in] var_type_name The type name of the variable with which refine_op is associated.
[in] refine_op The concrete refinement operator to add to the lookup list.
References d_transfer_operator_registry.
Referenced by SAMRAI::geom::GridGeometry::buildOperators(), and SAMRAI::geom::CartesianGridGeometry::buildOperators().
void SAMRAI::hier::BaseGridGeometry::addTimeInterpolateOperator (const char * var_type_name, const boost::shared_ptr< TimeInterpolateOperator > & time_op) [inline]
Add a concrete time interpolation operator.
Parameters:
[in] var_type_name The type name of the variable with which time_op is associated.
[in] time_op The concrete time interpolation operator to add to the lookup list.
References d_transfer_operator_registry.
Referenced by SAMRAI::geom::GridGeometry::buildOperators().
boost::shared_ptr<CoarsenOperator> SAMRAI::hier::BaseGridGeometry::lookupCoarsenOperator (const boost::shared_ptr< Variable > & var, const std::string & op_name) [inline]
Lookup function for coarsening operator.
Search list for the spatial coarsening operator matching the request for the given variable. If the operator is found, a pointer to it will be returned. Otherwise, an unrecoverable error will result and the program will abort.
Parameters:
[in] var The Variable for which the corresponding coarsening operator should match.
[in] op_name The string identifier of the coarsening operator.
References d_transfer_operator_registry.
boost::shared_ptr<RefineOperator> SAMRAI::hier::BaseGridGeometry::lookupRefineOperator (const boost::shared_ptr< Variable > & var, const std::string & op_name) [inline]
Lookup function for refinement operator.
Search list for the spatial refinement operator matching the request for the given variable. If the operator is found, a pointer to it will be returned. Otherwise, an unrecoverable error will result and the program will abort.
Parameters:
[in] var The Variable for which the corresponding refinement operator should match.
[in] op_name The string identifier of the refinement operator.
References d_transfer_operator_registry.
boost::shared_ptr<TimeInterpolateOperator> SAMRAI::hier::BaseGridGeometry::lookupTimeInterpolateOperator (const boost::shared_ptr< Variable > & var, const std::string & op_name = "STD_LINEAR_TIME_INTERPOLATE") [inline]
Lookup function for time interpolation operator.
Search list for the time interpolation operator matching the request for the given variable. If the operator is found, a pointer to it will be returned. Otherwise, an unrecoverable error will result and the program will abort.
Parameters:
[in] var The Variable for which the corresponding time interpolation operator should match.
[in] op_name The string identifier of the time interpolation operator. Default: STD_LINEAR_TIME_INTERPOLATE
References d_transfer_operator_registry.
void SAMRAI::hier::BaseGridGeometry::setMinTransferOpStencilWidth (const IntVector & min_value) [inline]
Set a minimum value on the value returned by getMaxTransferOpStencilWidth().
This method allows users to specify a minimum value returned by getMaxTransferOpStencilWidth(). The default minimum is zero. This value can be used as a substitute for data that is not yet registered with the Geometry and therefore cannot be reflected in getMaxTransferOpStencilWidth().
Parameters:
[in] min_value The minimum value to set.
References d_transfer_operator_registry.
const tbox::Dimension& SAMRAI::hier::BaseGridGeometry::getDim () const [inline]
Get the dimension of this object.
Returns:
the dimension of this object.
References d_dim.
Referenced by SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::printClassData(), putToRestart(), SAMRAI::geom::CartesianGridGeometry::putToRestart(), SAMRAI::geom::CartesianGridGeometry::setGeometryData(), setGeometryDataOnPatch(), and SAMRAI::geom::CartesianGridGeometry::setGeometryDataOnPatch().
const std::string& SAMRAI::hier::BaseGridGeometry::getObjectName () const [inline]
Get the name of this object.
Returns:
The name of this object.
Referenced by BaseGridGeometry(), getEquivalentLevelNumber(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::printClassData(), and ~BaseGridGeometry().
void SAMRAI::hier::BaseGridGeometry::registerNeighbors (const BlockId & block_a, const BlockId & block_b, const Transformation::RotationIdentifier rotation_b_to_a, const IntVector & shift_b_to_a)
Register a relationship between two neighboring blocks of a multiblock domain.
Parameters:
[in] block_a One block in the relationship
[in] block_b The other block
[in] rotation_b_to_a The rotation that aligns block b's index space with block a's
[in] shift_b_to_a The post-rotation shift to move b into its correct location within a's index space
Precondition:
getDim() = shift_b_to_a.getDim()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::Transformation::calculateReverseShift(), d_dim, SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::Transformation::getReverseRotationIdentifier(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxContainer::rotate(), SAMRAI::hier::BoxContainer::shift(), TBOX_ASSERT_OBJDIM_EQUALITY2, TBOX_ERROR, and SAMRAI::hier::BoxContainer::unorder().
Referenced by readBlockDataFromInput().
void SAMRAI::hier::BaseGridGeometry::findSingularities (std::set< std::set< BlockId > > & singularity_blocks)
find the blocks that touch singularities.
Parameters:
[out] singularity_blocks Container to hold the singularity information. Each singularity is represented by a member of the outer set, while the inner set holds all BlockIds for the blocks that touch a particular singularity.
Precondition:
singularity_blocks.empty()
d_number_blocks > 1
References chopDomain(), d_dim, SAMRAI::hier::Box::empty(), end(), find(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::IntVector::getOne(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::grow(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, TBOX_ERROR, transformBox(), and SAMRAI::hier::Box::upper().
Referenced by readBlockDataFromInput().
void SAMRAI::hier::BaseGridGeometry::chopDomain (BoxContainer & chopped_domain)
References begin(), d_dim, SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::empty(), end(), find(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::IntVector::getOne(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::BoxContainer::order(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, transformBox(), and SAMRAI::hier::Box::upper().
Referenced by findSingularities().
void SAMRAI::hier::BaseGridGeometry::getDomainOutsideBlock (BoxContainer & domain_outside_block, const BlockId & block_id) const
Get a BoxContainer that contains all of the index space of all other blocks in the multiblock domain.
A BoxContainer will be constructed that contains the full set of the coarse level domains of all blocks except the one identified by block_id. The domains will all be transformed into the index space represented by block_id.
Parameters:
[out] domain_outside_block
[in] block_id
References SAMRAI::hier::BlockId::getBlockValue(), and SAMRAI::hier::BoxContainer::spliceFront().
int SAMRAI::hier::BaseGridGeometry::getNumberOfBlockSingularities () const [inline]
Return the number of block singularities in the block configuration.
const BoxContainer& SAMRAI::hier::BaseGridGeometry::getSingularityBoxContainer (const BlockId & block_id) const [inline]
Return a BoxContainer that describes all of the singularities touched by the block indicated by block_id.
Returns:
For every singularity point the block touches, the BoxContainer will contain a single-cell box that lies just outside the block domain, touching the block only at the singularity point. For line singularities, the BoxContainer will contain boxes of width 1 in all directions except one, lying outside the block's coarse-level domain and touching the domain only along the line of singularity.
Parameters:
[in] block_id
References SAMRAI::hier::BlockId::getBlockValue().
Referenced by printClassData().
bool SAMRAI::hier::BaseGridGeometry::transformBox (Box & box, const IntVector & ratio, const BlockId & output_block, const BlockId & input_block) const
Modify a box by rotating and shifting from the index space of the transformed_block to the index space of the base_block at the resolution level defined by ratio_to_level_zero.
Parameters:
[in,out] box The boxes will be transformed from the transformed_block index space to the base_block index space.
[in] ratio
[in] output_block Integer identifier of the block whose index space will be represented in the boxes at output
[in] input_block Integer identifier of the block whose index space is represented in the boxes at input
Precondition:
(getDim() == box.getDim()) && (getDim() == ratio.getDim())
Returns:
Whether the box has been transformed. True if there is a relationship between input_block and output_block. False if there is no such relationship.
References getEquivalentLevelNumber(), and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by chopDomain(), SAMRAI::hier::AssumedPartition::findOverlaps(), and findSingularities().
bool SAMRAI::hier::BaseGridGeometry::transformBox (Box & box, int level_number, const BlockId & output_block, const BlockId & input_block) const
References end(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::BaseGridGeometry::Neighbor::getRotationIdentifier(), SAMRAI::hier::BaseGridGeometry::Neighbor::getShift(), SAMRAI::hier::Box::rotate(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::hier::BaseGridGeometry::transformBoxContainer (BoxContainer & boxes, const IntVector & ratio, const BlockId & output_block, const BlockId & input_block) const
Modify boxes by rotating and shifting from the index space of the input_block to the index space of the output_block at the resolution level defined by ratio_to_level_zero.
Parameters:
[in,out] boxes The boxes will be transformed from the input_block index space to the output_block index space.
[in] ratio
[in] output_block Integer identifier of the block whose index space will be represented in the boxes at output
[in] input_block Integer identifier of the block whose index space is represented in the boxes at input
Returns:
Whether the boxes have been transformed. True if there is a relationship between input_block and output_block. False if there is no such relationship.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), end(), SAMRAI::hier::BlockId::getBlockValue(), getEquivalentLevelNumber(), SAMRAI::hier::BaseGridGeometry::Neighbor::getRotationIdentifier(), SAMRAI::hier::BaseGridGeometry::Neighbor::getShift(), SAMRAI::hier::BoxContainer::rotate(), and SAMRAI::hier::BoxContainer::shift().
void SAMRAI::hier::BaseGridGeometry::getTransformedBlock (BoxContainer & block_boxes, const BlockId & base_block, const BlockId & transformed_block)
Get a box array that describes the coarse-level domain of the transformed_block in terms of the index space of base_block.
Parameters:
[out] block_boxes The coarse-level domain of the block identified by transformed_block, represented in the index space of the block identified by base_block
[in] base_block The block whose index space will be used for the output boxes
[in] transformed_block ID of another block whose domain will be represented in the index space of the base block
References end(), and SAMRAI::hier::BlockId::getBlockValue().
int SAMRAI::hier::BaseGridGeometry::getNumberOfNeighbors (const BlockId & block_id) const [inline]
Return the number of neighbors a specific block of the Multiblock domain has.
A block is the neighbor of another block if the two blocks abut in any way, whether at a point, a 1D line, or a 2D plane.
Returns:
The number of neighbors
Parameters:
[in] block_id
References SAMRAI::hier::BlockId::getBlockValue().
bool SAMRAI::hier::BaseGridGeometry::areNeighbors (const BlockId & block_a, const BlockId & block_b) const
Tell if the given BlockIds represent neighboring blocks.
Parameters:
block_a
block_b
References end(), and SAMRAI::hier::BlockId::getBlockValue().
Referenced by getOffset(), and getRotationIdentifier().
bool SAMRAI::hier::BaseGridGeometry::areSingularityNeighbors (const BlockId & block_a, const BlockId & block_b) const
Tell if the given BlockIds represent neighboring blocks.
Parameters:
block_a
block_b
References end(), and SAMRAI::hier::BlockId::getBlockValue().
Transformation::RotationIdentifier SAMRAI::hier::BaseGridGeometry::getRotationIdentifier (const BlockId & dst, const BlockId & src) const
Get the rotation identifier to rotate from src to dst.\.
Parameters:
dst
src
Precondition:
areNeighbors(dst, src)
References areNeighbors(), end(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ASSERT.
Referenced by readBlockDataFromInput().
const IntVector & SAMRAI::hier::BaseGridGeometry::getOffset (const BlockId & dst, const BlockId & src, int level_num) const
Get the offset to shift from src to dst after rotation.
Parameters:
dst
src
level_num
Precondition:
areNeighbors(dst, src)
References areNeighbors(), d_dim, end(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::IntVector::getOne(), and TBOX_ASSERT.
bool SAMRAI::hier::BaseGridGeometry::hasEnhancedConnectivity () const [inline]
Query if the geometry has enhanced connectivity.
bool SAMRAI::hier::BaseGridGeometry::hasIsotropicRatios () const [inline]
Query if the the refinement ratios used in this geometry are isotropic.
All ratios must be isotropic for this to return true.
void SAMRAI::hier::BaseGridGeometry::setUpRatios (const std::vector< IntVector > & ratio_to_coarser)
Set the relative refinement ratios between each level and its next coarser level.
Parameters:
ratio_to_coarser Vector of refinement ratios.
References d_dim, SAMRAI::hier::IntVector::getOne(), and TBOX_ASSERT.
int SAMRAI::hier::BaseGridGeometry::getEquivalentLevelNumber (const IntVector & ratio_to_level_zero) const [inline]
Get a level number based on a refinement ratio.
An error will occur if the given ratio is not equal to one of the ratios stored in this geometry.
Parameters:
ratio_to_level_zero
References getObjectName(), and TBOX_ERROR.
Referenced by transformBox(), and transformBoxContainer().
void SAMRAI::hier::BaseGridGeometry::printClassData (std::ostream & stream) const
Print object data to the specified output stream.
Parameters:
[out] stream The output stream (as a std::ostream&) to print to.
Reimplemented in SAMRAI::geom::CartesianGridGeometry.
References SAMRAI::hier::BoxContainer::begin(), begin(), SAMRAI::hier::BoxContainer::end(), end(), SAMRAI::hier::BaseGridGeometry::Neighbor::getBlockId(), getSingularityBoxContainer(), SAMRAI::hier::BaseGridGeometry::Neighbor::isSingularity(), SAMRAI::hier::BoxContainer::print(), and SAMRAI::hier::BoxContainer::size().
void SAMRAI::hier::BaseGridGeometry::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [virtual]
Writes the state of the BaseGridGeometry object to the restart database.
Parameters:
[in,out] restart_db The restart database to write/serialize to.
Precondition:
restart_db
Reimplemented in SAMRAI::geom::CartesianGridGeometry.
References begin(), SAMRAI::hier::Transformation::getBeginBlock(), SAMRAI::hier::BaseGridGeometry::Neighbor::getBlockId(), SAMRAI::hier::BlockId::getBlockValue(), getDim(), SAMRAI::hier::Transformation::getEndBlock(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::IntVector::getOne(), getPeriodicShift(), getPhysicalDomain(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::hier::BaseGridGeometry::Neighbor::getTransformation(), SAMRAI::hier::BaseGridGeometry::Neighbor::getTransformedDomain(), SAMRAI::tbox::Dimension::getValue(), HIER_GRID_GEOMETRY_VERSION, SAMRAI::tbox::Utilities::intToString(), SAMRAI::hier::BaseGridGeometry::Neighbor::isSingularity(), SAMRAI::hier::IntVector::putToRestart(), SAMRAI::hier::BoxContainer::putToRestart(), and TBOX_ASSERT.
NeighborIterator SAMRAI::hier::BaseGridGeometry::begin (const BlockId & block_id) [inline]
Create iterator pointing to the first Neighbor of the block with the supplied block id.
Parameters:
[in] block_id The block id of the block whose Neighbors are of interest.
Returns:
Iterator pointing to the first Neighbor of the block with supplied block id.
Referenced by chopDomain(), printClassData(), and putToRestart().
NeighborIterator SAMRAI::hier::BaseGridGeometry::end (const BlockId & block_id) [inline]
Create iterator pointing one past the last Neighbor of the block with the supplied block id.
Parameters:
[in] block_id The block id of the block whose Neighbors are of interest.
Returns:
Iterator pointing one past the Neighbor of the block with supplied block id.
Referenced by areNeighbors(), areSingularityNeighbors(), chopDomain(), findSingularities(), getOffset(), getRotationIdentifier(), getTransformedBlock(), printClassData(), transformBox(), and transformBoxContainer().
NeighborIterator SAMRAI::hier::BaseGridGeometry::find (const BlockId & block_id, const BlockId & nbr_block_id) [inline]
Create iterator pointing to the Neighbor with block id nbr_block_id of the block with block id block_id.
Parameters:
[in] block_id The block id of the block whose Neighbors are of interest.
[in] nbr_block_id The block id of the Neighbor of interest.
Returns:
Iterator pointing to the requested Neighbor of the block with supplied block id.
Referenced by chopDomain(), and findSingularities().
ConstNeighborIterator SAMRAI::hier::BaseGridGeometry::begin (const BlockId & block_id) const [inline]
Create iterator pointing to the first Neighbor of the block with the supplied block id.
Parameters:
[in] block_id The block id of the block whose Neighbors are of interest.
Returns:
Iterator pointing to the first Neighbor of the block with supplied block id.
ConstNeighborIterator SAMRAI::hier::BaseGridGeometry::end (const BlockId & block_id) const [inline]
Create iterator pointing one past the last Neighbor of the block with the supplied block id.
Parameters:
[in] block_id The block id of the block whose Neighbors are of interest.
Returns:
Iterator pointing one past the Neighbor of the block with supplied block id.
ConstNeighborIterator SAMRAI::hier::BaseGridGeometry::find (const BlockId & block_id, const BlockId & nbr_block_id) const [inline]
Create iterator pointing to the Neighbor with block id nbr_block_id of the block with block id block_id.
Parameters:
[in] block_id The block id of the block whose Neighbors are of interest.
[in] nbr_block_id The block id of the Neighbor of interest.
Returns:
Iterator pointing to the requested Neighbor of the block with supplied block id.
void SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput (const boost::shared_ptr< tbox::Database > & input_db) [protected]
Read multiblock metadata input from the input database.
Parameters:
[in] input_db
Precondition:
input_db
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::coalesce(), d_dim, SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), findSingularities(), SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::hier::IntVector::getOne(), getRotationIdentifier(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BoxContainer::grow(), SAMRAI::hier::BoxContainer::intersectBoxes(), SAMRAI::tbox::Utilities::intToString(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::hier::Box::numberCells(), registerNeighbors(), SAMRAI::hier::Box::rotate(), SAMRAI::hier::Box::setBlockId(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), SAMRAI::hier::BoxContainer::simplify(), SAMRAI::hier::Box::size(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, TBOX_ERROR, SAMRAI::hier::BoxContainer::unorder(), and SAMRAI::hier::Box::upper().
Member Data Documentation
boost::shared_ptr<TransferOperatorRegistry> SAMRAI::hier::BaseGridGeometry::d_transfer_operator_registry [protected]
The holder of all the transfer operators.
Referenced by addCoarsenOperator(), addRefineOperator(), addTimeInterpolateOperator(), getMaxTransferOpStencilWidth(), lookupCoarsenOperator(), lookupRefineOperator(), lookupTimeInterpolateOperator(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry(), and setMinTransferOpStencilWidth().
tbox::Dimension SAMRAI::hier::BaseGridGeometry::d_dim [protected]
Referenced by adjustMultiblockPatchLevelBoundaries(), BaseGridGeometry(), chopDomain(), computeBoundaryBoxesOnLevel(), computeBoxTouchingBoundaries(), computePhysicalDomain(), findPatchesTouchingBoundaries(), findSingularities(), getBoundaryBoxes(), getDim(), getOffset(), getPeriodicShift(), readBlockDataFromInput(), registerNeighbors(), setBoundaryBoxes(), setGeometryDataOnPatch(), setGeometryOnPatches(), setPhysicalDomain(), and setUpRatios().
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BaseGridGeometry.h
source/SAMRAI/hier/BaseGridGeometry.C