SAMRAI: SAMRAI::xfer::RefineClasses Class Reference
SAMRAI::xfer::RefineClasses Class Reference
Maintain a collection of refine items and organize them into equivalence classes.
#include <source/SAMRAI/xfer/RefineClasses.h>
Classes
struct Data
Data structure used to describe a refinement operation between patch data components on an AMR hierarchy.
Public Member Functions
RefineClasses ()
The constructor creates an empty array of refine classes.
~RefineClasses ()
The destructor destroys the refinement data items owned by this object.
int getNumberOfEquivalenceClasses () const
Return number of equivalence classes maintained by this object.
int getNumberOfRefineItems () const
Return total number of refine items that have been registered and stored in the RefineClasses object.
const RefineClasses::Data & getClassRepresentative (int equiv_class_index) const
Get representative item for a given equivalence class index.
RefineClasses::Data & getRefineItem (const int refine_item_array_id)
Get a refine item from the array of all refine items held by this object.
std::list< int >::iterator getIterator (int equiv_class_index)
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
std::list< int >::iterator getIteratorEnd (int equiv_class_index)
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
void insertEquivalenceClassItem (RefineClasses::Data &data_item, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >())
Given a RefineClasses::Data object, insert it into the proper equivalence class.
bool itemIsValid (const RefineClasses::Data &data_item, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >()) const
Check refine data item for validity.
bool classesMatch (const boost::shared_ptr< RefineClasses > &test_classes, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >()) const
Compare RefineClasses object with another RefineClasses object; return true if they match, else false.
bool itemsAreEquivalent (const RefineClasses::Data &data1, const RefineClasses::Data &data2, const boost::shared_ptr< hier::PatchDescriptor > &descriptor=boost::shared_ptr< hier::PatchDescriptor >()) const
Compare RefineClasses::Data objects for equivalence; return true if equivalent, else false.
void increaseRefineItemArraySize (const int size)
Increase the allocated size of the array storing refine items.
void printClassData (std::ostream &stream) const
Print data for all refine items to the specified output stream.
void printRefineItem (std::ostream &stream, const RefineClasses::Data &data) const
Print single refine item to the specified output stream.
Detailed Description
Maintain a collection of refine items and organize them into equivalence classes.
RefineClasses is used by the RefineSchedule and RefineAlgorithm classes to manage refinement data items that describe communication of patch data on an AMR hierarchy. Specifically, this class organizes these items into equivalence clases, so that items are grouped together if they have the same data communication dependencies. See documentation for the method itemsAreEquivalent() for definition of equivalence.
Constructor & Destructor Documentation
SAMRAI::xfer::RefineClasses::RefineClasses ()
The constructor creates an empty array of refine classes.
SAMRAI::xfer::RefineClasses::~RefineClasses ()
The destructor destroys the refinement data items owned by this object.
Member Function Documentation
int SAMRAI::xfer::RefineClasses::getNumberOfEquivalenceClasses () const [inline]
Return number of equivalence classes maintained by this object.
Referenced by classesMatch(), getClassRepresentative(), getIterator(), and getIteratorEnd().
int SAMRAI::xfer::RefineClasses::getNumberOfRefineItems () const [inline]
Return total number of refine items that have been registered and stored in the RefineClasses object.
const RefineClasses::Data& SAMRAI::xfer::RefineClasses::getClassRepresentative (int equiv_class_index) const [inline]
Get representative item for a given equivalence class index.
Returns:
Given index of an existing equivalence class, one item from that class is returned.
Parameters:
[in] equiv_class_index
Precondition:
(equiv_class_index >= 0) && (equiv_class_index < getNumberOfEquivalenceClasses())
References getNumberOfEquivalenceClasses(), and TBOX_ASSERT.
Referenced by classesMatch().
RefineClasses::Data& SAMRAI::xfer::RefineClasses::getRefineItem (const int refine_item_array_id) [inline]
Get a refine item from the array of all refine items held by this object.
The internal storage of the refine items held by this class is not controlled by the user, so this method is intended for use when looping over all of the items, from 0 to getNumberOfRefineItems()-1, or when looping over the integers in the List obtained from getIterator().
Returns:
A refine classes data object identified by an integer id.
Parameters:
[in] refine_item_array_id
std::list<int>::iterator SAMRAI::xfer::RefineClasses::getIterator (int equiv_class_index) [inline]
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
The number of quivalence classes can be determined via the getNumberOfEquivalenceClasses() member function. Valid integer arguments are from 0 to getNumberOfEquivalenceClasses()-1.
Note:
The list should not be modified through this iterator.
Returns:
The iterator iterates over a list of integers which are array ids that can be passed into getRefineItem(). The array ids in a single list all correspond to refine items in a single equivalence class.
Parameters:
[in] equiv_class_index
Precondition:
(equiv_class_index >= 0) && (equiv_class_index < getNumberOfEquivalenceClasses())
References getNumberOfEquivalenceClasses(), and TBOX_ASSERT.
std::list<int>::iterator SAMRAI::xfer::RefineClasses::getIteratorEnd (int equiv_class_index) [inline]
Return an iterator for the list of array ids corresponding to the equivalence class with the given integer index.
The number of quivalence classes can be determined via the getNumberOfEquivalenceClasses() member function. Valid integer arguments are from 0 to getNumberOfEquivalenceClasses()-1.
Note:
The list should not be modified through this iterator.
Returns:
The iterator iterates over a list of integers which are array ids that can be passed into getRefineItem(). The array ids in a single list all correspond to refine items in a single equivalence class.
Parameters:
[in] equiv_class_index
Precondition:
(equiv_class_index >= 0) && (equiv_class_index < getNumberOfEquivalenceClasses())
References getNumberOfEquivalenceClasses(), and TBOX_ASSERT.
void SAMRAI::xfer::RefineClasses::insertEquivalenceClassItem (RefineClasses::Data & data_item, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>())
Given a RefineClasses::Data object, insert it into the proper equivalence class.
If the item belongs in an existing equivalence class, it will be added to that class. Otherwise, a new equivalence class will be created for this item. The integer class index in the data item will set to the index of the equivalence class into which it is inserted.
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Parameters:
[in,out] data_item
[in] descriptor
Precondition:
itemIsValid(data, descriptor)
References SAMRAI::xfer::RefineClasses::Data::d_class_index, itemIsValid(), SAMRAI::tbox::perr, printRefineItem(), and TBOX_ERROR.
bool SAMRAI::xfer::RefineClasses::itemIsValid (const RefineClasses::Data & data_item, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>()) const
Check refine data item for validity.
A refine data item is invalid if any of its patch data integer ids are negative, or if its scratch data does not have sufficient ghost width for the stencil of the refine operator or the fill pattern, or if it is not a valid operation to copy from source data to scratch data or from scratch data to destination data, or when time interpolation is used the old and new time patch data enties are either undefined or their types do not match the source data type.
An error will occur with a descriptive message if the item is invalid.
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Returns:
True if the item is valid; else false.
Parameters:
[in] data_item
[in] descriptor
References SAMRAI::xfer::RefineClasses::Data::d_dst, SAMRAI::xfer::RefineClasses::Data::d_oprefine, SAMRAI::xfer::RefineClasses::Data::d_scratch, SAMRAI::xfer::RefineClasses::Data::d_src, SAMRAI::xfer::RefineClasses::Data::d_src_tnew, SAMRAI::xfer::RefineClasses::Data::d_src_told, SAMRAI::xfer::RefineClasses::Data::d_time_interpolate, SAMRAI::xfer::RefineClasses::Data::d_var_fill_pattern, SAMRAI::hier::VariableDatabase::getDatabase(), SAMRAI::hier::IntVector::getDim(), and TBOX_ERROR.
Referenced by insertEquivalenceClassItem().
bool SAMRAI::xfer::RefineClasses::classesMatch (const boost::shared_ptr< RefineClasses > & test_classes, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>()) const
Compare RefineClasses object with another RefineClasses object; return true if they match, else false.
This method checks whether all equivalence classes match between this RefineClasses object and the argument object. To match, the number of equivalence classes held by the objects must be the same and each equivalence class in this object must match the class with the same equivalence class number in the argument object. Two classes match if they have the same number of items and their representative items are equialvent as defined by the method itemsAreEquivalent().
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Returns:
true if test_classes matches this object.
Parameters:
[in] test_classes RefineClasses object to compare with this.
[in] descriptor
References getClassRepresentative(), getNumberOfEquivalenceClasses(), itemsAreEquivalent(), and NULL_USE.
bool SAMRAI::xfer::RefineClasses::itemsAreEquivalent (const RefineClasses::Data & data1, const RefineClasses::Data & data2, const boost::shared_ptr< hier::PatchDescriptor > & descriptor = boost::shared_ptr<hier::PatchDescriptor>()) const
Compare RefineClasses::Data objects for equivalence; return true if equivalent, else false.
Two RefineClasses::Data objects are equivalent if and only if the following conditions hold:
Each corresponding patch data component (d_dst, d_src, etc.) must have the same patch data type and ghost cell width.
The d_time_interpolate flag must be true or false for both objects. If true, each corresponding patch data component (d_src_told, d_src_tnew) must have the same data type and ghost cell width. Also, the time interpolate operators must be the same type.
d_fine_bdry_reps_var flag must have the same value for each object.
The refinement operator ptr d_oprefine must be null or non-null for both objects. If non-null, both operators must have the same stencil width.
The type of the d_var_fill_pattern must be the same for both objects.
If a null patch descriptor argument is passed (or ommitted), the descriptor associated with the variable database Singleton object will be used.
Returns:
true if test_classes matches this object.
Parameters:
[in] data1 RefineClasses::Data object to compare.
[in] data2 RefineClasses::Data object to compare.
[in] descriptor
References SAMRAI::xfer::RefineClasses::Data::d_dst, SAMRAI::xfer::RefineClasses::Data::d_fine_bdry_reps_var, SAMRAI::xfer::RefineClasses::Data::d_oprefine, SAMRAI::xfer::RefineClasses::Data::d_scratch, SAMRAI::xfer::RefineClasses::Data::d_src, SAMRAI::xfer::RefineClasses::Data::d_src_tnew, SAMRAI::xfer::RefineClasses::Data::d_src_told, SAMRAI::xfer::RefineClasses::Data::d_time_interpolate, SAMRAI::xfer::RefineClasses::Data::d_var_fill_pattern, and SAMRAI::hier::VariableDatabase::getDatabase().
Referenced by classesMatch().
void SAMRAI::xfer::RefineClasses::increaseRefineItemArraySize (const int size) [inline]
Increase the allocated size of the array storing refine items.
This should be used in cases where there is a large number of refine items being registered with the RefineAlgorithm, to avoid frequent resizing of the array. If the size argument is less than the current allocated size of the array, then the size of the array is not changed.
Parameters:
[in] size
void SAMRAI::xfer::RefineClasses::printClassData (std::ostream & stream) const
Print data for all refine items to the specified output stream.
Parameters:
[out] stream
References printRefineItem().
void SAMRAI::xfer::RefineClasses::printRefineItem (std::ostream & stream, const RefineClasses::Data & data) const
Print single refine item to the specified output stream.
Parameters:
[out] stream
[in] data
References SAMRAI::xfer::RefineClasses::Data::d_dst, SAMRAI::xfer::RefineClasses::Data::d_fine_bdry_reps_var, SAMRAI::xfer::RefineClasses::Data::d_oprefine, SAMRAI::xfer::RefineClasses::Data::d_optime, SAMRAI::xfer::RefineClasses::Data::d_scratch, SAMRAI::xfer::RefineClasses::Data::d_src, SAMRAI::xfer::RefineClasses::Data::d_src_tnew, SAMRAI::xfer::RefineClasses::Data::d_src_told, SAMRAI::xfer::RefineClasses::Data::d_tag, SAMRAI::xfer::RefineClasses::Data::d_time_interpolate, SAMRAI::xfer::RefineClasses::Data::d_var_fill_pattern, and SAMRAI::hier::VariableDatabase::getDatabase().
Referenced by insertEquivalenceClassItem(), and printClassData().
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/RefineClasses.h
source/SAMRAI/xfer/RefineClasses.C