SAMRAI: SAMRAI::hier::BoxContainerSingleBlockIterator Class Reference
SAMRAI::hier::BoxContainerSingleBlockIterator Class Reference
BoxContainer iterator picking items with a specified BlockId.
#include <source/SAMRAI/hier/BoxContainerSingleBlockIterator.h>
Public Member Functions
~BoxContainerSingleBlockIterator ()
Destructor.
BoxContainerSingleBlockIterator & operator= (const BoxContainerSingleBlockIterator &r)
Assignment operator.
const Box & operator* () const
Dereference operator mimicking a pointer dereference.
const Box * operator-> () const
Dereference operator mimicking a pointer dereference.
bool operator== (const BoxContainerSingleBlockIterator &r) const
Equality comparison.
bool operator!= (const BoxContainerSingleBlockIterator &r) const
Inequality comparison.
BoxContainerSingleBlockIterator & operator++ ()
Pre-increment iterator.
BoxContainerSingleBlockIterator operator++ (int)
Post-increment iterator.
int count () const
Returns the number of BoxContainers being iterated through.
Friends
class BoxContainer
Detailed Description
BoxContainer iterator picking items with a specified BlockId.
This iterator runs through all Boxes in a BoxContainer that has the given BlockId. The iterator runs through the Boxes in the order they appear in the BoxContainer, skipping over Boxes that do not have the specified owner rank.
Constructor & Destructor Documentation
SAMRAI::hier::BoxContainerSingleBlockIterator::~BoxContainerSingleBlockIterator ()
Destructor.
Member Function Documentation
BoxContainerSingleBlockIterator& SAMRAI::hier::BoxContainerSingleBlockIterator::operator= (const BoxContainerSingleBlockIterator & r) [inline]
Assignment operator.
const Box& SAMRAI::hier::BoxContainerSingleBlockIterator::operator* () const [inline]
Dereference operator mimicking a pointer dereference.
const Box* SAMRAI::hier::BoxContainerSingleBlockIterator::operator-> () const [inline]
Dereference operator mimicking a pointer dereference.
bool SAMRAI::hier::BoxContainerSingleBlockIterator::operator== (const BoxContainerSingleBlockIterator & r) const [inline]
Equality comparison.
bool SAMRAI::hier::BoxContainerSingleBlockIterator::operator!= (const BoxContainerSingleBlockIterator & r) const [inline]
Inequality comparison.
BoxContainerSingleBlockIterator & SAMRAI::hier::BoxContainerSingleBlockIterator::operator++ ()
Pre-increment iterator.
Pre-increment increment the iterator and returns the incremented state.
References SAMRAI::hier::BoxContainer::end().
BoxContainerSingleBlockIterator SAMRAI::hier::BoxContainerSingleBlockIterator::operator++ (int)
Post-increment iterator.
Post-increment saves the iterator, increment it and returns the saved iterator.
References SAMRAI::hier::BoxContainer::end().
int SAMRAI::hier::BoxContainerSingleBlockIterator::count () const
Returns the number of BoxContainers being iterated through.
References SAMRAI::hier::BoxContainer::begin(), and SAMRAI::hier::BoxContainer::end().
Friends And Related Function Documentation
friend class BoxContainer [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxContainerSingleBlockIterator.h
source/SAMRAI/hier/BoxContainerSingleBlockIterator.C