SAMRAI: SAMRAI::hier::SingularityFinder Class Reference
SAMRAI::hier::SingularityFinder Class Reference
Class SingularityFinder implements an algorithm to find multiblock singularities based on the relationships between blocks that touch on an entire face.
#include <source/SAMRAI/hier/SingularityFinder.h>
Public Member Functions
SingularityFinder (const tbox::Dimension &dim)
~SingularityFinder ()
Destructor.
void findSingularities (std::set< std::set< BlockId > > &singularity_blocks, const BoxContainer &domain_boxes, const BaseGridGeometry &grid_geometry, const std::map< BoxId, std::map< BoxId, int > > &face_neighbors)
Find the singularities based on the relationship between face neighbors.
Detailed Description
Class SingularityFinder implements an algorithm to find multiblock singularities based on the relationships between blocks that touch on an entire face.
Constructor & Destructor Documentation
SAMRAI::hier::SingularityFinder::SingularityFinder (const tbox::Dimension & dim)
References SAMRAI::tbox::Dimension::getValue().
SAMRAI::hier::SingularityFinder::~SingularityFinder ()
Destructor.
Member Function Documentation
void SAMRAI::hier::SingularityFinder::findSingularities (std::set< std::set< BlockId > > & singularity_blocks, const BoxContainer & domain_boxes, const BaseGridGeometry & grid_geometry, const std::map< BoxId, std::map< BoxId, int > > & face_neighbors)
Find the singularities based on the relationship between face neighbors.
The singularity information is computed based on the face_neighbors input. In the nested map of maps face_neighbors, the key for the outer map is a BoxId of a Box in the domain_boxes input (the reference Box). For each reference Box,the inner map contains information about all its face neighbors.
Each face neighbor has a BoxId as its identifying key and an integer to indicate which face of the reference Box the neighbor touches. The formula for the integer identifier is: For each normal direction D = 0,...,NDIM-1, the lower face identifier is 2*D and the upper face identifier is 2*D+1.
The domain_boxes input is a representation of the physical domain that must be set up such that all face neighbor relationships between Boxes touch each other across the entirety of each Box face.
Parameters:
[out] singularity_blocks Output for the computed singularities. The outer set is the container of all singularities, while each inner set contains all of the BlockIds for the blocks that touch one singularity.
[in] domain_boxes Representation of the physical domain.
[in] grid_geometry The grid geometry describing the multiblock layout.
[in] face_neighbors Input information about face neighbor relationships, described above.
References SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::BaseGridGeometry::getNumberBlocks(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/SingularityFinder.h
source/SAMRAI/hier/SingularityFinder.C