SAMRAI: SAMRAI::pdat::ArrayData< TYPE > Class Template Reference
SAMRAI::pdat::ArrayData< TYPE > Class Template Reference
Class ArrayData<TYPE> is a basic templated array structure defined over the index space of a box (with a specified depth) that provides the support for the various standard array-based patch data subclasses.
#include <source/SAMRAI/pdat/ArrayData.h>
Public Types
typedef ArrayDataIterator iterator
Public Member Functions
ArrayData (const hier::Box &box, unsigned int depth)
~ArrayData ()
bool isInitialized () const
Returns true when the array has been properly initialized and storage has been allocated; otherwise, return false.
void undefineData ()
const hier::Box & getBox () const
unsigned int getDepth () const
size_t getOffset () const
TYPE * getPointer (const unsigned int d=0)
const TYPE * getPointer (const unsigned int d=0) const
TYPE & operator() (const hier::Index &i, const unsigned int d)
const TYPE & operator() (const hier::Index &i, const unsigned int d) const
void copy (const ArrayData< TYPE > &src, const hier::Box &box)
void copy (const ArrayData< TYPE > &src, const hier::Box &box, const hier::IntVector &src_shift)
void copy (const ArrayData< TYPE > &src, const hier::Box &box, const hier::Transformation &transformation)
void copy (const ArrayData< TYPE > &src, const hier::BoxContainer &boxes, const hier::IntVector &src_shift)
void copy (const ArrayData< TYPE > &src, const hier::BoxContainer &boxes, const hier::Transformation &transformation)
void copyDepth (unsigned int dst_depth, const ArrayData< TYPE > &src, unsigned int src_depth, const hier::Box &box)
void sum (const ArrayData< TYPE > &src, const hier::Box &box)
void sum (const ArrayData< TYPE > &src, const hier::Box &box, const hier::IntVector &src_shift)
void sum (const ArrayData< TYPE > &src, const hier::BoxContainer &boxes, const hier::IntVector &src_shift)
size_t getDataStreamSize (const hier::BoxContainer &boxes, const hier::IntVector &src_shift) const
void packStream (tbox::MessageStream &stream, const hier::Box &dest_box, const hier::IntVector &src_shift) const
void packStream (tbox::MessageStream &stream, const hier::Box &dest_box, const hier::Transformation &src_shift) const
void packStream (tbox::MessageStream &stream, const hier::BoxContainer &dest_boxes, const hier::IntVector &src_shift) const
void packStream (tbox::MessageStream &stream, const hier::BoxContainer &dest_boxes, const hier::Transformation &transformation) const
void unpackStream (tbox::MessageStream &stream, const hier::Box &dest_box, const hier::IntVector &src_offset)
void unpackStream (tbox::MessageStream &stream, const hier::BoxContainer &dest_boxes, const hier::IntVector &src_offset)
void unpackStreamAndSum (tbox::MessageStream &stream, const hier::Box &dest_box, const hier::IntVector &src_offset)
void unpackStreamAndSum (tbox::MessageStream &stream, const hier::BoxContainer &dest_boxes, const hier::IntVector &src_offset)
void fillAll (const TYPE &t)
void fillAll (const TYPE &t, const hier::Box &box)
void fill (const TYPE &t, const unsigned int d=0)
void fill (const TYPE &t, const hier::Box &box, const unsigned int d=0)
void getFromRestart (const boost::shared_ptr< tbox::Database > &restart_db)
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db) const
const tbox::Dimension & getDim () const
bool isValid ()
Returns true if the array is valid.
Static Public Member Functions
static bool canEstimateStreamSizeFromBox ()
static size_t getSizeOfData (const hier::Box &box, unsigned int depth)
Detailed Description
template<class TYPE>
class SAMRAI::pdat::ArrayData< TYPE >
Class ArrayData<TYPE> is a basic templated array structure defined over the index space of a box (with a specified depth) that provides the support for the various standard array-based patch data subclasses.
The data storage is in (i,...,k,d) order, where i,...,k indicates spatial indices and the d indicates the component at that location. Memory allocation is in column-major ordering (e.g., Fortran style) so that the leftmost index runs fastest in memory.
The data type TYPE must define a default constructor (that takes no arguments) and also the assignment operator. Note that a number of functions only work for standard built-in types (bool, char, double, float, and int). To use this class with other user-defined types, many of these functions will need to be specialized, especially those that deal with message packing and unpacking.
Member Typedef Documentation
template<class TYPE> typedef ArrayDataIterator SAMRAI::pdat::ArrayData< TYPE >::iterator
The array data iterator iterates over the elements of a box associated with an ArrayData object. This typedef is convenient link to the ArrayDataIterator class.
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::ArrayData< TYPE >::ArrayData (const hier::Box & box, unsigned int depth) [inline]
Construct an array data object.
Parameters:
box Const reference to box object describing the spatial extents of the index space associated with the array data object.
depth Integer number of data values at each spatial location in the array.
Precondition:
depth > 0
References TBOX_ASSERT, and SAMRAI::pdat::ArrayData< TYPE >::undefineData().
template<class TYPE > SAMRAI::pdat::ArrayData< TYPE >::~ArrayData () [inline]
The destructor for an array data object releases all memory allocated for the array elements.
Member Function Documentation
template<class TYPE > bool SAMRAI::pdat::ArrayData< TYPE >::canEstimateStreamSizeFromBox () [inline, static]
Static member function that returns true when the amount of buffer space in a message stream can be estimated from box only. For built-in types (bool, char, double, float, int, and dcomplex), this routine returns true. For other data types (template paramters) that may require special handling, a different implementation must be provided.
template<class TYPE > size_t SAMRAI::pdat::ArrayData< TYPE >::getSizeOfData (const hier::Box & box, unsigned int depth) [inline, static]
Static member function that returns the amount of memory space needed to store data of given depth on a box.
Note that this function is only defined for the standard data types: bool, char, double, float, int, and dcomplex. It must be provided for other template parameter types.
Returns:
size_t value indicating the amount of memory space needed for the data.
Parameters:
box Const reference to box object describing the spatial extents of the array data index region of interest.
depth Integer number of data values at each spatial location in the array.
References SAMRAI::tbox::MemoryUtilities::align(), and SAMRAI::hier::Box::size().
template<class TYPE > bool SAMRAI::pdat::ArrayData< TYPE >::isInitialized () const [inline]
Returns true when the array has been properly initialized and storage has been allocated; otherwise, return false.
Note: Only arrays that have been initialized can do anything useful.
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::undefineData () [inline]
Set the array data to an ``undefined'' state appropriate for the data type. For example, for float and double, this means setting data to signaling NaNs that cause a floating point assertion when used in a numerical expression without being set to valid values.
References SAMRAI::pdat::ArrayData< TYPE >::fillAll().
Referenced by SAMRAI::pdat::ArrayData< TYPE >::ArrayData().
template<class TYPE > const hier::Box & SAMRAI::pdat::ArrayData< TYPE >::getBox () const [inline]
Return the box over which the array is defined.
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::pdat::ArrayDataAccess::access(), SAMRAI::pdat::access(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::pdat::OutersideData< TYPE >::copy(), SAMRAI::pdat::OuterfaceData< TYPE >::copy(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth(), SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth2(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth2(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth2(), SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth2(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::solv::SimpleCellRobinBcCoefs::restoreDirichletData(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
template<class TYPE > unsigned int SAMRAI::pdat::ArrayData< TYPE >::getDepth () const [inline]
Return the depth (e.g., the number of data values at each spatial location) of this array.
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
template<class TYPE > size_t SAMRAI::pdat::ArrayData< TYPE >::getOffset () const [inline]
Return the offset (e.g., the number of data values for each depth component) of this array.
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
template<class TYPE > TYPE * SAMRAI::pdat::ArrayData< TYPE >::getPointer (const unsigned int d = 0) [inline]
Get a non-const pointer to the beginning of the given depth component of this data array.
Precondition:
(d >= 0) && (d < getDepth())
References TBOX_ASSERT.
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::pdat::ArrayDataAccess::access(), SAMRAI::pdat::access(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
template<class TYPE > const TYPE * SAMRAI::pdat::ArrayData< TYPE >::getPointer (const unsigned int d = 0) const [inline]
Get a const pointer to the beginning of the given depth component of this data array.
Precondition:
(d >= 0) && (d < getDepth())
References TBOX_ASSERT.
template<class TYPE > TYPE & SAMRAI::pdat::ArrayData< TYPE >::operator() (const hier::Index & i, const unsigned int d) [inline]
Return reference to value in this array associated with the given box index and depth component.
Precondition:
getDim() == i.getDim()
(d >= 0) && (d < getDepth())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > const TYPE & SAMRAI::pdat::ArrayData< TYPE >::operator() (const hier::Index & i, const unsigned int d) const [inline]
Return const reference to value in this array associated with the given box index and depth component.
Precondition:
getDim() == i.getDim()
(d >= 0) && (d < getDepth())
References TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::copy (const ArrayData< TYPE > & src, const hier::Box & box) [inline]
Copy data from the source array data object to this array data object on the specified index space region.
Note that this routine assumes that the source and destination box regions require no shifting to make them consistent. This routine will intersect the specified box with the source and destination boxes to find the region of intersection.
Parameters:
src Const reference to source array data object.
box Const reference to box object describing the spatial extents of the index space region over which to perform the copy operation. Note: the box is in either the source or destination index space (which are assumed to be the same).
Precondition:
(getDim() == src.getDim()) && (getDim() == box.getDim())
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT_OBJDIM_EQUALITY3.
Referenced by SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::solv::SimpleCellRobinBcCoefs::cacheDirichletData(), SAMRAI::pdat::OutersideData< TYPE >::copy(), SAMRAI::pdat::OuterfaceData< TYPE >::copy(), SAMRAI::pdat::ArrayData< TYPE >::copy(), and SAMRAI::math::ArrayDataBasicOps< TYPE >::scale().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::copy (const ArrayData< TYPE > & src, const hier::Box & box, const hier::IntVector & src_shift) [inline]
Copy data from the source array data object to this array data object on the specified index space region.
Note that this routine assumes that the source array box region must be shifted to be consistent with the destination (this) array box region. This routine will intersect the specified box with the destination box and shifted source box to find the region of intersection.
Parameters:
src Const reference to source array data object.
box Const reference to box object describing the spatial extents of the index space region over which to perform the copy operation. Note: the box is in the destination index space.
src_shift Const reference to shift vector used to put the source array data box into the index space region of this array data object.
References SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::IntVector::getZero(), and SAMRAI::hier::Box::shift().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::copy (const ArrayData< TYPE > & src, const hier::Box & box, const hier::Transformation & transformation) [inline]
References SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::hier::Box::empty(), SAMRAI::hier::Transformation::getBeginBlock(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Transformation::getEndBlock(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::NO_ROTATE, and SAMRAI::hier::Transformation::transform().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::copy (const ArrayData< TYPE > & src, const hier::BoxContainer & boxes, const hier::IntVector & src_shift) [inline]
Copy data from the source array data object to this array data object on the specified index space regions.
Note that this routine assumes that the source array box region must be shifted to be consistent with the destination (this) array box region. This routine will intersect the specified boxes with the destination box and shifted source box to find the regions of intersection.
Parameters:
src Const reference to source array data object.
boxes Const reference to box list describing the spatial extents of the index space regions over which to perform the copy operation. Note: the boxes are in the destination index space.
src_shift Const reference to shift vector used to put the source array data box into the index space region of this array data object.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::pdat::ArrayData< TYPE >::copy(), and SAMRAI::hier::BoxContainer::end().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::copy (const ArrayData< TYPE > & src, const hier::BoxContainer & boxes, const hier::Transformation & transformation) [inline]
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::pdat::ArrayData< TYPE >::copy(), and SAMRAI::hier::BoxContainer::end().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::copyDepth (unsigned int dst_depth, const ArrayData< TYPE > & src, unsigned int src_depth, const hier::Box & box) [inline]
Copy given source depth of source array data object to given destination depth of this array data object on the specified index space region.
Note that this routine assumes that the source and destination box regions require no shifting to make them consistent. This routine will intersect the specified box with the source and destination boxes to find the region of intersection.
Parameters:
dst_depth Integer depth of destination array.
src Const reference to source array data object.
src_depth Integer depth of source array.
box Const reference to box object describing the spatial extents of the index space region over which to perform the copy operation. Note: the box is in either the source or destination index space (which are assumed to be the same).
Precondition:
(0 <= dst_depth) && (dst_depth <= getDepth()))
(0 <= src_depth) && (src_depth <= src.getDepth())
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::isSpatiallyEqual(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::OutersideData< TYPE >::copyDepth(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth(), SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth(), SAMRAI::pdat::OutersideData< TYPE >::copyDepth2(), SAMRAI::pdat::OuternodeData< TYPE >::copyDepth2(), SAMRAI::pdat::OuterfaceData< TYPE >::copyDepth2(), and SAMRAI::pdat::OuteredgeData< TYPE >::copyDepth2().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::sum (const ArrayData< TYPE > & src, const hier::Box & box) [inline]
Add data from the source array data object to this array data object on the specified index space region.
Note that this routine assumes that the source and destination box regions require no shifting to make them consistent. This routine will intersect the specified box with the source and destination boxes to find the region of intersection.
Parameters:
src Const reference to source array data object.
box Const reference to box object describing the spatial extents of the index space region over which to perform the sum operation. Note: the box is in either the source or destination index space (which are assumed to be the same).
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), and SAMRAI::hier::Box::isSpatiallyEqual().
Referenced by SAMRAI::pdat::ArrayData< TYPE >::sum().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::sum (const ArrayData< TYPE > & src, const hier::Box & box, const hier::IntVector & src_shift) [inline]
Add data from the source array data object to this array data object on the specified index space region.
Note that this routine assumes that the source array box region must be shifted to be consistent with the destination (this) array box region. This routine will intersect the specified box with the destination box and shifted source box to find the region of intersection.
Parameters:
src Const reference to source array data object.
box Const reference to box object describing the spatial extents of the index space region over which to perform the sum operation. Note: the box is in the destination index space.
src_shift Const reference to shift vector used to put the source array data box into the index space region of this array data object.
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Box::shift(), and SAMRAI::pdat::ArrayData< TYPE >::sum().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::sum (const ArrayData< TYPE > & src, const hier::BoxContainer & boxes, const hier::IntVector & src_shift) [inline]
Add data from the source array data object to this array data object on the specified index space regions.
Note that this routine assumes that the source array box region must be shifted to be consistent with the destination (this) array box region. This routine will intersect the specified boxes with the destination box and shifted source box to find the regions of intersection.
Parameters:
src Const reference to source array data object.
boxes Const reference to box list describing the spatial extents of the index space regions over which to perform the sum operation. Note: the boxes are in the destination index space.
src_shift Const reference to shift vector used to put the source array data box into the index space region of this array data object.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), and SAMRAI::pdat::ArrayData< TYPE >::sum().
template<class TYPE > size_t SAMRAI::pdat::ArrayData< TYPE >::getDataStreamSize (const hier::BoxContainer & boxes, const hier::IntVector & src_shift) const [inline]
Calculate the number of bytes needed to stream the data living in the specified box domains. This routine is only defined for the built-in types of bool, char, double, float, int, and dcomplex. For all other types, a specialized implementation must be provided.
Parameters:
boxes Const reference to box list describing the spatial extents of the index space regions of interest. Note: the boxes are assumed to be in the index space of this array data object.
src_shift Const reference to vector used to shift the given boxes into the index space region of this array data object. Note: this argument is currently ignored.
Precondition:
(getDim() == src_shift.getDim())
References SAMRAI::hier::BoxContainer::getTotalSizeOfBoxes(), NULL_USE, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::packStream (tbox::MessageStream & stream, const hier::Box & dest_box, const hier::IntVector & src_shift) const [inline]
Pack data living on the specified index region into the stream.
Note that this routine assumes that the given box region must be shifted to be consistent with the source (this) array box region.
Parameters:
stream Reference to stream into which to pack data.
dest_box Const reference to box describing the spatial extent of the destination index space region of interest.
src_shift Const reference to vector used to shift the given box into the index space region of this (source) array data object.
Note: The shifted box must lie completely within the index space of this array data object. When assertion checking is active, the routine will abort if the shifted box is not contained in the index space of this array.
References SAMRAI::tbox::MessageStream::pack(), SAMRAI::hier::Box::shift(), and SAMRAI::hier::Box::size().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::packStream (tbox::MessageStream & stream, const hier::Box & dest_box, const hier::Transformation & src_shift) const [inline]
References SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::tbox::MessageStream::pack(), and SAMRAI::hier::Box::size().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxContainer & dest_boxes, const hier::IntVector & src_shift) const [inline]
Pack data living on the specified index regions into the stream.
Note that this routine assumes that the given box regions must be shifted to be consistent with the source (this) array box region.
Parameters:
stream Reference to stream into which to pack data.
dest_boxes Const reference to boxes describing the spatial extents of the destination index space regions of interest.
src_shift Const reference to vector used to shift the given boxes into the index space region of this (source) array data object.
Note: The shifted boxes must lie completely within the index space of this array. If compiled with assertions enabled, the routine will abort if the shifted boxes are not contained in the index space of this array.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::getTotalSizeOfBoxes(), SAMRAI::tbox::MessageStream::pack(), SAMRAI::hier::Box::shift(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::packStream (tbox::MessageStream & stream, const hier::BoxContainer & dest_boxes, const hier::Transformation & transformation) const [inline]
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::getTotalSizeOfBoxes(), SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::tbox::MessageStream::pack(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::Box & dest_box, const hier::IntVector & src_offset) [inline]
Unpack data from the stream into the index region specified.
Parameters:
stream Reference to stream from which to unpack data.
dest_box Const reference to box describing the spatial extent of the destination index space region of interest.
src_offset Const reference to vector used to offset box into the index space region of some (source) array data object. Currently, this argument is ignored.
Note: The given box must lie completely within the index space of this array data object. When assertion checking is active, the routine will abort if the box is not contained in the index space of this array.
References NULL_USE, SAMRAI::hier::Box::size(), and SAMRAI::tbox::MessageStream::unpack().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::unpackStream (tbox::MessageStream & stream, const hier::BoxContainer & dest_boxes, const hier::IntVector & src_offset) [inline]
Unpack data from the stream into the index regions specified.
Parameters:
stream Reference to stream from which to unpack data.
dest_boxes Const reference to box list describing the spatial extents of the destination index space regions of interest.
src_offset Const reference to vector used to offset the given boxes into the index space region of some (source) array data object. Currently, this argument is ignored.
Note: The given boxes must lie completely within the index space of this array data object. When assertion checking is active, the routine will abort if some box is not contained in the index space of this array.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::getTotalSizeOfBoxes(), NULL_USE, TBOX_ASSERT, and SAMRAI::tbox::MessageStream::unpack().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::unpackStreamAndSum (tbox::MessageStream & stream, const hier::Box & dest_box, const hier::IntVector & src_offset) [inline]
Unpack data from the stream and add to the array in the index region specified.
Parameters:
stream Reference to stream from which to unpack data.
dest_box Const reference to box describing the spatial extent of the destination index space region of interest.
src_offset Const reference to vector used to offset the given box into the index space region of some (source) array data object. Currently, this argument is ignored.
Note: The given box must lie completely within the index space of this array data object. When assertion checking is active, the routine will abort if the box is not contained in the index space of this array.
References NULL_USE, SAMRAI::hier::Box::size(), and SAMRAI::tbox::MessageStream::unpack().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::unpackStreamAndSum (tbox::MessageStream & stream, const hier::BoxContainer & dest_boxes, const hier::IntVector & src_offset) [inline]
Unpack data from the stream and ad to the array in the index region specified.
Parameters:
stream Reference to stream from which to unpack data.
dest_boxes Const reference to box list describing the spatial extents of the destination index space regions of interest.
src_offset Const reference to vector used to offset the given boxes into the index space region of some (source) array data object. Currently, this argument is ignored.
Note: The given boxes must lie completely within the index space of this array. If compiled with assertions enabled, the routine will abort if some box is not contained in the index space of this array.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::getTotalSizeOfBoxes(), NULL_USE, TBOX_ASSERT, and SAMRAI::tbox::MessageStream::unpack().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::fillAll (const TYPE & t) [inline]
Fill all array values with value t.
References SAMRAI::hier::Box::empty().
Referenced by SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), and SAMRAI::pdat::ArrayData< TYPE >::undefineData().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::fillAll (const TYPE & t, const hier::Box & box) [inline]
Fill all array values within the box with value t.
References SAMRAI::pdat::ArrayData< TYPE >::fill().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::fill (const TYPE & t, const unsigned int d = 0) [inline]
Fill all array values associated with depth component d with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References SAMRAI::hier::Box::empty(), and TBOX_ASSERT.
Referenced by SAMRAI::pdat::ArrayData< TYPE >::fillAll().
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::fill (const TYPE & t, const hier::Box & box, const unsigned int d = 0) [inline]
Fill all array values associated with depth component d within the box with the value t.
Precondition:
(d >= 0) && (d < getDepth())
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::offset(), SAMRAI::hier::Box::size(), and TBOX_ASSERT.
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::getFromRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline]
Check to make sure that the class version and restart file version are equal. If so, read in data from restart database.
Precondition:
restart_db
References TBOX_ASSERT, and TBOX_ERROR.
template<class TYPE > void SAMRAI::pdat::ArrayData< TYPE >::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) const [inline]
Write out array data object data to restart database.
Precondition:
restart_db
References TBOX_ASSERT.
template<class TYPE > const tbox::Dimension & SAMRAI::pdat::ArrayData< TYPE >::getDim () const [inline]
Return the dimension of this object.
References SAMRAI::hier::Box::getDim().
Referenced by SAMRAI::math::ArrayDataNormOpsReal< TYPE >::abs(), SAMRAI::math::ArrayDataNormOpsInteger::abs(), SAMRAI::math::ArrayDataNormOpsComplex::abs(), SAMRAI::math::ArrayDataBasicOps< TYPE >::add(), SAMRAI::math::ArrayDataBasicOps< TYPE >::addScalar(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axmy(), SAMRAI::math::ArrayDataBasicOps< TYPE >::axpy(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::compareToScalarWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::computeConstrProdPosWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::divide(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataBufferOperationOnBox(), SAMRAI::pdat::ArrayDataOperationUtilities< TYPE, OP >::doArrayDataOperationOnBox(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dot(), SAMRAI::math::ArrayDataNormOpsComplex::dot(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::dotWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::integral(), SAMRAI::math::ArrayDataNormOpsComplex::integral(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::ArrayDataNormOpsComplex::L1Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::L1NormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::L1NormWithControlVolume(), SAMRAI::math::ArrayDataBasicOps< TYPE >::linearSum(), SAMRAI::math::ArrayDataBasicOps< TYPE >::max(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::ArrayDataNormOpsComplex::maxNorm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::maxNormWithControlVolume(), SAMRAI::math::ArrayDataNormOpsComplex::maxNormWithControlVolume(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::min(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::ArrayDataBasicOps< TYPE >::multiply(), SAMRAI::math::ArrayDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::ArrayDataBasicOps< TYPE >::scale(), SAMRAI::math::ArrayDataBasicOps< TYPE >::setRandomValues(), SAMRAI::math::ArrayDataBasicOps< TYPE >::subtract(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::ArrayDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::ArrayDataMiscellaneousOpsReal< TYPE >::testReciprocalWithControlVolume(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsComplex::weightedL2Norm(), SAMRAI::math::ArrayDataNormOpsReal< TYPE >::weightedL2NormWithControlVolume(), and SAMRAI::math::ArrayDataNormOpsComplex::weightedL2NormWithControlVolume().
template<class TYPE > bool SAMRAI::pdat::ArrayData< TYPE >::isValid () [inline]
Returns true if the array is valid.
References SAMRAI::hier::Box::empty().
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/ArrayData.h
source/SAMRAI/pdat/ArrayData.C