SAMRAI: SAMRAI::hier::Connector Class Reference
SAMRAI::hier::Connector Class Reference
A container which holds relationship connections between two BoxLevels.
#include <source/SAMRAI/hier/Connector.h>
Classes
class Outputter
A class for outputting Connector.
Public Types
typedef BoxContainer NeighborSet
NeighborsSet is a clarifying typedef.
typedef
BoxNeighborhoodCollection::ConstIterator ConstNeighborhoodIterator
Type of the iterator over neighborhoods.
typedef
BoxNeighborhoodCollection::Iterator NeighborhoodIterator
Type of the iterator over neighborhoods.
typedef
BoxNeighborhoodCollection::ConstNeighborIterator ConstNeighborIterator
Type of the iterator over neighbors in a neighborhood.
typedef
BoxNeighborhoodCollection::NeighborIterator NeighborIterator
Type of the iterator over neighbors in a neighborhood.
Public Member Functions
Connector (const tbox::Dimension &dim)
Creates an uninitialized Connector object in the distributed state.
Connector (const tbox::Dimension &dim, tbox::Database &restart_db)
Creates a Connector which is initialized from a restart database.
Connector (const Connector &other)
Copy constructor.
Connector (const BoxLevel &base_box_level, const BoxLevel &head_box_level, const IntVector &base_width, const BoxLevel::ParallelState parallel_state=BoxLevel::DISTRIBUTED)
Initialize a Connector with no defined relationships.
virtual ~Connector ()
Destructor.
void clear ()
Clear the Connector, putting it into an uninitialized state.
void clearNeighborhoods ()
Clear the Connector's neighborhood relations.
bool isFinalized () const
Returns true if the object has been finalized.
ConstNeighborhoodIterator begin () const
Iterator pointing to the first neighborhood.
NeighborhoodIterator begin ()
Iterator pointing to the first neighborhood.
ConstNeighborhoodIterator end () const
Iterator pointing one past the last neighborhood.
NeighborhoodIterator end ()
Iterator pointing one past the last neighborhood.
ConstNeighborIterator begin (const ConstNeighborhoodIterator &nbrhd) const
Iterator pointing to the first neighbor in nbrhd.
NeighborIterator begin (NeighborhoodIterator &nbrhd)
Iterator pointing to the first neighbor in nbrhd.
ConstNeighborIterator end (const ConstNeighborhoodIterator &nbrhd) const
Iterator pointing one past the last neighbor in nbrhd.
NeighborIterator end (NeighborhoodIterator &nbrhd)
Iterator pointing one past the last neighbor in nbrhd.
ConstNeighborhoodIterator findLocal (const BoxId &box_id) const
Returns an Iterator pointing to the neighborhood of box_id-- localized version.
NeighborhoodIterator findLocal (const BoxId &box_id)
Returns an Iterator pointing to the neighborhood of box_id-- localized version.
ConstNeighborhoodIterator find (const BoxId &box_id) const
Returns an Iterator pointing to the neighborhood of box_id-- globalized version.
bool localNeighborhoodsEqual (const Connector &other) const
Returns true if the local neighborhoods of this and other are the same.
bool neighborhoodEqual (const BoxId &box_id, const Connector &other) const
Returns true if the neighborhood of the supplied BoxId of this and other are the same.
bool hasNeighborSet (const BoxId &box_id) const
Return true if a neighbor set exists for the specified BoxId.
bool hasLocalNeighbor (const BoxId &box_id, const Box &neighbor) const
Return true if the supplied box is in the neighborhood of the supplied BoxId.
void getNeighborBoxes (const BoxId &box_id, BoxContainer &nbr_boxes) const
Return the neighbor set for the specified BoxId.
void getLocalNeighbors (BoxContainer &neighbors) const
Return all neighbors for all neighborhoods.
void getLocalNeighbors (std::map< BlockId, BoxContainer > &neighbors) const
Return all neighbors for all neighborhoods segragated by BlockId.
int numLocalNeighbors (const BoxId &box_id) const
Returns the number of neighbors in the neighborhood with the supplied BoxId.
int numLocalEmptyNeighborhoods () const
Returns the number of empty neighborhoods in the Connector.
void getLocalOwners (std::set< int > &owners) const
Places the ranks of the processors owning all neighbors into owners.
void getLocalOwners (ConstNeighborhoodIterator &base_boxes_itr, std::set< int > &owners) const
Places the ranks of the processors owning the neighbors of the Box pointed to by base_boxes_itr into owners.
void finalizeContext ()
Enforces implicit class invariants and removes non-local neighbors from relationships.
void setBase (const BoxLevel &new_base, bool finalize_context=false)
Change the Connector base to new_base. If finalize_context is true then this is the last atomic change being made and finalizeContext should be called.
const BoxLevel & getBase () const
Return a reference to the base BoxLevel.
void setHead (const BoxLevel &new_head, bool finalize_context=false)
Change the Connector head to new_head. If finalize_context is true then this is the last atomic change being made and finalizeContext should be called.
const BoxLevel & getHead () const
Return a reference to the head BoxLevel.
const IntVector & getRatio () const
Get the refinement ratio between the base and head BoxLevels.
bool ratioIsExact () const
Whether the ratio given by getRatio() is exact.
bool getHeadCoarserFlag () const
Return true if head BoxLevel is coarser than base BoxLevel.
bool isLocal () const
Return true if the Connector contains only relationships to local Boxes.
virtual Connector * createLocalTranspose () const
Create and return this Connector's transpose, assuming that all relationships are local (no remote neighbors).
virtual Connector * createTranspose () const
Create and return this Connector's transpose.
Connector & operator= (const Connector &rhs)
Assignment operator.
bool operator== (const Connector &rhs) const
Equality operator checks relationship data, Connector width and equality of base and head Box pointers.
bool operator!= (const Connector &rhs) const
Inequality operator checks the same data that equality operator checks.
void setParallelState (const BoxLevel::ParallelState parallel_state)
Set the parallel distribution state.
BoxLevel::ParallelState getParallelState () const
Return the current parallel state.
const tbox::SAMRAI_MPI & getMPI () const
Returns the MPI communication object, which is always that of the base BoxLevel.
void setWidth (const IntVector &new_width, bool finalize_context=false)
Change the Connector width to new_width. If finalize_context is true then this is the last atomic change being made and finalizeContext should be called.
const IntVector & getConnectorWidth () const
Return the Connector width associated with the relationships.
void shrinkWidth (const IntVector &new_width)
Shrink the width of the connector modifying the proximity relationships as needed.
int getLocalNumberOfNeighborSets () const
Return local number of neighbor sets.
int getLocalNumberOfRelationships () const
Return local number of relationships.
int getGlobalNumberOfNeighborSets () const
Return global number of neighbor sets.
int getGlobalNumberOfRelationships () const
Return global number of relationships.
void cacheGlobalReducedData () const
If global reduced data (global number of relationships, etc.) has not been updated, compute and cache them (communication required).
void putToRestart (const boost::shared_ptr< tbox::Database > &restart_db)
Write the neighborhoods to a restart database.
void writeNeighborhoodsToErrorStream (const std::string &border) const
Writes the neighborhoods to tbox::perr.
void writeNeighborhoodToStream (std::ostream &os, const BoxId &box_id) const
Writes the requested neighborhood to an output stream.
Outputter format (const std::string &border=std::string(), int detail_depth=2) const
Return an object that can format the Connector for insertion into output streams.
Outputter formatStatistics (const std::string &border=std::string()) const
Return an object that can format the Connector for inserting its global statistics into output streams.
Algorithms for changing individual Box's neighbor data
void insertNeighbors (const BoxContainer &neighbors, const BoxId &base_box)
Insert additional neighbors for the specified base Box.
void eraseNeighbor (const Box &neighbor, const BoxId &box_id)
Erase neighbor of the specified BoxId.
void insertLocalNeighbor (const Box &neighbor, const BoxId &box_id)
Adds a neighbor of the specified BoxId.
void insertLocalNeighbor (const Box &neighbor, NeighborhoodIterator &base_box_itr)
Adds a neighbor of the base box pointed to by base_box_itr.
void eraseLocalNeighborhood (const BoxId &box_id)
Erases the neighborhood of the specified BoxId.
void removePeriodicRelationships ()
Remove all the periodic relationships in the Connector.
void removePeriodicLocalNeighbors ()
Remove all the periodic neighbors in all local neighborhoods.
bool hasPeriodicLocalNeighborhoodBaseBoxes () const
Check for any base boxes which are periodic.
NeighborhoodIterator makeEmptyLocalNeighborhood (const BoxId &box_id)
Make an empty set of neighbors of the supplied box_id.
void eraseEmptyNeighborSets ()
Remove empty sets of neighbors.
bool isEmptyNeighborhood (const BoxId &box_id) const
Returns true is the neighborhood of the supplied BoxId is empty.
void coarsenLocalNeighbors (const IntVector &ratio)
Coarsen all neighbors of this connector by ratio.
void refineLocalNeighbors (const IntVector &ratio)
Refine all neighbors of this connector by ratio.
void growLocalNeighbors (const IntVector &growth)
Grow all neighbors of this connector by growth.
Static Public Member Functions
static void computeRatioInfo (const IntVector &baseRefinementRatio, const IntVector &headRefinementRatio, IntVector &ratio, bool &head_coarser, bool &ratio_is_exact)
Computes refinement ratio between head and base, whether that ratio is exact and whether the head is coarser than the base.
Protected Member Functions
void doLocalTransposeWork (Connector *transpose) const
Method to do the work of createLocalTranspose.
void doTransposeWork (Connector *transpose) const
Method to do the work of createTranspose.
Friends
class OverlapConnectorAlgorithm
For outputs, error checking and debugging.
void recursivePrint (std::ostream &os, const std::string &border, int detail_depth=2) const
bool isTransposeOf (const Connector &other) const
Return true if two Connector objects are transposes of each other.
size_t checkConsistencyWithBase () const
Check for consistency between the relationship data and base boxes, and return the number of consistency errors.
void assertConsistencyWithBase () const
Run checkConsistencyWithBase().
size_t checkConsistencyWithHead () const
Check that the neighbors specified by the relationships exist in the head BoxLevel.
void assertConsistencyWithHead () const
Run checkConsistencyWithBase(). If any inconsistency is found, write out diagnostic information and throw an unrecoverable assertion.
bool hasTranspose () const
Returns true if the transpose of this Connector exists.
Connector & getTranspose () const
Returns the transpose of this Connector if it exists.
void setTranspose (Connector *transpose, bool owns_transpose)
Sets this Connector's transpose and, if the transpose exists, sets its transpose to this Connector. If owns_transpose is true then this object will delete the transpose during its deletion.
size_t checkTransposeCorrectness (const Connector &transpose, bool ignore_periodic_relationships=false) const
Check that the relationships are a correct transpose of another Connector and return the number of erroneous relationships.
void assertTransposeCorrectness (const Connector &transpose, const bool ignore_periodic_relationships=false) const
Run checkTransposeCorrectness. If any errors are found, print out diagnostic information and throw an unrecoverable assertion.
int checkOverlapCorrectness (bool ignore_self_overlap=false, bool assert_completeness=true, bool ignore_periodic_images=false) const
void assertOverlapCorrectness (bool ignore_self_overlap=false, bool assert_completeness=true, bool ignore_periodic_images=false) const
Assert overlap correctness.
void findOverlapErrors (boost::shared_ptr< Connector > &missing, boost::shared_ptr< Connector > &extra, bool ignore_self_overlap=false) const
Find errors in overlap data of an overlap Connector.
static IntVector convertHeadWidthToBase (const IntVector &base_refinement_ratio, const IntVector &head_refinement_ratio, const IntVector &head_gcw)
Given the Connector width in the head index space, convert it to the base index space.
static void computeNeighborhoodDifferences (boost::shared_ptr< Connector > &left_minus_right, const Connector &left_connector, const Connector &right_connector)
Compute the differences between two relationship sets.
Detailed Description
A container which holds relationship connections between two BoxLevels.
Connectors have a notion of a "base" and a "head", representing a directional relationship between two BoxLevels. The relationships are a collection of Boxes in the head, pointed to by a Box in the base. The association between base and head relationships is 1 .. 0-many. That is, one Box in the base can be related to zero or more Boxes (called its NeighborSet) in the head.
Usage
Connections in a Connector can have three possible relationships:
# A Box in the base has no related NeighborSet. In this case, the Box in the base will exist as-is in the head. # A Box in the base has NeighborSet which is empty. In this case, the Box from the base will not exist in the head BoxLevel. # A Box in the base has a corresponding NeighborSet which in non-empty. In this case, the NeighborSet contains the set of Boxes to which the Box in the base is related.
Member Typedef Documentation
typedef BoxContainer SAMRAI::hier::Connector::NeighborSet
NeighborsSet is a clarifying typedef.
typedef BoxNeighborhoodCollection::ConstIterator SAMRAI::hier::Connector::ConstNeighborhoodIterator
Type of the iterator over neighborhoods.
typedef BoxNeighborhoodCollection::Iterator SAMRAI::hier::Connector::NeighborhoodIterator
Type of the iterator over neighborhoods.
typedef BoxNeighborhoodCollection::ConstNeighborIterator SAMRAI::hier::Connector::ConstNeighborIterator
Type of the iterator over neighbors in a neighborhood.
typedef BoxNeighborhoodCollection::NeighborIterator SAMRAI::hier::Connector::NeighborIterator
Type of the iterator over neighbors in a neighborhood.
Constructor & Destructor Documentation
SAMRAI::hier::Connector::Connector (const tbox::Dimension & dim) [explicit]
Creates an uninitialized Connector object in the distributed state.
Parameters:
dim The dimension of the head and base BoxLevels that this object will eventually connect.
See also:
setBase()
setHead()
setWidth()
SAMRAI::hier::Connector::Connector (const tbox::Dimension & dim, tbox::Database & restart_db)
Creates a Connector which is initialized from a restart database.
Parameters:
dim The dimension of the head and base BoxLevels that this object will eventually connect.
restart_db Restart Database written by a Connector.
See also:
setBase()
setHead()
setWidth()
SAMRAI::hier::Connector::Connector (const Connector & other)
Copy constructor.
Parameters:
[in] other
SAMRAI::hier::Connector::Connector (const BoxLevel & base_box_level, const BoxLevel & head_box_level, const IntVector & base_width, const BoxLevel::ParallelState parallel_state = BoxLevel::DISTRIBUTED)
Initialize a Connector with no defined relationships.
The Connector's relationships are initialized to a dummy state.
Parameters:
[in] base_box_level
[in] head_box_level
[in] base_width
[in] parallel_state
Precondition:
(base_box_level.getDim() == head_box_level.getDim()) && (base_box_level.getDim() == base_width.getDim())
References setBase(), setHead(), setWidth(), and TBOX_ASSERT_OBJDIM_EQUALITY3.
SAMRAI::hier::Connector::~Connector () [virtual]
Destructor.
References clear().
Member Function Documentation
void SAMRAI::hier::Connector::clear () [inline]
Clear the Connector, putting it into an uninitialized state.
References SAMRAI::hier::BoxNeighborhoodCollection::clear(), SAMRAI::hier::BoxLevel::DISTRIBUTED, MPI_COMM_NULL, and SAMRAI::tbox::SAMRAI_MPI::setCommunicator().
Referenced by ~Connector().
void SAMRAI::hier::Connector::clearNeighborhoods () [inline]
Clear the Connector's neighborhood relations.
References SAMRAI::hier::BoxNeighborhoodCollection::clear().
Referenced by SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel().
bool SAMRAI::hier::Connector::isFinalized () const [inline]
Returns true if the object has been finalized.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), cacheGlobalReducedData(), SAMRAI::hier::ConnectorStatistics::ConnectorStatistics(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), getBase(), getConnectorWidth(), getGlobalNumberOfNeighborSets(), getGlobalNumberOfRelationships(), getHead(), getHeadCoarserFlag(), getMPI(), getRatio(), operator!=(), operator==(), ratioIsExact(), recursivePrint(), and setParallelState().
ConstNeighborhoodIterator SAMRAI::hier::Connector::begin () const [inline]
Iterator pointing to the first neighborhood.
References SAMRAI::hier::BoxNeighborhoodCollection::begin().
Referenced by checkConsistencyWithBase(), checkConsistencyWithHead(), checkOverlapCorrectness(), checkTransposeCorrectness(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), computeNeighborhoodDifferences(), doLocalTransposeWork(), doTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), finalizeContext(), SAMRAI::hier::MappingConnector::findMappingErrors(), hasPeriodicLocalNeighborhoodBaseBoxes(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), numLocalEmptyNeighborhoods(), recursivePrint(), shrinkWidth(), and writeNeighborhoodsToErrorStream().
NeighborhoodIterator SAMRAI::hier::Connector::begin () [inline]
Iterator pointing to the first neighborhood.
References SAMRAI::hier::BoxNeighborhoodCollection::begin().
ConstNeighborhoodIterator SAMRAI::hier::Connector::end () const [inline]
Iterator pointing one past the last neighborhood.
References SAMRAI::hier::BoxNeighborhoodCollection::end().
Referenced by checkConsistencyWithBase(), checkConsistencyWithHead(), checkOverlapCorrectness(), checkTransposeCorrectness(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), computeNeighborhoodDifferences(), doLocalTransposeWork(), doTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), finalizeContext(), SAMRAI::hier::MappingConnector::findMappingErrors(), hasPeriodicLocalNeighborhoodBaseBoxes(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), numLocalEmptyNeighborhoods(), recursivePrint(), shrinkWidth(), and writeNeighborhoodsToErrorStream().
NeighborhoodIterator SAMRAI::hier::Connector::end () [inline]
Iterator pointing one past the last neighborhood.
References SAMRAI::hier::BoxNeighborhoodCollection::end().
ConstNeighborIterator SAMRAI::hier::Connector::begin (const ConstNeighborhoodIterator & nbrhd) const [inline]
Iterator pointing to the first neighbor in nbrhd.
Parameters:
nbrhd The neighborhood whose neighbors are to be iterated.
References SAMRAI::hier::BoxNeighborhoodCollection::begin().
NeighborIterator SAMRAI::hier::Connector::begin (NeighborhoodIterator & nbrhd) [inline]
Iterator pointing to the first neighbor in nbrhd.
Parameters:
nbrhd The neighborhood whose neighbors are to be iterated.
References SAMRAI::hier::BoxNeighborhoodCollection::begin().
ConstNeighborIterator SAMRAI::hier::Connector::end (const ConstNeighborhoodIterator & nbrhd) const [inline]
Iterator pointing one past the last neighbor in nbrhd.
Parameters:
nbrhd The neighborhood whose neighbors are to be iterated.
References SAMRAI::hier::BoxNeighborhoodCollection::end().
NeighborIterator SAMRAI::hier::Connector::end (NeighborhoodIterator & nbrhd) [inline]
Iterator pointing one past the last neighbor in nbrhd.
Parameters:
nbrhd The neighborhood whose neighbors are to be iterated.
References SAMRAI::hier::BoxNeighborhoodCollection::end().
ConstNeighborhoodIterator SAMRAI::hier::Connector::findLocal (const BoxId & box_id) const [inline]
Returns an Iterator pointing to the neighborhood of box_id-- localized version.
Parameters:
[in] box_id
References SAMRAI::hier::BoxNeighborhoodCollection::find(), SAMRAI::hier::BoxId::getGlobalId(), and SAMRAI::hier::PeriodicId::zero().
Referenced by checkOverlapCorrectness(), computeNeighborhoodDifferences(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), and SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap().
NeighborhoodIterator SAMRAI::hier::Connector::findLocal (const BoxId & box_id) [inline]
Returns an Iterator pointing to the neighborhood of box_id-- localized version.
Parameters:
[in] box_id
References SAMRAI::hier::BoxNeighborhoodCollection::find(), SAMRAI::hier::BoxId::getGlobalId(), and SAMRAI::hier::PeriodicId::zero().
ConstNeighborhoodIterator SAMRAI::hier::Connector::find (const BoxId & box_id) const [inline]
Returns an Iterator pointing to the neighborhood of box_id-- globalized version.
Parameters:
[in] box_id
References SAMRAI::hier::BoxNeighborhoodCollection::end(), SAMRAI::hier::BoxNeighborhoodCollection::find(), SAMRAI::hier::BoxId::getGlobalId(), TBOX_ERROR, and SAMRAI::hier::PeriodicId::zero().
Referenced by SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), and SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets().
bool SAMRAI::hier::Connector::localNeighborhoodsEqual (const Connector & other) const [inline]
Returns true if the local neighborhoods of this and other are the same.
Parameters:
[in] other
bool SAMRAI::hier::Connector::neighborhoodEqual (const BoxId & box_id, const Connector & other) const [inline]
Returns true if the neighborhood of the supplied BoxId of this and other are the same.
Parameters:
[in] box_id
[in] other
References SAMRAI::hier::BoxId::getGlobalId(), SAMRAI::hier::BoxNeighborhoodCollection::neighborhoodEqual(), and SAMRAI::hier::PeriodicId::zero().
bool SAMRAI::hier::Connector::hasNeighborSet (const BoxId & box_id) const [inline]
Return true if a neighbor set exists for the specified BoxId.
Parameters:
[in] box_id
References SAMRAI::hier::BoxNeighborhoodCollection::end(), SAMRAI::hier::BoxNeighborhoodCollection::find(), SAMRAI::hier::BoxId::getGlobalId(), and SAMRAI::hier::PeriodicId::zero().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::MappingConnector::findMappingErrors(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), getNeighborBoxes(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), and numLocalNeighbors().
bool SAMRAI::hier::Connector::hasLocalNeighbor (const BoxId & box_id, const Box & neighbor) const [inline]
Return true if the supplied box is in the neighborhood of the supplied BoxId.
Parameters:
[in] box_id
[in] neighbor
Precondition:
box_id.getOwnerRank() == getMPI().getRank()
References SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxNeighborhoodCollection::hasNeighbor(), and TBOX_ASSERT.
void SAMRAI::hier::Connector::getNeighborBoxes (const BoxId & box_id, BoxContainer & nbr_boxes) const [inline]
Return the neighbor set for the specified BoxId.
Parameters:
[in] box_id
[out] nbr_boxes
Precondition:
hasNeighborSet(box_id)
References SAMRAI::hier::BoxId::getGlobalId(), SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors(), hasNeighborSet(), TBOX_ASSERT, and SAMRAI::hier::PeriodicId::zero().
void SAMRAI::hier::Connector::getLocalNeighbors (BoxContainer & neighbors) const [inline]
Return all neighbors for all neighborhoods.
Parameters:
[out] neighbors
References SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors().
Referenced by SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), and SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance().
void SAMRAI::hier::Connector::getLocalNeighbors (std::map< BlockId, BoxContainer > & neighbors) const [inline]
Return all neighbors for all neighborhoods segragated by BlockId.
Parameters:
[out] neighbors
References SAMRAI::hier::BoxNeighborhoodCollection::getNeighbors().
int SAMRAI::hier::Connector::numLocalNeighbors (const BoxId & box_id) const [inline]
Returns the number of neighbors in the neighborhood with the supplied BoxId.
Parameters:
[in] box_id
Precondition:
hasNeighborSet(box_id)
References SAMRAI::hier::BoxId::getGlobalId(), hasNeighborSet(), SAMRAI::hier::BoxNeighborhoodCollection::numNeighbors(), TBOX_ASSERT, and SAMRAI::hier::PeriodicId::zero().
Referenced by checkOverlapCorrectness(), computeNeighborhoodDifferences(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), and recursivePrint().
int SAMRAI::hier::Connector::numLocalEmptyNeighborhoods () const [inline]
Returns the number of empty neighborhoods in the Connector.
Returns:
The number of empty neighborhoods in the Connector.
References begin(), SAMRAI::hier::BoxNeighborhoodCollection::emptyBoxNeighborhood(), and end().
void SAMRAI::hier::Connector::getLocalOwners (std::set< int > & owners) const [inline]
Places the ranks of the processors owning all neighbors into owners.
Parameters:
[out] owners
References SAMRAI::hier::BoxNeighborhoodCollection::getOwners().
void SAMRAI::hier::Connector::getLocalOwners (ConstNeighborhoodIterator & base_boxes_itr, std::set< int > & owners) const [inline]
Places the ranks of the processors owning the neighbors of the Box pointed to by base_boxes_itr into owners.
Parameters:
[in] base_boxes_itr
[out] owners
References SAMRAI::hier::BoxNeighborhoodCollection::getOwners().
void SAMRAI::hier::Connector::insertNeighbors (const BoxContainer & neighbors, const BoxId & base_box)
Insert additional neighbors for the specified base Box.
Parameters:
[in] neighbors
[in] base_box
Precondition:
(getParallelState() == BoxLevel::GLOBALIZED) || (base_box.getOwnerRank() == getMPI().getRank())
getBase().hasBox(base_box)
References SAMRAI::hier::BoxLevel::DISTRIBUTED, format(), getBase(), getMPI(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::BoxNeighborhoodCollection::insert(), and TBOX_ERROR.
void SAMRAI::hier::Connector::eraseNeighbor (const Box & neighbor, const BoxId & box_id)
Erase neighbor of the specified BoxId.
Parameters:
[in] neighbor
[in] box_id
Precondition:
(getParallelState() == BoxLevel::GLOBALIZED) || (base_box.getOwnerRank() == getMPI().getRank())
getBase().hasBox(box_id)
References SAMRAI::hier::BoxLevel::DISTRIBUTED, SAMRAI::hier::BoxNeighborhoodCollection::erase(), format(), getBase(), getMPI(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::GLOBALIZED, and TBOX_ERROR.
void SAMRAI::hier::Connector::insertLocalNeighbor (const Box & neighbor, const BoxId & box_id) [inline]
Adds a neighbor of the specified BoxId.
Parameters:
[in] neighbor
[in] box_id
Precondition:
box_id.getOwnerRank() == getMPI().getRank()
References SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), and TBOX_ASSERT.
Referenced by doTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
void SAMRAI::hier::Connector::insertLocalNeighbor (const Box & neighbor, NeighborhoodIterator & base_box_itr) [inline]
Adds a neighbor of the base box pointed to by base_box_itr.
Parameters:
[in] neighbor
[in] base_box_itr
Precondition:
base_box_itr->getOwnerRank() == getMPI().getRank()
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), and TBOX_ASSERT.
void SAMRAI::hier::Connector::eraseLocalNeighborhood (const BoxId & box_id) [inline]
Erases the neighborhood of the specified BoxId.
Parameters:
[in] box_id
Precondition:
box_id.getOwnerRank() == getMPI().getRank()
References SAMRAI::hier::BoxNeighborhoodCollection::erase(), SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), and TBOX_ASSERT.
void SAMRAI::hier::Connector::removePeriodicRelationships () [inline]
Remove all the periodic relationships in the Connector.
References SAMRAI::hier::BoxNeighborhoodCollection::erasePeriodicNeighbors(), and SAMRAI::hier::BoxLevel::GLOBALIZED.
Referenced by SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel().
void SAMRAI::hier::Connector::removePeriodicLocalNeighbors () [inline]
Remove all the periodic neighbors in all local neighborhoods.
References SAMRAI::hier::BoxNeighborhoodCollection::erasePeriodicNeighbors().
bool SAMRAI::hier::Connector::hasPeriodicLocalNeighborhoodBaseBoxes () const [inline]
Check for any base boxes which are periodic.
Returns:
true if any base box is periodic
References begin(), and end().
Referenced by checkOverlapCorrectness().
NeighborhoodIterator SAMRAI::hier::Connector::makeEmptyLocalNeighborhood (const BoxId & box_id) [inline]
Make an empty set of neighbors of the supplied box_id.
Parameters:
[in] box_id
Precondition:
box_id.getOwnerRank() == getMPI().getRank()
References SAMRAI::hier::BoxId::getOwnerRank(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), and SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel().
void SAMRAI::hier::Connector::eraseEmptyNeighborSets () [inline]
Remove empty sets of neighbors.
References SAMRAI::hier::BoxNeighborhoodCollection::eraseEmptyNeighborhoods().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships().
bool SAMRAI::hier::Connector::isEmptyNeighborhood (const BoxId & box_id) const [inline]
Returns true is the neighborhood of the supplied BoxId is empty.
Parameters:
[in] box_id
References SAMRAI::hier::BoxNeighborhoodCollection::emptyBoxNeighborhood().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships().
void SAMRAI::hier::Connector::coarsenLocalNeighbors (const IntVector & ratio) [inline]
Coarsen all neighbors of this connector by ratio.
Parameters:
[in] ratio
References SAMRAI::hier::BoxNeighborhoodCollection::coarsenNeighbors().
void SAMRAI::hier::Connector::refineLocalNeighbors (const IntVector & ratio) [inline]
Refine all neighbors of this connector by ratio.
Parameters:
[in] ratio
References SAMRAI::hier::BoxNeighborhoodCollection::refineNeighbors().
void SAMRAI::hier::Connector::growLocalNeighbors (const IntVector & growth) [inline]
Grow all neighbors of this connector by growth.
Parameters:
[in] growth
References SAMRAI::hier::BoxNeighborhoodCollection::growNeighbors().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead().
void SAMRAI::hier::Connector::finalizeContext ()
Enforces implicit class invariants and removes non-local neighbors from relationships.
To be called after modifying a Connector's context through setBase, setHead, or setWidth methods.
Precondition:
d_base_handle && d_head_handle
getBase().getGridGeometry() == getHead().getGridGeometry()
(getBase().getRefinementRatio() >= getHead().getRefinementRatio()) || (getBase().getRefinementRatio() <= getHead().getRefinementRatio())
(getParallelState() == BoxLevel::DISTRIBUTED) || (getBase().getParallelState() == BoxLevel::GLOBALIZED)
References begin(), SAMRAI::hier::BoxNeighborhoodCollection::clear(), computeRatioInfo(), SAMRAI::hier::BoxLevel::DISTRIBUTED, end(), SAMRAI::hier::BoxNeighborhoodCollection::eraseNonLocalNeighborhoods(), SAMRAI::hier::BoxLevel::format(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getParallelState(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::hier::BoxNeighborhoodCollection::numNeighbors(), SAMRAI::tbox::perr, TBOX_ASSERT, and TBOX_ERROR.
Referenced by setBase(), setHead(), and setWidth().
void SAMRAI::hier::Connector::setBase (const BoxLevel & new_base, bool finalize_context = false)
Change the Connector base to new_base. If finalize_context is true then this is the last atomic change being made and finalizeContext should be called.
Parameters:
new_base
finalize_context
Precondition:
new_base.isInitialized()
References finalizeContext(), SAMRAI::hier::BoxLevel::getBoxLevelHandle(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::BoxLevel::isInitialized(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), Connector(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), and SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel().
const BoxLevel& SAMRAI::hier::Connector::getBase () const [inline]
Return a reference to the base BoxLevel.
Precondition:
isFinalized()
References isFinalized(), and TBOX_ASSERT.
Referenced by assertConsistencyWithBase(), assertConsistencyWithHead(), SAMRAI::hier::MappingConnector::assertMappingValidity(), assertOverlapCorrectness(), assertTransposeCorrectness(), SAMRAI::mesh::VoucherTransitLoad::assignToLocalAndPopulateMaps(), SAMRAI::mesh::BoxTransitSet::assignToLocalAndPopulateMaps(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), checkConsistencyWithBase(), checkOverlapCorrectness(), checkTransposeCorrectness(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::hier::MappingConnector::createLocalTranspose(), createLocalTranspose(), SAMRAI::hier::MappingConnector::createTranspose(), createTranspose(), doLocalTransposeWork(), doTransposeWork(), eraseNeighbor(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::MappingConnector::findMappingErrors(), findOverlapErrors(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges(), getMPI(), insertNeighbors(), isTransposeOf(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), recursivePrint(), SAMRAI::xfer::RefineSchedule::RefineSchedule(), and shrinkWidth().
void SAMRAI::hier::Connector::setHead (const BoxLevel & new_head, bool finalize_context = false)
Change the Connector head to new_head. If finalize_context is true then this is the last atomic change being made and finalizeContext should be called.
Parameters:
new_head
finalize_context
Precondition:
new_head.isInitialized()
References finalizeContext(), SAMRAI::hier::BoxLevel::getBoxLevelHandle(), SAMRAI::hier::BoxLevel::isInitialized(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), Connector(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel().
const BoxLevel& SAMRAI::hier::Connector::getHead () const [inline]
Return a reference to the head BoxLevel.
Precondition:
isFinalized()
References isFinalized(), and TBOX_ASSERT.
Referenced by assertConsistencyWithBase(), assertConsistencyWithHead(), SAMRAI::hier::MappingConnector::assertMappingValidity(), assertOverlapCorrectness(), assertTransposeCorrectness(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), checkConsistencyWithHead(), checkOverlapCorrectness(), checkTransposeCorrectness(), SAMRAI::hier::MappingConnector::createLocalTranspose(), createLocalTranspose(), SAMRAI::hier::MappingConnector::createTranspose(), createTranspose(), doLocalTransposeWork(), doTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::MappingConnector::findMappingErrors(), findOverlapErrors(), SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps(), isTransposeOf(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), recursivePrint(), SAMRAI::xfer::RefineSchedule::RefineSchedule(), and shrinkWidth().
const IntVector& SAMRAI::hier::Connector::getRatio () const [inline]
Get the refinement ratio between the base and head BoxLevels.
The ratio is the same regardless of which is the coarser of the two. Use getHeadCoarserFlag() to determine which is coarser. If the ratio cannot be represented by an IntVector, truncated.
See also:
ratioIsExact().
Precondition:
isFinalized()
References isFinalized(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), checkOverlapCorrectness(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel(), and shrinkWidth().
bool SAMRAI::hier::Connector::ratioIsExact () const [inline]
Whether the ratio given by getRatio() is exact.
The ratio is exact if it can be represented by an IntVector.
See also:
getRatio().
Precondition:
isFinalized()
References isFinalized(), and TBOX_ASSERT.
bool SAMRAI::hier::Connector::getHeadCoarserFlag () const [inline]
Return true if head BoxLevel is coarser than base BoxLevel.
Precondition:
isFinalized()
References isFinalized(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), checkOverlapCorrectness(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), and shrinkWidth().
bool SAMRAI::hier::Connector::isLocal () const [inline]
Return true if the Connector contains only relationships to local Boxes.
The check only applies to neighbors of local base Boxes, so it is possible for the results to be different on different processors.
References getMPI(), and SAMRAI::hier::BoxNeighborhoodCollection::isLocal().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap().
Connector * SAMRAI::hier::Connector::createLocalTranspose () const [virtual]
Create and return this Connector's transpose, assuming that all relationships are local (no remote neighbors).
If any remote neighbor is found an unrecoverable assertion is thrown.
Non-periodic relationships in are simply reversed to get the transpose relationship. For each periodic relationship we create a periodic relationship incident from the unshifted head neighbor to the shifted base neighbor. This is because all relationships must be incident from a real (unshifted) Box.
Reimplemented in SAMRAI::hier::MappingConnector.
References convertHeadWidthToBase(), doLocalTransposeWork(), getBase(), getConnectorWidth(), and getHead().
Referenced by SAMRAI::hier::MappingConnectorAlgorithm::modify().
Connector * SAMRAI::hier::Connector::createTranspose () const [virtual]
Create and return this Connector's transpose.
Similar to createLocalTranspose(), but this method allows non-local edges. Global data is required, so this method is not scalable.
Reimplemented in SAMRAI::hier::MappingConnector.
References convertHeadWidthToBase(), doTransposeWork(), getBase(), getConnectorWidth(), and getHead().
Connector & SAMRAI::hier::Connector::operator= (const Connector & rhs)
Assignment operator.
Reimplemented in SAMRAI::hier::MappingConnector.
bool SAMRAI::hier::Connector::operator== (const Connector & rhs) const
Equality operator checks relationship data, Connector width and equality of base and head Box pointers.
CAUTION
Equality here means just the local parts are equal. This means that one processor may see the equality differently from another.
The cost for the comparison is on the order of the local relationship count. However, an object may be compared to itself, an efficient operation that always returns true. When comparing Connector objects, if you expect equality to hold, using the same objects would improve performance.
References isFinalized().
bool SAMRAI::hier::Connector::operator!= (const Connector & rhs) const
Inequality operator checks the same data that equality operator checks.
See also:
operator==(const Connector &rhs);
References isFinalized().
void SAMRAI::hier::Connector::setParallelState (const BoxLevel::ParallelState parallel_state)
Set the parallel distribution state.
Before a Connector can be in a GLOBALIZED state, the base BoxLevel given in setBase() must already be in GLOBALIZED mode. The base BoxLevel should remain in GLOBALIZED mode for compatibility with the Connector.
This method is not necessarily trivial. More memory is required to store additional relationships.
For serial (one processor) runs, there is no difference between the parallel states (except for the names), and there is no real cost for switching parallel states.
Parameters:
[in] parallel_state
Precondition:
isFinalized()
References SAMRAI::hier::BoxNeighborhoodCollection::clear(), SAMRAI::hier::BoxLevel::DISTRIBUTED, SAMRAI::hier::BoxLevel::GLOBALIZED, isFinalized(), and TBOX_ERROR.
BoxLevel::ParallelState SAMRAI::hier::Connector::getParallelState () const [inline]
Return the current parallel state.
Referenced by computeNeighborhoodDifferences(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), recursivePrint(), and shrinkWidth().
const tbox::SAMRAI_MPI& SAMRAI::hier::Connector::getMPI () const [inline]
Returns the MPI communication object, which is always that of the base BoxLevel.
Precondition:
isFinalized()
References getBase(), SAMRAI::hier::BoxLevel::getMPI(), isFinalized(), and TBOX_ASSERT.
Referenced by assertOverlapCorrectness(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), cacheGlobalReducedData(), checkTransposeCorrectness(), doLocalTransposeWork(), eraseNeighbor(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::MappingConnector::findMappingErrors(), insertNeighbors(), isLocal(), and recursivePrint().
void SAMRAI::hier::Connector::setWidth (const IntVector & new_width, bool finalize_context = false)
Change the Connector width to new_width. If finalize_context is true then this is the last atomic change being made and finalizeContext should be called.
Parameters:
new_width
finalize_context
Precondition:
new_width >= IntVector::getZero(new_width.getDim())
References finalizeContext(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getZero(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), Connector(), and SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel().
const IntVector& SAMRAI::hier::Connector::getConnectorWidth () const [inline]
Return the Connector width associated with the relationships.
For overlap Connectors, an relationship exists between a base and head Boxes if the base box, grown by this width, overlaps the head box. For mapping Connectors, the width the amount that a pre-map box must grow to nest the post-map boxes
Precondition:
isFinalized().
References isFinalized(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), checkOverlapCorrectness(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::hier::MappingConnector::createLocalTranspose(), createLocalTranspose(), SAMRAI::hier::MappingConnector::createTranspose(), createTranspose(), doLocalTransposeWork(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::MappingConnector::findMappingErrors(), findOverlapErrors(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::xfer::RefineSchedule::RefineSchedule(), and shrinkWidth().
void SAMRAI::hier::Connector::shrinkWidth (const IntVector & new_width)
Shrink the width of the connector modifying the proximity relationships as needed.
Parameters:
[in] new_width
Precondition:
new_width <= getConnectorWidth()
getParallelState() == BoxLevel::DISTRIBUTED
References begin(), SAMRAI::hier::BoxLevel::DISTRIBUTED, end(), SAMRAI::hier::BoxNeighborhoodCollection::erase(), getBase(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBoxStrict(), getConnectorWidth(), getHead(), getHeadCoarserFlag(), getParallelState(), getRatio(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::Box::grow(), SAMRAI::hier::Box::intersects(), SAMRAI::hier::Box::refine(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::hier::Connector::recursivePrint (std::ostream & os, const std::string & border, int detail_depth = 2) const
References begin(), SAMRAI::hier::Box::coarsen(), convertHeadWidthToBase(), SAMRAI::hier::BoxLevel::DISTRIBUTED, end(), getBase(), SAMRAI::hier::BoxLevel::getBox(), getHead(), SAMRAI::hier::BoxLevel::getLocalNumberOfBoxes(), getLocalNumberOfNeighborSets(), getMPI(), getParallelState(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::Box::grow(), isFinalized(), SAMRAI::hier::Box::numberCells(), numLocalNeighbors(), and SAMRAI::hier::Box::refine().
Referenced by SAMRAI::hier::operator<<().
bool SAMRAI::hier::Connector::isTransposeOf (const Connector & other) const
Return true if two Connector objects are transposes of each other.
Each Connector represents a set of directed relationships incident from its base to its head. The transpose represent the relationships in the opposite direction. In order for two Connector objects to be transpose of each other, their Connector widths and base refinement ratios must be such that an relationship in one set also appears in the other set. A transpose set must have
base and head BoxLevels reversed from the untransposed set.
the same Connector width, although it is described in the index space of a different base BoxLevel.
Parameters:
[in] other
References convertHeadWidthToBase(), getBase(), getHead(), and SAMRAI::hier::BoxLevel::getRefinementRatio().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), doLocalTransposeWork(), doTransposeWork(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), and SAMRAI::hier::MappingConnectorAlgorithm::modify().
IntVector SAMRAI::hier::Connector::convertHeadWidthToBase (const IntVector & base_refinement_ratio, const IntVector & head_refinement_ratio, const IntVector & head_gcw) [static]
Given the Connector width in the head index space, convert it to the base index space.
This method is useful for computing Connector widths for transpose Connectors. It handles negative refinement ratios. By SAMRAI convention, a refinement ratio of -N is interpreted as 1/N.)
This method is static because (1) it has nothing to do with an existing Connector object, and (2) it is often used to compute a Connector's initializing data.
Parameters:
[in] base_refinement_ratio
[in] head_refinement_ratio
[in] head_gcw The connector width in the head index space.
Returns:
A copy of the connector width converted to the base index space.
Precondition:
(base_refinement_ratio >= head_refinement_ratio) || (base_refinement_ratio <= head_refinement_ratio)
References SAMRAI::hier::IntVector::ceilingDivide(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::IntVector::getZero(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::MappingConnector::createLocalTranspose(), createLocalTranspose(), SAMRAI::hier::MappingConnector::createTranspose(), createTranspose(), isTransposeOf(), recursivePrint(), and SAMRAI::xfer::RefineSchedule::RefineSchedule().
size_t SAMRAI::hier::Connector::checkConsistencyWithBase () const
Check for consistency between the relationship data and base boxes, and return the number of consistency errors.
Consistency stipulates that each neighbor list must correspond to a base box.
relationship consistency errors should be treated as fatal because many operations assume consistency.
References begin(), end(), getBase(), SAMRAI::hier::BoxLevel::hasBox(), and SAMRAI::tbox::plog.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), assertConsistencyWithBase(), and findOverlapErrors().
void SAMRAI::hier::Connector::assertConsistencyWithBase () const
Run checkConsistencyWithBase().
If any inconsistency is found, write out diagnostic information and throw an unrecoverable assertion is found.
References checkConsistencyWithBase(), format(), getBase(), getHead(), and TBOX_ERROR.
size_t SAMRAI::hier::Connector::checkConsistencyWithHead () const
Check that the neighbors specified by the relationships exist in the head BoxLevel.
If the head is not GLOBALIZED, a temporary copy is made and globalized for checking, triggering communication.
Returns:
number of inconsistencies found.
Precondition:
getHead().getGlobalizedVersion().getParallelState() == BoxLevel::GLOBALIZED
References begin(), end(), SAMRAI::hier::BoxContainer::find(), SAMRAI::hier::BoxLevel::getGlobalBoxes(), SAMRAI::hier::BoxLevel::getGlobalizedVersion(), getHead(), SAMRAI::hier::BoxLevel::getParallelState(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::tbox::perr, TBOX_ASSERT, and SAMRAI::hier::PeriodicId::zero().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), assertConsistencyWithHead(), and findOverlapErrors().
void SAMRAI::hier::Connector::assertConsistencyWithHead () const
Run checkConsistencyWithBase(). If any inconsistency is found, write out diagnostic information and throw an unrecoverable assertion.
References checkConsistencyWithHead(), format(), getBase(), getHead(), and TBOX_ERROR.
void SAMRAI::hier::Connector::computeNeighborhoodDifferences (boost::shared_ptr< Connector > & left_minus_right, const Connector & left_connector, const Connector & right_connector) [static]
Compute the differences between two relationship sets.
Given Connectors left_connector and right_connector, compute the relationships that are in left_connector but not in right_connector.
Parameters:
[out] left_minus_right
[in] left_connector
[in] right_connector
References begin(), end(), findLocal(), format(), getParallelState(), numLocalNeighbors(), and SAMRAI::tbox::plog.
Referenced by findOverlapErrors().
bool SAMRAI::hier::Connector::hasTranspose () const [inline]
Returns true if the transpose of this Connector exists.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), getTranspose(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
Connector& SAMRAI::hier::Connector::getTranspose () const [inline]
Returns the transpose of this Connector if it exists.
Precondition:
hasTranspose()
References hasTranspose(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), and SAMRAI::xfer::RefineSchedule::RefineSchedule().
void SAMRAI::hier::Connector::setTranspose (Connector * transpose, bool owns_transpose) [inline]
Sets this Connector's transpose and, if the transpose exists, sets its transpose to this Connector. If owns_transpose is true then this object will delete the transpose during its deletion.
Note:
If owns_transpose is false, then client code is responsible for the deletion of the transpose. Similarly, if owns_transpose is true client code must never explicitly delete the transpose.
Parameters:
[in] transpose
[in] owns_transpose
Referenced by SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
size_t SAMRAI::hier::Connector::checkTransposeCorrectness (const Connector & transpose, bool ignore_periodic_relationships = false) const
Check that the relationships are a correct transpose of another Connector and return the number of erroneous relationships.
For every relationship in this Connector, there should be a corresponding relationship in the transpose Connector. Any missing or extra relationship constitutes an error.
Errors found are written to perr.
Parameters:
[in] transpose
[in] ignore_periodic_relationships
Returns:
Global number of errors in assuming that transpose is a transpose of *this.
References SAMRAI::tbox::SAMRAI_MPI::AllReduce(), SAMRAI::hier::BoxNeighborhoodCollection::begin(), begin(), SAMRAI::hier::BoxNeighborhoodCollection::end(), end(), SAMRAI::hier::BoxNeighborhoodCollection::find(), getBase(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxLevel::getBoxStrict(), SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), SAMRAI::hier::BoxId::getGlobalId(), SAMRAI::hier::Box::getGlobalId(), SAMRAI::hier::BoxLevel::getGlobalizedVersion(), getHead(), getMPI(), SAMRAI::hier::PeriodicShiftCatalog::getOppositeShiftNumber(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::Box::getPeriodicId(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::PeriodicShiftCatalog::getZeroShiftNumber(), SAMRAI::hier::BoxLevel::GLOBALIZED, SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::hier::BoxNeighborhoodCollection::hasNeighbor(), SAMRAI::hier::Box::initialize(), SAMRAI::hier::BoxNeighborhoodCollection::isBaseBox(), SAMRAI::hier::Box::isPeriodicImage(), MPI_SUM, SAMRAI::tbox::perr, TBOX_ASSERT, and SAMRAI::hier::PeriodicId::zero().
Referenced by assertTransposeCorrectness(), doTransposeWork(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), and SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel().
void SAMRAI::hier::Connector::assertTransposeCorrectness (const Connector & transpose, const bool ignore_periodic_relationships = false) const
Run checkTransposeCorrectness. If any errors are found, print out diagnostic information and throw an unrecoverable assertion.
Parameters:
[in] transpose
[in] ignore_periodic_relationships
References checkTransposeCorrectness(), format(), getBase(), getHead(), and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), doLocalTransposeWork(), and SAMRAI::hier::MappingConnectorAlgorithm::modify().
int SAMRAI::hier::Connector::checkOverlapCorrectness (bool ignore_self_overlap = false, bool assert_completeness = true, bool ignore_periodic_images = false) const
Check that overlap data is correct (represents overlaps).
Checking is done as follows:
Find overlap errors using findOverlapErrors().
Report overlap errors to tbox::perr.
Return number of local errors.
Note:
This is an expensive operation (it uses findOverlapErrors()) and should only be used for debugging.
See also:
findOverlaps()
Parameters:
[in] ignore_self_overlap Ignore a box's overlap with itself
[in] assert_completeness If false, ignore missing overlaps. This will still look for overlaps that should not be there.
[in] ignore_periodic_images If true, do not require neighbors that are periodic images.
Returns:
Number of overlap errors found locally.
Precondition:
(getBase().isInitialized()) && (getHead().isInitialized())
!hasPeriodicLocalNeighborhoodBaseBoxes()
References begin(), SAMRAI::hier::Box::coarsen(), end(), findLocal(), findOverlapErrors(), getBase(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBoxStrict(), getConnectorWidth(), SAMRAI::hier::BoxLevel::getGridGeometry(), getHead(), getHeadCoarserFlag(), getRatio(), SAMRAI::hier::Box::grow(), hasPeriodicLocalNeighborhoodBaseBoxes(), SAMRAI::hier::Box::numberCells(), numLocalNeighbors(), SAMRAI::tbox::perr, SAMRAI::hier::Box::refine(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), assertOverlapCorrectness(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel(), and SAMRAI::hier::MappingConnectorAlgorithm::modify().
void SAMRAI::hier::Connector::assertOverlapCorrectness (bool ignore_self_overlap = false, bool assert_completeness = true, bool ignore_periodic_images = false) const
Assert overlap correctness.
Assertions
if an error is found, the method will write out diagnostic information and throw an an error on all processes.
This is an expensive check.
See also:
checkOverlapCorrectness().
Parameters:
[in] ignore_self_overlap
[in] assert_completeness
[in] ignore_periodic_images
Precondition:
(getBase().isInitialized()) && (getHead().isInitialized())
References SAMRAI::tbox::SAMRAI_MPI::Allreduce(), checkOverlapCorrectness(), format(), getBase(), getHead(), getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSize(), MPI_2INT, MPI_MAXLOC, and TBOX_ERROR.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), and SAMRAI::xfer::RefineSchedule::RefineSchedule().
void SAMRAI::hier::Connector::findOverlapErrors (boost::shared_ptr< Connector > & missing, boost::shared_ptr< Connector > & extra, bool ignore_self_overlap = false) const
Find errors in overlap data of an overlap Connector.
An error is either a missing overlap or an extra overlap.
This is an expensive operation and should only be used for debugging.
Assertions
This version throws an assertion only if it finds inconsistent Connector data. Missing and extra overlaps are returned but do not cause an assertion.
Parameters:
[out] missing
[out] extra
[in] ignore_self_overlap
Precondition:
(getBase().isInitialized()) && (getHead().isInitialized())
References checkConsistencyWithBase(), checkConsistencyWithHead(), computeNeighborhoodDifferences(), format(), getBase(), getConnectorWidth(), SAMRAI::hier::BoxLevel::getGlobalizedVersion(), getHead(), SAMRAI::tbox::perr, TBOX_ASSERT, and TBOX_ERROR.
Referenced by checkOverlapCorrectness().
int SAMRAI::hier::Connector::getLocalNumberOfNeighborSets () const [inline]
Return local number of neighbor sets.
References SAMRAI::hier::BoxNeighborhoodCollection::numBoxNeighborhoods().
Referenced by cacheGlobalReducedData(), and recursivePrint().
int SAMRAI::hier::Connector::getLocalNumberOfRelationships () const [inline]
Return local number of relationships.
References SAMRAI::hier::BoxNeighborhoodCollection::sumNumNeighbors().
Referenced by cacheGlobalReducedData().
int SAMRAI::hier::Connector::getGlobalNumberOfNeighborSets () const [inline]
Return global number of neighbor sets.
This requires a global sum reduction, if the global size has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Precondition:
isFinalized()
References cacheGlobalReducedData(), isFinalized(), and TBOX_ASSERT.
int SAMRAI::hier::Connector::getGlobalNumberOfRelationships () const [inline]
Return global number of relationships.
This requires a global sum reduction if the global size has not been computed and cached. When communication is required, all processors must call this method. To ensure that no communication is needed, call cacheGlobalReducedData() first.
Precondition:
isFinalized()
References cacheGlobalReducedData(), isFinalized(), and TBOX_ASSERT.
void SAMRAI::hier::Connector::cacheGlobalReducedData () const
If global reduced data (global number of relationships, etc.) has not been updated, compute and cache them (communication required).
After this method is called, data requiring global reduction can be accessed without further communications, until the object changes.
Sets d_global_data_up_to_date;
Precondition:
isFinalized()
References SAMRAI::tbox::SAMRAI_MPI::Allreduce(), getLocalNumberOfNeighborSets(), getLocalNumberOfRelationships(), getMPI(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::BoxLevel::GLOBALIZED, isFinalized(), MPI_INT, MPI_SUM, SAMRAI::hier::BoxNeighborhoodCollection::numBoxNeighborhoods(), SAMRAI::hier::BoxNeighborhoodCollection::sumNumNeighbors(), and TBOX_ASSERT.
Referenced by getGlobalNumberOfNeighborSets(), and getGlobalNumberOfRelationships().
void SAMRAI::hier::Connector::putToRestart (const boost::shared_ptr< tbox::Database > & restart_db) [inline]
Write the neighborhoods to a restart database.
Parameters:
[in] restart_db
References SAMRAI::hier::BoxNeighborhoodCollection::putToRestart().
void SAMRAI::hier::Connector::computeRatioInfo (const IntVector & baseRefinementRatio, const IntVector & headRefinementRatio, IntVector & ratio, bool & head_coarser, bool & ratio_is_exact) [static]
Computes refinement ratio between head and base, whether that ratio is exact and whether the head is coarser than the base.
Parameters:
[in] baseRefinementRatio
[in] headRefinementRatio
[out] ratio
[out] head_coarser
[out] ratio_is_exact
References SAMRAI::hier::IntVector::getDim(), and SAMRAI::hier::IntVector::getZero().
Referenced by finalizeContext().
void SAMRAI::hier::Connector::writeNeighborhoodsToErrorStream (const std::string & border) const
Writes the neighborhoods to tbox::perr.
Parameters:
[in] border Left border of the output.
References begin(), end(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::BoxNeighborhoodCollection::numBoxNeighborhoods(), SAMRAI::hier::BoxNeighborhoodCollection::numNeighbors(), and SAMRAI::tbox::perr.
void SAMRAI::hier::Connector::writeNeighborhoodToStream (std::ostream & os, const BoxId & box_id) const
Writes the requested neighborhood to an output stream.
Parameters:
[in] os
[in] box_id
References SAMRAI::hier::BoxNeighborhoodCollection::begin(), SAMRAI::hier::BoxNeighborhoodCollection::end(), SAMRAI::hier::BoxNeighborhoodCollection::find(), SAMRAI::hier::BoxId::getGlobalId(), SAMRAI::hier::Box::numberCells(), TBOX_ERROR, and SAMRAI::hier::PeriodicId::zero().
Outputter SAMRAI::hier::Connector::format (const std::string & border = std::string(), int detail_depth = 2) const [inline]
Return an object that can format the Connector for insertion into output streams.
Usage example:
    tbox::plog << "my connector:\n" << connector.format() << endl;
Parameters:
[in] border
[in] detail_depth
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::addPeriodicImagesAndRelationships(), assertConsistencyWithBase(), assertConsistencyWithHead(), SAMRAI::hier::MappingConnector::assertMappingValidity(), assertOverlapCorrectness(), assertTransposeCorrectness(), computeNeighborhoodDifferences(), doLocalTransposeWork(), eraseNeighbor(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::MappingConnector::findMappingErrors(), findOverlapErrors(), insertNeighbors(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::PatchHierarchy::logMetadataStatistics(), SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel(), and SAMRAI::hier::MappingConnectorAlgorithm::modify().
Outputter SAMRAI::hier::Connector::formatStatistics (const std::string & border = std::string()) const [inline]
Return an object that can format the Connector for inserting its global statistics into output streams.
Usage example:
    cout << "my connector statistics:\n"
         << connector.formatStatistics("  ") << endl;
Parameters:
[in] border
Referenced by SAMRAI::hier::PatchHierarchy::logMetadataStatistics().
void SAMRAI::hier::Connector::doLocalTransposeWork (Connector * transpose) const [protected]
Method to do the work of createLocalTranspose.
Parameters:
transpose
Precondition:
transpose
References assertTransposeCorrectness(), begin(), SAMRAI::hier::BoxContainer::end(), end(), format(), SAMRAI::hier::BoxLevel::format(), getBase(), SAMRAI::hier::BoxLevel::getBox(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::PeriodicShiftCatalog::getCatalog(), getConnectorWidth(), SAMRAI::hier::Box::getGlobalId(), getHead(), getMPI(), SAMRAI::hier::PeriodicShiftCatalog::getOppositeShiftNumber(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::Box::getPeriodicId(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::BoxLevel::hasBox(), SAMRAI::hier::BoxNeighborhoodCollection::insert(), SAMRAI::hier::Box::isPeriodicImage(), isTransposeOf(), SAMRAI::tbox::perr, TBOX_ASSERT, TBOX_ERROR, and SAMRAI::hier::PeriodicId::zero().
Referenced by SAMRAI::hier::MappingConnector::createLocalTranspose(), and createLocalTranspose().
void SAMRAI::hier::Connector::doTransposeWork (Connector * transpose) const [protected]
Method to do the work of createTranspose.
Parameters:
transpose
Precondition:
transpose
References begin(), SAMRAI::hier::BoxNeighborhoodCollection::begin(), checkTransposeCorrectness(), end(), SAMRAI::hier::BoxNeighborhoodCollection::end(), SAMRAI::hier::BoxContainer::find(), getBase(), SAMRAI::hier::BoxLevel::getGlobalBoxes(), SAMRAI::hier::BoxLevel::getGlobalizedVersion(), getHead(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::GLOBALIZED, insertLocalNeighbor(), isTransposeOf(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by SAMRAI::hier::MappingConnector::createTranspose(), and createTranspose().
Friends And Related Function Documentation
friend class OverlapConnectorAlgorithm [friend]
The documentation for this class was generated from the following files:
source/SAMRAI/hier/Connector.h
source/SAMRAI/hier/Connector.C