SAMRAI: SAMRAI::pdat::CellOverlap Class Reference
SAMRAI::pdat::CellOverlap Class Reference
#include <source/SAMRAI/pdat/CellOverlap.h>
Public Member Functions
CellOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation)
virtual ~CellOverlap ()
virtual bool isOverlapEmpty () const
virtual const hier::BoxContainer & getDestinationBoxContainer () const
virtual void getSourceBoxContainer (hier::BoxContainer &src_boxes) const
Get a BoxContainer representing the source boxes of the overlap.
virtual const hier::IntVector & getSourceOffset () const
virtual const
hier::Transformation & getTransformation () const
Get the Transformation from source to destination index space.
virtual void print (std::ostream &os) const
Detailed Description
Class CellOverlap represents the intersection between two cell centered geometry boxes. It is a subclass of hier::BoxOverlap and records the portions of index space that needs to be copied between two objects with cell centered geometry. Note that CellOverlap does NOT compute the overlap of the arguments. It stores the arguments as given and assumes that they already represent an overlap previously computed.
See also:
hier::BoxOverlap
pdat::CellOverlap
Constructor & Destructor Documentation
SAMRAI::pdat::CellOverlap::CellOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation)
The constructor takes the list of boxes and the transfromation from the source to destination index spaces. This information is used later in the generation of communication schedules.
SAMRAI::pdat::CellOverlap::~CellOverlap () [virtual]
The virtual destructor does nothing interesting except deallocate box data.
Member Function Documentation
bool SAMRAI::pdat::CellOverlap::isOverlapEmpty () const [virtual]
Return whether there is an empty intersection between the two cell centered boxes. This method over-rides the virtual function in the hier::BoxOverlap base class.
Implements SAMRAI::hier::BoxOverlap.
const hier::BoxContainer & SAMRAI::pdat::CellOverlap::getDestinationBoxContainer () const [virtual]
Return the list of boxes (in cell centered index space) that constitute the intersection. The boxes are given in the destination coordinate space and must be shifted by -(getSourceOffset()) to lie in the source index space.
Referenced by SAMRAI::pdat::CellData< TYPE >::getDataStreamSize(), SAMRAI::pdat::CellData< TYPE >::packStream(), SAMRAI::pdat::CellData< TYPE >::sum(), SAMRAI::pdat::CellData< TYPE >::unpackStream(), and SAMRAI::pdat::CellData< TYPE >::unpackStreamAndSum().
void SAMRAI::pdat::CellOverlap::getSourceBoxContainer (hier::BoxContainer & src_boxes) const [virtual]
Get a BoxContainer representing the source boxes of the overlap.
The src_boxes container will be filled with the cell-centered source boxes of the overlap in the source coordinate space.
Parameters:
[out] src_boxes
Precondition:
src_boxes.isEmpty()
References SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::hier::BoxContainer::isEmpty(), and TBOX_ASSERT.
const hier::IntVector & SAMRAI::pdat::CellOverlap::getSourceOffset () const [virtual]
Return the offset between the destination and source index spaces. The destination index space is the source index space shifted by this amount.
Implements SAMRAI::hier::BoxOverlap.
References SAMRAI::hier::Transformation::getOffset().
Referenced by SAMRAI::pdat::CellData< TYPE >::getDataStreamSize(), SAMRAI::pdat::CellData< TYPE >::sum(), SAMRAI::pdat::CellData< TYPE >::unpackStream(), and SAMRAI::pdat::CellData< TYPE >::unpackStreamAndSum().
const hier::Transformation & SAMRAI::pdat::CellOverlap::getTransformation () const [virtual]
Get the Transformation from source to destination index space.
Implements SAMRAI::hier::BoxOverlap.
Referenced by SAMRAI::pdat::CellData< TYPE >::packStream().
void SAMRAI::pdat::CellOverlap::print (std::ostream & os) const [virtual]
Output the boxes in the overlap region.
Reimplemented from SAMRAI::hier::BoxOverlap.
References SAMRAI::hier::BoxContainer::begin(), and SAMRAI::hier::BoxContainer::end().
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/CellOverlap.h
source/SAMRAI/pdat/CellOverlap.C