SAMRAI: SAMRAI::hier::BoxId Class Reference
SAMRAI::hier::BoxId Class Reference
Identifier for a Box, consisting of a GlobalId and a PeriodicId.
#include <source/SAMRAI/hier/BoxId.h>
Public Member Functions
BoxId ()
Default constructor uses the default constructors for the GlobalId and PeriodicId.
BoxId (const LocalId &local_id, const int owner_rank, const PeriodicId &periodic_id=PeriodicId::zero())
Initializing constructor.
BoxId (const GlobalId &id, const PeriodicId &periodic_id=PeriodicId::zero())
Initializing constructor.
BoxId (const BoxId &other)
Copy constructor.
~BoxId ()
Destructor.
void initialize (const LocalId &local_id, const int owner_rank, const PeriodicId &periodic_id=PeriodicId::zero())
Set all the attributes to given values.
const GlobalId & getGlobalId () const
Access the GlobalId.
int getOwnerRank () const
Access the owner rank.
const LocalId & getLocalId () const
Access the LocalId.
const PeriodicId & getPeriodicId () const
Access the PeriodicId.
bool isPeriodicImage () const
Whether the PeriodicId refers to a periodic image.
bool isValid () const
Whether the BoxId is valid--meaning it has a valid GlobalId and PeriodicId.
Comparison operators
bool operator== (const BoxId &r) const
Equality operator.
bool operator!= (const BoxId &r) const
Inequality operator.
bool operator< (const BoxId &r) const
Less-than operator.
bool operator> (const BoxId &r) const
Greater-than operator.
bool operator<= (const BoxId &r) const
Less-than-or-equal-to operator.
bool operator>= (const BoxId &r) const
Greater-than-or-equal-to operator.
Friends
std::ostream & operator<< (std::ostream &co, const BoxId &r)
Format and insert the object into a stream.
Support for message passing
void putToIntBuffer (int *buffer) const
Put self into a int buffer.
void getFromIntBuffer (const int *buffer)
Set attributes according to data in int buffer.
void putToMessageStream (tbox::MessageStream &msg) const
Put self into a MessageStream.
void getFromMessageStream (tbox::MessageStream &msg)
Set attributes according to data in MessageStream.
static int commBufferSize ()
Give number of ints required for putting a BoxId in message passing buffer.
Detailed Description
Identifier for a Box, consisting of a GlobalId and a PeriodicId.
Boxes are identified by their GlobalId and PeriodicId. A Box and all its periodic images have the same GlobalId but different PeriodicId.
Comparison operators are provided to define sorted ordering of objects. The GlobalId and PeriodicId are used for all comparisons. The GlobalIds are compared first, followed by the PeriodicIds.
Constructor & Destructor Documentation
SAMRAI::hier::BoxId::BoxId ()
Default constructor uses the default constructors for the GlobalId and PeriodicId.
The object can be changed using initialize() or by assignment.
SAMRAI::hier::BoxId::BoxId (const LocalId & local_id, const int owner_rank, const PeriodicId & periodic_id = PeriodicId::zero())
Initializing constructor.
Parameters:
[in] local_id
[in] owner_rank
[in] periodic_id
Precondition:
periodic_id.isValid()
References SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
SAMRAI::hier::BoxId::BoxId (const GlobalId & id, const PeriodicId & periodic_id = PeriodicId::zero()) [explicit]
Initializing constructor.
Parameters:
[in] id
[in] periodic_id
Precondition:
periodic_id.isValid()
References SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
SAMRAI::hier::BoxId::BoxId (const BoxId & other)
Copy constructor.
Parameters:
[in] other
Precondition:
other.periodic_id.isValid()
References SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
SAMRAI::hier::BoxId::~BoxId ()
Destructor.
Member Function Documentation
void SAMRAI::hier::BoxId::initialize (const LocalId & local_id, const int owner_rank, const PeriodicId & periodic_id = PeriodicId::zero()) [inline]
Set all the attributes to given values.
Parameters:
[in] local_id
[in] owner_rank
[in] periodic_id
References SAMRAI::hier::GlobalId::getLocalId(), SAMRAI::hier::GlobalId::getOwnerRank(), and TBOX_ASSERT.
Referenced by getFromIntBuffer(), getFromMessageStream(), SAMRAI::hier::Box::initialize(), and SAMRAI::hier::Box::setLocalId().
const GlobalId& SAMRAI::hier::BoxId::getGlobalId () const [inline]
Access the GlobalId.
Referenced by SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Connector::find(), SAMRAI::hier::Connector::findLocal(), SAMRAI::hier::Box::getGlobalId(), SAMRAI::hier::Connector::getNeighborBoxes(), SAMRAI::hier::Connector::hasNeighborSet(), SAMRAI::hier::Connector::neighborhoodEqual(), SAMRAI::hier::Connector::numLocalNeighbors(), and SAMRAI::hier::Connector::writeNeighborhoodToStream().
int SAMRAI::hier::BoxId::getOwnerRank () const [inline]
Access the owner rank.
References SAMRAI::hier::GlobalId::getOwnerRank().
Referenced by SAMRAI::hier::Connector::eraseLocalNeighborhood(), SAMRAI::hier::Connector::eraseNeighbor(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::PatchLevel::getBoxForPatch(), SAMRAI::hier::BoxLevel::getBoxStrict(), SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::Box::getOwnerRank(), SAMRAI::hier::Connector::hasLocalNeighbor(), SAMRAI::hier::Connector::insertLocalNeighbor(), SAMRAI::hier::Connector::insertNeighbors(), SAMRAI::hier::Connector::makeEmptyLocalNeighborhood(), SAMRAI::hier::PatchLevel::patchTouchesRegularBoundary(), putToIntBuffer(), putToMessageStream(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), and SAMRAI::hier::Box::setLocalId().
const LocalId& SAMRAI::hier::BoxId::getLocalId () const [inline]
Access the LocalId.
References SAMRAI::hier::GlobalId::getLocalId().
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::Box::getLocalId(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), putToIntBuffer(), putToMessageStream(), and SAMRAI::hier::BoxNeighborhoodCollection::putToRestart().
const PeriodicId& SAMRAI::hier::BoxId::getPeriodicId () const [inline]
Access the PeriodicId.
Referenced by SAMRAI::hier::Box::Box(), SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::Box::getPeriodicId(), putToIntBuffer(), putToMessageStream(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), and SAMRAI::hier::Box::setLocalId().
bool SAMRAI::hier::BoxId::isPeriodicImage () const [inline]
Whether the PeriodicId refers to a periodic image.
References SAMRAI::hier::PeriodicId::zero().
Referenced by SAMRAI::hier::Box::isPeriodicImage().
bool SAMRAI::hier::BoxId::isValid () const [inline]
Whether the BoxId is valid--meaning it has a valid GlobalId and PeriodicId.
References SAMRAI::hier::LocalId::getInvalidId(), SAMRAI::tbox::SAMRAI_MPI::getInvalidRank(), SAMRAI::hier::GlobalId::getLocalId(), SAMRAI::hier::GlobalId::getOwnerRank(), and SAMRAI::hier::PeriodicId::isValid().
Referenced by SAMRAI::hier::BoxContainer::insert().
bool SAMRAI::hier::BoxId::operator== (const BoxId & r) const [inline]
Equality operator.
All comparison operators use the GlobalId and PeriodicId.
References SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
bool SAMRAI::hier::BoxId::operator!= (const BoxId & r) const [inline]
Inequality operator.
See note on comparison for operator==(const BoxId&);
References SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
bool SAMRAI::hier::BoxId::operator< (const BoxId & r) const [inline]
Less-than operator.
Compare the owner ranks first; if they compare equal, compare the LocalIds next; if they compare equal, compare the PeriodicIds.
References SAMRAI::hier::GlobalId::getLocalId(), SAMRAI::hier::GlobalId::getOwnerRank(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
bool SAMRAI::hier::BoxId::operator> (const BoxId & r) const [inline]
Greater-than operator.
Compare the owner ranks first; if they compare equal, compare the LocalIds next; if they compare equal, compare the PeriodicIds.
References SAMRAI::hier::GlobalId::getLocalId(), SAMRAI::hier::GlobalId::getOwnerRank(), SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
bool SAMRAI::hier::BoxId::operator<= (const BoxId & r) const [inline]
Less-than-or-equal-to operator.
References SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
bool SAMRAI::hier::BoxId::operator>= (const BoxId & r) const [inline]
Greater-than-or-equal-to operator.
References SAMRAI::hier::PeriodicId::isValid(), and TBOX_ASSERT.
static int SAMRAI::hier::BoxId::commBufferSize () [inline, static]
Give number of ints required for putting a BoxId in message passing buffer.
See also:
putToIntBuffer(), getFromIntBuffer().
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromIntBuffer(), and SAMRAI::hier::BoxNeighborhoodCollection::putToIntBuffer().
void SAMRAI::hier::BoxId::putToIntBuffer (int * buffer) const [inline]
Put self into a int buffer.
This is the opposite of getFromIntBuffer(). Number of ints written is given by commBufferSize().
References getLocalId(), getOwnerRank(), getPeriodicId(), SAMRAI::hier::PeriodicId::getPeriodicValue(), and SAMRAI::hier::LocalId::getValue().
Referenced by SAMRAI::hier::Box::putToIntBuffer().
void SAMRAI::hier::BoxId::getFromIntBuffer (const int * buffer) [inline]
Set attributes according to data in int buffer.
This is the opposite of putToIntBuffer(). Number of ints read is given by commBufferSize().
References initialize().
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromIntBuffer(), and SAMRAI::hier::Box::getFromIntBuffer().
void SAMRAI::hier::BoxId::putToMessageStream (tbox::MessageStream & msg) const [inline]
Put self into a MessageStream.
This is the opposite of getFromMessageStream(). Number of ints written is given by commBufferSize().
References getLocalId(), getOwnerRank(), getPeriodicId(), SAMRAI::hier::PeriodicId::getPeriodicValue(), and SAMRAI::hier::LocalId::getValue().
Referenced by SAMRAI::hier::Box::putToMessageStream().
void SAMRAI::hier::BoxId::getFromMessageStream (tbox::MessageStream & msg) [inline]
Set attributes according to data in MessageStream.
This is the opposite of putToMessageStream(). Number of ints read is given by commBufferSize().
References initialize().
Referenced by SAMRAI::hier::Box::getFromMessageStream().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & co, const BoxId & r) [friend]
Format and insert the object into a stream.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/BoxId.h
source/SAMRAI/hier/BoxId.C