SAMRAI: SAMRAI::hier::AssumedPartition Class Reference
SAMRAI::hier::AssumedPartition Class Reference
Compute an assumed partition of a set of boxes. The assumed partition should very fast to create and query and requires minimal storage.
#include <source/SAMRAI/hier/AssumedPartition.h>
Public Member Functions
AssumedPartition (const BoxContainer &unpartitioned_boxes, int rank_begin, int rank_end, int index_begin=0, double avg_parts_per_rank=1.0, bool interleave=false)
Construct AssumedPartition of a set of boxes.
AssumedPartition ()
Construct an empty AssumedPartition.
~AssumedPartition ()
Destructor.
void partition (const BoxContainer &unpartitioned_boxes, int rank_begin, int rank_end, int index_begin=0, double avg_parts_per_rank=1.0, bool interleave=false)
Partition a set of boxes, discarding the current state.
size_t getNumberOfParts () const
Number of box partitions.
int getOwner (int box_index) const
Return the owner for a partition box.
Box getBox (int box_index) const
Return partition box for given index.
void getAllBoxes (BoxContainer &all_boxes) const
Get all partition boxes.
void getAllBoxes (BoxContainer &all_boxes, int rank) const
Get all partition boxes for a given rank.
int begin () const
Return index of first partition box.
int end () const
Return one past index of last partition box.
int beginOfRank (int rank) const
Return index of first partition box assigned to given rank.
int endOfRank (int rank) const
Return one past index of last partition box assigned to given rank.
bool findOverlaps (BoxContainer &overlapping_boxes, const Box &box, const BaseGridGeometry &grid_geometry, const IntVector &refinement_ratio) const
Find box partitions overlapping the given box.
bool findOverlaps (BoxContainer &overlapping_boxes, const Box &box) const
Find partitions overlapping the given box, when all boxes are in the same block.
size_t selfCheck () const
Check the assumed partition for errors and inconsistencies. Write error diagnostics to plog.
void recursivePrint (std::ostream &os, const std::string &border, int detail_depth=2) const
Print info from this object.
Detailed Description
Compute an assumed partition of a set of boxes. The assumed partition should very fast to create and query and requires minimal storage.
An assumed partition avoids extreme imbalances, but its purpose is not fine load balancing.
See also AssumedPartitionBox.
Constructor & Destructor Documentation
SAMRAI::hier::AssumedPartition::AssumedPartition (const BoxContainer & unpartitioned_boxes, int rank_begin, int rank_end, int index_begin = 0, double avg_parts_per_rank = 1.0, bool interleave = false)
Construct AssumedPartition of a set of boxes.
Parameters:
[in] unpartitioned_boxes Incoming unpartitioned boxes
[in] rank_begin First rank
[in] rank_end One past last rank
[in] index_begin
[in] avg_parts_per_rank See partition()
[in] interleave See partition()
References partition().
SAMRAI::hier::AssumedPartition::AssumedPartition ()
Construct an empty AssumedPartition.
SAMRAI::hier::AssumedPartition::~AssumedPartition () [inline]
Destructor.
Member Function Documentation
void SAMRAI::hier::AssumedPartition::partition (const BoxContainer & unpartitioned_boxes, int rank_begin, int rank_end, int index_begin = 0, double avg_parts_per_rank = 1.0, bool interleave = false)
Partition a set of boxes, discarding the current state.
Parameters:
[in] unpartitioned_boxes Incoming unpartitioned boxes
[in] rank_begin First rank
[in] rank_end One past last rank
[in] index_begin
[in] avg_parts_per_rank Algorithm normally tries to average one partition per rank. This parameter is a request to change that.
[in] interleave Algorithm normally assign consecutive box indices to a process. This flag causes it to interleave (round-robin) the box assignments.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::size(), and TBOX_ASSERT.
Referenced by AssumedPartition().
size_t SAMRAI::hier::AssumedPartition::getNumberOfParts () const [inline]
Number of box partitions.
int SAMRAI::hier::AssumedPartition::getOwner (int box_index) const
Return the owner for a partition box.
References begin(), SAMRAI::tbox::SAMRAI_MPI::getInvalidRank(), TBOX_ASSERT, and TBOX_ERROR.
Box SAMRAI::hier::AssumedPartition::getBox (int box_index) const
Return partition box for given index.
References begin(), TBOX_ASSERT, and TBOX_ERROR.
Referenced by getAllBoxes().
void SAMRAI::hier::AssumedPartition::getAllBoxes (BoxContainer & all_boxes) const
Get all partition boxes.
void SAMRAI::hier::AssumedPartition::getAllBoxes (BoxContainer & all_boxes, int rank) const
Get all partition boxes for a given rank.
References beginOfRank(), endOfRank(), getBox(), and SAMRAI::hier::BoxContainer::push_back().
int SAMRAI::hier::AssumedPartition::begin () const [inline]
Return index of first partition box.
Referenced by beginOfRank(), endOfRank(), getBox(), getOwner(), and selfCheck().
int SAMRAI::hier::AssumedPartition::end () const [inline]
Return one past index of last partition box.
Referenced by beginOfRank(), endOfRank(), and selfCheck().
int SAMRAI::hier::AssumedPartition::beginOfRank (int rank) const
Return index of first partition box assigned to given rank.
References begin(), and end().
Referenced by getAllBoxes().
int SAMRAI::hier::AssumedPartition::endOfRank (int rank) const
Return one past index of last partition box assigned to given rank.
References begin(), and end().
Referenced by getAllBoxes().
bool SAMRAI::hier::AssumedPartition::findOverlaps (BoxContainer & overlapping_boxes, const Box & box, const BaseGridGeometry & grid_geometry, const IntVector & refinement_ratio) const
Find box partitions overlapping the given box.
Parameters:
[out] overlapping_boxes
[in] box
[in] grid_geometry
[in] refinement_ratio
Returns:
Whether any partitions are found.
References SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxContainer::size(), and SAMRAI::hier::BaseGridGeometry::transformBox().
bool SAMRAI::hier::AssumedPartition::findOverlaps (BoxContainer & overlapping_boxes, const Box & box) const
Find partitions overlapping the given box, when all boxes are in the same block.
An unrecoverable error will be thrown if there are multiple blocks.
Parameters:
[out] overlapping_boxes
[in] box
Returns:
Whether any partitions are found.
References SAMRAI::hier::BoxContainer::size(), and TBOX_ERROR.
size_t SAMRAI::hier::AssumedPartition::selfCheck () const
Check the assumed partition for errors and inconsistencies. Write error diagnostics to plog.
Returns:
Number of errors found. (Errors indicate a bug in this class.)
References begin(), end(), and SAMRAI::tbox::plog.
void SAMRAI::hier::AssumedPartition::recursivePrint (std::ostream & os, const std::string & border, int detail_depth = 2) const
Print info from this object.
Parameters:
[in,out] os The output stream
[in] border
[in] detail_depth
The documentation for this class was generated from the following files:
source/SAMRAI/hier/AssumedPartition.h
source/SAMRAI/hier/AssumedPartition.C