SAMRAI: SAMRAI::pdat::NodeGeometry Class Reference
SAMRAI::pdat::NodeGeometry Class Reference
#include <source/SAMRAI/pdat/NodeGeometry.h>
Public Types
typedef NodeOverlap Overlap
Public Member Functions
NodeGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct the node geometry object given an AMR index space box and ghost cell width.
virtual ~NodeGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in node-centered index space between the source box geometry and the destination box geometry.
void computeDestinationBoxes (hier::BoxContainer &dst_boxes, const NodeGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the node-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a EdgeOverlap object based on the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this node centered box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this node centered box geometry object.
Static Public Member Functions
static hier::Box toNodeBox (const hier::Box &box)
Convert an AMR index box space box into a node geometry box. A node geometry box is extends the given AMR index box space box by one at upper end for each coordinate direction.
static void transform (hier::Box &box, const hier::Transformation &transformation)
Transform a node-centered box.
static NodeIterator begin (const hier::Box &box)
static NodeIterator end (const hier::Box &box)
static void transform (NodeIndex &index, const hier::Transformation &transformation)
Transform a NodeIndex.
Detailed Description
Class NodeGeometry manages the mapping between the AMR index space and the node-centered geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between node- centered box geometries for communication operations.
See header file for NodeData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
NodeOverlap
Member Typedef Documentation
typedef NodeOverlap SAMRAI::pdat::NodeGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::NodeGeometry::NodeGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct the node geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::NodeGeometry::~NodeGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
static hier::Box SAMRAI::pdat::NodeGeometry::toNodeBox (const hier::Box & box) [inline, static]
Convert an AMR index box space box into a node geometry box. A node geometry box is extends the given AMR index box space box by one at upper end for each coordinate direction.
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::math::PatchNodeDataOpsInteger::abs(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchNodeDataNormOpsComplex::abs(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::add(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::addScalar(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::axmy(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::axpy(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::calculateOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::calculateOverlap(), SAMRAI::math::PatchNodeDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::PatchNodeDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), computeDestinationBoxes(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::math::PatchNodeDataOpsReal< TYPE >::copyData(), SAMRAI::math::PatchNodeDataOpsInteger::copyData(), SAMRAI::math::PatchNodeDataOpsComplex::copyData(), SAMRAI::pdat::NodeData< TYPE >::copyOnBox(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::divide(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::dot(), SAMRAI::math::PatchNodeDataNormOpsComplex::dot(), SAMRAI::pdat::OuternodeData< TYPE >::fill(), SAMRAI::pdat::NodeData< TYPE >::fill(), SAMRAI::pdat::OuternodeData< TYPE >::fillAll(), SAMRAI::pdat::NodeData< TYPE >::fillAll(), SAMRAI::pdat::OuternodeData< TYPE >::getDataBox(), SAMRAI::pdat::OuternodeData< TYPE >::getSizeOfData(), SAMRAI::pdat::NodeData< TYPE >::getSizeOfData(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::integral(), SAMRAI::math::PatchNodeDataNormOpsComplex::integral(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::L2Norm(), SAMRAI::math::PatchNodeDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::linearSum(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::max(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::PatchNodeDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchNodeDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::min(), SAMRAI::math::PatchNodeDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::multiply(), SAMRAI::pdat::NodeData< TYPE >::NodeData(), SAMRAI::math::PatchNodeDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchNodeDataNormOpsComplex::numberOfEntries(), SAMRAI::pdat::OuternodeData< TYPE >::OuternodeData(), SAMRAI::pdat::OuternodeData< TYPE >::printAxisSide(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::HierarchyNodeDataOpsReal< TYPE >::resetLevels(), SAMRAI::math::HierarchyNodeDataOpsInteger::resetLevels(), SAMRAI::math::HierarchyNodeDataOpsComplex::resetLevels(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::scale(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::setRandomValues(), SAMRAI::pdat::OuternodeGeometry::setUpOverlap(), setUpOverlap(), SAMRAI::math::PatchNodeDataBasicOps< TYPE >::subtract(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::PatchNodeDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchNodeDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::PatchNodeDataNormOpsReal< TYPE >::weightedL2Norm(), and SAMRAI::math::PatchNodeDataNormOpsComplex::weightedL2Norm().
void SAMRAI::pdat::NodeGeometry::transform (hier::Box & box, const hier::Transformation & transformation) [static]
Transform a node-centered box.
At input, the Box is assumed to represent an node-centered box. The Box will be transformed according to the coordinate system transformation defined by the Transformation object.
Parameters:
[in,out] box
[in] transformation
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::IntVector::getOne(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::hier::Box::setUpper(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::Box::upper().
NodeIterator SAMRAI::pdat::NodeGeometry::begin (const hier::Box & box) [static]
Referenced by SAMRAI::pdat::NodeData< TYPE >::print().
NodeIterator SAMRAI::pdat::NodeGeometry::end (const hier::Box & box) [static]
Referenced by SAMRAI::pdat::NodeData< TYPE >::print().
void SAMRAI::pdat::NodeGeometry::transform (NodeIndex & index, const hier::Transformation & transformation) [static]
Transform a NodeIndex.
This static method applies a coordinate system transformation to the given NodeIndex.
Parameters:
[in,out] index
[in] transformation
References SAMRAI::hier::Index::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, and TBOX_ERROR.
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::NodeGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in node-centered index space between the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::pdat::NodeGeometry::computeDestinationBoxes (hier::BoxContainer & dst_boxes, const NodeGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const
Compute the node-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
Precondition:
src_mask.getDim() == transformation.getOffset.getDim()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxContainer::intersectBoxes(), SAMRAI::hier::BoxContainer::pushBack(), SAMRAI::hier::BoxContainer::removeIntersections(), TBOX_ASSERT_OBJDIM_EQUALITY2, toNodeBox(), and SAMRAI::hier::Transformation::transform().
Referenced by SAMRAI::pdat::SecondLayerNodeVariableFillPattern::calculateOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::calculateOverlap(), and SAMRAI::pdat::FirstLayerNodeVariableFillPattern::calculateOverlap().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::NodeGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a EdgeOverlap object based on the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::pushBack(), and toNodeBox().
const hier::Box& SAMRAI::pdat::NodeGeometry::getBox () const [inline]
Return the box for this node centered box geometry object.
const hier::IntVector& SAMRAI::pdat::NodeGeometry::getGhosts () const [inline]
Return the ghost cell width for this node centered box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/NodeGeometry.h
source/SAMRAI/pdat/NodeGeometry.C