SAMRAI: SAMRAI::tbox::ParallelBuffer Class Reference
SAMRAI::tbox::ParallelBuffer Class Reference
#include <source/SAMRAI/tbox/ParallelBuffer.h>
Public Member Functions
ParallelBuffer ()
~ParallelBuffer ()
void setActive (bool active)
void setPrefixString (const std::string &text)
void setOutputStream1 (std::ostream *stream)
void setOutputStream2 (std::ostream *stream)
void outputString (const std::string &text)
void outputString (const std::string &text, const int length)
int sync ()
int overflow (int ch)
Detailed Description
Class ParallelBuffer is a simple I/O stream utility that intercepts output from an ostream and redirects the output as necessary for parallel I/O. This class defines a stream buffer class for an ostream class.
Constructor & Destructor Documentation
SAMRAI::tbox::ParallelBuffer::ParallelBuffer ()
Create a parallel buffer class. The object will require further initialization to set up the I/O streams and prefix string.
References TBOX_omp_init_lock.
SAMRAI::tbox::ParallelBuffer::~ParallelBuffer ()
The destructor simply deallocates any internal data buffers. It does not modify the output streams.
References TBOX_omp_destroy_lock.
Member Function Documentation
void SAMRAI::tbox::ParallelBuffer::setActive (bool active)
Set whether the output stream will be active. If the parallel buffer stream is disabled, then no data is forwarded to the output streams. The internal data buffer is deallocated and pointers are reset whenever the parallel buffer is deactivated.
References TBOX_omp_set_lock, and TBOX_omp_unset_lock.
Referenced by SAMRAI::tbox::PIO::initialize(), SAMRAI::tbox::PIO::logAllNodes(), SAMRAI::tbox::PIO::logOnlyNodeZero(), SAMRAI::tbox::PIO::resumeLogging(), and SAMRAI::tbox::PIO::suspendLogging().
void SAMRAI::tbox::ParallelBuffer::setPrefixString (const std::string & text) [inline]
Set the prefix that begins every new line to the output stream. A sample prefix is "P=XXXXX: ", where XXXXX represents the node number.
Referenced by SAMRAI::tbox::PIO::initialize().
void SAMRAI::tbox::ParallelBuffer::setOutputStream1 (std::ostream * stream) [inline]
Set the primary output stream. If not NULL, then output data is sent to this stream. The primary output stream is typically stderr or stdout or perhaps a log file.
Referenced by SAMRAI::tbox::PIO::initialize(), SAMRAI::tbox::PIO::logAllNodes(), SAMRAI::tbox::PIO::logOnlyNodeZero(), SAMRAI::tbox::PIO::resumeLogging(), and SAMRAI::tbox::PIO::suspendLogging().
void SAMRAI::tbox::ParallelBuffer::setOutputStream2 (std::ostream * stream) [inline]
Set the secondary output stream. If not NULL, then output data is sent to this stream. The secondary output stream is typically NULL or a log file that mirrors the primary output stream.
Referenced by SAMRAI::tbox::PIO::initialize(), SAMRAI::tbox::PIO::logAllNodes(), SAMRAI::tbox::PIO::logOnlyNodeZero(), SAMRAI::tbox::PIO::resumeLogging(), and SAMRAI::tbox::PIO::suspendLogging().
void SAMRAI::tbox::ParallelBuffer::outputString (const std::string & text) [inline]
Write a text string to the output stream. Note that the string is not actually written until an end-of-line is detected.
Referenced by outputString(), overflow(), and sync().
void SAMRAI::tbox::ParallelBuffer::outputString (const std::string & text, const int length)
Write a text string of the specified length to the output file. Note that the string is not actually written until an end-of-line is detected.
References NULL_STATEMENT, outputString(), TBOX_omp_set_lock, and TBOX_omp_unset_lock.
int SAMRAI::tbox::ParallelBuffer::sync ()
Synchronize the parallel buffer (called from streambuf).
References outputString().
Referenced by overflow().
int SAMRAI::tbox::ParallelBuffer::overflow (int ch)
Write an overflow character into the parallel buffer (called from streambuf).
References outputString(), and sync().
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/ParallelBuffer.h
source/SAMRAI/tbox/ParallelBuffer.C