SAMRAI: SAMRAI::xfer::RefinePatchStrategy Class Reference
SAMRAI::xfer::RefinePatchStrategy Class Reference
Abstract base class for user-defined patch data refining operations and physical boundary filling operations.
#include <source/SAMRAI/xfer/RefinePatchStrategy.h>
Public Member Functions
RefinePatchStrategy ()
Constructor.
virtual ~RefinePatchStrategy ()
Destructor.
virtual void setPhysicalBoundaryConditions (hier::Patch &patch, const double fill_time, const hier::IntVector &ghost_width_to_fill)=0
Pure virtual function interface for physical boundary filling.
virtual hier::IntVector getRefineOpStencilWidth (const tbox::Dimension &dim) const =0
Return maximum stencil width needed for user-defined data refinement operations performed by this object.
virtual void preprocessRefine (hier::Patch &fine, const hier::Patch &coarse, const hier::Box &fine_box, const hier::IntVector &ratio)=0
Perform user-defined patch data refinement operations.
virtual void postprocessRefine (hier::Patch &fine, const hier::Patch &coarse, const hier::Box &fine_box, const hier::IntVector &ratio)=0
Perform user-defined patch data refinement operations.
virtual void preprocessRefineBoxes (hier::Patch &fine, const hier::Patch &coarse, const hier::BoxContainer &fine_boxes, const hier::IntVector &ratio)
virtual void postprocessRefineBoxes (hier::Patch &fine, const hier::Patch &coarse, const hier::BoxContainer &fine_boxes, const hier::IntVector &ratio)
virtual void preprocessRefineLevel (hier::PatchLevel &fine_level, const hier::PatchLevel &coarse_level, const hier::Connector &coarse_to_fine, const hier::Connector &coarse_to_unfilled, const std::vector< std::vector< boost::shared_ptr< hier::BoxOverlap > > > &overlaps, const RefineClasses::Data **refine_items)
Perform user-defined patch data pre-refinement operations on a PatchLevel.
virtual void postprocessRefineLevel (hier::PatchLevel &fine_level, const hier::PatchLevel &coarse_level, const hier::Connector &coarse_to_fine, const hier::Connector &coarse_to_unfilled)
Perform user-defined patch data post-refinement operations on a PatchLevel.
Static Public Member Functions
static hier::IntVector getMaxRefineOpStencilWidth (const tbox::Dimension &dim)
Get the maximum stencil width over all RefinePatchStrategy objects used in an application.
Detailed Description
Abstract base class for user-defined patch data refining operations and physical boundary filling operations.
RefinePatchStrategy provides an interface for a user to supply methods for application-specific refining of data between levels in an AMR patch hierarchy and filling of physical boundary values. A concrete subclass must define four member functions to perform the following tasks:
define maximum stencil width for user-defined refine operations
fill physical boundary conditions
preprocess the interpolation
postprocess the interpolation
Note that the preprocess member function is called before standard data refine using RefineOperators and the postprocessor member function is called afterwards.
There are two versions of the preprocess and postprocess functions. The default abstract function only takes a single box. The user may also over-ride preprocess and postprocess functions that take a box list and process an entire patch at one time. By default, the box list version loops over all of the boxes in the box list and calls the single box version.
For operations on a mesh with block-singularities, implementations of this class must also inherit and implement SingularityPatchStrategy.
See also:
RefineAlgorithm
RefineSchedule
Constructor & Destructor Documentation
SAMRAI::xfer::RefinePatchStrategy::RefinePatchStrategy ()
Constructor.
The constructor will register the constructed object with a static set that manages all RefinePatchStrategy objects in an application.
SAMRAI::xfer::RefinePatchStrategy::~RefinePatchStrategy () [virtual]
Destructor.
Member Function Documentation
hier::IntVector SAMRAI::xfer::RefinePatchStrategy::getMaxRefineOpStencilWidth (const tbox::Dimension & dim) [static]
Get the maximum stencil width over all RefinePatchStrategy objects used in an application.
Returns:
The maximum of the return values of calls to getRefineOpStencilWidth() for every RefinePatchStrategy of the given Dimension used in an application.
Parameters:
[in] dim
References getRefineOpStencilWidth(), and SAMRAI::hier::IntVector::max().
Referenced by SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths().
virtual void SAMRAI::xfer::RefinePatchStrategy::setPhysicalBoundaryConditions (hier::Patch & patch, const double fill_time, const hier::IntVector & ghost_width_to_fill) [pure virtual]
Pure virtual function interface for physical boundary filling.
Set data in ghost regions at patch boundaries that touch the physical domain boundary. The specific data values set in physical boundary ghost regions are determined by the boundary conditions needed by the user application. The patch data components that should be set in this function correspond to the "scratch" components specified in calls to the registerRefine() function in the RefineAlgorithm class.
Parameters:
[out] patch Patch on which to fill boundary data.
[in] fill_time Simulation time for boundary filling.
[in] ghost_width_to_fill Maximum ghost width to fill over all registered scratch components.
Implemented in SAMRAI::mesh::MultiblockGriddingTagger, SAMRAI::solv::CartesianRobinBcHelper, SAMRAI::algs::HyperbolicPatchStrategy, and SAMRAI::algs::MethodOfLinesPatchStrategy.
virtual hier::IntVector SAMRAI::xfer::RefinePatchStrategy::getRefineOpStencilWidth (const tbox::Dimension & dim) const [pure virtual]
Return maximum stencil width needed for user-defined data refinement operations performed by this object.
This is needed to determine the correct interpolatin data dependencies and to ensure that the data has a sufficient amount of ghost width.
For any user-defined interpolation operations implemented in the preprocess or postprocess methods, return the maximum stencil needed on a coarse patch to refine data to a fine patch. If your implementation doesn't work with the given dimension, return zero.
Implemented in SAMRAI::mesh::MultiblockGriddingTagger, and SAMRAI::solv::CartesianRobinBcHelper.
Referenced by getMaxRefineOpStencilWidth().
virtual void SAMRAI::xfer::RefinePatchStrategy::preprocessRefine (hier::Patch & fine, const hier::Patch & coarse, const hier::Box & fine_box, const hier::IntVector & ratio) [pure virtual]
Perform user-defined patch data refinement operations.
This member function is called before standard refine operations (expressed using concrete subclasses of the RefineOperator base class). The preprocess function must refine data from the scratch components on the coarse patch into the scratch components of the fine patch on the specified fine box region. Recall that the scratch components are specified in calls to the registerRefine() function in the RefineAlgorithm class.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_box Box region on fine patch into which data is refined.
[in] ratio Refinement ratio between coarse and fine patches.
Implemented in SAMRAI::mesh::MultiblockGriddingTagger, and SAMRAI::solv::CartesianRobinBcHelper.
Referenced by preprocessRefineBoxes().
virtual void SAMRAI::xfer::RefinePatchStrategy::postprocessRefine (hier::Patch & fine, const hier::Patch & coarse, const hier::Box & fine_box, const hier::IntVector & ratio) [pure virtual]
Perform user-defined patch data refinement operations.
This member function is called after standard refine operations (expressed using concrete subclasses of the RefineOperator base class). The preprocess function must refine data from the scratch components on the coarse patch into the scratch components of the fine patch on the specified fine box region. Recall that the scratch components are specified in calls to the registerRefine() function in the RefineAlgorithm class.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_box Box region on fine patch into which data is refined. *
[in] ratio Refinement ratio between coarse and fine patches.
Implemented in SAMRAI::mesh::MultiblockGriddingTagger, and SAMRAI::solv::CartesianRobinBcHelper.
Referenced by postprocessRefineBoxes().
virtual void SAMRAI::xfer::RefinePatchStrategy::preprocessRefineBoxes (hier::Patch & fine, const hier::Patch & coarse, const hier::BoxContainer & fine_boxes, const hier::IntVector & ratio) [inline, virtual]
Perform user-defined patch data refinement operations on a list of boxes.
This member function is called before standard refining operations (expressed using concrete subclasses of the RefineOperator base class).
The default implementation of this virtual function loops over the box list and calls the preprocessRefine() method for a single box.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_boxes List of box regions on fine patch into which data is refined.
[in] ratio Refinement ratio between coarse and fine patches.
Precondition:
(fine.getDim() == coarse.getDim()) && (fine.getDim() == ratio.getDim())
Reimplemented in SAMRAI::solv::CartesianRobinBcHelper.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), preprocessRefine(), and TBOX_ASSERT_OBJDIM_EQUALITY3.
virtual void SAMRAI::xfer::RefinePatchStrategy::postprocessRefineBoxes (hier::Patch & fine, const hier::Patch & coarse, const hier::BoxContainer & fine_boxes, const hier::IntVector & ratio) [inline, virtual]
Perform user-defined patch data refinement operations on a list of boxes.
This member function is called after standard refining operations (expressed using concrete subclasses of the RefineOperator base class).
The default implementation of this virtual function loops over the box list and calls the postprocessRefine() method for a single box.
Parameters:
[out] fine Fine patch containing destination data.
[in] coarse Coarse patch containing source data.
[in] fine_boxes List of box regions on fine patch into which data is refined.
[in] ratio Refinement ratio between coarse and fine patches.
Precondition:
(fine.getDim() == coarse.getDim()) && (fine.getDim() == ratio.getDim())
Reimplemented in SAMRAI::solv::CartesianRobinBcHelper.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), postprocessRefine(), and TBOX_ASSERT_OBJDIM_EQUALITY3.
virtual void SAMRAI::xfer::RefinePatchStrategy::preprocessRefineLevel (hier::PatchLevel & fine_level, const hier::PatchLevel & coarse_level, const hier::Connector & coarse_to_fine, const hier::Connector & coarse_to_unfilled, const std::vector< std::vector< boost::shared_ptr< hier::BoxOverlap > > > & overlaps, const RefineClasses::Data ** refine_items) [inline, virtual]
Perform user-defined patch data pre-refinement operations on a PatchLevel.
This member function is called before standard refine operations (expressed using concrete subclasses of the RefineOperator base class).
Parameters:
[out] fine_level Fine patch level containing destination data.
[in] coarse_level Coarse patch level containing source data.
[in] coarse_to_fine Connector coarse to fine
[in] coarse_to_unfilled Connector coarse to level representing boxes that need to be filled.
[in] overlaps
[in] refine_items
References NULL_USE.
virtual void SAMRAI::xfer::RefinePatchStrategy::postprocessRefineLevel (hier::PatchLevel & fine_level, const hier::PatchLevel & coarse_level, const hier::Connector & coarse_to_fine, const hier::Connector & coarse_to_unfilled) [inline, virtual]
Perform user-defined patch data post-refinement operations on a PatchLevel.
This member function is called after standard refine operations (expressed using concrete subclasses of the RefineOperator base class).
Parameters:
[out] fine_level Fine patch level containing destination data.
[in] coarse_level Coarse patch level containing source data.
[in] coarse_to_fine Connector coarse to fine
[in] coarse_to_unfilled Connector coarse to level representing boxes that need to be filled.
References NULL_USE.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/RefinePatchStrategy.h
source/SAMRAI/xfer/RefinePatchStrategy.C