SAMRAI: SAMRAI::tbox::CenteredRankTree Class Reference
SAMRAI::tbox::CenteredRankTree Class Reference
Implementation of RankTreeStrategy aranging ranks with the root at the center of its descendent ranks.
#include <source/SAMRAI/tbox/CenteredRankTree.h>
Public Member Functions
CenteredRankTree ()
Constructor.
CenteredRankTree (const SAMRAI_MPI &mpi, bool make_first_rank_the_root=true)
Initializing constructor.
CenteredRankTree (int first_rank, int last_rank, int rank, bool make_first_rank_the_root=true)
Initializing constructor.
~CenteredRankTree ()
Destructor.
void setupTree (const RankGroup &rank_group, int my_rank)
Set up the tree.
int getRank () const
Access the rank used to initialize.
int getParentRank () const
Access the parent rank.
int getChildRank (unsigned int child_number) const
Access a child rank.
unsigned int getNumberOfChildren () const
Return the number of children.
unsigned int getChildNumber () const
Return the child number, or invalidChildNumber() if is root of the tree.
unsigned int getDegree () const
Return the degree of the tree (the maximum number of children each node may have).
unsigned int getGenerationNumber () const
Return the generation number.
int getRootRank () const
Return the rank of the root of the tree.
void makeFirstRankTheRoot (bool make_first_rank_the_root)
Set whether to use the first rank in the range for the root instead of the rank at the middle of the range.
Detailed Description
Implementation of RankTreeStrategy aranging ranks with the root at the center of its descendent ranks.
An example of a tree created is
 *                     7
 *                    / \
 *                   /   \
 *                  /     \
 *                 3       11
 *                / \     / \
 *               1   5   9   13
 *              /|  /|  /|   |\
 *             0 2 4 6 8 10 12 14
 *
 * or with 0 at the root:
 *                     0
 *                    / \
 *                   /   \
 *                  /     \
 *                 4       11
 *                / \     / \
 *               2   6   9   13
 *              /|  /|  /|   |\
 *             1 3 5 7 8 10 12 14
 *
The root of tree is the center, rounded up, of the rank in it left and right branches. The exception is the case where we force the first rank to be the root of the entire tree (
See also:
makeFirstRankTheRoot()).
Nodes that are close together in the tree tends to be close together in natural ordering. Without knowing about the underlying message passing network structure, we assume that close natural ordering usually means close together on the network. Thus nodes close together in the tree are also close together on the network. Thus, communication between nearest neighbors in the tree tend to be faster. If the weight of each edge is the difference in ranks of its nodes, the sum of all weights in a tree of N nodes is N*ln(N).
The tree formed by this class has the property that each and every subtree is composed nodes with contiguous natural ordering. This again benefits communication.
Constructor & Destructor Documentation
SAMRAI::tbox::CenteredRankTree::CenteredRankTree ()
Constructor.
SAMRAI::tbox::CenteredRankTree::CenteredRankTree (const SAMRAI_MPI & mpi, bool make_first_rank_the_root = true)
Initializing constructor.
See also:
setupTree()
Parameters:
[in] mpi
[in] make_first_rank_the_root See makeFirstRankTheRoot()
References SAMRAI::tbox::SAMRAI_MPI::getRank(), and SAMRAI::tbox::SAMRAI_MPI::getSize().
SAMRAI::tbox::CenteredRankTree::CenteredRankTree (int first_rank, int last_rank, int rank, bool make_first_rank_the_root = true)
Initializing constructor.
See also:
setupTree()
Parameters:
[in] first_rank
[in] last_rank
[in] rank
[in] make_first_rank_the_root See makeFirstRankTheRoot()
SAMRAI::tbox::CenteredRankTree::~CenteredRankTree ()
Destructor.
Deallocate internal data.
Member Function Documentation
void SAMRAI::tbox::CenteredRankTree::setupTree (const RankGroup & rank_group, int my_rank) [virtual]
Set up the tree.
Set up the tree for the processors in the given RankGroup. Prepare to provide tree data for the given rank.
Parameters:
[in] rank_group
[in] my_rank The rank whose parent and children are sought, usually the local process.
Implements SAMRAI::tbox::RankTreeStrategy.
References SAMRAI::tbox::RankGroup::getMapIndex(), SAMRAI::tbox::RankGroup::isMember(), SAMRAI::tbox::RankGroup::size(), and TBOX_ASSERT.
int SAMRAI::tbox::CenteredRankTree::getRank () const [inline, virtual]
Access the rank used to initialize.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::CenteredRankTree::getParentRank () const [inline, virtual]
Access the parent rank.
Implements SAMRAI::tbox::RankTreeStrategy.
Referenced by SAMRAI::hier::Connector::computeTransposeOf().
int SAMRAI::tbox::CenteredRankTree::getChildRank (unsigned int child_number) const [inline, virtual]
Access a child rank.
Implements SAMRAI::tbox::RankTreeStrategy.
References SAMRAI::tbox::RankTreeStrategy::getInvalidRank().
Referenced by SAMRAI::hier::Connector::computeTransposeOf().
unsigned int SAMRAI::tbox::CenteredRankTree::getNumberOfChildren () const [inline, virtual]
Return the number of children.
Implements SAMRAI::tbox::RankTreeStrategy.
Referenced by SAMRAI::hier::Connector::computeTransposeOf().
unsigned int SAMRAI::tbox::CenteredRankTree::getChildNumber () const [inline, virtual]
Return the child number, or invalidChildNumber() if is root of the tree.
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::CenteredRankTree::getDegree () const [inline, virtual]
Return the degree of the tree (the maximum number of children each node may have).
Implements SAMRAI::tbox::RankTreeStrategy.
unsigned int SAMRAI::tbox::CenteredRankTree::getGenerationNumber () const [inline, virtual]
Return the generation number.
Implements SAMRAI::tbox::RankTreeStrategy.
int SAMRAI::tbox::CenteredRankTree::getRootRank () const [inline, virtual]
Return the rank of the root of the tree.
Implements SAMRAI::tbox::RankTreeStrategy.
void SAMRAI::tbox::CenteredRankTree::makeFirstRankTheRoot (bool make_first_rank_the_root) [inline]
Set whether to use the first rank in the range for the root instead of the rank at the middle of the range.
Default choice is false. To change the choice, this call must be made before setupTree().
References SAMRAI::tbox::RankTreeStrategy::getInvalidRank(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/tbox/CenteredRankTree.h
source/SAMRAI/tbox/CenteredRankTree.C