SAMRAI: SAMRAI::pdat::EdgeGeometry Class Reference
SAMRAI::pdat::EdgeGeometry Class Reference
#include <source/SAMRAI/pdat/EdgeGeometry.h>
Public Types
typedef EdgeOverlap Overlap
Public Member Functions
EdgeGeometry (const hier::Box &box, const hier::IntVector &ghosts)
Construct the edge geometry object given an AMR index space box and ghost cell width.
virtual ~EdgeGeometry ()
The virtual destructor does nothing interesting.
virtual boost::shared_ptr
< hier::BoxOverlap > calculateOverlap (const hier::BoxGeometry &dst_geometry, const hier::BoxGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const bool retry, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the overlap in edge-centered index space between the source box geometry and the destination box geometry.
void computeDestinationBoxes (std::vector< hier::BoxContainer > &dst_boxes, const EdgeGeometry &src_geometry, const hier::Box &src_mask, const hier::Box &fill_box, const bool overwrite_interior, const hier::Transformation &transformation, const hier::BoxContainer &dst_restrict_boxes=hier::BoxContainer()) const
Compute the edge-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
virtual boost::shared_ptr
< hier::BoxOverlap > setUpOverlap (const hier::BoxContainer &boxes, const hier::Transformation &transformation) const
Set up a EdgeOverlap object based on the given boxes and the transformation.
const hier::Box & getBox () const
Return the box for this edge centered box geometry object.
const hier::IntVector & getGhosts () const
Return the ghost cell width for this edge centered box geometry object.
Static Public Member Functions
static hier::Box toEdgeBox (const hier::Box &box, int axis_direction)
Convert an AMR index box space box into an edge geometry box. An edge geometry box extends the given AMR index box space box by one in upper end for each coordinate direction not equal to the axis direction.
static void transform (hier::Box &box, int &axis_direction, const hier::Transformation &transformation)
Transform an edge-centered box.
static void transform (EdgeIndex &index, const hier::Transformation &transformation)
Transform an EdgeIndex.
static EdgeIterator begin (const hier::Box &box, int axis)
static EdgeIterator end (const hier::Box &box, int axis)
Detailed Description
Class EdgeGeometry manages the mapping between the AMR index space and the edge-centered geometry index space. It is a subclass of hier::BoxGeometry and it computes intersections between edge- centered box geometries for communication operations.
See header file for EdgeData<TYPE> class for a more detailed description of the data layout.
See also:
hier::BoxGeometry
pdat::EdgeOverlap
Member Typedef Documentation
typedef EdgeOverlap SAMRAI::pdat::EdgeGeometry::Overlap
The BoxOverlap implemenation for this geometry.
Constructor & Destructor Documentation
SAMRAI::pdat::EdgeGeometry::EdgeGeometry (const hier::Box & box, const hier::IntVector & ghosts)
Construct the edge geometry object given an AMR index space box and ghost cell width.
Precondition:
box.getDim() == ghosts.getDim()
ghosts.min() >= 0
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
SAMRAI::pdat::EdgeGeometry::~EdgeGeometry () [virtual]
The virtual destructor does nothing interesting.
Member Function Documentation
hier::Box SAMRAI::pdat::EdgeGeometry::toEdgeBox (const hier::Box & box, int axis_direction) [static]
Convert an AMR index box space box into an edge geometry box. An edge geometry box extends the given AMR index box space box by one in upper end for each coordinate direction not equal to the axis direction.
Precondition:
(0 <= axis) && (axis < box.getDim().getValue())
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::setUpper(), and TBOX_ASSERT.
Referenced by SAMRAI::math::PatchEdgeDataOpsInteger::abs(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::abs(), SAMRAI::math::PatchEdgeDataNormOpsComplex::abs(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::add(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::addScalar(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::axmy(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::axpy(), SAMRAI::math::PatchEdgeDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::PatchEdgeDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), computeDestinationBoxes(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::math::PatchEdgeDataOpsReal< TYPE >::copyData(), SAMRAI::math::PatchEdgeDataOpsInteger::copyData(), SAMRAI::math::PatchEdgeDataOpsComplex::copyData(), SAMRAI::pdat::EdgeData< TYPE >::copyOnBox(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::divide(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::dot(), SAMRAI::math::PatchEdgeDataNormOpsComplex::dot(), SAMRAI::pdat::EdgeData< TYPE >::EdgeData(), SAMRAI::pdat::OuteredgeData< TYPE >::fill(), SAMRAI::pdat::EdgeData< TYPE >::fill(), SAMRAI::pdat::OuteredgeData< TYPE >::fillAll(), SAMRAI::pdat::EdgeData< TYPE >::fillAll(), SAMRAI::pdat::EdgeData< TYPE >::getSizeOfData(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::integral(), SAMRAI::math::PatchEdgeDataNormOpsComplex::integral(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::L2Norm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::linearSum(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::max(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::PatchEdgeDataNormOpsComplex::maxNorm(), SAMRAI::math::PatchEdgeDataMiscellaneousOpsReal< TYPE >::maxPointwiseDivide(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::min(), SAMRAI::math::PatchEdgeDataMiscellaneousOpsReal< TYPE >::minPointwiseDivide(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::multiply(), SAMRAI::math::PatchEdgeDataOpsInteger::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchEdgeDataNormOpsComplex::numberOfEntries(), SAMRAI::pdat::OuteredgeData< TYPE >::printAxisSide(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::reciprocal(), SAMRAI::math::HierarchyEdgeDataOpsReal< TYPE >::resetLevels(), SAMRAI::math::HierarchyEdgeDataOpsInteger::resetLevels(), SAMRAI::math::HierarchyEdgeDataOpsComplex::resetLevels(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::scale(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::setRandomValues(), SAMRAI::pdat::OuteredgeGeometry::setUpOverlap(), setUpOverlap(), SAMRAI::math::PatchEdgeDataBasicOps< TYPE >::subtract(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::PatchEdgeDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchEdgeDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::pdat::OuteredgeGeometry::toOuteredgeBox(), SAMRAI::math::PatchEdgeDataNormOpsReal< TYPE >::weightedL2Norm(), and SAMRAI::math::PatchEdgeDataNormOpsComplex::weightedL2Norm().
void SAMRAI::pdat::EdgeGeometry::transform (hier::Box & box, int & axis_direction, const hier::Transformation & transformation) [static]
Transform an edge-centered box.
At input, the Box is assumed to represent an edge-centered box with the given axis direction. The Box will be transformed according to the coordinate system transformation defined by the Transformation object. At output, axis_direction will represent the output box's new axis direction.
Parameters:
[in,out] box
[in,out] axis_direction
[in] transformation
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_JUP_KUP, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::hier::Box::setUpper(), SAMRAI::hier::Transformation::transform(), and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::pdat::EdgeOverlap::getSourceBoxContainer().
void SAMRAI::pdat::EdgeGeometry::transform (EdgeIndex & index, const hier::Transformation & transformation) [static]
Transform an EdgeIndex.
This static method applies a coordinate system transformation to the given EdgeIndex.
Parameters:
[in,out] index
[in] transformation
References SAMRAI::pdat::EdgeIndex::getAxis(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::Transformation::getOffset(), SAMRAI::hier::Transformation::getRotation(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Transformation::IDOWN_JDOWN_KUP, SAMRAI::hier::Transformation::IDOWN_JUP_KDOWN, SAMRAI::hier::Transformation::IDOWN_KDOWN_JDOWN, SAMRAI::hier::Transformation::IDOWN_KUP_JUP, SAMRAI::hier::Transformation::IUP_JDOWN_KDOWN, SAMRAI::hier::Transformation::IUP_KDOWN_JUP, SAMRAI::hier::Transformation::IUP_KUP_JDOWN, SAMRAI::hier::Transformation::JDOWN_IDOWN_KDOWN, SAMRAI::hier::Transformation::JDOWN_IUP_KUP, SAMRAI::hier::Transformation::JDOWN_KDOWN_IUP, SAMRAI::hier::Transformation::JDOWN_KUP_IDOWN, SAMRAI::hier::Transformation::JUP_IDOWN_KUP, SAMRAI::hier::Transformation::JUP_IUP_KDOWN, SAMRAI::hier::Transformation::JUP_KDOWN_IDOWN, SAMRAI::hier::Transformation::JUP_KUP_IUP, SAMRAI::hier::Transformation::KDOWN_IDOWN_JUP, SAMRAI::hier::Transformation::KDOWN_IUP_JDOWN, SAMRAI::hier::Transformation::KDOWN_JDOWN_IDOWN, SAMRAI::hier::Transformation::KDOWN_JUP_IUP, SAMRAI::hier::Transformation::KUP_IDOWN_JDOWN, SAMRAI::hier::Transformation::KUP_IUP_JUP, SAMRAI::hier::Transformation::KUP_JDOWN_IUP, SAMRAI::hier::Transformation::KUP_JUP_IDOWN, SAMRAI::hier::Transformation::NO_ROTATE, SAMRAI::pdat::EdgeIndex::setAxis(), TBOX_ASSERT, and TBOX_ERROR.
EdgeIterator SAMRAI::pdat::EdgeGeometry::begin (const hier::Box & box, int axis) [static]
Referenced by SAMRAI::pdat::EdgeData< TYPE >::printAxis().
EdgeIterator SAMRAI::pdat::EdgeGeometry::end (const hier::Box & box, int axis) [static]
Referenced by SAMRAI::pdat::EdgeData< TYPE >::printAxis().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::EdgeGeometry::calculateOverlap (const hier::BoxGeometry & dst_geometry, const hier::BoxGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const bool retry, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const [virtual]
Compute the overlap in edge-centered index space between the source box geometry and the destination box geometry.
Precondition:
getBox().getDim() == src_mask.getDim()
References SAMRAI::hier::BoxGeometry::calculateOverlap(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::pdat::EdgeGeometry::computeDestinationBoxes (std::vector< hier::BoxContainer > & dst_boxes, const EdgeGeometry & src_geometry, const hier::Box & src_mask, const hier::Box & fill_box, const bool overwrite_interior, const hier::Transformation & transformation, const hier::BoxContainer & dst_restrict_boxes = hier::BoxContainer()) const
Compute the edge-centered destination boxes that represent the overlap between the source box geometry and the destination box geometry.
Precondition:
src_mask.getDim() == transformation.getOffset.getDim()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getDim(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxContainer::pushBack(), toEdgeBox(), and SAMRAI::hier::Transformation::transform().
boost::shared_ptr< hier::BoxOverlap > SAMRAI::pdat::EdgeGeometry::setUpOverlap (const hier::BoxContainer & boxes, const hier::Transformation & transformation) const [virtual]
Set up a EdgeOverlap object based on the given boxes and the transformation.
Implements SAMRAI::hier::BoxGeometry.
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Transformation::getOffset(), and toEdgeBox().
const hier::Box& SAMRAI::pdat::EdgeGeometry::getBox () const [inline]
Return the box for this edge centered box geometry object.
const hier::IntVector& SAMRAI::pdat::EdgeGeometry::getGhosts () const [inline]
Return the ghost cell width for this edge centered box geometry object.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/EdgeGeometry.h
source/SAMRAI/pdat/EdgeGeometry.C