SAMRAI: SAMRAI::xfer::CoarsenAlgorithm Class Reference
SAMRAI::xfer::CoarsenAlgorithm Class Reference
Class CoarsenAlgorithm encapsulates the AMR communication pattern to coarsen data from a finer level to any coarser level.
#include <source/SAMRAI/xfer/CoarsenAlgorithm.h>
Public Member Functions
CoarsenAlgorithm (const tbox::Dimension &dim, bool fill_coarse_data=false)
Construct a coarsening algorithm and initialize its basic state.
~CoarsenAlgorithm ()
The destructor releases all internal storage.
void registerCoarsen (const int dst, const int src, const boost::shared_ptr< hier::CoarsenOperator > &opcoarsen, const hier::IntVector &gcw_to_coarsen, const boost::shared_ptr< VariableFillPattern > &var_fill_pattern=boost::shared_ptr< VariableFillPattern >())
Register a coarsening operation with the coarsening algorithm.
void registerCoarsen (const int dst, const int src, const boost::shared_ptr< hier::CoarsenOperator > &opcoarsen, const boost::shared_ptr< VariableFillPattern > &var_fill_pattern=boost::shared_ptr< VariableFillPattern >())
Register a coarsening operation with the coarsening algorithm.
boost::shared_ptr
< CoarsenSchedule > createSchedule (const boost::shared_ptr< hier::PatchLevel > &crse_level, const boost::shared_ptr< hier::PatchLevel > &fine_level, CoarsenPatchStrategy *coarsen_strategy=0, const boost::shared_ptr< CoarsenTransactionFactory > &transaction_factory=boost::shared_ptr< CoarsenTransactionFactory >())
Create a communication schedule to coarsen data from the given fine patch level to the given coarse patch level.
bool checkConsistency (const boost::shared_ptr< CoarsenSchedule > &schedule) const
Given a previously-generated coarsen schedule, check for consistency with this coarsen algorithm object to see whether a call to resetSchedule is a valid operation.
void resetSchedule (const boost::shared_ptr< CoarsenSchedule > &schedule) const
Given a previously-generated coarsen schedule, reconfigure it to peform the communication operations registered with this coarsen algorithm object.
void printClassData (std::ostream &stream) const
Print the coarsen algorithm state to the specified data stream.
const tbox::Dimension & getDim () const
Return the dimension of this object.
Detailed Description
Class CoarsenAlgorithm encapsulates the AMR communication pattern to coarsen data from a finer level to any coarser level.
Most often, data is coarsened from the interiors of source patch components on the source patch level into interiors of destination patch components on the destination level. If the coarsening operators require ghost cells on a source component, then sufficient ghost cell storage must be provided by the source patch data component, and those ghost cells must be filled before calling the data coarsening routines.
Communication algorithms generally consist of three parts: an algorithm, a schedule, and a patch strategy. The algorithm describes the communication between patch data items but is independent of the configuration of the AMR hierarchy. PatchData items and their associated coarsening operators are registered with the algorithm. To generate the communication dependencies for a particular hierarchy configuration, the algorithm generates a schedule based on the current hierarchy configuration. This schedule then performs the communication based on the registered data types and their associated operators. User-defined coarsening operations can be written using the interfaces in CoarsenPatchStrategy for preprocessCoarsen() and postProcessCoarsen().
The source patch data space is used during processing to store temporary data. Thus, the user-defined coarsening operators should operate on the source space by using the patch data with those indices.
It is the user's responsibility to register valid operations with the coarsen algorithm so that the data communication can occur. In particular, communication operations (e.g., data coarsening, data copy, etc.) are performed in the order that items are registered for coarsening with a coarsen algorithm object. Thus, order of registration must repect any dependencies among patch data communicated. Also, users who use the preprocessCoarsen() and postProcessCoarsen() operations in the patch strategy object must make sure that all data that is needed in those operations are registered with the CoarsenAlgorithm using registerCoarsen() whether or not the data is to be coarsened.
Typical usage of a coarsen algorithm to perform data coarsening on an AMR hierarchy involves four steps:
Construct a coarsen algorithm object.
Register coarsen operations with the coarsen algorithm. Using the registerCoarsen() methods(s), one provides source and destination patch data information, as well as spatial coarsening operators as needed.
After all operations are registered with the algorithm, one creates a communication schedule using the createSchedule() method. This method identifies the source (fine) and destination (coarse) patch levels for data coarsening. Note that when creating a communication schedule, a concrete instance of a CoarsenPatchStrategy object may be required to supply user-defined spatial data coarsening operations.
Invoke the coarsenData() method in the communication schedule to perform the data transfers.
Note that each coarsen schedule created by a coarsen algorithm remains valid as long as the levels involved in the communication process do not change; thus, they can be used for multiple data communication cycles.
See also:
xfer::CoarsenSchedule
xfer::CoarsenPatchStrategy
xfer::CoarsenClasses
Constructor & Destructor Documentation
SAMRAI::xfer::CoarsenAlgorithm::CoarsenAlgorithm (const tbox::Dimension & dim, bool fill_coarse_data = false) [explicit]
Construct a coarsening algorithm and initialize its basic state.
Coarsening operations must be registered with this algorithm before it can do anything useful. See the registerCoarsen() routine for details
Parameters:
[in] dim Dimension
[in] fill_coarse_data boolean flag indicating whether pre-existing coarse level data is needed for the data coarsening operations. By default this argument is false. If a true value is value is provided, then source data will be filled on a temporary coarse patch level (copied from the actual coarse level source data) for use in coarsening operations registered with this algorithm. This option should only be used by those who specifically require this behavior and who know how to properly process the patch data on coarse and fine patch levels during the coarsening process.
SAMRAI::xfer::CoarsenAlgorithm::~CoarsenAlgorithm ()
The destructor releases all internal storage.
Member Function Documentation
void SAMRAI::xfer::CoarsenAlgorithm::registerCoarsen (const int dst, const int src, const boost::shared_ptr< hier::CoarsenOperator > & opcoarsen, const hier::IntVector & gcw_to_coarsen, const boost::shared_ptr< VariableFillPattern > & var_fill_pattern = boost::shared_ptr<VariableFillPattern>())
Register a coarsening operation with the coarsening algorithm.
Data from the interiors of the source component on a source (fine) patch level will be coarsened into the source component of a temporary (coarse) patch level and then copied into the destination component on the destination (coarse) patch level. If the coarsening operator requires data in ghost cells outside of the patch interiors (i.e., a non-zero stencil width), then those ghost cells must exist in the source patch data component and the ghost cells must be filled with valid data on the source level before a call to invoke the communication schedule. Note that the source and destination components may be the same.
Some special circumstances require that data be coarsened from the ghost cell regions of a finer level and the resulting coarsened data should be copied to the destination patch level. When this is the case, the optional integer vector argument should be set to the cell width, in the destination (coarser) level index space, of the region around the fine level where this coarsening should occur. For example, if the coarser level needs data in a region two (coarse) cells wide around the boundary of the finer level, then the gcw_to_coarsen should be set to a vector with all entries set to two. Moreover, if the ratio between coarse and fine levels is four in this case, then the source patch data is required to have at least eight ghost cells.
Parameters:
[in] dst Patch data index filled on destination level.
[in] src Patch data index coarsened from the source level.
[in] opcoarsen Coarsening operator. This may be a null pointer. If null, coarsening must be handled by the coarsen patch strategy member functions. See the comments for CoarsenPatchStrategy::preprocessCoarsen() and CoarsenPatchStrategy::postprocessCoarsen().
[in] gcw_to_coarsen Ghost cell width to be used when data should be coarsened from ghost cell regions of the source (finer) level into the destination (coarser) level. If coarsening from fine ghost cell regions is not desired, then it should be a zero IntVector. If this argument is nonzero, its value should be the cell width, in the destination (coarser) index space, of the region around the fine level where this coarsening should occur. This argument should only be made nonzero by those who specifically require this special behavior and know how to properly process the patch data on coarse and fine patch levels during the coarsening process.
[in] var_fill_pattern boost::shared_ptr to the variable fill pattern, which controls how box overlaps are constructed. If the NULL default is used, then class BoxGeometryVariableFillPattern will be used internally.
Precondition:
!d_schedule_created
References SAMRAI::xfer::CoarsenClasses::Data::d_dst, SAMRAI::xfer::CoarsenClasses::Data::d_fine_bdry_reps_var, SAMRAI::xfer::CoarsenClasses::Data::d_gcw_to_coarsen, SAMRAI::xfer::CoarsenClasses::Data::d_opcoarsen, SAMRAI::xfer::CoarsenClasses::Data::d_src, SAMRAI::xfer::CoarsenClasses::Data::d_tag, SAMRAI::xfer::CoarsenClasses::Data::d_var_fill_pattern, SAMRAI::hier::VariableDatabase::getDatabase(), and TBOX_ERROR.
Referenced by registerCoarsen().
void SAMRAI::xfer::CoarsenAlgorithm::registerCoarsen (const int dst, const int src, const boost::shared_ptr< hier::CoarsenOperator > & opcoarsen, const boost::shared_ptr< VariableFillPattern > & var_fill_pattern = boost::shared_ptr<VariableFillPattern>()) [inline]
Register a coarsening operation with the coarsening algorithm.
This will do all of the same things as the above registerCoarsen(), except it does not have the gcw_to_coarsen parameter.
References SAMRAI::hier::IntVector::getZero(), and registerCoarsen().
boost::shared_ptr< CoarsenSchedule > SAMRAI::xfer::CoarsenAlgorithm::createSchedule (const boost::shared_ptr< hier::PatchLevel > & crse_level, const boost::shared_ptr< hier::PatchLevel > & fine_level, CoarsenPatchStrategy * coarsen_strategy = 0, const boost::shared_ptr< CoarsenTransactionFactory > & transaction_factory = boost::shared_ptr<CoarsenTransactionFactory>())
Create a communication schedule to coarsen data from the given fine patch level to the given coarse patch level.
This communication schedule may then be executed to perform the data transfers. This schedule creation procedure assumes that the coarse level represents a region of coarser index space than the fine level. To avoid potentially erroneous behavior, the coarse level domain should cover the domain of the fine level.
Note that the schedule remains valid as long as the levels do not change; thus, it can be used for multiple data communication cycles.
Returns:
boost::shared_ptr to coarsen schedule that performs the data transfers.
Parameters:
[in] crse_level boost::shared_ptr to coarse (destination) level.
[in] fine_level boost::shared_ptr to fine (source) level.
[in] coarsen_strategy boost::shared_ptr to a coarsen patch strategy that provides user-defined coarsen operations. If this patch strategy is null (default state), then no user-defined coarsen operations will be performed.
[in] transaction_factory Optional boost::shared_ptr to a coarsen transaction factory that creates data transactions for the schedule. If this pointer is null default state), then a StandardCoarsenTransactionFactory object will be used.
Precondition:
crse_level && fine_level
(getDim() == crse_level->getDim()) && (getDim() == fine_level->getDim())
References TBOX_ASSERT, and TBOX_ASSERT_DIM_OBJDIM_EQUALITY2.
bool SAMRAI::xfer::CoarsenAlgorithm::checkConsistency (const boost::shared_ptr< CoarsenSchedule > & schedule) const [inline]
Given a previously-generated coarsen schedule, check for consistency with this coarsen algorithm object to see whether a call to resetSchedule is a valid operation.
Consistency means that the number of operations registered must be the same and the source and destination patch data items and operators must have identical characteristics (i.e., data centering, ghost cell widths, stencil requirements, etc.). However, the specific source, destination patch data ids and operators can be different.
Returns:
true if schedule reset is valid; false otherwise.
Parameters:
[in] schedule boost::shared_ptr to coarsen schedule, which cannot be null.
Precondition:
schedule
References TBOX_ASSERT.
void SAMRAI::xfer::CoarsenAlgorithm::resetSchedule (const boost::shared_ptr< CoarsenSchedule > & schedule) const
Given a previously-generated coarsen schedule, reconfigure it to peform the communication operations registered with this coarsen algorithm object.
That is, the schedule will be transformed so that it will function as though this coarsen algorithm created it. Note that the set of operations registered with this coarsen algorithm must be essentially the same as those registered with the coarsen algorithm that created the schedule originally, and this is enforced using a call to checkConsistency().
Parameters:
[in,out] schedule boost::shared_ptr to coarsen schedule, which cannot be null.
Precondition:
schedule
d_coarsen_classes->classesMatch(schedule->getEquivalenceClasses())
References TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::xfer::CoarsenAlgorithm::printClassData (std::ostream & stream) const
Print the coarsen algorithm state to the specified data stream.
Parameters:
[out] stream Output data stream.
const tbox::Dimension& SAMRAI::xfer::CoarsenAlgorithm::getDim () const [inline]
Return the dimension of this object.
The documentation for this class was generated from the following files:
source/SAMRAI/xfer/CoarsenAlgorithm.h
source/SAMRAI/xfer/CoarsenAlgorithm.C