SAMRAI: MDA_OrderRowMajor< MDA_DIM > Class Template Reference
MDA_OrderRowMajor< MDA_DIM > Class Template Reference
Performs computations based for row-major arrays.
#include <source/SAMRAI/pdat/MDA_Access.h>
Public Types
enum { MDA_Reduced_DIM = (MDA_DIM > 1 ? MDA_DIM - 1 : 1) }
Quantity of (MDA_DIM-1), used only if MDA_DIM > 1. Otherwise defined to 1 to avoid out-of-range subscripts.
typedef int index_t
Type for the index.
typedef MDA_IndexRange< MDA_DIM > range_t
typedef range_t::dir_t dir_t
Type for the dimension counter.
typedef MDA_OrderRowMajor
< MDA_Reduced_DIM > reduced_order_t
Public Member Functions
MDA_OrderRowMajor (const size_t *sz=((size_t *) 0), const index_t *st=((index_t *) 0))
Similar to MDA_IndexRange constructor.
MDA_OrderRowMajor (const index_t *si, const index_t *sf)
Similar to MDA_IndexRange constructor.
MDA_OrderRowMajor (const range_t &r)
Constructor for specifying index range object.
size_t totalSize (unsigned short d) const
Return the total size of subarray starting with direction d.
size_t reduce (index_t i, reduced_order_t &new_order) const
Computes the order object and offset for reducing the slowest direction.
Access to index range
const range_t & range () const
Const access to the index range object.
const MDA_OrderRowMajor & setSizeAndStart (const size_t *sz=((size_t *) 0), const index_t *st=((index_t *) 0))
Similar to MDA_IndexRange::setSizeAndStart().
const MDA_OrderRowMajor & setInclusiveRange (const index_t first[MDA_DIM], const index_t final[MDA_DIM])
Similar to MDA_IndexRange::setInclusiveRange().
const MDA_OrderRowMajor & adjustDim (dir_t d, index_t first, index_t final)
Similar to MDA_IndexRange::adjustDim().
Logical comparisons
bool operator== (const MDA_OrderRowMajor &r) const
Equivalence comparison.
bool operator!= (const MDA_OrderRowMajor &r) const
Inequivalence comparison.
Functions to compute offsets
index_t offset (const index_t i[MDA_DIM]) const
Compute offsets for arbitrary MDA_DIM.
index_t offset (index_t i0) const
index_t offset (index_t i0, index_t i1) const
index_t offset (index_t i0, index_t i1, index_t i2) const
index_t offset (index_t i0, index_t i1, index_t i2, index_t i3) const
index_t fixedOffset () const
Protected Types
enum { D0 = range_t::D0, D1 = range_t::D1, D2 = range_t::D2, D3 = range_t::D3 }
Detailed Description
template<unsigned short MDA_DIM>
class MDA_OrderRowMajor< MDA_DIM >
Performs computations based for row-major arrays.
This class computes things that are dependent on element order in memory, in this case, for the row-major order.
Member Typedef Documentation
template<unsigned short MDA_DIM> typedef int MDA_OrderRowMajor< MDA_DIM >::index_t
Type for the index.
Reimplemented from MDA_IndexRange< MDA_DIM >.
template<unsigned short MDA_DIM> typedef MDA_IndexRange<MDA_DIM> MDA_OrderRowMajor< MDA_DIM >::range_t
template<unsigned short MDA_DIM> typedef range_t::dir_t MDA_OrderRowMajor< MDA_DIM >::dir_t
Type for the dimension counter.
Type dir_t could be "unsigned short" instead of "short", but using short causes the GNU compiler to issue unneeded warnings about certain comparisons always being false (when instantiating with MDA_DIM of 1).
Reimplemented from MDA_IndexRange< MDA_DIM >.
template<unsigned short MDA_DIM> typedef MDA_OrderRowMajor<MDA_Reduced_DIM> MDA_OrderRowMajor< MDA_DIM >::reduced_order_t
Member Enumeration Documentation
template<unsigned short MDA_DIM> anonymous enum [protected]
Enumerator:
D0
D1
D2
D3
template<unsigned short MDA_DIM> anonymous enum
Quantity of (MDA_DIM-1), used only if MDA_DIM > 1. Otherwise defined to 1 to avoid out-of-range subscripts.
Enumerator:
MDA_Reduced_DIM
Constructor & Destructor Documentation
template<unsigned short MDA_DIM> MDA_OrderRowMajor< MDA_DIM >::MDA_OrderRowMajor (const size_t * sz = ((size_t *)0), const index_t * st = ((index_t *)0)) [inline]
Similar to MDA_IndexRange constructor.
Parameters:
sz Array sizes
st Array starting indices
template<unsigned short MDA_DIM> MDA_OrderRowMajor< MDA_DIM >::MDA_OrderRowMajor (const index_t * si, const index_t * sf) [inline]
Similar to MDA_IndexRange constructor.
Parameters:
si Array of initial indices
sf Array of final indices
template<unsigned short MDA_DIM> MDA_OrderRowMajor< MDA_DIM >::MDA_OrderRowMajor (const range_t & r) [inline]
Constructor for specifying index range object.
Parameters:
r Array index object
Member Function Documentation
template<unsigned short MDA_DIM> const range_t& MDA_OrderRowMajor< MDA_DIM >::range () const [inline]
Const access to the index range object.
The index range cannot be modified through this reference. To modify the index range, use other member functions.
Referenced by MDA_OrderColMajor< MDA_DIM >::operator!=(), MDA_OrderRowMajor< MDA_DIM >::operator!=(), MDA_OrderColMajor< MDA_DIM >::operator==(), and MDA_OrderRowMajor< MDA_DIM >::operator==().
template<unsigned short MDA_DIM> const MDA_OrderRowMajor& MDA_OrderRowMajor< MDA_DIM >::setSizeAndStart (const size_t * sz = ((size_t *)0), const index_t * st = ((index_t *)0)) [inline]
Similar to MDA_IndexRange::setSizeAndStart().
Reimplemented from MDA_IndexRange< MDA_DIM >.
References MDA_IndexRange< MDA_DIM >::setSizeAndStart().
Referenced by MDA_OrderRowMajor< MDA_DIM >::reduce(), MDA_Access< const MDA_TYPE, MDA_DIM, OrderType >::setSizeAndStart(), and MDA_OrderColMajor< MDA_DIM >::setSizeAndStart().
template<unsigned short MDA_DIM> const MDA_OrderRowMajor& MDA_OrderRowMajor< MDA_DIM >::setInclusiveRange (const index_t first[MDA_DIM], const index_t final[MDA_DIM]) [inline]
Similar to MDA_IndexRange::setInclusiveRange().
Reimplemented from MDA_IndexRange< MDA_DIM >.
References MDA_IndexRange< MDA_DIM >::setInclusiveRange().
Referenced by MDA_Access< const MDA_TYPE, MDA_DIM, OrderType >::setInclusiveRange(), and MDA_OrderColMajor< MDA_DIM >::setInclusiveRange().
template<unsigned short MDA_DIM> const MDA_OrderRowMajor& MDA_OrderRowMajor< MDA_DIM >::adjustDim (dir_t d, index_t first, index_t final) [inline]
Similar to MDA_IndexRange::adjustDim().
Reimplemented from MDA_IndexRange< MDA_DIM >.
References MDA_IndexRange< MDA_DIM >::adjustDim().
Referenced by MDA_Access< const MDA_TYPE, MDA_DIM, OrderType >::adjustDim(), and MDA_OrderColMajor< MDA_DIM >::adjustDim().
template<unsigned short MDA_DIM> bool MDA_OrderRowMajor< MDA_DIM >::operator== (const MDA_OrderRowMajor< MDA_DIM > & r) const [inline]
Equivalence comparison.
Only independent data is compared, not dependent (redundant) data.
Reimplemented from MDA_IndexRange< MDA_DIM >.
References MDA_OrderRowMajor< MDA_DIM >::range().
template<unsigned short MDA_DIM> bool MDA_OrderRowMajor< MDA_DIM >::operator!= (const MDA_OrderRowMajor< MDA_DIM > & r) const [inline]
Inequivalence comparison.
Only independent data is compared, not dependent (redundant) data.
Reimplemented from MDA_IndexRange< MDA_DIM >.
References MDA_OrderRowMajor< MDA_DIM >::range().
template<unsigned short MDA_DIM> index_t MDA_OrderRowMajor< MDA_DIM >::offset (const index_t i[MDA_DIM]) const [inline]
Compute offsets for arbitrary MDA_DIM.
This is flexible but not efficient! You should use dimension-specific offset computations whenever possible.
References MDA_IndexRange< MDA_DIM >::beg(), and MDA_IndexRange< MDA_DIM >::d_start.
Referenced by MDA_OrderRowMajor< MDA_DIM >::reduce().
template<unsigned short MDA_DIM> index_t MDA_OrderRowMajor< MDA_DIM >::offset (index_t i0) const [inline]
References MDA_IndexRange< MDA_DIM >::beg().
template<unsigned short MDA_DIM> index_t MDA_OrderRowMajor< MDA_DIM >::offset (index_t i0, index_t i1) const [inline]
References MDA_OrderRowMajor< MDA_DIM >::D0, MDA_OrderRowMajor< MDA_DIM >::D1, and MDA_IndexRange< MDA_DIM >::d_start.
template<unsigned short MDA_DIM> index_t MDA_OrderRowMajor< MDA_DIM >::offset (index_t i0, index_t i1, index_t i2) const [inline]
References MDA_OrderRowMajor< MDA_DIM >::D0, MDA_OrderRowMajor< MDA_DIM >::D1, MDA_OrderRowMajor< MDA_DIM >::D2, and MDA_IndexRange< MDA_DIM >::d_start.
template<unsigned short MDA_DIM> index_t MDA_OrderRowMajor< MDA_DIM >::offset (index_t i0, index_t i1, index_t i2, index_t i3) const [inline]
References MDA_OrderRowMajor< MDA_DIM >::D0, MDA_OrderRowMajor< MDA_DIM >::D1, MDA_OrderRowMajor< MDA_DIM >::D2, MDA_OrderRowMajor< MDA_DIM >::D3, and MDA_IndexRange< MDA_DIM >::d_start.
template<unsigned short MDA_DIM> index_t MDA_OrderRowMajor< MDA_DIM >::fixedOffset () const [inline]
template<unsigned short MDA_DIM> size_t MDA_OrderRowMajor< MDA_DIM >::totalSize (unsigned short d) const [inline]
Return the total size of subarray starting with direction d.
template<unsigned short MDA_DIM> size_t MDA_OrderRowMajor< MDA_DIM >::reduce (index_t i, reduced_order_t & new_order) const [inline]
Computes the order object and offset for reducing the slowest direction.
A reduced array is the subarray resulting from fixing the slowest (first) index. The reduced array has one fewer dimension, a different ordering object and its data starts at a different point in memory. The change in starting point is the returned offset value, and the new order object is returned in the referenced argument.
Returns:
Pointer offset (always positive) to the reduced array pointer.
References MDA_IndexRange< MDA_DIM >::beg(), MDA_OrderRowMajor< MDA_DIM >::offset(), MDA_OrderRowMajor< MDA_DIM >::setSizeAndStart(), and MDA_IndexRange< MDA_DIM >::size().
The documentation for this class was generated from the following file:
source/SAMRAI/pdat/MDA_Access.h