SAMRAI: SAMRAI::hier::IntVector Class Reference
SAMRAI::hier::IntVector Class Reference
Simple integer vector class with size based on a dimension value.
#include <source/SAMRAI/hier/IntVector.h>
Public Types
typedef tbox::Dimension::dir_t dir_t
Public Member Functions
IntVector (const tbox::Dimension &dim)
Creates an uninitialized IntVector for 1 block.
IntVector (size_t num_blocks, const tbox::Dimension &dim)
Creates an uninitialized IntVector of a given number of blocks.
IntVector (const tbox::Dimension &dim, int value, size_t num_blocks=1)
Construct an IntVector with all components equal to the value argument.
IntVector (const std::vector< int > &vec, size_t num_blocks=1)
Construct an IntVector with the values provided by an STL vector of ints.
IntVector (const tbox::Dimension &dim, const int array[], size_t num_blocks=1)
Construct an IntVector with values provided by a raw array.
IntVector (const IntVector &rhs)
Copy constructor.
IntVector (const IntVector &rhs, size_t num_blocks)
Construct an IntVector from another IntVector.
IntVector (const Index &rhs, size_t num_blocks=1)
Construct an IntVector from an Index.
IntVector & operator= (const IntVector &rhs)
The assignment operator sets the IntVector equal to the argument.
IntVector & operator= (const Index &rhs)
Assignment operator assigning the values of an Index to an IntVector.
virtual ~IntVector ()
The IntVector destructor does nothing interesting.
size_t getNumBlocks () const
Return the number of blocks for this IntVector.
IntVector getBlockVector (const BlockId &block_id) const
Return an IntVector for one block extracted from a possibly larger IntVector.
int & operator[] (const unsigned int i)
Return reference to the specified component of the vector. This can only be used when the number of blocks is 1.
const int & operator[] (const unsigned int i) const
Return the specified component of the vector as a const integer reference. This can only be used when the number of blocks is 1.
int & operator() (const unsigned int i)
Return reference to the specified component of the vector. This can only be used when the number of blocks is 1.
const int & operator() (const unsigned int i) const
Return the specified component of the vector as a const integer reference. This can only be used when the number of blocks is 1.
int & operator() (const BlockId::block_t b, const unsigned int i)
Return the specified component of the vector.
const int & operator() (const BlockId::block_t b, const unsigned int i) const
Return the specified component of the vector as a const integer reference.
IntVector & operator+= (const IntVector &rhs)
Plus-equals operator for two integer vectors.
IntVector operator+ (const IntVector &rhs) const
Plus operator for two integer vectors.
IntVector & operator+= (const int rhs)
Plus-equals operator for an integer vector and an integer.
IntVector operator+ (const int rhs) const
Plus operator for an integer vector and an integer.
IntVector & operator-= (const IntVector &rhs)
Minus-equals operator for two integer vectors.
IntVector operator- (const IntVector &rhs) const
Minus operator for two integer vectors.
IntVector & operator-= (const int rhs)
Minus-equals operator for an integer vector and an integer.
IntVector operator- (const int rhs) const
Minus operator for an integer vector and an integer.
IntVector & operator*= (const IntVector &rhs)
Times-equals operator for two integer vectors.
IntVector operator* (const IntVector &rhs) const
Times operator for two integer vectors.
IntVector & operator*= (const int rhs)
Times-equals operator for an integer vector and an integer.
IntVector operator* (const int rhs) const
Times operator for an integer vector and an integer.
IntVector & operator/= (const IntVector &rhs)
Quotient-equals operator for two integer vectors.
IntVector operator/ (const IntVector &rhs) const
Quotient operator for two integer vectors.
IntVector & operator/= (const int rhs)
Quotient-equals operator for an integer vector and an integer.
IntVector operator/ (const int rhs) const
Quotient operator for an integer vector and an integer.
void ceilingDivide (const IntVector &denominator)
Component-wise ceilingDivide quotient (integer divide with rounding up).
IntVector operator- () const
Unary minus to negate an integer vector.
bool operator== (int rhs) const
Returns true if all components are equal to a given integer.
bool operator!= (int rhs) const
Returns true if some components are not equal to a given integer.
bool operator== (const IntVector &rhs) const
Returns true if two vector objects are equal. All components must be the same for equality.
bool operator!= (const IntVector &rhs) const
Returns true if two vector objects are not equal. Any of the components may be different for inequality.
bool operator< (const IntVector &rhs) const
Returns true if each integer in vector is less than corresponding integer in comparison vector.
bool operator<= (const IntVector &rhs) const
Returns true if each integer in vector is less or equal to corresponding integer in comparison vector.
bool operator> (const IntVector &rhs) const
Returns true if each integer in vector is greater than corresponding integer in comparison vector.
bool operator>= (const IntVector &rhs) const
Returns true if each integer in vector is greater or equal to corresponding integer in comparison vector.
void min (const IntVector &rhs)
Return the component-wise minimum of two integer vector objects.
int min () const
Return the minimum entry in an integer vector.
void max (const IntVector &rhs)
Return the component-wise maximum of two integer vector objects.
int max () const
Return the maximum entry in an integer vector.
void setAll (const IntVector &vector)
Set all block-wise components of an IntVector.
long int getProduct (const BlockId &block_id=BlockId::invalidId()) const
Return the product of the entries in the integer vector.
virtual void putToRestart (tbox::Database &restart_db, const std::string &name) const
Store the object state to the specified restart database with the provided name.
virtual void getFromRestart (tbox::Database &restart_db, const std::string &name)
Restores the object giving it the provided name and getting its state from the specified restart database.
const tbox::Dimension & getDim () const
Return the dimension of this object.
void sortIntVector (const IntVector &values)
Set this IntVector to a sorted version of the given IntVector.
Static Public Member Functions
static IntVector ceilingDivide (const IntVector &numerator, const IntVector &denominator)
Component-wise ceilingDivide quotient (integer divide with rounding up).
static IntVector min (const IntVector &a, const IntVector &b)
Utility function to take the minimum of two integer vector objects.
static IntVector max (const IntVector &a, const IntVector &b)
Utility function to take the maximum of two integer vector objects.
static const IntVector & getZero (const tbox::Dimension &dim)
Return an IntVector of zeros of the specified dimension.
static const IntVector & getOne (const tbox::Dimension &dim)
Return an IntVector of ones of the specified dimension.
Friends
std::istream & operator>> (std::istream &s, IntVector &rhs)
Read an integer vector from an input stream. The format for the input is (i0,...,in) for an n-dimensional vector.
std::ostream & operator<< (std::ostream &s, const IntVector &rhs)
Write an integer vector into an output stream. The format for the output is (i0,...,in) for an n-dimensional vector.
Detailed Description
Simple integer vector class with size based on a dimension value.
Class IntVector implements a vector of integers that, depending on the usage context, has a length equal to the number of spatial dimensions being used or its length is the number of dimension multiplied by a certain number of blocks.
The integers in IntVector are stored first in order of dimension, and then in order of block number. For a 3-dimensional IntVector on 4 blocks, the order would be: { i0, j0, k0, i1, j1, k1, i2, j2, k2, i3, j3, k3 }.
When used in the context of a single-block problem, the number of blocks for an IntVector is always 1. In a multiblock context, the number of blocks for an IntVector may be either 1 or the number of blocks being used in the problem.
Member Typedef Documentation
typedef tbox::Dimension::dir_t SAMRAI::hier::IntVector::dir_t
Constructor & Destructor Documentation
SAMRAI::hier::IntVector::IntVector (const tbox::Dimension & dim) [explicit]
Creates an uninitialized IntVector for 1 block.
Parameters:
dim
References SAMRAI::tbox::Dimension::getValue().
SAMRAI::hier::IntVector::IntVector (size_t num_blocks, const tbox::Dimension & dim)
Creates an uninitialized IntVector of a given number of blocks.
Precondition:
num_blocks >=1
Parameters:
num_blocks
dim
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
SAMRAI::hier::IntVector::IntVector (const tbox::Dimension & dim, int value, size_t num_blocks = 1)
Construct an IntVector with all components equal to the value argument.
Precondition:
num_blocks >=1
Parameters:
dim
value
num_blocks
References TBOX_ASSERT.
SAMRAI::hier::IntVector::IntVector (const std::vector< int > & vec, size_t num_blocks = 1)
Construct an IntVector with the values provided by an STL vector of ints.
The dimension of the constructed IntVector will be the size of the vec argument. If num_blocks has a value greater than 1, then the IntVector will be constructed with the values held by vec duplicated for every block.
Precondition:
vec.size() >= 1
Parameters:
vec Vector of integers with a size equal to the desired dimension
num_blocks
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
SAMRAI::hier::IntVector::IntVector (const tbox::Dimension & dim, const int array[], size_t num_blocks = 1)
Construct an IntVector with values provided by a raw array.
This constructor assumes that the given array contains a number of values equal to the dimension value. As this constructor can do no error- checking that the array is properly allocated and initialized, it is up to the calling code to ensure that the array argument is valid.
If num_blocks has a value greater than 1, then the IntVector will be constructed with the values held by array duplicated for every block.
Parameters:
dim
array Array of ints that should be allocated and initialized at a length equal to dim.getValue()
num_blocks
References SAMRAI::tbox::Dimension::getValue().
SAMRAI::hier::IntVector::IntVector (const IntVector & rhs)
Copy constructor.
Precondition:
rhs.getNumBlocks() >= 1
References TBOX_ASSERT.
SAMRAI::hier::IntVector::IntVector (const IntVector & rhs, size_t num_blocks)
Construct an IntVector from another IntVector.
The main use case for this constructor is to use an IntVector sized for one block to construct an IntVector sized for a larger number of blocks. When used in this way, the constructed IntVector will duplicate the contents of the argument for every block.
If num_blocks is equal to the rhs argument's number of blocks, then this constructor is equivalent to the copy constructor.
Precondition:
num_blocks >=1
(rhs.getNumBlocks() == num_blocks || rhs.getNumBlocks() == 1)
Parameters:
rhs
num_blocks
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
SAMRAI::hier::IntVector::IntVector (const Index & rhs, size_t num_blocks = 1)
Construct an IntVector from an Index.
The constructed IntVector will have the same dimension value as the Index. If num_blocks is greater than 1, the values held by the Index argument will be duplicated for every block.
Parameters:
rhs
num_blocks
Precondition:
num_blocks >=1
Parameters:
rhs
num_blocks
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
SAMRAI::hier::IntVector::~IntVector () [virtual]
The IntVector destructor does nothing interesting.
Member Function Documentation
IntVector& SAMRAI::hier::IntVector::operator= (const IntVector & rhs) [inline]
The assignment operator sets the IntVector equal to the argument.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector & SAMRAI::hier::IntVector::operator= (const Index & rhs)
Assignment operator assigning the values of an Index to an IntVector.
The assigned IntVector will be sized for one block.
Precondition:
getDim() == rhs.getDim()
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
size_t SAMRAI::hier::IntVector::getNumBlocks () const [inline]
Return the number of blocks for this IntVector.
Referenced by SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary(), SAMRAI::hier::Index::coarsen(), SAMRAI::hier::Box::coarsen(), SAMRAI::hier::Connector::Connector(), SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::Box::grow(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::hier::Index::Index(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::hier::Index::operator*(), SAMRAI::hier::Index::operator*=(), SAMRAI::hier::Index::operator+(), SAMRAI::hier::Index::operator+=(), SAMRAI::hier::Index::operator-(), SAMRAI::hier::Index::operator-=(), SAMRAI::hier::Index::operator/(), SAMRAI::hier::Index::operator/=(), SAMRAI::hier::operator<<(), SAMRAI::hier::Index::operator=(), SAMRAI::hier::operator>>(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::hier::Box::refine(), SAMRAI::xfer::RefineSchedule::RefineSchedule(), SAMRAI::hier::PatchLevel::setCoarsenedPatchLevel(), SAMRAI::hier::PatchLevel::setRefinedPatchLevel(), SAMRAI::hier::Connector::setWidth(), and SAMRAI::hier::Connector::shrinkWidth().
IntVector SAMRAI::hier::IntVector::getBlockVector (const BlockId & block_id) const [inline]
Return an IntVector for one block extracted from a possibly larger IntVector.
This constructs an IntVector sized for one block using the int values associated with a given block. The constructed IntVector is returned by value.
Precondition:
block_id.getBlockValue() < getNumBlocks()
Parameters:
block_id BlockId indicates which block is associated with the desired integer values.
Returns:
A constructed IntVector sized for one block
References SAMRAI::hier::BlockId::getBlockValue(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
Referenced by SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenMax(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenNumber(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), SAMRAI::hier::BoxUtilities::fixBadCutPoints(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), and SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform().
int& SAMRAI::hier::IntVector::operator[] (const unsigned int i) [inline]
Return reference to the specified component of the vector. This can only be used when the number of blocks is 1.
Precondition:
(i >= 0) && (i < getDim().getValue())
getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
const int& SAMRAI::hier::IntVector::operator[] (const unsigned int i) const [inline]
Return the specified component of the vector as a const integer reference. This can only be used when the number of blocks is 1.
Precondition:
(i >= 0) && (i < getDim().getValue())
getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
int& SAMRAI::hier::IntVector::operator() (const unsigned int i) [inline]
Return reference to the specified component of the vector. This can only be used when the number of blocks is 1.
Precondition:
(i >= 0) && (i < getDim().getValue())
getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
const int& SAMRAI::hier::IntVector::operator() (const unsigned int i) const [inline]
Return the specified component of the vector as a const integer reference. This can only be used when the number of blocks is 1.
Precondition:
(i >= 0) && (i < getDim().getValue())
getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
int& SAMRAI::hier::IntVector::operator() (const BlockId::block_t b, const unsigned int i) [inline]
Return the specified component of the vector.
Precondition:
(b >= 0) && (b < getNumBlocks())
(i >= 0) && (i < getDim().getValue())
The desired component is specified by the pair of the block number b and the dimensional index i.
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
const int& SAMRAI::hier::IntVector::operator() (const BlockId::block_t b, const unsigned int i) const [inline]
Return the specified component of the vector as a const integer reference.
Precondition:
(b >= 0) && (b < getNumBlocks())
(i >= 0) && (i < getDim().getValue())
The desired component is specified by the pair of the block number b and the dimensional index i.
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
IntVector& SAMRAI::hier::IntVector::operator+= (const IntVector & rhs) [inline]
Plus-equals operator for two integer vectors.
The following comments apply to most of the arithmetic operators and some related methods:
The arithmetic operators and related methods such as ceilingDivide allow both full component-wise operations on IntVectors that have equal numbers of blocks, as well as operations between multiblock IntVectors and single-block IntVectors
When an operator is invoked on a multiblock IntVector with a right-hand- side single-block IntVector, the values within the right-hand-side are applied to every block within the "this" IntVector.
Assertion failures occur if operations are called using two multiblock IntVectors that have different numbers of blocks, or if the right-hand-side is a multiblock IntVector while "this" is single-block.
There also are some operators that take a single integer as a right- hand-side, in which case that integer value is applied in the operation to every component of "this".
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector SAMRAI::hier::IntVector::operator+ (const IntVector & rhs) const [inline]
Plus operator for two integer vectors.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector& SAMRAI::hier::IntVector::operator+= (const int rhs) [inline]
Plus-equals operator for an integer vector and an integer.
References SAMRAI::tbox::Dimension::getValue().
IntVector SAMRAI::hier::IntVector::operator+ (const int rhs) const [inline]
Plus operator for an integer vector and an integer.
IntVector& SAMRAI::hier::IntVector::operator-= (const IntVector & rhs) [inline]
Minus-equals operator for two integer vectors.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector SAMRAI::hier::IntVector::operator- (const IntVector & rhs) const [inline]
Minus operator for two integer vectors.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector& SAMRAI::hier::IntVector::operator-= (const int rhs) [inline]
Minus-equals operator for an integer vector and an integer.
References SAMRAI::tbox::Dimension::getValue().
IntVector SAMRAI::hier::IntVector::operator- (const int rhs) const [inline]
Minus operator for an integer vector and an integer.
IntVector& SAMRAI::hier::IntVector::operator*= (const IntVector & rhs) [inline]
Times-equals operator for two integer vectors.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector SAMRAI::hier::IntVector::operator* (const IntVector & rhs) const [inline]
Times operator for two integer vectors.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector& SAMRAI::hier::IntVector::operator*= (const int rhs) [inline]
Times-equals operator for an integer vector and an integer.
References SAMRAI::tbox::Dimension::getValue().
IntVector SAMRAI::hier::IntVector::operator* (const int rhs) const [inline]
Times operator for an integer vector and an integer.
IntVector& SAMRAI::hier::IntVector::operator/= (const IntVector & rhs) [inline]
Quotient-equals operator for two integer vectors.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector SAMRAI::hier::IntVector::operator/ (const IntVector & rhs) const [inline]
Quotient operator for two integer vectors.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector& SAMRAI::hier::IntVector::operator/= (const int rhs) [inline]
Quotient-equals operator for an integer vector and an integer.
References SAMRAI::tbox::Dimension::getValue().
IntVector SAMRAI::hier::IntVector::operator/ (const int rhs) const [inline]
Quotient operator for an integer vector and an integer.
void SAMRAI::hier::IntVector::ceilingDivide (const IntVector & denominator) [inline]
Component-wise ceilingDivide quotient (integer divide with rounding up).
Precondition:
getDim() == denominator.getDim()
getNumBlocks() == denominator.getNumBlocks() || denominator.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), ceilingDivide(), SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredFineConnectorWidthsForRecursiveRefinement(), SAMRAI::hier::Connector::convertHeadWidthToBase(), and SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary().
static IntVector SAMRAI::hier::IntVector::ceilingDivide (const IntVector & numerator, const IntVector & denominator) [inline, static]
Component-wise ceilingDivide quotient (integer divide with rounding up).
Precondition:
numerator.getDim() == denominator.getDim()
numerator.getNumBlocks() == denominator.getNumBlocks() || denominator.getNumBlocks() == 1
References ceilingDivide(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
IntVector SAMRAI::hier::IntVector::operator- () const [inline]
Unary minus to negate an integer vector.
bool SAMRAI::hier::IntVector::operator== (int rhs) const [inline]
Returns true if all components are equal to a given integer.
References SAMRAI::tbox::Dimension::getValue().
bool SAMRAI::hier::IntVector::operator!= (int rhs) const [inline]
Returns true if some components are not equal to a given integer.
bool SAMRAI::hier::IntVector::operator== (const IntVector & rhs) const [inline]
Returns true if two vector objects are equal. All components must be the same for equality.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::hier::IntVector::operator!= (const IntVector & rhs) const [inline]
Returns true if two vector objects are not equal. Any of the components may be different for inequality.
Precondition:
getDim() == rhs.getDim()
References TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::hier::IntVector::operator< (const IntVector & rhs) const [inline]
Returns true if each integer in vector is less than corresponding integer in comparison vector.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::hier::IntVector::operator<= (const IntVector & rhs) const [inline]
Returns true if each integer in vector is less or equal to corresponding integer in comparison vector.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::hier::IntVector::operator> (const IntVector & rhs) const [inline]
Returns true if each integer in vector is greater than corresponding integer in comparison vector.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
bool SAMRAI::hier::IntVector::operator>= (const IntVector & rhs) const [inline]
Returns true if each integer in vector is greater or equal to corresponding integer in comparison vector.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::hier::IntVector::min (const IntVector & rhs) [inline]
Return the component-wise minimum of two integer vector objects.
Precondition:
getDim() == rhs.getDim()
getNumBlocks() == rhs.getNumBlocks() || rhs.getNumBlocks() == 1
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::pdat::CellData< TYPE >::CellData(), SAMRAI::pdat::CellDataFactory< TYPE >::CellDataFactory(), SAMRAI::pdat::CellGeometry::CellGeometry(), SAMRAI::mesh::BalanceBoxBreaker::computeWidthScore(), SAMRAI::hier::Connector::Connector(), SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::pdat::EdgeData< TYPE >::EdgeData(), SAMRAI::pdat::EdgeDataFactory< TYPE >::EdgeDataFactory(), SAMRAI::pdat::EdgeGeometry::EdgeGeometry(), SAMRAI::pdat::FaceData< TYPE >::FaceData(), SAMRAI::pdat::FaceDataFactory< TYPE >::FaceDataFactory(), SAMRAI::pdat::FaceGeometry::FaceGeometry(), SAMRAI::pdat::SideData< TYPE >::getSizeOfData(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), min(), SAMRAI::pdat::NodeData< TYPE >::NodeData(), SAMRAI::pdat::NodeDataFactory< TYPE >::NodeDataFactory(), SAMRAI::pdat::NodeGeometry::NodeGeometry(), SAMRAI::pdat::OuteredgeGeometry::OuteredgeGeometry(), SAMRAI::pdat::OuterfaceGeometry::OuterfaceGeometry(), SAMRAI::pdat::OuternodeGeometry::OuternodeGeometry(), SAMRAI::pdat::OutersideGeometry::OutersideGeometry(), SAMRAI::hier::PatchDataFactory::PatchDataFactory(), SAMRAI::hier::VariableDatabase::registerInternalSAMRAIVariable(), SAMRAI::hier::VariableDatabase::registerVariableAndContext(), SAMRAI::hier::Connector::setWidth(), SAMRAI::hier::Connector::shrinkWidth(), SAMRAI::pdat::SideData< TYPE >::SideData(), SAMRAI::pdat::SideDataFactory< TYPE >::SideDataFactory(), and SAMRAI::pdat::SideGeometry::SideGeometry().
int SAMRAI::hier::IntVector::min () const [inline]
Return the minimum entry in an integer vector.
References SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::compareToScalar(), SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::computeConstrProdPos(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::dot(), SAMRAI::math::PatchSideDataNormOpsComplex::dot(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::integral(), SAMRAI::math::PatchSideDataNormOpsComplex::integral(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::L1Norm(), SAMRAI::math::PatchSideDataNormOpsComplex::L1Norm(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::L2Norm(), SAMRAI::math::PatchSideDataNormOpsComplex::L2Norm(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::maxNorm(), SAMRAI::math::PatchSideDataNormOpsComplex::maxNorm(), SAMRAI::mesh::MultiblockGriddingTagger::setPhysicalBoundaryConditions(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::sumControlVolumes(), SAMRAI::math::PatchSideDataNormOpsComplex::sumControlVolumes(), SAMRAI::math::PatchSideDataMiscellaneousOpsReal< TYPE >::testReciprocal(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedL2Norm(), and SAMRAI::math::PatchSideDataNormOpsComplex::weightedL2Norm().
void SAMRAI::hier::IntVector::max (const IntVector & rhs) [inline]
Return the component-wise maximum of two integer vector objects.
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary(), SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredFineConnectorWidthsForRecursiveRefinement(), SAMRAI::hier::Connector::Connector(), SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::xfer::CoarsenPatchStrategy::getMaxCoarsenOpStencilWidth(), SAMRAI::hier::CoarsenOperator::getMaxCoarsenOpStencilWidth(), SAMRAI::hier::PatchDescriptor::getMaxGhostWidth(), SAMRAI::xfer::RefinePatchStrategy::getMaxRefineOpStencilWidth(), SAMRAI::hier::RefineOperator::getMaxRefineOpStencilWidth(), SAMRAI::hier::TransferOperatorRegistry::getMaxTransferOpStencilWidth(), SAMRAI::hier::BoxUtilities::growAndAdjustAcrossBlockBoundary(), SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel(), max(), SAMRAI::hier::Connector::setWidth(), SAMRAI::hier::Connector::shrinkWidth(), and SAMRAI::algs::TimeRefinementIntegrator::TimeRefinementIntegrator().
int SAMRAI::hier::IntVector::max () const [inline]
Return the maximum entry in an integer vector.
References SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel().
static IntVector SAMRAI::hier::IntVector::min (const IntVector & a, const IntVector & b) [inline, static]
Utility function to take the minimum of two integer vector objects.
Precondition:
a.getDim() == b.getDim()
References min(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
static IntVector SAMRAI::hier::IntVector::max (const IntVector & a, const IntVector & b) [inline, static]
Utility function to take the maximum of two integer vector objects.
Precondition:
a.getDim() == b.getDim()
References max(), and TBOX_ASSERT_OBJDIM_EQUALITY2.
void SAMRAI::hier::IntVector::setAll (const IntVector & vector) [inline]
Set all block-wise components of an IntVector.
If this IntVector and the argument IntVector are sized for the same number of blocks, this is the equivalent of a copy operation. If this IntVector is multiblock while the argument is single-block, then the values of the argument are copied to each block-wise component of this IntVector.
An error will occur if the numbers of blocks are unequal and the argument IntVector is not single-block.
Parameters:
vector Input IntVector
References SAMRAI::tbox::Dimension::getValue(), TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
long int SAMRAI::hier::IntVector::getProduct (const BlockId & block_id = BlockId::invalidId()) const [inline]
Return the product of the entries in the integer vector.
If a BlockId argument is provided, the product of entries for that block will be computed. If no BlockId argument is provided, this IntVector must be single-block.
Parameters:
block_id Optional block on which to compute the product.
References SAMRAI::hier::BlockId::getBlockValue(), getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::BlockId::invalidId(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::VoucherTransitLoad::adjustLoad(), SAMRAI::mesh::BoxTransitSet::adjustLoad(), SAMRAI::mesh::BalanceUtilities::computeDomainDependentProcessorLayout(), SAMRAI::mesh::BalanceUtilities::computeDomainIndependentProcessorLayout(), SAMRAI::hier::AssumedPartitionBox::getBox(), SAMRAI::mesh::PartitioningParams::getMinLoad(), and SAMRAI::hier::AssumedPartitionBox::recursivePrint().
void SAMRAI::hier::IntVector::putToRestart (tbox::Database & restart_db, const std::string & name) const [virtual]
Store the object state to the specified restart database with the provided name.
References SAMRAI::tbox::Database::putDatabase().
Referenced by SAMRAI::hier::BaseGridGeometry::putToRestart().
void SAMRAI::hier::IntVector::getFromRestart (tbox::Database & restart_db, const std::string & name) [virtual]
Restores the object giving it the provided name and getting its state from the specified restart database.
References SAMRAI::tbox::Database::getDatabase(), SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
const tbox::Dimension& SAMRAI::hier::IntVector::getDim () const [inline]
Return the dimension of this object.
Referenced by SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::hier::OverlapConnectorAlgorithm::bridgeWithNesting(), SAMRAI::hier::Transformation::calculateReverseShift(), SAMRAI::geom::CartesianPatchGeometry::CartesianPatchGeometry(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::pdat::OutersideDataFactory< TYPE >::cloneFactory(), SAMRAI::pdat::OuternodeDataFactory< TYPE >::cloneFactory(), SAMRAI::pdat::OuterfaceDataFactory< TYPE >::cloneFactory(), SAMRAI::pdat::OuteredgeDataFactory< TYPE >::cloneFactory(), SAMRAI::hier::BaseGridGeometry::computeBoundaryBoxesOnLevel(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::mesh::BalanceUtilities::computeDomainDependentProcessorLayout(), SAMRAI::mesh::BalanceUtilities::computeDomainIndependentProcessorLayout(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::hier::Connector::computeRatioInfo(), SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::BoxUtilities::extendBoxesToDomainBoundary(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::OverlapConnectorAlgorithm::extractNeighbors(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenMax(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenNumber(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), SAMRAI::mesh::PartitioningParams::getDim(), SAMRAI::hier::PatchDataFactory::getDim(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::PatchData::getFromRestart(), SAMRAI::hier::Transformation::getInverseTransformation(), SAMRAI::hier::TransferOperatorRegistry::getMaxTransferOpStencilWidth(), getProduct(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), SAMRAI::hier::PeriodicShiftCatalog::initializeShiftsByIndexDirections(), SAMRAI::xfer::CoarsenClasses::insertEquivalenceClassItem(), SAMRAI::hier::Transformation::inverseTransform(), SAMRAI::xfer::RefineClasses::itemIsValid(), SAMRAI::hier::PatchHierarchy::makeCoarsenedPatchHierarchy(), SAMRAI::hier::PatchHierarchy::makeRefinedPatchHierarchy(), SAMRAI::hier::operator<<(), SAMRAI::hier::operator>>(), SAMRAI::hier::PatchData::putToRestart(), SAMRAI::hier::BoxLevel::putToRestart(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::algs::MethodOfLinesIntegrator::registerVariable(), SAMRAI::hier::PatchDescriptor::setMinGhostWidth(), SAMRAI::hier::Connector::setTranspose(), SAMRAI::hier::Connector::setWidth(), and SAMRAI::pdat::SideVariable< TYPE >::SideVariable().
static const IntVector& SAMRAI::hier::IntVector::getZero (const tbox::Dimension & dim) [inline, static]
Return an IntVector of zeros of the specified dimension.
Can be used to avoid object creation overheads. The returned IntVector is sized for one block.
References SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::Box::Box(), SAMRAI::hier::OverlapConnectorAlgorithm::bridge(), SAMRAI::solv::CellPoissonFACSolver::CellPoissonFACSolver(), SAMRAI::hier::BoxUtilities::checkBoxConstraints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPoints(), SAMRAI::hier::BoxUtilities::checkBoxForBadCutPointsInDirection(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::hier::BaseGridGeometry::computeBoundaryBoxesOnLevel(), SAMRAI::xfer::PatchLevelInteriorFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchLevelFullFillPattern::computeDestinationFillBoxesOnSourceProc(), SAMRAI::xfer::PatchInteriorVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::xfer::BoxGeometryVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerCellVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerCellNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::hier::BoxLevelConnectorUtils::computeNonIntersectingParts(), SAMRAI::hier::Connector::computeRatioInfo(), SAMRAI::xfer::RefineScheduleConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::StandardTagAndInitializeConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::GriddingAlgorithmConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::algs::TimeRefinementIntegratorConnectorWidthRequestor::computeRequiredConnectorWidths(), SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes(), SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::pdat::ArrayData< TYPE >::copy(), SAMRAI::xfer::RefineTimeTransaction::copyLocalData(), SAMRAI::hier::BoxUtilities::extendBoxesToDomainBoundary(), SAMRAI::hier::BoxUtilities::extendBoxToDomainBoundary(), SAMRAI::hier::BoxUtilities::findBadCutPointsForDirection(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenMax(), SAMRAI::hier::BoxUtilities::findBestCutPointsGivenNumber(), SAMRAI::mesh::TileClustering::findBoxesContainingTags(), SAMRAI::mesh::BergerRigoutsos::findBoxesContainingTags(), SAMRAI::hier::AssumedPartitionBox::findOverlaps(), SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance(), SAMRAI::hier::BoxUtilities::fixBadCutPoints(), SAMRAI::hier::AssumedPartitionBox::getBox(), SAMRAI::pdat::OutersideDataFactory< TYPE >::getBoxGeometry(), SAMRAI::pdat::OuternodeDataFactory< TYPE >::getBoxGeometry(), SAMRAI::pdat::OuterfaceDataFactory< TYPE >::getBoxGeometry(), SAMRAI::pdat::OuteredgeDataFactory< TYPE >::getBoxGeometry(), SAMRAI::hier::BaseGridGeometry::getPeriodicShift(), SAMRAI::xfer::PatchInteriorVariableFillPattern::getStencilWidth(), SAMRAI::xfer::BoxGeometryVariableFillPattern::getStencilWidth(), SAMRAI::pdat::FirstLayerSideVariableFillPattern::getStencilWidth(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::getStencilWidth(), SAMRAI::pdat::FirstLayerEdgeVariableFillPattern::getStencilWidth(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::BoxUtilities::growBoxWithinDomain(), SAMRAI::hier::Box::initialize(), SAMRAI::hier::PeriodicShiftCatalog::initializeShiftsByIndexDirections(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeCoarsenedGridGeometry(), SAMRAI::hier::PatchHierarchy::makeCoarsenedPatchHierarchy(), SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel(), SAMRAI::mesh::GriddingAlgorithm::makeFinerLevel(), SAMRAI::hier::PatchHierarchy::makeNewPatchLevel(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::geom::CartesianGridGeometry::makeRefinedGridGeometry(), SAMRAI::hier::PatchHierarchy::makeRefinedPatchHierarchy(), SAMRAI::hier::BoxLevelConnectorUtils::makeRemainderMap(), SAMRAI::hier::BoxLevelConnectorUtils::makeSortingMap(), SAMRAI::hier::Box::numberCells(), SAMRAI::solv::SimpleCellRobinBcCoefs::numberOfExtensionsFillable(), SAMRAI::hier::PatchDescriptor::PatchDescriptor(), SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform(), SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform(), SAMRAI::xfer::CoarsenAlgorithm::registerCoarsen(), SAMRAI::algs::PatchBoundaryEdgeSum::registerSum(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), SAMRAI::solv::SimpleCellRobinBcCoefs::setBcCoefs(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::hier::Connector::setWidth(), SAMRAI::hier::BoundaryBoxUtils::stretchBoxToGhostWidth(), SAMRAI::pdat::ArrayData< TYPE >::sum(), SAMRAI::pdat::SideGeometry::transform(), SAMRAI::pdat::NodeGeometry::transform(), SAMRAI::pdat::FaceGeometry::transform(), SAMRAI::pdat::EdgeGeometry::transform(), and SAMRAI::pdat::CellGeometry::transform().
static const IntVector& SAMRAI::hier::IntVector::getOne (const tbox::Dimension & dim) [inline, static]
Return an IntVector of ones of the specified dimension.
Can be used to avoid object creation overheads. The returned IntVector is sized for one block.
References SAMRAI::tbox::Dimension::getValue().
Referenced by SAMRAI::hier::BaseGridGeometry::BaseGridGeometry(), SAMRAI::hier::BoxLevelConnectorUtils::baseNestsInHead(), SAMRAI::hier::BaseGridGeometry::chopDomain(), SAMRAI::hier::CoarseFineBoundary::CoarseFineBoundary(), SAMRAI::hier::BoxLevelConnectorUtils::computeBoxesAroundBoundary(), SAMRAI::hier::BaseGridGeometry::computeBoxTouchingBoundaries(), SAMRAI::xfer::PatchLevelBorderFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::xfer::PatchLevelBorderAndInteriorFillPattern::computeFillBoxesAndNeighborhoodSets(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::pdat::FirstLayerNodeVariableFillPattern::computeFillBoxesOverlap(), SAMRAI::solv::CellPoissonFACOps::computeFluxOnPatch(), SAMRAI::hier::BaseGridGeometry::computePhysicalDomain(), SAMRAI::hier::Connector::convertHeadWidthToBase(), SAMRAI::hier::AssumedPartitionBox::findOverlaps(), SAMRAI::hier::BaseGridGeometry::findPatchesTouchingBoundaries(), SAMRAI::hier::BaseGridGeometry::findSingularities(), SAMRAI::hier::FlattenedHierarchy::FlattenedHierarchy(), SAMRAI::hier::AssumedPartitionBox::getBox(), SAMRAI::hier::BaseGridGeometry::getOffset(), SAMRAI::mesh::MultiblockGriddingTagger::getRefineOpStencilWidth(), SAMRAI::pdat::NodeOverlap::getSourceBoxContainer(), SAMRAI::pdat::SecondLayerNodeVariableFillPattern::getStencilWidth(), SAMRAI::pdat::SecondLayerNodeNoCornersVariableFillPattern::getStencilWidth(), SAMRAI::pdat::FirstLayerCellVariableFillPattern::getStencilWidth(), SAMRAI::pdat::FirstLayerCellNoCornersVariableFillPattern::getStencilWidth(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), SAMRAI::hier::BoxUtilities::growBoxesWithinDomain(), SAMRAI::hier::HierarchyNeighbors::HierarchyNeighbors(), SAMRAI::solv::CellPoissonFACOps::initializeOperatorState(), SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::ChopAndPackLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::geom::GridGeometry::makeCoarsenedGridGeometry(), SAMRAI::mesh::GriddingAlgorithm::makeCoarsestLevel(), SAMRAI::geom::GridGeometry::makeRefinedGridGeometry(), SAMRAI::hier::BaseGridGeometry::putToRestart(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::hier::AssumedPartitionBox::selfCheck(), SAMRAI::hier::BaseGridGeometry::setBoundaryBoxes(), SAMRAI::hier::BaseGridGeometry::setPhysicalDomain(), SAMRAI::hier::Connector::setTranspose(), SAMRAI::hier::BaseGridGeometry::setUpRatios(), SAMRAI::pdat::NodeGeometry::transform(), and SAMRAI::appu::VisItDataWriter::VisItDataWriter().
void SAMRAI::hier::IntVector::sortIntVector (const IntVector & values)
Set this IntVector to a sorted version of the given IntVector.
For an single-block IntVector, set the ith entry of this to the position of the ith smallest value in the argument IntVector.
If the IntVectors are multilbock, each section of the IntVector associated with a block is sorted independently.
References SAMRAI::tbox::Dimension::getValue(), and TBOX_ASSERT.
Friends And Related Function Documentation
std::istream& operator>> (std::istream & s, IntVector & rhs) [friend]
Read an integer vector from an input stream. The format for the input is (i0,...,in) for an n-dimensional vector.
std::ostream& operator<< (std::ostream & s, const IntVector & rhs) [friend]
Write an integer vector into an output stream. The format for the output is (i0,...,in) for an n-dimensional vector.
The documentation for this class was generated from the following files:
source/SAMRAI/hier/IntVector.h
source/SAMRAI/hier/IntVector.C