SAMRAI: SAMRAI::pdat::SideVariable< TYPE > Class Template Reference
SAMRAI::pdat::SideVariable< TYPE > Class Template Reference
#include <source/SAMRAI/pdat/SideVariable.h>
Public Member Functions
SideVariable (const tbox::Dimension &dim, const std::string &name, const hier::IntVector &directions, int depth=1, bool fine_boundary_represents_var=true)
Create an side-centered variable object with the given name and depth (i.e., number of data values at each edge index location).
SideVariable (const tbox::Dimension &dim, const std::string &name, int depth=1, bool fine_boundary_represents_var=true)
Constructor that will assume a directions vector of 1 in all coordinate directions.
virtual ~SideVariable ()
Virtual destructor for side variable objects.
const hier::IntVector & getDirectionVector () const
Return constant reference to vector describing which coordinate directions have data associated with this side variable object.
bool fineBoundaryRepresentsVariable () const
Return boolean indicating which side data values (coarse or fine) take precedence at coarse-fine mesh interfaces. The value is set in the constructor.
bool dataLivesOnPatchBorder () const
Return true indicating that side data on a patch interior exists on the patch boundary.
int getDepth () const
Return the the depth (number of components).
Detailed Description
template<class TYPE>
class SAMRAI::pdat::SideVariable< TYPE >
Class SideVariable<TYPE> is a templated variable class used to define side-centered quantities on an AMR mesh. It is a subclass of hier::Variable and is templated on the type of the underlying data (e.g., double, int, bool, etc.). See header file for SideData<TYPE> class for a more detailed description of the data layout.
Note that it is possible to create a side data object for managing data at cell sides associated with a single coordinate direction only. See the constructor for more information.
IMPORTANT: The class FaceVariable<TPYE> and associated "face data" classes define the same storage as this side variable class, except that the individual array indices are permuted in the face data type.
See also:
pdat::SideData
pdat::SideDataFactory
pdat::SideGeometry
hier::Variable
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::pdat::SideVariable< TYPE >::SideVariable (const tbox::Dimension & dim, const std::string & name, const hier::IntVector & directions, int depth = 1, bool fine_boundary_represents_var = true) [inline]
Create an side-centered variable object with the given name and depth (i.e., number of data values at each edge index location).
A default depth of one is provided. The fine boundary representation boolean argument indicates which values (either coarse or fine) take precedence at coarse-fine mesh boundaries during coarsen and refine operations. The default is that fine data values take precedence on coarse-fine interfaces.
References SAMRAI::hier::Variable::getDim(), SAMRAI::hier::IntVector::getDim(), and TBOX_ASSERT.
template<class TYPE > SAMRAI::pdat::SideVariable< TYPE >::SideVariable (const tbox::Dimension & dim, const std::string & name, int depth = 1, bool fine_boundary_represents_var = true) [inline]
Constructor that will assume a directions vector of 1 in all coordinate directions.
Constructs a SideVariable the same as the first constructor, except there is no directions argument, meaning that data is expected to exist on the sides in all coordinate directions.
template<class TYPE > SAMRAI::pdat::SideVariable< TYPE >::~SideVariable () [inline, virtual]
Virtual destructor for side variable objects.
Member Function Documentation
template<class TYPE > const hier::IntVector & SAMRAI::pdat::SideVariable< TYPE >::getDirectionVector () const [inline]
Return constant reference to vector describing which coordinate directions have data associated with this side variable object.
A vector entry of zero indicates that there is no data array allocated for the corresponding coordinate direction for side data created via this side variable object. A non-zero value indicates that a valid data array will be allocated for that coordinate direction.
template<class TYPE > bool SAMRAI::pdat::SideVariable< TYPE >::fineBoundaryRepresentsVariable () const [inline, virtual]
Return boolean indicating which side data values (coarse or fine) take precedence at coarse-fine mesh interfaces. The value is set in the constructor.
Implements SAMRAI::hier::Variable.
template<class TYPE > bool SAMRAI::pdat::SideVariable< TYPE >::dataLivesOnPatchBorder () const [inline, virtual]
Return true indicating that side data on a patch interior exists on the patch boundary.
Implements SAMRAI::hier::Variable.
template<class TYPE > int SAMRAI::pdat::SideVariable< TYPE >::getDepth () const [inline]
Return the the depth (number of components).
References BOOST_CAST, SAMRAI::hier::Variable::getPatchDataFactory(), and TBOX_ASSERT.
The documentation for this class was generated from the following files:
source/SAMRAI/pdat/SideVariable.h
source/SAMRAI/pdat/SideVariable.C