SAMRAI: SAMRAI::math::PatchSideDataNormOpsReal< TYPE > Class Template Reference
SAMRAI::math::PatchSideDataNormOpsReal< TYPE > Class Template Reference
#include <source/SAMRAI/math/PatchSideDataNormOpsReal.h>
Public Member Functions
PatchSideDataNormOpsReal ()
virtual ~PatchSideDataNormOpsReal ()
size_t numberOfEntries (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box) const
double sumControlVolumes (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const boost::shared_ptr< pdat::SideData< double > > &cvol, const hier::Box &box) const
void abs (const boost::shared_ptr< pdat::SideData< TYPE > > &dst, const boost::shared_ptr< pdat::SideData< TYPE > > &src, const hier::Box &box) const
double L1Norm (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double L2Norm (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double weightedL2Norm (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const boost::shared_ptr< pdat::SideData< TYPE > > &weight, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double RMSNorm (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double weightedRMSNorm (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const boost::shared_ptr< pdat::SideData< TYPE > > &weight, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
double maxNorm (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
TYPE dot (const boost::shared_ptr< pdat::SideData< TYPE > > &data1, const boost::shared_ptr< pdat::SideData< TYPE > > &data2, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &cvol=boost::shared_ptr< pdat::SideData< double > >()) const
TYPE integral (const boost::shared_ptr< pdat::SideData< TYPE > > &data, const hier::Box &box, const boost::shared_ptr< pdat::SideData< double > > &vol) const
Detailed Description
template<class TYPE>
class SAMRAI::math::PatchSideDataNormOpsReal< TYPE >
Class PatchSideDataNormOpsReal provides a collection of common norm operations that may be applied to real (double or float) numerical side-centered patch data. The primary intent of this class is to define part of the interface for an PatchSideDataOpsReal object which provides access operations that may be used to manipulate side-centered patch data. Each member function accepts a box argument indicating the region of index space on which the operation should be performed. The operation will be performed on the intersection of this box and those boxes corresponding to the patch data objects. Also, each operation allows an additional side-centered patch data object to be used to represent a control volume that weights the contribution of each data entry in the given norm calculation. Note that the control volume patch data must be of type double and have side-centered geometry (i.e., the same as the data itself). The use of control volumes is important when these operations are used in vector kernels where the data resides over multiple levels of spatial resolution in an AMR hierarchy. If the control volume is not given in the function call, it will be ignored in the calculation. Also, note that the depth of the control volume patch data object must be either 1 or be equal to the depth of the other data objects.
These operations typically apply only to the numerical standard built-in types, such as double, float, and the complex type (which may or may not be a built-in type depending on the C++ compiler). This templated class should only be used to instantiate objects with double or float as the template parameter. Note that a similar set of norm operations is implemented for complex patch data in the class PatchSideDataNormOpsComplex.
See also:
math::ArrayDataNormOpsReal
Constructor & Destructor Documentation
template<class TYPE > SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::PatchSideDataNormOpsReal () [inline]
Empty constructor and destructor.
template<class TYPE > SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::~PatchSideDataNormOpsReal () [inline, virtual]
Member Function Documentation
template<class TYPE > size_t SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::numberOfEntries (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box) const [inline]
Return the number of data values for the side-centered data object in the given box. Note that it is assumed that the box refers to the cell-centered index space corresponding to the patch hierarchy.
Precondition:
data
data->getDim() == box.getDim()
References SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::Box::size(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::RMSNorm(), and SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedRMSNorm().
template<class TYPE > double SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::sumControlVolumes (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const boost::shared_ptr< pdat::SideData< double > > & cvol, const hier::Box & box) const [inline]
Return sum of control volume entries for the side-centered data object.
Precondition:
data && cvol
data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector())
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::RMSNorm(), and SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedRMSNorm().
template<class TYPE > void SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::abs (const boost::shared_ptr< pdat::SideData< TYPE > > & dst, const boost::shared_ptr< pdat::SideData< TYPE > > & src, const hier::Box & box) const [inline]
Set destination component to absolute value of source component. That is, each destination entry is set to .
Precondition:
dst && src
dst->getDirectionVector() == src->getDirectionVector()
(dst->getDim() == src->getDim()) && (dst->getDim() == box.getDim())
References TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > double SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::L1Norm (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > double SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::L2Norm (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return discrete -norm of the data using the control volume to weight the contribution of each data entry to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::RMSNorm().
template<class TYPE > double SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedL2Norm (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const boost::shared_ptr< pdat::SideData< TYPE > > & weight, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return discrete weighted -norm of the data using the control volume to weight the contribution of the data and weight entries to the sum. That is, the return value is the sum . If the control volume is NULL, the return value is .
Precondition:
data && weight
(data->getDim() == weight->getDim()) && (data->getDim() == box.getDim())
data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), weight->getDirectionVector())
!cvol || (data->getDim() == cvol->getDim())
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
Referenced by SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedRMSNorm().
template<class TYPE > double SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::RMSNorm (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return discrete root mean squared norm of the data. If the control volume is not NULL, the return value is the -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the -norm divided by the square root of the number of data entries.
Precondition:
data
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::L2Norm(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::sumControlVolumes(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
template<class TYPE > double SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedRMSNorm (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const boost::shared_ptr< pdat::SideData< TYPE > > & weight, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return discrete weighted root mean squared norm of the data. If the control volume is not NULL, the return value is the weighted -norm divided by the square root of the sum of the control volumes. Otherwise, the return value is the weighted -norm divided by the square root of the number of data entries.
Precondition:
data && weight
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
References SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::numberOfEntries(), SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::sumControlVolumes(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::weightedL2Norm().
template<class TYPE > double SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::maxNorm (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return the -norm of the data using the control volume to weight the contribution of each data entry to the maximum. That is, the return value is , where the max is over the data elements where . If the control volume is NULL, it is ignored during the computation of the maximum.
Precondition:
data && weight
data->getDim() == box.getDim()
!cvol || (data->getDim() == cvol->getDim())
!cvol || (data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > TYPE SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::dot (const boost::shared_ptr< pdat::SideData< TYPE > > & data1, const boost::shared_ptr< pdat::SideData< TYPE > > & data2, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & cvol = boost::shared_ptr<pdat::SideData<double> >()) const [inline]
Return the dot product of the two data arrays using the control volume to weight the contribution of each product to the sum. That is, the return value is the sum . If the control volume is NULL, it is ignored during the summation.
Precondition:
data1 && data2
data1->getDirectionVector() == data2->getDirectionVector()
!cvol || (data1->getDim() == cvol->getDim())
!cvol || (data1->getDirectionVector() == hier::IntVector::min(data1->getDirectionVector(), cvol->getDirectionVector()))
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and SAMRAI::pdat::SideGeometry::toSideBox().
template<class TYPE > TYPE SAMRAI::math::PatchSideDataNormOpsReal< TYPE >::integral (const boost::shared_ptr< pdat::SideData< TYPE > > & data, const hier::Box & box, const boost::shared_ptr< pdat::SideData< double > > & vol) const [inline]
Return the integral of the function represented by the data array. The return value is the sum .
Precondition:
data && vol
(data->getDim() == vol->getDim()) && (data->getDim() == box.getDim())
data->getDirectionVector() == hier::IntVector::min(data->getDirectionVector(), vol->getDirectionVector())
References SAMRAI::hier::IntVector::min(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY3, and SAMRAI::pdat::SideGeometry::toSideBox().
The documentation for this class was generated from the following files:
source/SAMRAI/math/PatchSideDataNormOpsReal.h
source/SAMRAI/math/PatchSideDataNormOpsReal.C