SAMRAI: SAMRAI::pdat Namespace Reference
SAMRAI::pdat Namespace Reference
Classes
class ArrayData
Class ArrayData<TYPE> is a basic templated array structure defined over the index space of a box (with a specified depth) that provides the support for the various standard array-based patch data subclasses.
class ArrayDataAccess
Utility for wrapping data from ArrayData class in an MDA_Access or MDA_AccessConst object.
class ArrayDataIterator
class ArrayDataOperationUtilities
Struct ArrayDataOperationUtilities<TYPE, OP> provides generic looping operations for all array-based patch data types. The operations are templated on data type and the operation that will be performed on individual array elements in the innermost loop.
class CellComplexConstantRefine
class CellComplexLinearTimeInterpolateOp
class CellData
Class CellData<TYPE> provides an implementation for data defined at cell centers on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a cell data object represents data of some template TYPE and depth at the centers of the cells in the box. Here, depth indicates the number of data values at each cell index location. The CellGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and cell-centered data.
class CellDataFactory
class CellDoubleConstantRefine
class CellDoubleLinearTimeInterpolateOp
class CellFloatConstantRefine
class CellFloatLinearTimeInterpolateOp
class CellGeometry
class CellIndex
class CellIntegerConstantRefine
class CellIterator
class CellOverlap
class CellVariable
class CopyOperation
Class CopyOperation<TYPE> encapsulates a copy operation into an object.
class DoubleAttributeId
Attribute identifying class for double-valued attributes.
class EdgeComplexConstantRefine
class EdgeComplexLinearTimeInterpolateOp
class EdgeData
Class EdgeData<TYPE> provides an implementation for data defined at cell edges on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an edge data object represents data of some template TYPE and depth on the edges of the cells in the box. Here, depth indicates the number of data values at each edge index location. The EdgeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and edge-centered data.
class EdgeDataFactory
class EdgeDoubleConstantRefine
class EdgeDoubleLinearTimeInterpolateOp
class EdgeFloatConstantRefine
class EdgeFloatLinearTimeInterpolateOp
class EdgeGeometry
class EdgeIndex
class EdgeIntegerConstantRefine
class EdgeIterator
class EdgeOverlap
class EdgeVariable
class FaceComplexConstantRefine
class FaceComplexLinearTimeInterpolateOp
class FaceData
Class FaceData<TYPE> provides an implementation for data defined at cell faces on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a face data object represents data of some template TYPE and depth on the faces of the cells in the box. Here, depth indicates the number of data values at each face index location. The FaceGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and face-centered data.
class FaceDataFactory
class FaceDoubleConstantRefine
class FaceDoubleLinearTimeInterpolateOp
class FaceFloatConstantRefine
class FaceFloatLinearTimeInterpolateOp
class FaceGeometry
class FaceIndex
class FaceIntegerConstantRefine
class FaceIterator
class FaceOverlap
class FaceVariable
class FirstLayerCellNoCornersVariableFillPattern
Class FirstLayerCellNoCornersVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
class FirstLayerCellVariableFillPattern
Class FirstLayerCellVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
class FirstLayerEdgeVariableFillPattern
Class FirstLayerEdgeVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
class FirstLayerNodeVariableFillPattern
Class FirstLayerNodeVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
class FirstLayerSideVariableFillPattern
Class FirstLayerSideVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
class IndexData
class IndexDataNode
class IndexIterator
class IndexDataFactory
class IndexVariable
class IntegerAttributeId
Attribute identifying class for integer-valued attributes.
class NodeComplexInjection
class NodeComplexLinearTimeInterpolateOp
class NodeData
Class NodeData<TYPE> provides an implementation for data defined at nodes on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a node data object represents data of some template TYPE and depth at the nodes of the cells in the box. Here, depth indicates the number of data values at each node index location. The NodeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and node-centered data.
class NodeDataFactory
class NodeDoubleInjection
class NodeDoubleLinearTimeInterpolateOp
class NodeFloatInjection
class NodeFloatLinearTimeInterpolateOp
class NodeGeometry
class NodeIndex
class NodeIntegerInjection
class NodeIterator
class NodeOverlap
class NodeVariable
class OuteredgeData
Class OuteredgeData<TYPE> provides an implementation for data defined at cell edges on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outeredge data object represents data of some template TYPE and depth on the cell edges on the boundary of the box. Here, depth indicates the number of data values at each edge index location. The OuteredgedgeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outeredge-centered data.
class OuteredgeDataFactory
Class OuteredgeDataFactory<TYPE> is a factory class used to allocate new instances of OuteredgeData<TYPE> objects. It is a subclass of the patch data factory class and outeredge data is a subclass of patch data. Both the factory and data classes are templated on the type of the contained object (e.g., double or int).
class OuteredgeGeometry
class OuteredgeVariable
Class OuteredgeVariable<TYPE> is a templated variable class used to define edge-centered data quantities only on patch boundaries. It is a subclass of hier::Variable and is templated on the type of the underlying data (e.g., double, int, bool, etc.).
class OuterfaceComplexConstantRefine
class OuterfaceComplexLinearTimeInterpolateOp
class OuterfaceData
Class OuterfaceData<TYPE> provides an implementation for data defined at cell faces on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outerface data object represents data of some template TYPE and depth on the cell faces on the boundary of the box. Here, depth indicates the number of data values at each face index location. The OuteredgfaceGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outerface-centered data.
class OuterfaceDataFactory
class OuterfaceDoubleConstantRefine
class OuterfaceDoubleLinearTimeInterpolateOp
class OuterfaceFloatConstantRefine
class OuterfaceFloatLinearTimeInterpolateOp
class OuterfaceGeometry
class OuterfaceIntegerConstantRefine
class OuterfaceVariable
Class OuterfaceVariable<TYPE> is a templated variable class used to define face-centered data quantities only on patch boundaries. It is a subclass of hier::Variable and is templated on the type of the underlying data (e.g., double, int, bool, etc.).
class OuternodeData
Class OuternodeData<TYPE> provides an implementation for data defined at cell nodes on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outernode data object represents data of some template TYPE and depth on the cell nodes on the boundary of the box. Here, depth indicates the number of data values at each node index location. The OuternodnodeGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outernode-centered data.
class OuternodeDataFactory
Class OuternodeDataFactory is a factory class used to allocate new instances of OuternodeData objects. It is a subclass of the patch data factory class and outernode data is a subclass of patch data. Both the factory and data classes are templated on the type of the contained object (e.g., double or int).
class OuternodeDoubleInjection
Class OuternodeDoubleInjection implements constant averaging (i.e., injection) for outernode-centered double patch data defined over a mesh.
class OuternodeGeometry
class OuternodeVariable
Class OuternodeVariable<TYPE> is a templated variable class used to define node-centered data quantities only on patch boundaries. It is a subclass of hier::Variable and is templated on the type of the underlying data (e.g., double, int, bool, etc.).
class OutersideComplexLinearTimeInterpolateOp
class OutersideData
Class OutersideData<TYPE> provides an implementation for data defined at cell sides (faces) on the boundaries of AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, an outerside data object represents data of some template TYPE and depth on the cell sides (faces) on the boundary of the box. Here, depth indicates the number of data values at each face index location. The OuteredgsideGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and outerside-centered data.
class OutersideDataFactory
class OutersideDoubleLinearTimeInterpolateOp
class OutersideFloatLinearTimeInterpolateOp
class OutersideGeometry
class OutersideVariable
Class OutersideVariable<TYPE> is a templated variable class used to define side-centered data quantities only on patch boundaries. It is a subclass of hier::Variable and is templated on the type of the underlying data (e.g., double, int, bool, etc.).
class SecondLayerNodeNoCornersVariableFillPattern
Class SecondLayerNodeNoCornersVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
class SecondLayerNodeVariableFillPattern
Class SecondLayerNodeVariableFillPattern is a concrete implementation of the abstract base class VariableFillPattern.
class SideComplexConstantRefine
class SideComplexLinearTimeInterpolateOp
class SideData
Class SideData<TYPE> provides an implementation for data defined at cell sides (faces) on AMR patches. It is derived from the hier::PatchData interface common to all SAMRAI patch data types. Given a CELL-centered AMR index space box, a side data object represents data of some template TYPE and depth on the sides (faces) of the cells in the box. Here, depth indicates the number of data values at each side index location. The SideGeometry class provides the translation between the standard SAMRAI cell-centered AMR index space and side-centered data.
class SideDataFactory
class SideDoubleConstantRefine
class SideDoubleLinearTimeInterpolateOp
class SideFloatConstantRefine
class SideFloatLinearTimeInterpolateOp
class SideGeometry
class SideIndex
class SideIntegerConstantRefine
class SideIterator
class SideOverlap
class SideVariable
class SumOperation
Class SumOperation<TYPE> encapsulates a summation operation into an object.
Functions
template<int DIM>
MDA_Access< double, DIM,
MDA_OrderColMajor< DIM > > access (ArrayData< double > &array_data, int depth)
template<int DIM>
const MDA_AccessConst< double,
DIM, MDA_OrderColMajor< DIM > > access (const ArrayData< double > &array_data, int depth)
Function Documentation
template<int DIM> MDA_Access<double, DIM, MDA_OrderColMajor<DIM> > SAMRAI::pdat::access (ArrayData< double > & array_data, int depth) [inline]
References SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
template<int DIM> const MDA_AccessConst<double, DIM, MDA_OrderColMajor<DIM> > SAMRAI::pdat::access (const ArrayData< double > & array_data, int depth) [inline]
References SAMRAI::pdat::ArrayData< TYPE >::getBox(), SAMRAI::pdat::ArrayData< TYPE >::getPointer(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().