SAMRAI: SAMRAI::hier Namespace Reference
SAMRAI::hier Namespace Reference
Classes
class BaseConnectorAlgorithm
class BaseGridGeometry
Class BaseGridGeometry manages the index space that determines the extent of the coarse-level domain of a SAMRAI hierarchy.
class BlockId
Generic identifier for identifying the block id.
class BoundaryBox
Class BoundaryBox is is used to describe boundaries of a patch.
class BoundaryBoxUtils
Perform shifts, extensions, etc on a BoundaryBox using the box's location index and type.
class BoundaryLookupTable
Singleton class to organize patch boundary information.
class Box
class BoxIterator
class BoxContainer
A container for Boxes.
class BoxContainerSingleBlockIterator
BoxContainer iterator picking items with a specified BlockId.
class BoxContainerSingleOwnerIterator
BoxContainer iterator picking items with a specified owner rank.
class BoxContainerUtils
Utilities for performing simple common tasks on a container of Boxes.
class BoxGeometry
class BoxId
Identifier for a Box, consisting of a GlobalId and a PeriodicId.
class BoxLevel
A distributed set of Box objects which reside in the same index space.
class BoxLevelConnectorUtils
Utilities for common operating on BoxLevels.
class BoxLevelHandle
A handle for Connectors to access their head and base BoxLevels. A BoxLevel automatically releases its handle when it changes in a way that can invalidate Connector data, preventing the use of inconsistent data and deallocated objects.
class BoxLevelStatistics
A utility for writing out various statistics of Boxes.
class BoxNeighborhoodCollection
Given a Box in a base BoxLevel, the Boxes in a head BoxLevel which are adjacent to the base Box are its neighbors and are said to form the neighborhood of the base Box. This class describes the neighborhoods of a collection of base Boxes. Each base Box in the collection has a neighborhood of adjacent head Boxes.
class BoxOverlap
Class BoxOverlap is an abstract base class used to represent a region where data will be communicated between two AMR patches.
class BoxTree
Utility sorting Boxes into tree-like form for finding box overlaps.
struct BoxUtilities
class CoarseFineBoundary
Utility class to construct and maintain a description of the coarse-fine boundary between a patch level and a coarser level.
class CoarsenOperator
class ComponentSelector
Bit vector used to indicate on which patch data elements to apply operations.
class Connector
A container which holds relationship connections between two BoxLevels.
class ConnectorStatistics
A utility for writing out various statistics of Connectors.
class GlobalId
A locally determined, globally unique identifier.
class Index
class IntVector
class LocalId
Generic identifier for identifying things on the local process.
class MappingConnector
A container which holds overlap relationship connections between two BoxLevels.
class MappingConnectorAlgorithm
Algorithms for using MappingConnectors representing changes to a BoxLevel.
class MultiblockBoxTree
Utility sorting Boxes into tree-like form for finding box overlaps. Boxes are sorted by BlockId and then a BoxTree is constructed for each block in a BoxContainer.
class OverlapConnectorAlgorithm
Algorithms for working Connectors whose neighbor data represents overlaps.
class Patch
A container for patch data objects defined over a box.
class PatchBoundaries
Class PatchBoundaries is a container class for storing BoundaryBox objects for a single patch.
class PatchData
class PatchDataFactory
class PatchDataRestartManager
class PatchDescriptor
Class PatchDescriptor maintains a collection of patch data factories and associated names that describes how patch data entries are constructed on each patch in an AMR hierarchy. The factory mechanism is used to create new instances of concrete patch data objects without knowing their actual types. See the Design Patterns book by Gamma {et al.} for more details about the Abstract Factory pattern. Generally, a PatchDescriptor object is intended to be shared among all patches (which are distributed across processors) so that they store patch data objects in the same way.
class PatchFactory
class PatchGeometry
class PatchHierarchy
Class PatchHierarchy maintains the patch levels that define the AMR hierarchy.
class PatchLevel
Container class for patches defined at a single level of the AMR hierarchy.
class PatchLevelFactory
Factory used to create new patch levels.
class PeriodicId
Generic identifier for identifying the periodic shift.
class PeriodicShiftCatalog
Singleton for cataloging periodic shifts and assigning each one a unique "shift number".
class PersistentOverlapConnectors
A managager of overlap Connectors incident from a BoxLevel, used to store and, if needed, generate overlap Connectors in BoxLevel.
class ProcessorMapping
class RealBoxConstIterator
Iterator through real Boxes (not periodic images) in a const BoxContainer.
class RefineOperator
class SequentialLocalIdGenerator
Class for generating sequential LocalId.
class SingularityFinder
Class SingularityFinder implements an algorithm to find multiblock singularities based on the relationships between blocks that touch on an entire face.
class TimeInterpolateOperator
class TransferOperatorRegistry
Class TransferOperatorRegistry is intended to serve as the registry for SAMRAI transfer operators. It will be a singleton object held by class hier::BaseGridGeometry.
class Transformation
Class Transformation represents generalized transformations between coordinate systems or within coordinate systems.
class UncoveredBoxIterator
An iterator over the uncovered Boxes in a hierarhcy.
class Variable
class VariableContext
class VariableDatabase
Generates and manages mappings between Variables and/or (Variable,VariableContext) pairs and patch data indices.
Enumerations
enum ConnectorNotFoundAction { CONNECTOR_ERROR, CONNECTOR_CREATE, CONNECTOR_IMPLICIT_CREATION_RULE }
Action to take when Connectors between BoxLevels are not found.
Functions
std::istream & operator>> (std::istream &s, Box &box)
std::ostream & operator<< (std::ostream &s, const Box &box)
BoxContainer::operator std::vector< tbox::DatabaseBox > () const
std::ostream & operator<< (std::ostream &s, const BoxContainer::Outputter &format)
std::ostream & operator<< (std::ostream &co, const BoxId &r)
std::ostream & operator<< (std::ostream &s, const BoxLevel::Outputter &format)
std::ostream & operator<< (std::ostream &os, const Connector::Outputter &format)
std::ostream & operator<< (std::ostream &co, const GlobalId &r)
std::istream & operator>> (std::istream &s, IntVector &rhs)
std::ostream & operator<< (std::ostream &s, const IntVector &rhs)
std::ostream & operator<< (std::ostream &co, const LocalId &r)
std::ostream & operator<< (std::ostream &s, const Patch &patch)
std::ostream & operator<< (std::ostream &co, const PeriodicId &r)
Enumeration Type Documentation
enum SAMRAI::hier::ConnectorNotFoundAction
Action to take when Connectors between BoxLevels are not found.
Enumerator:
CONNECTOR_ERROR
CONNECTOR_CREATE
CONNECTOR_IMPLICIT_CREATION_RULE
Function Documentation
std::istream& SAMRAI::hier::operator>> (std::istream & s, Box & box)
References SAMRAI::hier::Box::lower(), NULL_STATEMENT, and SAMRAI::hier::Box::upper().
std::ostream& SAMRAI::hier::operator<< (std::ostream & s, const Box & box)
References SAMRAI::hier::Box::empty(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::Box::lower(), and SAMRAI::hier::Box::upper().
SAMRAI::hier::BoxContainer::operator std::vector< tbox::DatabaseBox > () const
std::ostream& SAMRAI::hier::operator<< (std::ostream & s, const BoxContainer::Outputter & format)
References SAMRAI::hier::BoxContainer::print().
std::ostream& SAMRAI::hier::operator<< (std::ostream & co, const BoxId & r)
References SAMRAI::hier::GlobalId::getLocalId(), and SAMRAI::hier::GlobalId::getOwnerRank().
std::ostream& SAMRAI::hier::operator<< (std::ostream & s, const BoxLevel::Outputter & format)
References SAMRAI::hier::BoxLevelStatistics::printBoxStats(), and SAMRAI::hier::BoxLevel::recursivePrint().
std::ostream& SAMRAI::hier::operator<< (std::ostream & os, const Connector::Outputter & format)
References SAMRAI::hier::ConnectorStatistics::printNeighborStats(), and SAMRAI::hier::Connector::recursivePrint().
std::ostream& SAMRAI::hier::operator<< (std::ostream & co, const GlobalId & r)
std::istream& SAMRAI::hier::operator>> (std::istream & s, IntVector & rhs)
References SAMRAI::hier::IntVector::getDim(), and SAMRAI::tbox::Dimension::getValue().
std::ostream& SAMRAI::hier::operator<< (std::ostream & s, const IntVector & rhs)
References SAMRAI::hier::IntVector::getDim(), and SAMRAI::tbox::Dimension::getValue().
std::ostream& SAMRAI::hier::operator<< (std::ostream & co, const LocalId & r)
std::ostream& SAMRAI::hier::operator<< (std::ostream & s, const Patch & patch)
std::ostream& SAMRAI::hier::operator<< (std::ostream & co, const PeriodicId & r)