SAMRAI: arith_functions Struct Reference
arith_functions Struct Reference
Public Attributes
string d_name
double(* d_r2r_func)(double)
dcomplex(* d_c2c_func)(const dcomplex &)
double(* d_c2r_func)(const dcomplex &)
Member Data Documentation
string arith_functions::d_name
Referenced by eval_function(), and parser_static_table_initialize().
double(* arith_functions::d_r2r_func)(double)
Referenced by eval_function(), and parser_static_table_initialize().
dcomplex(* arith_functions::d_c2c_func)(const dcomplex &)
Referenced by eval_function(), and parser_static_table_initialize().
double(* arith_functions::d_c2r_func)(const dcomplex &)
Referenced by eval_function(), and parser_static_table_initialize().
The documentation for this struct was generated from the following file:
source/SAMRAI/tbox/Grammar.C