SAMRAI: SAMRAI::mesh::BoxInTransit Struct Reference
SAMRAI::mesh::BoxInTransit Struct Reference
A Box moving around during load balancing.
#include <source/SAMRAI/mesh/BoxInTransit.h>
Public Member Functions
BoxInTransit (const tbox::Dimension &dim)
Constructor.
BoxInTransit (const hier::Box &origin)
Construct a new BoxInTransit from an originating box.
BoxInTransit (const BoxInTransit &other, const hier::Box &box, int rank, hier::LocalId local_id, double load=-1.)
Construct new object like an existing object but with a new ID.
BoxInTransit & operator= (const BoxInTransit &other)
Assignment operator.
int getOwnerRank () const
Return the owner rank.
hier::LocalId getLocalId () const
Return the LocalId.
hier::Box & getBox ()
Return the Box.
const hier::Box & getBox () const
Return the Box.
hier::Box & getOrigBox ()
Return the original Box.
const hier::Box & getOrigBox () const
Return the original Box.
double getLoad () const
Return the Box load.
void setLoad (double boxload)
Return the Box load.
bool isOriginal () const
Return whether this is an original box.
void putToMessageStream (tbox::MessageStream &mstream) const
Put self into a MessageStream.
void getFromMessageStream (tbox::MessageStream &mstream)
Set attributes according to data in a MessageStream.
Friends
std::ostream & operator<< (std::ostream &co, const BoxInTransit &r)
Insert BoxInTransit into an output stream.
Detailed Description
A Box moving around during load balancing.
The purpose of the BoxInTransit is to associate extra data with a Box as it is broken up and passed from process to process. A BoxInTransit is a Box going through these changes. It has a current work load and an orginating Box.
Constructor & Destructor Documentation
SAMRAI::mesh::BoxInTransit::BoxInTransit (const tbox::Dimension & dim) [inline, explicit]
Constructor.
Parameters:
[in] dim
SAMRAI::mesh::BoxInTransit::BoxInTransit (const hier::Box & origin) [inline]
Construct a new BoxInTransit from an originating box.
Parameters:
[in] origin
SAMRAI::mesh::BoxInTransit::BoxInTransit (const BoxInTransit & other, const hier::Box & box, int rank, hier::LocalId local_id, double load = -1.) [inline]
Construct new object like an existing object but with a new ID.
Parameters:
[in] other
[in] box
[in] rank
[in] local_id
[in] load Box load. If omitted, set to box's volume.
Member Function Documentation
BoxInTransit& SAMRAI::mesh::BoxInTransit::operator= (const BoxInTransit & other) [inline]
Assignment operator.
Parameters:
[in] other
int SAMRAI::mesh::BoxInTransit::getOwnerRank () const [inline]
Return the owner rank.
References SAMRAI::hier::Box::getOwnerRank().
hier::LocalId SAMRAI::mesh::BoxInTransit::getLocalId () const [inline]
Return the LocalId.
References SAMRAI::hier::Box::getLocalId().
hier::Box& SAMRAI::mesh::BoxInTransit::getBox () [inline]
Return the Box.
Referenced by SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges().
const hier::Box& SAMRAI::mesh::BoxInTransit::getBox () const [inline]
Return the Box.
hier::Box& SAMRAI::mesh::BoxInTransit::getOrigBox () [inline]
Return the original Box.
Referenced by SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges().
const hier::Box& SAMRAI::mesh::BoxInTransit::getOrigBox () const [inline]
Return the original Box.
double SAMRAI::mesh::BoxInTransit::getLoad () const [inline]
Return the Box load.
Referenced by SAMRAI::mesh::BoxTransitSet::insertAll().
void SAMRAI::mesh::BoxInTransit::setLoad (double boxload) [inline]
Return the Box load.
bool SAMRAI::mesh::BoxInTransit::isOriginal () const [inline]
Return whether this is an original box.
References SAMRAI::hier::Box::isIdEqual().
Referenced by SAMRAI::mesh::BoxTransitSet::generateLocalBasedMapEdges().
void SAMRAI::mesh::BoxInTransit::putToMessageStream (tbox::MessageStream & mstream) const [inline]
Put self into a MessageStream.
References SAMRAI::hier::Box::putToMessageStream().
Referenced by SAMRAI::mesh::BoxTransitSet::putToMessageStream().
void SAMRAI::mesh::BoxInTransit::getFromMessageStream (tbox::MessageStream & mstream) [inline]
Set attributes according to data in a MessageStream.
References SAMRAI::hier::Box::getFromMessageStream().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & co, const BoxInTransit & r) [friend]
Insert BoxInTransit into an output stream.
The documentation for this struct was generated from the following file:
source/SAMRAI/mesh/BoxInTransit.h