SAMRAI: SAMRAI::tbox::AsyncCommStage::Member Struct Reference
SAMRAI::tbox::AsyncCommStage::Member Struct Reference
Something on a stage, using MPI requests and statuses provided by the stage.
#include <source/SAMRAI/tbox/AsyncCommStage.h>
Public Member Functions
Member ()
Default constructor, requiring a follow-up call to attachStage() to properly stage the Member.
Member (const size_t nreq, AsyncCommStage *stage, Handler *handler)
Initializing constructor.
virtual ~Member ()
Destructor detach the Member from its stage. Memory allocated by the stage to support the Member will be recycled.
size_t numberOfRequests () const
Get the number of requests for the stage Member.
size_t numberOfPendingRequests () const
Return the number of pending SAMRAI_MPI::Request objects for the Member.
bool hasPendingRequests () const
Return whether the Member has some pending communication requests.
virtual bool isDone () const =0
Check whether entire operation is done.
virtual bool proceedToNextWait ()=0
If current MPI requests have completed, proceed to the next communication wait (or to completion if no more communication is needed).
virtual void completeCurrentOperation ()=0
Complete entire operation, including waiting for messages perform follow-up operations and waiting for follow-ups to complete.
void setHandler (Handler *handler)
Set a user-defined Handler.
Handler * getHandler () const
Regurgitate the handler from setHandler().
void pushToCompletionQueue ()
Push this onto its stage's list of completed Members.
void yankFromCompletionQueue ()
Yank this member from the stage's list of completed Members so it would not be returned by AsyncCommStage::popCompletionQueue().
bool hasStage () const
Returns true if there is a stage associated with this member.
Protected Member Functions
void attachStage (const size_t nreq, AsyncCommStage *stage)
Associate the member with a stage.
void detachStage ()
Disassociate the member from its stage (undo attachStage()).
SAMRAI_MPI::Request * getRequestPointer () const
Return the MPI requests provided by the stage for the Member.
SAMRAI_MPI::Status * getStatusPointer () const
Return MPI statuses for this Member of the stage.
size_t getNumberOfRequests () const
Return the number of requests for this stage Member.
Friends
class AsyncCommStage
Member is an integral part of the stage code and the stage will set the Member's internal data.
Detailed Description
Something on a stage, using MPI requests and statuses provided by the stage.
This class defines the interfaces required to participate in a AsyncCommStage. Subclasses should implement communication operations using the MPI requests and statuses returned by getRequestPointer() and getStatusPointer().
Constructor & Destructor Documentation
SAMRAI::tbox::AsyncCommStage::Member::Member ()
Default constructor, requiring a follow-up call to attachStage() to properly stage the Member.
SAMRAI::tbox::AsyncCommStage::Member::Member (const size_t nreq, AsyncCommStage * stage, AsyncCommStage::Handler * handler)
Initializing constructor.
Same as default construction plus attachStage(), plus setHandler().
SAMRAI::tbox::AsyncCommStage::Member::~Member () [virtual]
Destructor detach the Member from its stage. Memory allocated by the stage to support the Member will be recycled.
Precondition:
!hasPendingRequests()
References hasPendingRequests(), and TBOX_ERROR.
Member Function Documentation
size_t SAMRAI::tbox::AsyncCommStage::Member::numberOfRequests () const [inline]
Get the number of requests for the stage Member.
This is the number used to initialize the object. If the Member has not been initialized to a stage, zero is returned.
Referenced by SAMRAI::tbox::AsyncCommGroup::AsyncCommGroup().
size_t SAMRAI::tbox::AsyncCommStage::Member::numberOfPendingRequests () const
Return the number of pending SAMRAI_MPI::Request objects for the Member.
References getRequestPointer(), and MPI_REQUEST_NULL.
bool SAMRAI::tbox::AsyncCommStage::Member::hasPendingRequests () const
Return whether the Member has some pending communication requests.
References getRequestPointer(), and MPI_REQUEST_NULL.
Referenced by SAMRAI::tbox::AsyncCommStage::advanceSome(), SAMRAI::tbox::AsyncCommGroup::isDone(), and ~Member().
virtual bool SAMRAI::tbox::AsyncCommStage::Member::isDone () const [pure virtual]
Check whether entire operation is done.
This should not just check the MPI requests--that is the job for hasPendingRequests(). It should check the entire communication operation (which may have follow-up communications and computations). If MPI communications are completed but have not been followed through by a completeCurrentOperation(), it should return false.
Implemented in SAMRAI::tbox::AsyncCommGroup, SAMRAI::tbox::AsyncCommPeer< TYPE >, and SAMRAI::tbox::AsyncCommPeer< char >.
Referenced by SAMRAI::tbox::AsyncCommStage::advanceSome(), and pushToCompletionQueue().
virtual bool SAMRAI::tbox::AsyncCommStage::Member::proceedToNextWait () [pure virtual]
If current MPI requests have completed, proceed to the next communication wait (or to completion if no more communication is needed).
Implemented in SAMRAI::tbox::AsyncCommGroup, SAMRAI::tbox::AsyncCommPeer< TYPE >, and SAMRAI::tbox::AsyncCommPeer< char >.
Referenced by SAMRAI::tbox::AsyncCommStage::advanceSome().
virtual void SAMRAI::tbox::AsyncCommStage::Member::completeCurrentOperation () [pure virtual]
Complete entire operation, including waiting for messages perform follow-up operations and waiting for follow-ups to complete.
After this method completes, isDone() should return true.
This method should assume that all needed communications can finish within this method. Otherwise the method may hang.
Implemented in SAMRAI::tbox::AsyncCommGroup, SAMRAI::tbox::AsyncCommPeer< TYPE >, and SAMRAI::tbox::AsyncCommPeer< char >.
void SAMRAI::tbox::AsyncCommStage::Member::setHandler (Handler * handler) [inline]
Set a user-defined Handler.
A Handler is just some user-defined data.
When the stage returns completed Members, the Handler makes it easier to determine what was waiting for the Member to complete. If you do not need to find the handler this way, you do not need to set it. Typically, Handlers are only needed if a stage is simultaneously coordinating multiple Members per processor.
By design, a non-const Handler is returned, even by a const Member. This is because the Handler is expected to follow the communication operation with something non-trivial and possibly state-changing.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::initialize(), and SAMRAI::tbox::AsyncCommGroup::initialize().
Handler* SAMRAI::tbox::AsyncCommStage::Member::getHandler () const [inline]
Regurgitate the handler from setHandler().
void SAMRAI::tbox::AsyncCommStage::Member::pushToCompletionQueue ()
Push this onto its stage's list of completed Members.
This causes the member to be returned by a call to AsyncCommStage::popCompletionQueue(), eventually.
Precondition:
isDone()
References isDone(), and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::mesh::GraphLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::hier::BaseConnectorAlgorithm::setupCommunication().
void SAMRAI::tbox::AsyncCommStage::Member::yankFromCompletionQueue () [inline]
Yank this member from the stage's list of completed Members so it would not be returned by AsyncCommStage::popCompletionQueue().
bool SAMRAI::tbox::AsyncCommStage::Member::hasStage () const [inline]
Returns true if there is a stage associated with this member.
Referenced by getRequestPointer(), and getStatusPointer().
void SAMRAI::tbox::AsyncCommStage::Member::attachStage (const size_t nreq, AsyncCommStage * stage) [protected]
Associate the member with a stage.
Specify the stage to use and the number of SAMRAI_MPI::Request objects needed from the stage.
Parameters:
[in] nreq Number of SAMRAI_MPI::Requests needed by the member.
[in] stage The AsyncCommStage to attach to.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::initialize(), and SAMRAI::tbox::AsyncCommGroup::initialize().
void SAMRAI::tbox::AsyncCommStage::Member::detachStage () [protected]
Disassociate the member from its stage (undo attachStage()).
SAMRAI_MPI::Request * SAMRAI::tbox::AsyncCommStage::Member::getRequestPointer () const [protected]
Return the MPI requests provided by the stage for the Member.
To work on the stage, you must use these requests in your non-blocking MPI calls. The requests are a part of an array of requests for all Members on the stage. Use only getNumberOfRequests() requests. Terrible bugs will strike if you modify more than what was allocated for the Member.
Important: Do not save the pointer returned by this method. The stage's dynamic memory actions may render old pointers invalid.
Precondition:
hasStage()
References hasStage(), and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommGroup::checkBcast(), SAMRAI::tbox::AsyncCommGroup::checkGather(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation(), SAMRAI::tbox::AsyncCommGroup::completeCurrentOperation(), hasPendingRequests(), SAMRAI::tbox::AsyncCommPeer< TYPE >::logCurrentState(), SAMRAI::tbox::AsyncCommGroup::logCurrentState(), and numberOfPendingRequests().
SAMRAI_MPI::Status * SAMRAI::tbox::AsyncCommStage::Member::getStatusPointer () const [protected]
Return MPI statuses for this Member of the stage.
To work on the stage, you must use these statuses in your MPI calls. The status attributes are set by the stage only for requests completed by the stage. The statuses are a part of an array of statuses for all Members on the stage. Use only getNumberOfRequests() statuses. Terrible bugs will strike if you modify more than what was allocated for the Member.
Important: Do not save the pointer returned by this method. The stage's dynamic memory actions may render old pointers invalid.
Precondition:
hasStage()
References hasStage(), and TBOX_ERROR.
Referenced by SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), and SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation().
size_t SAMRAI::tbox::AsyncCommStage::Member::getNumberOfRequests () const [inline, protected]
Return the number of requests for this stage Member.
Friends And Related Function Documentation
friend class AsyncCommStage [friend]
Member is an integral part of the stage code and the stage will set the Member's internal data.
The documentation for this struct was generated from the following files:
source/SAMRAI/tbox/AsyncCommStage.h
source/SAMRAI/tbox/AsyncCommStage.C