SAMRAI: SAMRAI::tbox::MemoryUtilities Struct Reference
SAMRAI::tbox::MemoryUtilities Struct Reference
Class MemoryUtilities provides utility methods for memory usage and misc memory utilities.
#include <source/SAMRAI/tbox/MemoryUtilities.h>
Static Public Member Functions
static void printMemoryInfo (std::ostream &os)
static void recordMemoryInfo (double time=0.0)
static void printMaxMemory (std::ostream &os)
static size_t align (const size_t bytes)
Detailed Description
Class MemoryUtilities provides utility methods for memory usage and misc memory utilities.
"printMemoryInfo()" which does a simple dump of the current memory usage on a processor, and "recordMemoryInfo()" which records the memory for post-process analysis.
Calls to these methods may be placed at various points in an application to track memory usage characteristics. For applications running on a single processor, the call the print method is likely sufficient. The information can simply be printed to a log file or output stream. For applications running on multiple processors, or which otherwise have complex memory patterns that cannot easily be deciphered from prints to a log file, the record method may be more useful. Use of this method requires the TAU (Tuning and Analysis Utilities) package to keep a profile of the recorded memory information so that it can be analyzed via a post-processing tool.
Note that all member functions of this class are static so it is not necessary to instantiate the class. Simply call the functions as static functions; e.g.,MemoryUtilities::function(...).
Member Function Documentation
void SAMRAI::tbox::MemoryUtilities::printMemoryInfo (std::ostream & os) [static]
Print memory information to the supplied output stream.
References NULL_USE.
void SAMRAI::tbox::MemoryUtilities::recordMemoryInfo (double time = 0.0) [static]
Record memory info to be analyzed by TAU (Tuning and Analysis Utilities). If tracing is enabled, you can supply a time at which the memory is recorded. This method requires SAMRAI to be configured with TAU. If it is not, the method will do nothing.
References NULL_USE.
void SAMRAI::tbox::MemoryUtilities::printMaxMemory (std::ostream & os) [static]
Print maximum memory used (i.e. high-water mark) to the supplied output stream.
References SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), SAMRAI::tbox::SAMRAI_MPI::getSize(), MPI_INT, SAMRAI::tbox::SAMRAI_MPI::Recv(), and SAMRAI::tbox::SAMRAI_MPI::Send().
size_t SAMRAI::tbox::MemoryUtilities::align (const size_t bytes) [static]
Static function to compute alignment for memory allocation. Data allocations less than the alignment size are rounded up to the next multiple of the allocation size. All data allocations are aligned on 16 byte boundaries. Thus, a memory allocation of only 9 bytes will actually return a 16 byte chunk of memory.
Referenced by SAMRAI::pdat::ArrayData< TYPE >::getSizeOfData(), SAMRAI::pdat::SideDataFactory< TYPE >::getSizeOfMemory(), SAMRAI::pdat::OutersideDataFactory< TYPE >::getSizeOfMemory(), SAMRAI::pdat::OuternodeDataFactory< TYPE >::getSizeOfMemory(), SAMRAI::pdat::OuterfaceDataFactory< TYPE >::getSizeOfMemory(), SAMRAI::pdat::OuteredgeDataFactory< TYPE >::getSizeOfMemory(), SAMRAI::pdat::NodeDataFactory< TYPE >::getSizeOfMemory(), SAMRAI::pdat::IndexDataFactory< TYPE, BOX_GEOMETRY >::getSizeOfMemory(), SAMRAI::pdat::FaceDataFactory< TYPE >::getSizeOfMemory(), SAMRAI::pdat::EdgeDataFactory< TYPE >::getSizeOfMemory(), and SAMRAI::pdat::CellDataFactory< TYPE >::getSizeOfMemory().
The documentation for this struct was generated from the following files:
source/SAMRAI/tbox/MemoryUtilities.h
source/SAMRAI/tbox/MemoryUtilities.C