SAMRAI: SAMRAI::mesh::BalanceUtilities Struct Reference
SAMRAI::mesh::BalanceUtilities Struct Reference
Utility class BalanceUtilities provides several functions useful in various load balancing operations. These utilities include bin packing operations, box chopping by recursive bisection, and computation of effective processor layouts for boxes.
#include <source/SAMRAI/mesh/BalanceUtilities.h>
Static Public Member Functions
static double binPack (hier::ProcessorMapping &mapping, std::vector< double > &weights, int nproc)
static double spatialBinPack (hier::ProcessorMapping &mapping, std::vector< double > &weights, hier::BoxContainer &boxes, const int nproc)
static void recursiveBisectionUniform (hier::BoxContainer &out_boxes, std::list< double > &out_workloads, const hier::BoxContainer &in_boxes, double ideal_workload, const double workload_tolerance, const hier::IntVector &min_size, const hier::IntVector &cut_factor, const hier::IntVector &bad_interval, const hier::BoxContainer &physical_domain)
static void recursiveBisectionNonuniform (hier::BoxContainer &out_boxes, std::list< double > &out_workloads, const boost::shared_ptr< hier::PatchLevel > &in_level, int work_id, double ideal_workload, const double workload_tolerance, const hier::IntVector &min_size, const hier::IntVector &cut_factor, const hier::IntVector &bad_interval, const hier::BoxContainer &physical_domain)
static void computeDomainDependentProcessorLayout (hier::IntVector &proc_dist, int num_procs, const hier::Box &box)
static void computeDomainIndependentProcessorLayout (hier::IntVector &proc_dist, int num_procs, const hier::Box &box)
static void sortDescendingBoxWorkloads (hier::BoxContainer &boxes, std::vector< double > &workload)
static double computeNonUniformWorkload (const boost::shared_ptr< hier::Patch > &patch, int wrk_indx, const hier::Box &box)
static double computeNonUniformWorkloadOnCorners (std::vector< double > &corner_weights, const boost::shared_ptr< hier::Patch > &patch, int wrk_indx, const hier::Box &box)
Compute total workload in region of argument box based on patch data defined by given integer index, while also associating weights with corners of the box.
static void findSmallBoxesInPostbalance (std::ostream &co, const std::string &border, const hier::MappingConnector &post_to_pre, const hier::IntVector &min_width, size_t min_vol)
Find small boxes in a post-balance BoxLevel that are not in a pre-balance BoxLevel.
static void findSmallBoxesInPostbalance (std::ostream &co, const std::string &border, const hier::BoxLevel &pre, const hier::BoxLevel &post, const hier::IntVector &min_width, size_t min_vol)
Find small boxes in a post-balance BoxLevel that are not in a pre-balance BoxLevel.
static bool compareLoads (int flags[], double current_load, double new_load, double ideal_load, double low_load, double high_load, const PartitioningParams &pparams)
Evaluate whether a new load is an improvement over a current load based on their proximity to an ideal value or range of acceptable values.
static double computeLoadBalanceEfficiency (const boost::shared_ptr< hier::PatchLevel > &level, std::ostream &os, int workload_data_id=-1)
static void constrainMaxBoxSizes (hier::BoxLevel &box_level, hier::Connector *anchor_to_level, const PartitioningParams &pparams)
static void prebalanceBoxLevel (hier::BoxLevel &balance_box_level, hier::Connector *balance_to_anchor, const tbox::RankGroup &rank_group)
Load balance reporting.
static void reduceAndReportLoadBalance (const std::vector< double > &local_loads, const tbox::SAMRAI_MPI &mpi, std::ostream &output_stream=tbox::plog)
Globally reduce a sequence of workloads in an MPI group and write out a summary of load balance efficiency.
Static Public Attributes
static const int BalanceUtilities_PREBALANCE0 = 5
static const int BalanceUtilities_PREBALANCE1 = 6
Detailed Description
Utility class BalanceUtilities provides several functions useful in various load balancing operations. These utilities include bin packing operations, box chopping by recursive bisection, and computation of effective processor layouts for boxes.
Member Function Documentation
double SAMRAI::mesh::BalanceUtilities::binPack (hier::ProcessorMapping & mapping, std::vector< double > & weights, int nproc) [static]
Assign workloads to processors using a greedy algorithm that attempts to distribute the sum of weights on each processor evenly across the given number of processors.
Returns:
double-valued estimate of the load balance efficiency (ranges from zero to one hundred percent)
Parameters:
mapping Output processor mapping.
weights std::vector of double-valued weights to distribute.
nproc Integer number of processors, must be > 0.
Precondition:
nproc > 0
for each memeber of weights, w, w >=0
References SAMRAI::hier::ProcessorMapping::setMappingSize(), SAMRAI::hier::ProcessorMapping::setProcessorAssignment(), and TBOX_ASSERT.
double SAMRAI::mesh::BalanceUtilities::spatialBinPack (hier::ProcessorMapping & mapping, std::vector< double > & weights, hier::BoxContainer & boxes, const int nproc) [static]
Assign boxes to processors so that boxes spatially near each other are likely to be assigned to processors near each other (assuming that processor ordering is reflected in processor rank) and so that the workload is approximately evenly distributed among the processors. The routine uses a Morton space-filling curve algorithm.
Note that this routine potentially reorders the boxes passed in to achieve the first goal.
Returns:
Double-valued estimate of the load balance efficiency (ranges from zero to one hundred percent)
Parameters:
mapping Output processor mapping.
weights std::vector of double-valued box weights to distribute.
boxes hier::BoxContainer of boxes to distribute to processors.
nproc Integer number of processors, must be > 0.
Precondition:
nproc > 0
weights.size() == boxes.size()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::front(), SAMRAI::hier::ProcessorMapping::getProcessorAssignment(), SAMRAI::hier::ProcessorMapping::setMappingSize(), SAMRAI::hier::BoxContainer::size(), TBOX_ASSERT, and TBOX_ERROR.
void SAMRAI::mesh::BalanceUtilities::recursiveBisectionUniform (hier::BoxContainer & out_boxes, std::list< double > & out_workloads, const hier::BoxContainer & in_boxes, double ideal_workload, const double workload_tolerance, const hier::IntVector & min_size, const hier::IntVector & cut_factor, const hier::IntVector & bad_interval, const hier::BoxContainer & physical_domain) [static]
Recursively chop chops boxes in input boxlist until each box has a workload less than the prescribed ideal workload or no more more chopping is allowed by the given constraints. A spatially-uniform workload is assumed; i.e., all cells are weighted equally. This routine attempts to create as many boxes as possible with loads equal to or slightly less than the ideal workload value so that they can be mapped to processors effectively.
Parameters:
out_boxes Output box list.
out_workloads Output list of box workloads.
in_boxes Input boxlist for chopping.
ideal_workload Input double ideal box workload, must be > 0.
workload_tolerance Input double workload tolerance, must be >= 0 and < 1.0
min_size Input integer vector of minimum sizes for output boxes. All entries must be > 0.
cut_factor Input integer vector used to create boxes with correct sizes. The box size in each direction will be an integer multiple of the corresponding cut factor vector entry. All vector entries must be > 0. See hier::BoxUtilities documentation for more details.
bad_interval Input integer vector used to create boxes near physical domain boundary with sufficient number of cells. No box face will be closer to the boundary than the corresponding interval of cells to the boundary (the corresponding value is given by the normal direction of the box face) unless the face coincides with the boundary itself. The point of this argument is to have no patch live within a certain ghost cell width of the boundary if its boundary does not coincide with that boundary . That is, all ghost cells along a face will be either in the domain interior or outside the domain. All entries must be >= 0. See hier::BoxUtilities documentation for more details.
physical_domain hier::BoxContainer of boxes describing the physical extent of the index space associated with the in_boxes. This box array cannot be empty.
Precondition:
(min_size.getDim() == cut_factor.getDim()) && (min_size.getDim() == bad_interval.getDim())
ideal_workload > 0
(workload_tolerance >= 0) && (workload_tolerance < 1.0)
min_size > hier::IntVector::getZero(min_size.getDim())
cut_factor > hier::IntVector::getZero(min_size.getDim())
bad_interval >= hier::IntVector::getZero(min_size.getDim())
!physical_domain.empty()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::clear(), SAMRAI::hier::Box::empty(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::IntVector::getBlockVector(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getNumBlocks(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::pushFront(), SAMRAI::hier::Box::size(), SAMRAI::hier::BoxContainer::spliceBack(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
void SAMRAI::mesh::BalanceUtilities::recursiveBisectionNonuniform (hier::BoxContainer & out_boxes, std::list< double > & out_workloads, const boost::shared_ptr< hier::PatchLevel > & in_level, int work_id, double ideal_workload, const double workload_tolerance, const hier::IntVector & min_size, const hier::IntVector & cut_factor, const hier::IntVector & bad_interval, const hier::BoxContainer & physical_domain) [static]
Recursively chops boxes given by patches on input patch level until each box has a workload less than the prescribed ideal workload or no more more chopping is allowed by the given constraints. A spatially-nonuniform workload is assumed. Cell weights must be given bydata defined by the given patch data id on the given patch level. This routine attempts to create as many boxes as possible with loads equal to or slightly less than the ideal workload value so that they can be mapped to processors effectively.
Parameters:
out_boxes Output box list.
out_workloads Output list of box workloads.
in_level Input patch level whose patches describe input box regions and whose patch data contain workload estimate for each cell.
work_id Input integer patch data id for cell-centered double work estimate for each cell.
ideal_workload Input double ideal box workload, must be > 0.
workload_tolerance Input double workload tolerance, must be >= 0 and < 1.0
min_size Input integer vector of minimum sizes for output boxes. All entries must be > 0.
cut_factor Input integer vector used to create boxes with correct sizes. The box size in each direction will be an integer multiple of the corresponding cut factor vector entry. All vector entries must be > 0. See hier::BoxUtilities documentation for more details.
bad_interval Input integer vector used to create boxes near physical domain boundary with sufficient number of cells. No box face will be closer to the boundary than the corresponding interval of cells to the boundary (the corresponding value is given by the normal direction of the box face) unless the face coincides with the boundary itself. The point of this argument is to have no patch live within a certain ghost cell width of the boundary if its boundary does not coincide with that boundary . That is, all ghost cells along a face will be either in the domain interior or outside the domain. All entries must be >= 0. See hier::BoxUtilities documentation for more details.
physical_domain hier::BoxContainer of boxes describing the physical extent of the index space associated with the in_boxes. This box array cannot be empty.
Precondition:
(min_size.getDim() == cut_factor.getDim()) && (min_size.getDim() == bad_interval.getDim())
ideal_workload > 0
(workload_tolerance >= 0) && (workload_tolerance < 1.0)
min_size > hier::IntVector::getZero(min_size.getDim())
cut_factor > hier::IntVector::getZero(min_size.getDim())
bad_interval >= hier::IntVector::getZero(min_size.getDim())
!physical_domain.empty()
References SAMRAI::hier::BoxContainer::clear(), computeNonUniformWorkload(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::IntVector::getBlockVector(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getNumBlocks(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::BoxContainer::pushFront(), SAMRAI::hier::BoxContainer::spliceBack(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY3.
void SAMRAI::mesh::BalanceUtilities::computeDomainDependentProcessorLayout (hier::IntVector & proc_dist, int num_procs, const hier::Box & box) [static]
Compute factorization of processors corresponding to size of given box.
Parameters:
proc_dist Output number of processors for each coordinate direction.
num_procs Input integer number of processors, must be > 0.
box Input box to be distributed.
Precondition:
proc_dist.getDim() == box.getDim()
num_procs > 0
for each dimension, i, box.numberCells(i) > 0
References computeDomainIndependentProcessorLayout(), SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::hier::Box::numberCells(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_WARNING.
void SAMRAI::mesh::BalanceUtilities::computeDomainIndependentProcessorLayout (hier::IntVector & proc_dist, int num_procs, const hier::Box & box) [static]
Compute a factorization of processors that does NOT necessarily correspond to the dimensions of the supplied box. For example, the processor distribution in each direction may simply be a square root (cube root in 3D) of the number of processors. The box information is used simply to determine a maximum number of processors in each coordinate direction.
Parameters:
proc_dist Output number of processors for each coordinate direction.
num_procs Input integer number of processors, must be > 0.
box Input box to be distributed.
Precondition:
proc_dist.getDim() == box.getDim()
num_procs > 0
for each dimension, i, box.numberCells(i) > 0
References SAMRAI::hier::IntVector::getDim(), SAMRAI::hier::IntVector::getProduct(), SAMRAI::hier::Box::numberCells(), TBOX_ASSERT, TBOX_ASSERT_OBJDIM_EQUALITY2, and TBOX_ERROR.
Referenced by computeDomainDependentProcessorLayout().
void SAMRAI::mesh::BalanceUtilities::sortDescendingBoxWorkloads (hier::BoxContainer & boxes, std::vector< double > & workload) [static]
Sort box array in descending order of workload according to the workload array. Both the box array and the work array will be sorted on return.
Note that if you simply want to sort boxes based on their size, see hier::BoxUtilities.
Parameters:
boxes Boxes to be sorted based on workload array.
workload Workloads to use for sorting boxes.
Precondition:
boxes.size() == workload.size()
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::front(), SAMRAI::hier::BoxContainer::size(), and TBOX_ASSERT.
double SAMRAI::mesh::BalanceUtilities::computeNonUniformWorkload (const boost::shared_ptr< hier::Patch > & patch, int wrk_indx, const hier::Box & box) [static]
Compute total workload in region of argument box based on patch data defined by given integer index. The sum is computed on the intersection of argument box and box over which data associated with workload is defined.
Returns:
Sum of workload values in box region.
Parameters:
patch Input patch on which workload data is defined.
wrk_indx Input integer patch data identifier for work data.
box Input box region
Note that wrk_indx must refer to a valid cell-centered patch data entry.
Precondition:
patch
patch->getDim() == box.getDim()
References BOOST_CAST, SAMRAI::math::PatchCellDataNormOpsReal< TYPE >::L1Norm(), TBOX_ASSERT, and TBOX_ASSERT_OBJDIM_EQUALITY2.
Referenced by computeNonUniformWorkloadOnCorners(), and recursiveBisectionNonuniform().
double SAMRAI::mesh::BalanceUtilities::computeNonUniformWorkloadOnCorners (std::vector< double > & corner_weights, const boost::shared_ptr< hier::Patch > & patch, int wrk_indx, const hier::Box & box) [static]
Compute total workload in region of argument box based on patch data defined by given integer index, while also associating weights with corners of the box.
The corner weights are fractional values that identify how much of the workload is located in each quadrant or octant of the box.
Returns:
Sum of workload values in the box.
Parameters:
[out] corner_weights Fraction of weights associated with each corner of the patch. Vector must be empty on input.
[in] patch Patch on which workload data is defined.
[in] wrk_indx Patch data identifier for work data.
[in] box Box on which workload is computed
Precondition:
box.getBlockId() == patch->getBox().getBlockId()
box.isSpatiallyEqual(box * patch->getBox())
References computeNonUniformWorkload(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::Box::getDim(), SAMRAI::tbox::Dimension::getValue(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Box::isSpatiallyEqual(), SAMRAI::hier::Box::lower(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::Box::setLower(), SAMRAI::hier::Box::setUpper(), TBOX_ASSERT, TBOX_ERROR, and SAMRAI::hier::Box::upper().
Referenced by SAMRAI::mesh::VoucherTransitLoad::setWorkload(), and SAMRAI::mesh::BoxTransitSet::setWorkload().
void SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance (std::ostream & co, const std::string & border, const hier::MappingConnector & post_to_pre, const hier::IntVector & min_width, size_t min_vol) [static]
Find small boxes in a post-balance BoxLevel that are not in a pre-balance BoxLevel.
Parameters:
co Stream to report findings
border Left border in report output
[in] post_to_pre
[in] min_width Report post-balance boxes smaller than min_width in any direction.
[in] min_vol Report post-balance boxes with fewer cells than this.
References SAMRAI::tbox::SAMRAI_MPI::AllReduce(), SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::format(), SAMRAI::hier::Connector::getBase(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::Connector::getLocalNeighbors(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::hier::Connector::hasNeighborSet(), MPI_SUM, SAMRAI::hier::Box::numberCells(), and SAMRAI::hier::Box::size().
Referenced by findSmallBoxesInPostbalance().
void SAMRAI::mesh::BalanceUtilities::findSmallBoxesInPostbalance (std::ostream & co, const std::string & border, const hier::BoxLevel & pre, const hier::BoxLevel & post, const hier::IntVector & min_width, size_t min_vol) [static]
Find small boxes in a post-balance BoxLevel that are not in a pre-balance BoxLevel.
This method does not scale. It acquires and processes globalized data.
Parameters:
co Stream to report findings
border Left border in report output
[in] pre Pre-balance BoxLevel
[in] post Post-balance BoxLevel
[in] min_width Report post-balance boxes smaller than min_width in any direction.
[in] min_vol Report post-balance boxes with fewer cells than this.
References SAMRAI::hier::OverlapConnectorAlgorithm::findOverlaps(), findSmallBoxesInPostbalance(), SAMRAI::hier::BoxLevel::getDim(), and SAMRAI::hier::IntVector::getZero().
bool SAMRAI::mesh::BalanceUtilities::compareLoads (int flags[], double current_load, double new_load, double ideal_load, double low_load, double high_load, const PartitioningParams & pparams) [static]
Evaluate whether a new load is an improvement over a current load based on their proximity to an ideal value or range of acceptable values.
There is a slight bias toward current load. The new_load is better only if it improves by at least pparams.getLoadComparisonTol().
Return values in flags:
[0]: -1, 0 or 1: degrades, leave-alone or improves in-range
[1]: -1, 0 or 1: degrades, leave-alone or improves balance
[2]: -1, 0 or 1: degrades, leave-alone or improves overall
[3]: 0 or 1: whether new_load is within the range of [low, high]
Return whether new_load is an improvement over current_load.
References SAMRAI::mesh::PartitioningParams::getLoadComparisonTol().
double SAMRAI::mesh::BalanceUtilities::computeLoadBalanceEfficiency (const boost::shared_ptr< hier::PatchLevel > & level, std::ostream & os, int workload_data_id = -1) [static]
Compute and return load balance efficiency for a level.
Returns:
Double-valued estimate of the load balance efficiency (ranges from zero to one hundred percent)
Parameters:
level Input patch level to consider, can't be null.
os Output stream for reporting load balance details.
workload_data_id (Optional) Input integer id for workload data on level. If no value is given, the calculation assumes spatially-uniform load.
Precondition:
level
References BOOST_CAST, SAMRAI::hier::ProcessorMapping::getProcessorAssignment(), SAMRAI::math::PatchCellDataNormOpsReal< TYPE >::L1Norm(), MPI_SUM, NULL_USE, and TBOX_ASSERT.
void SAMRAI::mesh::BalanceUtilities::reduceAndReportLoadBalance (const std::vector< double > & local_loads, const tbox::SAMRAI_MPI & mpi, std::ostream & output_stream = tbox::plog) [static]
Globally reduce a sequence of workloads in an MPI group and write out a summary of load balance efficiency.
Each value in the sequence of workloads represent a certain load the local process had over a sequence of load balancings.
To be used for performance evaluation. Not recommended for general use.
Parameters:
[in] local_loads Sequence of workloads of the local process. The size of local_loads is the number times load balancing has been used. It must be the same across all processors in mpi.
[in] mpi Represents all processes involved in the load balancing.
[in] output_stream
References SAMRAI::tbox::SAMRAI_MPI::AllReduce(), SAMRAI::tbox::SAMRAI_MPI::getSize(), MPI_MAXLOC, MPI_MINLOC, and MPI_SUM.
Referenced by SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel(), SAMRAI::mesh::TreeLoadBalancer::printStatistics(), SAMRAI::mesh::ChopAndPackLoadBalancer::printStatistics(), and SAMRAI::mesh::CascadePartitioner::printStatistics().
void SAMRAI::mesh::BalanceUtilities::constrainMaxBoxSizes (hier::BoxLevel & box_level, hier::Connector * anchor_to_level, const PartitioningParams & pparams) [static]
References SAMRAI::hier::BoxContainer::begin(), SAMRAI::hier::BoxUtilities::chopBoxes(), SAMRAI::hier::BoxContainer::empty(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxContainer::front(), SAMRAI::mesh::PartitioningParams::getBadInterval(), SAMRAI::hier::Box::getBlockId(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::mesh::PartitioningParams::getCutFactor(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::mesh::PartitioningParams::getDomainBoxes(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxLevel::getLastLocalId(), SAMRAI::mesh::PartitioningParams::getMaxBoxSize(), SAMRAI::mesh::PartitioningParams::getMinBoxSize(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Connector::hasTranspose(), SAMRAI::hier::Connector::isFinalized(), SAMRAI::hier::Box::isSpatiallyEqual(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), SAMRAI::hier::Box::numberCells(), SAMRAI::hier::MappingConnectorAlgorithm::setTimerPrefix(), SAMRAI::hier::BoxContainer::size(), SAMRAI::hier::BoxLevel::swap(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel(), and SAMRAI::mesh::CascadePartitioner::loadBalanceBoxLevel().
void SAMRAI::mesh::BalanceUtilities::prebalanceBoxLevel (hier::BoxLevel & balance_box_level, hier::Connector * balance_to_anchor, const tbox::RankGroup & rank_group) [static]
Move Boxes in balance_box_level from ranks outside of rank_group to ranks inside rank_group. Modify the given connectors to make them correct following this moving of boxes.
Precondition:
!balance_to_anchor || balance_to_anchor->hasTranspose()
!balance_to_anchor || (balance_to_anchor->getTranspose().checkTransposeCorrectness(*balance_to_anchor) == 0)
!balance_to_anchor || (balance_to_anchor->checkTransposeCorrectness(balance_to_anchor->getTranspose()) == 0)
References BalanceUtilities_PREBALANCE0, BalanceUtilities_PREBALANCE1, SAMRAI::hier::BoxContainer::begin(), SAMRAI::tbox::AsyncCommPeer< TYPE >::beginRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::beginSend(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkRecv(), SAMRAI::tbox::AsyncCommPeer< TYPE >::checkSend(), SAMRAI::hier::Connector::checkTransposeCorrectness(), SAMRAI::hier::Box::commBufferSize(), SAMRAI::tbox::AsyncCommPeer< TYPE >::completeCurrentOperation(), SAMRAI::hier::BoxContainer::end(), SAMRAI::hier::BoxLevel::getBoxes(), SAMRAI::hier::Box::getBoxId(), SAMRAI::hier::BoxLevel::getDim(), SAMRAI::hier::BoxLevel::getGridGeometry(), SAMRAI::hier::BoxId::getLocalId(), SAMRAI::tbox::RankGroup::getMappedRank(), SAMRAI::hier::BoxLevel::getMPI(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvData(), SAMRAI::tbox::AsyncCommPeer< TYPE >::getRecvSize(), SAMRAI::hier::BoxLevel::getRefinementRatio(), SAMRAI::tbox::SAMRAI_MPI::getSize(), SAMRAI::hier::Connector::getTranspose(), SAMRAI::hier::IntVector::getZero(), SAMRAI::hier::Connector::hasTranspose(), SAMRAI::tbox::AsyncCommPeer< TYPE >::initialize(), SAMRAI::hier::Connector::insertLocalNeighbor(), SAMRAI::tbox::RankGroup::isMember(), SAMRAI::hier::MappingConnectorAlgorithm::modify(), SAMRAI::hier::Box::putToIntBuffer(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPI(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setMPITag(), SAMRAI::tbox::AsyncCommPeer< TYPE >::setPeerRank(), SAMRAI::hier::MappingConnectorAlgorithm::setTimerPrefix(), SAMRAI::hier::Connector::setTranspose(), SAMRAI::hier::BoxContainer::size(), SAMRAI::tbox::RankGroup::size(), SAMRAI::hier::BoxLevel::swap(), and TBOX_ASSERT.
Referenced by SAMRAI::mesh::TreeLoadBalancer::loadBalanceBoxLevel().
Member Data Documentation
const int SAMRAI::mesh::BalanceUtilities::BalanceUtilities_PREBALANCE0 = 5 [static]
Referenced by prebalanceBoxLevel().
const int SAMRAI::mesh::BalanceUtilities::BalanceUtilities_PREBALANCE1 = 6 [static]
Referenced by prebalanceBoxLevel().
The documentation for this struct was generated from the following files:
source/SAMRAI/mesh/BalanceUtilities.h
source/SAMRAI/mesh/BalanceUtilities.C