SAMRAI: SAMRAI::tbox::Utilities Struct Reference
SAMRAI::tbox::Utilities Struct Reference
#include <source/SAMRAI/tbox/Utilities.h>
Static Public Member Functions
static void recursiveMkdir (const std::string &path, mode_t mode=(S_IRUSR|S_IWUSR|S_IXUSR), bool only_node_zero_creates=true)
static void renameFile (const std::string &old_filename, const std::string &new_filename)
static std::string intToString (int num, int min_width=1)
static std::string sizetToString (size_t num, int min_width=1)
static std::string nodeToString (int num)
static std::string processorToString (int num)
static std::string patchToString (int num)
static std::string levelToString (int num)
static std::string blockToString (int num)
static void abort (const std::string &message, const std::string &filename, const int line)
Detailed Description
Utilities is a Singleton class containing basic routines for error reporting, file manipulations, etc.
Member Function Documentation
void SAMRAI::tbox::Utilities::recursiveMkdir (const std::string & path, mode_t mode = (S_IRUSR | S_IWUSR | S_IXUSR), bool only_node_zero_creates = true) [static]
Create the directory specified by the path string. Permissions are set by default to rwx by user. The intermediate directories in the path are created if they do not already exist. When only_node_zero_creates is true, only node zero creates the directories. Otherwise, all nodes create the directories.
References SAMRAI::tbox::SAMRAI_MPI::Barrier(), SAMRAI::tbox::SAMRAI_MPI::getRank(), SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld(), and TBOX_ERROR.
Referenced by SAMRAI::tbox::Statistician::printSpreadSheetOutput(), and SAMRAI::tbox::Statistician::printSpreadSheetOutputForProcessor().
static void SAMRAI::tbox::Utilities::renameFile (const std::string & old_filename, const std::string & new_filename) [inline, static]
Rename a file from old file name to new file name.
Precondition:
!old_filename.empty()
!new_filename.empty()
References TBOX_ASSERT.
std::string SAMRAI::tbox::Utilities::intToString (int num, int min_width = 1) [static]
Convert an integer to a string.
The returned string is padded with zeros as needed so that it contains at least the number of characters indicated by the minimum width argument. When the number is positive, the string is padded on the left. When the number is negative, the '-' sign appears first, followed by the integer value padded on the left with zeros. For example, the statement intToString(12, 5) returns "00012" and the statement intToString(-12, 5) returns "-0012".
Referenced by blockToString(), SAMRAI::pdat::SideData< TYPE >::getFromRestart(), SAMRAI::pdat::OutersideData< TYPE >::getFromRestart(), SAMRAI::pdat::OuternodeData< TYPE >::getFromRestart(), SAMRAI::pdat::OuterfaceData< TYPE >::getFromRestart(), SAMRAI::pdat::OuteredgeData< TYPE >::getFromRestart(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::getFromRestart(), SAMRAI::pdat::FaceData< TYPE >::getFromRestart(), SAMRAI::pdat::EdgeData< TYPE >::getFromRestart(), SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::tbox::Database::getObjectVector(), SAMRAI::mesh::GriddingAlgorithm::GriddingAlgorithm(), levelToString(), nodeToString(), SAMRAI::tbox::RestartManager::openRestartFile(), patchToString(), SAMRAI::solv::CVODESolver::printCVSpgmrStatistics(), processorToString(), SAMRAI::tbox::Database::putObjectVector(), SAMRAI::pdat::SideData< TYPE >::putToRestart(), SAMRAI::pdat::OutersideData< TYPE >::putToRestart(), SAMRAI::pdat::OuternodeData< TYPE >::putToRestart(), SAMRAI::pdat::OuterfaceData< TYPE >::putToRestart(), SAMRAI::pdat::OuteredgeData< TYPE >::putToRestart(), SAMRAI::pdat::IndexData< TYPE, BOX_GEOMETRY >::putToRestart(), SAMRAI::pdat::FaceData< TYPE >::putToRestart(), SAMRAI::pdat::EdgeData< TYPE >::putToRestart(), SAMRAI::hier::PatchHierarchy::putToRestart(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), SAMRAI::hier::BoxLevel::putToRestart(), SAMRAI::hier::BaseGridGeometry::putToRestart(), SAMRAI::hier::BaseGridGeometry::readBlockDataFromInput(), SAMRAI::hier::VariableDatabase::registerClonedPatchDataIndex(), and SAMRAI::algs::PatchBoundaryEdgeSum::registerSum().
std::string SAMRAI::tbox::Utilities::sizetToString (size_t num, int min_width = 1) [static]
Convert a size_t to a string.
The returned string is padded with zeros as needed so that it contains at least the number of characters indicated by the minimum width argument. When the number is positive, the string is padded on the left. When the number is negative, the '-' sign appears first, followed by the integer value padded on the left with zeros. For example, the statement intToString(12, 5) returns "00012" and the statement intToString(-12, 5) returns "-0012".
Referenced by SAMRAI::tbox::SiloDatabase::putStringArray().
static std::string SAMRAI::tbox::Utilities::nodeToString (int num) [inline, static]
Convert common integer values to strings.
These are simply wrappers around intToString that ensure the same width is uniformally used when converting to string representations.
References intToString().
Referenced by SAMRAI::tbox::RestartManager::openRestartFile().
static std::string SAMRAI::tbox::Utilities::processorToString (int num) [inline, static]
References intToString().
Referenced by SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::tbox::PIO::initialize(), SAMRAI::tbox::PIO::logAllNodes(), SAMRAI::tbox::RestartManager::openRestartFile(), SAMRAI::tbox::Statistician::printSpreadSheetOutputForProcessor(), SAMRAI::hier::BoxNeighborhoodCollection::putToRestart(), and SAMRAI::tbox::RestartManager::writeRestartFile().
static std::string SAMRAI::tbox::Utilities::patchToString (int num) [inline, static]
References intToString().
Referenced by SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::BoxNeighborhoodCollection::getFromRestart(), SAMRAI::hier::PatchLevel::putToRestart(), and SAMRAI::hier::BoxNeighborhoodCollection::putToRestart().
static std::string SAMRAI::tbox::Utilities::levelToString (int num) [inline, static]
References intToString().
Referenced by SAMRAI::hier::PatchLevel::getFromRestart(), SAMRAI::hier::PatchHierarchy::initializeHierarchy(), SAMRAI::hier::PatchHierarchy::logMetadataStatistics(), SAMRAI::hier::PatchLevel::putToRestart(), and SAMRAI::hier::PatchHierarchy::putToRestart().
static std::string SAMRAI::tbox::Utilities::blockToString (int num) [inline, static]
References intToString().
Referenced by SAMRAI::hier::PatchLevel::getFromRestart(), and SAMRAI::hier::PatchLevel::putToRestart().
void SAMRAI::tbox::Utilities::abort (const std::string & message, const std::string & filename, const int line) [static]
Aborts the run after printing an error message with file and linenumber information.
References SAMRAI::tbox::Logger::getInstance(), and SAMRAI::tbox::Logger::logAbort().
The documentation for this struct was generated from the following files:
source/SAMRAI/tbox/Utilities.h
source/SAMRAI/tbox/Utilities.C