//
// File:	ImplicitEquationStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "ImplicitEquationStrategy.h"
#include "ImplicitEquationStrategy.C"

namespace SAMRAI {
   namespace algs {
template class ImplicitEquationStrategy< NDIM >;
}
}
