//
// File:	pdat__IndexData-NDIM_appu__CutCell_NDIM_X.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "IndexData.h"
#include "IndexData.C"
#include "CutCell.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::IndexData< NDIM,appu::CutCell<NDIM> >;
}
}
