//
// File:	CartesianOuterfaceComplexWeightedAverage-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianOuterfaceComplexWeightedAverage.h"
#include "CartesianOuterfaceComplexWeightedAverage.C"

namespace SAMRAI {
   namespace geom {
template class CartesianOuterfaceComplexWeightedAverage< NDIM >;
}
}
