//
// File:	CartesianSideDoubleConservativeLinearRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianSideDoubleConservativeLinearRefine.h"
#include "CartesianSideDoubleConservativeLinearRefine.C"

namespace SAMRAI {
   namespace geom {
template class CartesianSideDoubleConservativeLinearRefine< NDIM >;
}
}
