#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/trunk/source/scripts/source_manipulation/replaceIncludeGuards $
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2010 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1917 $
## Modified:    $LastChangedDate: 2008-01-25 13:28:01 -0800 (Fri, 25 Jan 2008) $
## Description: shell script to insert package name in #includes
##

SARMAI_BIN=`dirname $0`

perl $SARMAI_BIN/removeTemplateOnDim.pl $SARMAI_BIN

exit
