#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-2-0/source/scripts/source_manipulation/findHeaderFiles $
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2007 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: Find all header files
##

BIN=`dirname $0`
cd `dirname $0`/../../../source || exit 1;
echo `pwd`
test -d "hierarchy/patches" || exit 1

perl scripts/source_manipulation/findHeaderFiles.pl > scripts/source_manipulation/headers.data

exit
