#!/bin/sh
##
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2005 The Regents of the University of California
## Revision:    $Revision$
## Modified:    $Date$
## Description: Find all header files
##

BIN=`dirname $0`
cd `dirname $0`/../../../source || exit 1;
echo `pwd`
test -d "hierarchy/patches" || exit 1

perl scripts/source_manipulation/findHeaderFiles.pl > scripts/source_manipulation/headers.data

exit
