#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-2-0/source/scripts/source_manipulation/replaceIncludeGuards $
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2007 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: shell script to convert 1.x codes to 2.0
##

BIN=`dirname $0`

$BIN/findHeaderFiles

perl $BIN/replaceIncludeGuards.pl 

exit
