//
// File:	FaceComplexConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceComplexConstantRefine.h"
#include "FaceComplexConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class FaceComplexConstantRefine< NDIM >;
}
}
