//
// File:	NodeFloatInjection-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "NodeFloatInjection.h"
#include "NodeFloatInjection.C"

namespace SAMRAI {
   namespace pdat {
template class NodeFloatInjection< NDIM >;
}
}
