//
// File:	NodeComplexInjection-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "NodeComplexInjection.h"
#include "NodeComplexInjection.C"

namespace SAMRAI {
   namespace pdat {
template class NodeComplexInjection< NDIM >;
}
}
