#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-2-0/source/scripts/copy-if-change $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2007 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: copy files if there is a change (ignoring CVS comments)
##

PERL=${PERL:-perl}

#
# Check usage - must have at least two arguments
#

BIN=`dirname $0`
if [ $# -le 1 ] ; then
	echo "usage: copy-if-change <destination directory> <file1> ..."
	exit 1
fi

#
# Get destination directory - check to make sure directory exists
#

DIR=$1 ; shift
if [ ! -d $DIR ] ; then
	echo "usage: copy-if-change <destination directory> <file1> ..."
	exit 1
fi

#
# Copy SRC to DST if the two files are not the same
#

for FILE in $*; do
	SRC=$FILE
	DST=$DIR/`basename $FILE`
	echo "Checking "$SRC
	if [ -r $DST ] ; then
		if $PERL $BIN/cmp.pl $SRC $DST ; then
			foo=foo # do nothing
		else
			echo "   updating "$DST
			cp -f $SRC $DST
		fi
	else
		echo "   creating "$DST
		cp $SRC $DST
	fi
done

exit 0
