#!/bin/sh
##
## File:        copy-if-change
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2005 The Regents of the University of California
## Revision:    $Revision$
## Modified:    $Date$
## Description: copy files if there is a change (ignoring CVS comments)
##

PERL=${PERL:-perl}

#
# Check usage - must have at least two arguments
#

BIN=`dirname $0`
if [ $# -le 1 ] ; then
	echo "usage: copy-if-change <destination directory> <file1> ..."
	exit 1
fi

#
# Get destination directory - check to make sure directory exists
#

DIR=$1 ; shift
if [ ! -d $DIR ] ; then
	echo "usage: copy-if-change <destination directory> <file1> ..."
	exit 1
fi

#
# Copy SRC to DST if the two files are not the same
#

for FILE in $*; do
	SRC=$FILE
	DST=$DIR/`basename $FILE`
	echo "Checking "$SRC
	if [ -r $DST ] ; then
		if $PERL $BIN/cmp.pl $SRC $DST ; then
			foo=foo # do nothing
		else
			echo "   updating "$DST
			cp -f $SRC $DST
		fi
	else
		echo "   creating "$DST
		cp $SRC $DST
	fi
done

exit 0
