#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-2-0/source/scripts/depend $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2007 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: shell script to generate dependencies for SAMRAI files
##

##
## Generate dependency information for all files in the current directory
## and subdirectories.
##

BIN=`dirname $0`
bindir=`cd $BIN && pwd`
INC=$BIN/../../include

PERL=${PERL:-perl}
COMP="$PERL $BIN/cmp.pl"

DIRS=`find . -type d -print | grep -v '\(to_be_implemented\|include\|noprefix\|CVS\|\.svn\)'`
for DIR in $DIRS ; do

   #
   # Generate a dependency file in the subdirectory if *.C files exist
   #

   echo "Checking dependencies in directory "$DIR
   FILES=`(cd $DIR; echo *.[fCc])`
   if [ "*.[fCc]" != "$FILES" ] ; then
      (cd $DIR && perl $bindir/depend.pl . '-' $FILES)

      #
      # If Makefile.depend does not exist, then create it
      #

      if [ ! -r $DIR/Makefile.depend ] ; then
         echo "   creating "$DIR/Makefile.depend
         mv -f $DIR/Makefile.depend.tmp $DIR/Makefile.depend

      #
      # Otherwise, copy if the two files are not the same.  Remove the CVS
      # portions of the header to ignore changes in date/revision/modified.
      #

      else
         if $COMP $DIR/Makefile.depend.tmp $DIR/Makefile.depend ; then
            rm -f $DIR/Makefile.depend.tmp
         else
            echo "   updating "$DIR/Makefile.depend
            mv -f $DIR/Makefile.depend.tmp $DIR/Makefile.depend
         fi
      fi
   fi
done

exit 0
