#! /bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-2-0/source/scripts/run-after-update $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2007 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: shell script for misc tasks after updating from repository.
##

# This script may be run after updating from svn to make bring
# the working directory from the svn state to a functional state.
# Nothing mysterious is done.  You can do everything by hand if you
# choose.

# Go to the top level SAMRAI directory and make sure we get there.
cd `dirname $0`/../.. || exit 1;
test -d "source/hierarchy/patches" || exit 1
pwd

# Make sure we have acmacros, which is needed for regenerating
# config/aclocal.m4, which is needed for regenerating configure.
#if test ! -d acmacros ; then
#  test "$CVSROOT_BTNG" || CVSROOT_BTNG=/usr/casc/samrai/gunney/cvsrepository
#  echo "No acmacros directory.  Using current version in $CVSROOT_BTNG"
#  cvs -d $CVSROOT_BTNG export -D now acmacros
#fi

# Update the includes directory.
echo "Running the includes script"
perl source/scripts/includes "$@"
