#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-2-0/source/scripts/update_configure $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2007 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: shell script to regenerate configure.
##

# Go to the top level SAMRAI directory and make sure we get there.
cd `dirname $0`/../.. || exit 1;
test -d "source/hierarchy/patches" || exit 1

echo "Checking out acmacros"
cvs -d /usr/casc/samrai/gunney/cvsrepository checkout -rv_0_3 acmacros

echo "Running aclocal"
aclocal -I config -I acmacros --output=config/aclocal.m4

echo "Running autoconf"
autoconf -I config
