//
// File:        $URL$
// Package:     SAMRAI algorithms
// Copyright:   (c) 1997-2000 Lawrence Livermore National Security, LLC
// Revision:    $LastChangedRevision$
// Modified:    $LastChangedDate$
// Description: Routines for summing edge data at patch boundaries.
//

namespace SAMRAI {
namespace algs {

SAMRAI_INLINE_KEYWORD
const std::string& PatchBoundaryEdgeSum::getObjectName() const
{
   return d_object_name;
}

}
}
