#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-2-0/tools/scripts/conversion2.0/rename_tbox $
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2007 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: shell script to run rename X class names to template on <DIM>
##

BIN=`dirname $0`

perl $BIN/rename_tbox.pl tbox_classes

exit

