#!/bin/sh
##
## File:        update
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2005 The Regents of the University of California
## Revision:    $Revision$
## Modified:    $Date$
## Description: shell script to run rename X class names to template on <DIM>
##

BIN=`dirname $0`

perl $BIN/rename_tbox.pl tbox_classes

exit

