//
// File:	HierarchyFaceDataOpsInteger-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyFaceDataOpsInteger.h"
#include "HierarchyFaceDataOpsInteger.C"

namespace SAMRAI {
   namespace math {
template class HierarchyFaceDataOpsInteger< NDIM >;
}
}
