//
// File:	LocallyActiveDataCoarsenAlgorithm-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2007 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocallyActiveDataCoarsenAlgorithm.h"
#include "LocallyActiveDataCoarsenAlgorithm.C"

namespace SAMRAI {
   namespace xfer {
template class LocallyActiveDataCoarsenAlgorithm< NDIM >;
}
}
